### ISSUE TITLE
TypeError: this.connection.getKnex is not a function ==> MongoDB

### ISSUE THREAD

**Issue by RajanKrishnan** [mikro-orm/mikro-orm#1002]
**Describe the bug**
migration error 

**Stack trace**

TypeError: this.connection.getKnex is not a function
    at new SchemaGenerator (C:\temp\lireddit\node_modules\@mikro-orm\knex\schema\SchemaGenerator.js:15:37)
    at new Migrator (C:\temp\lireddit\node_modules\@mikro-orm\migrations\Migrator.js:34:32)
    at Function.handleMigrationCommand (C:\temp\lireddit\node_modules\@mikro-orm\cli\commands\MigrationCommandFactory.js:71:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**To Reproduce**
npx mikro-orm migration:create

**Expected behavior**
Migratoin to complete with out errors

**Additional context**
None

**Versions**
npx mikro-orm debug //output is pasted below
Current MikroORM CLI configuration
 - dependencies:
   - mikro-orm 4.2.3
   - node 12.18.3
DirName C:\temp\lireddit\src
   - mongodb 3.6.2
   - typescript 4.0.5
 - package.json found
 - ts-node enabled
 - searched config paths:
   - C:/temp/lireddit/src/mikro-orm.config.ts (found)
   - C:/temp/lireddit/dist/mikro-orm.config.js (found)
   - C:/temp/lireddit/mikro-orm.config.ts (not found)
   - C:/temp/lireddit/mikro-orm.config.js (not found)
 - configuration found
 - will use `entities` array (contains 1 references and 0 paths)

**Comment by B4nan** [comment]
Migrations are not supported in mongo. You do not need to synchronize schema there (as there is no schema in mongo), so it is not usually needed, but it is planned for manual migrations (scripts) and indexes, you can subscribe to #295 if you are interested in that.

**Comment by RajanKrishnan** [comment]
Thought so .. Just want to get confirmation as well.. Thank you close the issue
