### ISSUE TITLE
Add collate option to go with charset

### ISSUE THREAD

**Issue by techmunk** [mikro-orm/mikro-orm#1012]
**Is your feature request related to a problem? Please describe.**
Would like the ability to specify the collation alongside the charset. Especially for Mysql.

**Describe the solution you'd like**
A new collate option that sets the default collation used.

**Describe alternatives you've considered**
I've though about manually adjusting the generated migration files, which mostly solves this issue for my use case. Be nice not to need that manual step.

**Additional context**
Umzug already supports the collate option, so that's a bonus.

**Comment by techmunk** [comment]
I was mostly asking for a global config. I currently do not have a use case that would need this setting per entity, though I could possibly see how it might be useful in some circumstances. If this is easier to implement in the `@Entity` decorator I'd be OK with that as well.

**Comment by B4nan** [comment]
Currently charset is set globally, are you asking for a global config or something in the `@Entity` decorator?
