### ISSUE TITLE
Assigning type DateType causing 00:00:00 in datetime value

### ISSUE THREAD

**Issue by lewispham** [mikro-orm/mikro-orm#1013]
**Describe the bug**
I tried to assign `new Date()` to a field with `type: DateType` and unfortunately the hh:mm:ss is always `00:00:00`. Removing `type: DateType` fixes the issue.

**Stack trace**
No stack trace
**To Reproduce**
1. Define an entity Token with a field of DateType
```
@Entity()
class Token {
    @Property({type: DateType})
    revokedAt: Date | null;
}
```
2. Assign `new Date()` to that field then save into db.
```
const token = new Token();
token.revokedAt = new Date();
await orm.em.persistAndFlush(token);
```
3. Check the related value saved into db
```
// token.revokedAt
2020-11-08 00:00:00
```

**Expected behavior**
Datetime value 

**Additional context**

**Versions**
4.2.3
| Dependency | Version |
| - | - |
| node | 14.10.0 |
| typescript | 4.0.2 | 4.0.2
| mikro-orm | 4.2.3 | 4.2.3
| your-driver | mariadb |

**Comment by B4nan** [comment]
`DateType` is for dates (when you want to work with a `Date` object, but use `date` column type in the database) - time is truncated at the database level. It is not a "datetime", but only a "date".
