### ISSUE TITLE
Explicit timestamptz converted to jsonb on migration

### ISSUE THREAD

**Issue by AzSiAz** [mikro-orm/mikro-orm#1023]
**Describe the bug**
Setting:
```
@Property({ type: 'timestamptz', defaultRaw: 'CURRENT_TIMESTAMP' })
date: Date = new Date()
``` 
Seem to set column migration on pg to:
 `"date" jsonb not null default CURRENT_TIMESTAMP` 

**Expected behavior**
Migration should use a correct timestamptz type on migration

**Versions**

| Dependency | Version |
| - | - |
| node | 14.15.0 |
| typescript | 4.0.5 |
| mikro-orm | 4.2.3 |
| @mikro-orm/postgresql | 4.2.3 |

**Comment by B4nan** [comment]
You should use `columnType` instead of `type` when providing the actual database type. (I guess you already found out :])

**Comment by AzSiAz** [comment]
Yep, this was exactly my problem :sweat_smile: 

This [exemple](https://mikro-orm.io/docs/defining-entities#entityschema-helper) is mileading for class entity, I think it's said too low on the doc [here](https://mikro-orm.io/docs/defining-entities#lazy-scalar-properties), but it should be around [here](https://mikro-orm.io/docs/defining-entities#classes-and-decorators) instead :smile: 

Thanks and sorry for the unnecessary noise :smile:
