### ISSUE TITLE
returning "field_name" - integer out of range

### ISSUE THREAD

**Issue by TicTak21** [mikro-orm/mikro-orm#1024]
**Describe the bug**
`returning "_id" - integer out of range` error after trying to add value to db using `persistAndFlush`

**Stack trace**
```
insert into "movie" ("_id", "adult", "country", "created_at", "description", "rating", "released_at", "title", "updated_at", "views") values ('j9p9ZpYUYQ', true, 'YE', 1604330998128, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 4.4, 1604330998128, 'Ghost Rider', 1604330998128, 3504) returning "_id" - integer out of range
```

**To Reproduce**
1. Create application using Nest.js with orm
2. Create Entity with `id` field as PrimaryKey
3. Try to add value to db using `persistAndFlush`

**Expected behavior**
The value(data) is added without error

**Additional context**
I tried to use the default value and different data types for the `_id` field, but the result is the same.

Movie entity:
```
export class Movie {
  @PrimaryKey()
  _id: number;
  
  // ....
}
```

MovieService:
```
@Injectable()
export class MovieService {
  constructor(
    @InjectRepository(Movie)
    private readonly movieRepository: EntityRepository<Movie>,
    private readonly em: EntityManager,
  ) {}

  async add(movie: Movie) {
    const movieEntity = this.em.create(Movie, movie);
    await this.movieRepository.persistAndFlush(movieEntity);
}
```

Config:
```
const config: Options = {
  migrations: {
    path: './src/database/migrations',
    pattern: /^[\w-]+\d+\.[tj]s$/,
  },
  entities: [Movie],
  entitiesTs: ['src/entities'],
  dbName: '....',
  type: 'postgresql',
  port: ....,
  debug: !__prod__,
  logger: logger.log.bind(logger),
};
```

**Versions**

| Dependency | Version |
| - | - |
| node | 14.12.0 |
| typescript | 3.9.7 |
| mikro-orm | 4.2.3 |

**Comment by B4nan** [comment]
This is not caused by MikroORM, its error thrown by postgres, because you are trying to store a number that is larger than maximum allowed one. And it has nothing to do with the `returing` clause, that is just end of the query that caused it, the error is just "integer out of range".

I would expect the numeric timestamps to be issue, `1604330998128` definitely won't fit into integer.
