### ISSUE TITLE
Annotating a `ManyToOne` relationship with `{nullable:false}` seems to not actually mark the column as `NOT NULL` in the database schema.

### ISSUE THREAD

**Issue by jjhbw** [mikro-orm/mikro-orm#1028]
First of all, thanks for this brilliant lib! Really takes the edge off of working with large nested entities.

**Describe the bug**
Annotating a `ManyToOne` relationship with `{nullable:false}` seems to not actually mark the column as `NOT NULL` in the database schema.

I get the following debug output. I have indicated where I expect the ORM to mark the column as `NOT NULL`.
```
[discovery] ORM entity discovery started, using ReflectMetadataProvider
[discovery] - processing entity Author
[discovery] - processing entity Book
[discovery] - entity discovery finished, found 2 entities, took 10 ms
[info] MikroORM successfully connected to database :memory:
[query] select name as table_name from sqlite_master where type = 'table' and name != 'sqlite_sequence' and name != 'geometry_columns' and name != 'spatial_ref_sys' union all select name as table_name from sqlite_temp_master where type = 'table' order by name [took 1 ms]
[query] pragma foreign_keys = off; [took 0 ms]
[query] create table `author` (`id` integer not null primary key autoincrement, `name` varchar not null); [took 0 ms]
[query] create table `book` (`id` integer not null primary key autoincrement, `name` varchar not null); [took 1 ms]
---> [query] alter table `book` add column `author_id` integer null; [took 0 ms]
[query] create index `book_author_id_index` on `book` (`author_id`); [took 1 ms]
[query] pragma foreign_keys = on; [took 0 ms]
```

**To Reproduce**
Run the below and note MikroORM's debug output.
```typescript
import { Entity, ManyToOne, MikroORM, PrimaryKey, Property } from "@mikro-orm/core"

@Entity()
class Author {
    @PrimaryKey()
    id!: number

    @Property({ type: 'varchar' })
    name!: string
}

@Entity()
class Book {
    @PrimaryKey()
    id!: number

    @Property({ type: 'varchar' })
    name!: string

    @ManyToOne(() => Author, { nullable: false, eager: true })
    author!: Author
}

const test = async () => {
    const connection = await MikroORM.init({
        entities: [
            Author,
            Book
        ],
        dbName: ':memory:',
        type: 'sqlite',
        debug: true,
        discovery: {
            disableDynamicFileAccess: true,
            requireEntitiesArray: true,
            alwaysAnalyseProperties: true,
            warnWhenNoEntities: true
        }
    })

    const generator = connection.getSchemaGenerator()
    await generator.updateSchema()
}

test().catch(console.log)
```

**Expected behavior**
I expect the ORM to make the ManyToOne relationship non-nullable on the database level.

**Versions**

| Dependency | Version |
| - | - |
| node | v14.1.0 |
| typescript | 4.0.5 |
| mikro-orm | 4.2.3 |
| mikro-orm/sqlite | 4.2.3|
| sqlite3 | 5.0.0 |

**Comment by B4nan** [comment]
Sqlite does not support adding not null columns via alter statements.

**Comment by jjhbw** [comment]
@B4nan thanks for your reply. Ah yes that makes perfect sense! 

So i take it that mikroORM also doesnt support setting not null in the CREATE TABLE statements?

**Comment by B4nan** [comment]
It is supported for create table statements, but FKs are always added via alter statements currently (unless it is a PK), to support circular references. I am planning to rework this a bit as there were some issues with ongoing mssql support so want to do it this way only when actually needed (when we know there is a cycle in the graph).

**Comment by jjhbw** [comment]
Great! Thanks for clearing that up. I can work without them just fine. It's just good to know that it is working as intended currently. Thanks again for this great lib!
