### ISSUE TITLE
Unique index with condition

### ISSUE THREAD

**Issue by sptGabriel** [mikro-orm/mikro-orm#1029]
Hello I didn't find anything in the documentation, I would like to know if it is possible to create a unique index with condition?

Something like this on the knex:
```
this.getKnex().raw(
              "create unique index employeePosition on employees(position, departament_id) where position <> 'tecnico'",
            ),
```

Entity:
```

export const enum Positions {
  TECNICO,
  GERENTE,
  DIRETOR,
}
@Entity({ tableName: 'employees' })
@Unique({ properties: ['position', 'departament_id'] })
export class Employee {
  @PrimaryKey()
  public readonly id: string;
  @Property()
  public matricula: string;
  @Property()
  public first_name: string;
  @Property()
  public last_name: string;
  @Property()
  public departament_id: string;
  @Enum()
  public position: Positions;
  @Property()
  public createdAt = new Date();
  @Property({ onUpdate: () => new Date() })
  public updatedAt = new Date();
  @Property()
  public deletedAt?: Date;
  
}
```

I would like to know if there is any possibility of putting any conditions in my unique index?

**Comment by B4nan** [comment]
Not really, apparently another feature that was PR'd to knex years ago but... Not merged, as always :/ This one even supports all possible drivers and have proper tests 🤷 

https://github.com/knex/knex/pull/2401

**Comment by sptGabriel** [comment]
so sad :/ 
@B4nan thank u 

Could you ask me one more question?
Is it possible to make this query with mikro orm, without the need to use querybuilder?

code:

```
 const rowProducts = await this.db
      .select('*')
      .from<Product>(this.tableName)
      .whereIn('id', [id])
      .then(row => {
        return row.map(product => {
          return Product.toDomain(product);
        });
      });
```

**Comment by B4nan** [comment]
Why would you need a QB there? Its literally just a look up by PK, right?

**Comment by sptGabriel** [comment]
> Why would you need a QB there? Its literally just a look up by PK, right?

I want to do without it,
something like repository.find (wherein: ids)

  **public byArray = async (ids: string[]): Promise<Product[] | undefined>  => {
    return await this.repository.find({$in:})
  }**

**Comment by B4nan** [comment]
Yes, and I asked why do you think you need QB for that :] `repo.find([1, 2, 3])` works just fine, as well as `repo.find({ id: [1, 2, 3] })` or`repo.find({ id: { $id: [1, 2, 3] } })`.

**Comment by ryall** [comment]
Looks like conditional indexes might finally be available in Knex since Oct:
https://github.com/knex/knex/pull/4768

**Comment by johanneslumpe** [comment]
@B4nan Just now running into this exact issue, requiring partial indexes. Since knex now supports partial unique indexes by adding a `where` condition, do you think it's worth revisiting this and adding first class support for partial indexes in mikro?

**Comment by B4nan** [comment]
You can use index expressions nowadays:

```ts
@Index({ name: 'custom_index_expr', expression: 'alter table `author` add index `custom_index_expr`(`title`)' })
@Property()
title!: string;
```

https://mikro-orm.io/docs/defining-entities#indexes

**Comment by johanneslumpe** [comment]
@B4nan thanks for the follow up - that’s exactly what I ended up doing :)
