### ISSUE TITLE
Should add an explicit example of Enum defined in another file, with nullable: true

### ISSUE THREAD

**Issue by pacome35220** [mikro-orm/mikro-orm#1034]
**Is your feature request related to a problem? Please describe.**
I had trouble generating a migration with the correct SQL for a `nullable: true` string enum.

**Describe the solution you'd like**
I suggest adding this 4th example in User class
https://mikro-orm.io/docs/defining-entities/#enums :

```ts
@Enum({ items: () => OutsideNullableEnum, nullable: true })
outsideNullable?: OutsideNullableEnum; // string enum defined outside of this file, may be null
```

**Comment by B4nan** [comment]
Sure, would you be up to send a PR for that?

**Comment by pacome35220** [comment]
Yes I will do it if i find the file
