### ISSUE TITLE
Lifecycle hooks not run if defined on base entity

### ISSUE THREAD

**Issue by joshstrange** [mikro-orm/mikro-orm#104]
I was trying to setup my base entity to have `@BeforeCreate` and `@BeforeUpdate` hooks on it to handle setting some common fields (id, created, createdBy, updated, updatedBy, etc) but they seem to be ignored. They work fine if I put them on one of my my main entities, just not on the base one I extend from.

Is this possible or is there a better way to define this functionality once and reuse it?

**Comment by B4nan** [comment]
I guess they are ignored, but not intentionally. Will fix this next week, I am out on vacation with very limited internet access. 

Or feel free to send a PR, the problem will be in MetadataDiscovery class, in the method that defines base entity properties.

**Comment by B4nan** [comment]
Fix released as v2.7.7
