### ISSUE TITLE
nested insert on many to many relation

### ISSUE THREAD

**Issue by sptGabriel** [mikro-orm/mikro-orm#1044]
Hello I have a n: n relationship with products, supply generating the supplied_products table

my entities:

Products:

```
@Entity({ tableName: 'products' })
export class Product {
  @PrimaryKey()
  public readonly id: string;
  @Property()
  public name: string;
  @Property()
  public codReference: string;
  @Property()
  public category_id: string;
  @Property()
  public createdAt = new Date();
  @Property({ onUpdate: () => new Date() })
  public updatedAt = new Date();
  @Property()
  public deletedAt?: Date;
  constructor(
    props: Omit<Product, 'id' | 'updatedAt' | 'createdAt'>,
    id?: string,
  ) {
    Object.assign(this, props);
    if (!id) this.id = v4();
  }
  static build = (
    props: Omit<Product, 'id' | 'updatedAt' | 'createdAt'>,
    id?: string,
  ): Product => {
    const isValidUUID = id ? validate(id) : null;
    if (isValidUUID === false) throw new Error(`Invalid UUID V4`);
    return new Product(props, id);
  };
}
```

supply:

```
@Entity({ tableName: 'supplies' })
export class Supplying {
  @PrimaryKey()
  public readonly id: string;
  @Property()
  public supplier_id: string;
  @Property()
  public arrived: boolean;
  @Property()
  public ordered_at: Date;
  @Property()
  public arrives_at: Date;
  @Property()
  public created_at = new Date();
  @Property({ onUpdate: () => new Date() })
  public updated_at = new Date();
  @Property()
  public deleted_at?: Date;
  @OneToMany(
    () => SuppliedProducts,
    suppliedProducts => suppliedProducts.supply,
    { cascade: [Cascade.PERSIST] },
  )
  public suppliedProducts = new Collection<SuppliedProducts>(this);
  constructor(
    props: Omit<
      Supplying,
      'id' | 'updated_at' | 'created_at' | 'suppliedProducts'
    >,
    id?: string,
  ) {
    Object.assign(this, props);
    if (!id) this.id = v4();
  }
  static build = (
    props: Omit<
      Supplying,
      'id' | 'updated_at' | 'created_at' | 'suppliedProducts'
    >,
    id?: string,
  ): Supplying => {
    const isValidUUID = id ? validate(id) : null;
    if (isValidUUID === false) throw new Error(`Invalid UUID V4`);
    return new Supplying(props, id);
  };
}
```

and supplied_products:

```
@Entity({ tableName: 'supplied_products' })
export class SuppliedProducts {
  @Property()
  public product_id: string;
  @Property()
  public supply_id: string;
  @Property()
  public quantity: number;
  @ManyToOne({ entity: () => Product, primary: true, joinColumn: 'product_id' })
  public product: Product;
  @ManyToOne({
    entity: () => Supplying,
    primary: true,
    joinColumn: 'supply_id',
  })
  public supply: Supplying;
  @Property()
  public createdAt = new Date();
  @Property({ onUpdate: () => new Date() })
  public updatedAt = new Date();
  @Property()
  public deletedAt?: Date;
  [PrimaryKeyType]: [number, number];
  constructor(product_id: string, supply_id: string, quantity: number) {
    this.product_id = product_id;
    this.supply_id = supply_id;
    this.quantity = quantity
  }
  static build = (
    product_id: string,
    supply_id: string,
    quantity: number,
  ): SuppliedProducts => {
    if (!validate(product_id)) throw new Error(`${product_id} Invalid UUID V4`);
    if (!validate(supply_id)) throw new Error(`${supply_id} Invalid UUID V4`);
    return new SuppliedProducts(product_id, supply_id, quantity);
  };
}
```

i have make this to create collection:

 ```
 const supply = Supplying.build(request.supply);
    supply.suppliedProducts.set(
      request.suppliedProducts.map(supplied => {
        return SuppliedProducts.build(
          supplied.product_id,
          supply.id,
          supplied.quantity,
        );
      }),
    );
```

and I created everything normally, but for some reason I have two sql errors:

`riverException: insert into "supplied_products" ("supply_id", "product_id", "supply_id", "quantity", "created_at", "updated_at") values ('ac719ff6-eaa5-4e2b-a344-6e62472e5591', '83c16f3c-f091-496f-b300-61023e106dde', 'ac719ff6-eaa5-4e2b-a344-6e62472e5591', 10, '2020-11-06T00:08:58.524Z', '2020-11-06T00:08:58.524Z'), ('ac719ff6-eaa5-4e2b-a344-6e62472e5591', 'e16ca718-7f6b-4f67-956a-1ec9fda7cf6f', 'ac719ff6-eaa5-4e2b-a344-6e62472e5591', 10, '2020-11-06T00:08:58.524Z', '2020-11-06T00:08:58.524Z') returning "product_id", "supply_id" - column "supply_id" specified more than once`

and:

`previous error: insert into "supplied_products" ("supply_id", "product_id", "supply_id", "quantity", "created_at", "updated_at") values ('ac719ff6-eaa5-4e2b-a344-6e62472e5591', '83c16f3c-f091-496f-b300-61023e106dde', 'ac719ff6-eaa5-4e2b-a344-6e62472e5591', 10, '2020-11-06T00:08:58.524Z', '2020-11-06T00:08:58.524Z'), ('ac719ff6-eaa5-4e2b-a344-6e62472e5591', 'e16ca718-7f6b-4f67-956a-1ec9fda7cf6f', 'ac719ff6-eaa5-4e2b-a344-6e62472e5591', 10, '2020-11-06T00:08:58.524Z', '2020-11-06T00:08:58.524Z') returning "product_id", "supply_id" - column "supply_id" specified more than once`

**Comment by B4nan** [comment]
Because you define that column twice. That is not how MikroORM works, you should define only the m:1, and from that you can get the PK even when the relation is not loaded. If you really want to have that `supply_id: string` there (together with the M:1 `suply`), then you need to mark it as virtual (via `@Property({ persist: false })`). 

Just a side note, mixing different naming conventions (camelCase vs snake_case) makes the code really hard to read, don't do that :]

Also unless you are using ts-morph, you should adhere to the [limitations of the default metadata provider](https://mikro-orm.io/docs/metadata-providers/#limitations-and-requirements) (`public created_at = new Date();` vs `public created_at: Date = new Date();`).

**Comment by sptGabriel** [comment]
> Porque você define essa coluna duas vezes. Não é assim que funciona o MikroORM, você deve definir apenas o m: 1, e a partir disso você pode obter o PK mesmo quando a relação não está carregada. Se você realmente quiser que `supply_id: string`ele esteja lá (junto com o M: 1 `suply`), será necessário marcá-lo como virtual (via `@Property({ persist: false })`).
> 
> Apenas uma observação: misturar diferentes convenções de nomenclatura (camelCase vs snake_case) torna o código realmente difícil de ler, não faça isso:]
> 
> Além disso, a menos que esteja usando ts-morph, você deve seguir as [limitações do provedor de metadados padrão](https://mikro-orm.io/docs/metadata-providers/#limitations-and-requirements) ( `public created_at = new Date();`vs `public created_at: Date = new Date();`).

Thanks I managed to solve, but is my relationship correct?
Many to one on supply and product in suppliedProducts entity and one to many on Supply table?
This worked, but would it be possible to do this with just many to many?
