### ISSUE TITLE
Postgres timestamptz field loses microsecond precision

### ISSUE THREAD

**Issue by daniielgak** [mikro-orm/mikro-orm#1046]
When a postgres timestamptz field is asigned as a primary key it loses the microsecond precision when it's stored in the database.

**To Reproduce**

1. Create an entity with a cratedAt field as PrimaryKey and an updatedAt:

```typescript
@Entity()
export class Log {
    @PrimaryKey()
    @Property({ columnType: 'timestamptz' })
    createdAt = new Date()

    @Property({ columnType: 'timestamptz', onUpdate: () => new Date() })
    updatedAt = new Date()
}
```

2. Persist a log

```typescript
    const log = new Log()

    await logRepository.persist(log)
    await logRepository.flush();
```

3. Get that updated_at has a better presition than the created_at field

| crated_at | updated_at |
| - | - |
| 2020-11-06 12:50:10+00 | 2020-11-06 12:50:10.422+00 |

4. If then you swap the primary key (for sake of trying) and rebuild the schema.

```typescript
@Entity()
export class Log {
    @Property({ columnType: 'timestamptz' })
    createdAt = new Date()

    @PrimaryKey()
    @Property({ columnType: 'timestamptz', onUpdate: () => new Date() })
    updatedAt = new Date()
}
```

5. Persist antoher log

```typescript
    const log = new Log()

    await logRepository.persist(log)
    await logRepository.flush();
```

6. Now the created_at field has better presition

| crated_at | updated_at |
| - | - |
| 2020-11-06 13:12:29.319+00 | 2020-11-06 13:12:29+00 |

I would expect that the same field has the same prestion. I noticed it when I was stress-testing my system, so for requests that occurred in the same second the postgres would give a PK violation in my log table.

| Dependency | Version |
| - | - |
| node | v14.15.0 |
| typescript | 3.7.4 |
| mikro-orm | 4.2.3 |
| postgres | 12.2 |

**Comment by B4nan** [comment]
You say microseconds, but you mean milliseconds, right? Because microseconds are not even supported by JS Date object.

You need to set the length, as default is to store just seconds:

```ts
@Property({ columnType: 'timestamptz(3)' })
createdAt: Date = new Date();
```

**Comment by daniielgak** [comment]
Yes, I was talking about miliseconds! Also I didnt realice that having the both decorators

```typescript
@PrimaryKey()
@Property({ columnType: 'timestamptz(3)' })
createdAt = new Date()
```
was giving me a bit of trouble... so just using one of them worked for me!

```typescript
@PrimaryKey({ columnType: 'timestamptz(3)' })
createdAt = new Date()
```

Thanks! @B4nan

**Comment by B4nan** [comment]
Btw I was thinking what was exactly happening here, and I believe you had both columns with `0` length (default), so only seconds, and the difference was caused by the fact that PK value get's remapped from the db value when persisting new entities. So the PK got back the value from database (in seconds), while the other column remained the original value from JS (so `new Date()` which has the milliseconds).

**Comment by JanJakes** [comment]
I just run into this (using Postgres) and find it a bit dangerous – I'd expect the Postgres default when no precision specified (which is microseconds; simply `timestamptz = timestamptz(6)`) but it gets silently trimmed to "0" instead.

> You say microseconds, but you mean milliseconds, right?

I wouldn't! Microseconds are completely valid as you may use native DB functions to save some timestamps and then sort them in queries, etc.

Moreover, `timestamptz` will always be `8-byte` even if you trim it to seconds so there's really not much need to do that. (https://www.postgresql.org/docs/9.1/datatype-datetime.html)

Do you think @B4nan this should be reopened or is there some reason to make seconds the default?

**Comment by B4nan** [comment]
> I just run into this (using Postgres) and find it a bit dangerous – I'd expect the Postgres default when no precision specified (which is microseconds; simply timestamptz = timestamptz(6)), but it gets silently trimmed to "0" instead.

There is no postprocessing for `columnType`, it is always used as it. So if you do `@Property({ columnType: 'timestamptz' })` the type is really a `timestamptz` (and microseconds will be stored in db). On the other hand if you do `@Property() date: Date`, so if you use the default column time for `Date`, it will be `timestamptz(0)`. Changing the defaults sounds like a breaking change to me, so we should keep that for v5.
