### ISSUE TITLE
b4nan.github.io/mikro-orm is 404ing

### ISSUE THREAD

**Issue by charlex** [mikro-orm/mikro-orm#105]
When visiting http://b4nan.github.io/mikro-orm a "Site not found" error is shown from GitHubPages:

![Screen Shot 2019-09-01 at 3 37 01 PM](https://user-images.githubusercontent.com/1542740/64081404-5b622a00-ccce-11e9-9b13-51292198a6c1.png)

**Comment by B4nan** [comment]
Should be fixed now, I thought it will be properly redirected after I moved the repo to new organization, but apparently not...

**Comment by charlex** [comment]
Thanks for resolving @B4nan !
