### ISSUE TITLE
Allow string as value for queries on a Date in MongoDB

### ISSUE THREAD

**Issue by visurel** [mikro-orm/mikro-orm#1053]
**Is your feature request related to a problem? Please describe.**
Currently when doing a `repository.find({ startTime: { $gt: '2020-11-07T10:00:00.000Z' } })` the data will be passed as is to MongoDB instead of converting the value to `ISODate()`. 
MongoDB will return no results, as it doesn't recognise the value is a date when using just a string.

**Describe the solution you'd like**
I'd like to be able to pass a string value to query an entity with a Date as type (also supporting $gt(e)/$lt(e).

```typescript
@Property()
startTime: Date;
```
```typescript
repository.find({ startTime: { $gt: '2020-11-07T10:00:00.000Z' } }) // Not working => .find({ startTime: { $gt: '2020-11-07T10:00:00.000Z' } })
repository.find({ startTime: { $gt: new Date() } }) // Working => .find({ startTime: { $gt: ISODate('2020-11-07T10:00:00.000Z') } })
```

1. Maybe we can do a check internally if the string passed matches a ISOTime-String (possibly regex or using the Date constructor?) and if it matches convert it to an ISODate
2. ... or we could have an extra option in the `@Property()` options?

**Describe alternatives you've considered**
I tried to create a Custom Type, but Custom Types can't be used for queries.

**Additional context**
I found the line where the Date.prototype is patched but couldn't find a way on how to make it support the string syntax.
The Types for FilterQuery<T> already seem to support the string syntax, so that part should be fine.
https://github.com/mikro-orm/mikro-orm/blob/4668e78d1c900d1718625364b603dda1b707dd82/packages/mongodb/src/MongoConnection.ts#L276

Thanks a lot for making this library! I hope this is a good addition that benefits the people using MongoDB.

**Comment by B4nan** [comment]
I don't really like that idea, the property type is `Date` so should be the parameter type. Custom type is the way to go if you want to support this automatically, but I'd say use `Date` object instead (so just wrap it to `new Date('2020-11-07T10:00:00.000Z')` on the call site).

> I tried to create a Custom Type, but Custom Types can't be used for queries.

What makes you think so? Current version do support mapping of custom types from query parameters. This test demonstrates it, all PKs are using custom types and we query by the runtime value on line 92:

https://github.com/mikro-orm/mikro-orm/blob/master/tests/issues/GH446.test.ts

Also just tried to change that line to use operators, and it works as expected.

> I found the line where the Date.prototype is patched but couldn't find a way on how to make it support the string syntax.

There is no such thing as `ISODate`, that is only about logging a date in mongo query. It is there mainly so users can clearly see what is wrong - as string date is not a `Date` object. The object is a regular `Date`, nothing special.

**Comment by visurel** [comment]
Wow, thanks a lot for the quick answer! Looks like I was wrong. Custom Types are a perfect fit for this use-case, I just didn't set it up correctly. Simply parsing the string to a Date and returning that Date in the Custom Type `covertToDatabaseValue` does the trick. Thanks a lot for the guidance and detailed answer! Closing the issue, as it's resolved now.
