### ISSUE TITLE
nested insert one to one relation.

### ISSUE THREAD

**Issue by sptGabriel** [mikro-orm/mikro-orm#1054]
i have two entities, product and stock products, stock products has a referenced pk: product_id

product:

```
@Entity({ tableName: 'products' })
export class Product {
  @PrimaryKey()
  public readonly id: string;
  @Property()
  public name: string;
  @Property()
  public cod_reference: string;
  @Property()
  public category_id: string;
  @Property()
  public created_at = new Date();
  @OneToOne(() => ProductStocks, stock => stock.product, {
    owner: true,
  })
  public stock: ProductStocks;
  @Property({ onUpdate: () => new Date() })
  public updated_at = new Date();
  @Property()
  public deleted_at?: Date;
  constructor(
    container:productContainer,
  ) {
    this.id = container.id ? container.id : v4();
    this.cod_reference = container.cod_reference;
    this.category_id = container.category_id;
    this.name = container.name
  }
  static build = (
    {id,category_id,cod_reference,name}:productContainer,
  ): Product => {
    if(id && !validate(id)) throw new Error(`invalid uuid`)
    return new Product({id,category_id,cod_reference,name});
  };
}
```
stock:

```
@Entity({ tableName: 'product_stocks' })
export class ProductStocks {
  @OneToOne({ mappedBy: 'stock', primary:true })
  public product: Product;
  @Property({default: null})
  public quantity: number;
  @Property()
  public created_at = new Date();
  @Property({ onUpdate: () => new Date() })
  public updated_at = new Date();
  @Property()
  public deleted_at?: Date;

  constructor(quantity:number, product:Product){
    this.product = product
    this.quantity = quantity
  }
  static build = (quantity:number, product:Product): ProductStocks => {
    return new ProductStocks(quantity,product)
  };
}
```
with that I have a relationship from one to another where the product is the owner, but when using a nested insert for some reason my product_id n field appears:

```
const product = await this.productRepository.create(Product.build(request));
const stock = ProductStocks.build(0,product)
product.stock = stock;
const productPersistence = await this.productRepository.create(product)
insert function:
```

```
  public create = async (product: Product): Promise<Product> => {
    if (!(product instanceof Product)) throw new Error(`Invalid Data Type`);
    await this.repository.persist(product).flush();
    return product;
  };
```

error:
`"insert into \"product_stocks\" (\"created_at\", \"quantity\", \"updated_at\") values ('2020-11-07T11:01:42.413Z', 0, '2020-11-07T11:01:42.413Z') returning \"product_id\", \"quantity\" - null value in column \"product_id\" of relation \"product_stocks\" violates not-null constraint"`

**Comment by B4nan** [comment]
The parameter of `repo.create()` needs to be POJO, not instance of entity. 

And more importantly, `@OneToOne({ mappedBy: 'stock', primary:true })` this is not possible, what do you expect from that? It's inverse, so it is virtual (the column exists on the other side), virtual properties cannot be PKs.

**Comment by sptGabriel** [comment]
> O parâmetro de `repo.create()`precisa ser POJO, não instância da entidade.
> 
> E o mais importante, `@OneToOne({ mappedBy: 'stock', primary:true })`isso não é possível, o que você espera disso? É inverso, portanto é virtual (a coluna existe do outro lado), as propriedades virtuais não podem ser PKs.

but how could I do if my primary key for the table stock is product_id?
and about the entity manager I fork each request
if I remove the primary I get:
ProductStocks entity is missing @PrimaryKey ()

**Comment by B4nan** [comment]
Not sure what you wanna hear, I can only repeat myself. PK cannot be a virtual property. Inverse side is always a virtual property. 

If you want to have that as a PK, it needs to be owning side, not inverse.

**Comment by sptGabriel** [comment]
> Não tenho certeza do que você quer ouvir, só posso me repetir. PK não pode ser uma propriedade virtual. O lado inverso é sempre uma propriedade virtual.
> 
> Se você quiser ter isso como um PK, precisa ser o lado do proprietário, não o inverso.

I understood I was confused, I thought that because the primary key of my stock is a reference to my product.id, my product would be the owner
