### ISSUE TITLE
Smart Nested Populate, self relation

### ISSUE THREAD

**Issue by sptGabriel** [mikro-orm/mikro-orm#1063]
Hello I have an entity that has a relationship with the pk itself:
A category can have a category as a parent, and a category has a collection of sub categories

```
@Entity({ tableName: 'product_categories' })
export class ProductCategory {
  @PrimaryKey()
  public readonly id: string;
  @ManyToOne(() => ProductCategory, {
    nullable: true,
    fieldName: 'parent_id',
  })
  public parent: ProductCategory;
  @Property()
  public name: string;
  @OneToMany(() => Product, product => product.category)
  public products = new Collection<Product>(this);
  @OneToMany({
    entity: () => ProductCategory,
    mappedBy: 'parent',
    orphanRemoval: true,
  })
  public parents = new Collection<ProductCategory>(this);
  @Property()
  public created_at = new Date();
  @Property({ onUpdate: () => new Date() })
  public updated_at = new Date();
  @Property()
  public deleted_at?: Date;

  constructor(container: categoryContainer) {
    this.id = container.id ? container.id : v4();
    this.name = container.name;
    if (container.parent) this.parent = container.parent;
  }
}
```

my repository:

```
  public byId = async (id: string): Promise<ProductCategory | undefined> => {
    const category = await this.repository.findOne(
      { id },
      { parents: LoadStrategy.JOINED },
    );
    if (!category) return;
    return category;
  };
```
for some reason I can load my collection correctly, but when I use getItems / load items it doesn't load:

```
  private validateParent = async (parent_id: string) => {
    const parent = parent_id
      ? await this.categoryRepository.byId(parent_id)
      : null;
    if (parent === undefined) {
      throw new Error('Parent Category Dont Exists.');
    }
    return parent;
  };

  public execute = async ({
    name,
    parent_id,
  }: CreateProductCategoryDTO): Promise<Either<AppError, ProductCategory>> => {
    const hasCategory = await this.categoryRepository.byCategoryName(name);
    if (hasCategory) return left(new Error('Category Already Exists.'));
    const parent = parent_id ? await this.validateParent(parent_id) : null;
    const category = await this.categoryRepository.create(
      ProductCategory.build({ name, parent }),
    );
    console.log(await category.parents.loadItems())
    return right(category);
  };
```

my getItems / load returns an empty array, but if I give a console.log in the instance of my entity I can see the collection as in the following print:

![image](https://user-images.githubusercontent.com/58380116/98596860-d3ef4e00-22b6-11eb-9190-46a7334f29ff.png)

**Comment by B4nan** [comment]
You need to mark the collection as populated to have it as part of the serialized response. Ideally you should use `populate` parameter when loading the entity, or `em.populate()` afterwards.

**Comment by sptGabriel** [comment]
> You need to mark the collection as populated to have it as part of the serialized response. Ideally you should use `populate` parameter when loading the entity, or `em.populate()` afterwards.
> 
> https://mikro-orm.io/docs/nested-populate/#populating-already-loaded-entities
> 
> Or mark it explicitly:
> 
> ```ts
> await category.parents.loadItems();
> category.parents.populated();
> ```

i make this here:

```
  public byId = async (id: string): Promise<ProductCategory | undefined> => {
    const category = await this.repository.findOne(
      { id },
      { populate: {parents: LoadStrategy.JOINED} },
    );
    if (!category) return;
    return category;
  };
```

would it be the same thing?

or do i need to do something in the insertion too?

```
  public create = async (
    category: ProductCategory,
  ): Promise<ProductCategory> => {
    if (!(category instanceof ProductCategory))
      throw new Error(`Invalid Data Type`);
    await this.repository.persist(category).flush();
    return category;
  };
```

**Comment by B4nan** [comment]
> my getItems / load returns an empty array, but if I give a console.log in the instance of my entity I can see the collection as in the following print:

Mmm I missed this sentence. What `getItems()` returns is definitely correct - if it gives you empty array, the collection is empty. What you see in the console might not be accurate, as that is not the list of entities, it's the indexed array accessors (so we can do `coll[1]` to access second element of the collection) and they might be out of sync for some reason.

I was wrong with the previous hint about explicit population - even without that, the collection would be still part of the responses. Loaded collections are always there, without population they will be array of PKs, if you populate them, you will have array of entities. And you have empty array, that means the collection is empty.

**Comment by sptGabriel** [comment]
> > my getItems / load returns an empty array, but if I give a console.log in the instance of my entity I can see the collection as in the following print:
> 
> Mmm I missed this sentence. What `getItems()` returns is definitely correct - if it gives you empty array, the collection is empty. What you see in the console might not be accurate, as that is not the list of entities, it's the indexed array accessors (so we can do `coll[1]` to access second element of the collection) and they might be out of sync for some reason.
> 
> I was wrong with the previous hint about explicit population - even without that, the collection would be still part of the responses. Loaded collections are always there, without population they will be array of PKs, if you populate them, you will have array of entities. And you have empty array, that means the collection is empty.

omg my bad i made a mess in fact my parent relationship that has the populated parents collection.

@B4nan thaks u

**Comment by B4nan** [comment]
Looking more into your code, this part does not make sense: 

```ts
const category = await this.categoryRepository.create(
      ProductCategory.build({ name, parent }),
    );
    console.log(await category.parents.loadItems())
```

Calling `loadItems()` will load the collection state from database, but your entity is not yet persisted anywhere, you just created its instance. You can get current collection items via `getItems()` instead, without making any database query.

**Comment by sptGabriel** [comment]
> ~Looking more into your code, this part does not make sense:~
> 
> ```ts
> const category = await this.categoryRepository.create(
>       ProductCategory.build({ name, parent }),
>     );
>     console.log(await category.parents.loadItems())
> ```
> 
> ~Calling `loadItems()` will load the collection state from database, but your entity is not yet persisted anywhere, you just created its instance. You can get current collection items via `getItems()` instead, without making any database query.~
> 
> edit: or maybe not, my bad, it will not make a query as the collection is initialized, this approach is fine

Hello could you help me with this?
I have a table to represent an n: n relationship, but it is getting complicated because I have to create an entity for each relationship,

i would like to know if i could just create with id?

```
@Entity({ tableName: 'supplied_products' })
export class SuppliedProducts {
  @ManyToOne(() => Product,{ primary: true, fieldName:'product_id' })
  public product!: ReferecedProduct;
  @ManyToOne(() => Supply,{ primary: true, fieldName:'supply_id' })
  public supply!: Supply;
  @Property()
  public unit_price: number;
  @Property()
  public quantity: number;
  @Property()
  public created_at = new Date();
  @Property({ onUpdate: () => new Date() })
  public updated_at = new Date();
  @Property()
  public deleted_at?: Date;
  [PrimaryKeyType]: [number, number];
  constructor(container:SuppliedProductsProps) {
    this.quantity = container.quantity
    this.product = container.product
    this.supply = container.supply
    this.unit_price = container.unit_price
  }
  public static build = (
    {supply,quantity,product, unit_price}:SuppliedProductsProps
  ): SuppliedProducts => {
    if (!(supply instanceof Supply)) throw new Error(`Invalid Supply Type`);
    if (!(product instanceof Product)) throw new Error(`Invalid Product Type`);
    return new SuppliedProducts({product, supply, quantity, unit_price});
  };
}
```

now i have this:

```
const supplyResult = Supply.build(supply, hasContract);
    supplyResult.suppliedProducts.set(
      suppliedProducts.map(supplied => {
        return SuppliedProducts.build({
          product: ensure(hasProducts.find(x => x.id == supplied.product_id)),
          quantity: supplied.quantity,
          supply: supplyResult,
          unit_price: supplied.unit_price
        });
      }),
    );
```

i want like this:

```
const supplyResult = Supply.build(supply, hasContract);
    supplyResult.suppliedProducts.set(
      suppliedProducts.map(supplied => {
        return SuppliedProducts.build({
          product: supplied.product.id,
          quantity: supplied.quantity,
          supply: supplyResult.id,
          unit_price: supplied.unit_price
        });
      }),
    );
```

that is, instead of the relationship being an entity, just being an id that references the entity
