### ISSUE TITLE
OneToOne: extra unique index on primary column

### ISSUE THREAD

**Issue by zarv1k** [mikro-orm/mikro-orm#1064]
**Describe the bug**
Schema generator creates unnecessary unique index on primary column in OneToOne relationship.

**To Reproduce**

**Versions**

| Dependency | Version |
| - | - |
| node | v12.14.1 |
| typescript | 4.0.3 |
| mikro-orm | 4.2.4-dev.121 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
What do you mean, unnecessary? 1:1 is by definition unique and this needs to be enforces via unique constraint.

**Comment by zarv1k** [comment]
@B4nan you are absolutely right, but it is not needed is this column is the only primary column.
Test is [here](https://github.com/zarv1k/mikro-orm/commit/4023e84f7eb972fb866c3d5a3f46374fd5c377fc)

**Comment by zarv1k** [comment]
ORM creates both primary and unique constraints for the same column.

```
alter table \\"user\\" add constraint \\"user_pkey\\" primary key (\\"app_id\\");
alter table \\"user\\" add constraint \\"user_app_id_unique\\" unique (\\"app_id\\");
```

I think `alter table \\"user\\" add constraint \\"user_app_id_unique\\" unique (\\"app_id\\");` is extra constraint and I removed it in my test snapshot.
