### ISSUE TITLE
EntityManager types

### ISSUE THREAD

**Issue by sptGabriel** [mikro-orm/mikro-orm#1065]
Hello I don't know if this is a bug or problem, but basically the type entityManager, it is not the same as type: em.fork or em:

![image](https://user-images.githubusercontent.com/58380116/98677089-4b66c100-233b-11eb-851c-cd207b1b72e7.png)

code:
```
@injectable()
export class DepartamentRepository implements IDepartamentRepository {
  private em: EntityManager;
  constructor(@inject('bootstrap') bootstrap: IBootstrap) {
    this.em = bootstrap.getDatabaseORM().getConnection().em.fork();
    //
  }
}
```

ts-error:
```

(property) DepartamentRepository.em: EntityManager<AbstractSqlDriver<AbstractSqlConnection>>
Type 'EntityManager<IDatabaseDriver<Connection>>' is missing the following properties from type 'SqlEntityManager<AbstractSqlDriver<AbstractSqlConnection>>': createQueryBuilder, getKnex, executets(2739)
```

**Comment by B4nan** [comment]
You need to specify the type argument. 

```ts
private em: EntityManager<AbstractSqlDriver>; // or even better use the actual driver instance, e.g. EntityManager<MySqlDriver>
```

Various drivers have custom EM implementations, like the SQL drivers have SqlEntityManager, that implements things like `createQueryBuilder()` method (contrary the mongo driver have MongoEntityManager which does not have such method, but have other ones, like `aggregate()`).

`SqlEntityManager` is reexporeted from all SQL driver packages aliased as `EntityManager`, so you can do:

```ts
import { EntityManager } from '@mikro-orm/mysql'; // this is in fact `SqlEntityManager`
```

**Comment by sptGabriel** [comment]
> 
> 
> You need to specify the type argument.
> 
> ```ts
> private em: EntityManager<AbstractSqlDriver>; // or even better use the actual driver instance, e.g. EntityManager<MySqlDriver>
> ```
> 
> Various drivers have custom EM implementations, like the SQL drivers have SqlEntityManager, that implements things like `createQueryBuilder()` method (contrary the mongo driver have MongoEntityManager which does not have such method, but have other ones, like `aggregate()`).
> 
> `SqlEntityManager` is reexporeted from all SQL driver packages aliased as `EntityManager`, so you can do:
> 
> ```ts
> import { EntityManager } from '@mikro-orm/mysql'; // this is in fact `SqlEntityManager`
> ```

i use this:
import { AbstractSqlDriver, EntityManager } from '@mikro-orm/postgresql';
```

import { AbstractSqlDriver, EntityManager } from '@mikro-orm/postgresql';
@injectable()
export class DepartamentRepository implements IDepartamentRepository {
  private em: EntityManager<AbstractSqlDriver>;
  constructor(@inject('bootstrap') bootstrap: IBootstrap) {
    this.em = bootstrap.getDatabaseORM().getConnection().em.fork();
    //
  }
}
```

but i got:
`Type 'EntityManager<IDatabaseDriver<Connection>>' is missing the following properties from type 'SqlEntityManager<AbstractSqlDriver<AbstractSqlConnection>>': createQueryBuilder, getKnex, executets(2739)`

I use the postgres package, but it still doesn't work

**Comment by B4nan** [comment]
Because you have wrongly typed `getDatabaseORM` or its `getConnection` method. It all need to be aligned, e.g. you should always import the EM from driver package. Also the `MikroORM` class have same type argument (as well as the `MikroORM.init()` method), so you need to have `MikroORM<PostgreSqlDriver>` in there to have `orm.em` typed correctly.

**Comment by sptGabriel** [comment]
> 
> 
> Because you have wrongly typed `getDatabaseORM` or its `getConnection` method. It all need to be aligned, e.g. you should always import the EM from driver package. Also the `MikroORM` class have same type argument (as well as the `MikroORM.init()` method), so you need to have `MikroORM<PostgreSqlDriver>` in there to have `orm.em` typed correctly.

this fix my entity manager but on my connection i got type error:

```
@injectable()
export class MikroOrmClient implements IDatabaseORM {
  private connection: MikroORM<PostgreSqlDriver>;
  constructor(@inject('OrmConfig') private options: Options) {}
 public start = async () => {
    try {
      this.connection = await MikroORM.init(this.options);
      container.registerInstance('Connection', this.getConnection());
      container.registerInstance<EntityManager>(
        'EntityManager',
        this.getEntityManager(),
      );
      const migrator = await this.connection.getMigrator();
      const migrations = await migrator.getPendingMigrations();
      if (!(migrations && migrations.length > 0)) return;
      await migrator.up();
    } catch (error) {
      process.stdout.write(chalk.redBright(`${(error as Error).message}\n`));
    }
  };
}
```

here:
`    this.connection = await MikroORM.init(this.options);`
i got:
```
Type 'MikroORM<IDatabaseDriver<Connection>>' is not assignable to type 'MikroORM<PostgreSqlDriver>'.
  Type 'IDatabaseDriver<Connection>' is missing the following properties from type 'PostgreSqlDriver': connection, replicas, platform, mapJoinedProps, and 24 more.ts(2322)
```

**Comment by B4nan** [comment]
As I said in the last message, you need to type the `MikroORM.init` too. 

```ts
this.connection = await MikroORM.init<PostgreSqlDriver>(this.options);
```

Or you can have the options parameter typed as `Options<PostgreSqlDriver>`.
