### ISSUE TITLE
Add `Reference<T>` wrapper to allow better type checking of m:1 and 1:1 references

### ISSUE THREAD

**Issue by vimmerru** [mikro-orm/mikro-orm#107]
Hi,

I noticed that documentation suggest to define one-2-one and many-2-one references this way:

```
@Entity()
export class User {
  @PrimaryKey()
  id!: number;

  @Property()
  username: string;

  @OneToOne({ mappedBy: 'credentials' })
  credentials: Credentials;

  constructor(props: Omit<User, 'id'>) {
    super();
    this.username = props.username;
    this.credentials = props.credentials;
  }
```

but when i load user with entity manager property credential can be Reference. It causes problems with typing and strict null checking. 

```user.credentails.some_property``` can just be null in runtime, but it can't be null from perspective of my domain model and type system.  This problem can be solved if credentials property will not be Credentials type directly, but some proxy generalized with Credentials type. For example,

```
@Entity()
export class User {
  @PrimaryKey()
  id!: number;

  @Property()
  username: string;

  @OneToOne({ mappedBy: 'credentials' })
  credentials: Reference<Credentials>;

  constructor(props: Omit<User, 'id'>) {
    super();
    this.username = props.username;
    this.credentials = new Reference(props.credentials);
  }
}
```

So if i call ```user.credentials``` it returns Reference<Credentials> and to access credentials i can do something like:

```await user.credentials.load()``` 

If reference is already populated it will just skip queries. Is it possible already?

**Comment by B4nan** [comment]
There is already `IEntity.init()` method that allows to load entity reference and `IEntity.isInitialized()` to tell you whether it is fully loaded already. Those methods are available on every discovered entity. 

https://mikro-orm.io/entity-references/

Not sure what would be the difference if following your approach with `Reference` wrapper. You would still have always a reference type instead of the entity type, regardless its loading state, or not? 

Currently `IEntity.init()` will always run queries and refresh the state, but we can easily add a parameter there to allow making queries only when needed.

**Comment by vimmerru** [comment]
> There is already IEntity.init() method that allows to load entity reference and IEntity.isInitialized() to tell you whether it is fully loaded already.

The problem with this approach is loosing of advantages of Typescript type system. If i just remember to call IEntity.init() i will just only know about this problem with crush on production instead of compilation error that most developers wants.

> Not sure what would be the difference if following your approach with Reference wrapper. You would still have always a reference type instead of the entity type, regardless its loading state, or not?

The difference in strictness of null checking. With my approach ```user.credentials``` have Reference type that doesn't expose Credential fields and you just can't write the code that will crash in runtime. The code will loos like:

```
const user = em.findOne(User, id); 
const credentials = await user.credentials.load();
const passwordHash = credentials.passwordHash; // just can't be null from type system and runtime perspectives
```

With current approach i can just write the code

```
const user = em.findOne(User, id); 
const passwordHash = user.credentials.passwordHash; // runtime crash here, but success compilation
```

**Comment by B4nan** [comment]
I guess I understand now. So you would want a solution which will force you to always call the `load()` method that would either unwrap the entity reference to just entity, or do the necessary queries to load it first. 

I am fine with having this as optional approach. `Reference` sounds like a good name for this. Would you be up to create a PR? If not, I can do this myself, probably as part of preparations for v3 release.

**Comment by vimmerru** [comment]
> I guess I understand now. So you would want a solution which will force you to always call the load() method that would either unwrap the entity reference to just entity, or do the necessary queries to load it first.

I believe it is a good summary

> I am fine with having this as optional approach. Reference sounds like a good name for this. Would you be up to create a PR? If not, I can do this myself, probably as part of preparations for v3 release.

For the moment i am considering switching from TypeORM to this project that looks promising. TypeORM looks unmaintainable, contains a lot of bugs, legacy, poor typings and based on patterns i don't like. I am not sure i am ready for PRs right now.  If you can provide some guidance i can try.

**Comment by B4nan** [comment]
First step is to setup docker, bootstrap all deps via `docker-compose`, then create mysql and postgre databases and you should be fine to run the tests. There is a contributing guide here: https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md

Feel free to try and feel free to reach out via slack to discuss any problems on the way. I would love to attract more collaborators, so if you find something you don't understand on this way, I will be more than happy to improve the contributing guide. 

Regarding the implementation itself, this will probably require some advanced validation of entity type, as currently the type is sniffed via reflection (via `ts-morph`) if not provided manually. And in this case one will be probably required to specify the type manually (via `entity` or `type` decorator options). But not 100% sure, it might be possible to sniff the generic parameter via `ts-morph` as well (then this would have to be implemented in `TypeScriptMetadataProvider`. 

I tagged the issue with help-wanted -- will remove that tag and assign myself when I have time for this so you know its being worked on. I would like to have it as part of v3 release, which is almost ready - I expect to finish with it by the end of this month (feature development is pretty much done, but need to write all the documentation and announcement article).

**Comment by B4nan** [comment]
One last thing - if you try to work on this, please use the `dev` branch as a base, and point the PR to be merged there.

**Comment by B4nan** [comment]
Initial implementation is available for testing via `next` tag (`3.0.0-alpha.3`).

There is `Reference<T>` entity wrapper and `IdentifiedReference<T, PK>` interface, which adds also PK property.

```typescript
// define like this
@ManyToOne({ cascade: [Cascade.PERSIST, Cascade.REMOVE] })
publisher: IdentifiedReference<Publisher, 'id'>; // second type parameter will be optional, it specifies the PK field name (can be also `'id' | '_id'` for mongo)

// assign via factory method that returns the `IdentifiedReference` interface
book.publisher = Reference.create(new Publisher(...));

// you can access PK and some helper methods directly
console.log(book.publisher.id);
console.log(book.publisher.isInitialized());
console.log(book.publisher.toJSON());

// you can also use unwrap to access the entity directly
console.log(book.publisher.unwrap()); // Publisher entity

// or use the load method to initialize if needed
console.log(await book.publisher.load()); // returns always intialized Publisher entity
```

**Comment by B4nan** [comment]
In `3.0.0-alpha.4` there is also `wrapped` flag in `em.getReference()`:

```typescript
const ref = orm.em.getReference<Author, 'id' | '_id'>(Author, 1, true);

// or via repository
const repo = orm.em.getRepository(Author);
const ref1 = repo.getReference<'id' | '_id'>(1, true);
console.log(ref1.id); // ok
console.log(ref1._id); // ok

// one can also omit the PK type parameter, but then unwrap() or load() is needed to access the PK
const ref2 = repo.getReference(1, true);
console.log(ref2.id); // type error
console.log(ref2.unwrap().id); // ok
console.log((await ref2.unwrap()).id); // ok
```

**Comment by B4nan** [comment]
Closing as resolved, feel free to reopen if you have any problem with that.
