### ISSUE TITLE
Changing the loading strategy globally doesnt work.

### ISSUE THREAD

**Issue by jagabs** [mikro-orm/mikro-orm#1075]
```
MikroORM.init({
  loadStrategy: LoadStrategy.JOINED,
});
```

but it does work here: 
```
return await ctx.em.getRepository(Employee).findOneOrFail(id, {
      filters: [FILTERS.TENANT],
			populate: ["deductions", "tax"],
			strategy: LoadStrategy.JOINED
    });
```

**Versions**

| Dependency | Version |
| - | - |
| node |v14.15.0 |
| typescript | ^3.9.7 |
| mikro-orm | 4.0.0-rc.0 |
"@mikro-orm/postgresql": "^4.0.0-rc.0",

**Comment by B4nan** [comment]
Are you really using version `4.0.0-rc.0`? If so, upgrade to latest, which is `4.2.3`.

**Comment by jagabs** [comment]
issue fixed. thanks
