### ISSUE TITLE
Issue with Embeddable when extending class?

### ISSUE THREAD

**Issue by murbanowicz** [mikro-orm/mikro-orm#1076]
**Describe the bug**
I have a base class for handling addresses across the application.

`export class BaseAddressModel extends BaseModel {` 
where BaseModel is used across the app for id and timestamps (working fine).

I am trying to use:
```ts
@Embeddable()
export class EmployerAddress extends BaseAddressModel {}
```

and use it like 
```ts
@Embedded()
public address: EmployerAddress
```

It is for some reason completely not recognized by the MikroORM then, which can be easily spotted by the fact that it is not included in the migrations at all.

It starts working as soon as I add `@Embeddable` to the BaseAddressModel, but this is not what I want to do to be honest, as we expect cases when we will need to extend it and use the entity, so not sure if `Embeddable` won't make a mess then?

I am using Postgres driver.
Node 14,
MikroORM: 4.2.3
PG: 12
TypeScript 4.0.3

**Comment by B4nan** [comment]
Oh I see, this was already reported in #1049 and fixed via #1051, should work in master.

**Comment by B4nan** [comment]
No, I mean master. You could try the dev version, its `4.2.4-dev.131`, but you need to use `yarn` and its `resolutions` due to one mispublished version.

```
  "resolutions": {
    "@mikro-orm/cli": "4.2.4-dev.131",
    "@mikro-orm/core": "4.2.4-dev.131",
    "@mikro-orm/knex": "4.2.4-dev.131",
    "@mikro-orm/postgresql": "4.2.4-dev.131",
    "@mikro-orm/reflection": "4.2.4-dev.131",
    "@mikro-orm/migrations": "4.2.4-dev.131",
    "@mikro-orm/entity-generator": "4.2.4-dev.131"
  },
```

**Comment by murbanowicz** [comment]
Ah, I understand. When do you expect it to be published as normal version?

**Comment by B4nan** [comment]
Up to an hour I guess, definitely today. I was already postponing it for too long, but there were some issues that could be seen as breaking changes so wanted to resolve it first.

**Comment by B4nan** [comment]
`4.3.0` is out

**Comment by B4nan** [comment]
Closing as resolved (as discussed on slack).
