### ISSUE TITLE
Typescript error on `$in` being used on an array with MongoDB

### ISSUE THREAD

**Issue by apascal** [mikro-orm/mikro-orm#1077]
Hi, I am having a problem regarding a `where` `FilterQuery`, used on a `find()` on a MongoDB database, which works but throws a TS exception with MikroOrm :

**Code**
Here is the definition of the entity, `categories` being an array:
```
class Article {
  ...
  @Property()
  categories: string[];
}
```

This is the code extract that triggers the error:
```
find({
  categories: { $in: ['a', 'b'] },
})
```

Here is the TS exception, which is quite cryptic:
```
(property) $in?: FilterValue2<string[]>[] | undefined
Argument of type '{ categories: { $in: string[]; }; }' is not assignable to parameter of type 'string | number | { [PrimaryKeyType]?: any; } | Article | { _id?: number | OperatorMap<FilterValue2<number>> | FilterValue2<number>[] | null | undefined; ... 16 more ...; path?: string | ... 4 more ... | undefined; } | OperatorMap<...> | FilterValue2<...>[] | undefined'.
  Types of property 'categories' are incompatible.
    Type '{ $in: string[]; }' is not assignable to type 'string[] | { [x: number]: string | RegExp | OperatorMap<FilterValue2<string>> | FilterValue2<string>[] | null | undefined; } | OperatorMap<FilterValue2<string[]>> | FilterValue2<...>[] | null | undefined'.
      Types of property '$in' are incompatible.
        Type 'string[]' is not assignable to type 'FilterValue2<string[]>[]'.
          Type 'string' is not assignable to type 'FilterValue2<string[]>'.ts(2345)
```

**Expected behavior**
According to the documentation of Mongo, this is a legit query: https://docs.mongodb.com/manual/reference/operator/query/in/#use-the-in-operator-to-match-values-in-an-array 

**Additional context**
When key `categories` is **not** an array (`id` for example), the `$in` keyword works and TS does not complain.

Workaround:
```
{
  categories: { $in: ['a', 'b'] } as any,
}
```

**Versions**
| Dependency | Version |
| - | - |
| node | 14.14.0 |
| typescript | 4.0.5 |
| mikro-orm | 4.2.3 |
| mongodb | 3.6.3 |

**Comment by DamithaPerera** [comment]
I also had the same problem, but after adding  `as any` worked for me.

`{
  categories: { $in: ['a', 'b'] } as any,
}`

**Comment by B4nan** [comment]
This isssue is almost 2 years old, there are tests added together with the fix, if you have similar issue, please provide reproduction.

**Comment by EmmanDizon** [comment]
encountering the same issue
