### ISSUE TITLE
Suggestion for debug in version 3.0

### ISSUE THREAD

**Issue by localnet** [mikro-orm/mikro-orm#108]
I think taking advantage the next major version can be interesting replace current debug configuration:

```
logger: console.log.bind(console),
debug: true,
```
And substitute it by [debug](https://github.com/visionmedia/debug) module, this can permit to filter easily the output:

`DEBUG=mikro-orm:query`

PS: This is more opinionated. But now there is one MySQL connector that seems more official [mariadb](https://github.com/MariaDB/mariadb-connector-nodejs) (developed by MariaDB and the [benchmarks](https://github.com/MariaDB/mariadb-connector-nodejs/blob/master/documentation/benchmarks.md) seems good).

**Comment by B4nan** [comment]
How would this work with frameworks like nest, where you have a logger instance - and you generally want to use this logger in ORM as well?

I am definitely open for more logging configuration (e.g. an array of log types/modules like `['query', 'query-time', 'connection-name', 'discovery']`), but not sure about the `debug` module itself. I feel like that is more for general debugging, while query logging is a bit different thing.

About the mariadb connector, we can easily support that via `MariaDbDriver` and let users choose, no problem with that. With knex integrated it should be really easy. Please create another issue for that.

**Comment by localnet** [comment]
I didn't think on frameworks as nest, I never used it. I can see you have been working on it, I will try it in the next version.

I will open another issue for the mariadb connector.

Nice talking to you, as always.

**Comment by B4nan** [comment]
Yop, just implemented all my proposals from above. Thanks for the poke, I wanted to make logging better for some time now, just wasn't sure how to improve it :]
