### ISSUE TITLE
cli: generate-entities only returns tables from the public schema (postgresql)

### ISSUE THREAD

**Issue by nip10** [mikro-orm/mikro-orm#1082]
**Describe the bug**
generate-entities only generates entities for tables in the default `public` schema.

**To Reproduce**
1. Create a custom schema in a PostgreSQL database
2. Run generate-entities

**Expected behavior**
The command should generate entities for all tables in all schemas.

**Additional context**
Using the following command `npx mikro-orm generate-entities -s -p=./my-entities`.
Config:
```ts
 config = {
    dbName: DB_DATABASE_DEV,
    type: 'postgresql',
    highlighter: new SqlHighlighter(),
    host: DB_HOST_DEV,
    port: Number(DB_PORT_DEV),
    user: DB_USERNAME_DEV,
    password: DB_PASSWORD_DEV,
    entities: ['dist/database/entity'],
    entitiesTs: ['src/database/entity'],
    debug: true,
  };
```

**Versions**

| Dependency | Version |
| - | - |
| node | v14.2.0 |
| typescript | v3.9.7 |
| mikro-orm | v4.3.0 |
| @mikro-orm/postgresql |v4.3.0 |

**Comment by B4nan** [comment]
Interesting to see this, next to #1301 that says the opposite 🤷 

This particular issue sounds more like you have misconfigured `search_path` or persmission problem. Here is the query used to get the list of tables in postgres, you can see it ignores just the system schemas (that start with `pg_` prefix) and the `information_schema`, it is not bound to just `public`:

```sql
select table_name, nullif(table_schema, 'public') as schema_name 
from information_schema.tables where table_schema not like 'pg_%' and table_schema != 'information_schema' 
and table_name != 'geometry_columns' and table_name != 'spatial_ref_sys' and table_type != 'VIEW' order by table_name
```
