### ISSUE TITLE
Possibility to use MariaDB connector

### ISSUE THREAD

**Issue by localnet** [mikro-orm/mikro-orm#110]
Now there is one MySQL connector that seems more official, [mariadb](https://github.com/MariaDB/mariadb-connector-nodejs), developed by MariaDB and the [benchmarks](https://github.com/MariaDB/mariadb-connector-nodejs/blob/master/documentation/benchmarks.md) seems good.

**Comment by B4nan** [comment]
Available for testing via `next` tag since `3.0.0-alpha.5`.

**Comment by B4nan** [comment]
Closing as resolved.
