### ISSUE TITLE
Question: Sql Query with filters

### ISSUE THREAD

**Issue by jagabs** [mikro-orm/mikro-orm#1103]
NOT (startDate>= :endDate OR endDate<= :startDate)`

Can i achieve this with @Filter? or Should i use queryBuilder?

@Filter({
  name: "startDateGte",
  cond: (args) => ({ startDate: { $gte: args.endDate } }),
})
@Filter({
  name: "endDateLte",
  cond: (args) => ({ endDate: { $lte: args.startDate} }),
})

how do I add NOT and OR?

**Comment by B4nan** [comment]
Sure, there are `$not` and `$or` operators too, you could do something like:

```ts
@Filter({
  name: 'startDate',
  cond: (args) => ({
    $not: { $or: [
      { startDate: { $gte: args.endDate } },
      { endDate: { $lte: args.startDate } },
    ] },
  }),
})
```

But it can be much easier if you simplify your condition by [propagating the negation](https://en.wikipedia.org/wiki/De_Morgan%27s_laws). You could rewrite `NOT (A || B)` to `(NOT A) && (NOT B)`, in other words `NOT (startDate>= :endDate OR endDate<= :startDate)` is the same as `(startDate < :endDate AND endDate > :startDate)`:

```ts
@Filter({
  name: 'startDate',
  cond: (args) => ({
    { startDate: { $lt: args.endDate } },
    { endDate: { $gt: args.startDate } },
  }),
})
```

**Comment by jagabs** [comment]
thanks it looks simple too :)
