### ISSUE TITLE
Custom classes for partial (and maybe cross-table) selects

### ISSUE THREAD

**Issue by alpharder** [mikro-orm/mikro-orm#1104]
**Q: Is your feature request related to a problem? Please describe.**

**A: Type mismatch when using partial selects.** 
When I work with fetching partial entities, I want to use powers of correct typings. 
Current implementation of fetching partial queries returns an instance of entity class with `undefined` as a value for fields that are left unselected.
I find this behaviour as OK for rapid development, but in case of using the `--strictNullChecks` TypeScript flag (which is encouraged to be used by TS team, and it really helps in big projects), it does not make sense. Entity class property type declarations, reflect the fact that all non-nullable fields will not have `undefined` value, so entity instance returned by ORM violates class type declarations.

```
    // Example of non-nullable field property definition:
    @Property()
    title: string;

    // Example of nullable field property definition:
    @Property({ nullable: true })
    title: string | null;
```
None of these fields can be `undefined`, but we end up having entity instance that passes all type constraints and even runtime type-checks like `typeof` or `instanceof`, but the actual properties' values do violate their declared types. This may lead to a lot of problems in the code and reduces the usefulness of using TypeScript.

**Describe the solution you'd like**

I'd like to have an ability either to 
* Create an emulation of views at ORM level – e.g. defining a virtual "entity" and its select query (which can be a selection of partial fields of one table or a selection of cross-table fields (e.g. query with joins) – for example, when I need to query some book fields and it's author's fields and have a separate class representation for each individual row of the query result set.

* or at least an ability to define a class that should be used for populating/hydrating fields for an individual query. There are lots of options that can be discussed, whether this API should be implemented on entity manager level or on query builder level. This is a proposal without the final vision of its API, because I'm not aware of the ORM internal design yet.

**Describe alternatives you've considered**
Alternative to that could be using so-called "views" at RDMBS level, while creating a mapping for each view to its individual ORM entity. This approach does solve the problem described above, but also introduces another problems: 
- Views maintenance is complicated (migrations, separate DB user permissions for managing views, etc)
- Some queries will be handled and managed by ORM, but others will exist in form of views, which is heterogeneity that should be avoided when possible 

Workarounds:
```
import { plainToClass } from 'class-transformer';

// Hydration of a custom class using class-transformer library
class BookInfoAvailableToRegularUser {
  id: number;
  title: string;
}
const plainObject = await orm.em.createQueryBuilder(Book).select(['id', 'title']).limit(1).execute('get');
const entity = plainToClass(BookInfoAvailableToRegularUser, plainObject);

console.assert(entity instanceof BookInfoAvailableToRegularUser); // true
```

**Additional context**

* This problem is also referenced at Doctrine docs https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/partial-objects.html#partial-objects, but they provide no solution for that.
* Yii framework's ORM has "extra fields" feature, but the mapping is done within the main entity, which is an arguable solution and is a mixup of concerns – table columns and result set fields.

Thank you for this library, it's already awesome and is constantly improving.

**Comment by alpharder** [comment]
This feature goes beyond the traditional vision of Object Relational Mapping, because we only usually map _table columns_ to object properties. However, the reality is a bit more complicated and we often need to optimise our queries and query only what's needed. This use case breaks the traditional ORM approach and introduces a requirement to map query _result set_ fields to object properties.

I personally find this feature request as a field for further analysis, discussions of its necessity and architectural design.

I've never met an ORM that provides this feature, but there are not so many fast-growing ORMs on the market like this one.

**Comment by B4nan** [comment]
There is already an issue for view entities: #672

**Comment by alpharder** [comment]
@B4nan As I've mentioned, working with RDBMS views _technically does solve_ the problem I've described, but it has a lot of downsides: they add complexity into the development and delivery process, increase maintenance efforts and introduce heterogeneity of querying logic.

ORM support for the view entities is definitely is a good feature _for those who uses_ RDBMS views. My proposal solves the same problem as RDBMS views + its' support by ORM, but without the downsides of having views in the project.

**Comment by B4nan** [comment]
Yes, but technically it will be the same feature, with some toggle to control how the backend works - whether or not to use native view or issue the query. The solution with a simple query instead of native view is indeed much easier to implement and maintain, so it could be the first step for sure.

**Comment by alpharder** [comment]
Yeah, this could be one of the possible ways of how to get things working in an expected way.
If the additional backend (query instead of working with a real view) can be planned to be added within #672 then I think this issue can be closed to avoid duplication.
