### ISSUE TITLE
[BUG] Select bug with findAll()

### ISSUE THREAD

**Issue by reramjiawan** [mikro-orm/mikro-orm#1106]
When your table name is the same as the property e.g:

```
@Entity({ tableName: 'type' })
export class TypeEntity implements TypeModel {
  @PrimaryKey({ length: 36 })
  id: string = v4();

  @Property({ unique: true, nullable: false })
  type: string;
}
```
And you perform a findAll();

![afbeelding](https://user-images.githubusercontent.com/15954808/99890058-ab266b80-2c5b-11eb-9ca6-ce997d66a10f.png)

The result will be only the id and the type property is missing.

![afbeelding](https://user-images.githubusercontent.com/15954808/99890043-75818280-2c5b-11eb-8dff-719b5d31d2ab.png)

**Comment by reramjiawan** [comment]
This is also the case for nested relations where the top parent has the same name as the nested properties and they are missing.

**Comment by B4nan** [comment]
What version are you on?

**Comment by reramjiawan** [comment]
Version: 4.3.1

**Comment by B4nan** [comment]
Provide a reproduction, and don't ignore the issue template. You gave me 2 screenshots of unrelated things, I need to see your code, not debug logs of the queries. Fetching such entity works as expected, all properties are there. Your logged query on the other hand, is not from loading entity via `findAll`, as there is a condition for the `id`, so I'd expect its from population. But you failed to give me literally any details, I see one entity with no relations. 

Will close this, as what you gave me here is working as expected. Open new issue with executable reproduction, take a look here for inspiration: 

https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues
