### ISSUE TITLE
Multiple ManyToOne relations with the same column

### ISSUE THREAD

**Issue by ml1nk** [mikro-orm/mikro-orm#1110]
**Is your feature request related to a problem? Please describe.**

I have the class "Base" which holds the primary key and a class "A" which is OneToOne related to the "Base" class with FK as PK. In addition there is a class "B" which has a "ManyToOne" relation to "Base". I want to define a  "OneToMany" relation from "A" to "B".

The "node" of "A" and "node" of "B" are each inherited by another class. So I can't change the relation in B to A instead of B and either way i want both ways (from B to A and B to Base) to work.  

It's a rather special feature, so just close this requests if it's out of scope. I'm currently using separate finds to get the data i need, which works but is rather ugly in comparison of using relations.

~~~javascript
export class A {
  [PrimaryKeyType]: number
  [PrimaryKeyProp]: 'node'
  @OneToOne({ primary: true, onDelete: 'cascade', onUpdateIntegrity: 'cascade' })
  node!: IdentifiedReference<Base>

  @OneToMany(() => B, b => b.node)
  bs!: B[]
}
~~~
~~~javascript
export class B  {

  @PrimaryKey()
  id!: integer

  @ManyToOne({ onUpdateIntegrity: 'cascade', onDelete: 'cascade' })
  node!: IdentifiedReference<Base>
}
~~~
~~~javascript
export class Base {
  @PrimaryKey()
  id!: integer
}
~~~

Throws as expected:
~~~javascript
MetadataError: A.node has unknown 'inversedBy' reference: Base.bs
~~~

**Describe the solution you'd like**
Some kind of way to create a readonly "ManyToOne" relation variant which uses the same column name as another "ManyToOne" relation, which then can be mapped normally by a "OneToMany" relation in the class. 

~~~javascript
@ExtendManyToOne({ original: 'node' })
a!: IdentifiedReference<A>
~~~

**Comment by B4nan** [comment]
Sounds a bit like polymorphic relations (#330)? Keep in mind that this would mean you cannot use native FKs (aka forget about native cascade delete, and be prepared to maintain inconsistent data). 

Or maybe a use case for [STI](https://mikro-orm.io/docs/inheritance-mapping/#single-table-inheritance)?

In general it is not possible to point to a base class from a relation, you can only target leafs or you need to use STI (where you can target the base class that defines the discriminator column. Base classes (mapped superclasses) do not live during runtime, their metadata are inlined to the leaf entities.

Btw your `B` entity has dedicated `id` PK, but your are telling the ORM that the PK is `node`.

**Comment by ml1nk** [comment]
You are right, it is kind of a polymorphic relation. STI does not solve our problem in a good way, MTI probably would. Native FKs would work at least in some ways over the "Base" class, as if I delete A then it deletes the correspondent Base which deletes B. Thanks.

> Btw your B entity has dedicated id PK, but your are telling the ORM that the PK is node.
Edited :+1:
