### ISSUE TITLE
Entities with nullable Many-To-One relations to entities with BigInt PK create updates on flush for no reason

### ISSUE THREAD

**Issue by hilkeheremans** [mikro-orm/mikro-orm#1117]
**Describe the bug**
When an entity has optional relations to itself (eg a parent-child relation pattern), the entity will in many cases create an _update_ query whenever any entity that has it populated is flushed. The update query attempts to set the 'parent' entity (a ManyToOne relation) to NULL, while it is undefined.

This appears to be a bug in the change set computing, where a false positive for entity changes appears to be produced for this type of relation.

**Stack trace**
None available, but with the repo below, it should be trivial for you to reproduce the issue.

**To Reproduce**
Consult the repo at https://github.com/hilkeheremans/mikro-orm-bug. Clone, install deps, and run `yarn start`. The console output will give you a few test scenarios that trigger the behavior. The debug output logs for Mikro-ORM will show that update queries are being generated even though not a single change is made to the entities.

**Expected behavior**
When an entity is loaded and not modified, it should not trigger any updates on flush, especially not in relations.

**Versions**

| Dependency | Version |
| node | v12.16.1 |
| typescript | v4.x |
| mikro-orm | confirmed in 4.2.x and 4.3.x |
| your-driver | SQLite as well as PostgreSQL |

**Comment by B4nan** [comment]
Looks like this is actually caused by wrong entity definition, your PKs do not have explicit type and are using property initializer, so the type is inferred only as `object`, which results in usage of wrong property comparator when diffing the state.

Changed it to this in all the entities and no update statements are issued.

```ts
  @PrimaryKey()
  id: string = v4()
```

**Comment by hilkeheremans** [comment]
Hm, then it looks like I repro'd it wrong. I also have this in a few other cases where the property _is_ defined. The repo I provided was an attempt at a simplified case.

I'll try to update the repro repo to see if I can find other cases. Could you leave this bug open in the mean time?

**Comment by B4nan** [comment]
Sure, will change the tag so its clear this is not reproducible just yet.

**Comment by hilkeheremans** [comment]
I switched the PK type to BigInts (per the Mikro-ORM docs), and now this issue is back. See repo - I pushed the changes needed to show the issue (did not update the console.logs).

This is probably the point where I facepalm and you tell me "I am using it wrong"? :-)

**Comment by B4nan** [comment]
Its more about how the comparison works now (with the JIT optimizations), BigIntType will be compared as object probably, and that is where the null vs undefined is not handled correctly.

**Comment by hilkeheremans** [comment]
👏 So there _is_ a bug. Whew. Updated the title a little. 

Let me know what I can do to help fix this.

**Comment by B4nan** [comment]
As a workaround, it should be enough to extend the `BigIntType` adding `compareAsType` method to force string comparison:

```ts
export class MyBigIntType extends BigIntType {

  compareAsType() {
    return 'string';
  }

}
```

Will need to verify if we actually want to compare objects as `null === undefined`, probably yes (we do so with scalars), that would be the correct fix then.

**Comment by B4nan** [comment]
Try `4.3.2-dev.11`, should be working fine now.

**Comment by hilkeheremans** [comment]
The workaround by itself was not sufficient; an upgrade to the dev version you specified helps for both SQLite and PostgreSQL. Big improvement. Thanks!

**Comment by B4nan** [comment]
Good, will ship stable later today.
