### ISSUE TITLE
Surprising cascade behaviour when pointing new entities to an existing Collection

### ISSUE THREAD

**Issue by jjhbw** [mikro-orm/mikro-orm#1126]
**Describe the bug**
Hi! Thanks for this amazingly fast and ergonomic ORM. 

I was surprised by some unexpected behaviour of a ManyToOne Collection.

The following snippet best illustrates my point.  Note that all relations have `eager:true` and `Cascade.ALL`. Please find a full reproduction in [this repository](https://github.com/jjhbw/mikro-ORM-repro).

```typescript
    const author = new Author()
    author.name = 'John'

    const page = new Page()
    page.text = 'new phone who dis'

    const book = new Book()
    book.pages.set([page])
    author.books.set([book])

    await connection.em.persistAndFlush(author)
    connection.em.clear()

    {
        const author = await connection.em.findOneOrFail(Author, 1)
        const book = new Book()
        const old_page = author.books.getItems()[0].pages.getItems()
        book.pages.set(old_page)
        author.books.set([book])
        await connection.em.persistAndFlush(author)
        connection.em.clear()        
    }

    {
        const author = await connection.em.findOneOrFail(Author, 1)
        if (author.books[0].pages.length !== 1) throw new Error(`Unexpected number of pages: ${author.books[0].pages.length}`)
    }
```

**To Reproduce**

```ts
import { Collection, Entity, LoadStrategy, ManyToOne, MikroORM, OneToMany, PrimaryKey, Property } from '@mikro-orm/core';
import { SqliteDriver } from '@mikro-orm/sqlite';

@Entity()
export class Author {

  @PrimaryKey()
  id!: number;

  @Property({ type: 'varchar' })
  name!: string;

  @OneToMany({
    entity: 'Book',
    mappedBy: 'author',
    eager: true,
    orphanRemoval: true,
  })
  books = new Collection<Book>(this);

}

@Entity()
export class Book {

  @PrimaryKey()
  id!: number;

  @ManyToOne(() => Author)
  author!: Author;

  @OneToMany({
    entity: 'Page',
    mappedBy: 'book',
    eager: true,
    orphanRemoval: true,
  })
  pages = new Collection<Page>(this);

}

@Entity()
export class Page {

  @PrimaryKey()
  id!: number;

  @ManyToOne(() => Book)
  book!: Book;

  @Property({ type: 'varchar' })
  text!: string;

}

describe('GH issue 1126', () => {

  let orm: MikroORM<SqliteDriver>;

  beforeAll(async () => {
    orm = await MikroORM.init({
      type: 'sqlite',
      dbName: ':memory:',
      entities: [Author, Book, Page],
      loadStrategy: LoadStrategy.JOINED,
    });
    await orm.getSchemaGenerator().createSchema();
  });

  afterAll(async () => {
    await orm.close(true);
  });

  test(`GH issue 1126`, async () => {
    const author = new Author();
    author.name = 'John';

    const page = new Page();
    page.text = 'new phone who dis';

    const book = new Book();
    book.pages.set([page]);
    author.books.set([book]);

    await orm.em.persistAndFlush(author);
    orm.em.clear();

    {
      const author = await orm.em.findOneOrFail(Author, 1);
      const book = new Book();
      const oldPage = author.books.getItems()[0].pages.getItems();
      book.pages.set(oldPage);
      author.books.set([book]);
      await orm.em.persistAndFlush(author);
      orm.em.clear();
    }

    {
      const author = await orm.em.findOneOrFail(Author, 1);
      expect(author.books[0].pages).toHaveLength(1);
    }
  });

});
```

**Expected behavior**
I expected the new `author.books[0].pages` Collection to contain the `old_page` entity. I can understand that the ORM is reluctant to point the Page entity to the new Book entity, as this may break the _old_ Book entity. I did not expect the new `book.pages` relationship to be empty, though.

**Versions**

| Dependency | Version |
| - | - |
| node | v14.1.0 |
| typescript | 4.0.5 |
| mikro-orm | 4.2.3 |
| your-driver | 5.0.0 |

**Comment by mivanovaxway** [comment]
Hello @jjhbw, are you sure this really is a bug? 

I mean your Page entity has: ` @ManyToOne(() => Book)`.
To me your example implies that you're trying to have two books with the same pages, but this implies ManyToMany, not ManyToOne. So  basically the only way this might work the way you want is for the old book to lose its pages.
(this sounds complicated because it implies that if there are instances of the old book, they must be tracked and modified and of course, it could be that only some pages and not all have been moved to a new book).

In my opinion, you could easily workaround this by setting the relation on the pages. Ie. get the Page collection and set their parent as the Book.

CC: Hello @B4nan , I am looking for a good Typescript ORM and having used Doctrine a lot in the past I am looking for a similar solution, hence why I am evaluating the issues in the board and trying to see if any of them are deal-breakers. Thanks for the great project.

**Comment by jjhbw** [comment]
@mivanovaxway I don't think so: the Many in the ManyToOne relationship refers to the `Page` in this case. So: many unique pages refer to one book. In my thinking each book has a unique set of pages. Be sure to correct me if my assumptions or understanding of the library are wrong.

Ultimately, I think @B4nan is the best judge as to whether the behaviour described can be considered a bug.

Regarding Mikro-ORM's fitness for production purposes: I'd say **yes**. The identity map model takes some getting used to IMO, especially when you're not working in the typical request-response context of a web application like I am. The optimizations (i.e. efficient SQL) that this pattern enables when working with complex relations is more than worth it, though. 

One piece of advice to help you with your ORM hunt: whatever you do, I would recommend staying away from TypeORM. I really respect the effort that the maintainers put in, and I don't mean to badmouth their work. However, I just want to warn you that that ORM has quite an impressive list of serious issues that remain pretty much unaddressed along with a sprawling scope.

**Comment by B4nan** [comment]
I do consider this as a bug, but it is a bit challaging to get around it. The issue is, that the old book is orpah removed, and that later on triggers cascade delete of the page that is still linked from the old book entity.

**Comment by mivanovaxway** [comment]
Hm, but the orphan removal is optional, right? Can't the old book just become authorless(null)? Or better yet, what if we flush after moving the pages to the new book?

```
        book.pages.set(old_page)
        await em.flush();
        author.books.set([book])
```

**Comment by B4nan** [comment]
Yes it is optional, but in the OP it is enabled on both collections, and it is the root cause of this issue.
