### ISSUE TITLE
MapToPk on M:1 yields no results

### ISSUE THREAD

**Issue by reramjiawan** [mikro-orm/mikro-orm#1128]
**Describe the bug**
mapToPk option returns nothing when its set on M:1 side and its populated from 1:M side

**To Reproduce**
```
import { Collection, Entity, ManyToOne, MikroORM, OneToMany, PrimaryKey } from '@mikro-orm/core';
import { AbstractSqlDriver } from '@mikro-orm/knex';

interface IA {
  id: number;
  entities: Collection<B>;
}

@Entity()
export class B {

  @PrimaryKey()
  id!: number;

  @ManyToOne({ entity: 'A', mapToPk: true }) // Setting mapToPk to false does yield 2 results
  entity!: IA;

}

@Entity()
export class A {

  @PrimaryKey()
  id!: number;

  @OneToMany({ entity: 'B', mappedBy: 'entity' })
  entities = new Collection<B>(this);

}

describe('GH issue 1128', () => {

  let orm: MikroORM<AbstractSqlDriver>;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [A, B],
      dbName: ':memory:',
      type: 'sqlite',
    });
    await orm.getSchemaGenerator().createSchema();
  });

  afterAll(() => orm.close(true));

  test('mapToPk option returns nothing when its set on M:1 side and its populated from 1:M side', async () => {
    const a = orm.em.create(A, {});
    const b1 = orm.em.create(B, {
      entity: a,
    });
    const b2 = orm.em.create(B, {
      entity: a,
    });
    a.entities.add(b1, b2);
    await orm.em.persistAndFlush(a);
    orm.em.clear();

    const entity = await orm.em.findOneOrFail(A, { id: 1 }, { populate: true });
    expect(entity.entities).toHaveLength(2);
  });
});
```

**Expected behavior**
I expected the mapToPk option to work when populating the relation from 1:M side.

**Versions**

| Dependency | Version |
| - | - |
| node | 12.18.4 |
| typescript | 4.0.3 |
| mikro-orm | 4.3.2 |
| mikro-orm/mysql | 4.3.2 |

**Comment by B4nan** [comment]
This is wrong:

```ts
  @ManyToOne({ entity: 'A', mapToPk: true })
  entity!: IA; // using mapToPk means the type will be `number`, not `IA`
```

(but that is not connected to the issue itself)

**Comment by B4nan** [comment]
Fixed in `4.3.3-dev.3`

**Comment by reramjiawan** [comment]
@B4nan I have installed the package for my project and it doesn't work properly. The relation doesn't get mapped to pk seems like mapToPk false and true do the same thing now. So my test is a false positive in that regard.

**Comment by B4nan** [comment]
Hmm your test is also wrong in that it creates the entity with a reference while using `mapToPk`.

```ts
    const a = orm.em.create(A, {});
    const b1 = orm.em.create(B, { entity: a }); // this is wrong, the `B.entity` is not instance of `A`
    const b2 = orm.em.create(B, { entity: a }); // this is wrong, the `B.entity` is not instance of `A`
```

If you really want to use `mapToPk` and want to have `B.entity` as not nullable, you need to first flush the `A` entity to have its PK.

```ts
    const a = orm.em.create(A, {});
    await em.persistAndFlush(a);
    const b1 = orm.em.create(B, { entity: a.id });
    const b2 = orm.em.create(B, { entity: a.id });
    a.entities.add(b1, b2);
    await em.flush(); `a` is already managed, no need to persist again
```

(but again, that itself is enough, there is indeed a bug in the propagation)

**Comment by B4nan** [comment]
Check the [updated test case](https://github.com/mikro-orm/mikro-orm/commit/b38df3e2a1fb2470365569557a0a9ac953dcf11d#diff-9d6a6606e9a5e644da015d02143d145318a9151e65f91503806856b553fa9b32R42), you might want to use explicit transaction to run it all in the same one (otherwise two flushes will result in two transactions). 

Once built, it will be available as `dev.5`
