### ISSUE TITLE
How to model weak entities?

### ISSUE THREAD

**Issue by andnofence** [mikro-orm/mikro-orm#1131]
I'm trying to model the very common scenario of sales orders that contain line items. I've tried this:

```
export abstract class BaseEntity {
  @PrimaryKey({ type: "number" })
  id!: number

  @Property({ type: Date, columnType: "timestamptz" })
  createdAt = new Date()

  @Property({ type: Date, columnType: "timestamptz", onUpdate: () => new Date() })
  updatedAt = new Date()
}

@Entity()
export class SalesOrder extends BaseEntity {
  @Property({ type: "number", nullable: true })
  invoiceId?: number

  @OneToMany(() => SalesOrderLine, (line) => line.order)
  lines = new Collection<SalesOrderLine>(this)
}

@Entity()
export class SalesOrderLine {
  //@PrimaryKey()
  @PrimaryKey({ type: "number", columnType: "integer" })
  lineNumber: number

  @Property({ type: "string" })
  itemCode: string

  @Property({ type: "string" })
  itemDescription: string

  @Property({ type: "number", columnType: "integer" })
  itemQuantity: number

  @Property({ type: "number", columnType: "decimal" })
  itemPrice: number

  @Property({ persist: false })
  get linePrice() {
    return this.itemQuantity * this.itemPrice
  }

  @PrimaryKey()
  //@ManyToOne(() => SalesOrder)
  order: Reference<SalesOrder>

  constructor(lineNumber: number, itemCode: string, itemDescription: string, itemQuantity: number, itemPrice: number, order: Reference<SalesOrder>) {
    this.lineNumber = lineNumber
    this.itemCode = itemCode
    this.itemDescription = itemDescription
    this.itemQuantity = itemQuantity
    this.itemPrice = itemPrice
    this.order = order
  }

}
```

The thing about weak entities like the sales order line here is that they don't have their own identity, instead a sales order line is identified by the combination of the containing sales order id and the line number.

But I'm struggling with two things:

1. The documentation doesn't explain how to instantiate a class like SalesOrder. It doesn't seem like I'm supposed to create a collection myself? I was expecting to be able to pass an array of SalesOrderLine but have not been able to do so. I think it would be good if the documentation on collections contained some examples.
2. I'm not sure it's possible to define a @PrimaryKey on a Reference like this? I'm not even sure that the Reference is the correct solution which is why I've commented out the first attempt of `@ManyToOne` since you can't have both `@PrimaryKey` and `@ManyToOne`.

**What I've tried:**

1. Creating a SalesOrder constructor like this:

```
constructor(invoiceId: number, lines: SalesOrderLine[]) {
    super()
    this.invoiceId = invoiceId
    this.lines.add(new SalesOrderLine(1, "a", "a", 2, 23, wrap(this).toReference())
  }
```

But this gives a type error on the order argument to new SalesOrderLine

```
Argument of type 'SalesOrder & { lines: LoadedCollection<SalesOrderLine, SalesOrderLine>; }' is not assignable to parameter of type 'Reference<SalesOrder>'.
  Type 'SalesOrder & { lines: LoadedCollection<SalesOrderLine, SalesOrderLine>; }' is missing the following properties from type 'Reference<SalesOrder>': entity, load, set, unwrap, and 5 more.
```

I also tried to change `SalesOrderLine` entity like this:

```
@PrimaryKey()
  order: IdentifiedReference<SalesOrder>

  constructor(lineNumber: number, itemCode: string, itemDescription: string, itemQuantity: number, itemPrice: number, order: SalesOrder) {
    this.lineNumber = lineNumber
    this.itemCode = itemCode
    this.itemDescription = itemDescription
    this.itemQuantity = itemQuantity
    this.itemPrice = itemPrice
    this.order = Reference.create(order)
  }
```

But now I get two errors:

```
MetadataError: SalesOrder.lines has wrong 'mappedBy' reference type: object instead of SalesOrder
```

And this:

```
TypeError: Cannot read property 'primaryKeys' of undefined

      43 |     this.itemQuantity = itemQuantity
      44 |     this.itemPrice = itemPrice
    > 45 |     this.order = Reference.create(order)
         |                            ^
```

Is what I'm trying perhaps not possible with Mikro-ORM? Will I just have to create a regular id column for SalesOrderLine too?

**Comment by B4nan** [comment]
You should use `@ManyToOne` with `primary: true`, as described here:

https://mikro-orm.io/docs/composite-keys#identity-through-foreign-entities

If you want to use the `Reference` wrapper, you either need to set `wrappedReference` or use ts-morph that does it automatically: 

https://mikro-orm.io/docs/metadata-providers/#tsmorphmetadataprovider
https://mikro-orm.io/docs/metadata-providers/#limitations-and-requirements

```ts
  @ManyToOne({ entity: () => SalesOrder, wrappedReference: true, primary: true })
  order: IdentifiedReference<SalesOrder>
```

> TypeError: Cannot read property 'primaryKeys' of undefined

This is caused by using not discovered entity (or not entity instance) as parameter to the `Reference.create()` most probably. 

> Argument of type 'SalesOrder & { lines: LoadedCollection<SalesOrderLine, SalesOrderLine>; }' is not assignable to parameter of type 'Reference<SalesOrder>'.

And this means you are trying to assign a `Reference` instance where it should not be (where you use naked entity and not the `Reference` wrapper).

**Comment by andnofence** [comment]
Thanks for responding so quickly @B4nan, much appreciated!

I tried the `primary: true` config, but now my `SalesOrder` constructor fails:

```
@Entity()
export class SalesOrder extends BaseEntity {
  @Property({ type: "number", nullable: true })
  invoiceId?: number

  @OneToMany(() => SalesOrderLine, (line) => line.order)
  lines = new Collection<SalesOrderLine>(this)

  constructor(invoiceId: number, lines: Omit<SalesOrderLine, "order" | "linePrice">[]) {
    super()
    this.invoiceId = invoiceId
    console.log("lines before", this.lines)
    lines.forEach(l => this.lines.add(new SalesOrderLine(l.lineNumber, l.itemCode, l.itemDescription, l.itemQuantity, l.itemPrice, this)))
    console.log("lines after", this.lines)
    console.log("lines", this.lines.getItems())
  }
}
```

Prints:

```
    TypeError: Cannot read property 'properties' of undefined

      21 |     this.invoiceId = invoiceId
      22 |     console.log("lines before", this.lines)
    > 23 |     this.lines.add(new SalesOrderLine(1, "a", "a", 2, 23, this))
```

And the console.log line is printed:

```
  console.log
    lines before Collection { initialized: true, dirty: false }
```

I've tried lots of different things but I'm unable to populate the `SalesOrderLine` collection.

**Comment by B4nan** [comment]
Try moving that line outside of the constructor. I'd expect issues with propagation, as by adding to the 1:m collection, the m:1 side is updated automatically, but your entity is not yet fully created (constructor did not finished) when you call the `coll.add()` method. 

If that is the real problem, then one way around that is to use static factory method (e.g. `SalesOrder.create()`).

**Comment by andnofence** [comment]
I got it working, but it doesn't feel right:

```
    const salesOrder = repository.create({})
    const salesOrderLine = new SalesOrderLine(1, "A", "B", 3, 100, salesOrder)
    const sol = em.create<SalesOrderLine>("SalesOrderLine", { lineNumber: 1, itemCode: "COLLARN", itemDescription: "Normal Collar", itemQuantity: 3, itemPrice: 2000 })
    salesOrder.lines.add(sol)
    console.log("salesOrder", salesOrder)
    await repository.persistAndFlush(salesOrder)
```

I'm supposed to be able to just new up the objects without having to think about the EntityManager much right? But here the `em` is the EntityManager. (`repository`, as you probably guessed, is `EntityRepository<SalesOrder>`).

But I tried another thing that might offer a clue and has me wondering if there's something I've gotten completely wrong. I tried something that's more in line with the Books example in the documentation:

```
    const so = new SalesOrder()
    const sol1 = new SalesOrderLine(1, "A", "B", 3, 100, so)
    const sol2 = new SalesOrderLine(1, "A", "B", 3, 100, so)
    console.log("so", so)
    await repository.persistAndFlush(so)
    console.log("so after persist", so)
```

Which gives:

```
ValidationError: Trying to persist not discovered entity of type SalesOrder. Entity with this name was discovered, but not the prototype you are passing to the ORM. If using EntitySchema, be sure to point to the implementation via `class`.

      63 |     const sol2 = new SalesOrderLine(1, "A", "B", 3, 100, so)
      64 |     console.log("so", so)
    > 65 |     await repository.persistAndFlush(so)
```

My understanding is that as long as I use normal classes and @Entity and other annotations I should be able to just create objects using normal constructor, whereas if I use `EntitySchema` I'll have to use the static `create()` method to create the objects?

**Comment by B4nan** [comment]
> I'm supposed to be able to just new up the objects without having to think about the EntityManager much right? But here the em is the EntityManager. (repository, as you probably guessed, is EntityRepository<SalesOrder>).

I am not sure what you are trying to say by that. Using `em.create()` is pretty much the same as using ctor. Your previous issue was not caused by usage of ctor, but by the fact that you were instantiating new entities inside ctor and passing the `this` of the currently constructed entity into those (at least that was my guess). As I mentioned, there is automatic propagation in place, which won't work if you try to trigger it from inside the ctor. But for sure it could be at least handled gracefully instead of throwing... 

> My understanding is that as long as I use normal classes and @entity and other annotations I should be able to just create objects using normal constructor, whereas if I use EntitySchema I'll have to use the static create() method to create the objects?

If you are using `EntitySchema` with regular classes, you can use the ctors as usual. That error says you are using wrong prototype of the entity, not discovered one (so not the same one as you specify in the `EntitySchema.class` property). If you are using folder based discovery, you might have something misconfigured (e.g. using `tsNode` toggle explicitly, or not specifying the path to TS entities via `entitiesTs`).

**Comment by andnofence** [comment]
Ok, to be clear I'm not using EntitySchema. When I read the docs I get the impression that you only need to use that if you want to programmatically define the entities, but I prefer the annotation approach.

My comment about being able "new up the objects" was to say that one of the things I really like about Mikro-ORM is that I just deal with plain classes and that I can create them without thinking much about the fact that I'm really dealing with an ORM. But that abstraction breaks down a bit when I can't just pass in an array of `SalesOrderLine` instances into my `SalesOrder` as that's the obvious way to create it. But all abstractions are leaky, it's just the way it is. So in this case I guess the improvement here would be to give a better error message, and perhaps more importantly, to have examples in the Collections section of the documentation on how to actually create and populate the collections.

My config is this:

```
const config = {
  entities: [BaseEntity, Customer, SalesOrder, SalesOrderLine],
  debug: true,
  dbName: "yukon",
  type: "postgresql",
  port: 54320,
  logger: logger.log.bind(logger),
} as Options
```

When I read https://mikro-orm.io/docs/configuration/ I get the understanding that the `entityTs` is only necessary if doing folder based discovery? At least adding it didn't help.

Any ideas on how to debug this (other than the `debug: true` option which doesn't seem to make much of a difference?)

**Comment by B4nan** [comment]
> But that abstraction breaks down a bit when I can't just pass in an array of SalesOrderLine instances into my SalesOrder as that's the obvious way to create it. 

But you are not doing that in your code, you are passing array of DTOs to your ctor and create the `SalesOrderLine` inside, and that is (I believe) the problem.

> When I read https://mikro-orm.io/docs/configuration/ I get the understanding that the entityTs is only necessary if doing folder based discovery? At least adding it didn't help.

Correct, the config is fine like this. So you had that `ValidationError: Trying to persist not discovered entity of type SalesOrder.` with such config? Are you sure you initialize the ORM before you work with the entities? (but that probably also won't be the issue, as the error says such entity name is known, just the prototype is wrong, so discovery did finish by that time).

That error is basically saying you have multiple `SalesOrder` entities in your app, one was discovered, but it is not the same one as you are using in the runtime.

`debug: true` should enable logs on discovery, from that you should see what entities gets discovered (and from what paths/files, when using folder based discovery). 

You can try `const meta = em.getMetadata().get('SalesOrder')` to get the metadata of that entity, there you have `meta.class` and `meta.prototype`, they are pointing to the discovered class, and it is not the same one as you are using in the test. You can try `console.log(meta.class === SalesOrder)` to see. It needs to give you true, otherwise you did something wrong.

**Comment by andnofence** [comment]
Thanks @B4nan, you are indeed correct, `console.log(meta.class === SalesOrder)` gives false.

> But you are not doing that in your code, you are passing array of DTOs to your ctor and create the SalesOrderLine inside, and that is (I believe) the problem.

Yes, that was imprecise of me. But passing the DTO is kinda what I want because it feels like the most obvious interface.

But I was trying to combine Nest.js and MikroORM. I decided to go back to square one and start a new project with nothing but MikroORM, and everything immediately fell into place. So it seems this has something to do about my Nest.js setup. I suspect I have multiple instances of MikroORM because after adding logging on the service constructors where the repository is being injected I see this:

```
    CONSTRUCTED SqlEntityRepository {
        _em: [EntityManager<3>],
        entityName: 'SalesOrder'
      }

      at new SalesOrderService (sales-order/sales-order.service.ts:12:13)
          at async Promise.all (index 3)

    console.log
      CONSTRUCTED SqlEntityRepository {
        _em: [EntityManager<4>],
        entityName: 'SalesOrder'
      }
```

The fact that it's being called multiple times and with EntityManager<3> and EntityManager<4> has me thinking something isn't right. I tried to follow the section on Nest.JS in the documentation but I'm new to both frameworks so there's a lot of things that can go wrong.

But back to MikroORM, this constructor now works:

```
constructor(invoiceId: number, ls: Omit<SalesOrderLine, "salesOrder" | "linePrice">[]) {
    super()
    this.invoiceId = invoiceId
    ls.forEach(l => this.lines.add(new SalesOrderLine(l.lineNumber, l.itemCode, l.itemDescription, l.itemQuantity, l.itemPrice, this)))
  }
```

which is great!

So now I just have to figure out what's wrong about my Nest.js setup.

**Comment by B4nan** [comment]
Weird, the EM inside DI should be singleton (by default) and it should be the global one, with id 1. So you are using the `@mikro-orm/nestjs` or a custom setup? This looks like you use transitive scope or something like that.

**Comment by andnofence** [comment]
I've tried to follow this: https://mikro-orm.io/docs/usage-with-nestjs

But frankly my head is spinning from trying to wrap it around all of it this at the same time, I think I'll bail on Nest.js for now and instead just go with a straight express service using MikroORM as my ORM.

**Comment by B4nan** [comment]
Maybe take a look at the example projects:

https://github.com/mikro-orm/nestjs-realworld-example-app
https://github.com/mikro-orm/nestjs-example-app

**Comment by andnofence** [comment]
Thanks @B4nan, the realworld one was new to me, I'll have a look. I'll close this as my original question has been well answered.
