### ISSUE TITLE
Smart populate does not load all data

### ISSUE THREAD

**Issue by reramjiawan** [mikro-orm/mikro-orm#1134]
**Describe the bug**
According to docs smart populate can load large nested relations. In this case it does not fetch all nested data.

**To Reproduce**
```
import { Entity, ManyToOne, MikroORM, OneToMany, OneToOne, PrimaryKey, Property } from '@mikro-orm/core';
import { AbstractSqlDriver } from '@mikro-orm/knex';
import { v4 } from 'uuid';

@Entity()
export class A {

  @PrimaryKey()
  id: string = v4();

  @Property({ unique: true })
  value!: string;

}

@Entity()
export class T {

  @PrimaryKey()
  id: string = v4();

  @Property({ unique: true })
  value!: string;

}

@Entity()
export class I {

  @OneToOne({ entity: 'V', joinColumn: 'id', primary: true, mapToPk: true })
  id!: string;

  @Property({ unique: true })
  value!: number;

}

@Entity()
export class V {

  @PrimaryKey()
  id: string = v4();

  @OneToOne({ entity: 'I', mappedBy: 'id' })
  i!: I;

}

@Entity()
export class E {

  @PrimaryKey()
  id: string = v4();

  @ManyToOne({ entity: 'A' })
  a!: A;

  @ManyToOne({ entity: 'T'  })
  t!: T;

  @ManyToOne({ entity: 'V'   })
  v!: V;

}

@Entity()
export class M {

  @PrimaryKey()
  id: string = v4();

  @ManyToOne({ entity: 'N', hidden: true })
  n!: string;

  @ManyToOne({ entity: 'E' })
  e!: E;

}

@Entity()
export class N {

  @OneToOne({ entity: 'E', joinColumn: 'id', primary: true })
  id!: E;

  @ManyToOne({ entity: 'A' })
  a!: A;

  @OneToMany({ entity: 'M', mappedBy: 'n' })
  m!: M[];

}

describe('GH issue 1124', () => {

  let orm: MikroORM<AbstractSqlDriver>;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [
        E,
        T,
        A,
        V,
        I,
        N,
        M,
      ],
      dbName: ':memory:',
      type: 'sqlite',
    });
    await orm.getSchemaGenerator().createSchema();
  });

  afterAll(() => orm.close(true));

  test('Load nested data with smart populate', async () => {
    const a = orm.em.create(A, {
      value: 'A',
    });

    const t = orm.em.create(T, {
      value: 'T',
    });

    const v = orm.em.create(V, {});

    const i = orm.em.create(I, {
      id: v,
      value: 5,
    });

    const a2 = orm.em.create(A, {
      value: 'A2',
    });

    const t2 = orm.em.create(T, {
      value: 'T2',
    });

    const v2 = orm.em.create(V, {});

    const i2 = orm.em.create(I, {
      id: v2,
      value: 6,
    });

    const e = orm.em.create(E, {
      a,
      t,
      v,
    });

    const e2 = orm.em.create(E, {
      a: a2,
      t: t2,
      v: v2,
    });

    const n = orm.em.create(N, {
      id: e,
      a,
    });

    const m = orm.em.create(M, {
      n,
      e: e2,
    });

    await orm.em.persistAndFlush([i, i2, m]);
    orm.em.clear();

    const entity = await orm.em.getRepository(N).findAll({ populate: true });

    console.log(JSON.stringify(entity, null, 2));

    // The data from entity M is not populated why?
    expect(entity[0].m[0].e).toMatchObject({
      a: {
        value: 'A2',
      },
      t: {
        value: 'T2',
      },
      v: {
        i: {
          value: 6,
        },
      },
    });
  });
});

```

**Expected behavior**
I expect smart populate to load all neccesary data when setting eager on true it does work.

**Versions**

| Dependency | Version |
| - | - |
| node | 12.18.4 |
| typescript | 4.0.3 |
| mikro-orm | 4.3.2 |
| mikro-orm/sqlite | 4.3.2 |

**Comment by B4nan** [comment]
This is wrong,  you cannot map to array of entities, it needs to be `Collection`:

```ts
  @OneToMany({ entity: 'B', mappedBy: 'a' })
  attributes!: B[]; // should be `attributes = new Collection<B>(this);
```

And more importantly this is wrong:

```ts
  @OneToOne({ entity: 'C', joinColumn: 'id', primary: true })
  id: string = v4(); // you are using 1:1 here, the type is `C`, not `string` and you can't just create some UUID for the value
```

When I fix those and explicitly set the `id` to `c` your test is passing:

```ts
const d = orm.em.create(D, { value: 'foo' });
const c = orm.em.create(C, { d });
const a = orm.em.create(A, { id: c });
const b = orm.em.create(B, { a, c });
await orm.em.persistAndFlush(b);
orm.em.clear();

const entity = await orm.em.getRepository(A).findAll({ populate: true });
expect(entity[0].attributes[0].c).toMatchObject({
d: { value: 'foo' },
});
```

**Comment by reramjiawan** [comment]
@B4nan I have updated my reproducable could you please have another look?

**Comment by B4nan** [comment]
Do you really need that much entities to reproduce it? It makes it much harder to understand.

**Comment by reramjiawan** [comment]
Sorry its a EAV design 😅. It boils down to that while entity N does load all info from entity E because of 1:1. Entity M does not load its info from entity E when I set eager to true then it will.

**Comment by B4nan** [comment]
Neither `eiger: true`, not `populate: true`, will follow cycles. You are testing very deep relation, so I'd guess this will be the problem.

**Comment by B4nan** [comment]
This test case had the same issue as the other one, this is how it should look like instead:

```ts
    const a = orm.em.create(A, { value: 'A' });
    const t = orm.em.create(T, { value: 'T' });
    const v = orm.em.create(V, {});
    const a2 = orm.em.create(A, { value: 'A2' });
    const t2 = orm.em.create(T, { value: 'T2' });
    const v2 = orm.em.create(V, {});
    const e = orm.em.create(E, { a, t, v });
    const e2 = orm.em.create(E, { a: a2, t: t2, v: v2 });
    const n = orm.em.create(N, { id: e, a });
    const m = orm.em.create(M, { n, e: e2 });
    await orm.em.persistAndFlush([m, n]);

    const i = orm.em.create(I, { id: v.id, value: 5 }); // we need to pass the PK value here
    const i2 = orm.em.create(I, { id: v2.id, value: 6 }); //  we need to pass the PK value here
    await orm.em.persistAndFlush([i, i2]);

    orm.em.clear();
```

Also note that you have the collection wrong again, it needs to be:

```ts
  @OneToMany({ entity: 'M', mappedBy: 'n' })
  m = new Collection<M>(this);
```

(again, it won't help with the population, but as it was before, it was probably not even persisting things correctly)

**Comment by reramjiawan** [comment]
Thanks for the tips. In my project I do not seem to have any persisting issues however. Database seems to be properly populated. With the relation decorator the entity property seems to be what triggers proper persisting so weither you pass id or a fully fledged entity seems to not matter. Same goes for not using collection ( could you touch on why using collection is important even if you dont use the build in methods? ). Perhaps it would be good to make it more dummy proof and just throw a error if you use mapToPk and things of that nature that you have to pass a id instead of a entity to help/guide the developer? Because yes you are right it shows intent and what you can expect so it does make sense to just pass the id with mapToPk on true but it works just fine even if your property type is off ( since you already said in the decorator this is the entity ).

**Comment by reramjiawan** [comment]
I actually got a good use case for using Collection after spending some more time on MikoORM. So forget what I said in my previous comment. It's nice to persist & flush at the parent and not on every child if not needed.

**Comment by B4nan** [comment]
> could you touch on why using collection is important even if you dont use the build in methods?

Especially because you are not using them, things will almost certainly break. The collection methods are managing `Collection.items` and `Collection.snapshot` properties that are used for persisting and diffing the collection. If you have array there, nothing can work properly. Same applies for propagation and orphan removal, those will never work if you do not have the `Collection` there. It might be working for you, because you do not specify the default value, so the ORM most probably just ignores the property. And loaded entity will have a `Collection` instance there automatically, whether you define it as an array or not - this works based on the decorator type, not TS type or property initializer.
