### ISSUE TITLE
Cli#debug folder discovery

### ISSUE THREAD

**Issue by elmpp** [mikro-orm/mikro-orm#1139]
**Describe the bug**
Running `yarn mikro-orm debug` reports the `entities` array incorrectly.

**Stack trace**
See picture (notice the console.log `paths :>>  [ './src/database/entity/main/*', './src/database/entity/ci/*' ]` is within MetaDiscovery#findEntities)
Note that there are is no dist folder and entities are found so am confident that `debug` is erroneous

**To Reproduce**
 - mikro-orm.config.ts - https://hastebin.com/cobukalufo
 - package.json:
```
{
  scripts: {
     "mikro": "mikro-orm"
  },
  "devDependencies": {
    "@mikro-orm/cli": "^4.3.2",
    "ts-node": "^9.0.0",
    "typescript": "4.0.2"
  },
  "dependencies": {
    "@mikro-orm/core": "4.3.2",
    "@mikro-orm/reflection": "4.3.2",
    "@mikro-orm/sqlite": "4.3.2",
    "tslib": "^1.13.0"
  },
  ...
  "mikro-orm": {
    "useTsNode": true,
    "configPaths": [
      "./src/database/mikro-orm.config.ts"
    ]
  }
```

**Expected behavior**
expect the debug command to report `will use the 'entitiesTs' array`

**Additional context**
<img width="722" alt="Screenshot 2020-11-28 at 12 34 08" src="https://user-images.githubusercontent.com/864612/100514565-0681bd80-3176-11eb-83d0-8c621925d2cc.png">

**Versions**

| Dependency | Version |
| - | - |
| node | 14.15.0 |
| typescript | 4.0.2 |
| mikro-orm | 4.3.2 |
| your-driver | ? |

**Comment by elmpp** [comment]
<img width="827" alt="Screenshot 2020-11-28 at 12 39 38" src="https://user-images.githubusercontent.com/864612/100514638-cff87280-3176-11eb-964b-0a44c3e68764.png">

**Comment by B4nan** [comment]
Nope, you have it wrong. Dont use __dirname in the baseDir option, that is almost never what you want, that variable has different value when you run via ts-node.

**Comment by elmpp** [comment]
I tried it without also. This ticket isn't about mis configuration - just
that the debug cli command reports the entity path differently to what's in
use under the hood. 🙃

**Comment by B4nan** [comment]
I see, it always reports the `entities` paths (so the ones for compiled JS files) - but the paths are correct, you just expect the `entitiesTs` paths to TS files, right? It should report both ideally. 

Note that you should not set `tsNode: true` in most cases, that is meant for development and tests, it needs to be set to `false` when running compiled code (it could have performance implications, other than that it should be technically ok).

**Comment by elmpp** [comment]
yeah, exactly as you mention. This debug was initially a nice help (spent days over the years on this with TypeORM).

**Comment by B4nan** [comment]
Will change it so it will print both sets of paths, and encode the `tsNode` value to the sentence too (`will` vs `could`):

```
 - will use `entities` array (contains 0 references and 1 paths)
   - /.../dist/entities (found)
 - could use `entitiesTs` array (contains 0 references and 1 paths)
   - /.../src/entities (found)
```

(the value should be dynamic, ts-node is detected automatically)

**Comment by elmpp** [comment]
But when ran with ts-node it would output:

 - will use `entitiesTs` array (contains 0 references and 1 paths)
   - /.../src/entities (found)
 - could use `entities` array (contains 0 references and 1 paths)
   - /.../dist/entities (found)

**Comment by B4nan** [comment]
Yes, when you run the app. But this is not dependent on how CLI is executed (it uses ts-node based on the config from `package.json`). So it will be different only if you manually specify the value (usually it should be dynamic as I mentioned before).

Feel free to suggest better wording, maybe we should drop the `will/could` altogether.

**Comment by elmpp** [comment]
Ah ok - this is the context i've been missing - i was using the cli to prove my setup which i think would not be uncommon. 

Only thing to add from my pov would then be to preface that text. e.g.

useTsNode found (true)
 - will use entitiesTs array (contains 0 references and 1 paths)
/.../src/entities (found)
 - could use entities array (contains 0 references and 1 paths)
/.../dist/entities (found)

**Comment by elmpp** [comment]
Thanks!
