### ISSUE TITLE
Tree Structure in MikroORM

### ISSUE THREAD

**Issue by totalard** [mikro-orm/mikro-orm#1149]
**Is your feature request related to a problem? Please describe.**
**Adjacency list
Nested set
Materialized Path (aka Path Enumeration)
Closure table**

Is these Possible.. Mianly the Adjuscency One.

**Comment by B4nan** [comment]
Possible? Yes. Supported? Nope, nothing out of box.

Will close this, if you want to propose a feature, you need to describe it, pick one instead of 4, and don't ignore the issue template.
