### ISSUE TITLE
Support running tests via ts-jest

### ISSUE THREAD

**Issue by Ezard** [mikro-orm/mikro-orm#1151]
**Is your feature request related to a problem? Please describe.**
Currently, MikroORM only supports Typescript config files if the process is being run through `ts-node`

**Describe the solution you'd like**
Typescript config files should be able to be used when running tests via `ts-jest`

**Describe alternatives you've considered**
Our current alternative is to transpile to project to Javascript, then copy across our config file (which is now Javascript) to the source directory

**Additional context**
I believe it should be possible to determine if ts-jest is being used by (a) checking if the current process is being run by Jest (`process.argv[1].includes('jest-worker')`), and then checking if "ts-jest" is present as a transformer in any Jest config (withing `package.json` or within `jest.config.json`). Just like with `ts-node`, there should also be an option in the MikroORM config within `package.json` which is required to be enabled by users before this check happens, to avoid messing up any existing configuration that users have

I'm happy to work on a PR, but let me know if anyone knows of a better way of achieving this functionality

**Comment by B4nan** [comment]
As discussed in the PR, for tests it should be just about adding `tsNode: true` to the ORM config.
