### ISSUE TITLE
Strange field cache behaviour using MongoDB + .find()

### ISSUE THREAD

**Issue by endel** [mikro-orm/mikro-orm#1159]
**Describe the bug**
A strange cache is going on when I'm using an `EntityRepository<T>`'s `.find()` providing custom `fields`.

It seems the `fields` are cached for the `EntityRepository` the first time `.find()` is called, and never changed after. 

**To Reproduce**
I've recorded a video demonstrating the issue here: https://drive.google.com/file/d/1ytQP3UuPgvfrhFVgwUhpYpSQzbUqtMKK/view?usp=sharing

In the video you can see:
- A URL query string is used to determine which `fields` are going to be used
- I open the URL using query string `"league"`
- The query string is changed to `"ranked"`, having no effect on the `fields` argument 
- I restart the server (thus clearing the "cache") and refresh the page still using `"ranked"` query string, and it displays correctly (changing back to `"league"` has no effect over the `fields`)

(I'm not using any kind of caching on my side)

**Expected behavior**
The `fields` should have changed

**Additional context**

I've used a global User Repository for the video, and later tried to retrieve a Repository for each HTTP request via `DI.orm.em.getRepository(User)` but the problem persisted

**Versions**

| Dependency | Version |
| - | - |
| node | `14.3.0` |
| typescript | `4.0.5` |
| mikro-orm | `4.3.2` |
| your-driver | `mongodb` |

**Comment by B4nan** [comment]
> It seems the fields are cached for the EntityRepository the first time .find() is called, and never changed after.

Not just fields, the whole entity is stored in identity map. If you select it for the first time with limited `fields`, you will have partial entity there. You can use `refresh: true` in `FindOptions` to force reload it. This is one of the reasons why each request needs to have its own identity map (aka request context).

https://mikro-orm.io/docs/identity-map

**Comment by endel** [comment]
Thanks for the quick reply @B4nan, I've totally missed this. It's working perfectly now! 🥳
