### ISSUE TITLE
[Fix] Embedded prefix

### ISSUE THREAD

**Issue by dvlalex** [mikro-orm/mikro-orm#1169]
**Describe the bug**
When setting an embeddable with "prefix: false", its properties overwrites the parent entity.

**To Reproduce**
Test available [here](https://github.com/dvlalex/mikro-orm/blob/GH1169/tests/issues/GH1169.test.ts)

**Expected behavior**
The combination { prefix: false, object: false } should not be allowed for this specific reason. There's no benefit of having no prefix for embeddables when they aren't objects.

**Versions**

| Dependency | Version |
| - | - |
| node | 13.13.0 |
| typescript | 4.1.2 |
| mikro-orm | 4.3.0 |

**Comment by B4nan** [comment]
Well, we can of course throw in such situation, but this is correct behaviour on its own. I don't agree that it should not be allowed, but the additional validation makes sense.

**Comment by dvlalex** [comment]
Makes sense. Do you want me to take care of this?

**Comment by B4nan** [comment]
Sure, that would be great. I guess the validation should be done in `MetadataDiscover.initEmbeddables()` (and it should be instance of `MetadataError`).
