### ISSUE TITLE
OrderBy ignored when doing leftJoinAndSelect

### ISSUE THREAD

**Issue by AzariasB** [mikro-orm/mikro-orm#1171]
**Describe the bug**
When using the query builder, and doing a `leftJoinAndSelect` followed by a `orderBy`, the order is not taken into account (seems like it's then ordered by ids instead)

**Stack trace**
```
// No stack trace, just a bad result
```

**To Reproduce**
1. Create a QueryBuilder
2. Do a left join and select with it
3. Add an orderBy clause
4. Get the result list

**[Here's a reproduction repo](https://github.com/AzariasB/mikro-orm/blob/042a24a246c4c15fb48ff13f19a62323a7d28c2c/tests/issues/GH1171.test.ts)**

**Expected behavior**
When doing an `orderby`, the order of the resulting list should be the same, whether there is a join or not.

**Additional context**
The current workaround for this issue is to use the sort method, but it can be costly for long lists

**Versions**

| Dependency | Version |
| - | - |
| node | 14.15 |
| typescript | 4.1.2 |
| mikro-orm | 4.3.3 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
Interesting, another issue there is that `.leftJoinAndSelect('b', 'b')` is not populating the `b` property - that is because of the same table and alias name apparently, as `.leftJoinAndSelect('b', 'b0')` fixes that particular problem.

**Comment by AzariasB** [comment]
Well that's two birds with one stone for you :)

**Comment by AzariasB** [comment]
As always, thank your very much for the excellent work you put in this awesome ORM :+1:
