### ISSUE TITLE
[Feature]: Implement afterTransactionCompletion, afterCommitCreate, et al similar to Hibernate counterparts

### ISSUE THREAD

**Issue by rhyek** [mikro-orm/mikro-orm#1175]
**Is your feature request related to a problem? Please describe.**
Our project is making use of explicit transactions with explicit use of `begin`, `commit`, and `rollback` methods. We need to register hook handlers for `afterFlush`, `afterCreate`, etc, to run some business logic that will notify users and/or integrated systems of such events.
Our problem as of now is that these are run after UoW commit phase and not transaction commit phase so in the case where a `commit` fails on the database side (deferred constraint checks, concurrency problems, etc), it is important to have a way from those hook handlers to be aware of this and therefore not execute their code *OR* have separate hooks that are guaranteed to only run on successful transactions. Currently those hooks are executed regardless and this presents a serious problem for our use case.

**Describe the solution you'd like**
Implement hooks similar to [afterTransactionCompleted](https://docs.jboss.org/hibernate/orm/5.2/javadocs/org/hibernate/EmptyInterceptor.html#afterTransactionCompletion-org.hibernate.Transaction-) and events such as [POST_COMMIT_INSERT](https://docs.jboss.org/hibernate/orm/5.2/javadocs/org/hibernate/event/spi/EventType.html#POST_COMMIT_INSERT), et al, which are part of the Hibernate ORM (I understand this project is inspired in part by it) so that we can make use of those hooks instead of the current ones. The behavior of the current ones would not be altered.

**Describe alternatives you've considered**
Our team has concluded that the only way for us to guarantee our business logic is run on successful transactions only is to make use of the CDC (Change Data Capture) functionalities of our preferred database in conjunction with perhaps something like Kafka Connect by way of a Debezium Kafka Source Connector and then additionally a Kafka Consumer that would execute our aforementioned business logic. This seems overkill to us.

**Additional context**
I had previously opened an issue regarding our findings: #1160. I am willing to write a PR implementing this feature, but would first like to hear from @B4nan if that is something that would be taken into consideration or not.

**Comment by rhyek** [comment]
The test suite referenced in #1160 had a few issues where some tests where not written correctly and I was not `await`ing some `expect`s.

With that fixed, I can see that actually more (and some new specific) test cases fail:

![image](https://user-images.githubusercontent.com/702922/101661390-d526ae80-3a0d-11eb-885c-2105a20a9f61.png)

So as you can see, in the case of `commit` statement failures, `afterCreate` and `afterFlush` are actually being called in the case of explicit transactions with `transactional()`, and `afterCreate` (but not `afterFlush`) in the case of implicit transactions.

After updating to `4.3.4-dev.8` (which includes #1177) 1 test cases now succeeds:

![image](https://user-images.githubusercontent.com/702922/101662167-c987b780-3a0e-11eb-93ce-298b9ad98b0d.png)

**Comment by kdi-1** [comment]
These hooks exist in other Node.js libraries  - 
[TypeORM](https://typeorm.io/#/listeners-and-subscribers/what-is-a-subscriber) - **afterTransactionCommit** and **afterTransactionRollback**
[Sequelize](https://sequelize.org/v5/manual/transactions.html#after-commit-hook) - **afterCommit**
It would be great to have something similar in MikroORM

**Comment by rhyek** [comment]
I am currently working on a PR for this. Will have something very soon.
