### ISSUE TITLE
Error when handle decorator @PrimaryKey

### ISSUE THREAD

**Issue by chaoyangnz** [mikro-orm/mikro-orm#118]
`TypeError: Cannot read property '1' of null
    at Function.lookupPathFromDecorator (/Users/chao.yang/Work/stuff-content/node_modules/mikro-orm/dist/utils/Utils.js:177:78)
    at /Users/chao.yang/Work/stuff-content/node_modules/mikro-orm/dist/decorators/PrimaryKey.js:12:23
    at DecorateProperty (/Users/chao.yang/Work/stuff-content/node_modules/reflect-metadata/Reflect.js:553:33)
`

OS: Mac OSX
Node: 10.x.x
Framework: NestJS
DB: Postgres

**Comment by B4nan** [comment]
Could you please add `console.log(stack, line);` to `node_modules/mikro-orm/dist/utils/Utils.js` file right before this error occurred (line 176 I guess) and pass the output here?

**Comment by chaoyangnz** [comment]
could you give me a link about the bug of `tslib` you mentioned?

**Comment by B4nan** [comment]
issue #100, it was fixed in v2.7.6

**Comment by B4nan** [comment]
Any updates on this one?

**Comment by B4nan** [comment]
I will close this one as resolved, let me know if you still have problems and I will reopen it, but be sure to include the debug output I was asking for as well as your ORM version.

**Comment by CyriacBr** [comment]
@B4nan I was working on a lib based on mikro-orm just now and the cli couldn't generate the cache. I had the same issue as @chaoyangnz .  
It appears that the `lookupFromDecorator` expect each stack trace line to contain the file path inside parentheses. However, on my repo that wasn't the case, no idea why.  
Check https://github.com/mikro-orm/mikro-orm/pull/378. This is working for me.
