### ISSUE TITLE
Can I use entity.columnId?

### ISSUE THREAD

**Issue by SDAdham** [mikro-orm/mikro-orm#1210]
**Is your feature request related to a problem? Please describe.**
Is it possible to use `entity.columnId` instead of `entity.table.id`?
I tried to do this but it didn't work with me, can you please help?

**Describe the solution you'd like**

**Describe alternatives you've considered**
For me to just set an id, I have to do this:
```
entity.someColumn = 'xyz';
entity.table = new Table();
entity.table.id = 2; // to link the row to another row of another table.
```

**Additional context**
Add any other context about the feature request here.

**Comment by B4nan** [comment]
Lol, this is not how you should use issue template 😭 You left 80% of the hints there and literally hidden your question inside 🤷 

You can use `mapToPk`, but it will have consequences (propagation of changes won't work, you can't use ). 

> For me to just set an id, I have to do this:

Nope, actually that is not even the correct way. If the entity with ID 2 exists, this is wrong way to go, as it would result in insert query. You should use `entity.table = em.getReference(Table, 2);` instead.
