### ISSUE TITLE
Any way to find parameters documentation?

### ISSUE THREAD

**Issue by vimmerru** [mikro-orm/mikro-orm#122]
**Describe the bug**
You have a lot of parameters without any description, code comments or typing. Just example

```
count(entityName: string | EntityClass<T>, where: any): Promise<number>
```

how `where` should look here? I have similar issues with entity definition annotations, query conditions and so on. Could you provide any guidance?

**Comment by B4nan** [comment]
All methods should accept `FilterQuery<T>` type, which is defined as `export type FilterQuery<T> = Partial<T> | Record<string, any>;`

I see that in `AbstractSqlDriver` the `count` method has `any`, but rest should be correctly typed. Also in entity manager methods you can pass PK directly (like `em.findOne(1)` instead of `em.findOne({ id: 1 })`).

Generally you can pass 
- PK value which will be automatically translated into `{ [PK]: PKValue }`
- dictionary of conditions like `{ prop1: val1, prop2: val2 }`
- smart query conditions are also supported, so one can write `{ 'prop1:in': [1,2,3], 'prop2:gte': 5 }`

**Comment by vimmerru** [comment]
``` export type FilterQuery<T> = Partial<T> | Record<string, any>;```

FIY: Record<string, any> allows to put near any object that breaks near any object and makes  Partial<T> meaningless here. I will respond with solution in dedicated ticket about em::find typings.

**Comment by B4nan** [comment]
Yeah I know how `Record` works, the point of having `Partial` there as well is to allow IDEs to autocomplete.

**Comment by vimmerru** [comment]
@B4nan 

Thanks for your support! One additional question. When i need to filter collection by foreign key for example find users in one organization should i use reference or there is a shortcut? 

I have ```organization: Organization``` filed in user and ```organization_id``` FK in the table and i  now i do:

```
const organization = em.getReferene(Organization, organizationId);
const users = em.find(User, { organization });
```

Is it possible to do something like 

```
const users = em.find(User, { organization:  organizationId});
```

without reference boilerplate?

**Comment by B4nan** [comment]
Sure, you can pass any of PK, Reference or Entity itself as a value in the query. 

```typescript
const id = 1;
const users = em.find(User, { organization: id });

const ref = em.getReference(Organization, id);
const users = em.find(User, { organization: ref });

const ent = em.findOne(Organization, id);
const users = em.find(User, { organization: ent });
```

**Comment by kgoncharov** [comment]
Hi @B4nan! 
What is the best way to handle optional DB fields using MikroORM?
I've noticed that I can't mark property as `property?: string` and then set `undefined` - the exception was thrown

**Comment by B4nan** [comment]
> Hi @B4nan!
> What is the best way to handle optional DB fields using MikroORM?
> I've noticed that I can't mark property as `property?: string` and then set `undefined` - the exception was thrown

Could you be more specific and provide some snippets of how you define the entity and how you try to persist it? Also include the thrown exception and ideally create new issue for this so we do not pollute this one.

**Comment by B4nan** [comment]
Adjusted docs about this in the dev branch, closing as resolved now, but feel free to reach out if it's not enough :] 

https://github.com/mikro-orm/mikro-orm/blob/dev/docs/entity-manager.md
