### ISSUE TITLE
FaunaDB support

### ISSUE THREAD

**Issue by ramiel** [mikro-orm/mikro-orm#1221]
**Is your feature request related to a problem? Please describe.**
I know this would be rocket science at this point, but do you think would it possible to support FaunaDB?

**Describe the solution you'd like**
Having FaunaDB handled by mikro-orm would be great but I understand the difficulties behind the task

**Describe alternatives you've considered**
Working with the faunadb driver directly is good, but not as good as using mikro-orm

**Additional context**
https://fauna.com/

**Comment by B4nan** [comment]
No plans to add such driver in near future, you could try to implement it yourself, if the API is similar to mongo driver, it should be quite easy (check its source code). Will be happy to assist with that.
