### ISSUE TITLE
PK as FK with References & getIdentifiers

### ISSUE THREAD

**Issue by ml1nk** [mikro-orm/mikro-orm#1224]
**Describe the bug**
The collection method "getIdentifiers" returns an array of references instead of the expecting ids:
~~~ts
      [ Reference { entity: Ref<Node> { id: 1 } } ]
~~~
This derivates from the type declaration.

**To Reproduce**
#1224

**Expected behavior**
~~~ts
      [ 1 ]
~~~
 instead of
~~~ts
      [ Reference { entity: Ref<Node> { id: 1 } } ]
~~~

**Versions**
| Dependency | Version |
| node | 15.4.0 |
| typescript | 4.1.2 |
| mikro-orm | 4.3.4  |
| postgresql |  8.5.1 |

**Comment by ml1nk** [comment]
I'm trying to fix the bug but i'm somewhat confused:

All Items in ArrayCollections are of type T which does not extend AnyEntity in any way. I would like to use the Entity helper directly, but I currently need to check if it's really an entity and provide a fallback. In which case is T not an Entity?

I expected getSerializedPrimaryKey to return a number, if there is only one primary key of this type. In my test case it's a string, but on the opposite getPrimaryKey returns a number but obviously fails other tests which needs serialization. It seems it is on purpose:  
~~~ts
      // EntityComparator line 122
      lines.push(`  return '' + entity.${meta.serializedPrimaryKey};`);
~~~


~~~ts
  getIdentifiers<U extends IPrimaryKey = Primary<T> & IPrimaryKey>(field?: string): U[] {
    const items = this.getItems();

    if (items.length === 0) {
      return [];
    }

    if (field === undefined) {
      return items.map(i=> Utils.isEntity(i) ? i.__helper!.getSerializedPrimaryKey() : i[this.property.targetMeta!.serializedPrimaryKey as keyof T]) as unknown as U[];
    }
    return items.map(i=> i[field as keyof T]) as unknown as U[];
  }
~~~

~~~ts
GH issue 1224 › PK as FK with References & getIdentifiers

    expect(received).toStrictEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

      Array [
    -   1,
    +   "1",
      ]
~~~

**Comment by B4nan** [comment]
It is always an entity, the reason why we do not define `T` as `extends AnyEntity<T>` is this: https://github.com/mikro-orm/mikro-orm/commit/1fb6cecb29c95de9307c89518a99bbb35620b867

And `getSerializedPrimaryKey` is expected to return a string, as stated by the method signature. 

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/entity/WrappedEntity.ts#L89

**Comment by ml1nk** [comment]
Thanks for the explanation. Sadly it seems using getSerializedPrimaryKey or getPrimaryKey is the wrong approach.
I updated my PR with a hopefully working fix and some comments.
