### ISSUE TITLE
Implement em::findAndCount and repository::findAndCount method

### ISSUE THREAD

**Issue by vimmerru** [mikro-orm/mikro-orm#123]
**Is your feature request related to a problem? Please describe.**
The problem is just to implement paging that requires totalCount as well as items in paging window. 

Now i need to send 2 separate queries and write 2 where conditions that causes boilerplate. Also some databases (like mysql) allow to calculate total count in more efficient way. 

**Describe the solution you'd like**

1. Implement ```em::findAndCount``` method that will return ```Pormise<[T[], totoalCount]>```

**Comment by B4nan** [comment]
Just tried postgres specific way to do this in single query (via `over()`) and it performs really badly on large tables (millions of rows). I do not have such database in mysql to test it, but I can imagine it won't be worth it to implement it... Let's start with simply doing 2 queries in the background, it is much simpler to implement than supporting driver specific ways to achieve this, sometimes via one query (postgres), sometimes via two (even mysql requires to do 2 queries, and they have to be ran against same connection, so effectively wrapped in a transaction from knex' perspective).

**Comment by B4nan** [comment]
Available for testing in `3.0.0-alpha.16`.
