### ISSUE TITLE
Many to Many filter doesnt work in my case

### ISSUE THREAD

**Issue by jagabs** [mikro-orm/mikro-orm#1232]
One to many filter works for me see below query.
For ManyToMany the query doesnt recognize the filter i assigned. What am i doing wrong? 

employee.ts

```
 @Field(() => [Benefit], { nullable: true })
  @ManyToMany(() => Benefit)
  public benefits?: Collection<Benefit> = new Collection<Benefit>(this);

  @Field(() => [DayOff], { nullable: true })
  @OneToMany({
    entity: () => DayOff,
    mappedBy: 'employee',
    orphanRemoval: true,
  })
  public dayOffs = new Collection<DayOff>(this);
```

dayoff.ts

```
@Filter({
  name: FILTERS.CURRENT_DAY_OFF,
  cond: (args) => ({
    dateTo: { $eq: null },
  }),
  default: false,
}) 
export class DayOff extends Base<DayOff> {

  @Field({ nullable: true })
  @Property({ nullable: true })
  public dateTo?: Date;
}
```

benefit.ts
```
@Filter({
  name: FILTERS.IS_ACTIVE,
  cond: (args) => ({
    benefitStatus: { $eq: STATUS.ACTIVE },
  }),
  default: true,
})
@Unique({ properties: ["benefitCode", "tenantId"] })
export class Benefit extends Base<Benefit> {

  @Field(() => STATUS)
  @Enum(() => STATUS)
  @Property({ columnType: "text" })
  public benefitStatus: STATUS;
}
```

 ```
const employee = await employeeRepository.findOneOrFail(
      readInput.employeeId,
      {
        strategy: LoadStrategy.SELECT_IN,
        filters: [FILTERS.CURRENT_DAY_OFF, FILTERS.IS_ACTIVE],
        populate: ["dayOffs", "benefits"],
      }
    );
```

`[query] select "e0".* from "tbl_day_off" as "e0" where "e0"."employee_id" in ('00000000-0000-0000-0000-000000000001') and "e0"."tenant_id" = '1' and "e0"."date_to" is null order by "e0"."employee_id" asc [took 3 ms]`

`[query] select "e0".*, "e1"."benefit_id", "e1"."employee_id" from "tbl_benefit" as "e0" left join "tbl_employee_benefits" as "e1" on "e0"."id" = "e1"."benefit_id" where "e1"."employee_id" in ('00000000-0000-0000-0000-000000000001') [took 2 ms]`

**Comment by B4nan** [comment]
Filters are never applied to the pivot table, only to the entity tables - is that what you want? Also you are querying employee entity, and it has only one filter (`CURRENT_DAY_OFF`), the other one can't be applied like this.

Hard to say, as you totally ignored the issue template and I also failed to understand what you actually want. You are talking about a filter, but your example defines 2 filters.  

**Please provide minimal executable reproduction (so no graphql involved, working entity definitions, as well as some data), and don't forget some assertions.**

https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues

**Comment by jagabs** [comment]
Hi @B4nan,

thank you for your fast reply. And sorry for not following the template.
i think youve answered my question with this _the other one can't be applied like this_

What i wanna achieve is query in employee entity and also filter the benefit status to only active.
So get all benefits with employee id = 1 and status = active something like that.

thanks :)

**Comment by B4nan** [comment]
Currently filters are applied only for the root entity, but you can filter the relation from there too. One of your filters is enabled by default - that is why it works, and that `filters: [FILTERS.CURRENT_DAY_OFF, FILTERS.IS_ACTIVE],` line in your query has no effect on that.

You could either enable both of them by default (and disable where needed), or specify the filters on the employee entity:

```ts
@Filter({
  name: 'IS_ACTIVE',
  cond: {
    benefits: { benefitStatus: { $eq: STATUS.ACTIVE } },
  },
})
@Filter({
  name: 'CURRENT_DAY_OFF',
  cond: {
    dayOffs: { dateTo: { $eq: null } },
  },
}) 
export class Employee {

  @ManyToMany(() => Benefit)
  public benefits?: Collection<Benefit> = new Collection<Benefit>(this);

  @OneToMany({
    entity: () => DayOff,
    mappedBy: 'employee',
    orphanRemoval: true,
  })
  public dayOffs = new Collection<DayOff>(this);

}
```

Then you can enable them when querying the employee:

```ts
const employee = await employeeRepository.findOneOrFail(
     readInput.employeeId,
     {
       strategy: LoadStrategy.SELECT_IN,
       filters: ['CURRENT_DAY_OFF', 'IS_ACTIVE'],
       populate: ["dayOffs", "benefits"],
     }
   );
```

**Comment by jagabs** [comment]
Hi @B4nan,

Thanks for clarifying...
My mistake was i added the filter in benefit.ts instead of adding it inside the employee class.
surpisingly though for dayoff class it works even tho i added it inside dayoff.ts not in the employee class as well.

**Comment by B4nan** [comment]
Nothing surprising, as I already mentioned, you had it enabled by default - that is why it worked for that filter.

**Comment by jagabs** [comment]
i also tried for benefit entity and it didnt work. I added it in the benefit class. Ill try to make a sample test file

**Comment by jagabs** [comment]
Also when i try to add the filters in the Employee entity it gives me a one whole query.

```
select "e0".* from "tbl_employee" as "e0" left join "tbl_employee_deductions" as "e2" on "e0"."id" = "e2"."employee_id" left join "tbl_deduction" as "e1" on "e2"."deduction_id" = "e1"."id" left join "tbl_employee_benefits" as "e4" 
on "e0"."id" = "e4"."employee_id" left join "tbl_benefit" as "e3" on "e4"."benefit_id" = "e3"."id" where "e0"."id" = '00000000-0000-0000-0000-000000000001' and "e0"."tenant_id" = '1'  limit 1
```

What i wanna achieve is that get the employee and then filter the benefits that has an active status. If its not possible i can just call another query.

**Comment by B4nan** [comment]
Yes, that is how filters work. Maybe global filters would work better for you, they are all enabled by default and can be defined for multiple entities at once.

https://mikro-orm.io/docs/filters/#global-filters

Or you can leverage the fact that filters are defined only by their name, so if multiple entities define filter with same name, you can control it also for relations via `FindOptions`:

https://mikro-orm.io/docs/filters/#naming-of-filters

**Comment by jagabs** [comment]
Hi @B4nan,

can you give me any document on how to run a test script? im sorry im new to the open source world :D i would like to provide an executable test. I forked the mikroorm and i created a test script but i dont know how to run it nor to connect to the database.

I really think this is a bug with ManyToMany. Even with global filters it seems the filter is not applied.

thank you very much for your time and effort

**Comment by B4nan** [comment]
https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md

And keep in mind I already told you filters are never applied to the join table. As well as I already told you why your filter for 1:m was working (as it was enabled by default), while the other for m:n was not (as that one was disabled by default - and you can't control that via `FindOptions` as you were trying).

**Comment by jagabs** [comment]
ohhh, i thought with this **strategy: LoadStrategy.SELECT_IN** it is treated as per query per table.

also what do you mean by enabled by default? i just want to clarify cos for 1:m (dayOff.ts) default: false and for benefit.ts I used default: true.

**Comment by B4nan** [comment]
`strategy: LoadStrategy.SELECT_IN` is the default

> also what do you mean by enabled by default? i just want to clarify cos for 1:m (dayOff.ts) default: false and for benefit.ts I used default: true.

I mean exactly that. If you put `default: true` on both, they will be both applied.

**Comment by jagabs** [comment]
thats the case, even if i put true it doesnt work haha

**Comment by B4nan** [comment]
Interesting, let's wait for the repro.

**Comment by jagabs** [comment]
Hi @B4nan,
I created a pr with the failed test, is this the correct way of doing things? thanks

**Comment by B4nan** [comment]
FYI your repro was not 100% correct, it will never work like that as the collection was already loaded in the memory - you need to clear the EM before you load the entity again to replicate new request. Also you were not populating the collection at all, so if you would actually clear, it would not be even loaded. 

Here is a fixed repro:

```ts
    const benefit = new Benefit();
    benefit.benefitStatus = 'IA';
    const employee = new Employee();
    employee.benefits.add(benefit);
    await orm.em.persistAndFlush(employee);
    orm.em.clear();

    const b1 = await orm.em.find(Benefit, {});
    expect(b1).toHaveLength(0);
    orm.em.clear();

    const e1 = await orm.em.findOneOrFail(Employee, employee.id, ['benefits']);
    expect(e1.benefits).toHaveLength(0);
```
