### ISSUE TITLE
one to many relation in where condition of find is not working properly

### ISSUE THREAD

**Issue by SDAdham** [mikro-orm/mikro-orm#1238]
Hello & Merry Christmas :)

**Describe the bug**
When I run the following code:
```
this.repo.find({
              $or: [
                {
                  membershipGroup: {
                    memberInMembershipGroups: [
                      {
                        memberUser: {
                          id: userId,
                        },
                      },
                    ],
                  },
                },
              ],
});
```
it results with:
```
select `e0`.* from `someEntity` as `e0` left join `membership_group` as `e3` on `e0`.`membership_group_id` = `e3`.`id` left join `member_in_membership_group` as `e4` on `e3`.`id` = `e4`.`membership_group_id` 
where (`e4`.`id` in ('{\"e4.memberUser\":23}'))
```
This returns null even though it should have results and my assumption its' not resolving the one to many relation properly

**To Reproduce**
```
@Entity()
class SomeEntity {
@ManyToOne(() => MembershipGroup, { nullable: true, eager: false })
  membershipGroup: MembershipGroup;
}

@Entity()
class MembershipGroup {
@OneToMany(
    () => AccessControlPermission,
    value => value.membershipGroup,
    {nullable: true, eager: false},
  )
  someEntities: SomeEntity[];

@OneToMany(
    () => ObjectInMembershipGroup,
    value => value.membershipGroup,
    {nullable: true, eager: false},
  )
  memberInMembershipGroups: MemberInMembershipGroup[];
}

@Entity()
class MemberInMembershipGroup {
@ManyToOne(() => MembershipGroup, {nullable: true, eager: false})
  membershipGroup: MembershipGroup;

@ManyToOne(() => User, {nullabe: true, eager: false})
  memberUser: User;
}
```

**Expected behavior**
`(`e4`.`id` in ('{\"e4.memberUser\":23}')` is wrong and the relation is not resolved properly, it should've been:
``e4`.`member_user_id` = 11`
Due to formatting issues:
Wrong:
![image](https://user-images.githubusercontent.com/11182824/103126908-ea752b80-46e3-11eb-8354-415d00ea7aa0.png)
Correct:
![image](https://user-images.githubusercontent.com/11182824/103126930-fb25a180-46e3-11eb-877d-c2d1e480df38.png)

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 12 |
| typescript | ? |
| mikro-orm | 4.3.4 |
| your-driver | mysql |

**Comment by SDAdham** [comment]
I worked around this by doing this:
```
this.repo.find({
              $or: [
                {
                  membershipGroup: {
                    memberInMembershipGroups: 
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
                      // @ts-ignore
                      {
                        memberUser: {
                          id: userId,
                        },
                      },
                  },
                },
              ],
});
```

**Comment by B4nan** [comment]
Your query is wrong, you can't just put an array there. As well as your entity definitions are wrong, you can't define 1:m or m:n as array, it needs to `Collection` instance and you need to instantiate that. 

https://mikro-orm.io/docs/collections

**Comment by SDAdham** [comment]
Do you also mean that my workaround is also incorrect @B4nan ?

**Comment by B4nan** [comment]
Its not a workaround, its the correct way, but you need to have correct entity definitions - then it will type check just fine so you wont need the ts-ignore comment.

**Comment by SDAdham** [comment]
Thanks @B4nan : the `repo` here is `SomeEntityRepo`. So the relations is this way `SomeEntity.MembershipGroup.MemberInMembershipGroups[]`, is this not correct, `memberInMembershipGroups` is an array as defined in the TS. what am I missing wrong?

**Comment by B4nan** [comment]
Again, the issue is your entity definition, it can't be an array, it needs to be `Collection`.

**Comment by SDAdham** [comment]
@B4nan : this won't be a good idea because the variable won't match the interface used by the angular project. Any alternative suggestions?

Thanks a lot.

**Comment by SDAdham** [comment]
I also created this question https://stackoverflow.com/questions/65453435/mikroorm-eager-is-set-to-false-yet-the-relation-is-still-being-loaded but I don't know if it's a bug or not.

**Comment by B4nan** [comment]
It is not a good idea to model your backend based on frontend. If you want to use array there, use different library - as I already told you multiple times, you need to use `Collection` wrapper in MikroORM. 

https://mikro-orm.io/docs/relationships

Regarding that SO question, read about how identity map works. Ideally read the whole docs (at least the overview and fundametals sections), because your questions sounds like you did not read very much of that... :] 

https://mikro-orm.io/docs/identity-map

**Comment by SDAdham** [comment]
@B4nan , I understood your point about the `Collection`, I'll try to seek a way of using it, I was just checking if there was alternatives. Sorry if my questions are irritating you.

I promise you I do read the `identity-map` of your documentation, in fact I have your documentation opened the entire time I am working with `MikroORM`. I do have tons of questions and issues that I'm having, but I'm not sharing them yet, I do a lot of homework before I post them here or in StackOverFlow.

In regards to your SO, regardless I use sometimes array or not, it sometimes doesn't honor what relations that should be loaded. Is it ok if I file a feature request that the relations load should be honored and if a relation is not loading, then at least load it's `id` please?

**Comment by SDAdham** [comment]
FYI, I just started working and here is my current tabs opened from last night:
![image](https://user-images.githubusercontent.com/11182824/103180915-d94c3a80-48ee-11eb-840f-c3b5211d2114.png)
You can see how many tabs I have opened for `Mikro-ORM`'s documentation.
