### ISSUE TITLE
toJSON not defined unless extending BaseEntity or manually wrapping

### ISSUE THREAD

**Issue by ashervb** [mikro-orm/mikro-orm#1239]
This might be more of a documentation issue, but most of the [examples in the docs](https://mikro-orm.io/docs/serializing/#property-serializers) seem to indicate that `toJSON` should work with any entity, but looking over the code base this only seems available when the returned obj is `wrap`ped or when the entity extends BaseEntity. Is this expected?

**Comment by B4nan** [comment]
The method is there, it is added to the prototype during discovery process. To make TS happy, you need to use `wrap` helper, but doing `(e as any).toJSON()` will work as well.

**Comment by B4nan** [comment]
In v2 there was no `wrap` helper and [entity interfaces were always merged with `IEntity`](https://mikro-orm.io/docs/2.7/defining-entities) that defined those method, so that is where those examples are comming from, will update it to use `wrap` helper so its up to date.
