### ISSUE TITLE
MicroORM is clearing Zone

### ISSUE THREAD

**Issue by SDAdham** [mikro-orm/mikro-orm#1244]
**Describe the bug**
For some strange unexpected reason, RequestContext returns `undefined` if any of the `MicroORM` functions is used i.e `find`, or `findOne` not sure about the rest.

**To Reproduce**
`request-context.js`
```
import { Request, Response } from 'express';

export class RequestContext {
  readonly id: number;
  request: Request;
  response: Response;

  constructor(request: Request, response: Response) {
    this.id = Math.random();
    this.request = request;
    this.response = response;
  }

  static currentRequestContext(): RequestContext {
    return Zone.current.get(RequestContext.name);
  }

  static currentRequest(): Request {
    const requestContext = RequestContext.currentRequestContext();

    if (requestContext) {
      return requestContext.request;
    }

    return null;
  }
}
```
In `request-context.middleware.ts`:
```
import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response } from 'express';
import { RequestContext } from './request-context';

@Injectable()
export class RequestContextMiddleware implements NestMiddleware {
  use(req: Request, res: Response, next: () => void): void {
      const requestContext = new RequestContext(req, res);
      Zone.current
        .fork({
          name: RequestContext.name,
          properties: {
            [RequestContext.name]: requestContext,
          },
        })
        .fork(Zone['longStackTraceZoneSpec'])
        .run(async () => {
          next();
        });
  }
}
```
In `app.module.ts`
```
...
export class AppModule implements NestModule {
  configure(consumer: MiddlewareConsumer): void {
    consumer.apply(RequestContextMiddleware).forRoutes('*');
  }
}
```
Then in any controller, service, wherever, try 

**Expected behavior**
`MikroORM` shouldn't impact `RequestContext`, maybe it's clearing `Zone`?

**Additional context**

Here is example block:
```
console.log(RequestContext.currentRequest().method); // output GET/PUST/OPTIONS
const someEntity = await this.someEntityService.findByName();
console.log(RequestContext.currentRequest().method); // Error, undefined
```

**Versions**

| Dependency | Version |
| - | - |
| node | ? |
| typescript | ? |
| mikro-orm | 4.3.4 |
| your-driver | mysql |

**Comment by B4nan** [comment]
Have you seen this? 

https://github.com/mikro-orm/mikro-orm/issues/315#issuecomment-698322261

**Comment by SDAdham** [comment]
Hello @B4nan , I did check https://github.com/mikro-orm/mikro-orm/issues/315#issuecomment-698322261 but this is not my case. I am not using `RequestContext` just for `MikroORM` but for other logics too, my issue here is why `RequestContext` is being affected by `MikroORM`, this used to work before migrating to `MikroORM`. I also tried using this https://www.npmjs.com/package/nestjs-request-context which does the same concept, but still the same issue.

> you can't just use "some class called RequestContext" and expect things to work

Can you please explain? Have you tried to reproduce it?

> TBH I don't really understand what you were even up to

I use `RequestContext` for few reasons, I'll list 2 here:

* One of the logics not related to `MikroORM`: A logger service to log which request that the log is written in regards to.
* Related to `MikroORM`: In class `EntitySubscriber`, I need to use to get `userId` from the `request` to help with automating setting `userId` before inserting.
```
@Subscriber()
export class EntitySubscriber implements EventSubscriber {...}
```

For https://mikro-orm.io/docs/async-local-storage/  , I have checked out https://mikro-orm.io/docs/usage-with-nestjs/#using-asynclocalstorage-for-request-context instead, but not sure about the following:
```
// register the request context middleware
const app = await NestFactory.create(AppModule, { ... });

app.use((req, res, next) => {
  storage.run(orm.em.fork(true, true), next); // where orm here comes from? main.ts doesn't have orm definition and why do I need this if i already enable "registerRequestContext: false"
});
```

**Comment by ardyfeb** [comment]
@SDAdham are you find a solution ? 

https://github.com/mikro-orm/nestjs/issues/13
