### ISSUE TITLE
No type check for `persistAndFlush` on a custom repository

### ISSUE THREAD

**Issue by anlauren** [mikro-orm/mikro-orm#1247]
**Describe the bug**
It of course starts with the classic disclaimer: "I'm likely doing something wrong, but..."
It seems that when using `persistAndFlush` there's no type check associated with the entity passed to it. (it actually says `AnyEntity` as the argument type).
I'm having trouble understanding why/how, the type safety is fine to retrieve objects from the db, but not to write to write objects to the db.

**To Reproduce**
Steps to reproduce the behaviour:
consider the following code:

```typescript
import {
  Entity,
  MikroORM,
  PrimaryKey,
  Property,
  Repository,
} from "@mikro-orm/core";
import { EntityRepository, MongoDriver, ObjectId } from "@mikro-orm/mongodb";

@Entity()
class Thing {
  @PrimaryKey()
  _id: ObjectId;

  @Property()
  stuff: string;
}

@Repository(Thing)
class ThingRepository extends EntityRepository<Thing> {}

async function fun(repository: ThingRepository) {
  repository.persistAndFlush({ dsf: "sdf" }); // this is not in the model "thing" should have a type error?
}

async function bootstrap() {
  const orm = await MikroORM.init<MongoDriver>({
    entities: [Thing], // path to your JS entities (dist), relative to `baseDir`
    dbName: "my-db-name",
    type: "mongo",
    clientUrl: "...", // defaults to 'mongodb://localhost:27017' for mongodb driver
  });
  const repository = orm.em.getRepository(Thing);
  fun(repository);
}

```

**Expected behaviour**
Should error if trying to persist object that does not match repository schema

**Versions**

| Dependency | Version |
| - | - |
| node | v12.20.0 |
|@mikro-orm/core| "^4.3.4"|
|@mikro-orm/mongodb| ^4.3.4|

**Comment by B4nan** [comment]
This is because you can persist any entity with any repository. And there is no way to describe entity in a type safe way (we do not have any common property or something, its just an object).

**Comment by B4nan** [comment]
It is even possible to use EntitySchema without actual classes (but then you would still need to create the entity instance via `em.create()`). 

What we can do is a runtime check, but I dont see a way to make this strictly typed.

**Comment by anlauren** [comment]
Maybe it's my conception of what the manager does that is wrong.
Can we assume that passing a plain javascript object that is not from an annotated `Entity` class will just do nothing? like in the above example?
Given that the repository is associated with one `Entity` I was under the impression that the data persisted in this call would be persisted ont the table defined in the `Entity` definition associated to it.

Wouldn't it make sense to make these repositories manage their own entities and nothing else? 

I am trying to encapsulate the whole data manipulation in a generic class so that my services can just pass it a plain object respecting a data interface, without having to know what framework is used, i find it pretty hard to get it typed end to end

**Comment by B4nan** [comment]
> Wouldn't it make sense to make these repositories manage their own entities and nothing else?

Nope, that could never work. Repository is not managing anything, its just an extension point, all it does is to work with the underlying entity manager. Using repositories is optional. 

All entities are interconnected, things are cascaded, and all of that is handled by the entity manager.

**Comment by anlauren** [comment]
Hum okay i see I guess the framework does much more that what i initially needed (I just want a properly typed CRUD mongodb repository  interface 😛  ).

I've checked and yes of course if we pass a generic js object that is not an entity it does fails. 
Can't see it at compile time but I guess this is the limit of structural typings

Thank you for the help :)
