### ISSUE TITLE
elemMatch condition mongodb

### ISSUE THREAD

**Issue by dinhmai74** [mikro-orm/mikro-orm#1251]
Hi, I wonder how can I use elemMatch to find entity like mongo db 
[](https://docs.mongodb.com/manual/reference/operator/query/elemMatch/#op._S_elemMatch)
https://docs.mongodb.com/manual/reference/operator/query/elemMatch/#op._S_elemMatch
Is that possible in mikro orm?

**Comment by B4nan** [comment]
You can use any mongo operator:

```ts
const res = await em.find({ name: { $elemMatch: ... } as any }); // either cast as any or use `expr('name')` to get around the strict type
```

Or get the native collection object:

```ts
const nativeCol = em.getCollection(Book); // the `em` needs to be correctly typed to the `MongoEntityManager`
```
