### ISSUE TITLE
`id` property is always overwritten to be a getter of `_id`

### ISSUE THREAD

**Issue by anlauren** [mikro-orm/mikro-orm#1253]
**Describe the bug**
I was hesitating to post this be because I don't know the source code well enough to be sure it's a bug, but here it is.

I am using the mongoDB driver, and I wanted to expose the `id` field in my Entity with the original type(`ObjectId`) not `string`.
To do this i've set up some setter/getters but they were overwritten by something. Reading the source code i think there might be a bug, because it states:
`defines magic id property getter/setter if PK property is _id and there is no id property defined`, and in the lines after i don't see a `if` statement to check if there already an `id` key in the object:

```typescript
     /**
     * defines magic id property getter/setter if PK property is `_id` and there is no `id` property defined
     */
    static defineIdProperty(meta, platform) {
        Object.defineProperty(meta.prototype, 'id', { //always assign the getter 🤔 
            get() {
                return this._id ? platform.normalizePrimaryKey(this._id) : null;
            },
            set(id) {
                this._id = id ? platform.denormalizePrimaryKey(id) : null;
            },
        });
    }
```

On a side note, if anybody is reading that and is looking to return `ObjetId` instead of `string` for their `id` in the entity, here is the trick i've found:
```typescript

@Entity()
class Thing {
  @PrimaryKey({ name: "_id" })
  id: ObjectId;

  @Property()
   name!: string;
}
```

**Expected behavior**
Only add the magic getter/setter if the user didn't set an "id" property

**Versions**

| Dependency | Version |
| - | - |
| node | 12 |
| typescript | 4.1.3 |
| mikro-orm | 4.3.4 |
| your-driver | mongodb/4.3.4 |

**Comment by B4nan** [comment]
Well your workaround is not a workaround - that is what you need to do. Mongo requires you to have the PK column called `_id` all the time. If you want to have an `id` property instead, it still needs to be mapped to the `_id` column.

Btw your workaround is not even doing what you think, as `@PrimaryKey({ name: "_id" })` is an alias for `@PrimaryKey({ fieldName: "_id" })`, you are not setting the `prop.name` this way (it is literally impossible to set it via decorators, it is always the actual name of the property).

Sounds like you did not look how the `defineIdProperty` is called - as one level above you can see it is conditional, only if the PK property name is `_id`. So literally, only if you define an `_id` property - and in your example you are not doing that.

> On a side note, if anybody is reading that and is looking to return ObjetId instead of string for their id in the entity, here is the trick i've found:

If serialization is the motivation, I don't understand why you need this. It will be handled for you - entity with the pair of `_id/id` as defined in the docs will be serialized to have `id: string` in the output. And if you want to control that, the right way is to use property serializer.
