### ISSUE TITLE
Custom type isn't always converted before queries

### ISSUE THREAD

**Issue by merceyz** [mikro-orm/mikro-orm#1263]
**Describe the bug**

When using a custom type it getting converted depends on which type of `FilterQuery` was passed to the ORM

**Stack trace**

N/A

**To Reproduce**

```ts
import 'reflect-metadata';
import { MikroORM, Entity, PrimaryKey, Type, Property } from '@mikro-orm/core';

import { parse, stringify, v4 as uuid } from 'uuid';

class UUID extends Type<string, Buffer> {
	convertToJSValue(value: Buffer) {
		return stringify(value);
	}

	convertToDatabaseValue(value: string) {
		return Buffer.from(parse(value));
	}

	getColumnType() {
		return 'binary(16)';
	}
}

@Entity()
class User {
	@PrimaryKey({ type: UUID })
	id = uuid();

	@Property({ nullable: true })
	name?: string;
}

(async () => {
	const db = await MikroORM.init({
		type: 'sqlite',
		debug: true,
		entities: [User],
		dbName: ':memory:',
	});

	await db.getSchemaGenerator().ensureDatabase();
	await db.getSchemaGenerator().createSchema();

	const testCases: Array<(id: string) => Promise<any>> = [
		// OK - delete from `user` where `id` = X'bd35187746cd4d0f85ddfab9c4352548'
		async (id) => db.em.nativeDelete(User, await db.em.findOneOrFail(User, id)),

		// KO - delete from `user` where `id` in ('ec72d4d9-27ec-4329-8462-bd0d0f266578')
		async (id) => db.em.removeAndFlush(await db.em.findOneOrFail(User, id)),

		// OK - delete from `user` where `id` = X'679c9d6fa4db4e64978f52b36780556e'
		(id) => db.em.nativeDelete(User, id),
		(id) => db.em.nativeDelete(User, { id: id }),

		// KO - delete from `user` where `id` in ('145ae140-eab1-4ec7-85b7-97bcd89d952b')
		(id) => db.em.nativeDelete(User, [id]),

		// KO - delete from `user` where `id` in ('14aa0439-8cab-48a4-a01b-966179d9fcb7', '14aa0439-8cab-48a4-a01b-966179d9fcb7')
		(id) => db.em.nativeDelete(User, [id, { id: id }]),
	];

	for (const testCase of testCases) {
		const id = uuid();

		const user = new User();
		user.id = id;
		await db.em.persist(user).flush();
		db.em.clear();

		await testCase(id);

		const userCount = await db.em.count(User, id);

		if (userCount !== 0) {
			console.log('Failed to delete user with: ', testCase.toString());
		} else {
			console.log('Success with', testCase.toString());
		}
	}

	// KO - update `user` set `name` = 'foo bar' where `id` = '1f8c3ec7-b3cf-4235-ad64-8bd4a90df730'
	{
		const user = new User();
		user.id = uuid();
		user.name = 'foo';
		await db.em.persist(user).flush();
		user.name = 'foo bar';
		await db.em.flush();
	}

	await db.close();
})();

```

**Expected behavior**

The custom type should always be converted

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 14.15.3 |
| typescript | 4.1.3 |
|@mikro-orm/core | 4.3.5-dev.38|
|@mikro-orm/migrations | 4.3.5-dev.38|
|@mikro-orm/sqlite | 4.3.5-dev.38|

**Comment by B4nan** [comment]
No `native*` method does work with custom types currently, it just ignores them (there is a config toggle for this - `convertCustomTypes`, but not exposed in any of those methods). Those methods are not really designed to work with entities, it is a way to make a query, so you should have the db type there, all the time. If you pass an entity there, it will have the runtime value = it is a bad input for such method. There is one exception - `nativeInsert(Many)`, that method will convert input entity to DTO for you automatically.

But there are some weird things going on for sure, mainly the `async id => db.em.removeAndFlush(await db.em.findOneOrFail(User, id))` sounds very weird, as well as the very last one with UoW update.

Thanks for the thorough test case!

**Comment by merceyz** [comment]
> But there are some weird things going on for sure, mainly the async id => db.em.removeAndFlush(await db.em.findOneOrFail(User, id)) sounds very weird, as well as the very last one with UoW update.

Yeah, it was those that I encountered in my actual usecase so went looking in all the methods to see where it didn't behave like I expected
