### ISSUE TITLE
add feature for disable tracking on query result entities for better performance similar to .AsNoTracking in entity framework

### ISSUE THREAD

**Issue by farid009** [mikro-orm/mikro-orm#1267]
hi I think this is a good feature for improve performance specially for heavy queries
add feature for disabling tracking on query result entities for better performance like .AsNoTracking in entity framework

**Comment by B4nan** [comment]
by tracking you mean change set tracking? please follow the feature request template

**Comment by farid009** [comment]
I mean disabling storing result entities in Identity Map for  a specific query by setting a property 
for example
repo.findOne({},{noTracking:true})
In the example above, the resulting entities are not expected to be stored in the identity map and mikro orm and mikro orm no longer tracks their changes
