### ISSUE TITLE
[docs] generate website docs for v3?

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#127]
Would be nice to be able to read them on the website. Not sure how that is possible, if you explain it, I can probably submit a PR.

**Comment by B4nan** [comment]
v3 is currently developed in the dev branch, once merged, it will be on the website automatically. as i noted in the other issue, i am not aware of a simple way to have both of them available.

i did send everything in single commit so you can see changes here https://github.com/mikro-orm/mikro-orm/pull/80/commits/704bb5648e4cdbb65cebf2cf4f5636bde8b6668c

although not very readable, better than nothing. i am not going to merge this into master before i finish with all breaking changes i am planning (currently there is #124 and #121, but there might be more). i will also first prepare migration guide first.

**Comment by lookfirst** [comment]
What i'm thinking is something like this:

https://www.postgresql.org/docs/11/index.html

some sort of versioned directory structure.

maybe not for v3, but going forward, something to consider.

**Comment by B4nan** [comment]
v3 docs are now published here: https://mikro-orm.github.io/docs-v3/index (only static copy of what is in the `dev` branch right now). 

I think this could be the easiest way to have versioned docs, once v3 is out, I will create `docs-v2` repository with latest v2 documentation and link it in v3 one.

**Comment by B4nan** [comment]
Created the `docs` repo: https://mikro-orm.github.io/docs/

v2 snapshot: https://mikro-orm.github.io/docs/v2/
v3 snapshot (will be redirected to mikro-orm.io once its released): https://mikro-orm.github.io/docs/v3/

**Comment by lookfirst** [comment]
Awesome sauce!

**Comment by B4nan** [comment]
You mean https://github.com/mikro-orm/docs-v3? I will redirect that to https://github.com/mikro-orm/docs/v3/

**Comment by lookfirst** [comment]
https://mikro-orm.github.io/docs/v3/installation/  the content of this page is out of date. scroll to the bottom and you can see the rendering is messed up. i think we fixed that.

**Comment by lookfirst** [comment]
Also, the link to 'edit the page' is broken.

**Comment by B4nan** [comment]
Both should be fixed now, also added the redirect from `docs-v3` to `docs/v3`.
