### ISSUE TITLE
Property with relation and fieldName config with mongo not populating properly

### ISSUE THREAD

**Issue by ryankauk** [mikro-orm/mikro-orm#1279]
**Describe the bug**
This issue seems present when using 

```typescript
import { ObjectId } from '@mikro-orm/mongodb';
```
to define the primary key on the entity.

For some reason I can use mongoose ObjectId and everything works

```typescript
 import { ObjectId } from 'mongoose';
```

Example usage and result
```typescript
const data = new MyEntity();
data.test = 'me';
const withRelation = new MyEntityTwo();
withRelation.entity = data.toReference();

DB_DI.orm.em.persist(data);
await DB_DI.repos.myEntity.nativeDelete({});
await DB_DI.repos.myEntityTwo.nativeDelete({});
DB_DI.orm.em.persist(withRelation);
await DB_DI.orm.em.flush();
DB_DI.orm.em.clear();
const datas = await DB_DI.repos.myEntityTwo.findAll({});
console.log(datas);
```
this will log
```bash
[
  MyEntityTwo { _id: ObjectId('5ff633eeb2b03e24953c665e'), entity: null }
]
```

**To Reproduce**
1. You can see a full example here: https://github.com/ryankauk/mikro-orm-request-time/commit/73ad32ba1a1f95eacaffa912a2c2c2e6c0256801
2. and if you hit the endpoint http://localhost:5999/myEntity/mikro-create you will see the result in the logs

**Expected behavior**
Should populate the entity

**Additional context**
I though it might be due to having mongoose installed as well and possibly a package collision or something. I removed the mongoose package and the same issue still appears.

**Versions**

| Dependency | Version |
| - | - |
| node |  v12.16.3 |
| typescript | 4.1.3 |
| mikro-orm | 4.3.4 |
| your-driver | 4.0.1 |

**Comment by B4nan** [comment]
Interesting issue, you should use the one from `@mikro-orm/mongodb`, that way the type is correctly inferred - but due to a bug in mongo driver, it was actually working only when it was not inferred correctly.

Btw you have misconfigured entity definition, you are missing `wrappedReference: true` (this is automatic only when using ts-morph):

```ts
  @ManyToOne(() => MyEntity, { fieldName: 'asdf', wrappedReference: true })
  entity: IdentifiedReference<MyEntity>;
```
