### ISSUE TITLE
Failure when using Embeddable and existing data has Embedded property null in mongo

### ISSUE THREAD

**Issue by ryankauk** [mikro-orm/mikro-orm#1296]
**Describe the bug**
Basically it's happening when using Embeddable. I'm switching over to mikro but I have some existing data in mongo where the Embedded property is undefined. This ends up throwing an error of something along the lines of "JIT runtime error: Cannot read property 'field' of undefined".

Seems to only happen when "object" param is true

**Stack trace**
```
TypeError: Cannot read property 'field' of undefined
    at eval (eval at createFunction (/Users/path/mikro-orm-nextjs/node_modules/@mikro-orm/core/utils/Utils.js:580:52), <anonymous>:9:24)
    at Function.callCompiledFunction (/Users/path/mikro-orm-nextjs/node_modules/@mikro-orm/core/utils/Utils.js:591:20)
    at ObjectHydrator.hydrate (/Users/path/mikro-orm-nextjs/node_modules/@mikro-orm/core/hydration/ObjectHydrator.js:23:23)
    at EntityFactory.hydrate (/Users/path/mikro-orm-nextjs/node_modules/@mikro-orm/core/entity/EntityFactory.js:81:27)
    at EntityFactory.create (/Users/path/mikro-orm-nextjs/node_modules/@mikro-orm/core/entity/EntityFactory.js:35:14)
    at MongoEntityManager.find (/Users/path/mikro-orm-nextjs/node_modules/@mikro-orm/core/EntityManager.js:95:52)
```

**To Reproduce**
1. clone https://github.com/ryankauk/mikro-orm-nextjs/tree/mikro-entity-null-embeddable-issue
2. hit GET http://localhost:3000/api/createUser
3. and then hit GET http://localhost:3000/api/users and you'll see the error

**Expected behavior**
Since I'm setting the property with an initializer I would assume that it would be used when the property is undefined.

**Versions**

| Dependency | Version |
| - | - |
| node | v12.16.3 |
| typescript | 4.1.3 |
| mikro-orm | 4.3.4 |
| your-driver | mongodb |

**Comment by ramiel** [comment]
I have the same problem and noticed that removing `object: true` solves the problem. But than I have issue when trying to update an embedded field

**Comment by B4nan** [comment]
Not that it matters here (the issue is easily reproducible), but in general - the reproduction should be minimal, I am not intersted in next js app (or any other framework), it just adds clutter... :]

**Comment by ryankauk** [comment]
Alright no problem, sorry about that

**Comment by ryankauk** [comment]
hey @B4nan has this been added to one of the dev releases?

**Comment by B4nan** [comment]
Yop

**Comment by ryankauk** [comment]
I tried using 4.3.5-dev.102 but my test case is still failing 

```typescript
const _native = await db.DB_DI.orm.em
      .getDriver()
      .nativeInsert('MyModel', { myValue:'tester' });
objectId = _native.row!._id;
const myObject = (await db.DB_DI.repos.myModel.findOne({ _id: objectId }))!;

expect(tenant2.jobs).toBeTruthy();
```

**Comment by B4nan** [comment]
But that is another story, `em.nativeInsert()` has nothing to do with entities, it's a shortcut for QB basically. So the property initializer can't be executed, as there is no entity instance at all.

**Comment by ryankauk** [comment]
Yes, I'm using that to simulate the creation of an object from a completely external system. After doing some tests around Mikro I found that some of my expectation around the initializers is wrong, the initializers/constructor of your model only run either by the obvious `new MyEntity()` or by using `orm.em.create(MyEntity, {})`. Any code for initializers or in the constructor will run at this point. 

My expectations that I'll describe in a bit, derive from the usage of `orm.em.create` and how it automatically does this "magic" initialization and construction without using the "new" constructor syntax.


I figure that when I run `orm.em.find(MyEntity, {})` or `orm.em.findOne(MyEntity, {_id})` which has similar usage to  `orm.em.create`, where the objects don't exist in the unit of work yet, would have this same initialization and constructor code running when parsed and added into the unit of work after being fetched from the database.

I'm not too familiar with the internals of Mikro but after these tests it seems like this is either a limitation or by design, could you describe either of the reasoning why if this is correct or maybe I'm missing a possible config for this?

Would it maybe be possible to define a Property config some thing like `@Property({onDatabaseNull: () => new MetaData()})` that could also exist on Embedded decorator?

**Comment by B4nan** [comment]
You can use `@OnInit` hook for this, it is executed when new entity instance gets created. Another option is to force ctor usage, you can do so in latest dev version via [`forceEntityConstructor`](https://mikro-orm.io/docs/next/configuration#using-native-private-properties) option.

**Comment by ryankauk** [comment]
These solutions work perfectly thank you for your help!
