### ISSUE TITLE
Documentation on how to replace entities in a collection(one-to-many-relation)

### ISSUE THREAD

**Issue by mivanovaxway** [mikro-orm/mikro-orm#1298]
**Is your feature request related to a problem? Please describe.**
I found it difficult(based on the current docs) to replace entities in a collection(one-to-many).

To give a concrete example:
I have an entity called Package and another entity called Layer.
Like so(I've tried to simplify my entities, to make the example shorter, hopefully I did not make any mistakes):

```
@Entity()
export class Package {

@PrimaryKey()
id!: number;

@OneToMany({
    entity: () => Layer,
    cascade: [Cascade.ALL],
    mappedBy: 'package',
    orphanRemoval: true
})
layers = new Collection<Layer>(this);
}
```

```
@Entity()
export class Layer {
    [PrimaryKeyType]: [number, string];

    @ManyToOne({
        entity: () => Package,
        inversedBy: 'layers',
        fieldName: 'id',
        primary: true,
    })
    package!: Package;

    @PrimaryKey({length: 128})
    name!: string;

}
```

My use case is the following:
I want to replace the layers for a specified package:
Ex. package {id:1} layers:[{1,"ala"},{1,"bala"}]
So then I want to change the layers - for example to [{1,"dala"},{1,"bala"},{1,"zala"}]

The solution I came to by trial and error:
```
orphanRemoval: true is a must for @OneToMany layers in Package
```

```
const newLayers = myInputData.map(name => {
    const found = package.layers.getItems().find(oldLayer => oldLayer.name == name);
    if (found) {
        return found;
    }
    const layer = new Layer();
    layer.name = name;
    return layer;
});
await package.layers.set(newLayers);
```

**Describe the solution you'd like**
I'd be glad if such documentation regarding OneToMany collection usage could be added.
Feel free to use my example or perhaps write a better one.

**Comment by B4nan** [comment]
You need to understand what 1:m means - it is always inverse side, manipulating that is always just about propagating the change to the owner (so m:1), where the relation is actually stored. Orpah removal is by no means "a must", this very much depends on what you are actually modelling, you can't generalize this.

If you want to make things simple and understandable, use 1:m for reading, and m:1 for manipulation/writing/changing the relation.
