### ISSUE TITLE
Ability to specify schema when using Entity Generator

### ISSUE THREAD

**Issue by WonderPanda** [mikro-orm/mikro-orm#1301]
**Is your feature request related to a problem? Please describe.**
I'm interested in using MikroORM in a system where migrations and schema management are handled by another tool. I attempted to use the `EntityGenerator` functionality but there doesn't appear to be any way to limit entity generation to specific schemas (in this case Postgres)

**Describe the solution you'd like**
I'd like to be able to pass additional configuration to either `getEntityGenerator` or to the actual call to `generate` which enables me to limit the discovered entities to a schema of my choosing.

**Additional context**
Looking into the code for Entity Generator it's easy to filter down to only the tables I want during table discovery by simply putting a filter on the result of `getTables` eg:

```
schema
      .getTables()
      .filter((x) => x.schema === 'public');
```

I'm happy to try and make a contribution to this project but would appreciate some guidance as to the best way to expose this functionality in a way that makes sense for the API since this particular use case is Postgres specific. I can see there being usefulness for other drivers like mySQL as well

**Comment by B4nan** [comment]
The question is more like - why do you care? `EntityGenerator` is one time only tool, you should use it when bootstrapping new project with existing database - so why don't you just remove what you do not want and keep the rest? It is not suitable for perpetual use, you always need to verify and adjust what it will generate (and not everything is possible to generate, e.g. m:n relations).

I am not opposed by the suggestion, sure we can have a way to filter by schema name. It should be rather a parameter for the `generate` method (better say a new option in the existing parameter). Feel free to send a PR.

**Comment by WonderPanda** [comment]
Hey @B4nan thanks for the quick response!

> The question is more like - why do you care?

I'm trying to evaluate whether or not it would be feasible to use MikroORM in an application where the migrations and schema are managed by a different tool. This is similiar to the Prisma approach of treating the database as the source of truth and then generating code artifacts that make it easier to interact with the DB.

I would love to be able to generate a data layer SDK with MikroORM that I can just point against the current tables as part of an automated process.

Is there any documentation or open issues regarding limitations that would prevent being able to generate `m:n` relationships or other problems you could foresee in continuing to pursue this is a potential option? Or do you think that given the nature of where things are at right now with this library that it would just be a bad idea in the first place to try and continuously generate entities based on external changes to the database?

**Comment by B4nan** [comment]
It is probably doable, but you will cut yourself from many features of the ORM. This library is code first. 

Main issues with such approach:
- no m:n relations, pivot table is generated as separate entity (for simple m:n with proper composite PK this is doable and just not yet implemented)
- no inverse sides, only owners are generated (so only m:1 and 1:1 owners)
- you will have no way to configure advanced/non-default features, e.g. cascading/orhan removal, eager loading, lazy properties, identified references, embeddables...

**Comment by WonderPanda** [comment]
Thanks for the insight. I'm trying to put together a comparison matrix of different approaches to managing data using the different ORMs that exist in the Typescript ecosystem and how we might leverage them.

Right now we are not embracing a code first approach to managing schema so this would be a large shift. However, I'll keep playing around with MikroORM as it has a large (and growing) list of compelling features.

Thanks for all the awesome work you do on an amazing project!
