### ISSUE TITLE
How do I pronounce Mikro ORM?

### ISSUE THREAD

**Issue by episourcedavid** [mikro-orm/mikro-orm#1308]
Is it pronounced ME-krow or MAI-krow?

This has been creating great contention among my team.

**Comment by B4nan** [comment]
I tend to say [ME]kro when talking in czeck but using [MY]krow exclusively when talking in english :) 

Similar to My S.Q.L. vs My Sequal, pick what you like :D

**Comment by episourcedavid** [comment]
Thanks. That helps haha. Wasn't sure I'd get a response for this 😀 I'll close this out.
