### ISSUE TITLE
Problem with OneToMany relation get Cannot access 'Entity' before initialization

### ISSUE THREAD

**Issue by ThammawatBee** [mikro-orm/mikro-orm#1310]
Problem with OneToMany relation get Cannot access 'AuthorEntity' before initialization
I create relation between two entity by reading from doc my code is

Author Entity
```
 @OneToMany(() => BookEntity, book => book.author)
  books = new Collection<BookEntity>(this);

```

Book Entity
```
 @ManyToOne(() => AuthorEntity)
author: AuthorEntity

```

and then I use command mikro-orm schema:update -r

but it has a problem ReferenceError: Cannot access 'AuthorEntity' before initialization
**Versions**

| Dependency | Version |
| - | - |
| node | v12 |
| typescript | ^4.0.5 |
| @mikro-orm/core | ^4.3.3  |
| @mikro-orm/mysql | ^4.3.4 |

**Comment by B4nan** [comment]
This happens when you define both classes in single file, nothing ORM specific, this is how JS works. 

One way to get around it is to use string names instead of class references:

```ts
@ManyToOne('AuthorEntity')
author: AuthorEntity
```

**Comment by ThammawatBee** [comment]
I write both entity in separate but your method is work

Thank you very much
