### ISSUE TITLE
cli/generate-entities doesn't emit collection name

### ISSUE THREAD

**Issue by jasonwilson** [mikro-orm/mikro-orm#1328]
**Describe the bug**
When using the `generate-entities` the emitted classes don't include the collection name on the entity. 

**Stack trace**
```
(node:3691) UnhandledPromiseRejectionWarning: TableNotFoundException: select count(distinct("e0"."id")) as "count" from "f20181234" as "e0" - relation "f20181234" does not exist
```

**To Reproduce**

### sql
```sql
CREATE TABLE f2018_1234(
    id INT NOT NULL,
    PRIMARY KEY (id)
)
```

### command

```bash
npx mikro-orm generate-entities --dump
```

### got

```typescript
@Entity()
export class F20181234 {

  @PrimaryKey()
  id!: number;

}
```

### expected
```typescript
@Entity({collection: 'f2018_1234'})
export class F20181234 {

  @PrimaryKey()
  id!: number;

}
```

**Expected behavior**
Ideally the generated classes would map back to the tables in the source database.

**Additional context**
Not sure if I'm missing something with args or this is expected behavior 

**Versions**

| Dependency | Version |
| - | - |
| node | 14.5.1 |
| typescript | 4.1.3 |
| mikro-orm | 4.3.4 |
| your-driver | postgres |

**Comment by B4nan** [comment]
That works as expected. In general only options with other than default value will be there. FooBar will be translated back to foo_bar based on the naming strategy.

**Comment by jasonwilson** [comment]
Thanks for the prompt response @B4nan! I updated the example to include a table name consisting of two numbers. Currently working from a legacy system where we don't have much control over existing names. 

What would be the suggested solution? A couple paths I see:

1) Manually update the generated output to include the correct collection mapping.
2) Add an option to `generate-entities` to map table_name -> collection when you don't want to infer based on classname.

Thanks!

**Comment by B4nan** [comment]
I see, we can make this work automatically.

**Comment by jasonwilson** [comment]
Do you have a preferred implementation strategy? I'm happy to open a PR

**Comment by B4nan** [comment]
This should be pretty much just a one liner in `SourceFile.generate()`. Compare `meta.collection` with `this.namingStrategy.classToTableName(metaa.className)`, if they don't match, we need to add the name explicitly to the decorator.
