### ISSUE TITLE
Cannot call repository.persistAndFlush from a method executed by a decorator

### ISSUE THREAD

**Issue by Timo972** [mikro-orm/mikro-orm#1337]
**Describe the bug**
I am experiencing weird behavior when calling persistAndFlush operations from a method that is triggered by a typescript decorator. Its not 100% reproducable but appeares pretty often.

**Stack trace**
```
(node:32576) UnhandledPromiseRejectionWarning: ValidationError: You cannot call em.flush() from inside lifecycle hook handlers
    at Function.cannotCommit (M:\Users\Timo972\afterlife-core-src\node_modules\@mikro-orm\core\errors.js:74:16)
    at UnitOfWork.commit (M:\Users\Timo972\afterlife-core-src\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:158:44)
    at SqlEntityManager.flush (M:\Users\Timo972\afterlife-core-src\node_modules\@mikro-orm\core\EntityManager.js:457:36)
    at SqlEntityManager.persistAndFlush (M:\Users\Timo972\afterlife-core-src\node_modules\@mikro-orm\core\EntityManager.js:409:36)
    at SqlEntityRepository.persistAndFlush (M:\Users\Timo972\afterlife-core-src\node_modules\@mikro-orm\core\entity\EntityRepository.js:21:23)
```

**To Reproduce**
1. Create a decorator like below
```ts
const scripts = [];
export function Shutdown(target: unknown, propertyKey: string, descriptor: PropertyDescriptor): void {
    descriptor.value.bind(target);
    scripts.push(descriptor.value);
}

export async function runAtShutdown(): Promise<void> {
   await Promise.all(scripts.map(func => func()));
}
```
2. create a class method
```ts
class Test {
   @Shutdown
   public static async calledAtShutdown(): Promise<void> {
      // query a database entity
      // ...
      await repository.persistAndFlush(queriedEntity);
   }
}
```
3. run the function ``runAtShutdown()``
4. it throws ValidationError: You cannot call em.flush() from inside lifecycle hook handlers but as far as i know is this not a lifecycle hook

**Expected behavior**
It should flush and not throw error

**Additional context**
I am not using any lifecycle hooks

**Versions**

| Dependency | Version |
| - | - |
| node | 12.4.0 |
| typescript | 4.1.3 |
| mikro-orm | 4.3.4 |
| your-driver | mysql |

**Comment by B4nan** [comment]
This can never work for two reasons:
1. you are using the global EM
2. you can't flush in parallel (not on the same EM instance)

You could try to get the current EM via `RequestContext.getEntityManager()`, as long as the method is executed inside the domain/context middleware, it should work.

**Comment by B4nan** [comment]
Even using the right EM seems wrong to me, I believe you should either not use flushing at all (so either using `em.nativeInsert/Update/Delete()` or QB), or always create new fork - that way it is possible to flush in parallel, as you will be flushing different EM instances (forks).

**Comment by Timo972** [comment]
Ok, thank you for your quick answer.
