### ISSUE TITLE
Feature: add ability to make a Postgres Property "serial" without it being a PrimaryKey

### ISSUE THREAD

**Issue by charlex** [mikro-orm/mikro-orm#1344]
**Is your feature request related to a problem? Please describe.**

I would like to create columns that automatically add serial sequences. These columns are not to be primary keys.

**Describe the solution you'd like**

Add a decorator, or an option on Property that would allow 'serial' to be set. 

**Describe alternatives you've considered**

Add a hook to migration generation that would allow me to create a sequence by manually writing some SQL first.

**Additional context**
Add any other context about the feature request here.

**Comment by charlex** [comment]
Nevermind, this is easier said than I made it out to be:

```
  @Property({
    columnType: 'serial',
  })
  @Field(() => Number, { nullable: false })
  public number: number;
```

I was using:

```
  @Property({
    columnType: 'int',
  })
  @Field(() => Number, { nullable: false })
  public number: number;
```

**Comment by charlex** [comment]
Although, note that while the above works for the first migration, on the second migration, it failes:

```
DriverException: alter table "xxxx" alter column "number" type serial using ("number"::serial); - type "serial" does not exist
```

**Comment by ml1nk** [comment]
> Although, note that while the above works for the first migration, on the second migration, it failes:
> 
> ```
> DriverException: alter table "xxxx" alter column "number" type serial using ("number"::serial); - type "serial" does not exist
> ```

I have the same problem in version 4.5.5. Have you found a solution?

**Comment by B4nan** [comment]
Diffing of serial/pk columns should be fixed in v5, no plans to change anything on v4 implementation as it would be very hard to rebase onto v5. 

For now you could only use `int` explicitly and use `serial` manually only in the migration (override it once generated). The column type is actually `int`, `serial` is just a shortcut for `int` with a sequence that handles the default incrementing value.

**Comment by ml1nk** [comment]
That's good to know. Thanks.

**Comment by ml1nk** [comment]
Is there an example of using serial in v5 in postgres without generating a breaking migration after init?

Currently it generates
~~~typescript
    this.addSql('alter table "tenant" drop constraint if exists "tenant_tk_id_check";');
    this.addSql('alter table "tenant" alter column "tk_id" type int4 using ("tk_id"::int4);');
    this.addSql('alter table "tenant" alter column "tk_id" drop default;');
~~~
in every migration.
