### ISSUE TITLE
[feat] CamelCaseNamingStrategy

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#135]
Has a dep on lodash, which you probably don't like so that is why it isn't a pr. Probably could also use some tests. Anyway, something I'd like to see. I personally like my database columns to match my entities.

```
import {AbstractNamingStrategy} from "mikro-orm";
import {camelCase} from 'lodash';

class CamelCaseNamingStrategy extends AbstractNamingStrategy {
	classToTableName(entityName: string): string {
		return this.underscore(entityName);
	}

	joinColumnName(propertyName: string, className?: string): string {
		return this.underscore(propertyName) + '_' + this.referenceColumnName();
	}

	joinKeyColumnName(entityName: string, referencedColumnName?: string): string {
		return camelCase(this.classToTableName(entityName) + '_' + (referencedColumnName || this.referenceColumnName()));
	}

	joinTableName(sourceEntity: string, targetEntity: string, propertyName?: string): string {
		return camelCase(this.classToTableName(sourceEntity) + '_to_' + this.classToTableName(targetEntity));
	}

	propertyToColumnName(propertyName: string): string {
		return this.underscore(propertyName);
	}

	referenceColumnName(): string {
		return 'id';
	}


	private underscore(name: string): string {
		return camelCase(name.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase());
	}
}

```

**Comment by B4nan** [comment]
Maybe you wanted PascalCase instead? As camelCase is with first lowercase letter.

**Comment by lookfirst** [comment]
Yea... more to think about really. Hmm... I could go for a NS that does...

PascalCase table names.
camelCase columns and relations.

**Comment by B4nan** [comment]
That should be pretty easy... 

```typescript
import { AbstractNamingStrategy } from 'mikro-orm';

export class PascalCaseNamingStrategy extends AbstractNamingStrategy {

  classToTableName(entityName: string): string {
    return entityName;
  }

  joinColumnName(propertyName: string): string {
    return propertyName;
  }

  joinKeyColumnName(entityName: string, referencedColumnName?: string): string {
    return entityName;
  }

  joinTableName(sourceEntity: string, targetEntity: string, propertyName?: string): string {
    return this.classToTableName(sourceEntity) + '_to_' + this.classToTableName(targetEntity);
  }

  propertyToColumnName(propertyName: string): string {
    return propertyName;
  }

  referenceColumnName(): string {
    return 'id';
  }

}
```

**Comment by lookfirst** [comment]
Perfect!

**Comment by B4nan** [comment]
Integrated as `NoopNamingStrategy`, as it pretty much does nothing (I don't like to call it neither camelCase nor PascalCase, as both are used there...).

Available since `3.0.0-alpha.9`, closing this as resolved.

**Comment by lookfirst** [comment]
Unfortunately, I think Noop is weird too though. Think from a developer using your tools perspective... what does 'does nothing' even mean?

Naming is hard! My favorite quote: https://twitter.com/secretGeek/status/7269997868

**Comment by lookfirst** [comment]
I think Pascal is a fine name. Another idea: EntityCaseNamingStrategy.... cause that is more accurate... it takes the case from the entity.

**Comment by lookfirst** [comment]
@B4nan for some reason, I can't get Noop to import correctly or even run when I do a dist/... full import. Not sure what it is...

**Comment by B4nan** [comment]
EntityCase sound good!

**Comment by B4nan** [comment]
> @B4nan for some reason, I can't get Noop to import correctly or even run when I do a dist/... full import. Not sure what it is...

Are you including version from npm or via linking to github? There is no `dist` in github, so that might be the issue.

**Comment by lookfirst** [comment]
Linking from npm, but running `yarn build`. Everything else works fine... just that one.

**Comment by B4nan** [comment]
Ok will try it myself to see what happens. Might be some circular dependecy problem, then things act really weirdly.

**Comment by lookfirst** [comment]
Yea, really weird. try it in my example project or even better... add some tests to yours! =)

**Comment by B4nan** [comment]
Well it works ok for me in my project. Will try to use it in yours tomorrow. 

Could you please try to use version from npm? Just publisher `3.0.0-alpha.10` with rename to `EntityCaseNamingStrategy`.

**Comment by lookfirst** [comment]
It is working now... even with yarn link.
