### ISSUE TITLE
Infer type-graphql fields from mikro-orm properties

### ISSUE THREAD

**Issue by Swapnull** [mikro-orm/mikro-orm#1358]
**Is your feature request related to a problem? Please describe.**
I have come to MikroORM due to Prisma + Nexus not supporting MongoDB yet. As I want to use GraphQL, I find that I have a lot of repeat code due to having to declare both `@Field()` from `type-graphql` and `@Property` from `@mikro-orm/core`. 

Both of them declare the same thing in different ways. For example `@Field(() => [Task])` to define a collection in `type-graphql`, and `@Property(() => Task)` followed by `new Collection<Task>(this)` in `mikro-orm`

You may consider me lazy for this request, but the main driver behind this request is the fact that about half of my MikroORM development time is trying to figure out why the graphql portion doesn't work (eg accidentally doing `@Field(() => Task)` instead of `@Field(() => [Task])` - so if it could be derived from the existing declaration, development would be faster. 

I am going to use the following entity in this example - this is an example snippet from a user entity. 
```ts
@Entity()
@ObjectType()
export class User extends BaseEntity {
  @Field()
  @Property()
  public name: string;

  @Field()
  @Property()
  public email!: string;
  
  @Property()
  public password: string;

  @Field(() => [Task], { nullable: true })
  @OneToMany({
    entity: () => Task,
    mappedBy: "owner",
    nullable: true,
  })
  public tasks? = new Collection<Task>(this);

  @Field(() => [Group], { nullable: true })
  @OneToMany({
    entity: () => Group,
    mappedBy: "leader",
    nullable: true,
  })
  public groups? = new Collection<Group>(this);
}
```

I guess there would then be an option inside `mikro-orm.config.ts` that is like `outputGraphql: true` which enables this inferrance. 

**Describe the solution you'd like**
I would like the `@Field()` to be assumed, unless I say otherwise. One example could be `@Private()` decorator. 
```ts
@Entity()
export class User extends BaseEntity {
  @Property()
  name: string;

  @Property()
  email!: string;
  
  @Property()
  @Private()
  password!: string;

  @OneToMany({
    entity: () => Task,
    mappedBy: "owner",
    nullable: true,
  })
  tasks? = new Collection<Task>(this);

  @OneToMany({
    entity: () => Group,
    mappedBy: "leader",
    nullable: true,
  })
  groups? = new Collection<Group>(this);
}
```

**Describe alternatives you've considered**
The first alternative could be for the `public` and `private` scopes to define whether it gets output to GraphQL or not. But this is probably worse practice than above. 
```ts
@Entity()
export class User extends BaseEntity {
  @Property()
  public name: string;

  @Property()
  public email!: string;
  
  @Property()
  private password!: string;

  @OneToMany({
    entity: () => Task,
    mappedBy: "owner",
    nullable: true,
  })
  public tasks? = new Collection<Task>(this);

  @OneToMany({
    entity: () => Group,
    mappedBy: "leader",
    nullable: true,
  })
  private groups? = new Collection<Group>(this);
}
```

**Comment by B4nan** [comment]
While I do understand why you want it, this is definitely not something to be part of this repository. Good idea for a 3rd party module for sure - if I would be using type-graphql myself, I would have probably made such 3rd party module already - but I am not :] 

Btw you are basically asking for me to fill the `type-graphql` metadata - that itself sounds very wrong idea, and might not be even possible (depends on where/how `type-graphql` stores the metadata).
