### ISSUE TITLE
Search feature is not working

### ISSUE THREAD

**Issue by standup75** [mikro-orm/mikro-orm#1360]
Try this:

https://mikro-orm.io/search?q=populate

**Comment by Langstra** [comment]
Interesting, never seen that page before on the docs. If you use the search bar on the docs page that is in the top right corner the search works. Or you could use ctrl+k and then type your query.

**Comment by B4nan** [comment]
Thats the SERP, when you click "all results" in the search modal it will go there - also this page allows searching historic versions which is quite nice. 

But there is nothing I can do about this, we'll need to wait for docusaurus update (they are quite frequent), for me this is just "put the algolia token here".
