### ISSUE TITLE
Enable explicit transactions using repositories

### ISSUE THREAD

**Issue by pablor21** [mikro-orm/mikro-orm#1361]
At the moment, there is no way to open a transaction from a repository, only via flush methods.
The problem I see is that we have no way to do the following:

1. open a transaction
2. save the entity sending the query  to the db (for example to get the autoincrement id)
3. do another operation (let's say save a file or whatever)
4. commit if 3 succeeded or rollback otherwise

I've tried some workarounds (using nestjs BTW) but no luck at the moment.

**Comment by B4nan** [comment]
You should inject the `EntityManager` and work with that, in the end repositories are just a thin layer on top of the EM.

**Comment by sergeyampo** [comment]
> You should inject the `EntityManager` and work with that, in the end repositories are just a thin layer on top of the EM.

Data Mapper pattern with repositories implementation is more preferable to Active Record, I think you should think about transactions functionality on repositories level.

**Comment by B4nan** [comment]
This has nothing to do with active record.
