### ISSUE TITLE
Search in Array at certain position

### ISSUE THREAD

**Issue by JustGreg** [mikro-orm/mikro-orm#1363]
**Is your feature request related to a problem? Please describe.**
I cant querying array fields at a certain position. 

**Describe the solution you'd like**
in books entity:
```typescript
  @Property({ nullable: true })
  tags: string[];
```
Query:
```typescript
const books = await em.find(Book, {
  [expr('tags[1]')]: 'important',
});
```
This returns an error:
`Trying to query by not existing property Book.tags[1]`

It works with querybilder:
```typescript
orm.em.createQueryBuilder(Book, 'b').select(['b.*']).where('b.tags[1] = ?', ['important'])
```

**Comment by B4nan** [comment]
Try this:

```ts
const books = await em.find(Book, {
  [expr('tags[1] = ?')]: 'important',
});
```

**Comment by JustGreg** [comment]
Thank you! This works!

Btw, i love this project! Its clean and simple yet powerful! great work!
