### ISSUE TITLE
isConnected method does not have timeout(MySQL driver)

### ISSUE THREAD

**Issue by mivanovaxway** [mikro-orm/mikro-orm#1364]
**Describe the bug**
After connecting to MySQL via VPN, and calling isConnected(), then disconnecting the VPN and calling isConnected() again, the second call is never resolved/rejected.

**To Reproduce**
1. Call MikroORM.init
2. Call isConnected()
3. Disconnect the VPN
4. Call isConnected() again

**Expected behavior**
The promise from the second call to isConnected should eventually be resolved/rejected

**Additional context**
Normally a NodeJS process will quit after all timers/promises/etc. have been resolved.
However the isConnected creates a Promise that is never resolved/rejected.
I've tried using acquireTimeoutMillis to no avail.
```
    const orm = await MikroORM.init<MySqlDriver>({
        entities: ['mikro-orm/entities'], // path to your JS entities (dist), relative to `baseDir`
        baseDir: __dirname,
        dbName: env.MYSQL_DB_NAME,
        pool: {
            min: 1,
            acquireTimeoutMillis: 500,
            reapIntervalMillis: 500,
            idleTimeoutMillis: 500,
            max: 5,
        },
        type: 'mysql',
        driverOptions: {},
        debug: !!env.MYSQL_DEBUG,
        clientUrl: env.MYSQL_DB_CONN_URI,
    });
```
**Versions**

| Dependency | Version |
| - | - |
| node | 12.20.1 |
| typescript | 4.1.3 |
| mikro-orm | 4.3.4 |
| @mikro-orm/mysql | 4.3.4 |

**Comment by B4nan** [comment]
Wait a minute, so this is about your VPN? That method does a simple db query, it's not special anyhow. If there is an issue with that, it's not in our end. 

https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/AbstractSqlConnection.ts#L35

The method works fine for me, closing as not reproducible - will be happy to reopen if you provide something executable that will reproduce.

**Comment by mivanovaxway** [comment]
Hello @B4nan, it's not about the VPN. 

I think that in general if the network is disconnected, the bug will occur. Ie - just do ``ifconfig eth0 down``, stop the router, unplug the Ethernet cable, etc.

Basically then if you do a query, it never timeouts.

**Comment by B4nan** [comment]
Well, as I said, if you think there is an issue, it's elsewhere (let it be knex or the mysql2 package underneath). All what MikroORM does is to execute a `select 1` query. But talking about VPNs, routers and ethernet cables, I doubt they will listen :] This sounds like your local network issue. 

When I don't have the mysql instance running locally, that command will fail early, as expected. 

Btw saying "its not about VPN", when your bug report starts with "After connecting to MySQL via VPN..." 🤷

**Comment by mivanovaxway** [comment]
I know, right :) Anyway, can I use MikroORM with mysql instead of mysql2?

**Comment by B4nan** [comment]
You could create new driver, extending the existing one and changing the `connect` method of connection class to do:

```ts
  async connect(): Promise<void> {
    this.client = this.createKnexClient('mysql');
  }
```

Not sure why would you want to do that, mysql2 should be compatible and is faster.

**Comment by mivanovaxway** [comment]
I am thinking that mysql2 uses the Node's net module, while mysql uses a binary driver(probably written in C/C++) with Node bindings. So perhaps mysql2 has a bug - not setting some of the timeouts when creating the socket or something.
I could be wrong though.

**Comment by B4nan** [comment]
Then I would suggest to verify that first, instead of writing new driver that might malfunction (while they say its compatible, there will be differences for sure). Try to do a `select 1` query with just the driver, or via knex (no MikroORM involed). 

> Btw, how is the existing driver called?

https://github.com/mikro-orm/mikro-orm/tree/master/packages/mysql

**Comment by mivanovaxway** [comment]
Tested with mysql driver via MikroORM. Same result. Will test tonight with just the two drivers(no mikro or knex) and see how it goes.
