### ISSUE TITLE
Array of embeddables

### ISSUE THREAD

**Issue by ramiel** [mikro-orm/mikro-orm#1369]
**Is your feature request related to a problem? Please describe.**
I'm not sure wether it's possible to have an embeddable as array, e.g.

```
  @Embedded(() => [Item], { object: true })
  items: Array<Item> = [];
```
where Item is an embeddable (like the above or using Collection). On DB, items would be an array of Item objects. At the moment this seems to be not possible but maybe I'm doing something wrong

**Describe the solution you'd like**
The same described above or with a Collection

**Comment by icex** [comment]
I'm also looking for a solution for this. I'm currently trying to use JsonType, but I have issues with updates not registered in computeChangeSets :(
