### ISSUE TITLE
Can't define Embeddable using EntitySchema

### ISSUE THREAD

**Issue by renegat59** [mikro-orm/mikro-orm#1370]
I can't find any relevant documentation about it, but there is a sentence in the docs, that makes me believe that I can define `Embeddables` using `EntitySchema` instead of annotations:

> Embeddables needs to be discovered just like regular entities

What is more the metadata object has an boolean property `embeddable` which again gives me a hint that I should be able to do it. However whenever I try I fail. My embeddable:
```
export const schema = new EntitySchema<CelebrationReasonDate>({
    class: CelebrationReasonDate,
    embeddable: true,
    properties: {
        value: { type: DateType },
    },
});
```

The `EntitySchema` for the Entity that wants to embed it:
```
export const schema = new EntitySchema<CelebrationReason>({
    class: CelebrationReason,
    properties: {
        // Some properties
        date: {
            reference: ReferenceType.EMBEDDED,
            entity: 'CelebrationReasonDate',
        },
    },
});
```

When I run `npx mikro-orm schema:create -r` it works fine, but when I start the app (with Nest.js) I'm getting the following error:
```
[Nest] 55945   - 01/31/2021, 7:40:06 PM   [ExceptionHandler] Duplicate entity names are not allowed: CelebrationReasonDate +19ms
MetadataError: Duplicate entity names are not allowed: CelebrationReasonDate
```

I have the entity discovery done by directories. Both entity schemas for embeddable and the entity are in the same folder and at the moment this are the only two entity schemas I have. Also I don't use any annotation in any file.

Am I doing something wrong or is it some error of the ORM?

**Comment by B4nan** [comment]
Maybe you are reexporting the embeddable somewhere? Provide full repro if you want better advice, this is probably not about entity definition.

**Comment by renegat59** [comment]
@B4nan thanks for a fast response. So theoretically this kind of definition of Embeddable is correct? I can't really share the full repository at the moment, sorry.. I will investigate more if you say it's a problem with my code.
Thank you

**Comment by B4nan** [comment]
> So theoretically this kind of definition of Embeddable is correct? 

Yes, looks good, invalid schema definition would not trigger this validation, it literally meas there were two classes with the same name. 

You can see examples of embeddables with `EntitySchema` in tests:

https://github.com/mikro-orm/mikro-orm/blob/master/tests/embedded-entities.mongo.test.ts#L177

> I can't really share the full repository at the moment, sorry.. I will investigate more if you say it's a problem with my code.

I am not interested in your app, I want to see minimal reproduction of the issue. 

But I am quite sure the issue here is reexporting of the embeddable... Or badly defined folders in the ORM config (e.g. if both JS and TS files are matching, it would also probably end up with this validation - that is the main reason why it was added).

**Comment by renegat59** [comment]
@B4nan thank you very much for the example of embeddable from the tests. I created an example repo trying to reproduce the issue and it doesn't occur. That only proves that the problem is somewhere within my project. I hope I can find it soon.
Since this is not an issue with MikroOrm I'm closing the topic.

**Comment by whocaresk** [comment]
For those, who came here like i from google and found 404 on test link, here is [permalink](https://github.com/mikro-orm/mikro-orm/blob/2f59953fe6deb147305bd7d02ad868ff506186b1/tests/features/embeddables/embedded-entities.mongo.test.ts)
