### ISSUE TITLE
[docs] entity-reference and reference-wrapper are duplicated

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#138]
In dev branch. Small issue... probably just merge those two into one.

**Comment by B4nan** [comment]
not sure what you mean?

**Comment by lookfirst** [comment]
https://github.com/mikro-orm/mikro-orm/blob/dev/docs/reference-wrapper.md
vs.
https://github.com/mikro-orm/mikro-orm/blob/dev/docs/entity-references.md#better-type-safety-with-referencet-wrapper

Just seems duplicated. I'd combine together.

**Comment by B4nan** [comment]
well entity reference and reference wrapper are actually two different things as of now. 

but you are right it looks a bit weird, i will move the reference wrapper page into entity references one.

**Comment by B4nan** [comment]
Merged into entity-references section

**Comment by lookfirst** [comment]
Excellent!
