### ISSUE TITLE
Type-Safety for nativeUpdate => camelCase gets in the way

### ISSUE THREAD

**Issue by SantoJambit** [mikro-orm/mikro-orm#1383]
**Describe the bug**
I just tried to do an update like this:

```
await em.nativeUpdate<Skill>("skill", { id: skills }, { lastSearchedAt: new Date() });
```

I specified `<Skill>` in order to get valid type-safety, but that fails at runtime. It tells me the column "lastSearchedAt" doesn't exist.
Removing the `<Skill>` and using underscores `last_searched_at` makes it work, but by doing that, I lose the type-safety.

**To Reproduce**
1. Create a model with a camelCase property
2. Try to bulk-update it with nativeUpdate using TypeScript.

**Expected behavior**
The typed call should work including type-safety and auto-completion.

It seems like a good idea to me to perform the camelCase to snail_case transformation here too, but I wonder if that might break stuff.

Another possibility would be to use TypeScript 4.1 to transform the attribute names to snail_case like with type-fest: https://github.com/sindresorhus/type-fest/blob/main/ts41/snake-case.d.ts

**Versions**

| Dependency | Version |
| - | - |
| node | 15.2.0 |
| typescript | 4.1 |
| mikro-orm |  4.4.1 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
Please provide full repro, this should work fine, the method works with entity properties, not with columns, and there are tests for this. I can imagine it would not work if you did not initialize the ORM first as then no metadata would be loaded.

https://github.com/mikro-orm/mikro-orm/blob/master/tests/EntityManager.sqlite2.test.ts#L831

(in that test the call is not typed, but adding the type makes no difference, it works fine, and the query uses snake_case based on the naming strategy)

Btw you can be do also this:

```ts
await em.nativeUpdate(Skill, { id: skills }, { lastSearchedAt: new Date() });
```

**Comment by B4nan** [comment]
Actuall I know what your problem is, you are passing entity name as `skill`, but it is `Skill`.

As mentioned above, preferred way should be doing this instead:

```ts
await em.nativeUpdate(Skill, { id: skills }, { lastSearchedAt: new Date() });
```

But this will work too:

```ts
await em.nativeUpdate<Skill>('Skill', { id: skills }, { lastSearchedAt: new Date() });
// or just await em.nativeUpdate('Skill', { id: skills }, { lastSearchedAt: new Date() });
```

**Comment by SantoJambit** [comment]
Ah, the code completion said entity name, so I thought I would have to pass a string. That seems to work. Thanks!
