### ISSUE TITLE
Properties using `CustomType` are migrated as JSON columns

### ISSUE THREAD

**Issue by mukaschultze** [mikro-orm/mikro-orm#1385]
**From the documentation:**

> To store dates without time information, we can use DateType. It does use date column type and maps it to the Date object.
> ```ts
> @Property({ type: DateType, nullable: true })
> born?: Date;
> ```

If I try to create a migration, the `born` field will be created as a JSON, and not as and date as the documentation suggests.

```ts
this.addSql('create table `user` (`id` varchar(255) not null, `born` json not null, ...
```

I've tried with the different custom types that come bundled with MikroORM, but all of them seem to be understood as a JSON when creating migrations.

**To Reproduce**
1. Create an entity and add the code above from the [documentation](https://mikro-orm.io/docs/custom-types#datetype)
2. Run `npx mikro-orm migration:create --initial`
3. Open the Migration file, the field is set to be created as an json

**Expected behavior**
The property should be created as a `date` column.

**Additional context**
Happens using either `postgresql` or `mysql` drivers.

**Versions**

| Dependency | Version |
| - | - |
| node | v12.19.1 |
| typescript | ^4.0.5 |
| mikro-orm | ^4.4.1 |
| @mikro-orm/mysql | ^4.4.1 |

**Comment by B4nan** [comment]
Please provide full reproduction, this is tested and works fine in tests:

```ts
  @Property({ type: DateType, index: true, nullable: true })
  born?: Date;
```

```sql
create table \`author2\` (
  \`id\` int unsigned not null auto_increment primary key,
  \`created_at\` datetime(3) not null default current_timestamp(3),
  \`updated_at\` datetime(3) not null default current_timestamp(3),
  \`name\` varchar(255) not null, \`email\` varchar(255) not null,
  \`age\` int(11) null default null,
  \`terms_accepted\` tinyint(1) not null default false,
  \`optional\` tinyint(1) null,
  \`identities\` text null,
  \`born\` date null,
  \`born_time\` time null,
  \`favourite_book_uuid_pk\` varchar(36) null,
  \`favourite_author_id\` int(11) unsigned null
) default character set utf8mb4 engine = InnoDB;
alter
```

https://github.com/mikro-orm/mikro-orm/blob/master/tests/entities-sql/Author2.ts#L45
https://github.com/mikro-orm/mikro-orm/blob/master/tests/__snapshots__/SchemaGenerator.test.ts.snap#L51

Also, do you really want to use the `DateType`? It is rather a toy type, it does store dates (only dates, no time or TZ), mapping them to `Date` object.

**Comment by mukaschultze** [comment]
Here's a minimal repo with the issue happening, it contains a `start` script in the package.json that creates a migration file where the column type is `json`. There's also added a custom type to test if the `getColumnType` method is ignored altogether.

https://github.com/mukaschultze/mikro-orm-issue-1385

It was tested both with `ReflectMetadataProvider` and `TsMorphMetadataProvider`, the two had the same result.  
The package-lock only contains one entry of `@mikro-orm/core`, so I guess the versions are aligned.

I don't really need the `DateType`, but this seems to affect other custom types as well, and they are pretty handful.

I've also added the `import 'reflect-metadata'` at the top, didn't make much of a difference.

**Comment by B4nan** [comment]
In that project you don't even have `@mikro-orm/cli` as a dependency. That makes me even more sure you have misaligned depedencies, the CLI should be installed locally.

**Comment by mukaschultze** [comment]
That was it, thanks! I had `@mikro-orm/cli@4.4.1` installed globally.  
Btw, I couldn't find anything in the documentation that says the CLI has to be installed locally, in fact, it has an "example" for global installs:
```sh
# or when installed globally
$ mikro-orm
```
Anyway, thanks for the help	you may close this issue if you want.

**Comment by B4nan** [comment]
Mmmm I guess I should remove that note and state that the CLI should be installed always locally. 

The issue here is that if you have one global installation, it will have its own `@mikro-orm/core` package. Then there will be another one in your local project dependencies. Now the problematic part is that if your entity uses custom type instance from the locally installed package, the global one will have another version of that type class - and using `instanceof` checks will fail.

Very same problem happens if you have misaligned versions, e.g. `core@4.2` and `cli@4.3` (unless they both resolve to the same version).
