### ISSUE TITLE
Pagination, orderBy with querybuilder

### ISSUE THREAD

**Issue by sptGabriel** [mikro-orm/mikro-orm#1388]
entity:

```
@Entity({ tableName: 'departaments' })
export class Departament {
  @PrimaryKey()
  public readonly id: string;
  @Property()
  @Unique({ name: 'name' })
  public departament_name: string;
  @OneToMany(() => Employee, employee => employee.departament)
  public employees = new Collection<Employee>(this);
  @Property()
  public createdAt = new Date();
  @Property({ onUpdate: () => new Date() })
  public updatedAt = new Date();
  @Property()
  public deletedAt?: Date;
  constructor(departament_name: string, id?: string) {
    if (!id) this.id = v4();
    this.departament_name = departament_name;
  }
  static build = (departament_name: string, id?: string): Departament => {
    const isValidUUID = id ? validate(id) : null;
    if (isValidUUID === false) throw new Error(`Invalid UUID V4`);
    if (!isString(departament_name))
      throw new Error(`name expect a string type`);
    return new Departament(departament_name, id);
  };
}
```

function:

 ```
 public all = async (pagination: Pagination): Promise<Departament[]> => {
    const qb = await this.em.createQueryBuilder(Departament);
    qb.select('*')
      .limit(pagination.perPage())
      .offset(pagination.offset())
      .orderBy("created_at", "desc")
    const departaments = await qb.getResult();
    console.log(departaments)
    return departaments;
  };
```

i got this error on orderBy:

`"select \"e0\".* from \"departaments\" as \"e0\" order by 0 c, 1 r, 2 e, 3 a, 4 t, 5 e, 6 d, 7 _, 8 a, 9 t limit 10 - syntax error at or near \"c\""`

if i use groupBy, is ok, but orderBy got this error...
is possible pagination without qb?

**Comment by sptGabriel** [comment]
I solved it with this:

```
    const res:Departament[] = await this.em.find(
      Departament,
      {},
      {
        orderBy: { createdAt: QueryOrder.ASC},
        offset: pagination.offset(),
        limit: pagination.perPage(),
        flags: [QueryFlag.PAGINATE],
      },
      ['employees']
    );
    for(let dep of res){
      await dep.employees.init()
    }
    console.log(res)
```

but there was a doubt about the populates, there are many employees to one departments, and I would like to know if there is a simpler way to load all the employees in the department, without needing 2 queries?
I tried ['employees'] but it is not initialized I have to use the init that generates two queries:

```
[query] select "e0".* from "departaments" as "e0" where "e0"."id" in (select "e0"."id" from (select "e0"."id" from (select "e0"."id" from "departaments" as "e0" order by "e0"."created_at" asc) as "e0" group by "e0"."id" limit 10) as "e0") order by "e0"."created_at" asc [took 3 ms]
[query] select "e0".*, "e1"."id" as "user_id" from "employees" as "e0" left join "users" as "e1" on "e0"."id" = "e1"."id" where "e0"."departament_id" = '8b87c2c0-b824-4145-bc41-92e6d62e384b' order by "e0"."id" asc [took 2 ms]
```

**Comment by B4nan** [comment]
You must be using some very weird typescript config or badly typed EM or something like that, as your code would never even compile under strict mode. The `qb.orderBy` method has different signature, it has only one parameter and it needs to be object. Also it needs to be object with property keys, not column names - so `createdBy`, not `created_by`.

Your second try is also wrong call, it should look like this:

    const res:Departament[] = await this.em.find(
      Departament,
      {},
      {
        orderBy: { createdAt: QueryOrder.ASC},
        offset: pagination.offset(),
        limit: pagination.perPage(),
        flags: [QueryFlag.PAGINATE],
        populate: ['employees'],
      },
    );
