### ISSUE TITLE
Relations are not persisted

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#140]
[relations-mikro.zip](https://github.com/mikro-orm/mikro-orm/files/3635557/relations-mikro.zip)

Looking in the database, createdBy is not populated.

`[query] insert into `Thing` (`createdBy`, `id`) values (?, ?) [took 0 ms]`

Just null is put there.

(This is also a perfect example of where logging parameters would be nice.)

**Comment by lookfirst** [comment]
This is also something lacking in the documentation. selects are documented, but inserts are not... which is part of why I think this bug snuck by.

**Comment by B4nan** [comment]
Can you please publish that project on github so I can browse the code online? Or ideally post snippets here directly. 

> This is also something lacking in the documentation. selects are documented, but inserts are not... which is part of why I think this bug snuck by.

Persisting is documented here: https://mikro-orm.io/entity-manager/

**Comment by lookfirst** [comment]
General persisting is documented, but reference persisting is not. ALL of the examples use find. There isn't anything that does a persistAndFlush().

https://mikro-orm.io/entity-references/
https://github.com/mikro-orm/mikro-orm/blob/dev/docs/entity-references.md
https://github.com/mikro-orm/mikro-orm/blob/dev/docs/reference-wrapper.md

**Comment by B4nan** [comment]
The point of reference is that this works automatically, it behaves just like an entity (but has only PK).

**Comment by lookfirst** [comment]
https://github.com/lookfirst/mikro-example

**Comment by lookfirst** [comment]
```
[query] begin
[query] insert into `Person` (`id`) values (?) [took 0 ms]
[query] commit
[query] begin
[query] insert into `Thing` (`createdBy`, `id`) values (?, ?) [took 1 ms]
[query] commit
[query] select `e0`.* from `Thing` as `e0` where `e0`.`id` = ? limit ? [took 1 ms]

TypeError: Cannot read property 'id' of null
    at Context.<anonymous> (test/index.spec.ts:37:40)
```

**Comment by lookfirst** [comment]
I am sure, once again, that I'm doing something stupid. =)

**Comment by B4nan** [comment]
Well this looks like a bug indeed, `Reference` creates PK getters in its constructor (so you can do `ref.id` if your PK is `id`), but they are not working when computing the change-set...

**Comment by lookfirst** [comment]
I glanced at the tests and didn't see anything like this. =(

**Comment by B4nan** [comment]
Ok found it, strange that tests were fine... Might be some dependency difference (the problem is that cloned entity reference failed to have the PK getter). God knows, will send a fix soon and publish new alpha.

**Comment by lookfirst** [comment]
confirmed fixed!
