### ISSUE TITLE
No overload matches this call error : when using findOne in generic repository/service.

### ISSUE THREAD

**Issue by trompx** [mikro-orm/mikro-orm#1405]
**Describe the bug**

I would like to create a generic repository, define some common methods then extend my other repositories with it.
When I use findOne in a generic service/repository, like the following implementation:
```js
import {
  AnyEntity,
  EntityName,
} from "@mikro-orm/core";
import { Service } from "typedi";
import { EntityRepository, EntityManager } from "@mikro-orm/postgresql";

@Service()
export class BaseRepository<
  T extends AnyEntity<T>
> extends EntityRepository<T> {
  constructor(
    protected entityManager: EntityManager,
    protected entityName: EntityName<T>
  ) {
    super(entityManager, entityName);
    this.entityName = entityName;
    this.entityManager = entityManager;
  }

  async findById(id: number): Promise<T | null> {
    return await this.findOne({ id });
  }
}
```

I'm getting this error:
```
No overload matches this call.
  Overload 1 of 2, '(where: FilterQuery<T>, populate?: any, orderBy?: QueryOrderMap | undefined): Promise<T | null>', gave the following error.
    Argument of type '{ name: string; }' is not assignable to parameter of type 'FilterQuery<T>'.
      Object literal may only specify known properties, and 'name' does not exist in type '{ [PrimaryKeyType]?: any; }'.
  Overload 2 of 2, '(where: FilterQuery<T>, populate?: FindOneOptions<T, any> | undefined, orderBy?: QueryOrderMap | undefined): Promise<T | null>', gave the following error.
    Argument of type '{ name: string; }' is not assignable to parameter of type 'FilterQuery<T>'.
      Object literal may only specify known properties, and 'name' does not exist in type '{ [PrimaryKeyType]?: any; }'.
```

While when I use it in a concrete class, I have no error.

```js
import { BaseRepository } from "modules/base/base.repository";
import { Service } from "typedi";
import { Specific } from "./specific.entity";
import { Repository } from "@mikro-orm/core";
import { EntityManager } from "@mikro-orm/postgresql";

@Repository(Specific)
@Service()
export class SpecificRepository extends BaseRepository<Specific> {
  public constructor(public readonly entityManager: EntityManager) {
    super(entityManager, "Specific");
  }

  async findById(id: number): Promise<Specific | null> {
    return await this.findOne({ id });
  }
}
```
The goal would be to have the findById method defined in the baseRepository to not repeat the same code in each repository.
I don't know if this a bug or if my implementation is just wrong. Anyway, an example of how to use mikro-orm in a generic service/repository would be awesome.

**Versions**

| Dependency | Version |
| - | - |
| node | 12.20.1 | 
| typescript | 3.9.7 | 
| mikro-orm | 4.4.2 |

**Comment by B4nan** [comment]
This is unfortunately issue with typescript itself (and its strutural types), I am not aware of any solution other than explicit type casting. 

Will try to look up some links/examples for this before I close it, so we have a reference issue for this problem.

**Comment by trompx** [comment]
Thanks for the fast answer @B4nan. I could live with explicit type casting, as I'd just do that in one or two files. I'll follow this closely and will share if I find a way to solve this on my side.

**Comment by B4nan** [comment]
Afaik it all boils down to this: 

```ts
export type FilterQuery<T> = { [K in keyof T]?: T[K] };

class Base<T> {
    id!: number;
}

export class EntityRepository<T> {
  async findOne(where: FilterQuery<T>): Promise<T | null> {
    return {} as any;
  }
}

export class BaseRepository<T extends Base<T>> extends EntityRepository<T> {
  async findById(id: number): Promise<T | null> {
    return await this.findOne({ id }); // fails with `Argument of type '{ id: number; }' is not assignable to parameter of type 'FilterQuery<T>'.(2345)`
    // doing this will pass: `return await this.findOne({ id } as FilterQuery<T>);`
  }
}
```

https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcBiBLANjYUCKArnogDwAqAfHALxwDecA2gNJwYB2cA1sIhADM45ALoB+AFzDWIuAF8A3ACglAYywBDAM5a4AIW3AK1ekrjn2AEwCEUjoQC2AIzzK5K0JFhx123QFEOGAwkACVgSC0Q6DIqBjM4bUQOVTgBTksAeQ5gAAoAdwALPGApTBw8IhJjAEopAAUoCAcMLSNyOAAfOHssLBME8yhgGEIoLno5RN0NDkRlc3d3JU9oeF8dfUNwyOioWLhQXA5LXQM242oj4BOAoJDEHYgomBjjePMklLSMvUQASUsuQwljsjhcUDqcEazVa7S6PUIfQGFjgw1G40S+Q0IQQhVaADp0idsnlGCD5DUFvIlHIgA

**Comment by trompx** [comment]
Awesome, thanks @B4nan! `return await this.findOne({ id } as FilterQuery<T>);` did it.

And thanks for the tip! I'll just add it as a service method, but I still have other methods to implement like findByName where name is not pk.
I'll let you close if you're satisfied with the example.
