### ISSUE TITLE
Using LoadStrategy.JOINED throws an exception on nested relationships?

### ISSUE THREAD

**Issue by thatsnotright** [mikro-orm/mikro-orm#1414]
**Describe the bug**
I think there is a bug related to specifying the join strategy for deeply nested objects.  Say we have a table and wish to specify criteria 3 tables away, and join all the relations in one query.

If I generate a simple list for the populate, which has the dot relations as well, such as: ```["container", "lineage", "lineage.origin", "lineage.origin.age"]``` then there are the expected additional queries generated for each relation.  However, if I generate this as ```[{"container": LoadStrategy.JOINED}, {"lineage":LoadStrategy.JOINED},{"lineage.origin":LoadStrategy.JOINED},{"lineage.origin.age":LoadStrategy.JOINED}]```

I get an exception.

**Stack trace**
```
Cannot read property 'type' of undefined","stack":["$ROOT/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:388:51","Array.forEach (<anonymous>)","MySqlDriver.getFieldsForJoinedLoad ($ROOT/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:385:21)","MySqlDriver.buildFields ($ROOT/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:514:30)","MySqlDriver.find ($ROOT/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:27:29)","SqlEntityManager.find ($ROOT/node_modules/@mikro-orm/core/EntityManager.js:92:43)
```

**To Reproduce**
I will work on modifying a test you have to create a test case, just thought this might get your brain turning.

**Expected behavior**
I expect that the two methods above work, because I don't see where in the documentation it should not.

**Versions**

| Dependency | Version |
| - | - |
| mikro-orm | 4.4.0 |

**Comment by B4nan** [comment]
I'd say this should work:

```ts
em.find(Entity, ..., { populate: ['container, 'lineage.origin.age'], strategy: LoadStrategy.JOINED });
```

What you were trying seems unsupported, you are mixing two approaches (dot notation was meant for a simple array of strings only).

I will most probably remove this way of setting strategy per populated property and keep just the option in `FindOptions`.

**Comment by thatsnotright** [comment]
Ah, OK.  It does work specifying the array and the strategy as you outline, thank you.  

The list of entities to join is created from the JSONLogic to where condition, I suppose I could cull this list.  Thanks for the help!
