### ISSUE TITLE
@mikro-orm/reflection have ts-morph as dependency instead of devDependencies

### ISSUE THREAD

**Issue by mercuriete** [mikro-orm/mikro-orm#1420]
This issue was reported here:
https://github.com/dsherret/ts-morph/issues/931

according to this line: https://github.com/mikro-orm/mikro-orm/blob/56e1e1f5570c1bdbe5ca7b56de2d3491642fd106/packages/reflection/package.json#L51

@mikro-orm/reflection depends on ts-morph that depends on typescript.

When you install @mikro-orm/reflection as dependency you end up with typescript as dependency on your node_modules in production mode

steps to reproduce:

create a repo depending on:
```    "@mikro-orm/reflection": "4.4.2",```

1- ``` yarn install --frozen-lockfile ```
2- ``` yarn install --frozen-lockfile --production ```

Actual Behaviour.
typescript folder is inside node_modules

Expected behaviour:
typescript is deleted when you do: yarn --production

**Comment by B4nan** [comment]
Yes, by using ts-morph, you also use the TS compiled api. I don't see anything wrong here, it is an actual dependency, it is required in production too, unless you deploy warmed up cache. 

If you don't want to have it in your production build, use the default reflect-metadata provider.

**Comment by mercuriete** [comment]
thanks for your support :-1:
