### ISSUE TITLE
ManyToMany : possibility to add createdAt / updatedAt

### ISSUE THREAD

**Issue by trompx** [mikro-orm/mikro-orm#1431]
**Is your feature request related to a problem? Please describe.**
All my entities extend a base entity with ceatedAt and updatedAt fields. For now when using the following
```ts
  @Field(() => [Entity], { nullable: true })
  @ManyToMany({ entity: () => Entity, owner: true })
  entityLikes = new MikroCollection<Entity>(this);
```
The resulting table **user_entity_likes** has only the fields **user_id** and **entity_id**.

**Describe the solution you'd like**
Would it be possible to add createdAt and updatedAt fields to the automatically generated table?

**Describe alternatives you've considered**
For now if I want an intermediary table with additional fields, I use ManyToOne - OneToMany.

**Comment by B4nan** [comment]
If you want more from the pivot table, it is no longer a pivot table. How would you read those values? Also updatedAt column would have no sense - the values in pivot table are never updated, only removed or added. 

If you care about preserving insertion order, you can use `fixedOrder: true`:

https://mikro-orm.io/docs/collections/#forcing-fixed-order-of-collection-items

Your alternative is the correct way to do it. That way you have transparent way to access and write to the additional columns. 

https://mikro-orm.io/docs/composite-keys#use-case-3-join-table-with-metadata

**Comment by trompx** [comment]
Thanks for the answer @B4nan, I'll go for the alternative way then, as the usecase for the like table was to aggregate likes per day / week etc. so I need at least the created_at column.
