### ISSUE TITLE
Related entities not persisted when using `Collection.add()`

### ISSUE THREAD

**Issue by danielgelling** [mikro-orm/mikro-orm#1438]
**Bug description**
When fetching a record from the database via `orm.em.findOne()` and adding a relation record to it, using `collection.add()` the added relation mapping is not persisted to the database.

**Stack trace**
*No stack trace was provided. MikroOrm thinks it has persisted everything correctly.*

**To Reproduce**
*In this example we assume a `Book` can only have one `Author`, but an author can have many books.*

1. Create two entities with a OneToMany and ManyToOne relation to each other.
2. Fetch the owning side, eg. using `author = orm.em.findOneOrFail(Author, {'name': 'William Shakespeare'}, ['books'])`
3. Create a new inverse side eg: `book = new Book('Romeo and Juliet', 'Some world renown content')`
4. Add the inverse side to the owning side, eg: `author.books.add(book)`
5. Persist both entities (*just to be sure, this step should not be necessary*) `orm.em.persist(author); orm.em.persist(book)`
6. Flush the entity manager `await orm.em.flush()`
7. Create a new ORM instance with `MikroOrm.init(...)` (or restart the node process)
8. Query the author `author = orm.em.findOneOrFail(Author, {'name': 'William Shakespeare'}, ['books'])`
9. Log the books of the author `console.log(author.books.getAll())`. This returns an empty array.

**Expected behavior**
- To fill the relation reference eg: `authorId` in the `Book` collection
- To get an array containing the `Book` we just added, using `author.books.getAll()`

**Versions**

| Dependency | Version |
| - | - |
| node | 12.0.0 |
| typescript | 3.9.8 |
| mikro-orm | 4.4.2 |
| driver | MongoDriver (also tested with MySQL)|

**Comment by B4nan** [comment]
Please provide the reproduction as code, including the entity definitions, ideally as a [single file test case](https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues).

> Query the author author = orm.em.findOneOrFail(Author, {'name': 'William Shakespeare'}

Here you say you do not populate the books property, why do you expect it to contain something? It should actually throw that it is not populated.

**Comment by danielgelling** [comment]
> Here you say you do not populate the books property, why do you expect it to contain something? It should actually throw that it is not populated.

I'm sorry, didn't add it to the issue, but tested it with `author = orm.em.findOneOrFail(Author, {'name': 'William Shakespeare'}, ['books'])`

**Comment by B4nan** [comment]
There are many tests that would match your reproduction, they all pass. My guess is some issue in entity definition, the relation needs to be properly linked. 

> To fill the relation reference eg: authorId in the Book collection

This sounds a bit like you are using `mapToPk`? If so, you are responsible to fill the FK. Propagation works only with regular relations.

Also ensure you have aligned ORM package versions, sometimes weird things happen if you have multiple copies of the ORM installed.

> Add the inverse side to the owning side, eg: author.books.add(book)

This is actually the opposite, here you are adding the owner to the inverse side. Author is the inverse, book is the owner - where the FK is stored.

**Comment by danielgelling** [comment]
Here are two Entity definitions, set-up as described in: https://mikro-orm.io/docs/defining-entities

```
import {Entity, ManyToOne, PrimaryKey, Property} from "@mikro-orm/core";
import {Author} from "./Author";

@Entity()
export class Book {
    @PrimaryKey()
    public id: number;

    @ManyToOne(() => Author, {nullable: true})
    public author?: Author;

    @Property()
    public title!: string;

    @Property()
    public content!: string;

    constructor(title: string, content: string)
    {
        this.title = title;
        this.content = content;
    }
}

import {Collection, Entity, OneToMany, PrimaryKey, Property} from "@mikro-orm/core";
import {Book} from "./Book";

@Entity()
export class Author
{
    @PrimaryKey()
    public id: number;

    @Property()
    public name: string;

    @OneToMany(() => Book, (book) => book.author)
    public books: Collection<Book> = new Collection<Book>(this);

    constructor(name: string)
    {
        this.name = name;
    }
}
```

First we create a new `Author` in our database:
```
orm.em.persistAndFlush(new Author('William Shakespeare'));
```

Then (restarting the node process, so the UoW is empty), we query that Author and add a `Book` to it.
```
const author = await orm.em.findOneOrFail(Author, {name: 'William Shakespeare'}, ['books']);
const book = new Book('Romeo and Juliet', 'Some world renown content');

author.books.add(book);

orm.em.flush();
```

Then, again in a new node process we query the Author again and want to get it's books:
```
const author = await orm.em.findOneOrFail(Author, {name: 'William Shakespeare'}, ['books']);

console.log(author.books.getItems());
```

This now logs an empty array, while an array with the `Book` we just created and added to the author is expected.

**Comment by B4nan** [comment]
You are missing two `await`s in your code. This is passing for me: 

```ts
import { Collection, Entity, ManyToOne, MikroORM, OneToMany, PrimaryKey, Property } from '@mikro-orm/core';
import { SqliteDriver } from '@mikro-orm/sqlite';

@Entity()
export class Book {

  @PrimaryKey()
  public id!: number;

  @ManyToOne('Author', { nullable: true })
  public author?: any; // to get around early usage

  @Property()
  public title!: string;

  @Property()
  public content!: string;

  constructor(title: string, content: string) {
    this.title = title;
    this.content = content;
  }

}

@Entity()
export class Author {

  @PrimaryKey()
  public id!: number;

  @Property()
  public name: string;

  @OneToMany(() => Book, book => book.author)
  public books = new Collection<Book>(this);

  constructor(name: string) {
    this.name = name;
  }

}

describe('GH issue 1438', () => {

  let orm: MikroORM<SqliteDriver>;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [Author, Book],
      dbName: ':memory:',
      type: 'sqlite',
      debug: true,
    });
    await orm.getSchemaGenerator().createSchema();
  });

  afterAll(() => orm.close(true));

  test('cascade persist with pre-filled PK and with cycles', async () => {
    await orm.em.persistAndFlush(new Author('William Shakespeare'));
    orm.em.clear(); // simulate new request

    const author = await orm.em.findOneOrFail(Author, { name: 'William Shakespeare' }, ['books']);
    const book = new Book('Romeo and Juliet', 'Some world renown content');
    author.books.add(book);
    await orm.em.flush();
    orm.em.clear(); // simulate new request

    const author1 = await orm.em.findOneOrFail(Author, { name: 'William Shakespeare' }, ['books']);
    expect(author1.books.getItems()).toHaveLength(1);
  });

});
```

**Comment by B4nan** [comment]
Btw you said you are using mongo? If you want to have a non-ObjectId PK in mongo, you need to provide its value, only `ObjectId` will be autogerated.

**Comment by danielgelling** [comment]
> Btw you said you are using mongo? If you want to have a non-ObjectId PK in mongo, you need to provide its value, only ObjectId will be autogerated.

Yes I'm using Mongo. Honestly, I don't really care how MikroOrm stores the relations in the database (that's why I'm using an ORM...).

Using your exact test it still returns an empty array on my machine. (also with the sqlite driver)

**Comment by B4nan** [comment]
> Using your exact test it still returns an empty array on my machine. (also with the sqlite driver)

Nope, it does pass in sqlite, as is. I did test it myself before sending it here. Do you really think I wrote the test case without trying? :] 

> Yes I'm using Mongo. Honestly, I don't really care how MikroOrm stores the relations in the database (that's why I'm using an ORM...).

Well as I said, for mongo you need to use `ObjectId` or provide the PK value yourself (e.g. uuid). Afaik mongo does not offer any numeric auto increment capabilities. **Moreover you are required to use `_id` as the primary key name.**

Those are requirements of mongo, nothing we can do about from the ORM point of view.

Here is a working mongo version:

```ts
import { Collection, Entity, ManyToOne, MikroORM, OneToMany, PrimaryKey, Property } from '@mikro-orm/core';
import { SqliteDriver } from '@mikro-orm/sqlite';
import { ObjectId } from 'bson';

@Entity()
export class Book {

  @PrimaryKey({ name: '_id' })
  public id!: ObjectId;

  @ManyToOne('Author', { nullable: true })
  public author?: any; // to get around early usage

  @Property()
  public title!: string;

  @Property()
  public content!: string;

  constructor(title: string, content: string) {
    this.title = title;
    this.content = content;
  }

}

@Entity()
export class Author {

  @PrimaryKey({ name: '_id' })
  public id!: ObjectId;

  @Property()
  public name: string;

  @OneToMany(() => Book, book => book.author)
  public books = new Collection<Book>(this);

  constructor(name: string) {
    this.name = name;
  }

}

describe('GH issue 1438', () => {

  let orm: MikroORM<SqliteDriver>;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [Author, Book],
      type: 'mongo',
      clientUrl: 'mongodb://localhost:27017,localhost:27018,localhost:27019/mikro-orm-test321?replicaSet=rs0',
      debug: true,
    });
  });

  afterAll(() => orm.close(true));

  test('cascade persist with pre-filled PK and with cycles', async () => {
    await orm.em.persistAndFlush(new Author('William Shakespeare'));
    orm.em.clear(); // simulate new request

    const author = await orm.em.findOneOrFail(Author, { name: 'William Shakespeare' }, ['books']);
    const book = new Book('Romeo and Juliet', 'Some world renown content');
    author.books.add(book);
    await orm.em.flush();
    orm.em.clear(); // simulate new request

    const author1 = await orm.em.findOneOrFail(Author, { name: 'William Shakespeare' }, ['books']);
    expect(author1.books.getItems()).toHaveLength(1);
  });

});
```

https://mikro-orm.io/docs/usage-with-mongo#defining-entity

Closing as it works correctly when having the PK defined correctly.
