### ISSUE TITLE
Disable createdAt generation from MikroORM

### ISSUE THREAD

**Issue by AaronPerezPerez** [mikro-orm/mikro-orm#1439]
At the moment we want to generate the createdAt timestamp from our backed, but the timestamp being saved is calculated by MikroORM. I can't find in the documentation if it is possible to persist the custom createdAt we are setting in the entity.

**To Reproduce**
```typescript
@Entity({ tableName: 'account_recoveries' })
export class AccountRecoveryEntity {
  @PrimaryKey()
  ine: string;

  @Property()
  phoneNumber: string;

  @PrimaryKey()
  createdAt: Date;

  [PrimaryKeyType]: [string, Date];

  constructor(p: AccountRecoveryPrimitives) {
    this.phoneNumber = p.phoneNumber;
    this.ine = p.ine;
    this.createdAt = p.createdAt; // We are passing the value 2021-02-15T12:57:54.861Z
  }
```
And after checking the database, the field is being saved as 2021-02-15T12:57:55.000Z.

**Comment by B4nan** [comment]
There is no such code that would compute the value here - what makes you think it's the ORM? Ideally provide full reproduction as a [single file test case](https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues).

How does the column definition in the database look like? You probably need to set the length to have milliseconds precision:

```ts
  @PrimaryKey({ length: 3 })
  createdAt: Date;
```

Or via `columnType`:

```ts
  @PrimaryKey({ columnType: 'timestamptz(3)' }) // driver specific
  createdAt: Date;
```

This sounds like it's the database that trims the milliseconds.

**Comment by AaronPerezPerez** [comment]
You were completely right, the issue was with the trimmering as the column was being created as **timestamptz(0)**.
Sorry for the bad issue format, next time I'll follow your advice.

Thanks for the reply!
