### ISSUE TITLE
[bug] assign bug

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#144]
https://github.com/lookfirst/mikro-example/blob/master/test/index.spec.ts#L46

```
[query] begin
[query] insert into `Person` (`email`, `id`) values (?, ?) [took 1 ms]
[query] commit
[query] begin
[query] rollback

insert into `Thing` (`createdBy`, `field`, `id`) values ('person:1', NULL, 'thing:1') - SQLITE_CONSTRAINT: NOT NULL constraint failed: Thing.field
Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: Thing.field
```

Thank you for putting the fields in the logs!

I would have expected the field to not be null.

Reading the docs: https://github.com/mikro-orm/mikro-orm/blob/dev/docs/entity-helper.md

`IEntity.assign()` api is not like `Object.assign()`. `Object.assign()` returns the object and it has a very different signature. I would make them more similar or rename it to be something else to avoid confusion.

**Comment by lookfirst** [comment]
fyi, latest dev branch. I yarn link it now. ;-)

Also, looking at the docs mentioned above, again, I don't see an example of a persist operation which makes me feel like this is how these sorts of bugs creep into things.

**Comment by B4nan** [comment]
> Thank you for putting the fields in the logs!

Not too fast, this is just an error and in errors there you will see the whole query, params included :] Dumping params in regular queries is still TODO :]

> IEntity.assign() api is not like Object.assign(). Object.assign() returns the object and it has a very different signature. I would make them more similar or rename it to be something else to avoid confusion.

Why do you say so? 

> https://github.com/lookfirst/mikro-example/blob/master/test/index.spec.ts#L46

This file is not there anymore, please add working link. And ideally please always provide a snippet where your error comes from.

**Comment by lookfirst** [comment]
[Object.assign()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Syntax) has different syntax.

Sorry about that, renamed the file.

https://github.com/lookfirst/mikro-example/blob/master/test/thing.spec.ts#L46

```
	it('creates a thing with createdBy relation through assign', async () => {
		const thing = new Thing({id: 'thing:1'}, createdBy);
		thing.assign({field: 'a field'});

		await orm.em.persistAndFlush(thing);
		assert.strictEqual(thing.createdBy.id, 'person:1');

		orm.em.clear();

		const thing1 = await orm.em.findOne(Thing, {id: 'thing:1'},
			{populate: ['createdBy']});

		assert.strictEqual(thing1!.id, 'thing:1');
		assert.strictEqual(thing1!.createdBy.id, 'person:1');
		assert.strictEqual(thing1!.createdBy.unwrap().email, 'foo@bar.com');

		assert.strictEqual((await thing1!.createdBy.load()).email, 'foo@bar.com');

		assert.strictEqual(thing1!.field, 'a field');
	});
```

**Comment by B4nan** [comment]
Well obviously, Object.assign is static helper, while entity.assign is instance method. I dont think we need to support multiple sources like in Object.assign. Returning the entity from assign call can be added, no problem with that.

**Comment by lookfirst** [comment]
My issue is the documentation... "By default, IEntity.assign(data) behaves same way as Object.assign(entity, data)"... you use it for another example, but taking this sentence out of context is not good.

**Comment by B4nan** [comment]
That test is passing for me (with `alpha.12`, with changes I described in #151). 

```sql
[query] begin
[query] insert into `Person` (`email`, `id`) values ('foo@bar.com', 'person:1') [took 1 ms]
[query] commit
[query] begin
[query] insert into `Thing` (`createdBy`, `field`, `id`) values ('person:1', 'a field', 'thing:1') [took 1 ms]
[query] commit
[query] select `e0`.* from `Thing` as `e0` where `e0`.`id` = 'thing:1' limit 1 [took 1 ms]
[query] select `e0`.* from `Person` as `e0` where `e0`.`id` in ('person:1') order by `e0`.`id` asc [took 0 ms]
```

You have problem with the testcase itself, as you are creating `Person` with same id via `beforeEach`, but that is another story :]

**Comment by lookfirst** [comment]
Yea, I noticed that problem too lol ... I think I've cleaned that up now.

**Comment by B4nan** [comment]
`assign` now returns the entity as well.

**Comment by B4nan** [comment]
Can we close this, or do you think the docs needs some adjustments? I cannot support multiple source objects as in Object.assign(), as I need that last parameter for additional options (although I could support lets say 1 to 5 sources manually, but I don't think that is really worth it, the code would be pretty ugly 😄).

**Comment by lookfirst** [comment]
Can!
