### ISSUE TITLE
Improve documentation of how config is loaded in `MikroORM.init()`

### ISSUE THREAD

**Issue by fhucho** [mikro-orm/mikro-orm#1440]
I have a `mikro-orm.config.ts` file and the CLI tool works. The documentation says:

> Once you have the CLI config properly set up, you can omit the MikroORM.init() options parameter and the CLI config will be automatically used.

So I removed the options parameter, but it fails to load the config file. Somehew I figured out that I can fix it by calling `require('ts-node').register();` before `MikroORM.init()` but still not 100% sure why this is needed, whether this is the right solution and why ts-node isn't loaded automatically.

**Comment by B4nan** [comment]
It should actually work that way. You also need to enable `useTsNode` in your package.json, and you need to compile your app so you also have JS version of the CLI config if you are running via `node`. Registering `ts-node` manually is wrong way to fix this - you don't want that in production. It is registered automatically if [`ts-node` is detected](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/utils/Utils.ts#L519) and only then the TS version of the config will be used. 

Looking at the docs it seems documented this way - the docs are talking about JS config, adding a note about how to use TS configs, mentioning the `useTsNode` flag too.

If you give me a repro, will be happy to look into why it fails to load it/detect the ts-node correctly. But after reading thru the docs, it feels like everything is there and right... Sounds more like it's just a bug/edge case/misconfiguration.

**Comment by fhucho** [comment]
I'm using Sapper. During development I start the server with the `"sapper dev"` script in package.json, if I replace it with `"ts-node node_modules/.bin/sapper dev"`, it works. The production build also needs to be run with ts-node.

Sapper compilation doesn't work by mapping every .ts file to a corresponding .js file. It ignores the mikro-orm.config.ts file because I never import it (and if I imported it, it would get compiled into the output bundle).

Honestly, I find all of this somewhat confusing...

**Comment by B4nan** [comment]
You can always do this which will be fine in terms of tree shaking:

```ts
import config from './mikro-orm.config';
const orm = await MikroORM.init(config);
```

**Comment by fhucho** [comment]
Good idea, that seems like the right solution. I just had to add `as Options` in mikro-orm.config.ts because I'm using strict mode. Thanks 👍
