### ISSUE TITLE
Doc : autoincrement bigint number

### ISSUE THREAD

**Issue by trompx** [mikro-orm/mikro-orm#1446]
**Is your feature request related to a problem? Please describe.**
Right now auto increment works only for the default BigIntType which is a string.
Is there a specific reason why it is set as string by default? Looks like it occupies more space and slower to query than number.
Anyway I tried the following:
```
  @PrimaryKey({ type: BigIntType })
  id!: number;
```
which is obviously not working as per https://mikro-orm.io/docs/using-bigint-pks/ but with NativeBigIntType I lose the autoincrement. I get the following error when trying to create an item without specifying the id:
`returning "id" - null value in column "id" violates not-null constraint...`

Maybe I missed the information in the doc somewhere but searching for **autoincrement** did not allow me to solve this.

**Comment by B4nan** [comment]
Sounds like you have wrong schema definition, it is the db that does auto increment, not ORM. And it works just fine for bigints too (part of the existing test suite too). 

Bigints are mapped to string because the max value would not fit into the regular number type.

**Comment by B4nan** [comment]
Will close this, as said, this is not handled at the ORM level, it's the database that handle auto increment columns - your schema is probably missing the `auto_increment` flag on that PK.

If you share a repro, I can look into it.
