### ISSUE TITLE
Strict typing for `em.create`

### ISSUE THREAD

**Issue by acro5piano** [mikro-orm/mikro-orm#1456]
Hi, first of all, thank you for the great library. I love it.

**Is your feature request related to a problem? Please describe.**

The method `create` of `EntityRepository<T>` receives `{ [k in T]?: T[k] | any }`. I'm wondering it should not accept `any` because it accepts incorrect type for Database, so  `{ [k in T]?: T[k] }` looks better.

Consider this example:

```ts
// entities/User.ts

import { Entity, Property, EntityRepositoryType } from '@mikro-orm/core'
import { UserRepository } from '../repositories/UserRepository'

@Entity({ customRepository: () => UserRepository })
export class User {
  [EntityRepositoryType]: UserRepository

  @Property({ default: 0 })
  height: number = 0
}
```

```ts
// repositories/UserRepository.ts

import { EntityRepository } from '@mikro-orm/postgresql'
import { User } from 'src/entities/User'

export class UserRepository extends EntityRepository<User> {}
```

```ts
// app.ts
import { User } from './entities/User'
import { UserRepository } from './repositories/UserRepository'

const userRepo = em.getRepository(User)
const user = await userRepo.create({
  height: 'ANYTHING_HERE_AND_FAILS_IN_RUNTIME',
})
```

**Describe the solution you'd like**

Remove `any` from the type definition.

https://github.com/mikro-orm/mikro-orm/blob/1a5ae3baa7583a7e38a5cb0083ce67ec990781b6/packages/core/src/typings.ts#L122

**Describe alternatives you've considered**

Manual constructing class instance checks type, but I think prefer `.create` method for readability. 

```ts
const newUser = new User()
newUser.height = 'THIS_RAISE_TS_ERROR'
```

**Additional context**

I think this is because supporting complex typing, like `json` type?

**Comment by B4nan** [comment]
Yes, this is something I'd like to rework in v5 - I feel like making the types stricter is an actual breaking change. There are more places than just this.

> Manual constructing class instance checks type, but I think prefer .create method for readability.

Interesting take, for me `em.create` is actually less readable. Btw it is a sync method for creating entity instances, no need to await it.

> I think this is because supporting complex typing, like json type?

It's more like the type was used internally on places that require it to be to loose. In fact we should have two types, one for the db type (e.g. snake case props), one for the entity type (e.g. camel case props) - but they are both represented as `EntityData`. Also in general the DTO can have any properties (e.g. when you define custom `toJSON` method). The type is simply used in too many places so it had to be loose in the end :D

**Comment by acro5piano** [comment]
@B4nan
Thank you for your reply!

> Yes, this is something I'd like to rework in v5 - I feel like making the types stricter is an actual breaking change. There are more places than just this.

Yeah I took a look at the code and it is used in massive parts of the codebase. I could be a hard work to change them.
I'm looking forward to v5! 

> Interesting take, for me em.create is actually less readable. Btw it is a sync method for creating entity instances, no need to await it.

Thank you for pointing out ;)

For now I'll use `patch-package` or something. Thank you!

**Comment by araujoigor** [comment]
@acro5piano did you have any luck in patching the library to enforce strict type checking? If yes what was the approach?

**Comment by B4nan** [comment]
I don't see why would you need to patch the library, just create the method elsewhere (e.g. custom base repository). 

But if you really want to, this is only a TS issue, so it should be possible to override the typings of the library similar way like you would extend a request object with a new property (quite common use case).

https://stackoverflow.com/questions/37377731/extend-express-request-object-using-typescript

**Comment by acro5piano** [comment]
@araujoigor
No, it seems to be easier to stick to set properties in a bit manual way. In the above example, use

```ts
class User {
  height!: number
}
const userRepo = await em.getRepository(User)
const newUser = new User()
newUser.height = 155
await userRepo.save(newUser)
```

Or if you don't like the null assertion ( `!:` ), modify a constructor 

```ts
class User {
  height: number
  constrcutor(height: number) {
    this.height = height
  }
}

const userRepo = await em.getRepository(User)
const newUser = new User(155)
await userRepo.save(newUser)
```

The context is that I came from Objection.js and Knex. Knex is a query builder where the create syntax is something like

```ts
interface User {
  height: number
}

await knex<User>('users').update({ height: 15 }) // Type checked
```

I don't compare them or say which is better or not.
Mikro-ORM is a full featured ORM, and setting everything in Class should be the proper way in that world .

**Comment by acro5piano** [comment]
@abrasher Thanks for sharing. I love the hack!
