### ISSUE TITLE
[feature] @OneToMany(type, (type)=> type.property)

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#146]
`@OneToMany(type => Thing, thing => thing.foo, {nullable: true})`

Using this syntax is more type safe than `{mappedBy: 'foo'}`

**Comment by B4nan** [comment]
Can this be really type checked? I guess then it's required to use multiple parameters instead of just one object hash... 

But yes, if it's possible I am all for better type checks :]

**Comment by lookfirst** [comment]
I like the way that typeorm defines things better... https://typeorm.io/#/many-to-one-one-to-many-relations

Strings are ugly.

**Comment by B4nan** [comment]
> Strings are ugly.

Well, string itself is not a problem, strings can be type checked too via `keyof` :]

**Comment by lookfirst** [comment]
Yes, but likely an IDE can't refactor it as easily.

**Comment by B4nan** [comment]
Sure, I am fine with proposed syntax as well, will take a look into this later and let you know. Adding new and more strict way to define entities is always welcome.

**Comment by B4nan** [comment]
Available for testing in `3.0.0-alpha.13` (not yet pushed to git, will finalize and add docs tomorrow). Includes all relationship decorators, adds type checking for current options version (via `keyof`) as well as adds the proposed syntax. 

```typescript
  @OneToOne(() => FooBaz, baz => baz.bar, { owner: true, orphanRemoval: true })
  baz: FooBaz ;
```

**Comment by lookfirst** [comment]
This seems working, so close whenever you want.

**Comment by B4nan** [comment]
Also added relationships section into docs: https://github.com/mikro-orm/mikro-orm/blob/dev/docs/relationships.md

**Comment by lookfirst** [comment]
just tested it... works great!
