### ISSUE TITLE
Column "id" does not exist

### ISSUE THREAD

**Issue by blechatellier** [mikro-orm/mikro-orm#1461]
**Describe the bug**
Creating a simple entity in postgresql with a UUID string, but can't get it to work. Works as expected if I use a number type.

**Stack trace**
```
previous error: insert into "user" ("created_at", "email", "first_name", "last_name", "password", "updated_at") values ('2021-02-18T15:54:50.047Z', 'john@email.com', 'John', 'Foo', '$2b$10$1beykaKF8bUuJr/ae7KgUuJn6RAA4bXfHGzvjRht1KzqmUpNTVKma', '2021-02-18T15:54:50.047Z') returning "id" - column "id" does not exist
    at Parser.parseErrorMessage (/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**To Reproduce**
```
import { v4 } from 'uuid';

@Entity()
@ObjectType()
export class Book {

  @PrimaryKey()
  @Field(() => ID)
  uuid: string = v4();

  @Property()
  @Field()
  title!: string;
}
```

**Expected behavior**
It should create the entity

**Additional context**
Using this entity with nestjs and graphql.

**Versions**

| Dependency | Version |
| - | - |
| node | v12.19.0 |
| typescript | 4.1.5 |
| mikro-orm | 4.4.3 |
| pg | 8.5.1 |
| @nestjs/core | 7.6.12 |
| @nestjs/graphql | 7.9.9 |

**Comment by B4nan** [comment]
Are you sure this is not just some cache? Have you defined the PK as `id` before, or was it `uuid` from the beginning? 

I will need a full reproduction for this, there are many things you can have wrong on the way - your entity definition looks fine.

**Comment by B4nan** [comment]
To start with - the fact that you do not have any `uuid` value there points to doing something wrong when creating the entity instance. You should either use `em.create()` or the entity ctor - both ways will result in the `uuid` property initializer being executed, therefore the value should be there. 

Just a guess - if you are using `class-transformer`, just don't :] It is not suited to create MikroORM entities - it has no knowledge of the identity map context. You need to use `em.create()` or the ctor instead (`em.create()` will call the ctor for you).

**Comment by blechatellier** [comment]
@B4nan I deleted the `dist` folder generated by nestjs and it worked, sorry about the hassle, closing.
