### ISSUE TITLE
mikro-orm debug not found entities files

### ISSUE THREAD

**Issue by blackcurry** [mikro-orm/mikro-orm#1465]
HI!!
when mikro-orm debug is run, if the entity path is given as an absolute path, it finds the path
```
- will use `entities` array (contains 0 references and 1 paths)
   - /Users/Work/git/nestjs-mikro/dist/src/author/entities/author.entities.js (found)
- could use `entitiesTs` array (contains 0 references and 1 paths)
   - /Users/Work/git/nestjs-mikro/src/author/entities/author.entities.ts (found)
```

change the path to globs and not found path  
```
- will use `entities` array (contains 0 references and 1 paths)
  - /Users/Work/git/nestjs-mikro/dist/src/**/entities/*.entities.js (not found)
- could use `entitiesTs` array (contains 0 references and 1 paths)
  - /Users/Work/git/nestjs-mikro/src/**/entities/*.entities.ts (not found)
```

test repo here
https://github.com/blackcurry/nestjsmikro.git

**Comment by B4nan** [comment]
So this is just about the debug CLI command, right? The app itself works as expected?

**Comment by dainiusm07** [comment]
Using with NestJS app itself works as expected so far. But as @blackcurry reported CLI with globs path seems to not work.

**Comment by B4nan** [comment]
The problem is not globs, the problem is in using file paths instead of folder paths (originally only folder paths were supported).

**Comment by rubiin** [comment]
nice catch @blackcurry

**Comment by blackcurry** [comment]
Thanks
After the 4.4.4 version update, the globs file paths works well.
