### ISSUE TITLE
Custom foreign keys

### ISSUE THREAD

**Issue by nickt26** [mikro-orm/mikro-orm#1469]
Hi B4nan.
Really enjoying working with mikro-orm so far.
Just running into some issues when attempting to use a custom foreign key name.

Here are my entities:
```node
@Entity({ tableName: "User" })
export class User {
  @PrimaryKey()
  id!: number;

  @Property()
  name!: string;

  @OneToMany(() => Car, (car) => car.user, { nullable: true })
  cars?: Collection<Car>;
}

@Entity({ tableName: "Car" })
export class Car {
  @PrimaryKey()
  id!: number;

  @Property()
  name!: string;

  @Property()
  userId!: number;

  @ManyToOne(() => User, { joinColumn: "userId" })
  user!: User;
}
```
The first issue starts with the migrations being generated trying to add 2 foreign keys to the Car table when generating migrations for the entities above.
```node
async up(): Promise<void> {
    this.addSql('create table `User` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null) default character set utf8mb4 engine = InnoDB;');

    this.addSql('create table `Car` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `user_id` int(11) not null, `userId` int(11) unsigned not null) default character set utf8mb4 engine = InnoDB;');
    this.addSql('alter table `Car` add index `Car_userId_index`(`userId`);');

    this.addSql('alter table `Car` add constraint `Car_userId_foreign` foreign key (`userId`) references `User` (`id`) on update cascade;');
  }
```

Now I try manually removing the column `user_id` generated in the migration like this:
```node
async up(): Promise<void> {
    this.addSql('create table `User` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null) default character set utf8mb4 engine = InnoDB;');

    this.addSql('create table `Car` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `userId` int(11) unsigned not null) default character set utf8mb4 engine = InnoDB;');
    this.addSql('alter table `Car` add index `Car_userId_index`(`userId`);');

    this.addSql('alter table `Car` add constraint `Car_userId_foreign` foreign key (`userId`) references `User` (`id`) on update cascade;');
  }
```

This at first seemed to solve the issue but then you run into further problems when trying to create a new Car with a userId:
```node
const user = ctx.em
            .getRepository(Car)
            .create({ name: 'Ford Fiesta', userId: 1 });
          await ctx.em.persistAndFlush(user);
          return user;
```
In the example above I've already created a user with id 1.
The code above produces this stack trace when you execute it:
```
InvalidFieldNameException: insert into `Car` (`name`, `user_id`) values ('Ford Fiesta', 1) - Unknown column 'user_id' in 'field list'
    at MySqlExceptionConverter.convertException (C:\Users\nickt26\Documents\projects\express-graphql-api\node_modules\@mikro-orm\mysql-base\MySqlExceptionConverter.js:37:24)
    at MySqlDriver.convertException (C:\Users\nickt26\Documents\projects\express-graphql-api\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:185:54)
    at C:\Users\nickt26\Documents\projects\express-graphql-api\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:189:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at MySqlDriver.nativeInsert (C:\Users\nickt26\Documents\projects\express-graphql-api\node_modules\@mikro-orm\knex\AbstractSqlDriver.js:148:21)
    at ChangeSetPersister.persistNewEntity (C:\Users\nickt26\Documents\projects\express-graphql-api\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:55:21)
    at ChangeSetPersister.executeInserts (C:\Users\nickt26\Documents\projects\express-graphql-api\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:24:13)
    at UnitOfWork.commitCreateChangeSets (C:\Users\nickt26\Documents\projects\express-graphql-api\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:482:9)
    at UnitOfWork.persistToDatabase (C:\Users\nickt26\Documents\projects\express-graphql-api\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:444:13)
    at MySqlConnection.transactional (C:\Users\nickt26\Documents\projects\express-graphql-api\node_modules\@mikro-orm\knex\AbstractSqlConnection.js:53:25)

previous Error: insert into `Car` (`name`, `user_id`) values ('Ford Fiesta', 1) - Unknown column 'user_id' in 'field list'
    at Packet.asError (C:\Users\nickt26\Documents\projects\express-graphql-api\node_modules\mysql2\lib\packets\packet.js:712:17)
    at Query.execute (C:\Users\nickt26\Documents\projects\express-graphql-api\node_modules\mysql2\lib\commands\command.js:28:26)
    at Connection.handlePacket (C:\Users\nickt26\Documents\projects\express-graphql-api\node_modules\mysql2\lib\connection.js:425:32)
    at PacketParser.onPacket (C:\Users\nickt26\Documents\projects\express-graphql-api\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (C:\Users\nickt26\Documents\projects\express-graphql-api\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\nickt26\Documents\projects\express-graphql-api\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column 'user_id' in 'field list'"
}
```
A couple notes on this though:
I've managed to circumvent the issue by creating a custom foreign key called user_id and then specifying the join column as 'user_id'. This still produces the forced foreign key in the migration and tries to make 2 columns both called 'user_id' but manually removing one will make the migrations run and the entity manager will be happy.

However I find this fix to be a bit silly since all custom foreign key columns will now have to use the snake case convention for naming and don't allow for any other naming convention.

I should also mention that my specific use case for doing this is for graphql resolvers, namely something along the lines of this:
```node

interface MyContext {
 em: orm.em.fork();
};

const UserType = new GraphQLObjectType({
  name: "User",
  fields: () => ({
    id: { type: GraphQLNonNull(GraphQLID) },
    name: { type: GraphQLNonNull(GraphQLString) },
    cars: {
      type: GraphQLList(CarType),
      resolve: async (root, args, ctx: MyContext, info) =>
        await ctx.em.getRepository(Car).find({ userId: root.id }),
    },
  }),
});
```

rather than having to do this in the resolver:
```node
const UserType = new GraphQLObjectType({
  name: "User",
  fields: () => ({
    id: { type: GraphQLNonNull(GraphQLID) },
    name: { type: GraphQLNonNull(GraphQLString) },
    cars: {
      type: GraphQLList(CarType),
      resolve: async (root, args, ctx: MyContext, info) =>
        await ctx.em.getRepository(Car).find({ user: { id: [root.id] } }),
    },
  }),
});
```
which will force a join when trying to find by the userId.

So I guess the feature request is to have support for custom foreign keys that you can reference in the find methods on the entity manager and to prevent the generated migrations from attempting to add a foreign key when the custom joinColumn exists on the entity.

I feel like I might be doing something very silly here and I just haven't found the right place to look in the documentation though.
If there's a way to do what I'm attempting I'd appreciate any help you can offer :)

1. Create entitiy with many-to-one relationship and add custom property representing foreign key.
2. Add joinColumn property on the many-to-one relationship.
3. Generate migrations based on the entities.
4. Manually remove forced foreign key generated in the migration.
5. Try create a new row on the entity containing the many-to-one relationship while providing the custom foreign key in the create options.

**Comment by B4nan** [comment]
Nope, this is not supported, you can't map two properties to single column - only if you make one of them virtual (so it will be ignored during persistence as well as schema generation). 

I never understood why people want this. This "typeorm" way seems like a very bad workaround to not have identity map, rather than a feature worth implementing... It is literally one of the reasons why I decided to work on MikroORM. 

So instead of discussing how to work this around, let's discuss why do you want this.

Btw have you seen [`mapToPk`](https://mikro-orm.io/docs/defining-entities/#mapping-directly-to-primary-keys)? 
I would rather not suggest using this, as you will loose a lot of ORM features (autocascading mainly, you will become responsible for providing the FK value).

**Comment by nickt26** [comment]
Thanks for the quick reply :)

I tried using persist: false and worked like a charm for my use case.

As for the reason I asked this it's as I said in the issue. It's for graphql resolvers when I'm querying fields that have relationships.
However if you know a better way of doing something like this with resolvers I'd be happy to take some advice :)
But that starts heading down the route of being a more graphql related issue or how you hould use ORM's in general with graphql.

I'll be closing this issue now since it's been resolved.

Once again thanks for the awesome ORM and being so active.
