### ISSUE TITLE
Feature request: Add feature to accept connection via env

### ISSUE THREAD

**Issue by rubiin** [mikro-orm/mikro-orm#1472]
**Is your feature request related to a problem? Please describe.**
Typeorm supports connections through .env files with some predefined keys

**Describe the solution you'd like**
Something like :
```
MIKROORM_CONNECTION = mysql
MIKROORM_HOST = localhost
MIKROORM_USERNAME = root
MIKROORM_PASSWORD = admin
MIKROORM_DATABASE = test
MIKROORM_PORT = 3000
MIKROORM_SYNCHRONIZE = true
MIKROORM_LOGGING = true
MIKROORM_ENTITIES = entity/*.js,modules/**/entity/*.js

```

**Describe alternatives you've considered**

**Additional context**
More on this can be read at: https://typeorm.io/#/using-ormconfig/using-environment-variables

**Comment by rubiin** [comment]
Any eta on the feature?

**Comment by B4nan** [comment]
no eta, use the beta

**Comment by rubiin** [comment]
> no eta, use the beta

thanks will be using beta to try it
