### ISSUE TITLE
[feature] typesafe configuration options

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#148]
If I put `Configuration` or `Options` in ????, I get all sorts of warnings from the ts compiler because I'm not defining all the properties, just the ones I want to override from defaults. It would be nice to make that object more typesafe.

```ts
const config = {
    test: {
    } as ....????
}

orm = await MikroORM.init(config.test);
```

**Comment by B4nan** [comment]
Well it is typesafe, that is the reason why it does not let you pass object with missing required properties. 

`Configuration` is the wrapper class, not the options interface. That is `MikroORMOptions`, but there a lot of things are required, even those that has default values. 

`Options` is what you should be using, as it removed those props that have default value from `MikroORMOptions`. 

Obviously you can always do `Partial<Options>` so allow having just some keys of that. Maybe show concrete example of what you would like to do and an error of what is missing from `Options` interface.

**Comment by lookfirst** [comment]
Once again, Partial to the rescue. =)

I setup my config in cli-config.ts and since that file doesn't have anything else in it... I want defining the config object to auto complete. Partial<Options> fixes that.

**Comment by lookfirst** [comment]
Actually, Partial<Options> then causes issues with .init().

**Comment by B4nan** [comment]
As I said, please add concrete example of what you try to put there, how you type that and what is the error.

**Comment by lookfirst** [comment]
https://github.com/lookfirst/mikro-example/blob/master/src/db/cli-config.ts
https://github.com/lookfirst/mikro-example/blob/master/test/dog.spec.ts#L13

added 'as any' to init.

```
Error:(13, 29) TS2345: Argument of type 'Partial<MikroORMOptions> | Partial<Pick<MikroORMOptions, "driver" | "namingStrategy" | "replicas" | "name" | "dbName" | "clientUrl" | "host" | "port" | "user" | "password" | "multipleStatements">>' is not assignable to parameter of type 'MikroORMOptions | Configuration | Pick<MikroORMOptions, "driver" | "namingStrategy" | "replicas" | "name" | "dbName" | "clientUrl" | "host" | "port" | "user" | "password" | "multipleStatements">'.
  Type 'Partial<MikroORMOptions>' is not assignable to type 'MikroORMOptions | Configuration | Pick<MikroORMOptions, "driver" | "namingStrategy" | "replicas" | "name" | "dbName" | "clientUrl" | "host" | "port" | "user" | "password" | "multipleStatements">'.
    Type 'Partial<MikroORMOptions>' is not assignable to type 'MikroORMOptions'.
      Types of property 'entities' are incompatible.
        Type '(EntityClass<IEntity<string | number>> | EntityClassGroup<IEntity<string | number>>)[] | undefined' is not assignable to type '(EntityClass<IEntity<string | number>> | EntityClassGroup<IEntity<string | number>>)[]'.
          Type 'undefined' is not assignable to type '(EntityClass<IEntity<string | number>> | EntityClassGroup<IEntity<string | number>>)[]'.
```

**Comment by B4nan** [comment]
Ok, will take a loot into this later.

**Comment by B4nan** [comment]
Well, I removed the `Partial` and that cast to `any` and it works as expected, no TS errors.

**Comment by lookfirst** [comment]
Is `any` cheating? I often wonder with laughter.

**Comment by B4nan** [comment]
I guess this can be closed now?
