### ISSUE TITLE
Schema diffing ignores changes to the length parameter

### ISSUE THREAD

**Issue by thomaschaaf** [mikro-orm/mikro-orm#1486]
**Describe the bug**
When adding the length parameter to an existing entity (such as Date) it is not noticed by the Migration generation and says that the migrations are up to date.

**Expected behavior**
Should generate migrations with changed length/precision.

**Versions**

| Dependency | Version |
| - | - |
| node | 12 |
| typescript | 4.1.3 |
| mikro-orm | 4.4.2 |

**Comment by B4nan** [comment]
this is tested and works fine. if you want to report a bug, providing repro is a must. 

my guess is you are trying to use `columnType` with `length` together - that indeed don't work as `columnType` is not processed anyhow - it is always used as is. this works fine in tests:

```ts
  @Property({ length: 3 })
  createdAt: Date;
```

or 

```ts
  @Property({ columnType: 'datetime(3)' })
  createdAt: Date;
```

https://github.com/mikro-orm/mikro-orm/blob/master/tests/__snapshots__/SchemaGenerator.test.ts.snap#L51

**Comment by B4nan** [comment]
Wait a minute - so your issue is that the diffing ignores length parameter, not that the parameter does not work, but the diffing ignores it? 

Afaik the diffing is currently written that way, agreed we should take the parameters into account.
