### ISSUE TITLE
[feat] warn when OneToOne does not define an owner

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#149]
If mikro can't figure out the relationship, it should give a good error message.

**Comment by lookfirst** [comment]
Additionally...

```
Thing:
	@OneToOne({owner: true})
	dog: Dog;

Dog:
	@OneToOne({entity: () => Thing, mappedBy: 'dog', inversedBy: 'thing'})
	thing: Thing;
```

Without the inversedBy, things fail. Seems like that could be inferred in several other ways.

Ideally, the api would be simpler too (assuming this is possible with TS):

```
Thing:
	@OneToOne()
	dog: Dog;

Dog:
	@OneToOne(() => Thing, (thing) => thing.dog)
	thing: Thing;
```

The fact that Dog refers back to Thing should make thing the automatic owner.

**Comment by B4nan** [comment]
There is a lot of validation when you define things badly, but as I see it now, it works only for collections on this level, as I was making it before I added 1:1 associations. 

https://github.com/mikro-orm/mikro-orm/blob/dev/lib/metadata/MetadataValidator.ts

**Comment by lookfirst** [comment]
Consider me your number one dumbest user. I'll find all the edge cases of stupidity. =)

**Comment by B4nan** [comment]
Added validation, also the proposed less verbose way is now supported (for both 1:1 and m:n).
