### ISSUE TITLE
Unique=true for MongoDB driver does not stop duplicate fields

### ISSUE THREAD

**Issue by i-am-zach** [mikro-orm/mikro-orm#1490]
**Describe the bug**
When setting `unique=true` for an entity using the MongoDB driver, creating a duplicate field does not throw an error. An new document is created with a duplicate email field. I switched to the PostgresQL driver and the unique constraint worked as expected.

**My Entity**
```
@Entity()
export class User {
  @PrimaryKey()
  _id: ObjectId;

  @SerializedPrimaryKey()
  id!: string;

  @Property({ unique: true })
  email!: string;

  @Property()
  createdAt: Date = new Date();

  @Property()
  password!: string;
}
```
**Code**
```
const user = em.create(User, { email: email, password: password });
await em.persistAndFlush(user);
```

Running this code with the same email created duplicate documents in MongoDB. 

**Versions**

| Dependency | Version |
| - | - |
| node | v12.14.1 |
| typescript | 4.1.5 |
| mikro-orm | 4.4.4|
| mongo-driver | 4.4.4 |

**Comment by B4nan** [comment]
You need to create the constraints via `ensureIndexes`, it does not happen automatically as it is performance heavy. 

https://mikro-orm.io/docs/usage-with-mongo/#indexes
