### ISSUE TITLE
Updating Child Collections with Soft Deletes

### ISSUE THREAD

**Issue by svantreeck** [mikro-orm/mikro-orm#1492]
**Is your feature request related to a problem? Please describe.**
I am building a new solution with soft deletes across all of my entities, and the filter criteria works great for reads, but I'm having difficulties doing updates of nested objects--specifically where orphan removal will attempt to delete the items that are no longer present.

```ts
// globally add the filter at startup
this.em.addFilter('active', { deleted: false });

// all entities have roughly this structure
@Entity({ abstract: true })
abstract class BaseEntity {
  @PrimaryKey({ type: 'uuid' })
  id = v4();

  @Property()
  deleted = false;
}
```

**Describe the solution you'd like**
I'd like a way of changing the behavior of deletes in the unit of work so that i can rewrite deletes into updates that set the deleted field
```sql
-- FROM
delete <entity> where id=<xyz>
-- TO
update <entity> set deleted = true where id=<xyz>
```

This would allow me to simplify my code so that any children collections were automatically handled without writing custom code on a per collection basis:
```ts
async update(id: string, newData: EntityData<ParentObject>) {
  const parent = await this.parentRepository.findOneOrFail(id, ["children"]); // or just have eagerly loaded children
  this.parentRepository.assign(parent, newData); // any children that were no longer present would get marked with child.deleted = true instead of having the record deleted.
  
  await this.parentRepository.persistAndFlush(parent);
}
```

**Describe alternatives you've considered**
Currently I am handling this by not eagerly loading any child collections.  Then, I separately fetch and manually iterate through the children and run the correct updates/inserts based on status.

I looked at creating a custom repository that implemented this behavior, but I think that the delete behavior is handled higher up in the UnitOfWork stack and not currently accessible

**Comment by B4nan** [comment]
I think this should be already possible via flush events - inside `onFlush` you can lookup remove changesets and change them to update.

http://mikro-orm.io/docs/lifecycle-hooks/#using-onflush-event

Something like the following lines (not tested):

```ts
@Subscriber()
export class SoftDeleteSubscriber implements EventSubscriber {

  async onFlush(args: FlushEventArgs): Promise<void> {
    const changeSets = args.uow.getChangeSets();
    const toRemove = changeSets.filter(cs => cs.type === ChangeSetType.REMOVE);

    toRemove.forEach({
      cs.entity.deleted = true;
      args.uow.computeChangeSet(baz);
      args.uow.recomputeSingleChangeSet(cs.entity);
    }
  }

}

const bar = new FooBar();
bar.name = 'bar';
await em.persistAndFlush(bar);
```

**Comment by svantreeck** [comment]
Interesting, I'll check that out and report back, thanks @B4nan!

**Comment by svantreeck** [comment]
It looks like I also have to set `cs.payload = { deleted: true }` or else the generated sql goes a bit crazy--I'm going to keep on testing this, but it looks like it works great with `orphanRemoval` set to true on child collections.  I tried to add some type safety to only do this if the object has a `deleted` prop/field as well, but hopefully this is a reusable solution for others!

```ts
import {
  ChangeSetType,
  EventSubscriber,
  FlushEventArgs,
  Subscriber,
} from '@mikro-orm/core';

const DeletedPropName = 'deleted';

@Subscriber()
export class SoftDeleteSubscriber implements EventSubscriber {
  async onFlush(args: FlushEventArgs): Promise<void> {
    const changeSets = args.uow.getChangeSets();
    const toRemove = changeSets.filter(
      (cs) => cs.type === ChangeSetType.DELETE,
    );

    toRemove.forEach((cs) => {
      //rewrite deletes for objects that have a deleted prop to soft deletes
      if (DeletedPropName in cs.entity) {
        cs.type = ChangeSetType.UPDATE;
        cs.entity[DeletedPropName] = true;
        cs.payload = { [DeletedPropName]: true };
        args.uow.recomputeSingleChangeSet(cs.entity);
      }
    });
  }
}

```

**Comment by B4nan** [comment]
I guess this could be a nice article or a recipe in the docs :] 

Can we close this or do you see more problems down this path?

**Comment by svantreeck** [comment]
The last issue I'm seeing is maybe a misunderstanding on my part--should updates be supported by this pattern?  I'm seeing inserts and deletes as expected, but if I update the contents of one of the existing items (by passing an id that matches an already created item), I am not seeing updates.   I saw https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/entity/EntityAssigner.ts#L158 and assumed if I passed `merge: true` into the options, that it ought to update the data, but it looks like I potentially still have to manually assign for updates to take place...this is probably unrelated to the soft deletes, but running across it right now (can create a separate issue if you think this is a bug).

```ts
// what I'd like to do 
async update(id: string, newData: EntityData<ParentObject>) {
  const parent = await this.parentRepository.findOneOrFail(id, ["children"]); 
  this.parentRepository.assign(parent, newData);
  
  await this.parentRepository.persistAndFlush(parent);
}

// what I'm doing currently
async update(id: string, newData: EntityData<ParentObject>) {
  const parent = await this.parentRepository.findOneOrFail(id, ["children"]);
  this.parentRepository.assign(parent, newData); 

  // handle child updates
  newData.children.forEach(childData => {
    const child = parent.children.getItems().find(item => item.id === childData.id);
    if (child) {
       this.childRepository.assign(child, childData); // could also be wrap(child).assign(childData)
     }
  });
  
  await this.parentRepository.persistAndFlush(parent);
}
```

**Comment by B4nan** [comment]
`assign` is not working recursively, there are multiple issues about that (most recent discussion is [here](https://github.com/mikro-orm/mikro-orm/discussions/1410)). also `merge: true` means objects will be treatet as managed entities = merged to the EM. merged entity will never produce any query, as its state was snapshotted during the merge.

**Comment by svantreeck** [comment]
Cool, then I think this is good to go.  Thank you for the help with the SoftDelete subscription

**Comment by s524797336** [comment]
v5 break this, need add `originalEntity` prop to avoid error
```typescript
import {
  ChangeSetType,
  EventSubscriber,
  FlushEventArgs,
  Subscriber,
} from '@mikro-orm/core';

const DeletedPropName = 'deleted';

@Subscriber()
export class SoftDeleteSubscriber implements EventSubscriber {
  async onFlush(args: FlushEventArgs): Promise<void> {
    const changeSets = args.uow.getChangeSets();
    const toRemove = changeSets.filter(
      (cs) => cs.type === ChangeSetType.DELETE && DeletedPropName in cs.entity,
    );

    toRemove.forEach((cs) => {
      //rewrite deletes for objects that have a deleted prop to soft deletes
      cs.type = ChangeSetType.UPDATE;
      cs.entity[DeletedPropName] = true;
      cs.payload = { [DeletedPropName]: true };
      cs.originalEntity = cs.entity; // this line
      args.uow.recomputeSingleChangeSet(cs.entity);
    });
  }
}

```

**Comment by TheNightmareX** [comment]
I've wrapped these into a package [mikro-orm-soft-delete](https://github.com/TheNightmareX/mikro-orm-soft-delete).

You can enable soft-delete simply by applying a decorator to your entity definitions:

```ts
@SoftDeletable(() => User, "deletedAt", () => new Date())
@Entity()
export class User extends BaseEntity<User, "id"> {
  @PrimaryKey()
  id: number;

  @Property({ nullable: true })
  deletedAt?: Date;
}
```
