### ISSUE TITLE
[bug] debug output doesn't look in devDependencies

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#152]
sqlite is in my devDeps, since i use postgres for production. i will eventually use postgres for testing too, but started with sqlite.

/functions/cli-config (not found) should really just be a yellow warning, not red, if the other two are found.

```
Current MikroORM CLI configuration
 - dependencies:
   - mikro-orm 3.0.0-alpha.10
   - node 12.10.0
   - knex 0.19.4
   - sqlite not-found
   - typescript 3.6.0-dev.20190806
 - package.json found
 - ts-node enabled
 - searched config paths:
   - /functions/src/db/cli-config.ts (found)
   - /functions/build/src/db/cli-config.js (found)
   - /functions/cli-config (not found)
 - configuration found
 - will use `entitiesDirs` paths:
   - /functions/build/src/db/model (found)
```

**Comment by B4nan** [comment]
> sqlite is in my devDeps, since i use postgres for production. i will eventually use postgres for testing too, but started with sqlite.

It does not search for deps in package.json, what it does is searching node_modules and getting the version from the actual package (as that information is not present in your package.json actually). do you really have `sqlite` module installed? maybe you have `sqlite3` instead? that is now supported as `knex` uses it, but original dependency of MikroORM is `sqlite` (promise based wrapper on `sqlite3`). 

> yellow warning, not red

It is not warning or error, red just says it was not found and green that it was found. I will keep it this way for now, its really just about the `found/not found` label, if it were a warning or error I would use yellow/red for the whole line.

**Comment by lookfirst** [comment]
Yes, sqlite3, so I guess at least that part needs to get fixed.

**Comment by B4nan** [comment]
Yeah in the end `sqlite` is really just a wrapper over `sqlite3` and now `sqlite` is not used in the codebase...

**Comment by B4nan** [comment]
> /functions/cli-config (not found) should really just be a yellow warning, not red, if the other two are found.

After thinking about this for a while, I think you are right, will change this to yellow as it is not required (on the other hand will keep red for checks in `entitiesDirs`, also globs are supported there, so will need to support that somehow too, now it just checks for the path via `fs`).

**Comment by B4nan** [comment]
try `3.0.0-alpha.11`

**Comment by B4nan** [comment]
Closing as resolved Tried latest alpha on your example project and works as expected.
