### ISSUE TITLE
Feature: Paginator for queries

### ISSUE THREAD

**Issue by rubiin** [mikro-orm/mikro-orm#1528]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Doctrine ORM ships with a Paginator for DQL queries. It has a very simple API and implements the SPL interfaces Countable and IteratorAggregate. We can do it manually, however when building something large an out of box solution can be very time saving. Typeorm supports this via a 3rd party package https://github.com/nestjsx/nestjs-typeorm-paginate

**Describe alternatives you've considered**
 paginator = new Paginator(query, fetchJoinCollection = true)

**Additional context**
All the details can be found here : https://www.doctrine-project.org/projects/doctrine-orm/en/2.8/tutorials/pagination.html#pagination

**Comment by B4nan** [comment]
This is already implemented as a `QueryFlag.PAGINATE`.

**Comment by B4nan** [comment]
https://github.com/mikro-orm/mikro-orm/blob/master/tests/EntityManager.mysql.test.ts#L2247
