### ISSUE TITLE
error when using subquery example

### ISSUE THREAD

**Issue by blackcurry** [mikro-orm/mikro-orm#1533]
**Describe the bug**

i'm using nestjs and mikro-orm/nestjs
I proceeded by referring to the example above, but there is an error when running the query.
When checking, the query made with knex.ref('a.id') is 
"b"."author_id" = **'"a"."id"'**, not "b"."author_id" = **"a"."id"**, which causes an error when executing the query.

| Dependency | Version |
| node | v14.15.4 |
| typescript | 4.1.5 |
| mikro-orm | 4.4.4 |
| your-driver | postgresql |
| mikro-orm/nestjs | 4.2.0 |
| @nestjs/core | 7.6.12 |

**Comment by B4nan** [comment]
Please provide actual repro, you are talking about _the_ example, why don't you link which one? You are talking about query, why don't you show the full code that runs it? You are talking about _an error_, why don't you provide the full error message with stack trace?

Let's not ignore the issue template. This is not how you should report bugs. Will be happy to reopen if you provide what's needed to reproduce.
