### ISSUE TITLE
Filter ignored if it's the same as discriminatorColumn

### ISSUE THREAD

**Issue by ramiel** [mikro-orm/mikro-orm#1539]
**Describe the bug**
I want to find some elements filtering by the same column as the discriminatorColumn. My filter is ignored and all the values are returned.

```
repo.find({col: {$in: ['a', 'b']}});
```

the query executed is `collection.find({col: {$in: ['a','b', 'c']}});

**Expected behavior**
My filter should take precedence

**Versions**

| Dependency | Version |
| - | - |
| node | 12 |
| typescript | 4.0.2 |
| mikro-orm | 4.4.4 |
| your-driver | mongo |

**Comment by B4nan** [comment]
Please provide actual reproduction, with entities and some input data.

**Comment by ramiel** [comment]
```ts
export enum RoomTypes {
  A = 'A',
  B = 'B',
  C = 'C',
}

  @Entity({
    discriminatorColumn: 'roomType',
    discriminatorValue: RoomTypes.A,
  })
  class Room  {
    @PrimaryKey()
    _id!: ObjectId;
  
    @SerializedPrimaryKey()
    id!: string;
  
    @Enum(() => RoomTypes)
    roomType!: RoomTypes;
  }


@Entity({ discriminatorValue: RoomTypes.B })
class RoomB extends Room {
}

// query
roomRepository.find({roomType: {$in: ['A']}});
```

This query still looks for B

**Comment by ramiel** [comment]
`roomRepository` is of type Room. I need to query on the base entity because the filter comes from the user

**Comment by B4nan** [comment]
But the base type won't add any condition for the `RoomB`, this is already tested and should work just fine:

https://github.com/mikro-orm/mikro-orm/blob/master/tests/features/single-table-inheritance.mysql.test.ts#L56

Can you provide full test case?

**Comment by ramiel** [comment]
Ok, I have no time now, I'll do my best to provide a complete example soon.

**Comment by B4nan** [comment]
Any updates on this? I am planning to ship v4.5 later this week, so if there is actual issue like this, I'd like to sort it out soon.

**Comment by ramiel** [comment]
Hello @B4nan . Sorry, I have no update on this, but I fear this may depend on my setup more than the library.

**Comment by B4nan** [comment]
Ok then please open new issue if you find a way to reproduce it and you still feel like it is a bug. 

Will close this one as it is not reproducible like this.
