### ISSUE TITLE
Adding using directives with @Index()

### ISSUE THREAD

**Issue by thekevinbrown** [mikro-orm/mikro-orm#1558]
**Is your feature request related to a problem? Please describe.**
We need to create an index like so:

```sql
create index "region_polygon_index" on "region" using gist("polygon");
```

**Describe the solution you'd like**
It'd be great to be able to specify the `using gist` part in an `@Index()` decorator for the schema generator.

**Describe alternatives you've considered**
Currently I've added the index in migrations and have a standard `@Index()` for it in the entity definition, which works fine, it'd just be nice to be able to emit the `using gist()` bit from the schema generator.

**Additional context**
If this is a feature you'd like to support I'm happy to have a crack at a PR to add this feature.

**Comment by B4nan** [comment]
I am currently rewriting schema diffing as a whole, so we have more precise and predictable results from it, so probably better to wait till this is done. 

The question is how can you do this via knex? Or will we need to create the indexes via raw queries? Knex does have a `type` parameter for the `index` function - and that is already exposed in the `@Index` decorator, so if that is enough, it should be already possible.

**Comment by thekevinbrown** [comment]
It's interesting. This seems to say that the type parameter is emitted in the index statement:
https://stackoverflow.com/questions/45871474/how-to-add-gin-index-using-knex-js

But when I set the index like:

```typescript
@Index({ type: 'GIST' })
@Property({ type: PolygonType, nullable: true })
polygon?: Polygon;
```

I'm not 100% sure, but I think it didn't come out in the generated result. I'll double check.

**Comment by B4nan** [comment]
Verified and it indeed works fine. What you might saw is another issue - indexes are currently diffed only by their name, so if the index was already created, it will never be changed. Which is something I already have fixed in the new schema diffing - targetting v5 for that.

**Comment by thekevinbrown** [comment]
Ah, yup, that's definitely what I hit. Thanks!
