### ISSUE TITLE
[bug] cache files have absolute paths

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#156]
Inside the cache files, there is an `origin` and `path` property that has an absolute path in it. I think that this path should really be relative to `baseDir`.

**Comment by B4nan** [comment]
Well that is on purpose, why do you think we should have relative path there? When the path differs, it will trigger cache reload for that entity (it should at least :) ). 

The idea was to force regenerating cache when changing baseDir or moving the project to different folder (e.g. deployment).

**Comment by lookfirst** [comment]
With that logic, if you move it to another directory, it invalidates the cache. It doesn't matter what the path is then. Deployment would break the cache anyway, so why even deploy the cache?

The data in the cache is only relative to baseDir to begin with. It doesn't need an absolute path to check for invalidation. If you change baseDir, why would that invalidate the cache?

**Comment by lookfirst** [comment]
We're back to my favorite quote: https://twitter.com/secretGeek/status/7269997868

**Comment by B4nan** [comment]
> Deployment would break the cache anyway, so why even deploy the cache?

One should not do that obviously. This is more of a fail safe thing so it still works even if one commits/deploys the cache. 

> If you change baseDir, why would that invalidate the cache?

Because you cannot know that possibly found entity in the new path is the same one as the one in old path. 

Again, more of a fail safe that should not be triggered, but this could happen:

- I have 2 entities with same name on two different locations, lets say A and B
- A is in location based on baseDir
- user changes baseDir so B is now in location based on baseDir

Cache won't be regenerated, but A and B might not be compatible.

**Comment by lookfirst** [comment]
> This is more of a fail safe thing so it still works even if one commits/deploys the cache.

What would break if you deploy the cache and the paths match up? Seems like at some level, the cache might even be worth checking in just for sanity to get diffs on.

> example....

I think that is a stretch. If there was a bug for that, then I'd consider fixing it in another way (like a simple hash on the file contents). I don't think that clogging the cache files with absolute paths is the solution for it.

**Comment by lookfirst** [comment]
Also realize that there are serverless environments that don't allow temp directories or don't benefit from it. I was even thinking of creating a firebase metadata backing for the cache....

**Comment by B4nan** [comment]
> I think that is a stretch. If there was a bug for that, then I'd consider fixing it in another way (like a simple hash on the file contents). I don't think that clogging the cache files with absolute paths is the solution for it.

Right, that sounds like a way to go, md5 hash of file contents as origin value and we can use relative paths in metadata.

> Also realize that there are serverless environments that don't allow temp directories or don't benefit from it. I was even thinking of creating a firebase metadata backing for the cache....

That is the reason why you can 1. disable cache and 2. implement your own cache adapter.

**Comment by B4nan** [comment]
Implemented in `3.0.0-alpha.15`, as always, feel free to reopen.
