### ISSUE TITLE
Use exists() with EntityManager

### ISSUE THREAD

**Issue by thekevinbrown** [mikro-orm/mikro-orm#1560]
**Is your feature request related to a problem? Please describe.**
We'd like to emit the following SQL:
```sql
select "e0".*
from "depot" as "e0"
where exists (
   select id
   from region
   where
     [region criteria in the filter] and
     ST_Intersects(e0.location, region.polygon)
)
```
I've gotten very close to getting where I want to go by being able to emit the above, but with an `= true` on the end:

```typescript
const subquery = orm.em
	.createQueryBuilder(Region, 'region')
	.select('id')
	.where(/* [region criteria in the filter] */)
	.andWhere(`ST_Intersects("e0"."location", "region"."polygon")`)
	.getFormattedQuery();

await orm.em.find(Depot, {
	[expr(`exists (${subquery})`)]: true
});
```

which emits:

```sql
select "e0".*
from "depot" as "e0"
where exists (
   select "region"."id"
   from "region" as "region"
   where [other filter criteria] and
      (ST_Intersects("e0"."location", "region"."polygon"))
) = true
```
Unfortunately the `= true` causes Postgres' optimizer to handle the query less efficiently, and I'd really like to stay away from `getFormattedQuery` here as while it quotes, I'd much rather have parameterised queries going to the database to be sure I'm not opening an SQL injection hole.

**Describe the solution you'd like**
I'd like to have a way to do this type of subquery with Entity Manager if possible. I was thinking it could work like this:

```typescript
await orm.em.find(Depot, {
	$exists: orm.em
		.createQueryBuilder(Region, 'region')
		.select('id')
		.where(/* [region criteria in the filter] */)
		.andWhere(`ST_Intersects("e0"."location", "region"."polygon")`)
});
```

**Describe alternatives you've considered**
1. I could theoretically use the query builder for this query, but I'm not actually sure how to. Knex has a kind of exists syntax using `.wrap`, but I couldn't see how to use `exists` or `not exists` with the Mikro query builder. This section of the docs only compares subqueries to specific values, not a pure `exists ()`: https://mikro-orm.io/docs/query-builder#using-sub-queries
2. I'm also not sure if there's a way to use `Knex.raw` or `.wrap` here to get what I'm after, and I'd be happy to, just trying to get this particular subquery to come out such that Postgres can optimise it into a join for me, and in a perfect world I'd love to be able to do it on EntityManager.

**Additional context**
As always, happy to implement this if it sounds interesting to you.

**Comment by B4nan** [comment]
Try this:

```ts
await orm.em.find(Depot, {
	[expr(`exists (${subquery})`)]: []
});
```

**Comment by thekevinbrown** [comment]
That results in:

```sql
select "e0".* from "depot" as "e0" where 1 = 0
```

Cool, I'll get to work on adding `$exists` as an operator that takes any query builder as the input.

**Comment by thekevinbrown** [comment]
Ok, having a really hard time with the aliases here.

What I need is to be able to reference an alias in the query builder inside the `$exists`, which hasn't been run through the entity manager yet.

To do that with an outer query builder, I can use `getAliasForJoinPath()`, but in this case we don't actually know what alias will be chosen.

What I'm trying to do is:

```typescript
orm.em.getRepository(Whatever).find({ $exists: orm.em
  .createQueryBuilder(Region, 'region')
  .where(
    `ST_Intersects("region"."polygon", "${
      // In here, I need to know whether Whatever will be e0, e1, etc.
      'e0'
    }"."location")`
  )});
```

I'm pretty sure I'm going to have to not create an $exists operator and instead just use query builder, no? Can you think of anything I'm missing?

**Comment by B4nan** [comment]
You would have to use a callback with the alias, just like in `@Formula` decorator.

```ts
em.find(Whatever, {
  $exists: alias => em.createQueryBuilder(Region, 'region').where(...),
});
```

But it might be a bit challanging as there could be conflicts (outer vs inner qb aliasing).

**Comment by thekevinbrown** [comment]
Yup, in the end we switched to query builder for this query and we do our own aliasing of the tables using `join`.

Thanks for your help!

**Comment by wasd171** [comment]
I think this feature is very much needed in the core.
Our use case is that we have an 1 -> N relation A -> B and would like to get all entities A where there is no connected B of a certain condition. Initially we tried
```
em.find(A, {
  $not: {
    b: {type: forbiddenType}
  }
})
```

Unfortunately this query does not output entities A that are connected to 0 entities B. `$exists` would've been super handy here
```
em.find(A, {
  $not: {
    $exists: {
      b: {type: forbiddenType}
    }
  }
})
```
