### ISSUE TITLE
Support for arrays of embeddables

### ISSUE THREAD

**Issue by chrispytoes** [mikro-orm/mikro-orm#1561]
In MongoDB, it's common to store an array of objects on a record for one-to-many relationships where the many side is not referenced by any other records. I see that nested embeddables were recently added, but I can't find anything in the docs related to storing an array of embeddables.

Is this possible or a feature that is already planned? If not, what are some ways to handle this with existing features?

**Comment by B4nan** [comment]
Already supported in master, see #1369 and #1496

https://mikro-orm.io/docs/next/embeddables#array-of-embeddables
