### ISSUE TITLE
nullable property is not automatically set if property is marked with ?

### ISSUE THREAD

**Issue by Beleren** [mikro-orm/mikro-orm#1569]
**Describe the bug**
Optional properties not working as [documentation](https://mikro-orm.io/docs/defining-entities/#optional-properties) explains: `nullable` property is not automatically set if property is marked with `?`

**Stack trace**
```
Error: You must pass a non-null value to the property test of entity TrackierRaw.
    at /mnt/hdd/Projects/rma/jarvis/media-event-ingestor/node_modules/@mikro-orm/core/entity/EntityAssigner.js:24:23
    at Array.forEach (<anonymous>)
    at Function.assign (/mnt/hdd/Projects/rma/jarvis/media-event-ingestor/node_modules/@mikro-orm/core/entity/EntityAssigner.js:17:27)
    at WrappedEntity.assign (/mnt/hdd/Projects/rma/jarvis/media-event-ingestor/node_modules/@mikro-orm/core/entity/WrappedEntity.js:42:48)
    at TrackierController.test (/mnt/hdd/Projects/rma/jarvis/media-event-ingestor/dist/trackier/trackier.controller.js:35:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /mnt/hdd/Projects/rma/jarvis/media-event-ingestor/node_modules/@nestjs/microservices/context/rpc-proxy.js:11:32
    at async ServerRMQ.handleEvent (/mnt/hdd/Projects/rma/jarvis/media-event-ingestor/node_modules/@nestjs/microservices/server/server.js:63:32)
```

**To Reproduce**
1. Define an optional property in your entity (e.g: `name?: string`);
```typescript
@Entity({ collection: 'trackier-raw' })
export class TrackierRaw {
  [EntityRepositoryType]?: TrackierRawRepository;

  @PrimaryKey()
  _id: ObjectId;

  @SerializedPrimaryKey()
  id: string;

  @Property()
  name?: string;
}
```

2. Create new entity;
```typescript
event = this.create({ name: data });
this.persistAndFlush(event);
```

3. Update entity with `wrap` and `assign`.
```typescript
const exists = await this.findOne({name: {$ne: null}});
if (exists) {
  event = exists;
  wrap(event).assign({ test: data.test });
 }
await this.flush();
```

**Expected behavior**
It should update any optional property as null when an Entity property is marked with optional flag `?` and `Property` decorator is not explicitly used with `nullable` argument.

**Additional context**
- NestJS;
- MongoDB.

**Versions**

| Dependency         | Version |
|--------------------|---------|
| Node               | 12.16.1 |
| typescript         | ^3.7.4  |
| @mikro-orm/core    | ^4.4.4  |
| @mikro-orm/nestjs  | ^4.2.0  |
| @mikro-orm/mongodb | ^4.4.4  |

**Comment by B4nan** [comment]
As the docs says, this only works with ts-morph.
