### ISSUE TITLE
EntitySchema documentation is outdated

### ISSUE THREAD

**Issue by Kinrany** [mikro-orm/mikro-orm#1581]
**Describe the bug**

EntitySchema documentation at https://mikro-orm.io/docs/entity-schema (linked from https://mikro-orm.io/docs/defining-entities) is outdated: `BaseEntity` in version `4.5.0` cannot be extended without explicitly specifying type parameters. The example code does not compile.

** Type Error **

```
Generic type 'BaseEntity<T, PK, P>' requires between 2 and 3 type arguments. ts(2707)
```

**To Reproduce**

Create a new `.ts` file and compile:

```typescript
import { BaseEntity } from '@mikro-orm/core';

interface Book extends BaseEntity {
  title: string;
}
```

**Expected behavior**
Examples from the docs should compile with the specified version of the ORM.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 14.16.0 |
| typescript | 4.2.3 |
| mikro-orm | 4.5.0 |
| your-driver | @mikro-orm/postgresql@4.5.0 |

**Comment by B4nan** [comment]
Not really, that example is not about the `BaseEntity` from the ORM (which is totally optional thing), but about _any_ base entity.

**Comment by Kinrany** [comment]
I see, thanks 🙂

**Comment by monarchwadia** [comment]
Just so you know, I got tripped up by this too :-)

**Comment by B4nan** [comment]
Feel free to send a PR and change the name to `MyBaseEntity` or something similar in the docs to make it more clear (or add a side note to point to the difference).

https://github.com/mikro-orm/mikro-orm/edit/master/docs/docs/entity-schema.md
https://github.com/mikro-orm/mikro-orm/edit/master/docs/versioned_docs/version-4.5/entity-schema.md
