### ISSUE TITLE
SQL injection concerns

### ISSUE THREAD

**Issue by lewispham** [mikro-orm/mikro-orm#1593]
I'm actually not quite sure about this issue. Basically when I retried to execute this code
```js
const topic = new Topic();
topic.name = "topic";
topic.description ="some descriptions";
await em.persistAndFlush(topic);
```
This log was printed.
```sql
insert into `topic` (`description`, `name`) values ('some descriptions', 'topic')
```

As I understand then sql commands should be executed with bound parameters in prepared statement fashion to prevent SQL injections. In that case this is should be the expected log
```sql
PREPARE stmt1 FROM 'insert into `topic` (`description`, `name`) values (?, ?)';
SET @name = 'topic';
SET @description = "some descriptions";
EXECUTE stmt1 USING @description, @name;
```

Is this a real issue or is there any magic done behind the current log?

**Comment by B4nan** [comment]
Escaping is done at the ORM level. I don't see any real issue with that, escaping is what prevents SQL injection. This was done mainly as a performance optimization, as with very large queries it is much faster this way. Also it allows much better debugging, as now you see the actual queries as they are executed - which was not true before, like in sqlite dates were printed as dates, but actual query used timestamps. 

Btw the escaping part is the very same as mysqljs library uses - they do the very same thing.

Btw2 the query is actually always constructed with `?` and then combined with parameters before execution.

Btw3 why would you expect a query like that to be printed? Is there some ORM doing it this way? Afaik everyone just prints the actual query even if prepared statements are used in the background - this would only make everything less readable. 

Will be happy to discuss actual issues, but this is purely theoretical... In other words, show me if it can be broken with current implementation, but I don't think so.

**Comment by lewispham** [comment]
Ah ok I see now. Thanks for the clarifications. I think it would be nice if you can include the above clarifications in the docs.

For the btw3, I just thought that exact logs can help developers on having better understanding about how the orm works as well as the way queries are really executed.
