### ISSUE TITLE
Custom Types with SQL fragments ignored in populate with joined strategy

### ISSUE THREAD

**Issue by haayman-imagem** [mikro-orm/mikro-orm#1594]
**Describe the bug**
I've defined a custom type but when using populate the 'convertToJSValueSQL' method isn't used to create the SQL statement

```
import { Geometry } from "geojson";
import { Type } from "@mikro-orm/core";
import { parse, stringify } from "wkt";

export class GeometryType extends Type<Geometry | undefined, string | undefined> {
  convertToDatabaseValue(value: Geometry | undefined): string | undefined {
    if (value === undefined || value === null) {
      return undefined;
    }

    return stringify(value);
  }

  convertToJSValue(value: string | undefined): Geometry | undefined {
    return value ? parse(value) : null;
  }

  convertToJSValueSQL(key: string) {
    return `ST_AsText(${key})`;
  }

  convertToDatabaseValueSQL(key: string) {
    return `ST_GeometryFromText(${key}, 4326)`;
  }

  getColumnType(): string {
    return "geometry";
  }
}
```

This should create SQL statements using 'st_AsText(geometry)'. However when using populate the SQL statement just says '"p1.geometry" as "p1__geometry"'

**Comment by haayman-imagem** [comment]
never mind. I just found the convertCustomTypes option

**Comment by haayman-imagem** [comment]
It turns out that the option convertCustomTypes doesn't work on findOne?

When I'm calling something like:
```
findOne(
  {code}, 
 {
    populate:['geometries'], 
    convertCustomTypes: true
  })
```
the resulting SQL statement doesn't contain 'ST_AsText(geometry)'

**Comment by B4nan** [comment]
This is not how you report a bug. You need to provide actual reproduction, ideally as a test case, but one way or the other, it needs to be complete and verifiable. 

Here are passing tests that do work with `findOne`: 

https://github.com/mikro-orm/mikro-orm/blob/master/tests/features/custom-types.test.ts

> However when using populate the SQL statement just says '"p1.geometry" as "p1__geometry"'

This sounds like you are using joined loading strategy? That is important thing to note, please provide something complete. Ideally try to extend the existing test to reproduce it.

**Comment by haayman-imagem** [comment]
I'm sorry, I don't know how to set that up. But fortunately it was indeed fixed by setting the loading strategy to SELECT_IN

**Comment by B4nan** [comment]
Let's keep this open, it sounds like a bug for sure.
