### ISSUE TITLE
Propagate Collection Reset to the inverse of a m2m Relation

### ISSUE THREAD

**Issue by dcrdev** [mikro-orm/mikro-orm#1596]
**Is your feature request related to a problem? Please describe.**
Currently diffing only happens on the owning side of a M2M relation, however there is some nuance here - altering the references on the inverse side works because the change is propagated up to the owning side, this does not work for resetting the collection i.e. assigning a empty array to the inverse side.

**Describe the solution you'd like**
It would be good if, when resetting a collection on the inverse, that were also propagated to the owning side.

**Comment by B4nan** [comment]
Closing as this should be working fine with v5 (tried to do `removeAll()` on an inverse side and it correctly removed the items from owner too).
