### ISSUE TITLE
[feature] Populate all

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#160]
I'd love an option to just load a top level entity and have it fully populated without having to do anything. Maybe just `{populate: true}`.

**Comment by B4nan** [comment]
Implemented in `3.0.0-alpha.15`, as always, feel free to reopen.

**Comment by lookfirst** [comment]
sweet! totally makes my day. loading `createdBy` all the time sucks. ;-)

i know you have your own tests, but this also works:

https://github.com/lookfirst/mikro-example/blob/master/test/db/populate.spec.ts

**Comment by lookfirst** [comment]
One other idea, what about using an annotation for this, like @Load. This way, I could just specify fields that I always wanted populated...

**Comment by B4nan** [comment]
Yeah, eager loading, that is also on the roadmap. Will probably do in as part of v3, as it should be pretty easy thanks to how populate support works now.

**Comment by lookfirst** [comment]
Oh interesting, populate `string | true` doesn't allow me to pass in a variable. it should be string | boolean i think.

**Comment by lookfirst** [comment]
Apologies, I don't see a way to reopen this issue.

**Comment by B4nan** [comment]
Its `string[] | true`, the array part is your problem I think. I could also support plain string.

**Comment by lookfirst** [comment]
No, it is a problem passing a boolean variable.

```
	async getRig(id: string, populate: boolean = true): Promise<Rig | null> {
		console.log('in get rig!');
		return this.getOrm().em.findOne(Rig, id, {populate});
	}
```

```
Error:(20, 10) TS2769: No overload matches this call.
  Overload 1 of 2, '(entityName: EntityName<Rig>, where: string | number | Record<string, any> | { toString?(): string; toHexString?(): string; } | Partial<Rig>, options?: FindOneOptions | undefined): Promise<...>', gave the following error.
    Argument of type '{ populate: boolean; }' is not assignable to parameter of type 'FindOneOptions'.
      Types of property 'populate' are incompatible.
        Type 'boolean' is not assignable to type 'true | string[] | undefined'.
  Overload 2 of 2, '(entityName: EntityName<Rig>, where: string | number | Record<string, any> | { toString?(): string; toHexString?(): string; } | Partial<Rig>, populate?: true | string[] | undefined, orderBy?: Record<...> | undefined): Promise<...>', gave the following error.
    Argument of type '{ populate: boolean; }' is not assignable to parameter of type 'true | string[] | undefined'.
      Object literal may only specify known properties, and 'populate' does not exist in type 'string[]'.
```

**Comment by B4nan** [comment]
Yeah well `false` is currently not valid value and it will probably cause an error. You could define your signature as:

	async getRig(id: string, populate: string[] | true = true): Promise<Rig | null> { }

But I can support `false` as well, probably better to do so, as it can be used without TS at all so no type checks for literal types...

**Comment by B4nan** [comment]
Fixed in dev branch.
