### ISSUE TITLE
Question: Use where clause on JOIN

### ISSUE THREAD

**Issue by HunterJS-bit** [mikro-orm/mikro-orm#1600]
Hi, gotta say first you have a great library, I have a quick question is it possible to use where clause in **populate**

For example:

`const author = await em.findOne(AuthorSchema, { ... }, ['books']);`

I would like to add also where clause so that it gets executed like:
`
INNER JOIN Books ON Book.authorId = Author.id AND Book.Name = 'Lord of the rings' ) `

**Comment by thekevinbrown** [comment]
Try
```typescript
const author = await em.findOne(AuthorSchema, { books : { name: 'Lord of the rings' } }, ['books']);
```

More info here: https://mikro-orm.io/docs/query-conditions

**Comment by B4nan** [comment]
To adjust the `on` condition you'd have to use a QB, if you are fine with `where` condition, then what Kevin is saying is the way to go.

**Comment by HunterJS-bit** [comment]
@B4nan @thekevinbrown 
Thank you for ansering
