### ISSUE TITLE
postgres should default to timestamptz for Date objects

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#161]
https://github.com/mikro-orm/mikro-orm/blob/dev/lib/schema/PostgreSqlSchemaHelper.ts#L31

for a Date type, postgres should default to timestamptz. 

http://knexjs.org/#Schema-timestamp
http://www.postgresqltutorial.com/postgresql-timestamp/

**Comment by B4nan** [comment]
Implemented in `3.0.0-alpha.14`.
