### ISSUE TITLE
Nestjsx CRUD integration

### ISSUE THREAD

**Issue by in-live-md** [mikro-orm/mikro-orm#1622]
**Is your feature request related to a problem? Please describe.**
My project depends on nestjsx/crud - it would be nice if mikro-orm supported this to make it easier to unplug typeorm

**Describe the solution you'd like**
Implement in mikro-orm similar to https://github.com/nestjsx/crud/blob/master/packages/crud-typeorm/src/typeorm-crud.service.ts

**Describe alternatives you've considered**
Handwrite each endpoint

**Comment by B4nan** [comment]
This is outside of the scope of this project. It is a 3rd party plugin to help ease integration with ORM and nest - this does not belong to the ORM at all, just like it was not part of typeorm.

I would rather push it on their end (https://github.com/nestjsx/crud/issues/499).

Also this is not a rocket science, if you miss such a plugin, another alternative is to write it yourself - will be happy on that path.
