### ISSUE TITLE
Relationships populate

### ISSUE THREAD

**Issue by blinkofaneye** [mikro-orm/mikro-orm#1629]
**Is your feature request related to a problem? Please describe.**
Relationships are not auto-populated. Suppose you have one to many relationship, you need to do:
```ts
const table = await tableRepository.findOne(..., ['chairs']);
const chairs = table.chairs.getItems();
```
Otherwise, you will get an error.

**Describe the solution you'd like**
Why getItems() doesn't check if the relationship is initialized and if not, initialize it?

**Describe alternatives you've considered**
For now, i just keep track of all the relationships i need to load in my code.

**Comment by B4nan** [comment]
That method is sync, it cannot load anything. You can use `coll.loadItems()` that will lazy load if the collection is not already initialized.
