### ISSUE TITLE
[feature] count(tablename)

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#163]
I just want to count all the entities without the requirement of a where clause.

`select count(*) from 'table';`

**Comment by B4nan** [comment]
So basically just making the where parameter optional will be enough, right?

**Comment by lookfirst** [comment]
Exactly.

**Comment by B4nan** [comment]
Looks like it was supported via `repository.count()` already. Now it allows omitting the `where` parameter in `em.count()` as well (in the `dev` branch). Will publish new alpha once #157 is finalized.

**Comment by B4nan** [comment]
Available in `3.0.0-alpha.16`.
