### ISSUE TITLE
Expected Iterable

### ISSUE THREAD

**Issue by sasa6277** [mikro-orm/mikro-orm#1631]
**Describe the bug**

**Stack trace**
i use mikro-orm v4.5.1
my code is :

`@Mutation(() => [Post])
  async createPost(
    @Arg('title', () => String) title: string,
    @Arg('body', () => String) body: string,
    @Ctx() { em }: MYContext
  ): Promise<Post> {
    const post = em.create(Post, { title, body });
    await em.persistAndFlush(post);
    console.log(post);

    return post;
  }`

and my mutation is

`mutation{
  createPost(title:"new post 4",body:"new body"){
    _id
    
  }
}`

my post Entity:
`import { Entity, PrimaryKey, Property } from '@mikro-orm/core';
import { Field, Int, ObjectType } from 'type-graphql';

@ObjectType()
@Entity()
export class Post {
  @Field(() => Int)
  @PrimaryKey()
  _id!: number;

  @Field(() => String)
  @Property({ type: 'date' })
  createdAt: Date = new Date();

  @Field(() => String)
  @Property({ type: 'date', onUpdate: () => new Date() })
  updatedAt: Date = new Date();

  @Field(() => String)
  @Property({ type: 'text' })
  title!: string;

  @Field(() => String)
  @Property({ type: 'text' })
  body!: string;
}`

error is :
`"errors": [
    {
      "message": "Expected Iterable, but did not find one for field \"Mutation.createPost\".",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createPost"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "message": "Expected Iterable, but did not find one for field \"Mutation.createPost\".",
          "stacktrace": [
            "GraphQLError: Expected Iterable, but did not find one for field \"Mutation.createPost\".",`

the row create and i can see data in console log,

but there is problem in fineone(Post,{_id:id})

```
...
```

**To Reproduce**
1. i get above error

**Expected behavior**

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 12 |
| typescript | 4.2 |
| mikro-orm | 4.5.1 |
| your-driver | postgres |

**Comment by B4nan** [comment]
This is very lazy bug report. "i get above error" is definitely not a way to reproduce your issue. 

Your issue is not with MikroORM, but with the layer above. My guess is that instead of `@Mutation(() => [Post])` you should be doing `@Mutation(() => Post)` in your `createPost` handler, but not a GQL user myself.

Will close this as it is not a MikroORM issue. Next time please try to respect the issue template and pay some attention to the formatting too
