### ISSUE TITLE
Model factory

### ISSUE THREAD

**Issue by rubiin** [mikro-orm/mikro-orm#1635]
**Is your feature request related to a problem? Please describe.**
We have our database but no data. One way to change that would be to manually enter data directly in the database.

But what append if we delete those data and want more? It will be a big time lost to go to the database each time and also that could be a security issues.

The "pro" way to do that is to use Factories and Seeders. The difference between those is the Model Factory object is a fake Model data creator and Seeder is used when we need to create real data in one table.

An example of Model Factory will be a UserFactory that define and create one or many fake users.

An example of Database seeding is a CountrySeeder that will fill the table countries with real country names. The Seeders can then for example be run before testing phase and/or another time before deploying to production

**Describe the solution you'd like**

something like this:
```
import Factory from '@mikro-orm/core'
import Post from 'App/Models/Post'

export const PostFactory = Factory
  .define(Post, ({ faker }) => {
    return {
      title: faker.lorem.sentence(),
      content: faker.lorem.text(),
    }
  })
  .build()

```

To create data we have to execute the ```PostFactory.create() or PostFactory.createMany(x)```

For simplicity purpose we can execute that code when visiting a specific route.

Let's open the start/routes.ts file and add this route:
```
route.get('/create-posts', async () => {
    await PostFactory.createMany(5)
})
```
So when we visit the '/create-posts' route. The PostFactory will create 5 fake posts.

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by B4nan** [comment]
This is already implemented and scheduled for v5. See #929.
