### ISSUE TITLE
Option to create an empty migration file

### ISSUE THREAD

**Issue by Dragory** [mikro-orm/mikro-orm#1636]
**Is your feature request related to a problem? Please describe.**
I prefer to write migrations by hand, from scratch.

**Describe the solution you'd like**
I'd like to have an option in the CLI to simply generate an empty migration file with no diffing against the schema.
E.g. `npx mikro-orm migration:create --empty`

**Describe alternatives you've considered**
The current best alternative is to generate a migration and then remove everything in it. This works fine, so it's more of a QoL request.

**Comment by Dragory** [comment]
I just realized there already is a `--blank` / `-b` option in the CLI. I didn't see this documented in the [Migrations](https://mikro-orm.io/docs/migrations) docs page, so I assumed it didn't exist. `npx mikro-orm migration:create --help` revealed this and other options.

**Comment by B4nan** [comment]
There is a toggle for that already, its `--blank` or `-b`.

**Comment by Dragory** [comment]
Thank you, @B4nan! I definitely should've checked the `--help` for `migration:create` before posting the issue 😅

**Comment by B4nan** [comment]
Anyway, PR mentioning this in the docs is welcome :)
