### ISSUE TITLE
Allow control over optimistic version numbers

### ISSUE THREAD

**Issue by nordfjord** [mikro-orm/mikro-orm#1638]
**Is your feature request related to a problem? Please describe.**

I want to use optimistic concurrency controls, but I also want to control the version number myself.

For example:

```ts
async function updateEntity(entity, event) {
  await orm.em.lock(entity, LockMode.OPTIMISTIC, entity.version);
  entity.version = event.version;
  doSomeStuffToTheEntity(entity, event)
  await orm.flush()
}
```

**Additional context**

This would be really helpful in event sourced contexts where we can say "this is the entity as of log version X"

**Comment by B4nan** [comment]
So you are asking for the change set tracking to respect the version value you provide, instead of incrementing? So if there is no difference, it would do the increment as it is now, but if you provide a different value that the one loaded from the database, it would use it?

**Comment by nordfjord** [comment]
> So you are asking for the change set tracking to respect the version value you provide, instead of incrementing?

Yes! Exactly

> So if there is no difference, it would do the increment as it is now, but if you provide a different value that the one loaded from the database, it would use it?

Yes that would certainly be a way to implement it! In my context (event sourced projection) I would always provide a newer version since all changes happen through events

**Comment by B4nan** [comment]
Ok, makes sense. Will probably keep this for v5, already started on it...

**Comment by nordfjord** [comment]
Sorry to butt back in. I thought a bit more about

> So if there is no difference, it would do the increment as it is now

I'm not sure that'd work for my use case. I think it would be better to put it entirely in the hands of the user to make sure to increment the version.

the reason I say this is because if two entities have the same version that means there's a conflict

I've implemented something that works for me via a subscriber:

```ts
@Subscriber()
export class VersionSubscriber
  implements EventSubscriber<{ checkpoint: bigint }> {
  getSubscribedEntities(): EntityName<{ checkpoint: bigint }>[] {
    return Entities;
  }

  async onFlush(args: FlushEventArgs): Promise<void> {
    const changeSets = args.uow.getChangeSets();
    const updates = changeSets.filter((x) => x.type === ChangeSetType.UPDATE);

    if (updates.length === 0) return;

    const hasSameVersionOrGreater = updates.find(
      (x) => x.entity.checkpoint >= x.entity.__next__checkpoint,
    );
    if (hasSameVersionOrGreater) {
      throw OptimisticLockError.lockFailed(hasSameVersionOrGreater);
    }

    const meta = updates[0].entity.__meta!;
    const $or = updates.map((x) => ({
      ...Utils.getPrimaryKeyCond(x.entity, meta.primaryKeys)!,
      checkpoint: x.entity.checkpoint!,
    }));

    const result = await args.em
      .getDriver()
      .find(meta.className, { $or }, { fields: meta.primaryKeys });

    if (result.length !== updates.length) {
      const compare = (a: any, b: any, keys: string[]) =>
        keys.every((k) => a[k] === b[k]);
      const entity = updates.find(
        (cs) =>
          !result.some((row) =>
            compare(
              Utils.getPrimaryKeyCond(cs.entity, meta.primaryKeys)!,
              row,
              meta.primaryKeys,
            ),
          ),
      )!.entity;
      throw OptimisticLockError.lockFailed(entity);
    } else {
      for (const update of updates) {
        update.entity.checkpoint = update.entity.__next__checkpoint!;
        args.uow.recomputeSingleChangeSet(update.entity);
      }
    }
  }
}
```

It's basically stitching together some of your `ChangeSetPersister` code.

Due to the nature of messaging it's very hard to guarantee "only-once" delivery.

So if I get a batch of events like:

```yaml
- {version: 1}
- {version: 1}
- {version: 2}
```

Then I'd expect that I'd succeed for the first event, and get an optimistic concurrency lock for the second one because I know it's already been handled

**Comment by B4nan** [comment]
Then we need a flag to allow this behaviour, that will disable the auto increment.

Or maybe #1525 would work for you? It will allow to pick what properties should be used for the version check, and they are just regular props, so no auto increment or any handling of them.

**Comment by nordfjord** [comment]
>  It will allow to pick what properties should be used for the version check, and they are just regular props, so no auto increment or any handling of them.

That would work beautifully!
