### ISSUE TITLE
[feature] persistAndFlush() should return Promise<Entity>

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#164]
Consider the following:

```ts
	async savePerson(user: UserInfo): Promise<Person> {
		const person = new Person({
			id: user.uid,
			email: user.email,
			photoURL: user.photoURL,
			displayName: user.displayName
		});

		await this.getOrm().em.persistAndFlush(person);
		return person;
	}
```

The problem with this is that awaiting the promise means that I can't do something like Promise.all() further down the line. It effectively serializes the persisting of the data. Obviously, I could convolute it a bit with wrapping in promises (or .then()), but it would be easier if pAF just returned the entity that was persisted... ala....

```ts
	async savePerson(user: UserInfo): Promise<Person> {
		const person = new Person({
			id: user.uid,
			email: user.email,
			photoURL: user.photoURL,
			displayName: user.displayName
		});

		return this.getOrm().em.persistAndFlush(person);
	}
```

Note that this would apply to all the em methods that return Promise<void> for stuff like this.

**Comment by B4nan** [comment]
This would result in every user being created inside its own small transaction, that is usually not what you want. Why not just use persist and do the flush once?

**Comment by lookfirst** [comment]
Ah, good point, forgot about that. Nevermind!

**Comment by B4nan** [comment]
https://stackoverflow.com/questions/55339019/how-can-i-insert-an-object-graph-by-using-mikroorm

**Comment by B4nan** [comment]
Btw you could achieve parallel inserts via `nativeInsert` wrapped in explicit transaction I think. Something like following:

```typescript
await orm.em.transactional(em => {
  await Promise.all(users.map(userData => em.nativeInsert(User, userData)));
});
```

Although you will end up with empty identity map (no entities created, just data inserted into database). `nativeInsert` will return `QueryResult` instance, that will have `insertId` property, so you could capture those into array and then manually construct entities from that (via `em.create()` or `em.merge()`). 

Still the way to go is with single `flush` I would say, it will do things serially though.

**Comment by lookfirst** [comment]
Thanks. Yea... you are totally right. I was just being dumb (again). Long day.
