### ISSUE TITLE
[discussion] how to run on firebase cloud functions

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#165]
Latest beta.

So this super simple code is failing, but I think I know the reason. It is because I'm running against the processed output from tsc instead of the actual typescript code, so the discovery isn't working right.

The issue is that this code will eventually live on firebase functions and up there, there is no ts-node... just compiled javascript.

I am not really sure how to resolve this. I guess one way would be to store the cached files somewhere and force that for the processing?

This also brings up the issue of needing to better handle the case where discovery really isn't doing anything...

fyi... https://firebase.google.com/docs/functions

```
		const jon = new Person({
				id: 'IDVALUE',
				displayName: 'Jon Stevens',
				email: 'jon@wdomain.com',
			}
		);
		mikroORM.em.persist(jon);
		await mikroORM.em.flush();
```

note the: `./build/src/db/model`

```
>  [info] MikroORM successfully connected to database rig-manager on postgresql://@127.0.0.1:5432
>  [discovery] ORM entity discovery started
>  [discovery] - processing 14 files from directory ./build/src/db/model
>  [discovery] - processing entity BaseEntity
>  [discovery] - ignoring file BaseEntity.js.map
>  [discovery] - processing entity Datacenter
>  [discovery] - ignoring file Datacenter.js.map
>  [discovery] - processing entity Gpu
>  [discovery] - ignoring file Gpu.js.map
>  [discovery] - processing entity Invoice
>  [discovery] - ignoring file Invoice.js.map
>  [discovery] - processing entity Person
>  [discovery] - ignoring file Person.js.map
>  [discovery] - processing entity Psu
>  [discovery] - ignoring file Psu.js.map
>  [discovery] - processing entity Rig
>  [discovery] - ignoring file Rig.js.map
>  [discovery] - entity discovery finished after 2180 ms
>  [query] begin
>  [query] begin
>  [query] insert into "Person" ("createdAt", "displayName", "email", "id", "photoURL", "updatedAt") values ('2019-09-26 14:11:03.263', 'Jon Stevens', 'jon@wdomain.com', 'IDVALUE', NULL, '2019-09-26 14:11:03.328') returning "id" [took 16 ms]
>  [query] rollback
>  (node:10141) UnhandledPromiseRejectionWarning: error: null value in column "id" violates not-null constraint
>      at Connection.parseE (/functions/node_modules/pg/lib/connection.js:604:11)
>      at Connection.parseMessage (/functions/node_modules/pg/lib/connection.js:401:19)
>      at Socket.<anonymous> (/functions/node_modules/pg/lib/connection.js:121:22)
>      at Socket.emit (events.js:209:13)
>      at Socket.EventEmitter.emit (domain.js:499:23)
>      at addChunk (_stream_readable.js:305:12)
>      at readableAddChunk (_stream_readable.js:286:11)
>      at Socket.Readable.push (_stream_readable.js:220:10)
>      at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
>  From previous event:
>      at Client_PG._query (/functions/node_modules/knex/lib/dialects/postgres/index.js:234:12)
>      at Client_PG.query (/functions/node_modules/knex/lib/client.js:158:17)
>      at /functions/node_modules/knex/lib/transaction.js:325:24
>  From previous event:
>      at Client_PG.trxClient.query (/functions/node_modules/knex/lib/transaction.js:320:12)
>      at Runner.query (/functions/node_modules/knex/lib/runner.js:135:36)
>      at /functions/node_modules/knex/lib/runner.js:39:23
>  From previous event:
>      at Runner.run (/functions/node_modules/knex/lib/runner.js:25:16)
>      at Builder.Target.then (/functions/node_modules/knex/lib/interface.js:14:43)
```

**Comment by lookfirst** [comment]
Ok... this is making me think even further... this is a whole mess with the cache. basically... what happens when I want to deploy only javascript to my production server? what if there is only one file produced and it is a js file? all the paths and hashes in the cache files are meaningless....

**Comment by B4nan** [comment]
> So this super simple code is failing, but I think I know the reason. It is because I'm running against the processed output from tsc instead of the actual typescript code, so the discovery isn't working right.

Are you sure it is not working right? I see correctly formed query and postgres error. What happens if you run that query manually? I see the id there, 

> The issue is that this code will eventually live on firebase functions and up there, there is no ts-node... just compiled javascript.

`ts-node` is a JS program, it can run anywhere, there is no special magic. you just generally do not want to run that in production, but it is 100% possible. 

> This also brings up the issue of needing to better handle the case where discovery really isn't doing anything...

Well there is already (I would say) extensive validation, it fails when source entity is not found (and is needed), it also fails if no entity was discovered. 

> note the: ./build/src/db/model 

What you see in the logs seems good, it is ok to see the compiled dir in the production. You will see the one with TS entities only when running via `ts-node`. When you run compiled code, then compiled entities will be discovered. It is also important to deploy your TS source files alongside the compiled output to allow the discovery as it will read types from the TS entity file, but the discovery happens on compiled entities. 

Btw it took 2180 ms to do the discovery, I am pretty sure it did the job.

**Comment by B4nan** [comment]
> Ok... this is making me think even further... this is a whole mess with the cache. basically... what happens when I want to deploy only javascript to my production server? what if there is only one file produced and it is a js file? all the paths and hashes in the cache files are meaningless....

1 entity has to be in 1 file, that is a requirement currently.

**Comment by lookfirst** [comment]
> It is also important to deploy your TS source files alongside the compiled output to allow the discovery as it will read types from the TS entity file, but the discovery happens on compiled entities.

As far as I can tell, that isn't how firebase functions works. It deploys a single compiled file.

**Comment by B4nan** [comment]
I will need to add a section about deploying into docs, where I will describe how it works, that is really missing and can be confusing... 

Back to your problem, as I said, I believe the discovery went well, what looks strange to me is that double transaction:

>  [query] begin
>  [query] begin

> As far as I can tell, that isn't how firebase functions works. It deploys a single compiled file.

Never used that, but how come it deploy single file, when you have `./build/src/db/model` folder filled with your entities? Also discovery finished, meaning that their TS counterparts were found as well.

**Comment by lookfirst** [comment]
> two begins

Yes, had a second item in there ... investigating if that is the issue now. I assumed that since the query just showed the failed insert on Person.

> why do you see the directory?

Running locally in their emulator. Actual live deployment is different.

**Comment by lookfirst** [comment]
Ok, my apologies, this is failing on the second persist. 'id' is a primary column and I'd think that it would just get created with a new... but alas...

```
		const jon = new Person({
				id: 'ID',
				displayName: 'Jon Stevens',
				email: 'jon@',
			}
		);

		const dc = new Datacenter({name: 'Name', createdBy: jon});

		mikroORM.em.persist(jon);
		mikroORM.em.persist(dc);
		await mikroORM.em.flush();
```

**Comment by B4nan** [comment]
This is something that I recently discovered myself and it took me some time till I understood it, but when query fails, it is not logged. It looks especially weird with transactions. 

I think we could log the query with some `(error)` prefix so one can clearly see what query caused it. Because sometimes you will see the query in error message, but in this case, you don't... 

> 'id' is a primary column and I'd think that it would just get created with a new

Depends on how your entity/schema is defined. Auto-generated PKs works (for postgres it uses `serial` type).

**Comment by lookfirst** [comment]
funny...

```
		const jon = new Person({
				id: 'ID,
				displayName: 'Jon Stevens',
				email: 'jon@',
			}
		);

		const dc = mikroORM.em.create(Datacenter, {name: 'NAME', createdBy: jon});

		mikroORM.em.persist(dc);
		await mikroORM.em.flush();
```

```
>  [info] MikroORM successfully connected to database rig-manager on postgresql://@127.0.0.1:5432
>  [discovery] ORM entity discovery started
>  [discovery] - processing 14 files from directory ./build/src/db/model
>  [discovery] - processing entity BaseEntity
>  [discovery] - using cached metadata for entity BaseEntity
>  [discovery] - ignoring file BaseEntity.js.map
>  [discovery] - processing entity Datacenter
>  [discovery] - using cached metadata for entity Datacenter
>  [discovery] - ignoring file Datacenter.js.map
>  [discovery] - processing entity Gpu
>  [discovery] - using cached metadata for entity Gpu
>  [discovery] - ignoring file Gpu.js.map
>  [discovery] - processing entity Invoice
>  [discovery] - using cached metadata for entity Invoice
>  [discovery] - ignoring file Invoice.js.map
>  [discovery] - processing entity Person
>  [discovery] - using cached metadata for entity Person
>  [discovery] - ignoring file Person.js.map
>  [discovery] - processing entity Psu
>  [discovery] - using cached metadata for entity Psu
>  [discovery] - ignoring file Psu.js.map
>  [discovery] - processing entity Rig
>  [discovery] - using cached metadata for entity Rig
>  [discovery] - ignoring file Rig.js.map
>  [discovery] - entity discovery finished after 16 ms
>  (node:40724) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'reference' of undefined
>      at /functions/node_modules/mikro-orm/dist/entity/EntityFactory.js:68:36
```

**Comment by lookfirst** [comment]
```
export class Datacenter extends BaseEntity {

	@PrimaryKey()
	id: number;

```

**Comment by B4nan** [comment]
And how does the schema look like? (even if you use schema generator for that, please double check the real schema)

> const dc = mikroORM.em.create(Datacenter, {name: 'NAME', createdBy: jon});

This is pretty much the same as what you had before. `em.create()` does instantiate the entity for you, it is handy when you use constructors in your entities as it will extract ctor params for you and pass them to the ctor, extracting them from the rest that as just simply assigned. 

Problem will be either in schema (that would mean the query will fail), or in metadata (that would mean your entity would not have PK set after successful insert query.

**Comment by lookfirst** [comment]
I used your schema generator.

```
create table "Datacenter"
(
    "createdAt" timestamp with time zone not null,
    "updatedAt" timestamp with time zone not null,
    id          serial                   not null
        constraint "Datacenter_pkey"
            primary key,
    name        varchar                  not null,
    "createdBy" varchar(255)
        constraint datacenter_createdby_foreign
            references "Person"
            on update cascade on delete set null,
    "updatedBy" varchar(255)
        constraint datacenter_updatedby_foreign
            references "Person"
            on update cascade on delete set null
);

```

**Comment by lookfirst** [comment]
> And how does the schema look like? (even if you use schema generator for that, please double check the real schema)
> 
> > const dc = mikroORM.em.create(Datacenter, {name: 'NAME', createdBy: jon});
>
> This is pretty much the same as what you had before. `em.create()` does instantiate the entity for you, it is handy when you use constructors in your entities as it will extract ctor params for you and pass them to the ctor, extracting them from the rest that as just simply assigned.

Right, I'm just trying both ways to see what happens. This way got a different error.

```
import {Collection, Entity, IEntity, ManyToOne, OneToMany, PrimaryKey, Property} from "mikro-orm";
import {BaseEntity} from "./BaseEntity";
import {Person} from "./Person";
import {Rig} from "./Rig";

@Entity()
export class Datacenter extends BaseEntity {

	@PrimaryKey()
	id: number;

	@Property({columnType: 'varchar'})
	name: string;

	@OneToMany(() => Rig, rig => rig.datacenter)
	rigs = new Collection<Rig>(this);

	@ManyToOne()
	createdBy: Person;

	@ManyToOne({nullable: true})
	updatedBy: Person;

	constructor(datacenter: Partial<Datacenter>) {
		super();
		this.id = datacenter.id!;
		this.name = datacenter.name!;
		this.createdBy = datacenter.createdBy!;
		this.updatedBy = datacenter.updatedBy!;
	}
}

export interface Datacenter extends IEntity<number> {
}
```

**Comment by lookfirst** [comment]
BaseEntity just has createdAt/updatedAt defined in it.

**Comment by lookfirst** [comment]
I think the crucial thing here is to test whether or not things work after running discovery on output from tsc. I've never had my tests pass when that happens. =(

**Comment by B4nan** [comment]
>  (node:40724) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'reference' of undefined
>      at /functions/node_modules/mikro-orm/dist/entity/EntityFactory.js:68:36

This is actually a bug in `em.create()` as it currently requires you to have constructor parameters named as entity properties, it does not support passing object like you do. Let's stick with the manual instantiation here.

Can you try commenting out this like in `Datacenter`'s ctor? 

> this.id = datacenter.id!;

Starting to be a bit lost in the conversation now, so also please paste current code and stack trace :] Btw you are now debugging on localhost, or is this working there and fails only in the firebase emulator?

> I think the crucial thing here is to test whether or not things work after running discovery on output from tsc. I've never had my tests pass when that happens. =(

My nestjs app is working without any problems, and it obviously does use compiled output in the production. 

---

Just one note that is totally off this discussion, but if you define base entity, you can move the interface merging with `IEntity` there so you do not have to repeat it in each entity.

**Comment by lookfirst** [comment]
> > (node:40724) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'reference' of undefined
> > at /functions/node_modules/mikro-orm/dist/entity/EntityFactory.js:68:36
> 
> This is actually a bug in `em.create()` as it currently requires you to have constructor parameters named as entity properties, it does not support passing object like you do. Let's stick with the manual instantiation here.

Oh good, I'm not totally crazy then. =)

> Can you try commenting out this like in `Datacenter`'s ctor?
> 
> > this.id = datacenter.id!;

Sure! And I just tested it with new Datacenter() and that works.

> Starting to be a bit lost in the conversation now, so also please paste current code and stack trace :] Btw you are now debugging on localhost, or is this working there and fails only in the firebase emulator?

I haven't tried a firebase deploy yet... just failing in local on the emulator.

> > I think the crucial thing here is to test whether or not things work after running discovery on output from tsc. I've never had my tests pass when that happens. =(
> 
> My nestjs app is working without any problems, and it obviously does use compiled output in the production.

Cool... good to know. I can see in the cache files that when they get created with a .ts.json suffix, the contents are the same as .js.json (except the internal names of the files of course). So I guess it is working...

> Just one note that is totally off this discussion, but if you define base entity, you can move the interface merging with `IEntity` there so you do not have to repeat it in each entity.

I use a mix of string/number for primary keys. Can I still do that?

Looking forward to the next release...

**Comment by B4nan** [comment]
> I use a mix of string/number for primary keys. Can I still do that?

Sure, every entity can have different PK type, in ORM's tests all entities have auto increment (serial) types and one have UUID (Book entity). 

> Sure! And I just tested it with new Datacenter() and that works.

What works, creating the entity or getting back auto generated PK? :] 

> Cool... good to know. I can see in the cache files that when they get created with a .ts.json suffix, the contents are the same as .js.json (except the internal names of the files of course). So I guess it is working...

Yeah that is how it should look like. 

---

Another out of this discussion note - thanks to cascading, you can persist only the `Datacenter` entity, and as your `Person` entity is referenced from it, it will be cascade-persisted too.

**Comment by lookfirst** [comment]
This is what works after commenting out the id setter in the constructor of datacenter...

```
const jon = new Person({
				id: 'ID',
				displayName: 'Jon Stevens',
				email: 'jon@',
			}
		);

		const dc = new Datacenter({name: 'Name', createdBy: jon});

		mikroORM.em.persist(dc);
		await mikroORM.em.flush();
```

> re IEntity

Awesome! Just removed it all over the place. Make sure to document that please. =)

**Comment by B4nan** [comment]
I will debug this myself, I think it might be problem with your constructors as that approach with data object in ctor is not used in the whole test suite. It might call your constructor even when it is not supposed to do so (entity ctors are supposed to be called only when you instantiate the entity yourself, either via `new` or via `em.create()`, otherwise `Object.create()`).

**Comment by lookfirst** [comment]
Cool. I don't feel like I'm doing anything too crazy with that approach.

**Comment by B4nan** [comment]
I will definitely support it, it just needs some additional tests :]
