### ISSUE TITLE
Question: Named bindings

### ISSUE THREAD

**Issue by theoephraim** [mikro-orm/mikro-orm#1654]
I have a situation where I have some pretty complex raw queries that are being constructed. To avoid dealing with escaping values myself, I'd like to let the query builder handle this. Additionally, because the queries are complex and constructed in many steps, I'd rather not have the ordering of the replacements be significant. In many other tools, I would use "named bindings" to do this, but I can't find any example of this in the docs.

For example, something like  `runQuery('SELECT * FROM mytable WHERE foo = :fooval', { fooval: 'value to use in the query' })`

Knex mentions this [here](http://knexjs.org/#Raw) as "named bindings", but I can't seem to find the right way to get access to this method, as the TS type for `queryBuilder.raw()` only accepts a single string.

**Comment by B4nan** [comment]
`qb.raw()` is just a shortcut for `qb.getKnex().raw()`, so you could use that to work with the real knex method (where the binding parameter exists).

sure we can add it here too (PR welcome)
