### ISSUE TITLE
LoadStrategy not honored on ManyToOne

### ISSUE THREAD

**Issue by evantrimboli** [mikro-orm/mikro-orm#1657]
**Describe the bug**
If I specify the `strategy` on a `ManyToOne` to be joined, the query doesn't do a join to load.

**Stack trace**
N/A

**To Reproduce**

Consider the following entities:
```typescript
@Entity()
export default class Order {
  @PrimaryKey()
  id!: number;

  @OneToMany(() => OrderItem, ({ order }) => order)
  orderItems = new Collection<OrderItem>(this);
}

@Entity()
export default class OrderItem {
  @PrimaryKey()
  id!: number;

  @ManyToOne({
    entity: () => Order,
    strategy: LoadStrategy.JOINED,
    eager: true
  })
  order!: Order;
}
```

Finally, run a query to pull order items:
```typescript
orm.em.getRepository<OrderItem>('OrderItem').find({
  id: {
    $gt: 100
  }
})
```

The generated query is:
```sql
select "e0".* from "order_item" as "e0" where "e0"."id" > 100
```

**Expected behavior**
There should be a join in the query to populate the `Order` entity.

**Additional context**
Specifying populate directly in the query does produce the join:
```typescript
orm.em
  .getRepository<OrderItem>('OrderItem')
  .find({ id: { $gt: 100 } }, { populate: { order: LoadStrategy.JOINED } });
```

```sql
select "e0"."id", "e0"."order_id", "o1"."id" as "o1__id" from "order_item" as "e0" left join "order" as "o1" on "e0"."order_id" = "o1"."id" where "e0"."id" > 100
```

**Versions**

| Dependency | Version |
| - | - |
| node | 14.15.4 |
| typescript | 4.1.5 |
| mikro-orm | 4.5.0 |
| your-driver | postgresql - 4.5.0 |

**Comment by B4nan** [comment]
I think this is more about combining `strategy` with `eager: true` (eager loading is implemented as automatically filling the `populate` for you).

**Comment by evantrimboli** [comment]
Just FYI, I tried it with only `eager: true` and omitted the load strategy and I had the same result, no join.

```typescript
@ManyToOne({
    entity: () => Order,
    eager: true
  })
```
