### ISSUE TITLE
Support index hints with the QueryBuilder

### ISSUE THREAD

**Issue by merceyz** [mikro-orm/mikro-orm#1663]
**Is your feature request related to a problem? Please describe.**

The MySQL query optimizer needs a little help choosing the right index every now and then and the query builder doesn't support this so I need to use knex and map the result to entities.

**Describe the solution you'd like**

A way to provide index hints using the query builder directly.

**Describe alternatives you've considered**

Using `getKnex` (or raw queries) and mapping the result to entities.

**Additional context**

https://dev.mysql.com/doc/refman/8.0/en/index-hints.html
https://stackoverflow.com/a/63603866

**Comment by B4nan** [comment]
Would a `qb.from()` method be good for this, or can you propose some API?

**Comment by merceyz** [comment]
Would a dedicated function make more sense or would that be too MySQL specific? (`qb.index`)

```ts
type IndexHint = {
	type: 'use' | 'force' | 'ignore';
	indexName: string | string[];
	forType?: 'JOIN' | 'ORDER BY' | 'GROUP BY' | Array<'JOIN' | 'ORDER BY' | 'GROUP BY'>;
};

declare function index(hint: IndexHint): void;

declare function index(
	type: IndexHint['type'],
	indexName: IndexHint['indexName'],
	forType?: IndexHint['forType']
): void;

```

**Comment by B4nan** [comment]
Well, if this would work only for mysql, then I would rather not have such a common API directly on QB. Apparently sqlite has something similar but with different syntax and postgres does not support it at all.

**Comment by merceyz** [comment]
That would work
