### ISSUE TITLE
Group by selected aliased expression

### ISSUE THREAD

**Issue by l00k** [mikro-orm/mikro-orm#1668]
**Describe the bug**
When I try to set grouping to one of aliased expression from select clause it's wrongly prefixing that field.

**To Reproduce**
```
entityManager.createQueryBuilder(Transaction, 'm')
    .select([
        'FLOOR(UNIX_TIMESTAMP(m.date) / 3600) as `chunkId`',
        'SUM(m.value) AS `totalValue`'
    ])
    .groupBy('chunkId')
    .getResultList();
```

**Expected behavior**
Should group by aliased dynamic expression from SELECT clause.

**What happens**
```
Unknown column 'm.`chunkId`' in 'group statement'
```
Aliased column is prefixed with main table prefix.

**Versions**

| Dependency | Version |
| - | - |
| node | 12.19 |
| typescript | 4.1.5 |
| @mikro-orm/mysql | 4.4.3 |

**Comment by B4nan** [comment]
You need to define it as virtual property otherwise it will get aliased.

**Comment by l00k** [comment]
Thx a lot for relatively fast response and for maintaining such wonderful lib. I really appreciate this.
Yeap you are right it should be `execute` (rush).
This query aggregates transaction values in some time frames.
But to be honest I don't like idea to include virtual property for single case.
I found solution - I set `groupBy` and `orderBy` via knex query builder created from prepared mikro orm qb.
In this particular case I think it seems reasonable.
In general I understand idea of using virtual properties and I think it is ok.
I just thought maybe there is some option to disable prefixing.

**Comment by B4nan** [comment]
Not tested, but you might try using `qb.raw()`, it might work too:

```ts
const qb = em.createQueryBuilder(Transaction, 'm');
qb.select([
    'FLOOR(UNIX_TIMESTAMP(m.date) / 3600) as `chunkId`',
    'SUM(m.value) AS `totalValue`'
  ])
  .groupBy(qb.raw('chunkId'))
  .getResultList();
```

**Comment by l00k** [comment]
If `groupBy()` / `orderBy()` would accept `Raw` it could work :) maybe it is good direction.
So far it only accepts `string`.

**Comment by B4nan** [comment]
Have you tried to type cast it? I'd say it should work fine, sounds like a typings issue only.

**Comment by l00k** [comment]
you are right :) I didn't checked. `any` cast worked fine.

**Comment by B4nan** [comment]
It is a map, there is just one parameter. `qb.orderBy({ [qb.raw('chunkId') as any]: QueryOrder.ASC })`

**Comment by l00k** [comment]
Yeap I know current implementation ;) unfortunately in this case using `qb.raw` as map key produce error
```Trying to query by not existing property Transaction.chunkStamp```

**Comment by l00k** [comment]
After analyzing code I have found interesting fragment:
`packages/knex/src/query/CriteriaNodeFactory.ts:11`

This works well:
```
(...)
    .groupBy('(chunkStamp)')
    .orderBy({ '(chunkStamp)': ORM.QueryOrder.ASC })
```

Thx for you time and have a cup of coffee so you can maintaining library more enjoyable :D

**Comment by B4nan** [comment]
Not sure what and when changed, but it looks like it works fine nowadays, as long as you have the virtual property defined and you use its field name in your SQL fragment - this last part is important, if your virtual property was called `chunkStamp` you need to select `chunk_stamp` or override the virtual property fieldname - there is no processing of SQL framents, so there is no way to know that you aliased something to `chunkStamp`. 

Here is an example I used for testing:

```ts
const qb = orm.em.createQueryBuilder(Author2, 'a');
qb.select([
  'floor(`a`.`age`) as `books_total`', // note i use `books_total` here
])
.groupBy('booksTotal') // but `booksTotal` here
.orderBy({ booksTotal: QueryOrder.ASC }); // and here

expect(qb.getQuery()).toEqual('select floor(`a`.`age`) as `books_total` from `author2` as `a` group by `books_total` order by `books_total` asc');
```

Alternatively if I defiend the virtual prop with an explicit fieldname:

```ts
@Property({ fieldName: 'booksTotal', persist: false })
booksTotal!: number;
```

It will work this way:

```ts
const qb = orm.em.createQueryBuilder(Author2, 'a');
qb.select([
  'floor(`a`.`age`) as `booksTotal`',
])
.groupBy('booksTotal')
.orderBy({ booksTotal: QueryOrder.ASC });

expect(qb.getQuery()).toEqual('select floor(`a`.`age`) as `booksTotal` from `author2` as `a` group by `booksTotal` order by `booksTotal` asc');
```

Will close with a passing test case so we dont break it over time.
