### ISSUE TITLE
Nested LoadStrategy in object form causes compile error.

### ISSUE THREAD

**Issue by evantrimboli** [mikro-orm/mikro-orm#1674]
**Describe the bug**
I may be doing something wrong here, I'm trying to add a nested inner join to load several entities, based off the documentation here:

```typescript
const author = await orm.em.findOne(Author, 1, { populate: {
  books: [LoadStrategy.JOINED, { publisher: LoadStrategy.JOINED }]
} });
```

Following a similar approach, it gives me a compile error.

**Stack trace**
N/A

**To Reproduce**
Consider the following models/code:

```typescript
@Entity()
export default class User {
  @PrimaryKey()
  id!: number;
}

@Entity()
export default class Order {
  @PrimaryKey()
  id!: number;

  @ManyToOne(() => User)
  user!: User;
}

@Entity()
export default class OrderItem {
  @PrimaryKey()
  id!: number;

  @ManyToOne(() => Order)
  order!: Order;
}
```

Finally, compare the following queries:

```typescript
// Runs fine with a join.
const ok = await orm.em.getRepository<OrderItem>(OrderItem).findOne({ id: 1 }, {
  populate: {
    order: LoadStrategy.JOINED
  }
});

// Compile error around the tuple declaring the order.
const bad = await orm.em.getRepository<OrderItem>(OrderItem).findOne({ id: 1 }, {
  populate: {
    order: [LoadStrategy.JOINED, {
      user: LoadStrategy.JOINED
    }]
   }
});
```

**Expected behavior**
The code should compile and provide multiple joins.

**Additional context**
I had a look at the type of `Populate<T>`, it doesn't seem as though there is any support for specify a tuple of `LoadStrategy` and `PopulateMap<Child>`, not sure if it's a doc issue or otherwise. Happy to do more investigation, or maybe I'm misunderstanding the use case here. I am able to achieve the behaviour I'm looking for by specifying the `strategy` on the `ManyToOne` relations and using:

```typescript
await orm.em.getRepository<OrderItem>(OrderItem).findOne({  id: 1 }, { populate: { order: { user: true } } });
```

Also, when specifying `populate: LoadStrategy.JOINED` on the root, it throws a RTE:

```typescript
const bad = await orm.em.getRepository<OrderItem>(OrderItem).findOne({ id: 1 }, { populate: LoadStrategy.JOINED });
```

```
(node:29792) UnhandledPromiseRejectionWarning: TypeError: populate.some is not a function
    at EntityLoader.normalizePopulate (D:\git\mikro-test\node_modules\@mikro-orm\core\entity\EntityLoader.js:41:43)
    at SqlEntityManager.preparePopulate (D:\git\mikro-test\node_modules\@mikro-orm\core\EntityManager.js:638:39)
    at SqlEntityManager.findOne (D:\git\mikro-test\node_modules\@mikro-orm\core\EntityManager.js:222:33)
```

**Versions**

| Dependency | Version |
| - | - |
| node | 14.15.4 |
| typescript | 4.1.5 |
| mikro-orm | 4.5.3 |
| your-driver | postgresql - 4.5.3 |

**Comment by B4nan** [comment]
I think the array form you are using was removed before the 4.0 release to simplify typings (as it was quite performance heavy, and still is).

You can now set the strategy via `FindOptions`, in the end I believe it should be enough as usually people want one or the other, instead of combination.

```ts
const author = await orm.em.findOne(Author, 1, { 
  populate: { books: { publisher: true } },
  strategy: LoadStrategy.JOINED,
});
```

**Comment by evantrimboli** [comment]
Ok that all makes sense. Thanks for your response.
