### ISSUE TITLE
Mikro ORM produces additional Select when joining Many to Many

### ISSUE THREAD

**Issue by HunterJS-bit** [mikro-orm/mikro-orm#1682]
**Describe the bug**
When querying many to many relations the Mikro ORM produces Additional select queries

**To Reproduce**

```
const authors = await orm.em.find(Author,   { books: { name: { '$ilike': '%a%' } } }
, { populate: ['books', 'books.tags' ] });
```

This produces following query simmilar to this:

`select "e0".* from "authors" as "e0" left join "books" as "e1" on "e0"."id" = "e1"."authorId" left join "tags" as "e2" on "e1"."tagId" = "e2"."id" where "e2"."name" ilike '%a%' order by "e0"."id" asc limit 29 `

But then bellow I get an additional **Select** statement:

` select "e0".* from "books" as "e0" where  "e0"."name" ilike '%a% order by "e0"."id" asc;`

Why I'm I getting that additional selection, it filters my Join instead of returning only the above statement, since I would like to query by Author ?

**Versions**

| Dependency | Version |
| node | 14 |
| mikro-orm | 4.5.2 |

**Comment by B4nan** [comment]
Each relation uses one query, that is how it is designed. It is not an "additional query", it is query to load books, the first one loads just authors. Check the select clauses.

https://mikro-orm.io/docs/nested-populate/

You can try joined loading strategy, that was added in v4.

https://mikro-orm.io/docs/loading-strategies/

The docs here are a bit dated, nowadays there is also `FindOptions.strategy` you can use to control this granularly.

**Comment by HunterJS-bit** [comment]
@B4nan  

Thank you for answering, I have read the docs I tried setting strategy to `LoadStrategy.JOINED` but nothing is happening, is there any way how could I bypass it or would I have to use queryBuilder ?

**Comment by B4nan** [comment]
Will be happy to look into it, if you provide something executable. Hard to tell what you got wrong without seeing actual code.

**Comment by B4nan** [comment]
Btw looking more at that query, it feels like you have something wrong in the entity definition. As the `find` call you have here would not even join the tags table, as you are trying to filter just by book name. This points to wrong relation definition of `Author.books` probably.

So start with giving me the entity definitions here, it might be enough.

**Comment by HunterJS-bit** [comment]
@B4nan 

Thank you again for replying 

**Author model**
```

import {
    BeforeUpdate,
    Cascade,
    Collection,
    Entity,
    Enum,
    Filter,
    ManyToOne,
    OneToMany,
    PrimaryKey,
    Property,
    QueryOrder,
} from '@mikro-orm/core';
import { AuthorBooks } from './author-books.entity';

@Entity({ tableName: 'authors', customRepository: () => AuthorRepository })
export class Author {

    @PrimaryKey()
    id!: number;

    @Property()
    title!: string;

    @Property()
    description!: string;

        @OneToMany({
        entity: () => AuthorBooks,
        mappedBy: (entity) => entity.book,
        orphanRemoval: true,
        cascade: [Cascade.ALL],
    })
    books = new Collection<AuthorBooks>(this);

}

```

**Author Books model**

```
import { Entity, ManyToOne, PrimaryKey } from '@mikro-orm/core';
import { Author } from './author.entity';
import { Book } from './book.entity';
import { AuthorBooksRepository } from '../modules/authors/author-books.repository';

@Entity({ tableName: 'author_books', customRepository: () => AuthorBooksRepository })
export class AuthorBooks {
    @PrimaryKey()
    id!: number;

    @ManyToOne(() => Ticket, { name: 'authorId' })
    author!: Author;

    @ManyToOne(() => Book, { name: 'bookId' })
    book!: Book;
}

```

**Books model**

```
import {
    Entity,
    PrimaryKey,
    Property,
    Index,
    ManyToOne,
    OneToMany,
    Collection,
    Cascade,
    BeforeUpdate,
    Filter,
    JsonType,
    EntityRepositoryType,
} from '@mikro-orm/core';
import { Author } from './author.entity';
import { BookRepository } from '../modules/book/book.repository';
import { AuthorBooks } from './author-books.entity';

@Entity({ tableName: 'books', customRepository: () => BookRepository })
export class Book {

    @PrimaryKey()
    id: number;

    @Property()
    name: string;

    @OneToMany({
        entity: () => AuthorBooks,
        mappedBy: (entity) => entity.author,
        orphanRemoval: true,
        cascade: [Cascade.ALL],
    })
    authors = new Collection<AuthorBooks>(this);
}
```


Query: 

```
const authors = await orm.em.find(Author,   { books: { name: { '$ilike': '%a%' } } }
, { populate: ['books', 'books.authors' ] });
```

And I would like this to produce the following query:

`select "e0".* from "authors" as "e0" left join "books" as "e1" on "e0"."id" = "e1"."authorId" left join "authors" as "e2" on "e1"."authorId" = "e2"."id" where "e1"."name" ilike '%a%' order by "e0"."id" asc limit 29`


Without additional query on books:

`select "e0".* from "books" as "e0" where "e0"."name" ilike '%a% order by "e0"."id" asc;`

**Comment by B4nan** [comment]
This looks clearly wrong:

```
    @ManyToOne(() => Ticket, { name: 'authorId' })
    author!: Author;
```

**Comment by HunterJS-bit** [comment]
@B4nan  Yes I mad a mistake while copying since I could not show you my real models :+1:

**Comment by B4nan** [comment]
Your query is also wrong, the `Author.books` is a collection of `AuthorBooks` entities, and those do not have a `name` property. 

Try to create executable repro (a [test case ideally](https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues)), as here I feel like you are oversimplifying, and without seeing the actual code that fails I don't really see a way to help.
