### ISSUE TITLE
Return type of EntityRepository.persist()

### ISSUE THREAD

**Issue by cbadger85** [mikro-orm/mikro-orm#1698]
**Describe the bug**

The documentation specifies that the return type of [EntityRepository.persist()](https://mikro-orm.io/docs/repositories-api#persistandflushentity-anyentity--anyentity-promisevoid) is `Promise<void>`, however, the type is on [EntityManager](https://github.com/mikro-orm/mikro-orm/blob/aa71065d0727920db7da9bfdecdb33e6b8165cb5/packages/core/src/EntityManager.ts#L617) that EntityRepository inherits from is `void`.

**Expected behavior**

persist should return a promise or the documentation should be updated.

**Additional context**

I believe the documentation is out of date, since `flush` is what marks the end of the transaction. If that's the case, I can put in a PR to update the documentation. 

**Versions**

| Dependency | Version |
| - | - |
| node | 12.18.2 |
| typescript | 4.2.4 |
| mikro-orm | 4.5.3 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
That whole page should go, API docs are now generated from code and elsewhere (link in the header).
