### ISSUE TITLE
Nested Embedables Array 

### ISSUE THREAD

**Issue by kodeine** [mikro-orm/mikro-orm#1699]
**Describe the bug**

`model`
```
  @Embedded({ entity: () => TargetExpression, nullable: true, array: true  })
  expression?: TargetExpression[] = [];
```

`DTO`
```
UpdateTargetInput {
  state: 'enabled',
  expression: [
    ProductTargetExpressionInput {
      type: 'someType',
      value: 'asdasdasd'
    }
  ],
  expressionType: 'manual'
}
```

Works fine and stores as array in mongodb.
```
const item = repository.create(dto);
wrap(item).assign(dto, { mergeObjects: true });
```

```
const item = await repository.findOneOrFail(where);
wrap(item).assign(dto, { mergeObjects: true, updateNestedEntities: true });
```
converts the dto to so it doesnt store in database.
```
expression: ProductTargetExpression {
    '0': ProductTargetExpressionInput {
      type: 'asinSameAs',
      value: 'asdasdasd'
    }
  }
```

**Versions**

| Dependency | Version |
| - | - |
| node | ? |
| typescript | ? |
| mikro-orm | ? |
| your-driver | mongodb |

**Comment by B4nan** [comment]
Provide actual repro, this is not enough. Where are the entity and embeddables definitions? What version are you on? Dont ignore the issue template. Reproduction needs to be complete and verifiable. I need to see the actual data, you did not even gave me valid code for that.

**Comment by B4nan** [comment]
`4.5.4-dev.13`
