### ISSUE TITLE
Check Constraints

### ISSUE THREAD

**Issue by evantrimboli** [mikro-orm/mikro-orm#1711]
**Is your feature request related to a problem? Please describe.**
To keep data layer logic centralized, it would be nice to be able to specify check constraints on fields.

**Describe the solution you'd like**
```typescript
@Entity()
class Product {
  @Property({
    check: (productMeta) => `${productMeta.price.dbName} >= 0`,
  })
  price!: number
}
```

The sql generated should be something like:

```sql
CREATE TABLE products (
    price numeric CHECK (price >= 0)
);
```

The `productMeta` would be some sort of construct to access the underlying column names to be able to construct the constraint according to the naming strategy. There are a few ways this could go down, not sure what would be most idiomatic.

**Describe alternatives you've considered**
- They could be manually added to migrations
- Handle these at the API layer

**Additional context**
N/A

**Comment by DASPRiD** [comment]
Check constraints can also be added to a table directly. This is actually how TypeORM did implement them. The resulting SQL from that usually looks something like this:

```sql
CREATE TABLE foo (
  price numeric NOT NULL,
  CONSTRAINT foo_bar CHECK (price >= 0)
)
```

This should be fairly easy to implement as a `@Check` annotation to the `@Entity`. We could basically allow the developer to write any SQL check expression, and then diff on the expression for migrations. This would also be the most flexible approach. For instance:

```typescript
@Entity()
@Check('price >= 0')
class Foo {
  @Property()
  price : number;
}
```
