### ISSUE TITLE
All work ok but `npx mikro-orm debug` show `mysql2 not-found`

### ISSUE THREAD

**Issue by xeladejo** [mikro-orm/mikro-orm#1715]
**Describe the bug**

All work ok but `npx mikro-orm debug` show `mysql2 not-found`. 

**To Reproduce**

npx mikro-orm debug
```
Current MikroORM CLI configuration
 - dependencies:
   - mikro-orm 4.5.3
   - node 14.16.0
   - knex 0.21.19
   - mysql2 not-found
   - typescript 4.2.3
 - package.json found
 - searched config paths:
   - /home/alejandro/Proyectos/tattoo/server/mikro-orm.config.js (found)
 - configuration found
 - will use `entities` array (contains 0 references and 1 paths)
   - /home/alejandro/Proyectos/tattoo/server/dist/entities/*.js (found)
 - could use `entitiesTs` array (contains 0 references and 1 paths)
   - /home/alejandro/Proyectos/tattoo/server/src/entities/*.ts (found)
```

**Expected behavior**

Show `mysql2 found`.

**Additional context**

mikro-orm.config.js
```javascript
require('dotenv').config({ path: '.env.development' });

module.exports = {
  type: 'mysql',
  host: process.env.DATABASE_HOST,
  port: Number(process.env.DATABASE_PORT),
  user: process.env.DATABASE_USER,
  password: process.env.DATABASE_PASSWORD,
  dbName: process.env.DATABASE_NAME,
  entities: ['dist/entities/*.js'],
  entitiesTs: ['src/entities/*.ts'],
  autoJoinOneToOneOwner: false,
  forceUtcTimezone: true,
  multipleStatements: true,
};
```

npm ls mysql2
```
@tattoo/server@0.0.1 /home/alejandro/Proyectos/tattoo/server
├─┬ @mikro-orm/cli@4.5.3
│ └─┬ @mikro-orm/knex@4.5.3
│   ├─┬ knex@0.21.19
│   │ └── mysql2@2.2.5 deduped
│   └── mysql2@2.2.5 deduped
└─┬ @mikro-orm/mysql@4.5.3
  ├─┬ @mikro-orm/mysql-base@4.5.3
  │ └── mysql2@2.2.5 deduped
  └── mysql2@2.2.5
```

package.json
```json
{
  "dependencies": {
    "@mikro-orm/core": "^4.5.3",
    "@mikro-orm/mysql": "^4.5.3",
  },
  "devDependencies": {
    "@mikro-orm/cli": "^4.5.3",
  }
}
```

**Versions**

| Dependency | Version |
| - | - |
| node | 14.16.0 |
| typescript | 4.2.3 |
| mikro-orm | 4.5.3 |
| your-driver | mysql |

**Comment by B4nan** [comment]
Any idea why this happens @merceyz? I'd expect some peer deps issue again. It happens via `const pkg = Utils.requireFrom(`${name}/package.json`, process.cwd());`, if I change the path to absolute (with `node_modules` explicitly there) it works fine with `require()`, but not with the `Utils.requireFrom()`. I guess we could have a fallback with the absolute path. 

On the other hand this is not really important, as the driver dependencies are pinned, so knowning what is the ORM driver package version would be more worthy. I might rather print all found ORM packages in the root and their versions, as that will also help with debugging misaligned package versions or nested installations.

**Comment by B4nan** [comment]
Closing as this is a won't fix, mysql2 library does not allow importing `package.json`, it is not part of the package exports. As mentioned above, this does not add much value nowadays, and will be probably changed to not list the dependency versions anyway.
