### ISSUE TITLE
Smart joins don't work with $or and $and

### ISSUE THREAD

**Issue by vimmerru** [mikro-orm/mikro-orm#172]
**Describe the bug**

If i use query

```
em.find(Entity, { product: {id: 1}, organization: {id: 1} });
```

it produces correct sql with joins. Similar query with $or or $and

```
em.find(Entity, { $or: [{product: { id: 1} }, { organization: { id: 1} }] });
```

produces incorrect sql without joins and any conditions.

**Expected behavior**
Correct sql or at least an error that such query is unsupported.

**Versions**

Latest @next

**Comment by B4nan** [comment]
I knew this won't work out of box :D 

Btw you don't have to wrap those `id` fields in object, you can pass the value directly:

    em.find(Entity, { product: 1, organization: 1 });

Wrapping it in the object will join the entity even if not needed (e.g. you already have the FK joined).

**Comment by vimmerru** [comment]
In general i don't need id, sorry. Let assume other fields:

```
em.find(Entity, { $or: [{product: { code: 'code'} }, { organization: { domain: 'domain'} }] });
```

**Comment by vimmerru** [comment]
So we have

```
class SomeEntity {

  @ManyToOne()
  Product product;

  @ManyToOne()
  Organization organization;
}
```

**Comment by B4nan** [comment]
Yeah I understand the problem, it was just a hint for other usecases.

**Comment by vimmerru** [comment]
BTW i really like this feature it allowed to significantly reduce boilerplate. Thanks!

**Comment by B4nan** [comment]
Turns out it is pretty complex thing to support also operators, but I think I finally cracked it. Will need to add more tests and clean up the code but this is passing for me already:

```typescript
const qb1 = orm.em.createQueryBuilder(Book2);
qb1.select('*').where({ $or: [{ author: { name: 'Jon Snow 1', termsAccepted: true } }, { author: { name: 'Jon Snow 2' } }] });
expect(qb1.getQuery()).toEqual('select `e0`.* ' +
  'from `book2` as `e0` ' +
  'left join `author2` as `e1` on `e0`.`author_id` = `e1`.`id` ' +
  'where ((`e1`.`name` = ? and `e1`.`terms_accepted` = ?) or `e1`.`name` = ?)');
expect(qb1.getParams()).toEqual(['Jon Snow 1', true, 'Jon Snow 2']);

const qb2 = orm.em.createQueryBuilder(Book2);
qb2.select('*').where({ $or: [{ author: { $or: [{ name: 'Jon Snow 1' }, { email: /^snow@.*/ }] } }, { publisher: { name: 'My Publisher' } }] });
expect(qb2.getQuery()).toEqual('select `e0`.* from `book2` as `e0` ' +
  'left join `author2` as `e1` on `e0`.`author_id` = `e1`.`id` ' +
  'left join `publisher2` as `e2` on `e0`.`publisher_id` = `e2`.`id` ' +
  'where ((`e1`.`name` = ? or `e1`.`email` like ?) or `e2`.`name` = ?)');
expect(qb2.getParams()).toEqual(['Jon Snow 1', 'snow@%%', 'My Publisher']);
```

Published that as `3.0.0-alpha.17` so you can try yourself. Feel free to report use cases that are still not working, will be happy to add them to tests.

**Comment by B4nan** [comment]
Again, it is more complicated than I was hoping. Latest alpha (`3.0.0-alpha.18`) is reverted back to the original state where no operators are supported. I might have to rework the whole criteria processing as now its too complex and I am really loosing my mind when refactoring that part :/ I am thinking about composite pattern.

**Comment by B4nan** [comment]
Should be fixed in `3.0.0-alpha.20`. Composite pattern was the right way, although this was one of the biggest challenges during ORM's development. There might be still some edge cases not covered, will add more tests before publishing the code. 

I also added validation, now when you try to query by non existing property it should throw, and also the case where no where clause was appended should also throw.

**Comment by vimmerru** [comment]
@B4nan Thanks! What is right way to look into code changes? Do you use PRs for internal pushes?

**Comment by B4nan** [comment]
Depends on how big is the feature/refactoring, and also if I am confident I am done with that :] I will send a PR right ahead so you can take a look.

**Comment by B4nan** [comment]
here you go: https://github.com/mikro-orm/mikro-orm/pull/185

**Comment by B4nan** [comment]
I guess it's working ok now, fixed last issues with 1:1 and self-referencing in `3.0.0-alpha.22`. If you find something not covered, please open new issue.

**Comment by vimmerru** [comment]
@B4nan I have a problem in latest version that population is broken if used together with complex query. Could you re-check this? I will provide an example ASAP.

**Comment by B4nan** [comment]
Sure, just show me how to break it :)

**Comment by B4nan** [comment]
Any updates with your issue @vimmerru?

**Comment by vimmerru** [comment]
@B4nan 

I have entities Report and Organization. Report belongs to some Organization. Organization has field domain that isn't OK. I need to filter Reports by organization domain:

```
const [reports, total] = await this.em.findAndCount(
      Report,
      {
        researcher,
        organization: { domain:  'some-domain'},
      },
      {
        populate: ['organization', 'product'],
        orderBy: orderByMapper[sorting.sortBy],
        ...pagination,
      },
    );
```

if i run it without ```populate``` parameter it generates correct query, but if i populate organization i see the following:

```
err: {
      "type": "Error",
      "message": "select `e0`.*, `e1`.`id`, `e1`.`undefined` from `report` as `e0` left join `organization` as `e1` on `e0`.`organization_id` = `e1`.`id` where `e0`.`researcher_id` = 3 and `e1`.`domain` = 'mydomain' order by `e0`.`code` desc limit 10 - Unknown column 'e1.undefined' in 'field list'",
      "stack":
          Error: Unknown column 'e1.undefined' in 'field list'
              at Packet.asError (/home/alexandermartynov/projects/ioxt/haxlab-be/node_modules/mysql2/lib/packets/packet.js:708:17)
              at Query.execute (/home/alexandermartynov/projects/ioxt/haxlab-be/node_modules/mysql2/lib/commands/command.js:28:26)
              at Connection.handlePacket (/home/alexandermartynov/projects/ioxt/haxlab-be/node_modules/mysql2/lib/connection.js:408:32)
              at PacketParser.Connection.packetParser.p [as onPacket] (/home/alexandermartynov/projects/ioxt/haxlab-be/node_modules/mysql2/lib/connection.js:70:12)
              at PacketParser.executeStart (/home/alexandermartynov/projects/ioxt/haxlab-be/node_modules/mysql2/lib/packet_parser.js:75:16)
              at Socket.Connection.stream.on.data (/home/alexandermartynov/projects/ioxt/haxlab-be/node_modules/mysql2/lib/connection.js:77:25)
              at Socket.emit (events.js:198:13)
              at Socket.EventEmitter.emit (domain.js:448:20)
              at addChunk (_stream_readable.js:288:12)
              at readableAddChunk (_stream_readable.js:269:11)
              at Socket.Readable.push (_stream_readable.js:224:10)
              at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
      "code": "ER_BAD_FIELD_ERROR",
      "errno": 1054,
      "sqlState": "42S22",
      "sqlMessage": "Unknown column 'e1.undefined' in 'field list'"
    }
```

As a workaround i have to run population later now. As i understand the problem is reproduced when:

- I use join with additional condition
- I use population by the same relation

**Comment by vimmerru** [comment]
I believe it is better to create separate issue.

**Comment by B4nan** [comment]
> I believe it is better to create separate issue.

Yeah please do so, also put there both entity definitions, and please test it with latest alpha version. I was making some fixes there recently, so it even might be fixed already.
