### ISSUE TITLE
MongDB insert many duplicate key ignore

### ISSUE THREAD

**Issue by vulongc3** [mikro-orm/mikro-orm#1720]
**Is your feature request related to a problem? Please describe.**
I can't find a way to ignore duplicate key error while insert many. I don't want to check is document exist one by one.

**Describe the solution you'd like**
I need some thing like `Database.entityManager.flush({ ignoreDuplicateKeyOnInsert: true })`

**Additional context**
I crawl thousands of documents for my collection on the internet and there is some chance that some documents I've just crawled are already exist.

**My current source code**
```
static async updateData(addressId: string) {
  try {
    const trans = await EthplorerClient
      .instance.getAddressTransactions(addressId)
      
    for (let i = 0, l = trans.length; i < l; i ++) {
      Database.manager.persist(
        Database.manager.create(Transaction, trans[i])
      )

      if (i % 100 === 0) {
        await Database.manager.flush()
        Database.manager.clear()
      }
    }

    await Database.manager.flush()
    Database.manager.clear()
  } catch (e) {
    console.error(e)
  }
}
```

**Comment by vulongc3** [comment]
And one more thing, the `find` and `findOne` return nothing (`[]` and `null`) while mongodb native query with the same filter return value.
**MikroORM:**
```
const filter = {
  $or: [
     { to: '0x8101ac3f0748918152778cbcc059384e89dad732' },
     { from: '0x8101ac3f0748918152778cbcc059384e89dad732' }
  ]
}

await Database.manager.find(Transaction, filter)
```
**Native query**
```
> db.transaction.find({ $or: [{ to: '0x8101ac3f0748918152778cbcc059384e89dad732' }, { from: '0x8101ac3f0748918152778cbcc059384e89dad732' }] })
```

**Comment by B4nan** [comment]
How do you expect this to work? Adding a bool flag ti handle it in db level is one thing, but what about consistency of the entities in memory? Anyway, no plans to add any flags on flush, that seems very wrong to me, but we might find a better way to handle this. 

I dont really see how we could add such thing on EM level. Also I dont fully understand what your problem is, you have some unique property on the entity that is causing the failure or what? 

Please try to be more specific if you want to propose something. Also if you want to file a bug report, create new issue with reproduction, including full entity definition and some data, ideally as a testcase, this is not enough and will be ignored if you dont provide more.

**Comment by vulongc3** [comment]
My issue is I can't insert many with ignore duplicate key error and continue insert feature. Like:
`db.collection.insertMany(documents, { ordered: false}) // ignore duplicate key error and continue insert`

**Comment by B4nan** [comment]
Sounds like you might be better off with using the driver directly (`em.getDriver().nativeInsertMany()`), where we could add a flag for [unordered batch inserts](https://stackoverflow.com/questions/34153058/mongodb-multi-document-insert-ignore-custom-duplicate-field-error), as those should ignore duplicate errors and continue with inserting. But it does not feel like something we should have on EM level.

> My issue is I can't insert many with ignore duplicate key error and continue insert feature. 

Again, without understanding your problem better, hard to suggest something. I asked for more details and you said what I already knex... ;] 

Do you really need to work with the entities after you persist them, or is using the driver API enough?

Btw you can also do literally any query, `em.getCollection('EntityName')` will give you the native collection instance.

**Comment by B4nan** [comment]
Closing as we nowadays have `em.upsert()` for this.
