### ISSUE TITLE
Populate with fields in find() is not working in ManyToOne relationship

### ISSUE THREAD

**Issue by michael-vascue** [mikro-orm/mikro-orm#1739]
**Describe the bug**
Populate with fields in find() is not working in ManyToOne relationship

**Stack trace**
N/A

**To Reproduce**

User Entity:
```
@Entity()
export class User {
    @PrimaryKey()
    id!: number;
    
    @Property({ length: 200 })
    name!: string;

    @ManyToOne(() => Company)
    company: Company;
} 
```

Company Entity:
```
@Entity()
export class Company {
    @PrimaryKey()
    id!: number;

    @Property({ length: 200 })
    name!: string;

    @OneToMany(() => User, (u) => u.company)
    users = new Collection<User>(this);
}
```

Without fields, populate is working as expected, company can be joined:
```
await this.userRepository.find({}, {
      populate: ['company'],
      strategy: LoadStrategy.JOINED,
});
/* SQL Output:
select `e0`.`id`, `e0`.`name`, `c1`.`id` as `c1__id`, `c1`.`name` as `c1__name`
from `user` as `e0` 
left join `company` as `c1` on `e0`.`company_id` = `c1`.`id`
*/
```

With fields, company is ignored:
```
await this.userRepository.find({}, {
      fields: [ 'id', 'company.id', 'company.name' ],
      populate: ['company'],
      strategy: LoadStrategy.JOINED,
});
/* SQL Output:
select `e0`.`id` from `user` as `e0` 
*/
```

**Expected behavior**
Expected to ManyToOne relationship can work with populate + fields combination in find()

**Additional context**
N/A

**Versions**

| Dependency | Version |
| - | - |
|node | 14.15.0|
|typescript | 4.2.4|
|mikro-orm | 4.5.4|
|@mikro-orm/mysql | 4.5.4|
|@mikro-orm/nestjs | 4.2.0|

**Comment by B4nan** [comment]
Why are you opening the very same issue as you already did (#1707)? This is implemented in v5 (2bebb5e), no plans to backport it to v4 as it is a bit breaking.

**Comment by michael-vascue** [comment]
Because it is working on M2M situation, I thought it is a different issue.

**Comment by B4nan** [comment]
Well I explicitly said that the combination of `fields` (partial loading) and joined strategy is not implemented at all. And closed your issue with a commit that implements it and includes [a test for nested m:n, 1:m and m:1](https://github.com/mikro-orm/mikro-orm/commit/2bebb5e75595ae3369887ee8bed7be48efc45173#diff-431a5cc12e41353fa46644dc3b8b3dad46ea2ff1a5cb2383882892e15f43f28eR203).

You can already try v5 via dev releases, but keep in mind there will be more breaking changes (currently there are just few minor ones, but planning to remove some signatures from EM, as described in #1623).

**Comment by michael-vascue** [comment]
Okay. Thanks a lot. Because in M:1 situation, the joining side SQL is missing rather than in a separate SQL so it makes no connection to me of the same root cause.
I will read the changes you made and try v5 in advance

**Comment by B4nan** [comment]
> Because in M:1 situation, the joining side SQL is missing rather than in a separate SQL

Well it works as it should (`fields` have precedense here, `strategy` is ignored), you have no condition for user entity (the `where` parameter is `{}`), so the first query loads all users, as you requested. Second query (if the first finds something) would load the companies, based on their PKs used in the just loaded users.

**Comment by michael-vascue** [comment]
> Second query (if the first finds something) would load the companies, based on their PKs used in the just loaded users.

I don't quite understand this sentence. 
The 1st case without fields works perfectly.
But for the 2nd case, if fields is provided, the company query is missing even have where conditions on company Id.

Anyway, I just tested v5 and it is working so it is the same issue. My bad for creating duplicate one.
But there is a strange behaviour in fields. Using string syntax, all fields will be retrieved.
I created a repo for you to have a look: https://github.com/michael-vascue/test-mikro
Sorry for not creating another issue because it may be my coding problem.

**Comment by B4nan** [comment]
> But for the 2nd case, if fields is provided, the company query is missing even have where conditions on company Id.

Read the link I provided about population, I am refering to `select in` strategy that is the default (and to second SQL query it would produce, not your second example). For your example will use up to 2 queries, one to load users, one to load companies that belong to those users. The second query will be issued _only_ if the first one returned something, as its where condition depends on the results of first query. And again, in v4 the combination is simply not implemented and partial loading has precedence - your `strategy` option is therefore ignored. 

Will take a look if we can fix the dot notation in v5, should be easy I guess.

Worth noting that you should not overuse this feature, partial loading should be done ideally only for entities you just read, not if you want to write/change something. If you have fields you need only in rare cases, it's better to use lazy properties and populate them when needed.

**Comment by michael-vascue** [comment]
Okay. Thanks for your explanation.

> Worth noting that you should not overuse this feature, partial loading should be done ideally only for entities you just read, not if you want to write/change something. If you have fields you need only in rare cases, it's better to use lazy properties and populate them when needed.

I am implementing GraphQL so I would like to join/retrieve corresponding tables/fields if needed in _read_ situation.
I have lazy properties on "infrequent use" properties.

**Comment by B4nan** [comment]
Will be addressed in v5.
