### ISSUE TITLE
ValidationError: You cannot call em.flush() from inside lifecycle hook handlers

### ISSUE THREAD

**Issue by Dan6erbond** [mikro-orm/mikro-orm#1744]
**Describe the bug**

When trying to save entities in a MySQL database using the entity repository, multiple `ValidationError` are thrown where previously everything worked. As I am using the NestJS framework and the `@mikro-orm/nestjs` integration, #696 doesn't apply here, due to the fact that the integration sets up a request context on its own internally.

Additionally, #627 is using Fastify, which should have been resolved in v4 of MikroORM anyway. But regardless, I am using Express under the hood, and the latest version of MikroORM and its integration for NestJS.

**Stack trace**
```
ValidationError: You cannot call em.flush() from inside lifecycle hook handlers
at Function.cannotCommit (/usr/src/app/node_modules/@mikro-orm/core/errors.js:77:16)
at UnitOfWork.commit (/usr/src/app/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:167:44)
at SqlEntityManager.flush (/usr/src/app/node_modules/@mikro-orm/core/EntityManager.js:488:36)
at SqlEntityManager.persistAndFlush (/usr/src/app/node_modules/@mikro-orm/core/EntityManager.js:440:36)
at SqlEntityRepository.persistAndFlush (/usr/src/app/node_modules/@mikro-orm/core/entity/EntityRepository.js:21:23)
at TapSubscriber._tapNext (/usr/src/app/dist/crawler/crawler.service.js:162:48)
at TapSubscriber._next (/usr/src/app/node_modules/rxjs/internal/operators/tap.js:59:27)
at TapSubscriber.Subscriber.next (/usr/src/app/node_modules/rxjs/internal/Subscriber.js:66:18)
at TapSubscriber._next (/usr/src/app/node_modules/rxjs/internal/operators/tap.js:65:26)
at TapSubscriber.Subscriber.next (/usr/src/app/node_modules/rxjs/internal/Subscriber.js:66:18) {
entity: undefined
}
```

**To Reproduce**

Unfortunately, as this project I am working on is work-related, I cannot provide the repository, but I can attempt to explain the steps and show the code that isn't protected.

I am creating an `Observable` with RxJS in an unrelated function, which runs a long-running task. Then, from the function where this error actually occurs, I `subscribe()` to said observable after doing some DB work, and push the results from various `map()` and `tap()` operators to a `ReplaySubject`, as can be seen done here:

```ts
  crawlAndPersist(path: string) {
    const subject = new ReplaySubject<
      SiteSnapshotEntity | PageSnapshotEntity | ExternalLinkEntity
    >();

    this.sitesRepository
      .findOne({
        url: path,
      })
      .then(async (siteEntity) => {
        if (!siteEntity) {
          siteEntity = this.sitesRepository.create({ url: path });
        }

        if (!siteEntity) {
          console.log("siteEntity");
        }

        const snapshot = this.siteSnapshotsRepository.create({});

        if (!snapshot) {
          console.log("snapshot");
        }

        this.snapshots.push(snapshot);

        siteEntity.siteSnapshots.add(snapshot);
        await this.sitesRepository.persistAndFlush(siteEntity);

        subject.next(snapshot);
        this.pubSub.publish(NEW_SNAPSHOT, {
          siteId: siteEntity.id,
          newSnapshot: snapshot,
        } as NewSnapshotMessage);

        this.crawlSite(path)
          .pipe(
            map(({ type, page }) => {
              if (type === "external") {
                const externalLink = this.externalLinksRepository.create({
                  url: page.path.toString(),
                  statusCode: page.statusCode,
                });

                if (!externalLink) {
                  console.log("externalLink");
                }

                return externalLink;
              } else {
                const pageSnapshot = this.pageSnapshotsRepository.create({
                  url: page.path.toString(),
                  title: page.title,
                  statusCode: page.statusCode,
                });

                if (!pageSnapshot) {
                  console.log("pageSnapshot");
                }

                for (const logEntry of page.logEntries) {
                  const logEntryEntity = this.logEntriesRepository.create({
                    level: LogEntryLevel[logEntry.level.name],
                    text: logEntry.message,
                  });

                  if (!logEntryEntity) {
                    console.log("logEntryEntity");
                  }

                  pageSnapshot.logEntries.add(logEntryEntity);
                }

                for (const link of page.externalLinks) {
                  const externalLink = snapshot.externalLinks
                    .get()
                    .find(
                      (externalLink) => externalLink.url === link.toString(),
                    );

                  externalLink && externalLink.pageSnapshots.add(pageSnapshot);
                }

                if (page.sourceResult?.messages?.length) {
                  for (const message of page.sourceResult.messages) {
                    const htmlValidationError = this.htmlValidationErrorsRepository.create(
                      { ...message },
                    );

                    if (!htmlValidationError) {
                      console.log("htmlValidationError");
                    }

                    pageSnapshot.htmlValidationErrors.add(htmlValidationError);
                  }
                }

                return pageSnapshot;
              }
            }),
            tap((_snapshot) => {
              if (_snapshot instanceof PageSnapshotEntity) {
                snapshot.pageSnapshots.add(_snapshot);
              } else {
                snapshot.externalLinks.add(_snapshot);
              }
            }),
            tap(async (_snapshot) => {
              try {
                await this.sitesRepository.persistAndFlush(siteEntity);
                subject.next(snapshot);
                this.pubSub.publish(PAGE_CRAWL, {
                  siteId: siteEntity.id,
                  snapshotId: snapshot.id,
                  pageCrawl: {
                    [_snapshot instanceof PageSnapshotEntity
                      ? "pageSnapshot"
                      : "externalLink"]: _snapshot,
                  },
                } as PageCrawlMessage);
              } catch (error) {
                console.error(error);
              }
            }),
            last(),
          )
          .subscribe(async () => {
            await this.sitesRepository.persistAndFlush(siteEntity);
            subject.next(snapshot);
            subject.complete();
            const index = this.snapshots.findIndex((s) => s.id === snapshot.id);
            this.snapshots.splice(index, 1);
          });
      });

    return subject;
  }
```

As can be seen in the above snippet, I attempted logging the entities to figure out if any of them might have not been created properly. This doesn't seem to be the case. `entity: undefined` suggests an issue similar to #696, but I already explained why that seems unlikely.

The error itself is thrown in the `try {}` statement of the second `tap()` operator.

What I find odd is that this error only started occuring, after having added the following entity to my codebase, and logic. I still have the codebase without this new entity, and all seems to work out fine, with little to no differrence in the core sections of the flow.

```ts
@Entity({ tableName: "html_validation_errors" })
export class HtmlValidationErrorEntity extends BaseEntity {
  @Property()
  ruleId: string;

  @Property({ nullable: true })
  ruleUrl?: string;

  @Property({ columnType: "int" })
  severity: number;

  @Property()
  message: string;

  @Property({ columnType: "int" })
  offset: number;

  @Property({ columnType: "int" })
  line: number;

  @Property({ columnType: "int" })
  column: number;

  @Property({ columnType: "int" })
  size: number;

  @Property()
  selector: string;

  @ManyToOne(() => PageSnapshotEntity, {
    joinColumn: "page_snapshot_id",
    onDelete: "CASCADE",
  })
  pageSnapshot: PageSnapshotEntity;
}
```

Unfortunately, the stacktrace pointing to `entity: undefined` makes it even harder to pinpoint where this could be happening, since the `tap()` operation affects a lot of entities.

**Expected behavior**

Saving the values to the database without hassle as it used to.

**Additional context**

- 

**Versions**

| Dependency | Version |
| - | - |
| `node` | 14.15.0 |
| `typescript` | 4.2.3 |
| `@mikro-orm/core` | 4.5.4 |
| `@mikro-orm/mysql` | 4.5.2 |
| `@nestjs/core` | 7.6.15

**Comment by B4nan** [comment]
This is a validation, it points to you using the ORM wrongly, not to a bug in ORM. It literally means you are using the same EM instance to flush multiple times in parallel, so not using proper context management.

**Comment by Dan6erbond** [comment]
@B4nan like I said, I understand what the possible sources of the issue _are_, having linked two related issues myself, but I can't see what's suddenly causing them here, when the only changes to the codebase I made are adding a new entity and creating it as part of the same flow that did very similar things before as well.

Nothing about _the way_ I'm using MikroORM has changed, I'm simply persisting additional values and this seems to have suddenly triggered a new error.

I would appreciate at least a pointer in the direction I could look, because I can't imagine parallel flushing to be happening, as I'm only triggering the job once (for now) and the NestJS integration takes care of context management on its own. This issue occurs even if I run the task as the very first thing I do when starting the application, or even if I start it using the CLI (so there's no side-effects running, no webserver, etc.)

I'll try aligning the ORM versions, though, and see if that helps. But I appreciate the input in that regard!

**Comment by B4nan** [comment]
> Nothing about the way I'm using MikroORM has changed, I'm simply persisting additional values and this seems to have suddenly triggered a new error.

Well nothing in the ORM changed either, the validation is still triggered in the very same way. And it still means the very same thing - you are flushing twice on the same EM instance at the very same time. 

> I would appreciate at least a pointer in the direction I could look, because I can't imagine parallel flushing to be happening

Again, the validation literally means you _are_ doing so, you _are_ flushing in parallel, and that triggers the validation. I don't have any better advice for you, not without executable repro. Try adding some `console.log`s to the ORM code I guess, to better understand what's happening. 

Check the code, it's deadly simple, there is a try/catch that toggles `working` flag on the UoW, switching it back to false in the finally block. 

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/unit-of-work/UnitOfWork.ts#L217
https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/unit-of-work/UnitOfWork.ts#L225
https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/unit-of-work/UnitOfWork.ts#L246
https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/unit-of-work/UnitOfWork.ts#L457

**Comment by Dan6erbond** [comment]
I'll be honest, I didn't think like that because my task is such a long-running one that I figured any ORM commits would almost have to be delayed, but it seems you were right! I'm getting some result emitted far too many times, now I have to find out why that's happening! Thank you!
