### ISSUE TITLE
First record from the list is randomly (changed by app restart) broken

### ISSUE THREAD

**Issue by murbanowicz** [mikro-orm/mikro-orm#1746]
**Describe the bug**
For some reason, the First event is not getting all field populated "sometimes".
The restart will usually fix the broken queries, but the other collections will become broken instead.

I am on the latest MikroORM version.
MySQL.

The code is available here: https://github.com/murbanowicz/birdie-test/tree/master/backend

The app is deployed here: https://urbanowicz-birdie-frontend.herokuapp.com/

I have successfully pushed real-life projects to production with MikroORM and never had an issue like this.

The app and the entity is crazy simple.

The strange thing is that it is the random factor here and the restart changing the affected collections.

**Comment by B4nan** [comment]
I havent checked the code in detail, but I don't see any place where you would handle request contexts. If you use global EM, this is exactly the kind of issues you fall into. 

https://mikro-orm.io/docs/identity-map/#problem-2---unstable-response-of-api-endpoints

**Comment by murbanowicz** [comment]
Hello,

This was exactly this one.
I got used to using MikroORM with NestJS where this is handled by the MikroORM integration itself.

I am really thankful for your help!
