### ISSUE TITLE
[feature] orderBy: {'table.column': 'direction'} could add the table to the FROM-clause

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#175]
`select "e0".* from "Rig" as "e0" order by "psu"."id" asc limit $1 - missing FROM-clause entry for table "psu"`

**Comment by lookfirst** [comment]
(sorry, i clicked bug but then decided to ask for a feature.)

**Comment by B4nan** [comment]
Can you add desired sql? Should it add join or just another from clause? How would it work? Never used such approach.

**Comment by lookfirst** [comment]
I desire the above SQL to work. =) I think it would be to just add the missing FROM clause.

Why I need this? I have columns in an html table that I'd like to sort. If I name the column key as something like 'psu.id', then I can send that to the server unmodified. In this case, I have a rig table with a 1-1 on psu id and I want to order by psu id.

**Comment by B4nan** [comment]
> I desire the above SQL to work.

But it is not valid sql, that is the problem, or not? So again, what exact sql would you like to be generated? Do you just want that second table to be added to from clause (which does not make sense to me), or should it join somehow? 

> I have a rig table with a 1-1 on psu id and I want to order by psu id.

This sounds like you want to join psu table based on the 1:1 relation. If so, this should be already supported via #157. 

https://github.com/mikro-orm/mikro-orm/blob/dev/docs/query-builder.md#implicit-joining

**Comment by lookfirst** [comment]
```
@Entity()
export class Rig {
	@OneToOne(() => Psu, psu => psu.rig, {owner: true})
	psu: Psu;
}
```

`em.findAndCount(Rig, {}, {orderBy: ['psu.id']})`

`select "e0".* from "Rig" as "e0", "Psu" as "e1" order by "e1"."id" asc limit $1`

**Comment by B4nan** [comment]
> select "e0".* from "Rig" as "e0", "Psu" as "e1" order by "e1"."id" asc limit $1

Does this really work? I mean I know this is valid SQL, but when you do not join tables, does it really sort like you want? As you do not join those tables...

**Comment by B4nan** [comment]
I think you should join them, this should already work: 

    em.findAndCount(Rig, {}, { orderBy: { psu: { id: QueryOrder.ASC } } })

Btw the value should be object, not array, and you need to specify the direction. (as a value, you can also use 'asc/desc/ASC/DESC/1/-1' if you do not want to use that enum)

**Comment by lookfirst** [comment]
Right, I messed up the syntax... how about making this work...

`em.findAndCount(Rig, {}, {orderBy: [{'psu.id': 'asc'}]})`

In this case, I'm trying to do as little data munging as I can on the server. My gridtable implementation already sends the format above.

**Comment by B4nan** [comment]
I am planning to make the query and order parameters type safe (#124), so I will require that nested object. 

Supporting array of objects in order by is on the other hand something I was also thinking about.

**Comment by lookfirst** [comment]
ok! closing then...
