### ISSUE TITLE
npx mikro-orm migration:create (node:12200) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token ] in JSON at position 170

### ISSUE THREAD

**Issue by NANI1734** [mikro-orm/mikro-orm#1750]
**bug**
when I type npx mikro-orm migration:create on terminal i got this error
```
(node:12200) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token ] in JSON at position 170
```

**package.json**
```json
{
  "name": "Server",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "watch": "tsc -w",
    "dev": "nodemon ./dist/index.js",
    "start": "node ./dist/index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/node": "^15.0.1",
    "nodemon": "^2.0.7",
    "ts-node": "^9.1.1",
    "typescript": "^4.2.4"
  },
  "dependencies": {
    "@mikro-orm/cli": "^4.5.4",
    "@mikro-orm/core": "^4.5.4",
    "@mikro-orm/migrations": "^4.5.4",
    "@mikro-orm/postgresql": "^4.5.4",
    "mikro-orm": "^4.5.4",
    "pg": "^8.6.0"
  },
  "mikro-orm": {
    "useTsNode": true,
    "configPaths": [
      "./src/mikro-orm.config.ts",
      "./dist/mikro-orm.config.js"
    ]
  }
}

```
**mikro-orm.config.ts**
```ts
import { Post } from "./intites/Post";
import { _prod_ } from "./constance";
import { MikroORM } from "@mikro-orm/core";
// @ts-ignore
import path from "path";

export default {
    migrations: {
        path: path.join(__dirname, "./migrations"),
        pattern: /^[\w-]+\d+\.[tj]s$/,
    },
    entities: [Post],
    type: 'postgresql',
    dbName: 'leriddit',
    debug: !_prod_,
} as Parameters<typeof MikroORM.init>[0];

```

**Versions**

| Dependency | Version |
| - | - |
| node | v14.15.5 |
| typescript | 4.2.2 |
| mikro-orm | 4.5.4 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
Your tsconfig is not a valid json.

**Comment by NANI1734** [comment]
> Your tsconfig is not a valid json.
wdym

**Comment by NANI1734** [comment]
my tsconfig is 
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "lib": [
      "dom",
      "es6",
      "es2017",
      "esnext.asynciterable",
    ],
    "removeComments": true,
    "sourceMap": true,
    "outDir": "./dist",
    "moduleResolution": "node",
    "baseUrl": ".",
    "experimentalDecorators": true
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "./src/**/*.tsx",
    "./src/**/*.ts"
  ],

}
```

**Comment by B4nan** [comment]
This is not a valid JSON, you have trailing commas there.

**Comment by NANI1734** [comment]
> This is not a valid JSON, you have trailing commas there.

I removed trailing commas but still doesn't work

**Comment by B4nan** [comment]
You have two trailing commas there. Just try `JSON.parse('./tsconfig.json')` and you will see.

**Comment by NANI1734** [comment]
bruh     
migrations: {
        path: path.join(__dirname,"./migrations"),
        pattern: /^[\w-]+\d+\.[tj]s$/
    },
    dbName: "lireddit",
    type: "postgresql",
    host: "localhost",
    port: 5432,
    user: "postgres",
    password: "toor",
    entities: [Post],
    debug: !__prod__

**Comment by NANI1734** [comment]
i removed trailing commas

**Comment by B4nan** [comment]
bruh? This is not even tsconfig, this is ORM config.

**Comment by NANI1734** [comment]
yea thats ORM config.

**Comment by B4nan** [comment]
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "lib": [
      "dom",
      "es6",
      "es2017",
      "esnext.asynciterable", <== here
    ],
    "removeComments": true,
    "sourceMap": true,
    "outDir": "./dist",
    "moduleResolution": "node",
    "baseUrl": ".",
    "experimentalDecorators": true
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "./src/**/*.tsx",
    "./src/**/*.ts"
  ], <== here

}
```

**Comment by NANI1734** [comment]
ohok

**Comment by NANI1734** [comment]
thx fixed
but 
wtf is that ```Error: Please provide either 'type' or 'entity' attribute in Post.id```

**Comment by NANI1734** [comment]
im using import 'reflect-metadata';

**Comment by B4nan** [comment]
maybe on a bad place 🤷 or maybe you have non-standard setup (e.g. webpack/babel) that do not support reflect-metadata out of box?

you know, it's sunday morning here, so if you will continue being rude ("bruh", "wtf", etc...), i will just close/lock this. show some respect, don't spam like this (3 messagers in 5 minutes, guess who just recieved 3 emails because of that?), and if you want help, provide enough details or search it yourself first. do you really think I can help from seeing one line error, not even full stack trace or entity definition? nope, i dont have a magic orb.

there are many example projects, they all just work, so ideally pick one and see what you did differently. the error is validation error, it points to you doing something wrong. if you see that, it really means the metadata are not present.

**Comment by NANI1734** [comment]
nvm i fix it thanks

**Comment by NANI1734** [comment]
Ugh sorry for beginning rude lol
