### ISSUE TITLE
@Property.onUpdate() does invoke custom type serializers

### ISSUE THREAD

**Issue by apancutt** [mikro-orm/mikro-orm#1751]
**Describe the bug**
The value returned by an `onUpdate()` callback does not get serialized by custom type handlers.

Perhaps this is intentional and by design, but should be documented if so.

**To Reproduce**

```ts
import { Entity, PrimaryKey, Property, Type } from '@mikro-orm/core';
import { DateTime } from 'luxon';

@Entity()
class MyEntity {

  @PrimaryKey()
  public id!: number;

  @Property({ onUpdate: () => DateTime.now(), type: LuxonDateTimeType })
  public updatedAt: DateTime = DateTime.now();

}

class LuxonDateTimeType extends Type<DateTime | undefined, string | undefined> {

  public convertToDatabaseValue(value: DateTime | undefined): string | undefined {
    return value && value.toUTC().toSQL({ includeOffset: false });
  }

  public convertToJSValue(value: string | undefined): DateTime | undefined {
    return value && DateTime.fromSQL(`${value} UTC`);
  }

}
```

Produces a query similar to:

```
update `my_entity` set `updated_at` = '2021-04-30T16:13:12.606Z' where `id` = 1
```

Which yields error:

```
Incorrect datetime value: '2021-04-30T16:13:12.606Z' for column 'updated_at' at row 1
```

**Expected behavior**

`LuxonDateTimeType.convertToJSValue()` is called on the value returned by `onUpdate()`, before the query is executed.

**Additional Context**

The `onUpdate()` handler is called by [ChangeSetPersister](https://github.com/mikro-orm/mikro-orm/blob/e8b7119eca0df7d686a7d3d91bfc17b74baaeea1/packages/core/src/unit-of-work/ChangeSetPersister.ts#L261).

Confusingly, plain `Date` objects are handled fine. I've not dug deep into why, but I suspect Date objects are cast to SQL-safe strings internally (either by Mikro-ORM, Knex or mysql2... who knows).

**Versions**

| Dependency | Version |
| - | - |
| node | 16.0.0 |
| typescript | 4.2.4 |
| mikro-orm | 4.5.4 |
| mysql2 | 2.2.5 |

**Comment by B4nan** [comment]
`4.5.5-dev.7`

**Comment by apancutt** [comment]
Thanks!
