### ISSUE TITLE
Conector for BigQuery

### ISSUE THREAD

**Issue by Nisgrak** [mikro-orm/mikro-orm#1761]
**Is your feature request related to a problem? Please describe.**
I need to manage a BigQuery database with MikroORM

**Describe the solution you'd like**
A conector like have mariadb, postgres, etc

**Comment by B4nan** [comment]
I dont follow, please try to be more verbose. Mariadb and pg are both supported.

**Comment by Nisgrak** [comment]
Sorry!

I mean BigQuery, not the managed MariaDB or PG servers by Google Cloud Platform.
BigQuery itself has a mixes from different SQL databases, so I don't know what to choose 

Follows more or less the SQL standard but I don't know if MikroORM or even Knex has support for it.

https://cloud.google.com/bigquery/docs/introduction
https://cloud.google.com/bigquery/docs/reference/standard-sql/enabling-standard-sql

**Comment by B4nan** [comment]
I see. I don't have any plans to add more drivers as of now (2 are WIP and if something, I'd like to focus on finishing those), but open for PR. Drivers are abstracted, so it is possible even now to provide custom driver.

**Comment by B4nan** [comment]
But if `BigQuery` supports one of the existing dialects, this should be pretty much only about the connection, so it could be very easy to make it work. 

Did a quick search and found some knex dialects for that (probably WIP but it should put you on the right path):

https://github.com/avian-aero/knex-bigquery
https://github.com/lchemy/knex-bigquery-client
https://github.com/knex/knex/pull/2381

**Comment by B4nan** [comment]
Closing, as I don't plan to work on this in near future. Will be happy to assist if anyone wants to give it a try, but it should be first born as a 3rd party module before we consider merging it to this repo.
