### ISSUE TITLE
Slack invite link is no longer active

### ISSUE THREAD

**Issue by royshouvik** [mikro-orm/mikro-orm#177]
Not sure if it's intentional but the invite link doesn't work.

**Comment by B4nan** [comment]
Here is the new one, will fix that during today:

https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA
