### ISSUE TITLE
Postgres SKIP LOCKED

### ISSUE THREAD

**Issue by johnkahn** [mikro-orm/mikro-orm#1786]
**Is your feature request related to a problem? Please describe.**
Skip locked is super useful for things like job queues. Looks like you can use it with Knex directly, but I don't want to lose the ability to use other mikro-orm features.

**Describe the solution you'd like**
Either a new lock mode, similar to TypeORM `pessimistic_partial_write`. AFAIK it should just need to set `skipLocked` on the Knex query builder along with the `forUpdate`

Or another option for skip locked.

**Describe alternatives you've considered**
Get the knex instance and use transactions manually (this is what I'm doing now, but I lose quite a bit of type safety)

**Additional context**
Add any other context about the feature request here.

**Comment by B4nan** [comment]
I'd also cover other cases too, looks like there are 4 (combination of `for share/update` and `skip lock/nowait`). Not sure about the naming, it looks like typeorm uses `pessimistic_partial_write` and `pessimistic_write_or_fail`, but I haven't seen other ORMs or tools with similar naming. Do you think it makes sense to call the `for share` variants as `partial_read` and `read_or_fail`? Do you know other tools that are abstracting this? What naming do they use? 

We can also allow passing the table names via query builder.

**Comment by johnkahn** [comment]
I think adding them to the current lock modes makes sense since you can't use `skip locked` or `nowait` without `for share/update`. I think knex actually throws an error if you add `.skipLocked()` without first doing `.forUpdate()` or `.forShare()`. So that should reduce the number of errors someone could get. It would just need to be documented well what each option does to the query, that's the only issue I had with TypeORM doing that. It was hard to tell what each option did.

Being able to specify the locked tables though is super important, especially for joins, otherwise you are locking every table that get's joined (even if you don't plan to update the other tables). So the query builder could have a second optional parameter for an array of tables/aliases to provide. And it would be great if it could be added to the Find/FindOne options as well, maybe as `lockTables`.

**Comment by B4nan** [comment]
Do you think we should allow this also for `em.find()`? Currently EM supports lock modes only on `em.findOne()`, but it feels like really artificial limitation, I guess I forgot to add it to the right place in the early days and nobody complaint :]

**Comment by johnkahn** [comment]
If there's no reason it can't be, then yeah. I'm currently having to use query builder because `find` doesn't support lock modes. Would there need to be two enums then to not allow optimistic on `find()`? Or would the type just be a union of the supported types for each?

Also I went ahead and made a patch for my project's use case to avoid having to use knex directly. Not sure if this will help implement it, but it's working for me currently. I had to add a check for the method because I noticed that the lock modes were being called when `update` queries take place and `skip locked` throws errors with `update`.

`@mikro-orm+core+4.5.4.patch`
```diff
diff --git a/node_modules/@mikro-orm/core/enums.d.ts b/node_modules/@mikro-orm/core/enums.d.ts
index c4ede3d..f97a83a 100644
--- a/node_modules/@mikro-orm/core/enums.d.ts
+++ b/node_modules/@mikro-orm/core/enums.d.ts
@@ -78,7 +78,8 @@ export declare enum LockMode {
     NONE = 0,
     OPTIMISTIC = 1,
     PESSIMISTIC_READ = 2,
-    PESSIMISTIC_WRITE = 3
+    PESSIMISTIC_WRITE = 3,
+    PESSIMISTIC_PARTIAL_WRITE = 4
 }
 export declare enum EventType {
     onInit = "onInit",
diff --git a/node_modules/@mikro-orm/core/enums.js b/node_modules/@mikro-orm/core/enums.js
index 89eb4a1..574d98d 100644
--- a/node_modules/@mikro-orm/core/enums.js
+++ b/node_modules/@mikro-orm/core/enums.js
@@ -83,6 +83,7 @@ var LockMode;
     LockMode[LockMode["OPTIMISTIC"] = 1] = "OPTIMISTIC";
     LockMode[LockMode["PESSIMISTIC_READ"] = 2] = "PESSIMISTIC_READ";
     LockMode[LockMode["PESSIMISTIC_WRITE"] = 3] = "PESSIMISTIC_WRITE";
+    LockMode[LockMode["PESSIMISTIC_WRITE"] = 4] = "PESSIMISTIC_PARTIAL_WRITE";
 })(LockMode = exports.LockMode || (exports.LockMode = {}));
 var EventType;
 (function (EventType) {

```

`@mikro-orm+knex+4.5.4.patch`
```diff
diff --git a/node_modules/@mikro-orm/knex/query/QueryBuilderHelper.js b/node_modules/@mikro-orm/knex/query/QueryBuilderHelper.js
index f22bf10..5fc9afb 100644
--- a/node_modules/@mikro-orm/knex/query/QueryBuilderHelper.js
+++ b/node_modules/@mikro-orm/knex/query/QueryBuilderHelper.js
@@ -373,6 +373,9 @@ class QueryBuilderHelper {
         if (lockMode === core_1.LockMode.PESSIMISTIC_WRITE) {
             return void qb.forUpdate();
         }
+        if (qb._method === 'select' && lockMode === core_1.LockMode.PESSIMISTIC_PARTIAL_WRITE) {
+            return void qb.forUpdate().skipLocked();
+        }
         const meta = this.metadata.find(this.entityName);
         if (lockMode === core_1.LockMode.OPTIMISTIC && meta && !meta.versionProperty) {
             throw core_1.OptimisticLockError.lockFailed(this.entityName);

```

**Comment by johnkahn** [comment]
Also I'm willing to open a PR for this, I just won't be able to start on it until next week

**Comment by B4nan** [comment]
No worries, I am already 90% there, just making some adjustments in the EM API as described above :] 

> Would there need to be two enums then to not allow optimistic on find()? Or would the type just be a union of the supported types for each?

We can do `lockMode: Exclude<LockMode, LockMode.OPTIMISTIC>`.

**Comment by johnkahn** [comment]
Awesome, looking forward to it 🎉  Thanks!

**Comment by B4nan** [comment]
There is one gotcha with the `lockTables`, as you need to specify aliases, not table names. Will try to swap the table names if there is an alias automatically, I guess it should be safe.

**Comment by johnkahn** [comment]
Right, would that work if someone overrides the alias in the query builder?

**Comment by B4nan** [comment]
Mmmm maybe it will be better to keep it up to the user, as the inference based on table/entity names wouldn't be really precise. There can be multiple joins to the same table, and we might want to lock only the root entity (and root entity always has alias `e0`).

**Comment by johnkahn** [comment]
That sounds good, could add a small warning to the docs about that so users are aware that they should probably add an alias for the table and then use that in the option (or use `e0` for the table). Should the option be called `lockAliases` then?
