### ISSUE TITLE
 TypeError: Cannot read property 'prototype' of undefined when test with jest

### ISSUE THREAD

**Issue by CANHBK** [mikro-orm/mikro-orm#1790]
**Describe the bug**
TypeError: Cannot read property 'prototype' of undefined

**Stack trace**
```
 FAIL  src/tests/sample.test.ts (10.089 s)
  × sample (950 ms)

  ● sample

    TypeError: Cannot read property 'prototype' of undefined

       5 |
       6 | test("sample", async () => {
    >  7 |   const orm = await MikroORM.init({
         |                              ^
       8 |     dbName: "cvs",
       9 |     password: "mandevices",
      10 |     user: "mandevices",

      at PostgreSqlConnection.patchKnexClient (../../node_modules/@mikro-orm/knex/Abstr
actSqlConnection.js:155:37)
      at new AbstractSqlConnection (../../node_modules/@mikro-orm/knex/AbstractSqlConne
ction.js:33:14)
      at new PostgreSqlConnection (../../node_modules/@mikro-orm/postgresql/PostgreSqlC
onnection.js:6:1)
      at new AbstractSqlDriver (../../node_modules/@mikro-orm/knex/AbstractSqlDriver.js
:11:27)
      at new PostgreSqlDriver (../../node_modules/@mikro-orm/postgresql/PostgreSqlDrive
r.js:9:9)
      at Configuration.initDriver (../../node_modules/@mikro-orm/core/utils/Configurati
on.js:160:16)
      at new Configuration (../../node_modules/@mikro-orm/core/utils/Configuration.js:2
5:28)
      at new MikroORM (../../node_modules/@mikro-orm/core/MikroORM.js:20:27)
      at Function.init (../../node_modules/@mikro-orm/core/MikroORM.js:40:21)
...
```

**To Reproduce**
```
import { MikroORM } from "@mikro-orm/core";

test("sample", async () => {
  const orm = await MikroORM.init({
    dbName: "cvs",
    password: "mandevices",
    user: "mandevices",
    host: "localhost",
    entities: ["**/entities/**.js"],
    type: "postgresql",
  });
  expect(4 + 5).toBe(9);
});

```

**Expected behavior**
No Errrors

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 14.15.1 |
| typescript | 4.2.3 |
| mikro-orm | 4.5.4 |
| your-driver | postgresql|

**Comment by CANHBK** [comment]
> Do you really think that there would be error reproducible just by initializing the ORM, and you would be the only one reporting it? Nope...
> 
> Closing, as this is obviously not reproducible like that. Check the [example apps](https://github.com/mikro-orm/mikro-orm-examples) if you need help with setting things up. Or provide full reproduction.
> 
> Btw for folder based discovery you need to setup both `entities` and `entitiesTs`, otherwise things will break during development (when `ts-node` is used).
> 
> But that would not produce such error most probably, it points rather to you having some dependency problems, how does your package.json look like? You need to have the ORM packages aligned (e.g. `core` package needs to use the very same version as driver package and cli package).

I still can't setup test mikro-orm with ts-jest, please give me example of ts-jest setup

**Comment by B4nan** [comment]
As I said, check the example apps, e.g. https://github.com/mikro-orm/nestjs-realworld-example-app has jest set up.

If you want more help, provide full repro, you are clearly trying more advanced setup, seeing the `moduleNameMapper` setting and `moduleDirectories`, you usually don't need that - do you have a monorepo? What is your full package.json? Do you have knex there? Because you should not, just a guess but I can imagine this happening if you somehow installed knex 0.95+ (MikroORM v4 is not compatible with that version).

If you haven't tried already, try wiping `node_modules` as well as the lockfile and reinstal. Also try `npx mikro-orm debug` and ensure the installed ORM packages really are on the same version.

**Comment by CANHBK** [comment]
> As I said, check the example apps, e.g. https://github.com/mikro-orm/nestjs-realworld-example-app has jest set up.
> 
> If you want more help, provide full repro, you are clearly trying more advanced setup, seeing the `moduleNameMapper` setting and `moduleDirectories`, you usually don't need that - do you have a monorepo? What is your full package.json? Do you have knex there? Because you should not, just a guess but I can imagine this happening if you somehow installed knex 0.95+ (MikroORM v4 is not compatible with that version).
> 
> If you haven't tried already, try wiping `node_modules` as well as the lockfile and reinstal. Also try `npx mikro-orm debug` and ensure the installed ORM packages really are on the same version.

Yes, I run in monorepo, mikro-orm work ok when develope, but not when test.

Here is repo, please help me https://github.com/CANHBK/debug-mikro-orm.

My test file at `packages/server/src/tests/sample.test.ts`

**Comment by B4nan** [comment]
I can't even install the dependencies in that repo. 

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@cvs%2fcommon: Not found".
```

**Comment by B4nan** [comment]
As I already said, that jest config looked suspicious. Tried removing the `moduleDirectories: ["node_modules", "."]` part and tests are passing. That dot there seems weird, not sure why you had it there.

**Comment by CANHBK** [comment]
Thank you so much! That is the cause. But can you explain to me why?

**Comment by CANHBK** [comment]
> As I already said, that jest config looked suspicious. Tried removing the `moduleDirectories: ["node_modules", "."]` part and tests are passing. That dot there seems weird, not sure why you had it there.

Thank you so much! That is the cause. But can you explain to me why?
