### ISSUE TITLE
NX and mikro-orm CLI - cannot find module (tsconfig: compilerOptions > path

### ISSUE THREAD

**Issue by Langstra** [mikro-orm/mikro-orm#1792]
**Describe the bug**
A bug that the mikro-orm cli has when being used in the nx monorepo environment (and most likely other environments using the compilerOption > paths option in the tsconfig)

The problem could be that exporting a `type` is alright by TypeScript, but exporting a `const` is not. However, when running (and building the code) there is no problem with this.

I created a reproduction repository with a similar explanation. Also with steps how to run it and reproduce the bug.

https://github.com/RiskChallenger/nx-mikro-orm-cli

**Stack trace**
```
- configuration not found (Cannot find module '@test-mikro-orm/shared'
Require stack:
- /home/langstra/Documents/test-mikro-orm/apps/api/src/app/house.entity.ts
- /home/langstra/Documents/test-mikro-orm/apps/api/src/app/project.entity.ts
- /home/langstra/Documents/test-mikro-orm/apps/api/src/app/mikro-orm.config.ts
- /home/langstra/Documents/test-mikro-orm/node_modules/@mikro-orm/core/utils/ConfigurationLoader.js
- /home/langstra/Documents/test-mikro-orm/node_modules/@mikro-orm/core/utils/index.js
- /home/langstra/Documents/test-mikro-orm/node_modules/@mikro-orm/core/typings.js
- /home/langstra/Documents/test-mikro-orm/node_modules/@mikro-orm/core/index.js
- /home/langstra/Documents/test-mikro-orm/node_modules/@mikro-orm/cli/CLIConfigurator.js
- /home/langstra/Documents/test-mikro-orm/node_modules/@mikro-orm/cli/cli.js)
Done in 0.60s.
```

**To Reproduce**
```bash
$ git clone git@github.com:RiskChallenger/nx-mikro-orm-cli.git
$ cd nx-mikro-orm-cli
$ yarn
$ yarn mikro-orm debug
```

**Versions**
```bash
Current MikroORM CLI configuration
 - dependencies:
   - mikro-orm 4.5.4
   - node 14.4.0
   - typescript 4.1.5
 - package.json found
 - ts-node enabled
 - searched config paths:
   - /home/langstra/Documents/test-mikro-orm/apps/api/src/app/mikro-orm.config.ts (found)
   - /home/langstra/Documents/test-mikro-orm/mikro-orm.config.ts (not found)
   - /home/langstra/Documents/test-mikro-orm/mikro-orm.config.js (not found)

```

**Comment by B4nan** [comment]
You need `tsconfig-paths` for this, and actually MikroORM does handle it (registers them automatically). So maybe take a look at that part:

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/utils/ConfigurationLoader.ts#L84

There is also #545, which might be somehow related.

**Comment by Langstra** [comment]
Ah I think the problem is that it does not support the `extends`.
`tsconfig.app.ts`
```
{
  "extends": "./tsconfig.json",
  ...
}
```
Then `tsconfig.json` extends the `tsconfig.base.ts` which contains the `compilerOptions.paths` and `compilerOptions.base`.

Should we adjust the code to check for the `extends` key, then read that file, check for the `extends` key again, merge the other properties and read the next file that is extended (if any).

**Comment by B4nan** [comment]
Btw you could get around this by creating dedicated tsconfig just for the CLI (and adjusting the path to it in `package.json`), with correct `paths` information.

**Comment by Langstra** [comment]
Yeah that works, but it ain't as nice, since you need to maintain the additional tsconfig. I'll try to create a fix and a PR. Should I create a PR to the 4.x branch and master?

**Comment by B4nan** [comment]
master, will cherry pick to 4.x once its there

**Comment by B4nan** [comment]
`4.5.5-dev.18`
