### ISSUE TITLE
Still using old version knex ?

### ISSUE THREAD

**Issue by asiFarran** [mikro-orm/mikro-orm#1797]
Hi,

Is there a reason why @mikro/orm/knex  4.5.4 is still pinned on the old knex 0.21.19?

I see the the =version was updated in the repo almost two months ago but in all the npm packages released since the dependency is still the old one.

??

**Comment by B4nan** [comment]
knex 0.95 is breaking as it drops support for TS and node versions that MikroORM v4 still supports, it will be part of v5
