### ISSUE TITLE
validate missing `qb.onConflict` calls

### ISSUE THREAD

**Issue by woltob** [mikro-orm/mikro-orm#1803]
I run a multi-threaded frontend that needs to send data to the API (running MikroORM) and discards them, when delivered. There are cases where data is being sent twice, leading to error from the database due to duplicate primary keys as the uuids need to be generated in the frontend.

Please implement Postgres' native upsert functionality that can do "DO NOTHING" when there is a duplicate:
https://www.postgresqltutorial.com/postgresql-upsert/

Or is there a good way of doing this without going back to bare SQL queries?

Thanks!

**Comment by B4nan** [comment]
You should use QB for this, I don't feel like the UoW should do something like upserts automatically. QB do support `onConflict()` with `ignore()` just like knex does.

**Comment by woltob** [comment]
Thanks for your quick response. Doing so, I receive occasionally an 

```
TypeError: Cannot read property 'length' of undefined
    at QueryBuilder.ignore (/path_to_project/node_modules/@mikro-orm/knex/query/QueryBuilder.js:166:43)
```

Do you have an idea what that could mean?

**Comment by B4nan** [comment]
And your code looks like what? Because this should be always defined if you first call `qb.onConflict()`.

Also every time I head "occasionally" it points to some other issue, like using single QB instance in parallel, which is wrong for sure.

**Comment by woltob** [comment]
I was mistaken, it happens on every call, it was just so the console was full of logs. 
My code looks like this:

```
const em = this.em.fork(false, false);
const deviceLog = new DeviceLog(...);
em.createQueryBuilder(DeviceLog).insert(deviceLog).ignore().execute(); 
```

**Comment by B4nan** [comment]
Which is... invalid - you are missing the `onConflict()` call there.

**Comment by woltob** [comment]
Thanks. This seems to have solved it. For everyone who sees this:

```
em.createQueryBuilder(DeviceLog)
          .onConflict('id')
          .insert(deviceLog)
          .ignore()
          .execute();
```

**Comment by B4nan** [comment]
`onConflict` currently requires a parameter which is apparently not needed (at least not in all drivers), will fix that as part of this issue and also add validation in case the `onConflict` call is missing

**Comment by B4nan** [comment]
`4.5.5-dev.18`
