### ISSUE TITLE
Query in onFlush/afterFlush hook `Transaction query already complete`

### ISSUE THREAD

**Issue by Langstra** [mikro-orm/mikro-orm#1824]
**Describe the bug**
When trying to insert some entities inside a `afterFlush` `onFlush` event handlers. I do this using a native query. So I was not expecting a problem with the entity map or anything. However, it does give another error.
`DriverException: Transaction query already complete, run with DEBUG=knex:tx for more info at MySqlExceptionConverter.convertException`

https://mikroorm.slack.com/archives/CFSAF8DEX/p1621260881195200

**Stack trace**
```
DriverException: Transaction query already complete, run with DEBUG=knex:tx for more info at MySqlExceptionConverter.convertException
```

**To Reproduce**

This error occurs in my case in a nestjs application. So I use the EM from the repository, but the general EM should give the same results here.

1. Create a subscriber
2. Use the onFlush/afterFlush hook

```
public async saveAuditTrail(auditObjects: AuditTrailDto[]): Promise<void> {
    const em: SqlEntityManager = this.em as SqlEntityManager;
    const qb = em.createQueryBuilder(AuditTrail);
    if (auditObjects.length > 0) {
      qb.insert(auditObjects);
      return qb.execute();
    }
  }
```

**Additional context**
As said by @B4nan `em.getDriver().nativeInsert(...)` is a nice workaround. However, should still be considered a bug.

**Versions**

| Dependency | Version |
| - | - |
| node | 14 |
| typescript | 4.1 |
| mikro-orm | 4.5.5 |
| mysql | 4.5.5 |
| mikro-orm/nestjs | 4.2.0 |

**Comment by B4nan** [comment]
Seems to be issue only with `afterFlush`, rest of the events work fine for me with `args.em.nativeInsert()`.

> This error occurs in my case in a nestjs application. So I use the EM from the repository, but the general EM should give the same results here.

Oh wait a minute, so you are using the global EM. That seems wrong, you should be using the one from `EventArgs/FlushEventArgs`. The root one will use the request fork under the hood, but that still might be the wrong instance, e.g. when using explicit or nested transactions.

It might not be an actual issue, but it feels wrong for sure. You might as well easily polute the wrong identity map this way.

**Comment by B4nan** [comment]
`4.5.6-dev.11`
