### ISSUE TITLE
[bug] 1-1 populate of inverse side isn't working

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#183]
v18

I've created a super simple example here:

https://github.com/lookfirst/mikro-example/blob/master/test/db/ab.spec.ts

```
TypeError: Cannot read property 'id' of undefined
```

Maybe I'm doing something wrong, but I'd expect the `populate: ['a']` to hydrate the object. Adding `.init()` doesn't work either since the object is undefined.

**Comment by lookfirst** [comment]
`{populate: true}` also fails.

**Comment by B4nan** [comment]
Your problem is that you persist the entity and try to load it right ahead in the same "session". When you persist new entity, it becomes managed. When you later on request that entity by PK (e.g. `findOne(B, 1)`), it will first check the identity map. And as its managed entity, it will return the entity from it instead of fetching it from database. So for tests like this, you can either call `em.clear()` after initial persisting of items, or fork the manager and work with the forked one. 

Here is what happens in your code:

```typescript
const a = new A();
a.id = 1;
const b = new B();
b.id = 1;

a.b = b; // you assign to A.b property, but B.a is still undefined
console.log(b.a); // this is undefined
await orm.em.persistAndFlush(a); // here both a and b become managed, but b.a is still undefined

const foundB = await orm.em.findOneOrFail(B, 1, ['a']); // here you fetch the very same `b`, just to another variable
expect(foundB).toBe(b); // this should be true, as it is reference to the very same object
console.log(b.a); // this is still undefined
```

**Comment by B4nan** [comment]
This should be working:

```typescript
const a = new A();
a.id = 1;
const b = new B();
b.id = 1;

a.b = b; // you assign to A.b property, but B.a is still undefined
await orm.em.persistAndFlush(a); // here both a and b become managed, but b.a is still undefined
orm.em.clear(); // clear the identity map, starting new session

const foundB = await orm.em.findOneOrFail(B, 1, ['a']); // now you fetch from database as identity map is cleared
expect(foundB).not.toBe(b); // now its different object
console.log(b.a); // and this should be defined/populated
```

**Comment by lookfirst** [comment]
I knew I was doing something stupid. Sorry for the trouble and thanks. Working great now.

**Comment by lookfirst** [comment]
By the way, I'm guessing that not calling `orm.em.clear()` this will be the bane of your existence.

**Comment by B4nan** [comment]
Well it should be issue pretty much only when testing, in real world you wouldn't do such thing. 

Maybe we could auto-wire things like this (missing 1:1 and m:1) when persisting the entity. Will write down a note about this, should be relatively easy.

**Comment by lookfirst** [comment]
v21 breaks my tests. v20 (and before) works.

Seems to happen on an update. The update is trying to set the id on the inverse (far) side of a 1-1 relationship, which is of course failing because the column doesn't exist.

**Comment by B4nan** [comment]
Which one? Tried to get latest version of your example repository, updated to alpha 21 and all tests are passing for me.

**Comment by lookfirst** [comment]
Sorry, I have tests for my own app, but they are pretty complicated so I'm not sure how to diagnose it effectively.  The big issue is that after a few hours of trying, I can't seem to replicate it at all in my example suite.

https://github.com/lookfirst/mikro-example/blob/master/test/db/ab.spec.ts#L56

I also noticed that it may be some weird timing issue with running the tests. The test failures look like this...

```
● ModelMgr › saveRig with create › creates a new rig with an existing psu

    update `Psu` set `rig` = 'rig:1', `updatedAt` = '2019-10-06 11:08:03.043' where `id` = 'psu:1' - SQLITE_ERROR: no such column: rigError: SQLITE_ERROR: no such column: rig

  ● ModelMgr › saveRig with create › creates a new rig with an existing psu

    ValidationError: Datacenter not found (1)

       96 | 			rig.updatedBy = person;
       97 | 		} else {
    >  98 | 			const datacenter = await this.em.findOneOrFail(Datacenter, 1);
          | 			                   ^
       99 | 			const rigType = await this.em.findOneOrFail(RigType, {id: rigInput.type});
      100 | 			rig = new Rig(rigInput, datacenter, person);
      101 | 			rig.type = rigType;

      at Function.findOneFailed (node_modules/mikro-orm/dist/utils/ValidationError.js:91:16)
      at Object.findOneOrFailHandler [as failHandler] (node_modules/mikro-orm/dist/utils/Configuration.js:113:74)
      at EntityManager.findOneOrFail (node_modules/mikro-orm/dist/EntityManager.js:90:27)
      at ModelMgr.createOrUpdateRig (src/db/ModelMgr.ts:98:23)
      at ModelMgr.saveRig (src/db/ModelMgr.ts:85:10)
      at Object.<anonymous> (test/db/ModelMgr.spec.ts:117:4)

  ● ModelMgr › saveRig with create › saving two rigs with the same id

    update `Psu` set `rig` = 'rig:1', `updatedAt` = '2019-10-06 11:08:03.432' where `id` = 'psu:1' - SQLITE_ERROR: no such column: rigError: SQLITE_ERROR: no such column: rig
```

The part where it can't find the datacenter is weird because it is created in the `beforeEach()`, which also does a database drop/create. It is especially weird because this runs fine in v19.

Let me try to explain what's happening...

I am creating a Rig with one Psu and then after `em.clear()`, updating it with a new Psu object and during the update, it is attempting to set the rig column on Psu to a value, which the column doesn't exist.

Essentially this...

```
insert Psu1
insert Rig with Psu1
clear()
insert Psu2
update Rig with Psu2
clear()
```

```
Error: update `Psu` set `rig` = 'randomid', `updatedAt` = '2019-10-06 10:25:12.155' where `id` = 'psu:1' - SQLITE_ERROR: no such column: rig
```

```
@Entity()
export class Rig extends BaseEntity implements Node {
	@OneToOne(() => Psu, psu => psu.rig, {owner: true})
	psu!: Psu;
}

@Entity()
export class Psu extends BaseEntity implements Node {
	@OneToOne(() => Rig, rig => rig.psu)
	@Field(type => Rig, {nullable: true})
	rig!: Rig;
}
```

**Comment by lookfirst** [comment]
So the good news is that I tested my code with swapping out a Psu and that seems to run fine with v22... it could just be something with the tests... but that doesn't explain why it works with v19. =(

**Comment by lookfirst** [comment]
Oh, I may have figured it out... one second!

**Comment by lookfirst** [comment]
FML... another missing `orm.em.clear()` issue. Ok, this time, I make sure to run it before and after every test!

**Comment by B4nan** [comment]
I will try to look into this, as this sounds like a bug indeed, if it produces invalid query.

> I make sure to run it before and after every test!

I think your problem is that you are creating entities in beforeEach hook, which pollutes the identity map. So running clear at the end of the hook should be enough. Or use `em.nativeInsert()` to create the entity there instead, as that will just create database records without touching identity map. Also you should not use the reference to entities created in the hook, get the reference inside the test instead.

So for example in your thing.spec.ts, do this:

```typescript
beforeEach(async () => {
	await generator.dropSchema();
	await generator.createSchema();
	await orm.em.nativeInsert(Person, {id: 'person:1', email: 'foo@bar.com'});
});

test('creates a thing with createdBy relation', async () => {
	const createdBy = orm.em.getReference(Person, 'person:1');
	const thing = new Thing({id: 'thing:1'}, createdBy);
	await orm.em.persistAndFlush(thing);
	expect(thing.createdBy.id).toEqual('person:1');

	orm.em.clear();

	const thing1 = await orm.em.findOne(Thing, {id: 'thing:1'}, {populate: ['createdBy']});
	// asserts...
});
```

**Comment by lookfirst** [comment]
Yup, exactly the issue. Finally getting the hang of things.

**Comment by B4nan** [comment]
Good, I have it replicated in my test suite and I am pretty sure I know where the problem is. It was there from the very beginning I guess, now it just popped out because I made the inverse-owner link automatically, but if one did it manually, it would fail (`a.b = b; b.a = a;`)

This is causing the same error:

```typescript
test('inverse side of 1:1 is ignored in change set', async () => {
  const bar = FooBar2.create('fb');
  bar.baz = new FooBaz2('fz 1');
  await orm.em.persistAndFlush(bar);

  bar.baz = new FooBaz2('fz 2');
  await orm.em.flush();
});
```

What about the `Datacenter not found (1)` thing, is that still issue or was it just another identity map and beforeEach hook issue?

**Comment by lookfirst** [comment]
I think the DC not found thing was also a result of the lack of clear(). All that cleared up and tests are passing now.
