### ISSUE TITLE
Migration file continues to be created

### ISSUE THREAD

**Issue by clwmem** [mikro-orm/mikro-orm#1832]
**Describe the bug**

Migration file will be created forever after migrate up

**Stack trace**
```
...
```

**To Reproduce**
1. Modified entity
```ts
  @Property()
  @Unique()
  email: string

```
=>
```ts
  @Property({ columnType: 'varchar(255) binary' })
  @Unique()
  email: string
```

2. `mikro-orm migration:create` run
3. migrate up
```ts
  const orm = await MikroORM.init({ ...options, ...{ dbName } })
  try {
    const migrator = orm.getMigrator()
    await migrator.up()
    await orm.close()
  } catch (err) {
    await orm.close()
    throw err
  }
```
4. `mikro-orm migration:create` run again

**Expected behavior**
No changes required, schema is up-to-date

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 14.16.1 |
| typescript | 4.0.5 |
| mikro-orm | 4.4.4 |
| your-driver | mysql5.7 |

**Comment by B4nan** [comment]
Already fixed in v5 via #1641, no plans to backport any schema diffing issues as it is pretty much impossible.
