### ISSUE TITLE
[feature] ordering OneToMany collections

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#184]
I saw a bit of discussion in #157...

I have a 'Rig' and it has a collection of 'Gpus'...

```
Rig {
  gpus = new Collection<Gpu>(this);
}

Gpu {
  index: number;
}
```

I'd like the collection to be returned ordered by `gpu.index` / asc.

Seems like this could be done in the database, but I think it might also be interesting to be able to have Collection have a builder pattern such that I could do:

`gpus = Collection.sort(myCustomSortMethod).build<Gpu>(this);`

That sort could then be run on Collection.add so everything is always sorted.

Thoughts?

**Comment by lookfirst** [comment]
Tests pass! ;-) Must be a better way...

```
	async getRig(id: string, populate: boolean = true): Promise<Rig | null> {
		const foundRig = await this.em.findOne(Rig, {id: id}, {populate});
		if (foundRig) {
			if (foundRig.gpus) {
				const items = sortBy(foundRig.gpus.getItems(), ['index']);
				foundRig.gpus.set(items);
			}
			return foundRig;
		}
		return null;
	}
```

**Comment by B4nan** [comment]
> Must be a better way

I think you could simply extend `Collection` class yourself and implement this directly in `add/set` methods. 

Sounds more like an extension than something to be in the core. Also you could re-use the `orderBy` attribute instead of using custom sort callback, that way it would be consistent - that is something I can imagine being implemented directly in the `Collection` class.

Btw I am planning to enhance the collection wrapper so it can be paginated and filtered, something similar like doctrine has. Can't find the right docs right now but they do support same API for both fetched and non-fetched collections.

**Comment by lookfirst** [comment]
I think the better way is to be able to specify the sort order in the database query on the populated collection.

**Comment by B4nan** [comment]
> I think the better way is to be able to specify the sort order in the database query on the populated collection.

Not sure what you mean, that is what is in place right now, or not? Or you mean to be able to have the collection ordered differently, based on how you query the owning entity?

**Comment by lookfirst** [comment]
I would love something like this:

```ts
this.em.findOne(Rig, id, {populate, orderBy: {gpus: {index: 'asc'}}})
```

Maybe I'm confused, but when I tried that, it didn't work. It put the order by on the initial query for the rig, not the query for the gpus collection.

**Comment by B4nan** [comment]
The thing is that every entity is loaded via one query (where in ...). So your example would load `Rig` entity, ordered by gpu's index property. But then, the `gpus` collection population would fire another query without this orderBy (with orderBy based on the collection's attribute if provided). 

But this could be (hopefully) propagated down to the query that loads the collection, I am fine with that.

**Comment by lookfirst** [comment]
"So your example would load Rig entity, ordered by gpu's index property."

It is a `findOneById`, there is no order on Rig and definitely not an order based on the gpu's index. 

So unless I'm not understanding something, the logic should absolutely be to push/propagate the `order by` down to the Gpu query since that is what I'm effectively asking for in the `orderBy` clause.

**Comment by B4nan** [comment]
> It is a findOneById, there is no order on Rig and definitely not an order based on the gpu's index.

Check the query log to see what's happening. It is findOne but you specify orderBy. Under the hood, findOne is just find + limit(1). And this is how currently nested where/orderBy works. It is just about the top level query, but again, it could be propagated, for orderBy it makes sense, not totally sure if it's ok for where as well (e.g. I can imagine problems with partially populated collections). 

There is some discussion about current implementation in the issue you mentioned (#157). This is how populate works right now: https://mikro-orm.io/nested-populate/

**Comment by lookfirst** [comment]
I did check the query and see what is happening... that is why I wrote: "It put the order by on the initial query for the rig, not the query for the gpus collection."

**Comment by lookfirst** [comment]
> I think you could simply extend Collection class yourself and implement this directly in add/set methods.

Nope, thanks to the `ObjectHydrator`. =( It should use the implementation defined in the entity...

**Comment by B4nan** [comment]
You could extend hydrator too :)

**Comment by lookfirst** [comment]
Interesting... sure, but why not just use the collection that is already on the property? no need to create a new one.

**Comment by lookfirst** [comment]
Also, I'd want to refactor the ObjectHydrator to have a protected method for creating the collection.

**Comment by B4nan** [comment]
Well you cant use the one on entity as that is created from constructor, which is not used internally when creating entities from database records.

**Comment by lookfirst** [comment]
Could define the right one to use in the @OneToMany annotation?

**Comment by B4nan** [comment]
Yeah factory method on decorator, I’m fine with that.

**Comment by B4nan** [comment]
Propagating of where and orderBy to populated queries is available for testing in `3.0.0-alpha.24`.

**Comment by lookfirst** [comment]
Very sexy...

`return this.em.findOne(Rig, id, {populate, orderBy: {gpus: {index: QueryOrder.ASC}}});`

`[query] select `e0`.* from `Gpu` as `e0` left join `Rig` as `e1` on `e0`.`rig` = `e1`.`id` where `e0`.`rig` in ('1') group by `e0`.`id` order by `e0`.`index` asc [took 0 ms]`

Now I can delete the in memory sorting code and I can return the promise up to apollo, instead of having to await it in the resolver.

**Comment by lookfirst** [comment]
Go ahead and close it if you want.

**Comment by B4nan** [comment]
Yeah I don't like the idea of doing some magic in `Collection.add()`, one can always easily sort things before adding to collection, or when updating, you can use `set` to replace the whole collection with new sorted items. Let's close this now, I might add something like `Collection.sort()` later though, when enhancing the collection wrapped. Was thinking about adding some basic array helpers there so one can directly work with the collection like with array:

```
const col = new Collection(...);
const found = col.getItems().find(i => i.foo === 'bar'); // current approach
const found = col.find(i => i.foo === 'bar'); // future?
```

I am thinking about `find/map/sort/reverse/forEach/has` methods (I would go for `has` instead of `includes` probably).

**Comment by lookfirst** [comment]
Collection helpers would be nice, but not a deal breaker since it is easy enough to just work on the array. People should just be using the database to get what they need since that is what it is good for.

**Comment by B4nan** [comment]
The ultimate goal would be to support both things with same api.
