### ISSUE TITLE
Embeddables are not populated by create()

### ISSUE THREAD

**Issue by belinde** [mikro-orm/mikro-orm#1840]
**Describe the bug**
When creating a new entity, Embeddable properties are not inflated.

**To Reproduce**
```typescript
import { Embeddable, Embedded, Entity, MikroORM, PrimaryKey, Property } from '@mikro-orm/core';

@Embeddable()
class Name {
    @Property()
    firstName?: string;
    @Property()
    lastName?: string;
}

@Entity()
class Person {
    @PrimaryKey()
    id: number = Math.floor(Math.random() * 1000000);

    @Embedded(() => Name)
    name = new Name();
}

MikroORM.init({
    entities: [Person, Name],
    type: 'mysql',
    clientUrl: 'mysql://username:password@localhost/tests',
}).then((orm) => {
    const repo = orm.em.getRepository(Person);
    const p = repo.create({ name: { firstName: 'John', lastName: 'Doe' } });
    console.log(p);
});

```
**Expected behavior**
The console.log() should output something like:
```Person { id: 908924, name: Name { firstName: 'John', lastName: 'Doe' } }```

The actual output instead is:
```Person { id: 544827, name: Name {} }```

**Versions**

| Dependency | Version |
| - | - |
| node | 16.1.0 |
| typescript | 4.2.4 |
| mikro-orm | 4.5.5 |
| mikro-mysql | 4.5.5 |

**Comment by B4nan** [comment]
This is most probably caused by the property initializer, do you really need it there? If you use `em.create()` for creating new entities, you definitely don't.

```ts
    @Embedded(() => Name)
    name: Name;
```

**Comment by belinde** [comment]
That's even worst, the output become ```Person { id: 984696 }```

**Comment by B4nan** [comment]
`4.5.6-dev.6`
