### ISSUE TITLE
Unable to run migrations on postgresql

### ISSUE THREAD

**Issue by grimurd** [mikro-orm/mikro-orm#1842]
Follow up to #422, #190

I'm running migrations on postgresql

Keep getting this error:
`DriverException: set session_replication_role = 'replica'; - permission denied to set parameter "session_replication_role"`

I normally run migrations programatically in a nestjs onApplicationBootstrap lifecycle hook but I've also tried to run it using the cli.

I've tried to disabled foreign key checks in nestjs migrations config, mikro-orm.config.ts file and using environment variable with no success.

I see in the previous issues there's talk about setting wrap = false but I can't find any cli argument or or any function argument where wrap can be disabled on migrations.

**Comment by B4nan** [comment]
`wrap` is a parameter name in `SchemaGenerator` API, you need to adjust migrations config:

```
migrations: { disableForeignKeys: false }
```

**Comment by grimurd** [comment]
Thanks for the help, the error I was making was setting disableForeignKeys to true.

**Comment by oojikoo** [comment]
can be resolved by using ENV `MIKRO_ORM_MIGRATIONS_DISABLE_FOREIGN_KEYS=false` . for whom may use mikro cli to run migrations

**Comment by productdevbook** [comment]
v5 - `migrations: { disableForeignKeys: false }` dont fixed some problem

**Comment by thomascodefield** [comment]
Same issue here. Setting the flag either `true` or `false` does not do anything. @B4nan

**Comment by B4nan** [comment]
Works fine on my end, just verified. Please provide reproduction.

**Comment by productdevbook** [comment]
@thomascodefield postgresql user change owner status and my fixed.

**Comment by B4nan** [comment]
Guys, if things dont work for you, provide complete reproductions, otherwise nothing will ever get fixed. As I said, I verified it and it works just fine on my end (tested in the realworld example project).

**Comment by buzzware** [comment]
I can't provide a minimal case, but this is some good evidence. The initial migration was generated with the following config. It failed at first, then succeeded with MIKRO_ORM_MIGRATIONS_DISABLE_FOREIGN_KEYS=false.

`const mikro_config = {
	autoLoadEntities: false,
	entities: ['./dist/**/*.entity.js'],
	entitiesTs: ['./src/**/*.entity.ts'],

	type: 'postgresql',
	host: (process.env.HCLOUD_MAINDB_INSTANCE && `/cloudsql/${process.env.HCLOUD_MAINDB_INSTANCE}`) || process.env.HCLOUD_MAINDB_HOST || 'localhost',
	port: process.env.HCLOUD_MAINDB_PORT || 5432,
	dbName: process.env.HCLOUD_MAINDB_DATABASE,
	user: process.env.HCLOUD_MAINDB_USER,
	password: process.env.HCLOUD_MAINDB_PW || null,
	//HCLOUD_MAINDB_INSTANCE

	highlighter: new sql_highlighter.SqlHighlighter(),
	debug: true,
	logger: logger.log.bind(logger),
	metadataProvider: reflection.TsMorphMetadataProvider,
	allowGlobalContext: true,
	implicitTransactions: process.env.NODE_ENV!=='test',

	schemaGenerator: {
		disableForeignKeys: false, // try to disable foreign_key_checks (or equivalent) // prevents error permission denied to set parameter "session_replication_role"
		createForeignKeyConstraints: true, // do not generate FK constraints
	},
	migrations: {
		tableName: 'migrations',
		path: 'migrations',
		pattern: /^[\w-]+\d+\.js$/,
		transactional: true,
		disableForeignKeys: false,	// prevents error permission denied to set parameter "session_replication_role"
		allOrNothing: true,
		dropTables: true,
		safe: true,
		emit: 'js',
	},
};
`

`
    "@mikro-orm/cli": "^5.1.2",
    "@mikro-orm/core": "^5.1.2",
    "@mikro-orm/migrations": "^5.1.2",
    "@mikro-orm/nestjs": "^5.0.1",
    "@mikro-orm/postgresql": "^5.1.2",
    "@mikro-orm/reflection": "^5.1.2",
    "@mikro-orm/sql-highlighter": "^1.0.1",
    "@nestjs/cli": "^8.0.0",
    "@nestjs/common": "^8.0.0",
    "@nestjs/config": "^2.1.0",
    "@nestjs/core": "^8.0.0",
`
[migrate-bug.zip](https://github.com/mikro-orm/mikro-orm/files/8882910/migrate-bug.zip)

**Comment by buzzware** [comment]
My ../dist/mikro-orm.config was actually this below ie disableForeignKeys: true and no schemaGenerator section.
Will try again and update.

```
const mikro_config = {
    autoLoadEntities: false,
    entities: ['./dist/**/*.entity.js'],
    entitiesTs: ['./src/**/*.entity.ts'],
    type: 'postgresql',
    host: (process.env.HCLOUD_MAINDB_INSTANCE && `/cloudsql/${process.env.HCLOUD_MAINDB_INSTANCE}`) || process.env.HCLOUD_MAINDB_HOST || 'localhost',
    port: process.env.HCLOUD_MAINDB_PORT || 5432,
    dbName: process.env.HCLOUD_MAINDB_DATABASE,
    user: process.env.HCLOUD_MAINDB_USER,
    password: process.env.HCLOUD_MAINDB_PW || null,
    highlighter: new sql_highlighter.SqlHighlighter(),
    debug: true,
    logger: logger.log.bind(logger),
    metadataProvider: reflection.TsMorphMetadataProvider,
    allowGlobalContext: true,
    implicitTransactions: process.env.NODE_ENV !== 'test',
    migrations: {
        tableName: 'migrations',
        path: 'migrations',
        pattern: /^[\w-]+\d+\.js$/,
        transactional: true,
        disableForeignKeys: true,
        allOrNothing: true,
        dropTables: true,
        safe: true,
        emit: 'js',
    },
};

```
