### ISSUE TITLE
Issues with seeder: TypeError: seederClass is not a constructor

### ISSUE THREAD

**Issue by unematiii** [mikro-orm/mikro-orm#1843]
**Describe the bug**

I was trying out the seeder functionality, I and I couldn't get it working. Issues I encountered:

a) Seeder is unable to instantiate seeder class:

```
npx mikro-orm seeder:create DatabaseSeeder
npx mikro-orm seeder:run [--class=DatabaseSeeder]
```

I am unable to run the seed, regardless whether the class name is provider or not. I tried exporting class (including default export), seeder path is correct and resolved by `require`. Also, seed created with CLI always uses `DatabaseSeeder` as a class name (ignoring specified name) and exports nothing.

Stack trace:

```
TypeError: seederClass is not a constructor
```

b) Creating database schema also triggers seeder

Running ```mikro-orm schema:create --run``` also triggers seeder. 

**To Reproduce**
1. Create and run seeder using CLI
2. Create DB schema using ``mikro-orm schema:create --run```

**Expected behavior**
a) I should be able to run seeders using CLI. Class name specified on seeder creation should be respected.
b) Seeds should not be ran on schema creation unless explicitly specified.

**Additional context**
I was able to get it working with [following changes](https://github.com/unematiii/mikro-orm/pull/1/files).

**Versions**

| Dependency | Version |
| - | - |
| node | v14.16.0 |
| typescript | 4.2.4 |
| mikro-orm | 5.0.0-dev.135 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
cc @Langstra

**Comment by Langstra** [comment]
Thanks for trying it out and debugging it. Fixed the bug as you suggested and improved the tests.

**Comment by unematiii** [comment]
@Langstra Thank you!

**Comment by monarchwadia** [comment]
Hi! Just ran across this issue in `5.0.0-dev.292`. Here's my package.json:

```
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "mikro": "MIKRO_ORM_CLI=./lib/db/mikro-orm.cli.config.ts mikro-orm"
  },
  "dependencies": {
    "@mikro-orm/cli": "5.0.0-dev.292",
    "@mikro-orm/core": "5.0.0-dev.292",
    "@mikro-orm/postgresql": "5.0.0-dev.292",
    "@mikro-orm/reflection": "5.0.0-dev.292",
    "dotenv": "^10.0.0",
    "next": "11.1.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "ts-node": "^10.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.15.0",
    "@babel/plugin-proposal-class-properties": "^7.14.5",
    "@babel/plugin-proposal-decorators": "^7.14.5",
    "@mikro-orm/seeder": "5.0.0-dev.292",
    "@types/react": "17.0.19",
    "babel-plugin-transform-typescript-metadata": "^0.3.2",
    "eslint": "7.32.0",
    "eslint-config-next": "11.1.0",
    "typescript": "4.3.5"
  },
  "mikro-orm": {
    "useTsNode": true,
    "tsConfigPath": "./tsconfig.orm.json",
    "configPaths": [
      "./lib/db/mikro-orm.config.ts"
    ]
  }
}
```

**Comment by Langstra** [comment]
Will look into this. Any possibility you could create a failing test case or reproduction repo?
