### ISSUE TITLE
 PostgreSqlPlatform does not support Migrator

### ISSUE THREAD

**Issue by jasonwilson** [mikro-orm/mikro-orm#1847]
**Describe the bug**
After upgrading to mikro-orm 4.5.5 we're seeing failures in our test code around migrator not being supported. Did something change in this release?

**Stack trace**
```
    PostgreSqlPlatform does not support Migrator

       7 |   let g = db.getSchemaGenerator()
       8 |   await g.dropSchema(false, true)
    >  9 |   const m = db.getMigrator()
         |                       ^
      10 |   await m.up()
      11 |


      at PostgreSqlPlatform.getMigrator (../node_modules/@mikro-orm/core/platforms/Platform.js:153:15)
      at MikroORM.getMigrator (../node_modules/@mikro-orm/core/MikroORM.js:105:42)
      ...
```

**To Reproduce**
Invoke `getMigrator` on a postgres instance

**Expected behavior**
getMigrator should be supported with postgres.

**Additional context**
Upgraded from 4.5.5-dev.1 to 4.5.5

**Versions**
4.5.5

**Comment by B4nan** [comment]
The method is there, this sounds more like some dependency resolution issue. How does your `package.json` look like? Make sure you have all the package versions aligned (e.g. core package is on the exact same version as driver package).

Or provide full repro.
