### ISSUE TITLE
Add an option to toJson to "depopulate" entities

### ISSUE THREAD

**Issue by standup75** [mikro-orm/mikro-orm#1861]
**Is your feature request related to a problem? Please describe.**
Returning entities with populated relationship can lead to heavy payloads

**Describe the solution you'd like**
I would like `toJson` to have an option like `{ keepRelationship: boolean }`, defaults to true.

**Describe alternatives you've considered**
Overloading toJson is the obvious alternative

**Comment by B4nan** [comment]
You should implement custom `toJSON` if you want custom behaviour, it is an extension point. Also you can mark entities as not populated via `wrap(book.author).populated(false)`.

Btw all what `toJSON` does is to call `toObject`, so if we wanna add some flags, it would go there and you would still need to implement your own `toJSON` method. You are in control of the parameters for `toJSON`. Regarding the name, I'd rather go with `simple: true` in this case, having boolean toggles that default to `true` makes the API less understandable (I've been there).

**Comment by standup75** [comment]
awesome, thank you
