### ISSUE TITLE
Find with $lte: new Date() is wrongfully parsed into (Postgre) SQL query

### ISSUE THREAD

**Issue by woltob** [mikro-orm/mikro-orm#1862]
**Describe the bug**

How can this query 
```
this.em.clear()
const availabilities = await this.em.find(
      Availability,
      {
        user: user,
        startTime: {
          $lte: new Date(),
        },
      },
      ['user'],
      {
        startTime: 'ASC',
      },
    );
```
be translated to 

```
select \"e0\".* from \"user\" as \"e0\" where \"e0\".\"deleted_at\" is null and \"e0\".\"id\" in ('576e3ef8-7d91-4c35-92d6-d64045d3c568') and 0 = '5' and 1 = '7' and 2 = '6' and 3 = 'e' and 4 = '3' and 5 = 'e' and 6 = 'f' and 7 = '8' and 8 = '-' and 9 = '7' and 10 = 'd' and 11 = '9' and 12 = '1' and 13 = '-' and 14 = '4' and 15 = 'c' and 16 = '3' and 17 = '5' and 18 = '-' and 19 = '9' and 20 = '2' and 21 = 'd' and 22 = '6' and 23 = '-' and 24 = 'd' and 25 = '6' and 26 = '4' and 27 = '0' and 28 = '4' and 29 = '5' and 30 = 'd' and 31 = '3' and 32 = 'c' and 33 = '5' and 34 = '6' and 35 = '8' order by \"e0\".\"id\" asc - invalid input syntax for type integer: \"e\"",
```

where startTime is of type DateTime in PostgreSQL. 

Happy to provide more info if needed.

Weirdly, this.em gives me the following function declaration:

```
EntityManager<PostgreSqlDriver>.find<Availability, "user"[]>(entityName: EntityName<Availability>, where: FilterQuery<Availability>, populate?: "user"[] | undefined, orderBy?: QueryOrderMap | undefined, limit?: number | undefined, offset?: number | undefined): Promise<...> (+1 overload)
```

where I don't know where "user"[] comes from.

this.em is defined via

```
@Injectable()
export class AvailabilityService extends BaseService {
  constructor(
    @Inject(forwardRef(() => DeviceLogService))
    private readonly deviceLogService: DeviceLogService,
    protected readonly entityManager: SqlEntityManager<PostgreSqlDriver>,
  ) {
    super(entityManager);
  }

...
```

whereas BaseService has the following structure (as I still don't know how to get a clean per-request entity manager with GraphQL using NestJS and MikroORM / could not find it):

```
import {
  EntityManager,
  PostgreSqlDriver,
  SqlEntityManager,
} from '@mikro-orm/postgresql';

export class BaseService {
  protected em: SqlEntityManager<PostgreSqlDriver>;

  constructor(
    protected readonly entityManager: EntityManager<PostgreSqlDriver>,
  ) {
    this.em = this.entityManager
      .getContext()
      .fork(true, true) as EntityManager<PostgreSqlDriver>;
  }
}
```

**Stack trace**
```
...
```

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | v14.15.5 |
| typescript | ^4.2.3 |
| mikro-orm | ^4.5.5 |
| your-driver | postgresql |

**Comment by woltob** [comment]
Removing ['user'] and putting [] for populate produces a valid query:

```const availabilityRepository = this.em.getRepository<Availability>(
      Availability,
    );
    const availabilities = await availabilityRepository.find(
      {
        user: user,
      },
      []
      {
        startTime: 'ASC',
      },
    );
```

**Comment by B4nan** [comment]
> How can this query...

How can you file a bug report with so many information, but without the most important bit - the entity definition? :] It does not really matter what the column type in the database is, the query is computed based on metadata = entity definition. 

We will need something reproducible, obviously there are tests for using operators with date properties, including postgres. 

Ideally try to create a failing test case like in https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues

Btw it also looks like you are using some filters (for soft deletes)? That might be also important here. As mentioned, providing failing test case would be more than welcome, as that way you will be kinda forced to find all the parts needed to make it fail like this. It is definitely not just about using operators with dates, there are many tests for that. 

> Removing ['user'] and putting [] for populate produces a valid query:

Well, your query that fails is for populating user entity, if you don't populate it, it won't be there.

**Comment by B4nan** [comment]
Still waiting for the repro, or at least the entity definitions.

**Comment by woltob** [comment]
I solved it. Does not seem to be a bug. My bad, apologies. Please close. 
I guess I was confusing EntityRepository queries with EntityManager queries.

**Comment by B4nan** [comment]
Ok good, would be good to let others know what exactly was the culprit, for future readers.
