### ISSUE TITLE
Allow providing custom Logger implementation

### ISSUE THREAD

**Issue by jahudka** [mikro-orm/mikro-orm#1863]
MikroORM provides only a basic logging facility allowing the user to specify a single callback which can be used to redirect logging output elsewhere than `stdout`. It would be amazing if we could either get a little bit more info about what is being logged (whether it's an SQL query, an error or a generic message) or provide a custom implementation of the `Logger` class to allow more advanced things to be done.

I'm the developer of [`debugr`](https://github.com/cdn77/debugr), which is an attempt at having something akin to Tracy in a NodeJS context. One of the key issues I have with logging in NodeJS is that if my app is in debug mode the log usually contains a _lot_ of stuff from various asynchronous jobs which run in parallel, so it's hard to find which messages correlate to which job. Debugr was designed to help remedy this. Leveraging the `async_hooks` API (which I only found out about now, thanks to your library, much obliged!) would allow me to log all queries that happen during the execution of, say, a given HTTP request handler, without having them interleaved with queries from concurrent requests. I know I can do this with the existing implementation, but it would be nice if I could differentiate between "log levels" of various messages and for example provide my own custom serialization mechanism for query parameters - this would allow for a more tight integration with Debugr.

If support for something like this is added I will create a `@debugr/mikro-orm` package so that everybody can benefit. And if there's anything I can do to help make it happen on your end, lay it on me! :-)

Thanks for all your amazing work, MikroORM is truly a marvel!

**Comment by B4nan** [comment]
Sure, if you have something more concrete in your mind, feel free to send a PR :]

Do you think it is enough to allow passing custom `Logger` class, or do we need something more? I'd probably use the current one as a base, so users don't need to implement things like `isEnabled` themselves.

**Comment by jahudka** [comment]
Well, the way I see it, the current Logger implementation is what I'd mostly consider a logger _writer_ - it only writes the log messages to a defined output, but parts of the logging logic are implemented in various other places, which means that while it would certainly improve matters if we could override the Logger class itself (and this should be pretty easy to do), it would be even more useful if at least some of the logic surrounding logging was refactored to also happen inside it.

For example logging in MikroORM now makes use of `ansi-colors` to make log messages more readable in terminal; but if I want to log to some other destination than `stdout` (or a file that I later intend to read in a terminal) I need to strip the ANSI escape codes to get back at the raw string. I think this should be a part of the logger itself as that would allow me to override it.

Another thing is query parameters - replacing of placeholders in queries for logging purposes now happens outside the logger (if I'm reading things correctly it's in `packages/knex/src/AbstractSqlConnection.ts`), which means that even if I replace the logger implementation I still can't log the raw query with placeholders and log the actual parameter values separately, and it also means that the "outside world" needs access to the `isEnabled(namespace)` method of the logger class to check whether parameter expansion in the log message should be done - I think delegating this to the logger itself would also add more flexibility.

I'll try to come up with something that makes sense and submit a PR in the following week. I don't know your plans for MikoORM internals and I know I'm biased towards making the logging facilities compatible with my library in particular, so please do feel free to steer me in the right direction from your viewpoint ;-)
