### ISSUE TITLE
Support getters in EntitySchema property types

### ISSUE THREAD

**Issue by charliecochran** [mikro-orm/mikro-orm#1867]
**Describe the bug**
When defining properties with getters using EntitySchema, TypeScript complains that `'getter' does not exist in type`.

**To Reproduce**

```ts
import { EntitySchema } from '@mikro-orm/core';

class User {
  id!: number;
  firstName!: string;
  lastName!: string;
  get fullName(): string {
    return `${this.firstName} ${this.lastName}`;
  }
}

const schema = new EntitySchema<User>({
  class: User,
  properties: {
    id: { type: 'number', primary: true },
    firstName: { type: 'string' },
    lastName: { type: 'string' },
    fullName: { type: 'method', persist: false, getter: true },
    /* Type '{ type: string; persist: false; getter: true; }' is not assignable to type 'Property<string, User>'.
     * Object literal may only specify known properties, and 'getter' does not exist in type 'Property<string, User>'.ts(2322)
     */
  },
});

```

**Expected behavior**
Getters should be supported without needing to use decorators.

**Additional context**
The getter functions as expected if I add this type assertion to the `fullName` property definition: `as EntityProperty<User>`. I think the root cause is that [EntitySchema's `Property` type](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/metadata/EntitySchema.ts#L14) is based on [`PropertyOptions` from decorator](https://github.com/mikro-orm/mikro-orm/blob/2521b8c14655f29e350d4dedcddf1b8f8148e160/packages/core/src/decorators/Property.ts#L37) which doesn't expose inferrable options like `getter`.

**Versions**

| Dependency | Version |
| - | - |
| node | 14.16.1 |
| typescript | 4.1.5 |
| mikro-orm | 4.5.4 |
| your-driver | n/a |

**Comment by B4nan** [comment]
`4.5.6-dev.6`
