### ISSUE TITLE
Unable to disable cascade persist. `cascade: []` has no effect.

### ISSUE THREAD

**Issue by chrisbrantley** [mikro-orm/mikro-orm#1870]
**Describe the bug**
I am trying to disable cascade persist as it is causing problems in testing with our fixtures and is not needed except in very specific situations.

I have my relationships defined like this:

```
@Entity()
export class FileUpload {

  @ManyToOne({ entity: "Org", nullable: true, onDelete: "cascade", cascade: [] })
  org?: Org;

}
```

However, when creating a new FileUpload object if the org entity is not managed (not in the identity map) it will try to persist it every time, even though the org entity has a pk and `org.isInitialized()` is `true`. 

This results in a database exception because the entity already exists in the database. If the entity is in the identity map it all works fine. It's only when we're running tests using our fixtures that we run into this problem. Fixtures are imported into the database in a separate context, so they do not exist in the IdentityMap that the test has access to.

We can get around this by passing an Identified Reference rather than the actual Org Entity. But that makes our tests brittle because it is expected that a full Org entity be passed.

I really just want to disable cascade persist as it's not something we need (except in specific cases) so we'd prefer to opt in to it... but right now I can't even seem to opt out!

**Versions**
| Dependecy | Version |
| --- | --- |
| node | 14.15.4 |
| typescript | 4.0.2 |
| mikro-orm | 4.5.0 |
| @mikro-orm/postgresql | 4.5.0 |

**Comment by B4nan** [comment]
> However, when creating a new FileUpload object if the org entity is not managed (not in the identity map) it will try to persist it every time, even though the org entity has a pk and org.isInitialized() is true.

New entities are always cascaded, this is on purpose, it is called persistence by reachability. It does not matter that you have it in initialized state (that is the default for new entities too), neither that it has a PK (as that does not necessarily mean it is present in the database). If it's not in identity map, it is always considered as new entity. 

So the real question is why are you putting there a detached entity instance instead of managed one?

**Comment by chrisbrantley** [comment]
We have a process that loads our fixtures into the database before tests run. This initializes the database to a known state. The tests themselves have access to the fixture entities by name. So, if I want to test creating an invoice (contrived example) but the invoice needs to be associated with a customer I can use "customerB" from the fixtures module in that relationship. I can trust that customerB is in the database because it was inserted previously. But it will be "detached" as it was not fetched from the database. We could call `findOne` for every fixture within the tests, but that would make tests much more verbose and has a performance impact.

So we've tried to solve this in many ways... none of which seem to work. One thought was that we could disable cascade persist. That clearly won't work based on your explanation, which makes sense.

The next thought was "Can we inject these entities into the identity map, so they are no longer detached, WITHOUT executing a database query?". I thought that's what `EntityManager.merge()` did. But calling `em.merge(detachedEntity)` doesn't seem to have any effect. It's possible that EntityManager instance that ends up calling `flush()` is not the same instance I'm calling `merge()` on, but it's hard to tell.

What we have done in some instances is pass a reference rather than the entity itself. This prevents the cascade persist, but now we're no longer sending the full entity which makes tests brittle.

Again, I want to make clear that this is only an issue with running our test cases. Normal production operation works fine because we're never working with detached entities. However, having a high-quality test suite is important so we're trying to strike the right balance between developer ergonomics, verbosity, and performance in our tests. My hope is there is just some fundamental aspect of the ORM that needs to "click" so I can solve this problem for us.

**Comment by chrisbrantley** [comment]
@B4nan turning these detached entities into references via `Em.getReference()` solves the cascade persist problem but obviously any code that relies on the full entity will now break. Is there a way to say "I know what I'm doing. Please treat this entity like a reference and don't try to persist it"?

I was hoping this is what `Entity.toReference()` does but it clearly doesn't.

**Comment by chrisbrantley** [comment]
Okay after diving deeper into this I think that `EntityManager.merge()` is my solution and it actually works as advertised. The cases where I thought it had no effect were because someone was forking the EM somewhere in the stack. This was just us not understanding how things worked. I cleaned that up to ensure our test code used the same EntityMap instance and calling `merge()` on the fixture entities had the desired effect I was looking for, e.i. "I know what I'm doing, treat this entity as managed".

Thank you for your patience. :)
