### ISSUE TITLE
Setting One-To-One relation from inverse side has no effect

### ISSUE THREAD

**Issue by visurel** [mikro-orm/mikro-orm#1872]
**Describe the bug**
When setting `undefined` from the inverse side of a One-To-One relation, the value is not persisted. The operation does not generate a SQL line and therefore does not persist the change.

Example:
```typescript
@OneToOne(() => Book, book => book.favoritedByAuthor, { owner: true, wrappedReference: true, nullable: true })
  favouriteBook?: IdentifiedReference<Book>;
```

```typescript
@OneToOne(() => Author, author => author.favouriteBook, { wrappedReference: true, nullable: true })
  favoritedByAuthor?: IdentifiedReference<Author>;
```

```typescript
    /** Preparation */
    const insertAuthor = new Author('Author 1', 'test@example.org');
    await this.orm.em.persistAndFlush(insertAuthor);

    const insertAuthor2 = new Author('Author 2', 'test@example.org');
    await this.orm.em.persistAndFlush(insertAuthor2);

    const insertBook = new Book('Book 1', insertAuthor);
    await this.orm.em.persistAndFlush(insertBook);

    const insertBook2 = new Book('Book 2', insertAuthor);
    await this.orm.em.persistAndFlush(insertBook2);

    /** Here it all starts */
    const author1 = await this.orm.em.findOneOrFail(Author, { name: 'Author 1' });
    const author2 = await this.orm.em.findOneOrFail(Author, { name: 'Author 2' });

    author1.favouriteBook = wrap(insertBook).toReference();
    await this.orm.em.flush();

    insertBook.favoritedByAuthor = undefined; // THIS IS THE RELEVANT LINE
    await this.orm.em.flush();
```
In this case `Author 1` will still keep `favourite_book_id` set to the ID of `insertBook` even though we set it to undefined.

**To Reproduce**
Example above or here is also a reproduction repo (you will need to start the docker-compose.yml and run the Migrations):
https://github.com/visurel/nestjs-example-app/commit/4d47ca2600d161e81b50e90ff7871ec80bf387c3

**Expected behavior**
The value should be set and the `favourite_book_id` should be set to `null`.

**Additional context**
I have also tried setting it to `null` instead of `undefined` with the same result.
Setting `propagateToOneOwner` to `true` also had no difference.

**Versions**

| Dependency | Version |
| - | - |
| node | 14.16.0 |
| typescript | ^3.9.7 and ~4.0.5  |
| mikro-orm | 4.5.5 |
| postgresql | 12.4 |

**Comment by B4nan** [comment]
`4.5.6-dev.6`
