### ISSUE TITLE
There isn't a way to execute raw/native SQL with Repositories

### ISSUE THREAD

**Issue by grimurd** [mikro-orm/mikro-orm#1874]
I'm using the NestJS module and I have a SQL query that is complicated enough that it isn't possible to create it using Knex or the query builder but there is no way to perform raw/native SQL queries on a Entity Repository.

An alternative way is to use the execute() method on the Entity Manager. However using the Entity Manager without request context causes lifecycle errors to be thrown (because the entity manager isn't supposed to be reused). Unfortunately using request context Isn't possible for me.

There are two solutions that I can see.

1. Make the em property on the repositories public instead of protected or add a method to get the entity manager instance
2. Add a execute or raw sql method to the repositories

EDIT: The lifecycle errors I mentioned seem to be caused by something else, must investigate that fruther.

**Comment by B4nan** [comment]
> However using the Entity Manager without request context causes lifecycle errors to be thrown (because the entity manager isn't supposed to be reused).

What you mean by that? How come you have "contextual" repositories but not EM? 

> Unfortunately using request context Isn't possible for me.

Why?

**Comment by grimurd** [comment]
I misunderstood the request context and was able to make this work with UseRequestContext decorator and with the entity manager.
