### ISSUE TITLE
Generate entities docs example doesn't work

### ISSUE THREAD

**Issue by vjpr** [mikro-orm/mikro-orm#1880]
https://mikro-orm.io/docs/entity-generator/

```
import { MikroORM } from '@mikro-orm/core';

(async () => {
  const orm = await MikroORM.init({
    dbName: 'your-db-name',
    // ...
  });
  const generator = orm.getEntityGenerator();
  const dump = await generator.generate({ 
    save: true,
    baseDir: process.cwd() + '/my-entities',
  });
  console.log(dump);
  await orm.close(true);
})();
```

Need to add this config or it complains that no entities were found...

```
    discovery: {
      warnWhenNoEntities: false, // by default, discovery throws when no entity is processed
      requireEntitiesArray: true, // force usage of class refrences in `entities` instead of paths
      alwaysAnalyseProperties: false, // do not analyse properties when not needed (with ts-morph)
    },
```

**Comment by Langstra** [comment]
Could you create a PR with a fix for this?

**Comment by B4nan** [comment]
> Need to add this config or it complains that no entities were found...

Only thing from that you need to use is `warnWhenNoEntities`, the rest is not related at all. 

And nope, we can't just toggle its default value. The validation is disabled automatically if you use the CLI, but here, there is no way how to disable it conditionally, we could only get rid of it, which is a no go for me, as it really has a value.
