### ISSUE TITLE
Custom Types: getColumnType is ignored if used with an constructor in @Property annotation

### ISSUE THREAD

**Issue by co-sic** [mikro-orm/mikro-orm#1896]
**Describe the bug**
The `getColumnType` function of my custom type is not called during schema/migration creation if i use the custom type with a constructor in the `@Property` annotation like this `@Property({ type: new CustomType() })` as described in the [docs](https://mikro-orm.io/docs/custom-types/#arraytype). With a postgres DB it falls back to `jsonb` type.

If i use the custom type without an constructor like this `@Property({ type: CustomType })` it works correctly and my supplied type is used.

**To Reproduce**
1. Create a custom type extending the `Type` class and implement the `getColumnType` function returning some db type string.
2. Create an Entity using the custom type via the `@Property` annotation like this `@Property({ type: new CustomType() })`.
3. With a postgres DB running, run `npx mikro-orm migration:create` and inspect the resulting migration file.

**Expected behavior**
It should call the `getColumnType` function during schema/migration creation.

**Versions**

| Dependency | Version |
| - | - |
| node | 14.16 |
| typescript | 4.2.4 |
| mikro-orm | 4.5.5 |
| mikro-orm/postgresql | 4.5.5 |

**Comment by B4nan** [comment]
If you want to pass an instance, you need to use `customType`:

```ts
@Property({ customType: new CustomType() })
```

**Comment by co-sic** [comment]
Thanks for the quick reply, it works now :+1:  But maybe it would be nice to add some documentation about this? The `customType` property could be described in the [Decorator Docs](https://mikro-orm.io/docs/decorators/#property) and adding an example of this usage to the [custom types doc](https://mikro-orm.io/docs/custom-types/) would be nice. Especially since there is the example of the ArrayType with a constructor, but it works with the `type` instead of `customType` attribute.

Additionaly i just saw that the type of `customType` is `Type<any>` maybe it should includ `Constructor<Type<any>>` as it is done in the `type` property.

**Comment by B4nan** [comment]
> Additionaly i just saw that the type of customType is Type<any> maybe it should includ Constructor<Type<any>> as it is done in the type property.

Nope, it's correct now, `Type` means an instance, `Constructor<Type>` means the class.

Agreed this is not fully documented, will try to do something about that.
