### ISSUE TITLE
Double / Float columns not generated via Migrations (PostgreSQL)

### ISSUE THREAD

**Issue by woltob** [mikro-orm/mikro-orm#1901]
For the following code and both properties, only integer columns are created via migrations for Postgres.
@Field is a Apollo Graphql Annotation that does not interfere usually.

`
  @Property({ type: Number, nullable: false })
  @Field((_type) => Number)
  latitude: number;

  @Property({ nullable: false })
  @Field((_type) => Number)
  longitude: number;
`

How can I force them to be Double / Float values. number in Typescript is a float value but can mean both integer and double. How is Mikro ORM understanding the exact type without having me specify a custom type.

I am only seeing this now and it's a big problem that needs to be solved quickly.
After extensive googeling the only solution I could find was custom types.

Thank you very much.

**Comment by B4nan** [comment]
Default for number type is to map to integer, you can specify either `type` or `columnType`, the difference being that the `columnType` is always used as is, but the `type` is mapped (checked for known type names and converted). 

```ts
// with columnType we need to use the final type name
@Property({ columnType: 'double precision' )
prop1: number;

// with type we can also use known mapped types
@Property({ type: 'double' )
prop2: number;
```

The difference here might not be that visible, so better example to show it is with JSON properties:

```ts
@Property({ columnType: 'jsonb' )
prop1: any;

@Property({ type: 'object' )
prop2: any;
```

Both props will have `jsonb` column type in postgres.

**Comment by woltob** [comment]
❤️  thanks for the quick reply, works like charm. Would be cool to find it in the documentation for other people to find it.
