### ISSUE TITLE
JOINED loading strategy seems to fail in some cases

### ISSUE THREAD

**Issue by pphunor72** [mikro-orm/mikro-orm#1902]
I have the following user-tenant entity:
```
export enum UserRole {
	ADMIN = 'admin',
	USER = 'user'
}

@Entity({ tableName: 'public.pgo_user_tenant' })
@Filter({ name: 'byUser', cond: args => ({ user: { id: args.id } }) })
@Filter({ name: 'byTenant', cond: args => ({ tenant: { id: args.id } }) })
export class UserTenantEntity {

	@ManyToOne({ primary: true, entity: () => UserEntity, fieldName: 'userId', cascade: [] })
	user!: UserEntity;

	@ManyToOne({ primary: true, entity: () => TenantEntity, fieldName: 'tenantId', cascade: [] })
	tenant!: TenantEntity;

	[PrimaryKeyType]: [number, number];

	@Property({ fieldName: 'isActive' })
	isActive: boolean = true;

	@Enum({ items: () => UserRole, default: UserRole.USER })
	role!: UserRole; // string enum
}

```
Querying this entity does not work properly with joined loading strategy. In my database there are two records with the same user id (1) but different tenant ids (1 and 2). Running the query below works fine, both records are returned:
```
userTenantRepository.findAll({
			filters: {
				byUser: { id: 1 }
			},
			populate: {
				tenant: true
			},
			//strategy: LoadStrategy.JOINED
		}
```
If I uncomment the loading strategy entry above then only the first record is returned. The same happens if I set the loading strategy within @ManyToOne decorator.
It is worth noting that even in these cases the SQL statement returns both two records, the issue is somewhere around mapJoinedProps (see @mikro-orm/knex/AbstractSqlDriver.js), because getCompositeKeyHash utility does not recognize the embedded tenant object as entity and the generated hash is

> 1~~~[Object object]

for both two records (1 is the user id).
Do I failed to add some property somewhere or is this really a buggy behavior?

**Versions**

| Dependency | Version |
| - | - |
| node | 14 |
| typescript | yes |
| mikro-orm | 4.5.5 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
Could you please provide a failing test case like in https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues?

**Comment by pphunor72** [comment]
Sure, here you are:
[GH1902.test.ts.zip](https://github.com/mikro-orm/mikro-orm/files/6598069/GH1902.test.ts.zip)

**Comment by B4nan** [comment]
`4.5.6-dev.11`
