### ISSUE TITLE
AsyncLocalStorage integration possibly not working..?

### ISSUE THREAD

**Issue by jahudka** [mikro-orm/mikro-orm#1907]
I'm having an issue using AsyncLocalStorage with Mikro. I have a relatively involved custom DI implementation in my app, but basically what it does can in this context be boiled down to what is shown in [MikroORM docs](https://mikro-orm.io/docs/async-local-storage) - there is a global MikroORM connection and entity manager and there is logic which forks the entity manager for each request and stores the forked EM in the appropriate ALS store.

It seems to work as expected in the HTTP server part of the application, but there are also a couple of background jobs that need to get notified when stuff happens in one of the HTTP endpoints and do some work, and these also need access to the EM. I've done everything I can think of to isolate these jobs from the async thread of execution of the HTTP endpoint handlers (there is now no direct call chain linking the two) _and_ they're themselves supposed to run in their own ALS context with a forked EM. If I try hacking around stuff like `em.getContext().foobar = 1;` in the request handler and then `console.log(em.getContext().foobar)` in the background job I see `undefined` in the console. Yet still the background job fails with the following error:

```
(node:17650) UnhandledPromiseRejectionWarning: DriverException: Transaction query already complete, run with DEBUG=knex:tx for more info
    at PostgreSqlExceptionConverter.convertException ($PROJECT/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
    at PostgreSqlExceptionConverter.convertException ($PROJECT/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:40:22)
    at PostgreSqlDriver.convertException ($PROJECT/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:194:54)
    at $PROJECT/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:198:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async PostgreSqlDriver.nativeUpdate ($PROJECT/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:241:19)
    at async ChangeSetPersister.persistManagedEntity ($PROJECT/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:96:21)
    at async ChangeSetPersister.executeUpdates ($PROJECT/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:34:13)
    at async UnitOfWork.commitUpdateChangeSets ($PROJECT/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:526:9)
    at async UnitOfWork.persistToDatabase ($PROJECT/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:462:13)

previous Error: Transaction query already complete, run with DEBUG=knex:tx for more info
    at completedError ($PROJECT/node_modules/knex/lib/transaction.js:358:9)
    at $PROJECT/node_modules/knex/lib/transaction.js:324:24
    at new Promise (<anonymous>)
    at Client_PG.trxClient.query ($PROJECT/node_modules/knex/lib/transaction.js:320:12)
    at Runner.query ($PROJECT/node_modules/knex/lib/runner.js:151:36)
    at $PROJECT/node_modules/knex/lib/runner.js:40:23
    at $PROJECT/node_modules/knex/lib/runner.js:277:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async PostgreSqlConnection.executeQuery ($PROJECT/node_modules/@mikro-orm/core/connections/Connection.js:56:25)
    at async PostgreSqlConnection.execute ($PROJECT/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:105:21)
```

Interestingly it doesn't fail on the first query executed within the job - it fails on the first DML query (an update to be precise). There is a couple of `SELECT`s before which seem to run without issue. The `UPDATE` query itself runs just fine when I run it manually. `DEBUG=knex:*` tells me that there was an `error running transaction query`, but this is apparently already caused by the "transaction query already complete" issue if I'm reading Knex code right.

I know this is more likely a bug in my own code rather than MikroORM, but I've tried everything, been sitting on this the whole day and I got nowhere. Is there something obvious about ALS and / or the way MikroORM integrates with it that I'm missing? 🙏

**Comment by B4nan** [comment]
Are you on latest? I was fixing one issue (#1824) that resulted in the same error, fix is already released as `4.5.6`. I don't think it has to be caused by bad context.

Can't help more without seeing it in action. The integration of ALS is deadly simple, run code in the handler, get the fork from the store, there is not much that could break.

**Comment by jahudka** [comment]
Thanks for the suggestion, I wasn't, but I am now and although the scenario looks almost exactly the same (I was also using the `afterFlush` event, forgot to mention that) the issue persists. I'll try to put together a simple self-contained reproduction, might help me narrow it down to where I can actually tell exactly what's happening and whether it's my code or it might actually be a bug..

**Comment by jahudka** [comment]
Wow, you'll _never_ in a million years guess what caused the issue..

I've been trying to integrate with a custom logger. In the `logger()` callback passed to Mikro I had a simple bit of logic to check for `[query]` messages, strip off the ANSI escape sequeces from them and parse them into `query` and `time` with a simple regexp. These I then passed to the logger as an object with the `query` and `time` keys. The logger saw an object instead of a string and so dumped it using the `dump` function from `js-yaml`; then wrote it to the console using regular `console.log()`.

Some queries didn't have `time` for some reason, and so the property was `undefined` in the object passed to the logger. By default `js-yaml` outputs a very verbose YAML tag for `undefined` values, and this did not look pleasing to my eye, so I tried solving it by setting the `schema` option of the `dump` function to `JSON_SCHEMA` as exported from `js-yaml`... and that caused the error.

Simply put, within synchronous code running inside the `logger()` callback, this works:

```typescript
console.log(dump(someObject));
```

while this doesn't:

```typescript
console.log(dump(someObject, { schema: JSON_SCHEMA }));
```

`someObject` isn't anything fancy, it's a plain object with two properties - `query` (string) and `time` (number or undefined).

And the reason for this I think is that the AsyncLocalStorage instance that's being used in the background somehow loses track of the async thread of execution because of something the `JSON_SCHEMA` option does, and so when the next query is run, there is no entity manager in the ALS anymore.. so the global EM is used and that breaks things.

Interestingly I can't seem to reproduce this outside my application.. but all I need to change in my application to make it work or not work is that one seemingly absolutely irrelevant option used in a context far away from the EM, the ALS instance or the DIC. I give up 😂

**Comment by kenspirit** [comment]
@jahudka Curiously on how you find this out.  Recently I went into the same issue of "Transaction query already complete, run with DEBUG=knex:tx for more info" but I cannot figure out where the context/transaction got mixed up.  :(

**Comment by jahudka** [comment]
@kenspirit well, I went through the call chain manually from the top and added lots of `console.log()` calls, both in my code and in installed `node_modules`.. it was a pain.

**Comment by kenspirit** [comment]
@jahudka Got it, thanks.  I can feel it and admire your patience. 👍
