### ISSUE TITLE
Nested transactions do not work as expected

### ISSUE THREAD

**Issue by aniketbhatnagar** [mikro-orm/mikro-orm#1910]
**Describe the bug**
It seems like nested transactions don't work as your work expect. For example, if there is a parent transaction that creates child transactions, the parent transaction rollback affects child transactions

**Stack trace**
No error but child transactions rollback too it seems

**To Reproduce**
https://github.com/mikro-orm/mikro-orm/pull/1911

**Expected behavior**
There should be a way to spawn a transaction independent of current transaction. Committing / rolling back of existing transaction should not affect other created transactions within that transaction

**Versions**
latest

**Comment by B4nan** [comment]
Why are you opening an issue when you do not have the repro yet? 

What you say seems like correct behaviour, parent transaction rollback should indeed cause rollback of the whole transaction, including all of its children.

**Comment by aniketbhatnagar** [comment]
> Why are you opening an issue when you do not have the repro yet?
> 
> What you say seems like correct behaviour, parent transaction rollback should indeed cause rollback of the whole transaction, including all of its children.

Sorry, I was trying to get GH number to put in the test file name. Here is the test - https://github.com/mikro-orm/mikro-orm/pull/1911. I am not sure why why users cannot control if they want nested transaction to be rolled back or not. In most transaction management frameworks, it is possible to spawn a transaction independent of current transaction like https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/annotation/Propagation.html#REQUIRES_NEW

**Comment by aniketbhatnagar** [comment]
Ruby on rails has similar feature too with `requires_new: true` to allow nested/child transaction to be independent on parent - https://api.rubyonrails.org/v6.1.3.2/classes/ActiveRecord/Transactions/ClassMethods.html

**Comment by B4nan** [comment]
Well, but that does not mean that a child tx rollback should not rollback the parent one by default, I am not aware of any ORM that would not behave this way.

Linking spring docs seems unrelated, this is ORM, so maybe try to compare it to hibernate instead. 

I really don't understand why are you using the top level transaction if you don't want this behaviour (and even weirder is why are you calling this as unexpected behaviour).

**Comment by B4nan** [comment]
In sqlite this cannot work as you can have only one connection to the database (pool size is 1, so you can't have parallel transaction contexts, nothing I can help with), but with other drivers, you should be able to just use the root EM or create a new fork (forks do not bare the transaction context):

```ts
    const root = orm.em.fork();

    const [id1, id2, id3, id4] = await root.transactional(async em => {
      await createA(em, 1);

      // either fork manually
      await em.fork().transactional(async em => {
        await createA(em, 2);
      });

      // or use the root EM
      await root.transactional(async em => {
        await createA(em, 3);
        await em.rollback();
      });

      await root.transactional(async em => {
        await createA(em, 4);
      });

      await em.rollback();

      return [1, 2, 3, 4];
    });
```

But that itself is still not working due to one issue in the `TransactionContext` class.

**Comment by aniketbhatnagar** [comment]
Thanks for acknowledging this :-)

**Comment by B4nan** [comment]
It should be indeed possible, but again, not with sqlite due to the single connection pool, and not like you tried to reproduce it.

**Comment by aniketbhatnagar** [comment]
Ya, using local em to spawn transactions wasn't intended. I actually ran into this using a global em but in an effort to prepare something reproducible, I accidentally used local em. I have updated the test now.

Regarding sqlite, it should be possible to use an in-memory DB that can have multiple connections as per https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/in-memory-databases#shareable-in-memory-databases. I have updated the test to use that as well.

**Comment by B4nan** [comment]
This is not dotnet, not sure what makes you think you can use dotnet docs when working with nodejs 🤷 Looking at the node's sqlite adapter, it [should be probably possible](https://github.com/mapbox/node-sqlite3/blob/593c9d498be2510d286349134537e3bf89401c4a/test/open_close.test.js#L58), but might as well not be possible via knex (which is the way MikroORM integrates sqlite). There is some kind of support, tried it locally but it still does not work as the table is locked:

```ts
Error: insert into `a` (`id`, `name`) values (2, 'my name is a') - SQLITE_BUSY: database is locked
```

**Comment by aniketbhatnagar** [comment]
I thought connection strings were similar cross platform or at the very least, one platform supporting the feature means its doable. Anyways, not sure why you have been initially assuming that sqlite doesn't support this and now think that its not possible with knex. Knex's documentation has an example :
```
const knex = require('knex')({
  client: 'sqlite3',
  connection: {
    filename: "file:memDb1?mode=memory&cache=shared"
    flags: ['OPEN_URI', 'OPEN_SHAREDCACHE']
  }
});
```

I hacked the SqliteConnection to do as documented @ https://github.com/mikro-orm/mikro-orm/pull/1911/files#diff-bf85fd1bf18900793ab6e5d372068109044692d8848ba54a00dd75c3ce96e947R35 and it works locally for me. Without the `flags`, it still works but doesn't create in-memory DB.

**Comment by B4nan** [comment]
Yes, that is exactly what I already tried and it produces the error I mentioned above (table is locked).

**Comment by aniketbhatnagar** [comment]
I debugged the issue with transaction context a little bit, and it seems like https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/utils/TransactionContext.ts#L17 causes nested transaction to not be independent of parent but I am not sure if removing that makes sense.

**Comment by B4nan** [comment]
Yes, I have it fixed already, but it breaks other tests, and havent had the time to fix them just yet.

**Comment by aniketbhatnagar** [comment]
oh ok.. thanks a ton, let me know if you need any help!

**Comment by B4nan** [comment]
As mentioned, this still won't work with sqlite. idk if its technically possible, but if it is, the problem is in knex or in its dependencies (maybe in node-sqlite3 itself). You can try to change the test I added to use sqlite to see how it behaves:

```ts
    orm = await MikroORM.init({
      entities: [A],
      dbName: 'file:memDb1?mode=memory&cache=shared',
      type: 'sqlite',
      pool: {
        min: 1,
        max: 10,
      },
	  driverOptions: {
		connection: {
		  flags: ['OPEN_URI', 'OPEN_SHAREDCACHE'],
		},
      },
      debug: true,
    });
```

This will end up with the locked table error I mentioned above. You can see that multiple parallel transactions are created, and they try to insert to the same table, but the first transaction locks it and it won't be released before it commits (but the following insert is executed sooner).

If you want to debug this deeper, I would first suggest to try things with raw knex to narrow it down a bit more. With the above config the database is actually created as a file called `file:memDb1?mode=memory&cache=shared` which sounds wrong to me - so might be either knex or node-sqlite3 issue (or the correct signature is different, but this is taken from knex docs directly).

**Comment by aniketbhatnagar** [comment]
Thanks for fixing this! Is this released? If not, any clue when would it be released?

**Comment by B4nan** [comment]
It's in v5, no plans to backport this, as v4 uses domain api and there it would be a breaking change to remove the copying of the active domain contents. But it's weird that in v4 it would result in this error, the code in v4 seems to be ok as the context is set after the old one is copied to the new one, so it would override the copy anyway.

https://github.com/mikro-orm/mikro-orm/blob/4.x/packages/core/src/utils/TransactionContext.ts#L21

**Comment by B4nan** [comment]
Ok found a way to fix it in 4.x too, will ship stable in a minute.

**Comment by aniketbhatnagar** [comment]
awesome! Thanks for the 4.5.7 release!
