### ISSUE TITLE
Populated relations of entities loaded using `connection.execute()` & `em.map()` cause an `UPDATE` on flush

### ISSUE THREAD

**Issue by jahudka** [mikro-orm/mikro-orm#1927]
When I execute a custom raw SQL query via `em.getConnection().execute(...)` and convert the result to entities using `em.map()` and then use `em.populate()` to populate a relation of the loaded entities, the next `em.flush()` will run an `UPDATE` on the populated relations, even though none of their properties have changed.

A minimal reproduction is available [here](https://github.com/jahudka/mikro-orm-repro-em-map).

As far as I can tell, when entities are loaded using `em.find()` the `EntityComparator.prepareEntity()` method is invoked only for the loaded `Book` instances; later, when `em.populate()` is called, `comparator.prepareEntity()` is called for the loaded `Author`s. In contrast, when `Book`s are loaded using `em.map()`, `comparator.prepareEntity()` is called for the `Author` references immediately as well; when `em.populate()` is called no further `comparator.prepareEntity()` call is logged. Thus when `.flush()` is called the `Author` entities have an empty `__originalEntityData` and therefore the values populated by `em.populate()` are considered a change by the UoW.

**Comment by jahudka** [comment]
Workaround is to pass `true` as the 5th argument to `em.populate()`;  this is the optional `refresh` argument. If I understand correctly it will force refreshing the properties of existing objects, which would otherwise be left alone by `em.populate()`. I still think `em.map()` on the parent entity shouldn't cause this in the first place, but with a usable workaround it's not that much of an issue anymore..

**Comment by B4nan** [comment]
Not reproducible for me, at least not with latest master or 4.x branch, so probably already fixed - you can try with `4.5.7-dev.8`. Closing with a test case based on your repro.

**Comment by s524797336** [comment]
@B4nan @jahudka   I tried 4.5.9, it is not fixed, when i populate or find with no refresh option set to true, it exec an update query. please reopen this issue.

**Comment by B4nan** [comment]
> @B4nan @jahudka I tried 4.5.9, it is not fixed, when i populate or find with no refresh option set to true, it exec an update query. please reopen this issue.

I closed this with a passing reproduciton, so if you want to see this reopened, provide another one that actually fails. Comments without failing repros will be ignored 🤷

**Comment by B4nan** [comment]
Actually it does reproduce something, but it was incomplete. Reproductions should prepare the initial data in the database, which this one did not do at all, and I just blidly rewrote the original repro code without much thinking...

**Comment by s524797336** [comment]
@B4nan 
Should i provide another one?

**Comment by B4nan** [comment]
Nope, I already said I found out why it was not reproducing anything.
