### ISSUE TITLE
Behavior of `schema:create` when using inheritance mapping

### ISSUE THREAD

**Issue by jacobdr** [mikro-orm/mikro-orm#1944]
**Describe the bug**
This is not a bug per se, more so seeking clarification to help steer some of our engineering direction. Obligatory preface: this is by far the best ORM out there for Typescript at the moment. Major kudos to the maintainers.

Our team is considering a move from the MongoDB to the Postgres driver. However, we've started to make use of the [Inheritance Mapping](https://mikro-orm.io/docs/inheritance-mapping) feature, and at first blush it seems to create some issues when running the `mikro-orm schema:create` command.

Before we continue to invest time into the migration, I wanted to seek clarification on the behavior when we overload a table table.

I guess the base case would be something like:

```typescript
@Entity({
    collection: DbCollectionName.Foo,
    abstract: true,
    discriminatorColumn: 'pipelineType',
})
export abstract class DbBaseFoo {
    pipelineType: 'a' | 'b';
}

@Entity({
    discriminatorValue: 'a',
})
export class FooA extends DbBaseFoo {
    pipelineType: 'a' = 'a' as const;
}

@Entity({
    discriminatorValue: 'b',
})
export class FooB extends DbBaseFoo {
    pipelineType: 'b' = 'b' as const;
}
```

The problem could also potentially be in our MikroORM config where we pass in the `entities` key explicitly. Unclear there if we would want to include `DbBaseFoo` in addition to `FooA` and `FooB`

**Stack trace**
```
TableExistsException: create table "foo" ... relation "foo" already exists
```

**Expected behavior**
Create table statements de-duplicated and merged to handle the overloads, and validation of any particular entity pushed downward to insertion/update time

**Additional context**

Admittedly we are moving from Mongo -> Postgres and Mongo is _way_ more flexible in how we can set up relations since it's all back in user space. Not sure if this use case is currently supported, so my "expected behavior" may not be fair.

**Versions**

| Dependency | Version |
| - | - |
| node | v12.18.0 |
| typescript | 3.9.10 |
| mikro-orm | 4.5.6 |
| your-driver | postgres & mongo |

**Comment by B4nan** [comment]
> The problem could also potentially be in our MikroORM config where we pass in the entities key explicitly. Unclear there if we would want to include DbBaseFoo in addition to FooA and FooB

All entities including the base ones need to be discovered, but some time ago I added auto-discovery for those, so it should as well work without that. 

It sounds like you are trying to use `schema:create` repeatedly. It will always issue the same queries, so only the first run will succeed, the rest will fail this way for sure, as it does not check what is in current schema, the command always creates it as if nothing was there. 

So maybe you want `schema:update` instead? Or do you really have multiple `create table "foo"` statements in the same run?

**Comment by jacobdr** [comment]
Jeez, that was a fast response. It seems like adding the abstract entities does sort the issue.

I did have to add `collection: DbCollectionName.Foo` to the base entities though in order to prevent duplicate calls to create tables it seems, though that is quite minor in the scheme of everything. 

Thanks for your hard work on this project
