### ISSUE TITLE
Can't populate 1:1 relationship using populate()

### ISSUE THREAD

**Issue by bnussman** [mikro-orm/mikro-orm#1947]
**Describe the bug**

```typescript
console.log("Can Location Populate?", ctx.em.canPopulate(User, 'location'));

await ctx.em.populate(ctx.user, 'location');

console.log("User's location after populate", ctx.user.location);
```

Outputs:

```
Can Location Populate? true
User's location after populate undefined
```

**Expected behavior**

The Entity Manager populates the location object on the user.

**Additional context**

**User Entity**
```typescript
@Field(() => Location, { nullable: true })
@OneToOne(() => Location, l => l.user, { nullable: true })
location?: Location;
```

**Location Entity**
```typescript
@Field(() => User)
@OneToOne(() => User)
user!: User;
```

**Versions**

| Dependency | Version |
| - | - |
| node | 14.15.4 |
| typescript | 4.3.4 |
| mikro-orm | 4.5.6 |
| @mikro-orm/postgresql | 4.5.6 |

**Comment by B4nan** [comment]
Well, but this means there is no value. For 1:1 owner, you would always have the value there, even if you dont populate it, there would still be a reference as we would know its PK.

**Comment by bnussman** [comment]
Very helpful, thank you!
