### ISSUE TITLE
Partially load collection based on WHERE or LIMIT clause

### ISSUE THREAD

**Issue by jsprw** [mikro-orm/mikro-orm#195]
**Is your feature request related to a problem? Please describe.**
Only load part of a collection with query instead of loading all and then filtering them by looping.

For example, only loading the dutch translations from table below:
Posts -> ContentTranslation (with column language) -> only load rows related to post WHERE language = en.

**Describe the solution you'd like**
A solution like this for ordering the collection:
https://github.com/mikro-orm/mikro-orm/issues/184#issuecomment-537825266, passing an init() argument to the createCondition method (https://github.com/mikro-orm/mikro-orm/blob/972c6e405738805b7204b783f0f609ce087a7b91/lib/entity/Collection.ts#L108).

Maybe have a seperate method to partially load a collection next to the initialize function. As well as setting a property that contains the total count and the count of data currently initialized.

**Describe alternatives you've considered**
Loading multiple queries seperately but would be great if it could be included in the initialize phase of a collection.

**Comment by B4nan** [comment]
I am planning to support both partial loading of collections as well as propagating the orderBy to collections (and other relationships). 

Will definitely fix the orderBy propagating issue from #184 before v3 release as now it really behaves unpredictably. Partial loading might come later in one of 3.x releases, as I would like to implement filter/sort collection API that would be compatible with both populated and not initialized collections.

**Comment by jsprw** [comment]
Thank you for your quick response (again)!

That would be a really great addition. Especially for collections that may get very big; it would be great to filter them in advance with a query.

**Comment by B4nan** [comment]
where and orderBy propagation available for testing in `3.0.0-alpha.24`. I will also allow where and orderBy in `Collection.limit()` soon.

**Comment by jsprw** [comment]
Test this fix now. Seems to work properly, will keep testing.

**Comment by B4nan** [comment]
`Collection.init()` now supports where and orderBy too in `3.0.0-alpha.26`.
