### ISSUE TITLE
Adding event subscribers to mikro-orm.config.ts causes cli to hang indefinitely

### ISSUE THREAD

**Issue by tolgap** [mikro-orm/mikro-orm#1956]
**Describe the bug**
Adding event subscribers to my MikroORM config, causes the CLI to never exit.

**To Reproduce**

Given a config with a simple subscriber and entity:

```ts
// db/config.ts
export const config: Options = {
  entities: [MyEntity],
  subscribers: [new MyEntitySubscriber()],
};


// mikro-orm.config.ts
import { config } from "./db/config"

export default config;
```

**Expected behavior**
When I run `npx mikro-orm debug`, the command should exit. But instead hangs indefinitely until I interrupt `^C` (or CTRL+C).

**Additional context**
This issue happens with every single command in `@mikro-orm/cli`. It works again if I remove the `subscribers` array in my config.

**Versions**

| Dependency | Version |
| - | - |
| node | v14.17.0 |
| typescript | v4.3.2 |
| mikro-orm | v4.5.6 |
| your-driver | postgresql@4.5.6 |

**Comment by B4nan** [comment]
Not reproducible on my end, can you provide executable repro?

**Comment by B4nan** [comment]
Closing as stale, will be happy to reopen if you provide actual reproduction.

**Comment by tolgap** [comment]
I figured it out.

I was importing a file that itself imported something from `bullmq`. When imported, that file performs a blocking task (spawning a queue).
