### ISSUE TITLE
Issue with "createFunction" when using embeddable property with hyphens

### ISSUE THREAD

**Issue by ryankauk** [mikro-orm/mikro-orm#1958]
**Describe the bug**

This issues seems to be an issue with the create function. Maybe it could use bracket notation instead of dot notation? Please let me know if there's any work arounds that you can think of. I'm unable to change the name of the property in my situation. Not sure if this is specific to embeddable or entities as a whole.

**Stack trace**
```
SyntaxError: Unexpected token 'with'
        at new Function (<anonymous>)

      at Function.createFunction (node_modules/@mikro-orm/core/utils/Utils.js:611:52)

  console.error
    return function(entity) {
      const ret = {};
      if ('id' in entity && entity.id != null) {
        ret.id = entity.id;
      }
    
      if ('name' in entity) {
        ret.name = entity.name;
      }
    
      if (entity.sub != null) {
        ret.sub_some-prop-with-hyphens = clone(entity.sub.some-prop-with-hyphens);
      }
    
      return ret;
    }

      at Function.createFunction (node_modules/@mikro-orm/core/utils/Utils.js:615:21)
```

**To Reproduce**
https://github.com/ryankauk/mikro-jest-global-setup/blob/master/src/index.spec.ts

test case "test embedded model with property and hyphens"

**Expected behavior**
I expect that you should be able to use hyphens in property name.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | v12.16.3 |
| typescript | ^4.1.3 |
| mikro-orm | 4.5.6 |
| your-driver | mongo |

**Comment by B4nan** [comment]
> To Reproduce ryankauk/mikro-jest-global-setup@e2f63b2/src/index.spec.ts

That link is invalid, looks like the repo is not even there?

I was fixing pretty much the same problem some time ago, it might as well be already fixed in master (v5) or in #1948. 

Or it is just a wrong entity definition. I'd say the property names itself cannot even contain hyphens (as that is not allowed at JS/TS level). What you can do is to have a `fieldName` with hyphen, but not a property name.

**Comment by ryankauk** [comment]
Sorry updated the link and my my repo public. I tried the fieldName to be using hyphens but it was the same issue.

**Comment by B4nan** [comment]
Wow, never thought this is actually valid property definition. So you have tried this, right?

```ts
@Embeddable()
export class SubModel {

  @Property({ name: 'some-prop-with-hyphens', nullable: true })
  somePropWithHyphens?: string;

}
```

**Comment by ryankauk** [comment]
Yea tried that and it ended up with the same error

**Comment by ryankauk** [comment]
So I did a bit more testing, the above you mentioned does work, I realized my real use case is that the property I'm trying to use hyphens with is using @Embedded , which does not have a fieldName option, I found a workaround in the meantime that I just introduced a function on my model that does the mapping

**Comment by B4nan** [comment]
So you have object embeddables, right? It should actually work to pass the `fieldName` there too, you will just need to type cast the options.
