### ISSUE TITLE
_id returns as an ObjectId 

### ISSUE THREAD

**Issue by vinniimiranda** [mikro-orm/mikro-orm#1960]
**Describe the bug**
All _id's stored on database retuns an object instead of string. 
![image](https://user-images.githubusercontent.com/33462844/123172394-7d084480-d453-11eb-8d2f-4f93b4771b28.png)

**To Reproduce**
![image](https://user-images.githubusercontent.com/33462844/123172535-a88b2f00-d453-11eb-9dac-d7dedc5f4392.png)

**Expected behavior**
Return _id as string instead of Object.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 14.16.1 |
| typescript | 4.0.5|
| mikro-orm | 4.5.6 |
| your-driver | mongo |

**Comment by B4nan** [comment]
You literally ask the orm to use objectid type. If you want strings, drop the type option from the decorator. But the dont expect autoincrement, as that works in mongo only with object id.

**Comment by vinniimiranda** [comment]
But if I don't use this way, find by id doesn't work

**Comment by B4nan** [comment]
I don't have magical orb, so hard to say what you are doing without seeing some code. There are example apps, including one using mongo, so look at that I guess. You either need to have only object id, or both string and object id variants. But not mix those into same property, that won't work. 

https://mikro-orm.io/docs/usage-with-mongo/#defining-entity
https://github.com/mikro-orm/express-ts-example-app

**Comment by vinniimiranda** [comment]
You don't need to be rude, i am just making some questions because i didn't found a solution looking into documentation. I am gonna try some workaround for this, anyway, thanks for your help.
