### ISSUE TITLE
ManyToMany collection with composite key remove from unrelated owner

### ISSUE THREAD

**Issue by knguyen0125** [mikro-orm/mikro-orm#1961]
**Describe the bug**

This is a two part problem, affecting ManyToMany collection with one side having more primary keys than the other.

The first problem: If the owner has more primary keys than target, removing target from collection will remove that target from all other owners with same one of primary keys

The second problem: If the owner has less primary keys than target, there is no way to remove that target from collection.

**Stack trace**
```
...
```

**To Reproduce**

First problem: 
1. Edit [tests/features/composite-keys/composite-keys.sqlite.test.ts](https://github.com/mikro-orm/mikro-orm/blob/master/tests/features/composite-keys/composite-keys.sqlite.test.ts)
2. Enable debug mode (query)
3. Edit test `composite entity in m:n relationship, one of entity is composite`
4. After
```ts
    user1.sandwiches.add(sandwich1, sandwich3);
    user2.sandwiches.add(sandwich3);
    user2.sandwiches.add(sandwich2, sandwich3);
    await orm.em.persistAndFlush([user1, user2, user3]);
```
5. Add
```ts
   user2.sandwiches.removeAll();
   await orm.em.persistAndFlush([user2]);
```
6. The delete query would be similar to
```sql
DELETE FROM user2_sandwichs WHERE (sandwich_id) in ((2, 3)) AND user2_first_name = "Henry"
```
7. Whereas the correct query should be
```sql
DELETE FROM user2_sandwichs WHERE (sandwich_id) in ((2, 3)) AND user2_first_name = "Henry" AND user2_last_name = "Doe 2"
```

Second problem:
1. Create an owner entity with 1 primary key (owner_id)
2. Create a target entity with 2+ primary keys (target_first_id, target_second_id)
3. Add some target in database. Add one owner entity to database. Add some target to owner entity
4. Run `owner.targets.removeAll(); ownerRepository.persistAndFlush(owner)`
5. The process will throw an error like
```
DELETE FROM owner_targets WHERE (target_first_id, target_second_id) in ((1,1), (2,2)) AND owner_id = 1 AND undefined = undefined
```

**Expected behavior**

The first problem: If the owner has more primary keys than target, removing target from collection will NOT remove that target from all other owners with same one of primary keys

The second problem: If the owner has less primary keys than target, removing target from collection will remove target from database

**Additional context**

I think this issue come from [AbstractSqlDriver](https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/AbstractSqlDriver.ts), function updateCollectionDiff, especially this line

```
      meta2.primaryKeys.forEach((pk, idx) => knex.andWhere(prop.joinColumns[idx], pks[idx] as Knex.Value[][]));
```

`meta2` seems to be target metadata, so its primary keys have equal length to `prop.inverseJoinColumns`. The line above should add information about the owner (from `prop.joinColumns`), so it should not be `meta2`

I think a quickest fix is

```
    prop.joinColumns.forEach((joinColumn, idx) => knex.andWhere(joinColumn, pks[idx] as Knex.Value[][]))
    // or
    meta.primaryKeys.forEach((pk, idx) => knex.andWhere(prop.joinColumns[idx], pks[idx] as Knex.Value[][]));
```

However, I'm just started using Mikro-ORM, I don't know if this is the correct fix. But it does seems to work based on my testing.

**Versions**

| Dependency | Version |
| - | - |
| node | 14.17 |
| typescript | 4.3.4 |
| mikro-orm | 4.5.6 |
| your-driver | postgres |

**Comment by B4nan** [comment]
Thanks for the detailed descriptions as well as the correct suggested fix!
