### ISSUE TITLE
Incorrect DDL generated by the mikro-orm schema:create CLI

### ISSUE THREAD

**Issue by ltudisco** [mikro-orm/mikro-orm#1962]
**Describe the bug**

Incorrect DDL generated by the mikro-orm schema:create CLI for mySQL

**To Reproduce**

1.  Given the following TS entity:

```typescript
import { Entity, PrimaryKey, Property } from '@mikro-orm/core';

@Entity({ collection: 'test_entity' })
export class TestEntity {

  @PrimaryKey({ fieldName: 'id' })
  id!: number;

  @Property({ length: 3, columnType: 'char', default: 'USD' })
  currencyCode!: string;
}
```

2.  Run `npx mikro-orm schema:create --run`

3. The generated DDL looks like this

```sql
create table `test_entity` (`id` int unsigned not null auto_increment primary key, `currency_code` char not null default 'USD') default character set utf8mb4 engine = InnoDB;
```

**Expected behavior**

The DDL above runs w/o issues.

**Additional context**

Running the DDL above fails with the following error message `Invalid default value for 'currency_code'`

It looks like the `currency_code` is generated as char instead of char(3).

**Versions**

"@mikro-orm/core": "^4.5.6"
"@mikro-orm/mysql": "^4.5.6"
"@mikro-orm/cli": "^4.5.6"

**Comment by B4nan** [comment]
When you use `columnType`, it is always used as is, no postprocessing is made on top of the value you provide. In other words, you need to pass the whole definition including the length there:

```ts
  @Property({ columnType: 'char(3)', default: 'USD' })
  currencyCode!: string;
```

**Comment by ltudisco** [comment]
@Property({ length: 3, columnType: 'char', .. })
currencyCode!: string;

is actually autogenerated using `mikro-orm generate-entities` from a DB schema that looks like

```sql
CREATE TABLE `test_entity` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `currency_code` char(3) NOT NULL DEFAULT 'USD',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by B4nan** [comment]
That is fixed already in v5, the schema diffing is reworked and entity generator now generates the correct `columnTypes` too.

**Comment by ltudisco** [comment]
Thanks @B4nan !

**Comment by ltudisco** [comment]
... when are you planning to release v5?

**Comment by B4nan** [comment]
No hard deadline, it's a bit hard to find time for open source during summer, but I hope to reach RC at the end of summer.

You can track the progress here: https://github.com/mikro-orm/mikro-orm/issues/1623
