### ISSUE TITLE
TypeError: Class constructor SqlEntityRepository cannot be invoked without 'new' when registering CustomRepo in @Entity

### ISSUE THREAD

**Issue by alumpe** [mikro-orm/mikro-orm#1965]
**Describe the bug**
When I register my CustomRepository via the `@Entity` decorator of my entity and omit the `@Repository` decorator like explained [here](https://mikro-orm.io/docs/repositories/#custom-repository), I get the error listed in the stack trace (at runtime when querying my API). When I register my repo via the `@Repository` decorator though, I don't get that error. I thought the two methods of registering the repo were interchangable, or did I do something wrong somewhere?

My user entity looks like this:
```
import { Entity, ... , EntityRepositoryType } from "@mikro-orm/core";
import { UserRepository } from "./userRepository";

@Entity({ customRepository: () => UserRepository })
export class User {
  [EntityRepositoryType]?: UserRepository;

  @PrimaryKey()
  id: number;

...
```

My user repo looks like this:
```
import { EntityRepository } from "@mikro-orm/postgresql";
import { User } from "./userEntity";

export class UserRepository extends EntityRepository<User> {}
```

**Stack trace**
```
(node:14168) UnhandledPromiseRejectionWarning: TypeError: Class constructor SqlEntityRepository cannot be invoked without 'new'
    at new UserRepository (C:\Users\Adrian\Documents\Projekte\dash-board\server\src\modules\user\userRepository.ts:23:42)
    at SqlEntityManager.getRepository (C:\Users\Adrian\Documents\Projekte\dash-board\server\node_modules\@mikro-orm\core\EntityManager.js:62:46)
    at SqlEntityManager.getRepository (C:\Users\Adrian\Documents\Projekte\dash-board\server\node_modules\@mikro-orm\knex\SqlEntityManager.js:27:22)
    at C:\Users\Adrian\Documents\Projekte\dash-board\server\src\middleware\passport.ts:11:34
    at step (C:\Users\Adrian\Documents\Projekte\dash-board\server\src\middleware\passport.ts:33:23)
    at Object.next (C:\Users\Adrian\Documents\Projekte\dash-board\server\src\middleware\passport.ts:14:53)
    at C:\Users\Adrian\Documents\Projekte\dash-board\server\src\middleware\passport.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Adrian\Documents\Projekte\dash-board\server\src\middleware\passport.ts:4:12)
    at C:\Users\Adrian\Documents\Projekte\dash-board\server\src\middleware\passport.ts:10:51
```

**Versions**

| Dependency | Version |
| - | - |
| node | v14.15.1 |
| typescript | 4.3.2 |
| mikro-orm | 4.5.4 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
Are you sure you have all the ORM packages aligned (on the very same version)? Sounds like a dependency resolution issue.

Just tried it myself on the realworld example and it works fine for me, I just can't use both (`@Repository` decorator and `customRepository`).

**Comment by alumpe** [comment]
Both packages are on version 4.5.4.
```
"@mikro-orm/core": "^4.5.4",
"@mikro-orm/postgresql": "^4.5.4",
```

Its very strange, literally the only difference in my code is `@Entity()` -> `@Entity({ customRepository: () => UserRepository })` and removing the `@Repository(User)` decorator and it throws the error whenever I use a repo in a route handler. Maybe I am doing something wrong there? I use AsyncLocalStorage for forking the em for every Request like suggested with node v14. Here is Code from my route handler that would throw an error:

```
import { em } from "../../server";

const getAllUserProjects = catchAsync(async (req: Request, res: Response) => {
  const projectRepo = em.getContext().getRepository(Project);
  const allProjects = await projectRepo.findAll({ populate: true });

  res.json(allProjects);
});
```

(Side question: Is the em.getContext() method even the correct way of getting the forked em in a route handler or is there a simpler way?)

**Comment by B4nan** [comment]
> Both packages are on version 4.5.4.

This means they need to be at least on 4.5.4, the actual version you use is in the lock file. Without lock file, this would install latest, which is 4.5.6. So please verify the lock file, or ideally wipe node_modules and lock file and reinstall to be absolutely sure. 

This is definitely not about usage, I'd be very surprised if it's not a dependency problem. If reinstalling deps won't help, prepare a repro 🤷 

What is in that file btw? `server\src\middleware\passport.ts:11:34`

**Comment by B4nan** [comment]
Mmmm it probably won't matter, but you should not get the repository from contextual EM

```diff
-const projectRepo = em.getContext().getRepository(Project);
+const projectRepo = em.getRepository(Project);
```

In general you should not need to use `em.getContext()`, it is used automatically where needed. Only place where it makes sense is when you debug request contexts so you can see the current/contextual EM id.

**Comment by alumpe** [comment]
In the passport file is the serializing/deserializing logic for the user (I use session cookies and express-session and passport.session()):

```
import passport from "passport";
import { User } from "../modules/user/userEntity";
import { em } from "../server";

const setupPassport = (): void => {
  passport.serializeUser((user, done) => {
    done(null, user.id);
  });

  passport.deserializeUser(async (id: number, done) => {
    const user = await em.fork().getRepository(User).findOne({ id: id }, true);
    if (!user) done(null, null);

    done(null, user);
  });
};

export default setupPassport;

```

The setupPassport() function is called in my app.ts which looks like this:
```
const app = express();

app.use(express.json()); // Middleware for parsing json bodies

app.use(cors(config.corsOptions)); // Middleware that adds cors headers to response

app.use(session(config.sessionOptions));

app.use((req, res, next) => {
  storage.run(em.fork(true, true), next);
});

app.use(passport.initialize());
app.use(passport.session());
setupPassport();

app.use(helmet());
app.use(morgan("dev"));

... (here come my routers and some error handling)
```

This is what my index.ts looks like just in case:
```
let em: EntityManager;

(async () => {
  const orm = await MikroORM.init(config.dbOptions);

  em = orm.em;

  const generator = orm.getSchemaGenerator();
  await generator.updateSchema();

  app.listen(config.port, () =>
    console.log(`Backend is listening on port ${config.port}.`)
  );
})();

export { em };
```

**Comment by B4nan** [comment]
You said you are using `AsyncLocalStorage`, but in your code you are forking manually?

**Comment by alumpe** [comment]
I decided to do it more like in your example projects with the DI (does that stand for Database Instance btw.?) and rewrote my index.ts really quick. It looks like this now:
```
import { MikroORM, EntityManager } from "@mikro-orm/core";
import { EntityRepository } from "@mikro-orm/postgresql";
import "reflect-metadata";
import { User } from "./modules/user/userEntity";
import { Project } from "./modules/project/projectEntity";

import app from "./app";
import config from "./config";

export const DI = {} as {
  orm: MikroORM;
  em: EntityManager;
  userRepository: EntityRepository<User>;
  projectRepository: EntityRepository<Project>;
};

(async () => {
  DI.orm = await MikroORM.init(config.dbOptions);
  DI.em = DI.orm.em;
  DI.userRepository = DI.orm.em.getRepository(User);
  DI.projectRepository = DI.orm.em.getRepository(Project);

  const generator = DI.orm.getSchemaGenerator();
  await generator.updateSchema();

  app.listen(config.port, () =>
    console.log(`Backend is listening on port ${config.port}.`)
  );
})();
```

Now I actually get the error directly when starting the server. This is the full stack trace now:
```
[discovery] ORM entity discovery started, using ReflectMetadataProvider
[discovery] - processing entity User
[discovery] - processing entity Project
[discovery] - processing entity xxx
[discovery] - processing entity xxx
[discovery] - processing entity xxx
[discovery] - entity discovery finished, found 5 entities, took 24 ms
[info] MikroORM successfully connected to database dash_board_db on postgresql://postgres:*****@localhost:5432
(node:20292) UnhandledPromiseRejectionWarning: TypeError: Class constructor SqlEntityRepository cannot be invoked without 'new'
    at new UserRepository (C:\Users\Adrian\Documents\Projekte\dash-board\server\src\modules\user\userRepository.ts:23:42)
    at SqlEntityManager.getRepository (C:\Users\Adrian\Documents\Projekte\dash-board\server\node_modules\@mikro-orm\core\EntityManager.js:62:46)
    at SqlEntityManager.getRepository (C:\Users\Adrian\Documents\Projekte\dash-board\server\node_modules\@mikro-orm\knex\SqlEntityManager.js:27:22)
    at C:\Users\Adrian\Documents\Projekte\dash-board\server\src\server.ts:20:33
    at step (C:\Users\Adrian\Documents\Projekte\dash-board\server\src\server.ts:33:23)
    at Object.next (C:\Users\Adrian\Documents\Projekte\dash-board\server\src\server.ts:14:53)
    at fulfilled (C:\Users\Adrian\Documents\Projekte\dash-board\server\src\server.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20292) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20292) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by B4nan** [comment]
Mmmm what about this? Are you by any chance target ES5 in your tsconfig.json?

https://stackoverflow.com/a/51860850/3665878

**Comment by alumpe** [comment]
Wow, yes that was the problem. Changing it from ES5 to ES2017 for example fixed the problem.

**Comment by B4nan** [comment]
You probably did not even had the custom repository set up before so it "worked", the `@Repository()` decorator works only if the class is required so the decorator gets executed.

**Comment by alumpe** [comment]
Yes, thanks very much for digging into it and finding the solution. Another quick question since we talked about `AsyncLocalStorage` and forking and such. After reading [the docs](https://mikro-orm.io/docs/async-local-storage/) and since I am not really familiar with the concept, I didn't quite get how to get the forked `EntityManager` in a request handler. Just using DI.em obviously returns the main instance from my index.ts, how do I get the forked instance, I was then using `DI.em.getContext()`, is that the correct way? Maybe adding a line to the docs about that would help some others as well :)

**Comment by B4nan** [comment]
> Just using DI.em obviously returns the main instance from my index.ts, how do I get the forked instance, I was then using DI.em.getContext(), is that the correct way? Maybe adding a line to the docs about that would help some others as well :)

The point of using ALS is that you don't need to care. You pass the context getter to the ORM options and it will use it automatically where needed. The contextual EM is always preferred when working with the global EM instance.

Yes, `em.getContext()` will give you the current fork, but you don't need to use it, as internals use it. 

ALS is used by default in v5 (already in master).

**Comment by alumpe** [comment]
I see, so just using DI.em would be the way to do it then, pretty cool! 👍

**Comment by B4nan** [comment]
Yeah the `DI` here stands for dependency injection, its kinda of a DI container (a toy one for sure, but enough for a simple example apps).
