### ISSUE TITLE
Embeddable property initializer is not ran during hydration

### ISSUE THREAD

**Issue by ryankauk** [mikro-orm/mikro-orm#1970]
**Describe the bug**
I use an initializer on an embedded property but it doesn't get fired when hydrate function is called. This is as deep as I could debug since I started getting lost in how the hydrator functions worked. I used the "forceEntityConstructor" with the embeddable but I'm assuming it might not work with embeddables. This seems to happen when there's pre existing data for the embeddable entity.

**Stack trace**
N/A

**To Reproduce**
https://github.com/ryankauk/mikro-jest-global-setup/blob/master/src/embeddableInitializer.spec.ts

**Expected behavior**
I expected that it would use the initializer when the property doesn't exist. I knew that this isn't the case unless "forceEntityConstructor" is set, and expected this would solve my issue and use the initializer.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | v12.16.3 |
| typescript | ^4.1.3 |
| mikro-orm | 4.5.6 |
| your-driver | mongo |

**Comment by B4nan** [comment]
This is correct behaviour, just like with entities, initializers are executed only in case of new entity/embedded instance, not for existing ones. If you don't use constructors in your entities and want this behaviour, just use `forceEntityConstructor`, or the onInit hook on parent entity.

We can add something like `forceEmbeddedConstructor` if you want.

**Comment by B4nan** [comment]
Actually you can already use `forceEntityConstructor` option, you can specify it as an array of classes to have control over what entities will use constructors (and in this sense embeddable is an entity). 

I see that you already found out this is possible, as you got it in your repro too. 

Closing, I don't think we need another option for this, I'd expect people will usually won't one way or the other (e.g. don't care about using own constructors at all).
