### ISSUE TITLE
Data not updated (even after a while) when cache is enabled (default). After disabling, it works (Postgres, NestJS, Apollo GraphQL)

### ISSUE THREAD

**Issue by woltob** [mikro-orm/mikro-orm#1977]
**Describe the bug**

I encountered a strange behavior where my data through a GraphQL API (Apollo, using NestJS) was not updated, even after hours. The data was immediately persisted in the postgres database however. 

After disabling cache in the MikroORM with cache { enabled: false}, it works like a charm.

Is this a known behavior, what am I doing wrong?

**Stack trace**
```
...
```

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Additional context**

**Versions**

| Dependency | Version |

"@mikro-orm/cli": "^4.5.5",
"@mikro-orm/core": "^4.5.5",
"@mikro-orm/nestjs": "^4.2.0",
"@mikro-orm/postgresql": "^4.5.5",
"@mikro-orm/reflection": "^4.5.5",
"@nestjs/cli": "^7.5.6",
"@nestjs/common": "^7.6.17",
"@nestjs/config": "^0.6.3",
"@nestjs/core": "^7.6.17",
"@nestjs/event-emitter": "0.0.3",
"@nestjs/graphql": "^7.10.6",
"@nestjs/passport": "^7.1.5",
"@nestjs/platform-express": "^7.6.17",
"@nestjs/schematics": "^7.3.0",
"@nestjs/testing": "^7.6.17",
"apollo-server-errors": "^2.4.2",
"apollo-server-express": "^2.24.0"
...

running postgres 13.

**Comment by B4nan** [comment]
> After disabling cache in the MikroORM with cache { enabled: false}, it works like a charm.

This will disable metadata cache, and metadata cache is disabled by default. 

In other words, this cannot have any effect on running the app unless you have invalid cache (which should be detected and rebuilt automatically, the cache stores a hash of the file contents of the entity definition).
