### ISSUE TITLE
Filters defined on base entity are not apllied when querying the child

### ISSUE THREAD

**Issue by nozgurozturk** [mikro-orm/mikro-orm#1979]
**Describe the bug**
If you define Filter on entity then use that filter in entity manager's method such as `findAndCount`, Filter does not affect on count result.

**Stack trace**
N/A

**To Reproduce**

1. Define Entity and Filter
```ts

enum Status {
  OPEN = 'open',
  CLOSED = 'closed',
  MERGED = 'merged',
}

@Filter({
  name: 'closed',
  cond: {
    status: Status.CLOSED,
  },
})

@Entity()
export class PullRequest {
  @PrimaryKey({ type: 'uuid' })
  id = v4();

  @Property()
  title!: string;

  @Index()
  @Property({ columnType: 'timestamp' })
  createdAt = new Date();

  @Enum()
  status: Status = Status.OPEN;
}

```
2. Let's imagine we have 50 closed, 20 merged, 30 open PR (100)

3. Fetching Entities

```ts
...
const [entities, totalCount] = await pullRequestRepository.findAndCount(
  {},
  {
    orderBy: { createdAt: QueryOrder.DESC },
    limit: 25,
    offset: 25,
    filters: ['closed'],
  },
);
...
```
4. The total count result is equal to the count of all PRs 

**Expected behavior**

Count result of the `findAndCount` method with Filter must be equal to the count of all filtered entities not all of them.

**Versions**

| Dependency | Version |
| - | - |
| node | 15.14.0 |
| typescript | 4.2.3 |
| mikro-orm | 4.5.6 |
| postgres | 13.2-1 |

**Comment by B4nan** [comment]
That's hard to believe, the very same condition object is used in both `find` and `count` methods, as well as the very same helper that applies filters is used inside those. Tried to reproduce it [this test](https://github.com/mikro-orm/mikro-orm/blob/master/tests/features/filters/filters.postgres.test.ts#L106) and it works as expected, the condition is part of both queries. 

```sql
select "e0".* from "benefit" as "e0" where "e0"."benefit_status" = $1
select count(distinct("e0"."id")) as "count" from "benefit" as "e0" where "e0"."benefit_status" = $1
```

Please provide executable repro, preferrably as a test case like in the https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues folder. 

And start with enabling debug mode and verifying what are the actual queries.

**Comment by Langstra** [comment]
Hey there, I attempted to create a reproduction for this. The example you gave I tried to recreate as best I could, but the results are as expected. Please feel free to edit the test to reproduce your own results. You can check my attempt at a reproduction here: https://github.com/RiskChallenger/mikro-orm/commit/a5804dcd89e183025a728669d7020f637870c9c8#diff-59830ebc3a4184110566bf1a290d08473dfdcbd492ce498b14cd1a5e2fa2e441

**Comment by nozgurozturk** [comment]
@B4nan thank you for your fast response and also @Langstra thank you for your interest.

Sorry for the misinformation. 

I also attempted to create a reproduction for my problem. You can check repro here https://github.com/nozgurozturk/mikro-orm/blob/issue/1979/tests/issues/GH1979.test.ts

I guess the bug is about single table inheritance.

These are SQL queries

With Filter
```sql
select "e0".* from "benefit" as "e0" where "e0"."type" = 'Profit'
select count(distinct("e0"."id")) as "count" from "benefit" as "e0" where "e0"."type" = 'Profit'
```

Without Filter
```sql
select "e0".* from "benefit" as "e0" where "e0"."benefit_status" = 'A' and "e0"."created_at" <= '2021-06-28T21:11:34.884Z' and "e0"."type" = 'Profit'
select count(distinct("e0"."id")) as "count" from "benefit" as "e0" where "e0"."benefit_status" = 'A' and "e0"."created_at" <= '2021-06-28T21:11:34.884Z' and "e0"."type" = 'Profit'
```

**Comment by B4nan** [comment]
Thanks for the repro!

If you look at the queries, the problem is not just with the count query, the condition is missing in both queries:

```sql
[query] select "e0".* from "benefit" as "e0" where "e0"."type" = 'Profit' [took 4 ms]
[query] select count(distinct("e0"."id")) as "count" from "benefit" as "e0" where "e0"."type" = 'Profit' [took 13 ms]
```

The issue is more generic, its about STI vs filters, nothing `em.findAndCount()` or even `em.count()` specific.

Also note that your filter as it is defined will use constant date value, you might want to use callback so the value is taken when filter is applied:

```ts
@Filter({
  name: 'isActive',
  cond: () => ({ benefitStatus: 'A', createdAt: { $lte: new Date() } }), // here the date will be dynamic
//  cond: { benefitStatus: 'A', createdAt: { $lte: new Date() } }, // here the date is constant, computed on require time
})
```

**Comment by nozgurozturk** [comment]
Thank you @B4nan for the fast response and fix, I investigated the issue and planned to open PR about that but you did, Thanks 🙏.
