### ISSUE TITLE
Async virtual Properties not loaded correctly

### ISSUE THREAD

**Issue by Benjamin-Frost** [mikro-orm/mikro-orm#1995]
**Describe the bug**
If one defines a `async` virtual property like such

```ts
@Property({ name: 'cardsCount' })
async cardsCount() {
  return await this.cards.loadCount();
}
```

where `cards = new Collection<Card>(this)` and one fetches the entity in any way, e.g. `fineOne` or `findAll` the result will contain an empty object (`{}`) instead of the expected count. The reason for this seems to be that Mikro-ORM does not await virtual properties if they are `async`.

**To Reproduce**

1. Create a new entity with a virtual property, e.g.

```ts
@Entity()
export class Test {
  @PrimaryKey()
  id: number;

  @Property({ name: 'test' })
  test() {
    return 1;
  }
}
```

2. Fetch the entity (for example `fetchAll`). You should see something like this

```json
[
    {
        "id": 1,
        "test": 1
    }
]
```

This seems to be perfectly fine 🚀 

3. Now, make the virtual method `async`

```ts
@Property({ name: 'test' })
  async test() {
    return 1;
  }
```

4. And fetch again

```json
[
    {
        "id": 1,
        "test": {}
    }
]
```

The virtual property now results in an empty object (`{}`) 😢 

**Expected behavior**
I would expect virtual methods to be awaited in case they are `async`. If this is not possible by default it would be great to be able to add an option like `isAsync` to a virtual property. In my example this would mean something like this

```ts
@Property({ name: 'test', isAsync: true })
  async test() {
    return 1;
  }
```

**Versions**

| Dependency | Version |
| - | - |
| node | `14.15.5` |
| typescript | `4.3.2` |
| mikro-orm | `4.5.5` |
| postgresql | `4.5.5` |

**Comment by B4nan** [comment]
So, bug you say? What makes you think this is supported? And why it should be in the first place?

Most of the methods that operate with entity properties are sync, so in many places it is literally impossible to do this. 

For me this is a bad idea in the first place, literally introducing n+1 issue.

**Comment by B4nan** [comment]
The idea behind virtual properties was to allow populating them from QB, not to let them load something asynchronously. See this test case, it is pretty much exactly about your use case, but using a single query with a sub-query to load the counts.

https://github.com/mikro-orm/mikro-orm/blob/master/tests/issues/GH1538.test.ts

Alternatively you could use `@Formula()` with a subquery (preferrably set to lazy), but that would result in the N+1 problem again, so not very good solution. 

Closing, as awaiting anything during serialization is not an option, `toJSON` method (where this happens) needs to be sync (just like `JSON.stringify` is sync).
