### ISSUE TITLE
One to one relationship not loaded when using populate

### ISSUE THREAD

**Issue by evantrimboli** [mikro-orm/mikro-orm#2009]
**Describe the bug**
When using populate on a one to one relationship, there is no attempt to populate the property.

**Stack trace**
N/A

**To Reproduce**
1. Clone the linked repository on branch `issue-2009`: https://github.com/evantrimboli/mikro-orm-test-cases/tree/issue-2009
2. `npm install`
3. create/up migrations
4. Run `src/test.ts`

**Expected behavior**
There should be a query executed to populate the `defaultImage` property.

**Additional context**
I may be going about this the wrong way, would be happy to use a better approach.

**Versions**

| Dependency | Version |
| - | - |
| node | v14.15.4 |
| typescript | 4.2.3 |
| mikro-orm | 4.5.7 |
| your-driver | pg |

**Comment by B4nan** [comment]
Your entity definition is wrong, both sides are owners, it is not a bidirectional relation, therefore you are setting it only on one side and populating the other won't do anything.

**Comment by evantrimboli** [comment]
Thanks for the response, I understand this better now. I found the docs for one to one a little confusing because it was referring to the same type. Do you think it would be worthwhile to add a second example where the types are different?

**Comment by B4nan** [comment]
I guess we can just change the one that is there, we don't really need an example with self-reference.
