### ISSUE TITLE
Partial Unique Index in Postgres

### ISSUE THREAD

**Issue by woltob** [mikro-orm/mikro-orm#2019]
**Is your feature request related to a problem? Please describe.**
I would like to add a partial unique index to my postgres database that is only "active" if an attribute has a certain value.

See this documentation: https://www.postgresql.org/docs/14/indexes-partial.html

As of now I would have to create a manual custom migration that does that?

Thank you so much.

**Comment by B4nan** [comment]
Custom index expressions are already implemented as `@Index({ expression: 'alter table book add index custom_index_expr(title)' })` in v5. 

In v4 you can create the index manually and just define regular index in your entity with the same name - indexes are diffed just based on the name in v4 so schema diffing will work fine this way.
