### ISSUE TITLE
OnInit hook called multiple times if entity is loaded by population

### ISSUE THREAD

**Issue by JakobStaudinger** [mikro-orm/mikro-orm#2022]
**Describe the bug**
When an entity is initially loaded by population, its `@OnInit`-hook gets called twice (once before the entity is actually initialized)

**To Reproduce**
1. Define an entity with a relation to another entity (e.g. parent -> children)
2. Load the entity and make sure the relation is populated.
3. Listen to the `@OnInit` hook, and you will find that it is called multiple times for the same entity (the one that is being loaded through population)

If the entity to be populated is loaded beforehand (e.g. by calling findOne directly), the `@OnInit` hook is only ever called once, as is expected.

Repo for reproduction: https://github.com/JakobStaudinger/mikro-orm-populate-init-reproduction

**Expected behavior**
The `@OnInit` hook should be called exactly once (for each entity), after the entity is fully initialized

**Versions**

| Dependency | Version |
| node | 12.22.1 |
| typescript | 4.3.5 |
| mikro-orm | 4.5.7 |
| your-driver | mongodb |

**Comment by JakobStaudinger** [comment]
I've investigated a bit and it seems that only dispatching the on-init event [right here](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/entity/EntityFactory.ts#L58) if `options.initialized` is `true` leads to the expected behavior, though I don't know the code well enough to know if this would cause problems elsewhere...

**Comment by B4nan** [comment]
This is kinda intentional, we could change it in v5 but for me this is a breaking change. Because it means we won't fire the onInit hook for references (not populated entitities) at all. You can make your hook conditional and just check `wrap(this).isInitialized()`.

**Comment by JakobStaudinger** [comment]
Thanks for the quick reply!
To me it seemed like unexpected behavior, since I don't expect an "init" hook to get called multiple times, but I see the reasoning behind it. I tried the workaround and it works perfectly for my situation, thank you very much 😄
I'm closing this issue, as it seems to be invalid now with the workaround.
