### ISSUE TITLE
Support for column operations

### ISSUE THREAD

**Issue by SDAdham** [mikro-orm/mikro-orm#2039]
**Is your feature request related to a problem? Please describe.**
Let's say we have the following structure (it may not look good logically but it's defeating the purpose of the demonstration):
```
Entity Employee {
  position: string;
  department: string;
  company: string;
}
Entity Profile {
  firstName: string;
  lastName: string;
  dob: Date;
}
Entity User {
  username: string;
  password: string;
  employee: Employee;
  profile: Profile;
}
```
We would want to allow a single input search for all users where we use text box with an auto-complete list based on the single input. Today, we can do this via [Custom query builder](https://mikro-orm.io/docs/query-builder/#custom-sql-in-where) and for such complex query, it can get very messy, difficult to read/write and we will need to write SQL statement manually which defeats the essence of MikroORM.
```
const qb = orm.em.createQueryBuilder(User, 'u');
qb.select('*').where({ 'concat(u.profile.firstName, u.profile.lastName)': '%query%String%' })
```

**Describe the solution you'd like**
It would be great if we can do the following:
```
const query = 'xyz'.toLowerCase();
const result = await this.repo.find({
    $or: [
        {
            employee: {
                $lower: {
                    $concat: {
                        columns: ['position', 'department', 'company'],
                        value: {
                            $like: `%${query}%`
                        }
                    }
                }
            }
        },
        {
            profile: {
                $lower: {
                    $concat: {
                        columns: ['firstName', 'lastName'],
                        value: {
                            $like: `%${query}%`
                        }
                    }
                }
            }
        },
        {
            user: {
                $lower: {
                    username: {
                        $like: `%${query}%`
                    }
                }
            }
        }
    ]
});
```

**Describe alternatives you've considered**
The current alternative is only the query builder but even with this, it's very difficult to use.

**Additional context**
Add any other context about the feature request here.

**Comment by B4nan** [comment]
> We would want to allow a single input search for all users where we use text box with an auto-complete list based on the single input. Today, we can do this via Custom query builder and for such complex query, it can get very messy, difficult to read/write and we will need to write SQL statement manually which defeats the essence of MikroORM.

Not really, today the solution is to use [custom query fragments](https://mikro-orm.io/docs/entity-manager/#using-custom-sql-fragments), which are available in the EM api too (so in `em.find/findOne/...`). For me that is better than trying to map every possible sql/nosql functions in code. 

> we will need to write SQL statement manually which defeats the essence of MikroORM.

I disagree especially with this part. ORM is to allow easy mapping, it does not mean you should never use raw SQL, those two can play nice together via SQL fragments. 

Closing as I am not interested in implementing this. Maybe in the long run (v6+), but right now this is out of scope for this project. 

Interesting alternative to this approach would be using `@Formula`, but that is currently not supported for conditions, only for selects (see #1599).
