### ISSUE TITLE
Bug: Wrong query being built when in presence of foreign key

### ISSUE THREAD

**Issue by juan-restrepo** [mikro-orm/mikro-orm#2057]
**Describe the bug**
This is the meaningful part of the entity causing trouble:

```ts
@Entity()
export class UserTask2 extends BaseEntity<UserTask2, 'id'> {
  @PrimaryKey()
  id!: number;

  @Property({ type: 'jsonb', nullable: true })
  metadata?: Record<string, any>;

  @ManyToOne('App')
  app: App;

  constructor({ metadata, app }: { metadata: Record<string, any>; app: App }) {
    super();
    this.metadata = metadata;
    this.app = app;
  }

  public static async fetchTasks({
    em,
    app,
  }: {
    em: EntityManager;
    app: App;
  }): Promise<UserTask2[]> {
    // const filterQuery: FilterQuery<UserTask> = {
    //   app,
    // };
    // const filterQuery: any = {};
    const filterQuery: any = {
      app,
    };
    filterQuery.metadata = {
      $contains: { vin: '1N6AD0EV8FN737744' },
    };
    const tasks: UserTask2[] = await em.find(UserTask2, filterQuery);
    return tasks;
  }
}
```

Whenever I try to use the method `fetchTasks`, I get an error saying the property "vin" does not exist on the model...which I know it doesn't. But it shouldn't be constructing the query that way. If I silence the error and inspect what query is being built, it yields:
```
  knex:client acquired connection from pool: __knexUid1 +979ms
  knex:client releasing connection to pool: __knexUid1 +2ms
[query] select "e0".* from "user_task2" as "e0" where "e0"."app_id" = 1 and "e0"."metadata" @> '{"e0.vin":"1N6AD0EV8FN737744"}' [took 2 ms]
```
where we can see that it is actually trying to do something very strange.

When I remove the `App` part of the filter query, this is the query that is built:
```
  knex:client acquired connection from pool: __knexUid1 +867ms
  knex:client releasing connection to pool: __knexUid1 +2ms
[query] select "e0".* from "user_task2" as "e0" where "e0"."metadata" @> '{"vin":"1N6AD0EV8FN737744"}' [took 2 ms]
```
which just works fine!

**Stack trace**
```
Trying to query by not existing property UserTask2.vin. Trace
Error: Trying to query by not existing property UserTask2.vin
    at /Users/juan/pact/user-task-service/node_modules/@mikro-orm/knex/query/CriteriaNode.js:27:27
    at Array.forEach (<anonymous>)
    at new CriteriaNode (/Users/juan/pact/user-task-service/node_modules/@mikro-orm/knex/query/CriteriaNode.js:18:48)
    at new ScalarCriteriaNode (/Users/juan/pact/user-task-service/node_modules/@mikro-orm/knex/query/ScalarCriteriaNode.js:6:1)
    at Function.createScalarNode (/Users/juan/pact/user-task-service/node_modules/@mikro-orm/knex/query/CriteriaNodeFactory.js:22:22)
    at Function.createNode (/Users/juan/pact/user-task-service/node_modules/@mikro-orm/knex/query/CriteriaNodeFactory.js:19:21)
    at Function.createObjectItemNode (/Users/juan/pact/user-task-service/node_modules/@mikro-orm/knex/query/CriteriaNodeFactory.js:47:25)
    at /Users/juan/pact/user-task-service/node_modules/@mikro-orm/knex/query/CriteriaNodeFactory.js:38:28
    at Array.reduce (<anonymous>)
    at Function.createObjectNode (/Users/juan/pact/user-task-service/node_modules/@mikro-orm/knex/query/CriteriaNodeFactory.js:37:45)
```

**To Reproduce**
1. Create a model called App with an int primary key
2. Create a model as described in the bug description
3. Attempt to use the function `fetchTasks`

**Expected behavior**
This is the query I would expect to see:
```
  knex:client acquired connection from pool: __knexUid1 +979ms
  knex:client releasing connection to pool: __knexUid1 +2ms
[query] select "e0".* from "user_task2" as "e0" where "e0"."app_id" = 1 and "e0"."metadata" @> '{"vin":"1N6AD0EV8FN737744"}' [took 2 ms]
```

**Additional context**
The models I actually have have a lot more properties, but I was able to reproduce this error with just this submodel.

**Versions**

| Dependency | Version |
| - | - |
| node | v12.18.4 |
| typescript | 4.3.4 |
| mikro-orm | 4.5.6 |
| your-driver | pg |

**Comment by B4nan** [comment]
You need to use `type: 'json'` or specify `type: JsonType`. `type` is for runtime type, not for the database specific column type (`columnType` option). `type: 'json'` maps to `jsonb` column type in postgres.

```ts
  @Property({ type: 'json', nullable: true })
  metadata?: Record<string, any>;

  // or

  @Property({ type: JsonType, nullable: true })
  metadata?: Record<string, any>;
```

(you can still control the column type via additional `columnType` option, but as mentioned above, for `jsonb` this is enough as it is the default in pg)

**Comment by juan-restrepo** [comment]
OMG. I need to change all my (very few) `jsonbs` now. I believe this was the first time I actually had to use the column for querying, and everything had worked well up to that point. I implemented the first models when v4 wasn't out yet, so I had totally skipped the neat part of the documentation where you talked about `JsonType`, and I wrongly assumed i had to type it as `jsonb` for it to be that in Postgres.

Hopefully this closed issue might help someone else who missed that!

I was really confused with the behavior, but I guess it serializes a "jsonb" in a strange way when there is the presence of an FK only

Thanks for quick turn around!

**Comment by B4nan** [comment]
i'll definitely spend some time improving the docs before v5 is out, this should be mentioned/linked in the defining entities page too, and i hope that with the new [`t` type map](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/types/index.ts#L29) it will be easier thanks to autocomplete. in the end we can add the `jsonb` key there as well (resolving to the same `JsonType`)
