### ISSUE TITLE
Insert queries are incorrect or throw error if multiple queries are executed at he same time

### ISSUE THREAD

**Issue by jsprw** [mikro-orm/mikro-orm#206]
**Describe the bug**
Queries end up wrong if multiple queries are ran at the same time. 

For example:
A website that makes multiple API-calls from multiple HTTP requests at the same time and each url is logged.

This function that is called as an Express middleware with an entitiy that wraps req.url

```
//middleware
console.log('inserting', req.url);
service.insertVisit(
    wrap(new Visit()).assign({ url: req.url})
);
return next();

//service
async insertVisit(visit: Visit): Promise<void> {
    const repository = (await Database.getConnection()).em.getRepository(
        Visit
    );

    console.log(visit.url);

    return repository.persistAndFlush(visit);
}
```
Produces the following log (look at the incorrect queries, in the database it has the wrong urls too):

```
inserting /api3/call1 //middleware
[query] select `e0`.* from `sessions` as `e0` where `e0`.`id` = 1limit 1 [took 50 ms]
/api3/call1 //service
[query] begin
Visit //log from abstract sql driver in native insert
[query] insert into `visits` (`url`) values ('/api3/call1') [took 50 ms]
[query] commit
inserting /api3/call2
/api3/call2
inserting /api3/call3
/api3/call3
inserting /api3/call4
/api3/call4
[query] begin
[query] begin
[query] begin
Visit  //log from abstract sql driver in native insert
Visit //log from abstract sql driver in native insert
Visit //log from abstract sql driver in native insert
[query] insert into `visits` (`url`) values ('/api3/call4') [took 1645 ms]
[query] insert into `visits` (`url`) values ('/api3/call4') [took 1635 ms]
[query] insert into `visits` (`url`) values ('/api3/call4') [took 1645 ms]
[query] commit
[query] commit
[query] commit
```

or even throws an error (seems inconsistent; sometimes after first refresh, sometimes it takes 4):

```
Unhandled Promise rejection: Cannot read property 'setValue' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'setValue' of undefined
    at ChangeSetPersister.persistEntity (C:\Users\XX\Repositories\XXProj\node_modules\mikro-orm\dist\unit-of-work\ChangeSetPersister.js:41:57)
    at ChangeSetPersister.persistToDatabase (C:\Users\XX\Repositories\XXProj\node_modules\mikro-orm\dist\unit-of-work\ChangeSetPersister.js:19:9)
    at UnitOfWork.commitChangeSet (C:\Users\XX\Repositories\XXProj\node_modules\mikro-orm\dist\unit-of-work\UnitOfWork.js:189:9)
    at Function.runSerial (C:\Users\XX\Repositories\XXProj\node_modules\mikro-orm\dist\utils\Utils.js:209:22)
    at promise (C:\Users\XX\Repositories\XXProj\node_modules\mikro-orm\dist\unit-of-work\UnitOfWork.js:81:39)
    at C:\Users\XX\Repositories\XXProj\node_modules\mikro-orm\dist\connections\AbstractSqlConnection.js:30:23 TypeError: Cannot read property 'setValue' of undefined
    at ChangeSetPersister.persistEntity (C:\Users\XX\Repositories\XXProj\node_modules\mikro-orm\dist\unit-of-work\ChangeSetPersister.js:41:57)
    at ChangeSetPersister.persistToDatabase (C:\Users\XX\Repositories\XXProj\node_modules\mikro-orm\dist\unit-of-work\ChangeSetPersister.js:19:9)
    at UnitOfWork.commitChangeSet (C:\Users\XX\Repositories\XXProj\node_modules\mikro-orm\dist\unit-of-work\UnitOfWork.js:189:9)
    at Function.runSerial (C:\Users\XX\Repositories\XXProj\node_modules\mikro-orm\dist\utils\Utils.js:209:22)
    at promise (C:\Users\XX\Repositories\XXProj\node_modules\mikro-orm\dist\unit-of-work\UnitOfWork.js:81:39)
    at C:\Users\XX\Repositories\XXProj\node_modules\mikro-orm\dist\connections\AbstractSqlConnection.js:30:23
``` 
or sometimes doesn't even execute queries for call2 and call3.

**Expected behavior**
No errors and properly inserted data.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 12.9.1. |
| typescript | 3.5.3 |
| mikro-orm | 3.0.0-alpha.29 |
| your-driver | mysql2 |

**Comment by B4nan** [comment]
> Queries end up wrong if multiple queries are ran at the same time.

You can't run multiple queries in parallel like this, you need to fork the entity manager to create new contexts.

If this is just about multiple requests (and not running multiple parallel queries inside single request), than make sure you are using `RequestContext` as that should be handled automatically. 

https://mikro-orm.io/identity-map/

**Comment by B4nan** [comment]
For this particular use case, do this:

```typescript
async insertVisit(visit: Visit): Promise<void> {
    const orm = await Database.getConnection();
    console.log(visit.url);

    await orm.em.fork().persistAndFlush(visit);
}
```

That way you will create new context where you persist the `Visit` entity, without polluting the global/request scoped context.

You could also use `em.nativeInsert()` just to save the entity, without touching the context (identity map).

**Comment by jsprw** [comment]
Yes! This works. 

So it would be more reliable if I create a new fork for each request that comes in? (And store it in req.database f.e.?)

**Comment by B4nan** [comment]
Yeah you should definitely use dedicated contexts (identity maps) for each request. 

In v3 docs there is also a section about why the context is needed and what can happen if you do not use it. 

As I said, for the general request context, the helper is enough and everything should work automagically:

```typescript
app.use((req, res, next) => {
  RequestContext.create(orm.em, next);
});
```

What this does is to register new EM fork with current request, and this fork will be used internally instead of the global EM instance (the one created when calling `MikroORM.init()`). It also works for repositories, so it comes really handy if you use some DI system like inversify or the one in nestjs. 

If you do not use any DI system, you can definitely fork the EM manually and assign it to the `req` object. Just don't forget to use this EM instead of the global one. 

But for the OP problem with running queries in middleware, you still need to fork manually.

**Comment by B4nan** [comment]
I guess we can close this now, or do you have more question about this topic?

**Comment by jsprw** [comment]
Yes, this can be closed for now. Looks very clear now. Will implement it when home, thank you once again :)
