### ISSUE TITLE
Get results count using query builder

### ISSUE THREAD

**Issue by angelvega93** [mikro-orm/mikro-orm#2066]
It would be great if we could get results count using the query builder, currently it seems not to be possible

For example:

```ts
const qb = ctx.em.createQueryBuilder(...).where(...);

let result = qb.getResult();
let total = qb.getCount();

await Promise.all([results, total]);
```

**Comment by B4nan** [comment]
Just use qb.execute()

**Comment by angelvega93** [comment]
Yes, currently im doing this: 
```ts
const total = (await qb.select("count(*) as total").execute("get"))?.total;
const result = await qb.select(...).limit(limit).offset(offset).execute();
```

but it would be nice and cleaner if we could just use getCount like TypeORM

https://github.com/typeorm/typeorm/blob/7a0f7733f2cf704d60548a6b15d1fa2977a9e401/src/query-builder/SelectQueryBuilder.ts#L1141

**Comment by B4nan** [comment]
I said you should use `execute` to read the results, there is already `qb.count()` method. Correct way is:

```ts
const res = await qb.count().where(...).execute(); // `res.count` is the count
```

But sure, we can have `getCount()` too in v5.
