### ISSUE TITLE
Left join on expression

### ISSUE THREAD

**Issue by evantrimboli** [mikro-orm/mikro-orm#2071]
**Is your feature request related to a problem? Please describe.**
I'm trying to construct a query where I'm pulling a list of posts. For each post, I want to also join to the most recent comment if it exists.

**Describe the solution you'd like**
I would like to be able to do something like this:

```ts
const recent = em
  .createQueryBuilder(Comment)
  .select('id')
  .limit(1)
  .orderBy({
    timestamp: QueryOrder.DESC
  })
  .where({
    post: knex.ref('p.id')
  });
const qb = em
  .createQueryBuilder(Post, 'p')
  .leftJoinAndSelect('comments', 'c', {
    'c.id': recent
  });
```

**Describe alternatives you've considered**
Using raw knex, it's still a bit difficult to do joins via subqueries.

Also tried passing the underlying sql query:

```ts
const qb = em
  .createQueryBuilder(Post, 'p')
  .leftJoinAndSelect('comments', 'c', {
    'c.id': recent.getKnexQuery().toQuery()
  });
```

**Additional context**
The above sample code very nearly works, the issue is that the condition it generates for the subquery is quoted.

```sql
select "c"."id" as "c__id", "c"."post_id" as "c__post_id", "c"."timestamp" as "c__timestamp" from "post" as "p" left join "comment" as "c" on "p"."id" = "c"."post_id" and "c"."id" = 'select "e0"."id" from "comment" 
as "e0" where "e0"."post_id" = "p"."id" order by "e0"."timestamp" desc limit 1'
```

Replacing the quotes with parentheses fixes the query and all is well.

**Comment by B4nan** [comment]
When working with subqueries, it should be a knex instance, not a string query. Try this instead:

```ts
const qb = em
  .createQueryBuilder(Post, 'p')
  .leftJoinAndSelect('comments', 'c', {
    'c.id': recent.getKnexQuery()
  });
```

This might also work:

```ts
const qb = em
  .createQueryBuilder(Post, 'p')
  .leftJoinAndSelect('comments', 'c', {
    'c.id': recent.raw(recent.getFormattedQuery())
  });
```

**Comment by evantrimboli** [comment]
You're absolutely right and was sure that I had tried that.

`recent.getKnexQuery()` does the trick. Thanks.
