### ISSUE TITLE
[BUG] - Duplicate sql command when generating migration with cli

### ISSUE THREAD

**Issue by hnxb** [mikro-orm/mikro-orm#2072]
**Describe the bug**
Duplicate sql command when generating migration with cli

**To Reproduce**
1. Create an entity:
```typescript
@Entity()
export class UserEntity {
  @PrimaryKey()
  id!: number;

  @Property()
  email!: string;
}
```
2. Run `npx mikro-orm migration:create --initial`
3. Update entity:
```typescript
@Entity()
export class UserEntity {
  @PrimaryKey()
  id!: number;

  @Property({ unique: true })
  email!: string;

  @Property({ unique: true })
  token?: string;
}
```
4. Run `npx mikro-orm migration:create`
5. Repo: https://github.com/hnxb/mikro-orm-issues

**Expected behavior**
New `Migration.ts` file has duplicated commands:
```typescript
this.addSql('alter table "user_entity" add column "token" varchar(255) null;');
// this line 👇
this.addSql('alter table "user_entity" add constraint "user_entity_token_unique" unique ("token");');

this.addSql('alter table "user_entity" add constraint "user_entity_email_unique" unique ("email");');

// ... and this line 👇
this.addSql('alter table "user_entity" add constraint "user_entity_token_unique" unique ("token");');
```

**Versions**

| Dependency | Version |
| - | - |
| node | v14.16.0 |
| typescript | ^4.1.5 |
| mikro-orm | ^4.5.7 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
You need to execute the migrations first via `up` command, otherwise you always get the same result. This is already fixed in v5, where we have a migration snapshots (#1815).

**Comment by hnxb** [comment]
@B4nan Hi, I was missing 1 step to reproduce. Actually I executed `npx mikro-orm migration:up` before I updated the entity, but a new `Migration.ts` file still has 2 token constaint line.

**Comment by B4nan** [comment]
Most probably fixed in v5 anyway, the schema diffing is completely reworked.
