### ISSUE TITLE
Separate Migration into subdirectories

### ISSUE THREAD

**Issue by randyyaj** [mikro-orm/mikro-orm#2076]
Currently you can create a migration through the CLI and it will produce a MigrationTS.ts file in a specified migrations directory where it'll run all the sql inside that file. 

Is there an example or way to easily configure mikroORM to discover migrations in a structure similar to the one below
Where the migrations.ts file will addSql by reading from the sql files instead.
```
migrations/
  | Migration20210731000000/
    - tables.sql
    - insert.sql
    - functions.sql
    - Migration20210731000000.ts
  | Migration2021080100000/
    - tables.sql
    - insert.sql
    - functions.sql
    - Migration2021080100000.ts
```

**Comment by B4nan** [comment]
Nope, not supported, not planned.
