### ISSUE TITLE
Hydrate props before call entity constructor

### ISSUE THREAD

**Issue by fabiocastrodev** [mikro-orm/mikro-orm#2080]
**Describe the bug**
My constructor receives the entity's properties, but it has custom types that are crudely passed to the constructor. I noticed that the data is hydrated after creating the entity instance, but as these properties only have public getters and not setters for design reasons, the custom type value is not correctly assigned to the instance.

**To Reproduce**
1. Create an entity class with private custom type property and only create public getters
2. Set a value to property in constructor
3. See the raw data and not custom type
![image](https://user-images.githubusercontent.com/23401350/127726408-03ab9561-2a3a-472b-80cd-5c2c73fa581a.png)

**Expected behavior**
I imagine the properties could be hydrated before being passed on to the constructor

**Versions**

| Dependency | Version |
| - | - |
| node |  v15.0.1 |
| typescript | 4.2.4 |
| mikro-orm | 4.5.7 |

**Comment by B4nan** [comment]
You are responsible for filling the contructor parameters yourself, the ORM never calls it, with a single exception which is `em.create()` - and still, even with that use case, you are the one who needs to ensure wellformed input.

Maybe I misunderstood it, next time please dont use screenshots and provide actual code that reproduces something, not just entity definition (this is not even entity definition, right? no decorators or `EntitySchema`)
