### ISSUE TITLE
MikroORM v5 - EntityDTO<any[]> does not have array properties

### ISSUE THREAD

**Issue by ThatOneAwkwardGuy** [mikro-orm/mikro-orm#2082]
**Describe the bug**
When wrapping an array type with EntityDTO, the methods of a normal array e.g join, map, forEach. etc are not on the type, only the length property is on the type.

**Stack trace**
N/A

**To Reproduce**
1. Code is shown in additional context

**Expected behavior**
I would expect EntityDTO<string[]> to have the join, map, forEach attributes on them.

**Additional context**
```
export type test = EntityDTO<string[]>;
export type test2 = test['length'];
```
Switching the EntityDTOProp from below:
```
export declare type EntityDTOProp<T> = T extends Scalar ? T : T extends Reference<infer U> ? EntityDTO<U> : T extends Collection<infer U> ? EntityDTO<U>[] : T extends {
    $: infer U;
} ? (U extends readonly (infer V)[] ? EntityDTO<V>[] : EntityDTO<U>) : T extends Relation<T> ? EntityDTO<T> : T;
```
to
```
export declare type EntityDTOProp<T> = T extends Scalar ? T : T extends Reference<infer U> ? EntityDTO<U> : T extends Collection<infer U> ? EntityDTO<U>[] : T extends {
    $: infer U;
} ? (U extends readonly (infer V)[] ? EntityDTO<V>[] : EntityDTO<U>) : T extends Relation<T> ? T : EntityDTO<T>;
```

Fixes the problem, by returning EntityDTO<T> as the last resort instead of T. I'm unsure if this breaks any typings on your end though :)

**Versions**

| Dependency | Version |
| node | v12.22.1 |
| typescript | 4.3.5 |
| @mikro-orm/core| ^5.0.0-dev.264 |
| @mikro-orm/mongo-highlighter| ^1.0.0 |
| @mikro-orm/mongodb| ^5.0.0-dev.264 |
| @mikro-orm/nestjs| ^4.2.0 |
| @mikro-orm/reflection| ^5.0.0-dev.264 |

**Comment by B4nan** [comment]
I don't follow, why would you use `EntityDTO`, a type for _entity DTOs_ (= objects), on an array of anything (scalar type like _string_ especially)? Can you provide some less artificial reproduction that shows the real use case?

**Comment by ThatOneAwkwardGuy** [comment]
I initially applied it to an object, EntityDTO is then applied recursively to its attributes, one of the attributes was an array. e.g.:

```
export type test = EntityDTO<{ test: string[] }>;
export type test2 = test["test"][""] <-- only the length attribute is available
```

**Comment by B4nan** [comment]
I see, makes sense. But your proposed change looks weird to me.
