### ISSUE TITLE
Log raw knex queries

### ISSUE THREAD

**Issue by notmedia** [mikro-orm/mikro-orm#2086]
While query in debug options passed we could also loging raw knex queries to the database via mikroorm logger handler.

**Comment by B4nan** [comment]
Can you be more specific? The issue template has a purpose, I have no idea what would you like to change. 

Currently you can either log the queries with wildcards via `debug: ['query']` or full formatted queries including parameter values via `debug: ['query', 'query-params']` (or via `debug: true`).

**Comment by notmedia** [comment]
Sure, when I'm using knex for quering database the query not auto logging.

For example 

```ts
  getCustomQuery(): Knex.QueryBuilder<CustomQueryResult> {
    const knex = this.em.getKnex();

    return knex
      .first()
      .from(***)
      .where(***);
  }
```

To log this query I can write something like this

```
  getCustomQuery(): Knex.QueryBuilder<CustomQueryResult> {
    const knex = this.em.getKnex();

    const query = knex
      .first()
      .from(***)
      .where(***);

  this.logger.trace(query.toString());

  return query;
  }
```

But on mikro-orm init I also have `debug` and `logger` option and I think that this can be done with that definitions inside mikro-orm

**Comment by B4nan** [comment]
I see, if you want logs from that, you need to execute knex via the ORM.

```ts
const qb = knex.first...;
const res = await em.execute(qb);
```

I don't think it is a good idea to blindly log every query done by knex - we would have to somehow distinguish what query is already logged by MikroORM and what was done directly via knex.
