### ISSUE TITLE
Using a custom integer array type in postgres results in the migration generator to always include alter statements

### ISSUE THREAD

**Issue by co-sic** [mikro-orm/mikro-orm#2092]
**Describe the bug**
I have exactly the same problem as was described here #713. I looked into the implementation of the ArrayType, but i want to have an `integer[]` type in postgres instead of the default `text[]` type which comes from the mikro-orm ArrayType. So i created my custom type which returns `integer[]` for the `getColumnType` method and everything works fine. But as described in the other issue if i run migration:create there is always a new migration with the same content:

```typescript
this.addSql('alter table "contract_change" drop constraint if exists "contract_change_plan_employees_check";');
this.addSql('alter table "contract_change" alter column "plan_employees" type integer[] using ("plan_employees"::integer[]);');
```

**Versions**

| Dependency | Version |
| - | - |
| node | v14.17.1 |
| typescript | 4.3.5|
| mikro-orm | 4.5.7 |

**Comment by B4nan** [comment]
that's because the type name is not `integer` but `int4`. you need to use the name that will be stored in the information schema, not its alias. 

you can verify how the type is stored in `information_schema.columns` table, in the `udt_name` column

**Comment by co-sic** [comment]
Thanks for the quick response and explanation, that worked!
