### ISSUE TITLE
Nested Embeddables Not Updating

### ISSUE THREAD

**Issue by ThatOneAwkwardGuy** [mikro-orm/mikro-orm#2094]
**Describe the bug**
Nested Embeddables inside of an array are not updating for some reason. I've marked this as a bug because I've checked my entire schema for a day, and now feel like it's likely a mikro-orm issue.

**Stack trace**
```
```

Definitions (I removed some attributes to save space)
```
@Embeddable()
export class DivorceCaseChildrenOrDependantsSurveyChildren {
  @ApiProperty()
  @Property()
  firstName: string;

  @ApiProperty()
  @Property()
  lastName: string;
}

@Embeddable()
export class DivorceCaseChildrenOrDependantsSurveyData {
  @ApiProperty()
  @Embedded(() => DivorceCaseChildrenOrDependantsSurveyChildren, {
    array: true,
  })
  children: DivorceCaseChildrenOrDependantsSurveyChildren[] = [];
}

@Entity({
  collection: CollectionsEnum.SURVEYS,
})
export class DivorceCaseChildrenOrDependantsSurvey extends BaseSurvey {
  /**Static values */
  surveyDataType: SurveyDataTypeEnum.DIVORCE_CASE_CHILDREN_OR_DEPENDANTS =
    SurveyDataTypeEnum.DIVORCE_CASE_CHILDREN_OR_DEPENDANTS;

  /**Other values */
  @ApiProperty()
  @Property()
  completed?: boolean;

  @ApiProperty()
  @Embedded(() => DivorceCaseChildrenOrDependantsSurveyData, { object: true })
  data: DivorceCaseChildrenOrDependantsSurveyData;
}
```

These are logs from NestJS, I console.log the data attribute before and after the assign call. As we can see, the entity is updated, however, when I call persistAndFlush, no updateMany is called (using MongoDB).

```
[0] DivorceCaseChildrenOrDependantsSurveyData {
[0]   hasChildren: true,
[0]   numberOfChildren: 1,
[0]   children: [ DivorceCaseChildrenOrDependantsSurveyChildren {} ]
[0] }
[0] DivorceCaseChildrenOrDependantsSurveyData {
[0]   hasChildren: true,
[0]   numberOfChildren: 1,
[0]   children: [
[0]     DivorceCaseChildrenOrDependantsSurveyChildren {
[0]       firstName: 'Testing',
[0]       lastName: 'Testing'
[0]     }
[0]   ]
[0] }
```

**To Reproduce**
1. Definitions provided above.

**Expected behavior**
I would expect the data to be persisted into the DB or some error to be thrown telling me what is wrong. As far as I can see from the server-side, the data is in the correct format even after the assign call. It's just the persistAndFlush call that is doing nothing.

 

**Versions**
| Dependency | Version |
| node | v12.22.1 |
| typescript | 4.3.5 |
| @mikro-orm/core| ^5.0.0-dev.277 |
| @mikro-orm/mongo-highlighter| ^1.0.0 |
| @mikro-orm/mongodb| ^5.0.0-dev.277 |
| @mikro-orm/nestjs| ^4.2.0 |
| @mikro-orm/reflection| ^5.0.0-dev.277 |
| @nestjs/common | 8.0.6 |
| @nestjs/core | 8.0.6 |
| @nestjs/passport | 8.0.1 |
| @nestjs/platform-express | 8.0.6 |
| @nestjs/platform-socket.io | 8.0.6 |
| @nestjs/serve-static | ^2.2.2 |
| @nestjs/swagger | 5.0.9 |
| @nestjs/websockets | 8.0.6 |

**Comment by B4nan** [comment]
Please provide reproduction, not just (incomplete) entity definitions. Also some more readable entity names would be welcome.

**Comment by ThatOneAwkwardGuy** [comment]
> Please provide reproduction, not just (incomplete) entity definitions. Also some more readable entity names would be welcome.
> 
> Ideally try to reproduce it with existing ORM tests:
> 
> [https://github.com/mikro-orm/mikro-orm/tree/master/tests/features/embeddables](https://github.com/mikro-orm/mikro-orm/tree/master/tests/features/embeddables?rgh-link-date=2021-08-06T16%3A29%3A00Z)

Quick question, the order of the entities array for MikroOrmModule.forRoot doesn't matter does it?

**Comment by B4nan** [comment]
It should not, but it might (in such case it would be buggy behaviour).
