### ISSUE TITLE
OrderBy doesn't work properly using populate, paginate flag, filters and semi-complex hierarchies

### ISSUE THREAD

**Issue by jamesmeneghello** [mikro-orm/mikro-orm#2095]
**Describe the bug**

Using Postgresql:

Attempting to fetch an offset list of entities using `QueryFlag.PAGINATE`, `populate`, entity-level filters ordered by a field will return incorrectly-ordered results - e.g. results sorted by date will return the first 20 results ordered correctly, but the second 20 results will include results that should've appeared in the first set (in terms of order).

This is basically to be used by server-side limit/offset pagination into a data grid, so when somebody sorts the grid it should order the results correctly across pages. Currently, fetching the second page returns results that order-wise should've been in the first set of results.

Not using the `QueryFlag.PAGINATE` flag results in duplicate rows (and hence less than the full number once duplicates are removed), so the flag must be used.

**To Reproduce**

Reproduction in test form here: https://github.com/jamesmeneghello/mikro-orm/blob/bug/pagination-order/tests/issues/GH2095.test.ts

**Expected behavior**

Expected each page of results to be ordered correctly when retrieving them.

**Additional context**

This took a surprisingly long time to reproduce.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.5 |

Other dependencies per mikro-orm.

**Comment by jamesmeneghello** [comment]
Just a bit more on this - moving the limit/offset calls to `subQuery` instead of `subSubQuery` in `wrapPaginateSubQuery` returns the correct results, but breaks a tonne of other tests, so there's probably a bunch of nuance I'm missing.

It's also not reproducible with just the three basic entities (C/TC/T), implying the problem is either due to the recursive-ish relationship through A/B, or something to do with eager loading.

**Comment by B4nan** [comment]
Wow, that's quite complex reproduction :]

**Comment by jamesmeneghello** [comment]
@B4nan are you actively working on this, or were you waiting for me to? It's becoming reasonably critical for us so I'll need to jump in if it's not on your radar, it'll just take me a long longer to fix :sweat_smile:

**Comment by B4nan** [comment]
I spent few hours on this but failed to find the right fix. So not really waiting for you, but having other things to work on. Any help will be appreciated :]

**Comment by jamesmeneghello** [comment]
I'll see if I can find some time to take a look this weekend, but I probably won't be successful :c

**Comment by zhirnov-av** [comment]
Hi, ALL. I guess I have a same bug. 
When I use 2 entities with m2m relation, and want to paginated result set, ordering of entities works incorrect. 
If I use flag DISTINCT, instead PAGINATE all works correctly, but in some cases I need to use in entity JSON fields. And in this case PostgreSQL returns error, which talk what can't use DISTINCT with JSON fields. 

I also prepared tests which reproduce this bug: https://github.com/zhirnov-av/mikro-orm/blob/bug/pagination/tests/issues/GH2095.test.ts

PS. I use postgresql, node version: 14.17.0

**Comment by kirdk** [comment]
+1!
We also faced this issue. No way to implement pagination correctly. Hope the solution will be found.

**Comment by jamesmeneghello** [comment]
PR opened. I took my tests and @zhirnov-av's and mashed them together. All of those, plus every other other test, is successful. This definitely needs sense-checking, because it's deep enough SQL that I have no idea what it really should be doing.

**Comment by jamesmeneghello** [comment]
Thanks :)

**Comment by B4nan** [comment]
Thanks to you!
