### ISSUE TITLE
MigrationsList needs to install other deps

### ISSUE THREAD

**Issue by Nisgrak** [mikro-orm/mikro-orm#2096]
**Describe the bug**
If you use the `migrationList` option it fails with a bunch of needed packages

**Stack trace**
![image](https://user-images.githubusercontent.com/19597708/128538517-8968bfb4-4ec5-4f24-924b-ee6722b6acb5.png)

**To Reproduce**
1. Don't use the migration:path option
2. Set the migrationList
3. ...

**Expected behavior**
Works like if I set the migration:path option

**Versions**

| Dependency | Version |
| - | - |
| node | 14.17 |
| typescript | 4.3.5 |
| mikro-orm | 4.5.7 |
| sqlite | 4.5.7 |

**Comment by B4nan** [comment]
I really doubt it, those are dependencies of knex mostly, MikroORM is not dependent on mssql at all. Also how could changing ORM configuration  have any effect on installations? 

Please provide full repro, but this will be most probably some misconfiguration. I guess you are using webpack or something like that, if you see those?

**Comment by Nisgrak** [comment]
I use webpack yes, i'm want to use the `migrationList` because of that

**Comment by B4nan** [comment]
Yes, you use webpack. And you have it misconfigured. This is not about how you configure the ORM, this is about your webpack configuration. 

https://mikro-orm.io/docs/deployment/#webpack-configuration

please note this is not a copy paste config for you, it is an example, you will need to adjust it based on what driver you use. 

Cant help more with webpack myself.
