### ISSUE TITLE
TypeError with EntityManager functions.

### ISSUE THREAD

**Issue by Tpuljak** [mikro-orm/mikro-orm#2100]
**Describe the bug**
When trying to query the entity manager, Typescript seems to always default to the Primary key typing instead of the `where` object filter (`Query<T>`). 

**To Reproduce**
Install the latest version of mikroorm and create a file with the following code:
```javascript
import { Entity, EntityManager, PrimaryKey, Property } from "@mikro-orm/core";

@Entity()
class User {
  @PrimaryKey()
  id: string

  @Property()
  username: string
}

class UserService {
  constructor(private readonly entityManager: EntityManager) {

  }

  public async getUserByUsername(username: string) {
    return await this.entityManager.findOne(User, {
      username
    })
  }
}
```

Typescript will throw the following error:
```
No overload matches this call.
  Overload 1 of 2, '(entityName: EntityName<User>, where: FilterQuery<User>, options?: FindOneOptions<User, any> | undefined): Promise<...>', gave the following error.
    Argument of type '{ username: string; }' is not assignable to parameter of type 'FilterQuery<User>'.
      Type '{ username: string; }' is not assignable to type 'string'.
  Overload 2 of 2, '(entityName: EntityName<User>, where: FilterQuery<User>, populate?: any, orderBy?: QueryOrderMap | undefined): Promise<User | null>', gave the following error.
    Argument of type '{ username: string; }' is not assignable to parameter of type 'FilterQuery<User>'.
      Type '{ username: string; }' is not assignable to type 'string'.ts(2769)
```
As you can see from the following screenshot, autocomplete seems to work fine for the method but when I enter the `username` an error is thrown.
![Screenshot 2021-08-09 at 16 47 07](https://user-images.githubusercontent.com/26512078/128725920-1bd8228a-4bec-4103-9835-09e6bf6f07a0.png)

**Expected behavior**
The expected behaviour is that the query passes the type check since it is valid and autocomplete works as expected and it works in multiple other projects.

**Additional context**
I've tried downgrading the Typescript version, downgrading mikroorm, but nothing seems to work.

**Versions**

| Dependency | Version |
| - | - |
| node | v12.22.4 |
| typescript | 4.3.5 |
| mikro-orm | 4.5.7 |
| your-driver | MySQL |

**Comment by B4nan** [comment]
Not reproducible, my guess is this is vscode issue and actual TS build will work just fine.

**Comment by lineCode** [comment]
has solution?

**Comment by Tpuljak** [comment]
I think what ended up happening is that I had a mismatch between package version. Check that all mikroorm version are the same in your repo and that TS is up to date.
