### ISSUE TITLE
Schema generator creates JSONB column for nullable string property

### ISSUE THREAD

**Issue by maxsommer** [mikro-orm/mikro-orm#2101]
**Describe the bug**
Schema generator creates `jsonb` type column for nullable string property.

**Stack trace**
/

**To Reproduce**
1. Define entity with the following property
```ts
@Property({ nullable: true })
ownerId: string | null = null;
```
2. Let schema generator dump create queries
```sh
npx mikro-orm schema:create -d
```
 and find
```sh
"owner_id" jsonb null
```
as column definition.

**Expected behavior**
Column type `varchar(255) null` 

**Additional context**
- postgres database

**Versions**

| Dependency | Version |
| - | - |
| node | v16.6.0 |
| typescript | 4.3.5 |
| mikro-orm | 4.5.7 |
| @mikro-orm/postgresql | 4.5.7 |

**Comment by B4nan** [comment]
You need to specify the type in decorator options, or use ts-morph metadata provider. Inference from reflect-metadata can never work with union types.
