### ISSUE TITLE
Add "propagateCreateError" and "createRetryIntervalMillis" parameters to PoolConfig

### ISSUE THREAD

**Issue by srgg** [mikro-orm/mikro-orm#2108]
Here is a Knex  issue that can be solved by setting  propagateCreateError to "false": 

https://github.com/knex/knex/issues/2820

**Comment by B4nan** [comment]
care to send a PR? 😉

**Comment by srgg** [comment]
Sure, I'll make it on this weekend.

**Comment by B4nan** [comment]
I reviewed the issue you linked and it seems like this is not suggested by knex team and should not be publicly configurable. 

No plans to add configuration that is not publicly exposed by knex (especially when its discouraged by their maintainers, see https://github.com/knex/knex/issues/3455), but if its just about the typings, you can always get around that via type casting.

**Comment by elhigu** [comment]
> Here is a Knex issue that can be solved by setting propagateCreateError to "false":

No it cannot. That should never be set to false with knex. It just hides the errors and increases delay when client notices that something is wrong. Knex is designed a way that it should be set true.
