### ISSUE TITLE
Support for ArangoDB

### ISSUE THREAD

**Issue by cardimajs** [mikro-orm/mikro-orm#212]
Awesome project,
this project have plans to add support to other databases?
will be nice to have support for ArangoDB?

Thank you.

**Comment by B4nan** [comment]
Hey there, I am not planning to add support for that natively, but you can implement custom driver. I am open for changes in the core if needed so more databases can be supported, but it should be doable right now I would say.

**Comment by B4nan** [comment]
There is some information here: https://mikro-orm.io/custom-driver/

Took a quick look at their docs, the node driver looks similar to mongodb, so I would recommend reading its source code: 
https://github.com/mikro-orm/mikro-orm/blob/master/lib/drivers/MongoDriver.ts
https://github.com/mikro-orm/mikro-orm/blob/master/lib/connections/MongoConnection.ts

Will be happy to help with implementing the driver, basic support should be relatively easy.

**Comment by B4nan** [comment]
Closing this as answered, feel free to join the slack channel to discuss more details on how to implement it, as I said, will be happy to help.
