### ISSUE TITLE
Report a bug with findAndCount

### ISSUE THREAD

**Issue by angusleung200** [mikro-orm/mikro-orm#2121]
**Describe the bug**
We have two entity call **product** and **tag** which are ManyToMany relationship. When we find all product with limit ,offset  and population with tags, everything is correct in the first page(limit: 8, offset:0). However, the tags are disappeared when only one product on the second page(limit: 8, offset:8).
```
let products = await this.productRepo.findAndCount(filter,{limit:limit,offset:offset,flags:[QueryFlag.PAGINATE],populate:['icon','tags']})
```
**Stack trace**
First page: (limit: 8, offset:0)
![圖片](https://user-images.githubusercontent.com/39556765/129346145-069fb219-b1e3-411b-992e-6e728a7f9539.png)
Response:
![圖片](https://user-images.githubusercontent.com/39556765/129347383-24dc3167-5c0f-426a-97bb-b3aa5be679ab.png)
Second Page: (limit: 8, offset:8)
![圖片](https://user-images.githubusercontent.com/39556765/129346181-4e24916c-4443-492b-83ea-460419ccb474.png)
![圖片](https://user-images.githubusercontent.com/39556765/129347516-17c41143-1fe9-411c-aa08-5eaebbef7c68.png)

**Versions**

| Dependency | Version |
| - | - |
| node | v14.15.3 |
| typescript | v4.3.5 |
| mikro-orm | v4.5.7 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
Please provide reproduction, ideally as a test case. You just gave us a single line that does not help much. Also don't use screenshots, use code snippets instead. 

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by kingdun3284** [comment]
> Please provide reproduction, ideally as a test case. You just gave us a single line that does not help much. Also don't use screenshots, use code snippets instead.
> 
> https://stackoverflow.com/help/minimal-reproducible-example
Here you go:
```
npm install
npm run start
```
https://github.com/kingdun3284/mikro-orm-offset-bug

**Comment by B4nan** [comment]
Interesting, the query is indeed wrong, it adds the limit/offset to the populate query too when there is just one item.
