### ISSUE TITLE
Do we have any documentation on how to use CLI?

### ISSUE THREAD

**Issue by vimmerru** [mikro-orm/mikro-orm#213]
I am trying to start using migrations with CLI and i don't understand how to provide a configuration. Seems it asks for mikro-orm.config.js file. Can i use typescript instead of js? In tests i see file called cli-config.ts.

**Comment by B4nan** [comment]
https://mikro-orm.github.io/docs/v3/installation/

**Comment by B4nan** [comment]
Also you can use the `mikro-orm debug` command to check the configuration. 

You can use TS file and you can name it as you want. Default is `mikro-orm.config.js`, if you enable TS via `useTsNode` in package.json, it will first look for `mikro-orm.config.ts`.

**Comment by vimmerru** [comment]
Thanks a lot! I am able to run and use it.

**Comment by B4nan** [comment]
Will try to rework the website soon with docusaurus so we have search there...
