### ISSUE TITLE
Cannot modify an empty FilterQuery

### ISSUE THREAD

**Issue by belinde** [mikro-orm/mikro-orm#2130]
**Describe the bug**
I want to programmatically compose a FilterQuery from scratch, but if I define it as an empty object the compiler refuses to further edit it.

**To Reproduce**
Given a simple entity:
```typescript

@Entity()
export class ApiKey {
    @PrimaryKey({ columnType: 'char(26)' })
    id = ulid();

    @ManyToOne()
    user: User;

    @Property()
    active: boolean = true;
}
```
I can normally do:
```typescript
em.find(ApiKey, { user: 'abc123' });
```

But if I try:
```typescript
const conditions: FilterQuery<ApiKey> = {};
conditions.user = 'abc123';
```
the compiler complains:
```
Property 'user' does not exist on type '{ [PrimaryKeyType]?: any; } | { id?: FilterValue<string>; apikey?: FilterValue<string>; scopes?: OperatorMap<FilterValue2<Scopes.api>> | ... 11 more ... | FilterValue<...>; user?: string | ... 3 more ... | FilterValue2<...>[]; active?: boolean | ... 5 more ... | FilterValue2<...>[]; } | OperatorMap<...>'.
  Property 'user' does not exist on type '{ [PrimaryKeyType]?: any; }'.
```

On the other hand, if the initial value is not an empty object, everything works like a charm:
```typescript
const conditions: FilterQuery<ApiKey> = { id: 'please' };
conditions.user = 'abc123';
```

**Expected behavior**
An empty condition should be editable, being it just a plain object.

**Additional context**
If a solution is hard to find, I'll appreciate at least a workaround.

**Versions**

| Dependency | Version |
| - | - |
| node | v16.3.0 |
| typescript | Version 4.3.5 |
| mikro-orm | 4.5.7 |
| mysql | 4.5.7 |

**Comment by B4nan** [comment]
The solution is hard/breaking and I am not aware of any workaround currently. But it is definitely something I'd like to address, probably by having a different type than `FilterQuery` that you could use for composing queries manually.

**Comment by belinde** [comment]
Thank you!

My use case is slightly different, so I don't know how to typecast... Not real code, but it can help you to understand what I'm saying:

```typescript
type ConditionsModifier<T> = (conditions: FilterQuery<T>) => FilterQuery<T>;

const myModifier: ConditionsModifier<ApiKey> = (conditions) => {
    conditions.user = 'abc123';
    return conditions;
};
```

In this case the message is:
```
Property 'user' does not exist on type 'FilterQuery<ApiKey>'.
  Property 'user' does not exist on type 'string'.
```

So, as a workaround, waiting for the next major release, I think I'll avoid a strict typing introducing a custom type:
```typescript

type LooselyFilterQuery<T> = FilterQuery<T> & { [field: string]: any };

type ConditionsModifier<T> = (conditions: LooselyFilterQuery<T>) => LooselyFilterQuery<T>;

const myModifier: ConditionsModifier<ApiKey> = (conditions) => {
    conditions.user = 'abc123';
    return conditions;
};
```

With a really quick test it seems to work well.

Thank you for your excellent work!

**Comment by B4nan** [comment]
You could try `QBFilterQuery` which is pretty much the same thing. But it will be probably pretty much the same as just `Record`. 

The problem here is that while the type works fine if you assign to it directly, the "lazy assignment" won't work due to union types that allow both nested object query as well as raw PK (e.g. `{ user: 123 }` vs `{ user: { name: '...' } }`).

**Comment by Jamyth** [comment]
See if it helps

```ts
import type {} from '@mikro-orm/core/typings';

type ExtractArrayType<T> = T extends (infer U)[] ? U : T;
export type Query<T extends object> = {
    [K in keyof T]?: T[K] extends object 
                        ? Query<T[K]> & FilterValue<T[K]>
                        : FilterValue<ExtractArrayType<T[K]>>
}
```
