### ISSUE TITLE
Support for sqlite v4 instead of v3

### ISSUE THREAD

**Issue by mendrik** [mikro-orm/mikro-orm#2135]
**Is your feature request related to a problem? Please describe.**
Sqlite has way more functionality than version 3. There are some breaking changes between the versions, but I wonder if it would be such a big effort to upgrade?

**Describe the solution you'd like**
bump up sqlite3 to just "sqlite"

**Describe alternatives you've considered**
I thought about copy/pasting the current driver and make own package out if it, but seems the drivers rely on the parent 
package a lot.

**Comment by B4nan** [comment]
> bump up sqlite3 to just "sqlite"

This seems like you misunderstood the versioning and naming (or maybe I did, feel free to correct me if I'm wrong). This library uses `node-sqlite3` to support working with sqlite databases, via knex (so not used directly at all). You are reffering to https://github.com/kriasoft/node-sqlite, which is apparently a wrapper on top of the `node-sqlite3` library. So I literally don't see any difference if we would use that instead of what we have now. 

I don't believe there is such thing as sqlite v4, if we are talking about the database, then latest is v3.36.0, see https://www.sqlite.org/index.html

**Comment by mendrik** [comment]
sorry for wasting your time with this. I should have checked this more thoroughly. The whole thing started when I tried to use sign() which is allegedly supported by sqlite: https://sqlite.org/lang_corefunc.html#sign, however I got `SQLITE_ERROR: no such function: sign` and I assumed this was due to v3. Thanks for clarifying this, however I still have no idea why sign() doesn't work, maybe it's a knex layer issue then.

Anyways, thanks for this great project. Everything works like a charm!

**Comment by boredland** [comment]
hi there! I think this ticket was indeed confusing, but kinda valid. As I see it, mikro-orm depends on the `[sqlite3](https://www.npmjs.com/package/sqlite3)` package, which contains two transitive security issues, while the current `[sqlite](https://www.npmjs.com/package/sqlite)` package solves them, has some breaking changes and native ts support. I currently have to much on my plate to try to upgrade this, but this is surely a relevant issue.

**Comment by B4nan** [comment]
Well, that `sqlite` package is just a wrapper over `sqlite3`. `sqlite` is not a "current" package, it is a wrapper. It is quite funny they claim to be zero dependency given you still need `sqlite3` (or some compatible library) to do the actual job. Also we don't use that library directly but via knex, so we don't really care about the TS support.

Not sure what security issues are you talking about, but as we would still use `sqlite3` under the hood, I doubt they would be actually fixed.

**Comment by boredland** [comment]
Oh man, that is super confusing. To add more confusion, the [security issues](https://github.com/mapbox/node-sqlite3/issues/1502) are [fixed](https://github.com/mapbox/node-sqlite3/pull/1503) upstream, but never made it into a release.
