### ISSUE TITLE
QueryBuilder .delete() ignores where conditions defined before

### ISSUE THREAD

**Issue by francescortiz** [mikro-orm/mikro-orm#2136]
**Describe the bug**

The following code clears the table ignoring all filters.

    const query = em
    .createQueryBuilder(EacGroupedClaim)
    .where({ value: 0 })
    .delete()

    query.getFormattedQuery()); // delete from "eac_grouped_claim"

**Expected behavior**
One of the following could work:
a) Trigger a compilation error (type error).
b) Trigger a runtime error.
c) Honor provided conditions.

**Additional context**
We are using Mikro-ORM with PostgreSQL driver.

**Versions**

| Dependency | Version |
| - | - |
| node | v12.19.0 |
| typescript | 4.3.2 |
| mikro-orm | 4.5.7 |

**Comment by B4nan** [comment]
FYI this will change in v5, runtime error will be throw. The solution in v4 is working only for very simple cases and fails to handle complex conditions (e.g. with operators) or auto-joining.

**Comment by francescortiz** [comment]
Since the problem is related to data structure, if a runtime error can be triggered, it may also be possible to trigger a compile-time error. I would like to have a look at the code to explore potential approaches if that is ok with you. Where can I find it? Thanks

**Comment by B4nan** [comment]
I was in the middle of explaining why we can't do it on type level (as I already tried), when I realized we actually can :] Initially I thought I will disallow this only for complex cases that would trigger joining, and there It would not be possible to type it (as it would require understanding the actual condition on type level). But as we disallow it for all cases now, we can just return `SelectQueryBuilder` from `qb.where()` and remove `update/delete` methods from that type.

**Comment by B4nan** [comment]
Hmmm turns out it is not that simple, TS tends to loose the context in some places, e.g. the `this` return type tends to not work as expected. Feel free to give it a try.

https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/query/QueryBuilder.ts#L872
https://github.com/mikro-orm/mikro-orm/blob/master/tests/QueryBuilder.test.ts#L71

**Comment by francescortiz** [comment]
If `this` is not working as expected then there is not much to do. My checks get to the same conclusion. Maybe in the following years they will strengthen the implementation of the `this` type, or maybe a non-OOP approach can be written when the [pipe operator](https://github.com/tc39/proposal-pipeline-operator) gets implemented in typescript.
