### ISSUE TITLE
Setting type of nullable column to `string | null` causes column type to be changed to `json`

### ISSUE THREAD

**Issue by bboltze** [mikro-orm/mikro-orm#2137]
**Describe the bug**
When I set a nullable column's type to `string | null` like this

```
@Entity()
export default class MyEntity {
  @Property({ nullable: true })
  my_property?: string | null;
})
```

then running `mikro-orm migration:create` generates a migration to turn the column to `json`:

```
this.addSql('alter table `my_entity` modify `my_property` json;');
```

This happens both when changing the type of an existing property and when creating a new property.

**To Reproduce**
1. Create a model with a nullable property of type `string | null`.
2. Run `mikro-orm migration:create`

**Expected behavior**
I expect the type to stay the same, i.e. `varchar(255)`.

**Versions**

| Dependency | Version |
| node | 14.17.5 |
| typescript | 4.2.4 |
| mikro-orm | 4.5.5 |
| your-driver | mysql2 2.2.5 |

**Comment by B4nan** [comment]
This is how reflection works in TS, you cannot use a union type if you want to use reflect-metadata to infer it. 

You can use ts-morph to get around it.
