### ISSUE TITLE
PostgreSQL / Migrations are generating extra constraint checks and re-create them

### ISSUE THREAD

**Issue by volo-maslow** [mikro-orm/mikro-orm#2138]
**Describe the bug**
Migrations with ```PostgreSqlSchemaHelper``` are generating extra constraint checks.

**To Reproduce**
1. Generate a migration for an entity with enum field

**user.entity.ts**
```
@Entity({ tableName: 'User' })
export class UserEntity extends BaseEntity<UserEntity, 'userId'> {

    @PrimaryKey({ type: BigIntType, columnType: 'bigint' })
    userId!: bigint;

    @Enum({ items: () => UserLanguageEnum, default: UserLanguageEnum.EN })
    language!: UserLanguageEnum;

    @Property({ columnType: 'timestamp', defaultRaw: UTC_NOW })
    createdAt: Date;
}
```

**NPM**
```
npx mikro-orm migration:create
```
2. Apply the migration to the database
```
npx mikro-orm migration:up
```
3. Add one new field to the entity and generate a migration one more time

**user.entity.ts**
```
@Entity({ tableName: 'User' })
export class UserEntity extends BaseEntity<UserEntity, 'userId'> {

    @PrimaryKey({ type: BigIntType, columnType: 'bigint' })
    userId!: bigint;

	@Property({ length: 256 })
    email!: string;

    @Enum({ items: () => UserLanguageEnum, default: UserLanguageEnum.EN })
    language!: UserLanguageEnum;

    @Property({ columnType: 'timestamp', defaultRaw: UTC_NOW })
    createdAt: Date;
}
```
**NPM**
```
npx mikro-orm migration:create
```
4. Apply the migration to the database
```
npx mikro-orm migration:up
```

**Expected behavior**
Migrations are altering only for changed/added columns:
```
import { Migration } from '@mikro-orm/migrations';

export class Migration20210823115253 extends Migration {

  async up(): Promise<void> {
	this.addSql('alter table "User" add column "email" varchar(256) not null;');
  }

}
```

**Actual behavior**
Migrations are altering non-changed columns with the same logic as they have before:
```
import { Migration } from '@mikro-orm/migrations';

export class Migration20210823115253 extends Migration {

  async up(): Promise<void> {
    this.addSql('alter table "User" drop constraint if exists "User_language_check";');
    this.addSql('alter table "User" alter column "language" type text using ("language"::text);');
    this.addSql('alter table "User" add constraint "User_language_check" check ("language" in (\'EN\'));');
    this.addSql('alter table "User" drop constraint if exists "User_createdAt_check";');
    this.addSql('alter table "User" alter column "createdAt" type timestamp using ("createdAt"::timestamp);');
    this.addSql('alter table "User" alter column "createdAt" set default timezone(\'utc\', now());');

	this.addSql('alter table "User" add column "email" varchar(256) not null;');
  }

}
```

**Versions difference**

Looks like this is related to ```PostgreSqlSchemaHelper``` file (at least for enum values) - it's missing the check at ```@mikro-orm/postgresql v4.5.7``` which exists at the master branch:

**v4.5.7**
_https://github.com/mikro-orm/mikro-orm/blob/v4.5.7/packages/postgresql/src/PostgreSqlSchemaHelper.ts#L127_

**master**
_https://github.com/mikro-orm/mikro-orm/blob/master/packages/postgresql/src/PostgreSqlSchemaHelper.ts#L113_

**Versions**

| Dependency | Version |
| - | - |
| node | v14.17.5 |
| typescript | 4.3.5 |
| mikro-orm | 4.5.7 |
| mikro-orm/postgresql | 4.5.7 |

**Environment**
| Env | Version |
| - | - |
| OS | MacOS Catalina 10.15.3 |
| DB | postgres:13 (Docker) |

**Comment by B4nan** [comment]
Sorry, but I do not plan to backport any fixes to schema generator from v5. It was a major refactoring and the changes are very deep and incompatible, I'd have to fix every single bug again basically.

If you want this to be fixed in v4, feel free to pick the needed parts from master and send a PR (targetting [`4.x` branch](https://github.com/mikro-orm/mikro-orm/tree/4.x)).

Or try v5, I'd say most of the BCs are done already.

**Comment by volo-maslow** [comment]
Thanks, I'm new here and didn't notice that there was a huge ongoing migration for a newer version.
Will be switching to v5.

**Comment by B4nan** [comment]
It is still work in progress (dev versions are availabe via `next` tag on npm), reworked schema generator was one of the major changes. See #1623 for more information. 

If you are working on some toy/learning project or you know it won't get to production soon, I'd go with v5. I hope to get to RC stage in few weeks, most breaking changes are done (planning to do few more API changes in driver interface and other internals).

Another huge benefit on v5 is better type-safety.
