### ISSUE TITLE
Support locking multiple rows at once

### ISSUE THREAD

**Issue by lewispham** [mikro-orm/mikro-orm#2141]
I need to lock multiple rows at once. It seems that mikro orm currently just support lock mode on `findOne` and `em.lock`. Both these 2 methods are for applying the lock on one single row.

I think it's ideal if we can apply lock mode on method `find` as well as supporting array of entities on method `em.lock`. Please correct me if there is something wrong with this proposal.

**Comment by B4nan** [comment]
nothing wrong, its already implemented in v5, no plans to backport any features at this stage

(only pessimistic locking will work with `em.find()`)

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/drivers/IDatabaseDriver.ts#L104
