### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by epechuzal** [mikro-orm/mikro-orm#2143]
**Describe the bug**
You can't install mikro-orm since the 4.5.8 release

**Stack trace**
```
yarn install v1.22.10
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@mikro-orm/mysql-base/-/mysql-base-4.5.8.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/eddypechuzal/Workspace/publisher-platform/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**To Reproduce**
Add these to your package.json and then try to install
```
    "@mikro-orm/core": "^4.5.8",
    "@mikro-orm/mysql": "^4.5.8",
    "@mikro-orm/nestjs": "^4.3.0",
    "@mikro-orm/sql-highlighter": "^1.0.1",
```

**Expected behavior**
The package should install

**Additional context**
Happens since 4.5.8 release

**Versions**

| Dependency | Version |
| - | - |
| node | 14.17.0 |
| typescript | 4.1.5 |
| mikro-orm | 4.5.8 |

**Comment by B4nan** [comment]
npm is somehow broken today, and you apparently tried to install the version that was not fully published. try it again, it should work fine now (only package i failed to publish is sqlite one).

**Comment by B4nan** [comment]
![image](https://user-images.githubusercontent.com/615580/130671820-4b936929-3762-42ee-a745-4794a04737b2.png)

**Comment by epechuzal** [comment]
> npm is somehow broken today, and you apparently tried to install the version that was not fully published. try it again, it should work fine now (only package i failed to publish is sqlite one).

I still get the same thing
```
error An unexpected error occurred: "https://registry.yarnpkg.com/@mikro-orm/mysql-base/-/mysql-base-4.5.8.tgz: Request failed \"404 Not Found\"".
```

**Comment by B4nan** [comment]
Yes, that lint indeed does return 404. Which means yarn repository do not have that version. 

I will try to publish new version once the build starts working properly. For now just pin to 4.5.7, I have no control over yarn's registry, not much I can do now.

**Comment by epechuzal** [comment]
Thanks! I'll keep an eye out for your next release

**Comment by vashisth00** [comment]
Even I can't download it

yarn add @mikro-orm/postgresql

yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@mikro-orm/postgresql/-/postgresql-4.5.8.tgz: Request failed \"404 Not Found\"".

**Comment by B4nan** [comment]
As said, pin the version to 4.5.7 for now.

```
yarn add @mikro-orm/postgresql@4.5.7
```

**Comment by epechuzal** [comment]
Also note: not just yarn, npm is also affected
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@mikro-orm/mysql-base/-/mysql-base-4.5.8.tgz - Not found
npm ERR! 404
npm ERR! 404  '@mikro-orm/mysql-base@https://registry.npmjs.org/@mikro-orm/mysql-base/-/mysql-base-4.5.8.tgz' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

4.5.7 works fine for now

**Comment by B4nan** [comment]
latest canary build just got published to npm without problems, 4.x canary build is in progress, if that will succeed too, will try to publish stable 4.5.9 again, so let's hope it was just some npm outage followed by a cascade of crap 💩

**Comment by B4nan** [comment]
4.5.9 is out and looks like things are working again, sorry for the inconvenience.
