### ISSUE TITLE
remove() on an Entity consisting of more than one Primary Keys not working

### ISSUE THREAD

**Issue by henrroga** [mikro-orm/mikro-orm#2148]
I have a table with two primary keys. Finding one entity with `findOne` or `findOneOrFail` gives me the correct response, but when I try to remove that entity with `remove` or `removeAndFlash` I get the error `Expected 1 bindings, saw 2`.

I believe this is related to having more than one primary key in the entity I'm trying to remove, but I'm really not sure if this is a bug of MikroORM or I am missing something. Here is the full code I am using:

```
public async doSomething(user: UserEntity, something: SomethingEntity): Promise<void> {
  const result = await this.repository.findOneOrFail({
    user,
    something,
  });
  
  return await this.repository.remove(result).flush();
}
```

I'm really not finding some related issue to this problem, so any help would be appreciated.

**Comment by B4nan** [comment]
Added a test case that is passing just fine, feel free to take that as a base for your reproduction. If you provide a failing one, will be happy to reopen.

(note I had tested this with ts-morph too, and also with 4.x branch, both working just fine)
