### ISSUE TITLE
Mandatory fields on MongoDB

### ISSUE THREAD

**Issue by ramiel** [mikro-orm/mikro-orm#2176]
**Describe the bug**
Maybe this is my misunderstanding. Let's say I have an entity defined like this

```ts
class Book {

   @PrimaryKey()
  _id!: ObjectId;

  @Field(() => ID)
  @SerializedPrimaryKey()
  id!: string;

  @Property()
  title!: string;
}
```

and I decide to create and persist the entity

```ts
const book = this.bookRepository.create({});
await this.bookRepository.persistAndFlush(book);
```

I expect this to fail because `title` should be mandatory. What happens is, instead, that the book get created on MongoDB. Is this the expected behavior?

**Expected behavior**
Mandatory fields should be validate before saving

**Versions**

| Dependency | Version |
| - | - |
| node | 14 |
| typescript | 4.3.5 |
| mikro-orm | 4.5.9 |
| your-driver | mongodb |

**Comment by B4nan** [comment]
This currently works only in SQL where optionality is checked on the database level. As mongo is schema-less, there is nothing like that.

I am ok with adding the runtime checks to the ORM code, but for performance reasons it should be optional (maybe we could enable it automatically for mongo, but it has a slight performance penalty). 

There is already optional validation that seems like the right place for this. 

https://mikro-orm.io/docs/configuration#strict-mode-and-property-validation
https://mikro-orm.io/docs/property-validation

**Comment by ramiel** [comment]
Yes, in fact these are the first options I tried to see if this was supported. I think the user should be at the least warned about the default behaviour with Mongo, otherwise what's the point of marking something as `nullable: false`?

**Comment by B4nan** [comment]
> Yes, in fact these are the first options I tried to see if this was supported. I think the user should be at the least warned about the default behaviour with Mongo, otherwise what's the point of marking something as nullable: false?

For mongo there is no point, that is SQL only option, which is documented. 

https://mikro-orm.io/docs/decorators/#property

**Comment by ramiel** [comment]
Indeed, my bad. If this could be checked at runtime with mongo, then that option could make sense for mongo as well
