### ISSUE TITLE
migration:create wants to make required ManyToOne fields nullable.

### ISSUE THREAD

**Issue by vimmerru** [mikro-orm/mikro-orm#218]
I noticed that migration:create for fields like this

```
@ManyToOne()
  product: Product;
```

always generates the following sql code:

```modify `product_id` int(11) unsigned null;``` despite the obvious fact it should be not null.

I can solve this by adding ```{ nullable: false }```, but it looks like an workaround for the bug.

**Comment by vimmerru** [comment]
The same is for ``` @OneToOne```

**Comment by B4nan** [comment]
Fixed in `3.0.0-alpha.33`

**Comment by l00k** [comment]
Not sure but this probably caused to always make ManyToOne not null (except litterally setting it in decorator args)
```
@ORM.ManyToOne(() => BlogCategory)
public mainCategory ? : BlogCategory;
```
gives
```
`main_category_id` int(11) unsigned not null
```

Making property non required (?) works for literal properties, but not for associations.

**Comment by B4nan** [comment]
As written in the docs, this auto-detection works only when you omit the type/entity attribute and let `ts-morph` do the work for you. Added some examples there recently so it is clear.

https://mikro-orm.io/docs/defining-entities#optional-properties

**Comment by B4nan** [comment]
On the other hand, the reason behind it was to allow skipping resource heavy source code analyses during the discovery process (by explicitly providing the types). Which can be now done via `ReflectMetedataProvider` (and it is also better as it does not force you to provide _all_ the types), so I think we can actually keep `TsMorphMetadataProvider` doing the job always, even when the type is explicitly set.

**Comment by l00k** [comment]
Yeap. It is clear, I missed that.
I were using search but it seems to not work
![img](https://user-images.githubusercontent.com/29358909/70645847-0a0af480-1c46-11ea-8b3d-c6ef1470cf49.png)

**Comment by B4nan** [comment]
Yeah I also noticed that the search works only for headings, and not for the actual content, will need to do something about it soon...

**Comment by l00k** [comment]
Hmm..
reflect-metadata - I wonder if it will not be a problem to use types with reflect metadata (because of cyclic dependencies).

I personally migrated to mikro-orm from sequelize-typescript. (BTW. I already love it)
It uses reflect-metadata (if field description is not specified in decorator)
And it is not possible to define complex (cyclic) associations using type only - it would lead to cyclic dependency problem - you have to use arrow func with return type.

Morph works because it parses source, but reflect-metadata loads script to memory which may lead to not imported modules (in cyclic cases).

Maybe you already solved that somehow?
I see you also use arrow declarations, but what about that case?
```
@ManyToOne()
favouriteBook?: Book; // correct: no `type` or `entity` provided, **will** be marked as `nullable`
```

**Comment by B4nan** [comment]
Yeah it has some limitations, that is why I kept the `ts-morph` solution as the default. One of it being the need to explicitly provide the `type`/`entity` (not necessarily everywhere, but where the reflection fails, like with circular dependencies).

https://mikro-orm.io/docs/metadata-providers/#reflectmetadataprovider

This nullability detection works only with `ts-morph`, with other metadata providers you need to state that a property is `nullable`.

To wrap up, I can make this configurable (and enabled by default) so when using `TsMorphMetadataProvider` it will always check for nullability. I think it makes sense, it will make the API more predictable, and as I already said, the reason for this was to allow skipping `ts-morph`, for which one should use the `ReflectMetadataProvider` nowadays.
