### ISSUE TITLE
Enums don't work with Babel: TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by ifeltsweet** [mikro-orm/mikro-orm#2198]
**Describe the bug**

A simple model with `@Enum()` produces error when compiled with Babel.

**Stack trace**
```
[Function: String]
[Function: String]
[Function: String]
[Function: String]
[Function: String]
{ ACTIVE: 'ACTIVE', INACTIVE: 'INACTIVE' } <- I added console.log(type) to ReflectMetadataProvider.js.
TypeError: Cannot read property 'toLowerCase' of undefined
    at ReflectMetadataProvider.initPropertyType (/src/node_modules/@mikro-orm/core/metadata/ReflectMetadataProvider.js:18:79)
    at /src/node_modules/@mikro-orm/core/metadata/ReflectMetadataProvider.js:9:50
    at ReflectMetadataProvider.initProperties (/src/node_modules/@mikro-orm/core/metadata/MetadataProvider.js:26:23)
    at async ReflectMetadataProvider.loadEntityMetadata (/src/node_modules/@mikro-orm/core/metadata/ReflectMetadataProvider.js:9:5)
    at async MetadataDiscovery.discoverEntity (/src/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:182:13)
    at async MetadataDiscovery.discoverReferences (/src/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:131:13)
```

As you can see from my custom logs, enums are turned into objects instead of `[Function(Object)]`.

**To Reproduce**

```
export enum Status {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE'
}
```

```
import { Status } from './Status';
import { Embeddable, Enum, Property } from '@mikro-orm/core';

@Entity()
export class User {
  @Property()
  readonly id: string;

  @Enum(() => Status)
  readonly status: Status;
}
```

**Expected behavior**
Should work.

**Additional context**
```
// babel.config.js
module.exports = {
  presets: [['@babel/preset-env', { targets: { node: '14' } }], '@babel/preset-typescript'],
  plugins: [
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    ['@babel/plugin-proposal-class-properties', { loose: true }],
    'babel-plugin-transform-typescript-metadata',
    ['module-resolver', { alias: { '@': './src' } }],
  ],
};
```

```
// package.json
    "@babel/cli": "^7.15.4",
    "@babel/core": "^7.15.5",
    "@babel/plugin-proposal-decorators": "^7.14.5",
    "@babel/plugin-transform-typescript": "^7.15.0",
    "@babel/preset-env": "^7.12.1",
    "@babel/preset-typescript": "^7.12.1",
    "babel-plugin-module-resolver": "^4.1.0",
    "babel-plugin-transform-typescript-metadata": "^0.3.2",
```

Running with BABEL_DECORATORS_COMPAT=true.

**Versions**

| Dependency | Version |
| - | - |
| node | 14.17.6 |
| typescript | 4.3.5 |
| mikro-orm | 4.5.9 |
| your-driver | postgres |

**Comment by B4nan** [comment]
Just a guess, but maybe the order of plugins matter? The `babel-plugin-transform-typescript-metadata` should be first as in the [docs](https://mikro-orm.io/docs/usage-with-babel/).

The method `ReflectMetadataProvider.initPropertyType()` should not be fired for enums at all, as it is a fallback for properties without specified type via options.

**Comment by ifeltsweet** [comment]
Thanks for such a quick reply. I've tried the suggestion but it did not help.

**Comment by B4nan** [comment]
Then please provide full repro repository, I don't have any babel project to test this on.

**Comment by ifeltsweet** [comment]
I was able to make it work by adding `@Property` decorator.

```
@Property({ type: String })
@Enum(() => Status)
readonly status: Status;
```

And this also worked:

```
@Enum({ type: String, items: () => Status })
readonly status: Status;
```

When `console.log(prop)` in the ReflectMetadataProvider.js without the fixes above it shows that type is undefined.

```
{
  name: 'status',
  reference: 'scalar',
  enum: true,
  items: [ 'ACTIVE', 'INACTIVE' ],
  type: undefined
}
```

I'm not sure if something is wrong with my Babel config or we should add this workaround to the docs for future Babel users.

**Comment by ifeltsweet** [comment]
And yes, I did have to remove `BABEL_DECORATORS_COMPAT=true` as was resolved in https://github.com/mikro-orm/mikro-orm/discussions/2202
