### ISSUE TITLE
Allow schema:drop to drop migrations table too

### ISSUE THREAD

**Issue by vimmerru** [mikro-orm/mikro-orm#220]
**Is your feature request related to a problem? Please describe.**
Now ```schema:drop``` remove all tables except migrations and i need to remove it manually so often when debug migrations.

**Describe the solution you'd like**
Allow ```schema:drop``` to remove migrations table. Maybe add some switch or setting to skip this behavior.

**Comment by B4nan** [comment]
Schema generator ignores it on purpose, but we can make it optional for sure.

**Comment by vimmerru** [comment]
I want to have the way to start database creation from scratch. ```schema:drop``` maybe not the best way for this. Maybe new command in migrations namespace.

**Comment by B4nan** [comment]
Like`database:create` and `database:drop`?

**Comment by vimmerru** [comment]
maybe ```migration: from_scratch```

**Comment by vimmerru** [comment]
```database:drop``` doesn't work for me as i have some ACL rules based on database object and don't wont to loose them.

**Comment by B4nan** [comment]
`drop-migrations-table` flag added in `3.0.0-alpha.33`.

`mikro-orm schema:drop --drop-migrations-table`
