### ISSUE TITLE
Descending index in MongoDB

### ISSUE THREAD

**Issue by ramiel** [mikro-orm/mikro-orm#2203]
**Is your feature request related to a problem? Please describe.**
Is there a way to create an index in descending order in MongoDB? I cannot find the right option to pass

**Comment by B4nan** [comment]
How would you do it with raw mongo api?

**Comment by ramiel** [comment]
Something like this
```
db.collection.createIndex(
  {
      "name": 1 // this can be -1 to indicate descending
  }
)
```

**Comment by ramiel** [comment]
https://docs.mongodb.com/manual/reference/method/db.collection.createIndex/

**Comment by B4nan** [comment]
The top level indexes do have `options` parameter, and if you don't specify any properties, [it will be used as the first argument to `collection.createIndex()`](https://github.com/mikro-orm/mikro-orm/blob/master/packages/mongodb/src/MongoDriver.ts#L142) so you might be able to push it that way.

```ts
@Entity()
@Index({ options: { name: 1 } })
class ... {}
```

**Comment by B4nan** [comment]
Just tried and it works, even without the `properties: []`, so closing.

**Comment by ramiel** [comment]
Perfect, thank you :+1:

**Comment by ramiel** [comment]
Actually this prevent passing other options

```ts
@Index({ options: { name: 1, sparse: true } })
```

because now `sparse` is considered a property, not an option
