### ISSUE TITLE
Same schema multi-tenancy support

### ISSUE THREAD

**Issue by klausXR** [mikro-orm/mikro-orm#2208]
**Is your feature request related to a problem? Please describe.**
I'm working on a multi-tenant application, where every shared table has a `tenand_id` column.

Is there a planned or existing feature that makes this easier to handle and reduce the chance of getting the `tenant_id` wrong?

**Describe the solution you'd like**

I don't have experience with other ORMs that support similar functionality, but I'm thinking about using something to the lines of the setup code to provide the `tenant_id`

```js
app.use((req, res, next) => {
  // the `req.tenant` is populated by another middleware that runs prior to this
  RequestContext.create(orm.em, next, { tenant_id: req.tenant.id );
});

// The `tenant_id` is automatically included in this query, despite not being specified explicitly
const books = await orm.em.find(Book, {});
```

and the ORM would later use this property and include it in the SQL queries when `find` and `save` are called.

Do note, this is not an actual API proposition, its just to get a grasp of the idea

**Describe alternatives you've considered**

**Additional context**

I believe this way of handling multi-tenancy is  pretty popular when you are expecting to have many tenants, but one of its downsides is the greater risk of fetching/mutating an entity of the wrong tenant. 

Handling this manually everywhere in the code is very error prone and something like this would, in my opinion, drastically reduce the chance of getting it wrong and it will also make the codebase look like, to an extent, as if it is not a multi-tenant application.

**Comment by B4nan** [comment]
You can use filters for this:

https://mikro-orm.io/docs/filters/
https://mikro-orm.io/docs/filters/#global-filters

This will work for reading the data, for writing you could use `onFlush` even subscriber:

https://mikro-orm.io/docs/lifecycle-hooks/#using-onflush-event

You can leverage the global filter parameter storage on the EM via `em.getFilterParams()` and `em.setFilterParams()` methods.
