### ISSUE TITLE
Nested Embeddables not saving

### ISSUE THREAD

**Issue by sidzan** [mikro-orm/mikro-orm#2216]
**Describe the bug**
The innermost embeddable **coordinates** is not saving to the database (PSQL) and returning a null error

```
@Entity({ tableName: 'plots' })
export default class Plot {
  @PrimaryKey()
  readonly id: number;
 
  ...
  
  @Embedded({ prefix: false })
  readonly location: PlotLocation;
}

@Embeddable()
export class Coordinates {
  @Property()
  readonly longitude: number;

  @Property()
  readonly latitude: number;
}

@Embeddable()
export class PlotLocation {
  @Property({ type: String })
  @Enum(() => PROVINCES)
  readonly province: PROVINCES;

  @Property({ type: String })
  @Enum(() => DISTRICTS)
  readonly district: DISTRICTS;

  @Embedded()
  readonly coordinates: Coordinates;
}

```

I am using the following code to save 
```
    await mikroOrm.em.persistAndFlush(
      new Plot({
        ...
        location: {
          province: PROVINCES.BANGKOK,
          district: DISTRICTS.BANGKOK_NOI,
          coordinates: {
            latitude: 14.579367,
            longitude: 102.197143,
          },
        },
       ...
      }),
    );
```

The code however works if i flatten the second layer as below
```
        location: {
          province: PROVINCES.BANGKOK,
          district: DISTRICTS.BANGKOK_NOI,
          latitude: 14.579367,
          longitude: 102.197143,
        },
```

**Stack trace**
```
NotNullConstraintViolationException: insert into "plots" ("area_size", "coordinates_latitude", "coordinates_longitude", "created_at", "crop_type", "deleted_at", "district", "farmer_id", "is_active", "landmark", "name", "planted_at", "province", "updated_at") values (52, NULL, NULL, '2021-09-19T07:11:28.071Z', 'RICE', NULL, 'BANGKOK_NOI', 'sBfMfwB2SDQpOZrlzvfJDW9so2Q2', true, 'Rice Farm', 'home', '2020-02-08', 'BANGKOK', '2021-09-19T07:11:28.071Z') returning "id", "is_active" - null value in column "coordinates_longitude" of relation "plots" violates not-null constraint
```

**To Reproduce**
1. . create the model as defined Class Plots
2.  have an Embeddable inside embeddable as above Plot > Location > Coordinates
3.  save to database with persistAndFlush

**Expected behavior**
The coordinates should be able to save without needing to flatten it on the second layer, i.e the following code should work

```
        location: {
          province: PROVINCES.BANGKOK,
          district: DISTRICTS.BANGKOK_NOI,
          coordinates: {
            latitude: 14.579367,
            longitude: 102.197143,
          },
        },
```

**Versions**

| Dependency | Version |
| - | - |
| node | v14.17.3 |
| typescript | ^4.3.5 |
| mikro-orm | ^4.5.9 |
| mikro-orm/postgresql | ^4.5.9 |

P.S any suggestion is much appreciated !

**Comment by B4nan** [comment]
Just a guess, but you should be providing the embedded class in decorator parameters:

```ts
@Embedded(() => Coordinates)
readonly coordinates: Coordinates;
```

Also embeddables need to be discovered just like regular entities, and historically there were several issues with order of discovery, so you might try to change that too.

**Comment by B4nan** [comment]
Actually, how does your entity constructor look like? Try console.logging the entity instance before you persist it. 

Ideally provide executable reproduction. This use case is tested and should work just fine - see https://github.com/mikro-orm/mikro-orm/blob/master/tests/features/embeddables/nested-embeddables.postgres.test.ts

**Comment by sidzan** [comment]
> Actually, how does your entity constructor look like? Try console.logging the entity instance before you persist it.
> 
> Ideally provide executable reproduction. This use case is tested and should work just fine - see https://github.com/mikro-orm/mikro-orm/blob/master/tests/features/embeddables/nested-embeddables.postgres.test.ts

Thanks a ton for the reply, however, it seems the issue was with the way I imported the entities
I need to import in this order and is working fine.
```    
    Plot,
    PlotLocation,
    Coordinates
```

**Comment by ramiel** [comment]
I also had the very same problem. Maybe this should be part of the documentation?
