### ISSUE TITLE
Exporting object ignores initialized fields.

### ISSUE THREAD

**Issue by jsprw** [mikro-orm/mikro-orm#222]
If you retrieve an object with populate: true or inititialize a collection later which contains multiple references to the same item, it does not fill the object.

For example this example; the entity is retrieved with eager:false, populate: false and it initialized manually:
```
const m = await entity.entitiesthatlinktoent1.init({ populate: ["ent1"] });
        console.log(m[0].entitiesthatlinktoent1, ent.entitiesthatlinktoent1[0].ent1); //these both log an initialized ent1 with "prop": "data"
        return entity;
```
but it returns:

```json
{"id":9,"ent1":{"id":23, "prop": "data"},"entitiesthatlinktoent1":[{"id":6,"ent1":{"id":23},"date":"2019-10-27T12:57:16.000Z"}]}
```

```
//main enitity
@OneToOne(() => Entity1, e => e.parent)
    ent1: Entity1;

//entity1
@OneToOne(() => Main)
    parent: MainEntity;

@OneToMany(() => Entity2, e => e.ent1)
    entitiesthatlinktoent1 = new Collection<Entity2>(this);

@Property({type:"string"})
   prop: string;

//enitity2
@ManyToOne(() => Entity1, e => e.entitiesthatlinktoent1)
   ent1: Entity1;

```

**Comment by lookfirst** [comment]
Which version are you using?

**Comment by jsprw** [comment]
Alpha 32

**Comment by lookfirst** [comment]
So my guess is that you're hitting the entity cache. You've queried once and it is now in the cache. Then you query again and get the cached item back. Do an equality test or try `em.clear()` first.

**Comment by jsprw** [comment]
I do not hit the cache. It is loaded correctly from cache. Only exporting an obj as JSON does not load the entity multiple times if it’s set to be populated. See the first code block and second code block.

**Comment by lookfirst** [comment]
🤷‍♂ post a working code test base.

**Comment by jsprw** [comment]
Just added the required entities. I dont have a whole code base I can easily post.

**Comment by B4nan** [comment]
> Just added the required entities. I dont have a whole code base I can easily post.

But you can create new reproduction repo, that you can share. One that will be simple as possible, just to demonstrate your issue.

**Comment by lookfirst** [comment]
https://github.com/lookfirst/mikro-example

just add your files to that repo

**Comment by B4nan** [comment]
> But when you export it using toJSON, you only get the id for objects that are exported multiple times (where main.ent1 has id 23 and where entity2.ent1 has id 23, only main.ent1 is filled and entity2.ent1 - expect that this has to do with preventing circular).

This will be most probably the cause, as I had to recently add some additional recursions checks there (I think it was because of an issue you were reporting elsewhere, but not sure now). 

Will try to verify that during this week.

**Comment by jsprw** [comment]
> https://github.com/lookfirst/mikro-example
> 
> just add your files to that repo. everything is already setup for you.

I have tried to replicate the problem using your repo, but I seem to be unable to right now :/

https://github.com/jsprw/mikro-example/ -> yarn test ab.spec
(this repo also contains a maximum stack exceeded error when not persistandflushing entity a before flushing c).

> This will be most probably the cause, as I had to recently add some additional recursions checks there (I think it was because of an issue you were reporting elsewhere, but not sure now).

Yes I reported that but that was because the child kept referencing its parent that references its child. This is a completely different type entity with that links to the same child

(to get an idea: a support ticket has an owner that is user 23 and has messages as childs. One of these messages is sent by user 23 and there the same user object is used as the owner of the support ticket).

**Comment by lookfirst** [comment]
That test passes just fine for me.

**Comment by lookfirst** [comment]
Wait, what? did you modify an existing test file? The code you're showing isn't in the file. lol. Please push the repo to your own github and show us.

**Comment by jsprw** [comment]
I have linked the repo already. See: https://github.com/jsprw/mikro-example/blob/master/test/db/ab.spec.ts

**Comment by jsprw** [comment]
No problem.

For the test I need to fill the database first. But what I’m trying to do is exporting to json. See the example case above, my problem is that the second time an entity is accessed during exporting it is just an id altough i would expect the complete object for the second time as well.

**Comment by B4nan** [comment]
So the issue you tried to reproduce is basically a typo. You need to serialize the entity loaded in the context (`foundC`), not the one that was used before clearing the identity map (just `c`). Left a comment in your reproduction repo:

https://github.com/jsprw/mikro-example/commit/f8a0542b5373f5da8d36eb79c016a694f1fe8876#r35777937

But I think the issue you are talking about is really there, you just failed to reproduce it properly. I think I saw it recently too.

Btw the recursion issue when flushing will be fixed in next version, already got that working on localhost.

**Comment by B4nan** [comment]
Please try to replicate it, I already spent few hours trying to understand your OP but its full of contradictions (like you are talking about eager loading and in following sentence you say no eager loading is used). Also your original example is full of wrong references (`Main` vs `MainEntity`, `ent` in the first `console.log` is nowhere defined, etc...).

**Comment by B4nan** [comment]
Ok, found it! Try `3.0.0-alpha.33`.

**Comment by jsprw** [comment]
Yes! Thank you very much. After some testing, it looks like this is fixed :)
