### ISSUE TITLE
Missing a clearDatabase() function that would casacade-delete all the tables in a database

### ISSUE THREAD

**Issue by woltob** [mikro-orm/mikro-orm#2220]
I am running tests with a database inside a docker-composed environment.
Why? Wanna make sure my service classes do exactly what they're supposed to do.

Currently, I am running a 

```
  beforeEach(async () => {
    await userRepository.nativeDelete({});
  });
```

for every test where I delete the data that was created during the test.

A clearDatabase() function would really help, since I want to have a clean database in the beginning of every test.

Also: do you provide a functionality for creating seed data so that I don't have to add things manually?

**Comment by B4nan** [comment]
I guess it makes sense to have a helper method for this, although don't expect too smart things, as each driver behaves a bit differently. 

If you want cascading using postgres, you can use `QueryBuilder.truncate()`, other drivers do not offer cascading deletes - this is a database feature, no plans to implement app level cascading outside of entity manager. In MySQL we can just disable FKs via `foreign_key_checks`.

Note that doing `nativeDelete()` (or in general simple delete query) will be usually faster than truncate, especially when cascading. I would say it should be preferred in tests.

You can also wipe the whole schema via `SchemaGenerator.dropSchema()` and just recreate it. 

> Also: do you provide a functionality for creating seed data so that I don't have to add things manually?

It's already implemented in v5, don't expect this to land to v4 either, only bugfixes are being backported.

https://mikro-orm.io/docs/next/seeding

_And lastly a regular reminder, if you want to open issues, please don't ignore the issue template._

**Comment by B4nan** [comment]
FYI v5 now has `SchemaGenerator.refreshDatabase()`, it will:
- ensure the database exists
- drop the schema if exists
- create the schema from scratch
