### ISSUE TITLE
Default values in an embeddable array do not work

### ISSUE THREAD

**Issue by kaname-png** [mikro-orm/mikro-orm#2232]
**Describe the bug**
When trying to push an array of a document with default values, the non-default fields do not appear when saving the document.

In my opinion they should improve the support for this kind of documents in mongodb.

**Stack trace**
https://github.com/kaname-png/mikro-orm-error-array-embeddables

**To Reproduce**
1. Create document
2. Push to array
3. Save document

**Expected behavior**
When pushing the array then when saving the document the default values are automatically added.

**Additional context**
N/A.

**Versions**

| Dependency | Version |
| - | - |
| node | v16.6.1 |
| typescript | 4.4.3 |
| mikro-orm | 4.5.9 |
| your-driver | mongo |

**Comment by kaname-png** [comment]
@B4nan
Sorry for the ping, could you help me?

**Comment by B4nan** [comment]
You should be adding embeddable instances to your array, not POJOs. Sounds weird that this even type-checks.

```ts
// testDocument.test_array.push({ test_array_no_default: 'x' }); // <- wrong, adding a POJO
testDocument.test_array.push(new TestEntityArray('x')); // <- correct, adding an embeddable instance
```
