### ISSUE TITLE
migration:up

### ISSUE THREAD

**Issue by wguerram** [mikro-orm/mikro-orm#2234]
**Describe the bug**
Hello I've manage to create the initial migrations ts file but when I run migration:up looks like the migration up is not being run.

I just don't know what else todo. what am i missing?

**Stack trace**
```
I get a successful message but the tables are not being created.

Successfully migrated up to the latest version
...
```

**To Reproduce**
1. ... create an initial migration
2. ... run migration:up

**Expected behavior**
I'm expecting the up method to be executed.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | v14.17.6|
| typescript | 4.3.5 |
| mikro-orm | 5.0.0-dev.382 |
| your-driver | mariadb|

**Comment by genu** [comment]
Are you able to run `schema:create` successfully?

**Comment by wguerram** [comment]
Yes, schema:create does create the database and tables.

**Comment by genu** [comment]
Do you have a migrations table that is created as well? Does it have any data there?

**Comment by wguerram** [comment]
When I run migration:up the migration table is created but empty

**Comment by Langstra** [comment]
Maybe a misconfiguration? What does migration:pending say? Could be that your cli is looking for js files instead of ts?

Please provide a reproduction repo so we can help you better.

**Comment by Langstra** [comment]
If your migrations table is empty then it leads me to believe that your configuration is wrong. But as I said before, please create a reproduction so we can have a look.

**Comment by wguerram** [comment]
Hello, so in the process of creating a reproduction I identified my issue is related to the .env file. after removing the config variables from my .env file it worked. So the question I have now is it possible to use the CLI with the configuration in an .env file only or it's mandatory to use a mikro-orm.config.ts file? I was hoping on not adding mikro-orm to my package.json and not creating a mikro-orm.config.ts.

I tried adding thes two to my .env file but it keeps looking Error: MikroORM config file not found in ['./mikro-orm.config.js']
MIKRO_ORM_CLI_USE_TS_NODE=true
MIKRO_ORM_CLI=./mikro-orm.config.ts

 Thanks for your help.

**Comment by genu** [comment]
I haven't verified, but you should be able to drive mikro-orm from only env vars.

See: https://mikro-orm.io/docs/configuration/#using-environment-variables

**Comment by wguerram** [comment]
Thanks @genu that's my thinking. I can run the application from .env, the problem I have is with the CLI

The ones related to the CLI are missing in the example and I can't find a working example of .env and CLI.

**Comment by genu** [comment]
🤔 From what I can tell, the if the config doesn't exist, it checks for envs:

https://github.com/mikro-orm/mikro-orm/blob/f16b236ce04433b4790d39bd05d7ed60bfaaa3e0/packages/core/src/utils/ConfigurationLoader.ts#L40-L44

Have you made sure that `env` vars are loaded and set before CLI executes?

**Comment by wguerram** [comment]
Hi, yes the env variables are being loaded.

**Comment by genu** [comment]
how are you checking that they are loaded?
