### ISSUE TITLE
Migrations table is saved with extension

### ISSUE THREAD

**Issue by woltob** [mikro-orm/mikro-orm#2239]
Migrations table is saving the extension of the migration file as well.
This causes issues for me since I am using npx mikro-orm migration:up to run the migrations locally, but have to rely on JS compiled migrations on deployment and are running migrations inside the application code (main.ts) on application start up.

Can you add a fix please that would omit the extension (js or ts) or at least give the option so that this causing no issues.
Currently, it wants to run the migrations again as it does not recognise js migrations that already run.

![image](https://user-images.githubusercontent.com/24568645/135162229-73d3dc5a-a66d-4ce7-ad49-80c2a961fa7e.png)

**Comment by B4nan** [comment]
Would be nice if you stop assigning me. It feels quite rude from you - I am not your employee or a paid support, this is not how open source work.

Anyway, this is something I am planning to do in v5 - it will be a breaking change, so don't expect it in v4.

**Comment by woltob** [comment]
Hi B4nan, 

thanks for the quick reply. I am not aware that I actively assigned you, that seems to happen automatically when I submit a bug. Also, in no way do I want to be rude or see you as support. It is just that we are under a lot of pressure and decided to go with MikroORM as it seems to be very stable.

Thank you very much for your work, very much appreciated!

**Comment by B4nan** [comment]
Ooops my bad, I remembered I removed myself from automatic assignees but I just removed the automatic bug tagging - so sorry for the rant, my bad!

And let's keep this open, as said, I do plan to work on this in v5, this is definitely someting to improve.
