### ISSUE TITLE
Why is find.refresh per default configured to false?

### ISSUE THREAD

**Issue by olof-nord** [mikro-orm/mikro-orm#2252]
**Is your feature request related to a problem? Please describe.**

We recently ran into an issue, where when using `findAndCount`, the responses were partially cached/not up-to-date (stale?).

Specifying `refresh: true` solved the issue and allowed us to correctly fetch DB entries, also including recently changed values.

**Describe the solution you'd like**

`refresh: true` being the default configuration.

**Describe alternatives you've considered**

This is the question: why is this needed to explicitly set? What are the impacts of this flag?

**Additional context**

We are using MySQL, MIkro-ORM `4.4.4`. The data fetching is done through a DB view which we define in a migration and use in combination with an entity+repository. We use Typescript `4.3.5`.

**Comment by B4nan** [comment]
Because it will effectively erase the changes you might have done on the already loaded entities, resulting in lost updates

**Comment by B4nan** [comment]
FWIW, if you need to use `refresh: true` almost everywhere, it might be a sign of not having request context set up properly - you should have a fresh fork of EM (and therefore clean identity map) for each request handler.

https://mikro-orm.io/docs/identity-map
