### ISSUE TITLE
Cached `fields`

### ISSUE THREAD

**Issue by fider** [mikro-orm/mikro-orm#2292]
**Describe the bug**
Please check **To Reproduce** and **Expected behavior**

**Stack trace**
N/A

**To Reproduce**
```typescript
  const resultsWithIdsAndNameOnly = await em
    .getRepository(Db.Client)
    .find({}, { fields: ['id', 'name'] }); // fields used
    // Returns Array<{ id: string; name: string}>
    // As EXPECTED

  const resultsAlsoWithIdsAndNameOnly = await em
    .getRepository(Db.Client)
    .find({}, { fields: ['state'] }); // different fields used
    // Also returns Array<{ id: string; name: string}>
    // EXPECTED Array<{ state: string }>

  const sameHere = await em
    .getRepository(Db.Client)
    .find({}); // no fields used
    // Also returns Array<{ id: string; name: string}>
    // EXPECTED Array<{ ...allFields }>

  em.clear();
  // After  `clear`  everything is as expected - until next projection (next `fields` argument used)
```

**Expected behavior**
If projection (fields) used in query and next queries do not include or includes different projection, then entity manager cache should not be used.

If you will decide to implement it (fetch missing fields) please consider performing separate query that fetch all requried database fields, not only missing (to keep data consistency).

**Additional context**
N/A

**Versions**

| Dependency | Version |
| node | v14.18.1 |
| typescript | 4.4.2 |
| @mikro-orm/cli | 4.5.9 |
| @mikro-orm/core | 4.5.9 |
| @mikro-orm/postgresql | 4.5.9 |
| @mikro-orm/sqlite | 4.5.9 |

Tested with Postgres 12 (imo behaviour is caused by mikro-orm not by database)

**Comment by B4nan** [comment]
This is not result cache, this is identity map, you should use `refresh: true` to reload the entity state. Result cache do respect all of the options in the cache key.

Also note that this should work automatically in v5, once #2263 is merged. 

> If you will decide to implement it (fetch missing fields) please consider performing separate query that fetch all requried database fields, not only missing (to keep data consistency).

That is how it works in that PR, the query will be fired as you configure it, and all the fields (excluding those that you changed since you loaded the entity) will be updated.
