### ISSUE TITLE
[question] Should MikroORM.init fail if no connection to database?

### ISSUE THREAD

**Issue by vimmerru** [mikro-orm/mikro-orm#230]
**The question**
MikroORM.init now doesn't fail if no database connection (at least for MySQL). Was it done intentionally? Will it be able to re-connect when database will be available later?

**Comment by B4nan** [comment]
Nothing changed there lately, of course the main difference in v3 is that knex is used to connect to and work with the database. 

You say no database connection, that sounds pretty strange. I could understand that connection is ok but there is no database.

**Comment by B4nan** [comment]
Can you share more details? When I tried to turn off all databases and run mysql tests, it will fail with `Error: connect ECONNREFUSED 127.0.0.1:3307`. So apparently it does fail.

**Comment by vimmerru** [comment]
It fails on query execution, but not in MikroORM.init

**Comment by B4nan** [comment]
Hmm I guess that is how knex behaves, will double check that. Might be also because of connection pooling. 

So if you want this behaviour, you could simply fire “select 1” query right after calling init, right?

**Comment by vimmerru** [comment]
@B4nan Thanks! Now the behavior is clear.
