### ISSUE TITLE
docs(entities): error in example to creating database indexes

### ISSUE THREAD

**Issue by KostyaTretyak** [mikro-orm/mikro-orm#2329]
Not sure, but it looks like there is an error in the [documentation](https://mikro-orm.io/docs/defining-entities/#indexes):

```ts
@Entity()
@Index({ properties: ['name', 'age'] }) // compound index, with generated name
@Index({ name: 'custom_idx_name', properties: ['name'] }) // simple index, with custom name
@Unique({ properties: ['name', 'email'] })
export class Author {

  @Property()
  @Unique()
  email!: string;

  @Property()
  @Index() // generated name
  age?: number;

  @Index({ name: 'born_index' })
  @Property()
  born?: Date;

}
```

Here three times refer to a non-existent property `name`.

**Comment by B4nan** [comment]
Most of the examples are "incomplete" in that sense, e.g. this entity also don't have any PK, it also don't have proper decorator options like `nullable`, ofthen same property is defined multiple times to show different ways, ...). They show the parts they are about, not a complete code snippets that can be copy pasted - if you want that, it's better to check some of the example projects or ORM tests.

Feel free to send a PR adding that property, if you think it's confusing.
