### ISSUE TITLE
tableName ignored with discriminators

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#2356]
**Describe the bug**
If a tableName is defined on a root entity and a child entity is persisted, it will attempt to insert using the standard generated table name of the root entity.

**To Reproduce**

```typescript
@Entity({ tableName: 'foobar', discriminatorColumn: 'type', abstract: true })
export default abstract class ParentMikro {

}

@Entity({ discriminatorValue: 'child' })
export class ChildMikro extends ParentMikro {

}

manager.persist(new ChildMikro());
```

The above will attempt to insert into the `parent_mikro` table.

**Expected behavior**
I would expect tableName to be inherited for all child entities.

**Additional context**
If i take `abstract: true` away, the queries attempt to include a generated discriminator value for the root entity (`parent_mikro`) which will break because it is a postgres enum column.

I can work around this by just duplicating the table name on all the child entities.

**Versions**

```
  "@mikro-orm/cli": "^4.5.9",
  "@mikro-orm/core": "^4.5.9",
  "@mikro-orm/nestjs": "^4.3.1",
  "@mikro-orm/postgresql": "^4.5.9",
  "@mikro-orm/reflection": "^4.5.9"
```

**Comment by B4nan** [comment]
Can you also try this please? `tableName` is an alias for `collection`

```ts
@Entity({ collection: 'foobar', discriminatorColumn: 'type', abstract: true })
export default abstract class ParentMikro { ... }
```

**Comment by parisholley** [comment]
@B4nan nope, same behavior

**Comment by B4nan** [comment]
not reproducible in master, so already fixed (i can reproduce in v4)
