### ISSUE TITLE
Update Migration Documentation

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#2358]
Wasn't obvious that I needed to add `@mikro-orm/migrations` as a dependency (only referenced in v3 > v4 changelog), and example could include the import:

```import { Migration } from '@mikro-orm/migrations';```

**Comment by B4nan** [comment]
In which example? Only one where we could add that import is not really a code you would write, as migrations are generated from the CLI.

**Comment by parisholley** [comment]
i am migrating from typeorm to mikro orm with an existing production schema. the fact that knex and/or mikro does not support enum postgres migrations makes it a no-go for me, so i just create migration files by hand.

example under migration class

```
export class Migration20191019195930 extends Migration {

  async up(): Promise<void> {
    this.addSql('select 1 + 1');
  }

}
```

**Comment by B4nan** [comment]
You should/could still use CLI to migrate blank migration file. 

Anyway, PR welcome.

**Comment by parisholley** [comment]
is there a hidden command to create a blank file, i only see `migration:create`, which attempts to diff.

no problem on PR

**Comment by B4nan** [comment]
you can add `-b/--blank` to that, looks like those flags are not documented
