### ISSUE TITLE
Library Supported "Native" Custom Types (Enum Array)

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#2363]
Having read through some past issues/discussions, there seems to be a general constraint that anything vendor libraries (eg: knex or umzug) do not support prevents certain functionality from being introduced. in particular the constraint seems to mostly be around schema generation.

i ran into #2079, where I have an existing production schema which uses enum[] array types. understandly, managing enum types is hard to pull off due how the underlying tools work for schema generation, but if your opt'ing out of that part of the library, a lot of these things can easily be supported.

example simple enum array support:

```typescript
import { Type, ValidationError } from '@mikro-orm/core';

export class EnumArrayType extends Type<string[], string> {
  convertToDatabaseValue(value: any): string {
    if (!Array.isArray(value)) {
      throw ValidationError.invalidType(EnumArrayType, value, 'JS');
    }

    return `{${value.join(',')}}`;
  }

  convertToJSValue(value: any) {
    if (typeof value !== 'string') {
      throw ValidationError.invalidType(EnumArrayType, value, 'JS');
    }

    const trim = value.substr(1, -1);

    return trim.split(',');
  }
}
```

I think we could feature flag types, eg, expand the Type interface like so:

```typescript
abstract class Type {
  supportsSchemaGeneration(): boolean;
}
```
if the types are used in a project who attempts schema generation, we can throw an exception and point to documentation outlining how to go about managing migrations yourself.

**Comment by B4nan** [comment]
Not sure I follow here, there is already an [`EnumArrayType`](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/types/EnumArrayType.ts) that works pretty much this way, and it does support schema generation.

**Comment by parisholley** [comment]
postgres stores enum arrays as {FOO,BAR,BAM}

**Comment by B4nan** [comment]
yes, that is what that type is exactly doing

**Comment by B4nan** [comment]
https://github.com/mikro-orm/mikro-orm/blob/master/packages/postgresql/src/PostgreSqlPlatform.ts#L95

**Comment by parisholley** [comment]
alright my mistake, everything I was reading in old issues pointed to it (enum maybe?) not being implemented

**Comment by B4nan** [comment]
Native postgres enums are not implemented (better say schema diffing for native postgres enums is not implemented, you could use them via `columnType`), but postgres arrays are, and postgres enum arrays work as `text[]` in the schema generator - for querying part it should have the same interface as with native enums i guess?

**Comment by parisholley** [comment]
@B4nan thought, wouldn't ts-morph/reflect be able to detect that a mapping is an array? eg:

```typescript
@Enum()
enums: MyEnum[];
```

if so, shouldn't we implicitly set the type to EnumArrayType (the combination of using @Enum and []) unless the user overrides?
