### ISSUE TITLE
IdentifiedReference invoking Lifecycle Hooks

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#2365]
Detected within the same example/setup as #2364, except if you expand the BaseMikro like so:

```typescript
@Entity({ tableName: 'base', discriminatorColumn: 'type', abstract: true })
export default abstract class BaseMikro {
  @ManyToOne(() => BaseMikro, { fieldName: 'parentId', wrappedReference: true })
  parent: IdentifiedReference<ActivityMikro<any>>;

  @OnInit()
  test() {
   throw new Error('NOOOO!');
  }
}
```

the `test` method is invoked, but it is a "partial" object (BaseMikro, not the discriminated class), with just the primary key available, i would expect the lifecycle hooks to only happen on hydrated objects?

**Comment by B4nan** [comment]
Yes, that is how it works, the onInit hook might be executed twice, once when the reference is created, once when it gets hydrated. I believe it should fire just once if you load the relation via joined strategy in the same query, but with select-in strategy the parent is loaded separately and that is where the first event might be fired on the reference. 

You can distinguish between those via `wrap(this).isInitialized()` from inside the hook.
