### ISSUE TITLE
Create a "Documentation" ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#2368]
Figure it would be more sane to auto-tag the trivial stuff :)

https://github.com/mikro-orm/mikro-orm/tree/master/.github/ISSUE_TEMPLATE

**Comment by B4nan** [comment]
It's quite funny to hear this from you, given that you created ~20 issues in 2 days, and didn't follow the issue templates fully even once :D 

What would you expect from such template?

**Comment by parisholley** [comment]
i didn't have an idea for the content of template, just allowing the issues to auto-label as documentation. i suppose it could require a link to an existing page/section. figured you'd appreciate at a glance what to respond to if someone like me wants to spam a bunch of places to improve documentation :)
