### ISSUE TITLE
Allow Collection.init() type-safe population

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#2369]
When using the `Collection.init()` method on a relation, Mikro allows us to populate a `OneToMany` collection, however it is returning `Promise<this>` instead of a `Promise<Loaded<..>>. Because of this, we are forced to manually cast the collection to a populated type for compilation.

**Additional context**
```
    "@mikro-orm/cli": "^4.5.9",
    "@mikro-orm/core": "^4.5.9",
    "@mikro-orm/migrations": "^4.5.9",
    "@mikro-orm/nestjs": "^4.3.1",
    "@mikro-orm/postgresql": "^4.5.9",
    "@mikro-orm/reflection": "^4.5.9",
```

**Comment by B4nan** [comment]
That method returns the collection instance (so a fluent interface), not entities. What you are asking for is a breaking change. 

What you want can be achieved via em.populate().

**Comment by parisholley** [comment]
how would it be a breaking change? unless there are some classes which extend Collection or otherwise alter the return type throughout the fluent call chain, the signature can simply return Collection<T & Loaded<T>> or LoadedCollection, etc?

and while yes, it can be achieved with em.populate, that is assuming you want to pass it down multiple layers. there can be instances where you can rely on the entitles them selves to lazy load if you weren't falling a strict DTO-like pattern

**Comment by B4nan** [comment]
I got confused by the `Loaded` type suggestion, makes sense to make it a `LoadedCollection` I guess.
