### ISSUE TITLE
Argument differences between EntityManager and EntityRepository API's

### ISSUE THREAD

**Issue by klausXR** [mikro-orm/mikro-orm#2384]
From the documentation [here](https://mikro-orm.io/docs/repositories/), it appears as though a repository is just a shortcut for the underlying EntityManager API, but why are the arguments different?

For example, look at the `findOne` docs of both - [EntityRepository](https://mikro-orm.io/docs/repositories-api/#findonewhere-filterqueryt--string-populate-string-promiset--null) - [EntityManager](https://mikro-orm.io/docs/entity-manager-api/#findoneentityname-entitynamet-where-filterqueryt-options-findoneoptionst-p-promiseloadedt-p--null)

There does not seem to be a way to specify the loading strategy on a specific query when using the EntityRepository, but it is available through the EntityManager.  

Is this discrepancy intentional? If the EntityRepository is merely a more convenient way of using the EM, then their functionality must be identical, except for the omitted first argument.

**Comment by B4nan** [comment]
You are looking at outdated docs, the arguments are not different - just check the actual code:

https://github.com/mikro-orm/mikro-orm/blob/v4.5.9/packages/core/src/EntityManager.ts#L306
https://github.com/mikro-orm/mikro-orm/blob/v4.5.9/packages/core/src/entity/EntityRepository.ts#L51 

From the code of the repository you can clearly see, that it's exactly like that, repository is just forwarding calls to entity manager.

Not sure where you found links to them, as they are no longer part of the sidebar. Correct API docs pages that are actually linked from sidebar:

https://mikro-orm.io/docs/api/classes/core.entitymanager/#findone
https://mikro-orm.io/docs/api/classes/core.entityrepository/#findone

But those are unfortunately also rendered wrongly. I am planning to use different typedoc plugin that should hopefully resolve it, also v5 uses different (simplified) signature that should help as well, in v4 (as you can see from the code), there are 3 signatures for `findOne`, v5 has only one.

**Comment by klausXR** [comment]
I found them by going to https://mikro-orm.io/ and searching for "EntityRepository API". Perhaps you have a cache invalidation issue.
