### ISSUE TITLE
Missing quotes around defaults with MySQL

### ISSUE THREAD

**Issue by franck-co** [mikro-orm/mikro-orm#2385]
**Describe the bug**
migrations set default values for string every time.
(The db diffing is incorrect because it treats the default value for varchar columns without quotes)

**To Reproduce**

1. Create an entity with a default string
```ts
@Entity()
export class MyEntity {

    @PrimaryKey()
    id!: number

    @Property({ default: "NEW" })
    stringDefault!: string
}
```
2. disable snapshots in the config (the problem occurs when the source is the db)

3. create a migration and run it 
(or just run the following query : ```create table `MyEntity` (`id` int unsigned not null auto_increment primary key, `stringDefault` varchar(255) not null default 'NEW') default character set utf8mb4 engine = InnoDB`)```

4. create the migration again.

**Expected behavior**
The 2nd migration should be empty but it contains
```SQL
alter table `MyEntity` modify  `stringDefault` varchar(255) not null default \'NEW\'
```

**Additional context**
It seems that the problem occurs because in `MySqlSchemaHelper.getColumns()`, the default value has no quotes. 

As a result, the schema comparator compares `default:''NEW''` with `default:'NEW'` and think it must correct it every time.

**Proposed fix**
in  `MySqlSchemaHelper.getColumns()`

replace
```
default:  col.column_default
```
by
```
default:  mappedType instanceof StringType ? `'${col.column_default}'` : col.column_default
```
Or something like that. 
But maybe there is a reason why the defaults are handled this way.

**Versions**

| Dependency | Version |
| - | - |
| node | v14.16.1 |
| typescript | 4.4.4 |
| mikro-orm | 5.0.0-dev.434 |
| your-driver | @mikro-orm/mysql |

**Comment by B4nan** [comment]
Thanks for the report, got it reproduced and I can confirm it behaves this way.
