### ISSUE TITLE
Support aurora serverless database with data api client

### ISSUE THREAD

**Issue by nickygb** [mikro-orm/mikro-orm#2387]
It would be nice to add support to aurora serverless via data api client. There is a library I use in production in some projects [knex-aurora-data-api-client](https://github.com/markusahlstrand/knex-data-api-client#readme) that allows to use knex with aurora serverless data api client.

I imagine two ways to implent this new feature: 

1. Add the possibility to initialize MikroORM passing knex instance, like it does Objection.js
2. Create a new package for `aurora-serverless` with AuroraServerlessConnection.ts  that createKnexInstance using knex-aurora-data-api-client.

**Comment by B4nan** [comment]
I am not interested in adding/maintaining more drivers right now. The interface is already extensible, and the correct way is to create new driver (extending the ones that already exists if possible, which definitely is if there is a knex support).

Closing, but feel free to ask more if you'd like to give that a try. It should be first born as a 3rd party package.

Note that you can already alter anything that gets passed to the `knex()` function via `driverOptions` configuration, so if only thing you need to change is those options, you already can. 

https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/AbstractSqlConnection.ts#L149
