### ISSUE TITLE
Embedded onCreate/onUpdate persist, but do not update IdentityMap 

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#2391]
```typescript
@Embeddable()
export default class Audit {
  @Property({ fieldName: 'archived' })
  archived?: Date;

  @Property({ fieldName: 'updated', onCreate: () => new Date(), onUpdate: () => new Date() })
  updated: Date;

  @Property({ fieldName: 'created', onCreate: () => new Date() })
  created: Date;
}

@Embeddable()
export default class Entity {
  @Embedded(() => Audit)
  audit = new Audit();
}

let line = manager.create(Entity, {});
manager.persist(line);
await manager.flush();

assert(!!line.audit.created); // fail

line = manager.findOne(Entity, line.id, {refresh:true});
assert(!!line.audit.created); // pass
```

If I remove the embedded above and just put `created`/`updated`/`archived`/ directly on entity, it gets updated as expected.

**Versions**

```
    "@mikro-orm/cli": "^4.5.9",
    "@mikro-orm/core": "^4.5.9",
    "@mikro-orm/migrations": "^4.5.9",
    "@mikro-orm/nestjs": "^4.3.1",
    "@mikro-orm/postgresql": "^4.5.9",
    "@mikro-orm/reflection": "^4.5.9",
```

**Comment by B4nan** [comment]
I don't think embeddables ever supported `onCreate/onUpdate`, those are handled only for entities. Not every property options are supported, it is basically the very opposite, only a small subset is (e.g. hooks are also not supported). Why don't you use property initializers? That is the suggested way here.

**Comment by parisholley** [comment]
> Not every property options are supported,

that is fine, though if there are features which are known to be unsupported, the bug is more-so that it allowed me to bootstrap without throwing an exception when building the metadata. in particular, this type of thing could easily get missed, i just so happened to catch it because i was using the dates immediately in some instances.

> I don't think embeddables ever supported onCreate/onUpdate

given that they are invoked and persist, it seems to be "half-supported". question is do we remove the persistence (so that it is truly unsupported), or fix the "bug" in not updating the identity map.

> Why don't you use property initializers

that is my workaround for now since usually i am not accessing the dates within the same transaction, and the onUpdate appears to still persist just not available right away
