### ISSUE TITLE
`LoadedCollection.get()` array not updated when collection is adjusted

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#2394]
**Describe the bug**

```typescript
const items = entity.items.get();

assert(items.length === 1); // pass
// items.push(item); // compile error, items is read only

entity.items.add(item);

assert(items.length === 2); // fail
```

I can see why the behavior may be the way it is (it is generating a unique immutable array each call), but if that is a specific constraint (instead of caching/returning the same array), then perhaps it should return an iterator instead. 

**Versions**

```
    "@mikro-orm/cli": "^4.5.9",
    "@mikro-orm/core": "^4.5.9",
    "@mikro-orm/migrations": "^4.5.9",
    "@mikro-orm/nestjs": "^4.3.1",
    "@mikro-orm/postgresql": "^4.5.9",
    "@mikro-orm/reflection": "^4.5.9",
```

**Comment by B4nan** [comment]
It does return a copy on purpose, to forbid things like `items.push()`, which would not trigger propagation. You should work with the collection if you want to have up to date data. Collection implements iterator.

**Comment by parisholley** [comment]
right, but the issue isn't mutation on the cloned array, its that the propagation system should have a record of arrays/iterators it handed out and can keep them up to date

making the user do a `Array.from(iterator)` makes it obvious that you are mutating a clone, a read-only array does not imply anything about subscription behavior

**Comment by B4nan** [comment]
I don't agree it should handle that 🤷 The method gives you snapshot (so you can run things like filter or sort), if you want up to date data, work with the collection instance. 

Maybe the LoadedCollection.get method should return the collection instance. That would be more aligned with LoadedReference. Right now it is basically alias for getItems().

**Comment by parisholley** [comment]
> if you want up to date data, work with the collection instance

in general, i agree, but i'll always advocate to expose APIs defensively, i'd rather not depend on a junior dev to know that distinction if they aren't comfortable with the ins/outs of the library

> Maybe the LoadedCollection.get method should return the collection instance

i think that is a fair change, if you need array, you can `Array.from` it

**Comment by B4nan** [comment]
Yeah or call getItems() explicitly. This will be a breaking change so v5.
