### ISSUE TITLE
`EntityManager.remove()` does not propagate to 1:M collections

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#2395]
**Works**
```typescript
assert(invoice.lines.get().length === 2); // pass

for(const line of invoice.lines.get(){
  if(line.id === '1'){
    invoice.lines.remove(line);
  }
}

assert(invoice.lines.get().length === 1); // pass
```
**Broken**
```typescript
assert(invoice.lines.get().length === 2); // pass

for(const line of invoice.lines.get(){
  if(line.id === '1'){
    em.remove(line);
  }
}

assert(invoice.lines.get().length === 1); // fail
```

This is problematic because the remove call could be done by a downstream service and the upstream consumer would be unaware. If you do a flush, the propagation does occur but we shouldn't depend on this, especially considering that persisting a new entity with a M:1 will update the 1:M collection, eg: 

**Broken**
```typescript
assert(invoice.lines.get().length === 2); // pass

for(const line of invoice.lines.get(){
  if(line.id === '1'){
    em.remove(line);
  }
}

awaot em.flush();

assert(invoice.lines.get().length === 1); // pass
```

**Versions**

```
    "@mikro-orm/cli": "^4.5.9",
    "@mikro-orm/core": "^4.5.9",
    "@mikro-orm/migrations": "^4.5.9",
    "@mikro-orm/nestjs": "^4.3.1",
    "@mikro-orm/postgresql": "^4.5.9",
    "@mikro-orm/reflection": "^4.5.9",
```

**Comment by B4nan** [comment]
You should be using collection.remove() if you want propagation to happen. You know you keep asking for things that can be implemented, but will add a performance penalty. At the same time you complain about flush performance, as well as ask for it to run on each find calls (that is really the only way i can imagine auto flush to work).

**Comment by parisholley** [comment]
> You should be using collection.remove() if you want propagation to happen

in simple app perhaps, but the service layers can pull data at any time and may be unaware of some other module which has a reference to an initialized collection. this of course will compound if that entity belongs to multiple 1:M collections across various models.

> You know you keep asking for things that can be implemented, but will add a performance penalty.

i'm aware of the performance implications, but consistency is more important than performance. you can optimize for speed, you can't undo production data corruption. additionally, a `performance penalty` is very relative:

* endpoints that are more reads than writes, mutation propagation is less an issue
* endpoints that are heavy writes (eg: thousands, batches) have different considerations
* endpoints that are all reads, no writes

there are various strategies you could put in place the solve each of those scenarios differently, it isn't practical that the API is going to address them all perfectly using the same methods. its better to make the user opt-in to performance, then to opt-in to consistency.

>  At the same time you complain about flush performance, as well as ask for it to run on each find calls (that is really the only way i can imagine auto flush to work).

don't think that is a fair assessment of my feedback (complaining). the CPU time of an operation can be optimized regardless of the frequency in which it is used. i've only made one issue on flush performance and found a clear optimization opportunity (i'm nearly done getting my test suite green and the patch hasn't presented any problems).
 
code can be refactored to minimize flushing, whether in the library or by the user, but saying a user shouldn't call it so much isn't an excuse for it performing poorly

as a note, i'm creating these issues as I believe Identity Mapped ORMS are sorely needed in the JS ecosystem while also understanding that you are pretty much doing it all yourself. i file these issues so we can have dialog on architecture so that I may contribute effectively (once my project is green, i'll be address many of the issues i filed myself). i'm not criticizing the quality of the code or work you have done, Hibernate was started over 20 years ago, i don't expect this project to do everything it does within a few years of only one sole contributor :)

**Comment by B4nan** [comment]
> This is problematic because the remove call could be done by a downstream service and the upstream consumer would be unaware. If you do a flush, the propagation does occur but we shouldn't depend on this, especially considering that persisting a new entity with a M:1 will update the 1:M collection, eg:

It is not `em.persist()` that does the propagation, it is the `em.create()` call, or better say the fact that you assign a value to the m:1 property. This works via patched entity prototypes, no need to use `em.create()`. 

https://mikro-orm.io/docs/propagation

Both `em.persist()` and `em.remove()` just adds to persist/remove stacks and everything is delegated to flush operation. More over, if you call `em.remove()`, that entity is automatically removed from persist stack, and vice versa. That is how your test code is interpreted:

```ts
const parent = orm.em.create(Parent, {});
orm.em.persist(parent); // add parent to persist stack
const instance = orm.em.create(Child, { parent });
orm.em.persist(instance); // add instance to persist stack
orm.em.remove(instance); // remove instance from persist stack and add it to remove stack

// during flush we actually remove the item and call `unsetIdentity()` on it, which goes
// thru all relations of that entity and removes it from the inverse side properties
await orm.em.flush();
```

Your proposal is basically to call the `unsetIdentity()` right when calling `em.remove()` but that would break this situation:

```ts
const instance = await orm.em.findOne(Child, ...);
orm.em.remove(instance); // add instance to remove stack
orm.em.persist(instance); // remove instance from remove stack and add it to persist stack

// flush would be no-op here, as the entity is managed and is not part of remove stack
await orm.em.flush();
```

As we can't simply undo calling `unsetIdentity()` without caching the values we remove. I am not convinced this should be addressed, both `em.persist` and `em.remove` work in the same manner now. The counterpart to assigning m:1 property is using `Collection.remove()` and that works fine.

**Comment by parisholley** [comment]
> Both em.persist() and em.remove() just adds to persist/remove stacks 

Makes sense.

> As we can't simply undo calling unsetIdentity() without caching the values we remove.

I'm not sure I understand enough of the underlying code to interpret this.

> The counterpart to assigning m:1 property is using Collection.remove() and that works fine.

Not sure what you mean by "counterpart". Assigning to the m:1 property would mean either `child.parent = parent` or `child.parent = null`. If setting to null, I imagine you remove the relationship but not the underlying entity.

> I am not convinced this should be addressed, both em.persist and em.remove work in the same manner now.

I don't think this would change how the stacks/flush model works. Each item in a `Collection` could have a reference to the collection it was pulled from and simply to do a `collection.remove()` behind the scenes?

otherwise, I would prefer that `em.persist()` throw an exception and tell the user they must do `collection.remove()`

**Comment by B4nan** [comment]
Looking at the repro once again, and the issue with that is you are trying to schedule removal on a fresh entity that was not yet persisted to database - `em.remove()` is ignored for entities that does not have PK set just yet. That can be easily fixed.

But here in the OP you were talking about a bit different issue I believe? Like you wanted that to happen before flush?

**Comment by parisholley** [comment]
> But here in the OP you were talking about a bit different issue I believe? Like you wanted that to happen before flush?

correct, the repo isn't the same as OP (existing entity which was being passed across service boundaries)

> Note that those methods need to be fast, and the fact that propagation is postponed till flush is a performance optimization.

**thought**: could a `propagate()` method be introduced which updates memory state, but doesn't issue queries until you `flush()`? regardless of outcome of this issue, that could allow someone to clean things up before hopping across service boundaries.

>  it will slow down working with many entities in one unit.

alternatively, maybe an em could be forked, or some equivalent of `em.transaction()` with a callback could wrap a series of interactions in a "propagate" at the end of execution. in the `.transaction()` model, i'd probably have my project throw an exception if you didn't start a "propagation transaction" prior to doing collection/em.remove(). 

> Once again, it is not persist call that does anything here

think i misspoke, i meant have `em.remove()` throw an exception

> If remove will do more than just put things on remove stack, persist would need to do the opposite, wiring relations back.

i think the case could be made this doesn't have to be inverse behavior. doing `em.remove(child)` would queue the entity itself for removal, and clean out all the associations. if you were to `em.persist(child)` later, it would keep the entity but still leave the associations removed (assuming no M:1 properties are set on the entity)?

*recap*

to restate the initial motivation behind this issue, the larger concern is around business logic making assumptions on entity state. example, say my service method will add up all the invoice line amounts to charge a credit card. at the end of my transaction, my database will be in the expected state (whether doing em.remove() or collection.remove()), but if my "sum" logic happens after entities are removed (say, due to some logic layers deep in delegated service calls) and i make a call to stripe, i will potentially be overcharging the customer.

collections are always particularly tricky in an ORM, whether it is lazy loaded (typeorm) or UoW patterns. i always look at native collection support as a convenience which inevitably comes with some trade-off (in this case, i'm proposing that trade-off be performance). 

i don't think collection removal is a common enough pattern that performance would need to be prioritized. if you are doing some type of n+1 logic, inherently you understand there is a performance penalty at scale. persist/insert/update patterns i would say are generally low-risk and work how you expect 99% of the time. as you mentioned, the prototype hooks will solve for most creation/insert paths but there isn't really anything implemented on the remove side.

**Comment by B4nan** [comment]
> i don't think collection removal is a common enough pattern that performance would need to be prioritized. 

It is not about being slow in that particular case, but rather about making any entity removal slower. 

Also note that you keep talking about collections, this problem is not just about collections, same issue is with references - if you mark some entity for removal, it will stay referenced if it has bidirectional relations. So very same issue if you remove the entity with 1:m collection, and it will stay referenced from its owner. Or same with 1:1 relations. Even with m:n relations, same. Because as I mentioned several times, propagation happens based on how you work with the entity (so assigning to m:1/1:1, or working with Collection.add/remove/set), not based on persist/remove calls.

I can imagine having a flag to control this behaviour, either globally, or locally in `em.remove()` calls. Then we can see how it behaves in terms of performance and interop with `em.persist()`. But right now I still feel like it will be too breaking to be the default.

**Comment by parisholley** [comment]
> I can imagine having a flag to control this behaviour

that is fair

> propagation happens based on how you work with the entity (so assigning to m:1/1:1, or working with Collection.add/remove/set), not based on persist/remove calls

right, the "point of entry" is different but the the behavior is the same? one part of the API (whether via collections or manual assignment) propagates without flushing but there isn't a mechanism for delete, which is what i find unintuitive.  i'd rather tell a developer that everything propagates or nothing does, where as right now, it depends on how you use the library and can lead to bugs

**Comment by parisholley** [comment]
to expand on my earlier idea of throwing, if we know an entity is inside a collection (can be a simple boolean without a lot of layer checking) and we call `em.remove(entity)`, we can throw and tell them to remove from a collection first. this is much more of a breaking change than propagation which would need to be flagged. alternatively, we could just expose some utility method to check if an entity is in a collection, eg: `em.isInCollection(entity)`, that way I can do the check myself in a "wrapped" EntityManager

**Comment by B4nan** [comment]
I guess I changed my mind, let's do the propagation by default in v5 and see how it works. We could always revert it and hide it behind a flag if it causes any problems. I agree consistency is worth it.
