### ISSUE TITLE
Tuple comparison

### ISSUE THREAD

**Issue by xeladejo** [mikro-orm/mikro-orm#2399]
**Is your feature request related to a problem? Please describe.**
At Least MySQL allow "tuple" comparison, this allow write complex where clause in a much simpler way.

**Describe the solution you'd like**
I would like to be able to perform a query with a syntax similar to:
```ts
entityRepository.find({ [expr(["created", "id"])]: { $le: [cursor.created, cursor.id] } });
```
So that generates a query like
```sql
select `e0`.* from `entity` as `e0` where (`e0`.`created`, `e0`.`id`) < ('2020-06-22 12:30:30.000', 44)
```

**Describe alternatives you've considered**
Use the same query expressed in a much more complex way:
```ts
entityRepository.find(
    {
        $or: [
            { created: { $lt: cursor.created } },
            { $and: [{ created: { $eq: cursor.created } }, { id: { $lt: cursor.id } }] },
        ],
    },
);
```
Which generates the following query:
```sql
select `e0`.* from `entity` as `e0` where (`e0`.`created` < '2020-06-22 12:30:30.000' or (`e0`.`created` = '2020-06-22 12:30:30.000' and `e0`.`id` < 44))
```

**Additional context**
From MySql [documentation](https://dev.mysql.com/doc/refman/8.0/en/comparison-operators.html#operator_less-than):
> For row comparisons, (a, b) < (x, y) is equivalent to:
> ```
> (a < x) OR ((a = x) AND (b < y))
> ```

**Comment by B4nan** [comment]
The API would probably need to look differently. `expr` is just an identity function to get around TS strict types, and object key needs to be a string, can't be array. 

Tuple comparison itself should already work internally, it is currently used for composite keys (e.g. in `where in` queries for composite PKs). Btw it works for all supported SQL drivers (sqlite is a bit more verbose as you need `values()` in the mix).

Btw this might already work:

```ts
entityRepository.find({ [expr('(e1.created, e1.id)')]: { $lte: [cursor.created, cursor.id] } });
```

**Comment by xeladejo** [comment]
Yeah, the second approach it's working. Something as `entityRepository.find({ [row('created', 'id')]: { $lte: [cursor.created, cursor.id] } });` with TS auto completed for the rows names it would be better :wink:, but this is enough for me.

What is `~~~`?

Thanks you.

**Comment by B4nan** [comment]
We can support what you suggested, this can happen behind the scenes. The tripple tilde is how composite keys are handled internally, so we have a single key in queries, so exactly this use case.

**Comment by B4nan** [comment]
> with TS auto completed for the rows names it would be better 😉, but this is enough for me.

That probably won't fly, there is no context inside the `expr` method, you'd have to pass the generic type argument explicitly like `expr<User>(['name', 'email'])` (we can definitely have such type arg, optional).
