### ISSUE TITLE
Alias-aware expr() support

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#2405]
**Is your feature request related to a problem? Please describe.**

When using expr, unless you have a single table `find()` or a query builder with an alias, you can hit ambiguous column errors due to the lack of column prefixing. Eg: self-referential eager joins

**Describe the solution you'd like**
Expand expr to support passing a function like so:

```typescript
expr((alias) => `lower(${alias}.column)`)
```

alternatively, perhaps we can add the ability to define the alias within find methods

**Comment by B4nan** [comment]
How do you expect that to work? `expr` is just an identity function, it needs to return string as it will be used as an object key. It also does not have any context so it would have to use global one?

**Comment by parisholley** [comment]
substring would be sufficient
