### ISSUE TITLE
Initialized connections when forceEntityConstructor = true

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#2406]
**Describe the bug**
This is either a documentation issue, or library issue. The docs say to initialize your model collections like so:

```typescript
procession = new Collection<JobProcessMikro>(this);
```

however the third parameter in that constructor is setting `Collection.initialized = true`, meaning any attempts to populate or `collection.loadItems()` will not do anything. When forceEntityConstructor is disabled, collections are added to the model with initialized = false

```
    "@mikro-orm/cli": "^4.5.9",
    "@mikro-orm/core": "^4.5.9",
    "@mikro-orm/migrations": "^4.5.9",
    "@mikro-orm/nestjs": "^4.3.1",
    "@mikro-orm/postgresql": "^4.5.9",
    "@mikro-orm/reflection": "^4.5.9",
```

**Comment by B4nan** [comment]
Regular population probably works fine, right? Otherwise it would be quite weird noone would report this sooner. 

Anyway, definitely a bug.

**Comment by parisholley** [comment]
populate doesn't work when doing em.findOne(Entity, id, {populate:...}); just runs a single query

**Comment by parisholley** [comment]
believe i ran into the reason why it is true by default... if you create two new entities, and associate them, then run a populate (or loadItems) before a flush occurs, the collections will get reset since initialized = false, related to #2408

**Comment by parisholley** [comment]
see my reproduction case here:

https://github.com/mikro-orm/mikro-orm/pull/2409

i tried to workaround by doing new Collection(this, undefined, false), but that opened up another can of worms
