### ISSUE TITLE
Throw exception if adding item to unitialized collection

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#2408]
> When cascade persisting collections, keep in mind only fully initialized collections will be cascade persisted.

at the moment, the library will allow you to lose data without warning

```typescript
entity.collection.add(new Entity());

await entity.collection.loadItems();
```

It feels like this code should do one of two things:

a) if entity has been persisted, throw an exception when adding to an uninitialized collection
b) if loadItems() is invoked, persist any pending items in the collection

**Comment by B4nan** [comment]
Adding to not initialized collection is a feature, so nothing i would like to explicitly disallow. 

Sounds like this would be covered with auto flush, or not? It uses em.find() under the hood too. 

I could even imagine that we just automatically merge the loaded items with those newly added. That way it would basically behave same way as if you swap those lines.

**Comment by parisholley** [comment]
what is an example use case of adding to an unitialized collection for a persisted entity?

yep, could be covered by auto flush

merging could work too.

**Comment by B4nan** [comment]
You dont need to load the items to add a new one, do you really want me to give you examples why thats good? :) collections can be huge. 

I would go with merging as autoflush could be disabled (or we might end up having it opt in due to performance penalties, lets see how it will behave when its there).

**Comment by parisholley** [comment]
ah, good feature to have 👍
