### ISSUE TITLE
Support running EntityManager inside Promise.all

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#2412]
From what I can tell, the only concern here is in flushing behavior since that has to be done in isolation. Any non-async calls (persist, remove, etc) will effectively block in order. Given that I have existing `Promise.all` code, I simply put a queue in place to run the flush in order (for context, these flushes are happening due to auto-flushing).

```typescript
  const flush = em.flush;

  let flushing = false;
  const queue: (() => Promise<void>)[] = [];

  em.flush = async (...args) => {
    if (flushing) {
      await new Promise<void>((resolve, reject) => {
        queue.push(async () => {
          try {
            await flush.apply(em, args);

            resolve();
          } catch (ex) {
            reject(ex);
          }
        });
      });

      return;
    }

    flushing = true;

    await flush.apply(em, args);

    while (queue.length) {
      await queue.shift()();
    }

    flushing = false;
  };
```

**Comment by B4nan** [comment]
Yeah that could work, better than disallowing parallel flush I guess. Do I read it right that you are using all those suggested patched in your app, so they are kinda tested to work in your environment?

**Comment by parisholley** [comment]
yeah, so far i've patched things like the above for auto-flushing, etc, no problems so far.

i have ran into one issue with the above queue example where for some reason the id isn't being set even though the insert happened (confirmed via debug) and my BaseEntity throws an exception for accessing an unset id. i'll need to dig into this more.

**Comment by B4nan** [comment]
Interesting, this actually batches the queries into a single transaction:

```ts
const ret = await Promise.all([
  (async () => {
    const a = new Author2('a1', 'e1');
    const b = new Book2('t1', a, 123);
    await orm.em.persistAndFlush(b);
    return b;
  })(),
  (async () => {
    const a = new Author2('a2', 'e2');
    const b = new Book2('t2', a, 456);
    await orm.em.persistAndFlush(b);
    return b;
  })(),
  (async () => {
    const a = new Author2('a3', 'e3');
    const b = new Book2('t3', a, 789);
    await orm.em.persistAndFlush(b);
    return b;
  })(),
]);
```

```sql
begin
insert into "author2" ("created_at", "updated_at", "name", "email", "terms_accepted") values ($1, $2, $3, $4, $5), ($6, $7, $8, $9, $10), ($11, $12, $13, $14, $15) returning "id", "created_at", "updated_at", "age", "terms_accepted"
insert into "book2" ("uuid_pk", "created_at", "title", "price", "author_id") values ($1, $2, $3, $4, $5), ($6, $7, $8, $9, $10), ($11, $12, $13, $14, $15) returning "uuid_pk", "created_at", "title"
commit
```
