### ISSUE TITLE
Collection items are unstably stringify

### ISSUE THREAD

**Issue by JuRoy** [mikro-orm/mikro-orm#2431]
**Describe the bug**

`JSON.stringify` seems to produce unstable output with `Collection`

Sometimes, only the id is serialized, sometimes it is the whole object.

**Stack trace**
```
> JSON.stringify(user)

'{"id":"e59fa40e-1406-4ab0-9a30-a5df85683618","created_at":"2021-11-19T21:36:22.784Z","roles":["344457fe-c5cf-48dd-af8d-d66c95e983b3"]'

> JSON.stringify({...user})

'{"id":"e59fa40e-1406-4ab0-9a30-a5df85683618","created_at":"2021-11-19T21:36:22.784Z","roles":[{"id":"344457fe-c5cf-48dd-af8d-d66c95e983b3","role":"service","user_id":"e59fa40e-1406-4ab0-9a30-a5df85683618"}]'
```

**To Reproduce**
```
export default class UserModel {
  [EntityRepositoryType]?: UserRepository;

  @PrimaryKey({type: 'string'})
  id?: string;

  @Property({type: Date})
  created_at = new Date();

  @OneToMany(() => RoleModel, (r) => r.user, {cascade: [Cascade.ALL], eager: true})
  roles = new Collection<RoleModel>(this);
}

export default class RoleModel {
  [EntityRepositoryType]?: RoleRepository;

  @PrimaryKey({type: 'string'})
  id?: string;

  @Property({type: 'string'})
  user_id?: string;

  @ManyToOne({
    entity: () => UserModel,
    inversedBy: 'roles',
    joinColumn: 'user_id',
    referenceColumnName: 'id',
  } as any)
  user!: UserModel;

  @Property({type: 'varchar'})
  role!: RoleLevel;
}

const user = new UserModel(userDto)
newUser.roles = new Collection<RoleModel>(newUser, [new RoleModel(roleDto)]);
await userRepository.persistAndFlush(newUser);
console.log(JSON.stringify(user))
console.log(JSON.stringify({...user}))
```

**Expected behavior**
I expect to always receive the full serialized version of the Collection items.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | v16.13.0 |
| typescript | 3.8.3 |
| mikro-orm | 4.5.9 |

**Comment by B4nan** [comment]
Those two ways are very different, the second one is not serialization of entity, as with the destructing you are creating new POJO, this way the collection dont have the context. 

Collection will give you the same results if it is in the same state. Serialization works based on the context where the entity was loaded, so it cant work if you dont work with entity at all. Maybe you just dont have request context set up properly, that is a common source of such issues. 

Closing as the repro is invalid, feel free to adjust it to something more realworld like, as you should not do those things in your app (both assigning new collection instances, or destructing entities this way).

Btw you might wanna use populateAfterFlush option, that way collections after flush will get marked as if they were populated (which then have effect on the serialization).
