### ISSUE TITLE
feat(filters): apply filters to auto-joined entities too

### ISSUE THREAD

**Issue by TheNightmareX** [mikro-orm/mikro-orm#2434]
**Is your feature request related to a problem? Please describe.**

I have made all the entities soft-deletable using https://github.com/mikro-orm/mikro-orm/issues/1492#issuecomment-785394397 and `em.addFilter("exclude-soft-deleted", { deleted: false });`

I tried to execute `em.find(Classroom, { membership: { owner: user } });` to get all the classrooms the user had joined. I expected the final query will be like `{ memberships: { owner: user, deleted: false }, deleted: false }`, but it turned out that the final query is like `{ memberships: { owner: user }, deleted: false }`, which caused the soft-deleted memberships are not excluded and then the classrooms the user had already exited still appeared in the query result. I must change the call to `em.find(Classroom, { membership: { owner: user, deleted: false } });` to exclude those soft-deleted memberships.

**Describe the solution you'd like**

Apply filters to auto-joined relations too, so that we won't have to repeat `deleted: false` over and over again, which is really frustrating.

**Comment by B4nan** [comment]
What do you mean by auto joined? How does the actual `em.find` call look like? That exact query (`em.find(Classroom, { membership: { owner: user } });`) is not populating anything, it just returns `Classroom` entities, hence it is enough if the filter is applied to the root entity. So maybe you are referring to joined strategy? Still you would have to populate explicitly or use eager loading.

**Comment by TheNightmareX** [comment]
Thanks for the reply.

```ts
this.em.find(Classroom, { memberships: { owner: 1 } });
```

```sql
select `e0`.* from `classroom` as `e0` left join `membership` as `e1` on `e0`.`id` = `e1`.`classroom_id` where `e0`.`deleted_at` is null and `e1`.`owner_id` = 1
```

The `membership` table is left-joined automatically because the condition involved it. 

`deleted_at is null` is only applied to the `classroom` table, I expect it to apply to the left-joined `membership` table too.

**Comment by B4nan** [comment]
> The membership table is left-joined automatically because the condition involved it.

Joined but not selected, that query selects only classrooms.

**Comment by TheNightmareX** [comment]
But as the global filter with the condition `{ deletedAt: null }` is not applied to the joined table, soft-deleted entities will be able to affect the query result. I guess may be it will make more sense if the global filter can prevent all the the soft-deleted entities from 
affecting queries ?

**Comment by rhyek** [comment]
Why was this closed?

**Comment by B4nan** [comment]
I think it was replaced by #2440.
