### ISSUE TITLE
There is a problem with fetching partial entities.

### ISSUE THREAD

**Issue by WumaCoder** [mikro-orm/mikro-orm#2435]
### Discussed in https://github.com/mikro-orm/mikro-orm/discussions/2432

<div type='discussions-op-text'>

<sup>Originally posted by **WumaCoder** November 20, 2021</sup>
I wanted to get the `group.name` and `group.creator.name` attributes, but he didn't return the `group.creator.name` attribute to me.

```ts
const [list, count] = await this.em.findAndCount(Group,{}, {
      populate: ['creator'],
      fields: ['name', 'creator',{ creator: ['name'] }],
 })

console.log(list);
/*
result:
    [
      {
        "id": "61988a133bc907382be7e56e",
        "name": "a",
        "creator":{
           "id": "6190e01900f84f823eb7a26b",
          "createdAt": "2021-11-14 18:08:25",
          "updatedAt": "2021-11-14 18:08:25",
          "openid": "openid_admin",
          "nick": "admin",
          // ...
        }
      },
    ]
*/
```

```ts
@Entity()
export class Group extends CommonEntity {
  [EntityRepositoryType]?: GroupRepo;

  @IsString()
  @Property()
  name: string;

  @ManyToOne(() => User, { strategy: LoadStrategy.SELECT_IN })
  creator: User;

  // ...
}


@Unique({ properties: ['unionid', 'openid'] })
@Entity()
export class User extends CommonEntity {
  [EntityRepositoryType]?: UserRepo;
  @IsString()
  @Property()
  nick: string; 

  @IsString()
  @Property()
  name: string; 

  @OneToMany(() => Group, (group) => group.creator)
  createdGroups = new Collection<Group>(this);
  // ...
}

```

</div>

> Can you provide full repro? This is already tested and tests are passing. Basically this test is exactly the same:
> 
> https://github.com/mikro-orm/mikro-orm/blob/master/tests/features/partial-loading/partial-loading.mysql.test.ts#L96

I wrote the wrong result here. I modified it. He said he would not filter out the properties of sub objects

**Comment by B4nan** [comment]
Can you provide full repro? This is already tested and tests are passing. Basically this test is exactly the same: 

https://github.com/mikro-orm/mikro-orm/blob/master/tests/features/partial-loading/partial-loading.mysql.test.ts#L82

**Comment by WumaCoder** [comment]
Mine is mongo engine

**Comment by B4nan** [comment]
It is tested the very same way in mongo too. 

https://github.com/mikro-orm/mikro-orm/blob/master/tests/features/partial-loading/partial-loading.mongo.test.ts#L96

**Comment by B4nan** [comment]
Are you sure that entity wasn't loaded before in the context? e.g.

```ts
const e = await this.em.findOne(User, 1);

// now the user with ID 1 will be loaded, you will end up with full entity for that particular row
const [list, count] = await this.em.findAndCount(Group,{}, {
      populate: ['creator'],
      fields: ['name', 'creator',{ creator: ['name'] }],
 })

**Comment by WumaCoder** [comment]
> 

id = 1 This user has been loaded before

**Comment by WumaCoder** [comment]
Is it for this reason?

**Comment by WumaCoder** [comment]
I still can't do this

```ts
  const [list, count] = await this.em.findAndCount(
      entity,
      where,
      Object.assign(
        {
          disableIdentityMap: true,
          refresh: true,
        },
        option,
      ),
    );
```

**Comment by B4nan** [comment]
Yes, if it was loaded, it will behave like this. You can mark it as not loaded via `wrap(user).populated(false)`, I'd suggest doing that right after you load it (I guess it is currently logged user or something like that?)

**Comment by WumaCoder** [comment]
Yes I got the user when I verified the permission.

Problem solved, thank you
