### ISSUE TITLE
Support Applying Filters to Joined Tables by Specifying `when: "joined"`

### ISSUE THREAD

**Issue by TheNightmareX** [mikro-orm/mikro-orm#2440]
### Current Problem

I'm trying to implement a soft delete solution for MikroORM: [mikro-orm-soft-delete](https://github.com/TheNightmareX/mikro-orm-soft-delete), and there are some issues because of MikroORM's filter strategy.

When executing a query, MikroORM will join relation tables involved in the query condition automatically, but filters will not be applied to these auto-joined tables, which is sometimes confusing to me.

I have an global filter with condition `{ deletedAt: null }`. I expect all those deleted entities having a value on their `deletedAt` field are kept away from my queries, but It turns out they can still affect my queries because of the behavior described before.

For example, I expect `em.find(Author, { books: { name: "a" } })` will find all the authors having a book named `"a"`. But it turns out that if there is an `Author` who had such a book previously but then deleted it, this `Author` will still be in the result list, because the global filter `{ deletedAt: null }` is only applied to the selected table `authors` but not to the joined table `books`, which is really confusing to me. I have to specify `{ deletedAt: null }` over and over again in a lot of query conditions such as `em.find(Author, { books: { name: "a", deletedAt: null } })` and make my code messy.

### Expected Solution

Add a new optional option `when: "selected" | "joined" | "any"` with a default value `"selected"`. Filters will be applied even when the table is just joined rather than selected when the new option `when` is specified to `"joined"` or `"any"`.

```ts
@Filter({
  name: "excludeDeleted",
  cond: { deletedAt: null },
  when: "any"
})
```

```ts
em.addFilter("exclude-deleted", { deletedAt: null }, ..., ..., "any");
```

**Comment by nthypes** [comment]
@TheNightmareX I was looking into your plugin. It's not possible to force a "hard delete" when not choose soft delete in specific scenarios?

**Comment by alfienguyen** [comment]
Is this being worked on? The current behavior seems inconsistent, if not buggy.

**Comment by B4nan** [comment]
No, its not being worked on. Best way to get something fixed is sending a PR.

**Comment by zmiter-softeq** [comment]
When I was a PHP developer I was so happy using Doctrine ORM. Mikroorm is pretty similar to Doctrine, so I choose it. Now I'm a bit disappointed that Mikroorm doesn't apply the filters to all JOINs within defined relations as Doctrine does.

**Comment by TheNightmareX** [comment]
Glad to see this finally been implemented. 
Thanks for your constant efforts in this library @B4nan.
This is seriously the most well-designed ORM ever in the Node.js community!
