### ISSUE TITLE
Unable to query for array equality

### ISSUE THREAD

**Issue by evantrimboli** [mikro-orm/mikro-orm#2462]
**Describe the bug**
When trying to query array type fields, the generated query is invalid.

**Stack trace**
N/A

**To Reproduce**
```typescript
@Entity()
class Thing() {
  @PrimaryKey()
  id!: number

  @Property({ type: ArrayType })
  groups!: readonly string[]
}

// Generates where groups in ('foo', 'bar')
em.find(Thing, {
  groups: ['foo', 'bar']
})

// Generates where groups = 'foo', 'bar'
em.find(Thing, {
  groups: {
    $eq: ['foo', 'bar']
  }
})
```

**Expected behavior**
It should generate a query like `where groups = '{foo, bar}'`

**Additional context**
The issue seems to be in `formatQuery` under platform. It doesn't consider arrays at all, so any arrays are just automatically stringified. However changing this behaviour seems like it would be a breaking change, not sure of the best course of action here. Another thought is it could act similarly to the check in `QueryHelper` where it checks `instanceof JsonType` and does custom processing based off that value.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.3 |
| typescript | 4.5 |
| mikro-orm | 5.latest |
| your-driver | postgres |

**Comment by B4nan** [comment]
You need to use postgres array operators for this.

```
  $overlap = '&&', // postgres only
  $contains = '@>', // postgres only
  $contained = '<@', // postgres only
```

**Comment by B4nan** [comment]
I though you need to use one of those to compare arrays, if we can use `=` too (I guess that would mean strict comparison, so order of items too?), then we might be able to support it via `$eq`, I am not sure if we support it via just comparing to array, as that means using `$in` operator (and that should be still supported even for array columns I guess).

> The issue seems to be in formatQuery under platform.

That method should already get serialized custom types, so array is actually a string there. And it does already work with the operators mentioned above, e.g. this works:

```ts
const qb = pg.em.createQueryBuilder(Author2);
qb.select('*').where({ identities: { $contains: ['4', '5', '6'] } });
expect(qb.getFormattedQuery()).toEqual(`select "a0".* from "author2" as "a0" where "a0"."identities" @> '{4,5,6}'`);
```

This works based on `ARRAY_OPERATORS` array, tried adding `$eq` inside and it works just fine then:

```ts
const qb = pg.em.createQueryBuilder(Author2);
qb.select('*').where({ identities: { $eq: ['4', '5', '6'] } });
expect(qb.getFormattedQuery()).toEqual(`select "a0".* from "author2" as "a0" where "a0"."identities" = '{4,5,6}'`);
```

And with that change all QB tests are passing fine, so I believe it should be safe (it is considered only if the value is array).

**Comment by evantrimboli** [comment]
> I guess that would mean strict comparison, so order of items too?
Yeah that's what I'm looking for here.

**Comment by B4nan** [comment]
Looking at this, we should support more operators this way (just by adding them to the `ARRAY_OPERATORS`, at least those that won't cause any issues). PR welcome :]

https://popsql.com/learn-sql/postgresql/how-to-compare-arrays-in-postgresql
