### ISSUE TITLE
Add option to hide embedded elements

### ISSUE THREAD

**Issue by Tititrois** [mikro-orm/mikro-orm#2464]
**Is your feature request related to a problem? Please describe.**
I am right now using typegoose and I start to see some limitations. I am interested by mikro orm. Using mongo db we have a lot of embedded data structure. Sometimes it is useful to hide the structure embedded. From what I have read and tried, it does not seem possible for now.

**Describe the solution you'd like**
Add an option in embedded to hide data like for the property decorator.

**Comment by B4nan** [comment]
You can set the property as `hidden: true` and it will not be part of the serialized response. It will still be present on the runtime, e.g. if you console.log the entity, but if you serialize it to JSON, it won't be there. This should work for any kind of property.

https://mikro-orm.io/docs/4.4/serializing/#hidden-properties

**Comment by Tititrois** [comment]
I don't think I can use the property hidden into the @Embedded.

If I do use the following example. Currently using mongo, I want the array of notes to be store inside the candidate as a sub document. 

```@Embeddable()
export class Note {
  @Property()
  content!: string;
}

@Entity({ collection: "candidates" })
export class MCandidate {
  @PrimaryKey()
  _id: string;

  @Property()
  firstName: string;

  @Property()
  lastName: string;

  // HERE: no hidden for embedded ?
  @Embedded(() => Note, { array: true })
  public notes?: Array<Note>;

  @Property()
  get totalNotes() {
    return this.notes.length;
  }
}
```

I would like to hide these notes using `@Embedded` and only return the getter about their number. I don't think it's possible, unless I concert notes into an entity, but it will be store in a different collection no ?

**Comment by B4nan** [comment]
That is probably just a typings issue, try casting:

```ts
  @Embedded(() => Note, { array: true, hidden: true } as any)
  public notes?: Array<Note>;
```

Please verify it works, if yes I can add it to the options right ahead.

As an alternative you can always use custom `toJSON` method, but this should work just fine.

**Comment by Tititrois** [comment]
Yes you are right it is working, notes are now hidden. That's good, definitely it would be nice to add the property in the interface.

Another small question related to the embedded. Is it possible to create a embedded structure based on the **Single Table Inheritance** ? Basically if I want my notes to have a different structure depending a `type` property storing all these as a sub document array (and not my notes in a new collection) ?

I know it's possible using the Entities but that would be very nice too. Something looking like this:

```
@Embeddable({
  discriminatorColumn: 'type',
  discriminatorMap: { textNote: 'TextNote', accountingNote: 'AccountingNote' },
})
export abstract class AbstractNote {
  @Enum()
  type!: "text" | "accounting";
}

@Embeddable()
export class TextNote extends AbstractNote {
  @Property()
  description: string;
}

@Embeddable()
export class AccountingNote extends AbstractNote {
  @Property()
  value: number;
}
```

And use it like this in the candidate:

```
  @Embedded(() => AbstractNote, { array: true, hidden: true } as any)
  public notes?: Array<AbstractNote>;
```

**Comment by B4nan** [comment]
That is actually implemented in v5 already, I was working on that few days ago (#2426):

https://mikro-orm.io/docs/next/embeddables#polymorphic-embeddables

**Comment by Tititrois** [comment]
Looks amazing 😀. Thank you very much, I will use this when the version 5 is out then !

Thank you for your quick
 answers and hopefully we can move our stack to mikro orm soon !
