### ISSUE TITLE
Implicit populate inferred from fields

### ISSUE THREAD

**Issue by evantrimboli** [mikro-orm/mikro-orm#2468]
**Is your feature request related to a problem? Please describe.**
Now that the fields property is strongly typed, it seems like it would be a nice quality of life improvement to be able to infer what needs to be populated if the `fields` are specified for a query.

**Describe the solution you'd like**
Given the following code, the query should figure out that it needs to populate `['order.user']`
```typescript
em.find(OrderItem, {
  id: 1
}, {
  fields: ['id', 'order.user.id']
});
```

**Describe alternatives you've considered**
Just specifying populate.

**Additional context**
It seems like this should be relatively simple, but there are probably things I'm not considering. There's also a question of whether implicit population is a good thing.

**Comment by B4nan** [comment]
I guess this does make sense as without the populate such query does not make sense (either won't work as expected or will error, not even sure rn). Should be indeed quite simple, PR welcome.

**Comment by B4nan** [comment]
Will be part of v5. Note that it will work only in case no populate hint is provided.
