### ISSUE TITLE
[5.0.0-dev.533] `populate` method always return an array

### ISSUE THREAD

**Issue by s524797336** [mikro-orm/mikro-orm#2474]
```typescript
const instance = repo.findOne()
const res = await repo.populate(instance, ['parent'])
console.debug(res) // res is [instance]
```
The `res` should be `instance` instead of `[instance]`

**Comment by B4nan** [comment]
Yes, that is one of the breaking changes.

**Comment by s524797336** [comment]
@B4nan

**Comment by s524797336** [comment]
@B4nan 
The EntityRepository.d.ts:117
```typescript
populate<P extends string = never>(entities: T, populate: AutoPath<T, P>[] | boolean, options?: EntityLoaderOptions<T>): Promise<Loaded<T, P>>;
```
Then this line must change to
```typescript
populate<P extends string = never>(entities: T, populate: AutoPath<T, P>[] | boolean, options?: EntityLoaderOptions<T>): Promise<Loaded<T, P>[]>;
```

**Comment by B4nan** [comment]
Nope, your code must change.

**Comment by s524797336** [comment]
Typescript says it's return is not an array, so my code must change?

**Comment by B4nan** [comment]
That method now always return arrays, so yes, your code must change to respect that.

**Comment by s524797336** [comment]
Yes, my code need change to respect that. but the typescript on your side shows it still some times not return arrays

**Comment by B4nan** [comment]
Oh I see, you are right about that, the repository method signature needs to be simplified too.
