### ISSUE TITLE
Unnecessary join 1:1

### ISSUE THREAD

**Issue by emrosenf** [mikro-orm/mikro-orm#248]
**Describe the bug**

Two classes

```typescript
@Entity()
class User {
  @OneToOne(() => Profile, profile => profile.user)
  profile?: Profile;
}

@Entity()
class Profile {
  @Field(() => User, { nullable: true })
  @OneToOne(() => User, user => user.profile, { owner: true, fieldName: 'userId'})
  user?: User;

  @Property({ type: 'text'})
  userId?: string;
}
```

Due to `populateMissingReferences`, whenever `User` is fetched, it will be joined with `Profile`. What was the design decision behind this? I think it's unnecessary.

```typescript
  /**
   * 1:1 owner side needs to be marked for population so QB auto-joins the owner id
   */
  protected populateMissingReferences(meta: EntityMetadata, populate: string[]): string[] {
    const toPopulate = Object.values(meta.properties)
      .filter(prop => prop.reference === ReferenceType.ONE_TO_ONE && !prop.owner && !populate.includes(prop.name))
      .map(prop => prop.name);

    return [...populate, ...toPopulate];
  }
```

**Comment by B4nan** [comment]
Reason for this is to have the reference to the owner on the inverse side. In your example, if you load user entity (which is in this case inverse side, without the FK), you will still have the reference to the profile entity.

**Comment by B4nan** [comment]
I see in the other issue that your profile table is defined as 

```sql
CREATE TABLE "Profile" (
  "id" TEXT NOT NULL   ,
  "user" TEXT    REFERENCES "User"(id) ON DELETE SET NULL,
  PRIMARY KEY ("id")
)
```

If so, you have the entity defined wrongly, `fieldName` should be just `user`. But as it is reference property, you need to define `joinColumn` (on owning side) and `inverseJoinColumn` (on inverse side) instead.

**Comment by emrosenf** [comment]
Thanks for your comments. This behavior is not desirable for me so I will prefer `ManyToOne` over `OneToOne`.

PS: the reason I had `userId` in the other example was because I was experimenting with different possibilities to get everything to work as desired.

You can close if you want.

**Comment by B4nan** [comment]
I am open for adding config toggle that would disable this behaviour. I dont like it either, but it was easier to add that instead of explaining others how owning/inverse side works. Also it is not consistent with mongo driver where it is not even possible.

**Comment by B4nan** [comment]
Now you can disable this behaviour via `autoJoinOneToOneOwner: false`:

```typescript
await MikroORM.init({
  // ...
  autoJoinOneToOneOwner: false,
});
```
