### ISSUE TITLE
docs: add description for customType property of Property annotation

### ISSUE THREAD

**Issue by co-sic** [mikro-orm/mikro-orm#2489]
```ts
@Property({ customType: new IntegerArrayType() })
numberOfEmployeesOptions: number[];
```
I have this property with my own defined IntegerArrayType. But if i use 
```ts
@Property({ type: new IntegerArrayType() })
numberOfEmployeesOptions: number[];
```
instead, the migration works the same, but if i want to insert something the build in Array type is used, which tries to insert it a text[].
This behaviour is fine for me, but in the docs of @Property annotation the customType property is not described, so this might be confusing

**Comment by B4nan** [comment]
> And on top, in the example of Customer Type in the docs: mikro-orm.io/docs/custom-types the type property of @Property is used instead of customType

Because you should be using `type` with the class, using `customType` with instance is only for stateful custom types. If you type is stateless, there is no need for having separate instances for each property in each entity where it is used.

Will improve the docs, thanks for the poke, I totally forgot about it :]

**Comment by B4nan** [comment]
Actually this should be working, I even see entity in the tests that uses `type` with a type instance (and `PropertyOptions` interface does allow for both too).

Could you provide reproduction for where it is acting differently?

**Comment by co-sic** [comment]
You are right, i did a small test just now and it was working also with the `type` property. I will check the exact case we had there it was not working on monday, maybe it was some other error on my part.

**Comment by co-sic** [comment]
```ts
@Entity()
export class BaseProductOptions extends BaseEntity {
  @Property({ type: new IntegerArrayType() })
  numberOfEmployeesOptions: number[];

  constructor(numberOfEmployeesOptions: number[]) {
    super();
    this.numberOfEmployeesOptions = numberOfEmployeesOptions;
  }
}


import { Type, ValidationError } from '@mikro-orm/core';

export class IntegerArrayType extends Type<number[], string> {
  private readonly length?: number;

  constructor(length?: number) {
    super();
    this.length = length;
  }

  static lengthValidationError(value: number[], mode: string, length: number) {
    return new ValidationError(
      `Could not convert ${mode} value of type ${IntegerArrayType.name}. Array length must be ${length} but received ${value.length}.`,
    );
  }

  convertToDatabaseValue(value: number[]): string {
    if (this.length && value.length !== this.length) {
      throw IntegerArrayType.lengthValidationError(value, 'JS', this.length);
    }
    return `{${value.join(',')}}`;
  }

  convertToJSValue(value: number[]): number[] {
    if (!Array.isArray(value)) {
      throw ValidationError.invalidType(IntegerArrayType, value, 'database');
    }
    if (this.length && value.length !== this.length) {
      throw IntegerArrayType.lengthValidationError(value, 'database', this.length);
    }
    return value;
  }

  compareAsType(): string {
    return 'array';
  }

  getColumnType(): string {
    return 'int4[]';
  }
}

// migration
this.addSql('create table "base_product_options" ("id" uuid not null default gen_random_uuid(), "mongo_db_id" varchar(255) null, "created_at" timestamptz(0) not null, "updated_at" timestamptz(0) not null, "number_of_employees_options" int4[] not null);');

// Test
const baseProductOptions = new BaseProductOptions([1, 2, 3]);
await orm.orm.em.persistAndFlush(baseProductOptions); 

```

I get this Error if i run the test `[ERROR] 15:43:38 DriverException: insert into "base_product_options" ("created_at", "mongo_db_id", "number_of_employees_options", "updated_at") values ('2021-12-07T14:43:38.962Z', NULL, '[1,2,3]', '2021-12-07T14:43:38.962Z') returning "id" - malformed array literal: "[1,2,3]"`
But if i use customType instead, it works fine.

**Comment by B4nan** [comment]
I am quite sure I won't be able to reproduce this. The problem here is that `instanceof Type` check can fail if you have multiple `@mikro-orm/core` packages installed, which will be most probably your issue - if there are multiple installs, there are also multiple `Type` classes. 

Could you provide full repro so I can confirm this? We could do the check via some known property instead of using `instanceof` to get around this, but generally having multiple core packages is wrong and can lead to other (more hidden) issues too.

**Comment by co-sic** [comment]
how do you know that i have multiple core packages installed? As far as i know i have only one, but maybe i am missing something.

```
    "@mikro-orm/cli": "4.5.9",
    "@mikro-orm/core": "4.5.9",
    "@mikro-orm/migrations": "4.5.9",
    "@mikro-orm/postgresql": "4.5.9",
    "@mikro-orm/reflection": "4.5.9",
```
this is from my package.json and i don't think i have any other package installed that uses mikro-orm. Is there an easy way to check if i have multiple instances installed? Since the repository is private i can't easily share it with you.

**Comment by B4nan** [comment]
I don't know it, but I highly expect it. Why? I saw things like that many times, and the tests for this case do exist and are passing. What you have in package.json is kind of irrelevant, you could still have things wrongly installed in node_modules. 

But that is why I am asking for full repro so I can verify it, maybe it's about something else. Or try to put some console.logs here and see yourself:

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/metadata/MetadataDiscovery.ts#L861

**Comment by co-sic** [comment]
Okay, i invited you to our repository so you can have a look: https://github.com/gastromatic/contract-service

**Comment by B4nan** [comment]
I'd like to see a reproduction, so something minimal. I dont have time to review your project, especially not a GQL one. If you dont want to make a small repro, then please try to debug this yourself the way I suggested above, I pointed to the line that is responsible to detect custom type instance via `type` option.

**Comment by B4nan** [comment]
Please stop inviting me to your private repositories, I am not going to review that. It is far above the free support I am willing to give, as that has nothing to do with a reproduction - reproductions need to be minimal.

**Comment by co-sic** [comment]
After i invited you to the repository in question i noticed that we have 3 private packages used there, so i added your there as well in case you wanted to do an install. But i can understand thats way to much trouble, so thank you for all the pointers, i will try to debug it myself. I'm very curious now about the multiple core packages installed, because that sounds like something that could also lead to other issues that are not easily noticable.

**Comment by co-sic** [comment]
I created a minimal example repository now with just the case i described above, in case you still want to have a look: https://github.com/co-sic/node-mikro-orm-playground
I'm sorry, should have done this directly. I thought it might have something to do with the other dependencies in my project, but seems not like it.

**Comment by B4nan** [comment]
So you are using tsmorph, maybe that is the problem, the existing tests for this use reflect metadata. Will take a look when I have some time.

**Comment by co-sic** [comment]
I can confirm it works with ReflectMetadataProvider instead of TsMroph.

**Comment by B4nan** [comment]
The culprit was actually metadata caching (which is enabled by default for ts-morph).

**Comment by B4nan** [comment]
Also backported to v4: `4.5.10-dev.27`
