### ISSUE TITLE
Mapping adds/omits additional columns on a select

### ISSUE THREAD

**Issue by mikey0000** [mikro-orm/mikro-orm#2499]
**When you query the same table with two different queries the results are different based on whats in the cache**

 ```
 async get(scheduleDate) {
        return this.stopRepository.findAll();
    }

    async mobileGet(scheduleDate) {
        const em = Main.DI.em;
        const qb = em.createQueryBuilder(Entities.Stops, "stops");
        const test = await qb
            .select(mobileStopColumns)
            .where({ start_date: { $lte: scheduleDate } })
            .andWhere({ end_date: { $gte: scheduleDate } })
            .getResultList()//.execute("all", false);
        return test;
    }
```
If I execute findAll, all columns are returns as expected however if I then call mobileGet with a subset of columns I still get all the columns (seemingly correctly filled in with data) as if I called findAll()
if I only call mobileGet first I only get the columns I expected, however then findAll returns the subset instead of the full column list

`return res.map(r => this.em.map(this.entityName, r));`

as long as I don't map it works as expected. (call execute)

**To Reproduce**
See above

**Expected behavior**
That mapping would only map for the columns selected and both calls would return their respective data.

**Versions**

| Dependency | Version |
| - | - |
| mikro-orm | 4.5.9 |

**Comment by B4nan** [comment]
That is how identity map works, its not result cache. Each request needs to have its own context. 

https://mikro-orm.io/docs/identity-map

**Comment by mikey0000** [comment]
I just discovered that now was about to say.
