### ISSUE TITLE
filter and find populate  problem

### ISSUE THREAD

**Issue by WumaCoder** [mikro-orm/mikro-orm#2506]
**Describe the bug**
When I use the populate of find to query after using the filter to achieve false deletion, I cannot achieve the function of continuous check.

He later returns id

**Versions**

| Dependency | Version |
| - | - |
| node | ? |
| typescript | ? |
| mikro-orm | 4.5 |
| your-driver | mongo |

**Comment by evantrimboli** [comment]
You haven't posted any code, it's not going to be possible to provide any insight without a test case here.

**Comment by B4nan** [comment]
Closing, this is really low effort issue, if you want to ask things this way, join the slack channel or use the discussions 🤷 issues are for bugs and feature requests, not for general support.
