### ISSUE TITLE
Wrong type hydration for DATETIME column mapped as string

### ISSUE THREAD

**Issue by belinde** [mikro-orm/mikro-orm#2507]
**Describe the bug**
I want to store a date/time value in a MySQL DATETIME column, but managing it as a string. Given this entity:
```typescript
import { Entity, Enum, PrimaryKey, Property } from '@mikro-orm/core';
import { ulid } from 'ulid';

export abstract class BaseEntity {
    @PrimaryKey({ columnType: 'char(26)' })
    id = ulid();
}

export enum PaymentAttemptStatus {
    PLANNED = 'planned',
    RUNNING = 'running',
    SUCCESS = 'success',
    FAILURE = 'failure',
    MANUAL = 'manual',
}

@Entity()
export class PaymentAttempt extends BaseEntity {
// ... other properties

    @Enum({ default: PaymentAttemptStatus.PLANNED })
    status: PaymentAttemptStatus = PaymentAttemptStatus.PLANNED;

    @Property({ type: 'string', columnType: 'datetime', nullable: true })
    effectiveExecution: string | null = null;

// ... other properties
}
```
If I try to edit and save like this:
```typescript
await em
    .findOneOrFail(PaymentAttempt, 'abc123')
    .then((attempt) => {
        attempt.status = PaymentAttemptStatus.SUCCESS;
        return em.flush();
    });
```
I get an error like
```
ValidationError: Trying to set PaymentAttempt.effectiveExecution of type 'string' to 'Fri Dec 10 2021 12:15:20 GMT+0100 (Ora standard dell’Europa centrale)' of type 'date'
    at Function.fromWrongPropertyType (/home/belinde/NaN/paydeal-backend/node_modules/@mikro-orm/core/errors.js:22:16)
    at EntityValidator.validateProperty (/home/belinde/NaN/paydeal-backend/node_modules/@mikro-orm/core/entity/EntityValidator.js:45:44)
    at /home/belinde/NaN/paydeal-backend/node_modules/@mikro-orm/core/entity/EntityValidator.js:23:35
    at Array.forEach (<anonymous>)
    at EntityValidator.validate (/home/belinde/NaN/paydeal-backend/node_modules/@mikro-orm/core/entity/EntityValidator.js:12:20)
    at SqlEntityManager.merge (/home/belinde/NaN/paydeal-backend/node_modules/@mikro-orm/core/EntityManager.js:375:24)
    at SqlEntityManager.merge (/home/belinde/NaN/paydeal-backend/node_modules/@mikro-orm/core/EntityManager.js:364:25)
    at SqlEntityManager.fork (/home/belinde/NaN/paydeal-backend/node_modules/@mikro-orm/core/EntityManager.js:547:20)
    at SqlEntityManager.transactional (/home/belinde/NaN/paydeal-backend/node_modules/@mikro-orm/core/EntityManager.js:267:25)
    at managePayoutLogic (/home/belinde/NaN/paydeal-backend/src/tools/MangoPay/payin.ts:59:8) {
  entity: undefined
}
```

**Expected behavior**
effectiveExecution should be hydrated as a plain string.

**Additional context**
It's worth mentioning that this doesn't happen using a MySQL DATE type.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.3 |
| typescript | 4.5.3 |
| mikro-orm | 4.5.9 |
| mikro-orm/mysql | 4.5.9 |

**Comment by B4nan** [comment]
You might need a custom mapped type for this, combining just `type` and `columnType` like this has no semantic meaning. If it is a datetime column, it will be converted to date object, regardless of what you put into `type` (unless it is a custom mapped type). Note this datetime conversion happens usually at the driver/connector level, so outside of MikroORM and you might need to also adjust the configuration of such driver - namely for mysql there is `dateStrings` option for such use case.

```ts
MikroORM.init({
  driverOptions: {
    connection: { dateStrings: true }
  }
})
```

If you would want this to happen only for some datetime properties, you will actually need the opposite - a mapped type that will then handle those strings and convert them to date objects on runtime, as if you disable date conversion in driver, it will be applied to everything (and can have potentially breaking effect on change set tracking).

https://mikro-orm.io/docs/custom-types/

**Comment by belinde** [comment]
Sorry, I didn't know about the dateStrings option, and propably is exactly what I need. Thank you again for all your work!
