### ISSUE TITLE
Create seeds as in Eloquent (Laravel)

### ISSUE THREAD

**Issue by AstroCorp** [mikro-orm/mikro-orm#251]
https://laravel.com/docs/6.x/seeding

**Comment by B4nan** [comment]
I was already working on something similar but then decided to drop it as it looked like unnecessary complex thing to write. Will look at how laravel does it, what I checked so far was how knex and typeorm seeding is working, but I did not really like the approach there, I saw too many things that could break easily (like the order of multiple seed files being decided by the file names). Also if one want the way knex is working already, then they can use knex directly (as it is direct dependency of MikroORM v3)... 

Currently for seeding purposes, there is a CLI command to execute SQL dump (`mikro-orm database:import <file>`).

**Comment by B4nan** [comment]
Looked at the link in more detail, and I kinda like it. Will try to incorporate something similar in one of 3.x releases.

**Comment by gperdomor** [comment]
👍 +1

**Comment by kibertoad** [comment]
@B4nan If that would help, we could expose something similar to CustomMigrationSource for seeds if you would like to reuse the rest of knex seeding functionality, or possibility to provide custom seed ordering implementation, to reduce amount of things you'd have to reimplement from a scratch.

**Comment by B4nan** [comment]
@kibertoad thanks, but I will probably do it from scratch here, as I want to support it in mongo driver too. The implementation should be quite similar to migrations, so hopefully it won't be that time consuming. i might be able to reuse umzug here, or maybe get rid of it and replace it with custom shared implementation for both migrations and seeds.

**Comment by CyriacBr** [comment]
You guys may want to look at ![`@mikro-resources/fixtures`](https://github.com/CyriacBr/mikro-resources/tree/develop/packages/fixtures), this is what I've been using. I like this approach better as it just take existing entity classes and generate random values/relations on the fly.

**Comment by Langstra** [comment]
I have worked with https://github.com/w3tecch/typeorm-seeding before. It was not bad, but definitely could use improvement.

Currently I have written a very basic seeder for my project, but see a lot of potential in writing something with a similar api to Laravel's seeder and factory. I'd like to work in my own time on such a thing if you'd agree @B4nan. Then we could include that as a package or as command to the cli?

**Comment by squareloop1** [comment]
Seeding would be a really nice feature. I've also worked with typorm-seeding before. It is basically a must have for setting up and reinitialize the database for e2e testing purposes.

**Comment by hkdobrev** [comment]
I am currently switching from TypeORM to Mikro ORM.
I have successfully used seeds with TypeORM migrations. I had a different set of configuration options for seeds with a separate migrations table and directory for seed "migrations". Inside those migrations, I've used different techniques - from pure insert queries to converting CSV files to SQL.
