### ISSUE TITLE
Module '"../../../node_modules/mikro-orm/dist"' has no exported member 'MongoEntity'

### ISSUE THREAD

**Issue by gpanainte** [mikro-orm/mikro-orm#252]
**Describe the bug**
I try to use mikro-orm in combination with nestjs and mongodb, and according to the documentation each entity must implement one of the `*Entity` interfaces. The problem is that `"mikro-orm": "2.7.9"` doesn't provide these interfaces, therefore compilation fails with `Module '"../../../node_modules/mikro-orm/dist"' has no exported member 'MongoEntity'`. In fact none of the `*Entity` interfaces are exposed in this version.

**To Reproduce**
1. Download [https://github.com/mikro-orm/nestjs-example-app](https://github.com/mikro-orm/nestjs-example-app)
2. Downgrade mikro-orm version to 2.7.9
3. Try to compile the project
4. BaseEntity from `src/entities/BaseEntity.st` will fail to compile with the message `Module '"../../node_modules/mikro-orm/dist"' has no exported member 'IdEntity'. Did you mean 'Entity'?`

**Expected behavior**
Update documentation or have a new stable version.

**Versions**

| Dependency | Version |
| - | - |
| node | 11.15.0 |
| typescript | 3.7.2 |
| mikro-orm | 2.7.9 |
| your-driver | mongodb |

**Comment by B4nan** [comment]
Current docs are for v3, same applies to all example repositories. If you want to use v2, look here: https://mikro-orm.io/docs/v2/installation/ (and here is historical version of the nestjs example: https://github.com/mikro-orm/mikro-orm-examples/tree/103b24d0b81035b0b5dd016714cc2262b4d8ec14/nest).

But I would suggest to use v3, the `rc.2` version is pretty much the final release, I am just working on the announcement article before the actual release.

**Comment by gpanainte** [comment]
Ok. I will go with v3 then. Thank you for the quick response!
