### ISSUE TITLE
Wrong column name in query when using relations

### ISSUE THREAD

**Issue by stefaanMLB** [mikro-orm/mikro-orm#2521]
**Description of the bug**
When using relations, an error is thrown that indicates that MikroORM is using a faulty column name in the depending table.
After having queried the `RequestOnline` table, MikroORM constructs a query on `mlb_request_online_tubes` table, but uses non-existing `request_requestnumber` column name.

Is there something wrong with our definition of the relation ?  we're trying to declare a simple unidirectional one-to-many relation between `RequestOnline` and `RequestOnlineTube` entities.

When omitting the `@ManyToOne(() => RequestOnline)` declaration from the `RequestOnlineTube` entity (to make the relation unidirectional), we get this error message during program setup (we're using the `Nestjs` framework).  Is there a way to investigate which object is missing the `name` property ?

```
TypeError: Cannot read property 'name' of undefined
    at C:\Users\lcartreul\Documents\projecten\uitpak2\node_modules\@mikro-orm\core\metadata\MetadataDiscovery.js:328:53
    at Array.forEach (<anonymous>)
...
```

**Entities**
```ts
@Entity({ tableName: 'mlb_request_online' })
@Index({ name: 'doctor', properties: ['doctor', 'created', 'dossier'] })
@Filter({ name: 'patientNameFilter', cond: args => ({ patientname: { $like: '%' + args.name + '%' } }) })
@Filter({ name: 'doctorFilter', cond: args => ({ doctor: { $in: args.doctorArray } }) })
@Filter({ name: 'animalFilter', cond: args => ({ dier: 'J' }) })
export class RequestOnline {
  @OneToMany(() => RequestOnlineTube, tube => tube.request)
  tubes = new Collection<RequestOnlineTube>(this)

  @PrimaryKey({ length: 17, default: '' })
  requestnumber!: string

  @Property({ length: 20, default: '' })
  doctor: string = ''

  // ... many more columns


}
```

```ts
@Entity({ tableName: 'mlb_request_online_tubes' })
export class RequestOnlineTube {
  @ManyToOne(() => RequestOnline)
  request!: RequestOnline

  @PrimaryKey({ length: 17, default: '' })
  requestnumber!: string

  @Index({ name: 'tube' })
  @PrimaryKey({ length: 12, default: '' })
  tube!: string

  @Property({ length: 35, default: '' })
  gescand!: string

  // ... many more colums
}
```

**Calling code**
```ts
    const filters: Dictionary<boolean | Dictionary<any>> = {
      doctorFilter: filter.doctors ? { doctorArray: filter.doctors } : false,
      patientNameFilter: filter.patient ? { name: filter.patient } : false,
      animalFilter: false,
    }
    try {
      result = await this._requestRepository.find(
        {},
        {
          filters,
          limit: 10,
          populate: ['tubes'],
        },
      )
    } catch (error) {
      console.log(error)
    }
```

**Stack trace**
```
InvalidFieldNameException: select `e0`.* from `mlb_request_online_tubes` as `e0` where `e0`.`request_requestnumber` in ('00000000000000001', '00000000000000002', '00000000000000003', '00000000000000005', '00000000000000006', '00000000000000008', '00000000000000009', '00000000000000010', '00000000000000011', '00000000000000013') order by `e0`.`request_requestnumber` asc - (conn=758, no: 1054, SQLState: 42S22) Unknown column 'e0.request_requestnumber' in 'where clause'
sql: select `e0`.* from `mlb_request_online_tubes` as `e0` where `e0`.`request_requestnumber` in ('00000000000000001', '00000000000000002', '00000000000000003', '00000000000000005', '00000000000000006', '00000000000000008', '00000000000000009', '00000000000000010', '00000000000000011', '00000000000000013') order by `e0`.`request_requestnumber` asc - parameters:[]
    at MySqlExceptionConverter.convertException (C:\Users\lcartreul\Documents\projecten\uitpak2\node_modules\@mikro-orm\mysql-base\MySqlExceptionConverter.js:37:24)
    at MariaDbDriver.convertException (C:\Users\lcartreul\Documents\projecten\uitpak2\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:202:54)
    at C:\Users\lcartreul\Documents\projecten\uitpak2\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:206:24
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at MariaDbDriver.find (C:\Users\lcartreul\Documents\projecten\uitpak2\node_modules\@mikro-orm\knex\AbstractSqlDriver.js:46:24)
    at SqlEntityManager.find (C:\Users\lcartreul\Documents\projecten\uitpak2\node_modules\@mikro-orm\core\EntityManager.js:93:25)
    at EntityLoader.populateMany (C:\Users\lcartreul\Documents\projecten\uitpak2\node_modules\@mikro-orm\core\entity\EntityLoader.js:127:22)
    at EntityLoader.populateField (C:\Users\lcartreul\Documents\projecten\uitpak2\node_modules\@mikro-orm\core\entity\EntityLoader.js:185:25)
    at EntityLoader.populate (C:\Users\lcartreul\Documents\projecten\uitpak2\node_modules\@mikro-orm\core\entity\EntityLoader.js:37:13)
    at SqlEntityManager.find (C:\Users\lcartreul\Documents\projecten\uitpak2\node_modules\@mikro-orm\core\EntityManager.js:105:9)
```

**Comment by B4nan** [comment]
What versions are you on? Can you prepare minimal executable repro from this? Ideally as a test case. In your code there is too many unrelated things, as well as many things missing (data setup, ORM config, ...).

Ideally instead of using filters, use real conditions, so it is truly minimal - try to find the place that breaks if while using the least features you can. 

> Is there a way to investigate which object is missing the name property ?

Try to put some console logs to where it is thrown. But it kinda makes sense, you can't have 1:m relation without the m:1 part - 1:m is always inverse, it can't exist without the owning side. I believe this should be validated and a readable error message should be thrown. Namely this validation should be it: 

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/metadata/MetadataValidator.ts#L110

You could also try latest dev version, there are quite a lot of bug fixes not yet released (not sure if something is related, but I believe there are some fixes for applying filters). Or even better try v5, as there are many other fixes that are not possible to back port.

**Comment by stefaanMLB** [comment]
@B4nan thank you for your swift reply
Minimal executable project at https://bitbucket.org/bruyland/mikro-orm-min-exec
I get the same error message.  
Presumably some problem with the setup of the relation, but we closely followed the docs.
The `request_requestnumber` should be `requestnumber` in the below query.
The fact that the list of 17-digit numbers is there indicates that mikroORM has done a successfull query to the main `RequestOnline` table before executing this query.  I don't think the problem is with the filters as these have been disabled here.

```SQL
select `e0`.* from `mlb_request_online_tubes` as `e0` where `e0`.`request_requestnumber` in ('00000000000000001', '00000000000000002', '00000000000000003', '00000000000000005', '00000000000000006', '00000000000000008', '00000000000000009', '00000000000000010', '00000000000000011', '00000000000000013') order by `e0`.`request_requestnumber` asc 
```

**Comment by B4nan** [comment]
Well, you actually should have a column named `request_requestnumber`, at least that is what your entity definition says. You define `request` property on your `RequestOnlineTube` entity as m:1 relation, so it will have a FK for it, and its field name will be `request_requestnumber` - the property name plus the target PK field name.

```ts
  @ManyToOne('RequestOnline')
  request!: RequestOnline;
```

You probably wanted to define it like this:

```ts
@Entity()
export class RequestOnlineTube {

  @ManyToOne({ entity: () => RequestOnline, fieldName: 'requestnumber', primary: true })
  request!: RequestOnline;

  // ... rest of your properties

}
```

Then the queries will be as follows:

```sql
select `r0`.* from `request_online` as `r0` limit 10
select `r0`.* from `request_online_tube` as `r0` where `r0`.`requestnumber` in ('00000000000000001', ...) order by `r0`.`requestnumber` asc
```

Alternatively you could use `mapToPk`, but you will loose some propagation features of the ORM, so I would rather not suggest doing that:

```ts
@Entity()
export class RequestOnlineTube {

  @ManyToOne({ entity: () => RequestOnline, fieldName: 'requestnumber', mapToPk: true, primary: true })
  requestnumber!: string;

  // ... rest of your properties

}

@Entity()
export class RequestOnline {

  @PrimaryKey({ length: 17 })
  requestnumber!: string;

  // eslint-disable-next-line @typescript-eslint/no-use-before-define
  @OneToMany(() => RequestOnlineTube, tube => tube.requestnumber)
  tubes = new Collection<RequestOnlineTube>(this);

}
```
