### ISSUE TITLE
why so big difference in options form method to method. 

### ISSUE THREAD

**Issue by Mitch-i** [mikro-orm/mikro-orm#2523]
> You need to populate separately if you want different conditions for the root entity:
> 
> ```ts
> const items = await em.find(RootEntity, {}); // we want entities regardless of what is in their roles collection
> await em.populate(items, ['roles'], { roles: { isActive: true } }); // we only use the condition here when loading the relation
> ```

for populate

`em.populate(items,` ['roles'], { roles: { isActive: true } }) // can filter`

for find 
```
find(
  +id,
  ['roles', 'roles.permissios', 'profiles']  // can't filter
)
```

Why so big difference in options form method to method. Why not some standard for all (find findOne, FindAndCount, create, remove, assign, populate all not have some connection)

In sequelize has conditions and options, no more other

```
create(createUserDto, options)  // options - CreateOptions<CreateUserDto>
findAll(options)  // options - FindOptions<CreateUserDto>
findAndCountAll(options)  // options - FindAndCountOptions<CreateUserDto>
findOne(options) // options - FindOptions<CreateUserDto>
findByPk(id, options)   // options - FindOptions<CreateUserDto>
destroy(options)  //  options - DestroyOptions<CreateUserDto>
update(updateUserDto, options)  //  options  -  UpdateOptions<CreateUserDto>
```
In options is all from transaction to where, includes

Too confused

**Comment by B4nan** [comment]
Because they are different methods, with different purpose?

**Comment by Mitch-i** [comment]
> Because they are different methods, with different purpose?

it have ths same purpose to populate, but one work well and other is limited
