### ISSUE TITLE
isConnected is not working correctly with MongoDB

### ISSUE THREAD

**Issue by ramiel** [mikro-orm/mikro-orm#2524]
**Describe the bug**
`await mikroOrm.isConnected()` always return true, also after mongoDB client disconnected from the db.
The client is correctly reporting that the connection is refused by the server, but that method always return true.

**To Reproduce**
1. run mikro orm normally and let it connect to MongoDB
2. Sto mongoDB server
3. check the result of `isConnected()`

**Expected behavior**
It should follow the real connection status and report about it

**Versions**

| Dependency | Version |
| - | - |
| node | 14 |
| typescript | 4.5.3 |
| mikro-orm | 4.5.9 |
| your-driver | mongo |

**Comment by B4nan** [comment]
Yes, that is how mongo driver works now with the unified topology, not much we can do.

https://mongodb.github.io/node-mongodb-native/3.3/reference/unified-topology/#why-does-mongoclient-isconnected-always-return-true

**Comment by ramiel** [comment]
Thanks for replying. Even like this I think there's an issue. With MySql mikro tries to execute an operation and report if this is failing when isConnected is called (I remember I read something somewhere 🙂 ). I think it should be the same with mongo because the driver will report an error if an operation fails.

**Comment by B4nan** [comment]
I don't mind, we can do the select query in mongo too, feel free to send a PR. 

SQL drivers are making the query here:

https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/AbstractSqlConnection.ts#L38

Mongo driver is now just checking internal property (that is true unless you call close explicitly):

https://github.com/mikro-orm/mikro-orm/blob/master/packages/mongodb/src/MongoConnection.ts#L45

Still this won't be perfect, e.g. if you use multiple mongo servers, this will reach only one. You should have proper health checks outside of the app, and check whether all replicas/serves are alive.

Not sure if we can make a similar query to what SQL drivers are doing (`select 1`, so no db tables need to exist - in mongo ideally it should not have any side effect, like it should not create any collection, or at least it should have some special name so it won't collide with what users might be using, e.g. prefixed name)
