### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Mitch-i** [mikro-orm/mikro-orm#2525]
Is not resolved https://github.com/mikro-orm/mikro-orm/issues/1097

RangeError: Maximum call stack size exceeded
    at /var/www/html/test/server/node_modules/@mikro-orm/core/entity/EntityTransformer.js:103:18
    at Array.map (<anonymous>)
    at Function.toObject (/var/www/html/test/server/node_modules/@mikro-orm/core/entity/EntityTransformer.js:103:14)
    at Permission.prototype.toJSON (/var/www/html/test/server/node_modules/@mikro-orm/core/entity/EntityHelper.js:27:62)
    at WrappedEntity.toJSON (/var/www/html/test/server/node_modules/@mikro-orm/core/entity/WrappedEntity.js:37:28)
    at /var/www/html/test/server/node_modules/@mikro-orm/core/entity/ArrayCollection.js:36:62
    at Array.map (<anonymous>)
    at Collection.toArray (/var/www/html/test/server/node_modules/@mikro-orm/core/entity/ArrayCollection.js:36:32)
    at Function.processCollection (/var/www/html/test/server/node_modules/@mikro-orm/core/entity/EntityTransformer.js:178:24)
    at Function.processProperty (/var/www/html/test/server/node_modules/@mikro-orm/core/entity/EntityTransformer.js:148:38)

```

import { BigIntType, Collection, Entity, ManyToMany, PrimaryKey, Property } from '@mikro-orm/core';
import { Role } from '../../roles/entities/role.entity'

@Entity()
export class Permission {

  @PrimaryKey({ type: BigIntType })
  id: number

  @Property()
  name: string;

  @Property({ default: true })
  isActive: boolean

  @ManyToMany(() => Role, role => role.permissions)
  roles: Collection<Role> = new Collection<Role>(this);

  // constructor(name: string) {
  //   this.name = name;
  // }
}

```

```

import { BigIntType, Cascade, Collection, Entity, ManyToMany, ManyToOne, PrimaryKey, Property } from '@mikro-orm/core';
import { User } from '../../users/entities/user.entity';
import { Permission } from '../../permissions/entities/permission.entity';
// import { BaseEntity } from './BaseEntity';

@Entity()
export class Role { // extends BaseEntity {

  @Property()
  title: string;

  @ManyToOne(() => User)
  user: User;

  @PrimaryKey({ type: BigIntType })
  id: number

  @Property({ default: true })
  isActive: boolean

  @ManyToMany(() => Permission)
  permissions = new Collection<Permission>(this);

  // constructor(title: string, author: Author) {
  //   super();
  //   this.title = title;
  //   this.author = author;
  // }
}
```

```

import { BigIntType, Cascade, Collection, DateType, Entity, OneToMany, PrimaryKey, Property, ManyToOne } from '@mikro-orm/core';

import { Role } from '../../roles/entities/role.entity';
// import { BaseEntity } from './BaseEntity';

@Entity()
export class User { // extends BaseEntity {

  @Property({ type: DateType, nullable: true })
  birthday: Date

  @Property({ onCreate: () => new Date() })
  createdAt: Date

  // @DeleteDateColumn({ type: 'datetime' })
  // deletionDate: Date

  @Property({ length: 320, nullable: false, unique: true })
  email: string

  @Property({ default: true  })
  gender: boolean

  @PrimaryKey({ type: BigIntType })
  id: number

  @Property({ default: true })
  isActive: boolean

  @Property({ default: false })
  isAdmin: boolean

  @Property({ length: 50, nullable: false })
  firstName: string

  @Property({ length: 100, nullable: false })
  lastName: string

  @Property({ length: 250, nullable: false })
  password: string

  @Property({ type: 'string' })
  token: string

  // @Property({ type: 'string' })
  // profiles: string

  @Property({ onCreate: () => new Date(), onUpdate: () => new Date() })
  updatedAt: Date

  @OneToMany(() => Role, role => role.user, { cascade: [Cascade.ALL] })
  roles = new Collection<Role>(this);

  // constructor(name: string, email: string) {
  //   super();
  //   this.name = name;
  //   this.email = email;
  // }
}

```

**Comment by B4nan** [comment]
Once again, please start following the issue template. What versions are you using? Have you tried latest dev version?

Please provide more details, entity definition is not enough, issues like this are always about the actual data and usage, as serialization works based on populate hints. Ideally full reproduction as a test case (https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues).

As mentioned in the other issue, we can definitely add a recursion limit to get around this.

**Comment by Mitch-i** [comment]
Don't know why that not work, but I found the problem of previous error https://github.com/mikro-orm/mikro-orm/issues/2519 (TypeError: Cannot read property 'reference' of undefined).

A typo in populate array ['roles', 'roles.permissions']  // was 'roles.permissios without "n"

**Comment by B4nan** [comment]
What about this? If you don't plan to provide actual reproduction, we can close it, there is nothing I can do without reproduction.
