### ISSUE TITLE
populate not work + very ugly and unclear error messages

### ISSUE THREAD

**Issue by Mitch-i** [mikro-orm/mikro-orm#2527]
--------------------------
    node v14.17.6 Ubuntu 20

    "@mikro-orm/cli": "^4.5.9",
    "@mikro-orm/core": "^4.5.9",
    "@mikro-orm/mysql": "^4.5.9",
    "@mikro-orm/nestjs": "^4.3.1",
    "@mikro-orm/reflection": "^4.5.9",
    "@nestjs/common": "^8.2.3",
------------------------------------

If I specify wrong relation name in populate array I will get all kind of error but no one that will say clear what is wrong.
I get error 'TypeError: Cannot read property 'orderBy' of undefined' if indicated wrong 

```
populate: [ 'roles', 'permissions'],  // correct roles.permissions
strategy: LoadStrategy.JOINED
```

but need to be populate: 

```
[ 'roles', 'roles.permissions'] 
strategy: LoadStrategy.JOINED
```

Get error 'TypeError: Cannot read property 'reference' of undefined' if miss one letter

```
populate: [ 'roles', 'permissios'],  // miss an n
// strategy: LoadStrategy.JOINED // without strategy
```

And finally populate with strategy: LoadStrategy.JOINED not work (no errors but it make only select without joins and roles array are empty)

```
findOne(
        {
          id: + id
        },
        {
          fields: ['email',  'roles.name', 'roles.permissions.name'],
          populate: [ 'roles', 'roles.permissions'],
          strategy: LoadStrategy.JOINED
        }
      )
```

And that not work (no errors but it make only select without joins and roles array are empty)

```

findOne(
        {
          id: + id
        },
        {
          fields: ['email',  'roles.name', 'roles.permissions.name'],
          populate: { roles: { permissions: true } }, // difference
          strategy: LoadStrategy.JOINED
        }
      )

```

Works only

```


findOne(
        {
          id: + id
        },
        {
          fields: ['email',  'roles.name', 'roles.permissions.name'],
          populate: [ 'roles', 'roles.permissions' ]
          // strategy: LoadStrategy.JOINED // without that
        }
      )

**Comment by Mitch-i** [comment]
works if not indicate fields array

**Comment by B4nan** [comment]
full stack trace?

**Comment by Mitch-i** [comment]
> full stack trace?

no errors but not work if indicate fields

**Comment by Mitch-i** [comment]
> full stack trace?

May be need to indicate fields in other mode? For example:


fields: [
            email,
            roles: {
              permissions: true
            }
          ],

**Comment by B4nan** [comment]
Oh, so you are trying partial loading with joined strategy - that is not implemented in v4, but it is working with v5. You will need to upgrade if you want that. v5 is almost complete, definitely safe choice if you are starting new project or just trying out things. Also both `populate` and `fields` are strictly type checked in v5, so you would not fall into those issues with typos.

And I was asking about those stack traces:

> I get error 'TypeError: Cannot read property 'orderBy' of undefined' if indicated wrong

> Get error 'TypeError: Cannot read property 'reference' of undefined' if miss one letter

**Comment by Mitch-i** [comment]
> Oh, so you are trying partial loading with joined strategy - that is not implemented in v4, but it is working with v5. You will need to upgrade if you want that. v5 is almost complete, definitely safe choice if you are starting new project or just trying out things. Also both `populate` and `fields` are strictly type checked in v5, so you would not fall into those issues with typos.
> 
> And I was asking about those stack traces:
> 
> > I get error 'TypeError: Cannot read property 'orderBy' of undefined' if indicated wrong
> 
> > Get error 'TypeError: Cannot read property 'reference' of undefined' if miss one letter

No matching version found for @mikro-orm/cli@^5.0.0.

**Comment by B4nan** [comment]
I am keeeping this open only for possible added error handling/validation. If you are not going to give me the reproductions for those errors I asked for, we can close this 🤷 

Tried to intentionally make typos in both `populate` hint and `fields`, but they both don't produce those error you were talking about, they fail with either populate validation or with a wrong fields in SQL query, both is fine to me. Maybe those cases are already handled in v5 correctly.

Will be happy to reopen if you can show me how to get to those ugly and unclear errors.
