### ISSUE TITLE
Try to migrate from version 4 to 5 - Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Mitch-i** [mikro-orm/mikro-orm#2529]
**Describe the bug**
Cannot read property 'name' of undefined

**Stack trace**

TypeError: Cannot read property 'name' of undefined
    at Configuration.cached (/var/www/html/test/server/node_modules/@mikro-orm/core/dist/utils/Configuration.js:182:29)
    at Configuration.getMetadataProvider (/var/www/html/test/server/node_modules/@mikro-orm/core/dist/utils/Configuration.js:102:21)
    at Configuration.init (/var/www/html/test/server/node_modules/@mikro-orm/core/dist/utils/Configuration.js:129:19)
    at new Configuration (/var/www/html/test/server/node_modules/@mikro-orm/core/dist/utils/Configuration.js:36:14)
    at new MikroORM (/var/www/html/test/server/node_modules/@mikro-orm/core/dist/MikroORM.js:17:27)
    at Function.init (/var/www/html/test/server/node_modules/@mikro-orm/core/dist/MikroORM.js:38:21)
    at InstanceWrapper.useFactory [as metatype] (/var/www/html/test/server/node_modules/@mikro-orm/nestjs/mikro-orm.providers.js:21:32)
    at Injector.instantiateClass (/var/www/html/test/server/node_modules/@nestjs/core/injector/injector.js:304:55)
    at callback (/var/www/html/test/server/node_modules/@nestjs/core/injector/injector.js:48:41)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**To Reproduce**
install version 5

**Expected behavior**
work well

**Versions**
    "@mikro-orm/core": "^5.0.0-dev.562",
    "@mikro-orm/migrations": "^5.0.0-dev.562",
    "@mikro-orm/mysql": "^5.0.0-dev.562",
    "@mikro-orm/nestjs": "^4.3.1",
    "@mikro-orm/reflection": "^5.0.0-dev.562",
    "@mikro-orm/sql-highlighter": "^1.0.1",
    
 node - v14.17.6

**Comment by Mitch-i** [comment]
```
    cached(cls, ...args) {

        console.log('>>    ', cls)
        if (!this.cache[cls.name]) {
            const Class = cls;
            this.cache[cls.name] = new Class(...args);
        }
        return this.cache[cls.name];
    }
```

output 

>>     [class UnderscoreNamingStrategy extends AbstractNamingStrategy]
>>     undefined

**Comment by B4nan** [comment]
Please join the slack channel or start using discussions here on GH, you keep creating low effort issues, full of pseudocode, that are more like questions, without proper context. 

Like sorry, but to reproduce I should install v5? Are you kidding me?

**Comment by Mitch-i** [comment]
@B4nan  Found the problem :) :) :). It's not you It's my bad :)!

Was that in config file i commented line:

`metadataProvider: TsMorphMetadataProvider,`

but in app.module file remains:

` metadataProvider: configService.get('app.db.metadataProvider'),`


But such error `Cannot read property 'name' of undefined` is not very usefully.

**Comment by B4nan** [comment]
So you get this error when `configService.get('app.db.metadataProvider')` gives you `undefined`, right?

So basically when doing:

```ts
MikroORM.init({
  metadataProvider: undefined,
});
```

**Comment by Mitch-i** [comment]
@B4nan yes

**Comment by Mitch-i** [comment]
@B4nan the weak part of mikro-orm is its error messages. other are nice

**Comment by B4nan** [comment]
This is not sequelize, it was never the goal to mimic their API 🤷 If something, the goal was to mimic doctrine/hibernate. 

> Transaction in sequelize is also passed with findOptions.

You can pass the transaction handle via `FindOptions` here too, its the `ctx?: Transaction` property. But you should almost never need to use this, as the transaction context is bared in the EM instance. 

> But here need to fork, call always flush.

In general you should not need to fork manually, that should happen in some middleware. See https://mikro-orm.io/docs/identity-map#-requestcontext-helper-for-di-containers

And I do care about error messages, a lot is actually deeply validated, including relationship definitions and populate hints (and in v5 many things are even validated on compile time). You are just breaking things in a way that literally noone tried before, like here - providing explicit `undefined` value for optional things.

**Comment by Mitch-i** [comment]
@B4nan oooo that I can, I will be very helpfully in that aspect :1st_place_medal :).
I am recently moved to node and I am in process of learning and moving some of my apps from php to node.

**Comment by Mitch-i** [comment]
> In general you should not need to fork manually, that should happen in some middleware. See https://mikro-orm.io/docs/identity-map#-requestcontext-helper-for-di-containers

@B4nan That was first error that I encountered with mikro-orm, when I save errors to BD but It say me that I can't flush in hooks. Resolve by fork.

**Comment by B4nan** [comment]
That error is also triggered if you try to work with global EM instead of having forks for each request. More about this is in the docs page I already gave you. Note that this particular issue is also part of the FAQ page: https://mikro-orm.io/docs/faq#you-cannot-call-emflush-from-inside-lifecycle-hook-handlers

You should not fork inside your handlers to get around this, you should already have a fresh for created in the middleware.

And lastly, in v5 it is now allowed to flush single EM in parallel via `Promise.all` (it won't really happen in parallel, but it won't fail with this error anymore unless you actually do flush from hooks - that is still disallowed as it would cause infinite loops).
