### ISSUE TITLE
Document version not generated

### ISSUE THREAD

**Issue by gpanainte** [mikro-orm/mikro-orm#253]
**Describe the bug**
I have created the following entities: 

```typescript
export abstract class BaseEntity implements MongoEntity<BaseEntity> {
    @PrimaryKey()
    _id!: ObjectID;

    @SerializedPrimaryKey()
    id!: string;

    @Property()
    createdAt: Date = new Date();

    @Property({ onUpdate: () => new Date() })
    updatedAt: Date;

    @Property({ version: true, default: 1 })
    version!: number;
}
```
```typescript
@Entity({ collection: 'company' })
export class CompanyEntity extends BaseEntity {

    @Property({ columnType: 'string', unique: true, nullable: false })
    uniqueId: string;

    @Property({ columnType: 'string', unique: true, nullable: false })
    label: string;

    @Property({ columnType: 'string', nullable: false, unique: true })
    name: string;

    @Property({ type: ContactEntity, columnType: 'object' })
    contact?: ContactEntity;

    constructor (uniqueId: string, label: string, name: string, contact: ContactEntity) {
        super();
        this.uniqueId = uniqueId;
        this.label = label;
        this.name = name;
        this.contact = contact;
    }

}
```
They are persisted using the following code : 
```typescript
export class CompanyRepository {
    constructor (
        @InjectRepository(CompanyEntity)
        private readonly companyRepository: EntityRepository<CompanyEntity>
    ) { }

async save(company: Company) {

        const entity = this.toEntity(company);

        await this.companyRepository.persistAndFlush(entity);
    }

   private toEntity(company: Company): CompanyEntity {

        const { identity, label, name, contact } = company;

        const entity = new CompanyEntity(
            identity.uniqueId,
            label.toString(),
            name.toString(),
            isEmpty(contact) ? null : new ContactEntity(contact.email.toString(),
                contact.phone.toString(),
                contact.website.toString())
        );

        return entity;

    }
}
```
The document is created in the database but is missing the `version` field. Am I missing something from the documentation or is this a bug?

```
{
    "_id": "5de6685bfcd31475455c560b",
    "createdAt": "2019-12-03T13:51:23.726Z",
    "uniqueId": "153a2a77-58c0-4285-b367-bbffb7d0b70e",
    "label": "TST",
    "name": "TEST COMPANY",
    "contact": {
        "email": "test@test.com",
        "phone": "047345444044",
        "website": "www.test.com"
    },
    "updatedAt": "2019-12-03T13:51:23.731Z"
}
```

**To Reproduce**
1. Create a fresh project using nestjs and mongodb
2. Create an entity having a `version` field with the following configuration
```typescript
@Property({ version: true, default: 1 })
    version!: number;
```
3. Create a new document and save it in the database

**Expected behavior**
Version field should be saved in the database and managed automatically bay mikro-orm

**Versions**

| Dependency | Version |
| - | - |
| node | 11.15.0 |
| typescript | 3.7.2 |
| mikro-orm | 3.0.0-rc |
| your-driver | mongodb |

**Comment by B4nan** [comment]
`default` is meant for SQL only. you should be fine just by defining the value via initializer:

    @Property({ version: true })
    version = 1;

But the bottom line is that optimistic locking (the thing version field is for) is not working in mongo -- currently there is no transaction support integrated there. 

If you want to have a field which increments every time you update the entity, you could use `@BeforeUpdate` hook.

**Comment by gpanainte** [comment]
Can you suggest the proper usage of @BeforeUpdate hook? It is not clear from the documentation [https://mikro-orm.io/docs/lifecycle-hooks](https://mikro-orm.io/docs/lifecycle-hooks) how it should be implemented.

**Comment by B4nan** [comment]
Something like this should work:

```typescript
@Entity()
export class Author implements MongoEntity<Author> {

  @Property()
  version = 1;

  @BeforeUpdate()
  beforeUpdate() {
    this.version += 1;
  }

}
```

**Comment by gpanainte** [comment]
I have updated the code as you suggested but still the version field is not saved in the database.

Here are my refactored entities:

```typescript
export abstract class BaseEntity implements MongoEntity<BaseEntity> {
    @PrimaryKey()
    _id!: ObjectID;

    @SerializedPrimaryKey()
    id!: string;

    @Property()
    createdAt: Date = new Date();

    @Property({ onUpdate: () => new Date() })
    updatedAt: Date;

    @Property()
    version: number = 1;

    @BeforeUpdate()
    beforeUpdate() {
        this.version += 1;
    }

}
``` 
```typescript
@Entity({ collection: 'company' })
export class CompanyEntity extends BaseEntity {

    @Property({ columnType: 'string', unique: true, nullable: false })
    uniqueId: string;

    @Property({ columnType: 'string', unique: true, nullable: false })
    label: string;

    @Property({ columnType: 'string', nullable: false, unique: true })
    name: string;

    @Property({ type: ContactEntity, columnType: 'object' })
    contact?: ContactEntity;

    constructor (uniqueId: string, label: string, name: string, contact: ContactEntity) {
        super();
        this.uniqueId = uniqueId;
        this.label = label;
        this.name = name;
        this.contact = contact;
    }

}
```

**Comment by B4nan** [comment]
That's pretty strange, try to wipe the cache (`temp` folder). I can imagine the invalidation mechanism fails here as you are modifying base entity (and invalidation is based on the contents of the entity itself) - that would be actually a bug.

Btw `columnType: 'string', unique: true, nullable: false` all of this is meant for SQL only. In near future, there will be support for mongo indexes, so `unique` will work then.

`columnType ` is for setting the underlying database column type, there is no such thing in mongo - the type can be different across documents. Same applies to `nullable`. They are all used in `SchemaGenerator` which is SQL only thing, there is no such thing as creating schema in mongo. 

I will add some validation for this, so it will throw when you try to use not supported attribute (based on current database driver).

    @Property({ type: ContactEntity, columnType: 'object' })
    contact?: ContactEntity;

Here you want to have embedded document, right? It should work, but you won't get instance of `ContactEntity` there automatically (if you load `CompanyEntity` from the db, the `contact` property will be just POJO). There is no native support for embedded entities (although I am planning to support that too at some point).

**Comment by B4nan** [comment]
For the embedded entity, you could leverage `@OnInit` hook, that is fired just after the instance of given entity is created. In there you could construct the instance of `ContactEntity` manually. 

```typescript
@Entity()
export class Company implements MongoEntity<Company> {

  @Property()
  contact?: ContactEntity;

  @OnInit()
  onInit() {
    if (this.contact) {
      this.contact = new ContactEntity(this.contact);
    }
  }

}
```

**Comment by B4nan** [comment]
Tried to add the version field in ORM's tests and it successfully creates the property. Caching is correctly invalidated (I did also put the property to BaseEntity to be aligned with your use case), so that is probably not the problem here. 

If you add `console.log(entity)` just before the `persistAndFlush` call, is the version property there? Does it work when you move the property definition to the `CompanyEntity`?

**Comment by gpanainte** [comment]
> That's pretty strange, try to wipe the cache (`temp` folder). I can imagine the invalidation mechanism fails here as you are modifying base entity (and invalidation is based on the contents of the entity itself) - that would be actually a bug.
> 

I have deleted `temp` and `dist` folders and now it's working.

> Btw `columnType: 'string', unique: true, nullable: false` all of this is meant for SQL only. In near future, there will be support for mongo indexes, so `unique` will work then.
> 
> `columnType ` is for setting the underlying database column type, there is no such thing in mongo - the type can be different across documents. Same applies to `nullable`. They are all used in `SchemaGenerator` which is SQL only thing, there is no such thing as creating schema in mongo.
> 
> I will add some validation for this, so it will throw when you try to use not supported attribute (based on current database driver).
> 

Thank you for clarifications. I think the documentation could be enhanced with the description of all decorators and decorator properties. With regards to supported attributes, validations and exceptions could be one solution, but I think it would be more helpful if somehow as a developer I could rely on types to set the correct attributes. 

> ```
> @Property({ type: ContactEntity, columnType: 'object' })
> contact?: ContactEntity;
> ```
> 
> Here you want to have embedded document, right? It should work, but you won't get instance of `ContactEntity` there automatically (if you load `CompanyEntity` from the db, the `contact` property will be just POJO). There is no native support for embedded entities (although I am planning to support that too at some point).

Indeed is an embedded document. I have refactored the code as you suggested. Thank you once again for the quick response.

**Comment by B4nan** [comment]
> but I think it would be more helpful if somehow as a developer I could rely on types to set the correct attributes.

If you mean TS typings, then only way could be to introduce different decorator types for mongo driver. I was thinking about something similar, but first I want to refactor this to monorepo - then we can have `@mikro-orm/mongo` package that would export all decorators with different typings. I think it will be probably one of things I will do as part of v4 development, but now I want to focus on v3. 

Will add that decorator list to the docs, good idea!

**Comment by gpanainte** [comment]
> > but I think it would be more helpful if somehow as a developer I could rely on types to set the correct attributes.
> 
> If you mean TS typings, then only way could be to introduce different decorator types for mongo driver. I was thinking about something similar, but first I want to refactor this to monorepo - then we can have `@mikro-orm/mongo` package that would export all decorators with different typings. I think it will be probably one of things I will do as part of v4 development, but now I want to focus on v3.
> 
> Will add that decorator list to the docs, good idea!

Indeed I was referring to TS typings. Tank you once again and good luck with the new release.

**Comment by B4nan** [comment]
Added the decorator reference page: https://mikro-orm.io/docs/decorators

Also started working on advanced configuration page (basically reference to the `Configuration` object), that will follow later this week probably. 

I guess we can close this now, right?

**Comment by gpanainte** [comment]
> Added the decorator reference page: https://mikro-orm.io/docs/decorators
> 
> Also started working on advanced configuration page (basically reference to the `Configuration` object), that will follow later this week probably.
> 
> I guess we can close this now, right?

I had a look and it is clear. Great job! Indeed this issue can be closed.
