### ISSUE TITLE
Very nice error message continues "DriverException: Cannot read property '0' of null"

### ISSUE THREAD

**Issue by Mitch-i** [mikro-orm/mikro-orm#2541]
**Describe the bug**
When I save 

{ name: 'string', roles: [ { name: 'string' }, { name: 'string' } ] }

get error - DriverException: Cannot read property '0' of null

**Stack trace**
```
...
```

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | ? |
| typescript | ? |
| mikro-orm | ? |
| your-driver | ? |

**Comment by B4nan** [comment]
So you won't stop creating low effor issues like this? You really think I can reproduce something from a single line of code? It is not even a line of code, just a payload.

Sorry, but closing, if you want to report anything, it needs to be complete.
