### ISSUE TITLE
Date typecasted as string in Embeddable class 

### ISSUE THREAD

**Issue by shahidcodes** [mikro-orm/mikro-orm#2545]
**Describe the bug**
I've created below entity, which consists of a `MetaData` embeddable class which is embedded in a `User` entity.
```user.entity.ts

import {
  Embeddable,
  Embedded,
  Entity,
  PrimaryKey,
  Property,
  SerializedPrimaryKey,
} from '@mikro-orm/core';
import { ObjectId } from '@mikro-orm/mongodb';

@Embeddable()
export class MetaData {
  @Property()
  lastLoginAt: Date;
}

@Entity()
export class User {
  @PrimaryKey()
  _id: ObjectId;

  @SerializedPrimaryKey()
  id!: string;

  @Property()
  name: string;

  @Embedded({ object: true })
  meta: MetaData;
}

```

When I create a new user like below

```ts
const user = this.userService.create({
   meta: {
      lastLoginAt: new Date(),
    },
});
this.userService.persistAndFlush(user);
return user;
```

The resulting object is mongo contains 'meta.lastLoginAt' as string not as `ISODate`. If the same property moved to `User` entity then it works as expected.

**Stack trace**
```
db.getCollection('user').insertOne({ meta: { lastLoginAt: '2021-12-17T03:58:37.134Z' }, dateWorkFineHere: ISODate('2021-12-17T03:58:37.134Z') }, { session: undefined }); 
```

**To Reproduce**
1. Clone https://github.com/shahidcodes/mikroorm-mongo-date-bug
2. Set .env
3. Create a post request to /user/test and check the database 

**Expected behavior**
The `Date` type properties should have ISODate type in the mongo database.

**Additional Context**
The problem seems to only happen when `{ object: true }` is set. But it prefixes the properties as expected.
**Versions**

| Dependency | Version |
| - | - |
| node | 16.13.1 |
| typescript |4.3.5 |
| mikro-orm | 4.5.9 |

**Comment by B4nan** [comment]
Fixed in v5, cannot be packported easily.

**Comment by B4nan** [comment]
Btw you are not awaiting the flush call in your `UserService.test` method.
