### ISSUE TITLE
Add option to disable generation of FKs

### ISSUE THREAD

**Issue by ramiel** [mikro-orm/mikro-orm#2548]
To support myISAM. Not to be confused with `migrations.disableForeignKeys` config option.

**Comment by B4nan** [comment]
`disableForeignKeys` is not an option to "disable generation of FKs". it never was. it only controls if the schema commands will be wrapped in `set foreign_key_checks = 0` and `set foreign_key_checks = 1`.

**Comment by ramiel** [comment]
Oh, in version 4 it disabled foreign key constraint creation. What changed here? How do I disable foreign key creation? Not all the mysql DB use the InnoDB engine

**Comment by B4nan** [comment]
It did not change, it never worked that way.

**Comment by B4nan** [comment]
What changed is that FKs are not properly diffed, in general schema diffing now works as it should.

**Comment by ramiel** [comment]
Ok. Question remains. Is there a way to avoid creating foreign key constraints?

**Comment by B4nan** [comment]
No it is not, there never was one. Feel free to send a PR, but it would have to be a top level configuration (that will be then feeded to the `SchemaGenerator` methods as part of their options), nothing about migrations, migrations just work with `SchemaGenerator`. 

Note that you still can use v5, you just need to remove the FK queries from your migrations manually if you don't want them there. That is the whole point of migrations, as you have absolute control over that.

**Comment by ramiel** [comment]
Thanks. I have no time to provide a PR and the codebase is too big, sorry.

>Note that you still can use v5, you just need to remove the FK queries from your migrations manually if you don't want them there

Can you explain more about this?

**Comment by B4nan** [comment]
You have migration file with SQL queries, so you can just remove those you dont want there. Not sure what more you want me to explain about that :]

Note that the codebase might be big, but this problem is about a single file. 

https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/schema/SchemaGenerator.ts#L69
https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/schema/SchemaGenerator.ts#L157
https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/schema/SchemaGenerator.ts#L166
https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/schema/SchemaGenerator.ts#L261
https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/schema/SchemaGenerator.ts#L303

(and maybe few more places in that file)

**Comment by B4nan** [comment]
Let's keep this open, I don't want to sound like I don't see this as something valid. But to me it feels like an edge case, it's been a decade since I came accross someone actually using myisam :D Might be just my bubble :D

**Comment by ramiel** [comment]
So, let me explain better what I mean. In my code, during startup in ev mode, I have something like this

```ts
const generator = orm.getSchemaGenerator();
    
await generator.updateSchema({
  wrap: false,
  safe: true,
  dropDb: false,
  dropTables: false,
});
```

this way I'm sure DB is up to date with my models. Maybe it's the wrong way, I don't know. If this fails, I print the needed update on console and I run manually. Having an option to disable foreign key contraints would avoid me to run anything manually.

On the other side, I'm not talking about myIsam. I don't know anybody using it. I'm talking about a new generation of cloud-centric mysql based DBs that have very large scalability performances. In a previous message I mentioned one of those (planetscale) and an engine very popular and used (vitess).

I'll try to find the time to work on this and propose a PR, but I'm afrai I really have not much time. What would take me hours or days to be done/tested and so on, it's for sure much less for whoever has already familiarity with the codebase. I'm not saying I want you to do it, I'm just asking if by any chance this can be done. 

Thanks for the support

**Comment by B4nan** [comment]
> this way I'm sure DB is up to date with my models. Maybe it's the wrong way, I don't know. If this fails, I print the needed update on console and I run manually. Having an option to disable foreign key contraints would avoid me to run anything manually.

It's not wrong, but I would be quite cautious with this in a production environment (but yeah, with `safe: true` it should be ok'ish). I wouldn't trust the schema diffing in v4 that much, v5 should be a different story, it's much smarter :] 

Note that you are using schema generator, so nothing you specify in `migrations` config has any effect on that, its a different layer, hence my confusion as you were talking about configuring how migrations work. 

And indeed, to me it will probably take an hour or two, to you it can take much more. But you are the one who needs it (actually the first one to ask for it). If you don't have time to collaborate, you can always sponsor the development, especially if this is something you need for a project that will bring you some revenue.

>  I'm not saying I want you to do it, I'm just asking if by any chance this can be done.

The sad fact is that pretty much all the issues wait for me to work on them. Only a small portion of people will try to contribute, many of them will send an incomplete (often failing) PR and never even reply to my feedback. I usually ask for that in issues like this one, where it really is easy task to achieve. Often I don't even want others to contribute, if it's something touching internals as it can easily have breaking effect to other parts of the codebase.

**Comment by varHarrie** [comment]
Is there an option to avoid creating foreign key constraints? Just like [createForeignKeyConstraints](https://github.com/typeorm/typeorm/issues/3120#issuecomment-776916662) from typeorm.

**Comment by nicomouss** [comment]
@B4nan I reach the need to be able to disable the generation of FKs, only on specific tables/relations.

Following what is done in fcdb236, would you be interested in a PR implementing the possibility to disable foreign key on specific `many-to-one`, `one-to-one`, and `many-to-many` relations ?

The idea would be to be able to do something like so:

```ts
@Entity()
export class Book {
  @ManyToOne({ /* ... */,  generateForeignKeyConstraint: false })
  author!: Author;
}
```

Logic would be:
- `generateForeignKeyConstraint` defaults to `true` by default on each relation.
- If global `generateForeignKeyConstraints` is set to `false`, then it would not generate any foreign key constraint whatsoever.
- If global `generateForeignKeyConstraints` is set to `true`, then it would generate foreign key constraint according to what is set for `generateForeignKeyConstraint` on each relation.
