### ISSUE TITLE
IdentifiedReference, eager loading, and wrapping

### ISSUE THREAD

**Issue by emrosenf** [mikro-orm/mikro-orm#256]
I'm doing some authentication work and fetching a `ValidationToken` with its associated `User` with relation defined as such:

```typescript
  @ManyToOne({ entity: () => User, cascade: [Cascade.MERGE], nullable: true })
  user?: IdentifiedReference<User>;
```

I've pasted the screenshot below so you can see the type hint.

<img width="868" alt="Screen Shot 2019-12-05 at 3 34 24 PM" src="https://user-images.githubusercontent.com/425523/70244646-16d6a680-1775-11ea-914a-67cd977d7aa5.png">

`token.user` is expected to be an `IdentifiedReference<User>` with an `unwrap()` method, but it is actually a full-blown `User` when I inspect it in the debugger. This line of code causes a runtime error.

I can `wrap(token.user).assign({...})` to it, but if I can't figure out how to get an actual `User` typed-object to pass into other functions.

What am I doing wrong?

**Comment by B4nan** [comment]
I think the problem is that you provide the `entity` attribute explicitly. Try adding `wrappedReference: true` to the decorator options:

```typescript
  @ManyToOne({ entity: () => User, cascade: [Cascade.MERGE], nullable: true, wrappedReference: true })
  user?: IdentifiedReference<User>;
 ```

If you do not provide the `entity` explicitly, `TsMorphMetadataProvider` will read the TS type (which is `IdentifiedReference`) and fill this `wrappedReference` attribute for you automatically.

**Comment by B4nan** [comment]
Looking at the docs, it is not really properly mentioned there, although we do have this example already in the Metadata Providers page in the limitations section... So again documentation issue probably.

**Comment by B4nan** [comment]
Added note about this into the docs. Please let me know if it helped, but I am pretty sure this should solve your problem.
