### ISSUE TITLE
MikroORM CLI Fails to Run with ts-node

### ISSUE THREAD

**Issue by dakotacookenmaster** [mikro-orm/mikro-orm#2565]
**Describe the bug**
Using TypeScript (ts-node), the config is undefined when trying to execute the `mikro-orm/cli` command from the terminal.

**Stack trace**
```
C:\Users\<user>\Documents\projects\emblem\server-new\node_modules\@mikro-orm\core\utils\ConfigurationLoader.js:67
        const { options } = tsNode.register({
                ^
TypeError: Cannot destructure property 'options' of 'tsNode.register(...).config' as it is undefined. 
    at Function.registerTsNode (C:\Users\<user>\Documents\projects\emblem\server-new\node_modules\@mikro-orm\core\utils\ConfigurationLoader.js:67:17)
    at Function.configure (C:\Users\<user>\Documents\projects\emblem\server-new\node_modules\@mikro-orm\cli\CLIConfigurator.js:20:46)
    at C:\Users\<user>\Documents\projects\emblem\server-new\node_modules\@mikro-orm\cli\cli.js:16:19
```

**To Reproduce**
1. Install @mikro-orm/cli
2. Define a TS Config File:

tsconfig.json
```
{
   "compilerOptions": {
      "lib": [
         "es5",
         "es6",
         "ES2021",
         "esnext.asynciterable"
      ],
      "target": "es2021",
      "module": "es2022",
      "moduleResolution": "node",
      "outDir": "./build",
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true,
      "esModuleInterop": true,
      "sourceMap": true,
      "resolveJsonModule": true
   }
}
```

3. Define a mikro-orm.config.ts file:

mikro-orm.config.ts
```
import { Options } from "@mikro-orm/core"
import dotenv from "dotenv"

const NODE_ENV = process.env.NODE_ENV || "production" // Default to production if not set

dotenv.config({
   path: `./${NODE_ENV}.env`
})

const config: Options = {
    entitiesTs: ['./src/entity/User.ts'], // entities: ['./src/entity/*.ts'],
    dbName: process.env.DB_NAME,
    type: process.env.DB_TYPE as any,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT as any,
    user: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    debug: process.env.DB_MODEL_LOGGING as any,
}

export default config
```

4. Update the package.json file to include mikro-orm configuration settings:

package.json
```
{
... other config ...,
"mikro-orm": {
      "useTsNode": true,
      "tsConfigPath": "./tsconfig.json",
      "configPaths": [
         "./mikro-orm.config.ts"
      ]
   }
}
```

5. Run the script from the command line:

``` npx mikro-orm debug ```

** Additional Information **
I did manage to get it to work by settting `useTsNode` to `false` and changing it to a JS file, but this is a non-solution.

**Expected behavior**
I expect to see the debug information.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.0.0 |
| ts-node | ^3.3.0 |
| typescript | ^4.3.5 |
| mikro-orm | ^4.5.9 |
| your-driver | 'mysql' |

**Comment by B4nan** [comment]
Do you have ts-node installed? You need to do so to use TS configs.

**Comment by dakotacookenmaster** [comment]
Hey, @B4nan ! Yes, I have ts-node installed.

**Comment by B4nan** [comment]
Then upgrade your local version of it. Latest is 10.4, so your version is quite archaic :)

**Comment by dakotacookenmaster** [comment]
Wow! I can't believe I'd been running with such an outdated version. That fixed the issue. Thank you for your help with such an insignificant issue.
