### ISSUE TITLE
Entity References is of wrong shape when updating entity

### ISSUE THREAD

**Issue by ColinCee** [mikro-orm/mikro-orm#2570]
**Describe the bug**
I'm have two endpoints for an entity, a READ and an UPDATE

The read response shape doesn't match the result of an update after it is `JSON.stringify`

READ Example
```json
{
    "id": 1780,
    "contract": {
        "id": 123033
    },
    "claimStatus": {
        "id": 6,
        "name": "Upcoming",
    },
}
```

UPDATE result
```json
{
    "id": 1780,
    "contract": 123033,
    "claimStatus": 7,
}
```
As you can see, the entity relations for both `contract` and `claimStatus`  are no longer an object, but rather a simple number. Should it not match the same shape as the read example?

Ideally this is so that my frontend can just update the cached result but because the shape is different I'd have to add extra code in the frontend to account for this behaviour or in the backend.

-----
My Entity looks like this

```ts
@Unique({
    name: "UC_Claim",
    properties: ["contract", "type", "claimStartDate"],
})
export class Claim {
    @Unique({ name: "id_UNIQUE" })
    @PrimaryKey({ type: "number" })
    id!: number;

    @OneToOne({ entity: () => Contract, nullable: true })
    contract?: Contract;

    @ManyToOne({
        entity: () => ClaimStatus,
        fieldName: "claim_status_id",
        nullable: true,
        index: "fk_status",
    })
    claimStatus?: ClaimStatus;
}
```

Here's is the Read and Update code:

```ts
export const getClaimById = async (id: number) => {
    const { claimRepository } = await initDatabase();
    return claimRepository.findOne(id, ["claimStatus"]);
};

export const updateClaimStatus = async (
    claim: Claim,
    claimStatusId: number
) => {
    const { orm } = await initDatabase();

    claim.claimStatus = orm.em.getReference<ClaimStatus>(
        ClaimStatus,
        claimStatusId
    );
    await orm.em.persistAndFlush(claim);

    return claim;
};
```
-----
I've also tried to return the updated entity by calling `getClaimById` as the last step in `updateClaimStatus`

```ts
export const updateClaimStatus = async (
    claim: Claim,
    claimStatusId: number
) => {
    const { orm } = await initDatabase();

    claim.claimStatus = orm.em.getReference<ClaimStatus>(
        ClaimStatus,
        claimStatusId
    );
    await orm.em.persistAndFlush(claim);

    return getClaimById(claim.id);
};
```

However the result is 

```json
{
    "id": 1780,
    "contract": 123033,
    "claimStatus": {
        "id": 7,
        "name": "Late",
        "code": "6a",
    }
}
```
Which is better than the previous example, as claimStatus is populated correctly. However the contract property is still a number and I don't wish to populate the entire relation as there is a lot of unnecessary data on contract, just the id is enough here.

P.S I've also tried `wrap(Claim).assign()` but got the same issue

-----
**Stack trace**
N/A

**To Reproduce**
1. Using the entities above
2. Call `getClaimById`
3. Call `updateClaimStatus`
4. Compare the `JSON.stringify` result of both calls, they should match

**Expected behavior**
After persisting and flushing the entity object should result in json that matches the read endpoint

**Additional context**
Deployed on lambda

**Versions**

| Dependency | Version |
| - | - |
| node | 14.18.1 |
| typescript | 4.4.4 |
| mikro-orm | 4.5.9 |
| mysql | 4.5.9 |

**Comment by B4nan** [comment]
You need to populate it to have object payload, references are always represented just by the PK. Or use custom serializer or toJSON method.

**Comment by ColinCee** [comment]
Thanks, that seems to have done it

However the default behaviour of `findOne` and `JSON.stringify` results in references that are not just the PK. Is this a bug then?

example

```json
{
    "id": 1780,
    "contract": {
        "id": 123033
    },
    "claimStatus": {
        "id": 6,
        "name": "Upcoming",
    },
}
```

**Comment by B4nan** [comment]
I don't understand what you mean. "default behaviour" is that not populated relation is represented by a FK. Only populated ones will be objects. We are talking about the seriazlied form, so what you get when doing `wrap(e).toObject/toJSON()`, which happens automatically if you try to serialize such object via `JSON.stringify`. On runtime/entity level, you always have the relation represented by object.
