### ISSUE TITLE
createQueryBuilder().update() type error with custom repository

### ISSUE THREAD

**Issue by alexy4744** [mikro-orm/mikro-orm#2576]
**Describe the bug**
When using `createQueryBuilder().update()` inside of a custom repository, the generic passed to the type `EntityRepository` must be a concrete type

**Stack trace**
```
Argument of type '{ path: "this is a string"; }' is not assignable to parameter of type 'EntityData<Node>'.ts(2345)
```

**To Reproduce**
[Reproduction repo](https://github.com/alexy4744/mikro-orm-v5-qb-bug)

**Expected behavior**
It should correctly infer the type for each field

**Versions**

| Dependency | Version |
| - | - |
| node | 17.0.1 |
| typescript | 4.5.4 |
| mikro-orm | 5.0.0-dev.592 |
| postgresql | 5.0.0-dev.592 |

**Comment by B4nan** [comment]
This is a TS limitation with generics and extensions, nothing we can do about it. Use custom repositories only for the final types so you dont need any `extends` in the type argument to get around it.

**Comment by B4nan** [comment]
Here is a reproduction without the ORM involved, just so you can see it is a more general problem:

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCoQM5mcg3gWACgdgATALmSylAHMBuInABzjAAtLq7HCBfIkTABPZigCi4YCIAibOAB5UAPmQBePMgDaAaWShkAawjCA9jDQBdAPyVUuy8j68iCADZwMGZADFTppVUCYmQYfwAKUnlKSTBpYTkwRRUASjwmHGQAeiyMgX5BQndPbwAhOCglZAgAD0gQUm90LFVa+sbff0D0kIAjCsjo5Fj4xOTlNODM5A5gDAA6MNNwqenkVg5KAHJZ7znkOCowGhBaLYAaDJw+FN5ronygA
