### ISSUE TITLE
Unable to unmarshall pg array

### ISSUE THREAD

**Issue by silentroach** [mikro-orm/mikro-orm#2583]
Seems like you forgot to implement unmarshallArray method for pg platform, so the [default split](https://github.com/silentroach/mikro-orm/blob/master/packages/core/src/platforms/Platform.ts#L259-L265) is used.

**Stack trace**
```
 ValidationError: Invalid enum array items provided in SomeEntity.values: [ '{first', 'second}' ]
    at EnumArrayType.convertToDatabaseValue (/code/node_modules/@mikro-orm/core/types/EnumArrayType.js:24:23)
    at /code/node_modules/@mikro-orm/core/hydration/ObjectHydrator.js:72:96
```

**To Reproduce**
```
enum SomeEnum {
  First = 'first',
  Second = 'second'
};

...

  @Enum({ items: () => SomeEnum, name: 'some', array: true, nullable: false })
  some!: SomeEnum[];
```

**Additional context**
PostgreSQL

**Versions**

| Dependency | Version |
| - | - |
| node | 16.13.1 |
| typescript | 4.5.4 |
| mikro-orm | 4.5.10 |
| your-driver | pg |

**Comment by B4nan** [comment]
Afaik the driver should give us array, not a string - that is how it works in postgres, we shouldnt get serialized array at all. Arrays definitely work fine in postgres, so this might be enum array issue. Still feels weid, full repro welcome.

**Comment by silentroach** [comment]
```sql
create type mikro_orm_test as enum ('first', 'second', 'third');

create table mikro_orm_test_table (
    id serial not null primary key,
    values mikro_orm_test[]
);

insert into mikro_orm_test_table (id, values)
select 1, array['first', 'second']::mikro_orm_test[]
```

```ts
import { Entity, Enum, PrimaryKey } from '@mikro-orm/core';

enum Value {
  First = 'first',
  Second = 'second',
  Third = 'third',
}

@Entity({ tableName: 'mikro_orm_test_table' })
export class TestEntity {
  @PrimaryKey({ name: 'id' })
  id!: number;

  @Enum({ name: 'values', items: () => Value, array: true })
  values!: Value[];
}
```

```ts
    @InjectRepository(TestEntity)
    private readonly testRepository: EntityRepository<TestEntity>,

    ...

    const entity = await this.testRepository.findOne({
      id: 1,
    });
```

**Comment by B4nan** [comment]
That is definitely not supported, you cant use native enums in pg.

**Comment by silentroach** [comment]
But it is native pg enums. What do you mean?

**Comment by silentroach** [comment]
Oh, got it, thank you

**Comment by B4nan** [comment]
Can you try to add that unmarchall method locally to see if its just about that? Native pg enums are not supported mainly due to schema diffing, but if this is just about runtime issues, we can definitely do something about that.

**Comment by silentroach** [comment]
Looks like it works fine, but not sure it will cover all potential use cases
