### ISSUE TITLE
Implement partial indexes now that Knex supports it

### ISSUE THREAD

**Issue by ryall** [mikro-orm/mikro-orm#2585]
Mostly a follow-on to #1029.

It appears that [Knex has recently merged support for partial indexes on relational databases](https://github.com/knex/knex/pull/4768). It would be great to support this in MikroORM.

---

Also, in the mean-time, what would be the best way to implement partial indexes until this feature is added? Would it be possible with a raw query of some kind?

**Comment by B4nan** [comment]
v4 is diffing indexes only by name, so just create index with matching name and schema diffing will ignore it. in v5 you can use index expressions for this. I don't plan to add more ways to create indexes, as index expressions do allow literally any kind of index to be created. 

```ts
  @Index({ name: 'custom_index_expr2', expression: 'alter table `book` add index `custom_index_expr2`(`title`)' })
  @Property()
  title!: string;
```

Note that you can also use `type` parameter of `@Index` decorator - it is exactly what will be passed to the [3rd parameter of `index` method](https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/schema/SchemaGenerator.ts#L420) of knex schema builder. But v4 has old version of knex (as there were breaking changes that would surface to us), so to use latest knex you also need to use v5.
