### ISSUE TITLE
Smart Nested Populate with $or Doesn't Populate Relations When Forced

### ISSUE THREAD

**Issue by dakotacookenmaster** [mikro-orm/mikro-orm#2586]
**Describe the bug**
MikroORM should be able to handle smart nested query population, even when using filtering options such as `$and`, `$or`, `$not`. However, making a query in which the two options in the `$or` clause are relations, MikroORM fails to populate both relations, even when forced with ```{ populate: true }```. The current workaround is to use ```em.populate(...)``` after the query, or to manually separate the `$or` clause into two separate queries, and use array destructuring (e.g. ```const result = [...query1, ...query2]``` in order to address this.

**Stack trace**
`No stack trace. MikroORM thinks it has successfully returned the appropriate result.`

**To Reproduce**
1. Create an entity with two fields that are of type ```Collection```

For example, let's say you had the following simple entity:

```JS
import {Collection, Entity, ManyToMany, PrimaryKey, } from "@mikro-orm/core"
import { v4 as uuid } from "uuid"
import User from "./User"
import Course from "./Course"

@Entity()
export default class Section {
    @PrimaryKey() // Generate universally-unique identifier
    id: string = uuid()

    @ManyToOne({ entity: "Course", inversedBy: "sections", onDelete: "CASCADE" })
    course: Course

    @ManyToMany({ entity: "User", mappedBy: "sections_enrolled_as_instructor" })
    instructors = new Collection<User>(this)

    @ManyToMany({ entity: "User", mappedBy: "sections_enrolled_as_student" })
    students = new Collection<User>(this)
}
```

Also, note that the relationship is bidirectional. The connections are situated appropriately on the reverse side of the relation in the `User` and `Course` entities.

2. Query that relation, using smart nesting to determine if a condition matches either something in the first collection or something in the second collection (using the `$or` operator), like so:

```JS
const sections = await request.em.find(Section, {
    $or: [
        {
            students: {
                id: request.user.id,
            }
        },
        {
            instructors: {
                id: request.user.id,
            }
        }
    ]
}, {
    populate: ['students', 'instructors', 'course', 'course.upload']
)
```

Assume that the `course.upload` field (type-checked) appears on the referenced `Course` entity.

**Expected behavior**
I expect that regardless of which match is found, both the `students` and `instructors` relations are completely populated. However, this is not the case. Instead, of fully-populated fields, only ONE of the fields is populated (generally the students field - the instructors field is left as an empty array).

At first I thought this may have been an issue on my end, so I checked my database (and ergo the join table created between the entities) and determined that the appropriate data did exist. I queried the data separately (i.e. `studentSections` and `instructorSections`) and populated each of them, and then merged them using array destructuring (i.e. `[...studentSections, ...instructorSections]`). This populated the entities. Another successful workaround was using my original query and then forcing population after the fact, using `await request.em.populate(sections, ['students', 'instructors', 'course', 'course.upload'])`. However, this really strikes me as anti-pattern and should be appropriately handled in the `populate` field of the initial request.

**Additional context**
I sincerely appreciate any help anyone can provide!

**Versions**

| Dependency | Version |
| - | - |
| node | 16.8.0 |
| typescript | ^4.3.5 |
| ts-node| ^10.4.0 |
| mikro-orm | ^5.0.0-dev.593 |
| your-driver | mysql |

**Comment by B4nan** [comment]
What queries does it produce and what queries would you expect? I guess the OR conditions are extracted but they are applied as AND instead of OR, or something like that?

Full repro would be welcome, ideally as a [test case](https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues).

> I expect that regardless of which match is found, both the students and instructors relations are completely populated.

That is not how it works. Nested queries will be extracted and applied to the populate queries. You need to use separate `em.populate()` call if you want different condition for root entity and for populate queries.

Imagine this example:

```ts
const authors = await em.find(Author, { books: [1, 2, 3] }, { populate: ['books'] });
```

This will find authors that have books with PK 1, 2, or 3, and populate their books relation, again with the same condition. So as a result, you will have partially loaded books collections only with books 1, 2, or 3. That might be what you are facing, and it is correct/expected behaviour.

**Comment by dakotacookenmaster** [comment]
I appreciate your quick response! Let me ask a simple question that might help to answer this.

In English, if I said, "Give me any section, **_with all of its relations_**, where either a student has a matching ID or an instructor has a matching ID," how would you write it?

I figured that I could `$or` those predicates together, but apparently that isn't the case. 

I really want to get ANY section that matches either of those conditions.

**Comment by B4nan** [comment]
I already gave you clear example of what is expected behaviour. Please re-read my post, I really feel like this part is exactly about your use case. If you want to load relations regardless of the where condition, you need to use separate populate call, and this would be covered with my proposal for `populateCondition: false`. If so, there is no need for a test case, and this would be actually a feature request, not a bug report.

> That is not how it works. Nested queries will be extracted and applied to the populate queries. You need to use separate em.populate() call if you want different condition for root entity and for populate queries.
>
>Imagine this example:
>
> ```ts
> const authors = await em.find(Author, { books: [1, 2, 3] }, { populate: ['books'] });
> ```
> This will find authors that have books with PK 1, 2, or 3, and populate their books relation, again with the same condition. So as a result, you will have partially loaded books collections only with books 1, 2, or 3. That might be what you are facing, and it is correct/expected behaviour. You are not the first one who needs this, I can imagine adding new option to "not propagate condition to populate queries", something like populateCondition: false - and it could be also used to override the condition to something else, the default would be to reuse the  condition from em.find().

If all you want is to load the relations for given entities:

```ts
// just load the sections here
const sections = await em.find(Section, {
    $or: [
        {
            students: {
                id: request.user.id,
            }
        },
        {
            instructors: {
                id: request.user.id,
            }
        }
    ]
});
// and populate their relations separately
await em.populate(sections, ['students', 'instructors', 'course', 'course.upload']);
```

**Comment by dakotacookenmaster** [comment]
Ok, it's good to know that this is the expected behavior. I appreciate your quick responses. Thank you!
