### ISSUE TITLE
Relation is not populated in new entity in NestJS

### ISSUE THREAD

**Issue by univerze** [mikro-orm/mikro-orm#2592]
**Describe the bug**
After creating a new entity and M:N relations, the relation in response only returns the ID of the related entity instead of the whole object.

**Stack trace**
```
...
```

**To Reproduce**
```
    const groups = await this.groupRepo.find({ id: { $in: dto.groups } });
    const user = new User();
    user.name = dto.name;
    user.email = dto.email;
    user.groups.set(groups);
    await this.repo.persistAndFlush(user);
    console.log(user);
    return user;
```
Console.log shows
```
User {
  id: '2fbba3f7-28f8-474e-be5f-a5dcc6f85cc0',
  groups: Collection {
    '0': Group {
      id: '0afb35bb-fc1a-4087-9ced-551d5d8be5a2',
      createdAt: 2022-01-01T11:45:09.000Z,
      updatedAt: null,
      deletedAt: null,
      name: 'new',
      description: null,
      users: [Collection],
      roles: [Collection]
    },
    initialized: true,
    dirty: false
  },
  name: 'eee',
  email: 'eee@eee.com'
}
```
However the request response is just
```
{
	"id": "2fbba3f7-28f8-474e-be5f-a5dcc6f85cc0",
	"groups": ["0afb35bb-fc1a-4087-9ced-551d5d8be5a2"],
	"name": "eee",
	"email": "eee@eee.com"
}
```

**Expected behavior**
The groups array in the response contains the whole collection item not just the ID.

**Additional context**
Using latest NestJS and latest MikroORM

**Versions**

| Dependency | Version |
| - | - |
| node | ? | v14.18.1
| typescript | ? | 4.3.5
| mikro-orm | ? | 4.5.9
| your-driver | ? | mikro-orm/mysql 4.5.9

**Comment by B4nan** [comment]
Don't ignore the issue template. How can I know if you are using v4 or v5? Because this behaviour changed in v5.

You need to enable `populateAfterFlush` in your ORM config. In v5 it is enabled by default.

Btw note that `groupRepo.find({ id: { $in: dto.groups } })` is the same as `groupRepo.find(dto.groups)`.
