### ISSUE TITLE
Can't use nullable boolean fields

### ISSUE THREAD

**Issue by vimmerru** [mikro-orm/mikro-orm#262]
**Describe the bug**

1. Define boolean field and mark it as nullable (default type will be tinyint in mysql)
2. Assign `false` to the field
3. flush em and look to database

The field is stored as 'null' instead of 0. 

**Versions**

3.0.0-rc.2

**Comment by B4nan** [comment]
Fixed in `3.0.0-rc.3`.

**Comment by SDAdham** [comment]
I still have this issue in `4.5.9`
