### ISSUE TITLE
Accessing properties on uninitialized entities doesn't fail

### ISSUE THREAD

**Issue by stephenh** [mikro-orm/mikro-orm#263]
If I have a Project, and a Project has a Client, i.e.:

```typescript
@Entity({ collection: "projects" })
export class Project implements IdEntity<Project> {
   ...
  @ManyToOne(() => Client)
  client: Client;
   ...
}
```

And I load the project w/o `client` being initialized, I can access `project.client.email` and it will return undefined.

This generally makes sense, b/c the client entity is not initialized yet, I need to `await project.client.load()`, however it seems like the `.email` should fail fast and immediately throw an exception that "hey, you're trying to access a property on an uninitialized entity, that is not going to work", instead of returning.

**Comment by B4nan** [comment]
You could use the `Reference` wrapped that would solve this: https://mikro-orm.io/docs/entity-references/#better-type-safety-with-referencet-wrapper

Previously I was under impression that what you suggest is not possible without a wrapper class, but it might be possible via `Proxy` class. I will need to experiment with that to be sure.

**Comment by stephenh** [comment]
Cool, thanks for the link to the `Reference`, yeah, I think I want to opt-in to that level of safety, so I'll start using that.

Per using a Proxy, I'm not against that per se, but inline with my thoughts on #145, I'm not sure that any approach that is based on "well, you can call `project.client.email` and it may/may not work" is really that great.

I.e. instead of focusing on figuring out how a Proxy could intercept this "you have an unloaded `Client` but called `client.email` so I need to tell you that was bad as a runtime exception" (which is technically what I requested in this bug), I'd personally nudge you towards refining Mikro's approach such that "if you have a `Client`, then by definition `client.email` will _always_ work, i.e. its already loaded and you can just call it w/o any proxy magic".

Which, right, means that anyone using "maybe loaded/maybe unloaded Client" (i.e. as the return value from `project.client`) is really a `Ref<Client>`.

So, given that, I'll just closing this out as "yeah, what #145 said". :-)

**Comment by B4nan** [comment]
Hmm you are right, Proxy wouldn't solve much, it would be just better error handling. I will try to spend the time with improving the `Reference` wrapper so we can have that as the default way.
