### ISSUE TITLE
Migrations are created with wrong characters in non-English locale on Windows

### ISSUE THREAD

**Issue by MrFoxPro** [mikro-orm/mikro-orm#2639]
**Describe the bug**
When I'm generating migrations  (e.g. ` npx mikro-orm migration:create --initial`) under WSL 2 with en-US locale migrations are creating correctly.
But on Windows 10 with ru-RU locale migrations are being generated with `` ` `` quoutes in typescript source code and this causes error when applying to DB. 
**Stack trace**
``MigrationError: Migration Migration20211219155639 (up) failed: Original error: create table `user` (`id` int unsigned not null auto_increment primary key, `username` varchar(255) not null, `email` varchar(255) not null, `bio` varchar(255) not null, `image` varchar(255) not null, `password` varchar(255) not null) default character set utf8mb4 engine = InnoDB; - ошибка синтаксиса (примерное положение: "`")``
![изображение](https://user-images.githubusercontent.com/17229619/149526586-24c1ca3c-270f-4522-8289-1843a0c07b00.png)

**To Reproduce**
1. Switch win10 to Russian locale
2. Clone [readlworld example](https://github.com/mikro-orm/nestjs-realworld-example-app/tree/v5) 
3. Try to create migration and apply scheme.

**Expected behavior**
Quoutes shouldn't depends on OS locale.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.13.0 |
| typescript | 4.5.5 |
| mikro-orm | ^5.0.0-dev.584 |
| your-driver | postgresql |

**Comment by MrFoxPro** [comment]
How can I help with solving this issue?

**Comment by B4nan** [comment]
That example project is done in mysql, if you want to use postgres, you need to adjust that migration yourself. Ideally just remove that old migration and create new one.

**Comment by MrFoxPro** [comment]
> That example project is done in mysql, if you want to use postgres, you need to adjust that migration yourself. Ideally just remove that old migration and create new one.
> 
> edit: just to be more clear, this has nothing to do with locales, quoting works based on the driver, not locale. postgres uses double quotes `"` while mysql/sqlite uses `` ` `` single backtick

Thank you.
