### ISSUE TITLE
Provide IdentifiedRef.set/WrappedEntity.toRef method

### ISSUE THREAD

**Issue by stephenh** [mikro-orm/mikro-orm#264]
Assign values to `IdentifiedRefs` is currently pretty clunky:

```typescript
    const client = new Client();
    client.email = "bob@client.com";
    await em.persistAndFlush(client);

    const project = new Project();
    project.client = context.em.getRepository(Client).getReference(client.id, true);
```

It'd be nice to be able to do:

```
project.client.set(client);
```

Or

```
project.client = client.toRef();
```

Where `toRef` was a new method on `WrappedEntity`.

Or is there a similarly succinct way of doing this that I'm not seeing?

**Comment by B4nan** [comment]
You can do `project.client = Reference.create(client);`. This way also cascading should work so you can persist only the `project` entity:

```typescript
const client = new Client();
client.email = "bob@client.com";

const project = new Project();
project.client = Reference.create(client);
await em.persistAndFlush(project);
```

**Comment by stephenh** [comment]
Ah great! `Reference.create` is definitely better and "so can I avoid the `client`-specific `persist` and just have cascading work?" was going to be my follow up question. :-) 

Fwiw, I still wouldn't mind a `client.toRef()`/`client.asRef()` method because when I was trying to guess at how this worked, I did `project.client = client.<control-space-and-look-for-a-method-that-returns-ref>`. :-) 

(I also generally like a `project.client.set(client)`, where the `client` property/`IdentifiedRef` is always set and acts more like the `Collection` class, i.e. it is always initialized on the instance, and then the user can call `.load`/`.set`/`.add`/etc. methods on it, instead of doing a whole-sale reassignment from one ref to another. Something like `@ManyToOne client = new IdentifiedRef<Project, Client>(this)` or what not.)

**Comment by B4nan** [comment]
> Fwiw, I still wouldn't mind a client.toRef()/client.asRef() method because when I was trying to guess at how this worked, I did project.client = client.<control-space-and-look-for-a-method-that-returns-ref>. :-)

Yeah, why not, anything that will make the usage more convenient. I think I will go with `toReference()` - or we could rename it everywhere to just `Ref`, but I am not a big fan of abbreviations, especially not when it comes to class names :] 

> (I also generally like a project.client.set(client), where the client property/IdentifiedRef is always set and acts more like the Collection class, i.e. it is always initialized on the instance, and then the user can call .load/.set/.add/etc. methods on it, instead of doing a whole-sale reassignment from one ref to another. Something like @ManyToOne client = new IdentifiedRef<Project, Client>(this) or what not.)

The problem with that would then be conditional checks for the existence of given reference (`if (client.project) { ... }` vs `if (client.project.exists()) { ... }`), it would be another hard to spot thing when migrating from other ORMs. But we could support that optionally. I will add the `Reference.set` method to start with.

**Comment by stephenh** [comment]
> I think I will go with toReference()

Cool, +1 for consistency.

Interesting point about `if (client.project)` ... I kind of wonder if there's a way for the TS compiler to realize that would always be true (i.e. if the field was marked as `readonly`) and so provide a compile/lint error.

**Comment by B4nan** [comment]
`Reference.set` and `WrappedEntity.toReference` are now both available in `3.0.0-rc.3`.

**Comment by stephenh** [comment]
Amazing turn around, thanks!

**Comment by B4nan** [comment]
I will close this one, the only outstanding thing here was the suggestion for null object support with references. Tried to play with that, but I still feel like it is not the right way to handle this. 

Btw I think one should be able to achieve this via `@OnInit` hook and by extending the `Reference` wrapper to support `null` value.

**Comment by stephenh** [comment]
> I will close this one

Cool, thanks again.

>  the only outstanding thing here was the suggestion for null object support with references

Not quite following the "null object support", which suggestion was that?

**Comment by B4nan** [comment]
Having that reference object always present, possibly wrapping null value.
