### ISSUE TITLE
Mapped type `Loaded<T, L>` breaks assignability for entities with `private` members

### ISSUE THREAD

**Issue by itsame-luigi** [mikro-orm/mikro-orm#2652]
**Describe the bug**
If an entity class contains TypeScript `private` members, the result from `em.findOne` isn't assignable to the type of the entity class as the `Loaded` mapped type loses private members.

**To Reproduce**
1. Define an entity class with a TS `private` method (NOTE: *not* a JS private name)
2. Use `em.findOne` or `em.findOneOrFail` to produce a result.
3. Attempt to pass the result as an argument to a function expecting that entity type.

```ts
import { Entity, MikroORM, PrimaryKey } from '@mikro-orm/core';

@Entity()
export class A {
    @PrimaryKey()
    id: number;

    constructor(id: number) {
        this.id = id;
    }

    private m() {}
}

declare function f(a: A): void;
declare let orm: MikroORM;

async function test() {
    const a = await orm.em.findOneOrFail(A, { id: 1 });
    f(a); // error: TS2345
          // Argument of type 'Loaded<A, never>' is not assignable to parameter of type 'A'.
          //   Property 'm' is missing in type 'Loaded<A, never>' but required in type 'A'.
}
```

**Expected behavior**
No type error.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.6.2 |
| typescript | 4.5.4 |
| mikro-orm | 5.0.0-dev.645 |
| your-driver | not applicable |

**Comment by itsame-luigi** [comment]
Changing `Loaded<T, L>` to intersect with `T` might be a solution, since intersections are ordered (and thus new types introduced in the map type would narrow the types of the properties of `T`):

```ts
// NOTE: Modified definition to use `T & { /* mapped type */ }`
export type Loaded<T, L extends string = never> = T & {
  [K in keyof T]: K extends Prefix<L>
    ? LoadedLoadable<Defined<T[K]>, Loaded<ExtractType<Defined<T[K]>>, Suffix<L>>>
    : T[K]
};
```

**Comment by B4nan** [comment]
> Changing Loaded<T, L> to intersect with T might be a solution, since intersections are ordered (and thus new types introduced in the map type would narrow the types of the properties of T):

I remember we have it like that in v4. Tried to change it in master and seems like no ORM tests are affected by that.

cc @JanJakes I believe you were the one who proposed the simplified types without the intersection - do you see any problem with this change?

**Comment by JanJakes** [comment]
@B4nan It's hard to quickly check such a complex typing without playing with the TS playground a bit but it seems to make sense to me to preserve anything else that the original type contains and is not of interest for the `Loaded` type.

**Comment by itsame-luigi** [comment]
I've been running into issues with my data model using 5.0.0-rc.3:

```
Type instantiation is excessively deep and possibly infinite. ts(2589)
Expression produces a union type that is too complex to represent. ts(2590)
```

This is just with a call to `findOne({ id })` for one of my entities. Since I'm not passing a value for `populate`, the call to `findOne` infers `never` for the `L` type variable in `Loaded`. 

If the intent of `Loaded` is to pass through `T` if there's nothing to populate, it might make sense to avoid creating a mapped type when `L` is `never`. Unfortunately, you can't directly test for `never` using a conditional type, as `never` has some interesting behavior when used as the constraint type in a conditional type:

```ts
type IsNever<T> = T extends never ? true : false;
type T1 = IsNever<{}>; // T1: false
type T2 = IsNever<unknown>; // T2: false
type T3 = IsNever<never>; // T3: never (!!!)
type T4 = IsNever<any>; // T3: boolean (!!!)
```

However, you can *indirectly* test for `never` if you flip the condition:

```ts
type IsNever<T> = (T extends never ? true : false) extends true ? true : false;
type T1 = IsNever<{}>; // T1: false
type T2 = IsNever<unknown>; // T2: false
type T3 = IsNever<never>; // T3: true
type T4 = IsNever<any>; // T3: false
```

I found that if I further modify `Loaded` in the following way I can avoid the "excessively deep" error by escaping early when there's nothing to populate:

```ts
export declare type Loaded<T, L extends string = never> =
    // Test whether `L` is `never`...
    (L extends never ? true : false) extends true ?
        // `L` is `never`, so don't use a mapped type
        T :
        // `L` is something other than `never`, so use a mapped type
        T & {
            [K in keyof T]: K extends Prefix<L> ?
                LoadedLoadable<Defined<T[K]>, Loaded<ExtractType<Defined<T[K]>>, Suffix<L>>> :
                T[K];
        };
```

**Comment by itsame-luigi** [comment]
Work could further be reduced by limiting the keys of `T` in the mapped type to only those that match the prefix, since you don't need to overwrite unpopulated keys:

```ts
export declare type Loaded<T, L extends string = never> =
    // Test whether `L` is `never`...
    (L extends never ? true : false) extends true ?
        // `L` is `never`, so don't use a mapped type
        T :
        // `L` is something other than `never`, so use a mapped type
        T & {
            // pre-filter `K` to only the keys that match `Prefix<L>`
            [K in Extract<keyof T, Prefix<L>>]: 
                LoadedLoadable<NonNullable<T[K]>, Loaded<ExtractType<NonNullable<T[K]>>, Suffix<L>>>;
        };
```

**Comment by itsame-luigi** [comment]
Apparently you don't need to flip the condition to test for `never` if you use a non-distributive conditional:

```ts
type IsNever<T> = [T] extends [never] ? true : false;
```

You can also avoid the mapped type and recursion if no key of `T` matches `Prefix<L>`:

```ts
export declare type Loaded<T, L extends string = never> =
    // If `L` is `never`, don't use a mapped type
    [L] extends [never] ? T :
    // If `T` contains no properties matching `Prefix<L>`, don't use a mapped type
    // NOTE: negated condition to keep each branch inline since TS doesn't support type negation
    ([Prefix<K>] extends [keyof T] ? true : false) extends false ? T :
    // otherwise, intersect with a mapped type containing only properties matching the prefix
    T & {
        [K in Extract<keyof T, Prefix<L>>]:
            LoadedLoadable<NonNullable<T[K]>, Loaded<ExtractType<NonNullable<T[K]>>, Suffix<L>>>;
    };
```

**Comment by itsame-luigi** [comment]
I'm running into other issues with instantiation around `findOne` having to do with `FilterQuery<T>`. I'll continue to investigate and will possibly open a separate issue.

**Comment by itsame-luigi** [comment]
It seems the issue is primarily in `FilterQuery`, not `Loaded`. The query I was performing was something like this:

```ts
export class ParticipantRepository extends EntityRepository<Participant> {
  async get(session: Session, member: Member) {
    return await this.findOne({ session, member }); // errors here
  }
   ...
}
```

As a workaround, I was able to change the query to this instead:

```ts
export class ParticipantRepository extends EntityRepository<Participant> {
  async get(session: Session, member: Member) {
    return await this.findOne({ session: session.id, member: { user: member.user.id, provider: member.provider.id } });
  }
   ...
}
```

Apparently `FilterQuery` doesn't like my entity model.

**Comment by B4nan** [comment]
@itsame-luigi Thanks for the suggestions, but please first provide reproduction, I am not interested in fixing things I cannot reproduce. Entity definitions should be enough in this case, but don't oversimplify them. I can imagine the custom repository can play a role here too (otherwise would be very weird the existing ORM tests don't reproduce this already).

Seeing your "workaround", I guess your `Member` entity has composite key? That is quite important thing to mention, if it's like that.

Note that `Loaded<T, never>` works just fine and I can't see any problems with that. It worked like that in v4 too. I don't think simplyfing it would help much, there is no recursion when the second type arg is `never`.

And also note that stable v5 is out, so either test on that, or ideally with the latest dev version (so 5.0.1).

**Comment by itsame-luigi** [comment]
> @itsame-luigi Thanks for the suggestions, but please first provide reproduction, I am not interested in fixing things I cannot reproduce. Entity definitions should be enough in this case, but don't oversimplify them. I can imagine the custom repository can play a role here too (otherwise would be very weird the existing ORM tests don't reproduce this already).

I'll provide a repro as soon as I have time to dedicate to that specifically.

> Seeing your "workaround", I guess your `Member` entity has composite key? That is quite important thing to mention, if it's like that.

Yes, this is the same entity model I was using when I encountered #2647. I should also mention I'm using custom entity repositories and the `EntityRepositoryType` symbol, which appears to be part of the problem. Another part of the problem is that the `Session` and `Participant` entities have references to each other, causing a circularity in the type system.

> Note that `Loaded<T, never>` works just fine and I can't see any problems with that. It worked like that in v4 too. I don't think simplyfing it would help much, there is no recursion when the second type arg is `never`.

As I mentioned above, it turns out its not actually `Loaded` that was causing the problem, but `FilterQuery<T>`. I'll file a separate issue when I am able to isolate a repro. 

> And also note that stable v5 is out, so either test on that, or ideally with the latest dev version (so 5.0.1).

I switched to 5.0.1-dev.23 and the issue is still present. I've found a few different things that make the errors I'm seeing go away:
1. Removing the `declare [EntityRepositoryType]: ...` property from my entities.
2. Removing the circularity between `Session` and `Participant`.

(1) is frustrating but I can work around it via cast. (2) breaks my data model.

Its possible that `FilterQuery<T>` is running into some kind of circularity because `ObjectQuery<T>` doesn't filter out properties like `EntityRepositoryType`.

**Comment by B4nan** [comment]
> Its possible that FilterQuery<T> is running into some kind of circularity because ExpandObject<T> doesn't filter out properties like EntityRepositoryType.

If that would be the case, you can try redefining `ExpandObject` type to use this for keys: `K in keyof T as ExcludeFunctions<T, K>`.

It will strip functions and symbols properties like `EntityRepositoryType`. Tried it locally and it does not break anything in the current tests.

**Comment by itsame-luigi** [comment]
That does work, yes.

**Comment by itsame-luigi** [comment]
I filed #2742 for the issue with `ExpandObject<T>`, along with a repro. Fixing `ExpandObject<T>` as you mentioned above does address the infinite instantiation issue, though I could not generate a repro that produces that specific compile time error. The repro provided does produce an compile time error, however (and it was likely hidden behind the infinite instantiation error), and the fix does seem to address all three compiler errors.
