### ISSUE TITLE
Incorrect TypeScript type returned when querying with smart nested populate

### ISSUE THREAD

**Issue by dzcpy** [mikro-orm/mikro-orm#2653]
**Describe the bug**
I was trying to do a query with a smart nested populate, however in TypeScript, it returned incorrect types, those nested fields are actually populated but I can't access them because their types are uninitialized ones. `.$.` works correctly with TypeScript but those fields do not exist in the result.
![image](https://user-images.githubusercontent.com/203980/150243011-e765d145-9b3f-4d3a-846f-d60fd86c1422.png)

**Stack trace**
```
TypeError: Cannot read properties of undefined (reading 'name')
```

**To Reproduce**
1. Query with smart nested populate
2. Access nested fields

**Expected behavior**
Return results with correct types

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 17.1.0 |
| typescript | 4.5.4 |
| mikro-orm | 5.0.0-dev629 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
This is almost certainly entity definition problem. You can use the `$` accessor only if you use `Reference` wrapper, which you are not given the sceenshot you shared. But if TS allows you to use it, it means you define the type as `Reference` but forgot to use `wrappedReference: true` in the decorator. 

Closing as you haven't provided any actual details, screenshot is really not enough to reproduce anything.

**Comment by B4nan** [comment]
Either use the reference wrapper or not, you can't have both.
