### ISSUE TITLE
Using EntityManager in a Migration results in `Knex: Timeout acquiring connection. The pool is probably full.`

### ISSUE THREAD

**Issue by bvobart** [mikro-orm/mikro-orm#2670]
**Describe the bug**
Similar to [a previous issue](https://github.com/mikro-orm/mikro-orm/issues/1102) I'm trying to use the entity manager in a migration. More specifically, I want to use the entities I defined in TypeScript classes (and the EM's repositories of those entities) to interact with the DB during migrations similar to how my actual application interacts with the DB. Since I saw that `this.driver` has a `createEntityManager` method on it, I assumed this could be used to create an EM object based on the underlying connection to the database that is already initialised by the CLI when the migration is executed. So, I was under the impression that it is possible to write the following migration:

```ts
import { Migration } from '@mikro-orm/migrations';
import { ActivationCode } from '../src';

export class Migration20220124172023 extends Migration {
  async up(): Promise<void> {
    // TODO: set an expiration date on all activation codes that don't have one yet.

    const em = this.driver.createEntityManager(true);
    const activationCodeRepo = em.getRepository(ActivationCode);
    const codes = await activationCodeRepo.find({ expirationDate: undefined });
    codes.forEach(c => console.log(c.code));

    throw new Error('not yet well implemented'); // temporary until the migration does what I expect
  }

  async down(): Promise<void> {
    console.log('migration 20220124172023 down');
  }
}
```

However, similar to the linked issue, I get a timeout acquiring the connection because the pool (which is automatically set to `{ min: 1, max: 1 }`) is already full: 

**Stack trace**
```
DriverException: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at PostgreSqlExceptionConverter.convertException (/home/bart/energiebespaarders/building-blocks-entities/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
    at PostgreSqlExceptionConverter.convertException (/home/bart/energiebespaarders/building-blocks-entities/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:40:22)
    at PostgreSqlDriver.convertException (/home/bart/energiebespaarders/building-blocks-entities/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:202:54)
    at /home/bart/energiebespaarders/building-blocks-entities/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:206:24
    at async PostgreSqlDriver.find (/home/bart/energiebespaarders/building-blocks-entities/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:46:24)
    at async SqlEntityManager.find (/home/bart/energiebespaarders/building-blocks-entities/node_modules/@mikro-orm/core/EntityManager.js:92:25)

previous KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (/home/bart/energiebespaarders/building-blocks-entities/node_modules/knex/lib/client.js:348:26)
    at async PostgreSqlConnection.executeQuery (/home/bart/energiebespaarders/building-blocks-entities/node_modules/@mikro-orm/core/connections/Connection.js:56:25)
    at async PostgreSqlConnection.execute (/home/bart/energiebespaarders/building-blocks-entities/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:105:21)
    at async QueryBuilder.execute (/home/bart/energiebespaarders/building-blocks-entities/node_modules/@mikro-orm/knex/query/QueryBuilder.js:306:21)
    at async PostgreSqlDriver.find (/home/bart/energiebespaarders/building-blocks-entities/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:46:24)
    at async SqlEntityManager.find (/home/bart/energiebespaarders/building-blocks-entities/node_modules/@mikro-orm/core/EntityManager.js:92:25) {
  sql: 'select "e0".* from "activation_code" as "e0" where "e0"."expiration_date" is null',
  bindings: undefined
}
```

**To Reproduce**
1. Create a migration that uses an EntityManager and a repository instantiated with it, like in the code example above.
2. Try to run it against a database.

**Expected behavior**
I expect the migration to connect to the DB properly and print all the activation codes where `{ expirationDate: undefined }`. If it is not possible to use the EntityManager or its repositories in this way during a migration, I expect to see an error or warning that the migration may / will fail to connect, preferably with some (link to) guidance for alternative solutions.

**Additional context**
I am 100% sure that the database credentials I'm using are correct. I am also aware that @B4nan stated _"You should not use EM inside migrations, definitely not like this."_ on his comment on the issue I linked, but I could not find any further documentation on how an EM or its repositories _can_ be used in migrations. I am also curious to learn if and how the mentioned seeder package (which is now merged but I presume this is slated for v5?) could help with this (especially given that this doesn't purely add initial data, but rather modifies existing data).

**Versions**

| Dependency | Version |
| - | - |
| node | v16.13.1 |
| typescript | 4.5.4 |
| `@mikro-orm/core` | 4.5.10 |
| `@mikro-orm/postgresql` | 4.5.10 |

**Comment by B4nan** [comment]
> I am 100% sure that the database credentials I'm using are correct. I am also aware that @B4nan stated "You should not use EM inside migrations, definitely not like this." on his comment on the issue I linked, but I could not find any further documentation on how an EM or its repositories can be used in migrations.

Nothing changed, this is not something you should do. There is no documention how to do it, because it is not supported use case.

> (especially given that this doesn't purely add initial data, but rather modifies existing data).

You should just use raw queries then (`this.execute()`), or `this.driver.nativeUpdate()`.

**Comment by bvobart** [comment]
> You could try this if you really want:

Thanks, that worked!

> Nothing changed, this is not something you should do. There is no documention how to do it, because it is not supported use case.

May I ask why it is not a supported use case and not something I should do? One of the reasons for using an ORM is not having to write raw SQL anymore to programmatically interact with the database of my application. Instead, the idea is to use TypeScript entity and repository classes to interact with the database, backed by the entity manager. If that's the recommended way to interact with the database in my application logic, why would that be different in migration logic?

Don't get me wrong btw, I'm loving MikroORM and all of its features so far, it's really well built and simple to use, thanks a lot for creating and maintaining MikroORM, in your free time, no less! :blush: Just wanted to share my train of thought and hopefully help improve upon an already great library :)

**Comment by bvobart** [comment]
Hi @B4nan, your suggestion worked, but have you seen my follow-up comment? Would you mind answering the question for explanation, please? :blush:

**Comment by B4nan** [comment]
I already said why, class-transformer doesn't understand how MikroORM entities work. It doesn't understand what is a `Reference` or a `Collection`. It does not understand the internal entity state (what entity is actually loaded and what is just an entity reference representing only its PK).
