### ISSUE TITLE
Specifying config file for use by CLI

### ISSUE THREAD

**Issue by calbro7** [mikro-orm/mikro-orm#2671]
**Is your feature request related to a problem? Please describe.**
If I have multiple databases, and therefore multiple different configs, I'd like to be able to specify one to use when running a CLI command. For example, my project has its "normal" database, and then a separate database which gets used for running tests against, so that the normal database does not have its data changed. Therefore I have a mikro-orm.config.js file and a mikro-orm.test.config.js file. I'd like to be able to specify which config file the CLI commands should use

**Describe the solution you'd like**
An optional additional flag passed to all CLI commands. This could either be a literal filename (e.g. --config=mikro-orm.config.js), or what I think would be cleaner is to allow an array of named config options within a single mikro-orm.config.js file, [similar to TypeORM](https://github.com/typeorm/typeorm/blob/master/docs/using-ormconfig.md). Then we could do --configname=main or --configname=test

**Describe alternatives you've considered**
A rather hacky workaround where a custom script temporarily copies/renames files and then reverts them when the CLI commands are finished

**Comment by B4nan** [comment]
You can use `MIKRO_ORM_CLI` env var for that.

```sh
$ MIKRO_ORM_CLI=/foo/bar/... npx mikro-orm debug
```
