### ISSUE TITLE
Replace `faker` with `@faker-js/faker`

### ISSUE THREAD

**Issue by pantajoe** [mikro-orm/mikro-orm#2673]
**Is your feature request related to a problem? Please describe.**
It's not exactly related to a problem, but I did not know which template else to use. 😅  I believe, everyone who has upgraded to the amazing new v5 rc and is using dependabot (or another similar solution) might have stumbled upon the "new" 6.6.6 version of the library `faker`.
And since I'm heavily using the package `@mikro-orm/seeder` (which is amazing btw), I'm quite frustrated when seeing the `faker` library abandoned and dependabot issuing yet another update PR.

**Describe the solution you'd like**
Is there any chance, we could replace `faker` with [`@faker-js/faker`](https://github.com/faker-js/faker). It looks more promising and is not only maintained by one person, so I believe it's more stable?

**Comment by B4nan** [comment]
> I believe, everyone who has upgraded to the amazing new v5 rc and is using dependabot (or another similar solution) might have stumbled upon the "new" 6.6.6 version of the library faker.

Well, its a pinned dependency, nothing you should install yourself, I dont understand why should dependabot issue anything. You depend on `@mikro-orm/seeder`, not on faker.

**Comment by pantajoe** [comment]
Thanks for the quick reply!
Ah, my bad then. It just was inside my project's direct dependencies because I used faker before upgrading to v5 and using `@mikro-orm/seeder`. 
But I believe, `faker` is now kind of abandoned, so wouldn't it make sense to replace this library with another library being actively maintained?

**Comment by B4nan** [comment]
We depend on the library for just few months, so I hope you understand I am not really into replacing it right now. 

But its true that even the docs suggest using faker directly, so installing it sounds like the right thing to do (you should always install things you directly use in your codebase).

And it looks like your proposal is a fork of faker, so I guess it could be just a drop in replacement - if so, I guess we could switch.

cc @Langstra

**Comment by pantajoe** [comment]
I totally get that! It indeed seems like a fork (without having tested it as a replacement yet), so I'm hoping it could be a drop-in replacement. But if you do not plan to depend on it in the long-term and replacing it takes too much time, then I understand if you choose not to replace it.

**Comment by B4nan** [comment]
So now the seeder package reexports both `faker` instance and `Faker` class type, so no need to install anything else yourself.

```ts
import { Factory, Faker } from '@mikro-orm/seeder';
import { Author } from './entities/author.entity';

export class AuthorFactory extends Factory<Author> {
  model = Author;

  definition(faker: Faker): Partial<Author> {
    return {
      name: faker.person.findName(),
      email: faker.internet.email(),
      age: faker.random.number(18, 99)
    };
  }
}
```

**Comment by pantajoe** [comment]
Great, thanks a lot!

**Comment by RDeluxe** [comment]
I know the issue is closed, but it seems that the seeder package still uses and exports faker and not the new, and better, fork.
There are some issues with the old version of fakerjs (ie, getting geographic position which gives position on the circle and not inside the given radius, etc.).

Should we open a PR to replace fakerjs with [@faker-js/faker](https://github.com/faker-js/faker) ?
