### ISSUE TITLE
Attribute/column transformer support?

### ISSUE THREAD

**Issue by DanielRamosAcosta** [mikro-orm/mikro-orm#2678]
**Is your feature request related to a problem? Please describe.**
When implementing Hex Architecture, it's common practice to have wrappers for primitives (ids for example), so instead of having:

```ts
class User {
  userId: string
  userName: string
}
```

you would have something like

```ts
class User {
  userId: UserId
  userName: UserName
}
```

Right now I'm using the Entity Schema for defining the DDBB schema and having it decoupeled from my domain layer. The problem is that I cannot use nested classes that map into some domain model.

**Describe the solution you'd like**
A way to solve this, is to implement something like TypeORM's `transformer` per column feature.

> transformer: `ValueTransformer|ValueTransformer[]` - Specifies a value transformer (or array of value transformers) that is to be used to (un)marshal this column when reading or writing to the database. In case of an array, the value transformers will be applied in the natural order from entityValue to databaseValue, and in reverse order from databaseValue to entityValue.

Here are the [original docs](https://typeorm.io/#/decorator-reference)

Also, [here](https://github.com/CodelyTV/typescript-ddd-course/blob/main/24-postgresql-typeorm-persistence/2-postgres-repository-tests/src/Contexts/Mooc/Courses/infrastructure/persistence/typeorm/CourseEntity.ts#L8) you can find a real usage of the transformer feature.

**Comment by B4nan** [comment]
https://mikro-orm.io/docs/custom-types/
