### ISSUE TITLE
Migration names include .js or .ts file extension causing completed migrations to try to re-run

### ISSUE THREAD

**Issue by gianlazz** [mikro-orm/mikro-orm#2684]
**Describe the bug**

I'm using the nestjs module and have implemented the same pattern from [the nestjs example repo](https://github.com/mikro-orm/nestjs-realworld-example-app/blob/8a409237f6536a06759bd2218d519b2e513cbf83/src/app.module.ts#L24-L30) to provide the functionality to run migrations on startup. I have one initial migration.

When I run `npm run start` the initial time it builds and runs the transpiled js code. The service starts up and runs the migration successfully.

My `mikro_orm_migrations` table then shows the initial migration entered.
| id | name | executed_at |
| - | - | - |
| 1 | Migration20220124234318.js | 2022-01-29 01:38:37.302999+00 |

The issue is that a fresh nestjs boilerplate project will run the `test:e2e` script as ts files. So when trying to start up the app.module in the root `app.e2e-spec.ts` it tries again to run the migrations on startup, this time checking if there is any `Migration20220124234318.ts` entries in the `mikro_orm_migrations` table, which there aren't as the last time it was run from the transpiled js code not via the .ts files directly. So it then tries to run the first migration again to make a second time; this time with with a name ending in `.ts`.

If it were to work it would result in the following...

| id | name | executed_at |
| - | - | - |
| 1 | Migration20220124234318.js | 2022-01-29 01:38:37.302999+00 |
| 2 | Migration20220124234318.ts | 2022-01-29 01:40:00.302999+00 |

However, this will never work as the functionality of the transpiled `Migration20220124234318.js` vs the typescript `Migration20220124234318.ts` is exactly the same. So it results in a `TableExistsException`.

**Stack trace**
```
# first run with "npm run start" is successful
== Migration20220124234318: migrating =======
== Migration20220124234318: migrated (0.053s)

# then running "npm run test:e2e" fails
== Migration20220124234318: migrating =======

    TableExistsException: create table "password_reset" ("id" serial primary key, "pin" varchar(255) not null); - relation "password_reset" already exists

      at PostgreSqlExceptionConverter.convertException (../node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:38:24)
      at PostgreSqlDriver.convertException (../node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:202:54)
      at ../node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:206:24
      at Function.runSerial (../node_modules/@mikro-orm/core/utils/Utils.js:490:22)
      at ../node_modules/@mikro-orm/migrations/MigrationRunner.js:23:17
      at PostgreSqlConnection.transactional (../node_modules/@mikro-orm/knex/AbstractSqlConnection.js:53:25)
      at MigrationRunner.run (../node_modules/@mikro-orm/migrations/MigrationRunner.js:20:13)
      previous error: create table "password_reset" ("id" serial primary key, "pin" varchar(255) not null); - relation "password_reset" already exists
      at Parser.parseErrorMessage (../node_modules/pg-protocol/src/parser.ts:369:69)
      at Parser.handlePacket (../node_modules/pg-protocol/src/parser.ts:188:21)
      at Parser.parse (../node_modules/pg-protocol/src/parser.ts:103:30)
      at Socket.<anonymous> (../node_modules/pg-protocol/src/index.ts:7:48)
```

**To Reproduce**
1. create an initial migration
2. configure your project to run migrations on startup via `orm.getMigrator().up()`
3. transpile your ts project into js & run it
4. then run your project from the ts source with `ts-node`

**Expected behavior**

I'd expect entries to the `mikro_orm_migrations` table to omit the file extension from the entries to the `name` column. The file `.js` or `.ts` file extension difference should not be a defining factor in deciding if a migration has already been run. This would look like the following example table without a file extension in the `name` column entry.

| id | name | executed_at |
| - | - | - |
| 1 | Migration20220124234318 | 2022-01-29 01:38:37.302999+00 |

**Additional context**

BTW, I'm a long-time TypeORM user and in the process of migrating an existing project over. I'm also coming from a .NET background with experience with entity framework so your efforts here are warmly welcomed here, on my end.

**Versions**

| Dependency | Version |
| - | - |
| node | 14 |
| typescript | 4.3.5 |
| mikro-orm | 4.5.10 |
| your-driver | N/A |

**Comment by B4nan** [comment]
Fixed in v5
