### ISSUE TITLE
Migration missing pivot table creation for ManyToMany

### ISSUE THREAD

**Issue by SpencerKaiser** [mikro-orm/mikro-orm#2693]
**Describe the bug**
I have two tables that I just added `ManyToMany` relations to and for some reason the migration created doesn't have anything for the pivot table... not sure if this is a bug or if I'm doing something dumb 😬 

**Stack trace**
N/A

**To Reproduce**
``` typescript

// ProviderBusiness.ts
@ManyToMany(() => Service, 'providers', { owner: true })
services = new Collection<Service>(this);

// Service.ts
@ManyToMany(() => ProviderBusiness, (providerBusiness) => providerBusiness.services)
providers = new Collection<ProviderBusiness>(this);
```

After making those changes and running `yarn mikro-orm migration:create` nothing gets generated for the pivot table.

**Expected behavior**
The new migration contains commands to create the pivot table

**Additional context**
I've tried practically every variation of syntax and read through the docs pretty thoroughly, so not sure what the issue is. I also checked to make sure the files being detected were showing up correctly. My only other path forward would be to try [this](https://github.com/mikro-orm/mikro-orm/issues/407).

**Versions**
| Dependency | Version |
| - | - |
| node | v16.13.0 |
| typescript | 4.4.3 |
| mikro-orm | 4.5.9 |
| @mikro-orm/postgresql | 4.5.9 |

**Comment by B4nan** [comment]
Your property definition is ok, but this is not enough to reproduce anything. There are dozens of tests that test exactly this, try to prepare full reproduction.

**Comment by SpencerKaiser** [comment]
Ugh I was worried about that 😅 any tips for getting a repro setup quickly?

**Comment by B4nan** [comment]
Start with what you have, and simplify it as much as you can while stil preserving the failure. 

But I kinda dont expect you to be able to provide failing repro, as I really dont believe it would not work :D I mean, if something like that would be true, I am sure there would be many people already reporting this, v4.5.9 is 5 months old already. 

Obviously double check the table is not already created, if its a dev database, try wiping it. Be sure to wipe dist, reinstall and rebuild things, compile TS, .... 

I guess you dont use any specific schema? 

Also be sure to upgrade to latest first, just for the sake of it. At this point I would even say upgrade to v5 rc (as schema diffing has been completely rewritten there).

**Comment by SpencerKaiser** [comment]
I actually think I managed to get a repo setup (just copied my codebase and just deleted a ton lol). [Check it out](https://github.com/SpencerKaiser/Repro) and look at the migration it created.

You **should** only need to run `yarn` and then duplicate `.env.sample` and rename as `.env.local`. Lemme know how it goes!

**Comment by B4nan** [comment]
I see we don't have the same idea of how _minimal_ repro should look like :P

**Comment by SpencerKaiser** [comment]
Haha well we made a few modifications and I thought it would be relevant to include them. I can try to pair it down more.

**Comment by B4nan** [comment]
You are supposed to remove all of them that are not related - usually you can find what you did wrong by just doing this. This is really over complicated, just opened the ORM config and I have no idea what I am reading there :D

**Comment by SpencerKaiser** [comment]
Alright I got rid of a bunch of additional stuff and the issue is still happening... I'll keep looking for more to trim, but see if that's better

**Comment by B4nan** [comment]
I guess I know what's wrong, you are using mongo naming strategy that does not have the pivot table name method.

**Comment by SpencerKaiser** [comment]
Yup, there it is! I would NEVER have figured that out. @johnkahn (I'll dm him) - what was your rationale for the below?

``` typescript
import { MongoNamingStrategy } from "@mikro-orm/core";

// ...

namingStrategy: MongoNamingStrategy, // Camel case property and table names
```

**Comment by B4nan** [comment]
You might be better of using `EntityCaseNamingStrategy`. 

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/naming-strategy/EntityCaseNamingStrategy.ts

I'll implement that method for v5 just for the added safety (although this is kind of a misusage). No plans to backport anything at this stage as v5 is almost ready.

**Comment by SpencerKaiser** [comment]
>although this is kind of a misusage

Call it what it is... it's a misusage 🤣

So if I make that swap, will there be any other things that might change in the naming and create a weird experience for devs? And thank you so much for the help; this has consumed a ton of my day 🙄

**Comment by SpencerKaiser** [comment]
Also good call on the other stuff you mentioned; sounds like a good approach!

**Comment by B4nan** [comment]
Compare the code, they might do almost the same thing, you could as well just extend the mongo strategy and implement that missing method. 

```ts
class MyNS extends MongoNamingStrategy {
    joinTableName(sourceEntity: string, targetEntity: string, propertyName: string): string {
    return this.classToTableName(sourceEntity) + '_' + this.propertyToColumnName(propertyName);
  }
}

**Comment by SpencerKaiser** [comment]
That worked flawlessly, you're awesome!!! 🍻

Thank you so much for the help and sorry committing cardinal sin by mixing Mongo and Postgres 🤣

**Comment by johnkahn** [comment]
Yeah, I think it was the quickest way to get camel case in Postgres, can't tell you why I didn't just use `EntityCaseNamingStrategy`. 🤦  It was an old decision that kept coming over into new projects from a template I made a long time ago.

@SpencerKaiser I would suggest looking into removing that. Hopefully it'll do a migration to switch from `camelCase` to `snake_case`. But a quick solution would be to just switch to `EntityCaseNamingStrategy` for the short term, if that's got that method defined.

**Comment by B4nan** [comment]
> Hopefully it'll do a migration to switch from camelCase to snake_case.

You could try, but the chances are quite high this will break things - detecting renamed columns can be hard if you want to rename all of them. But you can always adjust the migration manually if it fails to detect it.

**Comment by SpencerKaiser** [comment]
Yea it most certainly breaks things; it looks like it's a migration to half-way recreate the entire thing.

I'm still early on in this project... think the right play is to just nuke the DB and the migrations and make the hard switch to `EntityCaseNamingStrategy`?

**Comment by B4nan** [comment]
Btw go for v5, schema diffing is completely rewritten. It might work much better there even for such complicated use case, so definitely worth trying.

**Comment by SpencerKaiser** [comment]
What's the right yarn/npm version to use for v5? I tried yesterday but couldn't seem to find the right one and it looks like the releases for the repo don't include any v5 🤔

**Comment by B4nan** [comment]
`yarn add @mikro-orm/core@rc` or specify the version explicitly if you want latest dev version (you will need to pin it, as ranges would install the RC instead of latest dev, because... NPM is dumb and ignores the dist tags, and `rc` is technically > than `dev`, so its "later version") - so `yarn add @mikro-orm/core@5.0.0-dev.692`.

(you can see latest version in the versions tab here https://www.npmjs.com/package/@mikro-orm/core)

**Comment by SpencerKaiser** [comment]
Oh man, I tried and it broke everything for my configuration/customization 😢 I'm excited to try it out in the future, but I don't think I have the bandwidth right now to refactor our whole DB setup beyond the quick nuke-and-recreate for migrations. I really appreciate the help/suggestions though!!! And thanks again for the help figuring out this super obscure problem 😅
