### ISSUE TITLE
`tableName` Configuration not being used in Single Table Inheritance Configuration.

### ISSUE THREAD

**Issue by RoyLee** [mikro-orm/mikro-orm#2695]
**Describe the bug**
`tableName` is not respected when using single table inheritance.

**To Reproduce**
1. Create single table inheritance:

Fruit.ts
```
@Entity({
  discriminatorColumn: 'type',
  discriminatorValue: 'fruit',
  tableName: 'fruits',
})
export class Fruit extends BaseEntity {
}
```

Apple.ts
```
@Entity({
  discriminatorValue: 'apple',
})
export class Apple extends Fruit {
}
```

2. Start server so the tables are created.

3. Use mongosh or another mongodb shell to see the tables/collections. Notice that the name of the table is `fruit` and not the explicitly defined `fruits`.

**Expected behavior**
`tableName` to be the name in the database.

**Versions**
| Dependency | Version |
| node | v16.13.1 |
| typescript | v4.3.5 |
| mikro-orm | v4.5.9 |
| mongodb | v4.5.9 |

**Comment by B4nan** [comment]
already fixed, upgrade to latest
