### ISSUE TITLE
Migration create command messes up when converting embeddable to table

### ISSUE THREAD

**Issue by kristijanhusak** [mikro-orm/mikro-orm#2704]
**Describe the bug**
Converting embeddable to a separate table with ManyToOne, and also converting a string field to a ManyToOne relationship causes `migration:create` to constantly create same migration. You can never get to a "schema is up to date" state.

**To Reproduce**
1. Clone this project: https://github.com/kristijanhusak/mikroorm-migration-issue
2. `docker-compose up -d`
3. `docker-compose exec api npx mikro-orm migration:up`
4. `docker-compose exec api npx mikro-orm migration:create`
5. `docker-compose exec api npx mikro-orm migration:up`
6. `docker-compose exec api npx mikro-orm migration:create`
7. See that all migrations created are same and it never gets to the end

**Expected behavior**
Expected to get to an "up to date" schema.

**Additional context**
Note that "nuking" the migrations and creating a single one from empty database solves the issue. It seems that converting from embeddable/uuid to ManyToOne leaves some state in db that messes up the migration generator.

You can check the 1st commit where I added the embeddable for image, and uuid for product on customer, and in 2nd I converted it to ManyToOne for both.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.13 |
| typescript | 4.3.5 |
| mikro-orm | 4.5.10 |
| your-driver | postgresql, 4.5.10 |

**Comment by B4nan** [comment]
Please try with v5, there wont be any changes to v4, and v5 has rewritten schema diffing.

**Comment by kristijanhusak** [comment]
v5 fixes it, thanks. Do you know when I could expect v5 to become a regular release? I see that there's RC-2 at this point. Just trying to figure out if it's worth it to do the update now or to wait a bit.
