### ISSUE TITLE
Docs scrolling issue in Chrome (Mac M1)

### ISSUE THREAD

**Issue by andrew-sol** [mikro-orm/mikro-orm#2711]
There's some scrolling issue with the docs website in Chrome, Mac M1. Whenever I try to scroll the page down it jumps back to the top. I tried in incognito and with all extensions disabled. Tried clearing cache and hard reloading.

The bug is present on any docs page. For example this one:
https://mikro-orm.io/docs/installation/

It does not happen in Safari though. Also works fine in Chome if I disable JavaScript.

Chrome version 98.0.4758.80 (Official Build) (arm64)

**Comment by B4nan** [comment]
I am on M1 mac too, I don't see any problem, even after upgrading to chrome 98 🤷 .

**Comment by andrew-sol** [comment]
You were very helpful, thanks. Ha-ha :)

Okay, it still means that there is some bullshit in your scripts, cuz my browser works well with any other page on the internet. And I won't be debugging your minified code to find out what's going on there.

When I paste this script into the console the problem goes away:
```js
window.addEventListener('scroll', function(event) {
    event.stopImmediatePropagation();
}, true);
```

I made this script to run automatically on every page on your docs website and now I'm happy.

**Comment by B4nan** [comment]
Some bullshit in my scripts you say? Interesting you are the only person having this problem.

**Comment by evantrimboli** [comment]
I'm also having the issue on Chrome 97.x on Windows. Doesn't occur on Firefox. It seems to be something in the docs scaffolding.

**Comment by andrew-sol** [comment]
Sorry, I didn't want to offend you in any way. I appreciate your work. Just wanted to point out that something is messing up with the scroll there.

**Comment by andrew-sol** [comment]
Can confirm that the issue has gone btw.

I think it was related to this one facebook/docusaurus#6587

**Comment by pepakriz** [comment]
I was facing the same issue on Intel (so not related to M1) and now everything is OK.

**Comment by B4nan** [comment]
I did downgrade to beta 14 yesterday, not really because of this, more like because of the [new API docs](https://mikro-orm.io/api/next/) that are not yet compatible with beta 15.
