### ISSUE TITLE
Configuration validation not taking `entitiesTs` into account

### ISSUE THREAD

**Issue by saengowp** [mikro-orm/mikro-orm#2714]
**Describe the bug**

During configuration validation process (see [code](https://github.com/mikro-orm/mikro-orm/blob/c3f672fdc362ce50bc27919dd3498d49112f551d/packages/core/src/utils/Configuration.ts#L301-L317)), If I were to configure `entitiesTs` but lefted out `entities`, then the configuration validation would fail. Adding a non-sense entry to `entities` array fix the issue.

**Stack trace**
```
No stacktrace
```

**To Reproduce**

1. Using normal node environment, install mikro-orm cli and use following configurations:

#### `mikro-orm.config.ts`

```typescript
module.exports = {
    type: 'postgresql',
    //entities: ['./src/entities'],
    entitiesTs: ['./src/entities'],
    dbName: 'postgres',
};
```

2. Run mikro-orm CLI Command using ts-node

`MIKRO_ORM_CLI_USE_TS_NODE=true MIKRO_ORM_CLI=mikro-orm.config.ts ts-node $(which mikro-orm) debug`

**Expected behavior**

The command exit without error.

**Actual Behaviour**

Configuration validation failed.

```
Current MikroORM CLI configuration
 - dependencies:
   - mikro-orm 4.5.10
   - node 16.13.1
 - package.json not found
 - searched config paths:
   - /home/pipat/Workspace/sec2_ChocoTech/apps/doji-backend/mikro-orm.config.ts (found)
   - /home/pipat/Workspace/sec2_ChocoTech/apps/doji-backend/mikro-orm.config.js (not found)
- configuration not found (No entities found, please use `entities` option)
```

**Additional context**

When the config was changed to 

```typescript
module.exports = {
    type: 'postgresql',
    entities: ['./src/entities'],
    entitiesTs: ['./src/entities'],
    dbName: 'postgres',
};
```

The command output became:

```
Current MikroORM CLI configuration
 - dependencies:
   - mikro-orm 4.5.10
   - node 16.13.1
 - package.json not found
 - searched config paths:
   - /home/pipat/Workspace/sec2_ChocoTech/apps/doji-backend/mikro-orm.config.ts (found)
   - /home/pipat/Workspace/sec2_ChocoTech/apps/doji-backend/mikro-orm.config.js (not found)
 - configuration found
 - will use `entities` array (contains 0 references and 1 paths)
   - /home/pipat/Workspace/sec2_ChocoTech/apps/doji-backend/src/entities (found)
 - could use `entitiesTs` array (contains 0 references and 1 paths)
   - /home/pipat/Workspace/sec2_ChocoTech/apps/doji-backend/src/entities (found)
```

Also, `mikro-orm schema:update --run` works as expected after the change.

Probable cause is missing check in [this line](https://github.com/mikro-orm/mikro-orm/blob/c3f672fdc362ce50bc27919dd3498d49112f551d/packages/core/src/utils/Configuration.ts#L314)

**Versions**

| Dependency | Version |
| - | - |
| node | 16.13.1 |
| typescript | v9.1.1 |
| mikro-orm | 4.5.10 |

**Comment by B4nan** [comment]
Well, `entities` option is required, this is correct behaviour. You either have only `entities` (in case you use entity references) or both `entities` and `entitiesTs` (for folder based discovery).
