### ISSUE TITLE
MikroORM website bug: v4.5 api docs "page not found"

### ISSUE THREAD

**Issue by rmuchall** [mikro-orm/mikro-orm#2718]
**Describe the bug**

When navigating to the v4.5 API docs the website displays the following error message:
"Page Not Found"

**To Reproduce**
1. Navigate to the following URL:
https://mikro-orm.io/api/4.5/

**Expected behavior**
The older v4.5 API docs should be displayed.

![2022-02-07_085811](https://user-images.githubusercontent.com/9222511/152757011-88d7da9f-5f00-4878-bf11-02ae5963c24d.png)

**Comment by B4nan** [comment]
There is some bug in the docusaurus typedoc plugin, the page https://mikro-orm.io/api/4.5 works fine if you open it in anonymous window btw.

Reported here: https://github.com/milesj/docusaurus-plugin-typedoc-api/issues/22

**Comment by rmuchall** [comment]
Thanks! :)
Congrats on the v5 release. Amazing work.

**Comment by B4nan** [comment]
Should be fixed for now.
