### ISSUE TITLE
docs: link to the v4 to v5 upgrade

### ISSUE THREAD

**Issue by Langstra** [mikro-orm/mikro-orm#2719]
On the documentation website I could not find a link to the v4-v5 documentation. Using the search functionality I could find it very easily, but there is no menu item I believe (at least I could not find it, which could be a limitation of me).

My suggestion would be to add a header to the side menu bar with 'Upgrading/Updating' and then there add urls to the different update guides.

**Comment by B4nan** [comment]
It's in the footer, but agreed we could have it linked from some more visible place, especially now when its fresh. We can have a sidebar link for sure.
