### ISSUE TITLE
Allow orm as an argument in @UseRequestContext()

### ISSUE THREAD

**Issue by Lioness100** [mikro-orm/mikro-orm#2721]
**Is your feature request related to a problem? Please describe.**
I use this decorator in many different places for many different classes, and find it a bit extreme to attach `orm` to every single one. Instead, I'd love it if you could optionally pass in `orm` as an argument to @UseRequestContext() (which is already a decorator factory, so not a breaking change). This way, someone can use it without having to add any properties to the class.

Personally, I'd create my own decorator that just looks like this:

```ts
export const UseRequestContext = OriginalUseRequestContext.bind(orm);
```

This way the decorator can always access the context it needs and I wouldn't need to do anything extra.

**Describe the solution you'd like**
I'd like `UseRequestContext`'s parameters to be typed as `(orm?: MikroORM)` and the decorator to use `orm ?? this.orm` instead of just `this.orm` for all related operations. I didn't submit my own PR because I'm clueless with tests, sorry 😭

**Describe alternatives you've considered**
Adding the `orm` property to every class. It works, but is kind of inconvenient :(

**Comment by B4nan** [comment]
Where would you get the ORM instance? The decorators are evaluated on require time.

**Comment by Lioness100** [comment]
If someone, for example, exported a `DI` object from their main file that included `orm`, would they not be able to import that and use `@UseRequestContext(DI.orm)`?

**Comment by B4nan** [comment]
Nope, as I said, the decorator gets executed on require time. Your `DI.orm` would be undefined by then, as no async calls would be executed.

**Comment by Lioness100** [comment]
I like that idea. For your previous reply, I tried to reproduce it in [replit](https://replit.com/@JChickSMM/SquigglyPotableSourcecode#test.ts) but it worked as intended. Am I setting it up wrong? At this point I'm just kinda curious haha

**Comment by B4nan** [comment]
Well, with ESM and top level await it seems to work. I doubt it would work this way with CJS, but I might be wrong. I'll allow to pass the instance directly too.

**Comment by Lioness100** [comment]
Thank you so much for your quick reply and implementation!! 🤩
