### ISSUE TITLE
Getters are required property for `em.create`

### ISSUE THREAD

**Issue by oznakn** [mikro-orm/mikro-orm#2722]
**Describe the bug**
With v5, `em.create` now respects the required properties. However, these required properties also include `getters`.

**To Reproduce**
Create a model with with definition below:
```ts
@Entity()
export class Cat {
    @PrimaryKey()
    id: string;

    @Property()
    name: string;

    @Property({ persist: false })
    get lowerName() {
        return this.name.toLowerCase();
    }
}
```

If you run try to execute this code with TypeScript, TypeScript will say `lowerName` is a required property.
```ts
const orm = MikroORM.init({ ... });
orm.em.create(Cat, {
    name: 'TestCat',
});
```

**Expected behavior**
Getters should be excluded while creating a new entity with `em.create`. 

**Additional context**
We can overcome this issue by using the new `OptionalProps` property. 

**Versions**

| Dependency | Version |
| - | - |
| node | 16.10 |
| typescript | 4.5 |
| mikro-orm | 5.0.0 |
| your-driver | sqlite (5.0.0) |

**Comment by B4nan** [comment]
Getter is still a property, there is no way to distinguish it from a "normal" property. You need to use the `OptionalProps` symbol.

**Comment by oznakn** [comment]
Thank you for your answer and work on v5.

I've used a way to exclude getter properties in one of my old personal projects using [this](https://stackoverflow.com/a/52473108/4355624) StackOverflow answer.

```ts
type IfEquals<X, Y, A = X, B=never> =
  (<T>()=> T extends X ? 1 : 2) extends
  (<T>()=> T extends Y ? 1 : 2) ? A : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<{ [Q in P]: T[P] }, { -readonly [Q in P]: T[P] }, P>
}[keyof T];

type RequiredKeys<T> = Pick<T, WritableKeys<T>>;
```
This method is used for excluding read-only keys, but it also excludes getter properties (if setters do not exist).

I know it also excludes read-only keys, which may be something you don't want; however, I just wanted to let you know.

Thanks again.

**Comment by B4nan** [comment]
Interesting, didn't know about that, will see if I can integrate.
