### ISSUE TITLE
New<T> strip nullability information from entity properties

### ISSUE THREAD

**Issue by BennoDev** [mikro-orm/mikro-orm#2727]
**Describe the bug**

The `New` type that gets returned from `.create()` methods does some funky things. It seems to strip nullability from properties.

**Stack trace**

No stack trace, as it's a type issue.

**To Reproduce**

Reproducing this is very simple using just a class and the `New` type.
 
 ```ts
class MyEntity {
  @Property({ nullable: true })
  nullableProperty: null | string;
}

// Type `null` is not assignable to `string`
const myNewEntityInstance: New<MyEntity> = {
  nullableProperty: null,
};
 ```
 
I know we would never instantiate a `New<MyEntity>` like above, but whether we do it via a create call or manually makes no difference for the type information.

**Expected behavior**

It should not modify the entity's type information. The actual type result from a `.create()` call is now potentially incorrect.
In the above example `null` is an allowed value for the `MyEntity` class.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.13.1 |
| typescript | 4.5.5 |
| mikro-orm | 5.0.0 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
Maybe we should drop the `New` type (we can keep it for BC and just return `T` from `em.create()`).

**Comment by BennoDev** [comment]
That would indeed fix this, and would mean that upgrading to v5 is easier, no changes should be necessary then for `.create()` methods
