### ISSUE TITLE
Version check  error running migrations if using Yarn PnP in strict mode

### ISSUE THREAD

**Issue by joekrill** [mikro-orm/mikro-orm#2732]
**Describe the bug**

When using Yarn PnP, the new v5 version check ([`ConfigurationLoader.checkPackageVersion`](https://github.com/mikro-orm/mikro-orm/blob/cf702195e2dd0dce4d66da26f1d349dddf05b007/packages/core/src/utils/ConfigurationLoader.ts#L222)) throws an error when optional packages are installed (i.e. `@mikro-orm/cli`, `@mikro-orm/reflection`). This is because Yarn PnP requires that dependencies be explicit, and in these cases `@mikro-orm/core` does not have explicit dependencies on these packages, but still tries to access them, and it's attempt at determining their version results in `unknown`.

**Stack trace**

```
/var/app/.yarn/__virtual__/@mikro-orm-core-virtual-768cdd40e0/0/cache/@mikro-orm-core-npm-5.0.0-18c9cf61e1-c6c76b098c.zip/node_modules/@mikro-orm/core/utils/ConfigurationLoader.js:219
                throw new Error(`Bad ${colors_1.colors.cyan(ormPackage)} version ${colors_1.colors.yellow('' + version)}.\n` +
                      ^
Error: Bad @mikro-orm/reflection version undefined.
All official @mikro-orm/* packages need to have the exact same version as @mikro-orm/core (5.0.0).
Only exceptions are packages that don't live in the 'mikro-orm' repository: nestjs, sql-highlighter, mongo-highlighter.
Maybe you want to check, or regenerate your yarn.lock or package-lock.json file?
    at Function.checkPackageVersion (/var/app/.yarn/__virtual__/@mikro-orm-core-virtual-768cdd40e0/0/cache/@mikro-orm-core-npm-5.0.0-18c9cf61e1-c6c76b098c.zip/node_modules/@mikro-orm/core/utils/ConfigurationLoader.js:219:23)
    at async Function.configure (/var/app/.yarn/__virtual__/@mikro-orm-cli-virtual-37d47398b2/0/cache/@mikro-orm-cli-npm-5.0.0-dc706e76ce-f6baeff1b8.zip/node_modules/@mikro-orm/cli/CLIConfigurator.js:24:9)
    at async /var/app/.yarn/__virtual__/@mikro-orm-cli-virtual-37d47398b2/0/cache/@mikro-orm-cli-npm-5.0.0-dc706e76ce-f6baeff1b8.zip/node_modules/@mikro-orm/cli/cli.js:13:19
```

**To Reproduce**

1. Create a project using Yarn v2+ (Berry) as the package manager with PnP enabled using strict mode
2. Install MikroORM dependencies, including `@mikro-orm/cli` and/or `@mikro-orm/reflection`.
3. Run a CLI command. 

**Expected behavior**

Migrations should run as normal. 

**Additional context**

There are two possible workarounds currently:

1. Set the `MIKRO_ORM_ALLOW_VERSION_MISMATCH` environment variable, bypassing the check all-together.
2. Use `.yarnrc.yml` to tell Yarn about the incorrect dependencies
```yml
packageExtensions:
  "@mikro-orm/core@*":
    dependencies:
      "@mikro-orm/reflection": "*"
      "@mikro-orm/cli": "*"
```

I think maybe the "correct" fix would be to add `@mikro-orm/reflection` and `@mikro-orm/cli` as optional peerDependencies to `@mikro-orm/core` (in the `package.json`)? Or add them to the hard-coded `exceptions` Set in the `checkPackageVersion` function.  But that also means any future `@mikro-orm/`-prefixed packages will need to be handled this way. 

I can create a PR, but I'm not sure what the preferred approach would be here, because it's not entirely clear to me what the underlying reason for implementing this check is. There's a comment in the ConfigurationLoader -- `// inspired by https://github.com/facebook/mikro-orm/pull/3386` -- but that repo appears to be private so I'm unable to see that PR and any context related to it.

Neither of those 2 approaches I suggested really feels correct: the first feels like more of a hack because these aren't _truly_ peer dependencies; while the second requires specifying all possible dependencies in a rather obscure way. A third approach might be to limit the packages whose versions are checked to those that are listed as dependencies, devDependencies, or peerDependencies in the `@mikro-orm/core` package.

Also to consider: perhaps this shouldn't result in an error at all, but instead just output a warning? 

**Versions**

| Dependency | Version |
| - | - |
| node | 16.10 |
| typescript | ? |
| mikro-orm | 5.0.0 |
| @mikro-orm/postgresql | 5.0.0 |

**Comment by B4nan** [comment]
We can just skip packages where we can't detect the version, although this quite sucks, we should definitely check this for the CLI package, that is the number one most common use case where people do this mistake as it is often in dev deps unlike all the other ORM packages. So if making those peer deps of core package helps, we should do it too. 

The check needs to stay, why? Because it protects you from very hard to spot and very random issues, as you can end up with multiple `core` packages installed. Having that, you end up with malfunctioning `instanceof` checks, broken global state (decorator metadata), and god knows what more. And I will rather have it as an error (that can be skipped via env var) than a warning people can just ignore (and file more issues with weird things that are impossible to debug without full repro, I've seen too many of those).

**Comment by B4nan** [comment]
Can you try using `Utils.requireFrom()` instead to load the versions? We use that in the CLI debug command to check versions of TS, which is also not a peer dependency.

**Comment by B4nan** [comment]
> but that repo appears to be private so I'm unable to see that PR and any context related to it.

lol, the link is wrong, it should be facebook/docusaurus, how did i manage to change that? :D 

Btw I failed to reproduce this, using latest yarn 3 with this config:

```
yarnPath: .yarn/releases/yarn-3.1.1.cjs
pnpMode: "strict"
```

(but based on docs strict mode is enabled by default anyway)

Tried on the https://github.com/mikro-orm/nestjs-realworld-example-app repo.

**Comment by joekrill** [comment]
@B4nan Hmmm, interesting...  It looks like it may be specific to using Yarn Workspaces, though I can't see why that should matter. I put a quick repo together here: https://github.com/joekrill/mikroorm-yarn-berry-example

You can run `yarn run mikroorm-test` from the root to see the error. 

To see the workaround, uncomment the commented out lines in `.yarnrc.yml`, run `yarn`, and try again.
