### ISSUE TITLE
Type issue with populate

### ISSUE THREAD

**Issue by Jasenkoo** [mikro-orm/mikro-orm#2733]
**Describe the bug**
There seems to be some kind of an issue with type inheritance.

**Stack trace**
```
TS2322: Type 'string[]' is not assignable to type 'boolean | readonly never[]'.  
 Type 'string[]' is not assignable to type 'readonly never[]'.  
   Type 'string' is not assignable to type 'never'.
```

**To Reproduce**

I have the following code:

```ts
import { EntityRepository } from '@mikro-orm/postgresql';

export class DummyRepository extends EntityRepository<Dummy> {

    public async getByNameAndUuid(name: string, uuid: string): Promise<Dummy> {
        const populate = ['attributes'];
        // This one will report the error I posted above
        return this.findOne({ name , uuid }, { populate });
        // But if I add it like this, then it is working normally
        return this.findOne({ name , uuid }, { populate: ['attributes'] });
    }
}
```

As you can see, both have the same type, when using it like in the first line, there is an error, but on the second, it works fine.
Obviously, this is a demo code, since I can't show the full code, but in my project, populate is extracted in the method that populating based on a few conditions, so I can't pass it directly.

For now, the workaround I am using:

```ts
const populate = ['attributes'] as never[];
```

I hope this will be sorted out.

**Expected behavior**
It should be the same with both ways

**Versions**

| Dependency | Version |
| - | - |
| node | 14.17.6 |
| typescript | 4.5.5 |
| mikro-orm | 5.0.0 |
| your-driver | postgresql |

**Comment by pepakriz** [comment]
Try to use `const populate = ['attributes'] as const;` instead of `const populate = ['attributes'];`

**Comment by MrHIDEn** [comment]
Version 1

```typescript
const populate  = ['user'] as const;
const options: FindOptions<UserRate> = {
        populate: populate,
}
```

That doesn't work ever.
```
TS2322: Type readonly ["user"] is not assignable to type Populate<UserRate, never>
Type readonly ["user"] is not assignable to type readonly never[]
Type string is not assignable to type never
```

Version 2
```typescript
const options: FindOptions<UserRate> = {
    populate: ['user'] as const,
}
```
`TS2322: Type string is not assignable to type never`

Something went wrong with types?
Must I use `// @ts-ignore`?


Dependency | Version
-- | --
node | 18.17.1
typescript | 5.3.2
mikro-orm | 6.0.5
your-driver | mongodb

**Comment by MrHIDEn** [comment]
```typescript
const populate  = ['user'] as never;
```

That works, but I am not happy of that shape...

**Comment by B4nan** [comment]
Both should work, sounds like you have some other problem. Maybe you are using dev version of TS? TS 5.4 unfortunately breaks this completely, I hope its gonna be sorted before the stable release.

**Comment by MrHIDEn** [comment]
No, As I have vritten TS: 5.3.2
```
$ tsc -v
Version 5.3.2
```

`as never` wors so, ok.

**Comment by B4nan** [comment]
And you see this when you compile the app? Because often people see issues like that in vscode, using dev version without actually realizing it.

Either way, repro welcome, this is not how things should work (and I am not able to reproduce anything like that myself).

**Comment by MrHIDEn** [comment]
Yes, at build time. I am using Intellij.

```typescript
        const options: FindOptions<UserRate> = {
            populate: ['user'] as const,
```

```
$ nest build
⠋  TSC  Initializing type checker...
src/user-rate/user-rate.service.ts:132:24 - error TS2322: Type 'string' is not assignable to type 'never'.

132             populate: ['user'] as const,
```

**Comment by B4nan** [comment]
As I said, repro welcome, I can't help with those incomplete snippets. Could be caused by TS config, or anything else really.

**Comment by MrHIDEn** [comment]
I extracted part of the code.

[MrHIDEn/MikroORM-3.ts](https://gist.github.com/MrHIDEn/b9bf5b1ca7f18bebadeed207496e0b7d)

**Comment by B4nan** [comment]
Ok sorry for the confusion, using `FindOptions` as you do is the wrong way to do this - if you omit the second type parameter, you explicitly type it to have nothing populated, hence the type errors. TS currently does not support partial inference, so once you define the type as `FindOptions<User>`, which means `FindOptions<User, never>`, it will stay like that

One thing you can do is using const assertion of the whole options object:

```ts
const options = {
  populate: ['rates'],
  orderBy: { name: 'ASC' },
  fields: ['id', 'name', 'rates'],
} as const;
const users = await em.find(User, {}, options);
```

If you really want to have a builder for the options, you'll have to use `FindOptions<User, any>`, that way you allow any populate hint. You will loose all the strictness by doing that, so I'd rather discourage this (unless you need to do things dynamically).

You could also do this:

```ts
const options = {
  populate: ['rates'],
  orderBy: { name: 'ASC' },
  fields: ['id', 'name', 'rates'],
} as const satisfies FindOptions<User, any, any>;
const users = await em.find(User, {}, options);
```

You won't get autocomplete on the fields - that can only work if you put things directly to the `em.find` options, only that way the inference can actually work. But you will get type error when you use invalid property names at the call site (the `em.find` call won't accept wrong property names). Note the third generic type parameter, that's for the `fields` hint, you want to set both, so you need to provide the `any` type to both.

**Comment by MrHIDEn** [comment]
Ok, thanks.
```typescript
const options: FindOptions<User, any, any> = {
```
Above works well too. 
Soo this shows no error now:
```typescript
       const options: FindOptions<User, any, any> = {
            populate: ['rates'],
            orderBy: {name: 'ASC',},
            fields: ['id', 'name', 'rates'],
        };
        const users = await em.find(User, {}, options);
```
