### ISSUE TITLE
docs: Clear pros and cons to different metadata providers

### ISSUE THREAD

**Issue by Faithfinder** [mikro-orm/mikro-orm#2737]
I know that docs talk about the TsMorph vs ReflectMetadata extensively, but it's still hard to wrap my head around. I understand the superficial difference, - TsMorph allows us to infer database types from typescript types, while reflect metadata requires explicit annotations, but I would like to understand better what problems I might have down the line choosing one over the other. A sections with a table of pros and cons would help, I think.

**Comment by B4nan** [comment]
Note sure what more what you want to read, the downsides/limitations are [clearly defined there](https://mikro-orm.io/docs/metadata-providers/#limitations-and-requirements). They do the same job, its just more verbose with reflect-metadata, and much slower with ts-morph.
