### ISSUE TITLE
(v5) not assignable to parameter of type 'RequiredEntityData<EntityName>'

### ISSUE THREAD

**Issue by adlanarifzr** [mikro-orm/mikro-orm#2739]
**Describe the bug**
When initializing values inside entity class would still throw error when trying to insert the entity without defining the default value.

**Stack trace**
```console
Argument of type '{ }' is not assignable to parameter of type 'RequiredEntityData<EntityName>'.
  Type '{ }' is missing the following properties from type '{ data: string; }': data ts(2345)
```

**To Reproduce**
1. The entity is as follow:
```ts
@Entity()
export class EntityName {
	@PrimaryKey({ type: 'uuid' })
	id: string = v4();

	@Property()
	data: string = 'default';
}
```

2. Insert a new data using `em.create()`, but will show type error, expecting data to be defined as it is required param.
```ts
const test = em.create(EntityName, {});
await em.persistAndFlush(test);
```

**Expected behavior**
A variable/field that already been initialized with default value should not showing any type error

**Versions**

| Dependency | Version |
| - | - |
| node | 16.13.2 |
| typescript | 4.5.4 |
| mikro-orm | 5.0.0 |

**Comment by B4nan** [comment]
You need to use `OptionalProps` symbol to mark every optional property that has a database default.

```ts
@Entity()
export class EntityName {
    [OptionalProps]?: 'data'; // id is there automatically

	@PrimaryKey({ type: 'uuid' })
	id: string = v4();

	@Property()
	data: string = 'default';
}
```

**Comment by ramiel** [comment]
I have a similar problem. It works if I specify something like
```ts
 [OptionalProps]?: 'data';
 ```

but how to do it for more than one parameter? I tried

```ts
 [OptionalProps]?: ['prop1', 'prop2'];
```

but this is not working

**Comment by ramiel** [comment]
I'm also wondering why this is needed. Shouldn't be typescript capable of understanding that 
```ts
class A{
    optional = 'defaultvalue'
}
```

is optional?

**Comment by B4nan** [comment]
> but how to do it for more than one parameter? I tried

It needs to be union of keys, not array/tuple. So:

```ts
 [OptionalProps]?: 'prop1' | 'prop2';
```

> I'm also wondering why this is needed. Shouldn't be typescript capable of understanding that

I don't think so, that property is defined as mandatory, with a default value. It is you defining it this way, if you want to tell TS it is optional, you can do this instead:

```ts
class A {
    optional?: string = 'defaultvalue'
}
```

(or maybe there will be some hack to achieve this via assignability checks, but that seems like quite overkill, I can imagine perf costs if we try to do it that way, as well as some false positives - so we would fix one problem but introduced another)

**Comment by ramiel** [comment]
Thanks, I'll try.

In general these are considered optional in typescript

```ts
function x(aParameter = 'something') {} // aParameter is optional

class A {
   aMember = 'anything'; // aMember is considered with a value
}
```

I see, btw, how this can be complicated or impossible when assigning a type to the `create` function

**Comment by ramiel** [comment]
There's another problem with this `[OptionalProps]` approach. I have all my classes extending a base class similar to this

```ts
@ObjectType()
abstract class BaseEntity {
  [OptionalProps]?: 'createdAt' | 'updatedAt';

  @PrimaryKey()
  _id!: ObjectId;

  @SerializedPrimaryKey()
  id!: string;

  @Property()
  createdAt = new Date();

  @Property({
    onUpdate: () => new Date(),
  })
  updatedAt = new Date();
}
```

now, since this base class already defines `[OptionalProps]`, I cannot redeclare in all the children, forcing me to remove it from here and copy it in all the children classes.

**Comment by B4nan** [comment]
You can use generics for this

**Comment by ramiel** [comment]
Makes sense. Thanks

**Comment by calvinwyoung** [comment]
> Makes sense. Thanks

Just to clarify, is this roughly how you'd use generics to handle this case? Is there a more precise way to define the type for `T`?

```ts
@ObjectType()
abstract class BaseEntity<T> {
  [OptionalProps]?: 'createdAt' | 'updatedAt' | T;
}
```

**Comment by B4nan** [comment]
yop. you could have two type args if you want to make it type safe, so you could use `<E, K extends keyof E>`

**Comment by calvinwyoung** [comment]
Perfect makes sense, thank you! Would you consider adding some sort of `createPartial` method that supports the previous interface that doesn't require all keys? We frequently run into cases where we explicitly want to initialize a partial object that gets fully populated later, so we happened to prefer the behavior from <v5.

**Comment by B4nan** [comment]
You can always create such method yourself in a custom repository.

```ts
  createPartial<P = never>(data: EntityData<T>): T {
    return this.em.create(this.entityName, data as any);
  }
```

(if you dont like the `any` cast, it could be also `as unknown as RequiredEntityData<T>`)

**Comment by calvinwyoung** [comment]
Perfect, that's exactly what we've done. Thank you!
