### ISSUE TITLE
Unable to use custom repository with NestJS and Mikro ORM 5.0.1

### ISSUE THREAD

**Issue by kristijanhusak** [mikro-orm/mikro-orm#2767]
**Describe the bug**
I'm trying to update my own application from 4.5 to 5.0.1, but I'm running into some issues with the identity map, and `disableIdentityMap` seems to not work for some cases.
I tried to set up reproducible repo for it, but I'm now running into a different issue that I cannot understand.
I tried setting up a custom repository with Nest JS, but It seems it doesn't have a context.
I tried using the EntityRepository with `InjectRepository`, and that seems to work.

**Stack trace**
```
mikroorm-migration-issue-api-1       | TypeError: Cannot read properties of undefined (reading 'getContext')
mikroorm-migration-issue-api-1       |     at CustomerRepository.get em [as em] (/src/node_modules/@mikro-orm/knex/SqlEntityRepository.js:30:25)
mikroorm-migration-issue-api-1       |     at CustomerRepository.findAll (/src/node_modules/@mikro-orm/core/entity/EntityRepository.js:63:21)
mikroorm-migration-issue-api-1       |     at AppController.getCustom (/src/src/app.controller.ts:22:28)
mikroorm-migration-issue-api-1       |     at /src/node_modules/@nestjs/core/router/router-execution-context.js:38:29
mikroorm-migration-issue-api-1       |     at InterceptorsConsumer.intercept (/src/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:11:20)
mikroorm-migration-issue-api-1       |     at /src/node_modules/@nestjs/core/router/router-execution-context.js:46:60
mikroorm-migration-issue-api-1       |     at /src/node_modules/@nestjs/core/router/router-proxy.js:9:23
mikroorm-migration-issue-api-1       |     at Layer.handle [as handle_request] (/src/node_modules/express/lib/router/layer.js:95:5)
mikroorm-migration-issue-api-1       |     at next (/src/node_modules/express/lib/router/route.js:137:13)
mikroorm-migration-issue-api-1       |     at Route.dispatch (/src/node_modules/express/lib/router/route.js:112:3)
```

**To Reproduce**
1. Clone https://github.com/kristijanhusak/mikroorm-migration-issue
2. Start it with `docker-compose up`
3. open `http://localhost:3000`, see that `InjectRepository` work
4. Try to open `http://localhost:3000/custom`, see the error

**Expected behavior**
I expect to be able to use custom repository. I think I covered all the necessary things:
1. Extended `EntityRepository` from postgresql package
2. Added the repository to the Entity via `customRepository` option in `Entity` decorator
3. Registered repository as provider

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 16.13.0 |
| typescript | 4.5.5 |
| mikro-orm | 5.0.1 |
| your-driver | Postgres |

**Comment by B4nan** [comment]
> Registered repository as provider

This is your problem. Doing this makes nest to create the repository instance via its constructor, but not providing the parameters. 

It is the `forFeature()` call that registers repositories, don't put them to the `providers` array.

**Comment by julestruong** [comment]
Hi sorry to re-post on this closed issue but this issue helped me a lot but there is a little thing that still bothers me .
@B4nan 
Using GraphQLModule `nestjs` and `dataloader` i used to do this.

```
 GraphQLModule.forRootAsync<MercuriusExtendedDriverConfig>({
      driver: MercuriusGraphQLDriver,
      imports: [
      // BEGIN i tried this but this does not solve anything
        MikroOrmModule.forFeature([
          AddressEntity,
          MembershipEntity,
        ]),
        // END i tried ...
        AddressModule,
        MembershipModule,
      ],
      useFactory: (
        addressRepository: AddressRepository,
        membershipRepository: MembershipRepository,
      ) => ({
        // This is where fastify/mercurius plugins should be added
        // Exceptions for mercurius-upload and fastity-raw-body
        // https://github.com/nestjs/graphql/pull/2538
        plugins: [
          {
            plugin: import('./mercurius-logger.fastify-plugin'),
            options: {
              prependAlias: true, // default: false
              logBody: true, // default: false
              logVariables: true, // default: false
            },
          },
        ],
        playground: true,
        introspection: true,
        autoSchemaFile: true,
        sortSchema: true,
        context: ({ req }) => ({
          req,
          addressLoader: oneToOneDataLoader<AddressEntity>(addressRepository),
          membershipLoader:
            manyToOneDataLoader<MembershipEntity>(membershipRepository),
          
```

It seems the repository is `undefined`
My membershipRepository is used at another places in the app so it works 
```
export class MembershipRepository extends EntityRepository<MembershipEntity> {
```
```
@Entity({
  tableName: 'membership',
  customRepository: () => MembershipRepository,
})
export class MembershipEntity extends BaseEntity<Membership> {
  [EntityRepositoryType]?: MembershipRepository;
```

Is there any way ? 
Or should i add injectable service that flat passes the repository methods needed in the dataloaders ?
