### ISSUE TITLE
QueryBuilder `.execute` should be untyped by default?

### ISSUE THREAD

**Issue by Faithfinder** [mikro-orm/mikro-orm#2775]
**Is your feature request related to a problem? Please describe.**
With the query builder we can build quite a big variety of queries, and I imagine you're mostly expected to use it if the standard `find` is not enough. IMO, the probability of the query builder result matching the entity you started with is quite low.

**Describe the solution you'd like**
Remove `execute`'s generic default type, so the user always has to provide the resulting type. Otherwise, it's very easy to forget and you end up with unrelated return type.

**Additional context**
I guess it's a very breaking change?

**Comment by B4nan** [comment]
Sorry, not interested in doing that, indeed it would be a breaking change. Note that you are concerned with select queries, but all the other query types will actually be correctly typed (e.g. count query will get `{ count: number }`, insert/update/delete queries will get `QueryResult`).
