### ISSUE TITLE
Migrations not created for column type change (default number to double precision)

### ISSUE THREAD

**Issue by woltob** [mikro-orm/mikro-orm#2789]
Hi,

I am still running 4.5.9 and have seen that when changing the columnType to double precision from the default value for number (which is integer for postgres in MikroORM), it does not generate a migration.

Changing the code from

```
  @Property({ type: 'number', nullable: true })
  @Field({
    description: 'Fee for the job.',
    nullable: true,
  })
  public fee?: number;
```
to 
```  
  @Property({ type: Number, columnType: 'double precision', nullable: true })
  @Field({
    description: 'Fee for the job.',
    nullable: true,
  })
  public fee?: number;
```

should generate a migration when running migration create.

```
    this.addSql(
      'alter table "job" alter column "free" type double precision;',
    );
```

**Comment by B4nan** [comment]
Please upgrade to v5, schema diffing is completely rewritten, no plans to backport any changes to v4. Will be happy to reopen if it does not work in v5, but I am sure it will.

**Comment by woltob** [comment]
Thank you for your prompt reponses! This might perhaps be the greatest node open source project on github with amazing support :D
