### ISSUE TITLE
`Reference.load()` doesn't initialize the nested collection since v5

### ISSUE THREAD

**Issue by suerta-git** [mikro-orm/mikro-orm#2796]
**Describe the bug**
```ts
await player.room.load() // room: Reference<Room>

player.room.unwrap().players.getItems() // error! players: Collection<Player>
```

**Stack trace**
```
Collection<Player> of entity Room[94] not initialized

      27 | ) => {
      28 |   await player.room.load() // lazy load room entity
    > 29 |   player.room.unwrap().players.getItems()
         |                                ^

      at Collection.checkInitialized (node_modules/@mikro-orm/core/entity/Collection.js:276:19)
      at Collection.getItems (node_modules/@mikro-orm/core/entity/Collection.js:83:18)
```

**Expected behavior**
Can populate reference's properties by default, or provide a easy way to do that (for example a `populate` param for `load()`).

**Versions**

| Dependency | Version |
| - | - |
| node | v14.18.2 |
| typescript | v4.5.4 |
| mikro-orm | v5.0.2 |
| your-driver | postgres |

**Comment by B4nan** [comment]
`Reference.load()` just initializes the wrapped entity, not its relations - so works as expected, definitely not a bug. If you want to populate things, use `em.populate()` that supports nested hints out of box and is n+1 safe. You could also swap `Collection.getItems()` with `Collection.loadItems()` which loads them if the collection is not initialized. 

We can add populate option to both `Reference.load()` and `Collection.loadItems()`, I am fine with that.

**Comment by suerta-git** [comment]
Use `em.populate()` is ok but a bit verbose. 

Considering `EntityRepository.find*()` can return populated entities when given options, expecting `Reference.load()` has a similar capability is natural. Because it seems to me that these two methods' purpose is similar (loading entity from db).

So I suggest considering that as an enhancement. It's great if they can have the same options interface. (Sorry I am not very clear about the type issue you mentioned, hope it can be solved)
