### ISSUE TITLE
Improve type of the result from query builder with `unsetFlag(QueryFlag.CONVERT_CUSTOM_TYPES)` on v5

### ISSUE THREAD

**Issue by suerta-git** [mikro-orm/mikro-orm#2797]
**Is your feature request related to a problem? Please describe.**

```ts
const result = await roomRepository
    .createQueryBuilder()
    .unsetFlag(QueryFlag.CONVERT_CUSTOM_TYPES)
    .select('state')
    .where({ roomId })
    .execute('get', false))

result.state  // type is State
```

Here `state` is a custom type property which's JS type is `State`. In v5 the type of query builder result is the entity class, so `result.state` has `State` type. 

But because of `unsetFlag(QueryFlag.CONVERT_CUSTOM_TYPES)`, it's real type is json string (raw column type in database).

**Describe the solution you'd like**

Some type casting maybe.

**Comment by B4nan** [comment]
There is no way to access the "type of the custom type", as you only pass it in the decorator options - there is no way to infer that.
