### ISSUE TITLE
Error: MikroORM config file not found in ['./mikro-orm.config.js']

### ISSUE THREAD

**Issue by W2AlharbiMe** [mikro-orm/mikro-orm#2798]
**Describe the bug**
after installing `@mikro-orm/cli` and running `mikro-orm debug` got the following error:

**Stack trace**
```
Current MikroORM CLI configuration
 - dependencies:
   - mikro-orm 5.0.2
   - node 17.5.0
   - typescript 4.5.5
 - package.json found
 - searched config paths:
   - /server/mikro-orm.config.js (not found)
- configuration not found (MikroORM config file not found in ['./mikro-orm.config.js'])
```

**Expected behavior**
load `mikro-orm.config.js` from the `dist` folder

**Additional context**
is there a way to tell the cli to look inside the `dist` folder or provide a flag in the cli something like `--config-path=./dist/mikro-orm.config.js` ?

**Versions**

| Dependency | Version |
| - | - |
| node | 17.5.0 |
| typescript | 4.5.5 |
| mikro-orm | 5.0.2 |
| your-driver | `@mikro-orm/mariadb` |

**Comment by michaelgambold** [comment]
From the [docs] (https://mikro-orm.io/docs/installation#setting-up-the-commandline-tool) you can configure the config locations.

<img width="852" alt="image" src="https://user-images.githubusercontent.com/7439294/154833093-d9d5155b-c657-4214-8234-fc31ce909a98.png">

**Comment by B4nan** [comment]
As said, you can use `configPaths` in the package.json, or `MIKRO_ORM_CLI` env var. Default location is in the `baseDir`.

https://mikro-orm.io/docs/installation#setting-up-the-commandline-tool

**Comment by W2AlharbiMe** [comment]
thank you so much its working now i'm excited to try this ORM
