### ISSUE TITLE
Cannot find module '../package.json' when using webpack

### ISSUE THREAD

**Issue by sayav** [mikro-orm/mikro-orm#2799]
**Describe the bug**
When building with webpack, the function `Utils.getORMVersion` throws an error as it is unable to import package.json. This used to work in 4.x when `require('../package.json')` was used instead of `Utils.requireFrom`. The bug occurs in 5.0.0, 5.0.1 and 5.0.2. The code runs fine when using ts-node.

Also another issue is with `ConfigurationLoader.getPackageConfig` which has the same problem as it recursively looks for package.json files and cannot import them. When deploying with webpack this won't be an issue as there would be no local package.json file but is an issue for those using webpack in development.

**Stack trace**
```
(node:6003) UnhandledPromiseRejectionWarning: Error: Cannot find module '../package.json'
    at webpackEmptyContext (/Users/agni/development/temp/bundle.js:2:324247)
    at /Users/agni/development/temp/bundle.js:2:320610
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6003) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:6003) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
Repo - [https://github.com/sayav/mikro-orm-webpack-issue](https://github.com/sayav/mikro-orm-webpack-issue
)

`yarn start` runs using ts-node

`yarn webpack` creates bundle.js (when running with webpack, it's a good idea to copy bundle.js to a different location with no package.json files to avoid the second bug). Replacing `return  this.requireFrom('../package.json',  __dirname).version` with `require('../package.json')` in `Utils.getORMVersion` solves the issue.

**Expected behavior**
No crash

**Versions**
| Dependency | Version |
| - | - |
| node | 14.18.2 |
| typescript | 4.5.5 |
| mikro-orm | 5.x |
| your-driver | mysql |

**Comment by B4nan** [comment]
Thanks for the repro. I kinda hate webpack for this, but what can we do. Note that just changing it back to `require` in the bundle does not help, you need to rebuild it, in other words, this is not about webpack not liking `createRequire`, but rather about not bundling the package.json so it can't be required. 

I guess I will revert back to the `require` calls, I hope it won't break something else like ESM support (but given its a known path, it should work fine).

I don't understand how `getPackageConfig` can have the same problem, as that should never throw if the file is not found (and is not using `createRequire` like the former). It even first checks if the file exists.

**Comment by sayav** [comment]
Thanks for the reply! So I was actually changing the code in node_modules not the bundle, and then rebuilding which seemed to do the trick. 

Moving `MIKRO_ORM_ALLOW_VERSION_MISMATCH` would definitely help. I'll try and see if I can bundle my package.json to fix this one.

**Comment by B4nan** [comment]
FYI I ended up doing both, moving the `MIKRO_ORM_ALLOW_VERSION_MISMATCH` check as well as adding try/catch to the `getPackageConfig` helper, let's stay safe.
