### ISSUE TITLE
Replacing a one-to-one relation with a new entity sets the relation to null until refetched.

### ISSUE THREAD

**Issue by jamesmeneghello** [mikro-orm/mikro-orm#2806]
**Describe the bug**

Fetch an existing entity (A) with an existing 1-1 relation attached (B), where A is the owner with `orphanRemoval` set. Replace the 1-1 relation (`a.some_b = em.create(B, {...})`) and the UoW generates three changes:

1. Create new B
2. Update A setting `a.some_b` to `undefined`
3. Delete old B

Since `a.some_b` is set to undefined, the new B is created but the relation on A is not populated - accessing `a.some_b` at this point is undefined. Presumably #2 should hold some kind of reference to new B so that the new relation is written.

**Expected behavior**

Expected `a.some_b` to be the new instance of B.

**Versions**

| Dependency | Version |
| - | - |
| node | 16 |
| typescript | 4.4.4 |
| mikro-orm | 5.0.1 |

**Comment by B4nan** [comment]
I would appreciate some code in the reproduction, at least entity definition. Also please upgrade to latest first, there were many bug fixes in last weeks, ideally try 5.0.4 dev version.

**Comment by B4nan** [comment]
Failing test case:

```ts
import { Entity, MikroORM, OneToOne, PrimaryKey, Property } from '@mikro-orm/core';

@Entity()
export class A {

  @PrimaryKey()
  id!: number;

  @Property()
  name!: string;

  // eslint-disable-next-line @typescript-eslint/no-use-before-define
  @OneToOne({ entity: () => B, nullable: true, orphanRemoval: true })
  b?: any;

}

@Entity()
export class B {

  @PrimaryKey()
  id!: number;

  @Property()
  name!: string;

  @OneToOne(() => A, a => a.b, { nullable: true })
  a?: A;

}

describe('GH issue 2806', () => {

  let orm: MikroORM;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [A, B],
      dbName: ':memory:',
      type: 'sqlite',
      debug: true,
    });
    await orm.getSchemaGenerator().refreshDatabase();
  });

  afterAll(() => orm.close(true));

  test('search by m:n', async () => {
    const a = orm.em.create(A, { name: 'a', b: { name: 'b' } });
    await orm.em.fork().persistAndFlush(a);
    orm.em.clear();

    const a1 = await orm.em.findOneOrFail(A, a, { populate: ['b'] });
    a1.b = orm.em.create(B, { name: 'b2' });
    await orm.em.flush();
    expect(a1.b).toBeDefined();
    const a2 = await orm.em.fork().findOneOrFail(A, a, { populate: ['b'] });
    expect(a2.b).toBeDefined();
  });

});
```

note that the queries are correct, the relation gets written to the database just fine.

**Comment by jamesmeneghello** [comment]
Sorry, didn't have a lot of time to write it up. Thanks for the quick fix!
