### ISSUE TITLE
Postgresql migrations table not created under configured schema

### ISSUE THREAD

**Issue by ls-jason-rossiter** [mikro-orm/mikro-orm#2828]
**Describe the bug**

There are two bugs here.

The MigrationStorage class has an [ensureTable](https://github.com/mikro-orm/mikro-orm/blob/master/packages/migrations/src/MigrationStorage.ts#L56) method which verifies that the migrations table exists before running migrations.

First, the migrations table seems to be created without considering the [schema](https://github.com/mikro-orm/mikro-orm/blob/ffe6bd886ddc0c97bbfde600c3bec26570f3ca33/packages/core/src/utils/Configuration.ts#L358) value configured in `Options<PostgreSqlDriver>`.

The migrations table will be created under the `public` schema which results in the [logMigration](https://github.com/mikro-orm/mikro-orm/blob/master/packages/migrations/src/MigrationStorage.ts#L22) function failing when using a custom schema.

Second, the [line](https://github.com/mikro-orm/mikro-orm/blob/master/packages/migrations/src/MigrationStorage.ts#L59) that validates if the migrations table exists does not support multi-schema as well.

Once the migrations table has been created under any schema it will not validate if the configured schema has the table.

**Stack trace**
```
N/A
```

**To Reproduce**
1. Use the postgresql driver and configure a schema value.

```
export const config: Options<PostgreSqlDriver> = {
  schema: 'myschema'
}
```

2. Run the ensureTable method from MigrationStorage.

```
const orm = await MikroORM.init(config);
const migrator: Migrator = orm.getMigrator();
await migrator.getStorage().ensureTable();
```

3. The migrations table will be created under `public` instead of `myschema`.
4. Migrations will fail since the table does not exist in `myschema`.

The workaround for this is to manage the creation of this table ourselves.

**Expected behavior**

The migrations table should be created in the `myschema` schema.
The check to see if the table exists should also filter by the current schema.

**Additional context**
N/A

**Versions**

| Dependency | Version |
| - | - |
| node | 14.x |
| typescript | N/A |
| mikro-orm | 5.0.5 |
| your-driver | postgresql@5.0.5 |

**Comment by ls-jason-rossiter** [comment]
Thanks, that allows the migrations table to be created in the correct schema but then fails with the subsequent `logMigration` call. 

Config:
```
{
  schema: "myschema",
  migrations: { tableName: "myschema.mikro_orm_migrations" }
}
```

results in error:
```
insert into \"myschema\".\"myschema\".\"mikro_orm_migrations\" (\"name\") values ('Migration20220225044002') - cross-database references are not implemented: \"myschema. myschema.mikro_orm_migrations\"
```

Seems like half using schema, half not.

**Comment by ls-jason-rossiter** [comment]
I just stumbled upon a discussion of the same issue: https://github.com/mikro-orm/mikro-orm/discussions/1886

I can confirm that the workaround suggestion works like a treat:
1. Setting the search_path before using the migrator programmatically, and
2. Setting a unique per schema name for the migration table.

```
const connection = orm.em.getDriver().getConnection();
await connection.execute("SET search_path TO myschema");
```

This resolves the issue for us and require no overall changes to configuration or code.

**Comment by killjoy2013** [comment]
> I just stumbled upon a discussion of the same issue: #1886
> 
> I can confirm that the workaround suggestion works like a treat:
> 
> 1. Setting the search_path before using the migrator programmatically, and
> 2. Setting a unique per schema name for the migration table.
> 
> ```
> const connection = orm.em.getDriver().getConnection();
> await connection.execute("SET search_path TO myschema");
> await orm.getMigrator().up()
> 
> // mikro-orm.config.js
> {
>   schema: 'myschema',
>   migrations: { tableName: 'mikro_orm_migrations_myschema' }
> }
> ```
> 
> This resolves the issue for us and require no overall changes to configuration or code.

Hi,
How can we apply this solution to Nestjs + MicroORM?  Can you please show it in a more detailed way?
Thanks
