### ISSUE TITLE
Any array is a valid `QueryOrderMap<T>` if the entity `T` has a property `length`

### ISSUE THREAD

**Issue by gabubarks** [mikro-orm/mikro-orm#2829]
**Describe the bug**

Summary:

Strict typing for passing an array to `orderBy` argument does not work if the entity has a property `length`. Contents of the array are not type checked.

Long description:

I ran into this issue while updating some of my utility functions to also accept an `orderBy` argument typed as `QueryOrderMap<T> | QueryOrderMap<T>[]` just like in `FindOptions`:

https://github.com/mikro-orm/mikro-orm/blob/3c1441b92f9d3b73b067de935d463f5236e9cf98/packages/core/src/drivers/IDatabaseDriver.ts#L98

My code seemed to work, but for some reason type checking on my `orderBy` argument did not work for *one specific entity* (but it did work for all others). Namely if I passed an array of objects as an argument to my function it would not throw any compiler errors even if the properties did not exist on that entity. Later I found out that this even occurs with regular `EntityManager.find`, i.e.
```ts
em.find(SomeEntity, {}, {
    orderBy: [
        { someNonExistentProperty: 'and whatever value' },
    ]
})
```

while if I manually specified the type as follows, then I would get a type error when compiling, as expected:
```ts
em.find(SomeEntity, {}, {
    orderBy: [
        { someNonExistentProperty: 'and whatever value' },
    ] as QueryOrderMap<SomeEntity>[]
})
```

For some reason the type of the array was being inferred as `QueryOrderMap<SomeEntity>` instead of `QueryOrderMap<SomeEntity>[]` and for some reason an array was accepted as that type... After being stumped for a while I found out that removing property `length` on my entity would cause compilation to throw the correct error.

Then it all clicked.

https://github.com/mikro-orm/mikro-orm/blob/3c1441b92f9d3b73b067de935d463f5236e9cf98/packages/core/src/enums.ts#L76-L78

Any array is a valid `QueryOrderMap<T>`  (even if it's not a valid `QueryOrderMap<T>[]`) if the entity `T` has a property `length`, because the only non-function property of *any* array is also `length`.

Passing an array to `orderBy` for an entity with a `length` property will throw all type safety out the window. The contents of the array can be anything.

**To Reproduce**
Define an entity with the property named `length`:
```ts
@Entity()
export class SomeEntity {
    @PrimaryKey()
    id!: number

    @Property()
    length!: number

    @Property()
    otherProperties!: number
}
```

Now passing an array (with arbitrary contents) as `orderBy` argument passes compilation instead of giving a type error.

```ts
em.find(SomeEntity, {}, {
    orderBy: [
        { someNonExistentProperty: 'and whatever value' },
    ]
})
```

**Expected behavior**
Compilation should fail with for example the following type error:
```
src/test.ts:46:19 - error TS2322: Type '{ someNonExistentProperty: string; }' is not assignable to type 'QueryOrderMap<SomeEntity>'.
  Object literal may only specify known properties, and 'someNonExistentProperty' does not exist in type 'QueryOrderMap<SomeEntity>'.

46                 { someNonExistentProperty: 'and whatever value' },
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Additional context**
My knowledge of Typescript types and generics is not deep enough to suggest any specific fix, and also I can see how this might just be an issue in general if you define your interface (any interface) to have a property `length`, that arrays will match that type as well.

Hope this rambling analysis made sense, and thanks for all the great work!

**Versions**

| Dependency | Version |
| - | - |
| node | v16.13.2 |
| typescript | 4.5.5 |
| mikro-orm | 5.0.5 |
| your-driver | postgres |

**Comment by B4nan** [comment]
I am not sure if this can be worked around, given TS is a structurally typed language, so technically any object with `length` property is assignable to any array and vice versa. 

Will first do some testing...

**Comment by inflab-int** [comment]
How about define `orderBy` type like this?

```ts
    orderBy?: (QueryOrderMap<T> & { 0: never}) | QueryOrderMap<T>[];
```

**Comment by jbl428** [comment]
How about define `orderBy` type like this?

```ts
    orderBy?: (QueryOrderMap<T> & { 0: never}) | QueryOrderMap<T>[];
```

**Comment by B4nan** [comment]
Oh now I get it, its because of the dual syntax that allows object and array. Yeah the trick with `0: never` should help for such case, PR welcome.

**Comment by jbl428** [comment]
I found that the trick with `0: never` makes another problem.

It requires  single `order by` item should have  `0: never` type

```ts
em.find(SomeEntity, {}, {
    orderBy:  { otherProperties: 'ASC' }, // type error
})
```

The following code should work, but it is bad solution.

```ts
em.find(SomeEntity, {}, {
    orderBy:  { otherProperties: 'ASC' , '0': undefined as never }
})
```

**Comment by B4nan** [comment]
Looks like `orderBy?: (QueryOrderMap<T> & { 0?: never }) | QueryOrderMap<T>[];` does the job.
