### ISSUE TITLE
Invalid @Check Instances Should Throw ConstraintViolationException Instead of DriverException

### ISSUE THREAD

**Issue by slcrider** [mikro-orm/mikro-orm#2836]
**Is your feature request related to a problem? Please describe.**
Mikro ORM v5 added the `@Check` decorator.  When adding  `@Check` instances to my app and writing tests, I noticed that when a check is invalid, the lower-level `DriverException` is being thrown.  Given that [Postgres defines checks as a form of constraint](https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-CHECK-CONSTRAINTS), I would have expected the more-granular `ConstraintViolationException` to be thrown.

**Describe the solution you'd like**
Invalid Postgres checks throw the more specific `ConstraintViolationException`.  Alternatively, they could get an even-more-granular exception `CheckConstrainViolationException`, but Postgres defines checks as the most generic constraint type, so I don't see a huge need for this.

**Additional context**
I am using Mikro ORM 5.0.5.

**Comment by B4nan** [comment]
PR welcome, this should be just a one liner.
