### ISSUE TITLE
Index with the condition

### ISSUE THREAD

**Issue by Jasenkoo** [mikro-orm/mikro-orm#2837]
**Is your feature request related to a problem? Please describe.**
So far, I don't see a way to add a condition when using indexes.

My project requires that we don't delete any data, just to mark them as deleted. This is simply done by updating `deletedAt` column and using filters. However, in order to have unique flags on some properties, we need a `UNIQUE INDEX.

We manage this by adding manually in the migration file something like this

```ts
this.addSql('CREATE UNIQUE INDEX "index_name" ON "table_name" (UPPER("column_name")) WHERE "deletedAt" IS NULL');
```

However, each time a new migration file is generated, those indexes are getting removed and we need to manually remove those lines from the file.

**Describe the solution you'd like**
Either a way to declare a condition, or to not auto delete added indexes.

**Describe alternatives you've considered**
So far, none, manually removing the lines after the migration is generated

**Additional context**
None

**Comment by B4nan** [comment]
You can use index expressions added in v5, looks like they are not documented.

```ts
  @Index({ name: 'custom_index_expr', expression: 'alter table `book` add index `custom_index_expr`(`title`)' })
  @Property()
  title!: string;
```

**Comment by Jasenkoo** [comment]
Tnx
