### ISSUE TITLE
[FR] support query specific schema on findOptions

### ISSUE THREAD

**Issue by osman-mohamad** [mikro-orm/mikro-orm#284]
**Is your feature request related to a problem? Please describe.**
I am building multi-tenant app postgres and nodejs . I want to use the schema per tenant as architecture to separate data.
so I need to inject schema name while query Entity . by EntityManager API or RepositoryManager API.
I do not want to make Entity per tenant . because the tenants are dynamically  created. so I need to query same table on specific schema per user request.  

**Describe the solution you'd like**
for example 
```ts
// as part of the find options
repository.find({schema: 'some_schema'})
```
**Describe alternatives you've considered**
```ts
// or set on getting repository
const repository = orm.em.getRepository(Book, {schema: 'some_schema'});
repository.find() ....
```
**Additional context**
- there maybe some cross-schema joins needed.
- dynamic migrations with injected name of the schema can be run from code not command line.
- default schema is public or the one set in the Entity decorator

thanks

**Comment by nour-dev** [comment]
any news about this feature ?

**Comment by asmimo** [comment]
@B4nan nice that this feature is already implemented. This feature is more than what other orms provide but what about dynamic migrations? Its like providing a gun in a fight but with no bullets.

My solution is you can provide a option in entity for providing schema like
```js
@Entity({ schema: 'public' }) 
// if schema is provided skip dynamic migration
```
Which can be run like
```js
// run on code
migrator.up({ schema: 'newSchema' });
// run on command line
npx mikro-orm migration:up -s newSchema -r
```
I have only been through with mikro-orm for a day going through docs and creating a simple server. Correct me if this is already implemented in one way or another.

**Comment by B4nan** [comment]
Agreed this would be helpful, the support for multiple schemas is still very basic. Please create new issue for that.

Currently you can specify the schema in entity definition via `collection` (or its alias `tableName`), where you specify both schema and entity names together.
