### ISSUE TITLE
Schema generator fails creating foreign key contraints

### ISSUE THREAD

**Issue by mpp94** [mikro-orm/mikro-orm#2844]
**Describe the bug**
I've updated MikroORM to version 5.0.5 from version 4.5.9 and I've found what I think it's a regression. 

It seems to fail adding contraints when a third level of entities appear. If I remove the **OneToMany** relationship from **Step** to **Component** and the **ManytoOne** relationship from **Component** to **Step** everything works correctly.

![image](https://user-images.githubusercontent.com/86189277/156410257-7f652b92-f5f5-497d-828a-94c12e0a6c03.png)
![image](https://user-images.githubusercontent.com/86189277/156410297-077f6e59-6639-4ace-ac54-03e52cff52e6.png)
![image](https://user-images.githubusercontent.com/86189277/156410351-d00d548e-5768-4191-85aa-53f427545b90.png)

**Stack trace**
```
DriverException: alter table `component` add constraint `component_step_id_step_step_id_user_action_id_user_63c72_foreign` foreign key (`step_id_step`, `step_id_user_action_id_user_action`) references `step` (`id_step`, `id_user_action_id_user_action`) on update cascade on delete cascade; - (conn=6, no: 1822, SQLState: HY000) Failed to add the foreign key constaint. Missing index for constraint 'component_step_id_step_step_id_user_action_id_user_63c72_foreign' in the referenced table 'step'
sql: alter table `component` add constraint `component_step_id_step_step_id_user_action_id_user_63c72_foreign` foreign key (`step_id_step`, `step_id_user_action_id_user_action`) references `step` (`id_step`, `id_user_action_id_user_action`) on update cascade on delete cascade; - parameters:[]
    at MariaDbExceptionConverter.convertException (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
    at MariaDbExceptionConverter.convertException (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/@mikro-orm/mariadb/MariaDbExceptionConverter.js:78:22)
    at MariaDbDriver.convertException (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:180:54)
    at /home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:184:24
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async SchemaGenerator.execute (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:348:13)
    at async SchemaGenerator.createSchema (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:27:9)
    at async Function.handleSchemaCommand (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/@mikro-orm/cli/commands/SchemaCommandFactory.js:86:13)

previous Error: alter table `component` add constraint `component_step_id_step_step_id_user_action_id_user_63c72_foreign` foreign key (`step_id_step`, `step_id_user_action_id_user_action`) references `step` (`id_step`, `id_user_action_id_user_action`) on update cascade on delete cascade; - (conn=6, no: 1822, SQLState: HY000) Failed to add the foreign key constaint. Missing index for constraint 'component_step_id_step_step_id_user_action_id_user_63c72_foreign' in the referenced table 'step'
sql: alter table `component` add constraint `component_step_id_step_step_id_user_action_id_user_63c72_foreign` foreign key (`step_id_step`, `step_id_user_action_id_user_action`) references `step` (`id_step`, `id_user_action_id_user_action`) on update cascade on delete cascade; - parameters:[]
    at Object.module.exports.createError (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/mariadb/lib/misc/errors.js:61:10)
    at PacketNodeEncoded.readError (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/mariadb/lib/io/packet.js:511:19)
    at Query.readResponsePacket (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/mariadb/lib/cmd/resultset.js:46:28)
    at PacketInputStream.receivePacketBasic (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/mariadb/lib/io/packet-input-stream.js:104:9)
    at PacketInputStream.onData (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/mariadb/lib/io/packet-input-stream.js:169:20)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10) {
  text: "Failed to add the foreign key constaint. Missing index for constraint 'component_step_id_step_step_id_user_action_id_user_63c72_foreign' in the referenced table 'step'",
  sql: 'alter table `component` add constraint `component_step_id_step_step_id_user_action_id_user_63c72_foreign` foreign key (`step_id_step`, `step_id_user_action_id_user_action`) references `step` (`id_step`, `id_user_action_id_user_action`) on update cascade on delete cascade; - parameters:[]',
  fatal: false,
  errno: 1822,
  sqlState: 'HY000',
  code: 'ER_FK_NO_INDEX_PARENT'
}
...
```

**To Reproduce**
1. Create entity A, B and C
2. On entity A create a OnetoMany relationship to B, entity A has a primary key a
3. On entity B create a ManyToOne relationship to A, entity B has a composed primary key with property b and a reference to Entity A primary key a.
4. On entity B create a OnetoMany relationship to C
5. On entity C create a ManyToOne relationship to B, entity C has a primary key c.

**Expected behavior**
Contraints should be created correctly like on version 4.5.9

**Additional context**
The same entities work correctly and the schema generator succesfully creates tables, indexes and contraints in version 4.5.9.

**Versions**

| Dependency | Version |
| - | - |
| node | 14.17.5 |
| typescript | 4.4.4 |
| mikro-orm | 5.0.5 |
| @mikro-orm/mariadb | 5.0.5  |

**Comment by B4nan** [comment]
Please provide reproduction as code, also please don't use screenshots in issues, not for things that are part of the reproduction.

> Contraints should be created correctly like on version 4.5.9

What does that mean? Describe what you think is correct, not what version did it the way you think is correct.

Note that the error you have is about missing index, not about wrongly defined FK constraint.

**Comment by B4nan** [comment]
FYI reproductions should be minimal, so unless you face a bug that requires nest to reproduce, it shouldn't be there. Example projects are not base for reproductions (and the realworld example is the most complex one of them = the worst candidate for a repro). Ideally a repro should be just a single file, as in https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues. Anything that is not relevant should not be there, this applies to entity properties too, keep the entity definitions as simple as possible. This does not only help me to check it, but it will also take much less time to you to prepare it, there is no need for controllers, services and what not. 

Also I see you have 1:1 relation defined as not unique - that does not make sense to me, 1:1 relations are by definition unique, what was the reason behind that?

**Comment by mpp94** [comment]
The 1:1 relationship defined as not unique is a mistake definitely!

I will create a simpler repro example as you pointed it out. I will check out if NestJS is indeed needed (I am using NestJS in my APP).

Thanks for your response.

**Comment by B4nan** [comment]
No worries, I already got what I need, it was just a hint for future :] 

Here it is:

```ts
import { Entity, ManyToOne, MikroORM, OneToOne, PrimaryKey, Property } from '@mikro-orm/core';

@Entity()
export class UserAction {

  @PrimaryKey()
  idUserAction!: string;

  @Property()
  name!: string;

}

@Entity()
export class Step {

  @PrimaryKey()
  id!: number;

  @ManyToOne({ primary: true, onDelete: 'cascade' })
  userAction!: UserAction;

}

@Entity()
export class Component {

  @PrimaryKey()
  idComponent!: string;

  @ManyToOne({ onDelete: 'cascade' })
  step!: Step;

  @OneToOne({
    nullable: true,
    fieldName: 'resultComponentId',
    entity: () => Component,
  })
  resultComponent?: Component;

}

describe('complex FKs in mariadb (GH 2844)', () => {

  let orm: MikroORM;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [Component, Step, UserAction],
      dbName: `mikro_orm_test_gh_2844`,
      type: 'mariadb',
      port: 3309,
    });
    await orm.getSchemaGenerator().ensureDatabase();
  });

  afterAll(() => orm.close(true));

  test('schema generator adds the m:1 columns and FK properly', async () => {
    await orm.getSchemaGenerator().createSchema();
  });

});
```

**Comment by B4nan** [comment]
This is quite weird, it is complaining about missing index for the step table, while the FK target is already a PK of that table, which implies it has a key. Even if I do create explicit index for the PK, it complains the same.

**Comment by mpp94** [comment]
Awesome @B4nan, have a great weekend!
