### ISSUE TITLE
$ne doesn't work with null

### ISSUE THREAD

**Issue by vimmerru** [mikro-orm/mikro-orm#285]
**Describe the bug**
Try to filter some entities where some field isn't null. Obvious query will be 

```
find<Entity>(Entity, {field: { $ne: null }})
```

But typings doesn't allow it and generated query is also wrong. Seems the only workaround is to use use ```$and``` with combination with ```$not``` that looks too boilerplated.

Any suggestions?

**Versions**

rc5

**Comment by B4nan** [comment]
Have you tried undefined instead of null? Also, how is the property defined? How is the resulting query wrong when you type cast to any?

**Comment by kgoncharov** [comment]
As far as I remember either `field: {$ne: undefined}`  or `field: {$ne: null}` don't work, since one of those statements broke typing when other is converted to ` != NULL` in raw query

**Comment by B4nan** [comment]
Got it replicated.

**Comment by B4nan** [comment]
Will be fixed in next RC.

**Comment by henrroga** [comment]
Hello, is this fixed?
