### ISSUE TITLE
docs: The possibilities of abstract entities are not clear.

### ISSUE THREAD

**Issue by francescortiz** [mikro-orm/mikro-orm#2850]
I have many collections tables in a database that share the same structure and dependencies, so I though of creating abstract classes and extending them for each use case. The problem I face is that I cannot use the generic type in the `@ManyToOne` decorator, because typescript gives the error that types cannot be used as values. This is what fails:

```typescript

abstract class MyEntity<OtherEntity> {

  @ManyToOne({
    entity: () => OtherEntity, // This is where the problem arises.
    cascade: [],
  })
  myOther: OtherEntity;

}
```
I tried with Mikro-ORM 5 but the outcome was the same. I tried not defining the `entity` but then it complains at runtime about it. Is it possible to achieve this? Whatever is the answer, it would be great to have a section that clarifies this.

**Comment by B4nan** [comment]
Nope, this is not possible, you need value in the decorator, generics are always just types, not values. 

Note that `cascade: []` disables cascade persist, you probably dont want to do that.
