### ISSUE TITLE
Should default value be set when using `nativeInsert` and  `nativeUpdate`?

### ISSUE THREAD

**Issue by kenspirit** [mikro-orm/mikro-orm#2856]
**Is your feature request related to a problem? Please describe.**
During a migration process (loopback -> Micro-ORM) and also preparing future TypeScript upgrade, our company's project is still trying to use the EntitySchema approach to define the entity.  

Based on the [Default Value](https://mikro-orm.io/docs/defining-entities#default-values) docs, I learned that the `default` and `defaultRaw` only set default value of the field after persisting (`defaultRaw` is understandable but seems odd for `default` as it is just a constant or JS function.)  Both of these options are not helpful on setting default without relying on the return value from DB.  (Considering DB level default value setting is missing for historical reason.)

Hence, I put my hope to the `onCreate` and `onUpdate` defined for schema property, this is called runtime default value of the property.  However, I found that it's triggered only when ChangeSet calculation is called (`computeChangeSet` method in ChangeSetComputer).

That means when using `nativeInsert` and  `nativeUpdate`, this is not applied.  I am wondering if this is by-design or any consideration/difficulty.

The use case seems common and simple that user posts partial data to the application and then we just want to update DB using this partial data.  The fields such as `updatedAt`, `updatedBy` need to be populated on every update.  Instead of fetching the data from DB and manage by IdentityMap, persist and flush, wouldn't it be more efficient to issue a `nativeUpdate` statement?

**Describe the solution you'd like**
`onCreate` and `onUpdate` hooks can be triggered during `nativeInsert` and  `nativeUpdate`.

**Describe alternatives you've considered**

**Additional context**

**Comment by B4nan** [comment]
Those are handled by UoW, so only flush can trigger it. Using `em.nativeInsert()` is basically just a QB shortcut, there are no hooks or events, you dont work with entities there, only with DTOs.
