### ISSUE TITLE
BigIntTypes are truncated to 53 bits when retrieved from SQLite database

### ISSUE THREAD

**Issue by mcpower** [mikro-orm/mikro-orm#2857]
**Describe the bug**
When retrieving a property with type BigIntType from the database, the number itself is truncated to 53 bits (presumably due to being converted to a JavaScript `number` before being converted to a `string`).

I have observed this with SQLite, but this problem could occur with other databases.

**To Reproduce**
1. Download [bigint.zip](https://github.com/mikro-orm/mikro-orm/files/8184888/bigint.zip), which is a minimal reproducible example using SQLite.
2. Read all five files included in the zip to ensure it is not malicious.
3. Run `npm i && npm run all`.
4. Observe that it prints out `ID from database is 1490404699006197800, real ID is 1490404699006197764`.

**Expected behavior**
The two IDs should be the same.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.14.0 |
| typescript | 4.5.5 |
| mikro-orm | 5.0.4 |

**Comment by mcpower** [comment]
This also occurs for properties which aren't primary keys, which isn't in the minimal reproducible example.

**Comment by mcpower** [comment]
Update - it seems like [better-sqlite3 supports large integers with BigInts](https://github.com/JoshuaWise/better-sqlite3/blob/master/docs/integer.md). sqlite doesn't seem to work with large numbers.

I assume this needs to be fixed upstream in knex, so I've filed a bug (see above).

**Comment by B4nan** [comment]
I don't think this is about MikroORM or knex, this is a limitation of the node-sqlite3 connector. And they apparently don't care about it, seeing this old issue about the same: https://github.com/mapbox/node-sqlite3/issues/922

Closing, this is not really to be fixed here. The issue I linked can probably give you some workarounds, haven't read it fully but apparently you can use blobs to get around it. You can also use better-sqlite driver here, if that supports it out of box (added just recently).

Btw next time please share your reproductions on GH instead of uploading zip files, so they can be easily checked (also on mobile phone).

**Comment by mcpower** [comment]
Thanks for the background! better-sqlite3 does support large integers, but requires a `db.defaultSafeIntegers(true);` call. Currently, knex provides no way of actually enabling that functionality, so by extension MikroORM also can't enable that functionality.

I assume once the knex issue is fixed, adding support for this should be straightforward enough :)

> Btw next time please share your reproductions on GH instead of uploading zip files, so they can be easily checked (also on mobile phone).

Unfortunately, I can't create new repositories due to my employer's restrictions :(

**Comment by mcpower** [comment]
For other people finding this issue - the best way that I've found to work around it is:

- use string columns in the ORM and database
- whenever any integer operation is required in JS, cast it to a BigInt
- whenever any integer operation is required in SQL, cast it to a BigInt using a custom QueryBuilder expression (you can also add the [cast expression to an index if needed](https://www.sqlite.org/expridx.html))
  - a [generated column](https://www.sqlite.org/gencol.html) could be better, but isn't supported by MikroORM
