### ISSUE TITLE
Consider SchemaBuilder in Migrations

### ISSUE THREAD

**Issue by gsontag** [mikro-orm/mikro-orm#2866]
**Is your feature request related to a problem? Please describe.**
I try to make an app which is db agnostic. I use migration and don't want to adapt DDL code for each supported Db. Instead, I would prefer using Knex schema builder. But the addSql for migration doesn't accept schemabuilder.

**Describe the solution you'd like**
Change addSql to accept and process schemabuilder or add en addDdl to process schemabuilder

**Describe alternatives you've considered**
Actually, I do this `schemaBuilder.toQuery().split('\n').forEach(line => this.addSql(line));` as a workaround

**Comment by B4nan** [comment]
You can just use `this.getKnex()` and do what ever you want, no need to involve `this.addSql()`, just await the knex QB as usual. Alternatively you can also do `this.execute()` which accepts knex QB instance too.
