### ISSUE TITLE
Duplicate entity in collection when reloading after insert in a transaction

### ISSUE THREAD

**Issue by bspot** [mikro-orm/mikro-orm#2882]
**Describe the bug**
I have a parent and child model in a 1:n relationship.
I do the following:

1. Load the parent entity and populate the child collection
2. Create a child entity inside a transaction
3. Reload the child entity

Now the child collection of the parent entity is marked dirty and contains the child entity twice.

**To Reproduce**
Entity definitions:
```
@Entity()
class Widget {
  @PrimaryKey()
  id!: number

  @OneToMany(() => Gadget, gadget => gadget.widget)
  gadgets = new Collection<Gadget>(this);
}

@Entity()
class Gadget {
  @PrimaryKey()
  id!: number

  @ManyToOne(() => Widget)
  widget!: Widget;
}
```

Reproduction code:

```
const widgetId = 12345 // Some widget I know exists.

const widget = await mikroOrm.em.findOneOrFail(Widget, { id: widgetId }, { populate: ['gadgets'] })

await mikroOrm.em.transactional(async (em) => {
  const widget = await mikroOrm.em.findOneOrFail(Widget, { id: widgetId })
  em.create(Gadget, { widget })
})

console.log("A", widget)

await mikroOrm.em.find(Gadget, {})

console.log("B", widget)
```

Output:

```
A Widget {
  id: 11,
  gadgets: Collection<Gadget> {
    '0': Gadget { widget: [Widget], id: 9 },
    initialized: true,
    dirty: false
  }
}
B Widget {
  id: 11,
  gadgets: Collection<Gadget> {
    '0': Gadget { widget: [Widget], id: 9 },
    '1': Gadget { id: 9, widget: [Widget] },
    initialized: true,
    dirty: true
  }
}
```

As you can see, after `find()`ing the gadget, the `gadgets` collection of the widget is now marked dirty and contains the created gadget twice.

Additional remarks:
1. The behaviour does not change if I reload the gadget explicitly by id.
2. Reloading the widget with `mikroOrm.em.findOneOrFail(Widget, { id: widgetId }, { populate: ['gadgets'] })` also does not help.
3. However, reloading the widget with `mikroOrm.em.findOneOrFail(Widget, { id: widgetId }, { refresh: true, populate: ['gadgets'] })` does help.
4. This does **not** happen if I create the gadget outside of a transaction.
5. The example is contrived - in my actual project, there is a need for the transaction.

**Expected behavior**
I expect the gadget collection to contain the created entity only once.

**Versions**

| Dependency | Version |
| - | - |
| node | 14.17.0 |
| typescript | 4.6.2 |
| mikro-orm | 5.0.5, also 4.5.9 |
| mysql2 | 2.3.3, also 2.2.5 |

**Comment by B4nan** [comment]
> The behaviour does not change if I reload the gadget explicitly by id.
> Reloading the widget with mikroOrm.em.findOneOrFail(Widget, { id: widgetId }, { populate: ['gadgets'] }) also does not help.
> However, reloading the widget with mikroOrm.em.findOneOrFail(Widget, { id: widgetId }, { refresh: true, populate: ['gadgets'] }) does help.

`findOne` with a PK condition will always just give you the entity from identity map, so in fact you are not realing anything without explicit `refresh: true`. If you enable debug mode, you should see the first two calls dont produce any query, only when you query by a complex condition (so not a PK) or with `refresh: true`, it will fire a query.

Do I get it right that the code basically works (saves things correctly) but only once you reload, you get this duplication?

The code you have here seems a bit weird. You use `em.create()` but don't assign the value anywhere, nor persist it (so it only works based on propagation). You work with the global EM as well as the one from the parameter inside the `em.trasnactional()`, you definitely don't want to mix that (although it should refere to the same context in general, but there can be some edge cases).

Would be great if you could convert this into a test case, as in https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues

**Comment by B4nan** [comment]
Thanks for the repro, will try to look into this later today.

**Comment by bspot** [comment]
Thank you for the quick response!

> > The behaviour does not change if I reload the gadget explicitly by id.
> > Reloading the widget with mikroOrm.em.findOneOrFail(Widget, { id: widgetId }, { populate: ['gadgets'] }) also does not help.
> > However, reloading the widget with mikroOrm.em.findOneOrFail(Widget, { id: widgetId }, { refresh: true, populate: ['gadgets'] }) does help.
> 
> `findOne` with a PK condition will always just give you the entity from identity map, so in fact you are not realing anything without explicit `refresh: true`. If you enable debug mode, you should see the first two calls dont produce any query, only when you query by a complex condition (so not a PK) or with `refresh: true`, it will fire a query.

I just added this for completeness. I thought that because the collection is marked dirty, it maybe would issue a query. 

> Do I get it right that the code basically works (saves things correctly) but only once you reload, you get this duplication?

Yes, it does save things correctly. 

> The code you have here seems a bit weird. You use `em.create()` but don't assign the value anywhere, nor persist it (so it only works based on propagation). 

I was confused about that too. I knew that I don't have to `flush()`, because `transactional()` will do that automatically, but I assumed I had to at least `persist()` the entity. 
I tried with `em.persist(em.create(Gadget, { widget }))`, and it does not change the result, i.e. the entity is still duplicated in the collection.

> You work with the global EM as well as the one from the parameter inside the `em.trasnactional()`, you definitely don't want to mix that (although it should refere to the same context in general, but there can be some edge cases).

Oh?! That would be bad, because we depend on this behaviour. I.e. we regularly use methods on multiple repositories inside a transaction, assuming everything will use the transaction context.
Can you explain more explicitly under which conditions this will break? Or how we should be doing this differently?

However, the issue does not change if I only use the transactional `em`.

> Would be great if you could convert this into a test case, as in https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues

Done.

**Comment by B4nan** [comment]
> Oh?! That would be bad, because we depend on this behaviour. I.e. we regularly use methods on multiple repositories inside a transaction, assuming everything will use the transaction context.

It should work fine, I just don't like the idea of mixing it, as they are different entity manager instances. All methods that depend on the context should use the same UoW instance under the hood, you can verify the EM id, in v5 it will always reflect the contextual one so even `globalEM.id` will be the contextual if used inside `em.transactional()`.
