### ISSUE TITLE
MikroORM.init<PostgreSqlDriver>() 

### ISSUE THREAD

**Issue by thomascouto** [mikro-orm/mikro-orm#2899]
After updating typescript to 4.6.2 I have the following message on MikroORM initialization.

"Type instantiation is excessively deep and possibly infinite.ts(2589)"

```
import { MikroORM, RequestContext } from '@mikro-orm/core'
import { EntityManager } from '@mikro-orm/postgresql'
import type { PostgreSqlDriver } from '@mikro-orm/postgresql'
```

`DI.orm = await MikroORM.init<PostgreSqlDriver>()`

**Comment by B4nan** [comment]
Please dont ignore issue template. 

You are probably using custom base repository, right? This has been already fixed in master, check the latest dev version.
