### ISSUE TITLE
[PropertyOptions#serializer]: provide more arguments

### ISSUE THREAD

**Issue by marcpicaud** [mikro-orm/mikro-orm#2904]
Hello,

Currently, the `serializer` function `PropertyOptions<T>` ([source](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/decorators/Property.ts#L73))  only provides the decorated property's value : 
```serializer?: (value: any) => any;```

It would be nice to provide more arguments : the property name and the whole instance.
`serializer?: (value: any, key: string, obj: T) => any;` 

This would let developers do things like this : 
```typescript
@Entity()
export class Book {
  @Property()
  firstname: string;

  @Property()
  lastname: string;
  
  @Property({ persist: false, serializer: (value, key, obj) => `${obj.firstname} ${obj.lastname}` })
  fullName: string;  
}
```

What do you think ? I'd be happy to help, but I will need some guidance 🐣

**Comment by B4nan** [comment]
It is _property_ serializer, so I don't really like the idea it would do something else than work with the property value. 

Do you have better use case for this? Because your example is already supported via getters:

```ts
  @Property({ persist: false })
  get fullName() {
    return `${this.firstname} ${this.lastname}`;
  }
```

**Comment by marcpicaud** [comment]
Fair points !
I was (too) excited by the idea of transforming everything in the serializer 😅  

Thanks for the quick reply.
