### ISSUE TITLE
Query entities based on filter criteria on relations

### ISSUE THREAD

**Issue by co-sic** [mikro-orm/mikro-orm#2916]
Following up on this https://github.com/mikro-orm/mikro-orm/issues/2910#issuecomment-1067212914, i would like to know if mikro-orm will support filter criteria on relations in the future. Below is an example of use cases and the resulting queries generated with prisma and postgres.

#### Prisma models
```prisma
model Author {
  id   Int    @id @default(autoincrement())
  name String

  books Book[]
}

model Book {
  id              Int      @id @default(autoincrement())
  title           String
  publicationDate DateTime

  author   Author @relation(fields: [authorId], references: [id])
  authorId Int
}

```

#### Prisma queries
```ts
  // All authors without any books
  await prisma.author.findMany({ where: { books: { none: {} } } });

  // All authors with at least one book
  await prisma.author.findMany({ where: { books: { some: {} } } });

  // All authors where every book was published after 1990-01-01
  await prisma.author.findMany({ where: { books: { every: { publicationDate: { gte: new Date("1990-01-01") } } } } });

  // All authors that have no book with mikro-orm in the title
  await prisma.author.findMany({ where: { books: { none: { title: { contains: "mikro-orm" } } } } });
```

#### Resulting postgres queries
```sql
-- All authors without any books
SELECT "public"."Author"."id", "public"."Author"."name" FROM "public"."Author" WHERE ("public"."Author"."id") NOT IN (SELECT "t0"."id" FROM "public"."Author" AS "t0" INNER JOIN "public"."Book" AS "j0" ON ("j0"."authorId") = ("t0"."id") WHERE (1=1 AND "t0"."id" IS NOT NULL)) OFFSET $1

-- All authors with at least one book
SELECT "public"."Author"."id", "public"."Author"."name" FROM "public"."Author" WHERE ("public"."Author"."id") IN (SELECT "t0"."id" FROM "public"."Author" AS "t0" INNER JOIN "public"."Book" AS "j0" ON ("j0"."authorId") = ("t0"."id") WHERE (1=1 AND "t0"."id" IS NOT NULL)) OFFSET $1

-- All authors where every book was published after 1990-01-01
SELECT "public"."Author"."id", "public"."Author"."name" FROM "public"."Author" WHERE ("public"."Author"."id") NOT IN (SELECT "t0"."id" FROM "public"."Author" AS "t0" INNER JOIN "public"."Book" AS "j0" ON ("j0"."authorId") = ("t0"."id") WHERE ((NOT "j0"."publicationDate" >= $1) AND "t0"."id" IS NOT NULL)) OFFSET $2

-- All authors that have no book with mikro-orm in the title
SELECT "public"."Author"."id", "public"."Author"."name" FROM "public"."Author" WHERE ("public"."Author"."id") NOT IN (SELECT "t0"."id" FROM "public"."Author" AS "t0" INNER JOIN "public"."Book" AS "j0" ON ("j0"."authorId") = ("t0"."id") WHERE ("j0"."title" LIKE $1 AND "t0"."id" IS NOT NULL)) OFFSET $2
```

**Comment by co-sic** [comment]
Hey @B4nan, i'm running in more and more cases there such a feature would be very useful, so it would be nice to know if something like this could be added to mikro-orm in the near future, or if this is nothing what you would consider (or it would be a lot of work to implement with the current setup). 
Cheers.

**Comment by B4nan** [comment]
I already told you I do plan to have something like this, but not really in near future, if you want to see things happen now, you will need to contribute. 

Note that your issue title is asking for something that already works - you can already query entities based on their relations, and you can even use a subquery for the condition (it will join things instead of using subqueries, but that should be rather more performant than prisma's solution anyway). What is not possible directly is the "none/some/every" thingy on to-many properties. You can already query for to-many relations, and it will act as with the "every" modifier. You could negate that via `$not` and get to the "none" behaviour. So the only thing that is not easily doable is the "some" modifier.

**Comment by co-sic** [comment]
I'm sorry, you indeed already said that, i should have looked in the old issue again.

So just to clarify, i testet this behavior to query on to-many properties and for me it behaves like the "some" modifier in both cases (if i negate it with $not/$ne or if i don't use the negation). So the modifiers that are currently not working is "every" and "none". So is this the intended behavior? And will it stay the same way without a breaking change? Because as far is i know there is also no example in the docs for such a query case. 
Or maybe i did something wrong? You can have a look at the example at the bottom, based on the entities i defined in my OP.

> you can already query entities based on their relations, and you can even use a subquery for the condition 
And can you maybe elaborate on this or give me a very small example? I'm not sure how this would look with a subquery. Or do you mean the knex query builder?

```ts
(async () => {
  /** Setup */
  await initOrm();
  await orm.bookRepository.nativeDelete({});
  await orm.authorRepository.nativeDelete({});

  /** Create Entities */
  const author1 = new Author("Author 1");
  
  const author2 = new Author("Author 2");
  new Book(author2, "Foo", new Date(1950, 0, 1));
  new Book(author2, "Foo", new Date(1960, 0, 1));
  
  const author3 = new Author("Author 3");
  new Book(author3, "Foo", new Date(1950, 0, 1));
  new Book(author3, "Foo", new Date(1960, 0, 1));
  new Book(author3, "Bar", new Date(1960, 0, 1));
  new Book(author3, "Bar", new Date(1970, 0, 1));
  
  const author4 = new Author("Author 4");
  new Book(author4, "Foo Bar", new Date(2000, 0, 1));
  new Book(author4, "Foo Bar", new Date(2010, 0, 1));
  
  const author5 = new Author("Author 5");
  new Book(author5, "Foo", new Date(1950, 0, 1));
  
  await orm.entityManager.persistAndFlush([
    author1,
    author2,
    author3,
    author4,
    author5,
  ]);

  /** Queries */
  let results = await orm.authorRepository.find({
    books: { title: "Foo" },
  });
  console.log(results.map((res) => res.name));
  // [ 'Author 2', 'Author 3', 'Author 5' ]

  results = await orm.authorRepository.find({
    $not: { books: { title: "Foo" } },
  });
  console.log(results.map((res) => res.name));
  // [ 'Author 3', 'Author 4' ]

  results = await orm.authorRepository.find({
    books: { title: { $ne: "Foo" } },
  });
  console.log(results.map((res) => res.name));
  // [ 'Author 3', 'Author 4' ]

  results = await orm.authorRepository.find({
    books: { publicationDate: { $gt: new Date(1965, 0, 1) } },
  });
  console.log(results.map((res) => res.name));
  // [ 'Author 3', 'Author 4' ]

  results = await orm.authorRepository.find({
    books: { publicationDate: { $lt: new Date(1955, 0, 1) } },
  });
  console.log(results.map((res) => res.name));
  // [ 'Author 2', 'Author 3', 'Author 5' ]
})();
```

**Comment by co-sic** [comment]
@B4nan sorry for the ping, but would be nice to have a short clarification to my question from above since it contradicts with your earlier answer.

**Comment by B4nan** [comment]
Yeah agreed that the `$not` operator is not that helpful here, we will need the subquery approach most probably. I can also imagine `$count` (or maybe `$size`?) operator that would allow matching by the collection size (so `$none` could be also written as `$count: 0`).

I would do it via operators `$every/$some/$none`. It should be handled on the QB level most probably, that way it will work with EM out of box too. So a good place to start is to write some test case [here](https://github.com/mikro-orm/mikro-orm/blob/master/tests/QueryBuilder.test.ts), add the new operators to list of supported ones [here](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/utils/QueryHelper.ts#L11) and at the type level [here](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/typings.ts#L57). The rest will probably happen in either https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/query/QueryBuilder.ts or https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/query/QueryBuilderHelper.ts (more like in both of them). You might as well need to adjust the `CriteriaNode` layer, where auto-joining happens. Its one of the most complex parts, but we have a lot of tests so you should at least know if things are broken after you change something. Initially I would only care about the QB test suite to be able to iterate faster, once that is all green, proceed to the rest (a good set of edge cases are in issue tests, `yarn test issues` will run only those).

**Comment by B4nan** [comment]
Need to add more tests and clean things up, but #4917 is alive and the tests are passing.
