### ISSUE TITLE
Access QueryBuilder from within subscriber lifecycle hooks

### ISSUE THREAD

**Issue by fandy** [mikro-orm/mikro-orm#2937]
**Is your feature request related to a problem? Please describe.**
Cannot execute native SQL within subscribers, because `args.em` does not contain `createQueryBuilder`.

**Describe the solution you'd like**
```
import { ReviewProduct } from '../review-product/entities/review-product.entity';
import {
  EntityName,
  EventArgs,
  EventSubscriber,
  Subscriber,
} from '@mikro-orm/core';
import { Review } from './entities/review.entity';

@Subscriber()
export class ReviewSubscriber implements EventSubscriber<Review> {
  getSubscribedEntities(): EntityName<Review>[] {
    return [Review];
  }

  async afterCreate(args: EventArgs<Review>): Promise<void> {
    const { rating, product, tribe } = args.entity;

    // args.em.createQueryBuilder is undefined 😢 
    const qb = await args.em.createQueryBuilder(ReviewProduct);

    if (product) {
      const totalReviews = product.reviews.count();
      const totalRatings = qb.select('SUM(rating)');
      product.avgRating = totalRatings / totalReviews;
    }
    console.log(tribe.reviews.count());
  }

  async afterUpdate(args: EventArgs<Review>): Promise<void> {
    // ...
  }
}
```

Something like this is expected. So far I don't believe there's a way to access query builder in lifecycle hooks.

**Comment by B4nan** [comment]
It is there, it is by no chance `undefined`, it is missing only on type level, because core package has no idea of any QB. Learn how to distinguish typescript errors from runtime ones.

```ts
import { EntityManager } from '@mikro-orm/mysql'; // or any other sql driver

async afterCreate(args: EventArgs<Review>): Promise<void> {
  const em = args.em as EntityManager; // now it will be there
}
```

**Comment by fandy** [comment]
It looks like the types aren't well supported:
```
const em = args.em as EntityManager<PostgreSqlDriver>;
```

`Type instantiation is excessively deep and possibly infinite.ts(2589)`

**Comment by B4nan** [comment]
Do you see this when you build your project, or is it coming from vscode by any chance? Because there was a similar report recently because vscode used TS 4.7 nightly.

**Comment by fandy** [comment]
@B4nan I'm seeing this when I build the project in Nest.js:

```
[8:10:01 AM] File change detected. Starting incremental compilation...

src/review/review.subscriber.ts:18:16 - error TS2589: Type instantiation is excessively deep and possibly infinite.

18     const em = args.em as EntityManager<PostgreSqlDriver>;
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[8:10:01 AM] Found 1 error. Watching for file changes.
```

**Comment by mnowaczyk** [comment]
> It is there, it is by no chance `undefined`, it is missing only on type level, because core package has no idea of any QB. Learn how to distinguish typescript errors from runtime ones.
> 
> ```ts
> import { EntityManager } from '@mikro-orm/mysql'; // or any other sql driver
> 
> async afterCreate(args: EventArgs<Review>): Promise<void> {
>   const em = args.em as EntityManager; // now it will be there
> }
> ```

Where is this in the documentation? Why do I need to dig into the source code and do unsafe casts to access a documented functionality?

**Comment by B4nan** [comment]
Good luck with this attitute.
