### ISSUE TITLE
Support default exports for entity classes

### ISSUE THREAD

**Issue by pharophy** [mikro-orm/mikro-orm#294]
**Describe the bug**
When `EntityFactory` creates an entity and `config.discovery.requireEntitiesArray` is false, the module loading for `Entity` doesn't support models defined as default exports.

**Source code**
The source code causing this bug is in the `createEntity()` method here:
```
const path = utils_1.Utils.absolutePath(meta.path, this.config.get('baseDir'));
Entity = require(path)[meta.name];
```

Models that are defined as `export default class` are not supported.  A simple fix here may be checking if meta.key or default exists as a key on `require(path)`.

**Stack trace**
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'prototype' of undefined
    at EntityFactory.createEntity (c:\...\node_modules\mikro-orm\dist\entity\EntityFactory.js:64:45)
    at EntityFactory.create (c:\...\node_modules\mikro-orm\dist\entity\EntityFactory.js:27:29)
    at EntityManager.merge (c:\...\mikro-orm\dist\EntityManager.js:160:80)
    at EntityManager.find (c:\...\node_modules\mikro-orm\dist\EntityManager.js:59:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
...
```

**To Reproduce**
1. Create a model that is the default export of a module.
2. Run application and create a document in a mongo collection
3. Restart application
4. Run a simple query that loads an entity from a MongoDb collection

**Expected behavior**
The module should load regardless of if it's the default export or not.

**Additional context**
N/A

**Versions**
I'm running 3.0.0-rc.5

| Dependency | Version |
| - | - |
| node | ? |
| typescript | ? |
| mikro-orm | ? |
| your-driver | ? |

**Comment by B4nan** [comment]
Default exports are not supported for entities, but sure we can do something about that :]

**Comment by pharophy** [comment]
Even just adding a note to the docs on models may be enough so a newbie doesn't get stuck for a while debugging the issue.

**Comment by B4nan** [comment]
Will be fixed in next RC.
