### ISSUE TITLE
Duplicate index generated on owning side of @OneToOne relations

### ISSUE THREAD

**Issue by ghakko** [mikro-orm/mikro-orm#2942]
There is a bug in the schema generator which creates indexes twice on the foreign key on the owning side of a one-to-one relationship.

Here’s a minimal schema that produces this bug:
```
@Entity() class Foo {
  @OneToOne(() => Bar, b => b.foo, { owner: true, nullable: true }) bar!: IdentifiedReference<Bar>;
  @PrimaryKey() id!: number;
}

@Entity() class Bar {
  @OneToOne(() => Foo, f => f.bar) foo?: IdentifiedReference<Foo>;
  @PrimaryKey() id!: number;
}
```

The generated SQL is:
```
CREATE TABLE `bar` (`id` integer not null primary key autoincrement);
CREATE TABLE `foo` (`id` integer not null primary key autoincrement, `bar_id` integer null, constraint `foo_bar_id_foreign` foreign key(`bar_id`) references `bar`(`id`) on delete set null on update cascade);
CREATE INDEX `foo_bar_id_index` on `foo` (`bar_id`);
CREATE UNIQUE INDEX `foo_bar_id_unique` on `foo` (`bar_id`);
```

“foo_bar_id_index” is redundant.

| Dependency | Version |
| - | - |
| node | 16.14.2 |
| @mikro-orm/core | 5.1.1 |
| @mikro-orm/sqlite | 5.1.1 |

**Comment by B4nan** [comment]
So you say the unique index is enough, right? Because I don't see any duplicate index, there are two indexes with distinct name and type.

**Comment by ghakko** [comment]
Yes, the unique index is enough. There is no need for an additional non-unique index on top of that.
