### ISSUE TITLE
@poperty() does not work with private class property

### ISSUE THREAD

**Issue by ChiefJacob** [mikro-orm/mikro-orm#2944]
**Describe the bug**
you cannot apply `@Property()` decorator to a pivate class property when using `#` syntax to mark the private class property. 

**Stack trace**
```
...
```

**To Reproduce**
1. create an entity using `@Entity()` decorator
2. create a private property of the class using `#privateProperty`
3. add the `@Property ()` decorator above `#privateProperty`

**Expected behavior**
decorator is allowed here.

**Additional context**
This would be useful in order to then be able to have getters with the same naming.

**Versions**

| Dependency | Version |
| - | - |
| node | ? |
| typescript | ? |
| mikro-orm | ? |
| your-driver | ? |

**Comment by B4nan** [comment]
https://mikro-orm.io/docs/entity-constructors#using-native-private-properties
