### ISSUE TITLE
Can't find type preferReadReplicas in typescript

### ISSUE THREAD

**Issue by hibangun** [mikro-orm/mikro-orm#2946]
![image](https://user-images.githubusercontent.com/16166419/159873182-8fbd8b0f-eb8f-4f32-8c65-4e0edf100ad9.png)

How can I solve it?

**Comment by B4nan** [comment]
Dont ignore issue template. You are probably using outdated version.

**Comment by hibangun** [comment]
issue resolved after update the version (5.1.1) thanks @B4nan
