### ISSUE TITLE
create Migration does not pick up change in Enum Options

### ISSUE THREAD

**Issue by ChiefJacob** [mikro-orm/mikro-orm#2976]
**Describe the bug**
create migration does not pick up changes in the case of the enum options

**Stack trace**
```
...
```

**To Reproduce**
1. create an enum 
     ` export enum Type = {
  event = "event",
  meetup = "meetup",
}`

2. have entity use enum through @Enum() decorator 

4.  create migration and migrate up
5.  change the enum options to be in uppercase ` export enum Type = {
  EVENT = "EVENT",
  MEETUP = "MEETUP",
}`

6. create migration and migrate up
7. check database and typecheck of the enum values still expect lowercase options

**Expected behavior**
the database type checks should update to reflect the correct uppercase

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 17|
| typescript | 4|
| mikro-orm | 5.1.1 |
| your-driver | posgresql |

**Comment by B4nan** [comment]
So the problem is only with changing the case, otherwise if you add a new enum item, it picks the change correctly?

**Comment by ChiefJacob** [comment]
Yes that is correct.

**Comment by B4nan** [comment]
Can't reproduce, works fine on my end, tried both with just the schema generator as well as manually in realworld example app with postgres and migrations in place (and both with and without snapshots). Will reopen if you can provide full reproduction.
