### ISSUE TITLE
How to get owner entity at inverse side with bi-direaction one-to-one relation?

### ISSUE THREAD

**Issue by username1103** [mikro-orm/mikro-orm#2978]
Hi, I want to get owner entity in inverse side at one-to-one relation. If this field is public, then I can get owner entity using `populate`. But this field is private, then I can't get owner entity using `populate`..
And I don't want to use `autoJoinOneToOneOwner` option. I want to get owner entity when i want.

**Stack trace**
My Entity
```
./user.entity.ts

@Entity()
export class User {
  @PrimaryKey({ autoincrement: true })
  private id!: number;

  @Property()
  private name!: string;

  @OneToOne({
    entity: "Account",
    wrappedReference: true,
    mappedBy: "user",
  })
  private account?: IdentifiedReference<Account>;

  getId() {
    return this.id;
  }

  getName() {
    return this.name;
  }

  getAccount() {
    return this.account.load();
  }

  setName(name: string) {
    this.name = name;
  }

  setAccount(account: Account) {
    this.account = wrap(account).toReference();
  }
}
```
```
./account.entity.ts

@Entity()
export class Account {
  @PrimaryKey({ autoincrement: true })
  private id: number;

  @Property()
  private number!: string;

  @OneToOne({
    entity: "User",
    inversedBy: "account",
    owner: true,
    wrappedReference: true,
  })
  private user!: IdentifiedReference<User>;

  async getUser() {
    const user = await this.user.load();
    return user;
  }

  setUser(user: User) {
    this.user = wrap(user).toReference();
  }

  setNumber(number: string) {
    this.number = number;
  }
}

```
Test
```
 test("one-to-one select value", async () => {

      const user1 = await em.findOne(User, { id: 1 });
      console.log(user1);
     
      // result: User { id: 1, name: 'test1' }. 
      // So account is undefined in user.getAccount(). So I can't load account entity.
      
      const user2 = await em.findOne(
        User,
        { id: 1 },
        { populate: ["account"] }. -> It is throw error(Type '"account"' is not assignable to type 'keyof User'.ts(2322))
      );
      
    });
```

**Versions**

| Dependency | Version |
| - | - |
| node | 17.7.1 |
| typescript | 4.5.2 |
| mikro-orm | ^5.1.1 |
| your-driver | ^5.1.1 |

**Comment by B4nan** [comment]
You should not be using private properties exactly for this reason, as they cannot be worked with in the TS mapped types. If you need them, only way around it is via type assertions/casting - but you will loose all the strictness that ORM provides. 

> And I don't want to use autoJoinOneToOneOwner option. I want to get owner entity when i want.

That flag is there for getting just the FK, not the whole entity. You don't need it unless you don't care about knowing whether there is an entity or not without loading it. Also you can't lazy load it without this flag, as you don't know the FK which is needed. It has nothing to do with this TS problem you have.
