### ISSUE TITLE
Mikro-orm only inserts first element instead of whole list

### ISSUE THREAD

**Issue by Alwinator** [mikro-orm/mikro-orm#2997]
**Describe the bug**
I have a simple CRUD application. However, when I am inserting a list of elements, only the first one is inserted. 

**Stack trace**
Unfortunately, no error!

**To Reproduce**
I have created a strongly simplified version that still contains the bug. You can find it [here](https://github.com/Alwinator/mikro-orm-insert-bug).

**Expected behavior**
I expect that all four elements are in the database, not just the first one.

**Versions**

| Dependency | Version |
| - | - |
| node | v16.13.1 |
For other versions check the package.json file.

**Comment by B4nan** [comment]
This is already fixed in master. Note that flushing single EM instance will never work in parallel, the tasks get queued and executed sequentially as it is not allowed to work with a single UoW context in parallel. You should fork explicitly if you truly want to run things in parallel:

```ts
public async save(element: Unit): Promise<Unit> {
	const fork = this.em.fork();
    const id = element.id

    // @ts-ignore
    const exists = await fork.findOne(Unit, { id }, )

    if (!exists) {
      // @ts-ignore
      const e = fork.create(Unit, element)
      console.log('Creating', e)
      await fork.persistAndFlush(e)

      return e
    }else{
      return element
    }
  }
```

**Comment by Alwinator** [comment]
@B4nan Thanks!
