### ISSUE TITLE
Cannot populate on `afterFlush` method

### ISSUE THREAD

**Issue by abelland** [mikro-orm/mikro-orm#3005]
**Describe the bug**
when trying to populate an entity's M:1 relation on `afterFlush` method, i get stuck and nothing happens

**Stack trace**
Nothing happens, no error. application just hangs 

**To Reproduce**
```ts
import type { EventSubscriber, FlushEventArgs } from '@mikro-orm/core';
import { Collection, Entity, ManyToOne, MikroORM, OneToMany, PrimaryKey, Property, Subscriber } from '@mikro-orm/core';
import type { SqliteDriver } from '@mikro-orm/sqlite';

@Entity({ tableName: 'customers' })
class Customer {

  @PrimaryKey()
  id!: number;

  @Property()
  name: string = 'Foo';

  // eslint-disable-next-line @typescript-eslint/no-use-before-define
  @OneToMany(() => Order, order => order.customer)
  orders = new Collection<Order>(this);

}

@Entity({ tableName: 'orders' })
class Order {

  @PrimaryKey()
  id!: number;

  @Property()
  value: number = 200;

  @ManyToOne(() => Customer)
  customer!: Customer;

}

@Subscriber()
class OrdersSubscriber implements EventSubscriber<Order> {

  getSubscribedEntities() {
    return [Order];
  }

  async afterFlush(args: FlushEventArgs): Promise<void> {
    const changeSets = args.uow.getChangeSets();

    for (const changeSet of changeSets) {
      if (changeSet.entity instanceof Order) {
        await args.em.populate(changeSet.entity, ['customer']);
      }
    }
  }

}

let orm: MikroORM<SqliteDriver>;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [Order, Customer],
    dbName: ':memory:',
    type: 'sqlite',
  });
  await orm.getSchemaGenerator().refreshDatabase();
});

afterAll(() => orm.close(true));

test('GH issue 3005', async () => {
  const a = new Order();
  a.customer = new Customer();
  await orm.em.fork().persistAndFlush(a);

  const order = await orm.em.findOneOrFail(Order, a);
  order.value = Math.floor(Math.random() * (200 - 1 + 1) + 1);
  await orm.em.flush();
});
```

**Expected behavior**
just having M:1 relation populated

**Additional context**
- On mikro-orm v4.5 `populate` works as expected

**Versions**

| Dependency | Version |
| - | - |
| node | 14.18.3 |
| typescript | 4.5.4 |
| mikro-orm | 5.1.2 |
| your-driver | postgres |

**Comment by B4nan** [comment]
Not reproducible, if you want help, please provide something executable. Closing, will be happy to reopen if you provide failing reproduciton.

**Comment by abelland** [comment]
here's the repo -> https://github.com/abelland/afterflush-populate

i tried to be as concise as possible to help you understand what's going on. take a look at Readme.md file

Thanks!

**Comment by abelland** [comment]
@B4nan any updates on this or any chance to help you finding out the problem? thanks

**Comment by B4nan** [comment]
I tried to look into this a couple of times already, no luck so far. What would help is finding the commit that broke it, I added the test case to the OP so you could use that to bisect the history.

**Comment by B4nan** [comment]
Ok, good news. Guess how many lines of code (without tests) it takes to fix this...

**Comment by abelland** [comment]
lol. Thank you! 😎
