### ISSUE TITLE
Upgrade @mikro-orm/sqlite to sqlite3 v5.0.3+

### ISSUE THREAD

**Issue by jjhbw** [mikro-orm/mikro-orm#3014]
I noticed you changed the sqlite bindings used in @mikro-orm/sqlite to @vscode/sqlite3 (https://github.com/microsoft/vscode-node-sqlite3), which is a fork of https://github.com/TryGhost/node-sqlite3. IMO this was the correct move, as the former library long suffered from poor maintenance.

However, it seems that the good people at Ghost have taken over maintenance from Mapbox, and they already pushed a new maintenance release (https://github.com/TryGhost/node-sqlite3/releases/tag/v5.0.3). This release brings the library into 2022 and solves many annoying (build) issues (including #2991).

You may want to consider switching @mikro-orm/sqlite back to the 'mainline' sqlite bindings.

**Comment by jjhbw** [comment]
Regarding the new maintainers of node-sqlite3, see: https://github.com/TryGhost/node-sqlite3/issues/1572#issue-1203647774

**Comment by B4nan** [comment]
This is more about knex, we dont use the library directly. Feel free to propose this to them first.

**Comment by daniellockyer** [comment]
Knex has been switched back to sqlite3 🙂

**Comment by B4nan** [comment]
Good, will do so too, luckily for us this wont be a breaking change.

**Comment by B4nan** [comment]
So latest dev version is back on `sqlite3`. I will ship new stable soon.
