### ISSUE TITLE
Populate doesn't work with refs

### ISSUE THREAD

**Issue by stephenh** [mikro-orm/mikro-orm#302]
I have a parent/child relationship but populate is not working because the child's `mappedBy`/`ManyToOne` is modeled with an `IdentifiedReference`.

I.e. in the `child`, I have:

```typescript
  @ManyToOne({ entity: () => Parent, wrappedReference: true })
  parent: IdentifiedReference<Parent>;
```

When I try to preload the `OneToMany` collection on the other side of this relation (i.e. loading multiple `Parent`s and using `populate: ["children"]`, none of the `Parent.children` collections are populated correctly b/c this line is failing to match:

```
const items = children.filter(child => child[(prop.mappedBy)] as object === entity);
```

https://github.com/mikro-orm/mikro-orm/blob/master/lib/entity/EntityLoader.ts#L76

Because the `child["parent"]` is trying to match on `entity`, and `entity` is a `Parent` instance, but the `child["parent"]` field is an IdentifiedReference.

**Comment by B4nan** [comment]
Thanks for the report. Will release this early next week.
