### ISSUE TITLE
Allow passing additional arguments to seeders and additional seeders

### ISSUE THREAD

**Issue by vyobukhov** [mikro-orm/mikro-orm#3022]
**Is your feature request related to a problem? Please describe.**
There is a really nice feature to call additional seeders from the main one but it would be really cool to be able to pass additional arguments to seeders.

Let's say we have 3 entities, `Author`, `Post`, `Article`. Author can have both posts and articles. So in the main seeder I create author and then pass it to all seeders that depend on it.

Or I can just pre-generate uuid and then pass this uuid to AuthorSeeder, PostSeeder and ArticleSeeder to create 3 entities in parallel.

**Comment by B4nan** [comment]
I guess we could have a shared context you could use for this use case.

**Comment by onx2** [comment]
Adding arguments to the seeder is what I need _(or maybe I'm not seeing the correct way to do what I want)_. I'd like to be able to seed the database with a specific user (email and password) via arguments.

Sorry to post on an old issue, I can open a new one if you'd like.
