### ISSUE TITLE
MikroORM not updating nested entity

### ISSUE THREAD

**Issue by Alwinator** [mikro-orm/mikro-orm#3026]
**Describe the bug**
I have a nested entity and I want that it is updated when I update my entity using `wrap(e).assign(newRecipe, { mergeObjects: true })` (See [code](https://github.com/Alwinator/mikro-orm-bug/blob/3f265d7d9f9e2c59f907f28003b99996563bd156/src/recipe/recipe.service.ts#L98))

I also tried it with `updateNestedEntities: true`, but unfortunately it didn't work either.

**To Reproduce**
https://github.com/Alwinator/mikro-orm-bug
(Setup Guide: README)

**Expected behavior**
```ts
Actual:
{
  id: 1,
  ingredients: [ { id: 1, quantity: 2, ingredient: { id: 1, name: 'Tomato' } } ],
  name: 'Pizza'
}
Expected:
{
  id: 1,
  name: 'Pizza',
  ingredients: [ { id: 1, quantity: 2, ingredient: { id: 2, name: 'Cheese' } } ]
}
```

**Versions**
| Dependency | Version |
| - | - |
| node | 16.13.1 |
| typescript | 4.3.5 |
| mikro-orm | 5.1.2-dev.38 |
| others | [package.json](https://github.com/Alwinator/mikro-orm-bug/blob/main/package.json) |

**Comment by B4nan** [comment]
`mergeObjects` is for JSON properties, not for entities. `updateNestedEntities: true` is the default in v5.

Your main problem is that you call `assign` not on entity but on POJO, and then you even try to persist it. You need to work with entities. Try it this way:

```ts
  // we use EntityData, as that is what you are actually passing inside - it is not a Recipe entity instance as you had it typed
  public async updateRecipe(data: EntityData<Recipe>): Promise<void> {
    // all we need to do is to load the entity based on PK and call `assign` on it
    const e = await this.recipeRepository.findOne(data.id)
    wrap(e).assign(data) // no need to save the result of assign, it will be the exact same entity reference as you used
    await this.recipeRepository.flush() // and no need to persist anything, the entity is already managed
  }
```

Btw next time I would appreciate _minimal_ reproductions, not a nestjs app :] (Unless it's a nestjs specific problem, but that should be probably filed into the nest adapter repository instead.) Ideally it should be a script, everything in a single file.

Also note that the way you work with the EM is very inefficient, you should aim to call `flush` only once, that way all the queries will get automatically batched, e.g. this is what you should do instead when creating the entities:

```ts
// create entity instances and mark them for persistence
for (const data of ingredients) {
  const e = this.em.create(Ingredient, data)
  this.em.persist(e) // or you could use `em.create(Ingredient, data, { persist: true })` instead
}

// call flush once, will use a single multi insert query
await this.em.flush()
```

Also better not to lie about the types (as you often did in that repro, via casting first to `unknown`, as well as by using `ts-ignore`), dont interchange DTOs with entities, Ingredient !== EntityData<Ingredient>, one has things like entity instance, `Collection`s, `Reference` wrappers, the ohter has only POJOs and plain arrays.

**Comment by Alwinator** [comment]
@B4nan Thank you very much for the tips to improve my code! I am always very thankful for them. Additionally, sorry for pushing a Nest application. I never used MikroORM without Nest, so I didn't think of it. I have fixed everything you mentioned and the bug is unfortunately still there.

**Comment by Alwinator** [comment]
@B4nan The bug is still there! I have reproduced it without NestJS: https://github.com/Alwinator/mikro-orm-bug-without-nest

**Comment by B4nan** [comment]
Yeah I got it reproduced locally already, its a bit more complicated, trying to find a way to make it work as you want.

**Comment by Alwinator** [comment]
@B4nan Thank you very much! :)

**Comment by Alwinator** [comment]
@B4nan Thank you! I just tested your bug fix and it works perfectly!
