### ISSUE TITLE
Support for SSL in Postgres connections

### ISSUE THREAD

**Issue by DmiPet** [mikro-orm/mikro-orm#303]
Hello,

I'm having an issue connecting to a hosted DigitalOcean Postgres server, which requires SSL, but I can't seem to find a way to enable it currently in init() options. Is there a way to do this, or a workaround?

Thanks in advance!

**Comment by B4nan** [comment]
You could probably use `driverOptions` for that (if you can achieve that in knex, then this allows you to pass additional options to knex).

https://mikro-orm.io/docs/configuration/#driver

**Comment by B4nan** [comment]
You could try something like:

```typescript
MikroORM.init({
  // ...
  driverOptions: {
    connection: { ssl: true },
  },
});
```

There are some issues about this in knex's repository, you should take a look there. One suggests to use environment variable for this:

> Workaround which worked for me: set environment variable PGSSLMODE=require. It forces postgres driver to use SSL and it resolved the issue at least in my case. Still waiting for the official patch though.

https://github.com/knex/knex/issues/852

**Comment by B4nan** [comment]
@DmiPet did it work for you?

**Comment by DmiPet** [comment]
Hi @B4nan, thanks so much for the suggestions! Setting environment variable `PGSSLMODE=require` did the trick 👍

**Comment by liaujianjie** [comment]
> @DmiPet did it work for you?

In case anyone else prefers to have their database connection config in the Mikro config, adding these to `driverOptions` works for me:

```js
{
  connection: {
    ssl: true
  }
}
```

**Comment by standup75** [comment]
In case someone comes with a problem on heroku, or getting `UnhandledPromiseRejectionWarning: DriverException: self signed certificate` for some other reason, here is the fix

    driverOptions: {
      connection: { ssl: { rejectUnauthorized: false } },
    },

**Comment by dcsm8** [comment]
@standup75 Thanks, I ended up with the following config

```
driverOptions: {
  ...(process.env.NODE_ENV === 'production' && {
    connection: { ssl: { rejectUnauthorized: false } },
  }),
},
```

**Comment by alex996** [comment]
If you have the self-signed certificate file, it's better to pass its contents rather than set `rejectUnauthorized: false`:

```ts
driverOptions: {
  connection: {
    ssl: {
      ca: fs.readFileSync("./path/to/public.cert"),
    },
  },
},
```

This should fix `Error: self signed certificate in certificate chain`.
