### ISSUE TITLE
ordeBy ignored when used with offset

### ISSUE THREAD

**Issue by kaname-png** [mikro-orm/mikro-orm#3038]
**Describe the bug**
I am trying to paginate an ordered list of items by their creation date "createdAt", the problem is that if I use the offset property, which is to paginate natively with mikro-orm, the order of the items is inverted. I believe that it will be understood better with the images.

With:
```ts
await this.container.db.warnsRepo.findAndCount({ guild_id }, { orderBy: { createdAt: 'DESC' }, limit: Number(size) });
```

![image](https://user-images.githubusercontent.com/56084970/164336442-cbf6e51f-ee31-48b4-9227-7fa1f7d6022d.png)

With:
```ts
await this.container.db.warnsRepo.findAndCount(
      { guild_id },
      { orderBy: { createdAt: 'DESC' }, limit: Number(size), offset: Number(page) * Number(size) }
);
```

![image](https://user-images.githubusercontent.com/56084970/164336659-807fcd50-4843-4b0e-89b2-6ff7b3251299.png)

**To Reproduce**
1. Save documents in db with createdAt property as ISO Date.
2. Search documents with offset and orderBy options
3. See results

**Expected behavior**
Get the same order of items with or without the offset option.

The tests shown have exactly the same code, only the offset option is added or removed.

**Additional context**
This is the structure of the items in the database.

```json
{
  "_id": {
    "$oid": "61f819f399e439a4a5d46429"
  },
  "createdAt": {
    "$date": "2022-01-31T17:18:43.628Z"
  },
  "updatedAt": {
    "$date": "2022-01-31T17:18:43.628Z"
  },
  "user_id": "510190913146847272",
  "guild_id": "858410190414938143",
  "reason": "[kaname-png#6666]: dame a mi kanna",
  "channel_id": "858410191141994551",
  "case_id": "b171cq",
  "action": 7
}
```

**Versions**

| Dependency | Version |
| - | - |
| node | v18.0.0 |
| typescript | 4.6.3 |
| mikro-orm | 5.1.2 |
| your-driver | mongodb |

**Comment by B4nan** [comment]
Please dont use images, I need to see code and data - reproductions - not images of your app, in a language I dont understand, based on database I dont have, in a UI I can't really trust (how can I know this is not a UI issue?). 

I will close this, here is a passing test case so you know its not that simple as you are trying to tell me. Will be happy to reopen with a reproduction - minimal, but complete, ideally as a test case similar to this one.

```ts
const author = new Author('a', 'e');
const book1 = new Book('Part 1', author);
book1.createdAt = new Date('2022-03-23 11:00:00');
const book2 = new Book('Part 2', author);
book2.createdAt = new Date('2022-03-23 12:00:00');
const book3 = new Book('Part 3', author);
book3.createdAt = new Date('2022-03-23 13:00:00');

await orm.em.fork().persist(author).flush();

// no offset
const [res, count] = await orm.em.fork().findAndCount(Book, {}, { orderBy: { createdAt: 'DESC' }, limit: 3 });
expect(count).toBe(3);
expect(res.map(b => b.title)).toEqual(['Part 3', 'Part 2', 'Part 1']);

// with offset
const [res2, count2] = await orm.em.fork().findAndCount(Book, {}, { orderBy: { createdAt: 'DESC' }, limit: 3, offset: 1 });
expect(count2).toBe(3);
expect(res2.map(b => b.title)).toEqual(['Part 2', 'Part 1']);
```

I would appreciate if you first try to debug things you see before blindly reporting them here. If you would actually try to isolate this problem, you would see yourself its not like that. This feels like you saw a problem in a UI you build, and went directly here telling me about issues in the ORM 🤷 Please try to do the extra step, debug problems you see yourself, and report only things you actually believe are bugs in the ORM, after you rule out problems in your code.
