### ISSUE TITLE
Ensure schema exists when creating migrations table

### ISSUE THREAD

**Issue by B4nan** [mikro-orm/mikro-orm#3039]
**Describe the bug**
When using custom schema name in postgres, migrator tries to create the migrations table without ensuring the target schema exists.

**To Reproduce**
1. specify custom schema
2. try to use migrations when the schema does not exist yet
3. profit

**Expected behavior**
Schema should be created/ensured before we try to create the migrations table.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.10 |
| mikro-orm | 5.1.2 |
| postgres | 5.1.2 |

**Comment by carlswann** [comment]
When is this fix going to be published?

**Comment by B4nan** [comment]
Every commit is published to npm.
