### ISSUE TITLE
Literal "order" of Custom Pivot Entity properties breaks the join query

### ISSUE THREAD

**Issue by wyemun** [mikro-orm/mikro-orm#3040]
**Describe the bug**
When using _Custom Pivot Entity_ , the order of the two foreign keys matters. 

**To Reproduce**
1. Create the following entity schema:
```ts
export class Price {
  @PrimaryKey({type: 'uuid'})
  id: string = uuid.v4()
  
  @ManyToMany({ entity = () => Title, pivotEntity: () => SomePivot }, 'prices')
  titles = new Collection<Title>(this)
}

export class Title{
  @PrimaryKey({type: 'uuid'})
  id: string = uuid.v4()
  
  @ManyToMany({ entity = () => Title, pivotEntity: () => SomePivot }, 'titles')
  prices= new Collection<Price >(this)
}

export class SomePivot {
  @PrimaryKey({type: 'uuid'})
  id: string = uuid.v4()
  
  @ManyToOne({ entity = () => Title, fieldName: 'title_id' })
  title: Title
  
  @ManyToOne({ entity = () => Price , fieldName: 'price_id' })
  price: Price
}
```
2. Then when you run the following query:
```ts
const data = await em.findOne(Price, {id: '<id here>'}, {populate: ['titles']})
```
it will then return empty array.

3. However if you reverse the order of the properties in `SomePivot`:
```ts
export class SomePivot {
  @PrimaryKey({type: 'uuid'})
  id: string = uuid.v4()

 @ManyToOne({ entity = () => Price , fieldName: 'price_id' })
  price: Price
  
  @ManyToOne({ entity = () => Title, fieldName: 'title_id' })
  title: Title
}
```
The result will be retrieved correctly.

**Expected behavior**
Should return the related populated data correctly in custom pivot entity solution regardless of the order of the property

**Additional context**
Upon checking the debug log, you can see the query being done incorrectly:
```sql
select 
  "t0".*, "s1"."price_id" as "fk__price_id", "s1"."title_id" as "fk__title_id"
from
  "titles" as "t0"
left join "some_pivots" as "s1" on
  "t0"."id" = "s1"."title_id"
where
  "s1"."title_id" in ('<id here>') # <-- where this should be "s1"."price_id" instead
```

**Versions**

| Dependency | Version |
| - | - |
| node | 16.14.2 |
| typescript | 4.6.3  |
| mikro-orm | 5.1.2 |
| database | postgres |

**Comment by B4nan** [comment]
Yes, the order is important, you need to have the owning side defined first. This is documented:

> The pivot table entity needs to have exactly two many-to-one properties, **where first one needs to point to the owning entity** and the second to the target entity of the many-to-many relation.

https://mikro-orm.io/docs/next/collections#custom-pivot-table-entity

This needs to be explicit, we can't map things based on type, as it is totally valid to have m:n relation targeting the very same entity on both ends.

**Comment by B4nan** [comment]
Also note that your entity definition is invalid, you can't mix the two approaches of decorator signatures. Either use all the parameters, or just the first one as options object. Right now your second parameter is ignored and you have two owning sides defined.

**Comment by B4nan** [comment]
It's true we could match the entities and fix the order in metadata automatically if the types are different, and keep this requirement one for M:N between same entity types. And I will definitely add a validation to the decorators so what you did throws, I though this is obvious but you are the second person in this week who tried to use it wrongly, and its easy to validate this, so let's do that.
