### ISSUE TITLE
Nested property query incorrectly adjusted to primary key query.

### ISSUE THREAD

**Issue by Juullo** [mikro-orm/mikro-orm#3054]
**Describe the bug**
When using findOne and querying a nested object (jsonb) which contains a key identical to the primary key of the queried entity, the where query gets adjusted incorrectly.

**To Reproduce**
```ts
import { Entity, MikroORM, PrimaryKey, Property } from '@mikro-orm/core';
import type { SqliteDriver } from '@mikro-orm/sqlite';

@Entity()
class User {

  @PrimaryKey()
  id!: string;

  @Property()
  data!: { id: string };

}

let orm: MikroORM<SqliteDriver>;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [User],
    dbName: ':memory:',
    type: 'sqlite',
    debug: true,
  });
  await orm.getSchemaGenerator().createSchema();
});

afterAll(async () => {
  await orm.close(true);
});

test(`GH issue 3054`, async () => {
  const r = await orm.em.findOne(User, {
    data: {
      id: 'test',
    },
  });
});

```

**Expected behavior**
A query will be composed where User.data.id is checked for value 'test'.

**Actual behavior**
A query will be composed where User.data is checked for value 'test'.

**Additional context**
When debugging I can tell that the where object gets adjusted in QueryHelper.processWhere method.

**Versions**

| Dependency | Version |
| - | - |
| node | v17.4.0 |
| typescript | 4.5.5 |
| mikro-orm | 5.1.2 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
Note that you need to mark the property as JSON, otherwise this won't work. But there is indeed a bug specifically when using `id` property in the JSON object, which gets wrongly inlined when processing the query.

```ts
  @Property({ type: 'json' }) // or `type: t.json`
  data!: { id: string };
```
