### ISSUE TITLE
Factory / Seeder: makeOne & createOne expect wrong type for IdentifiedReference (wrappedReference)

### ISSUE THREAD

**Issue by tobiaskraus** [mikro-orm/mikro-orm#3062]
**Describe the bug**
We used the syntax described in [the docu: "Reference Wrapper"](https://mikro-orm.io/docs/entity-references#better-type-safety-with-referencet-wrapper) and now we cannot satisfy the typeScript types anymore when creating data in our seeder.

**To Reproduce**

```ts
@Entity()
export class Child {
    @ManyToOne({
        entity: () => Parent,
        wrappedReference: true, // new
    })
    parent: IdentifiedReference<Parent>; // before we had: `parend: Parent` and it worked with the Seeders
}

const child = new ChildFactory(orm.em).make({
    ...otherProps,
    parent: parent, // TS Error
});

// -> TS Error:
// Type 'Parent' is not assignable to type '{ id: number; } & Reference<Parent>'.
// Type 'Parent' is missing the following properties from type 'Reference<Parent>': entity, load, set, unwrap, and 5 more.
```

**The same with:**
- `Factory.create`
- `Factory.createOne`
- `Factory.make`
- `Factory.makeOne`

**Expected behaviour**
I want to be able to create an entity with a ManyToOne Relationship by simply passing the other entity or its id.
Just like it works when calling:

```ts
this.orm.em.create(Child, {...otherProps, parent});
```

**Suggestion**
We could give the methods in Factory<T> similar types as entityManager.create:

```diff
- makeOne(overrideParameters?: Partial<T>): T;
+ makeOne(overrideParameters?: RequiredEntityData<T>): T;
```

**Versions**

| Dependency | Version |
| - | - |
| mikro-orm | 5.1.1 |

**Comment by B4nan** [comment]
Good catch, agreed on the suggestion, PR welcome :]
