### ISSUE TITLE
Migration generates primary key column as "jsonb" when using typedef

### ISSUE THREAD

**Issue by javiermrz** [mikro-orm/mikro-orm#3080]
**Describe the bug**
If we have:
```typescript
export type Id = number;

@Entity()
export class User {
  @PrimaryKey()
  id: Id;

  @Property()
  name: string;
}
```
instead of:
```typescript
@Entity()
export class User {
  @PrimaryKey()
  id: number;

  @Property()
  name: string;
}
```

the column generated in the migration will be `"id" jsonb not null` instead of `"id" serial primary key`.

**To Reproduce**
1. Create a couple files with the following code:
```typescript
// id.ts
export type Id = number;

// user.ts
@Entity()
export class User {
  @PrimaryKey()
  id: Id;

  @Property()
  name: string;
}
```
2. Generate migration: `npx mikro-orm migration:create --initial`
3. Go to the generated Migration file, and check the id column type. It will state `"id" jsonb not null`.

**Expected behavior**
The migration should interpret the type of the property as a number.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.9.1 |
| typescript | 4.3.5 |
| mikro-orm | 5.1.3 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
How does your ORM config look like?

**Comment by javiermrz** [comment]
Not that I know of. This is my config:

```typescript
export default {
  type: 'postgresql',
  host: process.env.DB_HOST,
  port: parseInt(process.env.DB_PORT),
  password: process.env.DB_PASS,
  user: process.env.DB_USERNAME,
  dbName: process.env.DB_NAME,
  entitiesTs: ['src/**/*.model.ts'],
  entities: ['dist/**/*.model.js'],
  migrations: {
    path: './src/db/migrations',
  },
}
```

**Comment by B4nan** [comment]
That's weird, I can't reproduce this with reflect metadata 🤷 

Please provide executable repro

**Comment by javiermrz** [comment]
I'm importing 'reflect-metadata' too :thinking: 

I managed to reproduce it in a reduced repo: https://github.com/javiermrz/mikroorm-bug-report/blob/main/docker-compose.yml

Just run:
`npm i`
`docker-compose up -d`
`npx mikro-orm migration:create --initial`

You should see the generated migration file in `src/db/migrations`

**Comment by B4nan** [comment]
Interesting, it fails because the type is defined in another file. Unfortunately, this is a won't-fix, as it's the reflect-metadata package giving us wrong type (`object`). If you define the `Id` type in the same file, it works fine, but apparenly types defined elsewhere won't be resolved.
