### ISSUE TITLE
Wrong order when selecting related items

### ISSUE THREAD

**Issue by Alwinator** [mikro-orm/mikro-orm#3083]
**Describe the bug**
When selecting elements (in my case recipes) from the database the related elements (in my case steps) have the wrong order.

**To Reproduce**
https://github.com/Alwinator/mikro-orm-order-bug (See README and console output)

**Expected behavior**
I expect that the steps are in the same order as they are in the database (and as I created them)

```ts
{
  id: 1,
  name: 'Roast Beef with Onions',
  steps: [
    { id: 13, text: 'New1', recipe: 1 },
    { id: 14, text: 'New2', recipe: 1 }
  ]
}
```

**Actual behavior**
For some reason, they are in the wrong order when using MikroORM

```ts
{
  id: 1,
  name: 'Roast Beef with Onions',
  steps: [
    { id: 14, text: 'New2', recipe: 1 },
    { id: 13, text: 'New1', recipe: 1 }
  ]
}
```

**Versions**

| Dependency | Version |
| - | - |
| node | v16.13.1 |
| others | [package.json](https://github.com/Alwinator/mikro-orm-order-bug/blob/main/package.json) |

**Comment by B4nan** [comment]
You are not specifying the `orderBy` option. The items won't necesarily have the same order as you specified in when inserting - it is a 1:m collection, it's virtual and based only on the m:1 relations (the FKs) - there is no natural order of them.

**Comment by Alwinator** [comment]
@B4nan But shouldn't the elements be ordered by the id by default?

**Comment by B4nan** [comment]
Nope, but you can specify default order in the 1:m decorator if you want.

**Comment by Alwinator** [comment]
@B4nan Sounds good, how do I do that?

**Comment by B4nan** [comment]
Hmm, maybe open the docs, and check how it can be done? :] Or maybe check the interface for the decorator options? I am sure you can find it

**Comment by Alwinator** [comment]
@B4nan Okay! Thanks for your help!
