### ISSUE TITLE
populate against existing entities

### ISSUE THREAD

**Issue by stephenh** [mikro-orm/mikro-orm#310]
When writing business logic that is something like:

```
processChildren(children: Child[]): Promise<void> {
  await Promise.all(children.map(async child => {
    const parent = await child.parent.load()
  });
});
```

I've got an N+1 loading the `parent` for each child. I'd like to do something like `populate: { parent } ` but that only works if I'm the one who loaded the children / i.e. called `find`.

Would it be easy/possible to add a `populate` method directly to `EntityManager`, i.e.:

```
em.populate(children, ["parent"]);
```

?

Or is there an existing/better way to do this that I'm missing?

Thanks!

**Comment by B4nan** [comment]
`EntityLoader` is what you are looking for, you can use it manually:

https://mikro-orm.io/docs/nested-populate/#using-entityloader-manually

We could also expose this in the EM API for sure.

**Comment by stephenh** [comment]
@B4nan ah great, thanks! I'd thought I'd seen something like that while debugging something earlier, but yeah just didn't know where to look. Adding it to EM would be great I think for discoverability.

I was also going to say, technically this is a case where having DataLoader built-in would make this loop/map operation N+1 safe "for free", but I have to admit, after realizing how often you write `await` when every field/collection traversal is a `Promise`, it gets pretty tedious.

So, even if adding the populate hint looks boilerplate/annoying, it actually frees up using synchronous methods after the fact:

```
processChildren(children: Child[]): Promise<void> {
  await em.populate(children, "parent");
  children.forEach(child => {
    const parent = child.parent.get()
  });
});
``` 

Is actually more pleasant/ergonomic. Dunno, just thinking trade-offs/pros/cons... And, yeah, realizing that `await`'ing every little thing can get annoying.

**Comment by stephenh** [comment]
Not sure if this is possible or not, but fwiw using the `EntityLoader` API:

```
  await loader.populate("Project", Object.values(projects), ["children"]);
```

It'd be nice if `"Project"` could be inferred, like look at the array given as the current-2nd argument, and use `array[0].__meta.entityName` to infer/guess the entity name? (And if the array is empty, `populate` can early return anyway.)

**Comment by B4nan** [comment]
I don't want to change the `EntityLoader` signature now (BC), but we can add that new method to EM that would work like this.

**Comment by stephenh** [comment]
This is great, thanks @B4nan !
