### ISSUE TITLE
Calling Collection.init() twice loads duplicate children

### ISSUE THREAD

**Issue by stephenh** [mikro-orm/mikro-orm#312]
If `Collection.init` is called twice on the same collection, before `await`ing for the 1st call to resolve, the collection will end up with duplicate entries.

Test case:

```
    const ctx = await getTestContext();
    const { em } = ctx;
    const author = new Author(em, { firstName: "a", lastName: "b" });
    const post = new Post(em);
    author.posts.add(post);
    await em.flush();
    em.clear();

    const author2 = await em.findOneOrFail(Author, { id: 1 });
    const p1 = author2.posts.init();
    // Uncommenting this line makes the test pass
    // await p1
    const p2 = author2.posts.init();
    await Promise.all([p1, p2]);

    // fails with 2 b/c the post is in the collection twice
    expect(author2.posts.getItems().length).toEqual(1);
```

I.e. it looks like `init`'s "am I already initialized?" check waits for the promise to be resolved, instead of flagging "I am _starting_ to initialize" as soon as the first `init` is called, so that the 2nd `init` can immediately return / or ideally return the same promise that was returned from the 1st `init` call.

Fwiw this looks like an odd use case in the ^ reproduction (i.e. "...why are you calling `init` twice, don't do that"), but it can happen pretty easily when implementing a graphql resolver, because two different field resolvers (say `Author.numberOfPosts` and `Author.mostPopularPost`) may both access the `author.posts` collection as part of there implementation details (and so both separately call `.init()`, and the same GraphQL/Apollo servers work is that they call of requests fields in parallel / i.e. in the same event loop, and then `await` the promises that each field resolver returned.

**Comment by stephenh** [comment]
I can attempt a PR for this if you'd like; two questions:

1) I would probably add an `initPendingPromise` field to `Collection` and have that set here [1] and then any caller where `initalized` is false but `initPendingPromise` is set would just return that existing promise.

2) What test file would be good to add this to?

...somewhat musing, but another potential option would be if the `loadFromPivotTable` could catch "oh I'm already loading the pivot table"...i.e. maybe with something like DataLoader which would also batch multiple pivot table loads together. :-) 

Also very happy to have you just fix this directly.

**Comment by B4nan** [comment]
I am not sure I like this, multiple init calls might have different params, so technically your 2 resolvers might do different `init` calls. Every call will reinitiaze the collection based on the parameters (e.g. you could load a filtered collection). It is a valid use case to call `init` on already loaded collection and it not just a no-op. 

> I.e. it looks like init's "am I already initialized?" check waits for the promise to be resolved

It is `async` method, it always returns a promise, so yes, it always has to be resolved to return anything. 

> Fwiw this looks like an odd use case in the ^ reproduction (i.e. "...why are you calling init twice, don't do that"), but it can happen pretty easily when implementing a graphql resolver, because two different field resolvers (say Author.numberOfPosts and Author.mostPopularPost) may both access the author.posts collection as part of there implementation details (and so both separately call .init(), and the same GraphQL/Apollo servers work is that they call of requests fields in parallel / i.e. in the same event loop, and then await the promises that each field resolver returned.

This whole use case sounds weird, loading the whole collection just to get one item (or even number of items) from that. You should use aggregate fields for that (https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/cookbook/aggregate-fields.html#using-an-aggregate-field).

> ...somewhat musing, but another potential option would be if the loadFromPivotTable could catch "oh I'm already loading the pivot table"...i.e. maybe with something like DataLoader which would also batch multiple pivot table loads together. :-)

Only SQL drivers use pivot tables, this would not fit mongo driver (at least for the inverse side collections). Also, `EntityLoader` is here for this reason already, you can use it to populate multiple collections too.

**Comment by B4nan** [comment]
Btw I am able to solve this simply by moving the `this.items.length = 0;` line that resets the collection right before it gets populated again (`this.items.push(...items);`). Obviously still 2 SQL queries will be fired.

**Comment by stephenh** [comment]
> I am not sure I like this, multiple init calls might have different params

Oh huh. Well, fwiw, I am not sure I like that. :-) 

I didn't realize that init could take params like order by and where. That just seems like a fundamentally bad idea, b/c if one part of my code `init`s with `whereClauseA` and another part of the code is like "oh hey the collection is already loaded I'll just call `getItems()`" ...but it's actually a subset of the entities, that would be very surprising and a source of preventable bugs.

I think some sort of Collection method that allowed easy `populate` / `order` / `where` params would be handy if it returns a net-new collection every time (b/c it really would execute a SQL query per method call, essentially), i.e. not effect future `Collection.getItems` calls, but at that point its just a utility/helper method for doing one-off queries and not fundamentally affecting the behavior of the core `Collection`/`Collection.getItems` itself (to the current caller and any future caller).

> This whole use case sounds weird, loading the whole collection just to get one item
>  (or even number of items) from that. You should use aggregate fields

Well, I mean, yes, you're suggesting denormalizing (caching) some derived values so that they are calculated on write instead of on read, but that's a trade-off that should be chosen on a per-field basis (based on the cost/complexity/frequency of reads/writes) and not across-the-board "never loop over a collection on read", which is essentially what you're saying. Fwiw I do have several aggregate fields in our schema, and a few derived values which I don't want to make aggregate fields, and I'd like to generally be trusted to know which trade-off is appropriate for which use case. :-) 

Also/pedantically, using aggregate fields would just move this problem to the write-side, i.e. if I want to calculate two derives aggregates on `Parent`, and my implementation style happens to say "derive all aggregates for `Parent` in parallel" (because maybe some of them are expensive), multiple of my "derive aggregate x/y/z" routines could `.init()` the same collection "at the same time" and hit this same "now the collection is double/triple loaded" behavior.

Per my original comment, I think the primary reason I'm hitting is not any esoteric/wrong schema modeling decisions, and just that the GraphQL resolver implementation pattern is parallel-by-default.

I.e. in most "I'm just a REST endpoint" webapps, there is a "linear" thread of "do a/b/c" granted with some awaits while doing `a`, some awaits while doing `b`, etc., but its still essentially linear, unless the programmer very explicitly tries to split-up the request in multiple chunks of work on `Promise.all`s them together at the end.

The GraphQL impl pattern is inherently "screw it, let's do a/b/c all at once, and `Promise.all` at the end", which is actually pretty smart if a/b/c potentially come from different data stores, require different wire calls, etc.

So, I get why I'm the first one hitting this, but I assert within the realm of implementing GQL resolvers (or even a "more parallel" REST endpoint, although granted most people don't bother to do that), this is not a weird/uncommon use case.

**Comment by B4nan** [comment]
> Oh huh. Well, fwiw, I am not sure I like that. :-)

Well, on the other hand, others have requested that. Personally I am not using it, pretty much because of what you said, but I can understand some might want this sometimes and it is much more convenient to have this API that to have to fallback to query builder. 

The thing is, that `Collection.init()` for me serves only the single entity purpose - I am working with single instance of an entity and want to ensure its collection is initialized. If, like in your use case, I have multiple entities, I would use `EntityLoader` instead. It will handle the n+1 problem, not like when you call `init` multiple times. 

I am still inclined more to the solution I proposed (with moving the `items` array reset just before we populate it). I feel like if we should support this "multiple call returning single promise" behaviour, it would be strange to do it only here in the `Collection.init()` method.

**Comment by B4nan** [comment]
I will close this now, but feel free to continue the discussion.

Just to make it clear - the actual bug with duplicities in collection items is now resolved. If you call `init` multiple times in parallel, it will resolve in multiple queries. And this behaviour is the same as with e.g. `Reference.init()` and other `Reference` helpers, as well as if you call `em.findOne()` multiple times in parallel. There is not a single place in the ORM where it would "cache" the promise and return it if you try to call it again before its resolved.
