### ISSUE TITLE
Fix: Remove optional chaining on strings to support older nodejs versions

### ISSUE THREAD

**Issue by ilterugur** [mikro-orm/mikro-orm#3157]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@mikro-orm/core@^5.1.4` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@mikro-orm/core/utils/EntityComparator.js b/node_modules/@mikro-orm/core/utils/EntityComparator.js
index 520654f..471a570 100644
--- a/node_modules/@mikro-orm/core/utils/EntityComparator.js
+++ b/node_modules/@mikro-orm/core/utils/EntityComparator.js
@@ -264,7 +264,7 @@ class EntityComparator {
             ret += ` && entity${entityKey} != null`;
         }
         if (isRef) {
-            ret += ` && (entity${entityKey} == null || entity${entityKey}.__helper?.hasPrimaryKey())`;
+            ret += ` && (entity${entityKey} == null || entity${entityKey}.__helper ? entity${entityKey}.__helper.hasPrimaryKey() : undefined)`;
         }
         return ret;
     }
@@ -432,7 +432,7 @@ class EntityComparator {
             // We might be comparing PK to object, in case we compare with cached data of populated entity
             // in such case we just ignore the comparison and fallback to `equals()` (which will still mark
             // it as not equal as we compare PK to plain object).
-            const cond = `last${this.wrap(prop.name)}.toHexString?.() !== current${this.wrap(prop.name)}.toHexString?.()`;
+            const cond = `last${this.wrap(prop.name)}.toHexString ? last${this.wrap(prop.name)}.toHexString() : undefined !== current${this.wrap(prop.name)}.toHexString ? current${this.wrap(prop.name)}.toHexString() : undefined`;
             return this.getGenericComparator(this.wrap(prop.name), cond);
         }
         return `  if (!equals(last${this.wrap(prop.name)}, current${this.wrap(prop.name)})) diff${this.wrap(prop.name)} = current${this.wrap(prop.name)};`;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by B4nan** [comment]
No plans to support older versions. Use older version of MikroORM if you need old node version support.

**Comment by ilterugur** [comment]
> No plans to support older versions. Use older version of MikroORM if you need old node version support.

Almost every shared web hosting support nodejs up to version 12 but people can make incompatible packages work with their server using bundlers. 

The problem here is bundlers like esbuild can't transform strings like this.

MikroORM actually works fine on older nodejs versions using bundlers except this code block. You can support node v12 users easily if you just commit this small patch.

**Comment by B4nan** [comment]
I doubt this change would be enough, optional chaining is used on _many_ places, not just here. We compile the whole project for node 14+.

Node 12 already reached its end of life on 30.4.2022, its no longer officially supported version, it won't recieve any security updates and you should not use it anymore. I really don't care about supporting it.

https://nodejs.org/en/about/releases/
