### ISSUE TITLE
EntityManager.create() should return Loaded<> ManyToOne/OneToMany

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#3159]
**Is your feature request related to a problem? Please describe.**
This is more an annoyance with testing than normal code. Much of my service layer requires `Loaded<>` entities so that it forces the consumer to run populate upstream as much as possible for performance benefits. But when using the `create` API, none of the relationships appear as loaded.

**Describe the solution you'd like**
```typescript

function doSomething(entity:Loaded<MyChild, 'parent'>){

}

const parent = manager.create(MyParent, {});

const child = manager.create({
  parent
});

doSomething(child);

```

I expect `child` to be of type `Loaded<MyChild, 'parent'>` and not just `MyChild`

**Describe alternatives you've considered**
At the moment, you are effectively forced to run a flush/populate to make the object show as loaded which is more verbose and potentially a slight perf hit.

**Comment by parisholley** [comment]
here is an example of how I'd expect typing to match implementation:

```typescript
type DetectLoadedEntityData<I, D, K> = K extends keyof D
  ? D[K] extends I
    ? LoadedReference<LoadedCreation<I, D[K]>>
    : D[K] extends I[]
    ? LoadedCollection<I>
    : D[K]
  : never;

type LoadedCreation<T extends AnyEntity<T>, D extends EntityData<T>> = T & {
  [K in keyof T]: T[K] extends IdentifiedReference<infer I> | Collection<infer I> ? DetectLoadedEntityData<I, D, K> : T[K];
}

interface EntityManager {
  create<T, D extends RequiredEntityData<T>>(entityName: EntityName<T>, data: D): LoadedCreation<T, D>;
}
```

**Comment by parisholley** [comment]
in testing, simply setting the options `{ initialized: true, newEntity: true }` allows me to effectively build an object graph via a unit test and pass it down (so long as I use the `LoadedCreation` type above). i could see maybe an alternative to using `Loaded` is some type of `Hydrated` interface (if Loaded implies some state management is happening behind the scenes and would break things semantically).

**Comment by B4nan** [comment]
> At the moment, you are effectively forced to run a flush/populate to make the object show as loaded which is more verbose and potentially a slight perf hit.

Uh, at the moment you need type casting, why would you even involve UoW if all you have is a typing issue? Or are we talking about something else than just typings issue?

```ts
const child = manager.create({
  parent
}) as Loaded<Child, 'parent'>;
```

FYI we had `New` type for exactly this, and it was removed as it caused some issues (don't remember what exactly, but I am sure we can find that in the git history).

> in testing, simply setting the options { initialized: true, newEntity: true } allows me to effectively build an object graph

That's the default for `em.create()`, both `initialized: true` and `newEntity: true`.

**Comment by parisholley** [comment]
> Uh, at the moment you need type casting, why would you even involve UoW if all you have is a typing issue? Or are we talking about something else than just typings issue?

As a library consumer, I wouldn't want to make the assumption that I could just cast the result without hitting potential runtime issues. Additionally, this proposal is more useful for building nested object graphs (especially when you have a mix of required and optional many-to-ones). Having to write out the object graph AND build a nested type graph is very verbose.

> that's the default for em.create(), both initialized: true and newEntity: true

It isn't the default when dealing with nested 1:M/Collection, you have to explicitly set those parameters for it to recursively apply down the tree, otherwise you will hit a bunch of initialized collection errors, even though they were populated with data  on a new entity.

This is the implementation I use today in my tests, I boot up Mikro with connect = false but then pull the entity factory out so I can use it outside of system tests for deep graph hydration.

```typescript
export function createMikro<T, D extends EntityData<T>>(entityName: EntityName<T>, data: D): LoadedCreation<T, D> {
  const factory = getTestContainer().get<MikroORM>(MikroORM).em.fork({ clear: true }).getEntityFactory();

  const created = factory.create(entityName, data, { initialized: true, newEntity: true });

  return created as unknown as LoadedCreation<T, D>;
}
```

This is a simple example of what I use currently to produce a bunch of "fixture" methods, like so:

```typescript
export function fixtureMember(data?: EntityData<MemberMikro>) {
  return createMikro(MemberMikro, {
    id: v4(),
    company: 'vendor',
    timezone: TimeZone.US_EASTERN,
    ...data,
  });
}
```

Because I use the `LoadedCreation<T, D>` type, my test code can do things like this without flushing or persistence

```typescript
const parent = createMikro(ParentEntity, {
 name: 'parent',
 children: [
  { name: 'child' }
 ]
});

const children = parent.children.get();
```

It also has utility in non-test code, when you want to operate on a non-persisted object that is mutated through a few service layers before it gets flushed.

**Comment by parisholley** [comment]
spent about half the day trying to find a clean and performant (typescript compiler) way to pull this off but I don't think there is a good way to do it. think it is easier to just add a populate parameter to my createMikro call and hard cast it and call it a day.

**Comment by parisholley** [comment]
@B4nan do you think any of your v6 changes with Loaded may make this worth taking a look at again?

**Comment by B4nan** [comment]
We can give it a shot, I'd also like to give another chance to the type-safe partial loading. Maybe the fix for `Loaded` type assignability will be enough for the issues that were present with the initial implementation with `New` type.

**Comment by parisholley** [comment]
> I'd also like to give another chance to the type-safe partial loading

are you referring to #3443 ?

**Comment by B4nan** [comment]
Yep
