### ISSUE TITLE
Would it possible to get reliable stack trace from Mikro-ORM SQL errors?

### ISSUE THREAD

**Issue by CyriacBr** [mikro-orm/mikro-orm#316]
**Is your feature request related to a problem? Please describe.**

I've been working with TypeORM for a long time but if there's something I've always hated, it is the unreliable stack trace when a method from a repository throws. Today I decided to give Mikro-ORM a go but sadly it outputs unreliable stack trace as well.
Here's an example:
```ts
import { MikroORM } from "mikro-orm";
import mikroOrmConfig from "../mikro-orm.config";
import { Food } from "../src/modules/foods/foods.entity";

(async () => {
  const orm = await MikroORM.init(mikroOrmConfig);
  try {
    const foods = await orm.em.find(
      Food,
      {},
      {
        fields: ["foo"]
      }
    );
    console.log("foods :", foods);
  } catch (error) {
    console.log('Caught');
    console.error(error);
  }
})();
```
This code will fail with the following stack trace:
```
Caught
{ Error: Unknown column 'e0.foo' in 'field list'
    at Packet.asError (/mnt/0CC5166B0CC5166B/Work/diets_book/server/node_modules/mysql2/lib/packets/packet.js:712:17)
    at Query.execute (/mnt/0CC5166B0CC5166B/Work/diets_book/server/node_modules/mysql2/lib/commands/command.js:28:26)
    at Connection.handlePacket (/mnt/0CC5166B0CC5166B/Work/diets_book/server/node_modules/mysql2/lib/connection.js:417:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/mnt/0CC5166B0CC5166B/Work/diets_book/server/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/mnt/0CC5166B0CC5166B/Work/diets_book/server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/mnt/0CC5166B0CC5166B/Work/diets_book/server/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: 'Unknown column \'e0.foo\' in \'field list\'' }
```

Notice how the stack trace is foreign to my actual code, and even to Mikro-ORM source code.
That makes debugging really painful when you have many services interacting with each other. It becomes a hard task to know which repository method the error comes from. Plus, the debugging tooling in Node is not that great...

**Describe the solution you'd like**

Not knowing the internal of Mikro-ORM, I don't know if it's feasible and if it's not actually related to the driver I'm using, but I propose to catch SQL related errors from the EntityManager in order to have clean stack traces.

**Describe alternatives you've considered**

A possible solution, but detrimental to code readability, is to wrap every usage of a repository with a try/catch block and output `console.trace()` to get a reliable stack trace.
```ts
(async () => {
  const orm = await MikroORM.init(mikroOrmConfig);
  try {
    const foods = await orm.em.find(
      Food,
      {},
      {
        fields: ["foo"]
      }
    );
    console.log("foods :", foods);
  } catch (error) {
    console.error(error);
    console.trace(); 
  }
})();
```

**Comment by CyriacBr** [comment]
Alright, I've actually digged a bit and the problem actually comes from my driver, `mysql2`.
https://github.com/sidorares/node-mysql2/issues/1067

It appears that `mysql` does not have such issues, however MikroORM doesn't support it as knex throws:
```
Knex: run
$ npm install mysql2 --save
Cannot find module 'mysql2'
Error: Cannot find module 'mysql2'
```

Could it be possible to make Mikro-ORM support `mysql`? https://github.com/mysqljs/mysql

**Comment by B4nan** [comment]
This is not really a problem of the ORM, this comes from the actual driver that is used from Knex. ORM already does catch possible errors from the drivers/connectors. On the other hand, you are right we could instantiate new error instance so you have at least the trace to the ORM code and not this mess. I will experiment with that a bit. 

Btw knex offers some kind of async stack traces option, you could try using that: http://knexjs.org/#Installation-asyncStackTraces

```typescript
MikroORM.init({
  driverOptions: { asyncStackTraces: true }, // you should keep it disabled in production
});
```

You could also try that library suggested in the mysql2 issue you linked: https://github.com/mattinsler/longjohn

> Could it be possible to make Mikro-ORM support mysql? https://github.com/mysqljs/mysql

You can write the driver yourself if you want. I am not planning to add more drivers myself, definitely not ones that are not supported by knex. Maybe someone already did write a driver for knex for `mysql`, then you could easily reuse that. 

But looking at knex's docs, they say this actually is supported. So all you need to do is create new implementation of the mysql driver (pretty much the same as what is present in the ORM). The only difference should be here https://github.com/mikro-orm/mikro-orm/blob/master/lib/connections/MySqlConnection.ts#L7

**Comment by CyriacBr** [comment]
> Btw knex offers some kind of async stack traces option, you could try using that

It works! Thanks a lot.
