### ISSUE TITLE
`Type instantiation is excessively deep and possibly infinite.` in TS 4.7

### ISSUE THREAD

**Issue by ddadaal** [mikro-orm/mikro-orm#3161]
**Describe the bug**

`MikroORM.init<MySqlDriver>({})` reports `Type instantiation is excessively deep and possibly infinite.` in TS 4.7.

![image](https://user-images.githubusercontent.com/8363856/170858204-382d6c02-cb18-4448-867b-37c2ae5d7af4.png)

I saw [in a discussion thread](https://github.com/mikro-orm/mikro-orm/discussions/3068#discussioncomment-2639793) that such errors have been reported before, but it seems no action has been taken to resolve it. Now since TS 4.7 has released and more projects are adopting it, perhaps this bug should be resolved asap.

**To Reproduce**

Just call `MikroORM.init<MySqlDriver>()` just like in the documentation in a TS 4.7 project.

This is a repo for reproduction: https://github.com/ddadaal/mikro-orm-ts4.7

**Expected behavior**

No error should be reported.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.15.0 |
| typescript | 4.7.2 |
| mikro-orm | 5.1.4 |
| @mikro-orm/mysql | 5.1.4 |

**Comment by ddadaal** [comment]
I saw this issue has been resolved in master https://github.com/mikro-orm/mikro-orm/commit/06b6e4ead56ce8a8429e707492a1e190291d7f2c. Looking forward to the next release!

**Comment by B4nan** [comment]
You can use the dev version already, every commit to master is published.

**Comment by ddadaal** [comment]
Yes but I am using pnpm workspace but pnpm does not resolve @mikro-orm/core to `5.1.5-dev.12` even if it is specified in package.json. Maybe it has something to do with pnpm's peer dependency resolution. Currently I have to use TS 4.6.3 for that project. I believe it can be solved when 5.1.4 is officially released. Thanks!

**Comment by B4nan** [comment]
Yes, peer deps are unfotunately not handled correctly by lerna for canary builds, let's hope it will get better given there are new maintainers. 

But I am sure you can ignore/force that with `pnpm`, just like you can with `yarn`.

**Comment by ddadaal** [comment]
Ah I just found out pnpm supports [`overrides`](https://pnpm.io/package_json#pnpmoverrides), which seems to be able to solve this problem. I am going to try it out. Thanks!
