### ISSUE TITLE
Custom types are not handled properly when fields are qualified with a table alias

### ISSUE THREAD

**Issue by lagnat** [mikro-orm/mikro-orm#3172]
**Describe the bug**
Consider a QueryBuilder join such as this:
```
        qb.joinAndSelect('Foo', 'x', {
            e1.someField: 'abc'
        }, 'leftJoin');

```

`QueryHelper` tries to find the property using the full key, which in this case would be `e1.someField`. 

```const prop = meta?.properties[key];```

That results in prop being `null` and `processCustomType()` is not called.

**Stack trace**
None

**To Reproduce**

```ts
  test('aliased join condition', () => {
    const sql1 = orm.em.createQueryBuilder(Book2, 'b')
      .select('*')
      .where({ 'a.born': new Date('1990-03-23') })
      .getFormattedQuery();
    expect(sql1).toBe("select `b`.*, `b`.price * 1.19 as `price_taxed` from `book2` as `b` where `a`.`born` = '1990-03-23'");

    const sql2 = orm.em.createQueryBuilder(Book2, 'b')
      .select('*')
      .joinAndSelect('author', 'a', { 'a.born': new Date('1990-03-23') })
      .getFormattedQuery();
    expect(sql2).toBe("select `a`.*, `b`.`uuid_pk` as `b__uuid_pk`, `b`.`created_at` as `b__created_at`, `b`.`title` as `b__title`, `b`.`price` as `b__price`, `b`.price * 1.19 as `b__price_taxed`, `b`.`double` as `b__double`, `b`.`meta` as `b__meta`, `b`.`author_id` as `b__author_id`, `b`.`publisher_id` as `b__publisher_id` from `author2` as `a` inner join `book2` as `b` on `a`.`id` = `b`.`author_id` and `a`.`born` = '1990-03-23'");
  });
```

**Expected behavior**
I would expect `QueryHelper` to strip off the table alias before trying to lookup the propery, and the custom type behavior would work.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 4.18.3 |
| typescript | 4.6.4 |
| mikro-orm | 5.1.5 |
| your-driver | mysql |

**Comment by lagnat** [comment]
Correction:  Stripping off the table alias wouldn't be enough.  It would have to lookup the alias to find the proper metadata as well.

**Comment by B4nan** [comment]
`QueryHelper` does not know anything about aliases, it does not know QB class even exists, so this will need to be fixed elsewhere most probably.

**Comment by lagnat** [comment]
I was just looking at that.  Considered adding `aliasMap` to `ProcessWhereOptions` and sending over a PR.  Is that palatable?

**Comment by B4nan** [comment]
Yeah I guess we can do that :] Its not perfect but it will be probably the fastest way without much code duplication (we still need to duplicate [this method](https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/query/QueryBuilderHelper.ts#L540-L546)).

**Comment by B4nan** [comment]
That looks quite good, made some perf improvements so we dont need regexes on such hot path, but other than that all tests are passing. Thanks!
