### ISSUE TITLE
ManyToMany relationship between different schemas

### ISSUE THREAD

**Issue by diegopaiva1** [mikro-orm/mikro-orm#3177]
## Describe the bug
`ManyToMany` relationship between entities from different schemas generates SQL for entities of the same schema.

## Use case

We have a multi-tenant architecture where each tenant is represented by a schema in the DBMS (Postgres).

![schemas](https://user-images.githubusercontent.com/32985519/171686484-e6331070-3b83-4e68-83e3-d139df9a6ec6.png)

There is a `public` schema for general purpose data that doesn't belong to any tenant, although every schema have the same table structure.

The following UML diagram shows the use case we are currently trying to model inside MikroORM.
  
![Main](https://user-images.githubusercontent.com/32985519/171703679-5b4cf2f9-c990-4b4f-afde-85963524c575.jpg)

1. Every tenant have their own users, e.g., `tenant_0000000001.users` and `tenant_0000000002.users`;
2. Every user have an `AccessProfile`, which is defined within each tenant schema, e.g. `tenant_0000000001.access_profiles`;
3. There is a relationship between `AccessProfile` and `Permission`. However, permissions live inside the `public` schema (`public.permissions`) because they should be the same for every tenant;
4. `AccessProfilePermissions` is the association entity generated from that relationship, and every tenant configure it their own manner according to their access profiles. So we have `tenant_0000000001.access_profile_permissions`, etc.

#### Entities
---
`user.entity.ts` (User):

```ts
import { Entity, Reference, PrimaryKey, Property } from '@mikro-orm/core';
import { UserAccessProfile } from '@/modules/auth/domain/user-access-profile.entity';

@Entity({ tableName: 'users', schema: '*' })
export class User {
  @PrimaryKey()
  id: number;

  @Property()
  accessProfileId: number;

  @ManyToOne()
  accessProfile: Reference<UserAccessProfile>;
}
```

`user-acess-profile.entity` (AccessProfile):

```ts
import { Collection, Entity, ManyToMany, OneToMany, PrimaryKey, Property } from '@mikro-orm/core';
import { Permission } from '@/modules/auth/domain/permission.entity';
import { User } from '@/modules/user/domain/user.entity';
import { AccessProfilePermission } from './access-profile-permission.entity';

@Entity({ tableName: 'access_profiles', schema: '*' })
export class UserAccessProfile {
  @PrimaryKey()
  id: number;

  @OneToMany(() => User, (user) => user.accessProfile)
  users: Collection<User> = new Collection<User>(this);

  @ManyToMany({ entity: () => Permission, pivotEntity: () => AccessProfilePermission })
  permissions: Collection<Permission> = new Collection<Permission>(this);
}
```
`permission.entity.ts` (Permission):

```ts
import { Entity, PrimaryKey, ManyToMany, Collection } from '@mikro-orm/core';
import { AccessProfilePermission } from './access-profile-permission.entity';
import { UserAccessProfile } from './user-access-profile.entity';

@Entity({ tableName: 'permissions', schema: 'public' })
export class Permission {
  @PrimaryKey()
  id: number;

  @ManyToMany({ entity: () => UserAccessProfile, pivotEntity: () => AccessProfilePermission })
  accessProfiles: Collection<UserAccessProfile> = new Collection<UserAccessProfile>(this);
}
```
`access-profile-permission.entity.ts` (AccessProfilePermissions):

```ts
import { Entity, ManyToOne } from '@mikro-orm/core';
import { Permission } from './permission.entity';
import { UserAccessProfile } from './user-access-profile.entity';

@Entity({ tableName: 'access_profile_permissions', schema: '*' })
export class AccessProfilePermission {
  @ManyToOne({ primary: true })
  accessProfile: UserAccessProfile;

  @ManyToOne({ primary: true })
  permission: Permission;
}
```

#### Trying to fetch user permissions
---
```ts
async function getPermissions(id: number) {
  const userRepository = instance.em.getRepository(User);

  const user = await userRepository.findOne({ id }, { populate: ['accessProfile'] });
  const permissions = await user.accessProfile.permissions.init();

  return permissions.getItems(); // will return empty collection because of the generated query
}
```

## Expected behavior

I expected that the piece of code `const permissions = await user.accessProfile.permissions.init()` generated the following SQL query:

```sql
SELECT
  "p0".*,
  "t1"."permission_id" AS "fk__permission_id",
  "t1"."access_profile_id" AS "fk__access_profile_id"
FROM
  "public"."permissions" AS "p0"
LEFT JOIN
  "tenant_0000000001"."access_profile_permissions" AS "t1"
ON
  "p0"."id" = "t1"."permission_id"
WHERE
  "t1"."access_profile_id" in (1) -- when the desired user id is 1
```

That is, get permissions from `public` and the access profile permissions from `tenant_0000000001`.

## Actual behavior

This is the query that is being generated:

```sql
SELECT 
  "p0".*, 
  "a1"."permission_id" AS "fk__permission_id", 
  "a1"."access_profile_id" AS "fk__access_profile_id" 
FROM 
  "public"."permissions" AS "p0"
LEFT JOIN 
  "public"."access_profile_permissions" AS "a1" -- here is the problem, it fetches access profiles permission from the public schema (which is empty), i don't know why
ON 
  "p0"."id" = "a1"."permission_id" 
WHERE 
  "a1"."access_profile_id" in (1) -- when the desired user id is 1
```

## Versions

| Dependency | Version |
| - | - |
| node | 16.13.0 |
| typescript | 4.7.2 |
| mikro-orm | 5.1.5 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
Have you tried it with a regular m:n, without custom pivot table entity?

**Comment by diegopaiva1** [comment]
> Have you tried it with a regular m:n, without custom pivot table entity?

Yes. I thought that defining a custom pivot entity with defined schema would force to use it, but it didn't work. It seems, in this case, wildcard schema it's not being replaced by what it is defined in `MikroORM.init()` options.

**Comment by B4nan** [comment]
So does it work without the custom pivot table entity or not?

**Comment by diegopaiva1** [comment]
Nope!

**Comment by diegopaiva1** [comment]
Sure. I am gonna make one and when it's ready I'll leave it here.
