### ISSUE TITLE
duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by productdevbook** [mikro-orm/mikro-orm#3210]
**Describe the bug**
I am getting error while sending database seed data.  countries added but dont add `states` 

**Stack trace**
```
NULL, NULL) returning "id" - duplicate key value violates unique constraint "country_pkey"
    at Parser.parseErrorMessage (/home/productdevbook/Documents/GitHub/nestjs-realworld-example-app/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/productdevbook/Documents/GitHub/nestjs-realworld-example-app/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/productdevbook/Documents/GitHub/nestjs-realworld-example-app/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/productdevbook/Documents/GitHub/nestjs-realworld-example-app/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 186,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (id)=(1) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'country',
  column: undefined,
  dataType: undefined,
  constraint: 'country_pkey',
  file: 'nbtinsert.c',
  line: '663',
  routine: '_bt_check_unique'
}
```

**To Reproduce**
tree: bug

https://github.com/productdevbook/nestjs-realworld-example-app/tree/bug

1. docker compose run
2. posgtresql `CREATE EXTENSION IF NOT EXISTS "uuid-ossp";` create
3. npx mikro-orm migration:up
4. npx mikro-orm seeder:run --class=DatabaseSeeder
5. repeat
6. npx mikro-orm seeder:run --class=DatabaseSeeder

**Versions**

| Dependency | Version |
| - | - |
| node | v16.15.1 |
| typescript | 4.7.3 |
| mikro-orm | 5.2.0 |
| your-driver | postgres |

**Comment by Langstra** [comment]
In your seeder it seems that you are creating new country entities with the same primary key. This will result in duplicate key entries. 

You should reuse the entities you created earlier. Those are the entities that you persisted before and the orm knows. To optimize it a little more you could also create the country entities first, then attach the states and then persist and flush.

**Comment by productdevbook** [comment]
The first countries are saving in the database. Then when adding to the state it is add the with country id and getting out of the error.

**Comment by Langstra** [comment]
Yes, as I said before, you are doing this:
```ts
const a = new Country({
        id: Number(element.country_id),
      })

      dataState.country = wrap(a).toReference()
```

You are creating a new country, with the same primary key. This is not the same attaching an existing entity. To attach an existing entity you could do something like this.

```ts
dataState.country = Reference.create(arrayData.find(c => c.id === element.country_id));
```

**Comment by productdevbook** [comment]
```
dataState.country = Reference.create(arrayData.find(c => c.id === element.country_id));
``` 

Country ID available for states csv. The database country is the same. Is it not possible to save without searching for Array?

```dataState.country = element.country_id``` 
how to example used ? (because your database has this)

**Comment by productdevbook** [comment]
```
    const data2 = new Country()
      data2.id = Number(element.country_id)
      dataState.country = Reference.create(data2)
```

example used some problem

**Comment by productdevbook** [comment]
I still haven't figured it out, it doesn't work
