### ISSUE TITLE
`Cannot find module 'ts-node'` when `npx mikro-orm debug` is run

### ISSUE THREAD

**Issue by vowfood** [mikro-orm/mikro-orm#322]
**Describe the bug**
When I run `npx mikro-orm debug`, I get the error `Error: Cannot find module 'ts-node'`. I can resolve this by manually installing `ts-node` is this error resolved.

**Stack trace**
```
(node:18870) UnhandledPromiseRejectionWarning: Error: Cannot find module 'ts-node'
Require stack:
- /path/to/my_project/node_modules/mikro-orm/dist/cli/CLIHelper.js
- /path/to/my_project/node_modules/mikro-orm/dist/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Function.configure (/path/to/my_project/node_modules/mikro-orm/dist/cli/CLIHelper.js:48:13)
    at async /path/to/my_project/node_modules/mikro-orm/dist/cli.js:15:19
(node:18870) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18870) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
1. Create a Node project
2. Install MikroORM and Postgres support with: `npm i -s mikro-orm pg`
3. Add `useTsNode` flag and path to `mikro-orm.config.ts` file as per [Installation & Usage](https://mikro-orm.io/docs/installation/) page.
4. Run `npx mikro-orm debug`

**Expected behavior**
I _believe_ that `ts-node` should not need to be installed manually, as per the guide. Either the guide is missing a step or this is a bug.

**Versions**

| Dependency | Version |
| - | - |
| node | 12.14.1 |
| typescript | 3.7.5 |
| mikro-orm | 3.1.0 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
That is on purpose, you need to install `ts-node` yourself if you want to use it. If you do not have `useTsNode` flag enabled, it won't be used.

**Comment by soroushjp** [comment]
This is the same author as @vowfood , I accidentally used the company account instead of this personal one.

I can go ahead and make a PR for the docs, I have one other addition there as well.

**Comment by soroushjp** [comment]
Forget I said anything, you already beat me to it! Thank you for amazing maintenance work on a fantastic package @B4nan.

**Comment by B4nan** [comment]
Thanks for the warm words! 👍
