### ISSUE TITLE
Option to enable undefined as a No-Action.

### ISSUE THREAD

**Issue by FelipeCavichiolliSilvestre** [mikro-orm/mikro-orm#3222]
## Problem
Undefined and Null are different values, and should not be treated as if they were the same, my reasoning is: while undefined is the DEFAULT value when the variable has not been assigned Null is EXPLICITY, you are defining the absence of a value.

When using MikroORM they are treated in the same way, wich is a problem when you are receiving optional inputs from the user that has a different structure than your Database Entities.

## Example
In a GET route you would have optional query params, and some params will naturally be undefined. That causes a problem in the following code:

```typescript
  const users = await em.find(User, { name: req.query.username });
```
If req.query.username is undefined, it will trigger a SQL command finding all users where name is NULL :

```sql
select `u0`.* from `user` as `u0` where `u0`.`name` is null
```

I also believe that wrap(<entity>).assign(<data>) should ignore undefined values. That type of configuration would 

## Solution
Ideally undefined should be treated as a no action as default, but this would be a breaking change, so just a boolean option like "ignoreUndefined" in mikro-orm.config.ts would be enough.

**Comment by B4nan** [comment]
>   const users = await em.find(User, { name: req.query.username });

Interpretting this as just `em.find(User, {})` is a no-go for me, that would bring very bad security issues to your app. If you want this behaviour, define your own helper and call it before you pass in the query (e.g. in a middleware if you want it as a default behaviour). Btw you should validate your inputs too, this also opens room for another security issues (e.g. if you use some middleware that parses your query into objects, users can easily change such condition to use some `$or` decorator and return something else than anticipated.

**Comment by FelipeCavichiolliSilvestre** [comment]
My inputs are validated, the example it's just a over simplification of the actual app. Besides that type of "injection" i don't see how simply interpretting { name: undefined } as { } is such a security reason, since i'm validating the input and ALLOWING you filter by name optionally.

**Comment by FelipeCavichiolliSilvestre** [comment]
In my opnion "undefined" is not a filter, when you are making a GET request and you do not specify a query parameter it does not mean that you want the field to be empty.
GET /users means "get all users" and not "get all users where name is empty".
My argument is simply that, this incongruence between what a REST API is expected to do and what the MikroORM do, leads to workarounds, what I'm suggesting is the posibility to treat only null as a query, opposed to null and undefined.

About the security issue, It would only has one if I could not control when, where and how I allow such undefined values, which is what I'm doing.
