### ISSUE TITLE
getReference of the Primary resolves to never when id?: number is used

### ISSUE THREAD

**Issue by bobwade** [mikro-orm/mikro-orm#3224]
When id is set with ?, i.e. `id?: number`, `getReference` of the Primary resolves to `never`
However when specifying the type of `PrimaryKeyType` it works as expected e.g.

`
@PrimaryKey()
id?: number;
[PrimaryKeyType]: number;
`

**Comment by B4nan** [comment]
Thanks for the report, but please dont ignore issue template.
