### ISSUE TITLE
Type 'MongoDriver' does not satisfy the constraint 'IDatabaseDriver<Connection>'.

### ISSUE THREAD

**Issue by kevindavee** [mikro-orm/mikro-orm#3227]
**Describe the bug**
I'm trying to initialize MikroORM with MongoDB Driver. But got a Typescript error if I specify the types.

The error is

```
Type 'MongoDriver' does not satisfy the constraint 'IDatabaseDriver<Connection>'.
  Types of property 'loadFromPivotTable' are incompatible.
```

**Code**
```
export const init = async () => {
  const options: Options = {
    entities: [Product],
    dbName: process.env.DB_NAME,
    clientUrl: process.env.MONGO_URL,
    type: 'mongo'
  };

  const orm = await MikroORM.init<MongoDriver>(options);

  entityManager = orm.em;
}
```

**Expected behavior**
No red lines in Typescript compilation.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.13.0 |
| typescript | 4.7.4 |
| mikro-orm | 5.2.0 |
| mongo-driver | 5.2.0 |

**Comment by B4nan** [comment]
Not reproducible. Ensure you have all orm packages on the same versions.
