### ISSUE TITLE
$unset field with OneToOne relationship for mongo driver?

### ISSUE THREAD

**Issue by SDemonUA** [mikro-orm/mikro-orm#3233]
**Describe the bug**
It seems any approach to unset one-to-one field will result in null value and then will violate unique index.

**To Reproduce**
1. Create 2 entities with set one-to-one field
2. Update entities to reset one-to-one field
3. Second update will fail

**Expected behavior**
It should be possible to unset one-to-one fields

**Versions**

| Dependency | Version |
| - | - |
| node | 16 |
| typescript | 4.4 |
| mikro-orm | 4.5.9 |
| mongodb | 4.5.9 |

**Comment by B4nan** [comment]
You should upgrade to latest before reporting anything. There wont be any updates to v4.

Related discussion with a workaround [here](https://github.com/mikro-orm/mikro-orm/discussions/3132).

**Comment by B4nan** [comment]
Lets keep this open, I agree this is a valid problem that should work out of box.
