### ISSUE TITLE
Allow propagation of `add` operation on M:N collections to not initialized owning sides

### ISSUE THREAD

**Issue by alexbadm** [mikro-orm/mikro-orm#3240]
Linking entities from the inverse side doesn't work when the owning side is not initialized.

**To Reproduce**

```ts
import { Collection, Entity, ManyToMany, MikroORM, PrimaryKey, Property } from '@mikro-orm/core';
import type { SqliteDriver } from '@mikro-orm/sqlite';

type SquadType = 'GROUND' | 'AIR';

@Entity()
export class Soldier {

  @PrimaryKey()
  id!: number;

  @Property()
  firstName!: string;

  @Property()
  lastName!: string;

  @ManyToMany({ entity: 'Squad' })
  squads = new Collection<Squad>(this);

}

@Entity()
export class Squad {

  @PrimaryKey()
  id!: number;

  @Property()
  type!: SquadType;

  @Property()
  formedAt!: Date;

  @Property({ nullable: true })
  disbandedAt?: Date;

  @ManyToMany({ entity: 'Soldier', mappedBy: 'squads' })
  soldiers = new Collection<Soldier>(this);

}

let orm: MikroORM<SqliteDriver>;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [Soldier, Squad],
    dbName: ':memory:',
    type: 'sqlite',
  });
  await orm.getSchemaGenerator().createSchema();
});

afterAll(async () => {
  await orm.close(true);
});

test(`GH issue 3240`, async () => {
  const luke = orm.em.create(Soldier, {
    firstName: 'Luke',
    lastName: 'Skywalker',
  });

  const leia = orm.em.create(Soldier, {
    firstName: 'Leia',
    lastName: 'Organa',
  });

  await orm.em.persistAndFlush([luke, leia]);
  orm.em.clear();

  const soldiers = await orm.em.find(Soldier, {});

  const squad = orm.em.create(Squad, {
    type: 'AIR',
    formedAt: new Date(),
    soldiers,
  });

  await orm.em.persistAndFlush(squad);
  orm.em.clear();

  const fetchedSquad = await orm.em.findOneOrFail(
    Squad,
    { type: 'AIR' },
    { populate: ['soldiers'] },
  );
  expect(fetchedSquad.soldiers).toHaveLength(2);

  await orm.close();
});
```

**Versions**
| Dependency | Version |
|-----------|----------|
| node | 16.11.1 |
| typescript | 4.7.3 |
| mikro-orm | 5.1.5 |

**Comment by B4nan** [comment]
The owning side needs to be initialized, then it will work fine. This is definitely documented, the question is whether we still need this requirement (originally there was no way to add things to not-initialized collection, but that is no longer true).

```ts
const soldiers = await orm.em.find(Soldier, {}, { populate: ['squads'] });
const squad = orm.em.create(Squad, {
    type: 'AIR',
    formedAt: new Date(),
    soldiers,
});
```

<img width="655" alt="image" src="https://user-images.githubusercontent.com/615580/175017312-17b3cda6-f2d8-409c-a700-6bd9417197f2.png">

https://mikro-orm.io/docs/collections#working-with-collections

**Comment by wasd171** [comment]
Potentially it could also be solved with an ESLint plugin for mikro-orm :)

**Comment by B4nan** [comment]
If we can detect this, we can also fix it. The problem is in detecting it without false positives.

**Comment by wasd171** [comment]
Do decorators store information about owning side on the field itself? If yes, we should be able to check it in runtime when assigning properties

**Comment by B4nan** [comment]
This is much more complex. You want to propagate to owning sides, but _not always_.

**Comment by wasd171** [comment]
But for a first step we could always throw an error when assignment is done from non-owning side? This would at least not fail silently, even though it will not be a complete solution

**Comment by B4nan** [comment]
Nope, we could not.

**Comment by wasd171** [comment]
In what cases should we *not* propagate changes to the owning side?

**Comment by B4nan** [comment]
Looks like the trick was just to propagate taking snapshots too, this way we can get rid of the only unwanted side effect.
