### ISSUE TITLE
docs: search not works in latest (current / stable) version

### ISSUE THREAD

**Issue by drackp2m** [mikro-orm/mikro-orm#3243]
In [this url](https://mikro-orm.io/versions) the search engine (powered by Algolia) not works.

But for another version as for example for [next](https://mikro-orm.io/docs/next/installation) or [5.1 version](https://mikro-orm.io/docs/5.1/installation) works perfectly.

Is not a dramatical problem but is uncomfortable.

**Comment by B4nan** [comment]
Works fine for me 🤷

**Comment by B4nan** [comment]
Thats because I was releasing new docs version, it will get reindex automatically during today.

**Comment by drackp2m** [comment]
I didn't know there was an indexing process, or in this case, it took so many hours to complete. So, I'm very sorry to have distracted you unnecessarily.

Have a nice day.

**Comment by B4nan** [comment]
No probs, its good to know things are broken, I can issue the reindex manually, but it happens once a week on thrusday :] 

Would be great to automate this, but given how often I need this, its not that big deal...
