### ISSUE TITLE
Mikro-ORM reports connecting to DB in logs when this is not the case

### ISSUE THREAD

**Issue by soroushjp** [mikro-orm/mikro-orm#325]
**Describe the bug**
With `debug: true` provided, Mikro-ORM outputs:

```
MikroORM successfully connected to database some_database on postgres://@localhost:5432
```

However, this database is not actually connected.

**To Reproduce**
1. Call `MikroORM.init` with `debug: true` and database not online.

**Expected behavior**
Either `MikroORM.init` should error or the console message should be changed to not falsely claim it has connected to DB. Based on discussion at #230 , I think the latter change should be made.

**Versions**

| Dependency | Version |
| - | - |
| node | 12.14.1 |
| typescript | 3.7.5 |
| mikro-orm | 3.1.0 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
I guess we should make the call, so it behaves the same with all drivers (as mongo driver does fail when the db is not alive - this lazyness comes from knex, in v2 it was working this way).

**Comment by B4nan** [comment]
So the problem is that throwing an error would be a BC break. Currently you can use schema generator to create the schema together with the database, and there it would now throw an error when initializing the ORM to get the schema generator. I will at least change the logged message.

**Comment by soroushjp** [comment]
Good catch on BC break. Thanks for the logging fix here @B4nan !
