### ISSUE TITLE
nullable embeddable is undefined after hydration

### ISSUE THREAD

**Issue by andrey-hohlov** [mikro-orm/mikro-orm#3258]
It seems this bug https://github.com/mikro-orm/mikro-orm/issues/3063 is still actual.

I found place where problem happens: https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/hydration/ObjectHydrator.ts#L251

Generated hydration code:

```javascript
if (data.vessel != null) { // <- property value is not null nor undefined
  if (entity.vessel == null) {
    entity.vessel = factory.createEmbeddable("Vessel", data.vessel, {
      newEntity,
      convertCustomTypes,
    });
  }
  // other fields hydration...
} else if (data.vessel === null) { // <- property value is null
  entity.vessel = null;
}
```

Property ```vessel``` doesn't exist in data. After hydration it's ```undefined```.  Because we don't check for this case.

_It doesn't save embeddable field with null value to the database (Mongo). Maybe it should be topic of new issue._

```typescript
@Embeddable()
export class TradeVessel {
  @Property()
  imo: string;

  constructor(imo: string) {
    this.imo = imo;
  }
}

@Entity()
export class Trade {
  @Embedded(() => TradeVessel, { object: true, nullable: true })
  vessel: TradeVessel | null = null;
}
```

**Versions**

| Dependency | Version |
| - | - |
| node | v17.4.0 |
| typescript | 4.3.5 |
| mikro-orm | 5.2.0 |
| mongodb | 4.7.0 |

**Comment by B4nan** [comment]
This is a mongo specific problem and it is not really related to hydration - if the value is stored in database as `null`, it will be correctly hydrated as `null`. Next time I would appreciate if you share more details than this and focus on what you see, not what other issues are about, as they are often unrelated. Problem here is _not_ hydration of what is in the database, but storing of the `null` value on embeddable to the database.

```ts
import { Embeddable, Embedded, Entity, MikroORM, PrimaryKey, Property } from '@mikro-orm/core';
import { ObjectId } from 'bson';

@Embeddable()
export class TradeVessel {

  @Property()
  imo: string;

  constructor(imo: string) {
    this.imo = imo;
  }

}

@Entity()
export class Trade {

  @PrimaryKey()
  _id!: ObjectId;

  @Embedded(() => TradeVessel, { object: true, nullable: true })
  vessel: TradeVessel | null = null;

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [Trade],
    dbName: 'mikro_orm_test_3258',
    type: 'mongo',
    debug: true,
  });
  await orm.getSchemaGenerator().refreshDatabase();
});

afterAll(() => orm.close(true));

beforeEach(() => orm.em.nativeDelete(Trade, {}));

test('hydration works fine', async () => {
  await orm.em.getDriver().nativeInsertMany('Trade', [ { vessel: { imo: '123' } }, { vessel: null } ]);

  const t = await orm.em.find(Trade, {});
  expect(t[0].vessel?.imo).toBe('123');
  expect(t[1].vessel).toBeNull(); // works
});

test('storing does not', async () => {
  const t1 = new Trade();
  t1.vessel = new TradeVessel('123');
  const t2 = new Trade(); // this will get saved as just empty object, not as `{ vessel: null }` and that is the problem
  await orm.em.fork().persistAndFlush([t1, t2]);

  const t = await orm.em.find(Trade, {});
  expect(t[0].vessel?.imo).toBe('123');
  expect(t[1].vessel).toBeNull(); // fails
});
```

**Comment by andrey-hohlov** [comment]
@B4nan  I'm sorry about the way I reported this issue. I just tried to realise what it doesn't work as I expected
_Or maybe I do something wrong, it's my first experience with MikroORM._

I reported hydration because when I replace ```if (data.vessel === null)``` with ```if (data.vessel == null)``` it starts working.

Maybe, issue with saving to database has the same nature https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/utils/EntityComparator.ts#L360

**Comment by B4nan** [comment]
Yeah it will be most probably something in the `EntityComparator` as that is where we build the entity payloads. Although its weird this does not reproduce with SQL drivers...
