### ISSUE TITLE
Confusing CLI help for `mikro-orm migration:create`

### ISSUE THREAD

**Issue by soroushjp** [mikro-orm/mikro-orm#326]
**Describe the bug**
There is a line in the CLI help for `mkro-orm migration:create` which states:

```shell
--disable-fk-checks  Do not skip foreign key checks                  [boolean]
```

, but the name of the flag combined with the description is confusing. `--disable-fk-checks` sounds like it _will_ skip FK checks, but the description says the opposite.

**Expected behavior**
Should one of these (probably the description) be changed?

**Versions**

| Dependency | Version |
| - | - |
| node | 12.14.1 |
| typescript | 3.7.5 |
| mikro-orm | 3.1.0 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
This looks like the flag is not even taken into account. Only the ORM's configuration `disableForeignKeys` is used. I guess we could just remove the flag, it makes sense only when running the migration.
