### ISSUE TITLE
Uniqueness migration command is created for foreign key even though it is not explicitly set upgrading from 4.5.10 to 5.2.1

### ISSUE THREAD

**Issue by woltob** [mikro-orm/mikro-orm#3260]
**Describe the bug**

Model definition:

```
  @OneToOne({
    onUpdateIntegrity: 'cascade',
    onDelete: 'restrict',
    entity: () => Organization,
    cascade: [Cascade.MERGE, Cascade.PERSIST],
    nullable: true,
  })
  @Field((_type) => Organization, { nullable: true })
  public organization?: Organization;
```

Even adding `unique: false` to the @OneToOne options would produce the migration: 
```
    this.addSql('alter table "invitation" add constraint "invitation_organization_id_unique" unique ("organization_id");');
```

Why is this happening? It came up after migrating from v4.5.10 to v5.2 and running `npx mikro-orm migration.create`.

**Stack trace**
See migration line above.

**To Reproduce**
Create entity with this definition.

**Expected behavior**
Should not create migration command to generate a unique key for the foreign key as there can be multiple entries for the same foreign key.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 16.15.1 |
| typescript | 4.7.4 |
| mikro-orm | 5.2.1 |
| your-driver | postgres |

**Comment by B4nan** [comment]
1:1 is unique by definition, if you dont like that, dont use 1:1 relations.

**Comment by woltob** [comment]
Yes, got it. It would compile however but you are completely right. It got changed along the way, that is why it was like that.

Changed the inverse side to 

```
  @OneToMany({
    entity: () => Invitation,
    mappedBy: (invitation) => invitation.organization,
    cascade: [Cascade.PERSIST],
    strategy: LoadStrategy.SELECT_IN,
  })
  @Field((_type) => [Invitation])
  public invitations: Collection<Invitation>;
```

and the owning side looks like this:

```
@ManyToOne({
    onUpdateIntegrity: 'cascade',
    onDelete: 'restrict',
    entity: () => Organization,
    cascade: [Cascade.MERGE, Cascade.PERSIST],
    nullable: true,
    unique: false,
    index: true,
  })
  @Field((_type) => Organization, { nullable: true })
  public organization?: Organization;
```

correct? Excuse me for taking your time here. Thanks!

**Comment by B4nan** [comment]
> Short: is there anything I need to do to force `npx mikro-orm migration:create' to use whatever is in the code first (without caching or whatever) and check it against the database, regardless of the database structure or content?

That's exactly what that command already does. You can disable snapshots if you dont like them, or just remove the snapshot file manually if you want to force using the database schema. But not sure what you mean by the last bit - how could you check against database regardless of its structure? You check the database structure, that's the whole point.
