### ISSUE TITLE
MongoDb: ensureIndexes() goes into infinite loop, when there is an error while creating indexes

### ISSUE THREAD

**Issue by jagzmz** [mikro-orm/mikro-orm#3261]
https://github.com/mikro-orm/mikro-orm/blob/932a6e4a51178bc60db61281e44f93e16a84f137/packages/mongodb/src/MongoSchemaGenerator.ts#L77-L108

This error could be replicated by adding some entities with duplicate values onto the database, and then adding the @Unique() index on the property.

Database reports the error and promise becomes rejected, but nothing is logged by the ORM, and as it is recursive call if it gets failed, it keeps on looping.

Solution could look like this..

```ts
async ensureIndexes(options: EnsureIndexesOptions = {}, retryLimit = 3): Promise<void> { 
   .....
   if(retryLimit === 0) {
       // Crash with the error ?
   } 
   if (res.some(r => r.status === 'rejected') && options.retry !== false) { 
     const skipIndexes = res.filter(r => r.status === 'fulfilled').map((r: Dictionary, id) => ({ collection: promises[id][0], indexName: r.value })); 
     const collectionsWithFailedIndexes = res.filter(r => r.status === 'rejected').map((r: Dictionary, id) => promises[id][0]); 
     await this.dropIndexes({ skipIndexes, collectionsWithFailedIndexes }); 
     // Maybe some timeout before trying again ?
     await this.ensureIndexes({ retry: collectionsWithFailedIndexes }, retryLimit--); 
   } 
 } 
```

**Comment by B4nan** [comment]
Yeah retry limit sounds good, I was hoping it won't be needed but forgot about adding indexes that are invalid. PR welcome.
