### ISSUE TITLE
Calling `jest.useFakeTimers()` before importing Mikro-ORM results in dates not being hydrated properly.

### ISSUE THREAD

**Issue by jamesmeneghello** [mikro-orm/mikro-orm#3264]
**Describe the bug**

Title pretty much says it. Moving the call later (after the ORM has been loaded) works ok, otherwise they come through as ISO datestrings.

**To Reproduce**

```
import { Entity, ManyToOne, MikroORM, PrimaryKey, Property } from '@mikro-orm/core';
import type { SqlEntityManager } from '@mikro-orm/knex';

@Entity()
export class Trade {

  @PrimaryKey()
  id!: number;

  @Property()
  tradeStart: Date = new Date();

}

describe('GH issue xxxx', () => {

  let orm: MikroORM;

  beforeAll(async () => {
    jest.useFakeTimers({advanceTimers: true});
    orm = await MikroORM.init({
      entities: [Trade],
      type: 'postgresql',
      dbName: 'mikro_orm_test_xxxx',
    });
    await orm.getSchemaGenerator().refreshDatabase();
  });

  afterAll(async () => {
    await orm.close(true);
  });

  test(`GH issue xxxx`, async () => {
    const em = orm.em.fork() as SqlEntityManager;

    const t = em.create(Trade, {tradeStart: new Date()});
    await em.persistAndFlush(t);
    em.clear();

    const trade =  await em.findOne(Trade, {id: t.id});
    expect(trade?.tradeStart instanceof Date).toBeTruthy()
  });

});

```

**Expected behavior**

Expected `Date` fields to be hydrated as dates.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 18.3 |
| typescript | 4.4.4 |
| mikro-orm | 5.1.2 |
| your-driver | pg |

**Comment by B4nan** [comment]
I really doubt this is something to be fixed in MikroORM. Hydration is synchronous just like processing of mapped types. 

Tried your repro, it is passing on my end (at least on master, 5.1.2 is out dated version so be sure to update).

<img width="988" alt="image" src="https://user-images.githubusercontent.com/615580/176470275-90726433-eb12-478c-be18-40947ca7c6e5.png">
