### ISSUE TITLE
docs: How do we create/define a timeseries Collection in MongoDB?

### ISSUE THREAD

**Issue by icex** [mikro-orm/mikro-orm#3266]
Hello,

We're trying out the timeseries feature of MongoDB 5. How can we define this using decorators? https://www.mongodb.com/developer/products/mongodb/new-time-series-collections/

**Comment by B4nan** [comment]
You can't, there is no out of box support. Tbh I dont even know what timeseries are (in mongo context), and I dont have the time to learn it. If you would like to propose this as a feature, you will need to do the first step and propose/design some API and integration.
