### ISSUE TITLE
MongoDb: ensureIndexes() is buggy.

### ISSUE THREAD

**Issue by SevenWaysDP** [mikro-orm/mikro-orm#3275]
**Describe the bug**
The new function "Rebuild indexes" is still buggy. The logic in MongoSchemaGenerator.ts:105 returns incorrect Array[Index].

https://github.com/mikro-orm/mikro-orm/blob/master/packages/mongodb/src/MongoSchemaGenerator.ts#L105

**To Reproduce**
1. Add index to TestEntity()  => @Index()
2. Change Index in TestEntity() => @Unique()
3. The Index is not Unique()

**Expected behavior**

Rerun of  ensureIndexes() remove old index and create new index

**Soution**
The solution during a new search in the result:

const collectionsWithFailedIndexes = res.map((r, id) => r.status === 'rejected' ? promises[id][0] : undefined).filter(Boolean);

**Additional context**
This probably wouldn't lead to the error in https://github.com/micro-orm/micro-orm/issues/3261 either

**Versions**

| Dependency | Version |
| node | v16.13.1 |
| typescript | 4.2.4 |
| mikro-orm | 5.2.2 |
| your-driver | mongodb |

**Comment by B4nan** [comment]
PR welcome.
