### ISSUE TITLE
More flexible Loaded<> typing

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#3277]
Say I have the following model:

```typescript
class Parent {
  @ManyToOne(() => Child)
  child: IdentifiedReference<Child>;
}

class Child {
  @ManyToOne(() => Grandchild)
  grandchild: IdentifiedReference<Grandchild>;
}

class Grandchild {

}
```

If I have a function that looks like the following:

```typescript
function preloaded(parent:Loaded<Parent, 'child'>){

}

const parent1 = manager.findOne(Parent, 1, {populate: ['child']});

// works
preloaded(parent1);

const parent2 = manager.findOne(Parent, 1, {populate: ['child.grandchild']});

// typescript complains
preloaded(parent2);
```

I would expect to be able to pass both instances of parent since they at-least have the child populated. 
**Additional context**
Typescript: 4.5.5

**Comment by B4nan** [comment]
Not reproducible, I dont see any TS errors in that code. At least on master, not sure what version you are on.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/615580/177942320-234cc1cf-591d-496d-ab3d-d279ad899c25.png">

Let's reopen with a failing repro, this sounds like a bug to me, but clearly its not as easy as you described it.

**Comment by parisholley** [comment]
added PR to reproduce this issue

**Comment by B4nan** [comment]
That's weird, it complains about assignability in the wrong direction.

**Comment by B4nan** [comment]
This is quite tricky, spent the better half of the day trying to solve it, but I feel desperate. One of the issues I haven't found a way around: the serialized forms of the relations will be different - those are also strictly typed and respect the `Loaded` type. So the `Collection.toJSON` method will have a different return type for `Loaded<E, 'col'>` and `Loaded<E, never>`, those are not assignable to each other in any way.

```ts
const foo: Collection<Loaded<Vehicle>> = {} as Collection<Loaded<Vehicle, 'type'>>;

TS2322: Type 'Collection<Loaded<Vehicle, "type">, object>' is not assignable to type 'Collection<Loaded<Vehicle, never>, object>'.
   The types returned by 'toJSON()' are incompatible between these types.
     Type 'EntityDTO<Loaded<Vehicle, "type">>[]' is not assignable to type 'EntityDTO<Loaded<Vehicle, never>>[]'.
       Type 'EntityDTO<Loaded<Vehicle, "type">>' is not assignable to type 'EntityDTO<Loaded<Vehicle, never>>'.
         Types of property 'type' are incompatible.
           Type 'EntityDTO<Loaded<Type, never>>' is not assignable to type 'number'.
```

**Comment by parisholley** [comment]
No worries, I can take a crack at it. I was thinking maybe instead of trying to get two loaded objects to match each other, perhaps we create a new type that isn't returned by any APIs and only job in life is to be used on consumer-side function args, eg: `IsLoaded<T>` that wouldn't care about serialization or other "extra" things.

**Comment by parisholley** [comment]
@B4nan no luck either... the closest I got was passing the argument type to a custom `IsLoaded<>` but ultimately any way you slice it the crux of the problem is cascading it down. my initial brainstorms that i couldn't really nail down:

- could we build a "key graph" of two objects and compare them, ignoring types all together?
- could we somehow "defer" type resolution in some case by using (this: Loaded<xxx>)
- could we have an object be `Loaded<T, 'a'>` & `Loaded<T, 'a' | 'b'>` at the same time but with a very thin API (eg: only .get() with no complex returns

ultimately, this problem may only get fixed by typescript getting smarter in a future version (something like `satisfies`, but tailored to argument narrowing)

**Comment by parisholley** [comment]
a workaround for those who run into this issue, so long as the entity you needed `Loaded<>` is already in the UOW, you can simply "repopulate" it which will be zero-cost (query wise, still have promise delay).

eg:
```typescript
function preloaded(parent:Loaded<Parent, 'child'>){

}

const initial = await manager.findOne(Parent, 1, {populate: ['child.grandchild']});
const repopulate = await manager.populate(initia,l ['child']});

preloaded(repopulate);
```

**Comment by B4nan** [comment]
I feel like this is quite important to support, maybe we should rather discard the strictly typed serialization (and provide a way to make it work explicitly), to be able to support it in v6. Not sure how often people serialize entities manually and care at the resulting type. As opposed to being able to define populate constraints on type level, which might not be very well known (and due to this bug also not very usable) but feels like much more common use case.

**Comment by parisholley** [comment]
i would definitely vote to make serialization explicit. in my opinion, taking database entities and serializing them directly is a smell, I always make my team create DO's or generate POJO's manually with the exact data you need. Only takes one mistake and someone is sending sensitive information from the database to the client-side when they shouldn't because of automatic serialization.

i'm not familiar enough with the serialization stuff but if you can provide some direction i can maybe take a look at implementing a change. I have a lot of `TODO` markers and `as any` in my code base to work around this issue so plenty of test cases.

**Comment by B4nan** [comment]
I might have found a way to do this. It's super ugly, as it requires most of the public methods of `Collection` and `ArrayCollection` to have their separate type args that extend the main one. This way it both maintains the correct functionality as well as passes the checks from your repro. I found out about this when doing quite a massive type rewrite to able to enable `implicitAnyIndexErrors` for TS 5. 

<img width="827" alt="image" src="https://user-images.githubusercontent.com/615580/216792675-0e19ee99-93be-4746-892d-0b4c849b0ba1.png">

It will take some time to finalize this, but I guess I will give it a go in v6. Will need to do some breaking changes around this, but nothing super serious. Overriding base entity methods like `toJSON` would be a bit more painful, but I think `toJSON` is the only one people tend to override, and it does literally just forward the call to `toObject`, so we can drop it (on type level, it will be still present on prototype).

**Comment by B4nan** [comment]
Repro welcome, I have no idea what are you talking about :)

**Comment by Gonzalo9823** [comment]
> Repro welcome, I have no idea what are you talking about :)

[Here](https://codesandbox.io/p/sandbox/nervous-sun-hmqwq6?file=%2Fsrc%2Fmodels%2FChildModel.ts%3A1%2C1)!

**Comment by B4nan** [comment]
You need to use v6, your repro is v5. The types are greatly rewritten in there, they should also work better when it comes to suggestions and intellisense.
