### ISSUE TITLE
Unit tests in NestJS with @UseRequestContext decorator

### ISSUE THREAD

**Issue by epechuzal** [mikro-orm/mikro-orm#3279]
I have a worker class which handles jobs from a bullmq queue.

Per the documentation I am using the `@UseRequestContext()` decorator to make sure that I am not using the global entity manager context.

```
  @UseRequestContext()
  async process(job: Job) {
    // some job here
  }
```

This works great in production. However I cannot make unit tests work because of this error:
```
    @UseRequestContext() decorator can only be applied to methods of classes with `orm: MikroORM` property, or with a callback parameter like `@UseRequestContext(() => orm)`
```

For unit tests I will mock anything related to the database anyway so I don't need an ORM. Is there a way to mock the `orm` property or disable this warning?

**Comment by B4nan** [comment]
Its not just a warning you can disable, if the value is not there, you would get a runtime error. 

I guess you already saw [the implementation](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/decorators/UseRequestContext.ts)? It should give you some ideas.
