### ISSUE TITLE
Unique key constraint for 2 or more fields

### ISSUE THREAD

**Issue by gbikas** [mikro-orm/mikro-orm#328]
**Is your feature request related to a problem? Please describe.**
Is there a way to use 2 or more fields as a unique key (so the combination of them both would be unique)? I have gone through the documentation and the examples but I couldn't find anything. 

**Describe the solution you'd like**
I mean something like [this](https://dba.stackexchange.com/questions/17761/how-to-use-unique-key-via-combinations-of-table-fields) for sql

**Comment by B4nan** [comment]
Not really, but you can add the unique constraint manually, there should be no problem when running the ORM. 

I am planning to support this as part of `@Index` decorator that will allow to create also unique indexes, as well as composite ones. Most of it is already implemented, it will land to master in few weeks probably.
