### ISSUE TITLE
Problem with default "NaN" values generated by CLI

### ISSUE THREAD

**Issue by jvalrog** [mikro-orm/mikro-orm#3285]
**Describe the bug**
The CLI generated this entity:

```
@Entity()
export class Vrf {
  @PrimaryKey()
  id!: number;

  @ManyToOne({ entity: () => VrfType, index: 'vrf_FK' })
  vrfType!: VrfType;

  @Property({ length: 100 })
  vrfStringId!: string;

  @Property({ nullable: true, default: NaN })
  vrfId?: number = NaN;

  @Unique({ name: 'vrf_client_id_UN' })
  @Property()
  clientId!: number;

  @Property({ length: 100 })
  rt!: string;

  @Property({ length: 100 })
  rd!: string;

  @Property({ length: 100 })
  description!: string;

  @Property({ length: 150, nullable: true, defaultRaw: `NULL` })
  comments?: string;

  @Property({ nullable: true, defaultRaw: `current_timestamp()` })
  createdAt?: Date;

  @Property({ nullable: true, defaultRaw: `current_timestamp()` })
  updatedAt?: Date;

  @Property({ nullable: true, defaultRaw: `NULL` })
  removedAt?: Date;
}
```

When I try to insert a new record with an empty **vrfId** I get this error:

```
InvalidFieldNameException: insert into `vrf` (`client_id`, `comments`, `description`, `rd`, `rt`, `vrf_id`, `vrf_string_id`, `vrf_type_id`) values (10014, 'string4', 'string3', '<lo>:10014', '15704:10014', NaN, 'string5', 1) - Unknown column 'NaN' in 'field list'
```

**Versions**

| Dependency | Version |
| - | - |
| node | 16.15.1 |
| typescript | 4.4.4 |
| mikro-orm | 5.1.5 |
| your-driver | mysql-5.1.5 |

**Comment by B4nan** [comment]
Entity generator gives you an estimate, you might need to do some adjustments. Dont take this as a "schema first" approach, it's not. 

How does your schema look like? You havent provided anything to reproduce, just the outcome, not the source of the "bug". Also you should always test on the latest version before reporting anything.

**Comment by jvalrog** [comment]
Thanks for the heads up, I fixed it like this:

```
@Property({ nullable: true, default: null })
  vrfId?: number;
```

Now it works!

**Comment by B4nan** [comment]
Oh, so a numeric column with explicit `null` default, weird we dont have this in tests already, let me verify.

**Comment by jvalrog** [comment]
You mean latest CLI? or mikro-orm?

**Comment by B4nan** [comment]
Both, you should always use the exact same version of the CLI package as rest of your ORM packages.

**Comment by B4nan** [comment]
I see, ok will check how mariadb behaves.

> [edit] But I tried with 5.2.2 and "NaN" default and still crashed.

This is not about trying if the `NaN` default works, thats obviously wrong. I am asking if the entity generator produces the `NaN` default, because on my end it does not.

**Comment by jvalrog** [comment]
oh, yes, it still produces NaN.

```
npx mikro-orm --version
5.2.2
```
The generated entity:
```
import { Entity, ManyToOne, PrimaryKey, Property } from '@mikro-orm/core';
import { VrfType } from './VrfType';

@Entity()
export class Vrf {

  @PrimaryKey()
  id!: number;

  @ManyToOne({ entity: () => VrfType, index: 'vrf_FK' })
  vrfType!: VrfType;

  @Property({ length: 100 })
  vrfStringId!: string;

  @Property({ nullable: true, default: NaN })
  vrfId?: number = NaN;

  @Property()
  clientId!: number;

  @Property({ length: 100 })
  rt!: string;

  @Property({ length: 100 })
  rd!: string;

  @Property({ length: 100 })
  description!: string;

  @Property({ length: 150, nullable: true, default: 'NULL' })
  comments?: string;

  @Property({ nullable: true, defaultRaw: `current_timestamp()` })
  createdAt?: Date;

  @Property({ nullable: true, defaultRaw: `current_timestamp()` })
  updatedAt?: Date;

  @Property({ nullable: true, defaultRaw: `NULL` })
  removedAt?: Date;

}
```

**Comment by B4nan** [comment]
Provide a reproduction, the issue was closed with a test case and that is still passing, so its not the same problem.
