### ISSUE TITLE
Bulk operations, Upsert and Delete actions docs: 

### ISSUE THREAD

**Issue by conspireagency** [mikro-orm/mikro-orm#3293]
First absolutely love the project and for the most part the documentation is amazing.  I've been really using it as my go-to over the past month or two on any new projects.

Apologies in advance if I missed something or it was covered at a high level and I failed to interpret properly.

Few things I noticed while switching over:
1.  Upsert situations, similar to below

https://github.com/mikro-orm/mikro-orm/issues/2088
https://github.com/mikro-orm/mikro-orm/blob/master/tests/QueryBuilder.test.ts

2. Deleting items from a database would probably be good to have tossed into one of the code examples.  Feel like Create, Read and Update have some decent examples, but I don't really see all that much for delete. 

3. Bulk actions in general.  Say I have a large amount of Order [ids] in an array and I'd like to delete them from an Orders table.  How does one go about this most efficiently?  Something like below?

ordersToDelete.forEach((order)=>{
          this.em.nativeDelete(Order, {order_id: order.order_id});
})

await this.em.flush();

Appreciate all that you guys are doing!

**Comment by B4nan** [comment]
Agreed the batching is not really described anywhere (and it is quite a killer feature). Just use EM/UoW and it will work automatically. All operations are batched by default, even update queries. 

```ts
// if ordersToDelete is not array of entity instances, you can use `em.getReference(Order, oid)`, no need to load those entities from database
ordersToDelete.forEach((order: Order)=>{
  this.em.remove(order);
})
await this.em.flush();
```

I was describing in the blog post for v4.1:

https://mikro-orm.io/blog/mikro-orm-4-1-released

I never really described upserts, because I never really needed this myself, so hard to tell others how to do things I never did myself :] But I can at least try and we can iterate on that.

**Comment by conspireagency** [comment]
For Upserts feel like the common use case might be where you're syncing your database with an external data source.  In our case we do a lot of application development for Shopify and need to get say Order information from a Shopify store and have it in our database.

Sometimes their webhooks aren't reliable or don't provide all the information, so periodically we need to get all the orders from them and then sync it with our database.  At that point we grab all the orders (thousands often) and then have to update (if say the order status or items in order change) or create.

Few approaches to this:
1. Iterating through the orders we receive -> looking up in our database -> updating if exists or create if not (can batch the create if lookup fails) takes a really long time.  The lookups would take a while, and if we already have most of the orders in our database probably a decent amount of updates.  
2. Deleting all orders to make sure none exist then creating all orders.  Works really fast, but overall approach of deleting that data isn't great.
3.  Try and do it in a native database manner

**Comment by conspireagency** [comment]
Would love to hear how other people are handling the situation where many records in bulk are being inserted into a table where the item may already exist (and if so updating).

**Comment by conspireagency** [comment]
Okay, finally figured this out for anyone that comes here trying to do bulk updates.

Solved by stumbling across this issue and subsequent feature addition
https://github.com/mikro-orm/mikro-orm/issues/1240
https://github.com/mikro-orm/mikro-orm/commit/b97ecb547282a5563b47e2c624ceb9d2833bbb38

Basically QueryBuilder has an onConflict method that I didn't see documented.  So say I have an array of PackingItems that may or may not already exist in my database table... then I can run a querybuilder instert with the onConflict cause and a list of fields that I want to update on conflict.  



```
const qb = this.em.createQueryBuilder(PackingItem);

    qb.insert(itemsToSave)
      .onConflict('VariantId')
      .merge([
        'VariantTitle',
        'HeightIn',
        'WidthIn',
        'LengthIn',
        'PaddingIn',
        'KeepVertical',
        'PackMode',
        'NB',
      ])
      .execute();
```

Seems to work great.  Just wish there were more documentation around this.  I'm a little ashamed to admit, but I wasted days trying to figure this out.

**Comment by siawyoung** [comment]
@conspireagency thank you for this -- it was helpful!

**Comment by B4nan** [comment]
FYI v5.5 added `em.upsert`

https://mikro-orm.io/docs/entity-manager#upsert

**Comment by alex996** [comment]
@B4nan Is it possible to perform a bulk insert using the Query Builder? For example, I need to loop over a list of items and build a query to update them all in a single statement (each items adds its own condition to the `where` clause). I could build the query myself and run it with `em.execute` but is there a better alternative? I know the Entity Manager updates in bulk automatically, but I'd need to `find` the items first, which is an extra `select` query I technically don't need.

_This question is tangentially related to the thread, so I didn't create a new issue. Thanks_

**Comment by B4nan** [comment]
Sure, just pass array of items to `qb.insert`.

**Comment by alex996** [comment]
Sorry, typo - I meant a bulk update.

**Comment by conspireagency** [comment]
@alex996 upsert only works with a single entity, as of right now.  Seems the best way to do in bulk is the insert on conflict method using query builder, as shown above the post dated August 9th.

**Comment by alex996** [comment]
I may be in the wrong thread after all. I was wondering about bulk update, but it might be a separate topic. Thanks for your replies though.

**Comment by B4nan** [comment]
You can do bulk update as well, via `em.getDriver().nativeUpdateMany()`, that's what the UoW uses under the hood.
