### ISSUE TITLE
Properties marked 'hidden' are not cached

### ISSUE THREAD

**Issue by fa-sharp** [mikro-orm/mikro-orm#3294]
I was trying to do some caching on one of my frequently-used queries, and I was trying to figure out why some properties were disappearing from the entities on the server-side when using the cache. It turns out that marking a property as `hidden = true` will mean that it will be removed from the cached entity as well. So on subsequent queries using the cache, those properties will be `undefined` on the server-side.

Is this expected behavior? I'm using `hidden = true` basically to make sure these properties aren't sent to the client-side when the entity is serialized. But I definitely want access to those properties on the server-side. Perhaps though I'm misunderstanding the behavior or use-case here.

**To Reproduce**
1. Have a hidden property on an entity
2. Extend the cache time on a query for that entity, by using `{ cache: [ 'queryKey', 60 * 1000]} // 60 second cache` 
3. On the first query, the hidden property will be there on the server-side (as expected). But on subsequent queries within the cache time, the entity will be missing that hidden property. The property will return as `undefined` on the server-side regardless of what the value is.

**Expected behavior**
I would expect the `hidden = true` properties to still be cached and accessible on the server-side. They would only be hidden when serialized to send to the client-side.

**Additional context**
I'm guessing what's happening here is that the same serialization is used for caching as when calling `JSON.stringify`? And that serialization will remove the hidden properties in both cases. So maybe this is expected behavior. It was just kinda surprising to me, and it's not mentioned in the docs on Caching or Hidden properties. I would argue that when caching, Hidden properties should still be there (or at least have an option that they should be there).

**Versions**

| Dependency | Version |
| - | - |
| node | v16.13.0 |
| typescript | v4.7.4 |
| mikro-orm | v5.2.3 |
| mikro-orm/postgresql | v5.2.3 |

**Comment by B4nan** [comment]
Caching is using [`toPOJO()`](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/entity/WrappedEntity.ts#L61-L63), serialization uses `toJSON()`. Caching definitely ignores populate hints, but it probably respects the hidden flags. 

Should be enough to respect the `raw` flag [in here](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/entity/EntityTransformer.ts#L152-L158). PR welcome.

**Comment by fa-sharp** [comment]
Thank you @B4nan . I'm thinking I would simply pass in the `raw` parameter and modify line 154 so that if `raw = true`, the prop is still visible even if it's marked hidden. I assume that _prefixed_ properties should still not be included in the cached version, since those are internal properties? I'm happy to send that PR!

https://github.com/mikro-orm/mikro-orm/blob/a16039e86cfaac948dee15ea5cde6ac1030ad42e/packages/core/src/entity/EntityTransformer.ts?rgh-link-date=2022-07-11T09%3A56%3A35Z#L152-L158

**Comment by B4nan** [comment]
I would actually say we should keep the prefixed ones too, when you serialize the entity it will go thru the function again with raw = false, so they should be handled correctly. But you might depend on them internally. So we could just skip `isVisible` call in case `raw === true` instead of passing the parameter in there.
