### ISSUE TITLE
OperatorMap type doesn't include $exists

### ISSUE THREAD

**Issue by snigdha920** [mikro-orm/mikro-orm#3295]
**Is your feature request related to a problem? Please describe.**

I have a `deletedAt` field in my entities. I'm trying to fetch the entities where the `deletedAt` field does not exist. 

Here's what my query looks like: 

```
await this.myRepository.findOneOrFail({deletedAt: {$exists: false}})
```

After MikroORM v5, I can't use this anymore. 

It would be nice to have `$exists` option. Since it would check for both `undefined` and `null` at the same time. Also, there might be several other projects using `$exists` option, which will break. Having the `$exists` option will make v5 more backwards compatible with v4. 

**Describe the solution you'd like**

Update the types of [`OperatorMap<T>`](https://github.com/mikro-orm/mikro-orm/blob/e7843fbe2f02ee8922d99a2f0209e4e261898a66/packages/core/src/typings.ts#L57) to include `$exists` as well.

**Describe alternatives you've considered**

```
await this.myRepository.findOneOrFail({deletedAt: undefined})
```

I find this a little wobbly, because it won't match `deletedAt` being set to `null`.

**Additional context**
Add any other context about the feature request here.

I'd be happy to open a PR if you think this is worth adding.

**Comment by B4nan** [comment]
It was never there. In v4 it was just not strictly type checked. 

> After MikroORM v5, I can't use this anymore.

This is a TS error, you can just cast `as any` to get around it.

I dont mind adding it there, as long as we will have meaningful error handling for SQL drivers where this wont work (or maybe we should just contert that for SQL drivers to SQL alternative, maybe to `foo is not null`?)

**Comment by snigdha920** [comment]
Oh, I did not know that. In that case, what you said is perfect. Should I provide a PR for the same?
