### ISSUE TITLE
Cannot install version 5.2.3 correctly

### ISSUE THREAD

**Issue by snigdha920** [mikro-orm/mikro-orm#3299]
### Discussed in https://github.com/mikro-orm/mikro-orm/discussions/3297

<div type='discussions-op-text'>

<sup>Originally posted by **snigdha920** July 12, 2022</sup>
Hello, I'm trying to install v5.2.3 which includes a [fix](https://github.com/mikro-orm/mikro-orm/commit/e7843fbe2f02ee8922d99a2f0209e4e261898a66) I need for my CI to build successfully. 

I am using `@mikro-orm/core`, `@mikro-orm/mongodb`, `@mikro-orm/nestjs` in my project. I've specified the versions in the package.json as:

```
"@mikro-orm/core": "5.2.3",
"@mikro-orm/mongodb": "5.2.3",
"@mikro-orm/nestjs": "5.1.0"
```

However, when I look at the files installed, the fix is not included. Here are the logs from running `yarn install` related to MikroORM:

```
➤ YN0000: ┌ Fetch step
➤ YN0013: │ @mikro-orm/core@npm:5.2.3 can't be found in the cache and will be f
➤ YN0013: │ mikro-orm@npm:5.2.0 can't be found in the cache and will be fetched
➤ YN0019: │ @mikro-orm-core-https-968ca3539a-45884ac53e.zip appears to be unuse
➤ YN0000: └ Completed in 1s 25ms
```

Here, I see that it tries to fetch `mikro-orm@npm:5.2.0` which might be the cause of the issue. 

When I try to install the package using a github commit instead of the npm registry, I run into the following issue: 

```
➤ YN0000: ┌ Link step
➤ YN0007: │ @mikro-orm/core@https://github.com/mikro-orm/mikro-orm.git#commit=f906fd57ffde1173cca9e43781de34f50dd266ae must be built because it never has been before or the last one failed
➤ YN0009: │ @mikro-orm/core@https://github.com/mikro-orm/mikro-orm.git#commit=f906fd57ffde1173cca9e43781de34f50dd266ae couldn't be built successfully (exit code 127, logs can be found here: /private/var/folders/33/4x4cj27n1r5799d0bklpn8pc0000gn/T/xfs-9b640441/build.log)
```

build log:

```
# This file contains the result of Yarn building a package (@mikro-orm/core@https://github.com/mikro-orm/mikro-orm.git#commit=f906fd57ffde1173cca9e43781de34f50dd266ae)
# Script name: postinstall

command not found: husky
```

I'm not sure if this is a yarn issue, because a similar issue is being tracked in yarn [here](https://github.com/yarnpkg/yarn/issues/4722) or if it's related to MikroORM. 

Any help is appreciated. 

My yarn version is `3.2.1`, node version is `v16.15.1`

EDIT: I've deleted my node_modules, cleared the cache using `yarn cache clean`, deleted the yarn.lock file, and tried re-installing, but nothing seems to work. 

EDIT: I see in the build log, it says `command not found: husky`. I suppose I can get around this locally by installing `husky` but I don't want to install it in the CI, which is why I'm looking for another solution.</div>

**Comment by snigdha920** [comment]
This issue is incorrect. The version 5.2.3 was being installed correctly, however it didn't include the fix I needed as we can see in the commit history here:

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/62167899/178579352-1d1bd892-ee97-4e14-b191-b9e633944480.png">

I will open another issue, requesting an upgrade of the package to a newer version which includes the fix.

**Comment by B4nan** [comment]
There is no point in opening issues about something that was fixed in master. Just wait if you want to use stable, or use dev version if you need it right now.

**Comment by snigdha920** [comment]
Yep, I thought there was an issue with the installation of the fix which is why I opened an issue. I realised my mistake when I created a minimal reproduction repo to show this issue. I'm sorry, I'll look into how to use a dev version.
