### ISSUE TITLE
Add support for single table inheritance

### ISSUE THREAD

**Issue by B4nan** [mikro-orm/mikro-orm#33]
Similar to what doctrine implements: https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/inheritance-mapping.html#single-table-inheritance

But less verbose (one decorator should be enough).

**Comment by jeesus** [comment]
Looking forward to it as well. Until then will probably have to continue with TypeORM.

**Comment by B4nan** [comment]
Closing as implemented in dev branch.
