### ISSUE TITLE
postgresql numeric return as string

### ISSUE THREAD

**Issue by solayw** [mikro-orm/mikro-orm#3305]
`    @Property({
        type: types.decimal
    })
    price: number
`
the  type of price in database is numeric(16,2), but mikro-orm retrun is string,  number expected
,**Versions**

| Dependency | Version |
| - | - |
| node | 16.15.0 |
| typescript | 4.7.4 |
| mikro-orm | 5.2.3 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
This is on purpose, as you could loose precision with js numbers.
