### ISSUE TITLE
Repository<T>.create(data: RequiredEntityData<T>): Non-null properties should not accept null values

### ISSUE THREAD

**Issue by yodhcn** [mikro-orm/mikro-orm#3306]
**Describe the bug**
method ```Repository<T>.create(data: RequiredEntityData<T>)``` accepts null values on non-null properties.

**To Reproduce**
https://github.com/mikro-orm/nestjs-example-app/blob/master/src/modules/book/book.controller.ts#L33
```
const book = this.bookRepository.create({
  title: null,
  author: null,
  createdAt: null,
  updatedAt: null
});
```
typescript gives no warning, but this will throw an error when running em.flush().
I would like to know why it is designed this way.

**Expected behavior**
typescript should warn:
```Type 'null' is not assignable to type 'string'.```
```Type 'null' is not assignable to type '(EntityDataItem<Author> | undefined) & EntityDataItem<Author>'.```
```Type 'null' is not assignable to type 'Date'.```
```Type 'null' is not assignable to type 'Date'.```

**Versions**

| Dependency | Version |
| - | - |
| node | v16.15.1 |
| typescript | 4.5.5 |
| mikro-orm | 5.0.3 |
| your-driver | Windows 11 |

**Comment by B4nan** [comment]
Fixed in master.
