### ISSUE TITLE
Initiating a transaction triggers onUpdate hooks

### ISSUE THREAD

**Issue by mrmlnc** [mikro-orm/mikro-orm#3328]
**Describe the bug**

I have a [set of entities](https://github.com/mrmlnc/mikro-orm-onUpdate-hook-issue/blob/master/src/entities/FieldEntity.ts) that use [the `onUpdate` hook](https://github.com/mrmlnc/mikro-orm-onUpdate-hook-issue/blob/bff25afc749019e0f7f653369f917069f4323956/src/entities/FieldEntity.ts#L12-L15) for one of the fields. If a [transaction](https://github.com/mrmlnc/mikro-orm-onUpdate-hook-issue/blob/bff25afc749019e0f7f653369f917069f4323956/src/index.ts#L38) is initiated after receiving the records for this entity, an `onUpdate` hook will be called in each entity (even relations). The result returned from the hook does not apply to the record.

> 📖 I have a repository that makes it easy to reproduce the problem:
> https://github.com/mrmlnc/mikro-orm-onUpdate-hook-issue

In the example from the repository, the `onUpdate` hook will be called three times (for each entity with this hook).

```js
// All fine
{ 'entity.counter.before-persist': undefined }
{ onCreate: 'call' }
{ onCreate: 'call' }
{ onCreate: 'call' }
{ 'entity.counter.after-persist': 100 }

// The `onUpdate` hook should not be called
{ 'entity.counter.before-transactional': 100 }
{ onUpdate: 'call' }
{ onUpdate: 'call' }
{ onUpdate: 'call' }
{ 'entity.counter.after-transactional': 100 }
```

This happens with an empty transaction and a non-empty transaction. There are no problems when removing the transaction.

**To Reproduce**
1. `git clone https://github.com/mrmlnc/mikro-orm-onUpdate-hook-issue`
2. `npm ci`
3. `npm start`

**Expected behavior**

The `onUpdate` hook is only called when the entity is updated.

**Versions**

| Dependency | Version |
| - | - |
| node | `16.16.0` |
| typescript | `4.7.4` |
| mikro-orm | `5.2.3` |
| better-sqlite | `5.2.3` |

**Comment by B4nan** [comment]
This works as expected, doing `em.transactional()` creates a new fork, copies the state into it and runs `flush` on it. So yes, it you had some entities loaded in the context before, they will get the update hooks fired.

**Comment by mrmlnc** [comment]
Thanks for the quick response 🎉.

It looks strange to me that a hook will be called, but the result will not be used. For example, for 1000 records, it could be 1000 `new Date()` calls (or something like this). I'm going to go read the documentation on transactions first.

**Comment by B4nan** [comment]
Gave it a closer look at your repro, I thought you were talking about the before update hook and those are not fired, now I see you meant the property `onUpdate` option. We do compute those before we know whether the entity was changed or not, but for `onUpdate` specifically I believe we could do it afterwards. Let's reopen, will try to improve on this. I don't think we can do anything about `onCreate` being executed this way, but for those its clear the entity will issue a query, so it should be fine.
