### ISSUE TITLE
Make .snapshot have a deterministic order

### ISSUE THREAD

**Issue by noftaly** [mikro-orm/mikro-orm#3330]
**Is your feature request related to a problem? Please describe.**
Hello,
I've recently noticed that the `.snapshot` file often rewrites changes but in a different order as they were before.

This can generate very noisy diffs, which makes merging & rebasing way harder, and reading the file (to check for correctness or exhaustiveness) much harder too.

**Describe the solution you'd like**
It would be great if it was deterministic instead, making it always generate each parts in the exact same order.

**Describe alternatives you've considered**
Keeping it as-is

**Additional context**
Nothing special,
Thank you for your time!

**Comment by B4nan** [comment]
Can you describe what diffs you saw? Like was it about order of tables/entities, or more about properties or other things? I could imagine we build new metadata object from scratch in a predefined order. Other than that its `JSON.stringify` serializing things.

**Comment by noftaly** [comment]
> Can you describe what diffs you saw? Like was it about order of tables/entities, or more about properties or other things? I could imagine we build new metadata object from scratch in a predefined order. Other than that its JSON.stringify serializing things.

It was the order of entities. I added 1 property to an entity in my app, ran `migration:create` and 3 tables where moved (two of them being interchanged, making the diff even worse) as well as my property added.

I have not yet seen columns' order being changed, only tables'.

> it's probably not coming from our end, but we could indeed ensure stable order at least to some degree.

Hmm ok I understand, but yeah ensuring a stable order could be great! :smile:

**Comment by B4nan** [comment]
Ok ensuring the stable order of entities should be quite easy, so lets deal with that and reopen if it wont be enough. 

I am aware of some schema diffing tests here that are failing occasionally because of this, I recently tried to deal with it but I see we will need more "dumb fix" to ensure it really works as it should :]

**Comment by B4nan** [comment]
Btw this CI run demonstrates what I was referring to above:

https://github.com/mikro-orm/mikro-orm/runs/7559580840?check_suite_focus=true

**Comment by noftaly** [comment]
Yep, it looks very annoying...

Idk if it's feasible but one way to do it would be to sort the tables alphabetically (based on the column name) right before saving the file?
This is possible if it's still an object; if it has already been stringified then maybe do it before, or when generating it?
Just some ideas, i gave a quick glance at the code but did not really investigate it
