### ISSUE TITLE
Custom column type with migration snapshot updates column every time

### ISSUE THREAD

**Issue by l00k** [mikro-orm/mikro-orm#3331]
**Describe the bug**
When `migrations.snapshot = true` is set in configuration (by default) `migration:create` always creates statment to update custom type columns. Especially with DECIMAL(X,Y) type.

**Stack trace**
```
@mikro-orm/knex/schema/SchemaComparator.js:338
...
```

**To Reproduce**
Sample.ts
```
import * as ORM from '@mikro-orm/core';
import { DecimalType } from './DecimalType';

@ORM.Entity()
export class Sample
    extends AbstractModel<VerifiersNft>
{
    
    @ORM.PrimaryKey()
    public id : number;
    
    @ORM.Property({ 
        type: DecimalType,
        precision: 38,
        scale: 18,
    })
    public value : number = 0;

}
```
DecimalType.ts
```
import * as ORM from '@mikro-orm/core';

export class DecimalType
    extends ORM.Type<number, string | null | undefined>
{
    
    public convertToDatabaseValue (value)
    {
        if (!value) {
            return '0';
        }
        return value.toString();
    }
    
    public convertToJSValue (value)
    {
        if (!value) {
            return 0;
        }
        return parseFloat(value);
    }
    
    public getColumnType (prop : ORM.EntityProperty, platform : ORM.Platform)
    {
        return platform.getDecimalTypeDeclarationSQL(prop);
    }
    
    public compareAsType () : string
    {
        return 'string';
    }
    
}
```

**Expected behavior**
Don't update column type if it is already in proper type.

**Additional context**
@mikro-orm/knex/schema/SchemaComparator.js:330
Here columnType1 is wrong - propably because mappedType is wrong here.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.14 |
| typescript | 4.6.3 |
| mikro-orm | 5.2.4 |
| your-driver | mysql:8 |

**Comment by B4nan** [comment]
Can you enable debug mode to see why it thinks the type is different? Also can you try latest dev build? I was just fixing one issue with unkown types that might help. 

Just set `MIKRO_ORM_VERBOSE=1` env var when running the CLI.

Two more notes:
- you will loose precision if you map such type to JS number
- I guess you are using your own type because of that? otherwise there already is a `DecimalType` that does the job

**Comment by l00k** [comment]
Sure.
It think it is `varchar(255)`

It is still there in version `5.2.4-dev.12`

> you will loose precision if you map such type to JS number  

that is acceptable I rather prefer loose precision than deal with Decimal.js or something similar

> I guess you are using your own type because of that? otherwise there already is a DecimalType that does the job  

Std version gives string so it is also not acceptable.

**Comment by B4nan** [comment]
> that is acceptable I rather prefer loose precision than deal with Decimal.js or something similar

Then why are you using decimal type in the database? :]

So what is the output when you enable verbose loging via `MIKRO_ORM_VERBOSE`?

**Comment by l00k** [comment]
> Then why are you using decimal type in the database? :]
  
legacy, but it is less important ;) 

> So what is the output when you enable verbose loging  
  
Like I wrote: It think it is varchar(255)

**Comment by B4nan** [comment]
I asked you to provide logs. You say "you think"? Provide the logs please. If you "think", you clearly didnt even enable the logs.

**Comment by l00k** [comment]
It is not so important to me to explain the difference between "I" and "it"..
Only valuable info there was mentioned varchar. 
It is private project so I don't want to share any details..
Nvm I only wanted to inform about issue.

**Comment by B4nan** [comment]
All I asked was more details. And you gave me thoughts instead, hard to debug anything based on thoughts. I would appreaciate more 

Let't keep this open, its indeed valid. Here are the logs you were supposed to provide. Its quite clear what is happening there if you see the logs. They tell you much more than just the query, you can see the property gets typed one way and then retyped back. 

```
[schema] 'type' changed for column user.value { columnType1: 'varchar(255)', columnType2: 'numeric(38,18)' }
[schema] column user.value changed { changedProperties: Set(1) { 'type' } }
[schema] 'type' changed for column user.value { columnType1: 'numeric(38,18)', columnType2: 'varchar(255)' }
[schema] column user.value changed { changedProperties: Set(1) { 'type' } }
```

**Comment by B4nan** [comment]
Actually, this has been already fixed in master via https://github.com/mikro-orm/mikro-orm/commit/f0a20fafa1425ca20f4f6fb2977eae7773d6ac6a, you can use the dev version to try it out.
