### ISSUE TITLE
Limit filter option for querying Collection

### ISSUE THREAD

**Issue by ryankauk** [mikro-orm/mikro-orm#334]
**Is your feature request related to a problem? Please describe.**
I'm worried about relations that could become large with the collection.init() function using postgres. Looked through the code and it seems like a relatively simple change. I don't mind helping out with this if you'd like as this is something I would like to have and really like this project.

```typescript
qb.select('*').populate(populate).where(where).orderBy(orderBy);
```
could be change to:
```typescript
qb.select('*').populate(populate).limit(limit).offset(offset).where(where).orderBy(orderBy);
```

**Describe the solution you'd like**
drivers/DatabaseDriver.ts
```typescript
interface Filter<T>{
    where?: FilterQuery<T>;
    orderBy?: QueryOrderMap; 
    fields?: string[];
    limit?: number;
    offset?: number,
}

loadFromPivotTable<T extends AnyEntity<T>>(prop: EntityProperty, owners: Primary<T>[], filter: Filter<T>, ctx?: Transaction): Promise<Dictionary<T[]>>;
```
This should change the DatabaseDriver functions to all except Filter<T>, this could make the function arguments more dynamic and extendible for custom configuration. Which would cause a breaking change unfortunately, unless you had variants for the functions inputs until the next version.

Let me know your thoughts!

**Comment by B4nan** [comment]
I am not against this, but the problem is that semi-initialized collection can't be used for anything more than reading, so we will need to introduce some read only collection wrapper to be used instead. The problem is already there, as you are able to use filtering on collections. 

Are you talking just about the `Collection.init()` method, or you would like to incorporate this into the EM API too? Because you can populate collections too via `EntityLoader`, but that would be more complicated.

**Comment by stephenh** [comment]
Agreed with @B4nan that this will very likely cause bugs if 1 part of your application initializes the collection with the "only load 50" option, but then some other part of your application processes some business logic (like "sum all my account transactions") with the "great it's already loaded collection, I'll skip calling `init`" but it's missing ~80% of the rows.

If you have too many rows to pull into memory as a `Collection`, then it shouldn't be a collection, b/c the collection API insinuates to the rest of your program that "this is small enough to pull into memory", and if any caller forgets to pass this filter option, you'll cause a out-of-memory type error. 

Alternatively, Mikro could introduce a concept of `VeryLargeCollection<Child>`, with some sort of API that would make it very apparent to callers that they will never all a `Child[]` in-memory array of every single child this entity points to, but instead they could work in batches of 100, or maybe do bulk operations like `parent.largeChildrenCollection.deleteAll()` or something.
