### ISSUE TITLE
Issues with using non-ObjectId primary keys in mongo

### ISSUE THREAD

**Issue by davidpricedev** [mikro-orm/mikro-orm#3359]
**Describe the bug**

There is no way to set the `id` field when using a non-ObjectId primary key type in mongo. This is caused by the two functions mentioned below.

There is a hard-coded `id` property (on EntityHelper.ts) which is [implemented as a getter/setter](https://github.com/mikro-orm/mikro-orm/blob/7d5e32d8eb7ec25ace2336e1bd4da5d97d015c08/packages/core/src/entity/EntityHelper.ts#L41) on top of the _id property. This auto-generated property overwrites and tramples any existing id property. (The comment above the function claims _“if […] there is no id property defined”_ - but that function doesn't have any such checking. My testing confirms that there is no checking anywhere else either - it will throw errors when a getter/setter is already defined and silently overwrites a simple field)

MongoPlatform.ts implementation of [deNormalizePrimaryKey](https://github.com/davidpricedev/mikro-orm/blob/master/packages/mongodb/src/MongoPlatform.ts#L41) is called by that `id` setter. That `deNormalizePrimaryKey` function tries to convert the value to an ObjectId. This is done blindly without checking any metadata to confirm that the primary is actually implemented as an ObjectId. 

**Stack trace**

```
    BSONTypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer

    > 41 |         this.id = createDto.id;
         |         ^
      42 |         this.name = createDto.name;
      43 |         this.description = createDto.description;

      at new BSONTypeError (../../../common/temp/node_modules/.pnpm/bson@4.6.5/node_modules/bson/src/error.ts:16:5)
      at new ObjectId (../../../common/temp/node_modules/.pnpm/bson@4.6.5/node_modules/bson/src/objectid.ts:88:15)
      at MongoPlatform.denormalizePrimaryKey (../../../common/temp/node_modules/.pnpm/@mikro-orm+mongodb@5.2.0_@mikro-orm+core@5.2.0/node_modules/@mikro-orm/mongodb/MongoPlatform.js:30:16)
      at BillingSystemAccountEntity.set (../../../common/temp/node_modules/.pnpm/@mikro-orm+core@5.2.0_@mikro-orm+mongodb@5.2.0/node_modules/@mikro-orm/core/entity/EntityHelper.js:40:42)
      at new MyEntity (src/features/my/my.entity.ts:41:9)
```

**To Reproduce**

1. Define an entity to have any non-ObjectId primary key (such as uuid).
2. try to set the `id` field  anywhere - such as perhaps `this.id = id_value;` in a constructor.

**Expected behavior**

I expect: 

*  EntityHelper.defineIdProperty behavior should match the comment above the function describing its behavior
* MongoPlatform.deNormalizePrimaryKey should consult existing metadata to determine if the target type for the primary key is an ObjectId before trying to convert it to an ObjectId - maybe the `PrimaryKeyType`?
* And ultimately, I can use something other than ObjectId as a primary key in mongo without having to jump through workarounds.

**Additional context**

Let me know if there is anything more that would be needed.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.15.0 |
| typescript | 4.7.4 |
| mikro-orm | 5.2.0 |
| mongo | 5.2.0 |

** Workaround ** 

The workaround that works is to never _set_ the `id` property - always directly set the `_id` field, but either can be read.

I might be able to contribute here, but I'd need some pointers on how to access the appropriate metadata in that deNormalizePrimaryKey function.

**Comment by B4nan** [comment]
Please show some code of what you are actually doing.

You can't have the PK as `id`, this is a mongo requirement, you will always get a column called `_id` and thats the PK. What you can do is to have a runtime entity property `id` mapped to the `_id` database field name:

```ts
@PrimaryKey({ name: '_id' })
id: ObjectId;
```

> The comment above the function claims “if […] there is no id property defined” - but that function doesn't have any such checking

That getter is added only if you define a serialized PK called `id` next to a real PK called `_id`, the check is a level above. I don't think that is your issue, unless you define the PK as serialized.

https://github.com/mikro-orm/mikro-orm/blob/7d5e32d8eb7ec25ace2336e1bd4da5d97d015c08/packages/core/src/entity/EntityHelper.ts#L26-L28

**Comment by davidpricedev** [comment]
It sounds like maybe we are defining the entity wrongly then? This is what I have: 

```typescript
export class MyEntity {
    [PrimaryKeyType]?: MyUUID];

    @PrimaryKey({ type: MyUUID })
    public _id: string = new bson.UUID().toHexString(true);

    @SerializedPrimaryKey({ type: MyUUID })
    public id!: string;
}
```

**Comment by B4nan** [comment]
Depends on what you want. The concept of serialized PK is here to allow working with string variant of ObjectId, you dont need to use that if your PK is a string. What about this: 

```
export class MyEntity {
    [PrimaryKeyType]?: string; // this needs to be the type of the value, not a Type class

    @PrimaryKey({ name: '_id', type: MyUUID })
    public id: string = new bson.UUID().toHexString(true);

}
```

**Comment by davidpricedev** [comment]
Thanks for your help, that is working well. Apologies for reporting as a bug what was my error.

**Comment by B4nan** [comment]
I'll try to add some validation for this, e.g. we could throw if serialized PK is defined and the PK is not `ObjectId`.
