### ISSUE TITLE
Removing an entity from a collection does not affect records in a transaction

### ISSUE THREAD

**Issue by mrmlnc** [mikro-orm/mikro-orm#3360]
> 📖 I'm not sure if the current behavior is a bug, but the behavior is not obvious to me.

**Describe the bug**

I have an entity with a 1:M relation. For this relation I'm set the `orphanRemoval: true` option. If I delete an item from a collection and then call the `em.persistAndFlush` method in the transaction, then the items will not be deleted from the database.

```ts
entity.children.removeAll();

await orm.em.transactional(async (em) => {
    // Works fine
    // entity.children.removeAll();

    // Simplified code. There are several operations.
    await em.persistAndFlush(entity);
});
```

> 📖 I have a repository that makes it easy to reproduce the problem:
> https://github.com/mrmlnc/mikro-orm-collection-transaction-issue

**To Reproduce**
1. `git clone https://github.com/mrmlnc/mikro-orm-collection-transaction-issue`
2. `npm ci`
3. `npm run start`

**Expected behavior**

Items removed from the collection will be removed from the database.

**Additional context**

I found that the problem disappears if you do a deletion inside a transaction. I think the current problem is related to copying the current state into the fork for transaction.

**Versions**

| Dependency | Version |
| - | - |
| node | `16.16.0` |
| typescript | `4.7.4` |
| mikro-orm | `5.3.0` |
| better-sqlite | `5.3.0` |

**Comment by B4nan** [comment]
I will need to take a closer look but I believe you are not flushing the outer EM where the propagation happens. Does it work if you call flush after the transactional call?

**Comment by mrmlnc** [comment]
Hm, If I understand you correctly. It works correctly.

```ts
entity.children.removeAll();

await orm.em.transactional(async () => {});

// Works fine
await orm.em.persistAndFlush(entity);
// OR await orm.en.flush();
```

**Comment by B4nan** [comment]
I am not entirely sure if its a good idea, but lets fix this and revert if it causes some troubles.
