### ISSUE TITLE
docs: How to define and use a property that is an array of objects of a custom type.

### ISSUE THREAD

**Issue by sokudo** [mikro-orm/mikro-orm#3371]
I was looking at https://mikro-orm.io/docs/custom-types and could not find an answer to the following question(s).

How to define a property that is an array of custom objects?
PostgreSQL supports that. Is it supported by MikroORM? If yes, how to do that?
1. Given
```typescript
export class Item {
  name!: string;
  sha!: string;
  constructor (x: Partial<Item>) {
     ...
  }
}

export class ItemType extends Type<Item | undefined, string | undefined> {
  ...
}
```
would like to define a field `children`
```typescript
@Entity()
export class Tree {

  @PrimaryKey()
  id!: number;

  @Property({ type: ArrayType })
  children: Item[];
}
```
and use it
```
  tree.children.push(new Item({name: 'a', sha: '...'});
  const item = tree.children[0];
```
Doc says:
```
You can also have arrays of numbers or other data types - to do so, you will need to implement custom hydrate method that is used for converting the array values to the right type.
```

Is an array of custom objects supported?
What to put into `convertToDatabaseValueSQL()`?
Where to implement the custom hydrate method?

Is it possible to have this example completed and add it to the doc at https://mikro-orm.io/docs/custom-types ?

2. Is it possible to have a foreign key field in the custom data type?
Does MikroORM support that?
How to define that?

3. Could we use a custom data type with a foreign field in an array?
Does MikroORM support that?

**Comment by sokudo** [comment]
In sum, could we compose ArrayType with composite object types?
And could we put foreign keys into composite object types?

**Comment by B4nan** [comment]
This is what embeddables are for:

https://mikro-orm.io/docs/embeddables
