### ISSUE TITLE
Allow to change `FROM` clause using `QueryBuilder`

### ISSUE THREAD

**Issue by derevnjuk** [mikro-orm/mikro-orm#3374]
**Description**
As a user, I would like to have the ability to change/add `FROM` clause in which the entity's table select/update/delete will be executed.

**Motivation**

For example, implementing the seek pagination with the ability to navigate to the previous page, you have to reverse the ordering of the result set (`ASC` vs `DESC`) using the same predicate so that the results you want are to the right of the cursor:

```sql
SELECT * 
FROM (
  SELECT * 
  FROM users 
  WHERE createdAt < ? 
  ORDER BY createdAt DESC 
  LIMIT 10
) AS u 
ORDER BY createdAt ASC;
```

Currently, this is possible to do only using `knex.fromRaw()`, exposing the implementation details of `QueryBuilder`. What could be a issue from design perspective. As soon as the implementation of either `QueryBuilder` or `knex` is changed (e.g. `mikro-orm` starts using a different query builder from `knex`), the user will have to rework a significant part of his code.

Just by declaring a `from()` method, we are able to give the user a powerful mechanism to handle this without necessity to rely on `knex`:

```ts
const qb = orm.em.qb(User, 'user')
  .where({ createdAt: { $lt: new Date() } })
  .orderBy({ createdAt: 'DESC' })
  .limit(10);

const users1 = qb.from(qb.getKnexQuery())
  .orderBy({ createdAt: 'ASC' });

const users2 = qb.from(qb.clone())
  .orderBy({ createdAt: 'ASC' });
```

**Possible solution**
The new method(s) can be introduced to be used to change/add `FROM` clause, removing all previously set from-s:

```ts
export declare class QueryBuilder<T extends AnyEntity<T> = AnyEntity> {
    from<TFrom extends AnyEntity<TFrom> = T>(entityTarget: TFrom | Knex.QueryBuilder | QueryBuilder<TFrom>): QueryBuilder<TFrom>;
    addFrom<TFrom extends AnyEntity<TFrom> = T>(entityTarget: TFrom | Knex.QueryBuilder | QueryBuilder<TFrom>): QueryBuilder<TFrom>;
}
```

**Comment by B4nan** [comment]
I hope you also plan to send some PRs, and not just a huge round of issues :]

**Comment by derevnjuk** [comment]
@B4nan I hope so, but I can't do this without your help)
