### ISSUE TITLE
Docs: Use-Case 3: Join-Table with Metadata improve docs with example of use

### ISSUE THREAD

**Issue by mstaniewski** [mikro-orm/mikro-orm#3379]
Hello,

I'm trying to implement meta data for M:M relation join table, although I'm missing an example on how to consume additional join table meta data.

Been implementing this as of https://mikro-orm.io/docs/composite-keys#use-case-3-join-table-with-metadata

I have a Project, User and ProjectMember entities, implemented as such:

```
@Entity()
export class User {
  @PrimaryKey()
  id: number;

  @Property()
  @Unique()
  email: string;

  @Property()
  @Field()
  password: string;
}

```

```
@Entity()
export class Project {
  @PrimaryKey()
  id: number;

  ...

  @ManyToMany({ entity: () => User, pivotEntity: () => ProjectMember })
  members = new Collection<User>(this);

  @Property()
  createdAt: Date = new Date();

  @Property({ nullable: true })
  updatedAt: Date;
}
```

```
@Entity()
export class ProjectMember {
  @ManyToOne({ primary: true })
  project: Project;

  @ManyToOne({ primary: true })
  user: User;

  @Enum({ type: () => ProjectMemberRole, nullable: true })
  role: ProjectMemberRole = ProjectMemberRole.EMPLOYEE;

  @Enum({
    type: () => ProjectMemberStatus
  })
  status: ProjectMemberStatus = ProjectMemberStatus.INVITED;

  @Property({ nullable: true, defaultRaw: 'now' })
  invitationSentAt!: Date;

  @Property({ nullable: true, default: null })
  invitationToken!: string = v4();

  [PrimaryKeyType]?: [number, number];
}
```

I'm not sure how to access join table meta data, how to update this kind of relation or delete it. Whether I should query from ProjectMember repository and populate user and project or there's some option in `EntityRepository` to load extra fields (Like in TypeORM, prop extra).

Could you please let me know on how to manage the join table meta, relate / unrelate, update meta data?

**Comment by B4nan** [comment]
Generally speaking you either use the pivot entity directly, or you define the relations with the 1:m variants instead of m:n (you can keep the m:n for reading purposes where you dont care about the extra columns). That is described exactly on the link you already have. I will add a note about working with the pivot entity directly, thats indeed missing, but should be quite streightforwad (regular CRUD over an entity with two m:1 properties).

> to load extra fields (Like in TypeORM, prop extra).

Do you have some links about how they do it?

**Comment by B4nan** [comment]
Hmm I can't really say I understand the usage there (never used objection myself). But I don't think we can find better ways than what I mentioned above if we want to keep things type safe. Either you have the explicit 1:m relation (where you literally have a collection of the pivot rows, that include the extra properties), or you work with the pivot entity as with any other entity.

**Comment by mstaniewski** [comment]
Thanks for advice. Please update the docs in a spare time.

**Comment by B4nan** [comment]
lets keep this open so i dont forget :]
