### ISSUE TITLE
Inverse side of ManyToMany relationship sometimes triggers a TypeError in schema:create

### ISSUE THREAD

**Issue by darkbasic** [mikro-orm/mikro-orm#338]
**Describe the bug**
If you provide the inverse side of a many-to-many relationship inside your entities, sometimes calling schema:create on the CLI will fail because of a TypeError.
My workaround is to remove the inverse sides from the entities, to run schema:create and then to restore them. The application itself works fine, it's just the schema:create which fails.

**Stack trace**
```
$ npx mikro-orm schema:create --fk-checks=true -d
mikro-orm schema:create

Create database schema based on current metadata

Opzioni:
  -r, --run      Runs queries                                         [booleano]
  -d, --dump     Dumps all queries to console                         [booleano]
  --fk-checks    Do not skip foreign key checks                       [booleano]
  -v, --version  Mostra il numero di versione                         [booleano]
  -h, --help     Mostra la schermata di aiuto                         [booleano]

TypeError: Cannot read property 'name' of undefined
    at Function.className (/home/niko/WebstormProjects/beach/server/node_modules/mikro-orm/dist/utils/Utils.js:253:28)
    at TsMorphMetadataProvider.extractType (/home/niko/WebstormProjects/beach/server/node_modules/mikro-orm/dist/metadata/TsMorphMetadataProvider.js:37:34)
    at TsMorphMetadataProvider.initProperties (/home/niko/WebstormProjects/beach/server/node_modules/mikro-orm/dist/metadata/TsMorphMetadataProvider.js:25:31)
    at TsMorphMetadataProvider.loadEntityMetadata (/home/niko/WebstormProjects/beach/server/node_modules/mikro-orm/dist/metadata/TsMorphMetadataProvider.js:16:9)
    at MetadataDiscovery.discoverEntity (/home/niko/WebstormProjects/beach/server/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:109:9)
    at MetadataDiscovery.discoverDirectory (/home/niko/WebstormProjects/beach/server/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:80:13)
    at Function.runSerial (/home/niko/WebstormProjects/beach/server/node_modules/mikro-orm/dist/utils/Utils.js:303:22)
    at MetadataDiscovery.findEntities (/home/niko/WebstormProjects/beach/server/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:56:13)
    at MetadataDiscovery.discover (/home/niko/WebstormProjects/beach/server/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:30:9)
    at Function.init (/home/niko/WebstormProjects/beach/server/node_modules/mikro-orm/dist/MikroORM.js:45:24)
    at Function.handleSchemaCommand (/home/niko/WebstormProjects/beach/server/node_modules/mikro-orm/dist/cli/SchemaCommandFactory.js:51:21)
```

**To Reproduce**
I'm not sure what exactly is causing this behaviour, because almost identical ManyToMany inverse relationship may or may not cause the described behaviour.
I don't have a repro, but I can give access to a private repo with the faulty code.

**Versions**

| Dependency | Version |
| - | - |
| node | v13.8.0 |
| typescript | 3.7.5 |
| mikro-orm | 3.1.1 |
| pg | 7.18.1 |

**Comment by B4nan** [comment]
The code that throws the error is pretty much this:

https://github.com/mikro-orm/mikro-orm/blob/master/lib/metadata/TsMorphMetadataProvider.ts#L45

```typescript
  private extractType(prop: EntityProperty): string {
    if (Utils.isString(prop.entity)) {
      return prop.entity;
    }

    if (prop.entity) {
      return Utils.className(prop.entity()); // here
    }

    return prop.type;
  }
```

That would mean your `entity` callback in the decorator returns `undefined`. I guess you have a reference there, and there will be some circular dependency that causes the issue. You might want to change order of imports, or you can always use a string instead of reference. 

Could you debug that a bit more? Does it happen all the time (for particular entity/property), or is it random? If you can grant me the access, I can take a look.

**Comment by darkbasic** [comment]
Yes, it happens all the time for a particular entity/property, but not for all of them.
I've pushed the codebase to a repo and granted you access. It's a very small project so it should be easy to debug it.

**Comment by B4nan** [comment]
This is definitely circular dependency problem. I was able to work around that by using strings instead of entity references in decorators. It's really weird that is fails in CLI while it runs ok otherwise... Will need to spend more time debugging how is the code path different.

Btw to overcome this for now, you can also generate the cache first by running the app, and using the CLI afterwards, which will then use the cache instead of doing the discovery again. Keep in mind that node and ts-node have separate cache so if you would like to run the CLI in production, you need to run via node, and vice versa.

**Comment by darkbasic** [comment]
Circular deps are definitely annoying, I remember having similar issues back when I was using TypeORM and even when I was working on GraphQL-Modules. It's strange that it only happens on the CLI anyway...

**Comment by darkbasic** [comment]
> Btw to overcome this for now, you can also generate the cache first by running the app, and using the CLI afterwards

I tried your suggested workaround but it didn't work. I tried with both `yarn start` and `yarn start:ts-node` (the first one uses node while the second one uses ts-node) but still no luck with both `node ./node_modules/.bin/mikro-orm schema:create --fk-checks=true -d` and `ts-node ./node_modules/.bin/mikro-orm schema:create --fk-checks=true -d`

With the second one I get a different error:
```
$ ts-node ./node_modules/.bin/mikro-orm schema:create --fk-checks=true -d 
mikro-orm schema:create

Create database schema based on current metadata

Opzioni:
  -r, --run      Runs queries                                         [booleano]
  -d, --dump     Dumps all queries to console                         [booleano]
  --fk-checks    Do not skip foreign key checks                       [booleano]
  -v, --version  Mostra il numero di versione                         [booleano]
  -h, --help     Mostra la schermata di aiuto                         [booleano]

src/entities/BaseEntity.ts:2:5 - error TS7022: '__decorate' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

2 var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
      ~~~~~~~~~~
src/entities/BaseEntity.ts:2:57 - error TS7006: Parameter 'decorators' implicitly has an 'any' type.

2 var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
                                                          ~~~~~~~~~~
src/entities/BaseEntity.ts:2:69 - error TS7006: Parameter 'target' implicitly has an 'any' type.

2 var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
                                                                      ~~~~~~
src/entities/BaseEntity.ts:2:77 - error TS7006: Parameter 'key' implicitly has an 'any' type.

2 var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
                                                                              ~~~
src/entities/BaseEntity.ts:2:82 - error TS7006: Parameter 'desc' implicitly has an 'any' type.

2 var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
                                                                                   ~~~~
src/entities/BaseEntity.ts:4:55 - error TS2339: Property 'decorate' does not exist on type 'typeof Reflect'.

4     if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
                                                        ~~~~~~~~
src/entities/BaseEntity.ts:4:92 - error TS2339: Property 'decorate' does not exist on type 'typeof Reflect'.

4     if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
                                                                                             ~~~~~~~~
src/entities/BaseEntity.ts:12:14 - error TS2339: Property 'createdAt' does not exist on type 'BaseEntity'.

12         this.createdAt = new Date();
                ~~~~~~~~~
src/entities/BaseEntity.ts:13:14 - error TS2339: Property 'updatedAt' does not exist on type 'BaseEntity'.

13         this.updatedAt = new Date();
```

**Comment by B4nan** [comment]
So I gave this one another look. The difference when running via CLI is that you do not load the entities yourself before initializing the ORM. When running the app normally, you do (because you are registering the repositories). If I add these lines to the top of the ORM config file, then it will work, as I am forcing to load those entities before the ORM discovery finds them. 

```typescript
import { BaseEntity, Site, User, Match, Sport, Specialty, Relationship } from './entities';
const entities = [BaseEntity, Site, User, Match, Sport, Specialty, Relationship];
```

The whole problem is that this way you do have control on the loading of entities. I don't think there is a way to fix this in the ORM, so will close this one. 

In other words, you can also easily fix this by defining the entities via `entities` array instead of using the folder based discovery. Here is all what I changed in the project to make it work:

```diff
Index: src/mikro-orm.config.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/mikro-orm.config.ts	(revision 8d38d39b0d5fba8c37b89c3cbd4531d156b8970b)
+++ src/mikro-orm.config.ts	(date 1585314846454)
@@ -1,5 +1,7 @@
+import { BaseEntity, Site, User, Match, Sport, Specialty, Relationship } from './entities';
+
 export default {
-  entitiesDirs: ['./build/src/entities'],
+  entities: [BaseEntity, Site, User, Match, Sport, Specialty, Relationship],
   entitiesDirsTs: ['./src/entities'],
   dbName: 'beach',
   user: 'beach',
```

**Comment by darkbasic** [comment]
@B4nan maybe we could add a section in the docs about circular imports?

**Comment by B4nan** [comment]
Yeah agreed, will add something later today, you are not the only one facing this, and I am glad that there is relatively straightforward answer - use the `entities` array to have control over the order of entity imports as the folder based discovery will require them in the order they are found.
