### ISSUE TITLE
Add debug log on createQueryBuilder

### ISSUE THREAD

**Issue by willmeeh** [mikro-orm/mikro-orm#3380]
With debug flag as true on init config, i expected all queries to be printed to the console. Bu only abstract EntityManager methods like **findOne** are being printing.

```
// This line is not printed in the logs:
await db.em.createQueryBuilder(Entity).raw(`select * from entity_name where id = ? limit 1`, [1]);

// This line prints in the logs:
await db.em.findOne(Aceite, { id: 1 });
```

It would be nice if createQueryBuilder also displays the queries in the logs.

**Comment by B4nan** [comment]
By using `qb.raw()` and awaiting the instance you are using knex to execute it. If you want the query to be logged, execute it via the ORM instead:

```
const query = db.em.createQueryBuilder(Entity).raw(`select * from entity_name where id = ? limit 1`, [1]);
const res = await db.em.execute(query);
```
