### ISSUE TITLE
[Suggestion] Release canary versions on each commit to ease testing

### ISSUE THREAD

**Issue by darkbasic** [mikro-orm/mikro-orm#339]
In my project I need `@unique` decorators, which have been pushed to master just 3 days ago.
I wanted to test them, but unfortunately there is still no released version supporting those new decorators. Of course I can compile my own version and link it to my project, but it's good to have alphas automatically released on a per-commit basis because it allows for easier and more reproducible testing.

Here is how canary versions can be easily implemented using Github Actions: https://github.com/dotansimha/graphql-code-generator/blob/master/.github/workflows/main.yml#L40

**Comment by B4nan** [comment]
I was thinking about that too, thanks for the link, will try to look into this soon. 

Will also release some dev version later this evening probably so you can try things out. Will release 3.2 once #283 is done.

**Comment by B4nan** [comment]
Ok, I was finally brave enough to try `lerna --canary` to find out it actually does what I want from it :D It was a bit challenging to get the CI working, but it should be ok finally. 

New dev builds should be shipped every day at 6am (if there is something to ship).

**Comment by B4nan** [comment]
Looks like it's working, only downside is the spam from NPM, 13 emails for each release and they do not have any way to configure this 🤦 Will need to set up a rule to remove all that automatically, already did that with spam from JIRA some time ago (highly recommended if you are using it) :D 

It's tempting to keep this enabled for each commit when the tests are successful, will probably do it that way...

**Comment by darkbasic** [comment]
> It's tempting to keep this enabled for each commit when the tests are successful, will probably do it that way...

It's very useful, I recommend doing so!
