### ISSUE TITLE
Bug while executing migrations (Postgres)

### ISSUE THREAD

**Issue by nicomouss** [mikro-orm/mikro-orm#3390]
**Describe the bug**
This bug is related to #190 and #422

Using Postgres, an exception is raised when executing mikro-orm migrations if not connected to the Postgres instance as a superuser.

```js
const migrator = orm.getMigrator();
await migrator.up();
 
// Exception raised:
// set session_replication_role = 'replica'; - permission denied to set parameter "session_replication_role"
```

As noted within #190 and #422, there is the `wrap` parameter, but it is only available when using mikro-orm schema generator.

```js
const generator = orm.getSchemaGenerator();
await generator.createSchema({ wrap: false }); // Ok, no exception raised
```

**Expected behaviour**
In a secured Postgres production environment, we typically use a "db_admin" user, which is the db owner of the database (but which is not a superuser of the whole Postgres instance). You might not have any choice about that, as a production server administrator will probably never want to grant superuser privileges to someone.

That db_admin user is used to CREATE/DROP/ALTER tables on the database (meaning that user is used when executing your mikro-orm migrations). Then typically you would use another "db_user" when your app goes live, to access the db with only SELECT/UPDATE/DELETE... rights granted on tables.

That way you properly secure your Postgres production environment, and prevent some security hazards.

In order to enforce good practices about security, in my opinion there should be nothing on mikro-orm side preventing this setup.

**Additional context**

For the time being, to make things work you can monkey-patch mikro-orm like so:

```js
import { PostgreSqlSchemaHelper } from "@mikro-orm/postgresql";

// Code to be executed at app startup before everything else
PostgreSqlSchemaHelper.prototype.enableForeignKeysSQL = () => '';
PostgreSqlSchemaHelper.prototype.disableForeignKeysSQL = () => '';
```

This disables mikro-orm to issue `set session_replication_role` SQL commands, which are the source of the problem described here.

Now things are working properly:

```js
const migrator = orm.getMigrator();
await migrator.up(); // Ok, no exception raised

const generator = orm.getSchemaGenerator();
await generator.createSchema(); // Ok, no exception raised (no need of wrap option anymore)
```

**Versions**

| Dependency | Version |
| - | - |
| node | 16.14.2 |
| typescript | 4.6.3 |
| mikro-orm | 5.3.1 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
For migrations you need to use the ORM config. Migrator is not doing any diffs, hence there is no wrap parameter - its still the schema generator. 

```ts
orm = await MikroORM.init({
  migrations: {
    disableForeignKeys: false,
  },
})
```

https://mikro-orm.io/docs/migrations#configuration

And I believe it should as well respect the schema generator option, as again, its the schema generator who produces the queries:

```ts
orm = await MikroORM.init({
  schemaGenerator: {
    disableForeignKeys: false,
  },
})
```

**Comment by nicomouss** [comment]
Oh yes, very neat, thanks.

Didn't notice that `disableForeignKeys` options would disable the `set session_replication_role` SQL stuff.
All good then!
