### ISSUE TITLE
Implement transactions in mongo driver

### ISSUE THREAD

**Issue by B4nan** [mikro-orm/mikro-orm#34]
MongoDB 4 supports transactions, so we should add support for that. 

Maybe via new driver keeping the current `MongoDriver` for MongoDB 3, or via some configuration option that would be disabled by default (or automatically enabled via feature detection/version comparison).

**Comment by B4nan** [comment]
Looking into this now, already god the basics implemented, just have to adjust docker and travis setup so we can test it. 

@j as you were requesting this recently, do you think we should allow optional transactions in mongo or should we have it always enabled? It will require running replica set and it might not be needed for most users, so I am thinking about having it optional, just not sure about the default value. 

Also tagging @gustavopch and @seiyria as I know they are using the mongo driver.

**Comment by seiyria** [comment]
It should definitely be optional, off by default. Most people using or developing software will be running a single node of mongo.

**Comment by j** [comment]
Sorry for the late response, just saw this.  @B4nan That's a rough one.  I actually started 100% mongo transactions in a re-write and before I got too ahead of myself I decided to benchmark the two use-cases.  In a high traffic environment, transactions definitely slow things down, so I'd say keep it optional.  I don't think it should be either OFF or ON, but selective somehow?

I still want to be able to do a transaction if I want to.

We run ecom, so transactions on checkouts are pretty crucial.

**Comment by j** [comment]
Also, unrelated and I don't want to create another issue for a question.  I haven't dug into how the UoW does changeset tracking.  Does it just simply check the root object and if that root object changes, to update it?

In other words, if I have an array and remove an element at index 2 from it, is it smart enough to issue a pull on that index?  I know DoctrineODM does smart updates like this.  I'm sure this type of change-set tracking is hard to do though.  I was hoping one day there'd be a proxy library that's smart enough to figure a Mongo query based off changes.  I attempted it and gave up. Haha.

**Comment by B4nan** [comment]
So I guess it could work this way:
- add new config toggle (global) to enable/disable implicit transactions (those that happen automatically when flushing)
- add new platform option to distinguish drivers that are capable of tx but do not want them implicitly by default (will be true for mongo platform)
- so by default, mongo will be able to do explicit transactions via `em.transactional()`, but flushing will not cause implicit ones
- you will be able to enable implicit transactions manually, which will result in same behaviour as sql drivers

I will probably delay this for some 3.x release as it turned out being not that easy to incorporate into CI build and mainly because I don't want to postpone v3 release forever :]

> Does it just simply check the root object and if that root object changes, to update it?

Currently yes, but it will update only properties that actually changed. But for array, it will update it as a whole. Would be nice to support more granular array change sets, but nothing I am planning to work soon...

**Comment by ujwal-setlur** [comment]
Any update on this?

**Comment by B4nan** [comment]
It will land soon, probably not next feature release, but the following one (3.5).

**Comment by B4nan** [comment]
Will be part of 3.4. 

https://mikro-orm.io/docs/next/usage-with-mongo/#transactions
