### ISSUE TITLE
Cloning entity with non initialized collection

### ISSUE THREAD

**Issue by l00k** [mikro-orm/mikro-orm#3401]
**Describe the bug**
Atm it is not possible to simply clone (lodash clone) entity which has not initialized collection (for example entity loaded without population). I know entity should not be cloned when you deal with ORM. However in this case I want to serialize entity to send it as plain json so I want operate on clone - not original entity. My serialization process is a way complicated so I can't use `toJSON` or any other solution.

To fix this I used more complicated cloning process - first detect collection / entity with `cloneWith` and then create new instance of `Collection` with original collection items

**Stack trace**
```
Error: Collection<AssetPrice> of entity Asset[4] not initialized
    at Collection.checkInitialized (.../api/node_modules/@mikro-orm/core/entity/Collection.js:289:19)
    at Collection.count (.../api/node_modules/@mikro-orm/core/entity/Collection.js:141:14)
    at Collection.get length [as length] (.../api/node_modules/@mikro-orm/core/entity/ArrayCollection.js:139:21)
    at isArrayLike (.../api/node_modules/lodash/isArrayLike.js:30:42)
    at keys (.../api/node_modules/lodash/keys.js:34:10)
    at baseAssign (.../api/node_modules/lodash/_baseAssign.js:14:39)
    at baseClone (.../api/node_modules/lodash/_baseClone.js:123:32)
    at clone (.../api/node_modules/lodash/clone.js:33:10)
```

**To Reproduce**
1. load entity from db with collection not populated
2. clone entity with `lodash/clone`

**Expected behavior**
I think getter from ArrayCollection `get length()` should not trigger errors.
So I suggest to add `check = true` to `Collection.count()` the same as `getItems(check = true)` and use version without check in getter.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.15 |
| typescript | 4.7.4 |
| mikro-orm | 5.3.0 |
| your-driver | mysql |

**Comment by B4nan** [comment]
I dont really like this idea, and I would first like to hear why you think you cant use `toJSON` or similar. Converting to POJO first is the right approach, not removing invariants from the ORM and making it less safe/correct.

> So I suggest to add check = true to Collection.count() the same as getItems(check = true) and use version without check in getter.

What you suggest is changing behaviours, you want to have the default set to `false` unlike with `getItems()`.

And more importantly, why would you want to clone an entity is my main question. If you dont want to track changes on it, you should fetch it via a separate fork, or with `disableIdentityMap: true`. 

> To fix this I used more complicated cloning process - first detect collection / entity with cloneWith and then create new instance of Collection with original collection items

You might easiily fall into issues with persistence with such collections, if you break the internal state, or worse, if you let one entity be managed by multiple EMs.

**Comment by l00k** [comment]
In case of simple objects (without nested entities) `toJSON` is good enough. However sometimes even is such case it would be better to have control over that process - for example some properties may require additional processing when serializing / deserializating.
But when I have nested entities I don't want to get final JSON in one call - cuz I may want to serialize objects on lower levels in different way. For example - I may want to convert collection of entries to collection of ID strings (like "@/asset/23"). That process depends on object constructor type so I don't want to lose it after `toJSON` call.
I want to traverse entire nested object tree and process it manually.
For that purpose I want clone of EM managed object which will not be managed (EM lose track of it) anymore but keeps all typings (class constructors).
Check `class-transformer` for example. My serializer is similar to that library, however it also doesn't provide enough control over process and that is why I implemented my own.

Like I wrote before I fully understand `clone` is not adviced when one deal with managed objects and want to use cloned object later as ORM entity. But in my case cloning is done to:
1. lose reference to managed object 
2. keep object typing

If propsed adjustment breaks something - or even you only think it may break something - that is ok for me, I will preserve special clone version for ORM entities.

**Comment by B4nan** [comment]
> However sometimes even is such case it would be better to have control over that process - for example some properties may require additional processing when serializing / deserializating.

You have `toPOJO` for cloning purposes, it ignores populate hints. You also have [property serializers](https://mikro-orm.io/docs/serializing#property-serializers).

Anyway, what about using https://lodash.com/docs/#cloneDeepWith instead, and handling not initialized collections that way?

Because such collections shoudn't be mapped to empty arrays in the first places. Uninitialized collection is not the same as empty one. You should probably skip such fields instead of turning them to empty arrays.

**Comment by l00k** [comment]
> Because such collections shoudn't be mapped to empty arrays in the first places. Uninitialized collection is not the same as empty one. You should probably skip such fields instead of turning them to empty arrays.  

That makes sense. But as long as this behavior is described it is not so bad to return empty array for non initialized collection.

`cloneWith` is just enough if I pass proper handling function - I have it already working.
My suggestion was only to simplify it so `clone` would also work. I thought it will not be large change.

If you meant
```
count() {
    return this.isInitialized()
        ? super.count()
        : undefined;
}
```
it works well.

**Comment by B4nan** [comment]
> That makes sense. But as long as this behavior is described it is not so bad to return empty array for non initialized collection.

Let me disagree. One of the use cases for serializing entity is caching, with your changes the entity restored from cache would be invalid - it would suddently have initialized empty collections, instead of uninitialized ones. Their state would change. This is the part I dont like, this is why I even consider it breaking.

> it works well.

So it results in the property being omitted or it just produces empty array regardless of the length value?

I'll be happy to add some config toggle to allow this, but making it default behaviour seems dangerous/wrong. And I would much rather return `undefined` in there, especially if it would mean the collection property will be omitted from the cloned result.

**Comment by l00k** [comment]
>  add some config toggle to allow this

Ouu in that case it is overkill. I will stay with custom cloning for ORM entities.
I will close this. Thx for responsiveness.
