### ISSUE TITLE
Entity with composite key that auto-increments does not populate the key after `flush()`

### ISSUE THREAD

**Issue by amzhang** [mikro-orm/mikro-orm#3408]
**Describe the bug**
Entity with composite key that auto-increments does not populate the key after `flush()`

**To Reproduce**
Entity:
```ts
export class SampleTestRepository extends EntityRepository<SampleTest> {}

@Entity({ customRepository: () => SampleTestRepository })
export class SampleTest extends BaseEntity<SampleTest, 'id' | 'time'> {
  @PrimaryKey({ type: t.bigint, autoincrement: true })
  id: string;

  @PrimaryKey()
  time: Date;

  [PrimaryKeyType]?: [string, Date]; // this is needed for proper type checks in `FilterQuery`
}
```

Creating instance
```ts
const sampleTest = await this.sampleTestRepository.create(input);
await this.sampleTestRepository.persistAndFlush(sampleTest);
console.log(sampleTest);
```

`sampleTest.id` always has value "0". The entity in the DB behaves correctly with auto-incrementing `id`.

**Expected behavior**
The auto-incrementing `id` field should be populated after `persistAndFlush()`

**Versions**
V5

| Dependency | Version |
| - | - |
| node | v16.16.0 |
| typescript | 4.7.4 |
| mikro-orm | 5.3.1 |
| your-driver | @mikro-orm/postgresql: 5.3.1 |

**Comment by B4nan** [comment]
This is not supported, composite keys need to have both sides provided up front.

Technically doable at the SQL level, not supported in the ORM implementation.

**Comment by B4nan** [comment]
Btw whats the use case? Why is the autoincrement PK not enough on its own? 

You are like third person in last year asking for this, so maybe it would be worth supporting, but this invariant of composite key having all values know up front is used in many places, so it might be quite painful and require a lot of tests.

**Comment by amzhang** [comment]
Now that I think about this, I don't think auto-increment is the right choice for my use case:

I'm using the postgres extension `TimescaleDB` to store time-series data from videos. Since a single video frame can contain multiple events the timestamp field is not unique. But `TimescaleDB` requires the timestamp field to have a unique index or be a party of a composite key. So I have to create a column that's unique.

I should be using UUID as the column type and just initialise it in the entity as the documentation says:

```ts
@PrimaryKey({ type: t.uuid })
id: UuidType = uuid();

@PrimaryKey()
time: Date;

[PrimaryKeyType]?: [UuidType, Date]; // this is needed for proper type checks in `FilterQuery`
```

The UUID is 16 bytes, bigserial is 8 bytes, so not a big deal. The timestamp field gives me natural ordering, so there's no need for auto-increment column.

**Please discount my used case.**
