### ISSUE TITLE
Using operators directly on embeddable properties

### ISSUE THREAD

**Issue by B4nan** [mikro-orm/mikro-orm#3430]
Same issue here, I got same error when I want to filter data by nullable embeddable value

Schema:
```typescript
@Embeddable()
class Address {
  @Property()
  addressLine1: string;

  @Property()
  addressLine2: string;

  @Property()
  city: string;

  @Property()
  country: string;
}

@Entity()
export class Organization {
  @PrimaryKey()
  id: string;

  @Embedded(() => Address, { object: true, nullable: true })
  address: Address | null;
}
```

Failed with this query
```typescript
this.organizationRepo.findAndCount({ address: { $ne: null } });  // Using operators inside embeddables is not allowed, move the operator above. (property:Organization.address, payload: { address: { '$ne': null } })
```

CodeSandbox: [https://codesandbox.io/s/dawn-waterfall-cjcoft](https://codesandbox.io/s/dawn-waterfall-cjcoft)

---

**Update**
I can get data with this query, but I would prefer to use `{ $ne: null }`
```typescript
this.organizationRepo.findAndCount({ address: { addressLine1: { $exists: true } } });
```

_Originally posted by @ah-nvision in https://github.com/mikro-orm/mikro-orm/discussions/2894#discussioncomment-3506899_

**Comment by B4nan** [comment]
I was thinking about a workaround like `$not: { address: null }`, which would get around this validation, but looks like comparing it to `null` also does not work.

**Comment by ah-nvision** [comment]
> I was thinking about a workaround like `$not: { address: null }`, which would get around this validation, but looks like comparing it to `null` also does not work.

Just tried this, and seems it is not supported in MongoDB
```
MongoServerError: unknown top level operator: $not. If you have a field name that starts with a '$' symbol, consider using $getField or $setField.
```

**Comment by B4nan** [comment]
I see, yeah `$not` literally represents the [`NOT` operator](https://www.w3schools.com/sql/sql_ref_not.asp) in SQL queries.

**Comment by B4nan** [comment]
That should be already possible, we have tests for that too, e.g. https://github.com/mikro-orm/mikro-orm/blob/master/tests/features/embeddables/GH4787.test.ts#L51

If it doesn't work for you, provide a complete repro.

**Comment by svchostdotexe** [comment]
thanks for the fast answer! then i am doing something wrong. will provide a repo in case i can't solve it.

any idea where to start from this error message?

``` "TypeError: Cannot convert undefined or null to object\"```

**Comment by B4nan** [comment]
Yes, you start by providing the full stack trace, because without that, most of error messages are useless 😉

**Comment by svchostdotexe** [comment]
sorry my bad :pensive: 

i think i found the issue, i am on a very old version of mikroorm but cannot upgrade right now sadly. i have 5.6.8, ```core: improve handling of nullable embedded properties ``` was added in 5.8.7

still thank you for the responses and also for providing us with mikroorm, such a great tool :+1:
