### ISSUE TITLE
[ ] works in wrap(entity).assign() but never write to database

### ISSUE THREAD

**Issue by sonicgamer0721** [mikro-orm/mikro-orm#3434]
**Describe the bug**
Hi, I wrote this code to update User table with RESTful API, and I found something wired: 
1. If 'roles' is not an empty array ( for example: [1, 2] or [1] ), everything works fine.
2. When I wanted to remove all roles, I used **roles=[]** in this code, but MikroORM did not update the database.

The wired thing is:
After **wrap(entity).assign()**, **user.roles.loadCount()** returned **0**. That means **[] worked** in code but finally it did not write to database with **em.flush()**.

I've tried my best but still got confused. Could someone help me?

**Stack trace**
```typescript
// User entity
@Entity()
export class User {
...
  @ManyToMany(() => Role, (role) => role.users)
  roles = new Collection<Role>(this);
...
}

// The Code
const em = this.em;

for await (const updateUserDto of updateUserDtos) {
  const { id, roles, ...dto } = updateUserDto;
  const user = await em.findOne(User, { id });
  wrap(user).assign({
    ...dto,
    roles: roles.map((id) => em.getReference(Role, id)),
  });
  console.log(await user.roles.loadCount());
}

await em.flush();
```

**Versions**

| Dependency | Version |
| - | - |
| node | 16.15.0 |
| mikro-orm | 5.3.1 |
| mikro-orm/mariadb | 5.3.1 |
| mikro-orm/nestjs | 5.1.1 |

**Comment by B4nan** [comment]
Flushing is what will save things to database, and you flush after you check for the count. It actually probably auto-flushes to give you the right number. 

Anyway, it works fine for me, closing, lets reopen with complete reproduction.

> That means [] worked in code but did not write to database with em.flush().

Well, to me this proves the opposite, that it actually worked. `loadCount` gives you the result from database (or a cached one if called multiple times). If the number is right, it means the changes were flushed. 

Why dont you enable debug mode and check what queries are produced?

**Comment by sonicgamer0721** [comment]
> Why dont you enable debug mode and check what queries are produced? And what makes you think the changes are not written to database?

Yes I enabled debug mode and checked that no update queries were produced. That is why I said it is so weird. What else can I do to solve this?

**Comment by B4nan** [comment]
> What else can I do to solve this?

As I said, provide complete reproduction. Cant help you without seeing what you actually do, the code you provided is not enough to reproduce.

**Comment by sonicgamer0721** [comment]
I'm so sorry B4nan, my mistake. I pasted the wrong code. I use **user.roles.getItems()** not **user.roles.loadCount()**.
The truth is, **user.roles.getItems()** returned [], but it did not produced the update queries.

> As I said, provide complete reproduction. Cant help you without seeing what you actually do, the code you provided is not enough to reproduce.

OK.

**Comment by B4nan** [comment]
> The truth is, user.roles.getItems() returned [], but it did not produced the update queries.

Its the `em.flush()` call that does queries. `getItems` (or any other sync API) can never read things from database, it only gives you the current state.
