### ISSUE TITLE
@Unique decorator does not work when applied on the entity class

### ISSUE THREAD

**Issue by darkbasic** [mikro-orm/mikro-orm#344]
**Describe the bug**
When trying to create a composite unique constraint I noticed that it doesn't create any when I run `npx mikro-orm schema:create --fk-checks=true -d` if I put it into the entity class.
Instead, if I put `@Unique({properties: ['userOne', 'userTwo']})` into a single entity property it works fine:
```
alter table "relationship" add constraint "relationship_user_one_id_user_two_id_unique" unique ("user_one_id", "user_two_id");
```

Trying to put it into both properties leads to duplicate entries:
```
alter table "relationship" add constraint "relationship_user_one_id_user_two_id_unique" unique ("user_one_id", "user_two_id");
alter table "relationship" add constraint "relationship_user_one_id_user_two_id_unique" unique ("user_one_id", "user_two_id");
```

I also tried to put `@Unique({properties: ['userOne', 'userTwo']})` into the class and just `Unique()` into the properties (like in the documentation), but it ended up generating the following:

```
alter table "relationship" add constraint "relationship_user_one_id_unique" unique ("user_one_id");
alter table "relationship" add constraint "relationship_user_two_id_unique" unique ("user_two_id");
```

**To Reproduce**
You can checkout my personal project again in order to easily reproduce it. Please notice that I rebased it, so you will have to re-clone it or run `git fetch && git reset --hard origin/master`

**Versions**

| Dependency | Version |
| - | - |
| node | 13.9.0 |
| typescript | 3.7.5 |
| mikro-orm | 3.2.0 |
| pg | 7.18.1 |

**Comment by B4nan** [comment]
Confirmed, also present for `@Index` decorator on the entity level. 

> Trying to put it into both properties leads to duplicate entries:

That is kinda "correct behaviour", you should put it only to one of them, or actually only to the entity and not to its properties as it is compound index. 

> I also tried to put @Unique({properties: ['userOne', 'userTwo']}) into the class and just Unique() into the properties (like in the documentation), but it ended up generating the following:

I guess the docs/example are a bit misleading, `@Unique({properties: ['userOne', 'userTwo']})` is compound index, while using `@Unique()` on property level is simple unique constraint for that column only.

**Comment by B4nan** [comment]
Fixed in 3.2.1

**Comment by darkbasic** [comment]
@B4nan I updated to 3.2.1 but `npx mikro-orm schema:update --fk-checks=true -d` doesn't create the unique constraint (it didn't create it before).
If I run `npx mikro-orm schema:create --fk-checks=true -d` it works, but it should work with update as well.

**Comment by B4nan** [comment]
I am planning to rework the logic how schema updates are computed soon.
