### ISSUE TITLE
`@mikro-orm/core` depends on older version of `mikro-orm` 

### ISSUE THREAD

**Issue by jbmikk** [mikro-orm/mikro-orm#3441]
**Describe the bug**
I'm not sure this is a bug, and maybe it's not even important.

I updated to `5.4` and I noticed something weird in my `yarn.lock` file. It looks like it's depending on the previous version of the `mikro-orm` meta-package.
I know it's not a big deal because it's just a meta-package, I just found it weird and I'm not sure if it's intentional or not.

**Additional context**
```
"@mikro-orm/core@^5.4.0":
  version "5.4.0"
  resolved "https://registry.yarnpkg.com/@mikro-orm/core/-/core-5.4.0.tgz#29432927e6b8462a5ed00e638e523e5c6dd9e895"
  integrity sha512-x7H7X3EOxyiEuW0kqujTDTGPQsF0iUNHKMh7xxEhzj+4BlYebiAsmTtekoFJ500kcXqt7ICbcOu3RmfLcUSC4w==
  dependencies:
    acorn-loose "8.3.0"
    acorn-walk "8.2.0"
    dotenv "16.0.2"
    fs-extra "10.1.0"
    globby "11.0.4"
    mikro-orm "^5.3.1"
    reflect-metadata "0.1.13"
```

**Versions**
| Dependency | Version |
| mikro-orm | 5.4 |

**Comment by B4nan** [comment]
Yeah for some reason lerna is not bumping that package, although I am explicitly adding `--force-publish` flag.
