### ISSUE TITLE
Cannot use v5.4.0 with ts-node on Node v16

### ISSUE THREAD

**Issue by XanderEmu** [mikro-orm/mikro-orm#3442]
**Describe the bug**
After upgrading to v5.4.0 I can no longer run `npx mikro-orm debug` (or use it in any other way) if `ts-node` is involved. It has something to do with how dynamic imports are handled now.

I *did* make it work tho by running it like this:
```
node_modules/.bin/ts-node-esm node_modules/@mikro-orm/cli/cli debug
```

also like this (when running my app, not the mikro-orm's CLI itself):
```
node --inspect=0.0.0.0:9229 --loader ts-node/esm bootstrap.ts
```

Prior to the upgrade, it did work out of the box.
Everything seems to be fine outside the `ts-node`'s context (e.g. when running compiled JS).

**CLI**
```
npx mikro-orm debug 
Current MikroORM CLI configuration
 - dependencies:
   - mikro-orm 5.4.0
   - node 16.17.0
   - typescript 4.6.4
 - package.json found
 - ts-node enabled
 - searched config paths:
   - /path/to/my/project/config/mikro-orm.config.override.ts (not found)
   - /path/to/my/project/config/mikro-orm.config.ts (found)
   - /path/to/my/project/config/mikro-orm.config.js (not found)
   - /path/to/my/project/mikro-orm.config.ts (not found)
   - /path/to/my/project/mikro-orm.config.js (not found)
- configuration not found (Unknown file extension ".ts" for /path/to/my/project/config/mikro-orm.config.ts)
```

**tsconfig.json**
```
{
    "compilerOptions": {
      "target": "es2021",                       /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017','ES2018' or 'ESNEXT'. */
      "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
      "lib": ["es2021", "DOM"],                 /* Specify library files to be included in the compilation. */
      "declaration": true,                      /* Generates corresponding '.d.ts' file. */
      "sourceMap": true,                        /* Generates corresponding '.map' file. */
       "outDir": "build",                       /* Redirect output structure to the directory. */
      "strict": true,                           /* Enable all strict type-checking options. */
       "strictPropertyInitialization": false,  /* Enable strict checking of property initialization in classes. */
       "alwaysStrict": true,                  /* Parse in strict mode and emit "use strict" for each source file. */
       "noUnusedLocals": true,                /* Report errors on unused locals. */
       "noUnusedParameters": true,            /* Report errors on unused parameters. */
       "noImplicitReturns": true,             /* Report error when not all code paths in function return a value. */
       "noFallthroughCasesInSwitch": true,    /* Report errors for fallthrough cases in switch statement. */
      "moduleResolution": "node",               /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
      "rootDirs": [                             /* List of root folders whose combined content represents the structure of the project at runtime. */
      ],
      "types": [                                /* Type declaration files to be included in compilation. */
          "node",
          "mocha"
      ],
      "esModuleInterop": true,                  /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
      "experimentalDecorators": true,           /* Enables experimental support for ES7 decorators. */
      "emitDecoratorMetadata": true,            /* Enables experimental support for emitting type metadata for decorators. */
      "resolveJsonModule": true,
      "forceConsistentCasingInFileNames": true
    }
  }
  
```

**Additional context**
I'm not actually using ESM in my app. This app remembers NodeJS v8 :)

**Versions**

| Dependency | Version |
| - | - |
| node | 16.17.0 |
| typescript | 4.6.4 |
| mikro-orm | 5.4.0 |
| your-driver | MySQL |

**Comment by jblyberg** [comment]
Not just 16.x. I'm running in to this with node 18.7.0. It happened after I upgraded to 5.4.0 from 5.3.1.

**Comment by milesje** [comment]
Same here after upgrading from 5.3.1 to 5.4.0....

**Comment by toonvanstrijp** [comment]
Same thing here using after upgrading to 5.4.0

**Comment by alex996** [comment]
v5.3.0 doesn't work either. v5.2.0 does work but it breaks in typescript v4.8.2 when using the PostgreSQL driver: `Type 'PostgreSqlDriver' does not satisfy the constraint 'IDatabaseDriver<Connection>'`.

**Comment by jblyberg** [comment]
@alex996 I think that is a separate issue. This is regarding ts-node improperly rejecting .ts files when parsing the config file from the cli. See @XanderEmu's example output above.

**Comment by alex996** [comment]
@jblyberg It's unrelated but I mentioned it because staying on v5.2.0 isn't viable either unless you don't upgrade TypeScript.

**Comment by jblyberg** [comment]
I was able to work around this issue by setting `NODE_OPTIONS="--loader ts-node/esm"` and wound up putting it in my script definition until this issue is sorted:

```
"orm:migrate:create": "NODE_OPTIONS=\"--loader ts-node/esm\" mikro-orm migration:create",
"orm:migrate:up": "NODE_OPTIONS=\"--loader ts-node/esm\" mikro-orm migration:up",
```

**Comment by B4nan** [comment]
Ouch, I thought this is ESM only issue, totally forgot to test the CLI. WIll fix it in a moment. 

Since v5.4 its possible to provide your own dynamic import implementation, so you can also do this explicitly (in CJS projects):

```ts
dynamicImportProvider: id => require(id)
```

(This is exactly how I am going to fix it, enforcing this when initializing the ORM from CLI context.)

**Comment by D10100111001** [comment]
I tried with both 5.3.1 and 5.4.0 and I keep getting this when I run the migrations command (`yarn mikro-orm migration:create --initial`):

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/shah/Documents/repos/UmmahConnect/packages/domain/src/migrations/config/db-config.ts
    at new NodeError (node:internal/errors:371:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:87:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:102:38)
    at defaultLoad (node:internal/modules/esm/load:21:14)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at async Promise.all (index 0) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}


Using commonjs and also tried using `dynamicImportProvider: (id) => require(id),`

**Comment by Chowarmaan** [comment]
I tried making the suggested change in the mikro-orm.config.ts file, in the options setting:

    const MikroOrmConfig: Options = {
	type: 'mysql',
        ...
	entities: [`${__dirname}/**/*.entity.js`],
	entitiesTs: [`${__dirname}/**/*.entity.ts`],
	namingStrategy: EntityCaseNamingStrategy,
	loadStrategy: LoadStrategy.JOINED,
	highlighter: new SqlHighlighter(),
	dynamicImportProvider: id => require(id),

and this did not fix my error attempting to run the migrations from the CLI, using 5.4.0.

**Comment by B4nan** [comment]
Looks like it was just about the debug command.

**Comment by SpencerKaiser** [comment]
@B4nan I just pulled the latest dev release and it's still throwing the same `Unknown file extension ".ts"` error... do we need to modify our `ormconfig` after using that release?

**Comment by B4nan** [comment]
It works fine for me with dev 13, can you create a repro?

https://stackblitz.com/edit/mikro-orm-repro-wcqjfb?file=package.json

**Comment by SpencerKaiser** [comment]
Lemme look into it more. If I can repro it, is a repo ok or do you want a repro on stackblitz or something? I haven't worked too much with them so I'm a bit of a noob over in those environments 😅

**Comment by B4nan** [comment]
Well, I dont mind a repo, but I kinda just proved it works in that stackblitz :] Or is it some specific command? I am trying `debug` and `schema:create -d` usually.

**Comment by SpencerKaiser** [comment]
And for more context, here's the script I use with local development:
`ts-node-dev --exit-child --watch .env.local --ignore-watch ../web/.next --files --rs --respawn src/index.ts`

The same issue occurs with `ts-node-dev`, which I guess shouldn't be surprising 😅

**Comment by B4nan** [comment]
Oh I see, the fix was only about CLI as the OP was about CLI. 

We can run the same ts-node detection logic as we have in the `init` method and do the same automatically to support such use case. 

But the workaround mentioned above will help with this too, just add `dynamicImportProvider: (id) => require(id),` to the ORM config.

**Comment by SpencerKaiser** [comment]
Gotcha. Want me to open a new issue for that fix?

**Comment by B4nan** [comment]
Actually we dont need to detect ts-node at all, it makes sense to move the fix so its executed when creating the config object, always based on the `type: module` in package.json.

**Comment by B4nan** [comment]
let me know if next dev version works without that

**Comment by SpencerKaiser** [comment]
@B4nan doesn't look like it did ☹️ [Repro](https://stackblitz.com/edit/mikro-orm-repro-byb5fq?file=package.json,index.ts)

**Comment by B4nan** [comment]
Its not published yet https://github.com/mikro-orm/mikro-orm/actions/runs/3017061503

**Comment by SpencerKaiser** [comment]
Hahah whoops... I saw you pushed today and just assumed. My bad! I'll check when it's up 😆

**Comment by SpencerKaiser** [comment]
@B4nan same result after pulling in `dev.16` 😔 I tried with and without `"type": "module"` in the `package.json`

**Comment by B4nan** [comment]
Lol, right, because I fixed it only for the path where you dont provide the options to `init`... :D I am glad I gave this a bit more time to settle instead of rushing with hot fix releases :]

**Comment by SpencerKaiser** [comment]
Well I appreciate you trying to fix it so quickly!!! So you get kudos in my book haha

**Comment by Chowarmaan** [comment]
This dev-16 build addressed my issue as well, which was with the command line, but thought I would confirm for you.

**Comment by B4nan** [comment]
Looks like I managed to break it in dev.17 again :D Let me try once again.

**Comment by B4nan** [comment]
All good, it was wrong repro with ESM project, where this still requires the some extra configuration (e.g. the ts-node/esm loader).

**Comment by wagnerflo** [comment]
Hey everyone! I'm quite inexperience in all things Java-/TypeScript, SvelteKit and Mikro-ORM. Currently trying to gain understanding I ran into this very issue (or a very similar one). Same error on Mikro-ORM 5.6.0. Here's a reproduction: [https://stackblitz.com/edit/node-cq9rax?file=package.json](https://stackblitz.com/edit/node-cq9rax?file=package.json).

Possibly I'm doing something wrong. Help and/or bugfix would be appreciated.

**Comment by B4nan** [comment]
You should be using `npx mikro-orm-esm debug` instead in ESM projects, and AFAIK it won't work in stackblitz, but I just tried and it works fine locally.

**Comment by wagnerflo** [comment]
> You should be using `npx mikro-orm-esm debug` instead in ESM projects, and AFAIK it won't work in stackblitz, but I just tried and it works fine locally.

Thanks for the pointer. I got it working that way.

You're also right about stackblitz: I tried to copy what works on my Linux system there and somehow the Mikro-ORM CLI, even it it is started as `mikro-orm-esm` will still look for `{src/,}mikro-orm.config.js` instead of `.ts` files. It even ignores `"mikro-orm"."configPaths"` from the `package.json`. Forcing ts-node with `"mikro-orm"."useTsNode" = true` also does nothing.

**Comment by B4nan** [comment]
> You're also right about stackblitz: I tried to copy what works on my Linux system there and somehow the Mikro-ORM CLI, even it it is started as mikro-orm-esm will still look for {src/,}mikro-orm.config.js instead of .ts files. It even ignores "mikro-orm"."configPaths" from the package.json. Forcing ts-node with "mikro-orm"."useTsNode" = true also does nothing.

That's probably because you did not install `ts-node` - TS files are ignored without it being installed. But with stackblitz things don't work even if you install it :] The TS file gets imported and fails to recognize the extension as in the OP.

**Comment by wagnerflo** [comment]
You're right! Thanks again for the help.

**Comment by toonvanstrijp** [comment]
> You should be using `npx mikro-orm-esm debug` instead in ESM projects, and AFAIK it won't work in stackblitz, but I just tried and it works fine locally.

This fixed it for me! 🎉

**Comment by root0x** [comment]
I'm having this issue with next js, does anyone have any ideas how to solve it?
