### ISSUE TITLE
Required virtual property in create

### ISSUE THREAD

**Issue by Nisgrak** [mikro-orm/mikro-orm#3446]
**Describe the bug**
When create a virtual property with `get` it is required in `em.create()` with the TS type

**To Reproduce**
1. Create a virtual property with get 
```ts
@Property({ persist: false })
get fullName2() {
  return `${this.name} ${this.id}`;
}
```
2. Try to create with em.create or repository.create method
3. Check the TS error

**Expected behavior**
Works like the getFullName property, I can't set a value for that virtual key

**Additional context**
Line 22
https://stackblitz.com/edit/mikro-orm-esm-repro-ta8zqp?file=basic.test.ts

**Comment by B4nan** [comment]
Use `OptionalProps` symbol.

https://mikro-orm.io/docs/property-validation#properties-with-default-value
