### ISSUE TITLE
EntityManager.flush() not working in jest testing

### ISSUE THREAD

**Issue by seunggu** [mikro-orm/mikro-orm#345]
**Describe the bug**
flush method is not working in jesst.
when i try on application. i correctly work.
and when i read data from database in jest, also working.

i try search code in mikro-orm project.
but i didn`t find out it...

**Stack trace**
```
 ● EmailAuthenticationRepository › .findEmailAuthenticationById() › should return EmailAuthentication by id

    TypeError: wrapped.isInitialized is not a function

      44 |       persistence.createdAt = new Date();
      45 |
    > 46 |       await orm.em.getRepository(EmailAuthenticationEntity).persistAndFlush(persistence);
         |                                                             ^
      47 |     });
      48 |
      49 |     it('should return EmailAuthentication by id', async () => {

      at UnitOfWork.findNewEntities (node_modules/mikro-orm/dist/unit-of-work/UnitOfWork.js:149:22)
      at UnitOfWork.computeChangeSets (node_modules/mikro-orm/dist/unit-of-work/UnitOfWork.js:119:18)
      at UnitOfWork.commit (node_modules/mikro-orm/dist/unit-of-work/UnitOfWork.js:77:14)
      at EntityManager.flush (node_modules/mikro-orm/dist/EntityManager.js:319:36)
      at EntityManager.persistAndFlush (node_modules/mikro-orm/dist/EntityManager.js:265:20)
      at EntityRepository.persistAndFlush (node_modules/mikro-orm/dist/entity/EntityRepository.js:12:23)
      at src/module/identityAccess/infra/persistence/repository/EmailAuthentication.repository.spec.ts:46:61
      at src/module/identityAccess/infra/persistence/repository/EmailAuthentication.repository.spec.ts:8:71
      at Object.<anonymous>.__awaiter (src/module/identityAccess/infra/persistence/repository/EmailAuthentication.repository.spec.ts:4:12)
      at Object.<anonymous> (src/module/identityAccess/infra/persistence/repository/EmailAuthentication.repository.spec.ts:38:27)


```

**To Reproduce**
1. just try flush method in jest

**Expected behavior**
flush method is working just like another case.

**Additional context**

**Versions**
3.21

| Dependency | Version |
| - | - |
| node | 12.14.0 |
| typescript | 3.7.5 |
| mikro-orm | 3.21 |
|mysql2 | 2.1.0 |

**Comment by B4nan** [comment]
> just try flush method in jest

Well, the ORM itself is tested with jest, so this is definitely not enough. Could you prepare reproduction repository so I can take a look? How do you initialize the ORM in your tests?

The error itself looks like you are not initializing the ORM properly (or the entity you are using is not discovered). `isInitialized` method is added to the entity prototype during discovery process.

**Comment by B4nan** [comment]
One wild guess - do you run your tests in parallel? If so, maybe you have shared ORM instance, that would definitely cause problems. Try running serially (`jest --runInBand`).

**Comment by seunggu** [comment]
Oh, thank you for response.
I prepare repository for this issue.
can you look this code?

https://github.com/seunggu/mikro-orm-jest

**Comment by seunggu** [comment]
I try what you told.
`jest --runInBand`

but it doesn`t solved.

**Comment by B4nan** [comment]
Right, so the error you see is there only if I compile first. Without the `dist` folder, I get the error I would expect: `ValidationError: No entities were discovered`.

The issue is that ts-node is not being properly detected when running the tests. You can get around that by passing `tsNode: true` to the ORM configuration when running your tests.

```typescript
    moduleRef = await Test.createTestingModule({
      imports: [MikroOrmModule.forRoot(MikroOrmConfig.getConfig(true))],
      providers: [EmailAuthenticationMapper, EmailAuthenticationRepository],
    }).compile();

export class MikroOrmConfig {
  static getConfig(tests = false): Options {
    console.log(process.cwd(), __dirname + '/../..');
    return {
      tsNode: tests,
      // ...
    };
  }
}
```

**Comment by seunggu** [comment]
wow, it works now.
thank for your kind answer!
