### ISSUE TITLE
docs: Clarification for MySQL/Mariadb

### ISSUE THREAD

**Issue by ajitzero** [mikro-orm/mikro-orm#3451]
I noticed in the installation guide that there are 2 separate packages for MySQL (`@mikro-orm/mysql`) & MariaDB (`@mikro-orm/mariadb`) but the inline comments for both have the same description for both. Are these currently interchangeable? Is the older one expected to be deprecated soon?

https://github.com/mikro-orm/mikro-orm/blob/ae81ca98a12d04081b9ca934b492d0c916dee30d/docs/versioned_docs/version-5.3/installation.md?plain=1#L14-L15

https://github.com/mikro-orm/mikro-orm/blob/ae81ca98a12d04081b9ca934b492d0c916dee30d/docs/versioned_docs/version-5.3/installation.md?plain=1#L24-L25

The inline comment should be updated accordingly.

**Comment by B4nan** [comment]
They are both compatible with mysql as well as mariadb. That's all what it means, its up to you what you want to use, they are compatible.
