### ISSUE TITLE
FilterQuery<T> resolves to unknown when T extends AnyEntity passed into it

### ISSUE THREAD

**Issue by QuestionAndAnswer** [mikro-orm/mikro-orm#3455]
I'm trying to complete this function

```typescript
export function withDeactivate<TEntity extends { id: string; isActive: boolean }>(
    entityType: EntityName<TEntity>,
) {
    return async (em: EntityManager, id: string) => {
        const entity = await em.findOne(entityType, id);

        assert(entity, `${id} not found`);

        entity.isActive = false;

        em.persist(entity);
    };
}
```

but I'm getting the error `Argument of type 'string' is not assignable to parameter of type 'FilterQuery<TEntity>'` for id in `findOne` call.

I took a look into `findOne` definition and `FilterQuery<T>`

```typescript
findOne<T extends AnyEntity<T>, P extends string = never>(entityName: EntityName<T>, where: FilterQuery<T>, options?: FindOneOptions<T, P>): Promise<Loaded<T, P> | null>;
```

`T` must extend `AnyEntity<T>`, (recursive generic) not sure why and how this exactly works here, but I've done this small test

and filter
```typescript
export declare type FilterQuery<T> = ObjectQuery<T> | NonNullable<ExpandScalar<Primary<T>>> | T | FilterQuery<T>[];
```
And it seems like `Primary<T>` in it is meant to resolve into string as acceptable type, is failing here.

```typescript
type T0 = { id: string; isActive: boolean };

type T1 = AnyEntity<T0>;
type T2 = Primary<T0>; // resolves to string
type T3 = Primary<T1>; // resolves to unknown
type T4 = FilterQuery<T0>; // resolves to string | RegExp | T0 | ObjectQuery<T0> | FilterQuery<T0>[]
type T5 = FilterQuery<T1>; // resolves to unkown
```

And seems like this is the root cause of my issue, and I'm not sure if it's me or it is a types definition bug.

**Expected behavior**
`findOne` call with id as a string passed would work in this generic call

**Versions**
| Dependency | Version |
| - | - |
| node | 16.17.0 |
| typescript | 4.7.3 |
| mikro-orm | 5.3.1 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
This is a TS limitation with generics, not really something we support, see this for more details: 

https://stackoverflow.com/questions/65490587/generics-doesnt-seem-to-fit-well-with-queryfilter/65523491#65523491

> type T5 = FilterQuery<T1>; // resolves to unkown

It does not resolve to unknown on my end, at least not with TS 4.8 and MikroORM 5.4.

<img width="877" alt="image" src="https://user-images.githubusercontent.com/615580/188332302-5dd1e11a-a6f8-4291-a7d6-b8517e47982d.png">
