### ISSUE TITLE
wrap() doesn't work for virtual entities

### ISSUE THREAD

**Issue by rcfox** [mikro-orm/mikro-orm#3493]
**Describe the bug**
`wrap()` is supposed to give access to some helper functions, like `toJSON()`, etc. However, when using a virtual entity, these functions are not available at run-time, even though they appear to be at compile-time.

**To Reproduce**
`entity/Test.ts`:
```
import { Entity, Property } from '@mikro-orm/core';

@Entity({
  expression: 'SELECT 1 as long_name, 2 as another_long_name'
})
export class Test {
  @Property({ serializedName: 'long_name' })
  longName!: number;

  @Property({ serializedName: 'another_long_name' })
  anotherLongName!: number

}
```

`test.ts`:

```
# ...
const t = await DI.orm.em.find(Test, {})
console.log(wrap(t).toJSON()) // TypeError: (0 , core_2.wrap)(...).toJSON is not a function
```

**Expected behavior**
`toJSON`, `toObject`, etc should be available on the wrapped entity at run-time.

**Additional context**
I'm mostly concerned with being able to undo the naming strategy at serialization. Is there perhaps a better way to do it?

For now, I'm working around the issue by defining my own `toJSON` on the virtual entity's class:

```
  toJSON() {
    const properties = DI.orm.getMetadata().get<Test>('Test').properties as Dictionary
    const result: {[key: string]: any} = {}
    for (let [key, value] of Object.entries(this)) {
      const keyToUse = properties[key].serializedName || key
      result[keyToUse] = value
    }
    return result
  }
```

**Versions**

| Dependency | Version |
| - | - |
| node | 18.9.0 |
| typescript | 4.8.2 |
| mikro-orm | 5.4.1 |

**Comment by B4nan** [comment]
Virtual entity is more like a POJO, there is no `WrappedEntity` instance for it, that is on purpose. I dont think serialization flags even work here, which would be indeed nice to have.

You could try using the `EntityTransformer` directly, it is the same as using `wrap().toJSON()` and similar:

```ts
const pojo = EntityTransformer.toObject(test);
```

**Comment by rcfox** [comment]
Unfortunately, `EntityTransformer.toObject` calls `helper()`, which also doesn't seem to work for this:

```
TypeError: Cannot read properties of undefined (reading '__serializationContext')
    at Function.toObject (/usr/src/app/node_modules/@mikroorm/core/entity/EntityTransformer.js:87:22)
```
