### ISSUE TITLE
Awesome Work!

### ISSUE THREAD

**Issue by haschu** [mikro-orm/mikro-orm#350]
This isn't an actual issue and can be closed - I just want to leave some props here:

This ORM is awesome! This is in fact the Node ORM I was looking for years.

Our company is considering to switch from TypeORM to MikroORM because the TypeORM development seems to be stuck and we are spending our time with workaround development.

Since we weren't satisfied with any ORM in the Node.js world, we even considered spending the time to implement our own.
Then I came across MikroORM and spent a couple of hours  investigating the code. And what I can see is really really great work, also in terms of the overall software architecture.

You did an amazing job!

Do you considering Patreon or Open Collective in the future? I'd love to support this project.

**Comment by B4nan** [comment]
Thanks a lot, happy to hear that! 

Regarding sponsoring, I am waiting for github sponsors to be available here in CZ, but if it won't come in few weeks (waiting for months already), I will probably go for open collective.

**Comment by haschu** [comment]
Great to hear. Fingers are crossed :)

**Comment by darkbasic** [comment]
@haschu we had a similar experience with Node.js and ORMs and we even started to dissuade people about using ORMs. I'm very glad I've stumbled upon this project, thanks @B4nan !

**Comment by filipjnc** [comment]
I can't believe I didn't find this earlier. After being disappointed with TypeORM, I kind of gave up on ORMs and started using knex on a higher level. And here you go again :)

Really nice work @B4nan, keep it going <3

**Comment by GitStorageOne** [comment]
> Then I came across MikroORM and spent a couple of hours investigating the code. And what I can see is really really great work, also in terms of the overall software architecture.
It's not enough. When you will dive in, I'm sure you will find disadvantages as well.  
What about pooling support? It should be important for performance, isn't it?  
I'm not protecting TypeORM here, but trying to make more informed decision.

**Comment by B4nan** [comment]
> What about pooling support? It should be important for performance, isn't it?

Pooling is supported (and enabled by default), as knex is now used as a query runner. It was one of the reasons why I used it. 

> Would be nice to see a feature matrix comparison.

Will be happy to help with a comparison, but as I am not typeorm user myself, I am not that familiar with all its features and internal mechanisms, so can't do it myself (also it would be really biased I think :] ). Sure there might be some things missing - I am open for feature requests, but honestly I don't want to end up in similar position as typeorm, where it feels like there are too much features to maintain.

Anyway, the biggest difference with typeorm is the unit of work. MikroORM is truly inspired by JPA/hibernate/doctrine, while typeorm is (in my eyes) more of a query builder. There is no in memory management of entities, there is no identity map (so you can have many instances of one entity in the same context).

Also from what I saw, a lot of things have to be done manually via query builder in typeorm, while MikroORM provides much more convenient way. One example being auto-joining (https://mikro-orm.io/docs/entity-manager#searching-by-referenced-entity-fields)

**Comment by GitStorageOne** [comment]
Well, It seems worth a try)  
IMO TypeORM trying to support every possible database driver, so, every new feature become more and more complicated to implement and maintain.

**Comment by wkrueger** [comment]
Currently investigating this orm, already got excellent first impressions from:
  - Good and beatiful docs/website
  - wtf he statically analyzes code with TS api, this is another level of black magic fuckery
  - Reuses knex. Any JS ORM implementator not doing this is not sane

**Comment by irissoftworks** [comment]
Yeah, I have a few projects running with typeorm, and before that was using Knex in Production for a long while, but there's things that put me off from typeorm [no point in going over them here]. 

Mikro ORM having first class uow is a big thing, but it's not just that. The good docs, the clean code base and the fact that it uses Knex is an excellent choice. This seems to be the case for pretty much everything in this project - The author consistently makes good choices - It's inspiring.

I am still not using Mikro ORM but would gladly support it. At the very least I'll be sure to give at a try on my next project to check it out in a real life scenario!

**Comment by B4nan** [comment]
Once again thank you all for the warm words. 

I've been finally approved for github sponsors, I also added paypal link for one time contributions.
