### ISSUE TITLE
Top level $not on a join criteria fails silently

### ISSUE THREAD

**Issue by lagnat** [mikro-orm/mikro-orm#3504]
**Describe the bug**
Trying to use $not in a join results in missing sql criteria for the not clause

**To Reproduce**
```
    qb.select('*')
      .leftJoin('a.books', 'b', {
        $not: {
            'b.foo': '1',
        },
      });
```
Results in 
```
select `a`.* from `author2` as `a` left join `book2` as `b` on `a`.`id` = `b`.`author_id`
```
The `$not` part is ignored.

**Expected behavior**
```
select `a`.* from `author2` as `a` left join `book2` as `b` on `a`.`id` = `b`.`author_id` and  not b.foo = 1;
```

**Additional context**
None

**Versions**

| Dependency | Version |
| - | - |
| node | 16.x |
| typescript | 4.7.4 |
| mikro-orm | 5.4.2 |
| your-driver | mysql |

**Comment by B4nan** [comment]
You could try this as a workaround:

```ts
    qb.select('*')
      .leftJoin('a.books', 'b', {
        'b.foo': {
            $ne: '1',
        },
      });
```

**Comment by lagnat** [comment]
The workaround is not an option for me as the join clause is auto-generated from input that I do not control.  Is it intended that top-level $not should work?  Researching Knex a little, it's not clear to me that Knex can do this.

**Comment by B4nan** [comment]
Hmm looks like this is not really supported by knex, you cant have a generic `not` condition in the on clause, so this will require quite a redo of how the joins are created. Basically removing the knex API in favour of `joinRaw()`.

**Comment by lagnat** [comment]
IMO it's a very odd thing for knex to omit.  Relevant issue: https://github.com/knex/knex/issues/4598

I ended up applying a recursive De Morgan's to the criteria and that's working fine so far.  For context, my criteria objects are machine generated so I don't have the possibility for human intervention here.

My code depends on long-hand criteria objects, meaning shortcuts like my example above are not handled, but in my case we only generate long-hand criteria so not an issue for us.  Pasting here in case anyone else needs it.

```
    public static demorganNot(where: any, invert = false): any {
        if (!where) return where;

        if (Array.isArray(where)) {
            const arr: Array<any> = [];
            for (const el of where) {
                arr.push(this.demorganNot(el, invert));
            }
            return arr;
        }

        if (typeof where !== 'object') return where;

        // A $not operator can only exist by itself.
        if (Object.keys(where).length == 1) {
            const v = where['$not'];
            if (v) {
                return this.demorganNot(v, !invert);
            }
        }

        // Recursive descent through the rest of the criteria
        const obj = {};

        for (const [k, v] of Object.entries(where)) {
            if (k.startsWith('$') && invert) {
                const newOp = this.inverseOp[k];
                if (!newOp) throw new Error('No such op: ' + k);
                obj[newOp] = this.demorganNot(v, invert);
                continue;
            }

            obj[k] = this.demorganNot(v, invert);
        }

        return obj;
    }

    private static inverseOp = {
        $and: '$or',
        $or: '$and',
        $in: '$nin',
        $nin: '$in',
        $between: '$notBetween',
        $notBetween: '$between',
        $eq: '$ne',
        $ne: '$eq',
        $gte: '$lt',
        $lt: '$gte',
        $gt: '$lte',
        $lte: '$gt',
    };
```

**Comment by B4nan** [comment]
I will try to refactor the QB to be less dependent on knex here, I want to gradually move away from it (will keep it as a query runner, but the queries can be generated explicitly by the ORM and ran via `knex.raw()` to have absolute control). I am sure I will end up with simpler code, as mapping the ORM queries to the knex API was quite tedious - the API is very user oriented, so quite terrible for our use case).

**Comment by lagnat** [comment]
I'll admit I was thinking the same thing, so that's very encouraging news.

**Comment by B4nan** [comment]
Damn this was challenging, but I finally have the tests green.
