### ISSUE TITLE
Partial Entities Bug

### ISSUE THREAD

**Issue by kyro95** [mikro-orm/mikro-orm#3507]
**Describe the bug**
When you run multiples partial entities it is gonna sum all the fields you asked previously.
I'll make myself clear, 
You run a query that selects **only** your nickname
It will return you the entity that contains only your nickname
Then run another query that has the same entity selecting another field which is different from the previous selected which is nickname, let's suppose that is the last login timestamp which we are gonna call lastLogin
This time the query won't return only lastLogin but the nickname and lastLogin and so on

**To Reproduce**
1. Create a simple mikro orm entity 
2. Run a query that selects a random field
3. Run another query that selects another random field

**Expected behavior**
Fetch the partial entity with the fields that i passed to the parameters

**Additional context**
```typescript
console.log(await this.orm.em.findOne<CharacterEntity>(CharacterEntity, { name: "kyro" }, { fields: ["discordId"]}));
console.log(await this.orm.em.findOne<CharacterEntity>(CharacterEntity, { name: "kyro"}, { fields: ["name"]}));
```

```console
CharacterEntity {
  _id: ObjectId('631a98f674688863ba4e8926'),
  discordId: '312689099943444480',
  name: undefined,
  level: undefined,
  money: undefined,
  lastLogin: undefined,
  registrationDate: undefined,
  inventory: undefined,
  appearance: undefined
}
CharacterEntity {
  _id: ObjectId('631a98f674688863ba4e8926'),
  discordId: '312689099943444480',
  name: 'kyro',
  level: undefined,
  money: undefined,
  lastLogin: undefined,
  registrationDate: undefined,
  inventory: undefined,
  appearance: undefined
}
```

**Versions**

| Dependency | Version |
| node | 18.6.0 |
| typescript | 4.7.2 |
| mikro-orm | 5.3.1 |
| @mikro-orm/mongodb | 5.3.1 |

**Comment by B4nan** [comment]
This is a feature, you can never get two different entities from this, as there is an identity map, so only a single instance of an entity can exist.

You need to fork to have separate contexts if you want separate entities:

```ts
console.log(await this.orm.em.fork().findOne<CharacterEntity>(CharacterEntity, { name: "kyro" }, { fields: ["discordId"]}));
console.log(await this.orm.em.fork().findOne<CharacterEntity>(CharacterEntity, { name: "kyro"}, { fields: ["name"]}));
```

Or use `disableIdentityMap` which does this for you behind the scenes (literally forks the em and returns results from it):

```ts
console.log(await this.orm.em.findOne<CharacterEntity>(CharacterEntity, { name: "kyro" }, { fields: ["discordId"], disableIdentityMap: true }));
console.log(await this.orm.em.findOne<CharacterEntity>(CharacterEntity, { name: "kyro"}, { fields: ["name"], disableIdentityMap: true }));
```

**Comment by kyro95** [comment]
So **all** the entities are stored in the memory?

**Comment by B4nan** [comment]
Yes, every entity you load via EM is stored in identity map.

https://mikro-orm.io/docs/identity-map
