### ISSUE TITLE
generate-entities - postgresql type bigint is referred as string in typescript

### ISSUE THREAD

**Issue by aviz** [mikro-orm/mikro-orm#3514]
**Describe the bug**
bigint type in postresql is string instead of number.
in addition, it is columnType int8, while it should be int64.
the culumnType int8 is not a big deal, because it's a mistake in all places bigint is translated to int8 .
however it would be nice to correct it. bigint is 8 bytes, which are 64 bits. when you refer to intX type it's by bits (see https://www.gnu.org/software/libc/manual/html_node/Integers.html), the same mistake is done along any integer like inr4 and such.

**To Reproduce**
1. create a table with bigint field.
2. mikro-orm generate-entities
3. in the entity,  bigint will have type of string instead on number .

> @PrimaryKey({ columnType: 'int8' })
> id!: string;

**Expected behavior**
bigint should be of type number in typescript.

**Comment by B4nan** [comment]
Works as intended, bigings are mapped to strings so you dont loose precision.

Use custom mapped type if you want to convert it to number on runtime, but keep in mind JS numbers are floats, you can loose precision this way.
