### ISSUE TITLE
Insert query is not generated correctly when using Embeddable Entity

### ISSUE THREAD

**Issue by denis-maiorov-brightsec** [mikro-orm/mikro-orm#3519]
**Describe the bug**
Insert query is not generated correctly when using Embeddable Entity in "inlining mode" (`@Embedded({ entity: () => Entity, object: false })`)

**Stack trace**
```
SyntaxErrorException: insert into "test" ("config_tests") values ('1', '2', '3') returning "id" - INSERT has more expressions than target columns
```

**To Reproduce**:
```typescript
@Entity({ tableName: 'test' })
export class TestEntity {
  @Embedded({ entity: () => ConfigEntity })
  public config: ConfigEntity;
}
```
```typescript
@Embeddable()
export class ConfigEntity {
  @Property({
    columnType: 'jsonb',
    type: JsonType,
    nullable: true
  })
  public tests?: string[];
}
```

```typescript
public async create() {
  const entity = this.em.create(TestEntity, {config: { tests: ['1', '2', '3'] }});
  this.em.persist(entity);
  await this.em.flush();
}
```

**Expected behavior**
Should generate valid SQL query, in this case
```sql
insert into "test" ("config_tests") values ('["1", "2", "3"]') returning "id"
```

**Additional context**
Version 5.4.1 does not have the bug
There's no problem when using Embeddable with `json` column

**Versions**

| Dependency | Version |
| - | - |
| node | 14.19.2 |
| typescript | 4.6.2 |
| mikro-orm | 5.4.2 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
I will need complete reproduction for this.

**Comment by denis-maiorov-brightsec** [comment]
@B4nan here's a reproduction https://github.com/denis-maiorov-brightsec/embeddable-bug-mikroorm
