### ISSUE TITLE
Unexpected behavior of getFormattedQuery()

### ISSUE THREAD

**Issue by montycb** [mikro-orm/mikro-orm#3534]
Calling getFormattedQuery() after a join with pagination, causes subsequent QueryBuilder calls to insert SQL Statements in the wrong location.

I have included a minimal Example. Both qb and qb2 should build the same query, hover the getFormattedQuery() call modifies the result.

The DISABLE_PAGINATE flag can be used as a workaround, however I expect a getter function to not modify the underlying object. 

**Testcase**
```
import { Collection, Entity, ManyToOne, MikroORM, OneToMany, PrimaryKey } from "@mikro-orm/core";
import { SqliteDriver } from "@mikro-orm/sqlite";

@Entity()
export class A {
  @PrimaryKey()
  id!: string;

  @OneToMany({ entity: 'B', mappedBy: 'ref_a'})
  ref_b = new Collection<B>(this);
}

@Entity()
export class B {
  @PrimaryKey()
  id!: string;

  @ManyToOne(() => A)
  ref_a!: A;
}

test('sqlite', async () => {
  const orm: MikroORM<SqliteDriver> = await MikroORM.init({
    entities: [A, B],
    dbName: ':memory:',
    type: 'sqlite',
  });

  const qb = orm.em.createQueryBuilder(A, 'alias_a')
    .leftJoin('ref_b', 'alias_b')
    .limit(5)

  qb.getFormattedQuery() // finalizes query => paginate wrap
  qb.andWhere({ id: 5 })
  const a = qb.getFormattedQuery()

  const qb2 = orm.em.createQueryBuilder(A, 'alias_a')
    .leftJoin('ref_b', 'alias_b')
    .limit(5)

  qb2.andWhere({ id: 5 })
  const b = qb2.getFormattedQuery()
  expect(a).toBe(b);

  await orm.close(true);
})
```

**Comment by B4nan** [comment]
Fixing this might require quite deep refactoring of how the QB works, as we would need to cache the calls and evaluate everything later, right now there is no easy way to reset things to "before finalization" state. 

But in the long run it would make sense for sure, cloning would be much simpler too.

**Comment by montycb** [comment]
Maybe a warning could be added to the documentation until this gets fixed?

**Comment by B4nan** [comment]
We could probably throw if you try to modify a finalized QB, adding notes to docs wont help much, it would be still quite hidden.

**Comment by montycb** [comment]
I think that would be a good Idea, you really shouldn't be able to modify a finalized query.
