### ISSUE TITLE
Property metadata and entity metadata in custom types

### ISSUE THREAD

**Issue by lewispham** [mikro-orm/mikro-orm#3538]
**Is your feature request related to a problem? Please describe.**
I was having hard time with logging property name and entity name of a failed validation from custom types. Also, having the predefined flags (`unsigned`, `autoincrement`, `nullable`, etc ) for constructing new types is quite useful.

**Describe the solution you'd like**
mikro-orm supports having property metadata and entity metadata passed as arguments in all custom-types methods https://mikro-orm.io/docs/custom-types

```typescript
class AutoIncrementType extends IntegerType {
    private definition: EntityProperty;
    convertToDatabaseValue(value: number | null | undefined, propertyMetadata: PropertyMetadata, entityMetadata: EntityMetadata) {
        // wrong column name is passed
        return isPositiveInteger(value, propertyMetadata.name);
    }
    convertToJSValue(value: number | null | undefined, propertyMetadata: PropertyMetadata, entityMetadata: EntityMetadata) {
        // wrong column name is passed
        return isPositiveInteger(value, propertyMetadata.name);
    }
    getColumnType(prop: EntityProperty): string {
        prop.unsigned = true;
        prop.autoincrement = true;
        this.definition = prop;
        return prop.type;
    }
}


```

**Describe alternatives you've considered**
I tried to assign the metadata retrieved in method `getColumnType` to a private variable of the type class. But it looks like custom types are not consumed as instances but classes. As a result, I'm having wrong metadata when the validation methods are called.

```typescript
class AutoIncrementType extends IntegerType {
    private definition: EntityProperty;
    convertToDatabaseValue(value: number | null | undefined) {
        // wrong column name is passed
        return isPositiveInteger(value, this.definition.name);
    }
    convertToJSValue(value: number | null | undefined) {
        // wrong column name is passed
        return isPositiveInteger(value, this.definition.name);
    }
    getColumnType(prop: EntityProperty): string {
        prop.unsigned = true;
        prop.autoincrement = true;
        this.definition = prop;
        return prop.type;
    }
}


```

**Additional context**
Add any other context about the feature request here.

**Comment by B4nan** [comment]
Mapped types are singletons by default, so the workaround you tried would work only if you create new instances, e.g. `@Property({ type: new AutoIncrementType() })`.

I dont mind exposing the meta and prop as you suggested, maybe it would be better of via options object instead of separate params.

**Comment by lewispham** [comment]
@B4nan Thanks for the hint. I think singletons will likely cause multiple issues in the future. You should treat types as factory and create an instance for each property by default. With this approach, you just simply need to expose class variables or methods for adding new features. If that is the case, retrieving metadata could be achieved like the below. It doesn't require adding extra arguments for every related method.

```typescript
class AutoIncrementType extends IntegerType {
    convertToDatabaseValue(value: number | null | undefined) {
        const propertyMetadata = this.getPropertyMetadata(); // or even this.options.propertyMetadata
        const entityMetadata = this.getEntityMetadata();
        return isPositiveInteger(value, propertyMetadata.name);
    }
}
```

**Comment by B4nan** [comment]
This is a perfromance optimization, its designed based on how doctrine works - I dont plan to change this, if you want instances, you can have them, the way I showed above.

FYI this works the same since v3, so for years, I dont think it will "likely cause multiple issues in future".

**Comment by lewispham** [comment]
Thanks for your explanation. But I think that the performance different between the functional approach and OOP approach should be extremely small. The OOP approach should mostly slower on initialization but execution. I've made this small benchmark and it looks like V8 can even make it becomes a zero difference if there is enough ops. It's obviously no real world benchmark so I would really appreciate if you can share some benchmarks on the actual mikro-orm code base. I'm just not sure whether it's worth sacrificing code quality for.
https://jsbench.me/xql8fzm6rz/1
https://jsben.ch/6IgHJ

**Comment by B4nan** [comment]
Thats a bit too simplistic benchmark, but you are correct it clearly does not make much difference - tried to switch to new instances in my internal benchmark and it seems to be quite similar, even if I create new type instances every time the type is used.

So your proposal would be to have type instance per property usage (instead of type usage), right? Unlike the other way around, this sounds as a safe change to me, so if there is no real perf penalty, I dont mind changing it. I took the core implementation from doctrine together with the perf optimization but it might be irrelevant in JS (as well as in current PHP, I think the code was there for ages :]).

**Comment by lewispham** [comment]
>So your proposal would be to have type instance per property usage (instead of type usage), right? 

Yes, that's correct.

> or maybe not, we can just disable the cache in Type.getType and things could just work, as we call it only when there is no mapped type set already

Yes, that's true. But supporting my proposed feature requires refactoring the code a little bit more.

I've just double checked and it looks like the benchmark is irrelevant. Mikro-orm doesn't functionally call type-conversion methods directly. Instead, those methods are called with OOP style and wrapped under another function. In short, the change should have completely no impact on performance.
https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/hydration/ObjectHydrator.ts

```typescript
context.set(`convertToJSValue_${convertorKey}`, (val: any) => prop.customType.convertToJSValue(val, this.platform));
context.set(`convertToDatabaseValue_${convertorKey}`, (val: any) => prop.customType.convertToDatabaseValue(val, this.platform));
```

Even if the code is written this way, the performance difference should still be extremely negligible.
```typescript
context.set(`convertToJSValue_${convertorKey}`, prop.customType.convertToJSValue);
context.set(`convertToDatabaseValue_${convertorKey}`, prop.customType.convertToDatabaseValue);
```
https://jsbench.me/snl8h4z9m7/1

I think it's safe to say that micro-optimization is often a waste of time with modern compliers. In my experience, performance issues mostly only come from these 2 types of operations, iterations (loops, recursions) and async operations.

**Comment by B4nan** [comment]
I went with a different approach, the `type.meta` and `type.prop` are set during discovery on the type instance and the discovery no longer uses `Type.getType` so it creates new instances of types. The `Type.getType` method is still used internally for schema related parts.
