### ISSUE TITLE
Add config option for snapshot name(s)

### ISSUE THREAD

**Issue by Tlepel** [mikro-orm/mikro-orm#3562]
**Is your feature request related to a problem? Please describe.**
When we migrated to MikroORM v5, we added the database snapshot to our versioning. However, when running a migration from my local environment, a different snapshot file was created instead of changing the existing snapshot. I found out that the snapshot name is generated based on the `dbName` config variable, and this was the root of the problem. Since our local environments have different database names, the snapshots will keep being generated with different names.

**Describe the solution you'd like**
I'd like to have a configuration option to change the default name of the snapshot that is created.

**Describe alternatives you've considered**
An alternative would be to change the database names in our local configs. However, that's not a very suitable option because some team members already have databases with that name and a different name wouldn't be suitable. That's why our workflow allows for custom database naming, but the new snapshot doesn't allow for our usual workflow.

**Comment by B4nan** [comment]
Makes sense, PR welcome
