### ISSUE TITLE
Bug: valid query can break IdentityMap, leads to wrong changeSet generation, and update despite no mutation

### ISSUE THREAD

**Issue by rvion** [mikro-orm/mikro-orm#3566]
**Describe the bug**

❌ Some valid select queries break EntityMap and changeSet computation under specific `where` expression generating `left joins` with `multiples pairs`.
❌ after such query, `em.flush()` will generate sql updates despite having just a single `find()` call, with no mutation at all

here is a minimal piece of code that exhibits the problem, as long as an explanation of what happens:

👉 if I'm right, there might be two separates fixes to do here, highlighted in the 'expected' section below

----------

🟢 THIS WORKS (flush does nothing)

```ts
// dumb minial example
await CustomerRepo.find(
   { id: '00001c71-e0db-4c5e-85a2-97909466a80e', },
   { limit: 1, filters: false },
)
await db.em.flush()
```

🔴 THIS DOES NOT (flush **does** something, changesets are broken, em invariants are violated)

```ts
await CustomerRepo.find(
   {
      id: '00001c71-e0db-4c5e-85a2-97909466a80e',
      AAAA: { created_at: { $lt: '2023-01-01' } }, // some ManyToOne relation
   },
   { limit: 1, filters: false },
)
await db.em.flush()
// after computeChangeSets()
// we get a changeset with
//   - payload["Assignated_to"] = undefined ❌ WRONG HERE
//   - originalEntity["Assignated_to"] = null
// ❌ TRIGGERS AN UPDATE
// => [query] update "customer" set "assignated_to" = NULL, "modified_at" = '2022-10-05T13:11:27.377Z' where "id" = '00001c71-e0db-4c5e-85a2-97909466a80e' [took 8 ms]
```

with `Assignated_to` being a wrapped reference to some other table that has nothing to do with `AAAA`

# WHY ?

because the SQL generated looks like this

```pgsql
SELECT
	"c0".*
FROM
	"customer" AS "c0"
	LEFT JOIN "AAAA" AS "c1" ON "c0"."id" = "c1"."customerID"
WHERE
	"c0"."id" IN (
		SELECT
			"c0"."id"
		FROM (
			SELECT
				"c0"."id"
			FROM
				"customer" AS "c0"
			LEFT JOIN "AAAA" AS "c1" ON "c0"."id" = "c1"."customerID"
		WHERE
			"c1"."created_at" < '2023-01-01'
			AND "c0"."id" = '00001c71-e0db-4c5e-85a2-97909466a80e'
		GROUP BY
			"c0"."id"
		LIMIT 1) AS "c0")
```

that evaluates to 

```pgsql
SELECT
	"c0".*
FROM
	"customer" AS "c0"
	LEFT JOIN "AAAA" AS "c1" ON "c0"."id" = "c1"."customerID"
WHERE
	"c0"."id" IN ('00001c71-e0db-4c5e-85a2-97909466a80e')
```

## that returns twice the same item

![image](https://user-images.githubusercontent.com/2150990/194074068-fbdcf81b-5fcf-42df-85de-15b932e00f03.png)

# ❌ and MikroORM is confused about the two entities returned by the SQL.

(📝  the genereated SQL is probably a bit invalid too)

--------------

side experimental note: 

🔶 `disableIdentityMap: true ` indeed hides the problem

```ts
await CustomerRepo.find(
   {
      id: '00001c71-e0db-4c5e-85a2-97909466a80e',
      AAAA: { created_at: { $lt: '2023-01-01' } },
   },
   { limit: 1, filters: false disableIdentityMap: true },
)
```

# **Expected behavior**

From my understanding:

- The IdentityMap abstraction should not break when `find` returns twice the same row (to be safe)
- the generated SQL should be changed so this query does not return twice the same row
    - missing a `distinct on <primary key>` ?

**Versions**

| Dependency | Version |
| - | - |
| node | v16.14.2 |
| typescript | Version 4.8.3 |
| mikro-orm | 5.4.2 |
| your-driver | Postgres |

PS: thanks for this awesome ORM !

**Comment by B4nan** [comment]
Did I miss something or you didnt provided any reproduction, not even entity definition? 👀 

There is no static API as in your code snippets, how does that `CustomerRepo.find` work? Or is that just pseudocode? How do you handle contexts? I need to see a complete repro for this.

> The IdentityMap abstraction should not break when find returns twice the same row (to be safe)

No idea what you mean by that. It is safe to call `em.find` as many times as you want (although it does not make much sense to me, not sure what safety you refer to here). 

> the generated SQL should be changed so this query does not return twice the same row missing a distinct on <primary key> ?

`distinct on` is a postgres feature, we need a universal solution for this, but I failed to understand what your problem is in the first place. That query is correct, it should return multiple rows, those are not duplicates - you join a to-many relation, so you get a cartesian product of the two tables as a result. The subquery solution is there because you added `limit` clause, and that cant be applied to a cartesian product - you would loose the to-many relation values that way.

Please provide minimal but complete reproduction, without that I can't help much.

**Comment by rvion** [comment]
@B4nan 

Thanks for your quick answer !
sorry if I wan't clear but I maintain my report.

I forked your stackblitz and made a minimal repro that showcase the problem.
you can find the repro here: https://stackblitz.com/edit/mikro-orm-repro-tszgwe?file=test.ts

logging is enabled so you can see the sql generated.

This bug is quite tricky because it involves references, left joins, and how many rows are returned by the left join.

@B4nan I'm at your disposal for more informations

you can see how calling `find` is generating 

```sql
    [query] select `b0`.* from `books` as `b0` left join `reviews` as `r1` on `b0`.`id` = `r1`.`book_id` where `b0`.`id` in (select `b0`.`id` from (select `b0`.`id` from `books` as `b0` left join `reviews` as `r1` on `b0`.`id` = `r1`.`book_id` where `b0`.`id` = 1 and `r1`.`id` < 100 group by `b0`.`id` limit 1) as `b0`) [took 0 ms]
```
<details>
<summary>formatted version</summary>

```sql
SELECT
	`b0`.*
FROM
	`books` AS `b0`
	LEFT JOIN `reviews` AS `r1` ON `b0`.`id` = `r1`.`book_id`
WHERE
	`b0`.`id` IN (
		SELECT
			`b0`.`id`
		FROM (
			SELECT
				`b0`.`id`
			FROM
				`books` AS `b0`
			LEFT JOIN `reviews` AS `r1` ON `b0`.`id` = `r1`.`book_id`
		WHERE
			`b0`.`id` = 1
			AND `r1`.`id` < 100
		GROUP BY
			`b0`.`id`
		LIMIT 1) AS `b0`

```

</details>


<details>
<summary>Full code here</summary>

```ts
import { SqliteDriver } from '@mikro-orm/sqlite';
import {
  MikroORM,
  IdentifiedReference,
  Collection,
  EntitySchema,
  EntityCaseNamingStrategy,
} from '@mikro-orm/core';

// 1. entity definitions
// ------------------------------------------------
export interface IReview {
  id: number;
  Book: IdentifiedReference<IBook>;
}
// prettier-ignore
export const Review = new EntitySchema<IReview, any>({
  name: 'Review',
  tableName: 'reviews',
  properties: {
     id: { type: 'IntegerType', primary: true },
     Book: {reference: 'm:1', type: 'Book', joinColumn: 'book_id', wrappedReference: true, nullable: false},
  },
});

// ------------------------------------------------
export interface IBook {
  id: number;
  Reviews: Collection<IReview>;
  Publisher?: IdentifiedReference<IPublisher>;
}
// prettier-ignore
export const Book = new EntitySchema<IBook, any>({
  name: 'Book',
  tableName: 'books',
  properties: {
    id: {type: 'IntegerType', primary: true },
    Reviews: { reference: '1:m', entity: () => Review, mappedBy: (x:IReview) => x.Book, },
    Publisher: {reference: 'm:1', type: 'Publisher', joinColumn: 'publisher_id', wrappedReference: true, nullable: true},
  },
});

// ------------------------------------------------
export interface IPublisher {
  id: number;
  Books: Collection<IBook>;
}
// prettier-ignore
export const Publisher = new EntitySchema<IPublisher, any>({
  name: 'Publisher',
  tableName: 'publishers',
  properties: {
    id: { type: 'IntegerType', primary: true },
    Books: { reference: '1:m', entity: () => Book, mappedBy: (x: IBook) => x.Publisher }, 
  },
});

let orm: MikroORM<SqliteDriver>;

beforeAll(async () => {
  orm = await MikroORM.init({
    type: 'sqlite',
    dbName: ':memory:',
    entities: [Book, Publisher, Review],
    namingStrategy: EntityCaseNamingStrategy,
    debug: ['query', 'query-params'],
  });
  const connection = orm.em.getConnection();
  for (const sql of [
    `drop table if exists reviews`,
    `drop table if exists books`,
    `drop table if exists publishers`,
    `CREATE TABLE publishers ( id integer primary key );`,
    `CREATE TABLE books ( id integer primary key, publisher_id integer references publishers(id) );`,
    `CREATE TABLE reviews ( id integer primary key, book_id integer not null references books(id) );`,
    // create one book and two reviews
    `insert into books (id) values (1)`,
    `insert into reviews (id, book_id) values (1, 1)`,
    `insert into reviews (id, book_id) values (2, 1)`,
  ])
    await connection.execute(sql);
});

afterAll(async () => {
  await orm.close();
});

const step2_SHOWCASE_OK = async (opts: { FORCE_LEFT_JOIN: boolean }) => {
  const em = orm.em.fork();
  const b1 = await em.find(
    Book,
    opts.FORCE_LEFT_JOIN //
      ? { id: 1, Reviews: { id: { $lt: 100 } } }
      : { id: 1 },
    { limit: 1 }
  );

  expect(b1[0].id).toBe(1);
  em.getUnitOfWork().computeChangeSets();
  const changeSet = em.getUnitOfWork().getChangeSets();
  if (changeSet.length > 0) {
    const c = changeSet[0];
    console.log('[🔎]', c.type, c.payload, c.originalEntity);
  }
  expect(changeSet.length).toBe(0); // 🔴 BUG HERE
};

test('no left join', () => step2_SHOWCASE_OK({ FORCE_LEFT_JOIN: false }));
test('with left join', () => step2_SHOWCASE_OK({ FORCE_LEFT_JOIN: true }));

```
</details>

**Comment by rvion** [comment]
@B4nan the repro uses 3 entities(`Review`, `Book`, `Publisher`). 

👉 `Publisher` appears unused in the demo, but that's precisely the nullable `book(id:1).publisher` Identified reference that exhibits the IdentityMap bug.

**Comment by B4nan** [comment]
Ok, got it reproduced at my end. Next time I would appreciate more defaults in the repro - it should be minimal, and that is the first step I need to do, to remove all the custom queries and field name overrides. 

FYI you got the `type` options wrong, `IntegerType` does not mean anything there (as a string). You would have to pass the actual class there, not its name. Or just do `integer` or similar, even `number` will work for the PK.

**Comment by rvion** [comment]
@B4nan Thanks a lot !

>Next time I would appreciate more defaults in the repro - it should be minimal, and that is the first step I need to do, to remove all the custom queries and field name overrides.

please, can you share the cleaned repro ? 🙏 
I tried to mimmic the way entities are defined in our project, where most of this comes from codegen
but I'd love to see an exemple of what you were expecting; 

I have more confirmed bugs on my end to report


> 
Ok, got it reproduced at my end. Next time I would appreciate more defaults in the repro - it should be minimal, and that is the first step I need to do, to remove all the custom queries and field name overrides.

> FYI you got the type options wrong, IntegerType does not mean anything there (as a string). You would have to pass the actual class there, not its name. Or just do integer or similar, even number will work for the PK.

Aaarg... this was not done really by mistake, but as the best solution I found  to accomodate very specific needs we have (schemas are shared on the frontend, where an in-memory custom runtime of MikroDB is running; we'll get to publish that once it's finished). I had problems with date being the only type whose string alias would still be understood as datetime and lead to some other changeset issues due to comparing string (date without time representation) with dates (datetime representation)
