### ISSUE TITLE
Foreign key value is null

### ISSUE THREAD

**Issue by Hevax** [mikro-orm/mikro-orm#358]
Hi! 
I have a problem: 
When I create ManyToOne relationship by @ManyToOne decotator, I want to select foreign key value. 

But on field select result is null. 
How can i get a foreign key value? 
I`m tryng to use something like this:  

@Field(() => User)
@ManyToOne(() => User, { nullable: true })
user?: User;

@Field()
@Property({ hidden: false, fieldName: "user_id", unsigned: true })
userId: number; // result is NULL but entity exist (in db FK has value) and other fields has values

Thanks for help!

**Comment by B4nan** [comment]
You should not define the other property (`userId`), work with the `user` instead. Just read `ent.user.id`, it will be there even if you do not populate the relation.

**Comment by Hevax** [comment]
This behavior by design? Okey, thaks for a good orm =)

**Comment by B4nan** [comment]
Yes, this is by design.

**Comment by mrsimb** [comment]
> You should not define the other property (`userId`), work with the `user` instead. Just read `ent.user.id`, it will be there even if you do not populate the relation.

But what if i want to include a foreign key too?

**Comment by B4nan** [comment]
Every database column in the entity is mapped to one property. There is no need for the other column, it just adds clutter, also brings inconsistency (you would the have multiple places where you could define the column name, type, length, etc - which one should work then?).

If you do not like that behaviour, it should be possible to implement what you want via custom hydrator.

**Comment by mrsimb** [comment]
> Maybe show me the use case so I can advice better.

Primarily a backwards compatability with output from our previous orm.
There are many places in our app, which use foreign key directly.

**Comment by B4nan** [comment]
If it is only about being able to read values from existing entities, you could use `@OnInit` hook to fill that property. 

But you should define it as `persist: false` so it is ignored in the schema generator.

Although, if you have consistent naming (`prop` and `propId`), you could use simple find/replace to change `propId` to `prop.id`, right? 

Or as I mentioned, you can implement custom hydrator. I can help with that, but not right now.

https://github.com/mikro-orm/mikro-orm/blob/master/lib/hydration/ObjectHydrator.ts 
https://mikro-orm.io/docs/configuration/#custom-hydrator

**Comment by B4nan** [comment]
Actually there is quite easy way to achieve this, not sure why it did not pop up on my mind before. You can define the `userId` property as getter that will read the value from `user.id`:

```typescript
@ManyToOne(() => User, { nullable: true })
user?: User;

@Property({ persist: false })
get userId(): number {
  return this.user.id;
}
```

This is called virtual property in MikroORM: https://mikro-orm.io/docs/defining-entities#virtual-properties

If you want to be able to set to that property, it is a bit more tricky, as you need to set instance of the target entity to the `user` variable. It can be done via internal entity manager reference if the parent entity is loaded from database (and therefore managed). 

```typescript
@ManyToOne(() => User, { nullable: true })
user?: User;

@Property({ persist: false })
get userId(): number {
  return this.user.id;
}

set userId(value: number): void {
  this.user = wrap(this).__em!.getReference(User, value); // TODO __em can be undefined
}
```

**Comment by mrsimb** [comment]
Thanks for detailed answers, really appreciate that!
