### ISSUE TITLE
IdentifiedReference to same object are not equal

### ISSUE THREAD

**Issue by gggdomi** [mikro-orm/mikro-orm#3582]
(first: thanks a lot, this lib is amazing 😊)

**Describe the bug**

According to the [doc](https://mikro-orm.io/docs/entity-references#what-is-identifiedreference:~:text=This%20reference%20is%20stored%20in%20identity%20map%20so%20you%20will%20get%20the%20same%20object%20reference%20when%20fetching%20the%20same%20document%20from%20database.)

> Every single entity relation is mapped to an entity reference. Reference is an entity that has only its identifier. **This reference is stored in identity map so you will get the same object reference when fetching the same document from database.**

I may have misread, but I thought that two rows (ex: items) pointing to the same foreign row (ex: user) would have `item1.user === item2.user` (identified reference comparison)

**To Reproduce**

Minimal full repro : https://stackblitz.com/edit/mikro-orm-repro-c3yqhx?file=test.ts

Summary:
```ts
  // 2 items, 1 user. Both items have an identified reference pointing to the same user
  expect(i1.user.id === i2.user.id).toBe(true); // 🟢 ids are equals
  expect(i1.user.getEntity() === i2.user.getEntity()).toBe(true); // 🟢 entities are equal
  expect(i1.user === i2.user).toBe(true); // ❌ identified references are not
```

**Expected behavior**

```ts
  expect(i1.user === i2.user).toBe(true); // 🟢 I expected identified references to also be equal
  // if I misread the doc and the inequality is known behavior... intuitively it still feel like they should be equal ?
```

**Versions**

| Dependency | Version |
| - | - |
| node | v16.14.2 |
| typescript | 4.8.3 |
| mikro-orm | 5.4.2 |
| your-driver | Postgres (repro in SQLite) |

**Comment by B4nan** [comment]
Yes, they are not, they cant be. Identity is only on entities inside them.

**Comment by rvion** [comment]
> they cant be

@B4nan would you mind to elaborate ?

I was thinking they could/should be 🤔 

if we submit a patch for this, would it be accepted ?

**Comment by B4nan** [comment]
Oh, actually, I think I know a way how to do this, could be quite simple.

**Comment by B4nan** [comment]
This should do it.

**Comment by rvion** [comment]
Amazing ! Thanks a lot !
It even reduces memory usage 👌 

----------

naive / dumb questions: would that makes sense to 
- remove the ability to create `Reference` without em
	- then merge `Reference` functionality into  the `WrappedEntity` state object directly ?

---

also, it could make sense to change wording a bit I guess; from my understanding, `wrapReference` in doc pair with the `Reference` class in the code, and `reference` in the code pair with `WrappedEntity` class in the code

**Comment by gggdomi** [comment]
@B4nan amazing that you could improve something that feels so deep this quickly. Thanks.

**Comment by B4nan** [comment]
> remove the ability to create Reference without em

Why? I actually plan to use the `Reference.createFromPK` internally to lift some other restrictions (e.g. in the `assign` helper when used on not managed entities). Reference is now bound to entity instance, that should work just fine.

> then merge Reference functionality into the WrappedEntity state object directly ?

Many parts of the `WrappedEntity` are internal, I am not sure I want to mix those two things together. The `Reference` has some API based on the `WrappedEntity`, that's true.

> also, it could make sense to change wording a bit I guess; from my understanding, wrapReference in doc pair with the Reference class in the code, and reference in the code pair with WrappedEntity class in the code

`reference` is not really about the `WrappedEntity`, its about the property type - whether its relation (and what kind), a scalar or embedded property. I'd like to rename that to `kind` in v6 and `wrappedReference` to just `ref`, see #3593 for more.
