### ISSUE TITLE
When using the QueryBuilder, limit must come after any joins

### ISSUE THREAD

**Issue by lagnat** [mikro-orm/mikro-orm#3594]
**Describe the bug**
In order to get proper results with a query that has a limit, Mikro-orm must know if there are ToMany joins on the query so it can enable sub-queries.  The code refers to this as `pagination`.  If one supplies the limit before adding the joins, the results are incorrect as the sub-query is not applied.

**Expected behavior**
The properly paginated results are returned independent of the order in which limit and joins are applied.

**Additional context**
My initial thought was that the decision to handle pagination could be delayed until query generation time but I don't have enough familiarity with this code to know if that's actually a good idea.

One could also argue that this is a bug in the documentation as I don't believe I saw any warning about calling order.

**Versions**
mikro-orm 5.4.2

**Comment by B4nan** [comment]
Actually, this is not reproducible and your observations don't make much sense to me - neither joins nor setting limit (nor the whole pagination logic) is evaluated eagerly, this is both happening at the end when finalizing the QB. So I'd say this is just the same problem as your previous issue.

Next time please provide reproductions as code. 

Will be happy to reopen with failing reproduction if you still think there is a bug.

**Comment by lagnat** [comment]
You are correct.  This ended up being user error, however it's a trap that others might fall into so I'll explain what happened.

My code calls QueryBuilder methods in various phases.. 

```
    qb
        .limit(opts.limit)
        .offset(opts.offset)
        .orderBy(orderBy);

... other code here ...

    qb.join(...);

... other code here ...

    const data = await qb.getResultList();
```

As written, the IDE warns me that the first chunk of code is a floating promise (eslint[@typescript-eslint/no-floating-promises]).  It's wrong but it thinks it's a promise because you have a `.then()` method.  Without realizing that, I `await`ed it and that caused the query to run prematurely (getInnerPromise()), before the joins were added.  Once the joins are added and `qb.getResultList()` is called, the qb instance doesn't produce the properly paginated query.

**Comment by B4nan** [comment]
Hmm, that's indeed quite bad. But at the same time, I really don't want to remove the ability to await the QB (it would be breaking, so it's out of the question for now anyway)... 

Will do some googling and maybe ask on SO, did some initial testing, and even if I comment out the `then` methods, I am getting the eslint warning 🤷 

Knex is apparently having the same problem: 
- https://github.com/knex/knex/issues/5364
- https://github.com/typescript-eslint/typescript-eslint/issues/2640

**Comment by lagnat** [comment]
IMO this is not your problem to fix but you could detect when a qb is executed more than once.  Not sure if that's a supported use of qb, but if it is, then you might need to check that the pagination flag is properly set on the second invocation.
