### ISSUE TITLE
Formula defined with EntitySchema throws undefined error for type.toLowerCase()

### ISSUE THREAD

**Issue by squivix** [mikro-orm/mikro-orm#3603]
**Describe the bug**
Formula property `otherCount` defined with EntitySchema as follows:
```js
export const schema = new EntitySchema({
    name: "MyEntity",
    class: MyEntity,
    properties: {
        _id: { primary: true, type: 'number'},
        other: { type: 'OtherEntity', reference: ReferenceType.MANY_TO_MANY},
        otherCount: { formula: 'COUNT(other)' },
    },
});
```
Throws a TypeError: Cannot read properties of undefined (reading 'toLowerCase')

**Stack trace**
```
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at MetadataDiscovery.getMappedType (/home/user/WebstormProjects/test-mikro/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:845:52)
    at MetadataDiscovery.initColumnType (/home/user/WebstormProjects/test-mikro/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:820:37)
    at MetadataDiscovery.processDiscoveredEntities (/home/user/WebstormProjects/test-mikro/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:71:28)
    at async MetadataDiscovery.discover (/home/user/WebstormProjects/test-mikro/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:35:9)
    at async MikroORM.discoverEntities (/home/user/WebstormProjects/test-mikro/node_modules/@mikro-orm/core/MikroORM.js:102:25)
    at async Function.init (/home/user/WebstormProjects/test-mikro/node_modules/@mikro-orm/core/MikroORM.js:47:9)...
```

**To Reproduce**
1. Define an entity in Javascript using the EntitySchema
2. Add a property that is a formula without a type
3. Error

**Expected behavior**
Formula properties should not need a type, as [the docs show](https://mikro-orm.io/docs/defining-entities#formulas):
```
properties: {
  objectVolume: { formula: 'obj_length * obj_height * obj_width' },
},
```

**Versions**

| Dependency | Version |
| - | - |
| node | v16.17.0 |
| typescript | - |
| mikro-orm | 5.4.2 |
| @mikro-orm/postgresql | 5.4.2 |

**Comment by squivix** [comment]
Thanks. The formula works, but I realized it doesn't do what I need.

This might be off topic but:

I need to count the other side of the ManyToMany relationship. Using formulas doesn't work because `other` is not a  column in the MyEntity table. 

If I use `other.count()`, I need to populate all the other entities, which is very slow and seems unnecessary when all I need is their count. Is there a way to populate only the count of a collection?

**Comment by B4nan** [comment]
You can use a subquery inside formula.

**Comment by B4nan** [comment]
> Is there a way to populate only the count of a collection?

For that you can just use `Collection.loadCount()`. If you need this for an array of entities, its better to come up with the subquery via formula I guess, it will be more performant than N count queries.

**Comment by squivix** [comment]
> You can use a subquery inside formula.

Can you give an example of this? The from clause doesn't seem to fit. 

```js
otherCount: { type: 'number', formula: alias => `COUNT(*) FROM pivot_table WHERE other__id=${alias}._id`, persist: false}
```
or

```js
otherCount:{ type: 'number', formula: alias => `COUNT(SELECT * FROM pivot_table WHERE other__id=${alias}._id)`, persist: false }
``` 
I get a `SyntaxErrorException` in both cases

I'm using PostgresSQL btw

**Comment by B4nan** [comment]
you need to use actual subquery, not an incomplete sql fragment, and wrap it in parens. something like this (not tested, you will need to come up with the subquery yourself)

```ts
otherCount: { type: 'number', formula: alias => `(select COUNT(*) FROM pivot_table WHERE other__id=${alias}._id)`, persist: false}
```

**Comment by squivix** [comment]
Thanks a lot for being patient with me. The subquery formula worked but was slow. Then I found out my problem was lack of indexes. I thought MikroORM created them automatically because I came from another ORM that did. Definitely  have a lot to learn.

Again thanks :D

**Comment by B4nan** [comment]
Only mysql requires indexes for FKs, and there they are created automatically. In other drivers you need to be explicit.
