### ISSUE TITLE
Using bigserial / bigint in IdEntity

### ISSUE THREAD

**Issue by thekevinbrown** [mikro-orm/mikro-orm#361]
**Is your feature request related to a problem? Please describe.**

We use bigserial in Postgres for many primary keys. Typescript has a built in `bigint` type, but I can't use it with `IdEntity`:

```typescript
export class Credential implements IdEntity<Credential> {
	@PrimaryKey({ type: 'bigint' })
	id!: bigint;
}
```

gives

```
Type 'Credential' does not satisfy the constraint '{ id: string | number; }'.
  Types of property 'id' are incompatible.
    Type 'bigint' is not assignable to type 'string | number'.ts(2344)
```

**Describe the solution you'd like**

Maybe an approach like `UuidEntity` would work here? Maybe `BigIntIdEntity`? Or maybe it'd be simple enough to just have `id` in `IdEntity` defined as `id: number | string | bigint;`?

**Describe alternatives you've considered**

I'm relatively new to Mikro ORM, so I'm not sure what a good alternative would be. We need to be able to define the entity so the database handles it as well as not overflowing the number type if it gets large enough.

**Additional context**

None needed that I can tell.

**Comment by B4nan** [comment]
You can use any PK type, including the `bigint`, by using `AnyEntity` interface:

```typescript
export class Credential implements AnyEntity<Credential, 'id'> {
	@PrimaryKey({ columnType: 'bigserial' })
	id!: bigint;
}
```

I also used `columnType` here to specify the database type explicitly, as there is no `bigint` mapping in the ORM.

**Comment by B4nan** [comment]
Hmm but looks the schema generator then does not recognise the property as primary key then, so the fix above will help you only with the TS problem, not with correct schema.

**Comment by thekevinbrown** [comment]
I think the commit above might fix this, but in the schema generator with:

```typescript
@PrimaryKey({ columnType: 'bigserial', type: 'number' })
id!: number;
```

I'm getting:

```
create table "credential" ("id" serial primary key,  /* etc */
```

It'd be great if this could respect my `columnType`.

**Comment by B4nan** [comment]
That commit is just a first part to fix this, now you can use custom type to have bigints in node instead of strings, but the schema generator still does not correctly support it.

**Comment by B4nan** [comment]
`BigIntType` now available in v3.4.0

https://mikro-orm.io/docs/using-bigint-pks

**Comment by thekevinbrown** [comment]
@B4nan, thank you so much!

**Comment by PodaruDragos** [comment]
My apologies, I know this is old, but why does Mikro right now convert it to a string. JavaScript has BigInt built in. I think the custom type described  [here](https://mikro-orm.io/docs/using-bigint-pks) should be the default way.

If there is something I didn't get please fell free to correct me.

**Comment by B4nan** [comment]
Changing this would be breaking, we can consider it for v6. I don't remember if there were some problems supporting this in v5, but I think something was problematic, probably TS setup related in combination with the node 14.0+ requirement. I would be in favour of doing this in v6, also cutting support for node 14. Originally I even thought v6 could be ESM only, but I don't feel like the time has come just yet :]

**Comment by PodaruDragos** [comment]
Thanks for the answer, is there a roadmap for v6 ? I am just curious to what goodies v6 will bring us

**Comment by B4nan** [comment]
Not at all, right now I am focusing on a new getting started guide and improving the ESM support, I dont plan any big changes that would require major bump in near future. But thats a bit offtopic here :]
