### ISSUE TITLE
docs: `em.findOneOrFail` failure throws `NotFoundError` instead of `Error`

### ISSUE THREAD

**Issue by lokshunhung** [mikro-orm/mikro-orm#3620]
In the documentation section of "Custom Fail Handler" on the page about "Configuration" ([here](https://mikro-orm.io/docs/configuration#custom-fail-handler), current version is 5.3):

> When no entity is found during em.findOneOrFail() call, new Error() will be thrown.

However, by studying the source for [Configuration](https://github.com/mikro-orm/mikro-orm/blob/2f81120a48ff1d1f556211632295063fd0e2db62/packages/core/src/utils/Configuration.ts#L65-L66), the default value of `findOneOrFailHandler` and `findExactlyOneOrFailHandler` actually throws a [NotFoundError](https://github.com/mikro-orm/mikro-orm/blob/2f81120a48ff1d1f556211632295063fd0e2db62/packages/core/src/errors.ts#L230-L240), instead of a plain `new Error()`.

**Comment by B4nan** [comment]
It's an extension, so technically it is an `Error` instance.
