### ISSUE TITLE
Returning "id" - invalid input syntax for type uuid

### ISSUE THREAD

**Issue by Germano123** [mikro-orm/mikro-orm#3632]
**Describe the bug**
Database does not seed with the given information.

**To Reproduce**
Given the [simples test repo](https://github.com/Germano123/mikro-orm-test.git) follow the steps to reproduce the behavior:
1. npm i
2. npm run start:dev || npx mikro-orm migration:up
3. npm run database:localseed

**Expected behavior**
Add a bunch of data from the seed factories.

![image](https://user-images.githubusercontent.com/19863981/197246815-8881b42b-acb9-4822-b48d-a73882e72ddb.png)

Edit: upload the correct pic from the test repo.

**Comment by B4nan** [comment]
This is far from a _minimal_ reproduction, please simplify. Reproduction should be a simple script, not a web app. This has so many files I didn't even find the entities except the base one.

**Comment by Germano123** [comment]
The entities are organized in the modules. Should see the only two there: User and School. User is an abstraction for Common User, Supervisor, School Admins and Super Admin. And the other important part in the repo are in the seeders folder, separated with seeder files and some factories for each data I want to put in the database.

**Comment by B4nan** [comment]
That's all nice, but please provide minimal reproduction as I asked above. You are reporting issue with seeder, so provide a script that only uses seeder, rest is irrelevant and only adds complexity. 

Example reproductions: 

https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues

**Comment by Germano123** [comment]
Would this help? [Repo gist](https://gist.github.com/Germano123/d7b45958e7120376986f8bbd5c4f5fd5)

**Comment by B4nan** [comment]
It seems to be incomplete, e.g. `SchoolAdminEntity` is missing.

The first problem I can see is the `mapToPk` option, if you want that, the property type is the same as its PK, not the entity itself:

```diff
@OneToOne(() => SchoolAdminEntity, adminstrator => adminstrator.school, { owner: true, mapToPk: true })
-adminstrator: SchoolAdminEntity;
+adminstrator: string;
```

And this is probably the issue for what you see, as when you fix that, you will see you did something wrong when creating the entity instance - passing entity object where it was supposed to be a PK value.

**Comment by B4nan** [comment]
Yop, namely this line is wrong, and makes the seeder fail:

https://gist.github.com/Germano123/d7b45958e7120376986f8bbd5c4f5fd5#file-mikro-orm-test-gist-ts-L13
