### ISSUE TITLE
Provide Access To __loadedProperties In Wrap Helper

### ISSUE THREAD

**Issue by ThatOneAwkwardGuy** [mikro-orm/mikro-orm#3642]
**Is your feature request related to a problem? Please describe.**
I would like to store the diffs between certain entities when they are created, deleted or updated.

The problem is, when I  convert them to JSON they also include the data from all their loaded relationships.

**Describe the solution you'd like**
I saw that the toObject method on the wrap helper, allows you to filter out fields. If I had access to the __loadedProperties value, I believe I could filter out the fields containing relationships and to save space.

**Describe alternatives you've considered**
Currently, I'm storing all of it, but that's a waste of space and also can end up being thousands of lines of JSON

**Additional context**

**Comment by B4nan** [comment]
Its internal property, you have access to all of them, just use the second parameter:

```ts
wrap(entity, true). __loadedProperties
```
