### ISSUE TITLE
TypeError: The operator "is" is not permitted

### ISSUE THREAD

**Issue by wSedlacek** [mikro-orm/mikro-orm#3647]
**Describe the bug**
I get a TypeError when using findAll() with a `having` parameter.

**Stack trace**
```
previous TypeError: The operator "is" is not permitted
    at operator (node_modules/knex/lib/formatter/wrappingFormatter.js:132:11)
    at QueryCompiler_MySQL.havingBasic (node_modules/knex/lib/query/querycompiler.js:650:7)
    at QueryCompiler_MySQL.having (node_modules/knex/lib/query/querycompiler.js:601:31)
    at node_modules/knex/lib/query/querycompiler.js:133:40
    at Array.forEach (<anonymous>)
    at QueryCompiler_MySQL.select (node_modules/knex/lib/query/querycompiler.js:132:16)
    at QueryCompiler_MySQL.toSQL (node_modules/knex/lib/query/querycompiler.js:73:29)
    at Builder.toSQL (node_modules/knex/lib/query/querybuilder.js:83:44)
    at QueryBuilder.execute (node_modules/@mikro-orm/knex/query/QueryBuilder.js:427:43)
    at MySqlDriver.find (node_modules/@mikro-orm/knex/AbstractSqlDriver.js:49:46)
```

**To Reproduce**
```ts
@Entity({ tableName: 'applications' })
export class ApplicationEntity {
  @PrimaryKey({ type: UuidType })
  public id!: string;

  @Property()
  public name!: string;

  @Property()
  public icon!: string;

  @Property()
  public createdAt!: Date;

  @Property({ nullable: true })
  public removedAt?: Date;
}

@QueryHandler(GetApplications)
export class GetApplicationsHandler implements ICommandHandler<GetApplications> {
  constructor(
    @InjectRepository(ApplicationEntity)
    private readonly applications: EntityRepository<ApplicationEntity>
  ) {}

  public async execute(query: GetApplications): Promise<ApplicationDto[]> {
    const applications = await this.applications.findAll({ having: { removedAt: null } }); // Triggered on this line

    return applications.map((application) => new ApplicationDto(application));
  }
}
```

**Expected behavior**
The `having` to create a valid query for getting all applications meeting the critiea.

**Additional context**

I believe the error is coming from here
https://github.com/mikro-orm/mikro-orm/blob/12398fdd489791577f8dd592f42a85fd404602ea/packages/knex/src/query/QueryBuilderHelper.ts#L432

The `is` operator is not listed here
https://github.com/knex/knex/blob/1cc1df9c35eedf2f48cea487693166bab1bcfb90/lib/formatter/wrappingFormatter.js#L10-L54

I have also ran into issues when trying to use the `$in` with a similar error that the `in` operator is not permitted.

**Versions**

| Dependency | Version |
| - | - |
| node | 14.19.0 |
| mysql | 5.7 |
| typescript | 4.7.4 |
| mikro-orm | 5.5.0 |
| micro-orm/mysql | 5.5.0 |

**Comment by B4nan** [comment]
Please provide complete reproduction, this is not enough.

**Comment by wSedlacek** [comment]
I figured out a solution to my problem, I should have been using `.find()` instead of `.findAll()`.
That said, is this `findAll()` with `having` still a bug?

**Comment by B4nan** [comment]
[`repo.findAll` literally calls `repo.find()`](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/entity/EntityRepository.ts#L74-L76), so that feels a bit unreal :]

**Comment by B4nan** [comment]
My guess is you have some dependency mismatch after upgrading, try wiping node_modules and lock file and reinstall. I doubt `findAll` would behave differently than `find` given the implentation.

**Comment by wSedlacek** [comment]
https://github.com/wSedlacek/recreate-mikro-orm-bug-operators

Here is a recreation.
I attempted to use stackblitz, but ran into limitations of sqlite there (not supporting `returning`), so to test you'll need to run it locally.

I have it setup so that `localhost:3000/` triggers the issue on request. The recreation is dead simple, just pass in `having` to a `findAll()`

**Comment by B4nan** [comment]
I was hoping for minimal reproduction. A script without any additional dependencies, not a nestjs webapp.

**Comment by wSedlacek** [comment]
Let me see what I can do to get one that is just using MikroORM

**Comment by B4nan** [comment]
Interesting. `repo.find` behaves exactly the same as `repo.findAll`, as expected, so not sure why you think there is any difference.

This looks like some artificial limitation of knex (https://github.com/knex/knex/issues/5203). cc @kibertoad 

But when I add the operator to the place you linked (inside knex), the query compliles and ends up with SQLite error anyway. You are trying to create invalid query...

> DriverException: select `d0`.* from `data` as `d0` having `d0`.`removed_at` is NULL - SQLITE_ERROR: HAVING clause on a non-aggregate query

**Comment by wSedlacek** [comment]
Huh, good to know. When I was writing this I was really looking for a `where` clause, and `find()` gives me that, so no problem there. Maybe the type for `findAll()` could be smarter to reduce what you can pass to `having` such that it would not result in a runtime error?

Either way I am off and running with my project, was just caught off guard with the `having` not working as I expected.
