### ISSUE TITLE
Cannot select embedded property

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#3649]
```TypeError: Cannot read properties of undefined (reading '0')```

https://github.com/mikro-orm/mikro-orm/blob/12398fdd489791577f8dd592f42a85fd404602ea/packages/mongodb/src/MongoDriver.ts#L246

```typescript

@Embeddable()
export class ApproveRejectMikro {
  @Property({ type: Boolean, fieldName: 'approved' })
  approved!: boolean;

  @Property({ type: Date, fieldName: 'approvedDate' })
  approvedDate?: Date;

  @Property({ type: Date, fieldName: 'rejectedDate' })
  rejectedDate?: Date;
}

class Test {
  @Embedded(() => ApproveRejectMikro)
  approveReject: ApproveRejectMikro = new ApproveRejectMikro();
}
```

i'd expect it to know all of the fields mapped in the embedded and expand them for selection

**Comment by B4nan** [comment]
Sorry, I am tired of this, you haven't provided any reproduction, just incomplete entity definition, no runtime code, no setup (how can I know what is in your database), ignored the issue template (what versions are you on? is it new? are you on latest?), no ORM config, from the error you have you shared only the first line instead of full stack trace. 

So closing till you provide something reproducible, this is not how a bug report should look like.

**Comment by parisholley** [comment]
did you bother to look at the line i referenced? it would have taken all of 5 seconds to realize that it is pointing to the latest code in master, and given your intimate knowledge of the project, you would know just as I did, that the environment of my project isn't relevant when the logic of the reference line clearly shows there isn't any consideration for building field names based on nested objects.

if you don't wish to look into it, that is fine, the issue is here for anyone who may search for the problem in the future. i have about 10+ issues i haven't created so that i could find time to build reproductions for them (and probably fix myself, including this) but this issue is about metadata and your going to be best positioned to understand how to fix.

i can workaround this issue by just selecting all for now and i will revisit a reproduction when the problem becomes a bigger issue.

**Comment by B4nan** [comment]
Yes I did. And without additional details, I have no idea what you are talking about, neither how your project is configured. That line is covered with tests, they pass 🤷 That place shouldnt do anything about building fieldNames, that all happens during metadata discovery. 

> if you don't wish to look into it, that is fine

I wish to look into it. But apparently you expect me to debug issues without any information about them. 

> and probably fix myself, including this

You keep saying this. Yet I recall only one PR from you, fixing a typo in docs. On the other hand you created maybe 50 issues, many of them feature requests - I resolved most of them. Yet you are not willing to do the extra step and provide quality reproductions. 

So please, provide reproductionsc right ahead, and dont expect me to debug problems that are not well defined. 

Note that you already have some open issues about embeddables and field names. This is generally not supported (although it shouldnt end up with TypeError for sure).

**Comment by parisholley** [comment]
that function is using the fields/populate param of API calls to effectively return a column list to build the query. if i pass a field which is an embed, this error occurs. rather than it being a runtime error (eg: "you cannot select an embedded field"), the metadata discovery process already knows the type is embedded and that each sub-field has a "fieldName" defined. and can "Explode" my embedded field into multiple fields eg:

```for(field of prop.subfields){ret.push(field.fieldNames[0])}``

> Yet I recall only one PR from you, fixing a typo in docs

i often times have local npm patches for most of the issues i post, but until i get a chance to dig into the framework more to understand if it is a hack job vs final solution, i don't want to waste a bunch of time doing reproductions and PRs only for the solution to be something else. this framework is complex enough that opinion on what layer something sits (uow, metadata discovery, runtime query generation, etc) that there isn't a "right" way to solve most of the issues i raise.

> On the other hand you created maybe 50 issues, many of them feature requests - I resolved most of them

and I appreciate this and thus sponsor this project through github, but i also don't ask for you to do it and would be happy to do the work myself if you offer guidance as to which layers are appropriate. if it is a matter of semantics and you rather my issues be "discussions", then fine, I don't feel strongly one way or another.

>Yet you are not willing to do the extra step and provide quality reproductions.

thats a bit disingenuous, if the issue is obvious or i can understand the code/context, i will provide a repro or do a fix myself.

https://github.com/mikro-orm/mikro-orm/issues/2410 - provided PR
https://github.com/mikro-orm/mikro-orm/issues/2401 - provided PR
https://github.com/mikro-orm/mikro-orm/issues/2364 - provided reproduction
https://github.com/mikro-orm/mikro-orm/issues/2406 - provided reproduction
https://github.com/mikro-orm/mikro-orm/issues/3092 - did the research to show you where the issue is in code

here are issues where your replies made it obvious that i would be wasting my time with reproductions.
https://github.com/mikro-orm/mikro-orm/issues/2365
https://github.com/mikro-orm/mikro-orm/issues/2366
https://github.com/mikro-orm/mikro-orm/issues/2373
https://github.com/mikro-orm/mikro-orm/issues/2391
https://github.com/mikro-orm/mikro-orm/issues/2394
https://github.com/mikro-orm/mikro-orm/issues/2395

a lot of times i find errors but i don't need them fixed because i come up with an alternative/workaround, so i'm going to post the issue incase someone else runs into it and wants it fixed but i'm not going to take time reproduce
https://github.com/mikro-orm/mikro-orm/issues/2371
https://github.com/mikro-orm/mikro-orm/issues/2362

> dont expect me to debug problems

i don't, simply saying, "i'm not sure off the top of my head what the issue is, please provide reproduction" and i will gladly follow up with one if it is serious
