### ISSUE TITLE
Update embeddable's value via `entity.assign` won't try to fix types

### ISSUE THREAD

**Issue by ah-nvision** [mikro-orm/mikro-orm#3653]
**Describe the bug**
Update embeddable's value via `entity.assign` won't trying to fix data type, it is expected to works like `entity.create`

Example:
``` typescript
@Embeddable()
class Nested {
  @Property({ type: Date })
  date: Date | string;
}

@Entity()
export class Test {
  @PrimaryKey()
  _id: ObjectId;

  @Embedded(() => Nested, { object: true })
  nested: Nested;
}

---
const entity = await this.testRepo.findOne({ _id: ObjectId('6357a02753179128e7f92789') });

this.testRepo.assign(entity, { nested: { date: '2022-10-25T09:19:49.861Z' } });
await this.testRepo.persistAndFlush(entity);
```

**Current behvaior**
Generated query
```
db.getCollection('test').updateMany({ _id: ObjectId('6357a02753179128e7f92789') }, { '$set': { nested: { date: '2022-10-25T09:19:49.861Z' } } }, {})
```

**Expected behavior**
Query should be
```
db.getCollection('test').updateMany({ _id: ObjectId('6357a02753179128e7f92789') }, { '$set': { nested: { date: ISODate('2022-10-25T09:19:49.861Z') } } }, {})
```

**Versions**

| Dependency | Version |
| - | - |
| node | 16.14.0 |
| typescript | 4.7.4 |
| mikro-orm | 5.5.0 |
| mongodb | 5.5.0 |

**Comment by B4nan** [comment]
> Update embeddable's value via entity.assign won't trying to fix data type, it is expected to works like entity.create

Nope, it is not expected to fix your types. If your definition was valid (`date: Date | string` should be just `date: Date`), this woudn't even type check,
