### ISSUE TITLE
SQLite don't work in stackblitz repros

### ISSUE THREAD

**Issue by Nisgrak** [mikro-orm/mikro-orm#3655]
**Describe the bug**
I was making a repro for a bug with `upsert` bug and found that any of the repro you have in stackblitz work, they worked a few days ago.

https://stackblitz.com/edit/mikro-orm-esm-repro?file=package.json

**Stack trace**
```
SyntaxErrorException: insert into `user` (`name`) values ('old name') returning `id` - SQLITE_ERROR: near "returning": syntax error
```

**Expected behavior**
Insert the element without any errors

**Additional context**
I also tried the plain js/jest repro and also fails.

If you update the packages to 5.5.0 also fails.

**Comment by B4nan** [comment]
What do you expect from me, fixing stackblitz problems? :]

**Comment by Nisgrak** [comment]
You have right, I a few days ago was working isn't mikro fault. Sorry for the trouble

**Comment by B4nan** [comment]
Well, a few days ago it was working because you used different version of the ORM. v5.5 uses returning statements for SQLite, and stackblitz is not supporting that, as they dynamically swap the sqlite library with some other version that can run in browser I guess. That error simly means they use outdated SQLite version.

https://www.sqlite.org/lang_returning.html

> The RETURNING syntax has been supported by SQLite since version 3.35.0 (2021-03-12).

**Comment by B4nan** [comment]
I hope there is, as the stackblitz reproductions are quite handy. Technically this is configurable, but you would have to override the platform class to disable the returning clause usage.

Btw seeing you used the ESM repro, I am not surprised it didnt work for you with jest, its a huge pain to make jest work with ESM these days.

**Comment by Nisgrak** [comment]
Jest is huge pain, in any ways and form....

Actually I think the stackblitz repro are some "hidden", maybe you can include in the web or in the issue template?
Also have it in the readme, with a click check a minimal version of the lib working is awesome.

As always, thanks you so much for your work! It's amazing

**Comment by B4nan** [comment]
Doing this before `MikroORM.init()` should help:

```ts
import { SqlitePlatform } from '@mikro-orm/sqlite';

SqlitePlatform.prototype.usesReturningStatement = () => false;
```

https://stackblitz.com/edit/mikro-orm-esm-repro-9ruucs?file=basic.test.ts

> Actually I think the stackblitz repro are some "hidden", maybe you can include in the web or in the issue template?

That's the plan, but without this being resolved, it's not really usable.

**Comment by Nisgrak** [comment]
That works like a charm! I can now open the real issue with the compund index and upsert!
