### ISSUE TITLE
Support compound unique in upsert

### ISSUE THREAD

**Issue by Nisgrak** [mikro-orm/mikro-orm#3656]
**Describe the bug**
The new `upsert()` fails if you try to upsert with a compound index

**Stack trace**
```
Error: Unique property value required for upsert, provide one of: id
```

**To Reproduce**
https://stackblitz.com/edit/mikro-orm-esm-repro-y96acp?file=basic.test.ts

**Expected behavior**
Generate an insert on conflict 'my_autogenerate_compound_index'

**Comment by Nisgrak** [comment]
Yeah, maybe "bug" wasn't the aproppied word...

Anyway I see that Postgre and SQLite allow to specify what index have to conflict, maybe we can specify in the `upsert()`?
```ts
orm.em.upsert(User, { ... }, { index: "my_compound_index" } 
```

MariaDB doesn't seem to allow that.

**Comment by B4nan** [comment]
This is not about indexes, the problem is comparing complex PKs, that is the reason why this is disallowed, as you can't simply compare things like `a.id === b.id`, neither you can build a map of pk <-> entity easily. 

TBH I was just lazy implementing this, the `em.upsert` turned to be very complex already even without that... 

If you wanna take a look, its this part of codebase: https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/EntityManager.ts#L523

This would have to additionally check composite unique constraints - those live on the entity metadata (`meta.uniques`), not on property level. I guess it won't be that hard to support, it was just too much to do in a single run.

**Comment by LazerJesus** [comment]
I run into the same issue. Its happening even tho i define onCreate behavior on my entity schema.
```
  properties: {
    id: {
      type: String,
      primary: true,
      onCreate: () => v7(),
    },
    ...
```
trying to upsert that entity still yields a `unique constraint error`. 
This not being supported seems like its defeating the purpose  of the `upsert` method.

not a blocking issue, but somewhat annoying.

**Comment by B4nan** [comment]
If you do `em.upsert(Type, ...)`, there are no entity instances created before the query is fired, so neither property initializers, nor `onCreate` property hooks are executed. If you want that, you first need to create the entity (e.g. via `em.create` or the constructor) and feed that to the `em.upsert` call. You can as well override what columns should be used for updates in case the entity exists via upsert options (`onConflictMergeFields` or `onConflictExcludeFields` options).

https://mikro-orm.io/docs/entity-manager#upsert

**Comment by LazerJesus** [comment]
thats how i had solved it. copied straight from the docs. thank you. your docs are pretty fantastic.

still, this seems counterintuitive, but i might be thinking in the wrong paradigm. 
 
Why arent entity instances created on upsert while the unique constraints do fire?

**Comment by B4nan** [comment]
> while the unique constraints do fire?

Not sure what you mean? Unique constraints fire when you run a query, that is too late to do anything on runtime, what you want would require creating the entity instances before we create the query. 

You are not the first one who was expecting this to work, it's surely something I want to have another look at, maybe for v7. The root issue here is that before the query is fired, you can't know if you are inserting or updating, so you don't really know if a property initializer or `onCreate` hook should even be fired. I do have some ideas how to make this better, maybe just respecting the `onCreate` and `onUpdate` property hooks could be enough, but it's still problematic, those hooks are getting the entity instance in the parameters and we don't have one by the time we would need to call them.

**Comment by LazerJesus** [comment]
relying on the databases native upsert doesnt work? sqlite f.e. supports `UPSERT` natively.
