### ISSUE TITLE
Assigning a ManyToOne field no longer cascades to the owning side collection on persist and flush in 5.5.0

### ISSUE THREAD

**Issue by kpervin** [mikro-orm/mikro-orm#3658]
**Describe the bug**
Prior in 5.5.0, I was able to persist a reference to the owning side of a ManyToOne relationship via the following:

```ts
@Entity()
class Foo {
  @PrimaryKey()
  id: number;

  @OneToMany(() => Bar, bar => bar.foo)
  bars = new Collection<Bar>(this);
}

@Entity()
class Bar {
  @PrimaryKey()
  id: number;

  @ManyToOne({
    entity: () => Foo,
    onUpdateIntegrity: "cascade",
    onDelete: "cascade",
  })
  foo: Foo;
}

...

const foo = await fooRepository.findOneOrFail(fooId);

const bar = wrap(new Bar()).assign({
  foo
});

await orm.em.persistAndFlush(bar);

const bars = await foo.bars.loadItems(); // Previously created `bar` would be in the Identity Map

```
However, in 5.5.0, this no longer works and I now have to call `foo.bars.add(bar)` instead. 
I've looked across a lot of issues in here, and it seems that @B4nan always advocated for using `collection.add()` instead of `.assign()`, but why was it that the latter worked fine until 5.5.0? This does however work when calling `refresh: true` if querying for `foo` again, but the point is that the Identity Map is not updated when using `assign`.  

**Versions**

| Dependency | Version |
| - | - |
| node | 16.16.0 |
| typescript | 4.8.4 |
| mikro-orm | 5.5.0 |
| your-driver | MySQL |

**Comment by B4nan** [comment]
> This does however work when calling refresh: true if querying for foo again

This means you are probably mixing contexts. It also means the propagation works, as refreshing helps. Please provide complete repro, so I can see what you are doing with the contexts.

**Comment by B4nan** [comment]
You will need to provide repro 🤷

**Comment by kpervin** [comment]
Oddly, I also note that adding `this.orm.em.persist(foo)` after the `assign` call doesn't seem to add it to unitOfWork:

![image](https://user-images.githubusercontent.com/7747148/198109367-f5cbbab6-4603-4894-97a3-a0f5e8f707e5.png)

Is that expected?

**Comment by kpervin** [comment]
I think potentially my issue has to do with having `allowGlobalContext` set during unit tests. It is not set outside of tests, and seems to work fine there. How does one not use global request context with NestJS testing without needing to decorate every method with `@UseRequestContext()`?

**Comment by kpervin** [comment]
Ok, I was able to fix it with the following: https://mikro-orm.io/docs/faq#new-entity-instances-get-initialized-with-all-properties-set-to-undefined

However, any idea why this occurred in the first place? This is the first time this has happened before.
