### ISSUE TITLE
persist: false properties are being requested in `returning` clause in 5.5.0

### ISSUE THREAD

**Issue by lagnat** [mikro-orm/mikro-orm#3664]
**Describe the bug**
After upgrading to 5.5.0, my code is failing because mikro-orm is trying to request columns that do not exist.

**To Reproduce**
I don't have the bandwidth at the moment to work on a failing test but I wanted to get this reported.

**Additional context**
```
     insert into `channel` (.. columns redacted .. ) values ( .. values redacted .. ) returning `is_premium` - SQLITE_ERROR: no such column: is_premium
```
```
    @Property({
        persist: false,
        name: 'isPremium',
    })
    get isPremium(): boolean {
        .. code ..
    }

```

**Versions**

| Dependency | Version |
| - | - |
| node | 16.18.0 |
| typescript | 4.7.4 |
| mikro-orm | 5.5.0 |
| your-driver | sqlite |

**Comment by bnussman** [comment]
Same issue here with PostgreSQL on `5.5.0` when using 

```ts
@Property({ persist: false })
```

**Comment by PodaruDragos** [comment]
I added a somehow reliable stack trace on a thread in slack.

```
InvalidFieldNameException
insert into ...........
at PostgreSqlExceptionConverter.convertException
at PostgreSqlDriver.convertException
at processTicksAndRejections
at async PostgreSqlDriver.nativeInsertMany
at async ChangeSetPersister.persistNewEntity 
at async ChangeSetPersister.executeInserts
at async ChangeSetPersister.runForEachSchema
at async UnitOfWork.commitCreateChangeSets
at async UnitOfWork.persistToDatabase.
```

maybe this can help track down at least something.
