### ISSUE TITLE
Upsert implementation

### ISSUE THREAD

**Issue by ramiel** [mikro-orm/mikro-orm#367]
**Is your feature request related to a problem? Please describe.**
A clarification on a possible feature

I'm going to create a `CustomBaseRepository` to implement a generic method to find or create (upsert). Can you point me to some example on how to create such a base repository? The documentation (https://mikro-orm.io/docs/repositories#custom-repository) si not very exhaustive and the links provided have no example for a custom base repository.

Alternatively, does such method exist already?

**Comment by B4nan** [comment]
Just create a generic class extending `EntityRepository` and pass it in the ORM config via `MikroORM.init({ entityRepository: CustomBaseRepository })`. 

Something like this should work:

```typescript
export class CustomBaseRepository<T extends AnyEntity<T>> extends EntityRepository<T> {
  upsert() { ... }
}
```

> Alternatively, does such method exist already?

Nope.

Not sure if I understood well, do you also need help with implementation of the upsert method? Should be quite trivial.

**Comment by ramiel** [comment]
Thanks, it's perfect. No, I don't need help with the implementation but I need to understand about the internals of the EntityRepository, but for that I can check the source code. Thank you again

**Comment by B4nan** [comment]
Its pretty simple, all what repository does is that it forwards calls to the entity manager with the entity name stored in `this.entityName`. But you can use the repository methods directly so it will be handled for you:

```typescript
async upsert(data, where) {
  let e = await this.findOne(where);

  if (e) {
    wrap(e).assign(data);
  } else {
    e = this.create(data);
    await this.persistAndFlush(e); // or maybe you do not want to flush here, depends on the use case
  }

  return e;
}
```

**Comment by ramiel** [comment]
Oh, is there a way to take advantage of upsert in mongo? I know it would be specific for only one DB, but it would run in a transaction. Otherwise I don't know if multiple operations like reading/writing can happen in transaction on MongoDB.
To clarify, I'd like to use mongo specific method `findOneAndUpdate(where, updates, {upsert: true})`

**Comment by B4nan** [comment]
You can access the driver/connection and run methods on the native collection wrapper too:

```typescript
// @ts-ignore
const collection = (this.em as EntityManager<MongoDriver>).getConnection().getCollection(this.entityName);
await collection.findOneAndUpdate(where, updates, {upsert: true});
```

But looking at the code, `em` is defined as private - will fix that to protected so you can do this without the `@ts-ignore` hint.

**Comment by ramiel** [comment]
Perfect, thanks!

**Comment by B4nan** [comment]
`em` is now protected in v3.3.2

**Comment by ramiel** [comment]
Fast and cool, thanks!

**Comment by B4nan** [comment]
Can we close this now?

**Comment by ramiel** [comment]
Yes, sure, I'm closing it
