### ISSUE TITLE
Question: Help for writing query

### ISSUE THREAD

**Issue by osayfun** [mikro-orm/mikro-orm#368]
I want to find records matching `phone`, `code` and `date` greater than a exact time.
I'm trying this but VSCode says it's wrong.
```javascript
const validTime = Date.now() - 5 * 60 * 1000;
const record = await this.repo.findOne({
   $and: [{ code }, { phone }, { date: { $gte: validTime } }] });
```
How can I achieve this?

**Comment by B4nan** [comment]
What error do you get? I guess you should put there `Date` instance, if `date` property is of type `Date`. 

```typescript
const record = await this.repo.findOne({
   $and: [{ code }, { phone }, { date: { $gte: new Date(validTime) } }] });
```

Also to and things, you do not have to use $and here, this should also work:

```typescript
const record = await this.repo.findOne({ code, phone, date: { $gte: new Date(validTime) } });
```

**Comment by osayfun** [comment]
I first used that but I got the same error that I'm getting right now:
`
Type '{ code: number; date: { $gte: number; }; phone: number; }' is not assignable to type 'string'.
`

**Comment by osayfun** [comment]
I used `Date` type and it's working like a charm. Thank you so much!
