### ISSUE TITLE
Removing entities from collections removes the relation and sets it to null in the ChangeSet

### ISSUE THREAD

**Issue by Langstra** [mikro-orm/mikro-orm#3687]
**Describe the bug**
Removing entities from collections removes the relation and sets it to null in the ChangeSet. One of the use cases we have is that in a subscriber we check what entities were removed from collection and do something with that. However, since the relation is removed we do not know the related entity anymore. Before with v5.4.2 this relation was still available and could be used.

**To Reproduce**
1. Checkout PR https://github.com/mikro-orm/mikro-orm/pull/3686

**Versions**

| Dependency | Version |
| - | - |
| node | ? |
| typescript | ? |
| mikro-orm | 5.5.0 |
| your-driver | sqlite (but also on others) |

**Comment by B4nan** [comment]
This is a won't fix. Changes to relations are now propagated when you make them, not after flushing.

The question is what are you trying to do. You can access the values via `cs.originalEntity`.

**Comment by B4nan** [comment]
```
// this is where the change happens, before the flush is even called
project.users.remove(project.users.getItems()[0]);

// this is where flush events are executed
await orm.em.flush();
```

**Comment by B4nan** [comment]
Btw if this is about PKs as in the repro, you can also use `wrap(entity).getPrimaryKey()`, this will always prefer the values from `originalEntityData` - this is what is later used by the UoW to get the original PK when issuing the delete query.

**Comment by Langstra** [comment]
Oh I did not know that. I always used getItems() for this, but this seems much simpler. It is not about the PK in my use case, but I'll keep this in mind as well.

**Comment by Langstra** [comment]
I tried the `cs.originalEntity`, but that returned undefined. After that I looked through some of the docs and found `uow.getOriginalEntityData(entity)` and combined that with `cs.entity` to get to `uow.getOriginalEntityData(cs.entity)`.

I am not sure if this is how you expected it to work, but it does the job.

**Comment by B4nan** [comment]
> I tried the cs.originalEntity, but that returned undefined

That's weird, it should be the same as `wrap(cs.entity).__ originalEntityData`.
