### ISSUE TITLE
JIT Error when finding B entities where A-B is M:1 and A has an enum array field of empty array

### ISSUE THREAD

**Issue by ddadaal** [mikro-orm/mikro-orm#3694]
**Describe the bug**

MikroORM 5.5 throws the following error at the following situation.

1. there are two entities (say `User` and `UserAccount`)
2. `User` has a enum array property (say `enum1` of enum type `Enum1`)
3. `User` and `UserAccount` are of many-to-one relationship (a `User` might have multiple `UserAccount`)
4. an `User` entity instance has `enum1` set to an empty array `[]`
5. find `UserAccount` and populate `user` (`em.find(UserAccount, {}, { populate: ["user"]})`)

```
JIT runtime error: Cannot read properties of undefined (reading 'length')

  function(last, current) {
    const diff = {};
    if (current.id == null && last.id == null) {
  
    } else if ((current.id && last.id == null) || (current.id == null && last.id)) {
      diff.id = current.id;
    } else if (last.id !== current.id) {
      diff.id = current.id;
    }
  
    if (current.enum1 == null && last.enum1 == null) {
  
    } else if ((current.enum1 && last.enum1 == null) || (current.enum1 == null && last.enum1)) {
      diff.enum1 = current.enum1;
>   } else if (!compareArrays(last.enum1, current.enum1)) {
               ^
      diff.enum1 = current.enum1;
    }
  
    return diff;
  }
```

**To Reproduce**

Reproduction repo https://github.com/ddadaal/mikro-5.5-bug

**Expected behavior**

No error

**Additional context**

- 5.4.2 is free from this error. The problem might be introduced in 5.5
- No error if the enum array field is not empty

**Versions**

| Dependency | Version |
| - | - |
| node | 16.15.0 |
| typescript | 4.8.4 |
| mikro-orm | 5.5.0 |
| mysql | 5.5.0 |

**Comment by B4nan** [comment]
I am giving you special points for filling the versions table correctly :D

**Comment by ddadaal** [comment]
Oh the solution was fast! Thanks for the quick response and hard work!
