### ISSUE TITLE
Adding to collection overwrites the collection on mongodb

### ISSUE THREAD

**Issue by rubiin** [mikro-orm/mikro-orm#3705]
**Describe the bug**
On mongodb, doing `collection.add` overwrites the collection with new data instead of appending

**Stack trace**
```
...
```

**To Reproduce**
1. Create two entitities
2. Add a relationship (one-to-many)
3. Add to the collection. Then update the collection again with new data as `collection.add`

**Expected behavior**
Adding to an existing collection should append to the collection.But for mongodb, `collection.add` and `collection.set` behaves the same

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 18.12.0|
| typescript | 4.8.4 |
| mikro-orm | 5.5.1 |
| your-driver | mongodb |

**Comment by B4nan** [comment]
We already discussed this on slack, didn't we? You need to populate the collection first in mongo.

Please provide reproduction as code.
