### ISSUE TITLE
Infer primary key from relationship

### ISSUE THREAD

**Issue by pq987** [mikro-orm/mikro-orm#371]
Let's say I have the following entities:
`entities/Foo.ts`
```ts
import { Entity, PrimaryKey, OneToOne } from 'mikro-orm';
import Bar from './Bar';

@Entity()
export default class Foo {
  @PrimaryKey()
  id: string;
  @OneToOne(() => Bar)
  bar?: Bar;
  constructor(id: string) {
    this.id = id;
  }
}
```
`entities/Bar.ts`
```ts
import { Entity, PrimaryKey } from 'mikro-orm';

@Entity()
export default class Foo {
  @PrimaryKey()
  fooId: string;
  constructor(fooId: string) {
    this.fooId = fooId;
  }
}
```
And when using them it would be something along the liens of:
```ts
const foo = new Foo('a');
await db.orm.em.persistAndFlush(foo);
// somewhere later
const foundFoo = await db.orm.em.findOne(Foo, 'a');
if (foundFoo) foundFoo.bar = new Logs('a');
db.orm.em.flush();
```

I was wondering whether there would be a way to infer the `fooId` key since it will always be in a relationship with the Foo entity and is literally the pkey of Foo.. instead of having the pass the same key manually.

**Comment by B4nan** [comment]
This is not supported, and I am not planing to do so (at least not in near future), in fact it would not be a 1:1 relation - it sounds more like a joined table inheritance. Each entity has to have its own primary key.
