### ISSUE TITLE
CLI Error - cannot find driver package

### ISSUE THREAD

**Issue by Wiz1991** [mikro-orm/mikro-orm#3733]
**Describe the bug**
Running any mikro-orm cli command gives the same error

**Stack trace**
```
- configuration not found (Cannot find module '@mikro-orm/mysql'
Require stack:
- /home/wiz/.nvm/versions/node/v18.9.1/lib/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/utils/Configuration.js
- /home/wiz/.nvm/versions/node/v18.9.1/lib/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/utils/index.js
- /home/wiz/.nvm/versions/node/v18.9.1/lib/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/types/JsonType.js
- /home/wiz/.nvm/versions/node/v18.9.1/lib/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/utils/EntityComparator.js
- /home/wiz/.nvm/versions/node/v18.9.1/lib/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/typings.js
- /home/wiz/.nvm/versions/node/v18.9.1/lib/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/index.js
- /home/wiz/.nvm/versions/node/v18.9.1/lib/node_modules/@mikro-orm/cli/CLIHelper.js
- /home/wiz/.nvm/versions/node/v18.9.1/lib/node_modules/@mikro-orm/cli/cli.js)
...
```

**To Reproduce**
1. Clone [nestjs-realworld-example](https://github.com/mikro-orm/nestjs-realworld-example-app)
2. Setup
3. Run mikro-orm debug

**Expected behavior**
Commands should work, but debug breaks as does any other command with this same error

| Dependency | Version |
| - | - |
| node | 18.9.1 |
| typescript | 4.8.4 |
| mikro-orm | 5.5.3 |
| your-driver | postgresql / mysql |

**Comment by B4nan** [comment]
I am testing each release manually on that repo. No, this is not reproducible. 

Did you install the dependencies first?

**Comment by Wiz1991** [comment]
Yes, i did. It also complained about non matching versions of @mikro-orm/* packages
