### ISSUE TITLE
Wrong number type for MySQL

### ISSUE THREAD

**Issue by gquittet** [mikro-orm/mikro-orm#3739]
**Describe the bug**

I'm using the entity generator to get my database entities.

![image](https://user-images.githubusercontent.com/11082739/201735681-56bed229-4cdd-424c-ba00-7505bbba5caf.png)

TypeScript thinks the pk is a string, but in fact it is a number.

![image](https://user-images.githubusercontent.com/11082739/201735946-d90fc3b6-2bfe-4ff4-a152-ea1e7a5c8250.png)

![image](https://user-images.githubusercontent.com/11082739/201736048-c6c2b2d0-937a-4242-b0da-0f9aac25ed67.png)

![image](https://user-images.githubusercontent.com/11082739/201735955-e0a2649b-8f7f-48e9-9a21-9e16e99ee22a.png)

**Versions**

| Dependency | Version |
| - | - |
| node | 18.12.1 |
| typescript | 4.8.4 |
| mikro-orm | 5.5.3 |
| your-driver | mysql2 |

**Comment by B4nan** [comment]
> bigint can fit larger numbers than JavaScript number, for this reason it is mapped to a string. If we want to map it to a number anyway, we can implement [custom type](https://mikro-orm.io/docs/custom-types) that will do so. Similarly, we can define one to use the native bigint type:

https://mikro-orm.io/docs/using-bigint-pks/

**Comment by B4nan** [comment]
Oh wait a sec, I misread this, let me take a closer look

**Comment by B4nan** [comment]
Oh the other hand -- you haven't provided any details, just few screenshots. I dont even see the code you used to get the `assert` property, neither its type.

**Comment by gquittet** [comment]
My bad, I'm using:

```typescript
const asset = await em.findOne(Asset, { id })
```

**Comment by gquittet** [comment]
If I create one via `em.create` the type is correct but findOne and find returns wrong type.

**Comment by B4nan** [comment]
If you define the property as in the docs (with `type: t.bigint`), it will work, as that way the ORM type will ensure it's always a string. Apparently, mysql driver does not return it as a string unless needed - if you set a large enough value, it will return a string.

**Comment by gquittet** [comment]
I have generated the entities via MikroORM.

I haven't written them.

I think the generator should handle that.
