### ISSUE TITLE
Commit .yarn folder

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#3741]
The old 1.x yarn clients can auto-switch to v3 if `yarnPath: .yarn/releases/yarn-3.x.x.cjs` exists and is reference in .yarnrc.yml like so: 

```yarnPath: .yarn/releases/yarn-x.x.x.cjs```

**Comment by B4nan** [comment]
I don't want that. Use can use corepack instead of commiting the binary to every repository.

**Comment by B4nan** [comment]
(at least not now, lets see how things will work, but I really dont like the idea of a huge versioned binary, for git repository it's almost like a memory leak)
