### ISSUE TITLE
MongoDB indexes not created

### ISSUE THREAD

**Issue by ramiel** [mikro-orm/mikro-orm#375]
**Describe the bug**
I have this class 

```js
@Entity()
export class User extends Base {
  @Property()
  @Unique()
  email!: string;
}
```

and the Base class is 
```js
@Entity()
export default abstract class Base implements MongoEntity<Base> {
  @PrimaryKey()
  _id!: ObjectId;

  @SerializedPrimaryKey()
  id!: string;

  @Property()
  createdAt: Date = new Date();

  @Property({ onUpdate: () => new Date() })
  updatedAt: Date = new Date();

}
```

The unique index on email is not created. This also if I remove the inheritance and define everything in the User class, only the index on the _id is created. What am I doing wrong?

**Versions**
3.3.3

| Dependency | Version |
| - | - |
| node | 12 |
| typescript | 3.8.2 |
| mikro-orm | 3.3.3 |
| mongodb | 3.5.3 |

**Comment by ramiel** [comment]
Something I tried was to remove the collection, remove the temp folder with metadata and run everything again. No index has been created while being specified in metadata: Here the metadata:

```json
{
  "data": {
    "className": "User",
    "properties": {
      "email": {
        "name": "email",
        "reference": "scalar",
        "getter": false,
        "setter": false,
        "type": "string"
      }
    },
    "hooks": {},
    "indexes": [],
    "uniques": [
      {
        "properties": "email"
      }
    ],
    "path": "./src/models/User.ts",
    "name": "User",
    "constructorParams": [],
    "toJsonParams": [],
    "extends": "Base",
    "useCache": true,
    "collection": "user"
  },
  "origin": "./src/models/User.ts",
  "hash": "669cd636347199fc6de2f86355df3247"
}

```

**Comment by ttsirkia** [comment]
Check this issue: https://github.com/mikro-orm/mikro-orm/issues/159

**Comment by ramiel** [comment]
Sorry for duplication. I already saw that issue and I thought that it was already done because the related PR is closed. Of course the issue is till open so it still applies. It would be good if documentation describe precisely that indexes don't work with MongoDB.

**Comment by B4nan** [comment]
The PR was closed, not merged. Also it was about sql support only (although wrongly tagged to fix that mongo issue). 

Closing as duplicate, please subscribe to the other issue.
