### ISSUE TITLE
Iterating through an uninitialized collection should throw an error

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#3750]
**Is your feature request related to a problem? Please describe.**
I have run into a few instances where I've had business logic failures because of not being aware that I was iterating through a collection that had not been fetched. understandably this may be a breaking change to save for v6 (perhaps in v5 we make it a flag that is passed down to collections)

```typescript
const collection: Collection<Entity>;

// throws
collection.getItems();

// does not throw
collection[0];

// does not throw
Array.from(collection)[0];
```

**Comment by B4nan** [comment]
Implemented in v6 via 1260e588ac74521ef565f0271354ca0e1efe566d
