### ISSUE TITLE
Reference.load() should return Loaded<> when populating

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#3755]
**Is your feature request related to a problem? Please describe.**
When calling `reference.load()`, the return type is `Promise<T>` instead of `Promise<Loaded<T,P>>`

**Describe the solution you'd like**
Add more overloads to the load type

**Comment by B4nan** [comment]
And looks like with the changes I made in #4012 we can also resolve this, I just need to drop the function overload.
