### ISSUE TITLE
JsonType field returning string instead of parsed object in subscriber

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#3757]
See PR reproduction

**Comment by B4nan** [comment]
`ChangeSet.originaEntity` is a DTO/POJO, not entity instance, you get the serialized values, so the values returned by `Type.convertToDatabaseValue`, which for JSON can be a string (depends on the driver, they work differently when it comes to JSON properties).

Works as expected.

**Comment by B4nan** [comment]
I'd rather not do that. Maybe we could think about how to have the runtime value there instead of the (not so stable and sometimes even driver-specific) database value. As for scalar properties, it might be just fine to use that instead of the database one.
