### ISSUE TITLE
Bi-directional Loaded<> when accessing child via parent

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#3759]
**Is your feature request related to a problem? Please describe.**

Given a standard parent/child relationship:

```typescript
class Parent {
  @OneToMany(() => Child, (c) => c.parent)
  children = new Collection<Child>(this);
}

class Child {
  @ManyToOne(() => Parent, { inversedBy: 'children })
  parent!: IdentifiedReference<Parent>;
}
```

When pre-loading the child into the parent, even though behind the scenes, the `parent` property of child will indeed have a loaded reference, the type system does not know that.

```typescript
// parent = Loaded<Parent, 'child'>
const parent = await em.findOne(Parent, {}, {populate: ['children']});

// error
parent.child.get().parent.get()
```

**Describe the solution you'd like**
Understandably we can end up with some compiler recursion with a bad implementation, but I wonder if there is a way to maybe  have `Loaded` or some new type track its "populated ancestry"? There are probably too many holes that can be poked in this idea that may break it.

**Comment by B4nan** [comment]
I don't know how that would work, there is no information about the type of relation, whether it's bidirectional and what is its inverse - that is all runtime-only information, it would have to be provided by the user (so doing it twice, I dont see how we could infer things one way or the other).
