### ISSUE TITLE
seeder pathTs option not read

### ISSUE THREAD

**Issue by iam-robi** [mikro-orm/mikro-orm#3776]
**Describe the bug**
Seeder configuration pathTs , combined with path create file in wrong path : File NewSeeder generated at dist/src/seeders/NewSeeder.ts

**Configuration**
```
    seeder: {
        defaultSeeder: 'DatabaseSeeder',
        path: 'dist/src/seeders',
        pathTs: 'src/seeders'
    },
...
```

**To Reproduce**
1. set up nest with mikroorm 
2. configure seeder path: 'dist/src/seeders'  & pathTs: 'src/seeders'
3. run npx mikro-orm seeder:create NewSeeder

**Expected behavior**
File NewSeeder generated at src/seeders/NewSeeder.ts copying the behaviour of migrations module.

When changing the "path" parameter the output path change so path argumented is correctly updated and it seems it's the only one read. 

Trying to run the generated file from the ouput path will result in error : 
`SyntaxError: Cannot use import statement outside a module`

| Dependency | Version |
| - | - |
| node | 18.6.0 |
| typescript | 4.8.4|
| mikro-orm | 5.5.3 |
| postgresql | 5.5.3 |
| nest-js | 9.1. |

**Comment by B4nan** [comment]
Not reproducible, my guess is you don't have `ts-node` installed, as that is required for the TS paths to be taken into account.

Here you can see the `pathTs` is used for the `absolutePath` which drivers where things are both read and generated.

https://github.com/mikro-orm/mikro-orm/blob/f95a250c86cb56815f1f3829e4bf81a562b83810/packages/seeder/src/SeedManager.ts#L17-L18
