### ISSUE TITLE
Query Builder generates incorrect query compared to v5.4.2

### ISSUE THREAD

**Issue by RedMickey** [mikro-orm/mikro-orm#3778]
**Describe the bug**
After updating mikro-orm from v5.4.2 to v5.5.3 I faced a problem that, it seems, the query generation algorithm has been changed in the query builder, that leads to constructing incorrect SQL query in case the `limit` parameter is used. I prepared a comparison table below:
|Version|Query Builder config|SQL query|
|---|---|---|
|5.4.2| entityManager.createQueryBuilder(MEntity, 'm')<br>.select(['m.*'])<br>.where({active: true})<br>.join('sEntities', 's')<br>.groupBy(['m.id'])<br>.orderBy({order: 'ASC', ['COUNT(s.id)']: 'DESC', name: 'ASC'})<br>.limit(10)<br>.offset(0)|select "m".* from "m_entity" as "m" inner join "s_entity" as "s" on "m"."id" = "s"."m_entity_id" where "m"."active" = true group by "m"."id" order by "m"."ordr" asc, COUNT(s.id) desc, "m"."name" asc limit 10|
|5.5.3|entityManager.createQueryBuilder(MEntity, 'm')<br>.select(['m.*'])<br>.where({active: true})<br>.join('sEntities', 's')<br>.groupBy(['m.id'])<br>.orderBy({order: 'ASC', ['COUNT(s.id)']: 'DESC', name: 'ASC'})<br>.limit(10)<br>.offset(0)|select "m".* from "m_entity" as "m" inner join "s_entity" as "s" on "m"."id" = "s"."m_entity_id" where "m"."id" in (select "m"."id" from (select "m"."id" from "m_entity" as "m" inner join "s_entity" as "s" on "m"."id" = "s"."m_entity_id" where "m"."active" = true group by "m"."id" order by min("m"."ordr") asc, min(COUNT(s.id)) desc, min("m"."name") asc limit 10) as "m") group by "m"."id" order by "m"."ordr" asc, COUNT(s.id) desc, "m"."name" asc|
|5.5.3|entityManager.createQueryBuilder(MEntity, 'm')<br>.select(['m.*'])<br>.where({active: true})<br>.join('sEntities', 's')<br>.groupBy(['m.id'])<br>.orderBy({order: 'ASC', ['COUNT(s.id)']: 'DESC', name: 'ASC'})<br>.offset(0)|select "m".* from "m_entity" as "m" inner join "s_entity" as "s" on "m"."id" = "s"."m_entity_id" where "m"."active" = true group by "m"."id" order by "m"."ordr" asc, COUNT(s.id) desc, "m"."name" asc|

**Stack trace**
```
[Nest] 122  - 11/21/2022, 10:39:08 AM   ERROR [ExceptionsHandler] 
            select "m".* from "m_entity" as "m" inner join "s_entity" as "s" on "m"."id" = "s"."m_entity_id" where "m"."id" in (select "m"."id" from (select "m"."id" from "m_entity" as "m" inner join "s_entity" as "s" on "m"."id" = "s"."m_entity_id" where "m"."active" = true group by "m"."id" order by min("m"."ordr") asc, min(COUNT(s.id)) desc, min("m"."name") asc limit 10) as "m") group by "m"."id" order by "m"."ordr" asc, COUNT(s.id) desc, "m"."name" asc
         - aggregate function calls cannot be nested
error: 
            select "m".* from "m_entity" as "m" inner join "s_entity" as "s" on "m"."id" = "s"."m_entity_id" where "m"."id" in (select "m"."id" from (select "m"."id" from "m_entity" as "m" inner join "s_entity" as "s" on "m"."id" = "s"."m_entity_id" where "m"."active" = true group by "m"."id" order by min("m"."ordr") asc, min(COUNT(s.id)) desc, min("m"."name") asc limit 10) as "m") group by "m"."id" order by "m"."ordr" asc, COUNT(s.id) desc, "m"."name" asc
         - aggregate function calls cannot be nested
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
```

**To Reproduce**
1. Create the following entities:
```
@Entity({tableName: `m_entity`})
export class MEntity extends BaseEntity<any, any> {
    @PrimaryKey({type: 'string'})
    id = uuid();

    @Property({fieldName: 'name', unique: true, type: 'string'})
    name!: string;

    @Property({fieldName: 'ordr', type: 'integer'})
    order = 1000;

    @Property({type: 'boolean'})
    active!: boolean;

    @OneToMany({entity: () => SEntity, mappedBy: (sEntity) => sEntity.mEntity, persist: false})
    sEntities = new Collection<SEntity>(this);
}

@Entity({tableName: `s_entity`})
export class SEntity extends BaseEntity<any, any> {
    @PrimaryKey()
    id: string = uuid();

    @Property({fieldName: 'name'})
    name!: string;

    @ManyToOne({entity: () => MEntity, inversedBy: 'sEntities', fieldName: 'm_entity_id', persist: false, nullable: true})
    mEntity?: MEntity;
}
```
2. Try to use query builders described in the comparison table.

**Expected behavior**
I'd like the Query Builder to generate the correct SQL query as the previous version 5.4.2

**Versions**

| Dependency | Version |
| - | - |
| node | 18.9 |
| typescript | 4.7.4 |
| mikro-orm | 5.5.3 |
| your-driver | postgres |

**Comment by ml1nk** [comment]
In mikro-orm 5.0.5 there was this change:
~~~
query-builder: use paginate flag automatically based on to-many joins ([db9963f](https://github.com/mikro-orm/mikro-orm/commit/db9963fff8ceb980354b328f2d59353b9177aef3)), closes https://github.com/mikro-orm/mikro-orm/issues/2823
~~~
which normally helps to get the correct count when using joins with pagination.

Does it work like before if you disable it with:
.setFlag(QueryFlag.DISABLE_PAGINATE)

**Comment by ml1nk** [comment]
Just found issue #3770 with a better explanation.

**Comment by RedMickey** [comment]
> In mikro-orm 5.0.5 there was this change:
> 
> ```
> query-builder: use paginate flag automatically based on to-many joins ([db9963f](https://github.com/mikro-orm/mikro-orm/commit/db9963fff8ceb980354b328f2d59353b9177aef3)), closes https://github.com/mikro-orm/mikro-orm/issues/2823
> ```
> 
> which normally helps to get the correct count when using joins with pagination.
> 
> Does it work like before if you disable it with:
> 
> ```ts
> .setFlag(QueryFlag.DISABLE_PAGINATE)
> ```

Yes, it does. With this parameter, the query works as before. Thanks a lot for your reply. I'm closing the issue.
