### ISSUE TITLE
docs: contribution docs enhancement 

### ISSUE THREAD

**Issue by erie0210** [mikro-orm/mikro-orm#3793]
Hello, as I try to install dependencies in mikro-orm, I found it using yarn3 but gitignored .yarn([related lines](https://github.com/mikro-orm/mikro-orm/blob/e9a9aa617bf054a7f0c477aed6c2a67f44481b88/.gitignore#L17)). As yarn3 uses yarn cache for zero-installation policy and it provide the options with selective ignore, (for example `.yarn/cache`), I want to know why mikro orm gitignores `.yarn`

In addition, it would be nice to have written forms  about installing with yarn3 in CONTRIBUTING.md 🙂
As current stable yarn version is 1.22.19, it is possible for many to confront this error.

This is the error I met:
```
error @mikro-orm/root@5.0.0: The engine "yarn" is incompatible with this module. Expected version ">=3.2.0". Got "1.22.19"
```

**Comment by B4nan** [comment]
> I want to know why mikro orm gitignores .yarn

Because I don't want to version yarn in the repository, it would only grow the repository size with each yarn upgrade. I will adjust the contributing guide, all you need to do is to enable corepack support.

> As current stable yarn version is 1.22.19

Nope, current stable yarn is v3
