### ISSUE TITLE
support specifying "parser" of full text index for MySQL in schema generator

### ISSUE THREAD

**Issue by ghostoy** [mikro-orm/mikro-orm#3800]
**Is your feature request related to a problem? Please describe.**
MySQL full text index supports a "parser" option, which is usefully for indexing CJK text. Currently there is no way to specify this option when creating indexes with CLI schema generator.

**Describe the solution you'd like**
A "parser" option could be provided as part of `options` in `@Index` decorator.
```typescript
@Property()
@Index({ type: 'fulltext', options: { parser: 'ngram' } })
searchableField: string;
```
should generate following SQL.
```sql
alter table tableName add fulltext index `searchable_field_index`(`searchable_field`) with parser ngram;
```
**Describe alternatives you've considered**
Use migrations.

**Additional context**

**Comment by B4nan** [comment]
You can use index expressions to create any kind of index, as you can specify the full create index query yourself.

https://mikro-orm.io/docs/defining-entities#indexes
