### ISSUE TITLE
index.mjs is missing in current dev builds

### ISSUE THREAD

**Issue by ml1nk** [mikro-orm/mikro-orm#3808]
**Describe the bug**
The index.mjs which should be found in every package is missing in the latest dev builds. 

![image](https://user-images.githubusercontent.com/4943440/205083015-e8e583a7-56fb-4e09-93b4-706dcf5bb126.png)

**Versions**

| Dependency | Version |
| - | - |
| mikro-orm | 5.5.4-dev.25 |

**Comment by B4nan** [comment]
Weird, dev.8 is the first version without it, thanks for the note.
