### ISSUE TITLE
Don't default to a timestamp with precision for Postgresql (or at least allow turning off behavior)

### ISSUE THREAD

**Issue by yeedle** [mikro-orm/mikro-orm#3824]
**Is your feature request related to a problem? Please describe.**

When declaring a Date column, mikro-orm generates a `timestamptz(0)` for postgresql. [This is wrong](https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_timestamp.280.29_or_timestamptz.280.29) and should not be the default. What's worse, there is no way to explicitly set this to `null`. In `@Property`, `length` can't be set to `null`, and if  `undefined` is passed in, it gets interpreted as 0.

**Describe the solution you'd like**
The default should be `timestamptz` without any precision. Only set a precision if the user passes in a `length` to column properties.

**Describe alternatives you've considered**
If there's some alternative opinions and folks feel that `timestamptz(0)` is an acceptable default, at the very least, setting `length` to `null` should be possible, and should result in a generated type of `timestamptz`. Always forcing the use of a precision seems to incorrect regardless of what the default is.

**Additional context**
I can submit a PR to implement the above. I'd switch the logic in https://github.com/mikro-orm/mikro-orm/blob/master/packages/postgresql/src/PostgreSqlPlatform.ts#L40 to the reverse (only set the precision if `length` is not null), and would change the logic [here](https://github.com/mikro-orm/mikro-orm/blob/d4ac6385aa84208732f144e6bd9f68e8cf5c6697/packages/core/src/types/DateTimeType.ts#L8) to to not default to 0 if platform == postgresql.

**Comment by B4nan** [comment]
>  What's worse, there is no way to explicitly set this to null. 

You can use `columnType` to override anything, it is always used as is (so `length` is not taken into account).

```ts
@Property({ columnType: 'timestamptz' })
date: Date;
```

Changing this is imho quite breaking, but v6 development already started, so we can do it there.

**Comment by yeedle** [comment]
Oh, `columnType` works. thanks!

Do you want me to submit a PR against he v6 branch?

**Comment by B4nan** [comment]
Sure, PR welcome

**Comment by B4nan** [comment]
Closed via #3832
