### ISSUE TITLE
New migrations are generated if one adds a constraint expression written in lowercase without using parentheses

### ISSUE THREAD

**Issue by JasonRammoray** [mikro-orm/mikro-orm#3827]
**Describe the bug**
If one adds a constraint using [Check](https://mikro-orm.io/docs/defining-entities#check-constraints) decorator and provides a simple expression, like logical one, and written in lowercase without using parentheses, then `migration:create` will continue generating the same migration even after `migration:up` has been applied.
The subsequent migration, however, is not generated if one uses uppercase for `sql` keywords (for example, `IS NOT NULL`, `OR`).

**Stack trace**
None

**To Reproduce**
1. Create an entity with two nullable fields
2. Create a constraint for that entity as:
```typescript
@Check<EntityTypeHere>({
  expression: columns => `${column.<firstColumnNameHere>} is not null or ${column.<secondColumnNameHere>} is not null`,
  name: '<some_name_here>'
})
```
3. Generate a migration
4. Migrate to that migration
5. Try generating a migration one more time

**Expected behavior**
No second migration should be created given there were no changes to the entity model.

**Observations**
It appears if one wraps every expression in parentheses and writes `sql` keywords in caps, then the issue isn't reproducible.
E.g:
```typescript
@Check<EntityTypeHere>({
  expression: columns => `(${column.<firstColumnNameHere>} IS NOT NULL) OR (${column.<secondColumnNameHere>} IS NOT NULL)`,
  name: '<some_name_here>',
})
```

**Versions**

| Dependency | Version |
| - | - |
| node | 16.16.0 |
| typescript | 4.8.4 |
| mikro-orm | 5.5.3 |
| your-driver | postgresql (5.5.3) |

**Comment by B4nan** [comment]
Interesting, I guess postgres normalizes the query and store that instead of the expression provided by you. Will try to find some way to get around this, worst case we could compare the expression as lower case and ignore parens, could be good enough heuristic about what changed.
