### ISSUE TITLE
A column of type Date is unintentionally updated

### ISSUE THREAD

**Issue by Me1e** [mikro-orm/mikro-orm#3847]
**Describe the bug**
Even if the entity object is not modified, it seems to be updated because it is always judged to be different in dealing with the date.

**To Reproduce**
1. Create a table with Date type columns in mariadb
2. Just get that entity (don't modify)
3. When flushing, the column of the Date type of the unmodified entity is recognized as changed, resulting in an update query

**Expected behavior**
It was solved by changing the date type column to string, but it is not the solution i want

**Versions**

| Dependency | Version |
| - | - |
| node | 18-alpine |
| typescript | ^4.8.4 |
| mikro-orm | 5.5.3 |
| your-driver | "@mikro-orm/core": "^5.5.3",    "@mikro-orm/mariadb": "^5.5.3",    "@mikro-orm/migrations": "^5.5.3",    "@mikro-orm/nestjs": "^5.1.2",    "@mikro-orm/reflection": "^5.5.3", |

**Comment by B4nan** [comment]
What about providing some actual reproduction? How does your entity look like? How does your ORM config look like? Why didnt you first try upgrading to latest version? So many questions... :]

**Comment by B4nan** [comment]
I can tell you right ahead this is not reproducible without additional information. There are tests for this. Let's reopen with a failing repro, here is my take:

```ts
import { Entity, PrimaryKey, Property } from '@mikro-orm/core';
import { MikroORM } from '@mikro-orm/mariadb';
import { mockLogger } from '../helpers';

@Entity()
export class Test {

  @PrimaryKey()
  id!: number;

  @Property()
  name!: string;

  @Property()
  born!: Date;

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    dbName: `mikro_orm_test_3847`,
    port: 3309,
    entities: [Test],
  });
  await orm.schema.refreshDatabase();
});

afterAll(async () => {
  await orm.close(true);
});

test(`3847`, async () => {
  const r = await orm.em.nativeInsert(Test, { name: 'n', born: new Date() });
  const t = await orm.em.findOneOrFail(Test, r);
  const mock = mockLogger(orm);
  await orm.em.flush();
  expect(mock.mock.calls).toEqual([]);
});
```
