### ISSUE TITLE
Insert with select subquery

### ISSUE THREAD

**Issue by jvdberg08** [mikro-orm/mikro-orm#3849]
**Is your feature request related to a problem? Please describe.**
I'm trying to insert an entity with one column having a subquery `(select max(column) from table where foreign_key=some_id) + 1`. As far as I could see this is not currently possible, the only way to do this currently is by using the `defaultRaw` property config option, which does not allow a where clause with a dynamic value.

**Describe the solution you'd like**
Changing `defaultRaw` to allow a function which gets called with the entity as a paramer would probably work fine. Maybe allowing a QueryBuilder instance as return value would be nice too to prevent raw sql when not needed

**Describe alternatives you've considered**
Using the QueryBuilder to insert instead of the usual `em.create()` `em.persistAndFlush()`. This gets ugly quick though as you're basically rewriting a lot of functionality already in the ORM.

**Additional context**
N/A

If this is already possible, please let me know!
If not, I'd be happy to try and make a PR myself if needed.

**Comment by B4nan** [comment]
> Changing defaultRaw to allow a function which gets called with the entity as a paramer would probably work fine. Maybe allowing a QueryBuilder instance as return value would be nice too to prevent raw sql when not needed

I am not sure what you mean by that. Can you provide some examples around it? 

Note that `defaultRaw` needs to be a string, it can't be anything dynamic, it is literally what gets used in the database schema as the column default -> it needs to be an SQL fragment. And I doubt you can use subqueries in schema definition, although I might be wrong.

Note there is `onCreate` property option which might be something similar to what you want.

**Comment by jvdberg08** [comment]
It seems I have made some incorrect assumptions about `defaultRaw`. I assumed it was a sql statement that was used as a default for inserts when the column/property had no value provided, instead of a default in schema definition.

`onCreate` would not work due to concurrency issues I'm afraid.

What I'm trying to do, is get this query working without using the `QueryBuilder`, as I'd like to avoid it when possible.
```sql
INSERT INTO table (col1, col2, anumbercol, aforeignkeycol) 
VALUES ("X", "Y", (SELECT MAX(anumbercol) FROM table WHERE aforeignkeycol = 12345 FOR UPDATE) + 1)
```

This will lock records and execute queries in proper order, and won't result in duplicate `anumbercol` values even when executing 30+ queries at the same  time.

So some possible solutions I can think of:
- `@Formula` but for inserts instead of selects?
- Support for triggers. I have not tested if this will work regarding the concurrency issues with this query though.
- Or just allowing raw sql inside of `em.create()`, but this might be an ugly solution

Let me know if you need any further context!

**Comment by B4nan** [comment]
I would say this is quite an edge case and you should use QB here. Also making multiple queries in one transaction with explicit isolation level set might work, I dont think you need a subquery at all.

**Comment by jvdberg08** [comment]
You were right, a transaction with `LockMode.PESSIMISTIC_WRITE` worked fine. I thought I had tried this before but probably forgot the lockmode or something, thanks for your time!
