### ISSUE TITLE
Support soft delete

### ISSUE THREAD

**Issue by seunggu** [mikro-orm/mikro-orm#385]
Is soft delete feature available?
If is not supported
is there plan for this feature?

**Comment by B4nan** [comment]
Not natively supported, but planned (not sure yet if as an extension or directly integrated). What I would like to support in the core are filters (although with simpler API): https://docs.jboss.org/hibernate/orm/3.6/reference/en-US/html/filters.html
That would allow to create a default filter where you would ignore soft deleted entities, then one could implement custom `softRemove()` method on the repository or even on the entity, as it is enough to set the deletedAt on the entity (synchronous) and flush. I will definitely add a section to docs how to achieve this once filters are available, but currently I am not planning that in near future.

For now, you could create custom repository methods to handle this, you could reimplement `find()`, `findOne` and `remove` methods.

**Comment by seunggu** [comment]
Thank you for your reply.

I understand what you say.
that`s good.

If you do not mind, can i know the time planned?

**Comment by B4nan** [comment]
Hard to tell, I do not have any dedicated time for this, it's a free time project. For near future (lets say following 3 months) I would like to add support for mongo transactions, mongo migrations and mongo indexes, composite keys, and maybe seeds. Then (or maybe sooner) I will drop support for node <10 and TS <3.7. 

I do not want to release v4 with just BC breaks, so this (the filters) could be part of it, but when it comes is something I can't promise. It is also highly dependent on number of issues created/bugs found, as I always try to fix broken things before introducing more features.

**Comment by seunggu** [comment]
okay, thank you.

**Comment by nkovacic** [comment]
Scope/global filter support is a great feature for multi tenant apps also. It would be great if this feature would made it to v4.

**Comment by B4nan** [comment]
After giving this first few hours I feel quite confident that it will make it to v4 :] Here are some examples of the API I am working on:

```typescript
@Entity()
@Filter({ name: 'expensive', cond: { price: { $gt: 1000 } } })
@Filter({ name: 'long', cond: { 'length(text)': { $gt: 10000 } } })
@Filter({ name: 'hasAuthor', cond: { author: { $ne: null } }, default: true })
@Filter({ name: 'writtenBy', cond: args => ({ author: { name: args.name } }) })
export class Book {
  ...
}

const books1 = await orm.em.find(Book, {}, {
  filters: ['long', 'expensive'],
});
const books2 = await orm.em.find(Book, {}, {
  filters: { hasAuthor: false, long: true, writtenBy: { name: 'God' } },
});
```

**Comment by nkovacic** [comment]
That looks great, but also if something on orm to conditionally register filters depending on the entity (maybe similar to [Entity Framework](https://docs.microsoft.com/en-us/ef/core/querying/filters))

**Comment by B4nan** [comment]
> to conditionally register filters depending on the entity

Not sure I follow, can you craft an example for this? (looked at the link but I was not sure what I am looking for) How could that work conditionally, you need to apply filters before you get the entity (they are about augmenting the conditions).

**Comment by merceyz** [comment]
It would be really nice if the `@Filter` decorator took an async function, that would allow me to implement ACL logic directly on the entities, would use the `domain` module to get the request context so nothing special needed from the ORM there.

**Comment by B4nan** [comment]
We have the right EM instance when applying the filters so not even needed to use request context here. 

So how would it look like? you would have EM instance in the arguments, and return true/false to conditionally enable the filter? But based on what? Again, there is no entity instance at that time.

**Comment by merceyz** [comment]
For getting data my initial thought was something like this:
```ts
@Entity()
@Filter(async () => {
  const userIds = await someACL('users', 'get', domain.active.userId);

  return {
    id: { $in: userIds },
  };
})
export class User {
  @PrimaryKey()
  id: number;

  @Property()
  username?: string;
}
```
It would be nice if it could be done for update and delete as well, so the function is passed what type of action it is (find, update, delete) and then could apply the filter based on that, could potentially return true/false for update and delete to either allow or disallow.

**Comment by B4nan** [comment]
In general I don't really like the idea of making any db calls here (but that is up the user, I am fine with having async callback for this). 

Filters are already parametric - in my example see the `writtenBy` filter. But you need to set the parameter when making the call explicitly. So exposing the EM instance as part of `args` and allowing the callback to be async would work for you, right? 

I am planning to have filters working also for `nativeUpdate` and `nativeDelete` methods too, but not sure if we really need a way to know what type of query are we filtering on. Yes, from the ACL perspective it makes sense, but I am still not very convinced this is the right use case for filters. But again, technically not a problem to expose something in the `args` to tell you what type of query it is. 

Still MikroORM is about change set tracking, you should prefer to use UoW to make changes, and there you don't have filters for update/delete (they are applied only for reading, not flushing).

**Comment by nkovacic** [comment]
> > to conditionally register filters depending on the entity
> 
> Not sure I follow, can you craft an example for this? (looked at the link but I was not sure what I am looking for) How could that work conditionally, you need to apply filters before you get the entity (they are about augmenting the conditions).

Just want to solve the multi tenancy issue where every entity has an tenantId and we want to to always query with tenant filter automatically applied. Example: const res = await orm.em.find(Book) wound only return books that have the same tenantId that we get from cookie or jwt token.

**Comment by B4nan** [comment]
For multi tenancy it would be probably good to have some global filters, that would not be bound to just one entity, and it would be possible to set a filter parameter on the EM level. I was planning to add similar api for entity bound filters anyway. Something like this:

```typescript
// define
em.addFilter(Book, 'writtenBy', args => ({ author: args.id })); // bound to entity, disabled by default
em.addGlobalFilter('tenant', args => {}, true); // global, enabled by default, conditionally 

...

// set params
em.setFilterParams(Book, 'writtenBy', { id: 321 }); // setting entity filter params
em.setGlobalFilterParams('tenant', { tenantId: 123 }); // setting global filter params

...

// usage
em.find(Book, {}); // same as `{ tenantId: 123 }`
em.find(Book, {}, { filters: ['writtenBy'] }); // same as `{ author: 321, tenantId: 123 }`
em.find(Book, {}, { filters: { tenant: false } }); // disabled tenant filter, so truly `{}`
```

Global filters could be also defined via ORM configuration.

**Comment by merceyz** [comment]
> So exposing the EM instance as part of args and allowing the callback to be async would work for you, right?

I don't even need the EM instance, just async callbacks are fine

**Comment by nkovacic** [comment]
> ```ts
> em.addGlobalFilter('tenant', args => {}, true);
> ```

Exactly something like you proposed. Would be only great if in `em.addGlobalFilter('tenant', args => {}, true);`  args would return entity type so there would be a possibility to disable filter if entity does not have tenantId or some other condition.

**Comment by B4nan** [comment]
Yeah sure, we can have entity name in the `args`. 

One more general question - do you guys think it is ok/enough to apply filters only on the root entity? 

```typescript
// should we apply filters only to Book (root entity), or also to all the joined entities, like Author here
em.find(Book, { author: { name: ... } });

// and here, do we want to apply (default) filters on Book entity?
em.find(Author, {}, { populate: ['books'] });
```

**Comment by nkovacic** [comment]
Global filters should be applied to populated properties, atleast in Entity Framework global filters work in that way. Currently in Node.js land no ORM supports this feature, so you have to look to other languages and ORMs for guidelines.

**Comment by B4nan** [comment]
So you would say yes for both examples (auto-join and populate)? And do you think we should distinguish between entity bound and global types in this regard? Currently have it implemented with common logic, if the filter is enabled (either explicitly, or by default), it will be applied regardless of the type (entity bound/global/dynamic).

It makes sense for the populate for sure, I am just not sure about the auto-join. But as population can now happen via joins too, it probably makes sense to have this consistent. 

Btw I ended up with this API:

```typescript
em.addFilter('acl', args => ({ tenant: args.tenant }), [Author, Book]); // last param is optional, when omitted, the filter is enabled for all entities
em.setFilterParams('acl', { tenant: 123 });
```

The `cond` callback can be async, and the `args` are only what is provided in the `setFilterParams()` or in the `FindOptions`.

**Comment by B4nan** [comment]
Feel free to take a look at the initial implementation in #663, will be happy to hear any feedback. Still lots of missing test cases (no tests for global filters), no filters in joined entities, also no integration in nativeUpdate/Delete. I hope I will be able to finalize this tomorrow and ship it in the next alpha in the end of the weekend.

**Comment by B4nan** [comment]
Closing as filters are now implemented, will be part of alpha 6. 

https://github.com/mikro-orm/mikro-orm/blob/dev/docs/docs/filters.md

**Comment by cyrilchapon** [comment]
As of my experience, the hardest stuff about soft-deletion is the use of unique indexes.
At application-level, filtering is indeed the way to go; whatever the technological strategy to accomplish this.
(Sequelize, for example, adds a `AND deleted_at IS NULL OR deleted_at > now()` to each queries; and changes the behavior of `.remove()` on instances.

BUT, one should be aware there are some cryptic questions mainly regarding physical database behind the scene...

Put simple, when one accomplish "soft-delete", it changes the definition of a "deleted" row in database. As a consequence, the contraposed is it also changes **the definition of an "existing" row**

This implies dramatical adaptations, most notably around **unique indexes** (which make an extensive use of this "existing row" concept).

-----

A practical example (pseudo code and SQL for convenience) :

Imagine a table users
```
users {
  // PK
  id: int, primary key, autoincrement

  // Unique field
  email: string, unique index

  // Soft delete column
  deleted_at: date
}
```

Now some operations
```
// Create a user
INSERT INTO users (DEFAULT, 'foo@bar.com', NULL)
> 1, foo@bar.com, NULL

// "Soft-delete" the user
UPDATE users SET deleted_at = now() WHERE id = 1
> 1, foo@bar.com, 2020-09-24

INSERT INTO users (DEFAULT, 'foo@bar.com', NULL)
> Error : unique index email
```

In this simple case; we naively setup a unique index on email as usual.
(this seems stupid first; but this could result of the usage of `import {Unique} from 'mikro-orm'` for example)

You can re-read this 3 lines, and convince yourself this could be the SQL counterpart of simple ORM functions usage.
Respectively, `.create()`, `.softDelete()`, `.create()` or something like this

Now how to solve this ? Two Answers :
- More complex indexes. Notably compound ones. At first this could seem like a good idea :
  ```
  UNIQUE(email, deleted_at)
  ```
This allows multiple-deleted values at the same time; but only one non-deleted
- Conditonal indexes. Postgres for example supports it
  ```
  UNIQUE(email) WHERE deleted_at IS NULL
  ```

------

Now a more complicated question : how should it behave when "resurrecting" a deleted user, if one already took it's place in the unique index ?

**Comment by cyrilchapon** [comment]
IMHO, the perfect ORM should abstract this.

I'm using extensively Sequelize in several projects; and it doesn't.
As a consequence; it's concept of "simple `unique`" indexes (similar to the decorator in MikroORM) is basically **incompatible** with it's `paranoid` (soft-deletion) option. Furthermore; this is writen nowhere in the documentation.

When setting up "filter" in mikroOrm to achieve soft-deletion as suggested above; we are essentially re-creating the exact same situation.

This is harsh. I am personaly managing that with very complex indexes (that, TBH, not many developers understand in teams)

**Comment by B4nan** [comment]
Personally I would say the second insert query should "resurrect" the entity, so simple unique index is enough. But this depends on the business logic/requirements.

Btw you can use `@Unique()` to create compound indexes, just put it at the entity level and specify list of `properties`.

**Comment by lightning003** [comment]
@B4nan ... Bit confused how to achieve soft delete with relations. Had a question about soft-deleting orphans with orphanDelete. Is it possible to achieve this behavior directly or need to add custom repository and modify remove method for child entities?

**Comment by B4nan** [comment]
I am not sure what you are asking, better to open new issue (or a discussion if it's just question), with proper description and some code snippets. 

If I get it right, the answer is no - orpah removal is here to enforce we do not have any orpahns in the database - so entities that would point to something already deleted. It means actual removal of entity. And filters will never affect how the regular removal of entities work - filters (as their name suggests) are just about what you can read, not about writing/removing. Filters have effect only on the read methods (`em.find/findOne/...`).

**Comment by lightning003** [comment]
Thanks for quick response, was asking similar to that only - clears multiple things. Would open a discussion in case. Thanks.

**Comment by dzcpy** [comment]
Is there an easy way to implement @BeforeSoftDelete and @BeforeRestoreSoftDelete hooks?

**Comment by Phosphorus-M** [comment]
> Here is my implementation of soft delete based on a decorator of the entity class, in case anyone interested:
> 
> ```ts
> import { Filter } from '@mikro-orm/core';
> 
> export type SoftDeleteOptions = {
>   enabled?: boolean;
>   defaultIsDeleted?: boolean;
>   field?: string;
> };
> 
> const defaultOptions = { enabled: true, defaultIsDeleted: false, field: 'deletedAt' };
> 
> export const SoftDelete = (options: SoftDeleteOptions = {}): ClassDecorator => {
>   const { enabled, defaultIsDeleted, field } = { ...defaultOptions, ...options };
>   return Filter({
>     name: 'softDelete',
>     cond: ({ isDeleted = defaultIsDeleted }: { isDeleted?: boolean } = {}) =>
>       isDeleted ? { [field]: { $ne: null } } : isDeleted === false ? { [field]: null } : {},
>     args: false,
>     default: enabled,
>   });
> };
> ```
> 
> ```ts
> @SoftDelete()
> @Entity()
> export class User extends BaseEntity<User, 'id'> {
>   @PrimaryKey({ type: 'uuid', defaultRaw: 'uuid_generate_v4()' })
>   id: string;
> 
>   @Index()
>   @Property({ nullable: true })
>   deletedAt?: Date;
> }
> ```
> 
> ```ts
> await this.em.find(User, {}) // only returns active records
> await this.em.find(User, {}, { filters: { softDelete: { isDeleted: true} } }) // returns deleted records
> await this.em.find(User, {}, { filters: { softDelete: { isDeleted: null} } }) // returns all
> ```

It would be great if it was added as a default decorator in the project.

**Comment by B4nan** [comment]
If we should have some native soft delete support, it could be smarter and less verbose, e.g. we could just have some option on the property decorator like `@Property({ softDelete: true }) deletedAt?: Date`, and we should automatically register onFlush event that will convert delete queries to update ones, as in https://github.com/mikro-orm/mikro-orm/issues/1492#issuecomment-785394397

There is also this, which basically does it already as an extension: https://github.com/TheNightmareX/mikro-orm-soft-delete

**Comment by kallekulp** [comment]
TheNightmareX solution works, but what about restoring soft deleted records? Is there any updates for the native support of soft deletes?

**Comment by B4nan** [comment]
You can just do `em.nativeUpdate(User, { deletedAt: null })` or similar (e.g. using query builder).

**Comment by octet-stream** [comment]
> You can just do em.nativeUpdate(User, { deletedAt: null }) or similar (e.g. using query builder).

I know this is supposed to be implemented through filters and custom repos, but I think it would've been nice to have a way to extend `EntityManager` with custom methods. In case if one doesn't need custom repositories and soft delete is not going to be implemented by Mikro ORM. I am not sure if there's any other case where extension of the EM can be useful to see whether it's even worth to look into.

With extension this would be just

```js
await em.softDelete(User, id)
```

**Comment by B4nan** [comment]
Technically you can already extend the EM by overriding the `createEntityManager` driver method (either by patching the prototype or by creating your own driver extending an existing one). We could make this configurable, I don't mind that at all.

Also, I am not sure why you would say you need a custom repository, the proposed way for soft deletes is only by setting up filters and a flush subscriber, you don't need any custom methods, as you change the behavior of `remove` internally, from outside you delete the entity as usual. The question above was how to restore soft deleted entity, not how to soft-delete one, that feels like something you will do on one place in the whole app, so using `nativeUpdate` feels good enough (it's a one-liner vs one-liner in the end).

**Comment by octet-stream** [comment]
> Technically you can already extend the EM by overriding the createEntityManager driver method (either by patching the prototype or by creating your own driver extending an existing one). We could make this configurable, I don't mind that at all.

I would rather not monkey-patch anything, unless it's absolutely no user way to get the job done.

> Also, I am not sure why you would say you need a custom repository

This is just one way to implement soft deletions. The way I choose is through custom repository + filter. Something like this:

Repo

```ts
import {EntityRepository} from "@mikro-orm/mysql"

export class BaseRepo<T> extends EntityRepository<T> {
  softDelete(entity: T) {
    // Mark the entity as removed
    if (entity.deletedAt === null) {
      entity.deletedAt = new Date()
    }

    return this
  }

  restore(entity: T) {
    // Mark the entity as restored
    if (entity.deletedAt !== null) {
      entity.deletedAt = null
    }

    return this
  }
}
```

Filter

```ts
import {Filter} from "@mikro-orm/mysql"

export const ExcludeSoftRemovedFilter = () => Filter<{deletedAt?: boolean}>({
  default: true,
  name: "softRemoved",
  cond: {deletedAt: null}
})
```

Base soft removable entity

```ts
import {Property, PrimaryKey} from "@mikro-orm/mysql"

export abstract class BaseSoftRemovable {
  @PrimaryKey()
  id!: string = crypto.randomUUID()

  @Property({type: Date, nullable: true, default: null})
  deletedAt!: Date | null = null
}
```

Some entity

```ts
import {ExcludeSoftRemovedFilter} from "#filters/ExcludeSoftRemovedFilter.js"
import {BaseSoftRemovable} from "#entities/BaseSoftRemovable.js"

@ExcludeSoftRemovedFilter()
export class MyEntity extends BaseSoftRemovable {
  // ... other fields ...
}
```

Usage

```ts
import {orm} from "#orm"

import {MyEntity} from "#entities/MyEntity.js"

const repo = orm.em.getRepository(MyEntity)

const record = await orm.em.findOneOrFail(MyEntity, "00000000-0000-0000-0000-000000000000", {filters: false})

// Remove
await repo.softDelete(record).flush() // I know v6 will remove EM methods from repositories :)

// Restore
await repo.restore(record).flush()
```

I had to note that this is not a well though example, because I took this code from one of my old projects, currently I just mark entities as removed manually or via `nativeUpdate`. This is not a big deal for me when I work in small team or on my own projects, but just one of "quality of life" features I would say. Also, I don't mind if soft deletions would never be part of Mikro ORM, but I think there should be better way to handle this, by making global abstractions to use a single API project-wide.

**Comment by B4nan** [comment]
FYI #5064

**Comment by kallekulp** [comment]
What about restoring with cascading? Minimal example would be User -> OneToMany Address. Deleting works fine, but when using nativeUpdate only User is updated. Is there a way to update also the nested Address entities deletedAt to null?
