### ISSUE TITLE
Migrations + PostGIS

### ISSUE THREAD

**Issue by wkrueger** [mikro-orm/mikro-orm#386]
**Describe the bug**
Migrations does not recognize the tables under the "topology" schema/tablespace as "system tables", attempting to remove them. They seem to be treated as tables within the same context/tablespace.

Migration excerpt:
```ts
    this.addSql('drop table if exists "layer" cascade;');
    this.addSql('drop table if exists "topology" cascade;');
```

If I create an entity names "Layer", the migration attempts to modify the existing "layer" table as if it belonged to the same tablespace.

![image](https://user-images.githubusercontent.com/2209181/76092868-e59d8a80-5f9e-11ea-8b03-51daa8690f50.png)

**Additional context**
https://github.com/wkrueger/geostore

**Comment by B4nan** [comment]
Hmm interesting, I would expect that to fail. What does `SHOW search_path;` return? I guess your `topology` schema will be there, before the `public` one. 

You could get around that by specifying the schema explicitly:

```typescript
@Entity({ tableName: 'public.layer' }) // tableName works in 3.3.6, otherwise use `collection`
export class Layer { ... }
```

**Comment by wkrueger** [comment]
Thx for tip!

`conn.execute("SHOW search_path;")` returned `"$user", public, topology`

**Comment by B4nan** [comment]
Hmm right, I guess we can add a config to explicitly set global schema (allowing to change it on entity level, as well as on query level). 

It would affect all queries, so we also do not fall in false positives when querying the table  with classic CRUD queries.

**Comment by wkrueger** [comment]
I don't know if this would be right or have side effects, but maybe we don't even need to sync a table if it is not considered to be managed by the ORM

**Comment by B4nan** [comment]
Ok so the solution was in fact much easier. The SQL for fetching list of available tables in PG was querying all schemas except `information_schema`, so I just replaced that with a check for `current_schema()`.

**Comment by mnowaczyk** [comment]
It's still broken, this time not with PostGIS, but with pg_cron.
Generated migrations try to drop schema "cron", even though it's not in the search path.

**Comment by corbt** [comment]
Ah I see, being able to migrate diffs across all the schemas could be a handy feature I guess!

Building in support for an `ignoreSchema` configuration option would be nice, but since PostGIS is so widely used I think including its schemas by default would be a good start. Those schemas are named `tiger` and `topology`. I'll open a PR.
