### ISSUE TITLE
Custom pivot entity M2M relation queries from inverse side ID

### ISSUE THREAD

**Issue by Saegusae** [mikro-orm/mikro-orm#3860]
**Describe the bug**
When defining a M2M relation with custom `pivotEntity`, trying to load the relation into the collection from one side results in only getting one entity populated. This is consistent for `loadCount` and `init` methods for the collection.

Example Relation:
```ts
@Entity({ tableName: 'audiences' })
export class AudienceEntity extends EntityBase {
    
    ...

    @ManyToMany({
        entity: () => ContactEntity,
        pivotEntity: () => AudienceContactEntity,
      })
      contacts = new Collection<ContactEntity>(this);
}

@Entity({ tableName: 'contacts' })
export class ContactEntity extends EntityBase {

    ...

    @ManyToMany({
        entity: () => AudienceEntity,
        pivotEntity: () => AudienceContactEntity,
      })
      audiences = new Collection<AudienceEntity>(this);
}

@Entity({ tableName: 'audience_contacts' })
export class AudienceContactEntity {
    @ManyToOne({ entity: () => AudienceEntity, primary: true })
    audience!: AudienceEntity;

    @ManyToOne({ entity: () => ContactEntity, primary: true })
    contact!: ContactEntity;
}
```

I can see the contacts with proper corresponding IDs populated on the pivot table in the database:
![image](https://user-images.githubusercontent.com/22715174/208683745-ae7166bb-82f5-4954-b2e3-0924f271f8ce.png)

Yet the only ContactEntity that will get populated into the collection when called is the one with `ID = 4` which correlates with ID the AudienceEntity I'm calling it from (also ID 4)

Here is the query being executed:
```sql
select "c0".*, "a1"."audience_id" as "fk__audience_id", "a1"."contact_id" as "fk__contact_id" 
from "contacts" as "c0" 
left join "audience_contacts" as "a1" on "c0"."id" = "a1"."audience_id" 
where "a1"."contact_id"
```

even though the call to populate was done from the Audience side, the query matches audience_id from the pivot entity to contact join ID. Is this a configuration mistake on my part? The example to reproduce is same as it was shown on mikro-orm docs.

**Stack trace**
No errors thrown

**To Reproduce**

Example code shown above

**Expected behavior**
The collection should populate with the target entity using correct join column of the direction the call was made.

**Versions**

| Dependency | Version |
| - | - |
| node | `18.11.0` |
| typescript | `4.8.4` |
| mikro-orm | `5.6.0` |
| your-driver | `@mikro-orm/postgresql` |

**Comment by B4nan** [comment]
You need to link your properties if you want to form a bidirectional relation:

```ts
@Entity({ tableName: 'audiences' })
export class AudienceEntity extends EntityBase {
    
    ...

    @ManyToMany({
        entity: () => ContactEntity,
        pivotEntity: () => AudienceContactEntity,
      })
      contacts = new Collection<ContactEntity>(this);
}

@Entity({ tableName: 'contacts' })
export class ContactEntity extends EntityBase {

    ...

    @ManyToMany({
        entity: () => AudienceEntity,
        mappedBy: 'contacts',
      })
      audiences = new Collection<AudienceEntity>(this);
}
```

If that won't help, please provide reproduction as code, (incomplete) entity definition is not enough.

**Comment by Saegusae** [comment]
So pivot entity only needs to be defined by the owning side and the other side should point the mapping to the owner entity?

your proposed solution seems to work flawlessly, but I looked through the documentation for hours and could not find why this would be the case 😅

**Comment by B4nan** [comment]
You always need to link bidirectional relations - although for pivot entity we could detect which side is owning automatically. And yes, you don't need to duplicate the pivot entity option on both ends, unless the option is inverse side specific, its enough to have it on the owning side.

**Comment by Saegusae** [comment]
Thank you this seems resolved for now.
