### ISSUE TITLE
Inconsistent behavior when using OneToOne relationship and primary key

### ISSUE THREAD

**Issue by bryan-vh** [mikro-orm/mikro-orm#3869]
**Describe the bug**
When attempting to create a 1:1 relationship between two entities, there were inconsistencies in the produced SQL. I was able to get this working, but wanted to flag this as a potential issue for the library based on my experimentation.

```
@Entity()
export class Profile {
  @PrimaryKey()
  userId!: string;

  @OneToOne(() => Rating, (rating) => rating.profile, {
    cascade: [Cascade.ALL],
  })
  rating!: Rating;
}

@Entity()
export class Rating {
  @OneToOne({ entity: () => Profile, primary: true })
  profile!: Profile;

  // eslint-disable-next-line @typescript-eslint/no-inferrable-types
  @Property()
  rating: number = 1000;

  [PrimaryKeyType]?: [string];
}
```
When my profile and rating entities are written like this, I get the following SQL (which is desired):

```
create table "profile" ("user_id" varchar(255) not null, constraint "profile_pkey" primary key ("user_id"));

create table "rating" ("profile_user_id" varchar(255) not null, "rating" int not null default 1000, constraint "rating_pkey" primary key ("profile_user_id"));

alter table "rating" add constraint "rating_profile_user_id_foreign" foreign key ("profile_user_id") references "profile" ("user_id") on update cascade on delete cascade;
```
However, when I change profile and rating to be like this:

```
@Entity()
export class Profile {
  @PrimaryKey()
  userId!: string;

  @OneToOne({ inversedBy: 'profile' })
  rating!: Rating;
}

@Entity()
export class Rating {
  @OneToOne({ entity: () => Profile, mappedBy: 'rating', primary: true })
  profile!: Profile;

  // eslint-disable-next-line @typescript-eslint/no-inferrable-types
  @Property()
  rating: number = 1000;

  [PrimaryKeyType]?: [string];
}
```

For starters, if I don't include the 'entity' part in the decorator then ReflectMetadata throws an error, but also the SQL that's produced ends up with the rating table missing the entire "profile_user_id" column being included in the create table definition.

```
create table "rating" ("rating" int not null default 1000, constraint "rating_pkey" primary key ("profile_user_id"));

create table "profile" ("user_id" varchar(255) not null, "rating_profile_user_id" varchar(255) not null, constraint "profile_pkey" primary key ("user_id"));

alter table "profile" add constraint "profile_rating_profile_user_id_unique" unique ("rating_profile_user_id");

// this now throws an error since rating doesn't have this column
alter table "profile" add constraint "profile_rating_profile_user_id_foreign" foreign key ("rating_profile_user_id") references "rating" ("profile_user_id") on update cascade;
```

**Expected behavior**
Expected these different implementations to work in the same way.

**Versions**

| Dependency | Version |
| - | - |
| node | v19.3.0 |
| typescript | v4.7.4 |
| mikro-orm | v5.6.1 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
> However, when I change profile and rating to be like this:

Well, that change you made means your Profile entity has no PK, which is indeed invalid. You cannot use an inverse side 1:1 as the primary key, it represents no database column.

So if something, this is a missing validation. The side of the relation that uses `mappedBy` is always inverse, only owning side can be a primary key.

**Comment by bryan-vh** [comment]
Interesting, so adding the 'mappedBy' attribute makes it so that the relation no longer represents a database column if attempted to use as a PK? I didn't know that was the expected behavior. Would the same then happen if I marked the rating property in Profile as `{ owner: true }`?

**Comment by B4nan** [comment]
This is not about primary keys at all. You use `mappedBy` on one end and `inversedBy` on another, and that is what sets the owning side. It was always like that, from the very first version. The `owner` option was added to support setting owning side with the "multi param signature", e.g. `@OneToOne('Ent', 'prop')`, as the second parameter is always `mappedBy`. Also note that you need to link only one side - the side that don't provide a link is always considered as owner.

https://mikro-orm.io/docs/relationships

**Comment by alex996** [comment]
Is there a reason why:

> You cannot use an inverse side 1:1 as the primary key

Does it break something? A [valid use case](https://stackoverflow.com/a/47563393) is 1:0..1 relation. Ex: a user can optionally rate the website (most users won't).

```sql
create table "rating" (
  "user_id" int not null,
  "score" integer not null,
  constraint "rating_pkey" primary key ("user_id")
);
alter table "rating" add constraint "rating_user_id_foreign"
  foreign key ("user_id") references "user" ("id") on update cascade;
```

This could be `"rating" int null` in the `user` table, but it would be wasteful because most users won't leave a rating. Plus, a rating doesn't need an `id`, it's an extremely simple table.

In Mikro, this throws an error:

```ts
@Entity()
class Rating {
  @OneToOne({
    entity: () => User,
    mappedBy: (user) => user.rating,
    primary: true,
  })
  user!: User;
```

> MetadataError: Rating.user cannot be primary key as it is defined as inverse side. Maybe you should swap the use of 'inversedBy' and 'mappedBy'.

**Comment by B4nan** [comment]
Inverse side of 1:1 is not represented by any column, its inverse mapping based on the owning side. Sounds like you are confusing inverse with owner.

**Comment by alex996** [comment]
I was trying to make `User` the owning side, and `Rating` with `user_id` the inverse side. I believe the error would go away once I add an `id` PK to `Rating`, but I was trying to avoid that by making `user_id` both the PK and the FK.

**Comment by B4nan** [comment]
Well, but `User` is not the owning side, owning side is the one that declares the foreign key.

**Comment by B4nan** [comment]
I think you are just confused what owning side is, you can have a FK as PK, the entity can share the User.id value, its just the sides that you need to swap. Your user table wont have any FK, so that is the inverse side.

**Comment by alex996** [comment]
Great, thank you. I misunderstood the sides. This worked as intended:

```ts
class Rating {
  @OneToOne(() => User, { primary: true, owner: true })
  user!: User;
...

class User {
  @OneToOne(() => Rating, (rating) => rating.user)
  rating?: Rating;
...

this.addSql(`
  create table "rating" ("user_id" int not null, constraint "rating_pkey" primary key ("user_id"));
`);
this.addSql(`
  alter table "rating" add constraint "rating_user_id_foreign" foreign key ("user_id")
    references "user" ("id") on update cascade on delete cascade;
`);
```
