### ISSUE TITLE
support using getters for private fields when querying

### ISSUE THREAD

**Issue by xenoterracide** [mikro-orm/mikro-orm#3881]
**Is your feature request related to a problem? Please describe.**

note: currently this code doesn't use mikro because of this issue.

I have lots of code that looks like this.

```ts
  @IsUUID()
  @Expose({ groups: [groupMongo] })
  readonly menuItemId: MenuItemId;

  @IsUUID()
  @Expose({ groups: [groupMongo] })
  readonly productId: ProductId;

  @IsArray()
  @Expose({ name: 'variations', groups: [groupMongo] })
  @ValidateNested()
  @Type(() => StorefrontProductVariation)
  private _variations: StorefrontProductVariation[];

  get variations(): readonly StorefrontProductVariation[] {
    return this._variations;
  }
```

the mikro-orm decoroators were on `_variations`, however since that's private it couldn't be used for a query, and using `variations` in the filter didn't work. The reason for this design is that we're using a rich domain model, DDD style and this should never be modified outside of rich methods (db instantiation not counting)

it's worth saying that the stored name was `'variations'` and not `_variations`. I would have expected this to work as the names matched.

if need be I would simply add a second decorator that says what field to use for querying.

discusion https://github.com/mikro-orm/mikro-orm/discussions/3798

**Comment by B4nan** [comment]
This is a non-goal to me, at least the way you proposed, filtering cannot depend on runtime implementation, you need to use the decorated properties.

**Comment by xenoterracide** [comment]
is there a way that could work? I'd be willing to write a patch. My goal is external immutability with use of rich model methods to set properties (outside of db loading).

**Comment by xenoterracide** [comment]
wouldn't exposing this fix it? (I lack familiarity) https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/decorators/Property.ts#L25

**Comment by B4nan** [comment]
It sounds more like you want to override the [property name](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/decorators/Property.ts#L19). But I am more than sure it would break _many_ internals if you do that.
