### ISSUE TITLE
feat: add getResultAndCount

### ISSUE THREAD

**Issue by rubiin** [mikro-orm/mikro-orm#3885]
**Is your feature request related to a problem? Please describe.**
On typeorm we can use a function  called `getManyAndCount` which can be used on querybuilder 
that executes  SQL query and returns entities and overall entities count (without limitation)

**Describe the solution you'd like**
Add a function `getResultAndCount` which returns the count and the entities as well
Example:
```js

const [result, total] = await qb
			.take(limit)
			.skip(offset)
			.getManyAndCount();
```

**Describe alternatives you've considered**
 For now we can do, 

```js	
const result = await qb.getResult()
const total = await qb.clone().count("id", true).execute("get")
```

**Additional context**
The typeorm implementation can be found here
https://github.com/typeorm/typeorm/blob/15a4eb942e2d794eb5975e7a9e8b16cfe478a026/src/query-builder/SelectQueryBuilder.ts#L1832

**Comment by erie0210** [comment]
Can I try this one ? 🙌

**Comment by B4nan** [comment]
Sure!
