### ISSUE TITLE
Mikro-Orm Gets Incorrect Primary Key Name For bulkUpdateMany/initializeUnorderedBulkOp (Mongo)

### ISSUE THREAD

**Issue by ThatOneAwkwardGuy** [mikro-orm/mikro-orm#3897]
**Describe the bug**
When attempting to create an array of entities containing a 1:M and M:1 relationship, Mikro-Orm fails to establish the connection due to it trying to update the 1:M entity using "id" instead of "_id"

BaseSchemaString
```
@Entity({ abstract: true })
export abstract class BaseSchemaString  {
  /**
   * The ID of the entity
   */
  @PrimaryKey({ name: '_id' })
  id: string = customAlphabet(alphanumeric, 21)();
}
```

Asset
```
@Entity({
  collection: CollectionsEnum.ASSETS,
})
export class Asset extends BaseSchemaString {
  /**
   * The merged asset this asset belongs to.
   */
  @ManyToOne(() => MergedAsset, {
    serializer: populateProtector,
  })
  mergedAsset?: MergedAsset;
}
```

MergedAsset
```
@Entity({
  collection: CollectionsEnum.MERGED_ASSETS,
})
export class MergedAsset extends BaseSchemaString {
  /**
   * The assets that are considered to be the same entity.
   */
  @OneToMany(() => BaseAsset, 'mergedAsset', {
    eager: true,
    serializer: arrayPopulateProtector,
  })
  assets = new Collection<Asset>(this);
}
```

After some investigation, I believe somewhere in the ChangeSet.js getPrimaryKey function, the primary key is being retrieved as "id" when it should be "_id" which is leading to:
```
bulk = db.getCollection('assets').initializeUnorderedBulkOp({});bulk.find({ id: 'eL7CgAh8dwMQVtrfmghNq' }).update({ '$set': { mergedAsset: 'UiC4TJUHEnOmA8fiAfSwU', updatedAt: ISODate('2023-01-04T11:22:45.851Z') } })
```
 

**Expected behavior**
Primary key should be "_id" and the query executed should be
```
bulk = db.getCollection('assets').initializeUnorderedBulkOp({});bulk.find({ _id: 'eL7CgAh8dwMQVtrfmghNq' }).update({ '$set': { mergedAsset: 'UiC4TJUHEnOmA8fiAfSwU', updatedAt: ISODate('2023-01-04T11:22:45.851Z') } })
```

**Versions**

| Dependency | Version |
| node | 14.19.0 |
| typescript | 4.9.4 |
| mikro-orm | 5.6.3 |
| your-driver | Mongo |

**Comment by B4nan** [comment]
> When attempting to create an array of entities containing a 1:M and M:1 relationship

What about sharing that code as well? :] Entity definitions don't reproduce much on their own.

> After some investigation, I believe somewhere in the ChangeSet.js getPrimaryKey function, the primary key is being retrieved as "id" when it should be "_id" which is leading to:

This is not about what happen in the ChangeSet class most probably, rather about how the UoW calls the driver, or how the mongo connection handles batch updates.

**Comment by ThatOneAwkwardGuy** [comment]
> What about sharing that code as well? :] Entity definitions don't reproduce much on their own.
> 
> >

Haha my bad, completely skipped my mind.

```
    const groupedAssets = combineAssets(assets);
    const mergedAssets = groupedAssets.map((groupedAsset) =>
      this.mergedAssetModel.create({
        case: ccCase,
        assets: groupedAsset,
      })
    );
    await this.mergedAssetModel.persistAndFlush(mergedAssets);
```

the ```combineAssets``` function returns a 2d array of assets, so Asset[][].

**Comment by B4nan** [comment]
I guess this is because you are not using object id PKs, there are not many tests for that use case.

**Comment by ThatOneAwkwardGuy** [comment]
> Also note that `ChangeSet.getPrimaryKey()` should return the property key, which is `id`, not `_id` (that's column name - for mongo the terminology lags a bit, as they call it property as well, but the difference is simple, one is a property of your entity, one is a property of the mongo collection).

just saw in MongoDriver.js
```
    async nativeUpdate(entityName, where, data, options = {}) {
        if (core_1.Utils.isPrimaryKey(where)) {
            where = this.buildFilterById(entityName, where);
        }
        where = this.renameFields(entityName, where, true);
        data = this.renameFields(entityName, data);
        return this.rethrow(this.getConnection('write').updateMany(entityName, where, data, options.ctx, options.upsert));
    }
    async nativeUpdateMany(entityName, where, data, options = {}) {
        data = data.map(row => this.renameFields(entityName, row));
        return this.rethrow(this.getConnection('write').bulkUpdateMany(entityName, where, data, options.ctx, options.upsert));
    }
```

is there a reason why  ```buildFilterById``` isn't used by ```nativeUpdateMany```

or why the following isn't used in ```nativeUpdateMany``` like in ```nativeInsertMany```
```
const pk = meta?.getPrimaryProps()[0].fieldNames[0] ?? '_id';
```

I realise I'm clutching at straws as I don't have a complete understanding of what is going on here, just looking at differences.

**Comment by B4nan** [comment]
Because the `where` is always an array, never a PK. And the field name conversion is handled elsewhere (in the connection class). In fact, I believe in mongo it should be always an array of PKs (values, not objects with `_id` key, so in your case array of strings, but this might not be 100% correct).
