### ISSUE TITLE
Custom type is throwing missing metadata error

### ISSUE THREAD

**Issue by osayfun** [mikro-orm/mikro-orm#390]
For some reason I want to write a custom type for `ObjectID` type.
Here is my type:
```javascript
export class UserType extends Type {
  convertToDatabaseValue(value: any, platform: Platform): any {
    if (value instanceof ObjectID) {
      return value;
    }
    if (!ObjectID.isValid(value)) {
      throw new Error('User ID is not valid');
    }
    const objectID = new ObjectID(value);
    return objectID;
  }

  convertToJSValue(value: any, platform: Platform) {
    return UserService.getReference(value);
  }
}
```
And here I'm using the custom type:
```javascript
@Entity()
export default class Event extends BaseEntity {
  @Property({ type: UserType })
  user!: IdentifiedReference<Users>;

  @Property()
  category!: string;
}
```
But I'm getting this error and cannot understand why:
`ValidationError: Metadata for entity UserType not found`

I appreciate it if you could help me

**Comment by B4nan** [comment]
This is wrong, you cannot use custom type on a relation. Relation is always represented by the target entity. What you can do is to use custom type on the primary key of the target entity. 

But for this use case I do not even understand what would he that good for, as ObjectId is already supported and working this way.

**Comment by osayfun** [comment]
It is actually not a relation. `User` is an Entity from another database. So I would say it's somehow 'manual' relation.

**Comment by osayfun** [comment]
I was playing with custom types earlier. I also got this error for the example in the docs. I used `DateTyoe` and got this error:
`ValidationError: Metadata for entity DateType not found`

**Comment by B4nan** [comment]
Then you cannot use IdentifiedReference as a type there. I guess it could be connected to this problem, although it sounds weird. 

What does  UserService.getReference(value); do? You need to have those two methods complementary, so based on your snippet, it needs to return object id, which I guess it does not. Another possible problem is in the missing column type method implementation of the type. 

Anyway, there is an issue template, so please follow that, and specify all versions you are using as well as the full stack trace.

**Comment by B4nan** [comment]
> I was playing with custom types earlier. I also got this error even when I used the example in the docs. I used DateType and got this error:
ValidationError: Metadata for entity DateType not found

Then you have some nonstandard environment, the example from docs is included in the test suite. Maybe we will see from the stacktrace.

**Comment by osayfun** [comment]
Ok Got it.
