### ISSUE TITLE
TypeError: Cannot read properties of null (reading '__helper') when array of Embeddable contains null item.

### ISSUE THREAD

**Issue by acrosett** [mikro-orm/mikro-orm#3906]
**Describe the bug**
I used mikro-orm on a existing database, this bug might not be possible when creating the database with mikro-orm.
If an array of Embeddable contains a null item, mikro-orm will throw an error when trying to access its helper.

**Stack trace**
```
TypeError: Cannot read properties of null (reading '__helper')
    at helper (\node_modules\@mikro-orm\core\entity\wrap.js:31:19)
    at \node_modules\@mikro-orm\core\entity\EntityTransformer.js:177:67
    at Array.map (<anonymous>)
    at Function.processProperty (node_modules\@mikro-orm\core\entity\EntityTransformer.js:177:37)
    at \node_modules\@mikro-orm\core\entity\EntityTransformer.js:126:43
    at Array.map (<anonymous>)
    at Function.toObject (\node_modules\@mikro-orm\core\entity\EntityTransformer.js:121:14)
    at ProfileSchema.toJSON (\node_modules\@mikro-orm\core\entity\EntityHelper.js:26:62)
    at WrappedEntity.toJSON (\node_modules\@mikro-orm\core\entity\WrappedEntity.js:46:28)
    at Function.processProperty (\node_modules\@mikro-orm\core\entity\EntityTransformer.js:180:57)
```
Here's what the entity looks like at `Function.processProperty (node_modules\@mikro-orm\core\entity\EntityTransformer.js:177:37)`

![image](https://user-images.githubusercontent.com/104265464/210738943-2cfcf267-a800-492c-ba65-97b11ac2d79b.png)

Here's the simplified schema :

```
@Entity()
export class User {

  @PrimaryKey()
  _id: ObjectId;

  @Embedded(() => ProfileSchema, { nullable: true })
  profile: ProfileSchema;

}

@Embeddable()
export class ProfileSchema {

  @Embedded(() => AddressSchema, { array: true, nullable: true })
  addresses: AddressSchema[];

}

@Embeddable()
export class AddressSchema {

}
```

**To Reproduce**
1. Reproduce de above schema
2. In DB manually add a null item into the addresses array

**Expected behavior**
To handle null values in embeddable array. 

**Versions**

    "@mikro-orm/core": "^5.5.3",
    "@mikro-orm/mongodb": "^5.5.3",
    "@mikro-orm/nestjs": "^5.1.2",
    "@nestjs/core": "^9.2.1",

**Comment by B4nan** [comment]
Well, you cannot have a null item in that array, that's against your entity definition. In fact, we don't support modeling such a state, you can only have objects inside the array. I am not sure if this is something we should support, your reproduction literally says "do something invalid/againt the definition, directly in the database". That is far away from what I can call a bug... 

Also, entity definitions don't throw, you should provide reproduction = code I can use to reproduce the error. You can clearly see this is coming from serialization.

Lastly, you should always update to latest version before reporting anything.

**Comment by B4nan** [comment]
I guess the question here is: why did you add `null` item into that array, touching the database directly? Do you really need to support `null`s inside the array items? Why? Maybe better use a regular JSON column instead.

**Comment by acrosett** [comment]
Thank you for the quick reply.

I tested with the latest version but forgot to mention it. The exception occur on a find users with `_id: { $in : [ id1, id2...] }`.

You're right: a null item into an array doesn't really make sense. It's a mistake in the application I'm trying to migrate, it allowed the user to enter null into its address.

Now if the entity manager prevent null value when pushing a new embeddable, I might just have to clean the DB once of every null item in arrays. Then it won't happen again, (unless the DB is edited manually).

I guess it's more of an unsupported edge case than a bug. That being said, it would be nice to have a tool to sanitize/verify an already existing database.

**Comment by B4nan** [comment]
> The exception occur on a find users with _id: { $in : [ id1, id2...] }.

The stack trace says it's coming from serialization to JSON, so you can probably load the entity just fine. Btw `em.find(E, { _id: { $in : [ id1, id2...] } })` is the same as `em.find(E, [id1, id2...])`.

> That being said, it would be nice to have a tool to sanitize/verify an existing database. 

Well, it's about a value in a JSON column, I don't think we should care about that, do you know any other tool that provides some kind of validation from the values? How would that work? 

> Or to handle the error with a warning.

Yeah, we can do that, for this particular case it should be relatively cheap (perf-wise) and simple.
