### ISSUE TITLE
Improve Range error to include property causing the error

### ISSUE THREAD

**Issue by xenoterracide** [mikro-orm/mikro-orm#3910]
**Is your feature request related to a problem? Please describe.**

Semi Duplicate of https://github.com/mikro-orm/mikro-orm/issues/2525

would it be possible to improve the error? like what property is causing this? I get that it's likely a cycle... although I don't think I have any. I'm not sure how `toJson` is generated, if an object provides it's own does it use that?

I suspect in my case the problem is with `@js-joda/extra` `Interval` which I know does some self referential stuff... but I would think it's own toJson() would be used.

```
    RangeError: Maximum call stack size exceeded

      at ../../node_modules/@mikro-orm/core/utils/Utils.js:698:48
          at Array.some (<anonymous>)
      at Function.hasNestedKey (../../node_modules/@mikro-orm/core/utils/Utils.js:698:43)
      at ../../node_modules/@mikro-orm/core/utils/Utils.js:698:78
          at Array.some (<anonymous>)
      at Function.hasNestedKey (../../node_modules/@mikro-orm/core/utils/Utils.js:698:43)
      at ../../node_modules/@mikro-orm/core/utils/Utils.js:698:78
          at Array.some (<anonymous>)
      at Function.hasNestedKey (../../node_modules/@mikro-orm/core/utils/Utils.js:698:43)
      at ../../node_modules/@mikro-orm/core/utils/Utils.js:698:78
```

**Describe the solution you'd like**

I'd just like an error that can tell me where the problem is.

**Comment by B4nan** [comment]
Nope, its not an error we throw, it means there was a cycle in the code path.
