### ISSUE TITLE
Unable querying on type-safe references

### ISSUE THREAD

**Issue by vimmerru** [mikro-orm/mikro-orm#3920]
**Describe the bug**
Seems it is unable to query entity by any `Ref` property even with primary ref key.

**To Reproduce**

Define any entity with type-safe reference. For example, 

```typescript
@Entity()
export class Cat {
  @PrimaryKey()
  public id!: number;

  @ManyToOne(() => User, { ref: true })
  public owner: Ref<User>
}
```

try to find any entity using `Ref` property. For example,

```typescript
 const cat = await em.findOne(
        Cat,
        {
            id: 1,
            owner: {
                id: 1
            }
        }
    )
```

The code can't be compiled. tsc complains on missed `Ref` properties

```
Argument of type '{ id: number; owner: { id: number; }; }' is not assignable to parameter of type 'FilterQuery<Cat>'.
  Types of property 'owner' are incompatible.
    Type '{ id: number; }' is not assignable to type '{ id: number; } & Reference<User>'.
      Type '{ id: number; }' is missing the following properties from type 'Reference<User>': entity, load, set, unwrap, and 5 more.ts(2345)
```

**Expected behavior**

Code compiles and executes fine

**Versions**

| Dependency | Version |
| - | - |
| node | 19.1.0 |
| typescript | 4.9.4 |
| mikro-orm | 5.6.4 |
| your-driver | doesn't matter |

**Comment by vimmerru** [comment]
Even more strange. I created very simple entity

```typescript
@Entity()
export class Cat {
  @PrimaryKey()
  id!: string

  @Property()
  name!: string
}
```

And try just fetch all

```typescript
const cat = await em.find(
        Cat,
        {},
    )
 ```
 
 compiler says 
 
 ```typescript
 Argument of type '{}' is not assignable to parameter of type 'FilterQuery<Cat>'.
  Type '{}' is not assignable to type 'string'.ts(2345)
  ```
  
  Query like this says
  
  ```typescript
  const cat = await em.find(
        Cat,
        {
            name: 'test'
        },
    )
    ```
    
    
  ```
    Argument of type '{ name: string; }' is not assignable to parameter of type 'FilterQuery<Cat>'.
  Type '{ name: string; }' is not assignable to type 'string'.ts(2345)
  ```
  
  similarly query as complains on type of FilterQuery<Cat>
  
  ```typescript
  const cat = await em.find(
        Cat,
        {
            name: {
                $eq: 'test'
            }
        },
    )
   ```
   
   
  For some reason  FilterQuery<Cat> inference don't work in my environment or i don't understand something.

**Comment by B4nan** [comment]
Provide complete repro, none of the above is reproducible. Here is a passing test case, lets reopen with a failing one.

```ts
import { Entity, ManyToOne, PrimaryKey, Property, Ref } from '@mikro-orm/core';
import { MikroORM } from '@mikro-orm/sqlite';

@Entity()
class User {

  @PrimaryKey()
  id!: number;

  @Property()
  name!: string;

}

@Entity()
export class Cat {

  @PrimaryKey()
  public id!: number;

  @ManyToOne(() => User, { ref: true })
  public owner!: Ref<User>;

}

describe('GH issue 1346', () => {

  let orm: MikroORM;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [User, Cat],
      dbName: `:memory:`,
    });

    await orm.schema.ensureDatabase();
  });

  beforeEach(async () => {
    await orm.schema.dropSchema();
    await orm.schema.createSchema();
  });

  afterAll(() => orm.close(true));

  test('preserve data fields that match pivot field', async () => {
    const cat = await orm.em.findOne(
      Cat,
      {
        id: 1,
        owner: {
          id: 1,
        },
      },
    );
  });

});
```

**Comment by vimmerru** [comment]
@B4nan here is a ready to run gist that fails compilation https://gist.github.com/vimmerru/82987a42a264f2054c412abd853c9867 

It looks quite similar to your code. Maybe there is something related to typescript version or so.

**Comment by B4nan** [comment]
The very same code works fine when put inside the ORM repository, this is rather about your tsconfig, TS version is the same.

**Comment by B4nan** [comment]
> knex relies on node types without explicit dependency and d.ts gives wrong types without @types/node installation

I see, maybe they should specify it as a regular dependency then, cc @kibertoad
