### ISSUE TITLE
UnitOfWork contains ChangeSet even though only find and findOne are called

### ISSUE THREAD

**Issue by Tlepel** [mikro-orm/mikro-orm#3941]
**Describe the bug**
We are fetching some entity data without ever explicitly saving entities. However, the SQL logging shows `update` statements where we don't expect them.

**To Reproduce**
Steps to reproduce this behavior:
I've added a failing test in #3942 which shows a reproducable example.

**Expected behavior**
After flushing the entity manager, I don't expect any `update` statements to the database

**Versions**

| Dependency | Version |
| - | - |
| node | 16 |
| typescript | 4.9.4 |
| mikro-orm | 5.6.6 |
| mikro-orm/mysql | 5.6.6 |
| mysql | 8 |

**Comment by B4nan** [comment]
> 5.6.0

What about testing the latest version first? :] There was a fix exactly for this in one of the follow-ups.

**Comment by Tlepel** [comment]
I reproduced this bug in #3942, but I thought it would be best to specify the dependencies where we encountered this bug in production for full disclosure. I'll change it to the dependencies and version from MikroORM though.
