### ISSUE TITLE
Altering a Enum doesn't generate a schema change

### ISSUE THREAD

**Issue by followben** [mikro-orm/mikro-orm#397]
**Describe the bug**

After altering an enum, running `schemaGenerator.getUpdateSchemaSQL()` does not generate the expected alter table statements.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an enum and use it in an Entity definition
2. Run `schemaGenerator.createSchema()`
3. Add a new enumeration value to the enum type
4. Run `schemaGenerator.getUpdateSchemaSQL()` and confirm no alter table statements are dumped

**Expected behaviour**
Alter table statements for the updated constraint should be dumped

**Additional context**
It seems neither the `getColumns()` on the `PostgresSqlSchemaHelper` (and sqlite/ MySQL equivalents) or the `isSame()` methods on the abstract helper account for a) retrieving existing constraint information, or b) comparing it to the metadata. Perhaps this is just an omission from the implementation of Enums?

**Versions**

| Dependency | Version |
| - | - |
| node | 13.9.0 |
| typescript | 3.8.3 |
| mikro-orm |  3.3.5 |
| pg | 7.18.2 |

**Comment by followben** [comment]
@B4nan - sorry for the delay. Here's two tests that verify this issue for postgres: https://github.com/followben/mikro-orm/commit/07bf3a714c285a894cc28e910e6406d2a6c0d700?diff=unified

**Comment by B4nan** [comment]
Adding two links about how to query for the enum specific metadata as currently we do not have the information:

- postgres: https://stackoverflow.com/a/37072654/3665878
- mysql: https://dba.stackexchange.com/a/214877
