### ISSUE TITLE
Default behaviour of sql generated for DateTimeType using postgressql platform incorrectly uses timestamptz(0) rather than timestamptz

### ISSUE THREAD

**Issue by yangsu-ab** [mikro-orm/mikro-orm#3973]
**Describe the bug**

Default migration script generated for DateTimeType using postgressql platform incorrectly generates `timestamptz(0)` rather than `timestamptz`

**Stack trace**
```
...
```

**To Reproduce**
Steps to reproduce the behaviour:
1. create a schema that contains a DateTimeType. eg.
```
export const UserSchema = new EntitySchema<User>({
  class: User,
  tableName: 'user',
  properties: {
    _updatedAt: {
      type: types.datetime,
      name: 'updated_at',
      nullable: false,
      onCreate: () => new Date(),
      onUpdate: () => new Date(),
    },
  },
});
```
2. generate the migration script
which would show
```
import { Migration } from '@mikro-orm/migrations';

export class Migration20230126202338 extends Migration {

  async up(): Promise<void> {

    this.addSql('create table "user" ...."updated_at" timestamptz(0) not null, ....;');
  }
}
```
3. if we check the snapshot file we see
```
        "updated_at": {
          "name": "updated_at",
          "type": "timestamptz(0)",
          "unsigned": false,
          "autoincrement": false,
          "primary": false,
          "nullable": false,
          "length": 6,
          "mappedType": "datetime"
        }
```
4. timestamptz(0) does not mean length=6, timestamptz length =6 . thus we see the discrepancy. even in the sourcecode there is a comment that mentions 
```
  getDefaultDateTimeLength(): number {
    return 6; // timestamptz actually means timestamptz(6)
  }
```

**Expected behavior**
It should generate migration script that is `"updated_at" timestamptz(6)`

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 16.14.2 |
| typescript |  4.8.4 |
| mikro-orm | 5.8.7 |
| your-driver | postgres |

**Comment by B4nan** [comment]
this is fixed in v6, change it is imho breaking so dont plan to do it in 5.x branch

**Comment by yangsu-ab** [comment]
@B4nan thanks for the quick update, i thought i closed the bug myself by accident :|

**Comment by B4nan** [comment]
here is the PR btw #3832

**Comment by yangsu-ab** [comment]
oh nice. thanks, i should've looked through the issues. i forked it to create a fix as well but i guess that won't be needed :)
