### ISSUE TITLE
`em.populate` hangs when called inside `beforeTransactionStart` (EventSubscriber)

### ISSUE THREAD

**Issue by nikola-lenert** [mikro-orm/mikro-orm#3986]
**Describe the bug**
Calling `populate` is supposed to populate the relations on the provided entities, but instead the request hangs on the `populate` call. The issue is very similar to this resolved issue: https://github.com/mikro-orm/mikro-orm/issues/3005

**Stack trace**
No stack trace, the request just hangs.

**To Reproduce**
```
async beforeTransactionStart(args: TransactionEventArgs): Promise<void> {
    const relationsToPopulate = ['contract.contractor', 'invoiceTransaction.invoice'];
    const deleteChangeSets = args.uow
      .getChangeSets()
      .filter((cs) => cs.type == ChangeSetType.DELETE && cs.entity instanceof TransactionEntity);
    const entitiesToBeDeleted: TransactionEntity[] = deleteChangeSets.map((cs) => cs.entity as TransactionEntity);
    if (entitiesToBeDeleted.length) {
      await this.em.populate<TransactionEntity>(entitiesToBeDeleted[0], relationsToPopulate as never);
    }
  }
```

**Expected behavior**
Relations should be populated on the provided entities and the request execution should resume.

**Additional context**

**Versions**
| Dependency | Version |
| - | - |
| node | 14 |
| typescript | ? |
| mikro-orm | 5.2.3 |
| your-driver | ? |

**Comment by B4nan** [comment]
> mikro-orm | 5.2.3

That's really dated, you should always update before you file anything.

Moreover, I will need to see much more than this, your haven't even mention what driver you are using. Ideally provide complete repro, the issue you mentioned was closed with a test case, ideally modify that to make it fail. I tried to change the event to use `beforeTransactionStart` and the test is passing.

Also are you sure you are passing in a valid query to the `em.populate` call? This even might be too late to access removed entity relation values due to things being already propagated.

**Comment by nikola-lenert** [comment]
I apologise for not providing a complete repro, not exactly able to at the moment.

You are right, I updated to the latest version so it's no longer hanging, but it seems like it's too late as you said (the relations are null in `afterDelete` even though I tried to load them in the beforeTransaction hook).

The reason I tried the transaction hook is because I thought I'd be able to load the relations of the entity before the deletion cascades to the related entities. I know, it's a stupid situation I got myself in.
I shall try with the flush events as you suggested.

I'll close the issue, thank you for your time :)

**Comment by B4nan** [comment]
Great to hear it works with the latest version, those issues are quite painful to debug :] 

> The reason I tried the transaction hook is because I thought I'd be able to load the relations of the entity before the deletion cascades to the related entities.

Try `onFlush` event, that's the best thing to hook into the current flush, you get the changesets computed but no queries were fired yet (tx not yet started unless its a nested one).

**Comment by nikola-lenert** [comment]
Awesome, sounds like a plan! Thank you so much!
