### ISSUE TITLE
Composite FKs with custom type not handled properly

### ISSUE THREAD

**Issue by lsndr** [mikro-orm/mikro-orm#3988]
**Describe the bug**
I'm using OneToMany relation to model my parent Entity and Child entity. When I add a new child entity, to my Parent Rntity and try to persist it, it fails due to SQL error: invalid input syntax for..., because it doesn't respect the that I use custom types for primary keys in the Parent Entity.

I think this bug relates to all kind of relations.

**Stack trace**
```
  DriverException: insert into "attendance_employee" ("employee_id", "assigned_at", "attendance_visit_id", "attendance_date") values ('18ed2d36-db47-4456-b16b-2ac136c1e22e', '2023-01-23T14:00:28.460+00:00', '[object Object]', '[object Object]') returning "employee_id" - invalid input syntax for type date: "[object Object]"

      69 |     }
      70 |
    > 71 |     await attendanceRepository.persistAndFlush(attendance);
            |     ^
      72 |
      73 |     const employeeIds = Array.from(attendance.employees).map(
      74 |       (employee) => employee.employeeId.value,
```

**To Reproduce**
Parent Entity:
```typescript
@Entity()
class Attendance extends AggregateState {
  @PrimaryKey({ name: 'visit_id', type: VisitIdType })
  protected _visitId!: VisitId;

  @PrimaryKey({ name: 'date', type: ExactDateType })
  protected _date!: ExactDate;

  @OneToMany({
    entity: () => AssignedEmployee,
    mappedBy: 'attendance',
    orphanRemoval: true,
  })
  protected _employees!: Collection<AssignedEmployee>;

  @Property({ name: 'created_at' })
  protected _createdAt!: DateTime;

  @Property({ name: 'updated_at' })
  protected _updatedAt!: DateTime;

  @Property({ name: 'version', version: true })
  protected _version!: number;
}
```
Child Entity:
```typescript
@Entity({ tableName: 'attendance_employee' })
export class AssignedEmployee {
  @PrimaryKey({ type: EmployeeIdType })
  employeeId!: EmployeeId;

  @Property()
  assignedAt!: DateTime;

  @ManyToOne(() => Attendance)
  attendance!: unknown;
}
```

**Expected behavior**
Entity should properly persisted

**Versions**

| Dependency | Version |
| node | 18 |
| typescript | 4.9 |
| mikro-orm | 5.6.8 |
| your-driver | postgresql |

**Comment by lsndr** [comment]
I checked the source code and figured that custom type feature is not used for primary keys for some reason: https://github.com/mikro-orm/mikro-orm/blob/df631fd32f3b8c6901350caeb73e26a95d335077/packages/knex/src/AbstractSqlDriver.ts#L341

**Comment by B4nan** [comment]
> I checked the source code and figured that custom type feature is not used for primary keys for some reason:

That's not true, there are many tests for custom types on PKs. The code you linked is only about the SQL conversion method - is that what you are using? You haven't shared your type implementations.

I will need to see complete repro for such issues.

**Comment by B4nan** [comment]
>   attendance!: unknown;

Why `unknown`? 

>   protected _employees!: Collection<AssignedEmployee>;

You should provide property initializer here, not just type.

**Comment by lsndr** [comment]
> Why unknown?

To avoid "Entity" is not initailized error. I tried Ref<> as well, it doesn't change anything

> 
attendance!: unknown;

Why unknown?

> You should provide property initializer here, not just type.
I moved collection initialization to factory method to make entity defition clean. I also tried what you said, it doens't help

**Comment by B4nan** [comment]
> I tried Ref<> as well, it doesn't change anything

Well, it does, I know that error quite well. But you should use `Rel`, not `Ref` - `Ref` is for reference wrapper, that alters behavior too, `Rel` is just an identity type (`Rel<T> = T`).

> I also tried what you said, it doens't help

Yes, both of those questions/hints were unrelated. I need to see a complete repro for your issue.

**Comment by lsndr** [comment]
> That's not true, there are many tests for custom types on PKs.

Could you reference some test where it works? In general custom types on PKs work well. But the Child entities get inserted in database with [Object object] value instead of being coverted to database value

**Comment by lsndr** [comment]
I'll prepare a repo to demonstrate the issue

**Comment by B4nan** [comment]
> Could you reference some test where it works? In general custom types on PKs work well. But the Child entities get inserted in database with [Object object] value instead of being coverted to database value

I don't see how that would be useful, don't expect me to provide a test case for the issue you have :] Feature tests are [here](https://github.com/mikro-orm/mikro-orm/tree/master/tests/features/custom-types), for example [this one](https://github.com/mikro-orm/mikro-orm/blob/master/tests/features/custom-types/GH446.test.ts) uses FKs with custom mapped type. Note that you are talking about 1:m relations, but it's a bit irrelevant as that is the inverse side, the FK is on the m:1 end. There are more tests about this spread across various places, some are in the `tests/issues` too. Haven't found any that would be using 1:m, but as said above, I doubt that would be really relevant - but it depends on what you are doing, you haven't shared anything, just incomplete entity definition.

**Comment by lsndr** [comment]
@B4nan here is the repo: 

https://github.com/lsndr/mikroorm-2k-relation-bug

I provided 2 test cases:

1. For parent entity with one primary key
2. For parent entity with two primary keys

It works well when I have only 1 primary key, but fails with when I have 2 primary keys

**Comment by B4nan** [comment]
Thanks for the repro, looks valid, will try to look into this soon.

**Comment by productdevbook** [comment]
SyntaxError: The requested module '@mikro-orm/core' does not provide an export named 'Ref'


```
import { Entity, ManyToOne, Property, Ref } from '@mikro-orm/core'
import { CustomBaseEntity } from './base'
import { DebtEntity } from './debt.entity'

@Entity({ tableName: 'debtLog', schema: 'public' })
export class DebtLogEntity extends CustomBaseEntity {
  @Property({ type: 'number', columnType: 'decimal', default: 0, nullable: false })
  amount!: number

  /**
   * @description Kayıt öncesi kalan miktar - Yeni özellik
   */
  @Property({ type: 'number', columnType: 'decimal', default: 0, nullable: false })
  beforeLogAmount!: number

  /**
   * @description Kayıt sonrası kalan miktar - Yeni özellik
   */
  @Property({ type: 'number', columnType: 'decimal', default: 0, nullable: false })
  postLogAmount!: number

  /**
   * @description Kayıt statüsü - notu - Yeni özellik
   */
  @Property({ type: 'string', columnType: 'varchar', length: 255, nullable: true })
  note?: string

  /**
   * @description Sistem tarafından otomatik eklenmiş loglar - Yeni özellik
   */
  @Property({ type: 'boolean', columnType: 'bool', default: false, nullable: false })
  isSystemAdded!: boolean

  @ManyToOne(() => DebtEntity, { eager: false, nullable: false, fieldName: 'debtId', ref: true })
  debt!: Ref<DebtEntity>

  constructor(attrs: Partial<DebtLogEntity> = {}) {
    super()
    Object.assign(this, attrs)
  }
}
```

![image](https://user-images.githubusercontent.com/38668796/216236373-d6f3d124-db58-4e29-81a7-879e0eea3ae5.png)
