### ISSUE TITLE
Don't store empty migrations

### ISSUE THREAD

**Issue by jsprw** [mikro-orm/mikro-orm#399]
**Is your feature request related to a problem? Please describe.**
When running migrations automatically on file changes, it saves a migration file although nothing has changed with the following contents:

```
import { Migration } from 'mikro-orm';

export class Migration20200312115106 extends Migration {

  async up(): Promise<void> {

  }

}

```

**Describe the solution you'd like**
Don't store migrations without any changes, maybe have an option to disable storing empty migrations?

**Comment by B4nan** [comment]
I think we do not need an additional option, there is already a way to generate blank migration. 

When you use the automatic way, it should definitely ignore the run when the schema generator returns no queries.
