### ISSUE TITLE
Mongodb embedded transaction

### ISSUE THREAD

**Issue by FranckBontemps** [mikro-orm/mikro-orm#400]
I was working on a transactional version of your package for mongodb.
I just discovered with pleasure that this one has been added in version 3.4.

**Describe the bug**
I wrote the following test:
```
test('transactions with embedded transaction', async () => {
    try {
      await orm.em.transactional(async em => {
        // this transaction should not be commit
        await em.transactional(async subEm => {
          const god1 = new Author('test202003121545', 'test202003121545@heaven1.god');
          await subEm.persistAndFlush(god1);
        });
        throw new Error(); // rollback the transaction
      });
    } catch { }

    const res1 = await orm.em.findOne(Author, { name: 'test202003121545' });
    expect(res1).toBeNull();
  });
```
in the EntityManager.mongo.test.ts

If we PersistAndFlush within an embedded transaction the entity is persisted despite the fact that the parent transaction is not committed.

**Expected behavior**
To avoid the kind of behavior that's hard to predict. It is possible to forward the parent transation to the embedded transactional call?

**Versions**

| Dependency | Version |
| - | - |
| node | 12.13.0 |
| typescript | 3.6.5 |
| mikro-orm | 3.4.1 |
| your-driver | mongodb |

**Comment by B4nan** [comment]
Hmm right, that should be the behaviour, I though I got a test for it already.
