### ISSUE TITLE
Add option to emit js migrations with `.cjs` extension

### ISSUE THREAD

**Issue by stabai** [mikro-orm/mikro-orm#4005]
**Problem:**
[Certain environments](https://nodejs.org/api/packages.html#determining-module-system) will interpret `.js` files as ES6 modules by default. This means that the migrations generated by Mikro ORM in CommonJS form won't work out of the box, and will either require a package.json with `"type": "commonjs"` in the migrations folder (to convert that folder into cjs), or to rename the files so that they have the `.cjs` extension.

**Solution:**
It would be ideal if there were an option to set the extension that Mikro ORM assigns to the emitted migrations. Either there could be a `cjs` option for the `migrations.emit` configuration property, or there could just be a new property like `migrations.fileExtension` that can be overridden to any arbitrary value.

I tried adding a `migrations.fileName` function to do this renaming, but it still appends `.js` to the end.

**Alternatives:**
If users of Mikro ORM in such an environment just need to have a package.json file in the migrations folder, it would be nice if the tooling generated that file for you when creating the first migration.

**Additional context:**
This came up for me when using Mikro ORM with [SvelteKit](https://kit.svelte.dev/).

**Comment by B4nan** [comment]
I'd go with support via `emit` option, should be quite easy, want to take a peek? :]

**Comment by bacujlebc** [comment]
Have you resolved this issue ?

**Comment by stabai** [comment]
From [this code in MigrationGenerator](https://github.com/mikro-orm/mikro-orm/blob/31b89b892201386c76fde6c8742036908319e400/packages/migrations/src/MigrationGenerator.ts#L22), it seems like any `emit` value other than `ts` will just emit CJS code and use that value as an extension. So that makes me think that adding `cjs` as an option in the [union type for emit in MigrationsOptions](https://github.com/mikro-orm/mikro-orm/blob/31b89b892201386c76fde6c8742036908319e400/packages/core/src/utils/Configuration.ts#LL451C22-L451C22) should be all that's needed for this to work.

I'll try to set aside some time for forking and testing this, but since I haven't contributed to Mikro ORM before, I'm not sure how time consuming that will be.
