### ISSUE TITLE
`@EnsureRequestContext` decorator

### ISSUE THREAD

**Issue by snigdha920** [mikro-orm/mikro-orm#4009]
**Is your feature request related to a problem? Please describe.**
A limitation of the `@UseRequestContext` decorator from Mikro ORM, when used with NestJS `@ResolveField`s (from @nestjs/graphql) is when a `@ResolveField` is queried over a subscription, it uses the global entity manager.

When it uses the global EM a runtime error is thrown. 

Reproduction repo: https://github.com/snigdha920/nestjs-mikro-subscriptions-context

**Describe the solution you'd like**

An `@EnsureForkedEm ` decorator, which:
- does nothing if a forked EM is already exists on the request
- if there is no forked EM, then we will fork a new EM.

**Additional context**
Add any other context about the feature request here.

Happy to provide any info and clarifications.

**Comment by B4nan** [comment]
Something like this should work I guess:

```ts
export function EnsureRequestContext<T>(getContext?: MikroORM | ((type?: T) => MikroORM)): MethodDecorator {
  return function (target: any, propertyKey: string | symbol, descriptor: PropertyDescriptor) {
    const originalMethod = descriptor.value;
    descriptor.value = async function (this: T, ...args: any[]) {
      /* istanbul ignore next */
      const orm = getContext instanceof MikroORM ? getContext : (getContext?.(this) ?? (this as any).orm);

      if (!(orm as unknown instanceof MikroORM)) {
        throw new Error('@EnsureRequestContext() decorator can only be applied to methods of classes with `orm: MikroORM` property, or with a callback parameter like `@EnsureRequestContext(() => orm)`');
      }

      // this is the only difference
      if (RequestContext.currentRequestContext()) {
        return originalMethod.apply(this, args);
      }

      return await RequestContext.createAsync(orm.em, async () => {
        return originalMethod.apply(this, args);
      });
    };

    return descriptor;
  };
}
```

I will add it to v6 branch, but you should be able to define one yourself just fine too.

**Comment by snigdha920** [comment]
Perfect, I'll try it out today. Indd, `EnsureRequestContext` is more consistent with what's already there. 
Thank you!

**Comment by B4nan** [comment]
Implemented in v6 via 4204e3fdf00d2b9f3b6d2b9747a40cfc96864a2e

**Comment by snigdha920** [comment]
Was this removed? I tried out the code snippet and it didn't work, so I wanted to reproduce it in the tests to fix it but it looks like it has been removed from the codebase altogether. 

<img width="2032" alt="image" src="https://github.com/mikro-orm/mikro-orm/assets/62167899/c2f8032b-45c4-4721-abc9-1063c0579482">

**Comment by B4nan** [comment]
https://github.com/mikro-orm/mikro-orm/commit/f32e182ba1128cfc815bb8b1745e730288aea0ef

**Comment by snigdha920** [comment]
For me, the `@EnsureRequestContext` in the commit https://github.com/mikro-orm/mikro-orm/commit/f32e182ba1128cfc815bb8b1745e730288aea0ef didn't work, it didn't create the new context properly but it did not throw any error messages either. 

I using the decorator as follows:

```
  @ResolveField(() => MyEntity)
  @EnsureRequestContext()
  public async someField(@Parent() parent: p): Promise<MyEntity> {
    const parentEntity = await this.service.findOne(p.id);
    return await p.myEntity.load(); 
  }
```

This just returned `null` if there was no forked EM in the request context, instead of throwing the 'using global EM' warning, or at least throwing an error that it could not create a new request context with a forked EM.

I copied over the request context creation part from the `@UseRequestContext` decorator, and this is what worked for me: 

```ts
import { MikroORM, RequestContext } from '@mikro-orm/core';
export function EnsureRequestContext<T>(getContext?: MikroORM | ((type?: T) => MikroORM)): MethodDecorator {
  return function (target: any, propertyKey: string | symbol, descriptor: PropertyDescriptor) {
    const originalMethod = descriptor.value;
    descriptor.value = async function (this: T, ...args: any[]) {
      if (RequestContext.currentRequestContext()) {
        return originalMethod.apply(this, args);
      }

      /* istanbul ignore next */
      const orm = getContext instanceof MikroORM ? getContext : getContext?.(this) ?? (this as any).orm;

      if (!((orm as unknown) instanceof MikroORM)) {
        throw new Error(
          '@EnsureRequestContext() decorator can only be applied to methods of classes with `orm: MikroORM` property, or with a callback parameter like `@EnsureRequestContext(() => orm)`'
        );
      }

      return await RequestContext.createAsync(orm.em, async () => {
        return originalMethod.apply(this, args);
      });
    };

    return descriptor;
  };
}
``` 

I also forked the repo, and ran the unit test for the `EnsureRequestContext` decorator, to see if it would create the request context and return the correct value, and it did. 

I use nestjs + graphql, and maybe something differs there from the behaviour in the unit test. Perhaps best to:
1. Try out if the decorator works in a small nestjs app to see if it works
2. Changing the implementation of the `EnsureRequestContext` to what I've pasted above

I can help you out with 1, what's the version of mikro-orm you recommend I install for that?

**Comment by B4nan** [comment]
I am more than sure the decorator works as expected, as it's pretty simple, so there is not much room for errors. The fact that you don't see any errors about the global scope kinda confirms it.

Your problem will be rather about something else, my guess is the parallel execution and some race conditions, it sounds similar to #4343, what version are you on?

Or maybe another guess - that commit is from v6, where the `RequestContext.createAsync` is already removed in favor of `RequestContext.create`, which now returns the promise, and therefore is awaitable - other than that I don't see any difference from your version.
