### ISSUE TITLE
Using `Unique` & `Index` decorators creates duplicate indexes

### ISSUE THREAD

**Issue by patricksmith** [mikro-orm/mikro-orm#4013]
**Describe the bug**
I recently upgraded from 5.3.1 to 5.6.8 and ran into some issues when creating a schema in my test setup. `SchemaGenerator.createSchema` was failing because postgres was throwing a `TableExistsException` error due to too many `create index` statements in the generated SQL. The indexes in question were defined using the `Index` and `Unique` decorators. Removing those decorators in favor of using the `index` and `unique` options on the `Property` decorator fixed the issue.

**To Reproduce**
1. Create an entity using the `Unique` and `Index` decorators. An example adapted [from the docs](https://mikro-orm.io/docs/decorators#index-and-unique):
```js
@Entity()
export class Author {
  @PrimaryKey()
  id: string;

  @Property()
  @Unique()
  email!: string;

  @Index()
  @Property()
  age?: number;

  @Index({ name: "born_index" })
  @Property()
  born?: Date;
}
```
2. Create the schema using the SchemaGenerator or inspect the output of `SchemaGenerator.getCreateSchemaSQL`:
```js
const schemaGenerator = orm.getSchemaGenerator();
console.log(await schemaGenerator.getCreateSchemaSQL());
```
3. Notice that the generated sql contains repeated `create index` and `alter table` commands for the same indexes & constraints:
```sql

    create table "author" ("id" varchar(255) not null, "email" varchar(255) not null, "age" int not null, "born" timestamptz(0) not null, constraint "author_pkey" primary key ("id"));
    alter table "author" add constraint "author_email_unique" unique ("email");
    create index "author_age_index" on "author" ("age");
    create index "born_index" on "author" ("born");
    create index "author_age_index" on "author" ("age");
    create index "born_index" on "author" ("born");
    create index "author_age_index" on "author" ("age");
    create index "born_index" on "author" ("born");
    alter table "author" add constraint "author_email_unique" unique ("email");
    alter table "author" add constraint "author_email_unique" unique ("email");
```

**Expected behavior**
The indexes and constraints should only be included once:

```sql
    create table "author" ("id" varchar(255) not null, "email" varchar(255) not null, "age" int not null, "born" timestamptz(0) not null, constraint "author_pkey" primary key ("id"));
    alter table "author" add constraint "author_email_unique" unique ("email");
    create index "author_age_index" on "author" ("age");
    create index "born_index" on "author" ("born");
```

**Additional context**
The above expected behavior was created with the schema generator, but with using the `index`/`unique` options from `Property` instead:

```js
@Entity()
export class Author {
  @PrimaryKey()
  id: string;

  @Property({ unique: true })
  email!: string;

  @Property({ index: true })
  age?: number;

  @Property({ index: "born_index" })
  born?: Date;
}
```

**Versions**

| Dependency | Version |
| - | - |
| node | v14.18.1 |
| typescript | 4.6.3 |
| mikro-orm | 5.6.8 |
| mikro-orm/postgresql | 5.6.8 |

**Comment by B4nan** [comment]
I will need a complete reproduction for this, there are many tests using the decorators and asserting the schema.

**Comment by B4nan** [comment]
Are you sure this is not just a caching issue? Or maybe you have multiple `core` packages installed? This often happens when you forget to update some of the ORM packages, e.g. the `cli` that is in the dev deps.

**Comment by patricksmith** [comment]
> Are you sure this is not just a caching issue?

I don't believe so -- we're not doing any explicit caching and the problem persists if I add `cache: { enabled: false}` to the MikroORM config. Is there something other cache that I should try to clear out?

> Or maybe you have multiple `core` packages installed? This often happens when you forget to update some of the ORM packages, e.g. the `cli` that is in the dev deps.

I checked my dependencies and they're all 5.6.8, so I don't believe that's the issue.

> I will need a complete reproduction for this, there are many tests using the decorators and asserting the schema.

I tried to create a repo with a reproduction, but things work as expected in a new repo. I'm not sure what I'm doing wrong in my application code, but I guess I'll keep digging. We're using the wildcard for multiple schemas, so I assume it's something there, but adding that in the minimal reproduction doesn't cause any issues 🤔 

Sorry for the noise here!

**Comment by patricksmith** [comment]
I dug a bit more into this and found that our test framework (jest) is somehow importing the entity files multiple times. This is causing the decorators to be executed multiple times and the index to be registered multiple times in the metadata, which is why it shows up more than once in the generated SQL. 

I'm still not certain how/why jest is importing the files multiple times, but I wonder if the decorators should check the existing metadata to not add duplicate entries to `indexes`/`uniques`?

**Comment by B4nan** [comment]
For simple indexes it could work, but you can also have compound indexes, and indexes on the entity level, etc.

**Comment by tduenez** [comment]
@B4nan this happens when [mocking modules](https://jestjs.io/docs/jest-object#jestmockmodulename-factory-options) specifically without providing the `factory` param, and when those modules import entities (either directly or indirectly by importing other files that import entities)

I made a repo to reproduce it https://github.com/tduenez/mikro-index-bug
