### ISSUE TITLE
Delete after insert on flush causes UniqueConstraint error

### ISSUE THREAD

**Issue by yaroslavyal** [mikro-orm/mikro-orm#4019]
**Describe the bug**
When flush method is called, insert operations are executed first, and then delete operations. But it results in UniqueConstraint error in some cases.

**To Reproduce**
Example of code
```typescript
@Entity()
@Unique({ properties: ['title'] })
class Book {

@PrimaryKey()
id: string;

@Property()
title: string;
}

async function run() {
  const book = await this.bookRepository.findOne({ title: 'Test' });
  this.bookRepository.remove(book);
  const newBook = this.bookRepository.create({ title: 'Test' });
  this.bookRepository.persist(newBook);
  await this.bookRepository.flush();
}
```
**Expected behavior**
Run delete operations first.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.13.1 |
| typescript | 4.5.5 |
| mikro-orm | 5.6.8 |
| @mikro-orm/nestjs | 5.1.6 |

**Comment by B4nan** [comment]
Delete operations generally need to go last, as they could cascade delete some other entities that might be changed by other updates. But we have handling for unique field updates, and your repro seems to be working just fine on my end. What driver are you using? Tried sqlite and postgres, both working as expected.

Here is a passing repro, let's reopen with a failing one:

```ts
import {
  Entity,
  PrimaryKey,
  MikroORM,
  Property,
} from '@mikro-orm/core';
import { PostgreSqlDriver } from '@mikro-orm/postgresql';

@Entity()
class Book {

  @PrimaryKey()
  id!: number;

  @Property({ unique: true })
  title!: string;

}

describe('GH issue 1079', () => {

  let orm: MikroORM<PostgreSqlDriver>;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [Book],
      dbName: `4019`,
      driver: PostgreSqlDriver,
      debug: true,
    });
    await orm.schema.refreshDatabase();
    await orm.em.insert(Book, { title: 'Test' });
  });

  afterAll(() => orm.close(true));

  test(`GH issue 1079`, async () => {
    const book = await orm.em.findOneOrFail(Book, { title: 'Test' });
    orm.em.remove(book);
    const newBook = orm.em.create(Book, { title: 'Test' });
    orm.em.persist(newBook);
    await orm.em.flush();
  });

});
```

Which produces:

```sql
select "b0".* from "book" as "b0" where "b0"."title" = 'Test' limit 1 [took 2 ms]
begin
delete from "book" where "id" in (1) [took 1 ms]
insert into "book" ("title") values ('Test') returning "id" [took 2 ms]
commit
```

**Comment by B4nan** [comment]
This is the place where it's handled:

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/unit-of-work/UnitOfWork.ts#L484-L486

**Comment by lineCode** [comment]
if use compound unique, it look like will delete go last

**Comment by B4nan** [comment]
Please provide a repro

**Comment by lineCode** [comment]
https://github.com/mikro-orm/mikro-orm/blob/f1025114c309cb8140c7dfc099933500caf99b23/packages/core/src/typings.ts#L391
https://github.com/mikro-orm/mikro-orm/blob/f1025114c309cb8140c7dfc099933500caf99b23/packages/core/src/unit-of-work/UnitOfWork.ts#L586

for (const entity of this.removeStack) {
      /* istanbul ignore next */
      if (helper(entity).__processing) {
        continue;
      }

      const deletePkHash = [helper(entity).getSerializedPrimaryKey(), ...this.expandUniqueProps(entity)];
      let type = ChangeSetType.DELETE;

      for (const cs of inserts) {
        if (deletePkHash.some(hash => hash === cs.getSerializedPrimaryKey() || this.expandUniqueProps(cs.entity).find(child => hash === child))) {
          type = ChangeSetType.DELETE_EARLY;
        }
      }

      this.computeChangeSet(entity, type);
    }

it seems that the deletePkHash compare failed，expandUniqueProps() not use compound unique

**Comment by B4nan** [comment]
I asked for reproduction, not for code change suggestions. I need to see what I am fixing, no plans to do blind code changes.

**Comment by lineCode** [comment]
ok, think you, i will provide a repro later

**Comment by lineCode** [comment]
i created a new issues at: https://github.com/mikro-orm/mikro-orm/issues/4305, think you
