### ISSUE TITLE
Question: Does this support active record?

### ISSUE THREAD

**Issue by artoodeeto** [mikro-orm/mikro-orm#403]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by B4nan** [comment]
Nope and I am not planning to support it. 

I do not see a way how it could work, as technically one can have many entity managers in a single context (e.g. explicit nested transactions), and this abstraction would not be possible with active record..
