### ISSUE TITLE
MikroORM doesn't delete orphans if they have custom type primary key

### ISSUE THREAD

**Issue by lsndr** [mikro-orm/mikro-orm#4033]
**Describe the bug**
I have one to many relation. When I try to remove a child entity from parent's collection (removeOrphans set to true), it does nothing, since it improperly handles custom primary key type.

It runs the following query:

`delete from child_entity where id in ('[object Object]')`

**To Reproduce**
Here is a repository with a reproduction test
https://github.com/lsndr/mikroom-delete-1toM-bug

**Expected behavior**
Child entities must be removed

**Versions**

| Dependency | Version |
| - | - |
| node | ? |
| typescript | ? |
| mikro-orm | 5.6.8 |
| your-driver | ? |

**Comment by B4nan** [comment]
Thanks for the repro, looks valid.
