### ISSUE TITLE
ValidationError not exported from mikro-orm

### ISSUE THREAD

**Issue by fider-apptimia** [mikro-orm/mikro-orm#404]
Library version: `mikro-orm@3.4.0`

Problem:
Due to documentation https://mikro-orm.io/docs/custom-types mikro-orm should export `ValidationError` but it is **not exported**.

If this is intentional behavior please update documentation and provide other method for throwing TypeError properly when using custom types.

**Comment by B4nan** [comment]
You can import it from `mikro-orm/dist/utils` for now.

    import { ValidationError } from 'mikro-orm/dist/utils';

**Comment by fider-apptimia** [comment]
Thanks for quick response.
If you will find a moment please update docs to save other's time.

BR.
Wojtek

**Comment by B4nan** [comment]
I will export it directly

**Comment by B4nan** [comment]
Will be fixed in next release. Btw funny how issue about missing export is numbered as 404 :D

**Comment by fider-apptimia** [comment]
> Will be fixed in next release. Btw funny how issue about missing export is numbered as 404 :D

Yeah, also noticed it when copied link :)
