### ISSUE TITLE
FilterQuery<T> type-safety when spreading props

### ISSUE THREAD

**Issue by Tronikelis** [mikro-orm/mikro-orm#4043]
**Describe the bug**
Hello, in some places I use helper functions to generate nested dynamic where clauses based on some input

Then I spread them using the `...` operator into the where clause of `em.find()`

 I can see that when spreading the returned objects from the functions into the where param, typescript does not check that they are valid (no build errors are thrown)

```typescript
import {
    Collection,
    IdentifiedReference,
    Entity,
    ManyToOne,
    OneToMany,
    PrimaryKey,
    FilterQuery,
} from "@mikro-orm/core";
import { MikroORM } from "@mikro-orm/postgresql";

@Entity()
class User {
    @PrimaryKey()
    id!: number;

    @OneToMany(() => Pet, p => p.User)
    Pets = new Collection<Pet>(this);
}

@Entity()
class Pet {
    @PrimaryKey()
    id!: number;

    @ManyToOne(() => User, {
        ref: true,
    })
    User!: IdentifiedReference<User>;
}

const orm = MikroORM.init({
    entities: [User, Pet],
});

async function main() {
    const { em } = await Promise.resolve(orm);

    // placeholder example function that I use to return dynamic queries
    const foo = (val: number) =>
        ({
            NON_EXISTENT_NAME_HERE: {
                iii: val,
            },
        } as const);

    const bar = {
        NON_EXISTENT_NAME_HERE: {
            iii: 21,
        },
    } as const;

    const where: FilterQuery<User> = {
        id: 21,

        // ts error here
        NON_EXISTENT_NAME: {},

        // no ts errors, hmm
        ...foo(2),
        ...bar,
    };

    const users = await em.fork().find(User, {
        id: 231,
        Pets: {
            id: 31,
        },

        // ts error here
        NON_EXISTENT_NAME: {},

        // no ts errors, hmm
        ...foo(2),
        ...bar,
    });
}

main();
```

The weird thing that I see is that when in-lining the same non existent params, it throws the error, but when spreading the exact same thing it does not:

```typescript
const where: FilterQuery<User> = {
    id: 21,

    // ts error here
    NON_EXISTENT_NAME: {},

    // no ts errors, hmm
    ...foo(2),
    ...bar,
};
```

Other weird behavior that I noticed:

```typescript
const where = {
    ...foo(2),
};

// ts error
const users = await em.fork().find(User, {
    ...where,
});

// no ts error
const users1 = await em.fork().find(User, {
    id: 21,
    ...where,
});

// ts error
const users2 = await em.fork().find(User, {
    Pets: { ...where },
});

// no ts error
const users3 = await em.fork().find(User, {
    Pets: {
        id: 21,
        ...where,
    },
});
```

Throws errors when:
- spreading the object without any other already existent parameters

Does not throw errors when:
- spreading the object with at least one already existent parameter

This could also be a typescript limitation that I am not aware of

**To Reproduce**
Try to build the first code example above with typescript

**Expected behavior**
Should throw typescript errors in all situations

**Alternatives**
Do not spread the object but just assign to a parameter like this `Permissions: foo(1)`

**Versions**

| Dependency | Version |
| - | - |
| node | 16.19.0 |
| typescript | 4.9.5 |
| mikro-orm | 5.6.9 and 6.0.0-dev.36 |
| your-driver | postgres |

**Comment by B4nan** [comment]
Sounds like a TS limitation rather than something we can solve.

Here is a repro without any ORM code involved:

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgKoGdrIN4ChnLAAmAXMiAK4C2ARtANz7IAOEY6ZACmwNoC6jAL65coSLEQpuYHE2JlKtBkwqYoZDMuG4A9DpYAbSQAsA9gaJYIADzhVmBlDAogEYYKZDIwxuDICSyKooYKbIUGwUUF5EAJ4gdsAIyACOFNDAEOi4CJ7oMjCmYQC8yAAUAG5wBgrUdFAAlMjFAHxMZXgEBAByAPLdAPoAogAa-gDKACpD3ZMD3QCCALJDAwASQwBKQ2SdXQTAh2RVBgA0TASC55fIcOjIuSD5DYw5eTI0cFDNsj39w2MpjM5osVustjtfl1DsAyAAmACM12QV1wglu90e+VeYFirGQADFgAZxABFdJQWIAHkmLR+2GQPAA0oQvABrCCxUwwZCTPgAfjIk2ZfBRjFx+KJJOg5OgsThNLppQZzNZyA5XJ5fKFIrFIixMgA7sZoBAyFKyRTqZooEqofJkIjzkw9N57tAoKZviaIrp9H9BqMJtNZvNlpDsKiXfoQGF2MgPV70KdkMYqFQmAA6bOFUxlOENZHZzOfKDnQSvA3IY2muHm4mWuUKm12vYOp0iAiu+OJ72mv1dPqBwEhkHh3ZRrsxuPuqCeqDJ1PprM5or5wsrktfcuMIA

The issue goes away if the mapped type disallows optionality, which we obviously need - and when done in the ORM codebase, it won't help on its own anyway.

**Comment by B4nan** [comment]
Hmm actually, even that does not help, I forgot to check the error but it was only about the nonoptional pets collection, if I make it optional it won't trigger any error.

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgKoGdrIN4ChnLAAmAXMiAK4C2ARtANz7IAOEY6A-GQApsDaAXUYBfXLlCRYiFLzA4mxMpVoMmFTFDIZVo3AHo9LADbSAFgHsjRLBAAecKsyMoYFEAjDBzIZGFNw5AElkdRQwc2QoNgooHyIATxAHYARkAEcKaGAIdFwEb3Q5GHMIgF5kAAoANzgjJWo6KABKZFKAPiYKvAICADkAeV6AfQBRAA1AgGUAFRHe6aHegEEAWRGhgAkRgCURsm6egmBjshqjABomAmFL6+Q4dGR8kEKmxjyCuRo4KFb5PsGowmMzmC2Wa02Oz2-x6x2AZAATABGW7IG64YT3R7PQrvMDxVjIABiwCMkgAipkoPEADzTNp-bDIPgAaUIPgA1hB4uYYMhpgIyNNWQI0e8cXIAO6maAQMgksnQSnQWnaKAM8oHRTIZGXJgGXyPaBQcy-GVRfSGAHDcZTWbzRaraHYdH6wwgCLsZDG03oc7IUxUKhMAB0YeK5gqCKaqLDIe+UEuwkYQA

I'll close this as a wontfix, as it does not work even with bare bones mapped types like this (the one I use there is equivalent to `Partial`)... Also tried TS 5 and it behaves the same. 

I'd suggest you ensure the objects you want to stread are valid instead - you can keep using const assertions, but combine it with `satisfies`.

Btw I found this SO post that seems to be about the same:

https://stackoverflow.com/questions/70110432/typescript-allowing-incorrect-properties-via-object-destructuring

**Comment by Tronikelis** [comment]
Yeah, seems like this is the expected behavior of typescript, thanks 👍
