### ISSUE TITLE
Prevent class constructor renaming

### ISSUE THREAD

**Issue by lsndr** [mikro-orm/mikro-orm#4045]
When I use one-to-many relationship, my parent class gets renamed. For example if parent class has name `Parent`, `this.constructor.name` returns `Parent1`.

Is there a way to prevent such behaviour? It's a kind of unexpected thing. I haven't checked the source code yet, but I believe `Parent1` can be stored in some WeakMap, instead of renaming original constructor name.

**Comment by B4nan** [comment]
This is not done by the ORM, you probably have some bundler that does it.
