### ISSUE TITLE
Cannot disable cascade deletion of related entity with composite PK if part of PK comes from base class

### ISSUE THREAD

**Issue by RDSM-CM** [mikro-orm/mikro-orm#4051]
**Describe the bug**
MikroORM sets `on delete cascade` on the foreign key of an entity with composite primary key even if cascading is disabled. This happens when the entity extends a base class that defines a part of its composite primary key.

**Steps to reproduce**

1. Define entities:

```ts
abstract class Base {
  @PrimaryKey()
  public id: string
}

@Entity()
class Category extends Base {
  @OneToMany(() => Article, (attr) => attr.category, {
    cascade: [],
  })
  public articles = new Collection<Article>(this)
}

@Entity()
class Article extends Base {
  @ManyToOne(() => Category, {
    primary: true,
    ref: true,
    cascade: [],
  })
  public category: Ref<Category>

  public [PrimaryKeyType]?: [string, string]
}
```

2. Generate schema:

```ts
    const schemaGenerator = orm.getSchemaGenerator()
    const createSql = await schemaGenerator.getCreateSchemaSQL()
    console.dir(createSql)
```

**Expected behavior**
The foreign key constraint of `Article` does not contain `on delete cascade`.
```
  'alter table `article` add constraint `article_categoryId_foreign` foreign key (`categoryId`) references `category` (`id`);\n'
```

**Actual behavior**
The foreign key constraint of `Article` contains `on delete cascade`.
```
  'alter table `article` add constraint `article_categoryId_foreign` foreign key (`categoryId`) references `category` (`id`) on delete cascade;\n'
```

**Additional information**
Adding the other primary key component to `Article` results in the expected output.
```ts
@Entity()
class Article extends Base {
  @PrimaryKey()
  public override id: string

  @ManyToOne(() => Category, {
    primary: true,
    ref: true,
    cascade: [],
  })
  public category: Ref<Category>

  public [PrimaryKeyType]?: [string, string]
}
```

**Versions**
| Dependency | Version |
|---|---|
| node | 14.17.3
| typescript | 4.9.4
| @mikro-orm/core | 5.6.9
| @mikro-orm/mysql | 5.6.9

**Comment by B4nan** [comment]
As a workaround, you could use the `onDelete` option on the owning side to control it explicitly.

https://mikro-orm.io/docs/cascading#declarative-referential-integrity

Note that I would discourage disabling cascade persist (which you are doing in your code by setting `cascade: []`), it could lead to weird behavior and is probably not working as you expect anyway - I will be probably removing the possibility to disable it in v6, as its mostly misunderstood and in current implementation does not make much sense.

**Comment by RDSM-CM** [comment]
>As a workaround, you could use the onDelete option on the owning side to control it explicitly.

That doesn't seem to work:
```ts
@Entity()
class Article extends Base {
  @ManyToOne(() => Category, {
    primary: true,
    ref: true,
    cascade: [],
    onDelete: "no action",
  })
  public category: Ref<Category>

  public [PrimaryKeyType]?: [string, string]
}
```
still produces
```
'alter table `article` add constraint `article_categoryId_foreign` foreign key (`categoryId`) references `category` (`id`) on delete cascade;\n'
```

>Note that I would discourage disabling cascade persist (which you are doing in your code by setting cascade: []), it could lead to weird behavior and is probably not working as you expect anyway - I will be probably removing the possibility to disable it in v6, as its mostly misunderstood and in current implementation does not make much sense.

My intent is to prevent accidental cascade-deletion. When I disable cascading on a relation, I want the DB to throw an error if a referenced entity is deleted. That way I can detect if my code is incorrectly trying to delete an entity it shouldn't delete. Using the entities from this issue as an example, I want an error thrown if I'm deleting a `Category` that is referenced by an `Article`, rather than deleting the `Article` as well without intending to do so.

**Comment by B4nan** [comment]
> My intent is to prevent accidental cascade-deletion. When I disable cascading on a relation, I want the DB to throw an error if a referenced entity is deleted. That way I can detect if my code is incorrectly trying to delete an entity it shouldn't delete. Using the entities from this issue as an example, I want an error thrown if I'm deleting a Category that is referenced by an Article, rather than deleting the Article as well without intending to do so.

Sure, all I said is you should avoid disabling cascade persist, which you are doing with `cascade: []`. 

`cascade: [Cascade.PERSIST]` will disable cascade deletion while maintaining the persist enabled, which should be preferred.

As said, I know this is confusing, and I am currently not aware of a use case where disabling cascade persist would be a good thing - the ORM actually guards you from this mistake and cascades in some cases automatically (persistence by reachability + auto persist of managed entities, which basically leaves no place for disabling it). So the configurability will go away in v6, unless I will find some existing tests that would prove me wrong.
