### ISSUE TITLE
Memory leak with upsertMany()

### ISSUE THREAD

**Issue by Zmaon** [mikro-orm/mikro-orm#4052]
**Describe the bug**

It seems that there is a memory leak when using `upsertMany()` to insert large sets of data. When calling many times `upsertMany()` to insert chunks of data, the memory is not properly freed, even when `em.clear()` is called between the upserts.

**To Reproduce**
Here is a minimal code to reproduce the issue:

```typescript
import { Entity, PrimaryKey, Property } from "@mikro-orm/core";
import { MikroORM } from "@mikro-orm/mysql";

@Entity()
class MyEntity1 {
  @PrimaryKey({ type: 'number' })
  id!: number;

  @Property({ type: 'json' })
  field!: object;
}

(async() => {
  const orm = await MikroORM.init({
    type: 'mysql',
    dbName: 'motest',
    host: '127.0.0.1',
    user: 'root',
    password: 'root',
    port: 3378,
    allowGlobalContext: true,
    debug: false,
    entities: [MyEntity1]
  });
  await orm.schema.refreshDatabase();
  const em = orm.em;

  let id = 1;
  while(true) {
    const entities = [];
    for (let index = 0; index < 5000; index++) {
      const entity = em.create(MyEntity1, {
        id: id++,
        field: {
          firstName: 'John '.repeat(1000),
          lastName: 'Doe '.repeat(1000)
        }
      });
      entities.push(entity);
    }
    await em.upsertMany(entities);
    em.clear();
  }
})();
```
Executing this you'll see the memory of the process grow quite fast, until the process is killed by the system after 2-3 minutes.

**Expected behavior**
As `em.clear()` is called after each upsert, the memory should be freed. The process should be able to run indefinitely. 

**Additional context**

**Versions**

| Dependency | Version |
```json
{
  "devDependencies": {
    "@babel/plugin-proposal-decorators": "^7.20.13",
    "@types/jest": "^29.4.0",
    "jest": "^29.4.3",
    "ts-jest": "^29.0.5",
    "typescript": "^4.9.5"
  },
  "dependencies": {
    "@mikro-orm/core": "^5.6.9",
    "@mikro-orm/mysql": "^5.6.9"
  }
}

```

**Comment by B4nan** [comment]
Looks like this was actually caused by snapshotting of entities and #4053 seems to solve it. Let me know if `5.6.10-dev.6` helps.

**Comment by Zmaon** [comment]
Indeed, I just tested with `5.6.10-dev.6` and the problem appears to be fixed. Nice!
