### ISSUE TITLE
Null date fields in database are set to 1970-01-01 when fetched instead of null

### ISSUE THREAD

**Issue by AmauryD** [mikro-orm/mikro-orm#4057]
**Describe the bug**
Null date fields in database are set to 1970-01-01 when fetched instead of null.
The test below pass in version 5.6.9.

**To Reproduce**
```ts
import { Entity, PrimaryKey, Property } from "@mikro-orm/core";
import { MikroORM } from "@mikro-orm/sqlite";


@Entity()
class E {
    @PrimaryKey({
        type: "string"
    })
    public declare id: string;

    @Property({
        type: "date",
        nullable: true
    })
    public declare date? :Date;
}

test('null dates stay null when fetched',async ()  => {
    const orm = await MikroORM.init({
        dbName: ':memory:',
        entities: [E]
    });

    await orm.getSchemaGenerator().refreshDatabase();
    
    const repo = orm.em.fork().getRepository(E);
    const c = repo.create({
        id: '123',
        date: undefined
    });
    await repo.persistAndFlush(c);

    const entity = await orm.em.fork().findOne(E,'123');

    expect(entity?.date).toBeNull();

    await orm.close(true);
});
```

Result: 

```
● null date stay null when fetched

    expect(received).toBeNull()

    Received: 1970-01-01T00:00:00.000Z

      34 |     const entity = await orm.em.fork().findOne(E,'123');
      35 |
    > 36 |     expect(entity?.date).toBeNull();
         |                          ^
      37 |
      38 |     await orm.close(true);
      39 | });
```

**Expected behavior**
Date fields fetched are set to null when nullable.

**Versions**

| Dependency | Version |
| - | - |
| node | 18 |
| typescript | 4.9.5 |
| mikro-orm | 5.6.10 |

**Comment by B4nan** [comment]
Oops, how come there were no tests for such case.

Btw keep in mind that `type: 'date'` maps to datetime, you need `type: DateType` or `type: t.date` if you want a `date` column mapped to `Date` object. With that it will work fine, the problem is actually only with datetime mapping.

**Comment by AmauryD** [comment]
> Btw keep in mind that `type: 'date'` maps to datetime, you need `type: DateType` or `type: t.date` if you want a `date` column mapped to `Date` object. With that it will work fine, the problem is actually only with datetime mapping. The reason for that is the `type` option is the runtime type (and only falls back to be used as column type if there is no known mapping), basically the type we infer via reflect-metadata - this weirdness is unfortunately caused by JS naming the `Date` class just `Date` instead of `DateTime`.

Ohhhhh thank you for the tip ! I was indeed often misled, i always think type: "date" and type "datetime" were separate things.

**Comment by isanosyan** [comment]
@B4nan Same seems to happen the other way around.

With this field definition:

```ts
@Property({nullable: true, columnType: 'timestamp'})
start?: Date;
```

The code below actually assigns 1970-01-01 00:00:00.

```ts
wrap(entity).assign({start: null});
```

Not sure if this deserves a separate issue.
