### ISSUE TITLE
Mongo: ManyToMany relations in Embeddable cannot be populated

### ISSUE THREAD

**Issue by mrtcntn** [mikro-orm/mikro-orm#4064]
**Describe the bug**
ManyToMany relations in an Embeddable field cannot be populated properly.

**Stack trace**
```
...
```

**To Reproduce**
1. clone https://github.com/mrtcntn/embeddable-m2m-mongo-repro
2. run `run-rs` or your target test database. Change clientUrl accordingly.
3. run `yarn`
4. run `yarn test`

**Expected behavior**

**Additional context**

**Versions**

| Dependency | Version |
| node | 16.15.1 |
| typescript | 4.9.5 |
| mikro-orm | 5.6.11 |
| your-driver | mongo |

**Comment by B4nan** [comment]
You can have only m:1 relations in embeddables. This is documented limitation, an embeddable does not have identity, so it can only support m:1, which represents a foreign key of the target without any other constraints.
