### ISSUE TITLE
migration:create alters nullable string Enum

### ISSUE THREAD

**Issue by belinde** [mikro-orm/mikro-orm#4068]
**Describe the bug**
After upgrading to the latest version, I've added a new entity called Otp and launched migration:create. In the migration there were changes to an unrelated entity, BusinessEntity, that altered two enum fieds to tinyint. The enums are defined in the same file and worked fine until now. There is another enum in the entity that was left untouched, the only difference is that the "correct" one isn't nullable, the "failing" ones are nullable.

Here's an excerpt of the entity file:

```typescript
import { ArrayType, Collection, Embedded, Entity, Enum, IdentifiedReference, Index, ManyToMany, ManyToOne, OneToMany, Property } from '@mikro-orm/core';
import { BaseEntity } from './BaseEntity';

export enum BusinessEntityProfile {
    NATURAL = 'natural',
    SOLETRADER = 'soletrader',
    BUSINESS = 'business',
    ORGANIZATION = 'organization',
}

export enum BusinessEntityUsage {
    PAYEE = 'payee',
    PAYER = 'payer',
}

export enum ElectronicInvoicing {
    PA = 'PA',
    B2B = 'B2B',
}

@Entity()
export class BusinessEntity extends BaseEntity {

    @Enum({ default: null, nullable: true })
    profile: BusinessEntityProfile | null = null;

    @Enum({ default: BusinessEntityUsage.PAYER })
    usage: BusinessEntityUsage = BusinessEntityUsage.PAYER;

    @Enum({ default: null, nullable: true })
    eInvoice: ElectronicInvoicing | null = null;

}

```

**Workaround**
Explicitly list the items values keep the correct structure in the migration:

```typescript
@Entity()
export class BusinessEntity extends BaseEntity {

    @Enum({ default: null, nullable: true, items: Object.values(BusinessEntityProfile) })
    profile: BusinessEntityProfile | null = null;

}

``` 

**Versions**

| Dependency | Version |
| - | - |
| node | 19.2.0 |
| typescript | 4.9.5 |
| mikro-orm | 5.6.11 |
| your-driver | 5.6.11 |

**Comment by B4nan** [comment]
The correct enum definition, as described [in the docs](https://mikro-orm.io/docs/defining-entities#enums), is this:

```ts
@Enum({ default: null, nullable: true, items: () => BusinessEntityProfile })
profile: BusinessEntityProfile | null = null;
```

You need to provide the type explicitly, even if you are using ts-morph (we could improve on that, but seeing you explicitly set `nullable: true`, I guess you are not using ts-morph anyway). You don't have to use `Object.values()`, and it should be a callback to get around possible dependency cycles. 

Some time ago it was possible to infer enum values based on the type name, but IIRC that has been removed (if not, I will make sure it is removed in v6) and is no longer documented for quite some time (I believe the whole v5 lifecycle).
