### ISSUE TITLE
How to define the pivot table to ManyToMany relationships

### ISSUE THREAD

**Issue by chrisbrantley** [mikro-orm/mikro-orm#407]
I'm trying to model an existing MySQL schema that has a M:M relationship between `companies` and `users`. There is a pivot table called `company_user` that has an auto_incrementing pk along with columns for `company_id` and `user_id`. I can't change the schema since it's generated by a legacy Laravel app that has to function while we are working on the new architecture. 

I couldn't find anything in the docs for how to do this. Is it possible with MikroORM?

**Comment by B4nan** [comment]
Yes this should be supported, you can create the AI PK via `fixedOrder`: https://mikro-orm.io/docs/collections/#forcing-fixed-order-of-collection-items

```typescript
@Entity({ tableName: 'companies' })
export class Company {

  @ManyToMany({ pivotTable: 'company_user', joinColumn: 'company_id', inverseJoinColumn: 'user_id', fixedOrder: true })
  users = new Collection<User>(this); // owning side

}

@Entity({ tableName: 'users' })
export class User {

  @ManyToMany(() => Company, company => company.users)
  users = new Collection<Company>(this); // inverse side

}
```

You can control the name of the AI PK column via `fixedOrderProperty`.
