### ISSUE TITLE
Updating a nested Collection item via em.assign() does not work

### ISSUE THREAD

**Issue by RDSM-CM** [mikro-orm/mikro-orm#4074]
**Describe the bug**
When updating an item of a nested `Collection` via `em.assign()`, the change is not persisted when calling `em.persistAndFlush()`.

**Steps to reproduce**

1. Define entities:

```ts
@Entity()
class Category {
  @PrimaryKey()
  public id: string

  @OneToMany(() => Article, (attr) => attr.category, {
    cascade: [Cascade.ALL],
    orphanRemoval: true,
  })
  public articles = new Collection<Article>(this)
}

@Entity()
class Article {
  @PrimaryKey()
  public id: string

  @ManyToOne(() => Category, {
    primary: true,
    ref: true,
  })
  public category: Ref<Category>

  public [PrimaryKeyType]?: [string, string]

  @OneToMany(() => ArticleAttribute, (attr) => attr.article, {
    cascade: [Cascade.ALL],
    orphanRemoval: true,
  })
  public attributes = new Collection<ArticleAttribute>(this)
}

@Entity()
class ArticleAttribute {
  @PrimaryKey()
  public id: string

  @Property()
  public name: string

  @ManyToOne(() => Article, {
    primary: true,
    ref: true,
  })
  public article: Ref<Article, "id" | "category">

  public [PrimaryKeyType]?: [string, [string, string]]
}
```

2. Create entities:

```ts
    const em = orm.em.fork()
    const category = new Category()
    category.id = "category1"

    const article = new Article()
    article.id = "article1"
    category.articles.add(article)

    const articleAttribute = new ArticleAttribute()
    articleAttribute.id = "articleAttribute1"
    articleAttribute.name = "nameBeforeUpdate"
    article.attributes.add(articleAttribute)

    await em.persistAndFlush(category)
    em.clear()
```

3. Try to update them:
```ts
    const plainUpdate: EntityData<Category> = {
      articles: [
        {
          id: article.id,
          category: category.id,
          attributes: [
            {
              id: articleAttribute.id,
              article: [article.id, category.id],
              name: "nameAfterUpdate",
            },
          ],
        },
      ],
    }

    const loaded = await em.findOneOrFail(
      Category,
      { id: category.id },
      { populate: true },
    )

    em.assign(loaded, plainUpdate, { mergeObjects: true })
    await em.persistAndFlush(loaded)
    em.clear()
```

**Expected behavior**
The entities are updated in the database. `articleAttribute1`.`name` is `"nameAfterUpdate"`.
```ts
    const updated = await em.findOneOrFail(
      Category,
      { id: category.id },
      { populate: true },
    )
    console.dir(wrap(updated).toPOJO().articles, { depth: 3 })
```
```
[
  {
    id: 'article1',
    category: { id: 'category1' },
    attributes: [
      {
        id: 'articleAttribute1',
        article: [Object],
        name: 'nameAfterUpdate'
      }
    ]
  }
]
```

**Actual behavior**
`articleAttribute1`.`name` is still `"nameBeforeUpdate"`
```
[
  {
    id: 'article1',
    category: { id: 'category1' },
    attributes: [
      {
        id: 'articleAttribute1',
        article: [Object],
        name: 'nameBeforeUpdate'
      }
    ]
  }
]
```

**Additional information**
The error seems to occur when persisting. Calling `console.dir(wrap(loaded).toPOJO().articles, { depth: 3 })` after `em.assign(loaded, plainUpdate, { mergeObjects: true })` produces the expected output.

**Versions**
| Dependency | Version |
|---|---|
| node | 14.17.3
| typescript | 4.9.4
| @mikro-orm/core | 5.6.12
| @mikro-orm/mysql | 5.6.12

**Comment by B4nan** [comment]
I see it again and again, so let me say this: `mergeObjects` does not have any effect on your code, it is only for object merging of JSON properties, with no effect on entities/relations. And its default is `true`...

I'd also appreciate reproductions as a single script, it only adds time when you split it into multiple code blocks without imports :] Even better, if your reproduction is based on some previous one, send a PR adjusting the existing test.

**Comment by RDSM-CM** [comment]
> I see it again and again, so let me say this: mergeObjects does not have any effect on your code, it is only for object merging of JSON properties, with no effect on entities/relations. And its default is true...

I wasn't aware that it defaults to true. Thanks for the information.

> I'd also appreciate reproductions as a single script, it only adds time when you split it into multiple code blocks without imports :] Even better, if your reproduction is based on some previous one, send a PR adjusting the existing test.

I'll keep it in mind for the future.
