### ISSUE TITLE
JSON fields fire Update queries when aren't modified

### ISSUE THREAD

**Issue by belinde** [mikro-orm/mikro-orm#4078]
**Describe the bug**
An entity with a JSON field always fire an "updated" event o even if it has not been modified.

**To Reproduce**
This is a minimal example; the entity Contraxct has been previously created and exists on the database; every piece of code is in the correct file, here's in one shot for the sake of clarity (the project can be cloned here: https://github.com/belinde/mikroorm-bug).

```typescript
type Setup = {
  limits?: boolean;
  fallbackFees?: boolean;
};

@Entity()
export class Contract {
  @PrimaryKey({ columnType: "char(26)" })
  id = ulid();

  @Property()
  title: string;

  @Property({ type: JsonType, nullable: true })
  setup: Setup | null = null;
}

export class EntityOperationLogger implements EventSubscriber {
  async afterUpdate<T>(args: EventArgs<T>): Promise<void> {
    console.log("EntityOperationLogger", args);
  }
}

MikroORM.init()
  .then(async (orm) => {
    const em = orm.em.fork();
    await em.findOneOrFail(Contract, "01GT9WBT1Z05T1NARYGGTNMVFN");
    await em.flush();
  })
  .finally(() => process.exit());
```
With this code, an unnecessary UPDATE query is launched, ad the subsequent AfterUpdate event is fired.

**Expected behavior**
The previous code should'n make any UPDATE query, nor fire Update events

**Versions**

| Dependency | Version |
| - | - |
| node | 19.2.0 |
| typescript | 4.9.5 |
| mikro-orm | 5.6.12 |
| mysql | 5.6.12 |

**Comment by belinde** [comment]
The example project that shows the bug: https://github.com/belinde/mikroorm-bug

**Comment by B4nan** [comment]
Not reproducible, here is a test case that does not produce any extra updates:

```ts
import { Entity, EventArgs, EventSubscriber, JsonType, PrimaryKey, Property } from '@mikro-orm/core'; import { MikroORM } from '@mikro-orm/mysql'; import { TsMorphMetadataProvider } from '@mikro-orm/reflection';

type Setup = {
  limits?: boolean;
  fallbackFees?: boolean;
};

@Entity()
export class Contract {

  @PrimaryKey()
  id!: number;

  @Property()
  title!: string;

  @Property({ type: JsonType, nullable: true })
  setup: Setup | null = null;

}

export class EntityOperationLogger implements EventSubscriber {

  async afterUpdate<T>(args: EventArgs<T>): Promise<void> {
    console.log('EntityOperationLogger', args);
  }

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [Contract],
    dbName: `mikro_orm_test_4078`,
    port: 3308,
    metadataProvider: TsMorphMetadataProvider,
  });

  await orm.schema.refreshDatabase();
});

afterAll(async () => {
  await orm.close(true);
});

it('4078', async () => {
  await orm.em.insert(Contract, {
    id: 1,
    title: 't',
    setup: {
      limits: true,
      fallbackFees: false,
    },
  });
  await orm.em.findOneOrFail(Contract, 1);
  await orm.em.flush();
});
```

**Comment by B4nan** [comment]
try latest dev version, the fix wasnt mysql specific in the end

**Comment by Sn-Kinos** [comment]
I have the same issue with MariaDB driver.

**Comment by B4nan** [comment]
You need to provide a reproduction, this bug is fixed for more then a year, and the test is passing just fine with mariadb too. So nope, you don't really have "the same" issue.
