### ISSUE TITLE
ObjectId and string id duality

### ISSUE THREAD

**Issue by desmap** [mikro-orm/mikro-orm#408]
Not a bug but an issue about the docs and architecture:

Do you save both ObjectId and String or is the String a virtual one? If you save both, why? Coming from Mongo, I'd just need the ObjectId which I can convert to string with the native function.

**Comment by B4nan** [comment]
In database you will get only `_id: ObjectId`, that `id: string` property is virtual and also should be optional.

**Comment by desmap** [comment]
Thanks for the quick feedback! So there's no risk of setting different ids and this example...
```
@PrimaryKey()
_id: ObjectId;

@SerializedPrimaryKey()
id!: string;
```
...is just that you can do both but (I assume) the second one is optional because in Mongo every document gets an ObjectId. Thanks and closing :)

**Comment by B4nan** [comment]
> Edit: If I query with _id I need to do this always with ObjectID('<id>') while with id I can just use the plain string <id>, right?

You can use all combinations, both `_id` and `id` fields will be converted to `ObjectId` type (and they will both map to the `_id` in the database). All of this should work (also for relations, not just the PK):

    em.findOne(Book, '1234...');
    em.findOne(Book, new ObjectId('1234...'));
    em.findOne(Book, { id: '1234...' });
    em.findOne(Book, { _id: '1234...' });
    em.findOne(Book, { id: new ObjectId('1234...') });
    em.findOne(Book, { _id: new ObjectId('1234...') });

https://mikro-orm.io/docs/usage-with-mongo/#objectid-and-string-id-duality

**Comment by desmap** [comment]
Awesome, thanks!
