### ISSUE TITLE
TypeError: Cannot read property 'fieldName' of undefined

### ISSUE THREAD

**Issue by UTGuy** [mikro-orm/mikro-orm#409]
**Describe the bug**
I am using a base class like so...
```
export abstract class BaseEntity implements AnyEntity<BaseEntity, "id"> {
    constructor() {
        this.id = IdCreator.create();
    }

    @PrimaryKey()
    readonly id: string;
}
```

and 2 regular classes.... lets say Foo and Bar. Both extend the BaseEntity.
```
class Foo extends BaseEntity {}
class Bar extends BaseEntity {
  constructor(foo:Foo) {
    this.foo = foo;
  }
  @OneToOne()
  readonly foo: Foo;
}
```
if Bar is `@OneToOne` with Foo then the MetadataDiscovery fails with 
"TypeError: Cannot read property 'fieldName' of undefined".

Now IF, i remove the base class and simply add the PrimaryKey to Foo and Bar... it works fine.
I read some other issues where you allow only 1 level of abstraction which is fine, but it seems to fail in this basic case.

**Stack trace**
```
TypeError: Cannot read property 'fieldName' of undefined
    at MetadataDiscovery.initManyToOneFieldName (/workspace/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:167:72)
    at MetadataDiscovery.initFieldName (/workspace/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:159:35)
    at /workspace/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:36:86
    at Array.forEach (<anonymous>)
    at /workspace/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:36:65
    at Array.forEach (<anonymous>)
    at MetadataDiscovery.discover (/workspace/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:36:18)
    at Function.init (/workspace/node_modules/mikro-orm/dist/MikroORM.js:45:24)
    at Function.init (/workspace/tools/orm.utils.ts:13:21)
    at Function.runCreateSchema (/workspace/tools/orm.utils.ts:26:21)
    at create (/workspace/tools/cli.ts:28:13)
    at run (/workspace/tools/cli.ts:16:9)
```

**To Reproduce**
see above

**Expected behavior**
I would expect it to be able to find the PrimaryKey on the base class when a OneToOne is used.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 12.4.1 |
| typescript | 3.7.4 |
| mikro-orm | 3.3.3|
| pg | 7.18.1 |

**Comment by B4nan** [comment]
Can you try again with 3.4.1? There were quite a lot of bug fixes in 3.x versions.

**Comment by UTGuy** [comment]
yes I can, gimme a few minutes

**Comment by B4nan** [comment]
Also, its `@OneToOne()`, in your example you have just `@OneToOne`, but I guess that is just an error in your example?

**Comment by UTGuy** [comment]
Fixed the example thanks.

**Comment by UTGuy** [comment]
still fails with 3.4.1

**Comment by B4nan** [comment]
Do you register your base entity? Is it discovered? (if you are not sure, enable `debug` mode to see).

**Comment by B4nan** [comment]
This is passing for me:

```typescript
import { unlinkSync } from 'fs';
import { Entity, PrimaryKey, Property, MikroORM, ReflectMetadataProvider, OneToOne } from '../../lib';
import { SqliteDriver } from '../../lib/drivers/SqliteDriver';

abstract class BaseEntity {

  @PrimaryKey()
  id!: string;

}

@Entity()
class Foo extends BaseEntity { }

@Entity()
class Bar extends BaseEntity {

  @OneToOne(() => Foo)
  foo!: Foo;

}

describe('GH issue 409', () => {

  let orm: MikroORM<SqliteDriver>;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [Foo, Bar, BaseEntity],
      dbName: `mikro_orm_test_gh_409`,
      type: 'sqlite',
      metadataProvider: ReflectMetadataProvider,
      cache: { enabled: false },
    });
    await orm.getSchemaGenerator().ensureDatabase();
  });

  afterAll(async () => {
    await orm.close(true);
    unlinkSync(orm.config.get('dbName')!);
  });

  test(`schema updates respect default values`, async () => {
    await orm.getSchemaGenerator().dropSchema();
    await orm.getSchemaGenerator().createSchema();
  });

});
```

**Comment by UTGuy** [comment]
![image](https://user-images.githubusercontent.com/1872858/76806167-15c30580-67b7-11ea-95fa-3ddddc678000.png)

**Comment by UTGuy** [comment]
Found it.... one of the classes was missing `@Entity`. It was my mistake. Thanks for looking into it so fast though.

**Comment by bigbizze** [comment]
If anyone else runs into this problem, I have had the issue before due to an "onUpdate" callback specified in a decorator that was returning the wrong datatype.
