### ISSUE TITLE
[discuss] docs/on-boarding/ux

### ISSUE THREAD

**Issue by desmap** [mikro-orm/mikro-orm#411]
After evaluating mikro-orm (MO) yesterday, I wanted to toy a bit around with MO but the actual experience of getting started was rocky. So, it's an issue about your docs and how to get started and maybe a reason why MO doesn't take off despite having the best architecture.

First I couldn't get passed this:
```
7:19:59 AM - File change detected. Starting incremental compilation...
api    |
api    | node_modules/mikro-orm/dist/connections/AbstractSqlConnection.d.ts(1,8): error TS1259: Module '"/app/node_modules/knex/types/index"' can only be default-imported using the 'esModuleInterop' flag
api    | node_modules/mikro-orm/dist/query/QueryBuilderHelper.d.ts(1,8): error TS1259: Module '"/app/node_modules/knex/types/index"' can only be default-imported using the 'esModuleInterop' flag
api    |
api    | 7:19:59 AM - Found 2 errors. Watching for file changes.
```
My code:
```
import { MikroORM } from 'mikro-orm'
import { MongoDriver } from 'mikro-orm/dist/drivers/MongoDriver'

const main = async () => {
  const orm = await MikroORM.init({
    entitiesDirs: ['./build/**/entities'],
    driver: MongoDriver,
    driverOptions: {
      host: 'db',
      user: 'root',
      password: '<mypass>',
    },
  })
}

main()
````

- So, the reason I opted for MO was that the Mongo implementation should be better than the one from TypeORM (in particular relations) but when I see that the systems tries to get abstract SQL drivers and Knex => why all this baggage if I just want Mongo? Besides, I know that I have to set the esModuleInterop now but I would have be nice to have a note about this because every error early on just increases the risk that people bail out

Then:
- The docs have to clearly state how to import `MikroORM`. On the node server side people are still used to const/require and a default import; no big thing but still; you want to sell your lib, you want to get people into the funnel but if I have to 'think' to just get started I will opt out; it took me some time because your docs state nowhere how to import MikroORM

**Comment by B4nan** [comment]
> First I couldn't get passed this:

Well that error is self explanatory, you just need to enable `esModuleInterop` in your tsconfig, how is that an issue? Sure, will note that in the docs. 

Also your code is unnecessary complex, it can be done this way (which is the way described everywhere in the docs):

```typescript
import { MikroORM } from 'mikro-orm'

const orm = await MikroORM.init({
    entitiesDirs: ['./build/**/entities'],
    type: 'mongo',
    host: 'db',
    user: 'root',
    password: '<mypass>',
})

main()
```

>  why all this baggage if I just want Mongo?

Knex in bundled, this might change in v4, but I do not feel that is a big issue. Its just knex, not the sql connectors. A lot of the internals are SQL only (schema generator, migrations) and they depend on it. 

> The docs have to clearly state how to import MikroORM. On the node server side people are still used to const/require and a default import; no big thing but still; you want to sell your lib, you want to get people into the funnel but if I have to 'think' to just get started I will opt out; it took me some time because your docs state nowhere how to import MikroORM

I don't follow, what do you mean? You can import via require too, that has nothing to do with the ORM itself. Maybe add some example?

**Comment by B4nan** [comment]
I am sure it would be really helpful to add some tutorials (I guess one for mongo and one for mysql, as all sql drivers are almost the same) that would guide one thru the initial setup in detail. The quickstart in the readme tries to do this, but its generic and explains various options, we could have more "narrowed/specific" tutorials.

Also the quickstart is now not part of the docs, its only in readme...

**Comment by desmap** [comment]
> Also your code is unnecessary complex

I have this driverOptions sub-object idea from your docs here: https://mikro-orm.io/docs/configuration#driver

> You can import via require too,

Just tried again and now it works, before it didn't. Strange. I tried both as default require and within braces. Was driving me nuts, ok my bad, cannot reproduce it anymore.

More stuff:
- When I just declare an `entitiesDirsTs` it still ask for the build dir `entitiesDirs`; just providing latter works too but just the former doesn't, so why do I need the former at all?
- It starts now...
```
8:01:59 AM - File change detected. Starting incremental compilation...
api    |
api    |
api    | 8:02:00 AM - Found 0 errors. Watching for file changes.
```
then after a while (~1min) I get:
```
api    | MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
api    |     at Timeout._onTimeout (/app/node_modules/mongodb/lib/core/sdam/topology.js:430:30)
api    |     at listOnTimeout (internal/timers.js:549:17)
api    |     at processTimers (internal/timers.js:492:7) {
api    |   name: 'MongoServerSelectionError',
api    |   reason: TopologyDescription {
api    |     type: 'Single',
api    |     setName: null,
api    |     maxSetVersion: null,
api    |     maxElectionId: null,
api    |     servers: Map(1) { '127.0.0.1:27017' => [ServerDescription] },
api    |     stale: false,
api    |     compatible: true,
api    |     compatibilityError: null,
api    |     logicalSessionTimeoutMinutes: null,
api    |     heartbeatFrequencyMS: 10000,
api    |     localThresholdMS: 15,
api    |     commonWireVersion: null
api    |   },
api    |   [Symbol(mongoErrorContextSymbol)]: {}
api    | }
```

My new code:
```
import { MikroORM } from 'mikro-orm'
import { MongoDriver } from 'mikro-orm/dist/drivers/MongoDriver'

const main = async () => {
  try {
    const orm = await MikroORM.init({
      entitiesDirs: ['./build/**/entities'],
      entitiesDirsTs: ['./src/**/entities'],
      dbName: 'hello',
      driver: MongoDriver,
      host: 'db',
      user: 'root',
      password: '<mypass>',
    })
    console.log('Hello World')
  } catch (e) {
    console.log(e)
  }
}

```
I assume that still need to define a clientUrl with db as host since MO seems to ignore `host`

**Comment by desmap** [comment]
yep that was the reason, now it works:
```
import { MikroORM } from 'mikro-orm'
import { MongoDriver } from 'mikro-orm/dist/drivers/MongoDriver'

const main = async () => {
  try {
    const orm = await MikroORM.init({
      entitiesDirs: ['./build/**/entities'],
      entitiesDirsTs: ['./src/**/entities'],
      dbName: 'hello',
      driver: MongoDriver,
      clientUrl: `mongodb://root:${process.env.MONGO_INITDB_ROOT_PASSWORD}@db:27017`,
    })
    console.log('Hello World')
  } catch (e) {
    console.log(e)
  }
}

main()
```

**Comment by desmap** [comment]
I don't need `driver: MongoDriver,` either, so it's even cleaner...

**Comment by desmap** [comment]
Besides, do you think that supporting SQL is important? I mean, TypeORM excels in SQL-land, is still a bit maintained and supporting many different DBs is challenging (even Knex is full of inconsistencies). 

Just focusing on one, eg Mongo, could lead to a better overall ux and the options out there are subsubpar (Mongoose, Typegoose, etc.)

Just wondering...

**Comment by B4nan** [comment]
> I have this driverOptions sub-object idea from your docs here: https://mikro-orm.io/docs/configuration#driver

It is there to allow you to override driver level settings (e.g. for mongo you pass things like `useUnifiedTopology`), but one should prefer ORM configuration options where possible. 

> When I just declare an entitiesDirsTs it still ask for the build dir entitiesDirs; just providing latter works too but just the former doesn't, so why do I need the former at all?

This is actually documented (maybe a bit hidden), `entitiesDirsTs` is optional as its only for improving the discovery time (when using the default ts-morph metadata provider, otherwise its not needed). 

https://mikro-orm.io/docs/metadata-providers/#tsmorphmetadataprovider

> I assume that I still need to define a clientUrl with db as host since MO seems to ignore host

Hmm looking at the mongo connection class and you are right, it only cares about `clientUrl`. 

> I don't need driver: MongoDriver, either, so it's even cleaner...

Yes, mongo driver is the default, but that will change in v4 (will remove default value for this). You are supposed to use `type: 'mongo'`, that `driver` option is for using custom drivers mainly (its valid to use it like this, but its more convenient with the `type` option).

**Comment by desmap** [comment]
> but that will change in v4

Really? It would be a breaking change then (just added type: 'mongo' ;)

**Comment by B4nan** [comment]
> Besides, do you think that supporting SQL is important? I mean, TypeORM excels in SQL-land, is still a bit maintained and supporting many different DBs is challenging (even Knex is full of inconsistencies).

Yes it is, I am sure there are more SQL users currently. Also I would not say that TypeORM excels in SQL land, I feel like the problems with TypeORM are pretty much driver independent. The point is that MikroORM gives you different approach (UoW), that is even more important for SQL than for mongo (although now we have transactions support in mongo too).

> Really? It would be a breaking change then (just added type: 'mongo' ;)

Yes, that is why I said it will change in v4 and not in v3.5. Its a breaking change, therefore it will be part of major release. Having default value for this was a wrong decision.

**Comment by desmap** [comment]
> MikroORM gives you different approach (UoW), 

Right! And The need for an ORM is with SQL way bigger than with Mongo where you wouldn't die without one.

Ok, then let me dive deeper, feels better now and thanks again for the being responsive! :) 

Shall we close this issue or do you want to keep it open for on-boarding doc improvements?

**Comment by B4nan** [comment]
I guess we can close this, added the note about `esModuleInterop` and `type` in the docs. Feel free to send more suggestions, ideally as concrete as possible.
