### ISSUE TITLE
Updating a versioned entity with a bidirectional OneToOne mapping results in `OptimisticLockError`

### ISSUE THREAD

**Issue by PenguinToast** [mikro-orm/mikro-orm#4121]
**Describe the bug**
When you fetch a versioned entity with a bidirectional OneToOne mapping, and then try to update it, the optimistic concurrency control check will also check the version of the linked entity (which will be `null` in memory, since we only fetched the ID for the linked entity). This causes the update to always fail, unless we also fetch the linked entity or we explicitly filter out the mapping fields during the fetch.

**To Reproduce**
```typescript
import {
  Entity,
  Property,
  PrimaryKey,
  Ref,
  OneToOne,
  OptionalProps,
} from '@mikro-orm/core';
import { MikroORM } from '@mikro-orm/mysql';

@Entity()
export class Book {

  [OptionalProps]?: 'version';

  @PrimaryKey()
  id!: string;

  @OneToOne({ entity: () => Book, inversedBy: 'sequel', ref: true, nullable: true })
  prequel?: Ref<Book>;

  @OneToOne({ entity: () => Book, mappedBy: 'prequel', ref: true, nullable: true })
  sequel?: Ref<Book>;

  @Property({ version: true })
  version!: number;

  @Property()
  title!: string;

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    dbName: 'mikro_orm_ghXXXX',
    entities: [Book],
    port: 3308,
    debug: true,
  });
  await orm.schema.refreshDatabase();
});

afterAll(() => orm.close(true));

test('unnamed', async () => {
  const book1 = orm.em.create(Book, { id: 'book1', title: 'book1' });
  const book2 = orm.em.create(Book, { id: 'book2', title: 'book2', prequel: 'book1' });
  await orm.em.persistAndFlush([book1, book2]);
  orm.em.clear();

  const refetchedBook1 = await orm.em.findOneOrFail(Book, { id: 'book1' });
  refetchedBook1.title = 'updatedBook1';
  await expect(orm.em.flush()).resolves.not.toThrow();
});
```

**Expected behavior**
The update should succeed.

**Versions**
5.6.13 (and latest `master`)

| Dependency | Version |
| - | - |
| node | 18.5.0 |
| typescript | 4.9.0 |
| mikro-orm | 5.6.13 |

**Comment by B4nan** [comment]
Thanks for the repro, looks valid.

**Comment by B4nan** [comment]
The real problem in your repro is that there is a change set generated for the reference too, trying to update its FK. But technically you can update a reference and if it would be versioned, it would fail this way too, so two problems to fix in the end.
