### ISSUE TITLE
Add option to make migrator 'quiet'

### ISSUE THREAD

**Issue by Explodey54** [mikro-orm/mikro-orm#4124]
**Is your feature request related to a problem? Please describe.**
When I'm running tests via Jest I would like to drop schema before every test case, but that results in a lot of 'noise' in log output:
```
console.log
    Processing 'Migration20230222121600InitDb'

      at ../node_modules/@mikro-orm/migrations/Migrator.js:94:45
          at Array.map (<anonymous>)

console.log
    Applied 'Migration20230222121600InitDb'

      at ../node_modules/@mikro-orm/migrations/Migrator.js:95:44
          at Array.map (<anonymous>)
```

**Describe the solution you'd like**
Is it possible to add 'quiet' boolean option to migrator config? Something like this:
```
migrations: {
    quiet: true, // disables all log output from migrator, default: false
},
```

**Comment by SteadEXE** [comment]
I was looking for it too. 
An another solution would be to let the user to override the logger function, so you can make it does nothing or use a different logger, like the NestJS logger service.

Maybe we can implement both, it looks pretty straight forward to implement it.

**Comment by B4nan** [comment]
Sure, go for it. As mentioned above, I'd call it `silent`, and don't forget to implement it for both sql and mongo migrators.
