### ISSUE TITLE
Error: Cannot find module 'mikro-orm' with Webpack

### ISSUE THREAD

**Issue by thekevinbrown** [mikro-orm/mikro-orm#413]
**Describe the bug**
When using the recommended webpack config, `mikro-orm` is excluded from the webpack output because it's configured as an external.

**Stack trace**
Not needed.

**To Reproduce**
1. Bundle a Mikro app with this webpack config: 
https://mikro-orm.io/docs/deployment#webpack-configuration

**Expected behavior**
`mikro-orm` should be available.

**Question**
What was the intent in marking Mikro as an external? I had this previously working with the old version of the docs, so what was the motivation behind this change?

**Comment by thekevinbrown** [comment]
I can confirm that the issue is not version `3.4.1`, but instead the change to the webpack config in the docs. Reverting to the version here resolves the issue for me:

https://github.com/mikro-orm/mikro-orm/blob/f5181b2a42a5f1aa0100f1c49421929b8073403e/docs/docs/deployment.md#webpack-configuration

**Comment by B4nan** [comment]
It works ok for me, trying with your reproduction repository, upgraded to 3.4.1 and nothing changed. Also that config change in docs actually comes from your issue, when I was testing it, I was not even able to run it with your configs, so I had to dig a bit and this was what I found in knex issues. 

```
➜  mikro-orm-webpack-migrations git:(master) ✗ webpack
Hash: 1c4c98677edb5c36201b
Version: webpack 4.41.6
Time: 2881ms
Built at: 03/19/2020 1:26:31 PM
                                               Asset       Size  Chunks             Chunk Names
                      ../lib/src/entities/index.d.ts   24 bytes          [emitted]  
                       ../lib/src/entities/user.d.ts  133 bytes          [emitted]  
                               ../lib/src/index.d.ts   27 bytes          [emitted]  
../lib/src/migrations/1581650991133-InitialData.d.ts  157 bytes          [emitted]  
                                             main.js   31.8 KiB       0  [emitted]  main
Entrypoint main = main.js
[14] ./node_modules/umzug/lib sync 160 bytes {0} [built]
[15] external "mikro-orm" 42 bytes {0} [built]
[37] ./src/index.ts 1.32 KiB {0} [built]
[39] ./src/entities/index.ts 203 bytes {0} [built]
[40] ./src/entities/user.ts 1000 bytes {0} [built]
[79] external "path" 42 bytes {0} [built]
[81] ./src/migrations/1581650991133-InitialData.ts 498 bytes {0} [built]
    + 75 hidden modules

WARNING in ./node_modules/umzug/lib/helper.js 15:15-22
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/umzug/lib/migration.js
 @ ./src/index.ts

WARNING in ./node_modules/umzug/lib/migration.js 81:11-29
Critical dependency: the request of a dependency is an expression
 @ ./src/index.ts

WARNING in ./node_modules/umzug/lib/helper.js 16:15-30
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/umzug/lib/migration.js
 @ ./src/index.ts

WARNING in ./node_modules/umzug/lib/helper.js 19:17-37
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/umzug/lib/migration.js
 @ ./src/index.ts
```

Also more than a week ago I asked you something here: https://github.com/mikro-orm/mikro-orm/issues/362

**Comment by thekevinbrown** [comment]
No worries, I'll do up a proper reproduction and see what I learn.

**Comment by thekevinbrown** [comment]
Here you go: https://github.com/thekevinbrown/mikro-orm-webpack-config

If you're running the webpack output in the same directory as the project, then the external will work fine, because webpack bundles that up as:

```javascript
eval("module.exports = require(\"mikro-orm\");");
```

Interestingly I hit a different error with enums even with the old webpack config, which I'm digging into now.

**Comment by thekevinbrown** [comment]
I can work around the Enum issue like so:

```typescript
export enum UserRole {
  standard = "standard",
  administrator = "administrator",
}

@Entity()
export class User implements IdEntity<User> {
  @PrimaryKey({ type: "number" })
  id!: number;

  @Property({ type: "string" })
  role: UserRole = UserRole.standard;

  // Instead of:
  // @Enum({ type: "UserRole" })
  // role: UserRole = UserRole.standard;
}
```

It looks like there needs to be a different strategy for figuring out Enum values in this context. [This line in MetadataDiscovery.ts](https://github.com/TechInSite/mikro-orm/blob/master/lib/metadata/MetadataDiscovery.ts#L485) won't work in a webpack bundle. I tryed to pass in the actual enum instead of the string, so:

```typescript
@Enum({ type: UserRole })
role: UserRole = UserRole.standard;
```

But while that gives you access to the values for `Utils.extractEnumValues`, it doesn't give you the actual name of the enum, so it looked like I'd need to change the API for the Enum decorator, and at that point I stopped and figured checking back in with @B4nan would be best. Happy to persist if I'm on the right track and submit a PR.

**Comment by B4nan** [comment]
About that enum issue, no need to do anything, you just need to provide the values manually instead of letting the discovery pick them up for you. You were close, you just need to pass a callback there and use `items` instead:

@Enum(() => UserRole) // or @Enum({ items: () => UserRole })
role: UserRole = UserRole.standard;

**Comment by thekevinbrown** [comment]
That's really helpful, thank you!

I created a PR to update the Deployment docs with this pattern: https://github.com/mikro-orm/mikro-orm/pull/417

**Comment by B4nan** [comment]
3.5.0 is out, with fix for the `initEnumValues` thing.

**Comment by thekevinbrown** [comment]
@B4nan I can confirm that 3.5.1 fixes the `initEnumValues` issue for me. Thanks again!

For anyone who's not on Slack that's following this conversation, I'm creating a webpack sample to show how to set up Mikro in that context.

**Comment by B4nan** [comment]
Used the config of yours (from https://github.com/thekevinbrown/express-ts-webpack-example-app) in the docs, so I guess we can close this one. 

Going forward it would be great to add a recipe about general usage with webpack (also including migrations).
