### ISSUE TITLE
Persisting multiple entities with custom types broken on 5.5.0

### ISSUE THREAD

**Issue by maphe** [mikro-orm/mikro-orm#4133]
**Describe the bug**
Trying to upgrade from 5.3 to 5.6, I'm running into issues. I can't tell if there are breaking changes that I should apply to the code base or if that's just a bug. I tracked the issue as much as I could, it starts happening on 5.5.0 when I have a custom type on an entity.

**Stack trace**
```
Cannot read properties of undefined (reading 'id')
TypeError: Cannot read properties of undefined (reading 'id')
    at ChangeSetPersister.persistNewEntitiesBatch (node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:126:53)
    at async ChangeSetPersister.persistNewEntities (node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:102:13)
    at async ChangeSetPersister.runForEachSchema (node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:68:13)
    at async UnitOfWork.commitCreateChangeSets (node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:704:9)
    at async UnitOfWork.persistToDatabase (node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:656:13)
    at async SqliteConnection.transactional (node_modules/@mikro-orm/knex/AbstractSqlConnection.js:36:25)
    at async UnitOfWork.doCommit (node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:279:17)
    at async UnitOfWork.commit (node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:252:13)
    at async SqlEntityManager.flush (node_modules/@mikro-orm/core/EntityManager.js:753:9)
    at async SqlEntityManager.persistAndFlush (node_modules/@mikro-orm/core/EntityManager.js:698:9)

```

**To Reproduce**
Here's an example with the smallest scope I managed to get: https://gist.github.com/maphe/b29c1f670014c626bac83a71e64cf907

**Expected behavior**
Should not throw an error on persist.

**Additional context**
It only occurs when I persist more than 1 entity. Changing line 80 to 
```
orm.em.fork().persistAndFlush([u1]);
```
works fine.

**Versions**

| Dependency | Version |
| - | - |
| node | `v18.14.2` |
| typescript | `4.9.5` |
| mikro-orm | `5.5.0` and above |
| your-driver | `sqlite` |

**Comment by B4nan** [comment]
The issue is indeed relevant, but I wanted to mention this too:

```ts
orm.em.fork().persistAndFlush([u1, u2]);
orm.em.fork().clear();
```

Your code looks like you fork everywhere without much thinking, probably to get around the global context validation. Those two lines don't make much sense together, especially the second one. You create a clean fork via `em.fork()` and clear it, that will never have any effect, even if the clear would do something, you do it on the freshly created fork that you never store anywhere. Also note that you are missing an await on the first line.

Here is a "fixed" test case that is truly minimal, maybe you will find it useful:

```ts
import { Entity, PrimaryKey, Property, Type } from '@mikro-orm/core';
import { MikroORM } from '@mikro-orm/sqlite';

class RailsArrayType extends Type<string[], string> {

  convertToDatabaseValue(values: string[]): string {
    if (!values) {
      return null!;
    }

    // Convert to Set and back to Array to remove duplicates
    return ['---', ...[...new Set(values)].map(value => `- ${value}`)].join('\n');
  }

  convertToJSValue(value: string): string[] {
    if (!value) {
      return [];
    }

    return [...value.matchAll(/\n- (.*)/g)].map(matches => matches[1]);
  }

  getColumnType(): string {
    return 'text';
  }

}

@Entity()
class LegacyUser {

  @PrimaryKey()
  id!: number;

  @Property()
  username!: string;

  @Property({
    type: RailsArrayType,
  })
  teams!: string[];

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [LegacyUser],
    name: 'sfp_test',
    dbName: `:memory:`,
  });
  await orm.schema.refreshDatabase();
});

afterAll(async () => {
  await orm.close(true);
});

it('should work', async () => {
  const u1 = new LegacyUser();
  u1.username = 'test';
  u1.teams = ['engineering', 'product'];

  const u2 = new LegacyUser();
  u2.username = 'test';
  u2.teams = ['engineering', 'product'];

  await orm.em.persistAndFlush([u1, u2]);
  orm.em.clear();

  const user = await orm.em.findOneOrFail(LegacyUser, 1);
  expect(user.username).toEqual('test');
});
```

(the ORM tests have global context allowed)

**Comment by B4nan** [comment]
I see, v5.5.0 started using the returning statements in sqlite, but knex with sqlite can't detect returning statements automatically, so to get around that we use a regexp and it didn't support multiline queries (which your type produces).

**Comment by maphe** [comment]
Cool thank you. Yeah sorry about the spec I provided, I'll admit I just spent more time that I wanted tracking down the issue, at the end I copy/pasted an old spec and quick patched it just so the error can be reproduced. Not something I would do in production, but thanks for the heads up nonetheless.
