### ISSUE TITLE
Bug: Populating automatic 

### ISSUE THREAD

**Issue by tidytrax** [mikro-orm/mikro-orm#4152]
Hello, I have a  AuthGuard(nestJs) it fetchOne user and load the entity, and pass througth the request

`select userId, name, from user where userId = '1'`

if next query has the same userId value in the response it populate automatic,
Using query debug is possible to see that the query its corret,, no join.
`select id, name, userId from x`

`x.userId = User
`
to make work I have to do before each query

`em.clear()`

Then run...

`findAndCount, findOne, findOneOrFail`

`x.userId = string`

it only happens when the result match the same value, if the value is not the same as the userId, it returns a string normal.

**Comment by B4nan** [comment]
You need to have separate contexts for each request, you are probably not doing that.

https://mikro-orm.io/docs/identity-map#why-is-request-context-needed
