### ISSUE TITLE
Entities not populated correctly when using `JOINED` strategy or query builder

### ISSUE THREAD

**Issue by nstojanovikj** [mikro-orm/mikro-orm#4160]
**Describe the bug**
As the title says, it seems like in certain cases the entities are no populated in full when using `JOINED` load strategy or query builder. We experienced this issue with nested entities along with one-to-one relation, but not sure if there are other cases where this might be an issue.

**To Reproduce**
```ts
import { Collection, Entity, LoadStrategy, ManyToOne, OneToMany, OneToOne, OptionalProps, PrimaryKey, Property, Rel } from '@mikro-orm/core';
import { MikroORM } from '@mikro-orm/better-sqlite';

@Entity()
class Account {

  [OptionalProps]?: 'client';

  @PrimaryKey()
  id!: string;

  @Property()
  name!: string;

  @OneToOne(() => Client, c => c.account)
  client!: Rel<Client>;

}

@Entity()
class Client {

  @OneToOne({ primary: true, entity: () => Account })
  account!: Account;

  @OneToMany(() => Brand, brand => brand.client, { orphanRemoval: true })
  brands = new Collection<Brand>(this);

}

@Entity()
class Brand {

  @PrimaryKey()
  id!: string;

  @ManyToOne(() => Client)
  client!: Client;

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [Client, Account, Brand],
    dbName: ':memory:',
  });
  await orm.schema.refreshDatabase();

  const account1 = orm.em.create(Account, { name: 'Account 1', id: '1' });
  const client1 = orm.em.create(Client, { account: account1 });
  orm.em.create(Brand, { id: '1', client: client1 });
  orm.em.create(Brand, { id: '2', client: client1 });
  await orm.em.flush();
});

beforeEach(async () => {
  orm.em.clear();
});

afterAll(async () => {
  await orm.close(true);
});

it('populate with select-in strategy', async () => {
  const brands1 = await orm.em.find(Brand, {}, {
    populate: ['client.account'],
    strategy: LoadStrategy.SELECT_IN,
  });

  expect(brands1[0].client.account).toMatchObject({ id: '1', name: 'Account 1' });
  expect(brands1[1].client.account).toMatchObject({ id: '1', name: 'Account 1' });
});

it('populate with joined strategy', async () => {
  const brands1 = await orm.em.find(Brand, {}, {
    populate: ['client.account'],
    strategy: LoadStrategy.JOINED,
  });

  expect(brands1[0].client.account).toMatchObject({ id: '1', name: 'Account 1' });
  expect(brands1[1].client.account).toMatchObject({ id: '1', name: 'Account 1' });
});

it('populate with query builder', async () => {
  const brands2 = await orm.em
    .createQueryBuilder(Brand, 'brand')
    .leftJoinAndSelect('brand.client', 'client')
    .leftJoinAndSelect('client.account', 'account');

  expect(brands2[0].client.account).toMatchObject({ id: '1', name: 'Account 1' });
  expect(brands2[1].client.account).toMatchObject({ id: '1', name: 'Account 1' });
});
```

**Expected behavior**
The entities to be populated in full and `account` to not be `undefined` in this case. 

**Additional context**
This case seems to work fine with `SELECT_IN` strategy, we only experienced the issue with `JOINED` strategy or when using query builder. It's also interesting that only some of the entities are not populated and not all. In the case above, the test fails on the second entity, but the first is as expected.

**Versions**

| Dependency | Version |
| - | - |
| node | 18.15.0 |
| typescript | 5.0.2 |
| mikro-orm | 5.6.15 |
| @mikro-orm/postgresql	 | 5.6.15 |

**Comment by ThatsARapp** [comment]
I realized I didn't have my second test written correctIy. I updated it. I can also create a new issue if you like regarding the following.

1. When I switch to `SELECT_IN` both of my test cases pass.
2. https://mikro-orm.io/docs/nested-populate#filter-on-populated-entities indicates that using the `ALL` hint would find **all** comments for a post that has a comment with `userUuid: 'user2'` as opposed to `INFER` which would only find comments with `userUuid: 'user2'`.
3. In my second test where I first find `post1`, all of the nested comments are populated. At no point do I ever explicitly load in `comment1`, but first finding `post1` has a side effect where it is added.
