### ISSUE TITLE
Anormal time spent in `initializeCollections` (quadratic behaviour somewhere ?)

### ISSUE THREAD

**Issue by rvion** [mikro-orm/mikro-orm#4171]
## performance issue in `initializeCollections`

(using "5.6.16-dev.6", but the issue was present in previous versions too)

👋 Hello @B4nan  

I have a worker that process quite a few rows from various tables in batch.

## `Initialize Collections` takes way more time that we expect 🤔 

![image](https://user-images.githubusercontent.com/2150990/227898615-1884383c-8340-47fb-8d6f-e483f8e86398.png)

## some batch hints about some **quadratic behaviours**: here:

  -  🟢 `150ms` only to find and hydrate models
  -  🔴  `12seconds` to initialize collections

![image](https://user-images.githubusercontent.com/2150990/227900474-a1be0106-8f59-4ad6-89fa-e1286a169850.png)

------

## possible culprit: 

at https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/entity/EntityLoader.ts#L223

![image](https://user-images.githubusercontent.com/2150990/227901964-75abc777-3f48-4b15-8c47-60adf2e4e909.png)

- could it be something around this `filter` within a  `for` ?
- or the fact `helper(entity).getPrimaryKey()` is not cached above the filter closure ?
- or some hydratation checks that runs too many times on already instanciated entities ?

```ts
  private initializeOneToMany<T>(filtered: T[], children: AnyEntity[], prop: EntityProperty, field: keyof T): void {
    for (const entity of filtered) {
      const items = children.filter(child => {
        if (prop.targetMeta!.properties[prop.mappedBy].mapToPk) {
          return child[prop.mappedBy] as unknown === helper(entity).getPrimaryKey();
        }

        return Reference.unwrapReference(child[prop.mappedBy]) as unknown === entity;
      });

      (entity[field] as unknown as Collection<AnyEntity>).hydrate(items);
    }
  }
 ```

--------------

@B4nan Not quite sure what is the best way to help you reproduce this. not event sure if it's worth anything in case you'll simply spot the problem by just looking at the code. 

I'm a bit lost there, but tell me if I can do anything to help !

Best

**Comment by B4nan** [comment]
Do you use composite PKs, or FKs as PKs heavily? That could add some overhead to the `getPrimaryKey ` call. But that part is executed only when you use `mapToPk`, do you use that?

Could be more about the hydration, especially if your entities are huge. The `Collection.hydrate` does quite a lot of things, including propagation.

Can't help much without a complete reproduction, this will be probably very specific to your entity definition and number of items in the context. You know what method does it, so it should be quite easy, or what am I missing? It is about populating some to-many relation, so just create the entity definitions, populate with a lot of random data and do the find call.

**Comment by rvion** [comment]
thanks for the quick response; **I'll make a repro !** I understand those kind of issues without context can be quite annoying x)

In the meantime, just sharing this in case it rings a bell.

![image](https://user-images.githubusercontent.com/2150990/227912646-b96214e9-4738-41d2-b710-106e64fb4d50.png)

our collections are large (a few dozen to a few thouthands items max) but nothing too crazy; never more than 3/4000 instances.

I think we should not be using mapToPk as we only have basic PKs(id) and non composite Foreign keys 🤔 but the execution cost near the lines 170 / 171 / 174 feels wrong.

**Comment by B4nan** [comment]
That's indeed very interesting/weird. But at the same time, I feel like this will be much easier to fix than a hydration/propagation issue :]

I guess we will just need to chunk the `children` array into groups in one go instead of filtering it again and again for every entity.

**Comment by rvion** [comment]
Yeah, that was my initial guess; with ~1000 items in batch, each having ~1000 children, fusing the loop, or optimising the comparaison could probably brings a 2 or 3 magnitude order speedup.

**Comment by B4nan** [comment]
> Yeah, that was my initial guess; with ~1000 items in batch, each having ~1000 children, fusing the loop, or optimising the comparaison could probably brings a 2 or 3 magnitude order speedup.

Well, if you want to have 1 million entities in context, I'm afraid it will never be very fast :D 

Looks like this is enough to reproduce:

```ts
test('perf: populating many large one to many collections (#4171)', async () => {
  console.time('create');

  for (let i = 1; i <= 1000; i++) {
    const author = new Author2('Jon Snow ' + i, `snow-${i}@wall.st`);

    for (let j = 1; j <= 20; j++) {
      author.books.add(new Book2(`My Life on The Wall, part ${i}/${j}`, author));
    }

    await orm.em.fork().persist(author).flush();
  }

  console.timeEnd('create');

  console.time('find');
  await orm.em.fork().find(Author2, {}, { populate: ['books'] });
  console.timeEnd('find');
});
```

If I comment the problematic filter line and use an empty array instead, the `find` time goes from 9s to 0,5s.

**Comment by gggdomi** [comment]
From your repro, this may help: https://stackblitz.com/edit/mikro-orm-repro-bzsaor?file=test.ts

It's surprising:
- test 1: many authors, few books per author: create is fast (scales ~linearly), find does not scale linearly at all
- test 2+3: few authors, many books per author: find is fast (scales ~linearly), create does not scale linearly at all

<img width="886" alt="Capture d’écran 2023-03-27 à 13 49 59" src="https://user-images.githubusercontent.com/11262934/227933516-9fd4e4d5-014d-4bdd-a4e1-b4814d9670a7.png">

**Comment by B4nan** [comment]
The slow part is actually reading the relation property (so the `child[prop.mappedBy]` bit), as that is defined as a lazy getter on the prototype to allow propagation. That itself could be hopefully improved if we define the get/set pair directly on the instance after we create it, and it could be gotten around by using `child.__helper.__data[prop.mappedBy]` instead, so using the underlying value instead of the getter.

**Comment by rvion** [comment]
I tried to quickly patch the code like this:

```ts
initializeOneToMany(filtered, children, prop, field) {
   for (const entity of filtered) {
       const items = children.filter(child => {
           // /* 🔴 */ if (prop.targetMeta.properties[prop.mappedBy].mapToPk) {
           // /* 🔴 */     return child[prop.mappedBy] === (0, wrap_1.helper)(entity).getPrimaryKey();
           // /* 🔴 */ }
           // /* 🔴 */ return Reference_1.Reference.unwrapReference(child[prop.mappedBy]) === entity;

           return Reference_1.Reference.unwrapReference(child.__helper.__data[prop.mappedBy]) === entity;
       });
       entity[field].hydrate(items);
   }
}
```

Everything is indeed faster , but the cost remains high in unex

![image](https://user-images.githubusercontent.com/2150990/227985027-ba084d5b-fa31-42cf-9a10-3c3d3acbe6cb.png)

![image](https://user-images.githubusercontent.com/2150990/227985306-48d1c576-2cb6-4366-804f-c8ce7ad09dc3.png)
