### ISSUE TITLE
Composite key documentation is hard to understand

### ISSUE THREAD

**Issue by ttsirkia** [mikro-orm/mikro-orm#419]
I have some problems to understand the documentation for the composite keys, especially the use cases. I hope that pointing out these issues might help to improve the documentation and make the examples to be more understandable.

## Use-case 1

```ts
@Entity()
export class ArticleAttribute {

  @ManyToOne()
  article: Article;

  @PrimaryKey()
  attribute: string;

  [PrimaryKeyType]: [number, number]; // this is needed for proper type checks in `FilterQuery`
```

Why the `PrimaryKeyType` is here `[number, number]` as the `attribute` here is a string? Does the many-to-one relation automatically force that as the first primary key? In the following example `@ManyToOne({ primary: true })` is being used.

## Use-case 2

```ts
@OneToOne(() => Address2, address => address.author, { cascade: [Cascade.ALL] })
```

Where does this `Address2` come from? And `address.author`? The `PrimaryKeyType` is now missing, when it can be omitted?

## Use-case 3

`OrderItem` does not contain `PrimaryKeyType`. Can it be omitted and why?

**Comment by B4nan** [comment]
> Why the PrimaryKeyType is here [number, number] as the attribute here is a string? Does the many-to-one relation automatically force that as the first primary key? In the following example @ManyToOne({ primary: true }) is being used.

It should be `[PrimaryKeyType]: [number, string]`. number being the type of article's primary key. And you are right, there should be `primary: true`. 

> Where does this Address2 come from? And address.author? The PrimaryKeyType is now missing, when it can be omitted?

Also bad copy paste, I am using different entities in the tests... 

> OrderItem does not contain PrimaryKeyType. Can it be omitted and why?

It is needed for the ORM to understand your primary key type, one example being when querying by the PK like this: `em.findOne(Address, 123)`, here the type of the entity is type checked, so the ORM needs to know it is a number. 

So as long as you are not querying the entity via PK shorthand like this, you are fine. Also, it is not needed when you use `id/_id/uuid` as your primary key. You can always make the condition explicit, e.g. `em.findOne(Address, { user: 123 })`, then it won't be necessary. 

Oh god, so many mistakes on one page, sorry about that, I should have reviewed that in the morning :D

**Comment by ttsirkia** [comment]
OK, I guess that examples are easier to understand now. :-) Thanks for the great work!
