### ISSUE TITLE
Add partial fetching of nested embeddable 

### ISSUE THREAD

**Issue by acrosett** [mikro-orm/mikro-orm#4199]
Given the following entity with an object embeddable :
```
@Entity()
export class User {

  @PrimaryKey({serializedName: '_id' })
  _id: ObjectId;
  
  @Property()
  email: string;

  @Embedded(() => ProfileSchema, { nullable: true, object: true })
  profile: ProfileSchema;

}

@Embeddable()
export class ProfileSchema {

  @Property({ nullable: true })
  first: string;

  @Property()
  @Index()
  last: string;

  @Property()
  age: number;

}
```

I would like the following request :

`await em.find(User, { email : 'exemple@mail.com' }, { fields: ['email', 'profile.first', 'profile.age']})`

to return the following partial entity :
```
{
  email: 'exemple@mail.com',
  profile: { first: 'John', age: 30 },
}
```

**Comment by B4nan** [comment]
How do you expect that to work with object embeddable? It is all a single field, you cant load it partially.

**Comment by acrosett** [comment]
I would expect it to work like the [project feature of MongoDB](https://www.mongodb.com/docs/manual/tutorial/project-fields-from-query-results/#return-specific-fields-in-embedded-documents), by applying a filter after the initial load.

**Comment by B4nan** [comment]
Ok that could work for sure.

**Comment by B4nan** [comment]
Closing via #4203
