### ISSUE TITLE
Specifying a columnType in Property decorator doesn't produce desired schema

### ISSUE THREAD

**Issue by followben** [mikro-orm/mikro-orm#420]
**Describe the bug**
I'm trying to create an entity number property that maps to a Postgres numeric column with a specific precision and scale. However specifying the `columnType` option in the `@Property()` decorator doesn't seem to result in anything but `int4`.

**To Reproduce**
1. Create an entity with the following property
```
@Property({ type: 'number', columnType: 'numeric(10, 2)', default: 0 })
	myAttribute: number = 0.00;
```
2. Run `schemaGenerator.createSchema()` and inspect the dump

**Expected behavior**
The resulting sql builds a statement that includes the column definition as `"my_attribute" numeric(10,2) not null default 0`

**Actual behavior**
The resulting sql builds a statement that includes the column definition as `"my_attribute" int4 not null default 0`

**Versions**

| Dependency | Version |
| - | - |
| node | 13.9.1 |
| typescript | 3.8.3 |
| mikro-orm | 3.5.1 |
| pg | 7.18.2 |

**Comment by B4nan** [comment]
Hmm I guess that comes from those metadata changes in composite keys PR... Could you try with 3.4 to see if it works there?

**Comment by followben** [comment]
Yup - 3.4 will work because `initColumnType()` in MetadataDiscovery leaves columnType in place and that's what's used for schema generation. In the latest version it ignores columnType and looks for columnTypes. Because that can't be populated, it uses the 1st value returned from `getTypeDefinition()`.

**Comment by B4nan** [comment]
Can you try to add `rename(options, 'columnType', 'columnTypes');` to `EntitySchema.addProperty`? Should be just about that.

**Comment by followben** [comment]
That did it.

**Comment by followben** [comment]
Thanks @B4nan. You want a PR, or should I just look out for a point release?

**Comment by B4nan** [comment]
Will release this later today.
