### ISSUE TITLE
Add link to create reproduction to docs/GitHub issue template

### ISSUE THREAD

**Issue by SpencerKaiser** [mikro-orm/mikro-orm#4201]
Creating a reproduction is very helpful for maintainers (and often times the dev experiencing the perceived issue) but currently it's difficult to find how to make one.

If a handful of StackBlitz projects were maintained and provided either through the README and/or through an update to the Bug Report issue template, it would help others quickly provide more meaningful feedback.

Examples of other projects doing something similar:
- [Chakra UI](https://github.com/chakra-ui/chakra-ui#codesandbox-templates)
- [Next.js](https://github.com/vercel/next.js/issues/new?assignees=&labels=template%3A+bug&template=1.bug_report.yml) (scroll to `Link to the code that reproduces this issue`)

[Recent StackBlitz for v6](http://stackblitz.com/edit/mikro-orm-v6-strict-partial-loading)

**Comment by thiagomini** [comment]
Totally agreed! I do have public a minimum-repro repository using `schemas`. I hope it can be useful for someone out here:

https://github.com/thiagomini/mikro-orm-repro
