### ISSUE TITLE
Entity Generation

### ISSUE THREAD

**Issue by FredericLatour** [mikro-orm/mikro-orm#421]
I used entity generator to create entities from an existing mysql database and no index were generated?
Is it a limitation of the current generator or am I supposed to get index (@Index, ...) information generated?

Also, decimal columns have no range and scale information. How can you handle migration or create schema without this information?

**Comment by B4nan** [comment]
Missing feature, entity generator was added before support for indexes (`@Index` and `@Unique` decorators).

> Also, decimal columns have no range and scale information. How can you handle migration or create schema without this information?

You can use something like `@Property({ columnType: 'decimal(10, 2)' })`. But this is also something that could be improved.
