### ISSUE TITLE
JOINED strategy return wrong merged result when using binary(16) primary key

### ISSUE THREAD

**Issue by kangugau** [mikro-orm/mikro-orm#4219]
**Describe the bug**

**To Reproduce**
Assume I have entities like these
``` Javascript
@Entity()
class Customer {
  @PrimaryKey({
    name: customerTableMap.cust_id,
    type: UuidBinaryType,
  })
  uuid: string = v1();

  @ManyToMany(() => Role, 'customers', {
    owner: true,
  })
  roles: Role[];
}

class Role {
  @PrimaryKey({
    type: UuidBinaryType,
  })
  uuid: string = v1();

  @ManyToMany(() => Customer, 'roles')
  customers: Customer[];
}

class UuidBinaryType extends Type<string, Buffer> {
  convertToDatabaseValue(uuid) {
    return uuid && Buffer.from(parse(uuid));
  }

  convertToJSValue(bin) {
    if (!bin) return null;
    if (typeof bin === 'string') return bin;
    return stringify(bin);
  }

  getColumnType() {
    return 'binary(16)';
  }
}
```
Then below code return wrong merged result
```js
this.customerRepository.findAll({
   fields: [ 'uuid', { roles: ['uuid'] } ],
   strategy: LoadStrategy.JOINED,
});
```

I think it is caused by the util getHash function
``` javascript
// ./node_modules/@mikro-orm/core/utils/Utils.js
    static getPrimaryKeyHash(pks) {
        return pks.join(this.PK_SEPARATOR);
    }
```
**Expected behavior**
Return merged result properly

**Versions**

| Dependency | Version |
| - | - |
| node | v19.7.0 |
| typescript | 4.7.4 |
| mikro-orm | 5.6.16 |
| @mikro-orm/mysql | 5.6.16 |

**Comment by B4nan** [comment]
Can you be more specific? What does wrong result exactly mean? There are some tests for such setup already I think, bur they are not testing m:n relations. 

Note that you need to use the `Collection` class for m:n relations, you cant map that to array. But that is rather a type level issues, things will probably work fine (but you wont get an array in there, not for loaded entities).

**Comment by kangugau** [comment]
sorry I forgot to put the repo link [https://github.com/kangugau/mikro-orm-joined-bug](https://github.com/kangugau/mikro-orm-joined-bug)

**Comment by B4nan** [comment]
Can you try latest dev version? There are some improvements for how the custom types are handled especially with joined strategy.

**Comment by kangugau** [comment]
It does cause by **Utils.getPrimaryKeyHash** using Array.join to generate the internal primaryKeyHash. From [nodejs Buffer docs](https://nodejs.org/api/buffer.html#buftostringencoding-start-end):
> If encoding is 'utf8' and a byte sequence in the input is not valid UTF-8, then each invalid byte is replaced with the replacement character U+FFFD.

Since uuid buffers are not valid UTF-8, when raw results are merged by mikro-orm, they are very likely to be resolved to the same primaryKeyHash and then are filtered from final results.

**Comment by B4nan** [comment]
I thought the reproduction was supposed to fail somehow? I can see what you are talking about in the `getPrimaryKeyHash` function though.

<img width="623" alt="image" src="https://user-images.githubusercontent.com/615580/233808326-0308e34f-5263-4025-84ac-5a9215e2c59e.png">
