### ISSUE TITLE
Loose typings for find with arrays of mismatching props

### ISSUE THREAD

**Issue by darkbasic** [mikro-orm/mikro-orm#4220]
**Describe the bug**
Mikro-ORM uses the _IN_ predicate whenever your filter is an array of props:
```ts
em.fork().find(Chat, [{ owner: 1, recipient: 3 }, { owner: 1, recipient: 4 }])
```
translates to
```sql
select "c0".* from "chat" as "c0" where ("c0"."owner_id", "c0"."recipient_id") in ((1, 3), (1, 4))
```

So far so good, but what about arrays of mismatching props?
```ts
em.fork().find(Chat, [{ owner: 1, recipient: 3 }, { owner: 2 }])
```
It should either forbid it via typings or treat it like an `$or`:
```ts
em.fork().find(Chat, { $or: [{ owner: 1, recipient: 3 }, { owner: 2 }] })
```
which translates to
```sql
select "c0".* from "chat" as "c0" where (("c0"."owner_id" = 1 and "c0"."recipient_id" = 3) or "c0"."owner_id" = 2)
```
Instead typings allow that and it translates to the following query
```sql
select "c0".* from "chat" as "c0" where ("c0"."owner_id", "c0"."recipient_id") in ((1, 3, '{"c0.owner":2}'))
```
which obviously errors out (`unequal number of entries in row expressions`).

**To Reproduce**
1. `em.fork().find(Chat, [{ owner: 1, recipient: 3 }, { owner: 2 }])`

**Expected behavior**
This should either error out via stricter typings or treat it like an `$or`.

**Versions**

| Dependency | Version |
| - | - |
| node | v18.15.0 |
| typescript | 5.0.3 |
| mikro-orm | 5.6.16 |
| your-driver | postgresql |

**Comment by darkbasic** [comment]
Using the same props but with a mix of IDs and array of IDs leads to a similar problem:
```ts
em.fork().find(Chat, [{ owner: 1, recipient: 3 }, { owner: 1, recipient: [4, 5] }])
```
translates to
```sql
select "c0".* from "chat" as "c0" where ("c0"."owner_id", "c0"."recipient_id") in ((1, 3), (1, 4, 5))
```
which errors out (`unequal number of entries in row expressions`)

**Comment by B4nan** [comment]
Would be good to test this on v6, I wont be doing any refactoring of types in v5, but I guess this works the same in there. 

I would also appreciate complete repro, e.g. I have no idea what your entities look like.

**Comment by darkbasic** [comment]
I will likely have many more because I'm rewriting my dataloader to accomodate for the whole of the filter syntax and I'm encountering lots of edge cases, like https://github.com/mikro-orm/mikro-orm/issues/4222

> I have no idea what your entities look like
Chat has a composite key on owner+recipient.

> I would also appreciate complete repro
I will eventually do so, not sure if I will manage to do now because I'm tight on time and I won't be able to work on this for the whole of the next week.

**Comment by B4nan** [comment]
> Chat has a composite key on owner+recipient.

I want to see code, not words, I am sure you understand that :)

Also keep in mind the typings are best effort, it will never work exactly the same.

**Comment by darkbasic** [comment]
Here is the repro: https://github.com/darkbasic/mikro-orm-repro-4220
