### ISSUE TITLE
$and operator doesn't allow for PKs

### ISSUE THREAD

**Issue by darkbasic** [mikro-orm/mikro-orm#4222]
**Describe the bug**

**Single PK plus property**:
```ts
const a0 = await orm.em.fork().findOneOrFail(User, { id: 1, sex: 0 });
```
```sql
select "u0".* from "user" as "u0" where "u0"."id" = 1 and "u0"."sex" = 0 limit 1
```
```ts
const a1 = await orm.em.fork().findOneOrFail(User, { $and: [{ id: 1 }, { sex: 0 }] });
```
```sql
select "u0".* from "user" as "u0" where "u0"."id" = 1 and "u0"."sex" = 0 limit 1
```
```ts
const a2 = await orm.em.fork().findOneOrFail(User, { $and: [1, { sex: 0 }] });
```
```sql
select "u0".* from "user" as "u0" where "u0"."sex" = 0 limit 1
```

According to typings all the previous 3 queries should be the same and should lead to the same result, but the third one omits the condition on the PK.
**Multiple PKs plus property**:
```ts
const b0 = await orm.em.fork().findOneOrFail(User, { id: [1, 2], sex: 0 });
```
```sql
select "u0".* from "user" as "u0" where "u0"."id" in (1, 2) and "u0"."sex" = 0 limit 1
```
```ts
const b1 = await orm.em.fork().findOneOrFail(User, { $and: [{ id: [1, 2] }, { sex: 0 }] });
```
```sql
select "u0".* from "user" as "u0" where "u0"."id" in (1, 2) and "u0"."sex" = 0 limit 1
```
```ts
const b2 = await orm.em.fork().findOneOrFail(User, { $and: [[1, 2], { sex: 0 }] });
```
```sql
select "u0".* from "user" as "u0" where 0 = 1 and 1 = 2 and "u0"."sex" = 0 limit 1
```
```
node_modules/@mikro-orm/core/errors.js:186
        return new NotFoundError(`${name} not found (${(0, util_1.inspect)(where)})`);
               ^
NotFoundError: User not found ({ '$and': [ [ 1, 2 ], { sex: 0 } ] })
```
According to typings all the previous 3 queries should be the same and should lead to the same result, but the third one produces a broken query.

**To Reproduce**
1. Try the previous queries.

**Expected behavior**
They should all behave the same.

**Additional context**
The same should apply to composite keys.

**Versions**

| Dependency | Version |
| - | - |
| node | v18.15.0 |
| typescript | 5.0.3 |
| mikro-orm | 5.6.16 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
This feels more like imperfect typings, I wouldn't consider `{ $and: [1, { sex: 0 }] }` as a valid query, nor `{ $and: [1, 2] }` (same for `{ $and: [[1, 2]] }`). PK values should be supported only on top level, either single value or an array, which is interpreted as `$in` operator automatically.

You named this issue "$and operator doesn't allow for PKs" and that to me was never meant to be supported.
