### ISSUE TITLE
Env variables reset other config params to their defaults

### ISSUE THREAD

**Issue by andrew-sol** [mikro-orm/mikro-orm#4235]
Defining env variables removes all other config params from the same config section.
For example, `export MIKRO_ORM_MIGRATIONS_DISABLE_FOREIGN_KEYS=false` will erase the whole `migrations: {}` section of the config and leave only the env-defined variables there.

The problem lies in the following line of code (`ConfigurationLoader.ts`):
```ts
return new Configuration({ ...tmp, ...options, ...env }, validate);
```
this is a simple shallow merge, and we need a deep recursive merge here.

Here's an example of the current behaviour:
```ts
console.log({ migrations: { path: 'some/path' }, ...{ migrations: { disableForeignKeys: false } } });
// { migrations: { disableForeignKeys: false } } - "path" is missing now
```

**Versions**

| Dependency | Version |
| - | - |
| mikro-orm | 5.6.16 |

**Comment by B4nan** [comment]
Fixed via 392a623
