### ISSUE TITLE
migration generates invalid SQL statement

### ISSUE THREAD

**Issue by mouhandalkadri** [mikro-orm/mikro-orm#4239]
**Describe the bug**
When trying to generate migration for an entity containing an `uuid` column, a migration with invalid SQL statement is generated 

The entity class 
```typescript
import { Entity, PrimaryKey, Property } from '@mikro-orm/core';

@Entity()
export class Author {
    @PrimaryKey({
        columnType: "uuid"
    })
    id!: string;


    @Property()
    name!: string;
}

```
The generated statment is
```sql
create table `author` (`id` uuid not null, `name` varchar(255) not null, primary key (`id`)) default character set utf8mb4 engine = InnoDB;
```

**Environment**
Nestjs
Mysql
Mikro-orm 

**To Reproduce**
1. Create entity with a column of type `uuid`
2. Run `npx mikro-orm migration:create`
3. Run `npx mikro-orm migration:up`

**Expected behavior**
A valid SQL create statement should be generated.

**Versions**
| Dependency | Version |
| - | - |
| node | v16.15.0 |
| typescript | 4.7.4 |
| mikro-orm | 5.6.16 |
| @mikro-orm/mysql | 5.6.16 |
| @mikro-orm/migration | 5.6.16 |
| @mikro-orm/nestjs | 5.1.8 |

**Comment by B4nan** [comment]
You need to put valid column type in there, it is your responsibility. As opposed to just `type: uuid` which resolves to things based on current driver.
