### ISSUE TITLE
docs syntax error ?

### ISSUE THREAD

**Issue by wujingquan** [mikro-orm/mikro-orm#424]
**Describe the bug**
```
import globby from 'globby';

const orm = await MikroORM.init({
  entities: await globby('./dist/app/**/entities/*.js').map(require),
  // ...
});

may be is :

import globby from 'globby';

const orm = await MikroORM.init({
  entities: (await globby('./dist/app/**/entities/*.js')).map(require),
  // ...
});
```

**Stack trace**
```
...
```

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**
```
import globby from 'globby';

const orm = await MikroORM.init({
  entities: (await globby('./dist/app/**/entities/*.js')).map(require),
  // ...
});
```
**Additional context**

**Versions**

| Dependency | Version |
mikro-orm 3.5.0
   - node 10.16.0
   - knex 0.20.12
   - mysql2 2.1.0
   - typescript 3.8.3

**Comment by B4nan** [comment]
Looks like you are right, I originally had sync version of globby there so that is where this comes from.
