### ISSUE TITLE
ignore errors on upsertMany()

### ISSUE THREAD

**Issue by Zmaon** [mikro-orm/mikro-orm#4240]
**Is your feature request related to a problem? Please describe.**

Sometimes we need to ignore foreign key errors on large syncs that require calling different endpoints on an API. This is because, for example, by the time we reach endpoint 10 on the API data may have changed, and we will receive data on endpoint 10 pointing to entries that we didn't synchronize in endpoint 1 because they didn't exist yet (hope this is clear). 

To handle that correctly, the easiest way is to  simply ignore foreign key errors so that data is not inserted and will be synchronized next time. 

We would like to use the entityManager.upsertMany() method for such synchronizations, but I didn't find an option to ignore foreign key errors.

**Describe the solution you'd like**

```typescript
em.upsertMany(entityName, entities, {
  ignore: true,
});
```
Would trigger insert IGNORE for MySQL, not sure what the alternatives are for other databases.

**Describe alternatives you've considered**

We tried to use the queryBuilder to reach the same goal, like this:

```typescript
em.createQueryBuilder(entityName).insert(entities).onConflict().merge().ignore();
```

But this requires more processing on data before inserting. Using the native `upsertMany()` method would be more convenient.

**Comment by B4nan** [comment]
This seems to be really mysql specific, all the other drivers don't support such a combination. And I think it would also break the return values, a successful call should have the entities updated, you would lose the values while your entities would be probably already synced and the state would be flushed from memory.

What additional processing do you need with the QB? Maybe we need to improve that?

The use case is not very clear from what you said, and I haven't found anything online about using this combination, only a few notes discouraging the `insert ignore` in general. Also found this note from the knex issue about the upsert support:

> Relatedly specifying both ignore() and merge() in the same query is not valid, but there is currently no check to prevent you from doing this. It will simply compile invalid SQL. It wouldn't be hard to add a check.

https://github.com/knex/knex/issues/3186#issuecomment-605314991

**Comment by Zmaon** [comment]
You're right, I realize that this is very specific to MySQL, and there may be few use cases where this is really helpful. In my current use case we ended up writing more code to filter data that could cause foreign key issues before inserting it to DB, I think that this is more robust. 

Concerning the additional processing for query builder I understand now that I actually bumped on an issue where JSON columns are incorrectly inserted when using the QB (data seems to be double-escaped), but correctly when using `upsertMany()`. I spent some time trying to reproduce this with minimal code to submit an issue but couldn't, so I'm still trying to understand what causes this in the main project.

Anyway, I guess that unless there is a broader interest in being able to insert/ignore+merge with MySQL you can close this request. Thanks for your prompt reply.

**Comment by B4nan** [comment]
There were lots of edge cases around JSON properties, try out latest dev version, it could help. If not, repro welcome.

I'll close this, since the combination seems to be rather discouraged, but if you come across some reading about this topic that says otherwise, please share it here. I am not completely against the mysql only options, but given you can do this with QB already, it feels enough that way. As said above, if you find some issues with that approach, let me know.
