### ISSUE TITLE
Using Knex query builder to create WITH recursive query results in javascript heap out of memory error

### ISSUE THREAD

**Issue by bhavinks** [mikro-orm/mikro-orm#4243]
**Describe the bug**
When using knex to execute a with recursive table, I  am getting a javascript heap out of memory error. I am trying to query records from a Postgresql table which contain hierarchical records represented by a column parent_id (integer) and path (ltree)

**Stack trace**
<--- Last few GCs --->

2023-04-20T07:52:12.308375034Z [94:0x7fb7dd8c91c0]   288224 ms: Mark-sweep (reduce) 2045.1 (2081.4) -> 2044.1 (2081.7) MB, 2319.8 / 0.0 ms  (average mu = 0.243, current mu = 0.008) allocation failure; scavenge might not succeed

2023-04-20T07:52:12.308378048Z [94:0x7fb7dd8c91c0]   291440 ms: Mark-sweep (reduce) 2045.3 (2081.7) -> 2044.4 (2081.9) MB, 3199.4 / 0.0 ms  (average mu = 0.117, current mu = 0.005) allocation failure; scavenge might not succeed

<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

**To Reproduce**
```
      const qb = this.em.createQueryBuilder(AppFeature, "parent_features");
      const knex = qb.getKnexQuery();
      // Recursive query to get all enabled parent features and enabled sub features of the parent
      knex.withRecursive('parent_features', (qry) => {
        qry.select('parent.*')
          .from({parent: 'master.app_features'})
          .where({'parent.parent_id': 0, 'parent.is_enabled': true})
          .unionAll((qry) => {
            qry.select('child.*')
              .from({child: 'master.app_features'})
              .where('child.is_enabled', true)
              .innerJoin('parent_features', 'child.path', '@>', 'parent_features.path')
          })
      }).select('*').fromRaw('parent_features');
```
2. Execute query against database connection:
```
      const dbConnection = this.em.getConnection();
      return await dbConnection.execute(knex);

```
**Expected behavior**
The query should execute and return the results. When the sql is directly executed against the database table, the query works fine.

**Additional context**
Running the same query as a raw query via knex also results in the same heap out of memory error

**Versions**
   "@mikro-orm/core": "^5.1.5",
    "@mikro-orm/postgresql": "^5.1.5",
    "@mikro-orm/reflection": "^5.1.5",
    "@nestjs/bull": "^0.6.3",
    "@nestjs/common": "^9.1.4",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.1.4",

| Dependency | Version |
| - | - |
| node | 18.14.2 |
| typescript | 4.9.5 |
| mikro-orm | 5.1.5 |
| your-driver | ? |

**Comment by B4nan** [comment]
> Running the same query as a raw query via knex also results in the same heap out of memory error

Yes, so knex issue, report is there please.
