### ISSUE TITLE
AfterFlush ChangeSet payload is missing ManyToOne FK while entity is populated correctly

### ISSUE THREAD

**Issue by Tlepel** [mikro-orm/mikro-orm#4245]
**Describe the bug**

When creating an entity which contains a ManyToOne relation with another entity of the same type (for example, nodes in a linked list) the ChangeSet payload in the `afterFlush` event doesn't include the property at all. The entity, however, does have the proper reference.

**To Reproduce**
Failing test can be found in #4247

**Expected behavior**
The ChangeSet in the `afterFlush` hook should contain the relation

**Versions**

| Dependency | Version |
| - | - |
| node | 18.5.0 |
| typescript | 5.0.4 |
| mikro-orm | 5.6.16 |
| your-driver | MySQL |

**Comment by B4nan** [comment]
The relation is self-referencing, so it issues an extra update query to set it after we have the PKs - the property is not part of the changeset on purpose. If you enable debug mode, you can see there will be two queries:

```
[query] insert into `node` (`value`) values ('First node'), ('Second node') returning `id` [took 0 ms]
[query] update `node` set `parent_id` = 1 where `id` = 2 [took 2 ms]
```

Maybe the extra update could also propagate the change back to the changeset.

Note that you can get the list of extra updates from the UoW too, just like you can get the list of changesets.
