### ISSUE TITLE
Collection's type definition is missing declarations for `$` and `get`

### ISSUE THREAD

**Issue by bbuck** [mikro-orm/mikro-orm#4248]
**Describe the bug**
I'm trying to write tests for code that uses `Collection#init` and I'm encountering an issue mocking the return value (with jest). The implementation of `init` returns the instance of the collection but if I try and mock it to do this I get the below error in TypeScript because the typings for `Collection` are missing definitions for `$` and `get`.

It's possible it's because of the way these properties are defined: https://github.com/mikro-orm/mikro-orm/blob/v5.6.15/packages/core/src/entity/Collection.ts#L433-L436

**Stack trace**
```
 Type 'Collection<Entity, object>' is missing the following properties from type 'LoadedCollection<Loaded<Entity, string>>': $, get
```

**To Reproduce**
1. Have a jest configuration with TypeScript
2. Have a defined entity with a `Collection` field
3. Spy on, and mock the collection, `jest.spyOn(myEntity.collection, 'init').mockReturnValue(Promise.resolve(myEntity.collection)`

**Expected behavior**
No compilation error as all the fields necessary to match the `LoadedCollection` interface are present on `Collection`.

**Versions**

| Dependency | Version |
| - | - |
| node | 18.15 |
| typescript | 4.9.5 |
| mikro-orm | 5.6.15 |
| mikro-orm/postgresql | 5.6.15 |

**Comment by B4nan** [comment]
No, that would completely beat the purpose of type-safe relations - they are added to the type level only based on populate hints.
