### ISSUE TITLE
Excessive update queries for BigIntType/JsonType when fetching through ManyToOne relation

### ISSUE THREAD

**Issue by l-bujakowski** [mikro-orm/mikro-orm#4249]
Hello,

I've recently updated mikro-orm, and noticed that from version 5.6.10 upwards orm produces excessive update queries on flush. It seems the issue is related to only some field types (I have observed it with BigIntType and JsonType). Here's an example for reproduction:

```TypeScript
//Author.ts
import { Entity, PrimaryKey, BigIntType } from '@mikro-orm/core';

@Entity()
export default class Author {
  @PrimaryKey({ columnType: 'bigint', type: BigIntType })
  private id: string;

  public constructor(id: string) {
    this.id = id;
  }

  public getId(): string {
    return this.id;
  }
```
```TypeScript
//Post.ts
import { Entity, PrimaryKey, ManyToOne, Property, wrap, JsonType } from '@mikro-orm/core';
import { default as Author } from './Author';

@Entity()
export default class Post {
  @PrimaryKey()
  private id: number;

  @ManyToOne({ entity: () => Author })
  private author: Author;

  @Property({ columnType: 'json', type: JsonType })
  private extra: Record<string, any>;

  public constructor(authro: Author, extra: Record<string, any>) {
    this.author = authro;
    this.extra = extra;
  }

  public getId(): number {
    return this.id;
  }

  public async getAuthor(): Promise<Author> {
    if (!wrap(this.author).isInitialized()) {
      await wrap(this.author).init();
    }
    return this.author;
  }

  public getExtra(): Record<string, any> {
    return this.extra;
  }
}
```

```TypeScript
//reproduction.spec.ts
import { default as Author } from './Author';
import { MikroORM } from '@mikro-orm/mysql';
import { default as Post } from './Post';
import config from './orm.config';
import { FilterQuery } from '@mikro-orm/core';

describe('issue reproducton', () => {
  let orm: MikroORM;
  let postId: number;

  beforeAll(async () => {
    orm = await MikroORM.init(config);
    const em = orm.em.fork();
    const author = new Author('198604260123');
    const post = new Post(author, { category: 'Tech' });
    em.persist(author);
    em.persist(post);
    await em.flush();
    postId = post.getId();
  });

  afterAll(() => {
    orm.close(true);
  });

  it('makes unnecessary updates', async () => {
    const em = orm.em.fork();
    const post = await em.getRepository(Post).findOneOrFail(<FilterQuery<Post>>{ id: postId });
    await em.flush();
  });
});
```

queries issued:
```bash
begin
insert into `author` (`id`) values ('198604260123')
insert into `post` (`author_id`, `extra`) values ('198604260123', '{\"category\":\"Tech\"}')
commit
select `p0`.* from `post` as `p0` where `p0`.`id` = 4 limit 1
select `a0`.* from `author` as `a0` where `a0`.`id` = '198604260123' limit 1
begin
update `author` set `id` = '198604260123' where `id` = 198604260123
update `post` set `extra` = '{\"category\":\"Tech\"}' where `id` = 4
commit
```

When I've inspected Unit of Work right before flush, it had wrong type in entity 'original data' (e.g. for BigIntType it's a number, where as I would expect a string). Also as for BigIntType - it seems that entity fetched directly has proper type in UoW (so doesn't make any additional update queries). Only fetched via relation like in the example has this issue.  I've tried to overcome this with custom types, but with no success. I think it might be a bug.

**Comment by l-bujakowski** [comment]
I've just run it on ` 5.7.0` & ` 5.7.1-dev.2`, on both the issue is 1/2 resolved (json ok, big int issue remains).

```
[query] begin
[query] insert into `author` (`id`) values ('198604260123') [took 1 ms]
[query] insert into `post` (`author_id`, `extra`) values ('198604260123', '{\"category\":\"Tech\"}') [took 4 ms]
[query] commit
[query] select `p0`.* from `post` as `p0` where `p0`.`id` = 8 limit 1 [took 1 ms]
[query] select `a0`.* from `author` as `a0` where `a0`.`id` = '198604260123' limit 1 [took 1 ms]
[query] begin
[query] update `author` set `id` = '198604260123' where `id` = 198604260123 [took 0 ms]
[query] commit
```

**Comment by B4nan** [comment]
Well, your reproduction is not reproducing that, so provide new one that actually fails. And please provide a complete code, dont skip imports, dont skip the ORM config, so its clear what exactly are you doing, I am just guessing from the queries that you are using mysql or sqlite, tried both and both work fine.

```ts
import {
  BigIntType,
  Entity,
  JsonType,
  ManyToOne,
  PrimaryKey,
  Property, wrap,
} from '@mikro-orm/core';
import { MikroORM } from '@mikro-orm/mysql';

@Entity()
class Author {

  @PrimaryKey({ columnType: 'bigint', type: BigIntType })
  private id: string;

  public constructor(id: string) {
    this.id = id;
  }

  public getId(): string {
    return this.id;
  }

}

@Entity()
class Post {

  @PrimaryKey()
  private id: number;

  @ManyToOne({ entity: () => Author })
  private author: Author;

  @Property({ columnType: 'json', type: JsonType })
  private extra: Record<string, any>;

  public constructor(authro: Author, extra: Record<string, any>) {
    this.author = authro;
    this.extra = extra;
  }

  public getId(): number {
    return this.id;
  }

  public async getAuthor(): Promise<Author> {
    if (!wrap(this.author).isInitialized()) {
      await wrap(this.author).init();
    }
    return this.author;
  }

  public getExtra(): Record<string, any> {
    return this.extra;
  }

}

describe('issue reproducton', () => {
  let orm: MikroORM;
  let postId: number;

  beforeAll(async () => {
    orm = await MikroORM.init({
      dbName: '4249',
      entities: [Post],
      debug: true,
      port: 3308,
    });
    await orm.schema.createSchema();
    const em = orm.em.fork();
    const author = new Author('198604260123');
    const post = new Post(author, { category: 'Tech' });
    em.persist(author);
    em.persist(post);
    await em.flush();
    postId = post.getId();
  });

  afterAll(() => {
    orm.close(true);
  });

  it('makes unnecessary updates', async () => {
    const em = orm.em.fork();
    const post = await em.getRepository(Post).findOneOrFail({ id: postId } as any);
    await em.flush();
  });
});
```

**Comment by l-bujakowski** [comment]
Hello, I've made a PR with reproduction:

https://github.com/mikro-orm/mikro-orm/pull/4330

**Comment by l-bujakowski** [comment]
Thank you for re-open. I've noticed now that while copying from another issue I haven't changed dbName suffix to `4249`.

**Comment by B4nan** [comment]
So the problem here is mysql returning bigints are numbers unless they exceed the safe range of JS floats. I will enforce it to return strings with `bigNumberStrings` option, let's see if it won't break things for people, as it has some side effects on raw queries too - but they might be insignificant in the end. Worst case I will make this configurable and revert the default behavior.

You can already try to change this in your config:

```ts
MikroORM.init({
  driverOptions: {
    bigNumberStrings: true,
  },
});
```

Let me know if it works for you.

**Comment by l-bujakowski** [comment]
Doesn't seem to work. Isn't this option only available in maria db driver?  I can't find it in the MySql driver anywhere.

> we already convert the runtime value to strings explicitly, so we could use that

I suspect, that the problem lies in this, that the `BigIntType.convertToJSValue()` is not called in this scenario. It would be, when selecting such entity directly, but it isn't when loaded through relation. I would expect, that this would be always executed, in whatever way the entity is loaded.

**Comment by B4nan** [comment]
Have you tried the fix or just the workaround? v5.7.5 should work with all drivers.

**Comment by l-bujakowski** [comment]
I've tried using `bigNumberStrings: true,` in the config, but on 5.6.10 (first version I've encountered the issue). But you're right - the option exists in 5.7.5, and it works well for me. Using this option solves the issue for me, since in my project I want to use strings (in js) for bigints (db column type) all the way.

About the side effects - could I expect any other side effects, besides bigint casting?

Also - have what's your opinion on running results through `BigIntType.convertToJSValue()` in this scenario?

You're also right of course about the driver/template. I've used `import { MikroORM } from '@mikro-orm/mysql';`, which was a hint, but  I should've boldly state what driver I'm using from the beginning. Sorry for that, I'll remember to fill the template properly next time.

**Comment by B4nan** [comment]
> I've tried using bigNumberStrings: true, in the config, but on 5.6.10 (first version I've encountered the issue). But you're right - the option exists in 5.7.5, and it works well for me. Using this option solves the issue for me, since in my project I want to use strings (in js) for bigints (db column type) all the way.

The option is not "added in v5.7.5", that version fixes the issue in another way - you dont need to use it, just update.

**Comment by l-bujakowski** [comment]
I see now, you're referring to this commit:

https://github.com/mikro-orm/mikro-orm/commit/2acd25e1dfd2eb7764e38c4ff224a84e52d5ed0f

Ok then, so I'll just update to 5.7.5. It works, I've tested it before (just thought it's due the option). Thanks.
