### ISSUE TITLE
CLI fails to run any command

### ISSUE THREAD

**Issue by JustLitio** [mikro-orm/mikro-orm#4265]
**Describe the bug**
The CLI does not work anymore because the argument parsing throws an exception

**Stack trace**
```
$ npx mikro-orm migration:create
TypeError: Cannot read properties of undefined (reading 'length')
    at /home/jlario/projects/8belts-api/node_modules/.pnpm/@mikro-orm+cli@5.7.0_@mikro-orm+migrations@5.7.0_@mikro-orm+mysql@5.7.0_@mikro-orm+postgresql@5.7.0_pg@8.10.0/node_modules/@mikro-orm/cli/cli.js:14:16
```

**To Reproduce**
1. Run any CLI command, for example, `npx mikro-orm migration:create`

**Expected behavior**
Command runs

**Additional context**
From what I've been able to investigate, a Promise return value from `yargs.parse()` is not being awaited. See here: 
https://github.com/mikro-orm/mikro-orm/blob/ed5f7782264ce9c710bab73b242730d3155406a8/packages/cli/src/cli.ts#L14

**Versions**

| Dependency | Version |
| - | - |
| node | 18.16.0 |
| typescript | 5.0.4 |
| mikro-orm | 5.7.0 |

**Comment by B4nan** [comment]
Oops, I was expecting something from the yargs upgrade :] Thanks for the report, will fix this later today and ship a new stable. 

PR welcome, if you are interested and have some spare time now, but this is quite critical so want to have it fixed during today.

**Comment by wiese** [comment]
Thanks for the quick reaction.

Am I interpreting it correctly that the bug was reported for 5.7.0, has been fixed, but there is no release since (I'm seeing 5.7.1-dev.2 as next)?

Thanks

**Comment by B4nan** [comment]
Yes, exactly, didnt have time yesterday after work, will do it today.
