### ISSUE TITLE
Cannot create named migration from cli

### ISSUE THREAD

**Issue by rubiin** [mikro-orm/mikro-orm#4271]
**Describe the bug**
Using the --name arg with the migration create command throws error when used with mikroorm cli. 
The error is the handled error from 

```ts
      if (!name) {
        throw new Error(
          'Specify migration name via `mikro-orm migration:create --name=...`'
        );
      }

```
The command used is `npx mikro-orm migration:create --name=initial`

**Stack trace**
```
Error: Specify migration name via `mikro-orm migration:create --name=...`
    at Object.fileName (/home/projects/mikro-orm-repro-fu6y81/cli.ts:13:15)
    at TSMigrationGenerator.generate (/home/projects/mikro-orm-repro-fu6y81/node_modules/@mikro-orm/migrations/MigrationGenerator.js:22:42)
    at async Migrator.createInitialMigration (/home/projects/mikro-orm-repro-fu6y81/node_modules/@mikro-orm/migrations/Migrator.js:68:27)
    at async _0x469733.handleCreateCommand (/home/projects/mikro-orm-repro-fu6y81/node_modules/@mikro-orm/cli/commands/MigrationCommandFactory.js:126:21)
    at async _0x469733.handleMigrationCommand (/home/projects/mikro-orm-repro-fu6y81/node_modules/@mikro-orm/cli/commands/MigrationCommandFactory.js:77:17)
...
```

here is a reproduction link https://stackblitz.com/edit/mikro-orm-repro-fu6y81

**To Reproduce**
1.  Follow https://mikro-orm.io/docs/migrations#using-custom-migration-names
2.  Remove the migrations folder  and test.db
3.  run `npx mikro-orm migration:create --name=initial`

**Expected behavior**
Should generate named migration

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 18.15.0 |
| typescript | latest|
| mikro-orm | 5.7.1 |
| sqlite driver | 5.7.1 |

**Comment by B4nan** [comment]
cc @AbdlrahmanSaberAbdo, looks like you haven't tested this much? :]

**Comment by B4nan** [comment]
Running `npx mikro-orm migration:create --name=initial` works just fine, but seeing your stack trace, you did something like `npx mikro-orm migration:create --name=initial --initial` instead, and that indeed fails.

Please note that you almost never need the `--initial` flag. I feel like nobody reads the docs around it, you only need that if you already have a schema, it is aligned with your metadata, and you want to start using migrations.

**Comment by B4nan** [comment]
Feel free to suggest how to improve it, PR welcome, I don't mind making the docs more verbose/clear.

**Comment by AbdlrahmanSaberAbdo** [comment]
Thanks, @B4nan for seeing it, I just came back and saw your comment. I'll see if I can add more test cases.

**Comment by varunkamra** [comment]
@B4nan Is it possible to name migrations with prefix m<timestamp> instead of Migration<timestamp>? If I want to include a migration name the file name would be long.

**Comment by B4nan** [comment]
Yes, as long as they can be sorted by the file name properly. You could even drop the `m` and keep only the timestamp in front I guess.

You can do that with the `fileName` option.

https://mikro-orm.io/docs/migrations#using-custom-migration-names
