### ISSUE TITLE
Converting postgres date property to js value converts it to a date instead of string

### ISSUE THREAD

**Issue by co-sic** [mikro-orm/mikro-orm#4276]
**Describe the bug**
Since version 5.7.0 of mikro-orm the behaviour of fetching at property with postgres column type "date" changed. 

The postgres date type is stored as a string in the format "yyyy-mm-dd" in the database.

It was parsed as a string by mikro-orm up until v 5.6.16. But now it is parsed as a js Date object. I could not find something related to that change in the release notes. 

I have a custom type i'm using to convert the db value to a js object of CalendarDate:

```ts
import { EntityProperty, ValidationError, Platform, Type } from '@mikro-orm/core';
import { CalendarDate } from 'calendar-date';

export class CalendarDateType extends Type<CalendarDate, string> {
  convertToDatabaseValue(value: CalendarDate | string | undefined | null): string {
    if (value instanceof CalendarDate) {
      return value.toString();
    }

    if (!value || value.toString().match(/^\d{4}-\d{2}-\d{2}$/)) {
      return value as string;
    }

    throw ValidationError.invalidType(CalendarDateType, value, 'JS');
  }

  convertToJSValue(value: CalendarDate | string | null | undefined): CalendarDate {
    if (!value || value instanceof CalendarDate) {
      return value as CalendarDate;
    }
    return new CalendarDate(value);
  }

  compareAsType(): string {
    return 'date';
  }

  getColumnType(prop: EntityProperty, platform: Platform): string {
    return platform.getDateTypeDeclarationSQL(prop.length);
  }

  toJSON(value: CalendarDate): CalendarDate | string {
    return this.convertToDatabaseValue(value);
  }
}
```
In the convertToJSValue function the value was always a string but is a js date object now. Is that intended? Of course i can work with that and convert the date to the string i need, but the whole point of storing the date without time information in the DB, is to not deal with conversion of dates in different timezones.

**Versions**

| Dependency | Version |
| - | - |
| node | 18 |
| typescript | 5.04 |
| mikro-orm | 5.7.2 |

**Comment by B4nan** [comment]
I need to see a complete reproduction for such issues, this is most probably not about your type implementation, rather about the value returned from database being saved in the entity snapshot wrongly.

**Comment by B4nan** [comment]
One of the things that changed in postgres is that the type overrides are now scoped only to the ORM instance of the postgres client, before it was altered globally.

https://github.com/mikro-orm/mikro-orm/commit/5594c469f05d2c1fc76f3cc1a388f5e7162f4e72#diff-845d1587d2aabfa92fa22ab79ebb2eeaaed044eb22a3c4aa5f592500693d420cR19

As by default it is the postgres client that convers the string to date object, if its done by MikroORM, it would have to be your code (the mapped type implementation) most probably.

**Comment by co-sic** [comment]
Thanks for the quick reply! I added a minimal reproduction here: 
https://github.com/co-sic/node-mikro-orm-playground
This is working as it is, but if you change the mikro orm version to >=5.7.0, it will produce an error.

**Comment by B4nan** [comment]
Ok, no need for repro, it's caused by that change I mentioned above, apparently, the local overrides are not taken into account, when I switch back to the global overrides it works fine. 

So for now a workaround could be doing this somewhere, e.g. in your ORM config file:

```ts
import { types, defaults } from 'pg';

types.setTypeParser(1082, str => str);
```

I will try to isolate this more when I have some spare time, sounds like its a bug in the pg library, if so it would be better to report it and let them fix it.

**Comment by B4nan** [comment]
Oh wait, now I see it, I moved the line with `types` inside the `forceUtcTimezone` if block!

**Comment by co-sic** [comment]
Thank you for the quick fix, much appreciated! :)
