### ISSUE TITLE
EventSubscriber not picking up events from Postgres upsert

### ISSUE THREAD

**Issue by austinwilliams2021** [mikro-orm/mikro-orm#4282]
**Describe the bug**
I'm guessing this isn't a bug, but wanted to make sure. I'm using EventSubscriber to hook into a couple entities, however, when using upsertMany for one of the aforementioned entities, neither the afterCreate or afterUpdate methods get triggered. I'm guessing this is due to the nature of upsert, i.e., who's to know if a create or update will happen. Because it's ambiguous, perhaps upserts can't ever be picked up by EventSubscriber?

**To Reproduce**
1. Use EventSubscriber to hook into some entity and implement the afterCreate and afterUpdate methods with logging included.
2. Manipulate the db table corresponding to that entity with the upsertMany function.
3. Confirm neither afterCreate nor afterUpdate were triggered via the logs.

**Expected behavior**
Unclear - this is what I'm interested in.

**Versions**

| Dependency | Version |
| - | - |
| node | 18.15.0 |
| typescript | 4.9 |
| mikro-orm | 5.6.15 |
| your-driver | postgres@5.6.15 |

**Comment by B4nan** [comment]
Yeah, there are no hooks fired for upsert, as there is no way to tell whether it was insert or update, and you can even use it without entity instance, so the `before` hooks are also not possible. 

Maybe we should add some new event like `beforeUpsert` and `afterUpsert`? The before hook would sometimes get a POJO and sometimes an entity instance, based on how you use it, after hook would always get the entity instance.

Looking at the implementation, we also don't fire `OnInit` hook which we definitely can.

**Comment by austinwilliams2021** [comment]
Would definitely take advantage of those events if implemented. There’s a lot to like about EventSubscriber and to stick with it without upsert events, we’d have to override upsert to trigger existing events.
