### ISSUE TITLE
v6: Incorrectly deep DTO population and related performance issue

### ISSUE THREAD

**Issue by SpencerKaiser** [mikro-orm/mikro-orm#4285]
**Describe the bug**
When using a datastructure with circular references, `toPOJO` results in a performance issue and a object with incorrect depth

**Stack trace**
N/A

**To Reproduce**
1. Create a circular reference in your entities: `Author -> Books -> Author`
2. Query for the root entity and populate the dependency
3. Convert to POJO and examine the populated depth and note the execution time

[Repro](https://stackblitz.com/edit/mikro-orm-v6-strict-partial-loading-46bolg?file=index.ts)

**Expected behavior**
Only the loaded data will be populated in the DTO; the circular reference will stop with a a `Reference` instead of a populated DTO

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 16.14.2 |
| typescript | 4.9.5 |
| mikro-orm | 6.0.0-dev.64 |

**Comment by B4nan** [comment]
> Only the loaded data will be populated in the DTO

The point of `toPOJO` is to always serialize the full entity unless there is a cycle, it ignores populate and partial loading hints, and even if it didn't - eager loading is the same as if you would add the populate hint explicitly (it literally works by automatically adding to the populate hint), and you are using eager loading all over the place in the repro, e.g. the place you marked as you expect it to be number is populated via eager loading. That method is meant for caching, as you generally want to cache all the data, not just those marked as populated (the result cache is using it).

What you are expecting is what `toObject()` and `toJSON()` are doing (`toJSON()` is an extension point, it defaults to `toObject()`. So the type is wrong, not the runtime behavior.

**Comment by B4nan** [comment]
And the type would be correct if you used the `EagerProps` symbol. So sounds like a false alarm to me, it's indeed slow, but that's what you can get with eager loading of complex entities.

**Comment by B4nan** [comment]
As I said, you probably just want `toObject`, not `toPOJO`:

https://stackblitz.com/edit/mikro-orm-v6-strict-partial-loading-fh7d9t?file=index.ts

**Comment by B4nan** [comment]
Btw you can always use the explicit serialization, it is there exactly for such cases where it's easier to just say what you want instead of battling the implicit serialization.

**Comment by SpencerKaiser** [comment]
Yea I can definitely confirm `toObject` works better locally... is that documented anywhere? I've never truly understood the difference.

To give you some context, our API typically does a conversion to a DTO of sorts depending on where it goes. For example, a "Host" in our system can show up in one of two ways: Publicly and Privately. We have helper methods that convert it and depending on the circumstance, one of the two helpers issued:
```ts
static toSimpleDto(host: Host) {
    const hostDto = host.toObject();

    const { displayName, id, handle } = hostDto;
    return { displayName, id, handle };
  }

static async toPublicDTO(host: Host) {
    const hostTags = await host.tags.load();
    const tags = hostTags.getItems().map((hostTag) => hostTag.tag);

    const callOptions = host.callOptions
      .getItems()
      .map((callOption) => CallOption.toPrivateDTO(callOption)) // Create DTOs to eliminate irrelevant fields

    const hostDTO: Partial<EntityDTO<Host>> = host.toObject();
    delete hostDTO.user; // The FE doesn't care about the user
    delete hostDTO.tags; // Replace tags with just strings instead of the entity
    delete hostDTO.callOptions; // Use the cleaned-up DTOs from above

    return { ...hostDTO, callOptions, tags };
  }
```

And I know the deletion is partially redundant I just find it makes things clearer. Let me know if you have any follow up questions; there might be a better way of doing this, but we often need to do some manipulation before sending it along.

Also worth noting that we probably should make these class methods instead of static ones; we originally had static but I believe it was due to funky type issues that are likely resolved in v6.

**Comment by SpencerKaiser** [comment]
> Btw you can always use the explicit serialization

Super helpful to know that exists, but yea, we need data from the loaded entities too 😕

**Comment by B4nan** [comment]
Well, toObject is documented here: 

https://mikro-orm.io/docs/serializing

And toPOJO is just mentioned here:

https://mikro-orm.io/docs/entity-manager#entity-state-and-wrappedentity

So the question is more like why did you use the undocumented `toPOJO` :D 

Btw I am not following the note about explicit serialization - as long as you know how the response should look like, why can't you use that? Or is your response dynamic in shape?

**Comment by B4nan** [comment]
The docs are really dated, I will need to go through all of that, but I am delaying it before the getting started guide is somehow ready and added to the docs - as I might just remove some sections in favor of that.

**Comment by SpencerKaiser** [comment]
> So the question is more like why did you use the undocumented toPOJO :D

😆 yea I can't defend myself here... I was a bit confused at the time and the return type seemed to work well, so I just kinda went for it I guess...

~Ok well I'll switch over to `toObject` for everything because that sounds like what I need.~ 👇 

> Btw I am not following the note about explicit serialization - as long as you know how the response should look like, why can't you use that? Or is your response dynamic in shape?

Sorry, I was a bit distracted when I read that a few mins ago and I missed the example. Wow, yea that looks like EXACTLY what I need; lemme go play with it and I'll get back to you

**Comment by SpencerKaiser** [comment]
Oh also one other super relevant piece as to why I have these methods... often times I have multiple endpoints that all return the same data (`GET`, `POST`, `PUT`, etc.) and so I use the exact same method everywhere to ensure the structure is ALWAYS the same

**Comment by SpencerKaiser** [comment]
Ok so here's my first hiccup: what if I need to reorder the data and/or remove some? I feel like adjusting and then filtering on the actually entity is not a great call. BUT I need to remove stuff after sorting, so I'd have to use `serialize` twice... `serialize`, filter/sort, then delete the extra fields, maybe?

**Comment by B4nan** [comment]
You call it once, then you already have the shape you want, so you can mutate or map that to something else as you wish - no need to call serialize on that, its for entities and you will already have POJOs. Or maybe I am not following, as this seems quite obvious?

**Comment by SpencerKaiser** [comment]
I phrased it poorly, yea I can manipulate after the serialization... only downside is that the types aren't happy, but making the whole thing partial is fine

**Comment by B4nan** [comment]
I guess we can close this? Or is there anything still unresolved, apart from the dated docs?

**Comment by SpencerKaiser** [comment]
Yea as long as you're ok with the undocumented method having a weird type... which is 110% acceptable IMO, I was the one that did the dumb thing haha

**Comment by B4nan** [comment]
> Also teeny bit of feedback, it's a little weird that the second arg for wrap (e.g., wrap(this, true)) is necessary and will result in a runtime error if it's not there. I'm sure there's a reason, but it's a bit funky on the dev experience

What do you mean? There are tons of tests that are using just `wrap` without it, repro welcome, that sounds more like a bug.

**Comment by SpencerKaiser** [comment]
Just opened an issue; it seems to only be a thing when you extend `BaseEntity` 😬

**Comment by SpencerKaiser** [comment]
That being said, shouldn't I just use `import { serialize } from '@mikro-orm/core';`? I don't see any recent commits related to that, but I don't remember the docs using that method vs `wrap().serialize` - seems to be working as expected 🤨

**Comment by B4nan** [comment]
Oh I see, yeah that's indeed a bug.

> That being said, shouldn't I just use import { serialize } from '@mikro-orm/core';? I don't see any recent commits related to that, but I don't remember the docs using that method vs wrap().serialize - seems to be working as expected 🤨

I've added it because the `serialize()` always returns an array (haven't found a way to make it work with TS and inference properly, same issue with `em.populate()`, either inference works or autocomplete works, never both :/), while `wrap().serialize()` works on a single entity.

**Comment by SpencerKaiser** [comment]
Yea I literally just realized that haha

I'll probably continue to use `wrap` after the bug is fixed; I prefer to use `"noUncheckedIndexedAccess": true` so grabbing index zero would cause some funky types stuff if I used the isolated `serialize`
