### ISSUE TITLE
Using wrap().assign on entity with JSONType property doesn't work

### ISSUE THREAD

**Issue by ThatOneAwkwardGuy** [mikro-orm/mikro-orm#4290]
**Describe the bug**
When using the assign helper on an entity with a @Property with type json, so changes related to that property are persisted.

Upon further investigation it appears to me that the assign helper messes with the __originalEntityData value so that the value for the json property is the same in the entity and the __originalEntityData, therefore when running computeChangeset(s) there is no diff to be persisted.

**Stack trace**
No error

**To Reproduce**
1. Go to mikro-orm/tests/features/custom-types/json-properties.test.ts
2. on line 130 write this code instead:
```
    // res.value = { lol: true };
    wrap(res).assign({value: { lol: true }})
    await orm.em.flush();
    expect(mock).toBeCalled();
    mock.mockReset();
    await orm.em.flush();
    expect(mock).not.toBeCalled();
```
4. The test will fail on the line:
```
expect(mock).toBeCalled();
```

**Expected behavior**
To persist the changed JSON

**Versions**

| Dependency | Version |
| - | - |
    "@mikro-orm/core": "6.0.0-dev.64",
    "@mikro-orm/migrations-mongodb": "6.0.0-dev.64",
    "@mikro-orm/mongo-highlighter": "1.0.0",
    "@mikro-orm/mongodb": "6.0.0-dev.64",
    "@mikro-orm/nestjs": "5.1.8",
    "@mikro-orm/seeder": "6.0.0-dev.64",

**Comment by B4nan** [comment]
> Upon further investigation it appears to me that the assign helper messes with the __originalEntityData value so that the value for the json property is the same in the entity and the __originalEntityData, therefore when running computeChangeset(s) there is no diff to be persisted.

Not really, to me this seems to be the very opposite problem, the `assign` call is not changing the property at all:

```ts
// both logs will report `User { id: 1, value: false } { id: 1, value: 'false' }`
console.log(res, wrap(res, true).__originalEntityData);
wrap(res).assign({ value: { lol: true } });
console.log(res, wrap(res, true).__originalEntityData);
```

**Comment by ThatOneAwkwardGuy** [comment]
Ah, you're probably right, got confused when comparing my bools most likely

**Comment by ThatOneAwkwardGuy** [comment]
Ah, I only looked at the customType if statement because I assumed JSONType was being treated as such.
```
      if (prop.customType && platform && convertCustomTypes) {
```

Would it be worth treated it like a customType and doing an early return?

**Comment by B4nan** [comment]
It is treated as a custom type, but that is irrelevant, the problem is about object merging, not about mapping values from/to database types.
