### ISSUE TITLE
v6: `.serialize` is not a function when using wrap without `preferHelper` set to `true` and an entity that extends `BaseEntity`

### ISSUE THREAD

**Issue by SpencerKaiser** [mikro-orm/mikro-orm#4301]
**Describe the bug**
Using `wrap(entity).serialize()` results in a thrown error when the `preferHelper` arg is not set to `true`

**[Repro](https://stackblitz.com/edit/mikro-orm-v6-strict-partial-loading-w9tfgm?file=entities%2Fauthor.ts,basic.test.ts)**

**To Reproduce**
1. Retrieve an entity that extends `BaseEntity`
2. Use `wrap(entity).serialize()`
3. Observe thrown error at runtime

**Expected behavior**
Serialize will function as the types indicate the method is present

**Versions**

| Dependency | Version |
| - | - |
| mikro-orm | 6.0.0-dev.66 |

**Comment by B4nan** [comment]
Fixed via [8c54544](https://github.com/mikro-orm/mikro-orm/commit/8c54544fbe99252ccfe62280d31295c3749bb741)
