### ISSUE TITLE
Hooks priority execution

### ISSUE THREAD

**Issue by brunoqs** [mikro-orm/mikro-orm#4309]
**Is your feature request related to a problem? Please describe.**
In current version there is no way to define order when execute hooks

**Describe the solution you'd like**
I will be cool if its easy to define the priority into each hook

**Describe alternatives you've considered**
Something like this @BeforeUpdate({priority: 10}), the default priority could be 0, and the higher the priority the sooner the hook will be executed

**Comment by B4nan** [comment]
> In current version there is no way to define order when execute hooks

Hooks are executed in the same order as you define them. Or does it not work for you this way?

**Comment by B4nan** [comment]
Moreover, you can always define one "meta hook" which will orchestrate multiple methods. I don't think we need more than that.

**Comment by brunoqs** [comment]
Dou you have an example, of how to create a meta hook ?

**Comment by B4nan** [comment]
Just create one hook, the rest are regular methods/functions that you call from inside it.
