### ISSUE TITLE
OneToOne as primary key

### ISSUE THREAD

**Issue by jshearer** [mikro-orm/mikro-orm#431]
**Describe the bug**
I'm working on a project (https://github.com/mikro-orm/mikro-orm/issues/427) where I need a one-to-one linked table. What I want is to describe the secondary table as having a 1:1 field that is also its primary key. This seems to generate a migration and run fine, but the foreign key constraint is missing.

**To Reproduce**
My two tables are:

```es6
// Report.entity.ts -- must be in separate files for circular references to work
@Entity()
export class Report extends BaseEntity {
    @OneToOne(
        () => ReportLog,
        log => log.report,
    )
    public log: IdentifiedReference<ReportLog>;

    constructor() {
        super();
        this.log = Reference.create(new ReportLog());
    }
}

// ReportLog.entity.ts
@Entity()
export class ReportLog {
    @PrimaryKey()
    @OneToOne({ inversedBy: "log" })
    report: Report;

    @Property({ columnType: "text" })
    logText: string;
}
```

The migration that gets generated here looks like this:

```es6
export class Migration20200328205247 extends Migration {
  async up(): Promise<void> {
    this.addSql('create table "report_log" ("report" json not null, "log_text" text not null);');
    this.addSql('alter table "report_log" add constraint "report_log_pkey" primary key ("report");');
  }
}
```
Missing the foreign key constraint.

**Additional context**

If I change my `ReportLog` to have a separately defined primary key, it works (but I have an unnecessary primary key column  😢)

```es6
// ReportLog.entity.ts
@Entity()
export class ReportLog {
    @PrimaryKey()
    id = uuid.v4();

    @OneToOne({ inversedBy: "log", joinColumn: "report_id" })
    report: Report;

    @Property({ columnType: "text" })
    logText: string;
}

// Migration
export class Migration20200328205507 extends Migration {
    async up(): Promise<void> {
       this.addSql(
            'create table "report_log" ("id" json not null, "report_id" varchar(255) not null, "log_text" text not null);',
        );
        this.addSql('alter table "report_log" add constraint "report_log_pkey" primary key ("id");');
        this.addSql('alter table "report_log" add constraint "report_log_report_id_unique" unique ("report_id");');

        this.addSql(
            'alter table "report_log" add constraint "report_log_report_global_id_foreign" foreign key ("report_global_id") references "report" ("global_id") on update cascade;',
        );
    }
}
```

As a side note, why are these primary key columns getting generated as `json`? Is this related to using UUID primary key columns?  Is it safe to change the column type to `uuid`? I'm using Postgres.

**Comment by B4nan** [comment]
You should not use `@PrimaryKey` decorator there. Generally one can use only one property decorator at a time (only exceptions are `@Index` and `@Unique`). There is runtime validation for this constraint, so will need to check why it wasn't triggered (I guess I forgot to include `@PrimaryKey` decorator in the list). 

Try this instead:

```typescript
// ReportLog.entity.ts
@Entity()
export class ReportLog {
    @OneToOne({ primary: true, inversedBy: "log" })
    report: Report;

    @Property({ columnType: "text" })
    logText: string;
}
```

> As a side note, why are these primary key columns getting generated as json? Is this related to using UUID primary key columns? x

Apparently it does not recognise the type correctly and falls back to `json` type (which is the default basically). Are you using the default ts-morph metadata provider? Just a guess, but have you also installed `@types/uuid` package? 

> Is it safe to change the column type to uuid?

Yes you can use `uuid` (via `columnType`), or set the `type` to `string` manually. Or maybe it would be enough to specify the type explicitly (which is needed if you are using reflect metadata provider), so `id: string = uuid.v4();`.

**Comment by jshearer** [comment]
Ooooh, I didn't know about `{primary: true}`, I was looking here: https://mikro-orm.io/docs/decorators#onetoone. Thanks for the hint!

> Are you using the default ts-morph metadata provider? Just a guess, but have you also installed `@types/uuid` package?

Yes, and yes. I went and set the type to `uuid` and it's working fine.

Thank you for putting in the effort to build a _good_ orm! This is so refreshing. I'd absolutely love to support this project financially whenever you put up a way to do that :)

**Comment by jshearer** [comment]
I'm going to close this since I think the `{primary: true}` answer solved my problem. Thanks!
