### ISSUE TITLE
Postgres @Enum migration generating invalid syntax

### ISSUE THREAD

**Issue by jshearer** [mikro-orm/mikro-orm#432]
**Describe the bug**
When modifying an existing string column to be an enum, the migration that gets generated seems to have a syntax error

**To Reproduce**
Start with this table, generate and run the initial setup migration:

```es6
@Entity()
export class Report extends BaseEntity {
    @Property()
    status: string;
}
```

All good. Now change `status` to an enum:

```es6
export enum ReportStatus {
    PENDING = "PENDING",
    RUNNING = "RUNNING",
    FINISHED = "FINISHED",
    ERRORED = "ERRORED",
}

@Entity()
export class Report extends BaseEntity {
    @Enum()
    status: ReportStatus = ReportStatus.PENDING;
}
```

Creating a migration for this results in this:

```es6
export class Migration20200328220156 extends Migration {

  async up(): Promise<void> {
    this.addSql('alter table "report" alter column "status" drop default;');
    this.addSql('alter table "report" alter column "status" drop not null;');
    this.addSql('alter table "report" alter column "status" type text check ("status" in (\'PENDING\', \'RUNNING\', \'FINISHED\', \'ERRORED\')) using ("status"::text check ("status" in (\'PENDING\', \'RUNNING\', \'FINISHED\', \'ERRORED\')));');
    this.addSql('alter table "report" alter column "status" set not null;');
  }
}
```

And executing that gives a syntax error:

```bash
$ /Users/js/Documents/.../node_modules/.bin/mikro-orm migration:up
== Migration20200328220156: migrating =======
mikro-orm migration:up

Migrate up to the latest version

Options:
  -t, --to       Migrate up to specific version                         [string]
  -f, --from     Start migration from specific version                  [string]
  -o, --only     Migrate only specified versions                        [string]
  -v, --version  Show version number                                   [boolean]
  -h, --help     Show help                                             [boolean]

error: alter table "report" alter column "status" type text check ("status" in ('PENDING', 'RUNNING', 'FINISHED', 'ERRORED')) using ("status"::text check ("status" in ('PENDING', 'RUNNING', 'FINISHED', 'ERRORED'))); - syntax error at or near "check"
```

The problem seems to be this line

```sql
alter table "report" alter column "status" type text check ("status" in (\'PENDING\', \'RUNNING\', \'FINISHED\', \'ERRORED\')) using ("status"::text check ("status" in (\'PENDING\', \'RUNNING\', \'FINISHED\', \'ERRORED\')));
```

If I drop my db and get rid of the initial migration, the `create table` statement gets generated and run correctly, so that's a fairly easy workaround for the moment.

**Additional info**

My `mikro-orm.config.ts`:

```es6
const config: Options<IDatabaseDriver<Connection>> = {
    entities: [BaseEntity, Report, Reporter, ReportLog],
    entitiesDirsTs: ["src"],
    type: "postgresql",
    host: "localhost",
    dbName: "reports",
};
```

P.S Sorry for making so many issues :)

**Comment by B4nan** [comment]
Hmm looks like this is actually an issue with knex: 

https://stackoverflow.com/questions/45299464/alter-table-modify-enum-in-knex-js-for-postgresql-gives-error

Will try to get around it somehow, not first knex problem I came across :) 

> P.S Sorry for making so many issues :)

No problem at all, well defined issues like this are welcome :) Better than a slack message that can easily get lost/forgotten.

**Comment by murbanowicz** [comment]
@B4nan  Does this PR solves this issue?
I am on v4, exactly same use case with PG and I am also getting string with type check instead of proper ENUM

**Comment by B4nan** [comment]
The tests are still there and they are passing...

**Comment by B4nan** [comment]
> I am also getting string with type check instead of proper ENUM

This is how enums are implemented, this is how knex works. No support for native enum unfortunately.

**Comment by murbanowicz** [comment]
Got it. Thank you for the explanation

**Comment by willsoto** [comment]
@B4nan sorry to necro an old issue, but I wanted to point out that Knex **does** support native enums on postgres. See the docs: https://knexjs.org/#Schema-enum

**Comment by B4nan** [comment]
I know it does, but we would have to implement all the schema diffing too (which might not be that hard, but still its much more work than using a bool flag in knex).

Open for PR if it's that important for somebody, personally the text columns with check constraints seem to be much better solution, but havent really used the native ones in the wild, so I might be wrong.
