### ISSUE TITLE
Allow specifying which fields to exclude from update in upsert/upsertMany functions

### ISSUE THREAD

**Issue by squivix** [mikro-orm/mikro-orm#4325]
**Is your feature request related to a problem? Please describe.**
Currently, when using the entity manager's `em.upsert` or `em.upsertMany` functions to upsert data, all fields other than the unique ones are included in the update. However, sometimes we need to keep some of the fields as they are if the row already exists, but insert a new value for them if it doesn't.

**Describe the solution you'd like**
I would like to be able to specify which fields to exclude from the on conflict update clause. Maybewe can add an `excludeFieldsOnUpdate` option in the `NativeInsertUpdateOptions` which is an array of field names that should be kept as is if the row already exists, but inserted with new values if it doesn't. 

The proposed option looks like:
```ts
const author = await em.upsertMany(Author, [
  { email: 'foo@bar.com', name:"Foo Bar", age: 33 },
  { email: 'lol@lol.lol', name:"John Doe", age: 666 },
], {excludeFieldsOnUpdate:["name"]});
```

**Describe alternatives you've considered**
Some alternatives are to use the query builder or a raw SQL query instead of the ORM's `em.upsert` or `em.upsertMany` functions, but it would be nice to have the option through the EntityManager.

**Additional context**
This is based on discussion #4317

**Comment by jsprw** [comment]
Have you worked on this yet? I'm also interested in this feature and will be able to work on this.

**Comment by squivix** [comment]
I 'm struggling to set up the repo and get it to  run as I'm not very familiar with docker. Also currently busy with some other stuff. Feel free to work on it. I will probably try again in about a week

**Comment by B4nan** [comment]
FYI https://github.com/mikro-orm/mikro-orm/issues/4602#issuecomment-1697242198
