### ISSUE TITLE
Question about Mongodb distinct

### ISSUE THREAD

**Issue by osayfun** [mikro-orm/mikro-orm#433]
I'm using mongodb driver so I can't use query builder. How can this be achieved?
```
db.inventory.distinct( "prices", { dept: "A" } )
```

**Comment by B4nan** [comment]
```typescript
em.getConnection().getCollection('prices').distinct({ dept: 'A' })
```

Make sure your `em` is correctly typed as `EntityManager<MongoDriver>` otherwise the `getCollection` method won't be there.

**Comment by osayfun** [comment]
Thanks for the help but I think the correct answer would be:
```
em.getConnection().getCollection('inventory').distinct('prices', { dept: 'A' });
```
