### ISSUE TITLE
Using `populate` does not work correctly for nested keys of the same name

### ISSUE THREAD

**Issue by strmer15** [mikro-orm/mikro-orm#4339]
**Describe the bug**

When using the `populate` option on a `findOne` query, the returned entity does not contain nested lists as expected when the keys in the `populate` array have the same name. Our models are:

`Order`: { lineItems, shipments }
`Shipment`: { lineItems, order }
`LineItem`: { order, shipment }

When I query like `findOne(Order, orderId, { populate: ['lineItems', 'shipments.lineItems'] })`, the resulting order that is returned has the `Order.lineItems` and `Order.shipments` populated, but the `Shipment.lineItems` are *not* populated.

The "fix" is to change `populate` to use `populate: ['lineItems', 'shipments']`; when I do that, all of the shipment's line items are now in the result correctly. However, this is not what I'd normally expect, since I didn't ask for them to be populated.

**Stack trace**

N/A

**To Reproduce**

A reproduction is available at https://github.com/strmer15/MikroOrmBug/tree/5.7.5_bug, let me know if you have any trouble following the steps.

**Expected behavior**

When querying for model and populating nested collections, each collection should be available on the result, even if they have the same name.

**Additional context**

N/A

**Versions**

| Dependency | Version |
| - | - |
| node | 18.15.0 |
| typescript | 5.0.4 |
| mikro-orm | 5.7.5 |
| pg | 8.10.0 |

**Comment by hilkeheremans** [comment]
Can confirm this: it's a broader problem it seems -- we are having similar issues trying to populated nested properties. It's causing issues in our production environment.

**Comment by B4nan** [comment]
Few notes:
- the test is passing if you clear the EM instead of using `refresh: true`
- this is not about matching names, the problem persists if I rename the other relation to `lineItems2`
- `em.create` marks the entity for persistence automatically, no need for the nested `persist->create` call
- `em.create` will handle the references for you, no need for the explicit `em.getReference` calls if you provide the FK value

Here is a simplified repro:

```ts
import { Collection, Entity, LoadStrategy, ManyToOne, OneToMany, PopulateHint, PrimaryKey, Property, Ref, Rel } from '@mikro-orm/core';
import { MikroORM } from '@mikro-orm/sqlite';
import { v4 } from 'uuid';

@Entity()
class Shipment {

  @PrimaryKey({ type: 'uuid' })
  id: string = v4();

  @Property()
  createdAt!: Date;

  @Property({ onUpdate: () => new Date() })
  updatedAt!: Date;

  @OneToMany(() => LineItem, li => li.shipment)
  lineItems2 = new Collection<LineItem>(this);

  @ManyToOne(() => Order, { hidden: true })
  order!: Rel<Order>;

}

@Entity()
class Order {

  @PrimaryKey()
  id!: number;

  @Property()
  number!: string;

  @Property()
  createdAt!: Date;

  @Property({ onUpdate: () => new Date() })
  updatedAt!: Date;

  @OneToMany(() => LineItem, li => li.order)
  lineItems = new Collection<LineItem>(this);

  @OneToMany(() => Shipment, s => s.order)
  shipments = new Collection<Shipment>(this);

}

@Entity()
class LineItem {

  @PrimaryKey()
  id!: string;

  @Property()
  sku!: string;

  @Property()
  name!: string;

  @Property()
  createdAt!: Date;

  @Property({ onUpdate: () => new Date() })
  updatedAt!: Date;

  @ManyToOne(() => Order, { ref: true, hidden: true })
  order!: Ref<Order>;

  @ManyToOne(() => Shipment, { ref: true, hidden: true })
  shipment!: Ref<Shipment>;

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    dbName: ':memory:',
    loadStrategy: LoadStrategy.JOINED,
    populateWhere: PopulateHint.ALL,
    entities: [Order, Shipment, LineItem],
  });
  await orm.schema.createSchema();
});

afterAll(() => orm.close(true));

test('4339', async () => {
  orm.em.create(Order, {
    id: 1234,
    number: '6789567833435',
    createdAt: new Date(),
    updatedAt: new Date(),
  });
  orm.em.create(Shipment, {
    id: '67e24192-4454-41d5-af5f-25940b63b759',
    order: 1234,
    createdAt: new Date(),
    updatedAt: new Date(),
  });
  orm.em.create(Shipment, {
    id: '8d466cb1-8abc-4423-a1a8-5081ec43d26e',
    order: 1234,
    createdAt: new Date(),
    updatedAt: new Date(),
  });
  orm.em.create(LineItem, {
    id: v4(),
    shipment: '67e24192-4454-41d5-af5f-25940b63b759',
    order: 1234,
    sku: 'TEST_SKU',
    name: 'Test Product',
    createdAt: new Date(),
    updatedAt: new Date(),
  });
  orm.em.create(LineItem, {
    id: v4(),
    shipment: '8d466cb1-8abc-4423-a1a8-5081ec43d26e',
    order: 1234,
    sku: 'TEST_SKU_2',
    name: 'Test Product 2',
    createdAt: new Date(),
    updatedAt: new Date(),
  })

  await orm.em.flush();

  const order = await orm.em.findOneOrFail(Order, 1234, {
    populate: ['lineItems', 'shipments', 'shipments.lineItems2'],
    refresh: true,
  });

  console.log(order);
  console.log(order.shipments[0]);
  expect(order.id).toBe(1234);
  expect(order.lineItems).toHaveLength(2);
  expect(order.shipments).toHaveLength(2);
  expect(order.shipments[0].lineItems2).toHaveLength(2);
});
```
