### ISSUE TITLE
Populate of ManyToOne property is sometimes delayed if multiple queries run simultaneously

### ISSUE THREAD

**Issue by co-sic** [mikro-orm/mikro-orm#4343]
**Describe the bug**
The eager loading of a ManyToOne property is sometimes delayed and happens after the enityManager has returned my request.

```typescript
@Entity()
export class LocalizedString {
 @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string;

  @Property()
  de_DE: string;
}

@Entity()
class Product {
@PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string;

@ManyToOne({ cascade: [Cascade.ALL], eager: true, nullable: false })
  title: LocalizedString;

  @ManyToOne({ cascade: [Cascade.ALL], eager: true })
  shortTitle: LocalizedString | null;
...
}

const products = await this.repository.find({ id: { $in: [...ids] } });
console.log(products);
```

If i log this i can see that sometimes the localized string entity for shortTitle is populated and sometimes it's only the id reference. I have debug mode on, so i can see, that if the entity was no populated on console.log, the db select happens after the log. 
The title property is always loaded correctly, it's only the shortTitle.
This was not the case with version 5.6.16, the same query worked fine there.

**Expected behavior**
Everything should be populated/loaded when the query returns

**Stack trace**
```
[query] select "c0".* from "contract_change" as "c0" where "c0"."contract_id" in ('4c202672-a8f9-4766-b4ec-0d4b70b43a80') order by "c0"."valid_from" asc [took 5 ms]
[query] select "c0".* from "contract_change" as "c0" where "c0"."contract_id" in ('4c202672-a8f9-4766-b4ec-0d4b70b43a80') order by "c0"."contract_id" asc [took 7 ms]
[query] select "p0".* from "product" as "p0" where "p0"."id" in ('e890d5c5-2ce0-4edc-9540-3d814490b1a2') [took 3 ms]
[query] select "p0".* from "product_feature_change" as "p0" where "p0"."contract_change_id" in ('5aa2749f-09d2-445b-8e5a-4864daeff7d3') order by "p0"."valid_from" asc [took 6 ms]
[query] select "b0".* from "base_product_options" as "b0" where "b0"."id" in ('fb949a96-ec38-4c90-9cdb-d5a6c033c3d8') order by "b0"."id" asc [took 1 ms]
[query] select "p0".* from "product" as "p0" where "p0"."id" in ('e890d5c5-2ce0-4edc-9540-3d814490b1a2') order by "p0"."id" asc [took 6 ms]
[query] select "l0".* from "localized_string" as "l0" where "l0"."id" in ('9058d920-0a51-45d3-91b6-ef861c450b4d') order by "l0"."id" asc [took 3 ms]
[
  Product {
    id: 'e890d5c5-2ce0-4edc-9540-3d814490b1a2',
    title: LocalizedString {
      id: '9058d920-0a51-45d3-91b6-ef861c450b4d',
      de_DE: 'CORE',
      en_US: null
    },
    shortTitle: (LocalizedString) { id: '8225c6cb-553c-4882-8131-5d771210745f' },
    ...
  }
]
GRAPHQL_ERROR message: Cannot return null for non-nullable field BaseProduct.shortTitle., path: getCustomerByCustomerNumber,contracts,0,currentContractChange,product,shortTitle, locations: [object Object]
POST /graphql 200 65.227 ms - 1420
[query] select "l0".* from "localized_string" as "l0" where "l0"."id" in ('8225c6cb-553c-4882-8131-5d771210745f') order by "l0"."id" asc [took 7 ms]
[query] select "p0".* from "product_feature_change" as "p0" where "p0"."contract_change_id" in ('5aa2749f-09d2-445b-8e5a-4864daeff7d3') order by "p0"."contract_change_id" asc [took 2 ms]
```

you can see here that the localized string with id ='8225c6cb-553c-4882-8131-5d771210745f' is fetched after the console.log statement

if you need a minimal reproduction i can try to get one tomorrow

**Versions**

| Dependency | Version |
| - | - |
| node | 20 |
| typescript | 5.0.4 |
| mikro-orm | 5.7.5 |

**Comment by B4nan** [comment]
Sounds like this: #4324

I was already looking into that, I have no idea how to fix this, but no plans to blindly revert things, that would only reopen other issues... If your code looks different, I need to see a complete repro for that.

**Comment by co-sic** [comment]
I tried to get a working reproduction but it seems it's a little more complex. I will try next week again when i have more time. What i found out from testing with my production graphql service is:
- It happens when i have 2 different queries, that include the same product entity (i have one where i directly fetch the product by id (first query)  and one where i fetch something different and populate the product on it (second query))
- If i remove eager from the entity definition and in my second query use populate for the shortTitle and title, it works all the time.
- The two queries are run at the same time and 2 cases happen:
1. 
```
- First query runs
- Second query runs
- Some populate queries
- populate query of the shortTitle
- first query returns the promise.
- some more populate queries related to second query only
- second query returns the promise.
```
2.
```
- First query runs
- Second query runs
- Some populate queries
- first query returns the promise.
- populate query of the shortTitle
- some more populate queries related to second query only
- second query returns the promise.
```
So in the second case the first query returns before the populate of the required shortTitle. This happens in like 3/10 times i run exactly the same thing.
Not sure if this helps at all, like i said i will try to get a minimal reproduction, but it seems like a rare case.

**Comment by B4nan** [comment]
I really dont think this is about resolving too early, there is no ignored promise in the codebase or some other code that could result in that. This will be more about a race condition that results in overriding some values, or a clash in population.

**Comment by co-sic** [comment]
@B4nan i got a minimal reproduction Repository ready now. It seems like this happens if the same entity is queried at the same time with populate, but only under specific conditions. (E.g. if i remove one of the localized strings, it works): https://github.com/co-sic/node-mikro-orm-playground

**Comment by co-sic** [comment]
Hey @B4nan sorry to ping you again, but is this something you will have a look at? And if not can you maybe give me some hints where to look so i can maybe open a PR if i find the time. Currently we can't upgrade any of our microservices to a version above 5.6.16 with this still not resolved.

**Comment by B4nan** [comment]
Looks like this particular line is what breaks it. The second promise is probably fast enough to set the `__loadedRelations` value, and makes the first promise skip it.

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/entity/EntityLoader.ts#L261

cc @parisholley

**Comment by co-sic** [comment]
Okay, thank you for looking further into this! So you already know what to change in order for this to work again? Of course it would be better if it would not break the other issue, but for me this issue here sounds way for problematic. Especially because it is sometimes unreliable (in my productions case it was working in 7/10 cases for the same query) and just does not behave like you would expect, so it can lead to very hard to track bugs. It also took me some time to figure out what the root problem is.

**Comment by B4nan** [comment]
The changes that broke it are quite minimal, it's literally two lines that are causing this, and I agree it's probably better to revert those, I was trying to find a different way to make both things passing but no luck so far. Too bad the #4324 has a different cause...

**Comment by B4nan** [comment]
Got some good news #4415

**Comment by co-sic** [comment]
Awesome
