### ISSUE TITLE
new `const` enums break isolated modules

### ISSUE THREAD

**Issue by johanneslumpe** [mikro-orm/mikro-orm#4350]
**Describe the bug**
With the recent change of some enums to being `const`, mikro-orm fails to compile for applications using the `isolatedModules` flag. This is a breaking change in a minor version upgrade. Are you open to reverting the `const enum` changes?

**To Reproduce**
1. set up a TypeScript project with `isolatedModules` set to `true`
2. try using a const enum, e.g. `LockMode`
3. compile application

**Expected behavior**
Application should compile just fine.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 18.14.1 |
| typescript | 4.9.5|
| mikro-orm | 5.7.6||
| @mikro-orm/postgresql |5.7.6|

**Comment by B4nan** [comment]
Huh, that wasn't intentional, will revert that if its really breaking. I dont have time right now, will do tomorrow.

**Comment by johanneslumpe** [comment]
Awesome, appreciate it :)

**Comment by B4nan** [comment]
Hmm, I see this is a quite common issue, e.g. vue suffers from this too, and I'd guess it boils down to https://github.com/microsoft/TypeScript/issues/37774, as the enum is exported correctly, this seems to be just a type-checking error (so you could get around it via `skipLibChecks`).

I will revert it completely, the perf impact was hardly measurable, it just felt nice to inline those (mainly the `ReferenceType`, I might introduce some internal const enum just for that - and that one could be numeric, which could have a more positive effect when inlined).

**Comment by johanneslumpe** [comment]
Appreciate the quick help!
