### ISSUE TITLE
SQLite drivers return timestamp for `Date | null` fields

### ISSUE THREAD

**Issue by piotr-cz** [mikro-orm/mikro-orm#4362]
**Describe the bug**

When using SQLite driver, date values with nullable decorator are returned as timestamps instead of date objects.

Documentation > Property Validation > [Note about optional properties and metadata reflection](https://mikro-orm.io/docs/property-validation#note-about-optional-properties-and-metadata-reflection) states:

> ...if we would use a type union like `string | null`, reflect-metadata won't help us with such type, and we will be forced to define it explicitly.

however there is no example how to define type expicitely.

Problem may be reproduced with [koa-ts-example-app](https://github.com/mikro-orm/koa-ts-example-app):

in https://github.com/mikro-orm/koa-ts-example-app/blob/master/app/entities/BaseEntity.ts#L8-L9 change:

```diff
 import { PrimaryKey, Property } from '@mikro-orm/core';

 export abstract class BaseEntity {

   @PrimaryKey()
   id!: number;

-  @Property()
-  createdAt: Date = new Date();
+  @Property({ type: 'datetime', nullable: true })
+  createdAt: Date | null = new Date();

   @Property({ onUpdate: () => new Date() })
   updatedAt: Date = new Date();

 }
```

**Stack trace**
N/A

**To Reproduce**
1. Change the code in [koa-ts-example-app](https://github.com/mikro-orm/koa-ts-example-app) as in description above, start server (`npm run start:dev`)
2. Add new item: `curl -X POST "http://localhost:3000/author" -d 'name=John&email=john@doe.com'`:
  ```jsonc
  {
    "id":1,
    "createdAt":"2023-05-18T08:51:44.198Z", // Correct, value from memory
    "updatedAt":"2023-05-18T08:51:44.198Z",
    "termsAccepted":false,
    "books":[],
    "name":"John",
    "email":"john@doe.com"
  }
  ```
4. Get new item: `curl -X GET "http://localhost:3000/author/1?id=1"`
  ```jsonc
  {
    "id":1,
    "createdAt":1684399904198, // Value from database should be "2023-05-18T08:51:44.198Z"
    "updatedAt":"2023-05-18T08:51:44.198Z",
    "name":"John",
    "email":"john@doe.com",
    "age":null,
    "termsAccepted":"0",
    "born":null,
    "favouriteBook":null
  }
  ```

**Expected behavior**
Datetime columns should return date object, serializable to ISO8601 format

**Additional context**
I prefer to use `null` instead of `undefined` so field is being serialized in reply.

- Issue may be worked around by setting `type: Date`, however it's an undocumented feature
- What doesn't work:
  - `type: 'datetime', nullable: true`
  - `type: DateTimeType, nullable: true`
  - `type: types.datetime, nullable: true`
  - `columnType: 'datetime', nullable: true`

**Versions**

| Dependency | Version |
| - | - |
| node | 16.18.0 |
| typescript | 5.0.4 |
| mikro-orm | 5.7.7 |
| your-driver | @mikro-orm/sqlite: 5.7.7 / @mikro-orm/better-sqlite@5.7.7  |

**Comment by B4nan** [comment]
This is a bit more tricky than I have guessed, I will try to refactor this in v6 so the mapping of date columns is done via the `DateTimeType` instead of relying on the conversions provided by the other drivers. Want to keep that for v6 as it might have some side effects.

**Comment by B4nan** [comment]
As a workaround, just do `type: 'Date'`, it has the very same effect - that is what gets inferred via reflect-metadata. 

I think I should also change this in v6 finally, and only consider `Date` object as datetime, not a string `'date'`.

**Comment by piotr-cz** [comment]
> As a workaround, just do `type: 'Date'`, it has the very same effect - that is what gets inferred via reflect-metadata.
> 
> I think I should also change this in v6 finally, and only consider `Date` object as datetime, not a string `'date'`.

Thanks, this works.
I'll keep the issue open for You to decide

**Comment by B4nan** [comment]
Closing as resolved in v6
