### ISSUE TITLE
Cant update boolean property to false in entity

### ISSUE THREAD

**Issue by niklas-stegmann** [mikro-orm/mikro-orm#4363]
**Describe the bug**
I have a field in the user entity that is a boolean value with a default value of "false". When I try to update a user record that has the field set to true, the field is not updated in the database.

**To Reproduce**
1. Create the following entity:
```ts
@Entity({
  tableName: "users"
})
export class UserEntity {
  @PrimaryKey({ columnType: "uuid" })
  id!: string;
  
  @Property()
  showedTutorial? = false;
}
```

2.  Try to update the user entity and set "showedTutorial" to false
```ts
    const user = await this.entityManager.findOne(UserEntity, {
      id: id
    }) as UserEntity;

    user.showedTutorial = false;

    await this.entityManager.upsert(UserEntity, user);

    await this.entityManager.flush();
```

or

```ts
    await this.entityManager.nativeUpdate(
      UserEntity,
      {
        id: id
      },
      {
        showedTutorial: false
      }
    );
```

4. "showedTutorial" is not updated in the database

**Expected behavior**
"showedTutorial" should be "false" in the database.

**Versions**

| Dependency | Version |
| - | - |
| node | v18.16.0 |
| typescript | 4.7.4 |
| mikro-orm | 5.6.13 |
| @mikro-orm/postgresql | 5.6.13 |

**Comment by B4nan** [comment]
And a third one - why are you even doing this? Why the `upsert` call? It doesn't make any sense, you already know the entity exists, you want to update it, not upsert it. If you drop the `upsert` call, does it work?

**Comment by niklas-stegmann** [comment]
> And a third one - why are you even doing this? Why the `upsert` call? It doesn't make any sense, you already know the entity exists, you want to update it, not upsert it. If you drop the `upsert` call, does it work?

I first tried a nativeUpdate, but that didn't work. Then I tried it again with an upsert.

**Comment by niklas-stegmann** [comment]
> 2\. Always update to latest before reporting anything.

Sorry my fault: I extracted the wrong version from the package.json:

mikro-orm: 5.7.7
@mikro-orm/postgresql: 5.7.7

**Comment by B4nan** [comment]
> I first tried a nativeUpdate, but that didn't work. Then I tried it again with an upsert.

What do you mean "didnt work", it is literally a shortcut for query builder, it won't ignore anything. So what query did it fire? I did a quick test and it does work just fine on my end. Note that I tried with the correct proper definition - stating the type explicitly - that is a limitation of reflect-metadata, it won't give you any type back if there is a property initializer (and this problem is "fixed" in v6).

**Comment by B4nan** [comment]
Apparently it works even without the explicit type:

```ts
import { Entity, PrimaryKey, Property } from '@mikro-orm/core';
import { MikroORM } from '@mikro-orm/postgresql';

@Entity({
  tableName: 'users',
})
export class UserEntity {

  @PrimaryKey()
  id!: number;

  @Property()
  showedTutorial? = false;

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [UserEntity],
    dbName: `mikro_orm_test_gh_4363`,
    debug: true,
  });
  await orm.schema.refreshDatabase();
});

afterAll(() => orm.close(true));

test('4363', async () => {
  // fires: `[query] update "users" set "showed_tutorial" = false where "id" = 123 [took 1 ms]`
  await orm.em.nativeUpdate(UserEntity, { id: 123 }, { showedTutorial: false });
});
```

**Comment by niklas-stegmann** [comment]
Oh man, I'm sorry. I just looked at the query logs and saw that first a query is executed which sets the value to false. Then another call was made by a redirect in the frontend which set the value to true again.

I don't know how I could have missed that.... 😐 Sorry for that!
