### ISSUE TITLE
Loops in hydrate / clone

### ISSUE THREAD

**Issue by urshofer** [mikro-orm/mikro-orm#4376]
**Describe the bug**
The hydration process clones recursively and produces sometimes long lasting loops.

**Stack trace**

<img width="2021" alt="Bildschirmfoto 2023-05-22 um 12 44 30" src="https://github.com/mikro-orm/mikro-orm/assets/116976/fd98090e-2b4a-48a4-836d-8216e01bd3dd">

**Additional context**

I have a nested data structure:

```Contributions > OneToMany > Data > ManyToMany > Contributions```

Items are joined with data fields, whereas these fields can be linked to other items - possibly creating also endless loops. I'm aware that a loop should not exist, I can prohibit this, but there are situation where Mikro Orm needs a lot of time to hydrate even if there is no loop.

**Versions**

| Dependency | Version |
| - | - |
| node |18 |
| typescript | 4.9.5 |
| mikro-orm | 5.7.8 |
| your-driver | 5.7.8 |

**Comment by urshofer** [comment]
I could figure out that omitting the inversion in contributions speeds up the process, but I need it sometimes : )

```
  @ManyToMany({ entity: () => Data, mappedBy: 'rdatacontribution' })
  rdatacontributionInverse = new Collection<Data>(this);
```

**Comment by B4nan** [comment]
Actually, seeing that crazy query you have in there, I feel like this is a wont fix - you should really use select-in strategy instead of doing crazy joins, they always produce cartesian products with every to-many relation you join, causing heavy perf costs - this is usually a problem in your code, not something to fix in the ORM.

**Comment by urshofer** [comment]
Yeah I know. I have this idea of porting an old backend to a new infrastructure and keeping the database, so I could run both old and new on top of the same database. That's why the weird structure.

The thing with the query is: It runs fairly quick on MySQL Side (~75ms, 364 Results). The population of the data afterwards thake 8 seconds. Trying to figure out a reproduction though.

**Comment by urshofer** [comment]
I guess this does not work as a drop in replacement since clone in Mikro Orm is also used to clone functions.

> Am 22.05.2023 um 15:11 schrieb Martin Adámek ***@***.***>:
> 
> structuredClone

**Comment by B4nan** [comment]
As I said, the implementation is taken from a 3rd party package, I don't think we need to copy functions anywhere, definitely not in that `mergeData` function that triggers it for this case, that is just about copying a POJO before hydration, there should be only (sometimes nested) values.

**Comment by B4nan** [comment]
Huh, there should be no such thing in the `data`, that must be coming from one of the (non-enumerable) hidden symbols with the metadata or the state.

What do you get if you `console.log(data, new Error().stack)` in there?

**Comment by B4nan** [comment]
I think I see what's happening.

**Comment by urshofer** [comment]
Thanks! Huge Performance boost. The duration drops from 7500ms to 316ms. Processing of 1004 rows of a mysql result that lead to 33 hydrated items still lasts for about 300ms in my case, but it seems to be linear now. Profiler shows that it is spending about 55ms in the ArrayCollection `get property()` function, mainly in the line

`const field = Object.keys(meta.properties).find(k => this.owner[k] === this);`


```
  /**
   * @internal
   */
  get property(): EntityProperty<T> {
    if (!this._property) {
      const meta = helper(this.owner).__meta;

      /* istanbul ignore if */
      if (!meta) {
        throw MetadataError.fromUnknownEntity((this.owner as object).constructor.name, 'Collection.property getter, maybe you just forgot to initialize the ORM?');
      }

     const field = Object.keys(meta.properties).find(k => this.owner[k] === this);
      this._property = meta.properties[field!];
    }

    return this._property!;
  }
```

**Comment by B4nan** [comment]
Weird, maybe you have a lot of properties and the `Object.keys(meta.properties)` is slow? Nowadays we also have `meta.props` array, can you try to change it to this and see if it helps?

```diff
-const field = Object.keys(meta.properties).find(k => this.owner[k] === this);
-this._property = meta.properties[field!];
+this._property = meta.props.find(prop => this.owner[prop.name] === this);
```

**Comment by urshofer** [comment]
There is a slight difference, and since the code is anyway more readable, I would agree to this change :). Probably there are more situations like this which could be tuned.

Old: 

<img width="685" alt="Bildschirmfoto 2023-05-23 um 11 32 24" src="https://github.com/mikro-orm/mikro-orm/assets/116976/5a3ce005-83ea-4c68-9513-6d0db10c0709">

Modified:

<img width="704" alt="Bildschirmfoto 2023-05-23 um 11 29 47" src="https://github.com/mikro-orm/mikro-orm/assets/116976/61164904-4307-4e26-bd18-578732ac703f">

**Comment by B4nan** [comment]
62% reduction seems pretty nice on its own :] 

Since we are only interested in relation properties, this could be improved even more by using `meta.relations` instead of `meta.props`.
