### ISSUE TITLE
Can not populate OneToOne relation on inverse side

### ISSUE THREAD

**Issue by artur-dani** [mikro-orm/mikro-orm#4378]
**Describe the bug**
I just upgraded from v5.4.2 to v5.7.7  and it seems that i can not populate OneToOne relation from the inverse side

```
@Entity()
export default class Receipt {
@OneToOne(() => Payment, (payment) => payment.receipt, {
    owner: true,
    nullable: true,
  })
  payment: Payment;
}
```
```
@Entity()
export default class Payment {
@OneToOne(() => Receipt, (receipt) => receipt.payment)
  receipt: Receipt;
}
```
```
export type ReceiptData = Partial<Payment> &  Required< Pick< 'receipt'>  >;
```
and I used this same code (without any change) in both versions.
```
public async create(paymentData: PaymentData) {
    // const payment = new Receipt(paymentData);
    const payment = this.repo.create(paymentData);

    await this.repo.persistAndFlush(payment);

    return receipt;
  }
```

**Versions**

| Dependency | Version |
| - | - |
| node | 16.18 |
| typescript | 4.3.5 |
| mikro-orm | 5.7.7 |
| your-driver | postgres |

**Comment by B4nan** [comment]
Please share complete reproduction, not just snippets.

**Comment by B4nan** [comment]
Also please try v5.7.9, I just fixed one thing that might be affecting this case too.

**Comment by artur-dani** [comment]
The v5.7.9 version seems not to fix the issue.
Anyway I really appreciate your efforts, unfortunately I dont have enough time to share a reproduction atm.
I will give it another try during coming weekend and maybe provide more details.

I just needed the standalone serialization feat from the newer version though :(

**Comment by B4nan** [comment]
Ok then, I will close this for now as it's not actionable, let's reopen with the reproduction.

**Comment by B4nan** [comment]
Btw you said you have issues populating stuff, but you haven't shared any code that would do population or loading, can you at least share that? Maybe it's something wrong in there.
