### ISSUE TITLE
`null` unexpectedly removed from JSON properties

### ISSUE THREAD

**Issue by wSedlacek** [mikro-orm/mikro-orm#4383]
**Describe the bug**

`null` is removed from JSON objects by serializer.

**Stack trace**
```
Error
    at /Users/wsedlacek/Code/work/shipyard/node_modules/.pnpm/@mikro-orm+core@5.7.8_@mikro-orm+migrations@5.7.8_@mikro-orm+postgresql@5.7.8/node_modules/@mikro-orm/core/serialization/EntitySerializer.js:63:29
    at Array.map (<anonymous>)
    at Function.serialize (/Users/wsedlacek/Code/work/shipyard/node_modules/.pnpm/@mikro-orm+core@5.7.8_@mikro-orm+migrations@5.7.8_@mikro-orm+postgresql@5.7.8/node_modules/@mikro-orm/core/serialization/EntitySerializer.js:53:14)
    at /Users/wsedlacek/Code/work/shipyard/node_modules/.pnpm/@mikro-orm+core@5.7.8_@mikro-orm+migrations@5.7.8_@mikro-orm+postgresql@5.7.8/node_modules/@mikro-orm/core/serialization/EntitySerializer.js:167:75
    at Array.map (<anonymous>)
    at serialize (/Users/wsedlacek/Code/work/shipyard/node_modules/.pnpm/@mikro-orm+core@5.7.8_@mikro-orm+migrations@5.7.8_@mikro-orm+postgresql@5.7.8/node_modules/@mikro-orm/core/serialization/EntitySerializer.js:167:49)
```

**To Reproduce**

Store `{ "foo": null }` in a database (tested with postegress)
Query database with MikroORM and `foo` will be missing.

**Expected behavior**
`null` would be retained in JSON properties.

**Additional context**

This appears to be introduced with this change.
https://github.com/mikro-orm/mikro-orm/commit/4cf766932e902cc96d56b2a9aa9d1215785c8ad6

Setting `skipNull` to `true` nor `false` allows bypassing this behavior.

**Versions**

| Dependency | Version |
| - | - |
| node | v18.14.2 |
| typescript | 5.0.4 |
| mikro-orm | 5.7.8 |
| postgresql | 5.7.8 |

**Comment by B4nan** [comment]
I am a bit confused, what are you reporting here, that the `skipNulls` option is not respected, that it always behaves like it was true? In other words, that the condition there should be this?

```ts
if (options.skipNull && Utils.isPlainObject(val)) {
  Utils.dropUndefinedProperties(val, null);
}
```

Or is this about wiping the values from database?

**Comment by wSedlacek** [comment]
So I am querying from the database, no writes are being preformed.
I have `{ "foo": null }` in a `JsonType` in a table and when I query it I get back `{}`
Removing `Utils.dropUndefinedProperties(val, null);` allows me to get `{ "foo": null }`.

As far as what the default should be, I don't have an opinion, but as far as I can see there isn't a way to get `{ "foo": null }` in the current version. Using `skipNull` as a condition would solve my issue as I could set that to `false` and get the output I want.

**Comment by wSedlacek** [comment]
Thank you! You are awesome!
