### ISSUE TITLE
EventSubscriber - can't subscribe to single entity

### ISSUE THREAD

**Issue by Arcus16** [mikro-orm/mikro-orm#4400]
**Describe the bug**
I want to use `EventSubscriber` to listen for `afterFlush` events and execute some code afterward. 
This is my code:
```typescript
@Injectable()
export class AccountSubscriber implements EventSubscriber<Account> {
    public constructor(
        private readonly em: EntityManager,
    ) {
        em.getEventManager().registerSubscriber(this);
    }

    getSubscribedEntities(): EntityName<Account>[] {
        return [Account];
    }

    async afterFlush(args: FlushEventArgs): Promise<void> {
        const changeSets = args.uow.getChangeSets();
        // ... some additional code
    }
}
```
```typescript
@Entity()
export class Account extends BaseEntity<Account, 'id'> {
    @PrimaryKey()
    id!: number;
    @Property({ type: StringType, length: 100, nullable: true })
    name!: string | null;
    @Property({ default: false })
    personal!: boolean;
}
```

The `AccountSubscriber` should be subscribed only to `Account` entity changes. However, the `afterFlush` function is triggered even when modifying other entities.

**Expected behavior**
The `afterFlush` in `AccountSubscriber` should be called only for `Account` entity changes.

**Additional context**
I tried to debug it and I found out that [entity here](https://github.com/mikro-orm/mikro-orm/blob/55a5f025b89805bfe614da96b025b60c7043c3c3/packages/core/src/events/EventManager.ts#L33) is always `undefined` in my case and because of [this if](https://github.com/mikro-orm/mikro-orm/blob/55a5f025b89805bfe614da96b025b60c7043c3c3/packages/core/src/events/EventManager.ts#L46) the subscriber will be called. I also find out that from [here](https://github.com/mikro-orm/mikro-orm/blob/55a5f025b89805bfe614da96b025b60c7043c3c3/packages/core/src/unit-of-work/UnitOfWork.ts#L396) the `afterFlush` event is dispatched without the `entity` set. 

**Versions**

| Dependency | Version |
| - | - |
| node | 18.15.0 |
| typescript | 4.9.4 |
| mikro-orm | 5.6.15 |
| mysql | 2.18.1 |

**Comment by B4nan** [comment]
Flush events are not entity bound, this is on purpose, you subscribe to the event, not to changes on entity.
