### ISSUE TITLE
MongoDB querying on relationship fields

### ISSUE THREAD

**Issue by ujwal-setlur** [mikro-orm/mikro-orm#441]
**Describe the bug**
I don't know if this is a bug, but I can't figure it out. It's a very simple case. I am using OneToMany(), say ```Discount``` and ```Store``` with multiples stores to a discount:

```ts
  @OneToMany(
    () => DiscountStore,
    discountStore => discountStore.discount
  )
  stores = new Collection<DiscountStore>(this);
```

I am trying to query the ```Discount``` entity on a ```Store``` property:
```ts
  const [discounts, count] = await em.getRepository(Discount).findAndCount(
    {
      stores: {
        storeId: 1234
      }
    },
    { populate: ['categories', 'skus', 'stores', 'transactions'] }
  );
```
But I get nothing back.

This works where ```clientId``` is a direct property:
```ts
  const [discounts, count] = await em
    .getRepository(Discount)
    .findAndCount(
      { clientId: 1 },
      { populate: ['categories', 'skus', 'stores', 'transactions'] }
    );
```

**Stack trace**
This is the mongo query that is actually happening, and it looks incorrect since ```stores``` field is actually not in the ```discount``` collection:
```
  console.log node_modules/mikro-orm/dist/utils/Logger.js:22
    [query] db.begin();

  console.log node_modules/mikro-orm/dist/utils/Logger.js:22
    [query] db.getCollection('discount').find({ stores: { storeId: 1234 } }, { session: '[ClientSession]' }).toArray(); [took 2 ms]

  console.log node_modules/mikro-orm/dist/utils/Logger.js:22
    [query] db.getCollection('discount').countDocuments({ stores: { storeId: 1234 } }, { session: '[ClientSession]' }); [took 3 ms]

  console.log node_modules/mikro-orm/dist/utils/Logger.js:22
    [query] db.commit();
```

Here is what is in the mongodb:
```
rs:PRIMARY> db['discount'].find({})
{ "_id" : ObjectId("5e8514723c733927d2b33a0f"), "createdAtMs" : 1585779826405, "start" : ISODate("2020-01-21T04:11:22Z"), "clientId" : 1, "exclusive" : false, "amountOff" : 4, "billedToLocation" : 0 }
rs:PRIMARY> db['discount-store'].find({})
{ "_id" : ObjectId("5e8514723c733927d2b33a10"), "storeId" : 1234, "discount" : ObjectId("5e8514723c733927d2b33a0f") }
rs:PRIMARY>
```

What am I doing wrong? This seems to work with ```sqlite```

**Versions**

| Dependency | Version |
| - | - |
| node | 12.16 |
| typescript | 3.8.3 |
| mikro-orm | 3.6 |
| your-driver | MongoDriver |

**Comment by B4nan** [comment]
This is not supported in mongo. There are no joins, so I do not see any way to achieve it (other than using `$lookup`, but that has performance implications, it does not work the same way as joins). 

You have basically 2 options:
- query from the other side (find store first, and populate its discounts)
- denormalize, so you have the array of store ids in the inverse side (discount entity)

Btw you can see what query it produced - it tries to find discount entity based on `stores` property, when there is no such property, that is only virtual/orm mapping thing. You can always try to use that query directly (like in robomongo) to see.

I will put a not about this into the docs.

**Comment by ujwal-setlur** [comment]
Thanks @B4nan. I came to the conclusion that this is not supported as well. Unfortunately, either option is not great for us, so we will likely stick with SQL, which is not a terrible choice for our purpose :-)

Thank you for being so very prompt with responses.

**Comment by ujwal-setlur** [comment]
@B4nan By the way, there is a very cool package called [grapher](https://github.com/cult-of-coders/grapher) that works with Meteor and Mongo that does a lot of very cool query stuff on Mongo. It's meteor only package, but I wonder if some concepts could be utilized? I have used this a lot in the meteor world, and it is fantastic.

**Comment by B4nan** [comment]
Do you have any specific example?

**Comment by ujwal-setlur** [comment]
Example about how I have used grapher? As I said, I have used it in the meteor world. It allows you to establish links (relationships) and inverse links. And it allows you to query in both directions. I am not exactly sure what it does under the hood, but it is very performant.

**Comment by ujwal-setlur** [comment]
Here is a similar bug report I opened against grapher :)

https://github.com/cult-of-coders/grapher/issues/282

**Comment by B4nan** [comment]
I mean example of what queries was it actually doing in this case (or what does similar bug report mean, is it the same use case or not?). From that we could see the trick easily...

But I really don't think this is possible without $lookup or denormalization...

**Comment by ujwal-setlur** [comment]
Fair enough. But it would be nice to offer the option of doing a $lookup. I am doing a microservices where each service manages its own data, so the individual data load would not be huge.
