### ISSUE TITLE
Performance statistics

### ISSUE THREAD

**Issue by john-yick** [mikro-orm/mikro-orm#442]
Does anyone have any performance statistics for Mikro-orm against TypeOrm? I am contemplating switching from TypeOrm to Mikro-orm as development has stalled over there. 

I am mainly targeting Postgres.

Thanks,
J

**Comment by B4nan** [comment]
I am not aware of anything, will be happy to do my part, do you know about some performance test suite for typeorm? Or ideally some comparison with other ORMs?

**Comment by john-yick** [comment]
@B4nan was hoping this was done already by someone else and was just hidden somewhere. I am also un-aware of any standard test suites, but I would assume a simple add 10,000 rows across multiple tables and do some queries with joins followed by some updates and deletions should give a good base line of how it performs.

**Comment by B4nan** [comment]
Well, this ORM is build on the concept of identity map and unit of work, so every entity you have loaded into the context will impact the performance (you can control this manually if needed). Having 10k entities in memory will obviously break it (or not break it, but slowdown a lot), but that would be a misusage. How would that show us anything, ORMs are not meant for data imports (there are methods you can use for this so you get around the identity map, so you can do it, but using identity map for such thing is just wrong). 

Or you mean doing some queries on a db with 10k rows? 

Btw I have one performance test in the repo, that is inserting 300 entities (keeping them in memory), and it works quite well (~500ms on my macbook). It is in the mongo test suite, as I wanted to test the ORM performance without having much db overhead. Also note that to measure correctly, one should understand that the `expect` does have quite a big impact on the numbers. 

https://github.com/mikro-orm/mikro-orm/blob/master/tests/EntityManager.mongo.test.ts#L1833

**Comment by john-yick** [comment]
@B4nan I mean load 10k of rows into something like SQLite, then perform queries across it. Loading 10k of items into memory will break most things.

I have a few projects in mind which I would like to use this for but need to know how it scales first. I shall take a look into the test.

**Comment by DominikMueller64** [comment]
@john-yick Performace of MikroOrm _feels_ better compared to TypeOrm. But for bulk data insertion and loading (10k rows into one table), I'm currently using https://github.com/vitaly-t/pg-promise and it works really great.

**Comment by john-yick** [comment]
@DominikMueller64 awesome that is good to know.

**Comment by B4nan** [comment]
Just FYI, there are `em.nativeInsert()`, `em.nativeUpdate()` and `em.nativeDelete()` methods that you can use to fire queries without touching the identity map, so handy for bulk operations and data imports.

https://mikro-orm.io/docs/usage-with-sql/#native-collection-methods

**Comment by DominikMueller64** [comment]
@B4nan But these methods do not support multi-row insertion as far as I can tell. Can you import let's say 10k rows with `em.nativeInsert()` in a reasonable amount of time? With [pg-promise](http://vitaly-t.github.io/pg-promise), it takes < 10 sec in my use case.

**Comment by B4nan** [comment]
Correct, that is missing now, but we can easily add that. For now you can use knex for multi inserts.

**Comment by B4nan** [comment]
Here you go: 

https://github.com/mikro-orm/benchmark

I might did something wrong in the typeorm part, so feel free to suggest changes.
