### ISSUE TITLE
upsert treat falsey value as missing

### ISSUE THREAD

**Issue by wenerme** [mikro-orm/mikro-orm#4420]
**Describe the bug**

<img width="580" alt="image" src="https://github.com/mikro-orm/mikro-orm/assets/1777211/35cb68b4-7a65-47b8-a19b-0d9dc289f88a">

the unique check should check undefined or null

https://github.com/mikro-orm/mikro-orm/blob/7bdd57c6437e8015d5f1be445a7736c413bbadce/packages/core/src/EntityManager.ts#L592-L599

**To Reproduce**

upsert with empty string

**Expected behavior**

works as expected

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | ? |
| typescript | ? |
| mikro-orm | ? |
| your-driver | ? |

**Comment by B4nan** [comment]
PR welcome
