### ISSUE TITLE
upsertMany should split to batch

### ISSUE THREAD

**Issue by wenerme** [mikro-orm/mikro-orm#4421]
**Describe the bug**

<img width="1002" alt="image" src="https://github.com/mikro-orm/mikro-orm/assets/1777211/492caff8-a79e-4c6d-bced-52286ffcb60d">

**Stack trace**

**To Reproduce**

upsertMany with a lot rows.

**Expected behavior**

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | ? |
| typescript | ? |
| mikro-orm | ? |
| your-driver | better-sqlite |

**Comment by B4nan** [comment]
What does "a lot" mean, how complex your entity is? Note that I can see from your screenshot that you don't await the upsert call.

**Comment by rubiin** [comment]
> **Describe the bug**
> 
> <img alt="image" width="1002" src="https://user-images.githubusercontent.com/1777211/243344831-492caff8-a79e-4c6d-bced-52286ffcb60d.png">
> **Stack trace**
> 
> **To Reproduce**
> 
> upsertMany with a lot rows.
> 
> **Expected behavior**
> 
> **Additional context**
> 
> **Versions**
> 
> Dependency	Version
> node	?
> typescript	?
> mikro-orm	?
> your-driver	better-sqlite

https://antfu.me/posts/why-reproductions-are-required

**Comment by wenerme** [comment]
for SQLIite `SQLITE_MAX_COMPOUND_SELECT=500` (https://www.sqlite.org/limits.html), it's easy to rich the limit when using batch, maybe related to how sqlite is generated, I think mikro orm should support the automatic batch split or allowed pass a batch size options.

I think this error is common enough, it's easy to get the point.
