### ISSUE TITLE
V6. When using a condition on a relationship that uses STI, the ORM may choose the wrong table alias for the discriminator value 

### ISSUE THREAD

**Issue by YanDjin** [mikro-orm/mikro-orm#4422]
**Describe the bug**
On the version 6, when using a find with a condition on a relation that uses STI, the ORM will sometimes choose the wrong table alias for the discriminator value. It seems to depend on the type of relation and the owning side.

**To Reproduce**
- create entities with relationships that use STI
- use a find with a smart condition on the relation
- on some occasions, the ORM will choose the wrong table alias for the discriminator value

https://github.com/YanDjin/mikro-orm/blob/bug/find-sti-relation/tests/issues/GH4422.test.ts
this link contains the test that replicates the issue.

**Expected behavior**
To choose the correct columns on the join and apply the discriminator condition on the right table.

**Versions**

| Dependency | Version |
| - | - |
| node | 18.16.0 |
| typescript | 5.0.4 |
| mikro-orm | 6.0.0-dev.82 |
| your-driver | postgres/sqlite |

**Comment by YanDjin** [comment]
maybe related to #4423

**Comment by B4nan** [comment]
Fixed via 05e371b
