### ISSUE TITLE
V6. When populating a Many-to-Many relationship that uses STI, the ORM joins on the wrong column of the pivot table

### ISSUE THREAD

**Issue by YanDjin** [mikro-orm/mikro-orm#4423]
**Describe the bug**
On the version 6, when populating a Many-to-Many relation that uses STI (i did not specify a strategy), the ORM joins on the wrong column of the pivot table.
I tried the same with a relation that does not use STI and it does not seem to have the same issue.

**To Reproduce**
- use an entity that has a Many-to-Many relationship with an entity that uses STI
- use a find on the entity that owns the relation
- specify the relation to be populated, without specifying a strategy
- when loading the relation, the ORM will join on the wrong column

https://github.com/YanDjin/mikro-orm/blob/bug/find-sti-relation/tests/issues/GH4423.test.ts
this link contains the test that replicates the issue.

**Expected behavior**
To join the populate request on the correct column of the pivot table

**Versions**

| Dependency | Version |
| - | - |
| node | 18.16.0 |
| typescript | 5.0.4 |
| mikro-orm | 6.0.0-dev.82 |
| your-driver | postgres/sqlite |

**Comment by YanDjin** [comment]
maybe related to #4422

**Comment by B4nan** [comment]
This one is a bit more tricky, I guess I will try to do a bigger refactor to get rid of the weird `loadFromPivotTable` driver method and use `em.populate` instead.

**Comment by YanDjin** [comment]
I just happened to add a hotfix PR, if you have the time to check it out :)

**Comment by B4nan** [comment]
I managed to remove the weird parts from QB (together with this problematic `qb.autoJoinPivotTable` method), still have a few failing tests to deal with, but this new solution does not suffer from the problem you have in the PR.
