### ISSUE TITLE
Wrong SQL when using multiple primary key in Entity

### ISSUE THREAD

**Issue by sonicgamer0721** [mikro-orm/mikro-orm#4439]
**Describe the bug**
There are 3 primary keys in Entity. Select/Insert/Delete works fine. But when I update records, the SQL is so weird, please help me!

**Entity:**
```
@Entity({ tableName: 'core_role_resources' })
@Unique({ properties: ['role', 'resource', 'isOriginal'] })
export class RoleResourcePermission {
  @ManyToOne(() => Role, {
    primary: true,
    onDelete: 'cascade',
  })
  role: Role;

  @Property({ primary: true })
  resource: string;

  @Property({ primary: true })
  isOriginal: boolean;

  @Property()
  canCreate: number;
...
}
```

**When I execute this code:**
```
const found = await em.findOne( RoleResourcePermission,
  {
    role: em.getReference(Role, 1),
    resource: 'scm',
    isOriginal: true,
  },
);
wrap(found).assign({ canCreate: 1 });
await em.flush();
```

**The SQL generated is wrong:**
```
update `core_role_resources` set `can_create` = 1 where ((0 = 's' and 1 = 'c' and 2 = 'm'))
```

**Additional context**
The same code ran successfully few months ago. This problem happened when I upgraded Mikro to the latest version.
Did I miss something?

**Versions**

| Dependency | Version |
| - | - |
| node | 18.16.0 |
| typescript | 5.1.3 |
| mikro-orm | 5.7.11 |
| @mikro-orm/mariadb | 5.7.11 |

**Comment by B4nan** [comment]
5.7.11 is not the latest version anymore, try updating first.

If updating won't help, I need to see a complete reproduction.

**Comment by B4nan** [comment]
Closing as stale, let's reopen with a failing repro. 

I kinda hope this could be resolved by https://github.com/mikro-orm/mikro-orm/commit/fbb6958944998ca1abee331002e5aedd8bfa9c37, so would be great if you could check latest dev version.
