### ISSUE TITLE
Executing migrations fails when pool is set to single connection

### ISSUE THREAD

**Issue by Haringat** [mikro-orm/mikro-orm#444]
**Describe the bug**
When the pool settings are set to min=1 and max=1 (single-connection-mode) the command "mikro-orm migration:up" fails after a while with the error below.

**Stack trace**
```
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (/home/marcel/projects/etaplus-connect-brick4u/node_modules/.pnpm/localhost+4873/knex/0.20.13_pg@7.18.2/node_modules/knex/lib/client.js:347:26) {
  name: 'KnexTimeoutError',
  sql: undefined,
  bindings: undefined
}
```

**To Reproduce**
1. create migration file
2. set pool size max and min to 1
3. run migration:up

**Expected behavior**
A success message when it is finished

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | v13.12.0 |
| typescript | 3.8.3 |
| mikro-orm | 3.6.0 |
| your-driver | pg(7.18.2) |

**Comment by B4nan** [comment]
Interesting, I guess there are some reads happening outside of transaction. Thanks for the report, those pool settings should be default for migrations anyway, so will also do that as part of the fix.

**Comment by hanzlahabib** [comment]
i am facing this issue without migration
