### ISSUE TITLE
V6. When using STI, and two different children of an STI have properties referencing different children of another STI, an error can occur on update

### ISSUE THREAD

**Issue by YanDjin** [mikro-orm/mikro-orm#4440]
**Describe the bug**
The scenario:
- STI 1 -> User has children Manager and Employee
- STI 2 -> Collaborator has children ManagerCollaborator and EmployeeCollaborator
  - Manager has a OneToMany relation to ManagerCollaborator
  - Employee has a OneToMany relation to EmployeeCollaborator

When fetching a ManagerCollaborator, the __originalEntityData will contain two entries with the same data, __originalEntityData .manager and __originalEntityData .employee because the are referencing the same column, even though the property employee does not exist in Manager
if you set this fetched managerCollaborator as a relation of another entity, and flush, the diff between the original data and the current data will get discovered and the EntityManager will try to update the entry.

**To Reproduce**
- Have two different STIs base entities
- Two of the children of STI 1 reference in OneToMany relationships different children of STI 2
- when finding a entity of STI 2, you will have two properties in the __originalEntityData containing the data, the property of the used entity, and the property in the other child

[https://github.com/YanDjin/mikro-orm/blob/bug/sti-update/tests/issues/GH4440.test.ts](https://github.com/YanDjin/mikro-orm/blob/bug/sti-update/tests/issues/GH4440.test.ts)
this test replicates the issue.

**Expected behavior**
The em should not make the diff using the columns of another child of the STI

**Versions**

| Dependency | Version |
| - | - |
| node | 18.16.0 |
| typescript | 5.0.4 |
| mikro-orm | 6.0.0-dev.86 |
| your-driver | postgres/sqlite |

**Comment by B4nan** [comment]
That repro is wrong, you can't use a detached entity this way, `managerCollaborator` is no longer managed after you call `em.clear()`. You should be doing this instead:

```ts
const manager = new Manager();
manager.email = 'bbb@aaa.com';
manager.managerCollaborators.set([orm.em.getReference(ManagerCollaborator, 1)]);
await orm.em.flush();
```

**Comment by B4nan** [comment]
Maybe we could treat entities managed by a different fork as a reference automatically, so your code would work automatically.

**Comment by YanDjin** [comment]
The bug occurs even without the em.clear(). I added that when I was trying to figure out from where the bug came from.
I will update the test, sorry for the confusion.

**Comment by YanDjin** [comment]
Can you please re-open the issue @B4nan ?

**Comment by B4nan** [comment]
The repro is still kinda wrong, you can't redefine a property in the child class, as all the child classes are merged to the base entity type, and that is used internally. This is a known problem, there are other open issues about that, e.g. #2388. I want to look into that in v6 too.

**Comment by B4nan** [comment]
FYI with #4769 your new test is also passing.
