### ISSUE TITLE
Schema not inherited in query with relations

### ISSUE THREAD

**Issue by LMoota** [mikro-orm/mikro-orm#4472]
**Describe the bug**
When performing a query with relations and using a JOINED type strategy, the schema is not inherited by the related entity.

Remember that both entities must use the wildcard operator in schemas.
**SELECT_IN strategy works.**

**To Reproduce**
1. Create an entity with wildcard schema
2. Create another entity with wildcard schema
3. Perform a query operation using the JOINED strategy in a schema other than the default one.

**Versions**

| Dependency | Version |
| - | - |
| mikro-orm | 5.7.12 |

**Comment by B4nan** [comment]
Please provide complete reproduction as code, this is not enough.

**Comment by LMoota** [comment]
Execute this test:
https://pastebin.com/YkFtVj3N
