### ISSUE TITLE
removeAll from collection not removing relationships when called from non-owner side

### ISSUE THREAD

**Issue by njeirath** [mikro-orm/mikro-orm#4473]
**Describe the bug**
When I call removeAll on a collection on the non-owner side of the relationship it doesn't seem to remove the relationships unless I first initialize the collections on the owning side.

**To Reproduce**
I have a User entity which can follow a Team through a many-to-many relationship. The relevant parts of the entities are:

```ts
export class User {
    id: string
    teamsFollowed: Collection<Team>

    constructor(id: string, email: string) {
        this.teamsFollowed = new Collection<Team>(this)
    }
}

export const UserSchema = new EntitySchema<User, Observable>({
    class: User,
    tableName: 'person',
    properties: {
        id: {type: 'string', primary: true, name: 'cognito_id'},
        teamsFollowed: {reference: 'm:n', entity: () => Team, mappedBy: 'followedBy'},
    },
})
```

```ts
export class Team extends Observable {
    id: string
    followedBy: Collection<User>
 
    constructor(name: string, league: League) {
        this.id = uuidv4()
        this.followedBy = new Collection<User>(this)
    }
}

export const TeamSchema = new EntitySchema<Team>({
    class: Team,
    tableName: 'team',
    properties: {
        id: {type: 'string', primary: true},
        followedBy: {
            reference: 'm:n',
            entity: () => User,
            pivotTable: 'followed_team',
            joinColumn: 'team_id',
            inverseJoinColumn: 'person_cognito_id',
        },
    },
})
```

Now if I want to remove all the followed teams for a user I'm trying to run the following in a transaction:
```ts
const user = await em.findOneOrFail(User, {id: event.userId})
await user.teamsFollowed.init()
user.teamsFollowed.removeAll() //doesn't remove relationships
```

But this does not actually remove any of the relationships. 

If, however, I first initialize the the collection from the owning side then the removeAll call works as expected:

```ts
const user = await em.findOneOrFail(User, {id: event.userId})
await user.teamsFollowed.init()
await Promise.all(user.teamsFollowed.getItems().map((t) => t.followedBy.init()))
user.teamsFollowed.removeAll() //relationships get removed
```

**Expected behavior**
I would expect that the following code would remove all the followed teams for the user.

```ts
const user = await em.findOneOrFail(User, {id: event.userId})
await user.teamsFollowed.init()
user.teamsFollowed.removeAll()
```

**Additional context**
In case it's helpful, when I run the version of code above that works I see the following SQL being sent to the DB `delete from 'followed_team' where ('person_cognito_id') in ( values ('user123')) and 'team_id' = '9e8d241e-932b-46d8-9c6e-0ab31fb2ff1b'`. I'm wondering if it was simplified to `delete from 'followed_team' where ('person_cognito_id') in ( values ('user123'))` if that would eliminate the need to initialize the owning side collections (although I'm completely guessing here)?

**Versions**

| Dependency | Version |
| - | - |
| node | 19.8.1 |
| typescript | 4.8.3 |
| mikro-orm | 5.7.12 |
| your-driver | postgres |

**Comment by B4nan** [comment]
This is a known issue, only owning sides are tracked for changes. Not sure if we have something opened for it already, I'd like to review this in v6, worst case validate and throw instead of ignoring it silently.

**Comment by B4nan** [comment]
Closing in favour of #4564
