### ISSUE TITLE
Embeddable is not populated when configured as nullable and all properties are null

### ISSUE THREAD

**Issue by zetti-caletti** [mikro-orm/mikro-orm#4480]
**Describe the bug**
I have a company profile entity and a row in the database table. zipCode, city, street and housenumber are null. Mikroorm doesnt fetch these values. Only when one value is not null for example street, then the embeddable is loaded. This doesn't make any sense.

**To Reproduce**
```
@Embeddable()
export class Address {
    @Property({ type: 'int', nullable: true, default: null })
    zipCode: number | null;

    @Property({ nullable: true, default: null })
    city: string | null;

    @Property({ nullable: true, default: null })
    street: string | null;

    @Property({ type: 'int', nullable: true, default: null })
    housenumber: number | null;
}

@Entity()
export class CompanyDetails {
    @Embedded(() => Address, { nullable: true })
    address: Address | null;
}

@Entity({ abstract: true })
export abstract class CompanyProfile {
    @ManyToOne(() => CompanyDetails, { nullable: true, default: null })
    company: CompanyDetails | null;
}

@Entity()
export class User extends CompanyProfile {
}

const user = await this.userRepo.findOne(1, { populate: ['company', 'company.address'] });
```

**Expected behavior**
Should always load the embeddable, independent of the values.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | ? |
| typescript | ? |
| mikro-orm | 5.6.15 |
| your-driver | ? |

**Comment by B4nan** [comment]
I am not entirely sure what you are reporting, a complete repro would be welcome, including the setup part (creating some data). If all the embedded props are null, this is correct behavior.

> I have a company profile entity and a row in the database table. zipCode, city, street and housenumber are null. Mikroorm doesnt fetch these values. Only when one value is not null for example street, then the embeddable is loaded. This doesn't make any sense.

When all the fields are null and the embedded property is also nullable, it won't be hydrated. There is no way to distinguish those two things. You can use `onLoad` event to do this if you want.

> mikro-orm | 5.6.15

You should always upgrade to latest first before reporting anything. v5.6 is pretty old.

> `const user = await this.userRepo.findOne(1, { populate: ['company', 'company.address'] });`

Not sure why you are trying to populate the `address` property, you don't populate embeddables, that's only for relations (and lazy properties).

**Comment by B4nan** [comment]
Closing, checked locally and it behaves correctly to me, lets reopen with a complete failing repro if you think there is a problem to fix, I dont see one.

**Comment by zetti-caletti** [comment]
@B4nan 
I have tested it now with latest version 5.7.12 and it behaves exactly the same.
The problem is the following:
When a user is created, a company profile is created and the values of address are all NULL by default. If I now load the profile in backend and send it to frontend the address embeddable is not populated and I received an error in frontend. 
An embedabble is not like a relation with features like eager or lazy loading etc and should behave like normal table rows in my opinion. So I don't understand why an embeddable should not be loaded if all their values are NULL. In normal tables also every column is loaded even if all their values are NULL. I hope you understand that the current behavior is strange. Right now I set for street a default value of empty string, so that the embeddable gets loaded every time even if the user has not saved his address.

Do you agree?

**Comment by zetti-caletti** [comment]
@B4nan Can you reopen this?

**Comment by B4nan** [comment]
Not without a failing repro, I tried what you provided and it worked correctly on my end.
