### ISSUE TITLE
Issue with Entity Generator using the bidirectional relations (bidirectionalRelations) option

### ISSUE THREAD

**Issue by ben-cl** [mikro-orm/mikro-orm#4492]
I did notice an issue with Entity Generator using the bidirectional relations (bidirectionalRelations) option. 

When two @ ManyToOne relationships refer to the same id on a table, only one @OneToMany relationship is added to this table. I need both. 

Example: 
![image](https://github.com/mikro-orm/mikro-orm/assets/32286421/499316fd-f286-418b-a131-d5b8648931a1)

![image](https://github.com/mikro-orm/mikro-orm/assets/32286421/2bf98cc6-76d2-4956-bee9-4b3b0823e74f)

I believe the issue is with the naming. Since two idMasterCodeInverse are created, I think one could overwrite the other. 

![image](https://github.com/mikro-orm/mikro-orm/assets/32286421/9f449f9f-8ab5-4b26-8430-732f89743b3e)
I would suggest using the meta.tableName example here instead. 

When I want to populate my MasterCode with “ObjecttModel”, it is not really intuitive for me to use: 
populate: [”idMasterCodeInverse”]. 

Using → populate: [”ObjecttModel”] example would be. 

Thanks for taking a look

**Versions**

| Dependency | Version |
| - | - |
| node | ts-node ^10.9.1 |
| typescript | ^4.9.5 |
| mikro-orm | ^5.7.12 |
| mikro-orm/mysql |  ^5.7.12 |

**Comment by B4nan** [comment]
Lets reopen with a reproduction.
