### ISSUE TITLE
Unnecessary generated MongoDB collection for indexed embeddable object

### ISSUE THREAD

**Issue by bebjakub** [mikro-orm/mikro-orm#4495]
**Describe the bug**
Hello, I'm using unique localized slugs with Mongodb. Everything is working fine, but there is autogenerated collection `localized-slug` from the embedded object.
```
@ObjectType()
@Embeddable()
export class LocalizedSlug {
  @Field({ nullable: true })
  @Property({ nullable: true, unique: true })
  en?: string;

  @Field({ nullable: true })
  @Property({ nullable: true, unique: true })
  cz?: string;

  @Field({ nullable: true })
  @Property({ nullable: true, unique: true })
  sk?: string;
}

@ObjectType()
@Entity()
export class Course extends Base {
  @Field(() => LocalizedSlug)
  @Embedded({ entity: () => LocalizedSlug, object: true })
  slug!: LocalizedSlug;
}
```
Is there a way how to disable generation? Thank you!

**Minimal reproducible example**
https://github.com/bebjakub/nest-mikro-orm-example

**Versions**
| Dependency | Version |
| - | - |
| node | 18.14.0 |
| typescript | ^4.7.4 |
| @mikro-orm/core | ^5.7.12 |
| @mikro-orm/mongodb | ^5.7.12 |
| @mikro-orm/nestjs | ^5.2.0 |

**Comment by B4nan** [comment]
What is generating it, just starting the app will reproduce it, or some CLI command? I guess it's gonna be the `ensureIndexes`, but from a quick look, I can see it correctly uses the `getOrderedMetadata` method which omits embeddables:

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/utils/AbstractSchemaGenerator.ts#L107

**Comment by bebjakub** [comment]
Starting the app generates the collection. 
I tested it a few times with the manual collection deletion before the app started.

**Comment by dark544** [comment]
I have the same problem using MongoDB with `ensureIndexes` set to `true`.

https://github.com/mikro-orm/mikro-orm/blob/master/packages/mongodb/src/MongoSchemaGenerator.ts#L92

`getOrderedMetadata` is not called in this method, but `this.metadata.getAll()`

Maybe that is the bug?

When I log the meta in the for loop, all embeddables are included.

**Comment by B4nan** [comment]
I must have been blind when checking this initially, yeah that's gotta be it.

Btw keep in mind indexes are not supported on embedded properties just yet (#2129).

**Comment by bebjakub** [comment]
Thank you @B4nan 
Looks like the unique index on embedded properties works correctly.
Now also without unnecessary generated collections.
```
@Property({ nullable: true, unique: true })
```
It creates a unique and sparse index in MongoDB as expected.
