### ISSUE TITLE
Support custom connection string parameters

### ISSUE THREAD

**Issue by PenguinToast** [mikro-orm/mikro-orm#4502]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to specify session variables for MySQL connections (example: [`sessionVariables=max_execution_time=300000`](https://docs.pingcap.com/tidb/dev/dev-guide-timeouts-in-tidb#jdbc-query-timeout)) -- however, any extra parameters passed to `clientUrl` currently get lost (when [passing as an options object](https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/AbstractSqlConnection.ts#L152) to knex).

**Describe the solution you'd like**
I'd like to either be able to fully specify the connection string, or specify a `Record<string, string>` of extra connection parameters to add to the connection URI.

**Describe alternatives you've considered**
If I could hook into the connection creation event, I could potentially set the session variable at the start of every new connection. However, I could not find an obvious way to do this.

**Additional context**
I'm happy to help out with implementation of this feature -- however, it seems like we'd have to pass connection options as a string to `knex` instead of as an object as we currently do. I'm not sure if this might break anything currently existing.

**Comment by rubiin** [comment]
I think this is where it needs to be implemented
https://github.com/mikro-orm/mikro-orm/blob/1d870f103290149361f0e2bb52e19f1b87f3ad3e/packages/mysql/src/MySqlConnection.ts#L29C32-L29C53

**Comment by PenguinToast** [comment]
Was able to work around this with the pool's `afterCreate` hook: https://knexjs.org/guide/#aftercreate

**Comment by B4nan** [comment]
I will close this, it's not trivial to do it (as apparently not all the libraries, namely the mysql2 one, do not support connection strings out of box - and the ORM is not doing that either, it parses the URL you provide and uses the values only) and it has one very simple workaround - you can override anything that the ORM generates via `driverOptions`:

```ts
const clientUrl = 'mysql://root@localhost:3308/mikro_orm_3965?sessionVariables=max_execution_time=300000';

await MikroORM.init({
    clientUrl,
    // this overrides what knex constructor will be getting (deeply merged with what the ORM would infer)
    driverOptions: {
      connection: {
        // this is driver specific, from what I found, in mysql2 its done this way, otherwise you get a warning about not supported properties, but maybe im wrong
        pool: { uri: clientUrl },
      },
    },
    entities: [...],
  });
```
