### ISSUE TITLE
add @Index({expression: '...'}) near @Entity() don't create migration

### ISSUE THREAD

**Issue by darky** [mikro-orm/mikro-orm#4508]
**Describe the bug**
When I try to add `@Index({expression: '...'})` on already migrated `Entity`, then new migration not created

**To Reproduce**
1. Make entity:

```ts
@Entity()
class Entity {
  ...
}
```

2. Create migration
3. Change entity with index expression:

```ts
@Entity()
@Index({expression: '...'})
class Entity {
  ...
}
```
4. Try to create migration and nothing happens

**Expected behavior**
Migration should be created with creating index to table

**Versions**

| Dependency | Version |
| - | - |
| node | 20.2.0 |
| typescript | 5.1.6 |
| mikro-orm | 5.7.12 |
| your-driver | postgres |

**Comment by B4nan** [comment]
What you if provide the index name explicitly (which you should be doing anyway for index expressions)?

**Comment by darky** [comment]
It's helps! Thanks!
