### ISSUE TITLE
Is there a way to whitelist/blacklist schemas for entity generation?

### ISSUE THREAD

**Issue by tahmidsadik112** [mikro-orm/mikro-orm#452]
**Is your feature request related to a problem? Please describe.**
Currently I couldn't find a way to whitelist/blacklist schemas before generating entities. This is useful when you want to leave out couple of tables for which you do not want to generate entities e.g. migration tables and other stuff. 

**Describe the solution you'd like**
Configuration option to whitelist/blacklist schema.

**Describe alternatives you've considered**
Couldn't find any alternative.

**Comment by B4nan** [comment]
Are we talking about schemas or tables? (as you mentioned migration table, which I would expect in the same schema as the rest of tables)

Only current schema is used for retrieving the list of tables for entity generation:

https://github.com/mikro-orm/mikro-orm/blob/master/lib/schema/PostgreSqlSchemaHelper.ts#L64
https://github.com/mikro-orm/mikro-orm/blob/master/lib/schema/MySqlSchemaHelper.ts#L58

And not sure if we really need a way to blacklist/whitelist on a table basis, generating entities is a one time thing, you can always just delete the extra files.

**Comment by tahmidsadik112** [comment]
Sorry for the confusion, I am talking about tables here.

Generating models may not be a one time thing for different workflows. If you consider the workflow where you just write migrations and then regenerate the models every time. Also while developing, a given table structure might change several times and thus requiring regeneration of models. 

About deleting the extra files, I have to figure out which files are extra and delete those. This feels like chore. 

By the way the project is very interesting and would like to help with implementing this feature. Thank You.

**Comment by B4nan** [comment]
Well, I don't think that will play well for you. There are serious limitations in EntityGenerator (no support for m:n and 1:m to start with), it is really meant just for the initial bootstrapping. What you described is totally upside down, you should change your entities and generate migrations based on that.

**Comment by tahmidsadik112** [comment]
Let me know if you want to improve support around entity generation, I will be very glad to able to help out here, if needed.

**Comment by B4nan** [comment]
I don't think there is much to do. Only thing that is missing from my point of view is support for m:n. 

The whole point of MikroORM is to allow to put domain logic to your entities. The approach you want would disallow that, as you could not put any methods to your entities, if you would keep regenerating them. Also there is no way to generate bi-directional relations automatically, so you would lose a lot of possibilities to query your entities.

**Comment by tahmidsadik112** [comment]
https://github.com/volatiletech/sqlboiler regenerates models. I think `prisma` does  something like this as well. It has it's pros and cons. It makes sense if you don't want to support this feature. 

Just for curiosity, what would I be missing if the generated model is complete ( all the properties and relations are there ) and not modifying it?
