### ISSUE TITLE
Updating collection bug and SQL statement bug

### ISSUE THREAD

**Issue by sonicgamer0721** [mikro-orm/mikro-orm#4533]
**Describe the bug**
The old issue: [https://github.com/mikro-orm/mikro-orm/issues/4439](url)
I made a repo with SQLite ( I use MariaDB in production environment ). I'm sorry it takes so long.
I tried the latest dev version and these 2 bugs still exist.

**BUG 1**: No changes written to database after updating collection.
```
@Entity()
export class User {
  @PrimaryKey()
  id!: number;
  ...
  @ManyToMany(() => Role, (role) => role.users)
  roles = new Collection<Role>(this);
}
```
When I run the code:
```
wrap(users[0]).assign({ roles: [].map((id) => em.getReference(Role, id)) });
await em.flush();
console.log(users[0].roles);
```
I can see users[0].roles is updated from the console, but the database does not change.

**BUG 2**: The updating SQL generated is so weird.
```
@Entity()
export class RoleResourcePermission {
  @ManyToOne(() => Role, {
    primary: true,
    onDelete: 'cascade',
  })
  role!: Role;

  @Property({ primary: true })
  resource!: string;

  @Property({ primary: true })
  isOriginal!: boolean;

  @Property()
  canCreate!: number;
...
}
```
When I run the code:
```
wrap(permission).assign({ canCreate: 0 });
await em.flush();
```
The SQL from the console shows so weirdly:
`update `core_role_resources` set `can_create` = 0 where ((0 = 'c' and 1 = 'o' and 2 = 'r')...)`

**To Reproduce**
1. [https://github.com/sonicgamer0721/mikro_bug_20230715](url)
2. npm run start
3. see what happens in the console.

**Versions**

| Dependency | Version |
| - | - |
| node | 18.16.0 |
| typescript | 5.1.6 |
| mikro-orm | 5.7.12 |
| @mikro-orm/mariadb | 5.7.12 |

**Comment by B4nan** [comment]
> BUG 1: No changes written to database after updating collection.

This is because you are trying to modify the inverse side, but only owning sides are checked for m:n relations. To be honest, it sounds quite weird to have `Role.users` as owning side.

**Comment by B4nan** [comment]
The second problem is resolved via 733cb80

**Comment by sonicgamer0721** [comment]
> The second problem is resolved via [733cb80](https://github.com/mikro-orm/mikro-orm/commit/733cb80918fa83a2d028b59ee807e0a3bb9b72b7)

Thanks so much, the second bug in 5.7.13 is gone!

**Comment by sonicgamer0721** [comment]
> > BUG 1: No changes written to database after updating collection.
> 
> This is because you are trying to modify the inverse side, but only owning sides are checked for m:n relations. To be honest, it sounds quite weird to have `Role.users` as owning side.

Appreciate your help. As you suggested, I change `User.roles` as owning side, upgrade to 5.7.13, everything works fine in repo.
But NOT in my real project: NestJS+MariaDB :(

Something weird:
1. In my real project, if I add a role to user, the result is correct, but the steps are werid: Delete all from users_roles table, then add data to users_roles table. In repo, Mikro just add the new data to users_roles table!
2. In my real project, if I use empty array to clear all roles from a user, no SQL generated, but in repo I can see the SQL working correctly.

Please give me some days. Let me try to make a new repo to demonstrate this bug.

**Comment by sonicgamer0721** [comment]
> > > BUG 1: No changes written to database after updating collection.
> > 
> > 
> > This is because you are trying to modify the inverse side, but only owning sides are checked for m:n relations. To be honest, it sounds quite weird to have `Role.users` as owning side.
> 
> Appreciate your help. As you suggested, I change `User.roles` as owning side, upgrade to 5.7.13, everything works fine in repo. But NOT in my real project: NestJS+MariaDB :(
> 
> Something weird:
> 
> 1. In my real project, if I add a role to user, the result is correct, but the steps are werid: Delete all from users_roles table, then add data to users_roles table. In repo, Mikro just add the new data to users_roles table!
> 2. In my real project, if I use empty array to clear all roles from a user, no SQL generated, but in repo I can see the SQL working correctly.
> 
> Please give me some days. Let me try to make a new repo to demonstrate this bug.

Hi B4nan, I recently rebuilt my database from MariaDB to PostgreSQL and now this bug is gone! Thanks for your help!

**Comment by B4nan** [comment]
Ok then, I will close this then, I just opened this issue #4564 to track the problem with inverse sides of m:n.
