### ISSUE TITLE
left join with subquery

### ISSUE THREAD

**Issue by bannaarr01** [mikro-orm/mikro-orm#4549]
I have not been able to efficiently do this kind of left join:
```bash
SELECT u.id as userId, u.group_id as userGroupId, u.coop as cooperative, utl.firstTransc as userFirstTransc
FROM user as u
LEFT JOIN cooperative coop ON coop.id = u.coop
LEFT JOIN (SELECT user_id, MIN(created_at) as firstTransc FROM user_transc_log WHERE region = 'SE_EAST' GROUP BY user_id) utl ON utl.user_id = u.id
WHERE u.coop IS NOT NULL GROUP BY u.id;
```

This specific one:

```bash
LEFT JOIN (SELECT user_id, MIN(created_at) as firstTransc FROM user_transc_log WHERE region = 'SE_EAST' GROUP BY user_id) utl ON utl.user_id = u.id
```
It always give unknown alias error, that the alias is not recognized once i use
```bash
 qb.leftJoin()  //I have tried all method, even using raw, still give same error
````

I would like a kind of solution that will do the leftJoin on the query builder and make use of any provided alias.

If there is no way to perform the leftJoin on the qb, then it should recognised the alias provided in the subQuery leftjoin

**Comment by B4nan** [comment]
Closing as duplicate #4429
