### ISSUE TITLE
Bug: Getting Export Related Error in Fresh Installation WIth Nestjs

### ISSUE THREAD

**Issue by totalard** [mikro-orm/mikro-orm#455]
**Describe the bug**
In Fresh Installation, It Gives some export  / Typescript Related Errors, Kindly Fix, It is Not Working

**Stack trace**
```
node_modules/mikro-orm/dist/query/QueryBuilderHelper.d.ts:1:8 - error TS1259: Module '"D:/space.dev/ttl-space/node_modules/knex/types/index"' can only be default-imported using the 'esModuleInterop' flag

1 import Knex, { QueryBuilder as KnexQueryBuilder, Raw } from 'knex';
         ~~~~

  node_modules/knex/types/index.d.ts:2001:1
    2001 export = Knex;
         ~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.


11:18:14 AM - Found 2 errors. Watching for file changes.
```

**To Reproduce**
Just Install Nest and Mikro, I am Using Mariadb Connector

**Expected behavior**
It Should not throw error

**Additional context**
Fresh Clean Installation

**Versions**
`{
  "name": "ttl-space",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "license": "MIT",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint '{src,apps,libs,test}/**/*.ts' --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^6.10.14",
    "@nestjs/core": "^6.10.14",
    "@nestjs/platform-express": "^6.10.14",
    "mariadb": "^2.3.1",
    "mikro-orm": "^3.6.2",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.0",
    "rxjs": "^6.5.4"
  },
  "devDependencies": {
    "@nestjs/cli": "^6.13.2",
    "@nestjs/schematics": "^6.8.1",
    "@nestjs/testing": "^6.10.14",
    "@types/express": "^4.17.2",
    "@types/jest": "25.1.1",
    "@types/node": "^13.1.6",
    "@types/supertest": "^2.0.8",
    "@typescript-eslint/eslint-plugin": "^2.12.0",
    "@typescript-eslint/parser": "^2.12.0",
    "eslint": "^6.7.2",
    "eslint-config-prettier": "^6.7.0",
    "eslint-plugin-import": "^2.19.1",
    "jest": "^24.9.0",
    "prettier": "^1.18.2",
    "supertest": "^4.0.2",
    "ts-jest": "25.1.0",
    "ts-loader": "^6.2.1",
    "ts-node": "^8.6.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^3.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".spec.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
`

**Comment by B4nan** [comment]
As the error states, you need to add `esModuleInterop` to your tsconfig.json. This is documented: https://mikro-orm.io/docs/installation/
