### ISSUE TITLE
Error while storing array of string enums into jsonb column

### ISSUE THREAD

**Issue by bill-o-more** [mikro-orm/mikro-orm#4555]
**Describe the bug**
I have an entity defined as 
```typescript
enum GreatEnum {
  EnumValue = 'enumValue',
  AnotherEnumValue = 'anotherEnumValue'
}
export class MyEntity {
    @PrimaryKey({ columnType: 'uuid', defaultRaw: `uuid_generate_v4()` })
    id = uuidv4();

    @Property({ type: 'json', default: '[]' })
    greatProp: GreatEnum[] = [];
}
```

Two things happen. 
First - migration generator detects it as `text[]` instead of `jsonb`.
Second - when I manually correct the migration and `jsonb` column is created in DB, inserts are broken - this is the query I get:
```sql
insert into "my_entity" ("id", "great_prop")
values ('some-long-guid', '{enumValue,anotherEnumValue}') 
returning.....
``` 
Which surely throws `invalid input syntax for type json`.
**Stack trace**
```
insert into \"my_entity\" (\"id\", \"great_prop\") values ('11fdce9e-8e89-4e4f-a244-431a9ada814a',  '{enumValue,anotherEnumValue}' - invalid input syntax for type json\n    at Parser.parseErrorMessage (/path/to/my/project/node_modules/pg-protocol/src/parser.ts:369:69)\n    at Parser.handlePacket (/path/to/my/project/node_modules/pg-protocol/src/parser.ts:188:21)\n    at Parser.parse (/path/to/my/project/node_modules/pg-protocol/src/parser.ts:103:30)\n    at Socket.<anonymous> (/path/to/my/project/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:513:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Socket.Readable.push (node:internal/streams/readable:234:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":184,"name":"DriverException","severity":"ERROR","code":"22P02","detail":"Token \"enumValue\" is invalid.","]
```

**Expected behavior**
I'd expect it to insert an array of strings with correct json syntax

**Additional context**
The data arrives to `create` correctly, no type errors exist

**Versions**

| Dependency | Version |
| - | - |
| node | 18.12.1 |
| typescript | 5.0.4 |
| mikro-orm | 5.7.12 |
| your-driver | Postgres |

**Comment by B4nan** [comment]
Try latest version, I was fixing one issue with JSON arrays in there.

**Comment by bill-o-more** [comment]
@B4nan same result on 5.7.13

**Comment by B4nan** [comment]
This is not reproducible on my end, here is a passing test case:

```ts
import { Entity, PrimaryKey, Property } from '@mikro-orm/core';
import { MikroORM } from '@mikro-orm/postgresql';

enum GreatEnum {
  EnumValue = 'enumValue',
  AnotherEnumValue = 'anotherEnumValue'
}

@Entity()
class MyEntity {

  @PrimaryKey()
  id!: number;

  @Property({ type: 'json', default: '[]' })
  greatProp: GreatEnum[] = [];

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    dbName: 'gh4555',
    entities: [MyEntity],
    debug: true,
  });

  await orm.schema.refreshDatabase();
});

afterAll(async () => {
  await orm.close(true);
});

it('4555', async () => {
  const root = new MyEntity();
  root.greatProp = [GreatEnum.AnotherEnumValue];

  await orm.em.persistAndFlush(root);
});
```

**Comment by B4nan** [comment]
Oh wait a sec, the fix is not yet released to stable, please try latest dev version, that should help.

**Comment by B4nan** [comment]
Dude, it was you reporting it? :D 

#4548

**Comment by B4nan** [comment]
But from the code I can see how this would be still happening, hmm weird I can't reproduce it.

Will fix that in a minute.

**Comment by B4nan** [comment]
Ok, 5327bccd52596fe1368f2766e38300b0d4cda03c should help, new dev version will be out in 15-20 minutes, let me know if that works.

**Comment by bill-o-more** [comment]
will check tomorrow and report back :)

**Comment by bill-o-more** [comment]
Fails with the same result :/

**Comment by B4nan** [comment]
Then you will need to provide a failing repro.

**Comment by bill-o-more** [comment]
are you sure that https://github.com/mikro-orm/mikro-orm/commit/5327bccd52596fe1368f2766e38300b0d4cda03c entered the 5.7.14.dev.8? As I see the old code in my source files, even after removing node_modules and yarn.lock. Should I clone it manually somehow?

**Comment by bill-o-more** [comment]
Also, that's what I saw in debugger in MetadataDiscovery.

First of all, it does 2 runs on each model. 
In the relevan one, it has `type = "json"`, but this is where it goes:
```typescript
if (!prop.customType && prop.array && prop.items) {
    prop.customType = new types_1.EnumArrayType(`${meta.className}.${prop.name}`, prop.items);
}
```
But like I said - I have the old code for some reason, and your commit will fix that. 

But there's a second run as well, and it differs. On the second run our prop gets there as a customType prop, with `type = EnumArrayType` and `columnTypes = ["text[]"]`. So it goes to `prop.customType` clause. Now `text[]` column type is consistent with what it tries to send to the DB.. Not sure why there are 2 runs, is it ok or I have some kind of eff up in my setup, and why they're different for the same models..

Which column type is created by `refreshDatabase()` in DB when you run your repro?

**Comment by bill-o-more** [comment]
Ok, just missed a dash in the version number.
Updated to `dev8`, but now I get weird TS errors on DB init:
```
TS2344: Type 'PostgreSqlDriver' does not satisfy the constraint 'IDatabaseDriver<Connection>'.   Property '[EntityManagerType]' is missing in type 'PostgreSqlDriver' but required in type 'IDatabaseDriver<Connection>'.
```
on this 
```typescript
export const orm = await MikroORM.init<PostgreSqlDriver <-- here >({
    ...config,
    debug: ['query', 'query-params'],
});
```

Am I missing something again?

**Comment by B4nan** [comment]
I will release a stable so you can use that, my guess is you did the dev update wrongly (e.g. did you update all the ORM packages to the same version?)

**Comment by bill-o-more** [comment]
Sure. I'll try the fixed code, and if the problem persists - will build a repro for you. 

Regarding the upgrade - these are all mikroorm rows from my package.json:
```
"@mikro-orm/cli": "5.7.14-dev.8",
"@mikro-orm/core": "5.7.14-dev.8",
"@mikro-orm/entity-generator": "5.7.14-dev.8",
"@mikro-orm/migrations": "5.7.14-dev.8",
"@mikro-orm/postgresql": "5.7.14-dev.8",
"@mikro-orm/reflection": "5.7.14-dev.8",
```

**Comment by B4nan** [comment]
> "@mikro-orm/reflection": "5.7.14-dev.8",

This is the very first time you mentioned using ts-morph, it's gonna be probably about that...

**Comment by bill-o-more** [comment]
I thought it was kinda default.. Do you mean that the TS errors are about that? I've tried a few ways to eliminate them, but still with no luck... or do you mean the topic issue?

**Comment by B4nan** [comment]
I have no idea what those errors are about since I don't see your code. No magic orb in here, I really need to see a complete repro to be able to tell something more than a guess :]

I am referring to the original issue and the fact that you say things are mapped to the EnumArrayType - as that is almost certainly coming from the ts-morph and maybe a malfunctioning metadata cache. Have you tried v5.7.14?

**Comment by bill-o-more** [comment]
in 5.7.14 all type errors are gone, and both problems (with migration generation and the query) with them. Very thank you :)
