### ISSUE TITLE
Documentation: I cant see any information related to Schema Syncronization in Mikrorm

### ISSUE THREAD

**Issue by totalard** [mikro-orm/mikro-orm#456]
Documentation: I cant see any information related to Schema Syncronization in Mikrorm

No thing to tell more.. Please inform me whether it is Available? It is Very Important Feature,
i hope schema sync automatically by init() or programically is okay, CMD based is not good for me.. In typeorm, and Sequelize,, they have the feature.

Also,
 -> How to close Active connection to a database, like the orm.close();

**Comment by B4nan** [comment]
No, there is no auto sync currently, but if you want to have such behaviour, you could call `updateSchema()` manually as part of your app bootstrap (so right after you initialize the ORM). 

You can control `SchemaGenerator` programatically for sure: 

https://mikro-orm.io/docs/schema-generator#using-schemagenerator-programmatically

> How to close Active connection to a database, like the orm.close();

There is `orm.close()` method.
