### ISSUE TITLE
Add `--drop-db` flag to `migration:fresh` and `schema:fresh`

### ISSUE THREAD

**Issue by KazimirPodolski** [mikro-orm/mikro-orm#4569]
**Describe the bug**
`migration:fresh` doesn't drop routines, and as a consequence fails on re-run on existing migrated DB with error like `function "..." already exists with same argument types`.

**To Reproduce**
1. Make a migration with `CREATE FUNCTION <anything>`
2. Run `npx mikro-orm migration:fresh`
3. Run `npx mikro-orm migration:fresh` again

**Expected behavior**
DB is wiped out and migrated.

**Additional context**

I suspect `migration:fresh` does not actually `Drop the database` like docs say, and instead drops all schema _known to Mikroorm_, because in my case routines are only present in migration SQL, and not in any annotations on entities.

I can replace all `CREATE FUNCTION` with `CREATE OR REPLACE FUNCTION`, but it's not ideal.

Also I wonder if views will also break `:fresh`.

**Versions**

| Dependency | Version |
| - | - |
| node | 18 |
| typescript | 5 |
| mikro-orm | 5.7.13 |
| your-driver | postgres |

**Comment by KazimirPodolski** [comment]
Same for `CREATE ROLE`, which is annoying because there are no `IF NOT EXISTS` for roles and no not ugly way to do that.

**Comment by B4nan** [comment]
Not entirely sure if it's a good idea to drop the database by default, but we can surely have a flag for it like we do with the `schema:drop` command. You can use that for now as a workaround:

```
npx mikro-orm schema:drop --drop-db --run
```

**Comment by KazimirPodolski** [comment]
> ```
> npx mikro-orm schema:drop --drop-db --run
> ```

:+1:

> The docs says it drops database schema (so the tables), not the whole database. Moreover, it drops all the existing tables, not just those "known to MikroORM".

Nope, it says exactly "Drop the database", why I was expecting that: https://mikro-orm.io/docs/migrations#using-via-cli

**Comment by B4nan** [comment]
Let's keep this open, the flag should be there and its a trivial task to do.

The docs also needs to be fixed, I was looking at the schema generator instead, where this seems to be correct:

https://mikro-orm.io/docs/schema-generator

But even there it needs adjustments. This `fresh` command came in as a community PR, and I haven't checked properly how the docs were handled.
