### ISSUE TITLE
Query collections over a repository

### ISSUE THREAD

**Issue by pq987** [mikro-orm/mikro-orm#457]
**Is your feature request related to a problem? Please describe.**
As an example, let's say I want to get all `Books` from a repo of `Author`s that contains a specific property, which is defined like so:
```ts
@Entity()
export default class Author implements AnyEntity {
  @PrimaryKey()
  id: string;

  @OneToMany(() => Book, book => book.author)
  books = new Collection<Book>(this);
}
```
```ts
@Entity()
export default class Book implements AnyEntity {
  @PrimaryKey()
  id: string;

  @Property()
  someOptionalProperty?: string;

  @ManyToOne()
  author: Author;
}
```
Currently I would have to do something like this to get books
```ts
const authors = await db.orm.em.getRepository(Author).findAll({ populate: ['books'] });
authors.forEach(author => {
  author.books.forEach(book => {
    if (book.someOptionalProperty) {
      // do something with the book
    }
  });
});
```

**Describe the solution you'd like**
It would be more concise if there was a way to either find all the `Book`s from the the repo such that it could return  `Collection<Book>[] / Book[]` or even better if there was a way to set a query so that it returns only `Book`s that have `someOptionalProperty`. Therefore, I can just iterate over that instead of doing a nested `forEach()`.

**Describe alternatives you've considered**
Not any others apart from the one I've stated above.

**Additional context**
N/A

**Comment by B4nan** [comment]
This is already supported:

```typescript
const authors = await db.orm.em.getRepository(Author).find({ books: { someOptionalProperty: 'value' } }, { populate: ['books'] });
```

This will fire 2 queries, one that will load authors, joining the books and filtering by the `someOptionalProperty` property, and second to load books, also propagating the `someOptionalProperty` condition. 

https://mikro-orm.io/docs/entity-manager/#searching-by-referenced-entity-fields

**Comment by pq987** [comment]
@B4nan Thanks for the fast response! That's great, but the issue is I can't determine the `'value'` beforehand I would just like to ensure that the `someOptionalProperty` exists and isn't null (since its marked as nullable on the entity via `?`) so I'm unsure how to approach this?

**Comment by B4nan** [comment]
Something like this should work:

```typescript
const authors = await db.orm.em.getRepository(Author).find({ books: { someOptionalProperty: { $ne: null } } }, { populate: ['books'] });
```

https://mikro-orm.io/docs/query-conditions/

**Comment by pq987** [comment]
I will look into that, apologies for the inconvenience 😅

**Comment by pq987** [comment]
Sadly, the query attempts to look for a column named `$ne` as this error gets throw `ERROR:  column e0.$ne does not exist`
