### ISSUE TITLE
issue with unconventional foreign key. parent entity's primary key set to null when no child.

### ISSUE THREAD

**Issue by rhyek** [mikro-orm/mikro-orm#4572]
**Describe the bug**
We have some legacy mysql tables we're trying to model with mikro. They have a one-to-one relationship, where the foreign key owning table uses its primary key as the fk.

see the example in the reproduction here:
https://github.com/rhyek/mikro-orm-issue-with-unconventional-foreign-key/blob/395222ca87ead5d1731bb3e42ef8798b2adae250/seed.sql#L1-L9

an example of the relationship is:
- person has id `1`. there *can* be a person detail with id `1` that would correspond to person `1`.
- it is possible for a person to exist without it having a corresponding details record

the problem lies when there is no person detail record. querying for the person via the entity manager will return the person with `id` set to `null` (instead of `1` in the above example). this is part of a larger issue we are seeing in our project where after modifying the loaded entity and doing a flush, since `id` is null, the `update` will run without a `where` clause. this is of course apart from not being our intention, very dangerous.

if you run the included unit tests, the [second test case](https://github.com/rhyek/mikro-orm-issue-with-unconventional-foreign-key/blob/67e0086ab5505c40773e61533e02b06660b68bd7/tests/issue.spec.ts#L50) fails because of `id` being `null` as explained. when enabling debugging, the query we are seeing (formatted) is:
```sql
select 
  `p0`.*, 
  `p1`.`id` as `id` 
from 
  `person` as `p0` 
  left join `person_detail` as `p1` on `p0`.`id` = `p1`.`id` 
where 
  `p0`.`name` = 'Pam Klocko IV' 
limit 
  1
```
the issue seems to be with this part in the select: `p1.id as id`. the person detail table's id col is replacing the id in the person table. the alias should be `p1__id`, not `id`.

**To Reproduce**
follow the instructions in the reproduction: https://github.com/rhyek/mikro-orm-issue-with-unconventional-foreign-key/blob/main/README.md 

**Expected behavior**
in the second unit test, person.id should not be null.

**Versions**

| Dependency | Version |
| - | - |
| node | v18.17.0 |
| typescript | 5.1.6 |
| mikro-orm | 5.7.12 |
| your-driver | mysql |

**Comment by rhyek** [comment]
this may also be an issue with how the entities are modeled:
https://github.com/rhyek/mikro-orm-issue-with-unconventional-foreign-key/blob/main/tests/entities/person.ts
https://github.com/rhyek/mikro-orm-issue-with-unconventional-foreign-key/blob/main/tests/entities/person-detail.ts

**Comment by B4nan** [comment]
> this may also be an issue with how the entities are modeled:

There needs to be a 1:1 property marked as `primary: true` on the child entity side, not a separate primary key property.

https://mikro-orm.io/docs/composite-keys#use-case-2-simple-derived-identity

This use case is tested (e.g. https://github.com/mikro-orm/mikro-orm/blob/master/tests/entities-sql/Address2.ts#L7 but there will be more entities like that), so I believe it should work fine if you model it properly.

**Comment by rhyek** [comment]
your suggestion worked. this is the change: https://github.com/rhyek/mikro-orm-issue-with-unconventional-foreign-key/commit/083852420932a4224e97b17a90f65183a7822cf6
