### ISSUE TITLE
`Cannot read properties of undefined (reading '__data')` when deleting an entity that uses the mappedBy option of OneToMany as 'owner'

### ISSUE THREAD

**Issue by moowoonsunghoon** [mikro-orm/mikro-orm#4578]
**Describe the bug**
After updating to MikroORM 5.7.14, An error occurs when deleting an entity that uses the mappedBy option of OneToMany as 'owner'

**Stack trace**
<img width="1045" alt="스크린샷 2023-08-02 08 49 08" src="https://github.com/mikro-orm/mikro-orm/assets/39836297/f3a2f823-2339-481f-b5ba-11cdd752a9b2">

```typescript
import { Entity, ManyToOne, PrimaryKey, Property } from '@mikro-orm/core';

import { User } from './user.entity';

@Entity()
export class Team {
  @PrimaryKey({ columnType: 'uuid', defaultRaw: `gen_random_uuid()` })
  id!: string;

  @Property({ columnType: 'uuid', nullable: true })
  userId?: string;

  @ManyToOne(() => User, {
    fieldName: 'user_id',
    onUpdateIntegrity: 'set null',
    onDelete: 'cascade',
    nullable: true,
  })
  owner?: User;
}

```

```typescript
import {
  Cascade,
  Collection,
  Entity,
  OneToMany,
  PrimaryKey,
} from '@mikro-orm/core';
import { Team } from './team.entity';

@Entity()
export class User {
  @PrimaryKey({ columnType: 'uuid', defaultRaw: `gen_random_uuid()` })
  id!: string;

  @OneToMany(() => Team, (team) => team.owner, {
    cascade: [Cascade.ALL],
  })
  teams = new Collection<Team>(this);
}
```

**To Reproduce**
1. create a OneToMany and ManyToOne relationShip with mappedBy use 'owner' string or entity.owner 
2. Attempt to removeAndFlush entity with One relationship
3. Throws an error

**Expected behavior**
Data should be deleted normally.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.18.1 |
| typescript | 5.1.3 |
| mikro-orm | 5.7.14 |
| your-driver | "@mikro-orm/postgresql": "^5.7.14" |

**Comment by B4nan** [comment]
Can you please provide a complete repro? So in addition to the entity definition, add also few lines that create some data and some that trigger this error. Entity definition does not reproduce much on its own.

**Comment by moowoonsunghoon** [comment]
@B4nan 
Thanks for the quick response!
The same error occurs after removing the userId property.
 I've uploaded a reproduction [repository](https://github.com/moowoonsunghoon/mikro-orm-repro)
let me know if you have any trouble using it to reproduce the problem. Thanks again!

**Comment by B4nan** [comment]
Ok, this is quite a funny problem - it all boils down to your owning property being called `owner` which is the same as `Collection.owner`, an internal property. Because of this match, things got broken.

**Comment by moowoonsunghoon** [comment]
@B4nan 
thanks a lot for the quick fix!👍
May I know when the new version will be released?

**Comment by B4nan** [comment]
Use the dev version, I want to ship new feature release next, and still have few things I want to implement first. I hope stable will go out in the end of this week or during next week.
