### ISSUE TITLE
Add an option to em.populate to ignore already populated fields

### ISSUE THREAD

**Issue by SteadEXE** [mikro-orm/mikro-orm#4579]
**Is your feature request related to a problem? Please describe.**
My feature request is related to a logic flow we encourted, we have a lot on lifecycle hooks, and depending on some entity state, we call em.populate on our entity to lazy load some relation.
We ended up in a situation where two event called em.populate on same relation so changes got overwritten.

When you got a big relation tree, it quickly becomes really hard to manually check every relation to only init/load them when they are not.
Especially when the code is split and used in events.

**Describe the solution you'd like**
I would like to have an option to em.populate to make it ignore already loaded entity.

If books have an author, and two event call `em.populate(books, ['author'], { ignorePopulated: true }) ` author should be loaded from database only once.

Maybe it can be named "softPopulate" or a completely different method.

**Describe alternatives you've considered**
I have tried to manually check every relation with isInitialized() init() but it becames a nightmare, especially with unwrapped/wrapped reference to manage.

**Additional context**
I think it can be implemented without breaking any existing project, since it's a new options toggles off by default

Thank you

**Comment by B4nan** [comment]
`em.populate` should already ignore populated relations. Can you provide a complete repro if it doesn't behave this way for you?

**Comment by SteadEXE** [comment]
Hm, I need to investigate further so, because changes made in beforeUpdate does not get persisted to database.

**Comment by B4nan** [comment]
> Hm, I need to investigate further so, because changes made in beforeUpdate does not get persisted to database.

You might need to recalculate the changeset if you want to modify something in hooks. See this, it's the same as with other hooks

https://mikro-orm.io/docs/events#using-onflush-event

Scalar properties on the entity that triggered the hook might/should work I think.

**Comment by SteadEXE** [comment]
This is what I finally did, of course scalar on the entity itself works but not everything else.
You answered my question was I was writting it.

Thank you a lot for your reactivity and your patience!

Have a nice day
