### ISSUE TITLE
Rejection when flushing a removal from a collection

### ISSUE THREAD

**Issue by izexi** [mikro-orm/mikro-orm#458]
**Describe the bug**
When I attempt to remove an item from a collection and then go ahead and flush the change, it ends up throwing an error.

**Stack trace**
```
update "bar_entity" set "foo_id" = $1 where "id" = $2 - null value in column "foo_id" violates not-null constraint
    at Connection.parseE (/usr/src/havoc/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/usr/src/havoc/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/usr/src/havoc/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:311:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  name: 'error',
  length: 182,
  severity: 'ERROR',
  code: '23502',
  detail: 'Failing row contains (2, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'bar_entity',
  column: 'foo_id',
  dataType: undefined,
  constraint: undefined,
  file: 'execMain.c',
  line: '1960',
  routine: 'ExecConstraints'
}
```

**To Reproduce**

```ts
let entitiy = await this.orm.em.findOne(FooEntity, '1');
if (!entitiy) {
  entitiy = new FooEntity('1');
  await this.orm.em.persistAndFlush(entitiy);
}
const bar = new BarEntity('2');
entitiy.bars.add(bar);
await this.orm.em
  .flush()
  .catch(err => console.error('error when flushing addition', err));
entitiy.bars.remove(bar);
await this.orm.em
  .flush()
  .catch(err => console.error('error when flushing removal', err));
```
<details>
<summary>Definitions of FooEntity and BarEntity</summary>
```ts
import {
  Entity,
  PrimaryKey,
  AnyEntity,
  OneToMany,
  Collection
} from 'mikro-orm';
import BarEntity from './BarEntity';

@Entity()
export default class FooEntity implements AnyEntity {
  @PrimaryKey()
  id: string;

  @OneToMany(
    () => BarEntity,
    bar => bar.foo
  )
  bars = new Collection<BarEntity>(this);

  constructor(id: string) {
    this.id = id;
  }
}

```
```ts
import { Entity, AnyEntity, PrimaryKey, ManyToOne } from 'mikro-orm';
import FooEntity from './FooEntity';

@Entity()
export default class BarEntity implements AnyEntity {
  @PrimaryKey()
  id: string;

  @ManyToOne()
  foo!: FooEntity;

  constructor(id: string) {
    this.id = id;
  }
}

```
</details>

**Expected behavior**
Expected the flush to not reject and remove the according entity from the collection on the database.

**Versions**

| Dependency | Version |
| - | - |
| node | v12.14.0 |
| typescript | 3.8.3 |
| mikro-orm | 3.6.0 |
| your-driver | pg (7.18.2) |

**Comment by B4nan** [comment]
As the error says, you have defined `foo` as not nullable, but you are setting it to null. By removing the item from collection, the change is propagated to the owning side, so effectively setting the `BarEntity.foo` to `null`. 

This is working as intended, you probably want to have `foo` defined as nullable, or use `orphanRemoval` (which will remove such entity if it was removed from a collection).

**Comment by izexi** [comment]
I thought that removing the last item in a collection would result in "empty" collection rather than `null`, seems like having the `orphanRemoval` option does the job thanks.

**Comment by B4nan** [comment]
This is how 1:m collections work, the foreign key is on the owning side (m:1), so if you remove an item, it means that the foreign key needs to be unset (so it has to be nullable) or the entity needs to be removed (that is what `orphanRemoval` is for).
