### ISSUE TITLE
Is there way to say Entity Generator to skip processing some tables and/or columns?

### ISSUE THREAD

**Issue by kozubsky** [mikro-orm/mikro-orm#4584]
Hello guys and thanks to a amazing work! I am wonder if there is a way to say entities generator to ignore/skip some tables (and/or some table columns) while generating entity schema? I have in my DB some tables that just ties some records from table A to some records from table B — for example, users to roles.

Currently, when I run

```js
generator.generate({
    save: true,
    baseDir: process.cwd() + '/src/entities-schemas',
});
```

I got an error ` UsersXRoles entity is missing @PrimaryKey()`.

I'd prefer to work with this table not as Entity, but with plain SQL. But I want to use DB-first approach, so it will be nice to have option in generate method like `skipTables: string[]` and `skipColumns: string[]`, for example

```js
generator.generate({
    save: true,
    baseDir: process.cwd() + '/src/entities-schemas',
    skipTables: ['users_x_roles'],
});
```

I didn't found an option in documentation, please tell me if such option exists already!

Best regards and many thanks for your project and work!

**Comment by B4nan** [comment]
> that just ties some records from table A to some records from table B — for example, users to roles.

Those are called pivot tables and will be mapped to M:N relations if you define them properly. You should have a primary key on those as well, a composite one. If you don't have one, the entity generator won't understand this is a pivot table.

**Comment by kozubsky** [comment]
> > that just ties some records from table A to some records from table B — for example, users to roles.
> 
> Those are called pivot tables and will be mapped to M:N relations if you define them properly. You should have a primary key on those as well, a composite one. If you don't have one, the entity generator won't understand this is a pivot table.

Hm... Ok, it might be useful in some cases, but not in described above: I'd prefer to avoid using collections at all, especially for pivot tables. I'm not going to introduce primary keys in that tables — there is no any reason to do this (and get unneeded extra index).

So, for now I managed to workaround using the following scenario:

1. I run `./node_modules/.bin/tsx ./generate-entities.ts` using `entitySchema: true` flag (avoiding unneeded decorators in generated code)

2. After code is generated, in some files there are missing imports, so I run `ts-morph` `fixMissingImports` on each file (and it works perfectly).

3. Because I really want to skip generation of some entities, I just delete some generated files matching blacklisted ones.

When DB schema changes (using some migrations tool), I repeat this procedure, keeping entities in sync to actual DB structure.

I wonder if I do missing some Enitiy Generator configuration options that will just skip some tables to be reflected to generated entities files.

And... Is not `entitySchema`-style deprecated, I hope? Is it still maintained (because it has issues with missing imports already)?

**Comment by B4nan** [comment]
Yeah, I don't mind adding something like `skipTables`, it just feels weird not to have a primary key in general, but the use case is valid regardless of that.
