### ISSUE TITLE
docs: Provide example for using SQLite extensions like sqlean

### ISSUE THREAD

**Issue by stabai** [mikro-orm/mikro-orm#4588]
SQLite extensions like [sqlean](https://github.com/nalgeon/sqlean) can help bring it much closer to feature parity with other database servers like Postgres (e.g. regexp, statistics). Unfortunately, they're difficult to install in a MikroORM connection with the current API, and there's no example explaining how to do it.

After a lot of research and experimenting, I finally found that the `pool.afterCreate` property of the SQLite initialization options can be used for this purpose. For example, after downloading and extracting the sqlean plugins, you can load them like so:

```typescript
const orm = await MikroORM.init<BetterSqliteDriver>({
  // ...
  pool: {
    afterCreate: (conn: any, done: any) => {
      conn.loadExtension(
        '/Users/stabai/Downloads/sqlean-macos-arm64/sqlean'
      );
      done(null, conn);
    },
  },
});
```

It would be even better if there were a simpler API to do this, but this at least seems worth documenting for others who need these additional features in SQLite.

**Comment by B4nan** [comment]
If you know how to do it, what about sending a PR? :] Could be a section in here maybe.

https://mikro-orm.io/docs/usage-with-sql

> After a lot of research and experimenting, I finally found that the pool.afterCreate property of the SQLite initialization options can be used for this purpose.

This again comes down on how to do things with knex, as MikroORM does not manage any connections explicitly. It took me exactly one google search to find a hint to check `afterCreate`... :]

**Comment by stabai** [comment]
Happy to add it, just wanted to make sure it was welcomed and figure out where to put it.

> This again comes down on how to do things with knex, as MikroORM does not manage any connections explicitly. It took me exactly one google search to find a hint to check `afterCreate`... :]

I'm not sure I understand the intention of this statement. Regardless of the reason that it took me more than one google search, it's slightly upsetting to me that you felt the need to point out that it was easy for you to find.

As for the reason it was hard for me to find, it's because this is a leaky abstraction. I'm guessing I'm not the only user of Mikro ORM that doesn't think about Knex and add it to their search queries when debugging. I barely remember it exists, and when I do, I think of it more as an implementation detail of Mikro ORM rather than something I would expect to interface with directly. I think the state of this abstraction makes sense, but I'm just pointing out that it greatly increases the value of user education (e.g. the docs not letting me forget that Knex exists) and exhaustive documentation (e.g. the docs providing more links to recipes and specific bits of Knex documentation that would be useful to me).

**Comment by B4nan** [comment]
The point of my statement is, that MikroORM is (currently) a layer on top of knex (for SQL drivers), I believe this should be quite clear from the docs (maybe not so much as it should be), implementation (e.g. we have getters for `knex` directly on EM class), as well as package names (we have the `knex` package that all SQL drivers depend on, basically any stack trace will contain that). 

People are struggling way too often because of trying to find ways to do things with MikroORM instead of checking how to do it with knex... Didn't mean upset you anyhow.
