### ISSUE TITLE
Add more methods to Collections

### ISSUE THREAD

**Issue by bakura10** [mikro-orm/mikro-orm#4592]
Hi :),

I am coming from Doctrine world, where collections are having a lot of convenient methods (https://www.doctrine-project.org/projects/doctrine-collections/en/stable/index.html).

The workaround in Mikro-ORM seems to converting first to an array to have access to all JS array related methods. Arrays are more flexible in JS than they are in JS, but maybe exposing those methods to Mikro-ORM collections would reduce the need for this conversion. Here are the one I often use in Doctrine:

* Reduce
* Find
* Find first
* Exists
* Filter

Except from this I really love how Mikro-ORM is thought. It _feels_ like Doctrine, but with so many pain points being lifted. That's really a breath of fresh air :)

Thanks!

**Comment by B4nan** [comment]
FYI the collection items are stored in a `Set` internally, so you need to convert that to an array to be able to use the native array methods. I wanted to add some of those for v6, not sure if we need `reduce`, and not sure what should be the difference in `find` and `findFirst`? Also we already have `contains` method.

**Comment by rubiin** [comment]
`exists`, `slice`, `removeElement` and `isEmpty` seems useful as well.

**Comment by B4nan** [comment]
Another good candidate would be `map()`.
