### ISSUE TITLE
Naming strategy does not apply to embeddable objects

### ISSUE THREAD

**Issue by bakura10** [mikro-orm/mikro-orm#4593]
Hi :),

I am not sure if this is a bug or the intended result, but the naming strategy does not apply to embeddable set up as object. Considering this embeddable:

```
@Embeddable()
export class CollectionRules {
    @Property({type: types.boolean})
    allowMultipleCollects: boolean;
}
```

Used inside an entity:

```
@Embedded(() => CollectionRules, {object: true})
    collectionRules: CollectionRules;
```

The saved JSON will be saved like this:

```
[{"allowMultipleCollects": true}]
```

Instead of:

```
[{"allow_multiple_collects": true}]
```

It seems a bit inconsistent, I think the naming strategy should propagate to JSON objects as well :).

**Comment by B4nan** [comment]
Yes, this is a known issue, e.g. #4371

Closing as duplicate
