### ISSUE TITLE
Non-persisted properties emit an error if type is omitted

### ISSUE THREAD

**Issue by bakura10** [mikro-orm/mikro-orm#4594]
Hi,

I am using v6 branch (so this might be a regression, I did not try on the v5 branch).

I am using a non-persisted property, that looks like this:

```
@Property({type: Date, nullable: true})
    expiresAt?: Date;

    @Property({persist: false})
    get expired(): boolean {
        return this.expiresAt && this.expiresAt < Date();
    }
```

Unfortunately, the following error occurs:

```
throw new Error(`Please provide either 'type' or 'entity' attribute in ${meta.className}.${prop.name}. If you are using decorators, ensure you have 'emitDecoratorMetadata' enabled in your tsconfig.json.`);
                  ^


Error: Please provide either 'type' or 'entity' attribute in Card.expired. If you are using decorators, ensure you have 'emitDecoratorMetadata' enabled in your tsconfig.json.
```

Of course, emitDecoratorMetadata is properly configured (and all other properties are properly discovered).

To fix the issue, I have to set an explicit type:

```
@Property({persist: false, type: types.boolean})
```

This is however not documented anywhere in Mikro-ORM documentation, so maybe this should be mentioned somewhere that type is actually required even for non-persisted properties :)

Thanks!

**Comment by B4nan** [comment]
Weird, do you have some bundler on the way or use some non-standard compilation like swc? This is definitely not reproducible in the tests, we have entities like this, e.g. https://github.com/mikro-orm/mikro-orm/blob/master/tests/entities-sql/Author2.ts#L148-L151

**Comment by bakura10** [comment]
I'm using TSX (https://github.com/esbuild-kit/tsx). I will try to setup a minimal reproduction test case tomorrow.

**Comment by B4nan** [comment]
I though esbuild does not support reflect-metadata at all.

**Comment by B4nan** [comment]
Yeah... 

> [emitDecoratorMetadata](https://www.typescriptlang.org/tsconfig#emitDecoratorMetadata) is not supported

https://github.com/esbuild-kit/tsx#does-it-have-any-limitations

**Comment by bakura10** [comment]
Damn... after spending several days trying to manage to build everything, TSX was the only tool that worked out of the box, too bad :D. This ecosystem is so fragmented compared to PHP, this is really the annoying part.

I will close this as this is unrelated to Mikro-ORM.

**Comment by bakura10** [comment]
But what I don't understand is that if I set the type it actually works. Syringe decorator (@inject, @injectable...) also works properly, despite using TSX. Shouldn't everything actually fail?

**Comment by B4nan** [comment]
Decorators on their own will work, but there won't be any metadata. Maybe we could skip non-persistent properties from the validation, but I think we need to know the type for hydration.
