### ISSUE TITLE
Allow to use custom Date types

### ISSUE THREAD

**Issue by bakura10** [mikro-orm/mikro-orm#4603]
Hi :),

I am doing various date manipulation and, being used to the DateTime/DateInterval awesomeness in PHP, I decided to use temporal polyfill (https://tc39.es/proposal-temporal) which offers a very nice date interface (especially, working on range, interval... is super painful with the legacy Date).

To allow this, I have created my own custom type, for instance here is the PlainDateTime one:

```
import {EntityProperty, Platform, Type, ValidationError} from "@mikro-orm/core";
import {Temporal} from "@js-temporal/polyfill";
import PlainDateTime = Temporal.PlainDateTime;

export class PlainDateTimeType extends Type<PlainDateTime | undefined, string | undefined> {
    convertToDatabaseValue(value: PlainDateTime | null | undefined): string | null | undefined {
        if (value instanceof PlainDateTime) {
            return value.toString();
        }

        if (!value) {
            return value;
        }

        throw ValidationError.invalidType(PlainDateTime, value, 'JS');
    }

    convertToJSValue(value: string | undefined | null): PlainDateTime | null {
        if (!value) {
            return null;
        }
        
        return PlainDateTime.from(value); // Temporal does not accept the Z
    }

    getColumnType(prop: EntityProperty, platform: Platform): string {
        return platform.getDateTimeTypeDeclarationSQL({length: prop.length ?? 0});
    }
}
```

In my entity:

```
@Property({type: PlainDateTimeType})
readonly subscribedAt: PlainDateTime = Temporal.Now.plainDateTimeISO();
```

The problem is that apparently MikroORM might be doing a pre-conversion of the Date fields to the native Date type. In the `convertToJSValue`, I indeed get a Date instance (value instanceof Date evaluate to true), instead of a string.

In my understanding, all the conversion process should be handled in the type itself, so it was quite surprising to get a Date instance instead of the row column.

Is this expected? Is there anyway to get a string even if the column is mapped to date field in the db?

Thanks :)

**Comment by B4nan** [comment]
> The problem is that apparently MikroORM might be doing

This is actually done by the underlying db libraries, e.g. `mysql2` or `pg`, only `sqlite` is not converting things on its own. But I am in the middle of a refactoring for v6 that will switch the behavior - I thought I will leave the dates as they were and do it only for JSON columns, but I guess it makes sense to do it for dates too. I wasn't entirely sure if its a good idea but you kinda confirmed it should be done like that, it will make more sense and it will align the behavior for all the SQL drivers.

Linked the related issue about JSON columns as I will probably fix both in one step: #4476

**Comment by bakura10** [comment]
That's awesome news! As the Temporal API is in stage 3 now, it is likely a matter of time before they will be able to replace the old Date. Let me know once you have a working implementation, in the interim I will do an ugly conversion ;)

**Comment by B4nan** [comment]
Actually, this change is already partially implemented in v6 via #4391, but we are mapping to the `Date` object on the result mapping layer, so before hydration and before custom types are involved. 

Btw I ended up doing the same for JSON properties, using the result mapping layer, as it feels better to have those parsed automatically - the result is that when you use `qb.execute()` (so getting the raw results), you can have the JSONs parsed. And to be honest, now I am not entirely sure if it's a good idea to not have the `Date`s parsed there as well, which would happen if we move the parsing to the hydration layer.

Maybe this could be optional instead.

**Comment by bakura10** [comment]
Got it ! From a dev experience point of view I just found it very surprising, as for me the whole goal of the custom type is to be in charge of the conversion and to receive a raw value :)

**Comment by B4nan** [comment]
So I made a lot of progress on this a month ago, and somehow managed to lose it completely, the branch is apparently nowhere to be found :D I really need to start pushing those WIP branches, they are not safe locally :D

**Comment by bakura10** [comment]
I'm sorry to hear that!! This also happened to me in the past, I always push on GitHub now :D.

**Comment by B4nan** [comment]
I think I found it, it was in a different branch :]

**Comment by B4nan** [comment]
The more I think about this, the more I feel like it's a bad idea to even try to make it work. If we move the date mapping to the type implementation, it means we need to process all the types when doing result mapping - that on its own is quite a breaking change, but the more important part is that it means we'd have to convert the current value back to the db value when diffing (so perf penalty just to know if something changed) or we'd have to let users define their own comparison method on the type class (again, breaking pretty heavily, and it could have weird side effects when extending existing types).

So my question is, do we really need this? You get the `Date` object in your mapped type, its value should be correct, so you can just convert that back to the string in your mapped type, right? As it feels like a cosmetic change in the end, and fixing it could result in a lot of internal BCs as well as endless headaches when trying to implement it properly (not to speak about perf costs).

**Comment by B4nan** [comment]
> which will become a standard to replace Date, so at some point the story will happen again :D

That can easily take a decade, given how slow everything is with new ES features :] And I truly doubt they would ever remove the `Date` objects, as it would break not just half, but the entirety, of the internet. If there is one thing we can be sure about, it's the back compatibility of JS in general.

> but having the proper object from the starts make it more convenient.

I don't get this argument. The only difference is the roundtrip from `string` to `Date` and back during mapping, or not?

> My main problem here was also the lack of consistency in this custom type API. From a developer point of view it was quite surprising to have an exception just for dates here.

It's the same story with JSON objects, and in the end, booleans in mysq/sqlite too (as those are represented with a number instead of bool in the raw data).

**Comment by bakura10** [comment]
```
I don't get this argument. The only difference is the roundtrip from string to Date and back during mapping, or not?
```

The idea is to have a simpler domain object. In my case, my domain contains a creation date, and I might want to expire it based on a duration. The Temporal API offers all of this (the polyfill works well) and offers a similar interface to PHP Date:

```
public expireReward(duration: Duration) {
  this.expiresAt = this.createdAt.add(duration);
}
```

Both expiresAt and createdAt are date, but being able to having types that automatically create a Temporal object just makes it much more convenient. If I use Date, this means I constantly need to do conversions back and forth:

```
public expireReward(duration: Duration) {
  const createdAtTemporal = this.createdAt.toTemporalInstant(); // convert Date to temporal API

  // Do the manipulation using temporal API
  const expiresAtTemporal = createdAtTemporal.add(duration);

   // Convert back to date
   this.expiresAt = new Date(expiresAtTemporal.epochMilliseconds);
}
```

Being able to work only with the Temporal API (and just having the conversion happening once) just provides a much cleaner code (especially since I have ton of date manipulation in this project).

Hope it clarifies :)

**Comment by B4nan** [comment]
This feels like a misunderstanding, as you keep telling me why you want to use the temporal API - but you can, just have a custom type that converts the `Date` object to it.

**Comment by bakura10** [comment]
You might be perfectly correct. Sorry, I have not been able to work on this since then, I think my issue came from the fact I received a Date (rather than a string) and that I was attempting to do a string => Temporal rather than a Date => Temporal in the convertToJSValue. But as I did not work on that since then I was stuck on this :D.

I think you're correct that it might be a misunderstanding. I'm closing this issue, I will everntually re-open in the future if I face other issues. Sorry about that!
