### ISSUE TITLE
Extending an Entity from Other Entity Using Same Table

### ISSUE THREAD

**Issue by totalard** [mikro-orm/mikro-orm#462]
This is not same to #459 

As it is Said in the doc that, Entities can be extended, and Business Logic Can be implemented in Entity itself, As my App is Multi DB, Multi User, Multi Modules are there, I need to have Extending Feature like a normal class in typescript can do. Entity Should be Extended. It make the app much smaller and less complex always.

As an Example, Assume, Entity A -> B -> C,  (A has Table name "a")

A have Some Property A1, A2 and some Unique Indexes AU, and a PK, and Method AM

B have some Property B1, B2, B3 and another BU and No PK , Method BM(Own)
As Extended, It Should ALSO have A1, A2 and AU and PK and AM.

C have C1 Only as OWN Property
once C Extended from B, C, Then C Should have A1, A2, AU, PK, AM, B1, B2, B3,BU,BM,C1

Please Note:
Because of A -> B -> C .... The B & C Use Same Database Table of A, The Table Contain All Properties of C  ie: A1, A2, AU, PK, B1, B2, B3,BU,C1

Hope You Understood. Waiting for a Favorable reply. @B4nan

**Comment by B4nan** [comment]
This is called single table inheritance, subscribe here: #33.

Planning to support this in v4.

Btw this is the reason why I did not even bother supporting multiple base entities, because 99% of people thinks that it will work like this, while it is totally different feature.

**Comment by totalard** [comment]
Any v4 Progress? shedule expected?
