### ISSUE TITLE
Indexes Are Not Propagated  While Extending Base Entity

### ISSUE THREAD

**Issue by totalard** [mikro-orm/mikro-orm#463]
**Describe the bug**

If I marked Certain property as Unique in Base Entity.. It should be Unique once the base entity extended... Such Indexes are Not inherited... It's a Bug..Please Fix
**Stack trace**
Nothing Here

**To Reproduce**
`import { Property, Unique, PrimaryKey } from "mikro-orm";
@Unique({ properties: ['xmlId'] })
export abstract class Base {
    @PrimaryKey()
    id: number;
    @Property({ nullable: true })
    xmlId: string;
    @Property()
    createdAt = new Date();
    @Property({ onUpdate: () => new Date() })
    updatedAt = new Date();
}`

**Expected behavior**
Must be Inherited

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 13|
| typescript | 3.7 |
| mikro-orm | 3.6.3 |
| your-driver | mysql |

**Comment by totalard** [comment]
Thanks for Fixing The Issue, But There is still something missing,

Once The DB is Sync After The new Update, Only New Table Creations Propagated Index From Parents, 

All Previous Tables still not Extended Indexes from Parents. 

Please check

**Comment by B4nan** [comment]
Hmm that is a bit different problem, entity level indexes are not considered when creating the diff.
