### ISSUE TITLE
[bug] Schema:Create doesn't create foreign keys in SQLite

### ISSUE THREAD

**Issue by ShGKme** [mikro-orm/mikro-orm#464]
**Describe the bug**

`npx mikro-orm schema:create -r` doesn't create any foreign keys in SQLite for relations, while it's created successufully in Postgresql. 

`npx mikro-orm schema:create -d` prints SQL without any foreign keys.

**To Reproduce**
I may create a repl, but it seems to have this behavior in any sqlite database.

**Expected behavior**
Creating foreign keys in SQLite like it does in Postgres.

**Versions**

| Dependency | Version |
| - | - |
| node | 12.16.1|
| typescript | 3.8.3 |
| mikro-orm | 3.6.1 |
|sqlite3 |4.1.1|

**Comment by B4nan** [comment]
This is not supported because of SQLite limitations in knex, you can subscribe here https://github.com/knex/knex/issues/3351 (unfortunately the issue was ignored).
