### ISSUE TITLE
Do nothing if `em.insertMany()` is passed an empty array

### ISSUE THREAD

**Issue by squivix** [mikro-orm/mikro-orm#4640]
**Is your feature request related to a problem? Please describe.**
When calling `em.insertMany()` with an empty array instead of doing nothing it tries to insert anyway and generates an invalid query, resulting in:

```sql
insert into "entity" ("id") values  returning "id" - syntax error at or near "returning"
```

**Describe the solution you'd like**
I want it to ignore an empty array of entities. I know it's supposed to be a native insert query that provides direct access to the db, but I think this simple convenience like this is not too much to ask.

**Describe alternatives you've considered**
I can always wrap my call in a check. For example:
```ts
const entityAs = await this.em.find(EntityA, filters);
if (entityAs.length > 0)
    await this.em.insertMany(PivotEntityAEntityB, entityAs.map(entityA => ({entityA, entityB: entityB})));
```

but it's wordy

**Additional context**
The invalid SQL query mentioned earlier is encountered in miko-orm 5.6.7. 

Meanwhile in 6.0.0-dev.87 I seem to get a TypeError instead:
```
TypeError: Cannot use 'in' operator to search for 'id' in undefined
     at /home/user/WebstormProjects/project/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:318:45
     at Array.filter (<anonymous>)
     at PostgreSqlDriver.nativeInsertMany (/home/user/WebstormProjects/project/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:318:18)
     at SqlEntityManager.insertMany (/home/user/WebstormProjects/project/node_modules/@mikro-orm/core/EntityManager.js:850:37)
```

**Comment by rubiin** [comment]
@B4nan https://github.com/mikro-orm/mikro-orm/blob/f99298de189299cd321faf9ca1639277fe9e2351/packages/core/src/EntityManager.ts#L998 I think we can also add a length check for data in here
