### ISSUE TITLE
Nested object validation

### ISSUE THREAD

**Issue by FranckBontemps** [mikro-orm/mikro-orm#466]
Hello,

**Describe the bug**
In my use of Mongodb, I often use nested objects to describe my document, but these nested objects are not entities requiring PrimaryKey.

```
export class NestedObject {
    @Property()
    public stringValue?: string;
}

@Entity()
export class Foo {
    constructor() {
        this.bar = new NestedObject();
    }

    @PrimaryKey()
    public _id: ObjectId;

    @Property()
    public bar: NestedObject
}
```

**To Reproduce**
```
test('should trigger the nested object schema validation', async () => {
    const foo: any = new Foo();

    foo.bar.stringValue = 3712;

    await expect(orm.em.persistAndFlush(foo)).rejects.toThrowError();
});
```

**Expected behavior**
I expect metadata from the nested object types to be supported during root entity validation, persist and flush.

**Versions**

| Dependency | Version |
| - | - |
| node | 12.16.1 |
| typescript | 3.7.3 |
| mikro-orm | 3.6.4 |
| your-driver | mongodb |

**Comment by B4nan** [comment]
Not sure if it can work like you described, but I understand what you are missing there. I guess we could add support for nested entities in general (probably via different decorator on the child, something like `@ChildEntity()`, not sure now). It can work in SQL drivers too (via JSON columns).

For now you could use custom type and handle the validation yourself.

**Comment by B4nan** [comment]
In v4.2 you can use embeddables in object mode. Be sure to enable validation, as flushing no longer validates things by default (from 4.1).

```ts
@Embeddable()
export class NestedObject {
    @Property()
    public stringValue?: string;
}

@Entity()
export class Foo {
    constructor() {
        this.bar = new NestedObject();
    }

    @PrimaryKey()
    public _id: ObjectId;

    @Embedded({ entity: () => NestedObject, object: true })
    public bar: NestedObject
}

const orm = await MikroORM.init({
  //...,
  entities: [Foo, NestedObject], // be sure to let the embeddable be discovered too
  validate: true,
});
```
