### ISSUE TITLE
Cannot find module '~/server/entities/index.ts' 

### ISSUE THREAD

**Issue by imcm7** [mikro-orm/mikro-orm#4690]
**Describe the bug**
error TS2307: Cannot find module '~/server/entities/index.ts' or its corresponding type declarations.

**To Reproduce**
https://github.com/imcm7/nuxt-mikroorm-ts

pnpm db:update

**Versions**

| Dependency | Version |
| - | - |
| node | 18, 19, 20|
| typescript | ? |
| mikro-orm |core@^5.7.15-dev.46 |
| your-driver | MariaDb |

**Comment by imcm7** [comment]
https://github.com/mikro-orm/mikro-orm/discussions/4686

**Comment by B4nan** [comment]
Please don't create new issues again and again, this is not something to fix in the ORM. I will be happy to help you in the discussions, but you need to be patient, not bombard me with new issues with literally no new information.

**Comment by imcm7** [comment]
Why not ot fix in ORM if it's cli can't work with that path?

**Comment by B4nan** [comment]
Because it is not something the ORM should touch anyhow, this is a configuration issue. I did verify yesterday that the ORM correctly registers the tsconfig-paths module (even with just using `npx mikro-orm`, without the explicit registering). This is about how your project is set up, not about the ORM.

**Comment by imcm7** [comment]
if you see code that i attached you will see that i also use npx mikro-orm? and it not work

**Comment by B4nan** [comment]
I did see your project, and inside that exact project, I verified that the paths mapping is registered. It does not work, either because of wrong paths mapping, or by the vite setup in general. It's not about changing anything in the ORM.

**Comment by imcm7** [comment]
But when I run `npx mikro-orm schema:update --run`
it has nothing with vite? and it not work

**Comment by imcm7** [comment]
Yes result with mikro-orm and thse same configts.json are the same if i not install nuxt `Error: Cannot find module '~/server/entities'
`

**Comment by imcm7** [comment]
I try that config, remove some things, and it also not work

```
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,

    "forceConsistentCasingInFileNames": true,
    "jsx": "preserve",
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Node",
    "skipLibCheck": true,
    "isolatedModules": true,
    "useDefineForClassFields": true,
    "strict": true,
    "allowJs": true,
    "noEmit": true,
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "paths": {
      "~": [
        ".."
      ],
      "~/*": [
        "../*"
      ]      
    }
  }
}
```

**Comment by imcm7** [comment]
So I think mikro-orm cli can't work with such paths, or need some tsconfig what I not know.

**Comment by B4nan** [comment]
I already gave you the exact line where this happens, if you wouldn't have created 3 issues for the same, you could have found it here... 

> I wiil try the same without nuxt and I think result will be the same.

Well, and that's the problem, you expect things to be generally broken, while they are not. The problem is most probably in the modern setup you are trying to use (ESM, vite, esbuild). There are many people using paths mapping happily with MikroORM.

Here is for example a project someone shared in the issues just today. They use paths mapping:

https://github.com/kent-0/api
https://github.com/kent-0/api/blob/main/tsconfig.json#L21

**Comment by imcm7** [comment]
> Here is for example a project someone shared in the issues just today. They use paths mapping:

> https://github.com/kent-0/api
> https://github.com/kent-0/api/blob/main/tsconfig.json#L21

That is good news, I will try that tsconfigs

**Comment by imcm7** [comment]
The problem was in tsconfig,json

In your examples it is
```
"paths": {
      "~/*": ["./*"]
    }
    ```
    
    In nuxt is
    ```
    "~": [
        ".."
      ],
      "~/*": [
        "../*"
      ]  
      ```

**Comment by imcm7** [comment]
And a nuxt-mikroorm module will be nice

**Comment by imcm7** [comment]
How to pas here `"db:update": "mikro-orm schema:update --run"` other tsconfig file (like mikro-orm.cli.tsconfig.jshon, some oprions may be exists) with working in cli paths?

**Comment by B4nan** [comment]
Either via `MIKRO_ORM_CLI_TS_CONFIG_PATH` env var or in the package.json:

```json
{
  "name": "our-app",
  "dependencies": { ... },
  "mikro-orm": {
    "useTsNode": true,
    "tsConfigPath": "...", // <-- here
    "configPaths": [
      "./src/mikro-orm.config.ts",
      "./dist/mikro-orm.config.js"
    ]
  }
}
```

https://mikro-orm.io/docs/installation#setting-up-the-commandline-tool

**Comment by imcm7** [comment]
nice

**Comment by imcm7** [comment]
But now if I add that 
```
"devDependencies": {
    "@mikro-orm/cli": "^5.7.14",
 },
 dependencies: {
   "cli@^5.7.15-dev.46": "link:mikro-orm/cli@^5.7.15-dev.46"  // I think that you mean in response to my old problem?
},
"mikro-orm": {
    "tsConfigPath": "./tsconfig.mikro-orm.cli.json",
```
I get `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined`
https://github.com/mikro-orm/mikro-orm/issues/4681


But if I change path in nuxt tsconfig to needed all is ok?

**Comment by B4nan** [comment]
Start by upgrading all the packages to v5.8, you should never mix different ORM package versions.

**Comment by B4nan** [comment]
I just realized another thing, in the context of an ESM project, `import * as entities from '~/server/entities'` is wrong on its own - it should be `import * as entities from '~/server/entities/index.js' - as for ESM you need to specify the file including an extension, and you don't even have such file in that folder. ESM doesn't support directory imports at all.

(this itself still didn't help either)

**Comment by imcm7** [comment]
> I just realized another thing, in the context of an ESM project, `import * as entities from '~/server/entities'` is wrong on its own - it should be `import * as entities from '~/server/entities/index.js'` - as for ESM you need to specify the file including an extension, and you don't even have such file in that folder. ESM doesn't support directory imports at all.
> 
> (this itself still didn't help either)

Prior to write to you i try to import `import * as entities from '~/server/entities/index.ts' `, because I use ts and not work. Now work without to specify index.ts

**Comment by imcm7** [comment]
And `data-source.ts` too?

**Comment by imcm7** [comment]
And that is used by nuxt and all in nuxt is in ts. Not understand
