### ISSUE TITLE
Composable Checks/Filters/etc

### ISSUE THREAD

**Issue by kpervin** [mikro-orm/mikro-orm#4697]
**Is your feature request related to a problem? Please describe.**
Due to how Checks, Filters, and various other top-of-class decorators are used, it begins to make the code look a bit messy. If you have various checks, you can easily have a class that looks like this:

```ts
@Entity()
@Unique<Ex>({
  properties: ["relation", "min"],
})
@Unique<Ex>({
  properties: ["relation", "max"],
})
@Unique<Ex>({
  properties: ["relation", "min", "max"],
})
@Check<Ex>({
  name: "check_min_lt_max",
  expression: (cols) =>
    `${cols.max} = -1 OR ${cols.min} < ${cols.max}`,
})
@Check<Ex>({
  name: "check_max_not_lte_negative",
  expression: (cols) => `${cols.max} >= -1`,
})
@Check<Ex>({
  name: "check_min_max",
  expression: (cols) => `NOT(${cols.min} = 0 AND ${cols.max} = -1)`,
})
export class Ex {
  @PrimaryKey({ autoincrement: true })
  id: number;

  @ManyToOne()
  relation: Ref<Relation>;

  @Property({
    default: 0,
  })
  min= 0;

  @Property({
    default: -1,
    comment: "-1 = no limit",
  })
  max= -1;
}
```

**Describe the solution you'd like**
NestJS has an ability to combine decorators into a single decorator ([docs ](https://docs.nestjs.com/custom-decorators#decorator-composition)/ [code](https://github.com/nestjs/nest/blob/master/packages/common/decorators/core/apply-decorators.ts)). Having the ability to combine these checks and filters together would be significant.

For example, to compose filters we could have a function such as the following:

```ts
// compose-filters.ts
import { Filter, FilterQuery } from "@mikro-orm/core";
import { Dictionary, EntityName } from "@mikro-orm/core/typings";
import { EntityManager } from "@mikro-orm/mysql";
import { applyDecorators } from "@nestjs/common";

export type FilterDefinition<Entity> = {
  cond:
    | FilterQuery<Entity>
    | ((
        args: Dictionary,
        type: "read" | "update" | "delete",
        em: EntityManager,
      ) => FilterQuery<Entity> | Promise<FilterQuery<Entity>>);
  default?: boolean;
  args?: boolean;
};

export type FilterDefinitions<Entity> = {
  [key: string]: FilterDefinition<Entity>;
};

export function composeFilters<Entity extends object>(
  entity: EntityName<Entity>,
  filters: FilterDefinitions<Entity>,
): () => ReturnType<typeof applyDecorators> {
  const filterDefs = Object.entries<FilterDefinition<Entity>>(filters).map(
    ([key, value]) => {
      return {
        name: key,
        cond: value.cond,
        default: value.default,
        args: value.args,
      };
    },
  );

  return () => applyDecorators(...filterDefs.map((filter) => Filter(filter)));
}
```
```ts
// guy.filters.ts
import { composeFilters } from "../compose-filters";
import { Guy } from "./test-class";

export const GuyFilterName = {
  NO_GUYS_NAMED_STEVE: "noGuysNamedSteve",
  NO_GUYS_WITH_NAME: "noGuysWithName",
} as const;

export const GuyFilters = composeFilters(Guy, {
  [GuyFilterName.NO_GUYS_NAMED_STEVE]: {
    cond: {
      name: { $ne: "Steve" },
    },
  },
  [GuyFilterName.NO_GUYS_WITH_NAME]: {
    cond: (args) => ({
      name: { $ne: args.name },
    }),
  },
});
```
```ts
// guy.entity.ts
import { Entity, PrimaryKey, Property } from "@mikro-orm/core";
import { GuyFilters } from "./test.filter";

@Entity()
@GuyFilters()
export class Guy {
  @PrimaryKey()
  id: number;

  @Property()
  name: string;
}
```
Similarly, we could have other composition functions for other top-of-class entity decorators.

**Comment by B4nan** [comment]
PR welcome, this is a great candidate for anyone who wants to contribute, as it does not require any knowledge of the codebase really.

**Comment by kpervin** [comment]
Is there any way you would prefer it set up in terms of syntax, however?

**Comment by kpervin** [comment]
In this case I had to alter the @Filter interface to acquire Entity type hints. Also curious how you'd like to see this for driver extensibility, as I've written this for my own codebase but contingent on the `@mikro-orm/mysql` EntityManager.

**Comment by B4nan** [comment]
I don't mind adding generics wherever needed. For the driver types, this would also have to be implemented via generics, as nothing in the core package can reference the driver classes.

**Comment by kpervin** [comment]
I'll see what I can do.

**Comment by B4nan** [comment]
I will close this as I am not personally interested in implementing this (and this issue didn't get any traction from the community), but would still accept a PR.
