### ISSUE TITLE
Some entities are not persisted when inserting in parallel

### ISSUE THREAD

**Issue by Yaty** [mikro-orm/mikro-orm#470]
Hello

I'm writing some tests for my application. For those tests I need to create multiple users and persist them in the database.

I'm using MikroORM with Nest.js.

If I create them this way it works, every user is persisted and every user entity I get in return have an id :
```ts
const users = [
  await utils.givenUser(),
  await utils.givenUser(),
  await utils.givenUser(),
  await utils.givenUser(),
];
```

But if I use `Promise.all` multiple weird things are happening.

First case, I try to create two users : 

```ts
const users = await Promise.all([
  utils.givenUser(),
  utils.givenUser(),
]);
```

`users[0].id` is undefined and `users[1].id` is defined

With three users : `users[0].id` and `users[2].id` are defined, `users[1].id` is undefined

With four users : `users[0].id` and `users[2].id` are defined, `users[1].id` and `users[3].id` are undefined

With five users : `users[0].id`, `users[2].id` and `users[3].id` are defined, `users[1].id` and `users[4].id`  are undefined

With six users and more an error is thrown : 

```
TypeError: Cannot read property 'setValue' of undefined

    at ChangeSetPersister.mapPrimaryKey (/home/hugo/projets/paffme/node_modules/mikro-orm/dist/unit-of-work/ChangeSetPersister.js:49:53)
    at ChangeSetPersister.persistEntity (/home/hugo/projets/paffme/node_modules/mikro-orm/dist/unit-of-work/ChangeSetPersister.js:39:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ChangeSetPersister.persistToDatabase (/home/hugo/projets/paffme/node_modules/mikro-orm/dist/unit-of-work/ChangeSetPersister.js:20:9)
    at UnitOfWork.commitChangeSet (/home/hugo/projets/paffme/node_modules/mikro-orm/dist/unit-of-work/UnitOfWork.js:208:9)
    at UnitOfWork.persistToDatabase (/home/hugo/projets/paffme/node_modules/mikro-orm/dist/unit-of-work/UnitOfWork.js:342:13)
```

Sometimes it works with 6 users but it seems the more I increase the number of entity to create the more chance I have to get the error.

I had some cases where the error was thrown for 4 or 5 users creation. The ordering between defined and undefined id seems to be the same every time.

I cleaned the table, tried to create 6 users, got the error and only 5 users were created : 1, 2, 3, 5, 6

**To Reproduce**, 

Try to insert multiple entities at once with `Promise.all`

**Expected behavior**

Obviously I would like to not get the error and to retrieve every users correctly inserted.

**Additional context**

```js
async givenUser(): Promise<User> {
   const registerDto = {
      email: `${uuid.v4()}@${uuid.v4()}.fr`,
      password: uuid.v4().substr(0, 10),
    };

    const newUser = new User();
    newUser.password = await this.hashPassword(password);
    newUser.email = email.trim();

    await this.userRepository.persistAndFlush(newUser);
    return newUser;
  }
```

```ts
@Entity()
export class User extends BaseEntity {
  @Property({ hidden: true })
  @IsEmail()
  email!: string;

  @Property({ hidden: true, length: 512 })
  password!: string;

  // a lot of relations and some other properties
}
```

```ts
export abstract class BaseEntity {
  @PrimaryKey()
  id!: number;

  @Property()
  createdAt = new Date();

  @Property({ onUpdate: () => new Date() })
  updatedAt = new Date();
}
```

```ts
{
  type: 'postgresql',
  host: 'localhost',
  port: 5432,
  user: configService.get('POSTGRESQL_USER'),
  password: configService.get('POSTGRESQL_PASSWORD'),
  dbName: configService.get('POSTGRESQL_DATABASE'),
  entities: [BaseEntity, User],
  entitiesDirsTs: ['src'],
}
```

**Versions**

| Dependency | Version |
| - | - |
| node | 12.13.1 |
| typescript | 3.8.3 |
| mikro-orm | 3.6.5 |
| pg | 7.18.2 |
| nestjs-mikro-orm | 1.0.3 |
| @nestjs/testing | 7.0.7 |
| @nestjs/common | 7.0.7 |
| @nestjs/core | 7.0.7 |

**Comment by B4nan** [comment]
You cannot flush in parallel, not with the same entity manager. If you need to do it it parallel, use forks (this is from ORM's tests):

```typescript
test('persisting entities in parallel inside forked EM with copied IM', async () => {
  const author = new Author2('name', 'email');
  await orm.em.persistAndFlush(author); // we need to flush here so the entity gets inside IM

  // fork EM without clearing the IM (once for each process), so author entity will be there
  await Promise.all([
    orm.em.fork(false).persistAndFlush(new Book2('b1', author)),
    orm.em.fork(false).persistAndFlush(new Book2('b2', author)),
    orm.em.fork(false).persistAndFlush(new Book2('b3', author)),
  ]);

  orm.em.clear();
  const a1 = (await orm.em.findOne(Author2, author.id, { populate: ['books'] }))!;
  expect(a1.books.count()).toBe(3);
});
```

What you should do instead is to `em.persist()` those entities first, and then flush once at the end. 

```typescript
em.persist(u1, u2, u3, u4);
await em.flush();
```

But if this is about test fixtures, I would use `em.nativeInsert()` instead as that won't use identity map (as you need to have the identity map clean before you do the actual test). This approach should be compatible with `Promise.all`

```typescript
await Promise.all([
  em.nativeInsert(User, u1),
  em.nativeInsert(User, u2),
  em.nativeInsert(User, u3),
  em.nativeInsert(User, u4),
]);
```

**Comment by Yaty** [comment]
Good to known, thank you

**Comment by jtomaszewski** [comment]
What if the entities that are to be persisted are in nested async stack, i.e. at the moment of introducing parallelization (calling `Promise.all`), I don't know what will be persisted in each of the "sub-threads"?

I guess I have to create a fork for each "sub-thread", and set the fork as _the_ EM in the context?

Redoing the example from the original post of this issue, the correct code would be:

```ts
const users = await Promise.all([
  RequestContext.create(em, () => utils.givenUser()),
  RequestContext.create(em, () => utils.givenUser()),
]);
```

am I correct?
