### ISSUE TITLE
Using Getters and Setters with a persisted property

### ISSUE THREAD

**Issue by ChilloManiac** [mikro-orm/mikro-orm#4700]
**Is your feature request related to a problem? Please describe.**
I've got a larger table with multiple different fields that i want to track when each field has last been touched. This is done by having 2 columns: `field` and `fieldUpdatedAt`. 

I'd love to tie in to native Getter/Setter functionality in order to ensure that it is impossible to update the field without setting a new date like so:

```typescript
@Entity({ tableName: "myEntity"}) 
export class MyEntity {
    @Property({ name: 'myField' })
    _myField: number;

     public get myField(): number { 
       return this._myField
     }

     public set myField(num: number) {
       this._myField = num;
       this._myFieldUpdatedAt = new Date()
    }

    @Property({name: 'myFieldUpdatedAt'})
    _myFieldUpdatedAt: Date = new Date();

    public get myFieldUpdatedAt(): Date {
      return this._myFieldUpdatedAt;
    }
}
```

This works allright until i want to query by the fields, as they don't show up in the FilterQuery type. I also tried to use the `getter` and `setter` fields of the `Property` decorator, but this ended up running the setter every time the Entity was fetched from the DB resulting in updates to `myFieldUpdatedAt`. 

**Describe the solution you'd like**
Using native getter/setter functionality

**Describe alternatives you've considered**
1. Using a separate function to set fields, and then verify (manually) that fields aren't set directly in application code
2. Looking into ways to make the DB track the changes to fields and update the columns

**Additional context**
Love the tool otherwise, great job :)

**Comment by B4nan** [comment]
You can add the decorator to the getter.

**Comment by octet-stream** [comment]
This should work:

```ts
@Entity()
export class MyEntity {
  // or use native private members prefixed by the "#"
  private _myField!: number

  @Property()
  get myField(): number {}

  set myField(value: number): void {
    this._myField = value
    this._myFieldUpdatedAt = new Date()
  }

  private _myFieldUpdatedAt!: Date = new Date()

  get myFieldUpdatedAt(): Date {
    return this._myFieldUpdatedAt
  }
}

```

But I don't think that in your case you necessarily need accessors. Just pass `onUpdate` option to `Property` decorator and it will automatically update the update (it does it on em.flush, probably) like this:

```ts
@Entity()
export class MyEntity {
  @Property()
  myField!: number

  @Property({onUpdate: () => new Date()})
  readonly myFieldUpdatedAt: Date = new Date()
}
```
