### ISSUE TITLE
Allow to pass `.ts` files as config with Bun when `ts-node` is disabled

### ISSUE THREAD

**Issue by octet-stream** [mikro-orm/mikro-orm#4701]
**Is your feature request related to a problem? Please describe.**

Hi, I'm experimenting with MikroORM and Bun, and I find out that MikroORM's configuration loader ignores `.ts` files when `ts-node` is not enabled. And while this constraint is suitable for node, it is not necessary for Bun since it support TS files [out of the box](https://bun.sh/docs#design-goals).

**Describe the solution you'd like**

I think it would be nice to add at least an option for configurator loader to pass `.ts` files when this option enabled. Something like `bypassTsFiles` flag in `mikro-orm` section of `package.json`. When enabled, [this](https://github.com/mikro-orm/mikro-orm/blob/3f30c16a1614ab059be71f3dbf51ccdd40dd9033/packages/core/src/utils/ConfigurationLoader.ts#L110) filter will be ignored same was as if `ts-node` was enabled.

**Describe alternatives you've considered**

Enabling `ts-node` works with Bun 1.0.1, but this running code from `ts-node` with Bun is not necessary.

**Additional context**

No additional context. But I think I can send a PR upon agreement on implementation details.

**Comment by B4nan** [comment]
Makes sense, PR welcome. Maybe the name should be a bit better, as its not really about bypassing the TS files? Ideally we should have a guide about bun in the docs.

**Comment by octet-stream** [comment]
> Maybe the name should be a bit better, as its not really about bypassing the TS files?

Yes, this flag should enable ts files without ts-node, so maybe something like `allowTs`? Or `alwaysAllowTs`?

Actually, I have another though: Maybe allow ts files by default, but then if we fail to import config with `.ts` extension, then just suggest `ts-node`?

Something like (just a pseudo code)

```
const path = getConfigPath()
try {
  await import(path)
} catch (e) {
  // Check for error type, and then:
  if (path.endsWith(".ts")) {
    throw new Error("Failed attempt to load ORM config from .ts file. Try enabling ts-node with useTsNode flag in package.json")
  }
}
```

Something like this.

> Ideally we should have a guide about bun in the docs.

I think we need to have mikro-orm tests to pass with bun first. I haven't tested this yet.

**Comment by octet-stream** [comment]
This also should work with entities, subscribers, migrations and other stuff that might be loaded by MikroORM itself.

**Comment by B4nan** [comment]
I would love to get rid of the `useTsNode` flag, but it cant be at the cost of some errors/warning for js only projects.

**Comment by octet-stream** [comment]
> I would love to get rid of the useTsNode flag, but it cant be at the cost of some errors/warning for js only projects.

It's ok, but I would rather report errors to tell user they're doing something wring, than silently ignoring `.ts` files altogether.

**Comment by B4nan** [comment]
Well, but it's completely fine to not use TS in your project, and that needs to be the baseline, TS should be opt in, not opt out.

**Comment by octet-stream** [comment]
Makes sense, then I think default `.js` configs should've come first in the list, so that MikroORM will try to read those first (after custom paths).

**Comment by octet-stream** [comment]
So, the algorithm would be: custom paths -> default `.js` -> default `.ts`, if none found - then show an error.
If somebody specify TS file as config, they probably know what they're doing, and if such file exists, but it can't be executed by runtime (can't be imported due to unsupported file format) - the error should be shown. But that's just my thoughts :)

**Comment by B4nan** [comment]
That would be heavily breaking, as it would mean a compiled js file has precedence over the ts source file.

**Comment by narcopata** [comment]
Sorry, is this really already fixed? I tried to run the CLI on my Bun MikroORM API, had setup the config `.ts` file, set the `alwaysAllowTs` flag on "mikro-orm" as true on package.json, and still I have the error: `- configuration not found (Unknown file extension ".ts" for /home/rws/projects/empresa_alberto_testes/test-back/src/database/mikro-orm.config.ts)`.

**Comment by octet-stream** [comment]
Could you provide minimal reproduction repo, please?

**Comment by narcopata** [comment]
@octet-stream 

I hope this has enough:
https://github.com/narcopata/min-reproduction-mikro-orm-bun-config-allow-ts

**Comment by octet-stream** [comment]
You need to run command with `--bun` flag in order to run Mikro ORM CLI via Bun instead of Node.js. Like this: `bun run --bun mikro-orm debug` or `bunx --bun mikro-orm debug`.

See documentation: https://bun.sh/docs/cli/bunx#shebangs

**Comment by narcopata** [comment]
> You need to run command with `--bun` flag in order to run Mikro ORM CLI via Bun instead of Node.js. Like this: `bun run --bun mikro-orm debug` or `bunx --bun mikro-orm debug`.
> 
> See documentation: https://bun.sh/docs/cli/bunx#shebangs

Thanks it worked!

I think it would be interesting to have this usage example available on 
MikroORM's documentation (along with npm, yarn, npx, etc.).
