### ISSUE TITLE
`mikro-orm schema:update -r` fails to take into consideration my `EntityCaseNamingStrategy`

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#472]
**Describe the bug**
I think that...

`mikro-orm schema:update -r` fails to take into consideration my `EntityCaseNamingStrategy`.

**Stack trace**
```
error: select relname as constraint_name, attname as column_name, idx.indisunique as unique, idx.indisprimary as primary
      from pg_index idx
      left join pg_class AS i on i.oid = idx.indexrelid
      left join pg_attribute a on a.attrelid = idx.indrelid and a.attnum = ANY(idx.indkey) and a.attnum > 0
      where indrelid = 'public.BaseHistory'::regclass - relation "public.basehistory" does not exist
```

**To Reproduce**

1. Create an entity with a ECNS... BaseHistory
1. Create the database using `schema:create`
1. Run `schema:update`

**Expected behavior**
No error.

**Versions**

| Dependency | Version |
| mikro-orm | 3.6.5 |
| postgres | |

**Comment by B4nan** [comment]
Hmmm so `regclass` makes the names lowercase, weird. Maybe we could change that to `where indrelid::regclass = 'public.BaseHistory'::regclass`...

**Comment by B4nan** [comment]
LOL so this should be the way: `where indrelid::regclass = '"public"."BaseHistory"'::regclass`

**Comment by lookfirst** [comment]
@B4nan Thank you man! =)

**Comment by lookfirst** [comment]
@B4nan Can we get a release? =)
