### ISSUE TITLE
Getters Incorrectly Required When Creating Entities in TypeScript

### ISSUE THREAD

**Issue by devcaeg** [mikro-orm/mikro-orm#4750]
**Describe the bug**
There's an issue with the types in MikroOrm. If you have an entity with one or more "getters", when invoking the "create" function from the entity's repository, it will require those "getters" as required parameters. That should not happen (or so I think).

**Example**
```typescript
@Entity({
  collection: 'users',
})
export class User extends Base {
  @Property({
    hidden: true,
  })
  password?: string;

  @Property({
    unique: true,
  })
  username?: string;

  @OneToMany({
    entity: () => UserPermission,
    mappedBy: 'user',
    cascade: [Cascade.ALL],
  })
  private _permissions = new Collection<UserPermission>(this);

  @OneToMany({
    entity: () => UserRole,
    mappedBy: 'user',
    cascade: [Cascade.ALL],
  })
  private _roles = new Collection<UserRole>(this);

  @Property({
    getter: true,
    persist: false,
  })
  get permissions(): Permission[] {
    return this._permissions
      .getItems()
      .map((permission) => permission.permission);
  }

  @Property({
    getter: true,
    persist: false,
  })
  get roles(): Role[] {
    return this._roles.getItems().map((role) => role.role);
  }
}
```
If you try to create a "User" entity, you'll find that "getters" such as "permissions" and "roles" are required as parameters. Therefore, TypeScript will throw an error until you set those properties.

**Expected behavior**
I believe "getters" shouldn't be required properties when creating an entity.

**Additional context**
I'm using the metadata provider "TsMorphMetadataProvider".

**Versions**
| Dependency | Version |
| - | - |
| node | 20.5.1 |
| typescript | 5.2.2 |
| mikro-orm | 5.8.3 |
| mikro-orm/mongodb | 5.8.3 |
| nestjs | 10.2.6 |

**Comment by B4nan** [comment]
This is a wontfix, there is no way to confidently detect what is a getter and what not (PR welcome if you think otherwise, I tried already and failed), you should mark those as optional via `OptionalProps` symbol.

https://mikro-orm.io/docs/property-validation#properties-with-default-value
