### ISSUE TITLE
Property $ does not exist on Ref property when using `em.populate(Entity, ...)`

### ISSUE THREAD

**Issue by kpervin** [mikro-orm/mikro-orm#4754]
**Describe the bug**
I am unsure if this is a bug, or if the docs simply need to be updated, but when calling `WrappedEntity.populate(...)` or `em.populate(Entity, ...)` without assigning to a new variable we lose any sort of type hints to the fact we have indeed populated the reference.

**To Reproduce**
```ts
// Foo entity
@Entity()
export class Foo extends BaseEntity<Foo, "id"> {
  @PrimaryKey()
  id: number;

  @ManyToOne(() => Bar, { onUpdateIntegrity: "cascade", onDelete: "cascade" })
  bar: Ref<Bar>;
}
```
```ts
// Bar
@Entity()
export class Bar extends BaseEntity<Bar, "id"> {
  @PrimaryKey()
  id: number;

  @Property()
  name: string;
}
```

```ts
@Injectable()
export class FooService {
  constructor(private readonly orm: MikroORM) {}
  
  async populateFooOnFind(fooId: number): Promise<Foo> {
    const foo = await this.orm.em.findOneOrFail(Foo, fooId, {
      populate: ["bar"],
    });
    console.log(foo.bar.$.name); // Fine
    return foo;
  }

  async populateFooAfterFind(fooId: number): Promise<Foo> {
    const foo = await this.orm.em.findOneOrFail(Foo, fooId);
    await this.orm.em.populate(foo, ["bar"]);
    console.log(foo.bar.$.name); // TS2339: Property  $  does not exist on type  { id: number; } & Reference<Baz> 
    return foo;
  }

  async populatePassedFoo(foo: Foo): Promise<Foo> {
    await this.orm.em.populate(foo, ["baz"]);
    console.log(foo.baz.$.name); // TS2339: Property  $  does not exist on type  { id: number; } & Reference<Baz> 
    return foo;
  }

  async populatePassedFooNewVar(foo: Foo): Promise<Foo> {
    const populatedFoo = await foo.populate(["baz"]);
    console.log(populatedFoo.baz.$.name); // Fine
    return foo;
  }

  async populatePassedFooAssignOldVar(foo: Foo): Promise<Foo> {
    foo = await foo.populate(["baz"]);
    console.log(foo.baz.$.name); // TS2339: Property  $  does not exist on type  { id: number; } & Reference<Baz> 
    return foo;
  }
}
```
**Expected behavior**
Given that the populate method mutates the original entity it would be expected that it also changes the typing of the variable. That being said, this may be a limitation of Typescript or simply intended behavior.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.16.0 |
| typescript | 5.2.2 |
| mikro-orm | 5.8.3 |
| your-driver | MySQL |

**Comment by B4nan** [comment]
This is a wontfix, it is not possible to alter a type of an existing property, only way to do this is via `asserts` keyword, which does not work with async methods (and it would require us to return `boolean` - it cannot do both, either it mutates, or it returns something).

I am planning to have a section about working with the `Loaded` type in the getting started guide, so will try to mention this there.

**Comment by kpervin** [comment]
I figured it was something like that. Is there any way to restrict usage of the `get()` or the `$` keywords unless you use a `find*` method? That would probably be more explicit, but also likely a large chore to attempt.

**Comment by kpervin** [comment]
Another question (and this is stretching my knowledge of Typescript): if we passed a `Loaded<Foo>` instead of just `Foo` to the methods, is there any way to expand the type that way in changing the `never` signature to the type hints? I'm thinking of things like how type assertions work on optional fields.
