### ISSUE TITLE
mikro-orm packages should depend on exact versions for other mikro-orm packages

### ISSUE THREAD

**Issue by stefansundin** [mikro-orm/mikro-orm#4764]
**Describe the bug**

Hello. I'm having trouble installing mikro-orm version `6.0.0-dev.108`. I noticed that not all packages have `6.0.0-dev.109` published, so I want to use `108` for the time being.

The dependencies in my `package.json`:

```
    "@mikro-orm/cli": "6.0.0-dev.108",
    "@mikro-orm/core": "6.0.0-dev.108",
    "@mikro-orm/migrations": "6.0.0-dev.108",
    "@mikro-orm/postgresql": "6.0.0-dev.108",
```

However, even though I am depending on the exact versions like above, the packages themselves are pulling in a newer version of each other, resulting in a mess in my `yarn.lock` file.

Of these four packages, only `@mikro-orm/core` have an `109` version published, but `@mikro-orm/knex` is also pulled in with version `109`.

**Stack trace**

When I try to run my app, I get this error:

```
Error: Bad @mikro-orm/cli version 6.0.0-dev.108.
All official @mikro-orm/* packages need to have the exact same version as @mikro-orm/core (6.0.0-dev.109).
Only exceptions are packages that don't live in the 'mikro-orm' repository: nestjs, sql-highlighter, mongo-highlighter.
Maybe you want to check, or regenerate your yarn.lock or package-lock.json file?
```

**To Reproduce**

1. Try to install `6.0.0-dev.108` as described above.
2. Run the app.
3. See the error.

**Expected behavior**

I expect mikro-orm packages to depend on exact versions of each other so that I can consistently install a version that isn't the latest version.

**Additional context**

I am not able to figure out the correct "resolutions" or "override" syntax to use to override the transient version dependencies.

Packages missing a `109` release: `@mikro-orm/cli`, `@mikro-orm/postgresql`, `@mikro-orm/migrations`.

Thanks!

**Versions**

| Dependency | Version |
| - | - |
| node | 18.18.0 |
| typescript | 5.1.6 |
| mikro-orm | 6.0.0-dev.108 |

**Comment by B4nan** [comment]
Yeah agreed, we should make this change, it's not just about the constant NPM hiccups, causing some packages to be missing (as they decide to throw a 503 at us in the middle of the publishing).
