### ISSUE TITLE
CLI option --silent or -s

### ISSUE THREAD

**Issue by localnet** [mikro-orm/mikro-orm#477]
**Is your feature request related to a problem? Please describe.**
I am writing tests and to setup the database, in `globalSetup`, I am using:
```typescript
exec("mikro-orm schema:drop -r --drop-db");
exec("mikro-orm schema:create -r");
```

And in the test files:
```typescript
beforeEach(() => {
    exec("mikro-orm database:import test/__datasets__/delete.sql");
    exec("mikro-orm database:import test/__datasets__/insert.sql");
});
```

But this pollute the output with:
```
Schema successfully dropped
Schema successfully created
File test/__datasets__/delete.sql successfully imported
File test/__datasets__/insert.sql successfully imported
```

**Describe the solution you'd like**
CLI option `--silent` or `-s` to don't show process output.

**Describe alternatives you've considered**
Use some other system to handle the database in the tests.

**Comment by B4nan** [comment]
Why don't you use schema generator directly? 

https://mikro-orm.io/docs/schema-generator#using-schemagenerator-programmatically

To mimic the import command, you can do this:

```typescript
await orm.em.getConnection().loadFile('...');
```

**Comment by localnet** [comment]
Feel free to close it. I found that "exec" has a "silent" option:
```typescript
exec("mikro-orm schema:drop -r --drop-db", { silent: true });
exec("mikro-orm schema:create -r", { silent: true });
exec("mikro-orm database:import test/__datasets__/delete.sql", { silent: true });
exec("mikro-orm database:import test/__datasets__/insert.sql", { silent: true });
```

Thanks.

**Comment by localnet** [comment]
> Why don't you use schema generator directly?
> 
> https://mikro-orm.io/docs/schema-generator#using-schemagenerator-programmatically
> 
> To mimic the import command, you can do this:
> 
> ```ts
> await orm.em.getConnection().loadFile('...');
> ```

It is other possibility. Thanks you.

**Comment by localnet** [comment]
As comment, I remember I had seen that in your tests, but when try to use it:
```typescript
export async function start(): Promise<void> {
    await ormClient.connect();
    await webServer.listen();

    await ormClient.em.getConnection().loadFile("test/__datasets__/delete.sql");
}
```

I get this error:
```
TSError: test/__helpers__/bootstrap.ts:19:40 - error TS2339: Property 'loadFile' does not exist on type 'Connection'.
```

**Comment by B4nan** [comment]
You need to have the `orm` instance correctly typed with the driver interface (`AbstractSqlDriver` will do the job too). It is noted in few places on the docs, one example here:

https://mikro-orm.io/docs/query-builder/#using-knexjs

```typescript
await (ormClient as MikroORM<AbstractSqlDriver>).em.getConnection().loadFile("test/__datasets__/delete.sql");
```
