### ISSUE TITLE
Bug Related to Populate on em.find and em.findOne etc..

### ISSUE THREAD

**Issue by totalard** [mikro-orm/mikro-orm#478]
**Describe the bug**
Populate field populating unwanted in nested manner and sometime it creates Maximum Call Stack exceeded error.

**Response**
You can Open and See formatted JSON response Arrived, and in JSON response, i have marked some as comments, where you can see the issue clearly. Please Check from **Line # 131**
[test.txt](https://github.com/mikro-orm/mikro-orm/files/4473045/test.txt)

**To Reproduce**
```
@Unique({ properties: ['xmlId'] })
export abstract class Base {

    @Field({ humanName: 'ID', discription: 'The Unique Identifier' })
    @PrimaryKey()
    id: number;

    @Field({ humanName: 'XMLID', discription: 'Unique XMLID Generated From Modules' })
    @Property({ nullable: true })
    xmlId: string;

    @Field({ humanName: 'Create Date', discription: 'The Record Creation Date' })
    @Property({ nullable: true })
    createdAt = new Date();

    @Field({ humanName: 'Update Date', discription: 'The Record Last Updation Date' })
    @Property({ onUpdate: () => new Date(), nullable: true })
    updatedAt = new Date();

    @Property({ persist: false })
    get _name() {
        return `${this.id}_${this['name']}`;
    }
}

@Entity()
export class Nav extends Base {

    @Property({ persist: false })
    get _name() {
        return this.name;
    }

    @Property()
    name!: string;

    @Property({ nullable: true })
    icon?: string;

    @Property({ type: 'text' })
    description?: string;

    @Property()
    order: number = 0;

    @Property()
    default: boolean = false;

    @ManyToOne({ nullable: true, onDelete: 'set null' })
    parent?: Nav;

    @OneToMany(type => Nav, children => children.parent)
    children = new Collection<Nav>(this);

    @ManyToOne({ nullable: true, eager: true })
    action?: Actions
}


async test() {
    let db = await this.mm.db.getDB();
    let data = await db.em.find(Nav, {}, ['children', 'parent']);
    console.dir(data);
    return '<html><body><pre>' + JSON.stringify(data, undefined, 2) + '</pre></body></html>';
  }
```

**Expected behavior**
Only Populate the related fields that given as Array. No Need of additional fields that populated as a bug, the requested related fields are enough

**Additional context**
It is Happening in Self Referanced Relations.

**Versions**

| Dependency | Version |
| - | - |
| node | 13 |
| typescript | 3.7.4|
| mikro-orm | 3.6.5 |
| your-driver | pg |

**Comment by B4nan** [comment]
This looks like a correct behaviour (in terms of loading/populating), this is how identity map works (you always have only 1 instance of given entity, so you can't expect to have something populated one time and not later on in the same context). 

The question is, are you really using `JSON.stringify` manually on entities like this? As that could be the cause, you need to use `wrap(entity).toJSON()` that handles what should be populated or not.

**Comment by totalard** [comment]
No.. I am not using in that way,, just to get formatted input..

Also.

Nav Entity populated with its parent and children.
so nav instance will have parent and children. But populate option provide me parent of nav instance and parent of it, and child of  like nested way.. it is not needed,, if i need only just related fields , why i need all of it. 


di you checked formatted json file i given

**Comment by totalard** [comment]
https://codebeautify.org/jsonviewer/cb0e0f10

Check this json, choose 2nd Item, where you can see how much it is nested.

Can you suggest me what is the equal substitution here 

https://github.com/typeorm/typeorm/blob/master/docs/find-options.md#basic-options

in Relation Title. please check..

**Comment by B4nan** [comment]
> so nav instance will have parent and children. But populate option provide me parent of nav instance and parent of it, and child of like nested way.. it is not needed,, if i need only just related fields , why i need all of it.

This is how identity map works. You load all the entities (`em.find({})`), so all the relations are actually set in the entity graph. And you are explicitly telling the ORM that you want "parent and children of each Nav entity", so that is what you get. 

> Can you suggest me what is the equal substitution here

No, this is not a TypeORM replacement, MikroORM is built around the concept of identity map, while TypeORM is not, they are very different thanks to this. 

You will need to handle the serialization yourself here, by implementing the `toJSON` method on the entity, where you have the control over what it will actually do. So depends on the output you are expecting, something like this could work:

```typescript

@Entity()
export class Nav {

  @PrimaryKey()
  id!: number;

  @Property()
  name: string;

  @ManyToOne({ nullable: true })
  parent?: Nav;

  @OneToMany(() => Nav, nav => nav.parent)
  children = new Collection<Nav>(this);

  constructor(name: string) {
    this.name = name;
  }

  toJSON() {
    const ret = wrap(this).toObject(['parent', 'children']);
    ret.parent = this.parent ? this.parent.id : null;
    ret.children = this.children.toArray();

    return ret;
  }

}
```

**Comment by totalard** [comment]
The issue solved. The em should be cleared by em.clear() to solve the populate issue.

dear @B4nan , that is why the issue i specify cant be seen in your tests and i feel it.. the need to be cleared at every request.

**Comment by B4nan** [comment]
You should have forked (and therefore cleared) EM for each request already, if you use nestjs (with the nestjs-mikro-orm helper), it is created for you automatically. 

https://mikro-orm.io/docs/identity-map

The manual clearing is usually needed only in tests.
