### ISSUE TITLE
defaultRaw current_timestamp(3) not taken into account in generated migration

### ISSUE THREAD

**Issue by kalu06** [mikro-orm/mikro-orm#4782]
**Describe the bug**
When specifying `defaultRaw: 'CURRENT_TIMESTAMP(3)'` on a Date property on an entity, the generated migration will contain `default current_timestamp(0)`

**To Reproduce**
1. Use the `mysql` type in mikro-orm.config.ts
2. Create an entity that contains a Date property like this:
```
@Property({
  columnType: 'timestamp(3)',
  defaultRaw: 'CURRENT_TIMESTAMP(3)',
 })
updatedAt!: Date;
```
4. Generate a migration using `npx mikro-orm migration:create`

**Expected behavior**
I would expect the migration to contain `default current_timestamp(3)` as specified in the entity `defaultRaw`.

**Versions**

| Dependency | Version |
| - | - |
| node | 18.6.0 |
| typescript | 5.2.2 |
| mikro-orm | 5.8.3 |

**Comment by B4nan** [comment]
Looks like an issue with `defaultRaw`, as with `default` it behaves correctly (but you can't use that for SQL functions, so won't help with this).

**Comment by kalu06** [comment]
Digging in the source code, I think I found the root cause in https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/schema/SchemaHelper.ts#L251.
It seems that knex uses the `length` prop to replace the precision of the `current_timestamp` from `defaultRaw`.

Changing my example above with the following seems to work:
```
@Property({
  columnType: 'timestamp(3)',
  defaultRaw: 'CURRENT_TIMESTAMP(3)',
  length: 3,
 })
updatedAt!: Date;
```

**Comment by B4nan** [comment]
Hmm interesting, I'd say the problem is that we shouldn't touch the user-provided `defaultRaw`, just like we never touch the `columnType` option.

**Comment by B4nan** [comment]
Right, the main issue here is the inference of the length for datetime columns were not implemented, we just used the platform default. That's why providing `length` explicitly helps.

https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/schema/DatabaseTable.ts#L85

**Comment by kalu06** [comment]
@B4nan thanks for checking!
Should it deserve a change in the documentation to clarify this out?
