### ISSUE TITLE
Question about Text Indexes

### ISSUE THREAD

**Issue by osayfun** [mikro-orm/mikro-orm#479]
Are MongoDB text indexes supported? Something like this:
```javascript
db.reviews.createIndex( { comments: "text" } )
```

**Comment by B4nan** [comment]
Nope, I can't believe that they designed the API this way omg. Looks like there is no way to do this via the second options parameter.

Anyway, you can create the index manually for now, in mongo there is no schema diffing, so the index support is just about creating them, those that are already present will be kept intact.

**Comment by osayfun** [comment]
This came as a surprise to me too!
How about using an attribute in `options` and then handling it in the MongoDriver `createIndex` method?

**Comment by B4nan** [comment]
Yeah sure, its not a problem to support this, the problem is why the hell they did not simply add a `text: boolean` option (or `type: 'text' | ...`). The first parameter of `createIndex` is not even properly defined anywhere.
