### ISSUE TITLE
Read replica not used when defined by clientUrl

### ISSUE THREAD

**Issue by Arcus16** [mikro-orm/mikro-orm#4813]
**Describe the bug**
When I define read replica by `clientUrl`, the read replica is never used.

[Reproduction repository](https://github.com/Arcus16/mikro-orm-read-replica-bug) 

**Expected behavior**
The read replica will be used regardless of how is configured.

**Versions**

| Dependency | Version |
| - | - |
| node | 20.8.0|
| typescript | 5.2.2 |
| mikro-orm | 5.8.7 |
| @mikro-orm/mysql | 5.8.7 |

**Comment by B4nan** [comment]
It's actually only about the database name, the rest of the options seem to be respected.
