### ISSUE TITLE
isInitialized() always returns true for Collection from ManyToMany relationship

### ISSUE THREAD

**Issue by dyedwiper** [mikro-orm/mikro-orm#4815]
**Describe the bug**
When having a ManyToMany relationship, the isInitialized() method on the referenced Collection always returns true, regardless if the reference is populated or not.

**To Reproduce**
See this CodeSandbox: https://codesandbox.io/p/sandbox/brave-pasteur-rz9y3k
Send a GET request and check response and console!

or

1. Create two entities with one entity referencing the other in a ManyToMany relation.
2. Store some data in the database.
3. Fetch the entity that owns the relation from the database without populating the relation.
4. Call the isInitialized() method on the referenced collection.

**Expected behavior**
 isInitialized() returns false.

**Additional context**
I tried it only with NestJs and MongoDB. I don't know if it is restricted to that.

For OneToMany relationships it works correctly.

**Versions**
| node | 18.14.0 |
| typescript | 5.1.3 |
| mikro-orm | 5.8.7 |
| mikro-orm/mongodb | 5.8.7 |

**Comment by B4nan** [comment]
Because they are always initialized, meaning you can see what items are there. You can use the methods parameter to check if they are fully initialized or not, meaning the items state is initialized, not just the collection state.

**Comment by dyedwiper** [comment]
But isn't this inconsistent with the behavior of `wrap(ref).isInitialized()` for ManyToOne relations? Because in this case in MongoDB you also always have the FK stored in the entity, but the return value of isInitialized() changes whether you populate the relation or not.

I added this case to the Sandbox for illustration.
