### ISSUE TITLE
Initializing a relation can result in the loss of pending changes

### ISSUE THREAD

**Issue by followben** [mikro-orm/mikro-orm#486]
**Describe the bug**
Lazily populating a bidirectional relation inadvertently writes any pending changes for the parent (and any onward relations) to the EntityManager's `originalEntityData` map. When the resulting UnitOfWork is committed, those changes are omitted from the changeSet and never written to the DB.

**To Reproduce**
1. Fetch an entity instance but don't populate any bidirectional relations
2. Change a property on the fetched instance (e.g. a scalar value)
3. Initialize a bidirectional relation and change it (e.g. add a new instance to a Collection)
4. Call `em.persistAndFlush()`

**Expected behavior**
Both changes are persisted to the database.

**Actual behavior**
Only the 2nd change, after the relation `init()`, is persisted.

**Versions**

| Dependency | Version |
| - | - |
| node | 13.10.1 |
| typescript | 3.8.3 |
| mikro-orm | 3.6.7 |
| pg | 7.18.2 |

**Comment by B4nan** [comment]
Thanks for the repro, appreciated!
