### ISSUE TITLE
FindQuery empty symbol

### ISSUE THREAD

**Issue by Kalos-S** [mikro-orm/mikro-orm#4873]
I need to implement a get multiple api endpoint that can be searched by multiple properties like status, user, and so on. If one of those properties is omitted from the request query it should be ignored by the find query.

Currently if either undefined or null gets passed the column gets queried for null which is not the wanted behaviour for an omitted filter. Adding the option to pass an empty symbol would fix that issue.

Example:
```js
const query = {
  status: "active",
};

em.find(Foo, { status: query.status, user: query.user })
```
currently returns
```sql
SELECT * FROM FOO WHERE status = "active" AND user is null
```

With an Empty symbol added the code could look like this:
```js
const query = {
  status: "active",
};

em.find(Foo, { status: query.status || Symbols.Empty, user: query.user || Symbols.Empty })
```
would return
```sql
SELECT * FROM FOO WHERE status = "active"
```

Expanding this same behaviour to query conditions like $gt or $lte would also be amazing.

**Comment by B4nan** [comment]
Numerous users were asking for `undefined` to be ignored this way, I am planning to have an option to trigger that behaviour. Do you think we really need some special symbol for that, or will it be enough if `undefined` behaves like that?
