### ISSUE TITLE
One-to-One relationship is not populated in the inverse side

### ISSUE THREAD

**Issue by thiagomini** [mikro-orm/mikro-orm#4879]
**Describe the bug**
* **Given** we have a relationship of One-to-One: 1 `User` has 1 `Profile`
* **And** the `User` side is the inverse side (it holds the `profile_id` column)
* **And** There is a managed `user` entity
* **When** we create a new `Profile` passing the `user`'s id as a parameter, and using the `Reference.createFromPK(User, user.id)` strategy
* **Then** the user's `profile_id` is not correctly populated (and therefore, the `profile_id` is not updated in the database

**Stack trace**
```
 FAIL  src/mikro-orm.test.ts > Mikro Orm > creates a user and assign a profile to it (using id)
AssertionError: expected null to be truthy

- Expected: 
null

+ Received: 
false

 ❯ src/mikro-orm.test.ts:73:37
     71|       refresh: true
     72|     });
     73|     expect(userWithProfile.profile).toBeTruthy()
       |                                     ^
     74|   });
     75| });

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  1 failed | 1 passed (2)
   Start at  16:24:34
   Duration  1.38s (transform 200ms, setup 0ms, collect 119ms, tests 215ms, environment 0ms, prepare 216ms)
```

**To Reproduce**
1. Clone the minimum reproducible code repository: https://github.com/thiagomini/mikro-orm-repro/tree/bug/bidirectional-relationship
2. run `yarn`
3. run `docker compose up -d`
4. run `yarn test`

**Expected behavior**
the `profile_id` should be populated in the `user` side

**Additional context**

Here are some logs for the failing test:

```
stdout | src/mikro-orm.test.ts > Mikro Orm > creates a user and assign a profile to it (using id)
[query] begin

stdout | src/mikro-orm.test.ts > Mikro Orm > creates a user and assign a profile to it (using id)
[query] insert into "test"."user" ("first_name", "last_name", "email", "created_at", "updated_at") values ('firstName', 'lastName', 'email@mail.com', '2023-10-26T19:24:35.495Z', '2023-10-26T19:24:35.495Z') returning "id" [took 1 ms]
[query] commit

stdout | src/mikro-orm.test.ts > Mikro Orm > creates a user and assign a profile to it (using id)
[query] begin

stdout | src/mikro-orm.test.ts > Mikro Orm > creates a user and assign a profile to it (using id)
[query] insert into "test"."profile" ("id", "image_url", "active") values ('0', 'https://example.com', true) returning "id", "active" [took 1 ms]
[query] commit

stdout | src/mikro-orm.test.ts > Mikro Orm > creates a user and assign a profile to it (using id)
[query] select "u0".* from "test"."user" as "u0" where "u0"."id" = '1' limit 1 [took 1 ms, 1 result]
```

As you can see, the `user.profile_id` column is not updated.

**Versions**

| Dependency | Version |
| - | - |
| node | 18.12.1 |
| typescript | 5.0.4 |
| mikro-orm | 5.8.4 |
| pg | 8.11.2 |

**Comment by thiagomini** [comment]
Just one additional info, @B4nan: This [test case](https://github.com/thiagomini/mikro-orm-repro/blob/bb16c7330f78619732026462f951cbfd6300bb84/src/mikro-orm.test.ts#L34) passes when we pass the `User` instance instead of its `id`. So, the issue is probably related to the `Reference.createFromPK()` method.

I also believe the issue is somewhere in the `defineReferenceProperties` method:
https://github.com/mikro-orm/mikro-orm/blob/70b75a54656418d81acf384e54d2f38d8e0e3820/packages/core/src/entity/EntityHelper.ts#L150

IIRC, it was not recognizing the `Ref` with an `Id` as a reference

**Comment by B4nan** [comment]
FYI you dont need that conditional logic in your constructor, see https://github.com/mikro-orm/mikro-orm/commit/9b2c9fe89b67f3f1190dc0cdd7bab9911c2f9efa?w=1#diff-1936bed9cc864e416877178c1a1072b1099c07da96fceeb4b01e809d34dd4673R22

**Comment by thiagomini** [comment]
Thank you very much for the fix and the hint, Martin! We truly appreciate it!
