### ISSUE TITLE
Incorrect DELETE_EARLY type

### ISSUE THREAD

**Issue by zoltan-mihalyi** [mikro-orm/mikro-orm#4895]
**Describe the bug**
If an entity is created and an other is deleted in a transaction, and they have the same id, the other will have DELETE_EARLY ChangeSetType instead of DELETE.

**To Reproduce**
```ts
import { Entity, MikroORM, PrimaryKey } from '@mikro-orm/sqlite';

@Entity()
class A {

  @PrimaryKey()
  id!: string;

}

@Entity()
class B {

  @PrimaryKey()
  id!: string;

}

describe('GH issue 1346', () => {

  let orm: MikroORM;
  const types: string[][] = [];

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [A, B],
      dbName: `:memory:`,
      subscribers: [{
        onFlush: args => {
          const changeSets = args.uow.getChangeSets();
          types.push(changeSets.map(cs => cs.type));
        },
      }],
    });

    await orm.schema.ensureDatabase();
  });

  beforeEach(async () => {
    await orm.schema.dropSchema();
    await orm.schema.createSchema();
  });

  afterAll(() => orm.close(true));

  test('preserve data fields that match pivot field', async () => {
    await orm.em.transactional(async em => {
      em.create(A, { id: '1a' });
      em.remove(em.getReference(B, '1a'));
    });

    await orm.em.transactional(async em => {
      em.create(A, { id: '2a' });
      em.remove(em.getReference(B, '2b'));
    });

    expect(types).toEqual([
      ['create', 'delete'],
      ['create', 'delete'],
    ]);
  });

});
```
**Expected behavior**
The following output:
```
[ 'create', 'delete_early' ]
[ 'create', 'delete' ]
```
**Actual behavior**
The following output:
```
[ 'create', 'delete' ]
[ 'create', 'delete' ]
```

**Versions**

| Dependency | Version |
| - | - |
| node | 16.20.0 |
| typescript | 5.2.2 |
| mikro-orm | 5.9.2 |
| sqlite | 5.9.2 |

**Comment by B4nan** [comment]
FYI `delete_early` is a valid change set type, there are cases where you will get that instead of just `delete`. Maybe I should simplify this in v6, so it's easier to work with it in the subscribers, we could have a flag instead of a separate changeset type, same for `update_early`.

But in this case it's indeed wrong, and I can see why, the check does not care about entity types. I hope you don't mind if I fix this in v6 only, I want to move forward with that today.

**Comment by B4nan** [comment]
Fixed in v6 via 9af367ca3

**Comment by zoltan-mihalyi** [comment]
Thank you!

A simple workaround is to check for `delete_early` type too.

**Comment by B4nan** [comment]
Backported the fix to 5.x branch:

https://github.com/mikro-orm/mikro-orm/commit/fef7a1b5f0dc6a013134ae43d7b2de32418ec26c
