### ISSUE TITLE
repository.remove() works different depending on if entity or entity reference being used as argument

### ISSUE THREAD

**Issue by alekbarszczewski** [mikro-orm/mikro-orm#4905]
**Describe the bug**
`repository.remove(entity)` and `repository.remove(entityReference)` work different when in same context entity is being persisted. Remove by entity works correctly (I think), while remove by entity reference does not (see example below).

**To Reproduce**
Entity classes:
```ts
// TestEntity1 class
export class TestEntity1 {
  public readonly id: string;

  constructor(id: string) {
    this.id = id;
  }
}

// TestEntity2 class (identical to TestEntity1)
export class TestEntity2 {
  public readonly id: string;

  constructor(id: string) {
    this.id = id;
  }
}
```
Entity schemas:
```ts
// TestEntity1 schema
export const TestEntity1Schema = new EntitySchema({
  class: TestEntity1,
  properties: {
    id: {
      type: 'text',
      primary: true,
    },
  },
});

// TestEntity2 schema (identical to TestEntity2 schema)
export const TestEntity2Schema = new EntitySchema({
  class: TestEntity2,
  properties: {
    id: {
      type: 'text',
      primary: true,
    },
  },
});
```

```ts
const e1 = new TestEntity1('abc');
const e2 = new TestEntity2('def');

em.persist(e1);
em.persist(e2);

// remove by entity
em.remove(e1);

// remove by entity reference
em.remove(em.getReference(TestEntity2, 'def'));

await em.flush();
```

**Current behavior**
```sh
[query] begin
# TestEntity2 is deleted first and then inserted is not correct as in code at first it was inserted and then deleted by reference
[query] delete from "test_entity2" where "id" in ('def') [took 2 ms]
[query] insert into "test_entity2" ("id") values ('def') returning "id" [took 2 ms]
# TestEntity1 is (I think correctly) only deleted, insertion is skipped
[query] delete from "test_entity1" where "id" in ('abc') [took 3 ms]
[query] commit
```

**Expected behavior**
`remove(entityReference)` should work in a same way as `remove(entity)` I think.

**Additional context**
The behaviour is even more strange when persisted entity loaded from db before the flush:
```ts
const e1 = new TestEntity1('abc');

this.testEntity1Repository.persist(e1);

// findOne() before persisted entity is flushed
const e1FromRepo = await this.testEntity1Repository.findOne('abc');

console.log(!!e1FromRepo);

this.testEntity1Repository.remove(e1FromRepo!);
```

gives following output:

```sh
[query] begin
[query] insert into "test_entity1" ("id") values ('abc') returning "id" [took 3 ms]
[query] commit
true
[query] begin
[query] delete from "test_entity1" where "id" in ('abc') [took 2 ms]
[query] commit
```
This is weird because `repository.findOne()` causes two separate transactions when on flush.
First one saves persisted entity in db and another one deletes it from db.
I am not sure if this is expected behaviour - I thought that when entity is persisted but not flushed yet then repository.findOne(PK) will get it from IdentityMap. 

**Versions**

| Dependency | Version |
| - | - |
| node | 18.16.0 |
| typescript | 5.2.2 |
| mikro-orm | 5.9.3 |
| mikro-orm/postgresql | 5.9.3 |

**Comment by B4nan** [comment]
I would appreciate reproductions without using repositories, it only complicates the code and it is a common source of user-land bugs if used wrong. Not to mention that `persist/remove/flush` are all removed from the repository level in v6 (as they were only shortcuts for the EM).

I am also missing flush calls from your example completely, just calling `persist` or `remove` will never fire any queries.

> The behaviour is even more strange when persisted entity loaded from db before the flush:

Nothing weird about that code, its expected behaviour. Your entity is marked for persistance, the find call sees that and triggers auto-flush, returns the flushed entity right ahead (without a query, as its already in the ID map) and then you remove it (and flush again, you skipped that part in the code, but it does not happen just from the `remove` call, you need to flush explicitly).

> I am not sure if this is expected behaviour - I thought that when entity is persisted but not flushed yet then repository.findOne(PK) will get it from IdentityMap.

Its not in the ID map as you havent flushed, just calling persist does not add it there, only managed entities are there, and entity becomes managed after flush (as only then we can be sure it has a primary key).

**Comment by alekbarszczewski** [comment]
Got it, thanks, as for persisted entity not in identity map it makes sense I guess.
However not sure about different behaviour when entity or reference is being used.
I updated my comment with entity manager instead of repositories and the output is the same (previously I just skipped `em.flush()` call from comment, but I am always calling em.flush() in the end - updated this is comment too).

**Comment by B4nan** [comment]
> However not sure about different behaviour when entity or reference is being used.

There should be no difference, that expectation is indeed correct :]

**Comment by alekbarszczewski** [comment]
From what I tested it seems there is a problem with this line:
https://github.com/mikro-orm/mikro-orm/blob/5.x/packages/core/src/unit-of-work/UnitOfWork.ts#L311

Since `persistStack` is native `Set` it removes items only by `===` operator, so when entity is actually entity reference then it won't be removed from persist stack.

And here https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/entity/EntityFactory.ts#L214 reference is a real entity instance only if it's in IdentityMap (and entities that are persisted but not flushed are not inside IdentityMap as you mentioned).

So the only idea I have is to make additional search for entity here https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/entity/EntityFactory.ts#L219 - before creating reference check if entity of same type and PK is not already in persistStack - and if it is, then take it from there and return instead of creating a reference - what do you think?

**Comment by B4nan** [comment]
> Since persistStack is native Set it removes items only by === operator, so when entity is actually entity reference then it won't be removed from persist stack.

This only points to you having context mismatch, the reference and actual entity should be the same.

**Comment by B4nan** [comment]
If this code is what you are actually doing, then it make sense - as again, you are missing a flush call there.

```ts
const e1 = new TestEntity1('abc');
const e2 = new TestEntity2('def');

em.persist(e1);
em.persist(e2);

// remove by entity
em.remove(e1);

// remove by entity reference
em.remove(em.getReference(TestEntity2, 'def'));

await em.flush();
```

That would be a wontfix to me, as you are calling `em.getReference(TestEntity2, 'def')` before the entity gets flushed. If you would do this instead, things should work fine:

```ts
const e1 = new TestEntity1('abc');
const e2 = new TestEntity2('def');

em.persist(e1);
em.persist(e2);

await em.flush(); // <=== added flush here

// remove by entity
em.remove(e1);

// remove by entity reference
em.remove(em.getReference(TestEntity2, 'def'));

await em.flush();
```

**Comment by alekbarszczewski** [comment]
My current workaround is that I have custom repository with my own `remove()` method which looks like this:

```ts
remove(id: string): void {
  let ref: MyEntity | undefined = undefined;

  // Check if entity of same type and id is in persistStack
  // If yes then it is passed to original "remove()" method (and then this entity is removed from persist stack)
  this.em.getUnitOfWork()
    .getPersistStack()
    .forEach((x) => {
      if (x instanceof MyEntity && x.id === id) {
        ref = x;
      }
    });

  if (!ref) {
    ref = this.em.getReference(MyEntity, id);
  }

  this.em.remove(ref);
}
```
Not sure if it's desired behaviour in MikroOrm.
I will add "flush()" call in my example, again I skipped it accidentaly.

**Comment by B4nan** [comment]
The problem with that approach is that entities in the persist stack might not have the primary key yet, it will work only with user-provided PKs.

**Comment by alekbarszczewski** [comment]
Makes sense, I use user-provided PKs. Just wondering, if it already behaves differently for entity/reference then maybe it would be better to make it work "as expected" just for the case when PK is present / user-provided? Just wondering, I can leave with my workaround :).

**Comment by B4nan** [comment]
I will consider that for v6, although I really dislike the idea of dealing with entities differently based on a PK value.

**Comment by alekbarszczewski** [comment]
Thank you. It's worth to mention I think that in .net EFCore DbContext (which is kind of equivalent to Mikro Orm UnitOfWork) entities added to the context (but not saved in DB yet) are returned from the context by `Find(PK)` method (see https://learn.microsoft.com/en-us/ef/ef6/querying/#finding-entities-using-primary-keys):

> Find will return entities that are in the Added state. That is, Find will return entities that have been added to the context but have not yet been saved to the database.

`dbContext.Find(PK)` is equivalent of `em.findOne(PK)`.

So AFAIK in EFCore  it's possible to do something like this:

```
em.persist(new Entity(1));
const instance = await em.findOne(Entity, 1); // <-- in EFCore it does not make query to DB, just gets instance from IdentityMap
em.remove(instance);
em.flush();
```

I am mentioning this because I consider EF Core DbContext a very good implementation of UnitOfWork pattern.

**Comment by B4nan** [comment]
Interesting, thank you for the link, if other UoW frameworks behave this way, it might be the correct thing to do. There were several people confused by this behavior, it's not the first time I am discussing this, and with every single discussion I lean more towards what people say than my beliefs, maybe this is the inflection point :]

**Comment by B4nan** [comment]
Looking into this and just wanted one last confirmation, are we aligned on your test not producing any queries from the flush call? As you basically cancel the `em.persist()` with the `em.remove` call.

**Comment by alekbarszczewski** [comment]
Yes, this is how I think it should work - when persisted entity is removed then it's removed from UoW entirely and there are no changes to be made to database. And this is how it works with my current workaround I mentioned above.

**Comment by B4nan** [comment]
This was a bit harder than expected, but I am quite happy with the result. #4912

**Comment by alekbarszczewski** [comment]
Wow that was quick, thank you! Looking forward for 6.x :D
