### ISSUE TITLE
Schema Generator touches nullable properties with each update

### ISSUE THREAD

**Issue by jasperroloff** [mikro-orm/mikro-orm#491]
**Describe the bug**
When generating a migration or running a schema upgrade directly, the schema generator alters the nullable properties of the entity each time.

**Stack trace**
The generated schema update is the following (even if executed already):

```
set names utf8;
set foreign_key_checks = 0;

alter table `foo_entity` modify `nullable_string_property` varchar(255), modify `nullable_boolean_property` tinyint(1), modify `nullable_number_property` int(11);

set foreign_key_checks = 1;
```

**To Reproduce**
I've created a sample repository. Use `ts-node src/main.ts` to run.
https://github.com/jasperroloff/mikro-orm-nullable-issue

**Expected behavior**
Since the entity didn't change, the schema generator should generate an empty update (without the "alter table ..." statements).

**Additional context**
I discovered this behavior with both metadata providers: TsMorph, ReflectMetadata and with both database drivers: mysql, mariadb.

**Versions**

| Dependency | Version |
| - | - |
| node | v13.13.0 |
| typescript | ^3.8.3 |
| mikro-orm | ^3.6.8 |
| mariadb | ^2.3.1 |
| mysql2 | ^2.1.0 |
| ts-node | ^8.8.2 |

(see package.json in sample repo)

**Comment by B4nan** [comment]
Well it does not produce any additional queries for me. What version of MySQL are you using (not the driver)? Maybe you use MySQL 8?

**Comment by jasperroloff** [comment]
Hi, thanks for your reply.

I am using MariaDB, `select version()` returns the following: `10.4.11-MariaDB`.

**Comment by B4nan** [comment]
Interesting, tried it with mariadb 10.1 first and it passed, but with 10.4 it does behave like you described.
