### ISSUE TITLE
The filter is not disabled if `default: true` is specified

### ISSUE THREAD

**Issue by baikinkirill** [mikro-orm/mikro-orm#4910]
**Describe the bug**
The filter is not disabled if `default: true` is specified

**To Reproduce**

1. Declaring a filter in which we specify that default is true:
```ts
@Filter({
    name: 'isArchived',
    cond: { isArchived: false },
    default: true,
});
```
2. Disabling the filter by name:
```ts
return await this._testRepository.findOneOrFail({ id }, {
    filters: { isArchived: false },
});
```

**Expected behavior**
The filter will be disabled and will not be included in the sql query.

**Additional context**
The filter remains active.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.16.0 |
| typescript | 4.8.4 |
| @mikro-orm/core | 5.7.12 |
| @mikro-orm/nestjs | 5.1.8 |
| @mikro-orm/postgresql | 5.7.12 |

**Comment by baikinkirill** [comment]
I'm sorry, I had two different sql queries in one endopint.

**Comment by B4nan** [comment]
We actually have this use case covered in tests, so it should indeed work.
