### ISSUE TITLE
v6 - using populate true in find returns wrong reference type

### ISSUE THREAD

**Issue by boopeshmahendran227** [mikro-orm/mikro-orm#4920]
**Describe the bug**
using populate true in find returns wrong reference type

```typescript
export class User extends BaseEntity {
  @OneToOne(() => JobSeeker, (e) => e.user, { nullable: true, ref: true })
  jobSeeker!: Ref<JobSeeker> | null;
}

const user = await this.em.findOneOrFail(User, userId, {
  populate: true,
});
if (!user.jobSeeker) {
  throw new BadRequestException('JobSeeker not found');
}
const x = user.jobSeeker.$.city;
```

Error:
Property '$' does not exist on type '{} & Reference<JobSeeker>'

But when i use `populate: ['jobSeeker']` it works

**Comment by B4nan** [comment]
I will end up with `populate: ['*']`, that's the only way I can keep all the connected types working correctly, at least without adding a lot of method overrides.
