### ISSUE TITLE
Limitations of lifecycle hooks

### ISSUE THREAD

**Issue by Dschoordsch** [mikro-orm/mikro-orm#493]
**Describe the bug**
Limitations of lifecycle hooks are not documented.
I would like to be able to modify a related entity (`OneToOne`) in `@BeforeCreate` and `@BeforeDelete` hooks. This fails for various reasons:
* `@BeforeCreate` does not have EntityManager
* `@AfterCreate` calling `flush` fails with locking error, just `persist` is not flushed
* `@BeforeDelete` same `flush` and `persist` issue

**Stack trace**
```
(node:464192) UnhandledPromiseRejectionWarning: ValidationError: The optimistic lock on entity SocialActivity failed
    at Function.lockFailed (/home/dschoordsch/eventbadger/badger/node_modules/mikro-orm/dist/utils/ValidationError.js:80:16)
    at ChangeSetPersister.processOptimisticLock (/home/dschoordsch/eventbadger/badger/node_modules/mikro-orm/dist/unit-of-work/ChangeSetPersister.js:60:43)
    at ChangeSetPersister.persistEntity (/home/dschoordsch/eventbadger/badger/node_modules/mikro-orm/dist/unit-of-work/ChangeSetPersister.js:42:20)
    at process._tickCallback (internal/process/next_tick.js:178:7)
```

**To Reproduce**
modify a related entity in `@BeforeDelete` and `flush()`

**Expected behavior**
Ideally there would be a way to modify current entity in `@BeforeCreate` and `@BeforeDelete`, i.e. I could create a related entity and set the reference.
At least the limitations of the hooks should be documented, i.e. don't modify the changeset, don't flush.

**Versions**

| mikro-orm | 3.6.5 |

**Comment by B4nan** [comment]
> Ideally there would be a way to modify current entity in @BeforeCreate and @BeforeDelete, i.e. I could create a related entity and set the reference.

How does modifying an entity that will be removed at the end of the commit phase make sense? Your changes would be lost anyway. 

Generally touching the current UoW in the hooks is weird idea, although there is EM instance, it is internal, that is why it is prefixed with `__`. 

Looks like you want something like `onFlush` event in doctrine: https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/events.html#onflush

**Comment by Dschoordsch** [comment]
I have an entity `Session` which has 1:1 `SessionLog`, when it gets deleted, I wanted to update `SessionLog` with a timestamp, so the changes would not have been lost. I would also like to create `SessionLog` in `@BeforeCreate` of `Session`, but I do it currently in the constructor, which is ok.

I got confused by the statement that in the `@AfterCreate` etc. hooks the EntityManager is available, that's why I consider this mostly a documentation issue.

Looking at the `onFlush` documentation, I would like to keep current hooks since I don't want to have global behaviour for the flush, but just specific to one entity.
Of course if the hooks could be made to work with the same restrictions:

> The following restrictions apply to the onFlush event:
>
>If you create and persist a new entity in onFlush, then calling EntityManager#persist() is not enough. You have to execute an additional call to $unitOfWork->computeChangeSet($classMetadata, $entity).
Changing primitive fields or associations requires you to explicitly trigger a re-computation of the changeset of the affected entity. This can be done by calling $unitOfWork->recomputeSingleEntityChangeSet($classMetadata, $entity).

that would be awesome.

**Comment by B4nan** [comment]
> Looking at the onFlush documentation, I would like to keep current hooks since I don't want to have global behaviour for the flush, but just specific to one entity.

Well as said, making changes to entities when the flush already started will never have an effect, as changesets are already computed. Same applies to creating new or deleting existing entities - that is all handled via changesets (and they are all computed already at the time of executing hooks). If you want this behaviour, you would have to hook to the flush event as they allow in doctrine and change the changesets by hand. 

Which is again more of a hack, I would suggest to not use hooks here and model the behaviour elsewhere (custom repository, service or a dedicated method on entity that you call outside of the flush). Putting this kind of logic into hooks reduces readability (there is no direct link between the hook method and your code).

The concepts here are very similar to doctrine, so a lot of what is said on that page I linked applies here too (although there are hooks missing like the `onFlush`). I will think about adding the `onFlush` event in v4, or maybe the `preFlush` event would be even more suitable here, as it would be fired before the changesets are computed, so you could change the entity state as usual. Calling flush inside any of the hooks will be still forbidden, it just does not make sense.

**Comment by B4nan** [comment]
Check out #642
