### ISSUE TITLE
upsertMany error within nullable and composite key reference.

### ISSUE THREAD

**Issue by z4o4z** [mikro-orm/mikro-orm#4945]
### Describe the bug

ORM generates incorrect `Ref` for nullable and composite key references. 

Here's an example:
```ts
class EntityA {
  @Primary()
  id!: string;
  
  @Primary()
  envID!: string;
}

class EntityB {
  @Primary()
  id!: string;
  
  @Primary()
  envID!: string;

  @Property({ type: 'text' })
  name!: string;

  @ManyToOne(() => EntityA, {
    name: 'entity_a_id',
    default: null,
    onDelete: 'set default',
    nullable: true,
    fieldNames: ['entity_a_id', 'env_id'],
  })
  entityA: Ref<EntityA> | null = null;


}
```

when I try to upsert entities like below, I get an error `ValidationError: Value for EntityB.envID is required, 'undefined' found`.

```ts
await this.em.upsertMany(EntityA, [{ id: 'entity-a-1', envID: 'env-1' }, { id: 'entity-a-2', envID: 'env-1' }]);

await this.em.upsertMany(EntityB, [{ id: 'entity-b-1', envID: 'env-1', name: 'entity-b-1', entityA: ref({ id: 'entity-a-1', envID: 'env-1' }) }, { id: 'entity-b-2', envID: 'env-1', name: 'entity-b-2', entityA: ref({ id: 'entity-a-2', envID: 'env-1' }) }]);
```

After some debugging, I've found that [finalize method in the `QueryBuilderHelper`](https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/query/QueryBuilderHelper.ts#L663-L673) adds `entity_a_id` as a returning field, cause it has default value, I guess that makes sense. But when the [returned value is mapped](https://github.com/mikro-orm/mikro-orm/blob/a737b207744a85b2034a5e4a2b362e4aaefea570/packages/core/src/EntityManager.ts#L998C8-L998C8) the original `entityA` ref (that has both `id` and `envID`) replaced with incorrect one (that has only id, no env id), it happens cause in the `mapReturnedValues` `entityA` is set to `entity_a_id` that is returned from the DB, but it should be a composite value (array of `entity_a_id` and `envID`). 

Not sure what's the best solution here, probably ignore nullable + composite key references during `mapReturnedValues`?

### Reproduction

see above

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

5.9.4

### Node.js version

v16.19.0

### Operating system

macOS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Backported the fix from v6 here: https://github.com/mikro-orm/mikro-orm/commit/a7e9a82710b3b1451dba5d60add87c85393ec74b
