### ISSUE TITLE
Cannot merge OneToOne where the PrimaryKey is the ForeignKey

### ISSUE THREAD

**Issue by merceyz** [mikro-orm/mikro-orm#495]
**Describe the bug**
Creating a OneToOne relationship where the PrimaryKey is also the ForeignKey MikroORM fails to fetch data from the database; though it was able to insert it.

**Stack trace**
```
UnhandledPromiseRejectionWarning: ValidationError: You cannot merge entity 'User' without identifier!
    at Function.fromMergeWithoutPK (C:\repro\node_modules\mikro-orm\dist\utils\ValidationError.js:50:15)
    at EntityValidator.validatePrimaryKey (C:\repro\node_modules\mikro-orm\dist\entity\EntityValidator.js:62:43)
    at EntityManager.merge (C:\repro\node_modules\mikro-orm\dist\EntityManager.js:214:24)
    at EntityManager.findOne (C:\repro\node_modules\mikro-orm\dist\EntityManager.js:120:23)
    at EntityManager.findOneOrFail (C:\repro\node_modules\mikro-orm\dist\EntityManager.js:130:24)
    at C:\repro\src\index.ts:27:2
```

**To Reproduce**
<details>
  <summary>Source code</summary>

```ts
// entities/User.ts
import { Entity, PrimaryKey, OneToOne } from 'mikro-orm';
import { Profile } from './Profile';

@Entity()
export class User {
	@PrimaryKey()
	user_id!: number;

	// Setting joinColumn: 'user_id' results in:
	// Error: alter table `user` add column `user_id` integer null; - SQLITE_ERROR: duplicate column name: user_id
	// Without joinColumn, MikroORM creates the column `profile_user_id` which it shouldn't in this case
	// However it doesn't actually use the column when inserting data
	@OneToOne({ fieldName: 'user_id' })
	profile!: Profile;
}

// entities/Profile.ts
import { Entity, PrimaryKey, OneToOne } from 'mikro-orm';
import { User } from './User';

@Entity()
export class Profile {
	@PrimaryKey()
	user_id!: number;

	@OneToOne(() => User, (user) => user.profile, { fieldName: 'user_id' })
	user!: User;
}

// index.ts
import { MikroORM } from 'mikro-orm';
import { User } from './entities/User';
import { Profile } from './entities/Profile';

(async () => {
	const db = await MikroORM.init({
		type: 'sqlite',
		entitiesDirs: ['./entities'],
		entitiesDirsTs: ['./entities'],
		dbName: 'test.sqlite',
		baseDir: __dirname,
		cache: { enabled: false },
	});

	await db.getSchemaGenerator().ensureDatabase();
	await db.getSchemaGenerator().createSchema();

	const user = new User();
	user.profile = new Profile();

	await db.em.persistAndFlush(user);

	db.em.clear();

	// ValidationError: You cannot merge entity 'User' without identifier!
	await db.em.findOneOrFail(User, user);
})();
```
</details>

**Expected behavior**
I expect MikroORM to be able to fetch the data it just inserted into the database.

**Additional context**
I inherited a mysql database where the User table is linked to the Profile table using the PrimaryKey, meaning `User.PrimaryKey = Profile.PrimaryKey`

**Versions**

| Dependency | Version |
| - | - |
| node | v12.16.1 |
| typescript | 3.8.3 |
| mikro-orm | 3.6.8 |
| sqlite3 | 4.1.1 |
| mysql2 | 2.1.0 |

**Comment by opotonil** [comment]
It could be that you are trying to use [Composite and Foreign Keys as Primary Key](https://mikro-orm.io/docs/composite-keys), or more specifically the [Use-Case 2: Simple Derived Identity](https://mikro-orm.io/docs/composite-keys#use-case-2-simple-derived-identity).

**Comment by B4nan** [comment]
You should have only one property on the Profile entity (the 1:1, but add primary: true to the options). Mapping single column to multiple properties is not supported (but you can have virtual properties).

**Comment by merceyz** [comment]
> It could be that you are trying to use Composite and Foreign Keys as Primary Key, or more specifically the Use-Case 2: Simple Derived Identity.

@opotonil Ah, yes it is. Thank you, I didn't quite know what to search for. Although quick note: [Use-Case 2: Simple Derived Identity](https://mikro-orm.io/docs/composite-keys/#use-case-2-simple-derived-identity) fails in sqlite with `SQLite3 Foreign & Primary keys may only be added on create`

> Look at the docs that are linked here, there is pretty much the same use case covered.

@B4nan Indeed it is, sorry about that. I'll close this issue then.

---

I see that `em.populate(user, 'address')` performs a where-in query, would it not be better to do a simple select?
```
select `e0`.* from `address` as `e0` where `e0`.`user_id` in (123) order by `e0`.`userid` asc
vs
select `e0`.* from `address` as `e0` where `e0`.`user_id` = 123
```
