### ISSUE TITLE
Allow duplicate names if they are from different schema

### ISSUE THREAD

**Issue by bakura10** [mikro-orm/mikro-orm#4955]
### Describe the bug

Hi,

I am not sure if this is expected or not, feel free to close the ticket if not.

I am trying to create two entities with the same name but different schema:

```
import { Entity, PrimaryKey } from "@mikro-orm/postgresql";

@Entity({ tableName: 'staff_members', schema: 'first' })
export class StaffMember {
  @PrimaryKey()
  id: string = crypto.randomUUID();
}
```

```
import { Entity, PrimaryKey } from "@mikro-orm/postgresql";

@Entity({ tableName: 'staff_members', schema: 'two' })
export class StaffMember {
  @PrimaryKey()
  id: string = crypto.randomUUID();
}
```

With this code for the config:

```
import { defineConfig } from "@mikro-orm/postgresql";
import { StaffMember as FirstStaffMember } from "./staff-one.js";
import { StaffMember as SecondStaffMember } from "./staff-two.js";

export default defineConfig({
  // ...
  entities: [
    FirstStaffMember, SecondStaffMember
  ],
});
```

It complains that the entities have the same name. But as I imported them as two different named imports, the error feels a bit unintuitive, as the schema are different so they are not mapping to the same table.

Thanks.

### Reproduction

-

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.0.0-dev198

### Node.js version

Node.js 20

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Not supported on purpose, entity name on its own is important, as that is used everywhere.

**Comment by B4nan** [comment]
Any reason you don't use wildcard schema entity for this?

**Comment by bakura10** [comment]
The idea is to have a global user entity, but that this user can belongs to multiple "types" of users (of type "A" or "B"). Those two types of users are completely distinct kind of users in the system. Anyway, I'm ok with naming them differently :)
