### ISSUE TITLE
Typing issue with filter queries and generics

### ISSUE THREAD

**Issue by roderik** [mikro-orm/mikro-orm#4962]
### Describe the bug

Cannot explain it better than the reproduction: countWaiting used to work in v5, the other two also did not

![CleanShot 2023-11-26 at 09 01 14@2x](https://github.com/mikro-orm/mikro-orm/assets/16780/2707c4ba-2ebf-4199-bb4a-5340b2641e10)

### Reproduction

https://github.com/mikro-orm/reproduction/pull/3

### What driver are you using?

None

### MikroORM version

6.0.0-rc.2

### Node.js version

20

### Operating system

osx

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
I will need to check, but if this worked in v5, it might have been because the method was not type-safe before, as what you are trying to do is a TS limitation IMHO. 

https://stackoverflow.com/questions/65490587/generics-doesnt-seem-to-fit-well-with-queryfilter/65523491#65523491

**Comment by B4nan** [comment]
Oh I see, it does not work even with the type assertion.
