### ISSUE TITLE
Relationship conditions

### ISSUE THREAD

**Issue by lewispham** [mikro-orm/mikro-orm#4963]
**Is your feature request related to a problem? Please describe.**
It looks like mikro-orm does not support default conditions for a relationship. At this time, we'll have to pass the condition as `init` options when we want to load a collection under some conditions.

```typescript
const errors = await collection.init({
  where: {
    type: "ERROR"
  }
})
```
It would be ways more convenient to be able to pass the condition beforehand, when we define the relationship for example.
**Describe the solution you'd like**
Pass the condition as `Collection` options
```typescript
  @OneToMany(() => Log, log => log.user)
  errors = new Collection<Candidate>(this, {
    where: {
      type: "ERROR"
    }
  });
```

**Describe alternatives you've considered**
Define the condition as relationship definition
```typescript
  @OneToMany({
    entity: () => Log,
    mappedBy: log => log.user,
    where: {
      type: "ERROR"
    }
  })
  errors = new Collection<Candidate>(this);
```

**Comment by B4nan** [comment]
Why don't you use a filter instead? This is exactly the use case for filters, I am not sure if we need more.

**Comment by lewispham** [comment]
@B4nan Using filters still requires passing filter name into every single query. While my proposed approach requires no further steps. It's also a bit less readable since filter definition is at entity level, not property level.

**Comment by B4nan** [comment]
You can enable a filter by default...

**Comment by B4nan** [comment]
There are indeed some gotchas with filters, if you would use them here, they would always join the target relation, while what you are proposing would be applied only if you load the collection, right?

Btw we will need to go with the alternative approach, the second parameter of the constructor is already occupied, and it feels more correct anyway - it is metadata and as such it should be part of the entity definition, a property initializer is a runtime concept - you won't know anything about that unless you create some entity instance.

**Comment by B4nan** [comment]
You can already specify `orderBy`, for `limit` it would be pretty hard for anything else than the `init` call, this would require window functions or subquery joins.

**Comment by lewispham** [comment]
Ah I see. It should be ok with just `where` and `orderBy` then.

**Comment by lewispham** [comment]
Hi @B4nan, is there any chance that this feature will be implemented soon?

**Comment by B4nan** [comment]
Yes, there is a chance, e.g. when someone sends a PR :] 

I will need to prioritize bug fixing in the upcoming weeks and have a short vacation planned too, I won't have time fore feature development.

**Comment by pohnean** [comment]
+1

**Comment by whather** [comment]
Hey @B4nan, I have a relationship declared as:

```
@OneToMany(() => AgentSession, 'company', {
    orderBy: [{ createdAt: 'ASC' }],
    where: {
      contact: null,
    },
  })
  sessionsWithoutContacts = new Collection<AgentSession>(this);
```

But doing a `await company.sessionsWithoutContacts.loadItems()` or `await company.sessionsWithoutContacts.init()` does not obey the `where`. It ignores it.

However, doing:

```
company.sessionsWithoutContacts.loadItems({
      where: { contact: null },
    });
```

works great. Any clue why the `where` defined on the `@OneToMany()` is being ignored? I'm on 6.3.6.

**Comment by B4nan** [comment]
Complete repro welcome 🤷
