### ISSUE TITLE
Many-to-Many association with Custom Pivot Entity fails when one of the Entities' class name is non-standard

### ISSUE THREAD

**Issue by thiagomini** [mikro-orm/mikro-orm#4988]
### Describe the bug

* **Given** we have a relationship of Many-to-Many: A `Company` has many `ProductEntity`'s , and a `ProductEntity` may belong to many `Company`'s
* **And** the associations were defined using entity schemas
* **And** There is a custom pivot entity called `CompanyProduct`
* **When** we create a new `Company` and add a new `Product` to its collection
* **Then** MikroORM throws an error: `InvalidFieldNameException: insert into "test"."company_product" ("company_id", "product_entity_id") values ('1', '1') returning "id" - column "product_entity_id" of relation "company_product" does not exist`

Full Stack trace:

```
src/mikro-orm.test.ts > Mikro Orm > creates a company with products
InvalidFieldNameException: insert into "test"."company_product" ("company_id", "product_entity_id") values ('1', '1') returning "id" - column "product_entity_id" of relation "company_product" does not exist
 ❯ PostgreSqlExceptionConverter.convertException node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:36:24
 ❯ PostgreSqlDriver.convertException node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:201:54
 ❯ node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:205:24
 ❯ PostgreSqlDriver.nativeInsertMany node_modules/@mikro-orm/knex/AbstractSqlDriver.js:300:21
 ❯ PostgreSqlDriver.updateCollectionDiff node_modules/@mikro-orm/knex/AbstractSqlDriver.js:742:13
 ❯ UnitOfWork.persistToDatabase node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:715:13
 ❯ PostgreSqlConnection.transactional node_modules/@mikro-orm/knex/AbstractSqlConnection.js:36:25
 ❯ UnitOfWork.doCommit node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:295:17
 ❯ UnitOfWork.commit node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:268:13
 ❯ Parser.parseErrorMessage node_modules/pg-protocol/src/parser.ts:369:69
 ❯ Parser.handlePacket node_modules/pg-protocol/src/parser.ts:188:21
 ❯ Parser.parse node_modules/pg-protocol/src/parser.ts:103:30
```

### Reproduction

1. Clone the minimum reproducible code repository: https://github.com/thiagomini/mikro-orm-repro/tree/bug/many-to-many-association
2. run `yarn`
3. run `docker compose up -d`
4. run `yarn test`

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

5.9.4

### Node.js version

20.9.0

### Operating system

WSL 2.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
While the issue is valid, the repro won't work after the fix on its own - you can't use `onCreate` property option for pivot entities here, working with the M:N relation does not create such entity instances under the hood, so they won't be executed. You need a db default (`defaultRaw: 'current_timestamp'`), and similarly, pivot rows are never updated, only added or removed, so the `onUpdate` will only work if you manually load that pivot entity and modify it.
