### ISSUE TITLE
Question: Does mikro-orm help with impedance mismatch?

### ISSUE THREAD

**Issue by mikicho** [mikro-orm/mikro-orm#499]
Hey,
I'm thrilled to find an orm in nodejs/TS that uses the unit-of-work and the identity map patterns!
Thanks.

Mikro-ORM let us define relationships (one to many, many to many, etc).
Isn't it expose the users to even bigger problems that may cause by impedance mismatch? lazy/eager loading? etc..

Thanks :)

**Comment by B4nan** [comment]
Not sure I understand, can you be more specific?

**Comment by mikicho** [comment]
Mikro-ORM (and other ORMs) let us do things like this:
```
@Entity()
export class Business {

  @PrimaryKey()
  id!: number;

...

  @OneToMany(() => Dish, dish => dish.business)
  dishes!: Dish[];

  constructor(...) {
    ...
  }
}
```

Now, `OneToMany` may seem like a good idea, and it is for small projects, it causes a lot of troubles because it's pretty difficult to map relational data into an object. ([wiki](https://en.wikipedia.org/wiki/Object-relational_impedance_mismatch))

So, nested models like this:
```
{
  id: 1
  dishes: [...]
}
```

It can be a bad idea because for example you never know if dishes property is undefined or already populated by `join` query, fetch all relations isn't practical.

I'm going to try to use Mikro-ORM with flat Entities (not use `OneToMany`, `ManyToMany` etc decorators) but I'm curious if there are design decisions/patterns/best-practices in Mikro-ORM which help users to avoid such problems.

**Comment by B4nan** [comment]
> Now, OneToMany may seem like a good idea, and it is for small projects, it causes a lot of troubles because it's pretty difficult to map relational data into an object. (wiki)

All associations are lazy by default, it's up to you when you populate what. 1:m and m:n are implemented as `Collection`, not as array. If you want to load only a part of the collection, you can use QB. 

> It can be a bad idea because for example you never know if dishes property is undefined or already populated by join query, fetch all relations isn't practical.

It is always defined, as a `Collection`. If you do not populate it, it will not be initialized (so you can't read its values). In v4 it will be possible to add new items to not initialized collections. Collection updates in m:n are implemented as diffs, so only necessary insert/update/delete queries are made to get the collection in sync. 

https://mikro-orm.io/docs/collections

**Comment by mikicho** [comment]
> All associations are lazy by default
This is sort of the problem because you never can know in what "form" the entity will be.

This example also for your second point.

We have the following Entity/Modal:
```
@Entity()
export class Dish{

  @PrimaryKey()
  id!: number;

...

  @ManyToOne(() => Business, dish => dish.businessId)
  business!: Business[];

  constructor(...) {
    ...
  }
}
```

Now we have the following function:
```
function printDish(dish: Dish) {
   console.log(dish.business.name); //may cause "Cannot read property 'name' of undefined" error
}
```

Am I wrong?
Thanks

**Comment by B4nan** [comment]
https://mikro-orm.io/docs/entity-references#better-type-safety-with-referencet-wrapper

**Comment by mikicho** [comment]
Oh, how did I miss that!? 
I'll close it for now and reopen if I'll have further questions. thanks!
