### ISSUE TITLE
Allow the Query Builder entity to be specified as EntityName<T>

### ISSUE THREAD

**Issue by followben** [mikro-orm/mikro-orm#500]
**Is your feature request related to a problem? Please describe.**
We had a bug where Mikro threw a validation error when trying to create an EntityManager's QueryBuilder when deployed with Webpack. This was because the entity classname has to be supplied as a string, but the deployed entity name was different.

**Describe the solution you'd like**
Allow `EntityManager.createQueryBuilder` the class to be specified as a generic (like the `EntityManager.find`).

**Describe alternatives you've considered**
I'm working around this for now by first creating a repository for the entity, then using creating the QueryBuilder from that.

**Additional context**
I haven't discovered any yet, but if there are other APIs that only allow entity types to be specified as string, they'd also be good to overload with a typed variant.

**Comment by B4nan** [comment]
It already does work the very same way as other public EM API:

https://github.com/mikro-orm/mikro-orm/blob/master/lib/EntityManager.ts#L70

**Comment by followben** [comment]
Really sorry @B4nan - must have been something odd with my TS compilation that would only allow me to supply a string in that first param. Should have at least checked the source before writing this up or bothering you.

**Comment by B4nan** [comment]
There is `AbstractSqlDriver.createQueryBuilder()` that does accept string only but that method is protected.
