### ISSUE TITLE
Incorrect Entity map when using nested Entities relations

### ISSUE THREAD

**Issue by xmajzel** [mikro-orm/mikro-orm#5003]
### Describe the bug

We have written clear test to reproduce the bug (together with @ruby184), I will briefly describe test cases.

**Test reschedule registration from slot1 to slot2 (lazy loading assignees):**

The problem is with registration entity, where after updating slot (to slot2) an then populating nested assignees entities, registration entity has incorrectly set slot1 (the old one) on itself.

**Test reschedule registration from slot1 to slot2 (eager loading assignees):**

The problem is with nested assignees entity, where after assigning of slot2 to registration is also incorrectly changed slotReference inside assignee entity.

### Reproduction

```typescript
import { MikroORM } from '@mikro-orm/sqlite';
import {
  PrimaryKey,
  ManyToOne,
  Ref,
  Collection,
  Property,
  Entity,
  t,
  OneToMany,
} from '@mikro-orm/core';

@Entity()
class Assignee {

  @PrimaryKey({ autoincrement: true, type: t.bigint })
  readonly id!: string;

  @ManyToOne(() => Slot, { ref: true })
  slot!: Ref<Slot>;

  @Property()
  email!: string;

}

@Entity()
class Slot {

  @PrimaryKey({ autoincrement: true, type: t.bigint })
  readonly id!: string;

  @OneToMany(() => Assignee, a => a.slot)
  assignees = new Collection<Assignee>(this);

  @OneToMany(() => Registration, r => r.slot)
  registrations = new Collection<Registration>(this);

  @Property()
  name!: string;

}

@Entity()
class Registration {

  @PrimaryKey({ autoincrement: true, type: t.bigint })
  readonly id!: string;

  @ManyToOne(() => Slot, { ref: true })
  slot!: Ref<Slot>;

}

describe('GH issue XXX', () => {
  let orm: MikroORM;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [Assignee, Slot, Registration],
      dbName: ':memory:',
    });
    await orm.schema.refreshDatabase();

    /* Create data */
    const slot1 = orm.em.create(Slot, { name: 'slot1' });
    const slot2 = orm.em.create(Slot, { name: 'slot2' });

    const assignee1 = orm.em.create(Assignee, { email: 'slot1@user.com', slot: slot1 });
    const assignee2 = orm.em.create(Assignee, { email: 'slot2@user.com', slot: slot2 });

    const registration = orm.em.create(Registration, { slot: slot1 });
    await orm.em.flush();
    orm.em.clear();
  });

  afterAll(() => orm.close(true));

  test('reschedule registration from slot1 to slot2 (lazy loading assignees)', async () => {
    expect.assertions(2);

    const registration = await orm.em.findOneOrFail(Registration, { slot: { name: 'slot1' } }, { populate: ['slot'] });
    const slot2 = await orm.em.findOneOrFail(Slot, { name: 'slot2' }, { populate: ['registrations'] });

    const slot1 = registration.slot.$;

    registration.slot.set(slot2);
    await orm.em.persistAndFlush(registration);

    expect(registration.slot.id).toEqual(slot2.id);

    await orm.em.populate(registration, ['slot.assignees']);
    await orm.em.populate(slot1, ['assignees']);

    expect(registration.slot.id).toEqual(slot2.id);
  });

  test('reschedule registration from slot1 to slot2 (eager loading assignees)', async () => {
    const registration = await orm.em.findOneOrFail(Registration, { slot: { name: 'slot1' } }, { populate: ['slot.assignees'] });
    const slot2 = await orm.em.findOneOrFail(Slot, { name: 'slot2' }, { populate: ['registrations', 'assignees'] });

    const slot1 = registration.slot.$;

    registration.slot.set(slot2);
    await orm.em.persistAndFlush(registration);

    expect.assertions(2);
    slot1.assignees.getItems().forEach(assignee => expect(assignee.slot.id).toEqual(slot1.id));
    slot2.assignees.getItems().forEach(assignee => expect(assignee.slot.id).toEqual(slot2.id));
  });
});

```

### What driver are you using?

None

### MikroORM version

5.9.4

### Node.js version

v18.16.1

### Operating system

Mac OS Sonoma 14.1.2 (23B92)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Workaround is to use `ref` (or in general, create the reference from the new target entity instead of using `set` on the old one):

```diff
-registration.slot.set(slot2);
+registration.slot = ref(slot2);
```

(helps with both tests)

**Comment by B4nan** [comment]
I am actually thinking it might be a good idea to make the `Reference.set` method private, and enforce the usage I suggested above. This feels like a wontfix, as by using the `set` method, you change the wrapped entity, but the references also hold identity, so this might have side effects - which I believe is happening in your repro too. The reference to the `Reference` class stays somewhere and messes up things.

**Comment by xmajzel** [comment]
I understand, it makes sense to me, thanks for the solution!

I've seen usage of Reference.set() in the docs (https://github.com/mikro-orm/mikro-orm/blob/master/docs/docs/type-safe-relations.md), which probably should be also updated (search for `book.author.set(new Author(...));`).

**Comment by B4nan** [comment]
> I've seen usage of Reference.set() in the docs ([master/docs/docs/type-safe-relations.md](https://github.com/mikro-orm/mikro-orm/blob/master/docs/docs/type-safe-relations.md?rgh-link-date=2023-12-14T07%3A46%3A13Z)), which probably should be also updated (search for book.author.set(new Author(...));).

Thanks, forgot about that, addressed here:

https://github.com/mikro-orm/mikro-orm/commit/f845bfd68bc29bf46193705e6fba0ae5200c1c22?w=1
