### ISSUE TITLE
MySQL Order By `*_NULLS_(LAST|FIRST)` incorrect syntax

### ISSUE THREAD

**Issue by kpervin** [mikro-orm/mikro-orm#5004]
### Describe the bug

When using `orderBy` in a find operation, using `ASC_NULLS_LAST` or equivalent will insert the syntax `order by ... asc nulls last`. This is incorrect syntax.

If we have a table

```sql
CREATE TABLE foo
(
  id            INT UNSIGNED AUTO_INCREMENT
    PRIMARY KEY,
  text          VARCHAR(255) NOT NULL,
  optional_text VARCHAR(255) NULL,
);
```

Then to sort nulls on `optional_text`, we need to do the following:

| Operation        | Syntax                                                   |
|------------------|----------------------------------------------------------|
| ASC NULLS FIRST  | `order by optional_text is not null, optional_text`      |
| ASC NULLS LAST   | `order by optional_text is null, optional_text`          |
| DESC NULLS FIRST | `order by optional_text is not null, optional_text desc` |
| DESC NULLS LAST  | `order by optional_text is null, optional_text desc`     |

### Reproduction

https://github.com/kpervin/MikroORM-Issue-Example-Repo/blob/c446d1fd0b313da3c1ccb97915fc6a2fd09003ae/test/mysql-order-by-issue.spec.ts#L49-L73

### What driver are you using?

@mikro-orm/mysql

### MikroORM version

5.9.4

### Node.js version

20.9.0

### Operating system

Ubuntu 20.04 LTS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Looks like the support was added only for postgres (#677), it's indeed not working in mysql.

**Comment by kpervin** [comment]
> Looks like the support was added only for postgres (#677), it's indeed not working in mysql.
> 
> (and in a way, this is postgres only feature, what you want can be achieved explicitly)

Is there a way to do this using EntityManager? Or can this only be done by the query builder?

**Comment by kpervin** [comment]
I'm willing to put in a PR if need be. I know I've opened a few issues with no follow up. Been a bit busy at work and home to find time to put in the work.

**Comment by kpervin** [comment]
@B4nan found that this works in the meantime, while raw sql fragments did not:

```ts
await orm.em.find(
      Foo,
      {},
      {
        orderBy: [{ optionalText: "IS NOT NULL" }, { optionalText: "asc" }],
      },
    );
```
