### ISSUE TITLE
Expose `FilterValue` type

### ISSUE THREAD

**Issue by JustLitio** [mikro-orm/mikro-orm#5011]
**Is your feature request related to a problem? Please describe.**
We are trying to implement a builder pattern to create a `FilterQuery` structure. In each phase of the builder, we need to use the type `FilterValue`, but this type is not exposed.

**Describe the solution you'd like**
`FilterValue` is an exposed type

**Describe alternatives you've considered**
We've explored the other types (`ObjectQuery` i.e.) related to this problem but we haven't found a viable option

**Comment by rubiin** [comment]
I have just created a pr for this. You should be able to use this once its merged
