### ISSUE TITLE
:ref enforces select-in strategy for 1:m relationships

### ISSUE THREAD

**Issue by darkbasic** [mikro-orm/mikro-orm#5013]
### Describe the bug

With `joined` strategy:
```ts
const site = await orm.em.fork().findOneOrFail(Site, { id: 1 }, { populate: ["matches:ref"] });
```
```
[query] select "s0".* from "site" as "s0" where "s0"."id" = 1 limit 1 [took 1 ms, 1 result]
[query] select "m0"."id", "m0"."site_id" from "match" as "m0" where "m0"."site_id" in (1) [took 1 ms, 12 results]
```

> could be some strategy override, there are places where select-in is enforced (e.g. because of cycles or populate: * and recursion)

### Reproduction

Not needed.

### What driver are you using?

pg

### MikroORM version

v6

### Node.js version

20

### Operating system

Linux

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by darkbasic** [comment]
Many to many seems to be working:

```ts
const sports = await orm.em.fork().find(Sport, { id: 1 }, { populate: ["sites:ref"] });
```
```
[query] select "s0".*, "s1"."sport_id" as "s1__sport_id", "s1"."site_id" as "s1__site_id" from "sport" as "s0" left join "site_sports" as "s1" on "s0"."id" = "s1"."sport_id" where "s0"."id" = 1 [took 1 ms, 2 results]
```

But one to many still doesn't:
```ts
const site = await orm.em.fork().findOneOrFail(Site, { id: 1 }, { populate: ["matches:ref"] });
```
```
[query] select "s0".* from "site" as "s0" where "s0"."id" = 1 limit 1 [took 1 ms, 1 result]
[query] select "m0"."id", "m0"."site_id" from "match" as "m0" where "m0"."site_id" in (1) [took 1 ms, 12 results]
```

**Comment by darkbasic** [comment]
Not supporting `ref` for one to many would be fine, but we should either error out when used or take the standard path which leads to the default join strategy.

**Comment by B4nan** [comment]
I guess we should just support it the way it should work for 1:m too - doing a partial join selecting only the PK of the target. That's what the user wants based on the query, and we can easily do that (lets put aside whether is a good idea or not for the user, it still has some value to select just one column instead of everything).
