### ISSUE TITLE
Feature: Entity Generator Custom Filename 

### ISSUE THREAD

**Issue by mboudreau** [mikro-orm/mikro-orm#5026]
**Is your feature request related to a problem? Please describe.**
When creating my entities, I'd like to follow the node/javascript standard of using kebab-case for all filenames, instead of using the [class name as the filename as is currently in Entity Generator](https://github.com/mikro-orm/mikro-orm/blob/master/packages/entity-generator/src/EntityGenerator.ts#L66).

**Describe the solution you'd like**
In the naming strategy API, there should be a function that specifies what the filename should be based on the table/entity name

**Describe alternatives you've considered**
Currently, I have a script that generates the entities, then rename the files using a regex with the `rename` utility in ubuntu

**Comment by mboudreau** [comment]
@B4nan really appreciate how quick you got this out, but this is only adding the filename function to the generator - which is amazing in itself - but it's not adding it to the `NamingStrategy` API which is what will make it much easier to use for CLI generation as you can set the strategy in the config.

Thank you so much for all the work you do :)

**Comment by B4nan** [comment]
> as you can set the strategy in the config.

You can set the new `fileName` option also in config.

https://github.com/mikro-orm/mikro-orm/commit/4ebc8e3665d7c75788b51a6da59575ccff19f612?w=1#diff-01a043e67776caef68ead04538e8cccac0cdb40e699b002234bf35613f1cff14R583

**Comment by mboudreau** [comment]
Great, I need to get my eyes checked it seems :|
