### ISSUE TITLE
Feature: `findOne` function to return `undefined` instead of `null` (low priority)

### ISSUE THREAD

**Issue by mboudreau** [mikro-orm/mikro-orm#5036]
**Is your feature request related to a problem? Please describe.**
This is just me being nitpicky because I absolutely despise `null` in javascript/typescript.  I understand that databases works with nulls, but undefined is the defacto standard and works better with things like `Partial` or optional operators, which null doesn't.

**Describe the solution you'd like**
In the configuration, if you could have an option that would set if it returns `undefined` instead of `null` for all your find functions, the same way that there's a setting for `undefined` for properties instead of nulls.

Actually, scratch that, a simpler way would be to have a `findOneOrUndefined` function.

**Describe alternatives you've considered**
Easy workaround is to do `(await em.find(...)) || undefined`, but it does add a lot of boilerplate.  Would be nice if we had something out of the box :)

**Additional context**
Low priority.  It's just a nice to have IMO.  Appreciate all the work you do.  If I had more time currently, I'd try to implement this myself.

**Comment by B4nan** [comment]
Not interested in doing this, I like the explicit `null` for `findOne`, returning `undefined` from methods is usually a sign of `void` so that's one reason why (but I have none that would be in favor of it). If you want to change my mind, I want to see an actual case this would make things better, not "I am being nitpicky", that's not an argument really :]

> Actually, scratch that, a simpler way would be to have a findOneOrUndefined function.

Definitely not interested in that, the EM interface is way too bloated already (with methods that actually have some importance), but feel free to create a custom base repository, there you can have your `findOneOrUndefined` method or anything else.

**Comment by mboudreau** [comment]
All good, I did create a custom `EntityRepository` to get this behavior in our codebase.  My argument for it is this: it breaks typescript typings, things like `Partial` or the optional operator `?` breaks with it.  Your typings, which normally would be something like:

```
interface UserResponse {
   user?:User;
   subscription?:UserSubcription;
}
```
Instead I need to specify `null` for each one instead:
```
interface UserResponse {
   user:User | null;
   subscriptions:UserSubcription | null;
}
```
which means that using something like `Partial<UserResponse>` will break typings, making the interface accept both `undefined` or `null`.  And lastly, [it's the recommended Best Practice by the Typescript team themselves](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#null-and-undefined) to use `undefined`, very explicitly at that: 

> Use undefined. Do not use null.

**Comment by B4nan** [comment]
> And lastly, [it's the recommended Best Practice by the Typescript team themselves](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#null-and-undefined) to use undefined, very explicitly at that:

Did you read that page from the top? :] It starts with **STOP READING IMMEDIATELY**, followed by **These are Coding Guidelines for Contributors to TypeScript. This is NOT a prescriptive guideline for the TypeScript community. These guidelines are meant for contributors to the TypeScript project's codebase. We have chosen many of them for team consistency. Feel free to adopt them for your own team.**.

**Comment by B4nan** [comment]
I just stumbled upon this article about some breaking changes in typeorm 0.3, and it quite nicely confirms my points about null vs undefined, as well as highlights one new problem they introduced (the missing where when you have an empty value in the filter) which MikroORM protects you from doing (and is also a common source of questions and confusion). Funny how they are doing these steps in 2023, I thought everybody was saying how mature the library is many years ago 🤣 

https://hackernoon.com/unexpected-discoveries-in-typeorm-0311
