### ISSUE TITLE
Feature: Disable logger colors from configuration (low priority)

### ISSUE THREAD

**Issue by mboudreau** [mikro-orm/mikro-orm#5037]
**Is your feature request related to a problem? Please describe.**
Maybe I'm being stupid, but I couldn't find/figure out how to disable colors from the configuration in 6.0.0-rc.3.  The [docs seems to only refer to setting environment variables](https://mikro-orm.io/docs/next/logging#disabling-colored-output).

**Describe the solution you'd like**
Having a property called `colors` in the configuration and setting it to `false` would be helpful.

**Describe alternatives you've considered**
Currently setting `process.env.MIKRO_ORM_NO_COLOR = "true";` where I set the configuration works for the time being, but seems cumbersome.  It's also global, which means if you have multiple mikro instances (like we do), it disables it for all of them.

**Comment by B4nan** [comment]
Next time start with using the search (let it be in the docs or on github) :]

**Comment by B4nan** [comment]
To be frank, I am not sure I want to proceed with this, what we have feels more than enough. Why would you want to disable colors for one ORM instance and not the other? This is a global option, it always will be. If you want to control it for one instance, you can toggle the env var only for that particular app context, so it's not like you cannot do what you want...

**Comment by mboudreau** [comment]
It just seems like a normal place to put configuration.  Everything else is configured using the config JSON, just this one thing is using an env var.  Just seems a bit jarring is all and I was kinda expecting to just be able to see the option in the autocomplete, but instead I had to search for it.  Not a big hassle, just out of sorts since everything else is done via the config...

**Comment by B4nan** [comment]
> just be able to see the option in the autocomplete

That's a good point. As I said, this is technically just about switching the env var internally, so very easy to implement.
