### ISSUE TITLE
nativeInsertMany fails with entity having a collection field

### ISSUE THREAD

**Issue by BrannJoly** [mikro-orm/mikro-orm#5038]
### Describe the bug

I'm trying to do a nativeInsertMany on an entity with a OneToMany collection.
I have tracked down the problem to knex.AbstractSqlDriver.nativeInsertMany

``` javascript

async nativeInsertMany(entityName, data, options = {}) {
        // ...
        const meta = this.metadata.find(entityName); //the metadata for my collection doesn't have an associated FieldName (it's a FK !)
      // ...
        data.forEach(row => Object.keys(row).forEach(k => set.add(k)));
        const props = [...set].map(name => meta?.properties[name] ?? { name, fieldNames: [name] });
        let fields = core_1.Utils.flatten(props.map(prop => prop.fieldNames)); // for my collection field, there is no fieldNames property and the returned value is thus undefined
        const duplicates = core_1.Utils.findDuplicates(fields);
        const params = [];
        if (duplicates.length) {
            fields = core_1.Utils.unique(fields); // we handle the duplicated but not the undefined ...
        }
        const tableName = meta ? this.getTableName(meta, options) : this.platform.quoteIdentifier(entityName);
        let sql = `insert into ${tableName} `;
         // this method fails for undefined values with  Cannot read properties of undefined (reading 'replace')
        sql += fields.length > 0 ? '(' + fields.map(k => this.platform.quoteIdentifier(k)).join(', ') + ')' : `(${this.platform.quoteIdentifier(pks[0])})`;

       // ....
       }


```

### Reproduction

create two classes (A has a field bs containing a collection of B)
``` javascript

@Entity({ tableName: 'bs' })
export class B {
  @PrimaryKey()
  id: IdType = uuidv4();
  
  @Property()
  v!: number;

  @ManyToOne({ entity: 'A' })
  @Index()
  a!: A;

}


@Entity({ tableName: 'as' })
export class A{
  @PrimaryKey()
  id: IdType = uuidv4();
  
  @Property()
  name!: string;

  @OneToMany(() => B, (item) => item.b)
  bs = new Collection<B>(this);
}
```

and then do a native insert many 

  ``` javascript
  await this.entityRepository
      .getEntityManager()
      .getDriver()
      .nativeInsertMany('A', data);
```

this fails with` Cannot read properties of undefined (reading 'replace')`. See explanation above.

this works fine if I remove the collection.

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

5.9.5

### Node.js version

18.16.0

### Operating system

osX

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
You should be using `em.insertMany()` if you want to put inside entity instances, the driver methods expect a POJO with only actual columns.

**Comment by B4nan** [comment]
Actually, what are you trying to do? Your repro is a bit unclear - using driver methods with entity instances is surely wrong, but even `em.insertMany()` won't handle any relations, it only represents single insert query, to flush a whole entity graph you'd have to use `persist` and `flush`.

**Comment by BrannJoly** [comment]
@B4nan thank you. This works as expected. 

I've got a follow-up issue though :  My insert request seems to be executed twice, once when I do em.insertMany(entities), and one when I do em.flush()

is this behavior normal ? is there something I can do? Feel free to let me know if you want me to open a separate issue in the q&a section
thanks

**Comment by B4nan** [comment]
I guess you are using `em.create()` right? It shouldn't behave like that, so complete repro for that welcome. 

`em.create` will call `em.persist` automatically, but when you use `em.insert/Many`, this record is automatically cleared:

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/EntityManager.ts#L1347
