### ISSUE TITLE
onUpdate runs on create?

### ISSUE THREAD

**Issue by jacobleesinger** [mikro-orm/mikro-orm#504]
**Describe the bug**
The `onUpdate` function that can be passed to `@Property` runs on create as well as on update. If a property with an `onUpdate` function is initialized with a value or also has an `onCreate` function, the value returned from the `onUpdate` function will immediately overwrite it.

**Expected behavior**
The `onUpdate` function only runs on update, not on create.
Initial values can be set on properties with `onUpdate` functions without being immediately overwritten.

**Versions**

| Dependency | Version |
| - | - |
| mikro-orm | 3.6.9 |

I'd be happy to submit a PR to fix this myself, just wanted to make sure this behavior is not intentional first.

**Comment by B4nan** [comment]
Yeah sure, send a PR.
