### ISSUE TITLE
add decorators to execute arbitrary SQL in migrations

### ISSUE THREAD

**Issue by BrannJoly** [mikro-orm/mikro-orm#5056]
**Is your feature request related to a problem? Please describe.**
I have triggers, stored procedures and views in my database, and I would love to leverage mikro orm's migrations to keep all my code ('including sql'), in my TS respository.

Currently I updated a migration created by mikro orm to add my triggers and views creation statements. this works fine.

However, to speed up the db schema creation process (notably for our CI), from time to time we remove all our migrations and restart from a clean slate using npx mikro-orm migration:create --initial
doing this will loses our custom creation codee, so we need to remember to reapply it manually.

Also, the code is hidden in a migration file. A custom decorator would be much better !

**Describe the solution you'd like**
a new decorator 
``` javascript
@ArbitrarySqlMigration({
 up : 'CREATE TRIGGER my_trigger etc ....', 
 down : 'drop trigger my_trigger' })
 });
```

**Describe alternatives you've considered**

I know the Index() decorator enables the execution of arbitrary sql code, but : 
- it's a ugly hack
- the code needs to be a one liner or mikro orm generates one sql command per line
- the down migration is not handled properly

**Comment by B4nan** [comment]
I am fine with support for triggers, but this feels a bit weird, so closing in favor of the other issue.
