### ISSUE TITLE
eager loading not working with nested populate using find query

### ISSUE THREAD

**Issue by dimitriSaplatkin** [mikro-orm/mikro-orm#5057]
### Describe the bug

When I call a find query with a populate then the eager loading is not working for the nested populated entity.
Let's say we have the following query:
```    
const authors = await orm.em.find(
      Author,
      { firstName: "Jon" },
      { populate: ["books", "books.genre"] },
    );
```
On the Genre entity there is another ManyToOne property with the option `eager: true`.

I would now expect this property is also populated. This case was working for us on mirko-orm v5.

You can see the full reproduciton in the provided github repo

### Reproduction

https://github.com/dimitriSaplatkin/reproduction

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6

### Node.js version

20

### Operating system

Ubuntu 23

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
This is actually caused by you passing the `books` hint twice, if you omit the first one it works fine:

```ts
const authors = await orm.em.find(
  Author,
  { firstName: 'Jon' },
  { populate: ['books.genre'] },
);
```

**Comment by dimitriSaplatkin** [comment]
Hmm okay. But it feels a bit like inconsistent behavior because it works for a findOne query in my example to populate 
```
{ populate: ["books", "books.genre"] },
```
So I would expect that it also should not work for a fineOne query

**Comment by B4nan** [comment]
I closed the issue with a fix, I guess you missed that? Otherwise I'd rather expect "thank you" instead of "hmm okay" :D

**Comment by dimitriSaplatkin** [comment]
Sorry, my bad. I didn't saw the fix. Thanks for fixing and Happy New Year 🎉.
