### ISSUE TITLE
Query Builder not working with Virtual Entity

### ISSUE THREAD

**Issue by co-sic** [mikro-orm/mikro-orm#5069]
### Describe the bug

I'm not sure if this is something that is intended to work, so feel free to close this issue if this is out of scope or not intended to work.
I have defined a Virtual entity with an expression and this is working fine if i query it through the entity manager. But if i create a query builder for this entity, it just treats the entity as a DB table and tries to select that (non-exsisten) table, ignoring the expression.
My current use case is, that i have an existing FilterQuery (which is dynamically generated) for a Virtual Entity. I know need to use this FilterQuery inside of the knex query builder for an complex aggregation query.

### Reproduction

https://github.com/co-sic/node-mikro-orm-playground

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.0.0-rc.3

### Node.js version

20.9.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
It's not supposed to work this way now, but maybe it could. And if not, we can at least add a validation there.
