### ISSUE TITLE
schema:update always has updates

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#507]
**Describe the bug**
schema:update always has updates.

Tried rebuilding the cache and that didn't fix things.

**Stack trace**
```
NODE_ENV=proxy mikro-orm schema:update -r --fk-checks
Config environment: proxy
Schema successfully updated

NODE_ENV=proxy mikro-orm schema:update -d --fk-checks
Config environment: proxy
alter table "Person" drop constraint if exists "Person_displayName_check";
alter table "Person" alter column "displayName" type varchar using ("displayName"::varchar);
alter table "Person" alter column "displayName" set default null;
alter table "Person" drop constraint if exists "Person_photoURL_check";
alter table "Person" alter column "photoURL" type varchar using ("photoURL"::varchar);
alter table "Person" alter column "photoURL" set default null;
```

**Expected behavior**
Shouldn't see anything.

**Versions**

| Dependency | Version |
| - | - |
| mikro-orm | 3.6.10 |
| your-driver | postgres |

**Comment by lookfirst** [comment]
fyi, removing `default: null` from:

```
	@Property({columnType: 'varchar', nullable: true})
```

Fixed it.

**Comment by B4nan** [comment]
Did you really test this with 3.6.10? I see in the email you reported it on older version and there were fixes related to schema generator recently. 

Anyway, i need to see entities, its not that simple (not happening always) - there are tests for this, and they pass. It might be also connected to the db version (not driver or connector, but the actual db).

**Comment by B4nan** [comment]
Ok got it replicated, it's really because of the `default: null` (although it is not needed, as nullable columns already default to `null`, but agreed this should be covered).

**Comment by lookfirst** [comment]
Yea, I went back and tested it after upgrading. =)
