### ISSUE TITLE
Loaded<> type does not produce a TypeScript error when nested relations of the same type are not correctly populated

### ISSUE THREAD

**Issue by grigmag** [mikro-orm/mikro-orm#5070]
### Describe the bug

Hi, I experienced a case where I would expect that constraining a parameter using the Loaded<> type would be stricter and would produce a TypeScript error, but no such error is produced. I understand this might be a limitation of TypeScript or quite difficult to resolve.

Assume the following entities:

```ts
@Entity()
export class Child {}

@Entity()
export class Parent1 {
  @OneToOne(() => Child, { ref: true })
  child!: Ref<Child>;
}

@Entity()
export class Parent2 {
  @OneToOne(() => Child, { ref: true })
  child!: Ref<Child>;
}

@Entity()
export class Grandparent {
  @ManyToOne(() => Parent1, { ref: true })
  parent1!: Ref<Parent1>;

  @ManyToOne(() => Parent2, { ref: true })
  parent2!: Ref<Parent2>;
}
```

Then we do
```ts
const grandparent = await em.findOne(
    Grandparent,
    {},
    {
      populate: ['parent1.child', 'parent2'],
    },
  );

  const func = (
    param: Loaded<Grandparent, 'parent1.child' | 'parent2.child'>,
  ) => param;

  func(grandparent);
```

**Expected behavior**
Calling `func(grandparent)` should produce a TypeScript error because `grandparent` does not have `'parent2.child'` populated.

**Actual behavior**
No error is produced.

### Reproduction

I think the issue is self-explanatory, but let me know if a reproduction repo would be helpful.

### What driver are you using?

None

### MikroORM version

5.8.8 (also tested 5.9.7 in Code Sandbox)

### Node.js version

Node 18.15.0, TypeScript 5.2.2

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Try v6, many types including the `Loaded` type are reworked there and this use case works fine.

<img width="1022" alt="image" src="https://github.com/mikro-orm/mikro-orm/assets/615580/115a3263-d9d2-4c53-9d5e-721edbb3db76">
