### ISSUE TITLE
Automatic Conversion of TypeScript Optionals to Database Nullables with ts-morph

### ISSUE THREAD

**Issue by mwaeckerlin** [mikro-orm/mikro-orm#5081]
Description:
When using `ts-morph` with MikroORM, there currently isn't an automatic conversion of TypeScript optional properties (e.g., `property?: type`) to database nullable fields. This behavior is somewhat counterintuitive, especially when `ts-morph` is employed to tightly integrate TypeScript code with the database schema.

In typical use cases, a TypeScript optional is logically equivalent to a nullable field in the database. Therefore, it would be expected that `ts-morph` would automatically interpret a TypeScript optional as `nullable: true` in the database schema.

Current Behavior:
Currently, when defining an optional property in a TypeScript entity (like `user?: string`), MikroORM does not automatically set this field as nullable in the database unless explicitly defined with `{ nullable: true }`. This requires additional boilerplate and can lead to discrepancies between the TypeScript model and the database schema.

Expected Behavior:
When using `ts-morph`, optional properties in TypeScript entities should automatically be treated as nullable in the database schema. This change would enhance the developer experience by reducing boilerplate and aligning the database schema more closely with the TypeScript model.

Steps to Reproduce:
1. Define an entity with an optional property in TypeScript using `ts-morph` with MikroORM.
2. Generate a migration.
3. Observe that the optional property is not set as nullable in the database schema unless explicitly specified.

Suggested Solution:
Implement an automatic mapping in MikroORM when using `ts-morph` that interprets TypeScript optional properties as nullable fields in the database. This would align the database schema more closely with the TypeScript definitions and reduce the need for manual specification of nullability.

**Comment by B4nan** [comment]
This is not true, the [optionality is respected](https://github.com/mikro-orm/mikro-orm/blob/master/packages/reflection/src/TsMorphMetadataProvider.ts#L87-L89). Please provide a complete reproduction.

**Comment by B4nan** [comment]
How does your ORM config look like? Maybe you are setting up the `basePath` dynamically? That's a common source of bugs, I'd suggest to keep the default on that which is `process.cwd()`.

**Comment by mwaeckerlin** [comment]
I have split the configuration, so that all code common to all microservices is in a library, and only minimal code must be generated by the nest -template:

e.g.:

local in the service:

```
import {MikroOrmConfig} from "@scrypt-swiss/nest"
import {Trade} from './src/trades/entities/trade.entity'
import {Order, ProfitAndLoss} from './src/orders/entities/order.entity'
import {Market} from './src/market/entities/market.entity'
import {Security} from './src/market/entities/security.entity'
import {Quote} from './src/market/entities/quote.entity'

export default MikroOrmConfig(__dirname, 'TRADING', Quote, Security, Market, Order, Trade, ProfitAndLoss)
```


Global in a library:

```
import 'dotenv/config'
import {TextType, Type} from '@mikro-orm/core'
import {CachedMetadataProvider} from './CachedMetadataProvider'
import path from 'path'

let metadataProvider
if (process.env.NODE_ENV === 'production') {
  metadataProvider = CachedMetadataProvider
} else {
  const {TsMorphMetadataProvider} = require('@mikro-orm/reflection')
  metadataProvider = TsMorphMetadataProvider
}

class TimestampTZType extends Type<Date | string, Date | string> {
  convertToDatabaseValue(value: Date | string): string {
    if (value instanceof Date) return value.toISOString()
    return new Date(value).toISOString()
  }

  convertToJSValue(value: Date | string): Date {
    if (value instanceof Date) return value
    return new Date(value)
  }

  getColumnType(): string {
    return 'timestamptz'
  }
}

export const MikroOrmConfig = (localPath, NAME, ...args) => ({
  entities: args,
  entitiesTs: args,
  type: process.env[NAME + '_DB_TYPE'] ?? 'postgresql',
  dbName: process.env[NAME + '_DB_NAME'] ?? 'database',
  host: process.env[NAME + '_DB_HOST'],
  port: process.env[NAME + '_DB_PORT'] ? +process.env[NAME + '_DB_PORT']! : null,
  user: process.env[NAME + '_DB_USER'],
  password: process.env[NAME + '_DB_PASSWORD'],
  charset: 'UTF-8', // never change!
  timezone: 'GMT', // never change!
  cache: {enabled: true},
  metadataProvider,
  discovery: {
    getMappedType(type, platform) {
      if (type === 'datetime') return Type.getType(TimestampTZType) // Date → timestamp
      if (type === 'string') return Type.getType(TextType) // string → text
      return platform.getDefaultMappedType(type ?? 'undefined')
    },
    //disableDynamicFileAccess: true
  },
  migrations: {
    path: path.join(localPath, './migrations'),
  
  }
})
```

I'm using it in local `npm start` and in docker with `nexe` in `Dockerfile`:

```
ARG DOCKER_REPOSITORY
ARG DOCKER_TAG
FROM ${DOCKER_REPOSITORY}/base:${DOCKER_TAG:-latest} AS build
COPY --chown=${BUILD_USER} . backends/trading
RUN npm install
RUN npx nx run trading:build
ENV NODE_ENV 'production'
RUN find -name node_modules -prune -exec rm -rf {} \;
RUN npm install
WORKDIR /app/backends/trading
RUN nexe --build --python=$(which python3) -r "temp" -r "dist/migrations" -o app dist/src/main.js

FROM mwaeckerlin/nodejs as production
EXPOSE 4001
COPY --from=build /app/backends/trading/app /app/app
CMD ["/app/app", "--trace-uncaught"]
```

I had to add `localPath` because of `npm start`: After split of the configuration to the library, `migration.up()` in `npm start` read the migration from `./migration/file.ts` instead of `./dist/migration/file.js`.

Now applying the migration works when running with `npm start` and when running in docker.

But now, when running `mikro-orm migration:create`, then the migration `file.ts` is created in `./dist/migration/file.js`

I am still looking for a solution.

For entities, there are to variables, `entities` and `entitiesTs`, but not for `migration.path`…

**Comment by mwaeckerlin** [comment]
Addendum: Before splitting the config file, `./migrations` was good for all…

**Comment by B4nan** [comment]
That `__dirname` is exactly what I was referring to as dynamic, I'd suggest not using that, as the value changes when you run things in production mode (in `dist` folder).

**Comment by mwaeckerlin** [comment]
Test:

Running `migrations:create`:
> __dirname = /home/marc/git/scrypt/backends/trading/dist
> process.cwd() = /home/marc/git/scrypt/backends/trading

Here `__dirname` is wrong and `process.cwd()` is wrong.

But running in docker:
> __dirname = /app/dist
> process.cwd() = /app

Here `__dirname` is correct and `process-cwd()` is wrong.

Same when running `npm run start`:

> __dirname = /home/marc/git/scrypt/backends/trading/dist
> process.cwd() = /home/marc/git/scrypt/backends/trading

So `__dirname` is correct at runtime and wrong in cli; `process.cwd()` just the other way round… :-(

So I don't see a solution.

For entities, there is a `entities` and `entitiesTs` antry. For migrations, it needs the same: a `migrations` and a `migrationsTS` that's used to generate the TS files in the CLI.

Or what should be the solution?

**Comment by mwaeckerlin** [comment]
Test:

Running `migrations:create`:
> __dirname = /home/marc/git/scrypt/backends/trading/dist
> process.cwd() = /home/marc/git/scrypt/backends/trading

Here `__dirname` is wrong and `process.cwd()` is wrong.

But running in docker:
> __dirname = /app/dist
> process.cwd() = /app

Here `__dirname` is correct and `process-cwd()` is wrong.

Same when running `npm run start`:

> __dirname = /home/marc/git/scrypt/backends/trading/dist
> process.cwd() = /home/marc/git/scrypt/backends/trading

So `__dirname` is correct at runtime and wrong in cli; `process.cwd()` just the other way round… :-(

So I don't see a solution.

For entities, there is a `entities` and `entitiesTs` antry. For migrations, it needs the same: a `migrations` and a `migrationsTS` that's used to generate the TS files in the CLI.

Or what should be the solution?

**Comment by B4nan** [comment]
As I said, `__dirname` is bad for this use case, as it reflects the folder you execute the file in (the file that evaluates the `__dirname` - your own file - the one that is inside `src` for source and `dist` for compiled). Unlike `process.cwd()`, that one will keep the value regardless of this, of course, unless you execute inside `dist` folder.

> For entities, there is a entities and entitiesTs antry. For migrations, it needs the same: a migrations and a migrationsTS that's used to generate the TS files in the CLI.

It already works that way: https://mikro-orm.io/docs/migrations#running-migrations-in-production

> Or what should be the solution?

The solution is not using `__dirname`, or even better - understanding what it does so you can use it properly (if you really really want to, but IMO you shouldn't).

**Comment by mwaeckerlin** [comment]
That looks like a solution. Unfortunately, the same parameter `pathTs` is missing in the documentation here (where I was looking for): https://mikro-orm.io/docs/configuration#migrations
