### ISSUE TITLE
Improve AbstractNamingStrategy to get access to table schema

### ISSUE THREAD

**Issue by mazyvan** [mikro-orm/mikro-orm#5084]
**Is your feature request related to a problem? Please describe.**

Yes, currently there's no way to generate entities for tables with the same name but belonging to different schemas. In Postgres you can create schemas and a table a can exist in 2 different schemas but if you try to generate entities for all the tables in your database you'll get name collisions

**Describe the solution you'd like**

I noticed there's this naming strategy thing I can use to generate names prefixed by schema that way entities will truly be unique

**Describe alternatives you've considered**

I considered having a map and running entities generate for different entities and storing the resulting files in different directories. but that's not ideal I think a more scalable solution is to support entities generation names to be made according the schema they belong 

Another alternative is to add a new option `skipSchemas` to the `entityGenerator.generate()` method to later generate the schema separately but with a class prefix. similar to the `skipTables` or `skipColumns` that already exist (not ideal tho)

**Comment by B4nan** [comment]
Not sure I follow here, entity generator already supports multiple schemas and will generate entities from all accessible schemas in postgres. The method that looks for existing tables is using [this SQL](https://github.com/mikro-orm/mikro-orm/blob/2bd612ec70d73bf7f5e6e5d70e2c7259e8d9c90b/packages/postgresql/src/PostgreSqlSchemaHelper.ts#L20), which is not limited to a specific schema (it only ignores some system schemas and those you specify in the config.

Here is an example from the tests, the `label2_tests` table is defined is `label_schema` schema. The schema is [here](https://github.com/mikro-orm/mikro-orm/blob/master/tests/postgre-schema.sql#L73), and generated entity [here](https://github.com/mikro-orm/mikro-orm/blob/master/tests/features/entity-generator/__snapshots__/EntityGenerator.postgres.test.ts.snap#L322). Looks like this is the only test we have, but the code should be already in place. So if you have such an issue, please provide a complete reproduction (in this case a complete sql schema dump is enough probably). 

> Another alternative is to add a new option skipSchemas to the entityGenerator.generate() method to later generate the schema separately but with a class prefix. similar to the skipTables or skipColumns that already exist (not ideal tho)

In fact, this is already supported, its just not configurable on the entity generator level, its in the `schemaGeneartor.ignoreSchema`, as that is what drives the schema introspection.

**Comment by B4nan** [comment]
> Yes, currently there's no way to generate entities for tables with the same name but belonging to different schemas. In Postgres you can create schemas and a table a can exist in 2 different schemas but if you try to generate entities for all the tables in your database you'll get name collisions

Reading this again, I guess I understand what you mean now. The `getClassName` method is used to get the generated entity name, but you won't get the current schema name in its parameters, and it will produce the same name for two tables with the same name (regardless of the schema).

**Comment by mazyvan** [comment]
@B4nan I was looking at your commit. This is awesome man, highly appreciated 🚀 !
I know there is not much use of postgres schemas out there, but those of us who are in big projects will appreciate it a lot
