### ISSUE TITLE
Migrations not working in CLI

### ISSUE THREAD

**Issue by peschee** [mikro-orm/mikro-orm#5087]
### Describe the bug

I cannot get the basic migrations CLI command to work. It fails with the following error when running `npx mikro-orm-esm migration:create --initial`:

```
Error: Migrator extension not registered.
    at MikroORM.getMigrator (mikro-orm-6-migrations/node_modules/@mikro-orm/core/MikroORM.js:220:15)
    at Function.handleMigrationCommand (mikro-orm-6-migrations/node_modules/@mikro-orm/cli/commands/MigrationCommandFactory.js:84:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Reproduction

https://github.com/peschee/mikro-orm-6-postgres-migrations-test

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.0.1

### Node.js version

20.10.0

### Operating system

MacOS 14.2.1 (23C71)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
You need to register the migrator extension

https://mikro-orm.io/docs/upgrading-v5-to-v6#orm-extensions

**Comment by B4nan** [comment]
Will mention this in the migrations section too, now its only in the upgrading and [getting started](https://mikro-orm.io/docs/guide/project-setup#migrations) guides.

**Comment by peschee** [comment]
Cool! This commit fixes it in the repro repo: https://github.com/peschee/mikro-orm-6-postgres-migrations-test/commit/ba8a7ca1a19a5062ab13de3bec6453baf65c7df7#diff-93c90c8b17ef60f13197d97c1a5ff29c8da9d5de0c713c337b1c4b1e3a6f5c71
