### ISSUE TITLE
Unknown column 'expression' in 'field list'

### ISSUE THREAD

**Issue by hooliy** [mikro-orm/mikro-orm#5091]
### Describe the bug

```yarn mikro-orm schema:fresh  -r ```

Error: select table_name as table_name, nullif(table_schema, schema()) as schema_name, index_name as index_name, non_unique as non_unique, column_name as column_name, expression as expression
        from information_schema.statistics where table_schema = database()
        and table_name in ('book')
        order by schema_name, table_name, index_name, seq_in_index - Unknown column 'expression' in 'field list'

### Reproduction

no

### What driver are you using?

@mikro-orm/mysql

### MikroORM version

@mikro-orm/cli@6.0.1

### Node.js version

v20.5.1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Sounds like you are using an old MySQL version, we test with MySQL 8 only. If you are using MySQL 5.7, you should upgrade, it already reached the end of life a few months ago.

**Comment by hooliy** [comment]
> Sounds like you are using an old MySQL version, we test with MySQL 8 only. If you are using MySQL 5.7, you should upgrade, it already reached the end of life a few months ago.

MySQL version: 8.0.2-dmr

**Comment by B4nan** [comment]
Then try upgrading, not sure what `dmr` means, but based on mysql website, v8.0.2 is ~7 years old, so pretty dated as well.

https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-2.html

**Comment by B4nan** [comment]
Looking at [this](https://dev.mysql.com/doc/refman/8.0/en/information-schema-statistics-table.html), you will need MySQL v8.0.13 is newer (that version is also more than 5 years old btw).

**Comment by hooliy** [comment]
> Looking at [this](https://dev.mysql.com/doc/refman/8.0/en/information-schema-statistics-table.html), you will need MySQL v8.0.13 or newer (that version is also more than 5 years old btw).
> 
> edit: let's see how common this will be, we could make it conditional, just like we handle support for check constraints

Thank you. After testing, there are no bugs in MySQL v8.0.13.

**Comment by sheyDev** [comment]
Please make this optional. We can't upgrade our production DBs
