### ISSUE TITLE
Query with new collection operators is not working on a nested query 

### ISSUE THREAD

**Issue by co-sic** [mikro-orm/mikro-orm#5099]
### Describe the bug

```ts
class Publisher {
   @OneToOne()
   owner: Author;
}

class Author {
   @OneToMany(() => Book, (book) => book.author)
   books = new Collection<Book>(this);
}

class Book {
   @Property()
   title: string;

   @ManyToOne()
   author: Author;
}

em.find(Publisher, {
   owner: {
      books: {
         $some: {
            title: "Book 2",
         },
      },
    },
});
```
This query gives the following Error: `Error: Trying to join 'books', but 'books' is not a defined relation on Publisher.`.
If i do the query directly on the Author with the some condition on books, it works fine.

### Reproduction

https://github.com/co-sic/node-mikro-orm-playground

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.0.1

### Node.js version

20.9.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by co-sic** [comment]
Thanks!

**Comment by piotr-cz** [comment]
My guess is that you can only use relationships that are some levels deep
