### ISSUE TITLE
Add support for raw() to orderBy

### ISSUE THREAD

**Issue by bozorgmehr96** [mikro-orm/mikro-orm#5110]
**Is your feature request related to a problem? Please describe.**
The only reason I'm using query builder now, is because of lack of this feature.

**Describe the solution you'd like**
Add support to use raw() as orderBy object keys, like what we do now in the where object.
```ts
await em.find(
  User,
  { [raw('similarity("name", ?)', [searchTerm])]: { $gte: 0.3 } },
  {
    orderBy: {
      [raw('similarity("name", ?)', [searchTerm])]: QueryOrder.DESC,
    },
  },
);```

**Comment by B4nan** [comment]
EM is capable of the same things as QB already, it's actually all handled on the QB level.

Please provide a complete repro for this. I got a similar report on slack, so some issue is surely there.

**Comment by B4nan** [comment]
I couldn't find any existing tests for this, weird, I am sure we have some. But that kinda confirms it can be buggy :] 

This is the part that handles it btw:

https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/query/QueryBuilderHelper.ts#L613

(again, `em.find` is not doing anything special, it uses QB abstraction for all of this - so if you can do something with QB, you can surely do the same with EM)

**Comment by bozorgmehr96** [comment]
I think it's buggy when we use the `populate` option on find methods or QB's `joinAndSelect()` methods.
I'm testing it right now and will come back with more details.

**Comment by bozorgmehr96** [comment]
using QB everything works until we use joinAndSelect() methods:

w/o `leftJoinAndSelect()`
```ts
em
  .qb(User, 'u')
  .select('*')
  .where({
    [raw((alias) => 'similarity("u"."name", ?)', [search])]: { $gte: 0.3 }
  })
  .orderBy({
    [raw((alias) => 'similarity("u"."name", ?)', [search])]: QueryOrder.DESC_NULLS_LAST,
  })
  .limit(100)
  .offset(0);
```
generated query:
```sql
select "u".*
from "users" as "u"
where similarity("u"."name", 'john') >= 0.3
order by similarity("a"."name", 'john') desc nulls last
limit 100
```

w/ `leftJoinAndSelect()`
```ts
em
  .qb(User, 'u')
  .select('*')
  .leftJoinAndSelect('addresses', 'a')
  .where({
    [raw((alias) => 'similarity("u"."name", ?)', [search])]: { $gte: 0.3 }
  })
  .orderBy({
    [raw((alias) => 'similarity("u"."name", ?)', [search])]: QueryOrder.DESC_NULLS_LAST,
  })
  .limit(100)
  .offset(0);
```

```sh
"type": "Error",
      "message": "Expected 0 bindings, saw 1",
      "stack":
          Error: Expected 0 bindings, saw 1
              at replaceRawArrBindings (/home/mohammad/workbench/odin/node_modules/knex/lib/formatter/rawFormatter.js:27:11)
              at Ref.toSQL (/home/mohammad/workbench/odin/node_modules/knex/lib/raw.js:77:13)
              at Ref.toSQL (/home/mohammad/workbench/odin/node_modules/knex/lib/ref.js:35:18)
              at Ref.Target.toQuery (/home/mohammad/workbench/odin/node_modules/knex/lib/builder-interface-augmenter.js:9:21)
              at Ref.toString (/home/mohammad/workbench/odin/node_modules/knex/lib/raw.js:70:17)
              at QueryBuilder.wrapPaginateSubQuery (/home/mohammad/workbench/odin/node_modules/@mikro-orm/knex/query/QueryBuilder.js:1141:70)
              at QueryBuilder.finalize (/home/mohammad/workbench/odin/node_modules/@mikro-orm/knex/query/QueryBuilder.js:1072:18)
              at QueryBuilder.getKnexQuery (/home/mohammad/workbench/odin/node_modules/@mikro-orm/knex/query/QueryBuilder.js:460:14)
              at QueryBuilder.execute (/home/mohammad/workbench/odin/node_modules/@mikro-orm/knex/query/QueryBuilder.js:584:28)
              at QueryBuilder.getResultList (/home/mohammad/workbench/odin/node_modules/@mikro-orm/knex/query/QueryBuilder.js:629:32)
```

**Comment by B4nan** [comment]
>               at PostgreSqlDriver.buildPopulateOrderBy (/home/mohammad/workbench/odin/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:997:27)

Ok now I get it, it's caused by a rather recent refactor which came much later than the raw queries one, that's what broke it and is missing the support (and its value is inferred from the `orderBy` option by default).

**Comment by B4nan** [comment]
Reopening as the issue with `qb.joinAndSelect()` is still there, I only fixed the `populateOrderBy` one.

**Comment by rrrokhtar** [comment]
Is there any chance to have raw/sql on populating a field? since I am trying to make an order by query like the following: 
```sql
SELECT * FROM mytable WHERE id IN (3,2,1,4) ORDER BY FIELD(id,3,2,1,4)
```
so I can run 
```typescript
const ids = [3,2,1,4];
findOptions.orderBy = [
      { id: raw(`FIELD(id, ${ids .join(',')}) DESC`) },
];
```
If it is possible to provide the raw query right there? 

https://github.com/mikro-orm/mikro-orm/blob/6f678259b1fa1b89aa4e7ca27d3e2d66ff3a8da5/packages/knex/src/dialects/mysql/MySqlPlatform.ts#L114-L125

**Comment by rrrokhtar** [comment]
**Solution of last issue I had:**

modify the key of the sortBy like that:
```js
findOpts.orderBy = [
 { [raw(`FIELD(\`p0\`.\`id\`, ${ids.join(',')})`)]: 'ASC' },
]
```

______________________________
> @B4nan Please if you can help, appreciating that
> 
> Is there any chance to have raw/sql on populating a field? since I am trying to make an order by query like the following:
> 
> ```sql
> SELECT * FROM mytable WHERE id IN (3,2,1,4) ORDER BY FIELD(id,3,2,1,4)
> ```
> 
> so I can run
> 
> ```ts
> const ids = [3,2,1,4];
> findOptions.orderBy = [
>       { id: raw(`FIELD(id, ${ids .join(',')}) DESC`) },
> ];
> ```
> 
> If it is possible to provide the raw query right there?
> 
> https://github.com/mikro-orm/mikro-orm/blob/6f678259b1fa1b89aa4e7ca27d3e2d66ff3a8da5/packages/knex/src/dialects/mysql/MySqlPlatform.ts#L114-L125

sorry for bothering. feel free to ignore @B4nan
