### ISSUE TITLE
Change to key inline prevents using IN clause

### ISSUE THREAD

**Issue by ZeroUltimax** [mikro-orm/mikro-orm#5114]
### Describe the bug

**Describe the bug**
Mikro-ORM doesn't uses the IN predicate whenever your filter is an array of Primary Key Objects.

```js
em.fork.find(Assets, [ { id: "id1", orgId: "orgId1" }, { id: "id2", orgId: "orgId2" } ]);
```

translates to
```sql
select `a0`.* from `assets` as `a0` where ((`a0`.`id` = ? and `a0`.`orgId` = ?) or (`a0`.`id` = ? and `a0`.`orgId` = ?))
```
when it could instead translate to
```sql
select `a0`.* from `assets` as `a0` where (`a0`.`id`, `a0`.`orgId`) in ((?, ?), (?, ?))
```

### Reproduction

```ts
@Entity()
export class Assets {
  @PrimaryKey()
  id!: string;

  @PrimaryKey()
  orgId!: string;
}

em.fork.find(Assets, [ { id: "id1", orgId: "orgId1" }, { id: "id2", orgId: "orgId2" } ]);
```

### What driver are you using?

None

### MikroORM version

6.0.1

### Node.js version

20

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ZeroUltimax** [comment]
I tracked down the issue to this fix: https://github.com/mikro-orm/mikro-orm/commit/7212a53fddc8c7712d7b2ec1eba8df41ccdab0eb

It seems that the change to `inlinePrimaryKeyObjects` inadvertently broke it.

**Comment by B4nan** [comment]
What's wrong with the current approach? I recall one report that was actually mentioning the previous tuple approach was causing perf issues as it wasnt properly optmized (i think it was mysql).

**Comment by B4nan** [comment]
FWIW, I'd say your query should not produce a tuple comparison, for that you'd have to pass tuples:

```ts
em.find(Assets, [ ["id1", "orgId1", ["id2", "orgId2"] ]);
```

So unless you have an actual problem, I don't think this is something to fix.

**Comment by ZeroUltimax** [comment]
Thanks for the info about perf. I'm not immediately concerned with performance, but I think either way ( whether it's preferable to use "where-in-tuples" or "where-or-and-tuples" ), the allowed syntax is inconsistent.

For example, using these entities:
```ts
@Entity()
export class Assets {
  @PrimaryKey()
  id!: string;

  @PrimaryKey()
  orgId!: string;
}

@Entity()
export class Categories {
  @PrimaryKey()
  id!: number;

  @ManyToOne()
  assets!: Assets;
}
```

The two following queries will generate contradicting forms of SQL queries:
```ts
const queries = [ { id: "1", orgId: "1" }, { id: "2", orgId: "2" } ];
const categoryQuery = orm.em.createQueryBuilder(Categories).where({
  assets: [...queries],
});
const assetsQuery = orm.em.createQueryBuilder(Assets).where([...queries]);
console.log(categoryQuery.getQuery());
console.log(assetsQuery.getQuery());
```

Will produce those two SQL queries:
```sql
select `c0`.* from `categories` as `c0` where (`c0`.`assets_id`, `c0`.`assets_org_id`) in ( values (?, ?), (?, ?))
```
```sql
select `a0`.* from `assets` as `a0` where ((`a0`.`id` = ? and `a0`.`org_id` = ?) or (`a0`.`id` = ? and `a0`.`org_id` = ?))
```

**Comment by ZeroUltimax** [comment]
In my completely biased personal preference, I think the top level query
````ts
[ { id: "1", orgId: "1" }, { id: "2", orgId: "2" } ]
```
should also be resolve to using "where-in-tuple".

Fixing that is as easy as allowing the primary key inlining process to work as before https://github.com/mikro-orm/mikro-orm/commit/7212a53fddc8c7712d7b2ec1eba8df41ccdab0eb

Before that fix, `GroupOperator[key as string]` would return `undefined` when key was `undefined`.  I suggest this fix:
https://github.com/ZeroUltimax/mikro-orm/commit/3c8cd0edd0cd151fb772d4d87fb636e2093ad5ec

**Comment by B4nan** [comment]
i dont have that strong opinion, feel free to PR this if the change is not breaking existing tests (apart from query assertions that should be affected by this), worst case we can make this configurable (and consistent)

**Comment by B4nan** [comment]
I checked what tests your suggested change breaks, and it won't be that simple, at least one test is completely broken and fails to produce a valid query (namely [this one](https://github.com/mikro-orm/mikro-orm/blob/master/tests/issues/GH4220.test.ts#L52)).

**Comment by ZeroUltimax** [comment]
I agree. I've been familiarizing myself with the mechanisms for querying PKs, and how they're translated into queries.
For me, the confusion seems to be that the QueryHelper can't easily differentiate between a nested PKs, and a nested "in".

For example, if I query this ( ugly syntax, but "should" work ): `await orm.em.find(Chat, [1,[2,3]]);`, the query builder assumes `[2,3]` is a nested PK, but in this case, since `User` has a non-composite PK, it should be treated as a nested "in".

This is indirectly what happens to break now. `[{ owner: 1, recipient: [3, 6] }, { owner: 1, recipient: [4, 5] }]` gets reduced to `[ [ 1,  [3, 6] ], [ 1, [ 4, 5 ] ] ]`, where `[3, 6]` gets wrongly understood as a nested PK.

I'm still tinkering to fix this, and trying to do so with a small footprint.

**Comment by B4nan** [comment]
I will close this one as I am personally not interested in changing the behavior, but PR welcome if you find the right place to change and keep the tests green.
