### ISSUE TITLE
`type` not converted for non-ID properties with `forceEntityConstructor`

### ISSUE THREAD

**Issue by mjroeleveld** [mikro-orm/mikro-orm#5118]
### Describe the bug

I have found a reproduction for a previously created [discussion](https://github.com/mikro-orm/mikro-orm/discussions/5117). When using `forceEntityConstructor: true`, properties other than the primary key do not get converted to their `type`.

### Reproduction

```typescript
import { Entity, MikroORM, PrimaryKey, Property, Type } from '@mikro-orm/core';
import { SqliteDriver } from '@mikro-orm/sqlite';

class Value {
  protected readonly value: string;

  toString() {
    return this.value;
  }

  constructor(id: string) {
    this.value = id;
  }
}

class SimpleType extends Type<
  Value | undefined,
  string | undefined
> {
  constructor(
    private classRef: new (value: any) => Value,
  ) {
    super();
  }

  convertToDatabaseValue(
    value: Value | string | null | undefined,
  ): string | undefined {
    if (!value) {
      return undefined;
    }
    if (typeof value === 'string') {
      return value;
    }
    return value.toString();
  }

  convertToJSValue(
    value: Value | string | undefined,
  ): Value | undefined {
    if (!value) {
      return undefined;
    }
    return new this.classRef(
      typeof value === 'object' ? value.toString() : value,
    );
  }
}

@Entity()
export class File {
  @PrimaryKey({ type: new SimpleType(Value) })
  public readonly id: Value;

  @Property({ type: new SimpleType(Value) })
  public readonly uri: Value;

  constructor({ id, uri }: { id: Value; uri: Value }) {
    this.id = id;
    this.uri = uri;
  }
}

describe('Q&A', () => {
  let orm: MikroORM;

  beforeAll(async () => {
    orm = await MikroORM.init({
      forceEntityConstructor: true,
      driver: SqliteDriver,
      entities: [File],
      dbName: 'mirko-orm-test',
    });
    await orm.schema.dropSchema();
    await orm.schema.createSchema();
  });

  afterAll(async () => {
    await orm.close(true);
  });

  test(`Q&A`, async () => {
    const em = orm.em.fork();
    await em.persistAndFlush(
      new File({
        id: new Value('foo'),
        uri: new Value('bar'),
      }),
    );
    em.clear();
    const retrieved = await em.findOneOrFail(File, {
      id: new Value('foo'),
    });
    expect(retrieved.id).toBeInstanceOf(Value); // Passes
    expect(retrieved.uri).toBeInstanceOf(Value); // Doesn't pass
  });
});
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.0.2

### Node.js version

18

### Operating system

Mac

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Nice, thanks. Can you please remove the abstraction in your custom type to make the repro simpler?

**Comment by mjroeleveld** [comment]
Thanks a lot! 🙏🏻
