### ISSUE TITLE
Collection populated with itself when there is no items

### ISSUE THREAD

**Issue by adrien2p** [mikro-orm/mikro-orm#5119]
### Describe the bug

I am not sure but I d like to discuss one point in case something is going on there.

Basically, I have an entity which is an instance of an entity and the data. I am using `manager.assign(entity, data)` to assign the data and the entity has a collection property. 

In this scenario, the entity collection property is not initialized/dirty and we are not assigning anything to it, it is empty in both sides.
When calling the assign, we are at some point reaching the `assignCollection` from the `EntityAssigner`, this one is converting the `value` (being the empty collection) to an array before looping through the items. When it gets converted to an array, it returns an array with one item being the collection itself because of this line `return Array.isArray(data) ? data : [data];` (since it is not undefined or a set). Therefore, we are always adding an item to the collection resulting in an error `collection not initialized`.

I would have thought at this point, that the utils should, in case of a collection, use the items property or the items property should be passed to the utils, to be compared and used to be converted to an array.

Let me know if I am missing something or anything 👍 

For investigation purpose here are some screenshot from the EntityAssigned

See the following screenshot in order from the `EntityAssigner.assignCollection` method
<img width="1310" alt="Screenshot 2024-01-11 at 12 28 05" src="https://github.com/mikro-orm/mikro-orm/assets/25098370/f155c9eb-c7de-4394-aff0-f9317505ea63">
<img width="1330" alt="Screenshot 2024-01-11 at 12 28 25" src="https://github.com/mikro-orm/mikro-orm/assets/25098370/265420b5-c745-45d5-9a17-6fbaf61c53fc">
<img width="1577" alt="Screenshot 2024-01-11 at 12 29 00" src="https://github.com/mikro-orm/mikro-orm/assets/25098370/2ad86732-b74d-49c4-a3df-bc8634c8c622">

### Reproduction

- create an entity with a collection property
- retrieve the entity
- create a data object containing non collection properties
- call manager.assign(entity, data)
- observe that the collection contains an element being based on the collection itself

```ts
      @Entity()
      class Test {
        @PrimaryKey()
        id: string

        @Property()
        name: string

        @OneToMany(() => Items, (lineItem) => lineItem.test, {
          orphanRemoval: true,
        })
        items = new Collection<Items>(this)
      }

      @Entity()
      class Items {
        @PrimaryKey()
        id: string

        @Property()
        name: string

        @ManyToOne(() => Test, {
          onDelete: "cascade",
          fieldName: "test_id",
        })
        test!: Test
      }

      // This init mikro orm
      const MikroOrmWrapper = TestDatabaseUtils.getMikroOrmWrapper([
        Test,
        Items,
      ])

      await MikroOrmWrapper.setupDatabase()
      const manager = await MikroOrmWrapper.forkManager()

      const testEntity = manager.create(Test, {
        id: "test-1",
        name: "name-1",
      })
      await manager.persistAndFlush(testEntity)

      ///////////

      class TestRepository extends mikroOrmBaseRepositoryFactory(Test) {
        async update(
          data: { entity; update }[],
          context = {}
        ): Promise<Test[]> {
          const manager = this.getActiveManager<SqlEntityManager>(context)

          const entities = data.map(({ entity, update }) => {
            return manager.assign(entity, update)
          })

          return await super.update(entities, context)
        }
      }

      const repository = new TestRepository({ manager })

      // Reproduction

      const updatedEntity = await manager.transactional(async (txManager) => {
        const retrievedEntity = await txManager.findOne(Test, {
          id: "test-1",
        })

        await repository.update(
          [
            {
              entity: retrievedEntity,
              update: {
                name: "name-2",
              },
            },
          ],
          {
            transactionManager: txManager,
          }
        )

        const updatedEntity = await txManager.findOne(
          Test,
          {
            id: "test-1",
          },
          {
            populate: ["items"],
          }
        )

        return updatedEntity
      })

      const serializedEntity = await mikroOrmSerializer(updatedEntity, {
        populate: ["items"],
      })

      console.log(JSON.stringify(serializedEntity.items, null, 4))

      // output


// [
//   {
//     "id": [
//       [
//         {
//           "id": [
//             {
//               "test": {
//                 "id": "test-1",
//                 "items": [
//                   {}
//                 ],
//                 "name": "name-2"
//               }
//             }
//           ],
//           "test": {
//             "id": "test-1",
//             "items": [
//               {
//                 "id": [
//                   {}
//                 ]
//               }
//             ],
//             "name": "name-2"
//           }
//         }
//       ]
//     ],
//     "test": "test-1"
//   }
// ]
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

5.9.7

### Node.js version

18+

### Operating system

mac os

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Screenshots are not a reproduction (especially those that are only showing the symptoms, not the cause), I can't help with that, please provide complete reproduction as code.

**Comment by adrien2p** [comment]
Sorry for that, the SS was more for global description purpose. I ll provide you with a minimal code reproduction 👍

**Comment by adrien2p** [comment]
I ll continue the investigation on my side for now as with a simpler reproduction example I can't get it to reproduct it. I ll keep you in touch

**Comment by adrien2p** [comment]
I ve updated the reproduction example and logged the content of the collection property. Let me know if this is ok for you? I ve tried to do something as close as possible to our setup

**Comment by adrien2p** [comment]
I am sure that I must have missed a simple thing but I am not sure what here. The idea here is simply to update the entity with some values assigned to some scalar properties. and we do not touch the collections at this point. we don't get any issues elsewhere though, it is the first time that we are encountering this one

**Comment by adrien2p** [comment]
could it be link to calling assign with both argument being an Entity instance?

**Comment by adrien2p** [comment]
I am closing for now as It looks like that if both argument of assign are an entity then it leads to issues but if the second argument is just the data then it works. I let you decide if that is a an issue or not 👍 thanks for the great package ❤️
