### ISSUE TITLE
Incorrect type when loading an entity with a JSON array property using 'fields'

### ISSUE THREAD

**Issue by montycb** [mikro-orm/mikro-orm#5123]
### Describe the bug

I have an entity featuring a JSON array as one of its properties. When loading the entity without additional options, the returned object's type accurately designates this property as an array. However, when specifying the array in the 'fields' options, the resulting type only designates the property as a single object instead of an array.

I've included a testcase

### Reproduction

``` ts
import { Entity, PrimaryKey, Property, JsonType } from '@mikro-orm/core';
import { MikroORM } from '@mikro-orm/sqlite';
@Entity()
class A {

  @PrimaryKey()
    id!: number;

  @Property({ type: JsonType })
    array!: B[];

}

export interface B {
  test: string;
}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [A],
    dbName: 'test-5100',
  });
  await orm.schema.ensureDatabase();
  await orm.schema.refreshDatabase();
});

test('test', async () => {
  const a = orm.em.create(A, { array: [{ test: 'test' }] });
  await orm.em.persistAndFlush(a);

  const a1 = await orm.em.findOneOrFail(A, 1);
  const a2 = await orm.em.findOneOrFail(A, 1, { fields: ['array'] });

  a1.array; // typescript says B[], ok
  a2.array; // typescript says Loaded<B, never, never, never>, wrong
});
```

### What driver are you using?

None

### MikroORM version

6.0.2

### Node.js version

v21.5.0

### Operating system

Linux

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Do you have an actual problem with this or you just don't like the inferred type? It should work the same as if it would be `B[]` I think. And it feels like a wontfix to me, there is no way to detect what interface is an entity on type level.
