### ISSUE TITLE
Reexport `AutoPath` and `UnboxArray` types

### ISSUE THREAD

**Issue by ceopaludetto** [mikro-orm/mikro-orm#5124]
**Is your feature request related to a problem? Please describe.**
Not really

**Describe the solution you'd like**
I'm using `AutoPath` and `UnboxArray` to mimic populate option in custom scenarios. Imagine the following example:
```ts
async function getUserByID(id: string, populate: Mapped<User>) {
  return em.findOneOrFail(User, { id }, { populate })
}
```

I want to correctly type the populate option, so I've created the `Mapped<T>` type which is basically this:
```ts
export type Mapped<T extends object, P extends string = ""> = AutoPath<UnboxArray<T>, P, "*">[] | false;
```

But these types are not available from default `@mikro-orm/core` export. 

**Describe alternatives you've considered**
Recreate these types in my codebase.

**Additional context**
.

**Comment by B4nan** [comment]
FYI you don't really need `UnboxType`, that's only for methods that accept `T | T[]` and returns one item or an array based on that (e.g. `em.populate()` or `serialize()`).

But I dont mind exposing both.
