### ISSUE TITLE
Incomplete Migration for Single Table Inheritance with Shared Columns in Different Entities

### ISSUE THREAD

**Issue by rethRed** [mikro-orm/mikro-orm#5126]
### Describe the bug

I utilize a UserBaseEntity as a base class for all user entities, implementing Single Table Inheritance for users. However, there's an issue with the migration process for entities like DefaultUserEntity and OauthUserEntity. Both entities possess the username and email attributes, but in the database, they are represented by different column names. Unfortunately, during migration, only the columns oauth_username and oauth_email are being created, leaving out the default_username and default_email columns. Consequently, attempts to use DefaultUserEntity result in errors due to missing columns in the database.

### Reproduction

```ts

@Entity({ 
    discriminatorColumn: "discr",
    // discriminatorMap: {  },
    tableName: "users",
    abstract: true,
    
})
export abstract class BaseUserEntity extends BaseEntity {}

--

@Entity({ 
    discriminatorValue: "oauth",
})
export class OauthUserEntity extends BaseUserEntity {
 
    @Property({ name: "oauth_username" })
    username!: string;

    @Property({ name: "oauth_email" })
    email!: string;
}


--

@Entity({ 
    discriminatorValue: "default",
})
export class DefaultUserEntity extends BaseUserEntity {

    @Property({ name: "default_username" })
    @Unique()
    username!: string;


    @Property({ name: "default_email" })
    @Unique()
    email!: string;
}
 ```

### What driver are you using?

@mikro-orm/mysql

### MikroORM version

6.0.2

### Node.js version

18.18.2

### Operating system

linux

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
I gave this a shot some time ago and supporting this will be pretty hard to achieve, as it goes against how things were designed (we inline all children to the root entity).

**Comment by nicomouss** [comment]
@rethRed That's not a bug, you should do proper OOP/polymorphism in your entity design if you want Single Table Inheritance to fit in properly.

So in your case what you should do is:

```ts
@Entity({ 
    discriminatorColumn: "discr",
    tableName: "users",
    abstract: true,
})
export abstract class BaseUserEntity extends BaseEntity {
    @Property({ name: "username" })
    username!: string;

    @Property({ name: "email" })
    email!: string;
}

@Entity({ 
    discriminatorValue: "oauth",
})
export class OauthUserEntity extends BaseUserEntity {
}

@Entity({ 
    discriminatorValue: "default",
})
export class DefaultUserEntity extends BaseUserEntity {
}
```

In your db, you'll then have something like so (postgresql):

```sql
create table "users" (
  ... 
  "username" varchar(255), 
  "email" varchar(255), 
  "discr" text check ("type" in ('oauth', 'default'));
);
```

On the db side, you thus have the "discr" column to know which entity type you are dealing with.

Having two different columns like "oauth_username" and "default_username" would be redundancy, as you can use the "discr" column to know whether you are dealing with an oauth user or a default one.

Hope that helps.
