### ISSUE TITLE
MySQL should use utf8mb4 instead of utf8

### ISSUE THREAD

**Issue by thomaschaaf** [mikro-orm/mikro-orm#513]
**Describe the bug**
Currently you can not save emojis in the database with the default encoding setting.

Here is a blog post about it:
https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434

**Comment by B4nan** [comment]
There is no diffing support for this (and I am not planning to add it), so you can just change it manually on existing tables.

**Comment by thomaschaaf** [comment]
But could the default be changed? I bet a lot of people don't know why saving emojis won't work for them. It would just have to be changed here right? https://github.com/mikro-orm/mikro-orm/blob/c36b495244c4b5f861c7c3c20c1b401161baf877/lib/schema/MySqlSchemaHelper.ts#L38-L47

**Comment by B4nan** [comment]
Only thing that makes sense to change is the `finalizeTable` part. Sure we can make this configurable.
