### ISSUE TITLE
SAVEPOINT Error on migration

### ISSUE THREAD

**Issue by conspireagency** [mikro-orm/mikro-orm#5130]
### Describe the bug

When running migrate on v6 the changes in the migration get made to the database, but the migration errors out in the terminal with the following:

`MigrationError: Migration Migration20240114220255 (up) failed: Original error: RELEASE SAVEPOINT trx3; - SAVEPOINT does not exist: RELEASE SAVEPOINT trx3`

<img width="787" alt="Screenshot 2024-01-14 at 2 09 25 PM" src="https://github.com/mikro-orm/mikro-orm/assets/29992361/4ba4ddcf-559e-46d3-b508-0e3a4206def1">

I've been using MikroOrm for a while now, albiet with Postgres until recently.  Not sure if some of this is a new v6 Migrator related or database type (Mysql on Planetscale) related.  

Looked into mysql2 / knex issues first.  I'm guessing since the updates get executed on the database and doesn't revert, it's maybe related to snapshotting / tracking migrations run on the database.  Would also make sense, since another issue I'm running into since the v6 + mysql switch is that when migrating it tries to run migrations that have already been run on the database and thus errors out.

Let me know what else I can provide.
<img width="694" alt="Screenshot 2024-01-14 at 2 20 11 PM" src="https://github.com/mikro-orm/mikro-orm/assets/29992361/00c2e254-c2e7-4c78-a97e-78d815fae03c">

<img width="694" alt="Screenshot 2024-01-14 at 2 20 27 PM" src="https://github.com/mikro-orm/mikro-orm/assets/29992361/62e677e7-abc2-4bb7-8596-dd5035966c24">

<img width="1118" alt="Screenshot 2024-01-14 at 2 22 17 PM" src="https://github.com/mikro-orm/mikro-orm/assets/29992361/fbefeec0-e6ba-4d33-b8c5-34ec1b050064">

`{
  "namespaces": [],
  "tables": [
    {
      "columns": {
        "shop": {
          "name": "shop",
          "type": "varchar(255)",
          "unsigned": false,
          "autoincrement": false,
          "primary": false,
          "nullable": false,
          "mappedType": "string"
        },
        "is_active": {
          "name": "is_active",
          "type": "tinyint(1)",
          "unsigned": false,
          "autoincrement": false,
          "primary": false,
          "nullable": false,
          "default": "false",
          "mappedType": "boolean"
        }
      },
      "name": "shop",
      "indexes": [
        {
          "keyName": "PRIMARY",
          "columnNames": [
            "shop"
          ],
          "composite": false,
          "constraint": true,
          "primary": true,
          "unique": true
        }
      ],
      "checks": [],
      "foreignKeys": {},
      "nativeEnums": {}
    },
    {
      "columns": {
        "id": {
          "name": "id",
          "type": "varchar(255)",
          "unsigned": false,
          "autoincrement": false,
          "primary": false,
          "nullable": false,
          "mappedType": "string"
        },
        "content": {
          "name": "content",
          "type": "varchar(3000)",
          "unsigned": false,
          "autoincrement": false,
          "primary": false,
          "nullable": false,
          "length": 3000,
          "default": "''",
          "mappedType": "string"
        },
        "shop_shop": {
          "name": "shop_shop",
          "type": "varchar(255)",
          "unsigned": false,
          "autoincrement": false,
          "primary": false,
          "nullable": false,
          "mappedType": "string"
        },
        "created_at": {
          "name": "created_at",
          "type": "datetime",
          "unsigned": false,
          "autoincrement": false,
          "primary": false,
          "nullable": false,
          "length": 0,
          "mappedType": "datetime"
        },
        "updated_at": {
          "name": "updated_at",
          "type": "datetime",
          "unsigned": false,
          "autoincrement": false,
          "primary": false,
          "nullable": false,
          "length": 0,
          "mappedType": "datetime"
        }
      },
      "name": "session",
      "indexes": [
        {
          "columnNames": [
            "shop_shop"
          ],
          "composite": false,
          "keyName": "session_shop_shop_index",
          "constraint": false,
          "primary": false,
          "unique": false
        },
        {
          "keyName": "PRIMARY",
          "columnNames": [
            "id"
          ],
          "composite": false,
          "constraint": true,
          "primary": true,
          "unique": true
        }
      ],
      "checks": [],
      "foreignKeys": {
        "session_shop_shop_foreign": {
          "constraintName": "session_shop_shop_foreign",
          "columnNames": [
            "shop_shop"
          ],
          "localTableName": "session",
          "referencedColumnNames": [
            "shop"
          ],
          "referencedTableName": "shop",
          "updateRule": "cascade"
        }
      },
      "nativeEnums": {}
    },
    {
      "columns": {
        "id": {
          "name": "id",
          "type": "int",
          "unsigned": true,
          "autoincrement": true,
          "primary": true,
          "nullable": false,
          "mappedType": "integer"
        },
        "customer_email": {
          "name": "customer_email",
          "type": "varchar(255)",
          "unsigned": false,
          "autoincrement": false,
          "primary": false,
          "nullable": false,
          "mappedType": "string"
        },
        "name": {
          "name": "name",
          "type": "varchar(255)",
          "unsigned": false,
          "autoincrement": false,
          "primary": false,
          "nullable": false,
          "mappedType": "string"
        },
        "shop_shop": {
          "name": "shop_shop",
          "type": "varchar(255)",
          "unsigned": false,
          "autoincrement": false,
          "primary": false,
          "nullable": false,
          "mappedType": "string"
        }
      },
      "name": "wishlist",
      "indexes": [
        {
          "columnNames": [
            "shop_shop"
          ],
          "composite": false,
          "keyName": "wishlist_shop_shop_index",
          "constraint": false,
          "primary": false,
          "unique": false
        },
        {
          "keyName": "PRIMARY",
          "columnNames": [
            "id"
          ],
          "composite": false,
          "constraint": true,
          "primary": true,
          "unique": true
        }
      ],
      "checks": [],
      "foreignKeys": {
        "wishlist_shop_shop_foreign": {
          "constraintName": "wishlist_shop_shop_foreign",
          "columnNames": [
            "shop_shop"
          ],
          "localTableName": "wishlist",
          "referencedColumnNames": [
            "shop"
          ],
          "referencedTableName": "shop",
          "updateRule": "cascade"
        }
      },
      "nativeEnums": {}
    },
    {
      "columns": {
        "id": {
          "name": "id",
          "type": "int",
          "unsigned": true,
          "autoincrement": true,
          "primary": true,
          "nullable": false,
          "mappedType": "integer"
        },
        "name": {
          "name": "name",
          "type": "varchar(255)",
          "unsigned": false,
          "autoincrement": false,
          "primary": false,
          "nullable": false,
          "mappedType": "string"
        },
        "wishlist_id": {
          "name": "wishlist_id",
          "type": "int",
          "unsigned": true,
          "autoincrement": false,
          "primary": false,
          "nullable": false,
          "mappedType": "integer"
        }
      },
      "name": "wishlist_group",
      "indexes": [
        {
          "columnNames": [
            "wishlist_id"
          ],
          "composite": false,
          "keyName": "wishlist_group_wishlist_id_index",
          "constraint": false,
          "primary": false,
          "unique": false
        },
        {
          "keyName": "PRIMARY",
          "columnNames": [
            "id"
          ],
          "composite": false,
          "constraint": true,
          "primary": true,
          "unique": true
        }
      ],
      "checks": [],
      "foreignKeys": {
        "wishlist_group_wishlist_id_foreign": {
          "constraintName": "wishlist_group_wishlist_id_foreign",
          "columnNames": [
            "wishlist_id"
          ],
          "localTableName": "wishlist_group",
          "referencedColumnNames": [
            "id"
          ],
          "referencedTableName": "wishlist",
          "updateRule": "cascade"
        }
      },
      "nativeEnums": {}
    },
    {
      "columns": {
        "id": {
          "name": "id",
          "type": "int",
          "unsigned": true,
          "autoincrement": true,
          "primary": true,
          "nullable": false,
          "mappedType": "integer"
        },
        "product_id": {
          "name": "product_id",
          "type": "int",
          "unsigned": false,
          "autoincrement": false,
          "primary": false,
          "nullable": false,
          "mappedType": "integer"
        },
        "variant_id": {
          "name": "variant_id",
          "type": "int",
          "unsigned": false,
          "autoincrement": false,
          "primary": false,
          "nullable": false,
          "mappedType": "integer"
        },
        "wishlist_id": {
          "name": "wishlist_id",
          "type": "int",
          "unsigned": true,
          "autoincrement": false,
          "primary": false,
          "nullable": false,
          "mappedType": "integer"
        }
      },
      "name": "wishlist_product_variant",
      "indexes": [
        {
          "columnNames": [
            "wishlist_id"
          ],
          "composite": false,
          "keyName": "wishlist_product_variant_wishlist_id_index",
          "constraint": false,
          "primary": false,
          "unique": false
        },
        {
          "keyName": "PRIMARY",
          "columnNames": [
            "id"
          ],
          "composite": false,
          "constraint": true,
          "primary": true,
          "unique": true
        }
      ],
      "checks": [],
      "foreignKeys": {
        "wishlist_product_variant_wishlist_id_foreign": {
          "constraintName": "wishlist_product_variant_wishlist_id_foreign",
          "columnNames": [
            "wishlist_id"
          ],
          "localTableName": "wishlist_product_variant",
          "referencedColumnNames": [
            "id"
          ],
          "referencedTableName": "wishlist",
          "updateRule": "cascade"
        }
      },
      "nativeEnums": {}
    },
    {
      "columns": {
        "wishlist_group_id": {
          "name": "wishlist_group_id",
          "type": "int",
          "unsigned": true,
          "autoincrement": false,
          "primary": false,
          "nullable": false,
          "mappedType": "integer"
        },
        "wishlist_product_variant_id": {
          "name": "wishlist_product_variant_id",
          "type": "int",
          "unsigned": true,
          "autoincrement": false,
          "primary": false,
          "nullable": false,
          "mappedType": "integer"
        }
      },
      "name": "wishlist_group_wishlist_product_variants",
      "indexes": [
        {
          "columnNames": [
            "wishlist_group_id"
          ],
          "composite": false,
          "keyName": "wishlist_group_wishlist_product_variants_wishlist_group_id_index",
          "constraint": false,
          "primary": false,
          "unique": false
        },
        {
          "columnNames": [
            "wishlist_product_variant_id"
          ],
          "composite": false,
          "keyName": "wishlist_group_wishlist_product_variants_wishlist_p_aab69_index",
          "constraint": false,
          "primary": false,
          "unique": false
        },
        {
          "keyName": "PRIMARY",
          "columnNames": [
            "wishlist_group_id",
            "wishlist_product_variant_id"
          ],
          "composite": true,
          "constraint": true,
          "primary": true,
          "unique": true
        }
      ],
      "checks": [],
      "foreignKeys": {
        "wishlist_group_wishlist_product_variants_wishlist_6b5f0_foreign": {
          "constraintName": "wishlist_group_wishlist_product_variants_wishlist_6b5f0_foreign",
          "columnNames": [
            "wishlist_group_id"
          ],
          "localTableName": "wishlist_group_wishlist_product_variants",
          "referencedColumnNames": [
            "id"
          ],
          "referencedTableName": "wishlist_group",
          "deleteRule": "cascade",
          "updateRule": "cascade"
        },
        "wishlist_group_wishlist_product_variants_wishlist_b0233_foreign": {
          "constraintName": "wishlist_group_wishlist_product_variants_wishlist_b0233_foreign",
          "columnNames": [
            "wishlist_product_variant_id"
          ],
          "localTableName": "wishlist_group_wishlist_product_variants",
          "referencedColumnNames": [
            "id"
          ],
          "referencedTableName": "wishlist_product_variant",
          "deleteRule": "cascade",
          "updateRule": "cascade"
        }
      },
      "nativeEnums": {}
    }
  ],
  "nativeEnums": {}
}
`

### Reproduction

Since the error is coming back from the database, not sure beyond what I provided would be of help.

### What driver are you using?

@mikro-orm/mysql

### MikroORM version

├─┬ @mikro-orm/cli@6.0.3 │ ├── @mikro-orm/core@6.0.3 deduped │ └─┬ @mikro-orm/knex@6.0.3 │   └── @mikro-orm/core@6.0.3 deduped ├── @mikro-orm/core@6.0.3 ├─┬ @mikro-orm/migrations@6.0.3 │ └── @mikro-orm/core@6.0.3 deduped └─┬ @mikro-orm/mysql@6.0.3   └── @mikro-orm/core@6.0.3 deduped

### Node.js version

18.17.0

### Operating system

Mac Sonoma

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
I will need something I can try myself, screenshots won't help much, try to build a repro repository. Tried to use 6.0.3 in the realworld example repo to create and run some migrations, but it all works fine on my end. 

The problem won't be in the things you provided, its about the migration execution. Try enabling debug mode (you might need `verbose` option for the CLI) to see the executed queries, to see if there is a snapshot of that name created (it should). 

FWIW, savepoints are handled via knex, not in the ORM code.

**Comment by conspireagency** [comment]
@B4nan here's a more barebones version of the repo.  I hear what you're saying re the error originating from Knex (looked at their issues as well), just wasn't sure if it's something related to the ORM + knex.  

https://github.com/conspireagency/mikroorm-issue

To replicate:
-npm install (+ ran a build for good measure)
-add DATABASE_URL.  I'm using Planetscale mysql.  Emailed you a fresh database url you can use if you'd like.
-npm run migration (this succeeds)
-npm run migrate (this changes the database, but errors out in the terminal with the savepoint error)

As a result, even though the changes are made, if you update the models and run a new migration + migrate it will try to run the initial migration first.  Guessing this is as a result of the first savepoint issue?

**Comment by conspireagency** [comment]
@B4nan heads up, all things the same the issue doesn't happen when I switched to postgres.

**Comment by B4nan** [comment]
Isn't this just about the mysql limitations? You won't really get transactions for DDL statements with mysql, it will autocommit on each statement, so what you are trying seems not supported in the first place.

**Comment by conspireagency** [comment]
@B4nan to be honest it's been a while since I used mysql and not super familiar.  Not really trying to do anything specific besides getting migrations to run properly on the database.  Are you saying that in the mikro orm config that the "transactional" or "allOrNothing" settings in migrations should be excluded and are the likely reason the migrations are erroring on a mysql database? I think the reason I added those is because it was failing/acting weird, typically I haven't had those options there in other projects using Postgres.

Sent you a temp fresh database via email along with the repo if you want to see what I mean.

**Comment by B4nan** [comment]
My guess is its specific to planetscale as it wont be the regular mysql behind the scenes - otherwise you wouldnt be the first one reporting this.

Maybe we should just disable transactions for mysql in migrator to get around this.

**Comment by conspireagency** [comment]
@B4nan yeah maybe, I'll give their support a ring too... see what they think =)

That could work, granted transactions be default is pretty nice.  If people aren't having issues with mysql, as long as in the config disabling transactions works, then can probably leave as is... 

Will report back on what Planetscale says.

**Comment by ThatsARapp** [comment]
For Planetscale, I had to turn off migration transactions in the mikro-orm config
```
  migrations: {
    path: "dist/src/server/db/migrations",
    pathTs: "src/server/db/migrations",
    transactional: false,
  },
  ```

**Comment by B4nan** [comment]
I'll close this as a wontfix, as I mentioned earlier, transactions on DDL statements in MySQL are problematic even without planetscale as they cause autocommit, so this all feels like you are trying to achieve nonachievable (and run into planetscale-specific issues for unsupported use case).

I'd be still interested to head what their support has to say about this (but I can imagine their first-level support won't be very technical :]).
