### ISSUE TITLE
Error with nested foreign primary key

### ISSUE THREAD

**Issue by Urtyom-Alyanov** [mikro-orm/mikro-orm#5144]
### Describe the bug

ORM throws an `MetadataError` on defining entity with relation to entity with identity through foreign entities.

`MetadataError: Organization.owner has unknown 'inversedBy' reference: Account.organizations`

### Reproduction

Define entities:
```ts
export enum AccountType {
  User = 1,
  Organiztion = 2,
}

@Entity()
export class Account {
  @PrimaryKey()
  id!: number;

  @Property()
  name: string;

  @Property()
  balance: number = 0;

  @OneToOne(() => User, "account")
  user?: Ref<User>;

  @OneToOne(() => Organization, "account")
  organization?: Ref<Organization>;

  @Enum(() => AccountType)
  type!: AccountType;

  constructor(name: string, startBalance: number = 0, type = AccountType.User) {
    this.name = name;
    this.balance = startBalance;
    this.type = type;
  }
}

@Entity()
export class User {
  @OneToOne({ primary: true })
  account!: Ref<Account>;

  @Property()
  username!: string;

  @Property({ hidden: true })
  password!: string;

  @Property({ hidden: true })
  salt!: string;

  @OneToMany(() => Organization, (org) => org.owner)
  organizations = new Collection<Organization>(this);

  [PrimaryKeyProp]?: "account";

  constructor(account: Account, username: string, password: string) {
    this.account = ref(account);
    this.username = username;

    const salt = crypto.randomBytes(16).toString("hex");
    this.salt = salt;
    this.password = crypto
      .pbkdf2Sync(password, salt, 1000, 64, `sha512`)
      .toString(`hex`);
  }
}

@Entity()
export class Organization {
  @OneToOne({ primary: true })
  account!: Ref<Account>;

  @ManyToOne()
  owner!: Ref<User>;

  [PrimaryKeyProp]?: "account";

  constructor(account: Account, owner: User) {
    this.account = ref(account);
    this.owner = ref(owner);
  }
}
```

[![Edit Urtyom-Alyanov/reproduction-nested-foreign-primary-key/master](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/github/Urtyom-Alyanov/reproduction-nested-foreign-primary-key/master?file=%2Fsrc%2Faccount.entity.ts&embed=1)

### What driver are you using?

@mikro-orm/sqlite

### MikroORM version

6.0.4

### Node.js version

v20.6.1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
This is a problem with ts-morph metadata provider apparently, if you specify the type explicitly, it works fine:

```ts
@ManyToOne(() => User)
owner!: Ref<User>;
```
