### ISSUE TITLE
Add support for entity independent hooks/subscribers

### ISSUE THREAD

**Issue by carmas123** [mikro-orm/mikro-orm#516]
Hi, I want to migrate my app from TypeORM to MikroORM. Now I've a problem with event listening.
In TypeORM I've a EntitySubscriberInterface injectable by @Subscriber() that hook all events afterUpdate, beforeUpdate or other into an external handler and not directly into the entity. This is very useful to manage some events from external.

There is an alternative into MikroORM?

**Comment by B4nan** [comment]
As discussed on slack, you could use base entity and define the hooks there, so they will be fired for all entities that extend this base entity. 

I am planning to add support for something similar to EntitySubscriber in v4 (not necessarily in 4.0 though).

**Comment by B4nan** [comment]
Closing as implemented in v4 via #614, subscribe to #527 for updates (this will be part of `4.0.0-alpha.4`).
