### ISSUE TITLE
Duplicate join clause when using populate and filter by relation at the same time.

### ISSUE THREAD

**Issue by bozorgmehr96** [mikro-orm/mikro-orm#5160]
### Describe the bug

For the blow find query, two join clauses will be generated.
```ts
em.find(Address, {user: { email: 'me@example.com' } }, { populate: ['user'] });
```

### Reproduction

[bozorgmehr96/mikro-orm-duplicate-join-repro](https://github.com/bozorgmehr96/mikro-orm-duplicate-join-repro)

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.0.4

### Node.js version

20.11.0

### Operating system

Ubuntu 22.04

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
This is expected behaviour, populate joins have their own branches by default, as the where query only affects the root entity. You can change this behaviour with `populateWhere: infer`.

https://mikro-orm.io/docs/loading-strategies#population-where-condition
