### ISSUE TITLE
Inserting using QueryBuilder requires columns even though they have a `defaultRaw` / `default` value

### ISSUE THREAD

**Issue by stad-nico** [mikro-orm/mikro-orm#5170]
### Describe the bug

Trying to insert using a `QueryBuilder` still requires every non-optional property of the entity to be given, even though some of those properties have a `defaultRaw`.
Making all properties that have a default value also optional to pass the type checking cannot be an option.

### Reproduction

```ts
import { Entity, ManyToOne, PrimaryKey, Property } from '@mikro-orm/core';

@Entity({ tableName: 'directories' })
export class Directory {
	@PrimaryKey({ type: 'uuid', nullable: false, defaultRaw: 'UUID()', unique: true })
	readonly id!: string;

	@Property({ type: 'varchar', nullable: false })
	readonly name!: string;

	@Property({ type: 'tinyint', nullable: false, default: false })
	readonly isRecycled!: boolean;

	@Property({ type: 'datetime', nullable: false, defaultRaw: 'current_timestamp()' })
	readonly createdAt!: Date;

	@Property({ type: 'datetime', nullable: false, defaultRaw: 'current_timestamp() on update current_timestamp()' })
	readonly updatedAt!: Date;
}


await entityManager
    .createQueryBuilder(Directory, "directories")
    .insert({
        name: "test"
    }); // TypeError: not assignable to `RequiredEntityData<Directory>`

```

### What driver are you using?

@mikro-orm/mariadb

### MikroORM version

6.0.4

### Node.js version

v.20.5.1, typescript@5.3.2

### Operating system

Windows 11

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
That's only a type-level issue, you need to mark those properties with runtime defaults via `Opt` type (or via `OptionalProps` symbol), otherwise TS only sees required properties - there is no way to detect there is a runtime default. Decorators options are not relevant here, they don't have any effect on type level.

https://mikro-orm.io/docs/property-validation#properties-with-default-value

**Comment by stad-nico** [comment]
Maybe we should add a reference to that in the docs under ​​https://mikro-orm.io/docs/defining-entities#optional-properties?
Perhaps this would make optional properties with typescript clearer.
