### ISSUE TITLE
v6.0.5 insertMany

### ISSUE THREAD

**Issue by tkudlicka** [mikro-orm/mikro-orm#5179]
### Describe the bug

when i insert only one record, because i expecting 1 or more items i use insertMany, but when i insert only one, then returned ids insertIds are undefined and it should return insertedId from response in array
```{ affectedRows: 1, insertId: 1, row: { id: 1 }, rows: [ { id: 1 } ] }```

### Reproduction

// Works as a workaround
await em.insertMany(
          Test,
          [{
            test: "test"
          }],
        );

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.0.5

### Node.js version

v18.18.2

### Operating system

mac

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
I am not sure what you are reporting here. Your reproduction starts with a comment saying the code is a workaround? Also, it's a bit incomplete, e.g. no entity definition, ORM config, etc. Most importantly, there is no assert, so no notion of what you expect in the response, you don't even save the response anywhere...

**Comment by tkudlicka** [comment]
at EntityManager should be for function insertMany last return```return data.length === 1 ? [res.insertedId] : res.insertedIds;```
