### ISSUE TITLE
Schema differences between sqlite and postgres

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#518]
**Describe the bug**
I have a @ManyToOne and in sqlite, the column is created without not null, but in postgres, it is created correctly. This caused me a bug because I was able to do the insert in my tests, but it failed in postgres. Database for postgres is created with the CLI shema:create and the one for sqlite3 is with my tests that just call the methods directly.

Entity property:

```
	@ManyToOne()
	datacenter!: Datacenter;
```

DDL sqlite3:
```
    datacenter        integer,
```

DDL postgres:

```
    datacenter          integer                  not null
        constraint invoice_datacenter_foreign
            references "Datacenter"
            on update cascade,
```

**Versions**

| Dependency | Version |
| - | - |
| mikro-orm | 3.6.11 |
| postgres | 1.0.2 |
| sqlite3 | 4.2.0 |

**Comment by B4nan** [comment]
Sqlite requires nullable columns for altering, generally there are more limitations there. Also there is that knex bug (the one with warnings).

**Comment by lookfirst** [comment]
Oh well, I guess I need to setup postgres for tests now too. This one was particularly bad since my tests pass.

**Comment by lookfirst** [comment]
Yea, you can close this. But I think adding a section to the documentation would be good.
