### ISSUE TITLE
Postgres `interval` type creates a `varchar` column instead of `interval`

### ISSUE THREAD

**Issue by stefansundin** [mikro-orm/mikro-orm#5181]
### Describe the bug

I'm attempting to create a column using the `interval` type but I have to work around a bug with a custom type.

```typescript
  @Property({
    type: 'interval',
    nullable: true,
  })
  durationBuggy?: string | null;
```

results in:

```sql
"duration_buggy" varchar(255) null
```

I can define a custom type to work around this issue.

```typescript
// IntervalType.ts

import { EntityProperty, Type } from '@mikro-orm/core';

export class IntervalType extends Type<
  string | null,
  string | null | undefined
> {
  getColumnType(prop: EntityProperty) {
    return `interval(${prop.length ?? 6})`;
  }
}
```

```typescript
  @Property({
    type: IntervalType,
    nullable: true,
  })
  durationWorkaround?: string | null;
```

results in:

```sql
"duration_workaround" interval(6) null
```

### Reproduction

https://github.com/stefansundin/mikro-orm-reproduction/tree/interval-type-bug

```typescript
@Entity()
export class Session {

  @PrimaryKey()
  id!: number;

  @Property({
    type: 'interval',
    nullable: true,
  })
  durationBuggy?: string | null;

  @Property({
    type: IntervalType,
    nullable: true,
  })
  durationWorkaround?: string | null;

}
```

### What driver are you using?

None

### MikroORM version

6.0.5

### Node.js version

v18.19.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
You don't need the custom type for this:

```ts
@Property({
  columnType: 'interval',
  nullable: true,
}) 
durationBuggy?: string | null;
```

**Comment by stefansundin** [comment]
It seems like `columnType: 'interval'` creates this persistent diff:

```sql
alter table "session" alter column "duration" type interval using ("duration"::interval);
```

**Comment by B4nan** [comment]
Yes, that's correct. If you want `interval(6)`, put it there, it needs to be explicit.

**Comment by stefansundin** [comment]
It seems to be working fine with `columnType: 'interval(6)'` :+1:

**Comment by B4nan** [comment]
Hmm so I guess for postgres the default length for interval type is also 6 like for timestamp?

**Comment by stefansundin** [comment]
It would appear so: https://www.postgresql.org/docs/current/datatype-datetime.html

I have to use my custom type in order to actually write to this column, because just using `PostgresInterval()` from `postgres-interval` doesn't call `.toPostgres()` to generate the correct value.

```typescript
import { type IPostgresInterval } from 'postgres-interval';

import { EntityProperty, Type } from '@mikro-orm/core';

export class IntervalType extends Type<
  IPostgresInterval | null,
  string | null | undefined
> {
  convertToDatabaseValue(value: IPostgresInterval | null): string | null {
    if (!value) {
      return null;
    }
    return value.toPostgres();
  }

  getColumnType(prop: EntityProperty) {
    return `interval(${prop.length || 6})`;
  }
}
```

Then in my entity:

```typescript
  @Property({
    type: IntervalType,
    nullable: true,
    length: 6,
  })
  duration?: IPostgresInterval | null;
```

Maybe that should be built into mikro-orm?
