### ISSUE TITLE
Include PrimaryKeyProp in optional key set

### ISSUE THREAD

**Issue by sualko** [mikro-orm/mikro-orm#5187]
### Describe the bug

If you use a primary key other than the usual `id` field, you manually have to mark it as optional. For me it would be nice if this would be handled directly by mikro-orm.

My best guess would be to include the `PrimaryKeyProp` in the `ProbablyOptionalProps`.

```
type ProbablyOptionalProps<T> = ExplicitlyOptionalProps<T> | 'id' | '_id' | 'uuid' | Defined<NullableKeys<T>>;
```

### Reproduction

```
@Entity()
class Book {
  @PrimaryKey()
  bookId: number;

  [PrimaryKeyProp]: 'bookId';

  @Property()
  title: string;
}
```

If you try to create a new book with `em.create(Book, {title})`, typescript throws an error, because `bookId` is missing. I know I can mark it as optional with the usually symbols or wrappers, but for me it would be nicer if mikro-orm would detect the key on its own.

### What driver are you using?

@mikro-orm/mysql

### MikroORM version

6.0.6

### Node.js version

18.13.0

### Operating system

Ubuntu 22.04

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Good point, I was actually thinking exactly the same a few days ago.

**Comment by sualko** [comment]
Works like a charm :tada:

**Comment by Heniker** [comment]
So... What to do if you don't use `autoincrement` on PK and need it to actually be required?
