### ISSUE TITLE
Inconsisten behaviour of date conversion to js value between array and single value

### ISSUE THREAD

**Issue by co-sic** [mikro-orm/mikro-orm#5188]
### Describe the bug

I have two custom type for a postgres date type column (no time information). In the first example with a single value, i get a string from the `convertToJSValue` function, which is what i would expect and also what i want. But if i make the same type but for an array, I get an array of js Date objects from the `convertToJSValue` function.

```ts
class CalendarDateType extends Type<CalendarDate | null, string | null> {
  convertToJSValue(
    value: CalendarDate | string | null | undefined
  ): CalendarDate {
    console.log(typeof value === "string"); // true
  }

  getColumnType(): string {
    return "date";
  }
}

```

```ts
export class CalendarDateArrayType extends Type<
  CalendarDate[] | null,
  string | null
> {
  convertToJSValue(
    value: CalendarDate[] | string | null | undefined
  ): CalendarDate[] | null {
    console.log(value[0] instanceof Date) // true;
  }

  getColumnType(): string {
    return "date[]";
  }
}

```

### Reproduction

Let me know if you need a reproduction for this one, then i can provide one.

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.0.6

### Node.js version

20

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
I think you need `ArrayType` here, either extend it on handle the ser/deser the same way. 

> Let me know if you need a reproduction for this one, then i can provide one.

The rule of thumb: I always want to see a reproduction. From what you gave me, I don't know much, I only see a type that does not convert anything either way.

I do have a hunch, postgres shouldnt be converting anything to `Date` objects, as its disabled here:

https://github.com/mikro-orm/mikro-orm/blob/master/packages/postgresql/src/PostgreSqlConnection.ts#L20

Maybe there is an explicit `date[]` type ID too we need to add here? But it feels pretty weird.

**Comment by co-sic** [comment]
Okay, i'll provide a reproduction. For using ArrayType: at least on the type level it only supports a value that extends string or number and my value (on the js side) is an object.

**Comment by co-sic** [comment]
Okay, i'll provide a reproduction. :+1:  For using ArrayType: at least on the type level it only supports a value that extends string or number and my value (on the js side) is an object.

**Comment by B4nan** [comment]
Arrays are serialized to strings, in postgres it's a comma-delimited list wrapped in curly braces. And that is what the ORM handles for you via the `ArrayType`. For such things to universally work (also for embeddables and other use cases), it needs to be handled by the ORM, not by some automated quirks on the db library level (which I think is what converts your `date[]` column to `Date[]` on JS side, I doubt its some code from the ORM).

**Comment by B4nan** [comment]
So the problem was twofold, one was node-postgres converting things to Date objects, the other was a proper support for working with objects in the ArrayType, both is handled via #5204
