### ISSUE TITLE
findAndCount returns incoherent results

### ISSUE THREAD

**Issue by Yaty** [mikro-orm/mikro-orm#519]
**Describe the bug**

Hi!

I try to use `findAndCount` on a repository with a filter. The entity is a composite of two primary keys. The result of the `findAndCount` is not ok, I get a count of 1 entity and the correct amount of entities in the array of entities.

**To Reproduce**

I created a gist here : https://gist.github.com/Yaty/52ae391fa3c7158e18b9701994d878ed

**Expected behavior**
The count should be correct

**Versions**

| Dependency | Version |
| - | - |
| node | 12.6.2 |
| typescript | 3.8.3 |
| mikro-orm | 3.6.11 |
| pg | 8.0.3 |

**Comment by B4nan** [comment]
Thanks for the repro!

**Comment by B4nan** [comment]
`v3.6.12` is out with the fix

**Comment by Yaty** [comment]
I confirm! Thanks :)
