### ISSUE TITLE
Return type of get method in CacheAdapter should also allow 'undefined'

### ISSUE THREAD

**Issue by SnowMarble** [mikro-orm/mikro-orm#5199]
### Describe the bug

Currently the type of get method in `CacheAdapter` is:

```ts
get<T = any>(name: string): T | Promise<T> | undefined;
```

But, as non-promise return type allows `undefined`, I think Promise return type also needs to allow  `undefined`.

```ts
get<T = any>(name: string): T | Promise<T | undefined> | undefined;
```

### Reproduction

```ts
// Type error: Type 'T | undefined' is not assignable to type 'T'
async get<T = unknown>(name: string): Promise<T | undefined> {
  // rest of the code
}
```

### What driver are you using?

None

### MikroORM version

6.0.2

### Node.js version

Bun v1.0.25

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
PR welcome
