### ISSUE TITLE
Bug with orphan removal in nested entities

### ISSUE THREAD

**Issue by Darent98** [mikro-orm/mikro-orm#5213]
### Describe the bug

In the scenario outlined in the provided reproduction case, an issue emerges when in an entity B c1 was set and then is set to null. The entity in C is not referenced anymore, but is not removed automatically even though in B oprhanRemoval is set to true for c1.

### Reproduction

``` ts
import { Collection, Entity, EntityData, ManyToOne, MikroORM, OneToMany, OneToOne, PrimaryKey, Property, Ref, RequiredEntityData } from '@mikro-orm/sqlite';

@Entity()
class A {

  @PrimaryKey()
  id!: number;

  @OneToMany(() => B, b => b.a, {eager: true, orphanRemoval: true})
  b = new Collection<B>(this)
}

@Entity()
class B {
  @PrimaryKey()
  id!: number

  @ManyToOne({entity: () => A, deleteRule: 'cascade', updateRule: 'cascade'})
  a!: Ref<A>

  @OneToOne(() => C, c => c.b1, {owner: true, nullable: true, default: null, orphanRemoval: true})
  c1!: Ref<C> | null

  @OneToOne(() => C, c => c.b2, {owner: true, nullable: true, default: null, orphanRemoval: true})
  c2!: Ref<C> | null
}

@Entity({abstract: true})
abstract class D {
  @PrimaryKey()
  id!: number

  @ManyToOne({entity: () => E, deleteRule: 'cascade', updateRule: 'cascade', eager: true})
  e!: Ref<E> 

}

@Entity()
class C extends D {
  @OneToOne(() => B, b => b.c1, {})
  b1!: B | null
  @OneToOne(() => B, b => b.c2, {})
  b2!: B | null
}


@Entity()
class E {
  @PrimaryKey()
  id!: number

  @Property()
  name!: string
}

interface BI {
  id?: number | null
  c1?: CI | null
  c2?: CI | null
}

interface CI {
  id?: number
  e: number
}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    dbName: ':memory:',
    entities: [A,B,C,D,E],
    debug: ['query', 'query-params'],
    allowGlobalContext: true, // only for testing
  });
  await orm.schema.refreshDatabase();
});

afterAll(async () => {
  await orm.close(true);
});

test('example', async () => {
  orm.em.create(E, {name: 'test'})
  await orm.em.flush()
  orm.em.clear()

  const e = await orm.em.findOneOrFail(E, {name: 'test'})
  expect(e.name).toBe('test')

  const a = orm.em.create(A, {
    b: [{
      c1: {
        e: e.id
      }
    }]
  })
  await orm.em.persistAndFlush(a)
  orm.em.clear()

  const existingAs = await orm.em.findAll(A, {populate: ['b', 'b.*']})
  const existingA = existingAs[0]

  existingA.b.getItems().forEach(b => orm.em.assign(b, {
    c1: null,
    c2: null
  }))
  
  await orm.em.persistAndFlush(a)
  orm.em.clear()

  const csCount = await orm.em.count(C)

  // expecting that count is 0, because the only existing C is not referenced in any B anymore
  expect(csCount).toBe(0)
});
```

### What driver are you using?

@mikro-orm/sqlite

### MikroORM version

6.1.1-dev.3

### Node.js version

20.10.0

### Operating system

linux

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
You need to initialize the relation, then it works fine. You are doing `populate: ['b.*']` but that's not populating the `b.c1` and `b.c2` relations, the star works only on the top level. I am not entirely sure if that should be considered a bug, it works this way because the populate hint is inferred from the partial loading hint if only that one is provided, and there it has a different meaning (select all columns from the relation). But we could surely skip that when inferring the populate hint, so it's not a real problem.

```ts
import {
  Collection,
  Entity,
  ManyToOne,
  MikroORM,
  OneToMany,
  OneToOne,
  PrimaryKey,
  Property,
  Ref,
} from '@mikro-orm/sqlite';

@Entity()
class A {

  @PrimaryKey()
  id!: number;

  @OneToMany(() => B, b => b.a, { eager: true, orphanRemoval: true })
  b = new Collection<B>(this);

}

@Entity()
class B {

  @PrimaryKey()
  id!: number;

  @ManyToOne({ entity: () => A, deleteRule: 'cascade', updateRule: 'cascade' })
  a!: Ref<A>;

  @OneToOne(() => C, c => c.b1, { owner: true, nullable: true, default: null, orphanRemoval: true })
  c1!: Ref<C> | null;

  @OneToOne(() => C, c => c.b2, { owner: true, nullable: true, default: null, orphanRemoval: true })
  c2!: Ref<C> | null;

}

@Entity()
class C {

  @PrimaryKey()
  id!: number;

  @ManyToOne({ entity: () => E, deleteRule: 'cascade', updateRule: 'cascade', eager: true })
  e!: Ref<E>;

  @OneToOne(() => B, b => b.c1, { nullable: true })
  b1!: B | null;

  @OneToOne(() => B, b => b.c2, { nullable: true })
  b2!: B | null;

}

@Entity()
class E {

  @PrimaryKey()
  id!: number;

  @Property()
  name!: string;

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    dbName: ':memory:',
    entities: [A, B, C, E],
    debug: ['query', 'query-params'],
  });
  await orm.schema.refreshDatabase();
});

afterAll(async () => {
  await orm.close(true);
});

test('example', async () => {
  const a = orm.em.create(A, {
    b: [{
      c1: {
        e: { name: 'test' },
      },
    }],
  });
  await orm.em.persistAndFlush(a);
  orm.em.clear();

  const existingAs = await orm.em.findAll(A, { populate: ['b.c1'] });
  const existingA = existingAs[0];

  existingA.b.getItems().forEach(b => orm.em.assign(b, {
    c1: null,
    c2: null,
  }));

  await orm.em.flush();
  orm.em.clear();

  const csCount = await orm.em.count(C);

  // expecting that count is 0, because the only existing C is not referenced in any B anymore
  expect(csCount).toBe(0);
});
```

**Comment by Darent98** [comment]
Thank you for your quick response. After explicitly populating my entities the behavior is as expected.

Is there a plan for the future to implement the asterisk on deeper levels than the top level?
It would be more of a QoL change, but in my case there are six references, that I need to populate and the populate array is getting pretty long.

**Comment by B4nan** [comment]
Either way, this won't be strictly typed - the `Loaded` type won't recognize this.

> But it's probably a good idea to limit the scope.

The top-level start populate surely needs to stay working recursively, that would be a huge breaking change. And because of that, I am not entirely sure it's a good idea to have a different behavior for the star when it's nested.

Overall, those `*` populate hints were always meant to be testing toy, not a production tool. You should be explicit in your code.

**Comment by Darent98** [comment]
You are right, the asterisk should work on all levels the same.
Still thanks for the adjustment and the hint, to only use the asterisk as a testing tool.

**Comment by B4nan** [comment]
The next version will support this without the relation being populated thanks to fc9a1c1c0102eab2bb9fef2def7144e857cce6e8
