### ISSUE TITLE
Filtering on properties of JSON embeddables not working for type number

### ISSUE THREAD

**Issue by NicklasKnell** [mikro-orm/mikro-orm#5239]
### Describe the bug

Filtering on embeddables does not function correctly for properties of type number, since it does not convert the JSON stored value to its actual type.

If need I can also create a reproduction.

### Reproduction

`
@Embeddable()
export class MyEmbeddable {
  @Property({ type: 'double' })
  numberProperty: number;
}

@Entity()
export class MyEntity {
  @Embedded({ object: true })
  myEmbeddable: MyEmbeddable;
}
`

when trying to filter using:

`{ myEmbeddable: { numberProperty: { $gt: 100 } } }`

it does not convert numberProperty to a number, but rather tries to do `text > number`.

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.1.0

### Node.js version

20.*

### Operating system

Unix

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
> If need I can also create a reproduction.

Please do, we need a reproduction, either you do it and I will have more time to focus on the actual fix, or I will do it and everything will take a bit longer.

Note that we have tests for this and it works fine in there, my guess is it's caused by the `type: 'double'`, try to remove that (it won't have any effect anyway, as this property represents the stuff inside JSON, you cant type that outside of the regular string/number/boolean/null).

**Comment by B4nan** [comment]
Ok good, that helps too. I will try to look into this later today, I have a hunch on what's happening. So you can postpone the repro for a bit, and wait for me till tomorrow, maybe I'll resolve it without it. Will ping you here if I need the repro.
