### ISSUE TITLE
Options provided by error message `ValidationError.cannotRemoveFromCollectionWithoutOrphanRemoval` doesn't work

### ISSUE THREAD

**Issue by rbao** [mikro-orm/mikro-orm#5243]
### Describe the bug

I saw this error:
```
ValidationError: Removing items from collection xxx without `orphanRemoval: true` would break non-null constraint on the owning side. You
 have several options:                                                        
     - add `orphanRemoval: true` to the collection options
     - add `deleteRule: 'cascade'` to the owning side options                                                                                               
     - add `nullable: true` to the owning side options
 ```
and I added the deleteRule to the owning side
```
@ManyToOne(() => User, { ref: true, deleteRule: 'cascade' })
```
but I still get the same error. In 5.x (`onDelete: 'cascade'`) use to work fine for me.

I looked through the code and I saw this code: https://github.com/mikro-orm/mikro-orm/blob/c02c057dbb52a3f576e9033b0a7601573a98332f/packages/core/src/entity/ArrayCollection.ts#L429-L435

Which is checking for `updateRule` not `deleteRule` as suggested in the error message, so I think either the error message needs to be updated or the if condition need to be updated. I believe the if condition is actually correct since removing from collection is not necessarily removing the owning side from the database so updateRule make more sense. Not sure if my understanding is correct. So just need to fix the error message as it is a bit confusing.

### Reproduction

I think the issue is obvious enough to understand, if not I am happy to provide more details.

### What driver are you using?

@mikro-orm/sqlite

### MikroORM version

6.1.2

### Node.js version

v20.11.0

### Operating system

Mac

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
> since removing from collection is not necessarily removing the owning side from the database so updateRule make more sense

The error message is correct, and that is exactly the point of that code - if you want to remove from a 1:m collection without actually removing the item, you need to have the owner nullable, otherwise you end up with an error on the db level (as the ORM will try to update the FK to null).

**Comment by rbao** [comment]
Thanks for the explanation and quick fix, mikro-orm is honestly the best ORM I can find for typescript. I tried TypeORm and Prisma and they don't even come close. It's really quality work!
