### ISSUE TITLE
The populateWhere filter does not work for deeply nested objects

### ISSUE THREAD

**Issue by SergiyRybin** [mikro-orm/mikro-orm#5266]
### Describe the bug

The PopulateWhere filter does not work for two or more nested objects, but everything is filtered correctly for one nested object.

### Reproduction

```
@Entity()
export class UserContact {
   @PrimaryKey()
   id!: number;
   
   @Property()
   address: string;
   
    @Property()
   main: boolean;
      
   @ManyToOne({
    entity: () => User ,
    nullable: true,
   })
    user?: User;
}


@Entity()
export class User {

   @PrimaryKey()
   id!: number;

   @Property()
   fullName!: string;
   
   @ManyToOne({
    entity: () => Article ,
    nullable: true,
   })
    article?: Article;
   
   @OneToMany({
    entity: () => UserContact,
    mappedBy: 'user',
    orphanRemoval: false,
    })
   contacts: new Collection<UserContact>(this);
}

@Entity()
export class Article {

 @PrimaryKey()
   id!: number;

  @Property()
  title: string;

  @Property()
  description?: string;

  @Property()
  text?: string;

  @OneToMany({
    entity: () => User,
    mappedBy: 'article',
    orphanRemoval: false,
  })
  authors?: new Collection<User>(this);
}
```
// call to the Article repository
```
    const articles = await this.articleRepository.findOne(
      { id },
      {
        populate: ['authors.contacts.user'],
        populateWhere: {
          authors: { contacts: { main: { $eq: true } } },
        },
      },
    );
```

I expect to get something like this:
```json

{
  "id": 1,
  "title": "any",
  "authors": [
    {
      "id": 1,
      "fullName": "Any",
      "contacts": [
        {
          "id": 1,
          "address": "Any address",
          "main": true
        },
        
      ]
    }
  ]
}
```

or if there is no primary contact

```json
{
  "id": 1,
  "title": "any",
  "authors": [
    {
      "id": 1,
      "fullName": "Any",
      "contacts": []
    }
  ]
}

```

Instead if `populateWhere` applied I got

```json

{
  "id": 1,
  "title": "any",
  "authors": []
}

```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

5.9.5

### Node.js version

18.15.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
I believe this should be working in v6, a lot has changed when it comes to how `populateWhere` works (and as such, I don't plan to backport this as parts of it are breaking).

**Comment by rybser** [comment]
> I believe this should be working in v6, a lot has changed when it comes to how `populateWhere` works (and as such, I don't plan to backport this as parts of it are breaking).

Yes, I have tested the latest version 6.1.5, it works as expected. Thanks. We can close the issue.
