### ISSUE TITLE
"loadItems()" overwrites unflushed changes

### ISSUE THREAD

**Issue by TiesB** [mikro-orm/mikro-orm#5268]
### Describe the bug

`loadItems()` overwrites unflushed changes. I think it's due to the ORM loading too much data when eager-loading relations, in some weird circular setting.

```
expect(risk.name).toBe("TestRisk");

risk.name = "Updated";
expect(risk.name).toBe("Updated");

await risk.causes.loadItems();
expect(risk.name).toBe("Updated"); // <-- this assertion fails. risk.name has reset to "TestRisk"
```

### Reproduction

[Repro repo](https://github.com/TiesB/mikro-orm-loaditems-reproduction)

### What driver are you using?

None

### MikroORM version

6.1.5

### Node.js version

18.13.0

### Operating system

Ubuntu 22.04.3 through WSL on Windows 11

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Not that it would make this invalid in any way, but the idea of having a bidirectional m:n with eager enabled on both ends is quite crazy... :]
