### ISSUE TITLE
assigning null to entityRefs do not apply to DB

### ISSUE THREAD

**Issue by DecathectZero** [mikro-orm/mikro-orm#5274]
### Describe the bug

On PG, if you assign `null` to a nullable column for an entity, it does not get applied at all.
It's very unclear how you're supposed to clear the column.

The assumed behavior is that by assigning `entityRef.nullableColumn = null` it should just apply with the flush, but it does not. I've tried with `undefined` as well.

https://mikro-orm.io/docs/5.9/type-safe-relations#assigning-to-reference-properties

### Reproduction

We have an entity with this property:
```
  @ManyToOne(() => FolderEntity, {
    name: 'folder_id',
    default: null,
    onDelete: 'cascade',
    nullable: true,
    fieldNames: ['folder_id', 'environment_id'],
  })
  folder: Ref<FolderEntity> | null = null;
```

Apply null to it, nothing happens. We need to reset the column to `null` during a data write
```      
const entityRef = this.getReference(entity);

entityRef.folder = null

await this.em.flush();
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

5.9.4

### Node.js version

Node 20

### Operating system

MacOS/Linux

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
This is a bit tricky, with entity reference you don't have the old value, so diffing ignores it. We can make it work in some cases (like this specific one, where you assign `null` and there was no value at all), to support assigning `undefined` seems to be unfortunately impossible (at least not without too much hustle or perf costs).

One alternative that could work in v6 is using a raw fragment:

```ts
const entityRef = this.getReference(entity);
entityRef.folder = sql`null`;
await this.em.flush();
```

Although I am not sure if that will help in this case, since your FK is composite. You can always use a QB for cases like this (or `em.nativeUpdate`).

**Comment by DecathectZero** [comment]
Much appreciated, makes sense the `undefined` should be ignored during diff checks, but `null` would be a fairly common use case. The fragment works.

**Comment by B4nan** [comment]
The fix I did is not ideal but it will cover what you were doing. Instead of diffing the old state, we now use the whole snapshot of the entity when it's not initialized, ignoring only its primary keys.
