### ISSUE TITLE
raw() in orderBy in decorator throws error: column [raw] does not exist

### ISSUE THREAD

**Issue by squivix** [mikro-orm/mikro-orm#5277]
### Describe the bug

When using the `raw()` helper function in the orderBy field of the decorator, it generates an invalid sql which results in an error: `column [raw] does not exist`.

Example:

```ts

@Entity()
export class EntityA {
    @PrimaryKey({type: types.integer})
    id!: number;

    @OneToMany({
        entity: () => EntityB, mappedBy: (entityB: EntityB) => entityB.entityA,
        orderBy: {
            [raw("LENGTH(text)")]: "asc"
        }
    })
    orderedEntityBs: Collection<EntityB> = new Collection<EntityB>(this);
}
```

```ts

@Entity()
export class EntityB {
    @PrimaryKey({type: types.integer})
    id!: number;

    @Property({type: types.string, length: 500})
    text!: string;

    @ManyToOne({entity: () => EntityA, inversedBy: (entityA) => entityA.entityBs, deleteRule: "cascade", updateRule: "cascade"})
    entityA!: Ref<EntityA>;
}
```

Then trying to query:
```ts
await em.find(EntityA, {}, {
        populate: ["orderedEntityBs"]
    });
```
throws error:

```txt
InvalidFieldNameException: select `e0`.*, `o1`.`id` as `o1__id`, `o1`.`text` as `o1__text`, `o1`.`entity_a_id` as `o1__entity_a_id` from `entity_a` as `e0` left join `entity_b` as `o1` on `e0`.`id` = `o1`.`entity_a_id` order by `o1`.`[raw]` asc - SQLITE_ERROR: no such column: o1.[raw]
```

Meanwhile using the same raw() in the orderBy of find functions works perfectly fine as seen in repro.

Note that `expr` in MikroORM v5 didn't have the same problem.

### Reproduction

[Repro](https://github.com/squivix/mikroorm-order-by-raw-repro)

### What driver are you using?

@mikro-orm/sqlite

### MikroORM version

6.1.6-dev.1

### Node.js version

v18.18.0

### Operating system

Linux

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by squivix** [comment]
I'm wondering why `expr()` worked before in v5 🤔? Was it implemented differently?

I like the @Formula workaround though.

**Comment by B4nan** [comment]
`expr` was always just a type helper, it didnt have any effect on runtime
