### ISSUE TITLE
SQLITE_ERROR: no such column

### ISSUE THREAD

**Issue by rmaes4** [mikro-orm/mikro-orm#530]
**Describe the bug**
I'm trying to set up unit testing for my application and I want to use Mikro ORM with a SQLITE in memory DB instead of postgres for performance reasons. My unit test is throwing an error.
**Stack trace**
```
create table `user_to_store` (`role` text check (`role` in ('owner', 'manager')) not null, primary key (`user_uuid`, `store_uuid`)); - SQLITE_ERROR: no such column: user_uuid
```

**To Reproduce**
1. user-to-store.entity.ts
```ts
export enum UserStoreRole {
  OWNER = 'owner',
  MANAGER = 'manager'
}

registerEnumType(UserStoreRole, {
  name: 'UserStoreRole'
});

@ObjectType()
@Entity()
export class UserToStore {
  @ManyToOne(() => User, { primary: true })
  user!: User;

  @ManyToOne(() => Store, { primary: true })
  store!: Store;

  @Field((type) => UserStoreRole)
  @Enum()
  role!: UserStoreRole;

  [PrimaryKeyType]: [string, string];
}
```
2. user.service.spec.ts
```ts
...
MikroOrmModule.forRoot({
          type: 'sqlite',
          dbName: ':memory:',
          entitiesDirs: ['dist/entities'],
          entitiesDirsTs: ['src/entities'],
          debug: true
        })
...
```
3. ...

**Expected behavior**
I expect the entity to work with both PostgreSQL and SQLite given that I am not using any postgres-specific types

**Additional context**
I am using the default Jest setup with NestJS

**Versions**

| Dependency | Version |
| - | - |
| node | 12.14.1 |
| typescript | ^3.7.4 |
| mikro-orm | ^3.6.12 |
| sqlite3 | ^4.2.0 |
| nestjs | ^7.0.0 |
| nestjs-mikro-orm | ^1.0.3 |
| jest | ^25.1.0 |

**Comment by B4nan** [comment]
This is caused by sqlite itself, as there it is not possible to 

1. create FKs when altering columns
2. create empty tables without column

I could get around this only if we drop FKs on sqlite altogether.

**Comment by rmaes4** [comment]
Hmm ok I guess I will use a separate test DB in Postgres

**Comment by lookfirst** [comment]
I came to the conclusion that we can't expect sqlite to be postgres. No point in banging heads against the differences.

**Comment by rmaes4** [comment]
Makes sense. I liked the speed of the in memory sqlite but it's probably better to test against the same DB as production.

**Comment by lookfirst** [comment]
Agreed as well, but unfortunately, this caused a bug that showed up in production that didn't get hit in my local tests. Lesson learned. =)
