### ISSUE TITLE
Invalid SQL query for ManyToMany relations using some, none or every when querying

### ISSUE THREAD

**Issue by NicklasKnell** [mikro-orm/mikro-orm#5301]
### Describe the bug

Using a query operator like $some, $none or $every on a ManyToMany relation results in an invalid query, if the Entities start with the same Letter.

This error is from the provided reproduction:
```sql
select count(*) as "count"
from "user" as "u0"
where
    "u0"."id" in (
        select "u0"."id"
        from
            "user" as "u0"
            left join "user_labels" as "u1" on "u0"."id" = "u1"."user_id"
            inner join "public"."user_label" as "u1" on "u1"."user_label_id" = "u1"."id"
        where
            "u1"."user_label_id" = 1
    )
```
**_table name "u1" specified more than once_**

### Reproduction

I used docker compose to start a postgresql instance.
https://github.com/NicklasKnell/reproduction/tree/illegal-query-for-manytomany

When renaming the Entity UserLabel to Label it will work.

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.1.5

### Node.js version

v20.11.0

### Operating system

Ubuntu

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
I guess I see it, we clone the QB (which resets the alias counter), but then use the original QB instance to get the next alias [here](https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/query/ObjectCriteriaNode.ts#L46).
