### ISSUE TITLE
Filter with Embeddable array leads to InvalidFieldNameException

### ISSUE THREAD

**Issue by mlbonniec** [mikro-orm/mikro-orm#5310]
### Describe the bug

Hi :) I found an interesting bug with Mikro-ORM, Filters and Embeddable.
_Not too much interesting, because it's blocking my company._

To make it short, I'll explain myself based on the reproduction.

## Structure

I've 3 entities.  
* `Instance` which is the "application" where an entity belongs to.
* `Item` which is a product.
* `Cart` which is a cart of `Item`.

`Item` are stored as an array in `Cart` using an `Embeddable` to allow specifying the quantity.

## Issue

Once is apply the `Filter` decorator to my base class, I've got a `no such column: c0.item_id`.
The bug is present when:
* `items` embed is an array. When it's a single item, there's no issue.
* A filter is applied to query

The bug is not present when:
* I add `fields: ['*']` into the query. Isn't that the default value ?

## The full error (_from the reproduction_)
```bash
InvalidFieldNameException: select `c0`.*, `i1`.`id` as `item_id` from `cart` as `c0` left join `item` as `i1` on `c0`.`item_id` = `i1`.`id` left join `instance` as `i2` on `i1`.`instance_id` = `i2`.`id` - SQLITE_ERROR: no such column: c0.item_id
```

## Notes

> [!NOTE]
> The issue is present with the `sqlite` driver, but my project is using `postgresql` and I've the same issue.

> [!NOTE]
> There's no need to have data in the database. Just a basic `findAll()`, `findOne()` etc. is enough to have the error.

### Reproduction

```ts
import { Entity, MikroORM, PrimaryKey, Property, Embeddable, ManyToOne, Embedded, Collection, Filter } from '@mikro-orm/sqlite';

@Entity()
class Instance {
  @PrimaryKey()
  id!: number;

  @Property()
  slug: string;

  constructor(slug: string) {
    this.slug = slug;
  }
}

@Filter({ name: 'instance', cond: (args) => ({ instance: { slug: args.slug } }), default: true })
class CommonEntity {
  @ManyToOne(() => Instance)
  instance: Instance;

  constructor(instance: Instance) {
    this.instance = instance;
  }
}

@Entity()
class Item extends CommonEntity {
  @PrimaryKey()
  id!: number;

  @Property()
  name: string;

  constructor(instance: Instance, name: string) {
    super(instance);
    this.name = name;
  }
}

@Embeddable()
class CartItem {
  @ManyToOne(() => Item)
  item: Item;

  @Property()
  quantity: number;

  constructor(item: Item, quantity: number) {
    this.item = item;
    this.quantity = quantity;
  }
}

@Entity()
class Cart extends CommonEntity {
  @PrimaryKey()
  id!: number;

  @Embedded(() => CartItem, { array: true, nullable: true })
  items: CartItem[];

  constructor(instance: Instance, items: CartItem[]) {
    super(instance);
    this.items = items;
  }
}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    dbName: ':memory:',
    entities: [
      Instance,
      Item,
      Cart,
    ],
    debug: ['query', 'query-params'],
    allowGlobalContext: true,
  });
  await orm.schema.refreshDatabase();
});

afterAll(async () => {
  await orm.close(true);
});

test('setFilterParams x findAll', async () => {
  orm.em.setFilterParams('instance', { slug: 'demo' });

  await orm.em.findAll(Cart);
});
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.1.8

### Node.js version

v21.6.1

### Operating system

macOS 14.3.1 (23D60)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
As a workaround, you can add `autoJoinRefsForFilters: false` to your config now. This is caused by the changes in v6 which automatically joins to-one relations with filters, as the filters could result in your FK pointing to an entity that cannot be fetched (so it gets replaced with `null` automatically).

https://mikro-orm.io/docs/filters#filters-and-relationships

**Comment by mlbonniec** [comment]
Oh okay!

This is fixing the issue on the reproduction, but only a part of my real project.

My cart has `coupons` and `items` properties, and I'd like to populate it.

**Working**
```ts
return await this.cartRepository.findOneOrFail({ id }, {
  populate: ['items.item']
});
```

**Working**
```ts
return await this.cartRepository.findOneOrFail({ id }, {
  populate: ['coupons']
});
```

**Not working**
I got the same error as previously. `InvalidFieldNamException`, even with the `autoJoinRefsForFilters: false`
```ts
return await this.cartRepository.findOneOrFail({ id }, {
  populate: ['items.item', 'coupons']
});
```

**Comment by mlbonniec** [comment]
For your information, this workaround works.
The `populate` is specified after the query, and not inside the `options` parameter.

```ts
const cart = await this.cartRepository.findOneOrFail({ id });

await this.cartRepository.populate(cart, ['coupons', 'items.item']);

return cart;
```

**Comment by B4nan** [comment]
So what is that `coupons` property? It's not present in your repro.
