### ISSUE TITLE
Formulas no longer working when querying across ManyToMany relationship

### ISSUE THREAD

**Issue by mareksuscak** [mikro-orm/mikro-orm#5319]
### Describe the bug

It seems that MikroORM breaks formulas which are no longer pulled across a ManyToMany relationship. See the example below.

### Reproduction

Consider the following 3 entities:

```ts
@Entity()
export class User {
  @Property({ type: t.text, nullable: true })
  firstName?: string;

  @Property({ type: t.text, nullable: true })
  lastName?: string;

  @Formula((alias) => `CONCAT(${alias}.first_name, ' ', ${alias}.last_name)`)
  fullName?: string;

  @Formula((alias) => `LOWER(${alias}.email)`)
  emailLower?: string;
}

@Entity()
export class PageRevision {
  @ManyToMany({
    entity: () => User,
    inversedBy: (user) => user.pageRevisions,
    owner: true,
    pivotEntity: () => PageRevisionUser,
  })
  users?: Collection<User> = new Collection<User>(this);
}

@Entity()
export class PageRevisionUser {
  @ManyToOne(() => PageRevision, {
    primary: true,
    fieldName: 'page_revision_id',
    onUpdate: () => 'cascade',
    onDelete: 'cascade',
  })
  pageRevision: PageRevision;

  @ManyToOne(() => User, {
    primary: true,
    fieldName: 'user_id',
    onUpdate: () => 'cascade',
    onDelete: 'cascade',
  })
  user: User;
}
```

Now consider the following query:

```ts
const revision = await this.pageRevisionRepository.findOne(where, {
  populate: ['users'],
});
```

Below is the generated SQL query:

```sql
-- Mikro ORM 5.9.x
-- Notice the two formulas
SELECT
	"u0".*,
	CONCAT("u0".first_name, ' ', "u0".last_name) AS "full_name",
	LOWER("u0".email) AS "email_lower",
	"p1"."user_id" AS "fk__user_id",
	"p1"."page_revision_id" AS "fk__page_revision_id"
FROM
	"user" AS "u0"
	LEFT JOIN "page_revision_user" AS "p1" ON "u0"."id" = "p1"."user_id"
WHERE
        "p1"."page_revision_id" in('018e1bb2-a8e0-81f6-c008-6811fe9d6c63')
```

```sql
-- Mikro ORM 6.x.x
-- Note that formulas are no longer included
SELECT
	"u1".*,
	"p0"."user_id" AS "fk__user_id",
	"p0"."page_revision_id" AS "fk__page_revision_id"
FROM
	"page_revision_user" AS "p0"
	INNER JOIN "public"."user" AS "u1" ON "p0"."user_id" = "u1"."id"
WHERE
	"p0"."page_revision_id" in('018e1bb2-a8e0-81f6-c008-6811fe9d6c63')
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.1.8

### Node.js version

20.x

### Operating system

MacOS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mareksuscak** [comment]
Let me know if you need a minimum reproducible example. I can put something together but had to significantly simplify the above classes because it comes from a fairly complex app with many more properties. I was hoping that it might be an obvious use case to replicate and fix.

**Comment by B4nan** [comment]
> Let me know if you need a minimum reproducible example

I always need one :)

**Comment by mareksuscak** [comment]
Yes, we are on v6 and yes it does compile. I'll put together a repro.

**Comment by B4nan** [comment]
> Yes, we are on v6 and yes it does compile.

Your screenshot is not the same as what you have put into the issue description. Note the `deleteRule` (on screenshot) vs `onDelete` (in the issue).

**Comment by mareksuscak** [comment]
Sorry, I simplified the entities and I must have based them on a different branch or something. What's in the screenshot is right.

**Comment by B4nan** [comment]
Here is a passing repro, let's reopen with a failing one:

```ts
import { Entity, MikroORM, Property, ManyToOne, Collection, ManyToMany, Formula, PrimaryKey } from '@mikro-orm/sqlite';
import { mockLogger } from '../../helpers';

@Entity()
class User {

  @PrimaryKey()
  id!: number;

  @Property({ nullable: true })
  firstName?: string;

  @Property({ nullable: true })
  lastName?: string;

  @Property({ nullable: true })
  email?: string;

  @Formula(alias => `CONCAT(${alias}.first_name, ' ', ${alias}.last_name)`)
  fullName?: string;

  @Formula(alias => `LOWER(${alias}.email)`)
  emailLower?: string;

}

@Entity()
class PageRevision {

  @PrimaryKey()
  id!: number;

  @ManyToMany({
    entity: () => User,
    pivotEntity: () => PageRevisionUser,
  })
  users = new Collection<User>(this);

}

@Entity()
class PageRevisionUser {

  @ManyToOne(() => PageRevision, { primary: true })
  pageRevision!: PageRevision;

  @ManyToOne(() => User, { primary: true })
  user!: User;

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    dbName: ':memory:',
    entities: [PageRevision, User, PageRevisionUser],
    debug: true,
  });
  await orm.schema.refreshDatabase();
});

afterAll(async () => {
  await orm.close(true);
});

test('GH #5319', async () => {
  const mock = mockLogger(orm);
  await orm.em.findAll(PageRevision, { populate: ['users'] });
  expect(mock.mock.calls[0][0]).toMatch('select `p0`.*, `u1`.`id` as `u1__id`, `u1`.`first_name` as `u1__first_name`, `u1`.`last_name` as `u1__last_name`, `u1`.`email` as `u1__email`, CONCAT(`u1`.first_name, \' \', `u1`.last_name) as `u1__full_name`, LOWER(`u1`.email) as `u1__email_lower` ' +
    'from `page_revision` as `p0` ' +
    'left join `page_revision_user` as `p2` on `p0`.`id` = `p2`.`page_revision_id` ' +
    'left join `user` as `u1` on `p2`.`user_id` = `u1`.`id`');
});
```

**Comment by mareksuscak** [comment]
Just following up on this one. I don't know what happened but this issue seems resolved and formulas work fine again in the latest release `6.2.1`. We skipped the last few minor releases due to various subtle issues introduced in v6 that we had to work around in various ways but this last release seems to have fixed at least some of them, thank you!
