### ISSUE TITLE
Enum Array doesn't work with nativeEnumName

### ISSUE THREAD

**Issue by NeelDigonto** [mikro-orm/mikro-orm#5322]
### Describe the bug

Enum Array doesn't work with nativeEnumName

### Reproduction

```ts
  @Enum({
    items: () => TenantFeatureFlag,
    array: true,
  })
  tenantFeatureFlags: TenantFeatureFlag[];
```
This creates 

```sql
"tenantFeatureFlags" text[] not null
```

```ts
  @Enum({
    items: () => TenantFeatureFlag,
    array: true,
    nativeEnumName: 'TenantFeatureFlag',
  })
  tenantFeatureFlags: TenantFeatureFlag[];
```

But this produces

```sql
"tenantFeatureFlags" "TenantFeatureFlag" not null
```
It's missing the `[]` after TenantFeatureFlag.

The update query then fails with

`DriverException ...   '{feat1, feat2}' ... - invalid input value for enum "TenantFeatureFlag": "{feat1,feat2}"`

Using Reflect Metadata, and swc with the recommended settings.

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "target": "esnext",
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "sourceMaps": true
}
```

I can provide more reproduction, if the bug is not obvious.

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.1.6

### Node.js version

20.11.1 LTS

### Operating system

Ubuntu 23.04

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
This might be a bit tricky, it feels like knex does not support native enum arrays at all, haven't found a single issue on their end, and I don't see a way to even set up such a column (only via `table. specificType()`, which is kinda the same as using raw queries...).

This does not mean there is no way around it, but it complicates things - we will need to implement some things that knex is doing (but better, lol), so we don't use `table.enum()` at all for native enum arrays.

**Comment by NeelDigonto** [comment]
@B4nan Thank you so much for the wuick updates.
I will test them tomorrow.

**Comment by NeelDigonto** [comment]
@B4nan 
I tried it now,

1. With `getCreateSchemaSQL()` as in your mock, the returned SQL is correct and as expected.
2. With `getUpdateSchemaSQL()` the enum creation SQL is itself not present, but it is correctly references for ex. as `TenantFeatureFlag[]`.
3. With `migration create` from `Migrator`, again enum creation is itself not present in the SQL but reference correctly.

**Comment by B4nan** [comment]
I knew it will be more tricky :D

**Comment by NeelDigonto** [comment]
@B4nan Will test again once it's released.

**Comment by B4nan** [comment]
Btw you can test the dev version already, every commit to master gets published.
