### ISSUE TITLE
Add an option to ignore nested entities when using assign

### ISSUE THREAD

**Issue by acrosett** [mikro-orm/mikro-orm#5327]
**Is your feature request related to a problem? Please describe.**
When assigning content to new/existing entities, nested entities are exposed (see exemple below)

**Describe the solution you'd like**
An option passed to the assign fonction that make it ignore nested entities (no creation/update of relations). However it would allow us to change the ID (when updating the owning side).

**Describe alternatives you've considered**
We can validate the payload that is assigned to the entity, however it is not secure by default if a decorator is forgotten. I would like to disable that feature entirely.

**Additional context**
This exemple (with `updateNestedEntities:false`) create two nail object in DB. I would like the new nails to be ignored.

```typescript
@Entity()
export class Box {
    @PrimaryKey({ name: '_id'})
    id: ObjectId;

    @Property()
    name: string;

    @OneToMany(() => Nail, mel => mel.box)
    nails = new Collection<Picture>(this);
}

@Entity()
export class Nail {
    @PrimaryKey({ name: '_id'})
    @IsString()
    @IsOptional()
    id: ObjectId;

    @ManyToOne(() => Box)
    box: Box | string;

    @Property()
    size: number;
}
```

```typescript
    let em = entityManager.fork();
    const payload = {
      id: new ObjectId() as any,
      name: "My nail box",
      nails: [
        {
          id: new ObjectId() as any,
          size: 10
        }
      ]
    }
    const entity = new Box();
    wrap(entity).assign(payload as any, { em, updateNestedEntities:false, mergeObjectProperties: true, onlyProperties: true });

    const res = await em.persistAndFlush(entity);

    const payload2 = {
      id: payload.id,
      name: "Renamed Box",
      nails: [
        {
          id: new ObjectId() as any,
          size: 99
        },
      ]
    }

    em = entityManager.fork();

    const dbEntity = await em.getReference(Box, payload.id);

    wrap(dbEntity).assign(payload2 as any, { em, updateNestedEntities:false, mergeObjectProperties: true, onlyProperties: true });
    await em.flush();
```

    "@mikro-orm/core": "^6.1.6",
    "@mikro-orm/mongodb": "^6.1.6",
    
    node version : 18.15.0

**Comment by B4nan** [comment]
So maybe something like `onlyOwnProperties: true`? I don't want to change the behavior of `updateNestedEntities: false` as that feels breaking.

Sounds like an easy change, would you be up for a PR yourself?
