### ISSUE TITLE
nativeDelete fails with persist: false

### ISSUE THREAD

**Issue by montycb** [mikro-orm/mikro-orm#5334]
### Describe the bug

I've linked two entities through the ManyToOne/OneToMany decorators. In the configuration, I've set persist: false along with a field name. However, I've encountered a problem where I can't use nativeDelete on this relationship. It appears that the resulting delete statement doesn't correctly reference the column. I've included a test case to demonstrate this issue. It's worth noting that in this case, using the persist flag isn't necessary, but due to project requirements, I must rely on persist: false.

### Reproduction

```ts
import { Collection, Entity, ManyToOne, MikroORM, OneToMany, PrimaryKey, Property, Ref } from '@mikro-orm/sqlite';

@Entity()
class EntityA {

  @PrimaryKey()
  id!: number;

  @OneToMany(() => EntityB, 'a')
  bs = new Collection<EntityB>(this)
}

@Entity()
class EntityB {
  @PrimaryKey()
  id!: number;

  @Property()
  test!: string

  @ManyToOne(() => EntityA, { fieldName: 'id', persist: false })
  a = new Collection<EntityA>(this)
}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    dbName: ':memory:',
    entities: [EntityA, EntityB],
    debug: ['query', 'query-params'],
    allowGlobalContext: true, // only for testing
  });
  await orm.schema.refreshDatabase();
});

afterAll(async () => {
  await orm.close(true);
});

test('delete entity from persist false relation', async () => {
  orm.em.create(EntityA, {
    bs: [{test: 'qwer'}, {test: 'asdf'}, {test: 'yxcv'}]
  }, {persist: true})

  await orm.em.flush()

  await orm.em.nativeDelete(EntityB, {a: 1}) // delete from `entity_b` where `e0`.id = 1 - SQLITE_ERROR: no such column: e0.id

});
```

### What driver are you using?

@mikro-orm/sqlite

### MikroORM version

6.1.10-dev.10

### Node.js version

v20.10.0

### Operating system

Linux

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Hmm, that must be coming from 20a4cfb005fed168786d0da806d1c89e29b6f4ab
