### ISSUE TITLE
Type mismatch between class Migration and interface Migration

### ISSUE THREAD

**Issue by montycb** [mikro-orm/mikro-orm#5340]
Migrations are generated using the Migration class from mikro-orm/migrations. This class defines these two methods:

```ts
abstract up(): Promise<void> | void;
down(): Promise<void> | void;
```

However, when initializing MikroORM and specifying migrations using the migrationsList property, it expects a MigrationObject. This object utilizes the Migration interface for its class definition, which is defined as follows:

```ts
up(): Promise<void>;
down(): Promise<void>;
```

While the Migration class allows both asynchronous and synchronous implementations for up and down methods, the interface used during initialization does not permit synchronous implementations. Is this intended?

**Comment by B4nan** [comment]
PR welcome
