### ISSUE TITLE
Automatic migration generation creates new changes even if schema is up to date

### ISSUE THREAD

**Issue by stad-nico** [mikro-orm/mikro-orm#5363]
### Describe the bug

AFAIK there is no other way to define sql on update and on create (=default value) expressions in an entities column besides using `defaultRaw: 'current_timestamp() on update current_timestamp()'`.
This seems to generate the correct sql code.

However, using this workaround to create a migration, using `mikro-orm migration:fresh` to migrate to the latest version and then generating a new migration using `mikro-orm migration:create` creates a new migration with the following sql statements instead of skipping generation and displaying the message "No changes required, schema is up-to-date":

```sql
'alter table `<entity name>` modify `updatedAt` datetime not null default current_timestamp() on update current_timestamp();'
```

Migrating to the latest schema including this additional migration still does not fix this issue. `mikro-orm migration:create` still creates a new migration identical to the  previous one.

### Reproduction

1. Create an entity definition with a column with `defaultRaw: 'current_timestamp() on update current_timestamp()'`:

```ts
@Entity({tableName: "test")
export class TestEntity {
    @Property({ type: 'datetime', nullable: false, defaultRaw: 'current_timestamp() on update current_timestamp()' })
    readonly updatedAt!: Date;
}
```

2. Create an initial migration:
`mikro-orm migration:generate`

3. Migrate to the latest changes:
`mikro-orm migration:fresh`

4. Create another migration (this one will contain the sql alter code):
`mikro-orm migration:generate`

5. Again, migrate to the latest changes:
`mikro-orm migration:fresh`

6. Create yet another migration (this one will again contain the exact same sql alter code):
`mikro-orm migration:generate`

### What driver are you using?

@mikro-orm/mariadb

### MikroORM version

6.1.4

### Node.js version

v19.6.0

### Operating system

Windows 10

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
> AFAIK there is no other way to define sql on update and on create (=default value) expressions in an entities column besides using defaultRaw: 'current_timestamp() on update current_timestamp()'.
This seems to generate the correct sql code.

You want this:

```ts
@Property({ type: 'datetime', defaultRaw: `current_timestamp()`, extra: `on update current_timestamp()` })
updatedAt!: Date;
```

Here is a passing test case:

```ts
import { Entity, PrimaryKey, Property } from '@mikro-orm/core';
import { MikroORM } from '@mikro-orm/mariadb';

@Entity({ tableName: 'book' })
export class Book1 {

  @PrimaryKey()
  id!: number;

  @Property({ type: 'datetime', defaultRaw: `current_timestamp()` })
  createdAt!: Date;

  @Property({ type: 'datetime', defaultRaw: `current_timestamp()`, extra: `on update current_timestamp()` })
  updatedAt!: Date;

}

@Entity({ tableName: 'book' })
export class Book2 {

  @PrimaryKey()
  id!: number;

  @Property({ type: 'datetime', defaultRaw: `current_timestamp()` })
  createdAt!: Date;

  @Property({ type: 'datetime', defaultRaw: `current_timestamp()` })
  updatedAt!: Date;

}

@Entity({ tableName: 'book' })
export class Book3 {

  @PrimaryKey()
  id!: number;

  @Property({ type: 'datetime', defaultRaw: `current_timestamp()` })
  createdAt!: Date;

  @Property({ type: 'datetime', defaultRaw: `current_timestamp()`, extra: `on update current_timestamp()` })
  updatedAt!: Date;

}

describe('changing column in mysql (GH 5363)', () => {

  let orm: MikroORM;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [Book1],
      dbName: `mikro_orm_test_gh_5363`,
      port: 3309,
    });
    await orm.schema.refreshDatabase();
  });

  afterAll(() => orm.close(true));

  test('schema generator respect indexes on FKs on column update', async () => {
    const diff0 = await orm.schema.getUpdateSchemaSQL({ wrap: false });
    expect(diff0).toBe('');
    orm.getMetadata().reset('Book1');
    await orm.discoverEntity(Book2);
    const diff1 = await orm.schema.getUpdateSchemaSQL({ wrap: false });
    expect(diff1).toBe('alter table `book` modify `updated_at` datetime not null default current_timestamp();\n\n');
    await orm.schema.execute(diff1);

    orm.getMetadata().reset('Book2');
    await orm.discoverEntity(Book3);
    const diff3 = await orm.schema.getUpdateSchemaSQL({ wrap: false });
    expect(diff3).toBe('alter table `book` modify `updated_at` datetime not null default current_timestamp() on update current_timestamp();\n\n');
    await orm.schema.execute(diff3);
  });

});
```
