### ISSUE TITLE
Maximum call stack exceed with double $none operator

### ISSUE THREAD

**Issue by axotion** [mikro-orm/mikro-orm#5368]
### Describe the bug

When using two $none operators in one smart collection query,

```typescript
 return this.ownerRepository.find({
      dogs: {
        $none: {},
      },
      cats: {
        $none: {},
      },
    });
```

 we got following error

```
DriverException: Maximum call stack size exceeded
app-1       |     at MySqlExceptionConverter.convertException (/usr/src/app/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
app-1       |     at MySqlExceptionConverter.convertException (/usr/src/app/node_modules/@mikro-orm/mysql/MySqlExceptionConverter.js:80:22)
app-1       |     at MySqlDriver.convertException (/usr/src/app/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:326:54)
app-1       |     at /usr/src/app/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:330:24
app-1       |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
app-1       |     at MySqlDriver.find (/usr/src/app/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:68:24)
app-1       |     at SqlEntityManager.find (/usr/src/app/node_modules/@mikro-orm/core/EntityManager.js:144:25)
app-1       |     at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
app-1       |     at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
app-1       | 
app-1       | previous RangeError: Maximum call stack size exceeded
app-1       |     at Function.processParams (/usr/src/app/node_modules/@mikro-orm/core/utils/QueryHelper.js:11:25)
app-1       |     at /usr/src/app/node_modules/@mikro-orm/core/utils/QueryHelper.js:34:37
app-1       |     at Array.forEach (<anonymous>)
app-1       |     at Function.processObjectParams (/usr/src/app/node_modules/@mikro-orm/core/utils/QueryHelper.js:33:36)
app-1       |     at Function.processParams (/usr/src/app/node_modules/@mikro-orm/core/utils/QueryHelper.js:28:25)
app-1       |     at /usr/src/app/node_modules/@mikro-orm/core/utils/QueryHelper.js:34:37
app-1       |     at Array.forEach (<anonymous>)
app-1       |     at Function.processObjectParams (/usr/src/app/node_modules/@mikro-orm/core/utils/QueryHelper.js:33:36)
app-1       |     at Function.processParams (/usr/src/app/node_modules/@mikro-orm/core/utils/QueryHelper.js:28:25)
app-1       |     at /usr/src/app/node_modules/@mikro-orm/core/utils/QueryHelper.js:25:51
```

### Reproduction

https://github.com/axotion/mikro-orm-repro-collection

In order to reproduce bug, you have to run docker-compose up on repository and call GET /, then error will appear

### What driver are you using?

@mikro-orm/mysql

### MikroORM version

6.1.11 core and mysql

### Node.js version

21

### Operating system

MacOS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
> In order to reproduce bug, you have to run docker-compose up on repository and call GET /, then error will appear

Next time please don't use webservers for reproductions that has nothing to do with webservers.

Got this reproduced in isolation, so no need for another repro here.
