### ISSUE TITLE
Inintended caching of EntityManager by EntityRepository from within a transactional context

### ISSUE THREAD

**Issue by hesalx** [mikro-orm/mikro-orm#5395]
### Describe the bug

According to the docs (https://mikro-orm.io/docs/identity-map#how-does-requestcontext-helper-work) it should be pefectly safe to use a more "global" EM instance from within a transactional or request context (i.e. not having to pass down the EM instance passed to the transaction callback).

However, this expectation breaks in at least one specific scenario that is very easy to replicate.

When the **first time** a repository is accessed is within a transaction but from the "outside" EM instance (the one on which `.transactional` was called) then the repository will get "stuck" with the transaction-specific EM instance (can be verified by comapring `em.id`) which in the best case leads to `DriverException: Transaction query already complete` and in the worst case can cause data corruption due to improper isolation.

This problem can occur naturally when using MikroORM with NestJS and having services that call one another while each relies primarily on the (global) injected EM instance.

It is worth noting that `.getContext()` on the "stuck" EM instance is a no-op and returns self, thus the repository is corrupted for the entire lifetime of the application process.

### Reproduction

Reproduction:
```typescript
const orm = await MikroORM.init({});
// EM like the one injected in NestJS
const em = orm.em.fork({ useContext: true });
await em.transactional(async _ => {
    // this could happen in a nested service without access to tx-specific EM
    await em.getRepository(Post).find({id: 1});
});
// some time later, even in a different request
await em.getRepository(Post).find({id: 1}); 
// ^ DriverException: Transaction query already complete, run with DEBUG=knex:tx for more info

// the following does not work anymore, the EM of this repo is forever "stuck"
await em.getRepository(Post).getEntityManager().getContext().find(Post, {id: 1}); 

// em.id !== em.getRepository(Post).getEntityManager().id 
```

If the repository happened to be accessed prior to a transaction, the issue does not happen:
```typescript
const orm = await MikroORM.init({});
const em = orm.em.fork({ useContext: true });
// First repo access is outside a transaction
await em.getRepository(Post).find({id: 1});
await em.transactional(async _ => {
    await em.getRepository(Post).find({id: 1});
});
await em.getRepository(Post).find({id: 1}); // works!
// em.id === em.getRepository(Post).getEntityManager().id 
```

Using tx-specific instance or explicitly calling `.getContext()` inside the transaction also resolves the issue:
```typescript
const orm = await MikroORM.init({});
const em = orm.em.fork({ useContext: true });
await em.transactional(async emtx => {
    await emtx.getRepository(Post).find({id: 1});
    await em.getContext().getRepository(Post).find({id: 1});
});
await em.getRepository(Post).find({id: 1}); // works!
// em.id === em.getRepository(Post).getEntityManager().id 
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.1.12

### Node.js version

18.16.0

### Operating system

MacOS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
That's funny, the commit that broke this (af87693aae0c1a4bf95d4ad3f78e81a96439dded) was trying to fix the exact same error (#3074). Will need to reread that thread, as reverting this would probably break some other case...

**Comment by hesalx** [comment]
It is worth noting that the aforementioned https://github.com/mikro-orm/mikro-orm/commit/af87693aae0c1a4bf95d4ad3f78e81a96439dded explicitly states "do not use context in em.getRepository()", however it is still used there (v6.1.12) and was added by https://github.com/mikro-orm/mikro-orm/commit/b5b03a61dbe1898a10ce8243d517a200fc8bcadf#diff-a62cd78c400d99253a3c0fb5a9bf26e1e63e0deb511059d28ba51014b58242ddR146 but the change does not seem related to the commit's intention.

**Comment by ashleyww93** [comment]
Could this be causing other unintended consequences?

I’m currently trying to track down an issue(so I can make a reproduction) where entities are deleted and recreated with the same ID.

I thought it was an issue our side (and might be), but it’s seemingly random, like the identity map is incorrect on some occasions.

**Comment by hesalx** [comment]
@ashleyww93 You can override `.getRepository()` with a custom EM to be able to get visibility into any occurence of this specific issue. Feel free to just log instead of a hard error.
```typescript
// replace `PostgreSqlDriver` with you respective driver
export class ExtendedEntityManager extends EntityManager<PostgreSqlDriver> {
  public getRepository<Entity extends object>(entityName: EntityName<Entity>) {
    const repository = super.getRepository(entityName);
    const currentContext = this.id;
    const repoContext = repository.getEntityManager().id;
    if (currentContext !== repoContext) {
      throw new Error(
        `EntityRepository<${repository.getEntityName()}> context (${repoContext}) did not match the current EntityManager context (${currentContext})!`,
      );
    }
    return repository as any;
  }
}
```

```typescript
defineConfig({
  // ...
  entityManager: ExtendedEntityManager,
});
```
Docs: https://mikro-orm.io/docs/entity-manager#extending-entitymanager

**Comment by hesalx** [comment]
@ashleyww93 If this issue is the culprit of your problem, it may appear random because it requires the first `.getRepository()` call in the app process to be inside a transaction. After a server restart it may be completely up to chance whether it happens this way.

**Comment by B4nan** [comment]
> It is worth noting that the aforementioned https://github.com/mikro-orm/mikro-orm/commit/af87693aae0c1a4bf95d4ad3f78e81a96439dded explicitly states "do not use context in em.getRepository()", however it is still used there (v6.1.12) and was added by https://github.com/mikro-orm/mikro-orm/commit/b5b03a61dbe1898a10ce8243d517a200fc8bcadf#diff-a62cd78c400d99253a3c0fb5a9bf26e1e63e0deb511059d28ba51014b58242ddR146 but the change does not seem related to the commit's intention.

Yeah correct, and reverting this bit is not making any of the existing tests fail, I guess I will go with that, worst case we will revert it, but I agree it looks unrelated to the commit. That change also makes the e2e test suite of the real-world app pass, so it feels safe.

**Comment by hesalx** [comment]
@B4nan Awesome! Thanks.

Any chance the test suite can be amended with a case like this?
```typescript
await em.transactional(async _ => {
    // first even call to a repository, em is not tx-specific
    await em.getRepository(Post).find({id: 1});
});
assert.equal(em.id, em.getRepository(Post).getEntityManager().id)
```

**Comment by B4nan** [comment]
Yeah, for sure, I will include the repro from OP.

**Comment by tmikoss** [comment]
@B4nan any chance on a v5 backport? I'm seeing this same issue, and v6 upgrade is proving to be surprisingly hard due to changes in `date` type handling.

**Comment by B4nan** [comment]
> and v6 upgrade is proving to be surprisingly hard due to changes in date type handling.

If you mean that dates are no longer mapped to `Date` objects, you can create the very same mapped type as in v5 and use it in v6 too.

**Comment by tmikoss** [comment]
@B4nan I did try that - copied the v5 type to my codebase, and used that. It mostly worked, except one condition - composite primary keys with dates. With UTC+ time zones, it would break updates.

Where v5 would issue `update table set ... where id = 123 and date = '2024-06-19'`, in v6 even with v5 `DateType`, it would become `update table set ... where id = 123 and date = '2024-06-18T18:00:00Z'`.

With UTC / UTC- time zones the bug is not readily apparent, because date part stays the same when converting to UTC, and postgres drops the time partition when writing to date - as a result, you get expected values there.

Is it possible that conditions for update statements skip custom types, and just run the data through the default serializer?

Does this sound familiar, or should I make a reproduction repo?

**Comment by B4nan** [comment]
Repro welcome, nobody complained so far.

**Comment by tmikoss** [comment]
@B4nan https://github.com/tmikoss/reproduction/tree/v6-date-type-repro here you go. Seems not to be an issue with sqlite, only postgres. Two samples, one with unmodified v5, one with my best attempt at fixing it.

**Comment by B4nan** [comment]
The problem here is that v6 handles date parsing early, during result mapping, and since your property runtime type is `Date`, this mechanism kicks in. The type ignored timezones (same in v5), that's the first issue, which starts the cascade down the path. It did work with v5 because we did the date parsing later, during hydration, and I think it was skipped completely for the `DateType`.

You can disable the date parsing done by the ORM by setting the `runtimeType` option to something else than `Date` (`string` should be safe).

```ts
@PrimaryKey({ type: DateType, runtimeType: 'string' })
date!: Date;
```

You could just define a `get runtimeType(): string` on the type itself, but that is apparently not respected now and the type we get via reflect-metadata is preferred, will try to fix that when I have some spare time.

You still get the UTC date, but that works the same in v5 and can be fixed in the type implementation. Btw this whole mess with timezones was exactly the motivation to change this and keep strings at runtime :] 

---

I want to take a closer look at the how/why and compare more with v5, but my time is quite limited this month.
