### ISSUE TITLE
Minor type issue: em.fork does not use entityManager type set by MikroORM.init

### ISSUE THREAD

**Issue by briankchan** [mikro-orm/mikro-orm#5415]
### Describe the bug

`em.fork` has a return type of `Driver[typeof EntityManagerType]`, which does not account for custom entity managers set by
```
MikroORM.init({
  entityManager: MyEntityManager,
})
```

Changing `fork`'s return type to return `this` should fix this issue, but I'm not sure if it'll break the types somewhere else.

### Reproduction

https://github.com/briankchan/mikro-orm-bug-entitymanager-type

Both tests pass, but the tsc build fails.

### What driver are you using?

None

### MikroORM version

6.1.13-dev.21

### Node.js version

v18.17.1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Good catch, thanks!
