### ISSUE TITLE
Question: SQL Injection

### ISSUE THREAD

**Issue by ALITHEALI** [mikro-orm/mikro-orm#542]
Hello, 

First of all, thanks a lot for this awesome and feature-rich package. I am working on an app which its security is one of its core features and as I was running `schema:update`, I noticed an error which was saying `"syntax error .0"` now I wasn't sure about the error but I later on I realised that it's because I had:

```ts
@Property({default: '0.0.0.0'})
IP?: string;
``` 
and it was throwing an error because it was not escaping `'0.0.0.0'` as String in the process of migration.
Now, I wanted to see if this package is safe from SQL injection based on the abovementioned factor? 

Once again thanks a lot for your amazing work on this package.

**Comment by B4nan** [comment]
`default` is used as is, so what you have there is just a misconfiguration. You need to wrap string values in quotes yourself. 

`@Property({ default: "'0.0.0.0'" })`

This is to allow things like `@Property({ default: 'now()' })`. 

All runtime queries (`e.g. produced by `em.flush()`) are executed as prepared statements, this is done via knex, so they are safe.

**Comment by ALITHEALI** [comment]
Thanks a lot for clearing that up. That's great. I didn't know about the `'now()'` feature. Many thanks.

**Comment by arcanis** [comment]
@B4nan Is there a way to make Mikro escape this content, either implicitly or by using a public helper function? I have a default based on a file content, stored as JSON, and while I can work my way around that by doing a `replace(/'/g, "''")`, it feels a little brittle (iirc different dbs have different escape strategies?).

**Comment by B4nan** [comment]
This is old issue, in v4 this has changed, `default` is escaped, if you want unuescaoed default, there is `defaultRaw`.
