### ISSUE TITLE
Postgres Native Enum with * schema

### ISSUE THREAD

**Issue by PrestonGiorgianni** [mikro-orm/mikro-orm#5456]
### Describe the bug

While trying to use the `schema: *` option to allow multiple postgres schemas to be created with the same classes, I have noticed that the update command does not generate the proper Enum types. There are all generated as `*.${nativeEnumName}` instead of `${options.schema}.${nativeEnumName}`.

I have tracked the issue down to this code block, where meta.schema is `*` and thus that is what is used in generating the sql. I am unfamiliar with the project and how best this could be fixed.

## output
```sql
create type "*"."axis_move_axis_type_enum" as enum ();
```

## desired output
```sql
create type "test"."axis_move_axis_type_enum" as enum ();
```

https://github.com/mikro-orm/mikro-orm/blob/5180b6aacec442689169cf1edbc6f7826e32dd83/packages/knex/src/schema/DatabaseSchema.ts#L88-L101

## additional context
the create sql function also has issues with the `*` schema. It generates this sql, where the enum has the schema in it twice, but the create table references the enum differently.
```sql
create type "test"."test.axis_move_axis_type_enum" as enum ();
create table "test"."axis_move" ("id" serial primary key, "axis_type" axis_move_axis_type_enum not null);
```

### Reproduction

```ts
//Type def
import { Entity, Enum, PrimaryKey, Property } from "@mikro-orm/core";

export enum AxisType {
...
}

@Entity({tableName: "axis_move", schema: "*"})
export class AxisMove {
  @Enum({
    type: 'AxisType',
    name: "axis_type",
    nativeEnumName: "axis_move_axis_type_enum",
  })
  axisType: "linear" | "rotary";
...
}

// schema generator
import { MikroORM } from '@mikro-orm/core';
import config from './config.js';

const orm = await MikroORM.init(config);
const schemaGenerator = orm.getSchemaGenerator();

console.log(await schemaGenerator.getUpdateSchemaSQL({
  schema: 'test',
}));
orm.close();
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.2.1

### Node.js version

v20.11.1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
I was looking into this yesterday, and the challenging part is diffing combined with support for enums in a specific schema (for entity in wildcard schema). Will need to give it a bit more time, worst case I'll implement at least the support for wildcard enums in general, as that should be rather easy (and I got that mostly already implemented locally).

**Comment by B4nan** [comment]
not perfect, but it should cover your use case
