### ISSUE TITLE
feat: extended filtering options for EntityGenerator

### ISSUE THREAD

**Issue by patrykbojczuk** [mikro-orm/mikro-orm#5469]
**Is your feature request related to a problem? Please describe.**
I have to create entity models for small subset of tables.
Currently I'd have to use `skipTables` with very long array of table names to get only the entities I need.
Also some of those table have constant prefix which can be matched with the pattern.

**Describe the solution you'd like**
I'd like to have another option `takeTables` to specify tables to generate entities for.
I'd also like to have the ability to specify `RegExp` to match table names to take/skip.

**Describe alternatives you've considered**
Getting list of all tables, filtering them out and using in `skipTables`.

**Additional context**
I could implement this feature.

**Comment by B4nan** [comment]
Sure, PR welcome.
