### ISSUE TITLE
toPOJO() should ignore serializedName option in @Property decorator

### ISSUE THREAD

**Issue by volk234** [mikro-orm/mikro-orm#5479]
### Describe the bug

If we use the `serializedName` option when describing the entity field, then we cannot use the toPOJO method to save the entity to the cache and then restore it via repository.merge. It is placed in the cache with the changed field name and the relation is discarded when merging.

### Reproduction

```ts
   @OneToMany(() => PlaceUser, 'user', {
        serializedName: 'places',
        serializer: (t: Collection<PlaceUser>) => {
            if (!t.isInitialized()) {
                return undefined;
            }
            return t.map(p => ({
                ...p.place.toObject(),
                verified: p.verified,
            }));
        },
    })
    placesPivot = new Collection<PlaceUser>(this);

    @ManyToMany(() => Place, p => p.users, { hidden: true })
    places = new Collection<Place>(this);
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.2.1

### Node.js version

20.12.1

### Operating system

Windows

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Should be easy fix, PR welcome
