### ISSUE TITLE
[SQL] Using null values in em.find's FilterQuery leads to unexpected results

### ISSUE THREAD

**Issue by darkbasic** [mikro-orm/mikro-orm#548]
```ts
@Entity()
export class Message extends BaseIdEntity {
  @ManyToMany({pivotTable: 'message_to_deletion'})
  deletions: Collection<User> = new Collection<User>(this);
```
This is a query which matches a non-null value on the M:N `deletions` field:
```ts
em.find(Message, {
  group: groupId,
  deletions: 1,
});
```

This is the sql that gets generated:
```sql
select "e0".*, "e1"."message_id", "e1"."user_id"
from "message" as "e0"
left join "message_to_deletion" as "e1"
on "e0"."id" = "e1"."message_id"
where "e0"."group_id" = 1 and "e1"."user_id" = 1
```

So far so good.

Now let's  try to match a null value instead:
```ts
em.find(Message, {
  group: groupId,
  deletions: null,
});
```

This is what gets generated:
```sql
select "e0".*, "e1"."message_id", "e1"."user_id"
from "message" as "e0"
left join "message_to_deletion" as "e1"
on "e0"."id" = "e1"."message_id"
where "e0"."group_id" = 25 and "e0"."deletions" is null
```

This obviously won't work, because `deletions` is not a column.

**Expected behavior**
```sql
select "e0".*, "e1"."message_id", "e1"."user_id"
from "message" as "e0"
left join "message_to_deletion" as "e1"
on "e0"."id" = "e1"."message_id"
where "e0"."group_id" = 1 and "e1"."user_id" is null
```

**Additional context**
```ts
em.find(Message, {
  group: groupId,
  deletions: {id: null},
});
```

The previous workaround works, but with some caveats: in fact having to explicitly specify the PK column will trigger an unnecessary join, see https://github.com/mikro-orm/mikro-orm/issues/549

**Versions**

| Dependency | Version |
| - | - |
| node | v13.14.0 |
| typescript | 3.8.3 |
| mikro-orm | 3.6.11 |
| pg | 8.0.3 |

**Comment by B4nan** [comment]
Closing as fixed in dev via https://github.com/mikro-orm/mikro-orm/commit/fdc9e06e9a6aa394a2e5fe5b137849432a9f76cd
