### ISSUE TITLE
MySql signed primary key migration 

### ISSUE THREAD

**Issue by HermanFassett** [mikro-orm/mikro-orm#5485]
### Describe the bug

I have an entity that has a signed primary key like so:
 ```
@PrimaryKey({ autoincrement: false, type: new BigIntType('bigint'), unsigned: false })`
id!: number;
```

I am trying to use in another class as a `ManyToOne` reference, but in the generated migrations, the generated foreign key `user_id` is of type `unsigned` so running the migration fails with error `Referencing column 'user_id' and referenced column 'id' in foreign key constraint 'message_user_id_foreign' are incompatible` (or similar error, in repro the error is a missing index). Am I missing something that can get this working?

### Reproduction

https://github.com/HermanFassett/mikro-orm-repro/

### What driver are you using?

@mikro-orm/mysql

### MikroORM version

6.2.2

### Node.js version

20.12.0

### Operating system

Windows 10

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
> ```
> @PrimaryKey({ autoincrement: false, type: new BigIntType('bigint'), unsigned: false })`
> id!: number;
> ```

Just FYI this definition does not make much sense, you use `new BigIntType('bigint')`, but map to a JS `number`? Sounds like you want this instead:

```ts
@PrimaryKey({ autoincrement: false, unsigned: false })`
id!: bigint;
```

(it won't fix the problem you are reporting, but at least you won't be lying to yourself - the ORM would hydrate `bigint`s there, not `number`s.

**Comment by HermanFassett** [comment]
> Just FYI this definition does not make much sense, you use `new BigIntType('bigint')`, but map to a JS `number`?

Yes I believe I originally did that since I do want a JS number, but MySQL int does not support same max/min value as JS number so I was getting errors saving some values to the database.

**Comment by B4nan** [comment]
> Yes I believe I originally did that since I do want a JS number, but MySQL int does not support same max/min value as JS number so I was getting errors saving some values to the database.

My point is that `new BigIntType('bigint')` means "bigint column that maps to bigint JS type". If you want to map to JS number, you need `new BigIntType('number')`, if you want to map to JS bigint, you should declare the property type as bigint (and in such case, you don't need to explicitly use the `BigIntType` as mentioned in the previous comment).
