### ISSUE TITLE
QueryBuilder in 6.2.x

### ISSUE THREAD

**Issue by piotr-cz** [mikro-orm/mikro-orm#5490]
### Describe the bug

I have simple game database with `Player`, `GameSession (@ManyToOne)` and `GameAction (@ManyToOne)` entities.
I'd like to run simple query to get aggregate max and avg values for game action for giver user.

Since mikro-orm `6.2.x` query builder creates different query than before, which fails.

Strange thing is that when I run `query.getQuery()` before execute, it produces same query as in `6.1.x`:
Update: Apparently it's because it finalizes the query and so it's not modified in the `execute` method

#### Entity definitions

```ts
@Entity()
export class Player {

  @PrimaryKey({ type: t.integer })
  id!: number

  // Inverse relationship 
  @OneToMany(() => GameSession, gameSession => gameSession.player, { orphanRemoval: true, hidden: true })
  gameSessions = new Collection<GameSession>(this)
}

@Entity({ tableName: 'game_session' })
export class GameSession {

  @PrimaryKey({ type: t.integer })
  id!: number

  @ManyToOne(() => Player, { joinColumn: 'player', nullable: true })
  player: Rel<Player> | null = null

  // Inverse relationship 
  @OneToMany(() => GameAction, gameAction => gameAction.gameSession, { orphanRemoval: true })
  gameActions = new Collection<GameAction>(this)
}

@Entity({ tableName: 'game_action' })
export class GameAction {

  @PrimaryKey({ type: t.integer })
  id!: number

  @ManyToOne(() => GameSession, { joinColumn: 'game_session', nullable: true })
  gameSession: Rel<GameSession>

  @Property({ type: t.integer })
  value: number
}
```

#### Code

```ts
const qb = (em as SqlEntityManager).createQueryBuilder(Player, 'p')

const query = qb
  .select([
    raw('max(ga.value) as max'),
    raw('avg(ga.value) as avg'),
  ])
  .leftJoin('gameSessions', 'gs')
  .leftJoin('gs.gameActions', 'ga')
  .where({ id: player.id })

// Workaround to fix created query
// query.getQuery()

const result = await query
  .execute<{ max: number | null, avg: number | string | null }>('get')
```

Invalid sql query created with above code by mikro-orm 6.2.x:

```sql
select max(ga.value) as max, avg(ga.value) as avg
from `player` as `p`
where `p`.`id` in (
  select `p`.`id` from (
    select `p`.`id` from `player` as `p`
    left join `game_session` as `gs` on `p`.`id` = `gs`.`player`
    left join `game_action` as `ga` on `gs`.`id` = `ga`.`game_session`
    where `p`.`id` = 1
    group by `p`.`id`
    limit 1
  ) as `p`
)
 - SQLITE_ERROR: no such column: ga.value"
```

Correct sql query when using:
- miko-orm 6.1.x
- 6.2.x with `query.getQuery()`
- changing `.execute('get')` to `.execute('run')` or `.execute('all')`

```sql
select max(ga.value) as max, avg(ga.value) as avg
from `player` as `p`
left join `game_session` as `gs` on `p`.`id` = `gs`.`player`
left join `game_action` as `ga` on `gs`.`id` = `ga`.`game_session`
where `p`.`id` = 1
```

### What driver are you using?

@mikro-orm/sqlite

### MikroORM version

6.2.2

### Node.js version

18.18.2

### Operating system

Windows

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by piotr-cz** [comment]
Suspect commit: https://github.com/mikro-orm/mikro-orm/commit/7f1f3c3c04c9d1b4bc878cc55a621ad4fced843d

**Comment by B4nan** [comment]
Please provide a complete repro, I need at least the entity definition, I have no idea how to reproduce this.

**Comment by piotr-cz** [comment]
@B4nan 
I have updated entity definitions in the issue reproduction.

It looks like generated query is different after https://github.com/mikro-orm/mikro-orm/commit/7f1f3c3c04c9d1b4bc878cc55a621ad4fced843d (I've tested with a rollback).

Dirty work around is to execute `query.toQuery()` which finalizes the query and the limit is not added in the execute method.

**Comment by piotr-cz** [comment]
Issue may be reproduced even without using aggregate methods:

```ts
const qb = (em as SqlEntityManager).createQueryBuilder(Player, 'p')

const query = qb
  .select(['id'])
  .leftJoin('gameSessions', 'gs')
  .leftJoin('gs.gameActions', 'ga')
  .where({ id: player.id })

await query.execute('get', false)

console.log(query.getQuery());
```

Output sql query:
```sql
select `p`.`id` from `player` as `p`
where `p`.`id` in (
  select `p`.`id` from (
    select `p`.`id`
    from `player` as `p`
    left join `game_session` as `gs` on `p`.`id` = `gs`.`player`
    left join `game_action` as `ga` on `gs`.`id` = `ga`.`game_session`
    where `p`.`id` = ?
    group by `p`.`id`
    limit ?
  ) as `p`
)
```

Output sql query for 6.1.x or for 6.2.x when calling `query.getKnexQuery()` before execute:

```sql
select `p`.`id` from `player` as `p`
left join `game_session` as `gs` on `p`.`id` = `gs`.`player`
left join `game_action` as `ga` on `gs`.`id` = `ga`.`game_session`
where `p`.`id` = ?
```

**Comment by B4nan** [comment]
Note that the query you are after is not what should be produced - the pagination mechanism kicks in automatically since you join to-many relations and apply a limit - you call the `get`  method which now automatically adds `limit 1` (that is resolved to the subquery to be able to actually load the related to-many items, since they result in cartesian product). If you want to disable that, just do `qb.setFlag(QueryFlag.DISABLE_PAGINATE)` - having an explicit `group by` also disables it.

This is surely still valid.

**Comment by B4nan** [comment]
The actual culprit is d228976d9ca4b8a2e69361ad31f63ef88977ee9e which tried to optimize unnecessary join branches which can cause quite a significant perf hit in case of large tables.

**Comment by piotr-cz** [comment]
Thanks for detailed explanation.

I didn't choose to use `qb.setFlag(QueryFlag.DISABLE_PAGINATE)`, because even that it comes up once a time in the GitHub issues/ discussions, I didn't find it in docs so I thought its' some sort of internal method (and may be dropped in future releases)

With the information You gave, I think the docs could be improved to explain `qb.setFlag` and explicit `groupBy` usage when querying for single row result.

**Comment by B4nan** [comment]
Let's keep this open, as I said, its valid, the join pruning needs to be less aggressive. We already check if the joins are used, we should probably skip it completely if there are raw query fragments selected, or try to read what they wrap.

**Comment by piotr-cz** [comment]
From my perspective I'd prefer mikro-orm to do *less magic* when using QueryBuilder.

I decided to use QueryBuilder because I wasn't able to construct expected query using entity manager filters and aggregate functions.

In this case I'd rather expect syntax which is as close to SQL as possible.
For example that `where({ id: 1 })` would always translate to `WHERE "p"."id" = '1'` without subqueries - because it's hard to debug why these came up.

**Comment by piotr-cz** [comment]
True, I should have added `group by` at the start,
but somehow the query was returning correct results in tests and that turned me off the track.

IMHO just adding some docs on `qb.setFlag` would be enough. Thanks to our explanation I now know what it's for.
