### ISSUE TITLE
The migration:check command exits with ERR_IMPORT_ASSERTION_TYPE_MISSING

### ISSUE THREAD

**Issue by piotr-cz** [mikro-orm/mikro-orm#5497]
### Describe the bug

Affects only 6.2.2, both Windows and Linux
Affects only commands and only related to snapshots (not programmatic usage)

It looks like that in https://github.com/mikro-orm/mikro-orm/commit/7e8409bb86ca6a35c755700b77e17b425c5ab186 the support to `require` json files have been removed together with a jest workaround.

Partially reverting commit fixes the issue

```ts
static async dynamicImport(id) {
    if (id.endsWith('.json')) {
        return require(id);
    }

    //...
}
```

#### Context
The `dynamicImport` method by default uses config's 

https://github.com/mikro-orm/mikro-orm/blob/ff3148b674a20f0d4977f26894b69e14595a61eb/packages/core/src/utils/Configuration.ts#L154

which produces the error.

Node's dynamic `import()` for json files should be used along with

- [Import attributes](https://nodejs.org/docs/latest-v18.x/api/esm.html#import-attributes) in node >= 18.20
  ```ts
  import(id, { with: { type: 'json' } })
  ```

- [Import assertions](https://nodejs.org/docs/latest-v17.x/api/esm.html#import-assertions) in node < 18.20
  ```ts
  import(id, { assert: { type: 'json' } })
  ```

Another thing is that the json file is imported in the `default` namespace.

As as result, such fix is possible:

```ts
async dynamicImportProvider(id) {
  if (id.endsWith('.json')) {
    const { default: data } = await import(id, { assert: { type: 'json' }, with: { type: 'json' } })

    return data
  }

  return import(id)
}
```

### Reproduction

Prepare project as in docs > [Creating a new project](https://mikro-orm.io/docs/guide/first-entity#creating-a-new-project)

Execute
```console
npx mikro-orm-esm migration:check
```
See output
```
Check if migrations are needed. Useful for bash scripts.
...

TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///xxx/src/migrations/.snapshot.json" needs an import assertion of type "json"
    at new NodeError (node:internal/errors:405:5)
    at validateAssertions (node:internal/modules/esm/assert:95:15)
    at defaultLoad (node:internal/modules/esm/load:91:3)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at xxx\node_modules\ts-node\src\esm.ts:255:45
    at async addShortCircuitFlag (xxx\node_modules\ts-node\src\esm.ts:409:15)
    at async nextLoad (node:internal/modules/esm/loader:163:22)
    at async ESMLoader.load (node:internal/modules/esm/loader:603:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:11)
    at async link (node:internal/modules/esm/module_job:68:21) {
  code: 'ERR_IMPORT_ASSERTION_TYPE_MISSING'
}
```

### What driver are you using?

@mikro-orm/sqlite

### MikroORM version

6.2.2

### Node.js version

18.18.2

### Operating system

Windows

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
I knew this would break at least something. Good old `require`, I miss you.

**Comment by B4nan** [comment]
I think I will just replace the import call with a simple `readJSONSync` from `fs-extra`.

**Comment by piotr-cz** [comment]
Yes, the `readFileSync` is probably best fit for this case
