### ISSUE TITLE
On MariaDB, It updates JSON column which not changed.

### ISSUE THREAD

**Issue by Sn-Kinos** [mikro-orm/mikro-orm#5499]
### Describe the bug

SQL Update executes when...
- `SELECT` executed and It didn't changes
- `forceEntityConstructor: true`
- Inside `em.transactional`
<img width="960" alt="image" src="https://github.com/mikro-orm/mikro-orm/assets/26380261/74859e7d-bc82-4722-9603-a5e0c0cf057b">

### Reproduction

1. Clone https://github.com/Sn-Kinos/nestjs-mariadb-update-reproduce
2. Run `npm i`
3. Modify `clientUrl`
4. Run `npm start`

### What driver are you using?

@mikro-orm/mariadb

### MikroORM version

next

### Node.js version

v20.11.1

### Operating system

macOS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
This is caused by `forceEntityConstructor`, why do you want to use that? You shouldn't need this unless you use native private properties in your entity. Do you understand `em.create` uses the constructor regardless of this option? It's only about using constructor for creating managed entity instances.

**Comment by Sn-Kinos** [comment]
We are using it because of private properties in entity. Actually, We are using EntitySchema for our code conventions on NestJS. (model class, repository pattern, interface inject, etc.) Is it the only solution to solve this situation that disable `forceEntityConstructor` and avoid private properties?

**Comment by Sn-Kinos** [comment]
I checked it again, the problem is `readonly` properties not `private`. I made new commit about it on reproduce repository.

**Comment by B4nan** [comment]
That flag has nothing to do with readonly modifier, you shouldnt need that in this test. Readonly modifier is a ts thing, it has no effect on runtime, and this flag has no type level effect.

**Comment by Sn-Kinos** [comment]
Thanks for feedback! I confused because of the original source code in companies. It occurs on property with `=`. I made new commit about it on reproduce repository, but I can figure out the reason is `Object.create`.
Then how can we solve that? On the original, we are using it like `logger = new Logger('User');` but in this case `this.logger` is `undefined`.

**Comment by Sn-Kinos** [comment]
I got it. For the same reason, all of method in class with arrow function are undefined too. I should change them all... 😵‍💫

**Comment by B4nan** [comment]
Do you have an actual reason to use arrow functions there? Turn them into actual methods and this problem disappears too.

**Comment by Sn-Kinos** [comment]
Yeah, It didn't have an actual reason about it... Just the reason it uses less lines.
```ts
isDisabled = () => this.status === 'progress';

isDisabled() {
  return this.status === 'progress';
}
```
Thanks for the reply!

**Comment by B4nan** [comment]
Let's keep this open, I'll first look if we can fix this as it should generally work the way you tried. It's just that many people really don't need this option, and generally speaking, you should rather not combine it with explicit constructor usage.
