### ISSUE TITLE
Cursor pagination `first: 0` returns all items

### ISSUE THREAD

**Issue by stefansundin** [mikro-orm/mikro-orm#5501]
### Describe the bug

Passing `first: 0` to `findByCursor` returns all items.

I have a situation where, in the front-end, I want to just retrieve the total count of items. I don't have an endpoint to just get meta information, so I am just issuing a query to list zero items and then reading the page information. Unfortunately, right now this retrieves all items which is a major performance issue. So as a workaround I am requesting a single item with `first: 1`.

Since `limit: 0` returns zero items, I think `first: 0` also should return zero items.

### Reproduction

https://github.com/stefansundin/mikro-orm-reproduction/tree/first-0

```typescript
test('basic CRUD example', async () => {
  for (let i=0; i < 100; i++) {
    orm.em.create(User, { name: `Foo ${i}` });
  }
  await orm.em.flush();
  orm.em.clear();

  // {limit: 0} works
  const [limitResult, limitTotalCount] = await orm.em.findAndCount(User, {}, { limit: 0 });
  expect(limitTotalCount).toBe(100);
  expect(limitResult.length).toBe(0);

  // {first: 1} works
  const result1 = await orm.em.findByCursor(User, {}, { first: 1, orderBy: [{name: 'ASC'}] });
  expect(result1.totalCount).toBe(100);
  expect(result1.length).toBe(1);

  // {first: 0} is a performance trap!
  const result2 = await orm.em.findByCursor(User, {}, { first: 0, orderBy: [{name: 'ASC'}] });
  expect(result2.totalCount).toBe(100);
  expect(result2.length).toBe(0); // <-- bug
});
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.2.1

### Node.js version

18.20.2

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Note that `first: 0` shouldn't result in `limit 0` but rather to `limit 1`, as with cursor based pagination we are overfetching by default to know whether there is a next page. You can disable that via `overfetch: false`.
