### ISSUE TITLE
Infinite cycle when querying an entity

### ISSUE THREAD

**Issue by Darent98** [mikro-orm/mikro-orm#5503]
### Describe the bug

I have a problem with an infinite cycle when querying an entity. Right now I cannot provide a reproduction case, because it only occurs in a specific configuration. 

When debugging I noticed that there may be an infinite cycle in the parser. I will provide a few screenshot from the callstack and try to provide more infos, if I have some.

![image](https://github.com/mikro-orm/mikro-orm/assets/84193036/13187cd0-9593-4b1c-988e-715d0e13fbf3)

![image](https://github.com/mikro-orm/mikro-orm/assets/84193036/5fe0efe2-6a7e-46ba-b4e5-f730ba6086dd)

![image](https://github.com/mikro-orm/mikro-orm/assets/84193036/3be7f7d4-b07e-4aaf-9695-f86539df6a2e)

![image](https://github.com/mikro-orm/mikro-orm/assets/84193036/cc8eebc6-b5ea-4b85-b25d-6e7c4ba0d990)

![image](https://github.com/mikro-orm/mikro-orm/assets/84193036/d68cfee9-479e-4553-8d2c-71d68adc4c36)

### Reproduction

-

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.2.2

### Node.js version

20.11.1

### Operating system

Linux

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Darent98** [comment]
I copied the generated sql query and directly executed it via dbeaver. The result were 203k rows. Seems a bit too much. They also all seem to be the same.

**Comment by B4nan** [comment]
I cant help with screenshots, please provide a complete reproduction.
