### ISSUE TITLE
"Source file '...' not found." error occurs since version 6.2.2-dev.7 with Bun.

### ISSUE THREAD

**Issue by SnowMarble** [mikro-orm/mikro-orm#5507]
### Describe the bug

I'm using Bun(1.1.4), and got `Source file '...' not found. Check your 'entitiesTs' option and verify you have 'compilerOptions.declaration' enabled in your 'tsconfig.json'. If you are using webpack, see https://bit.ly/35pPDNn` error while using v6.2.2. 

My `mikro-orm.config.ts` looks like this:
```ts
export default defineConfig({
  // other configs
  entities: ['./src/**/entities/*.entity.ts', './src/lib/ddd/BaseEntity.ts'],
  entitiesTs: ['./src/**/entities/*.entity.ts', './src/lib/ddd/BaseEntity.ts'],
  metadataProvider: TsMorphMetadataProvider,
})
```
I tried to pass full paths of the entity files and use imported entities, but it was the same.

The version where this bug first started occurring is 6.2.2-dev.7.

I looked up the diff between .7 and .6 and found [this commit (d64be7e)](https://github.com/mikro-orm/mikro-orm/commit/d64be7ef5ba7c2a655ea014992905d8afde3c231) has to do with the issue.

I don't fully understand the code base, so I can't diagnosis what caused the problem right now. 

Please help me to fix it.

### Reproduction

You need Bun v1.1.4, and v6.2.2-dev.7 of mikro orm. 

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.2.2-dev.6

### Node.js version

Bun 1.1.4

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Ruby184** [comment]
See this discussion for explanation https://github.com/mikro-orm/mikro-orm/discussions/5496#discussion-6544778. I have started to work on the PR to fix that.

**Comment by SnowMarble** [comment]
@Ruby184 Sorry for missing the discussion. Then let me close the issue and follow your work.
