### ISSUE TITLE
Configure Sentry in repo that uses Mikro-ORM

### ISSUE THREAD

**Issue by Loown** [mikro-orm/mikro-orm#551]
I tried to configure Sentry in my NestJS API, but when I installed Sentry I got this error :

> node_modules/mikro-orm/dist/utils/RequestContext.d.ts:7:11 - error TS2451: Cannot redeclare block-scoped variable 'active'.
> 
> 7     const active: ORMDomain;
>             ~~~~~~
> 
>   node_modules/@sentry/hub/dist/hub.d.ts:5:9
>     5     let active: Domain;
>               ~~~~~~
>     'active' was also declared here.

**Comment by B4nan** [comment]
Apparently sentry also uses the domain api. The error is just about typings mismatch, that could be solved quite easily. The question is whether it will be enough or if those two will collide. 

Please prepare a reproduction repository so I can try.

**Comment by Loown** [comment]
https://github.com/Loown/mikro-orm-sentry-fail

Here's a repo that reproduce the same error as I got in mine.

I'm beginner, so I can't really help you on that, good luck !
