### ISSUE TITLE
MikroORM should merge all changes of one record into one sql update statement

### ISSUE THREAD

**Issue by ssljivic** [mikro-orm/mikro-orm#5510]
### Describe the bug

I have an entity that has `updatedAt` column that is updated with the current date on each update of the entity.

When I make a change to the entity - in this case I have updated FK column/property - and flush the changes to the database, I get 2 UPDATE SQL queries for the same record in the DB. One that updates updated_at column and another that updated the FK column.

Those 2 UPDATEs should be merged into one.

### Reproduction

```ts
import { Entity, OneToOne, PrimaryKey, Property } from '@mikro-orm/core'
import { MikroORM, PostgreSqlDriver } from '@mikro-orm/postgresql'

import { mockLogger } from '../helpers'

@Entity()
export class Other {
  @PrimaryKey()
  id!: number

  @Property()
  name!: string

  @Property({ length: 0, nullable: true, onUpdate: () => new Date() })
  updatedAt?: Date
}

@Entity()
export class Test {
  @PrimaryKey()
  id!: number

  @Property()
  name!: string

  @Property({ length: 0, nullable: true, onUpdate: () => new Date() })
  updatedAt?: Date

  @OneToOne(() => Other, { nullable: true, owner: true })
  other?: Other
}

describe('MikroORM', () => {
  let orm: MikroORM

  beforeAll(async () => {
    orm = await MikroORM.init({
      host: 'localhost',
      port: 5432,
      user: 'mikro-orm-test',
      password: 'mikro-orm-test',
      dbName: 'mikro-orm-test',

      driver: PostgreSqlDriver,

      allowGlobalContext: true,
      debug: true,
      entities: [Test],
    })
    await orm.schema.refreshDatabase({ wrap: true })
  })

  afterAll(async () => {
    await orm.close(true)
  })

  it('should merge all changes of one record into one sql update statement', async () => {
    const tid = await orm.em.insert(Test, { name: 'Foo' })
    await orm.em.flush()

    const test = await orm.em.findOne(Test, { id: tid })

    const other = new Other()
    other.name = 'Foo'
    orm.em.persist(other)
    test!.other = other

    const mock = mockLogger(orm)
    await orm.em.flush()

    expect(mock.mock.calls).toHaveLength(
      [['begin'], ['insert into other'], ['update test'], ['commit']].length,
    )
  })
})
```

The executed SQLs statements are:

```
begin;
insert into "other" ("name") values ('Foo') returning "id";
update "test" set "updated_at" = '2024-04-26T12:49:50.788Z' where "id" = 1;
update "test" set "other_id" = 1, "updated_at" = '2024-04-26T12:49:50.841Z' where "id" = 1;
commit;
```

but I would expect them to be:
```
begin;
insert into "other" ("name") values ('Foo') returning "id";
update "test" set "updated_at" = '2024-04-26T12:49:50.788Z', "other_id" = 1 where "id" = 1;
commit;
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.2.3

### Node.js version

18.17.1

### Operating system

MacOS 14.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rubiin** [comment]
Never noticed this however it seems to be an issue .
