### ISSUE TITLE
Serialised entity is populated instead of FK

### ISSUE THREAD

**Issue by labzy88** [mikro-orm/mikro-orm#5513]
### Describe the bug

I'm trying to get a serialised entity without anything populated. I just need the FKs.

In the reproduction I invented the junction table Debt for Users, I want to get a serialised/unpopulated entity with just the FK for lender and debtor, but it seems I can still get lender.id, when all I want is for the lender to be the FK. Likewise, VSCode is giving me the same:

![image](https://github.com/mikro-orm/mikro-orm/assets/29731902/5c5e1e55-938e-4631-9ab7-e66ee59d4e07)
![image](https://github.com/mikro-orm/mikro-orm/assets/29731902/e0f26398-18bc-475e-856b-718729255e7d)

I have a feeling I could be misunderstanding how Mikro-ORM works, appreciate any input/help !

### Reproduction

please see fk-serialised.test.ts

In my project I use Postgres, but it appears to be the same using sqlite in the reproduction.

https://github.com/labzy88/reproduction

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

^6.2.3

### Node.js version

v20.11.0

### Operating system

Debian

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
You need to use the Reference wrapped to have this level of type safety.

**Comment by labzy88** [comment]
@B4nan , I just discovered another issue when running the test, it states "User.jncLenders has wrong 'mappedBy' reference type: Reference instead of User"
