### ISSUE TITLE
Extra query fired when fetching a join table entity and populating a join column

### ISSUE THREAD

**Issue by jedusei** [mikro-orm/mikro-orm#5518]
### Describe the bug

I have 3 entities: `Product`, `Order` & `OrderItem`, based on [this example from the docs](https://mikro-orm.io/docs/composite-keys#use-case-3-join-table-with-metadata): 

![image](https://github.com/mikro-orm/mikro-orm/assets/18331712/5f1fe21c-aedc-48f5-8b58-501a86bc542e)

(Note that I'm using a UUID as the primary key instead of a number.)

The problem is that this code:
![image](https://github.com/mikro-orm/mikro-orm/assets/18331712/9f36d0d0-344d-4438-9b2c-02d6632c735d)

Results in 2 queries being fired:
![image](https://github.com/mikro-orm/mikro-orm/assets/18331712/fd450b98-bb60-4c4f-8ee3-10ed34c9c063)

The first query already has the product information, so I don't see the need for the second query to be fired.

Interestingly, there's no 2nd query if I change the primary key definition:
![image](https://github.com/mikro-orm/mikro-orm/assets/18331712/b41d961d-96b8-42c6-9beb-eb43a33d8587)

It also works fine if the primary key is a number.

### Reproduction

https://github.com/jedusei/mikro-orm-extra-query-bug

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.2.3

### Node.js version

20.11.0

### Operating system

Windows 11

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ssljivic** [comment]
I just stumbled upon this very same issue.

Here is the test for it:

```ts
import { BigIntType, Entity, OneToOne, PrimaryKey, Property, Reference } from '@mikro-orm/core'
import { MikroORM, PostgreSqlDriver } from '@mikro-orm/postgresql'

import { mockLogger } from '../helpers'

@Entity()
export class Game {
  @PrimaryKey({ type: new BigIntType('number') })
  id!: number

  @Property({ length: 255 })
  name!: string

  @OneToOne({ entity: 'Gameplay', mappedBy: 'game' })
  gameplay!: Reference<Gameplay>
}

@Entity()
export class Gameplay {
  @OneToOne({ entity: () => Game, primary: true, inversedBy: 'gameplay', joinColumn: 'id' })
  game!: Game

  @Property({ nullable: false, default: false })
  inChallenge: boolean = false
}

describe('MikroORM', () => {
  let orm: MikroORM

  beforeAll(async () => {
    orm = await MikroORM.init({
      host: 'localhost',
      port: 5432,
      user: 'mikro-orm-test',
      password: 'mikro-orm-test',
      dbName: 'mikro-orm-test',

      driver: PostgreSqlDriver,

      debug: true,
      entities: [Game, Gameplay],
    })
    await orm.schema.refreshDatabase({ wrap: true })
  })

  afterAll(async () => {
    await orm.close(true)
  })

  it('should ...', async () => {
    let em = orm.em.fork()

    const gameplay = new Gameplay()

    const game = new Game()
    game.id = 1
    game.name = 'The Game'
    game.gameplay = Reference.create(gameplay)

    em.persist(game)
    await em.flush()

    em = orm.em.fork()

    const mock = mockLogger(orm)

    await em.findOneOrFail(
      Gameplay,
      { game: { id: 1 } },
      {
        populate: ['game'],
      },
    )

    console.log(mock.mock.calls)

    expect(mock.mock.calls).toHaveLength(1)
  })
})
```
