### ISSUE TITLE
Optimistic locking not working with upsert

### ISSUE THREAD

**Issue by ssljivic** [mikro-orm/mikro-orm#5527]
### Describe the bug

When an entity is upsert-ed and after that loaded (`find`) by ID, optimistic locking SQL is not created as expected. The version column is not added to the WHERE condition.

However, if option `disableIdentityMap: true` is set, optimistic locking is working OK. To test this case, uncomment line 41 in the test (`// disableIdentityMap: true,`).

### Reproduction

```ts
import { BigIntType, Entity, type Opt, PrimaryKey, Property } from '@mikro-orm/core'
import { MikroORM, PostgreSqlDriver } from '@mikro-orm/postgresql'

import { mockLogger } from '../helpers'

@Entity()
export class Test {
  @PrimaryKey()
  id!: number

  @Property()
  name!: string

  @Property({ length: 0, nullable: true, onUpdate: () => new Date() })
  updatedAt?: Date

  @Property({ type: new BigIntType('number'), defaultRaw: '1', version: true })
  version!: number & Opt

  constructor(props?: Pick<Test, 'id' | 'name'>) {
    if (props) {
      this.id = props.id
      this.name = props.name
    }
  }
}

describe('MikroORM', () => {
  let orm: MikroORM

  beforeAll(async () => {
    orm = await MikroORM.init({
      host: 'localhost',
      port: 5432,
      user: 'mikro-orm-test',
      password: 'mikro-orm-test',
      dbName: 'mikro-orm-test',

      driver: PostgreSqlDriver,

      // disableIdentityMap: true,

      debug: true,
      entities: [Test],
    })
    await orm.schema.refreshDatabase({ wrap: true })
  })

  afterAll(async () => {
    await orm.close(true)
  })

  it('should always use optimistic locking query when version column is defined', async () => {
    const em = orm.em.fork()

    await em.upsert(new Test({ id: 1, name: 'Foo' }))
    const test = await em.findOneOrFail(Test, { id: 1 })

    await em.flush()

    test.name = 'Bar'
    em.persist(test!)

    const mock = mockLogger(orm)
    await em.flush()

    console.log(mock.mock.calls)

    expect(mock.mock.calls).toSatisfy((it) => {
      for (const l of it) {
        for (const ll of l) {
          console.log(typeof ll, ll)
          if (ll.indexOf('where "id" = 1 and "version" = 1 returning "version"') >= 0) {
            return true
          }
        }
      }
      return false
    })
  })
})

```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.2.3

### Node.js version

18.17.1

### Operating system

MacOS 14.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
> When an entity is upsert-ed and after that loaded (find) by ID

You don't load it at all, it's in the context, you query the entity by its PK, so you just get it from the memory. There is no select query from your `findOne` call. The `upsert` call returns your entity, you don't need to load it again. 

If this is the reason why you started experimenting with that global `disableIdentityMap` option, I would discourage that. You can use `refresh: true` where appropriate.

**Comment by B4nan** [comment]
The issue is only about getting the version value back from the upsert call (via returning statement), that's all. Because of that not working correctly, you started experimenting with disabling the identity map, but that's really the worst path I would suggest.

As said above, you can just slam `refresh: true` to the find call to get the same (but only where needed).

```ts
await em.upsert(Test, { id: 1, name: 'Foo' });
const test = await em.findOneOrFail(Test, 1, { refresh: true });
```

Should be easy to fix.

**Comment by ssljivic** [comment]
Thanks fo rthe fix.

One thing though:
> The issue is only about getting the version value back from the upsert call (via returning statement), that's all. Because of that not working correctly, you started experimenting with disabling the identity map

This was not the case. The test case was slimmed down for simplicity, so it could look like this was the reason for an extra `find`, but in the actual use case the `find` would fetch some related entity collections...

Anyway, glad this is fixed now. Thanks again.

> Also it feels like you tend to flush randomly...
The intention was to flush init SQLs before mocking the logger. This was just for the test.
