### ISSUE TITLE
Extra updates on embedded entities with camelCase field name

### ISSUE THREAD

**Issue by mrmlnc** [mikro-orm/mikro-orm#5530]
### Describe the bug

The comparator finds false changes in the embeddable entity field if the name of the field does not match the one stored in the database. This leads to an additional UPDATE query to the database and a false version increment for entity.

After a little investigation, I assume that the problem is in these lines of code. They mutate the data in the payload.

https://github.com/mikro-orm/mikro-orm/blob/e513cb97ca678ef50439f198a8346d728a4439d7/packages/knex/src/AbstractSqlDriver.ts#L499-L502

Here is the output of the payload before the changes ([here](https://github.com/mikro-orm/mikro-orm/blob/e513cb97ca678ef50439f198a8346d728a4439d7/packages/knex/src/AbstractSqlDriver.ts#L495)). This is a valid state.

```js
[
  {
    steps: [{ camelCasePropertyName: 1 }]
  }
]
```

Here is the output of the payload after the function is running ([here](https://github.com/mikro-orm/mikro-orm/blob/e513cb97ca678ef50439f198a8346d728a4439d7/packages/knex/src/AbstractSqlDriver.ts#L513)).

```js
[
  {
    steps: [{ camel_case_property_name: 1 }]
  }
]
```

Output of arguments of the array comparison function ([here](https://github.com/mikro-orm/mikro-orm/blob/e513cb97ca678ef50439f198a8346d728a4439d7/packages/core/src/utils/Utils.ts#L96)) called from [here](https://github.com/mikro-orm/mikro-orm/blob/e513cb97ca678ef50439f198a8346d728a4439d7/packages/core/src/utils/EntityComparator.ts#L630).

```js
{
  a: [{ camel_case_property_name: 1 }],
  b: [{ camelCasePropertyName: 1 }]
}
```

### Reproduction

https://github.com/mrmlnc/mikro-orm-json-extra-updates

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.2.4

### Node.js version

22.0.0

### Operating system

macOS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
[This](https://github.com/mrmlnc/mikro-orm-json-extra-updates/blob/main/src/entities/test-case.entity.ts#L16C5-L16C51) is wrong, it should be just `@Embedded(() => StepEntity, { array: true })`. Not sure if that's the culprit.

Note that embeddables (since v6) respect the naming strategy, so your payload should contain the camel-cased keys (and such should be stored in the database too).

**Comment by B4nan** [comment]
Single file repro based on your test here (next time please try to provide such right ahead to save me a few minutes):

```ts
import { Entity, MikroORM, OptionalProps, PrimaryKey, Property, Embeddable, Embedded } from '@mikro-orm/sqlite';
import { mockLogger } from '../helpers';

@Embeddable()
class StepEntity {

  @Property()
  camelCasePropertyName!: number;

}

@Entity({ tableName: 'test_case' })
class TestCaseEntity {

  [OptionalProps]?: keyof Pick<TestCaseEntity, 'sid' | 'steps'>;

  @PrimaryKey({ autoincrement: true })
  sid!: number;

  @Embedded(() => StepEntity, { array: true })
  steps: StepEntity[] = [];

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    dbName: ':memory:',
    entities: [TestCaseEntity],
    debug: true,
  });
  await orm.schema.createSchema();
});

beforeEach(async () => {
  orm.em.clear();
});

afterAll(async () => {
  await orm.close(true);
});

test(`relations' orderBy should be respected when using LoadStrategy.JOINED`, async () => {
  const testCase = orm.em.getRepository(TestCaseEntity).create({
    steps: [{ camelCasePropertyName: 1 }],
  });

  await orm.em.persistAndFlush(testCase);

  const mock = mockLogger(orm);
  await orm.em.flush();
  expect(mock).not.toHaveBeenCalled();
});
```

(and indeed its still valid even after the fix I proposed above)
