### ISSUE TITLE
SUM function in query builder has incorrect syntax.

### ISSUE THREAD

**Issue by labzy88** [mikro-orm/mikro-orm#5546]
### Describe the bug

Hi,

Trying to select using the SUM function creates a SQL query with the backticks in the wrong position.

The query I'm using is:
```
const results = await orm.em
    .createQueryBuilder(User, "u")
    .select(["u.id as id", "sum(t.amount) as total"])
    .leftJoin("u.jncSales", "t")
    .where({ email: "foo" })
    .getResultList();
```

This translates to the SQL query:
```
select `u`.`id` as `id`, `sum(t`.`amount)` as `total` from `user` as `u` left join `transaction` as `t` on `u`.`id` = `t`.`seller_id` where `u`.`email` = 'foo' - SQLITE_ERROR: no such column: sum(t.amount)
```

I have added 2 tests for a knex raw query and a normal knex query in my reproduction, they pass ok.

### Reproduction

https://github.com/labzy88/reproduction

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.1.4

### Node.js version

v20.11.0

### Operating system

Debian

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
You need to wrap raw queries with `raw` or `sql` helpers

```ts
const results = await orm.em
    .createQueryBuilder(User, "u")
    .select(["u.id as id", sql`sum(t.amount)`.as('total')])
    .leftJoin("u.jncSales", "t")
    .where({ email: "foo" })
    .getResultList();
```

https://mikro-orm.io/docs/raw-queries

**Comment by labzy88** [comment]
@B4nan thanks!
