### ISSUE TITLE
[Bug]: Formula set as ScalarReference not loaded as LoadedScalarReference at runtime

### ISSUE THREAD

**Issue by kpervin** [mikro-orm/mikro-orm#5557]
### Describe the bug

When using a formula with a lazy scalar reference, it appears as type `ScalarReference` or `LoadedScalarReference` when using the `.load()`, `.get()`, or `.$` methods. However, at runtime, all properties are lost and the field is loaded as the formula value. Additionally, in MySQL, if set to a Boolean type, it does not serialize and ends up as a TinyInt.

### Reproduction

https://github.com/kpervin/mikro-orm-reproduction/tree/lazy-scalar-reference-issue

Please note that this is using the SQLite default. Testing with MySQL should also be done to see the serialization issue.

### What driver are you using?

MySQL

### MikroORM version

next

### Node.js version

20.9.0

### Operating system

5.15.146.1-microsoft-standard-WSL2

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kpervin** [comment]
Closing due to realizing that the `ref` option was required. Was under the impression that it would have been picked up by TsMorphMetadataProvider.

**Comment by B4nan** [comment]
Let's keep this open, I want to review it first (probably this evening). ts-morph should pick this up, and it might be failing because you use it with the `Opt` type intersection. Note that your repro does not use ts-morph.

**Comment by kpervin** [comment]
Yes, I saw that before I closed the issue. Required a bit of refactoring for it to work. Adding it now.

**Comment by B4nan** [comment]
Yeah, this is surely something to fix, it's about the `Opt` type intersection. Note that in your repro [you test whether the value is `true`](https://github.com/kpervin/mikro-orm-reproduction/blob/lazy-scalar-reference-issue/src/example.test.ts#L39) - it never will be the value itself with the `Ref` wrapper, it is always the `Reference` class (in this case `ScalarReference`), which wraps the value.

**Comment by B4nan** [comment]
So the problem here is that the TS compiler API returns the type for `hasBarPost` as `any` for some reason. If you use `hasBarPost!: Opt<Ref<boolean>>` it does work fine though.

**Comment by kpervin** [comment]
Wow, what a simple fix for such a weird issue haha

**Comment by kpervin** [comment]
@B4nan unfortunately this still seems to be an issue, but only one aspect:

> Additionally, in MySQL, if set to a Boolean type, it does not serialize and ends up as a TinyInt.

Should I create a new issue for this specific aspect of the issue?

I have updated [the reproduction](https://github.com/kpervin/mikro-orm-reproduction/tree/lazy-scalar-reference-issue) to use MySQL and the test to show the expected outcome.

**Comment by B4nan** [comment]
This one is about the property runtime type apparently, again an issue with the reflection, it works fine with reflect metadata. Looking at the metadata cache, it gets inferred as `Ref<boolean>` which is technically correct, but the ORM expects the raw type name there. We only strip the `Ref<>` wrapper on type level when extracting the `type` but keep the `runtimeType` intact. Sounds like a simple fix.

**Comment by kpervin** [comment]
I actually tried it with explicitly passing BooleanType as well as `type: "boolean"` in the Property decorator, but that didn't seem to help matters. I was trying to debug this myself, so I'm very curious to see where this was falling short (otherwise I'd put in a PR).

**Comment by B4nan** [comment]
Here you go: ff6a7ae

**Comment by kpervin** [comment]
I see you have a call to both Ref and Reference with `processWrapper`, but only `ScalarReference` with scalars. Does this need a call for `ScalarRef` as well?

**Comment by B4nan** [comment]
Good point, fixed here: 6b1a349

**Comment by kpervin** [comment]
For the array `['Ref', 'Reference', 'EntityRef', 'ScalarRef', 'ScalarReference']`, since you're essentially using the same values at both [94-99](https://github.com/mikro-orm/mikro-orm/blob/6b1a3494780f55130d4240109cba8e7af4131c89/packages/reflection/src/TsMorphMetadataProvider.ts#L94C5-L99C45) and [203](https://github.com/mikro-orm/mikro-orm/blob/6b1a3494780f55130d4240109cba8e7af4131c89/packages/reflection/src/TsMorphMetadataProvider.ts#L203), would it make sense to make this a const array either as a private value in `TsMorphMetadataProvider` or as a const outside of it? That way you could do something like this for 94-99:
```typescript
private wrapperNames = [
    'Ref',
    'Reference',
    'EntityRef',
    'ScalarRef',
    'ScalarReference'
  ] as const;

...

for(const name of this.wrapperNames) { //originally 94-99
      this.processWrapper(prop, name);
}
this.processWrapper(prop, 'Collection');
prop.runtimeType ??= prop.type;

...

if (this.wrapperNames.includes(wrapper)) { // originally 203
      prop.ref = true;
    }
```

**Comment by B4nan** [comment]
PR welcome if you consider that important, it's not happening often that we need to adjust this, but I agree that this duplicity in the same class can cause unnecessary regressions.
