### ISSUE TITLE
matching doesn't set _populated to true

### ISSUE THREAD

**Issue by SDAdham** [mikro-orm/mikro-orm#5559]
### Describe the bug

_populated is not set to true when using matching with populate and populateWhere which leads `.toJSON` to strip off the populated entities

### Reproduction

https://github.com/SDAdham/reproduction/blob/master/src/example.test.ts

### What driver are you using?

@mikro-orm/mysql

### MikroORM version

6.2.5

### Node.js version

20.9.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SDAdham** [comment]
Discord Thread: https://discord.com/channels/1214904142443839538/1238875455436881971

**Comment by B4nan** [comment]
A workaround for your repro would be using `em.populate`, which will adjust the `user` entity populate hint internally and that is the main source when serializing now. The `_populated` flag is only meant for manual overrides (via the public `populated()` method, no need to access it directly).

```ts
await orm.em.populate(user, ['groups.permissions'], {
  where: {
    groups: {
      permissions: {
        write: true,
      },
    },
  },
  orderBy: {
    groups: {
      permissions: {
        id: 'ASC',
      },
    },
  },
});
```

Note that you need to call this on the root entity (`user`) which you will be serializing, it wouldn't help if called on `user.groups` separately.

**Comment by SDAdham** [comment]
Will it affect the loaded groups? I have a where condition on those as well?

**Comment by B4nan** [comment]
Why don't you check the query yourself? It should be equivalent (it's actually a better approach in general).

**Comment by SDAdham** [comment]
@B4nan, how can I limit populate from populating an entire collection? I want to just take 1 for example.

**Comment by SDAdham** [comment]
So, here is a conversion of your suggestion:
```
await this.repo.populate(
            user,
            ['profiles.links', 'profiles.themes', 'profiles.groups', 'settings'], // here, I want to get the last applied settings by the user
            {
              orderBy: {
                profiles: {
                  links: {
                    urlOrder: 'ASC'
                  }
                },
                pictures: {
                  sizes: 'ASC'
                }
              },
              where: {
                profiles: {
                  links: {
                    publish: true
                  },
                  themes: {
                    default: true
                  }
                }
              },
              populateWhere: PopulateHint.INFER
            }
          );
```

**Comment by SDAdham** [comment]
Hello @B4nan , have you had a chance to see my comment above? Is there any chance I limit the populate for `settings`? I used to be able to do this easy with `matching`.

**Comment by B4nan** [comment]
you can't do that with `em.populate`, that only loads complete collections. 

i think i have a workaround for you, you could use `setSerializationContext` private method of EntityLoader, that is what makes it work with `em.populate`:

```ts 
await users[0].groups.matching({ ... });

// @ts-ignore accessing private variables and methods
orm.em.entityLoader.setSerializationContext(users, [{ field: 'groups', children: [{ field: 'permissions' }] }], {});
```

**Comment by B4nan** [comment]
I found a way to make this work automatically, under the hood it uses the  `setSerializationContext` which is now also available via `wrap(entity).setSerializationContext()` and that one accepts the same options as `em.find` and others (so string array with dot paths), in case someone needs to adjust this from higher levels.

**Comment by SDAdham** [comment]
@B4nan , how can I use this? I checked https://github.com/mikro-orm/mikro-orm/commit/57f234bae7ecb212f19f85de78234280f6d35f3a#diff-0ff5eff74e69157ae82c4c9778d18af0f72c77d22f77770ae81c6e9dbe0ce690 and it's not clear on the usage?

So, do I do this:
```
    await users[0].groups.matching({
      store: true,
      orderBy: {
        permissions: {
          id: 'ASC',
        },
      },
      where: {
        permissions: {
          write: true,
        },
      },
      populate: ['permissions'],
      populateWhere: {
        permissions: {
          write: true,
        },
      },
    });

wrap(users[0].groups).setSerializationContext() // ******do I do this ?*******
```

**Comment by SDAdham** [comment]
I managed to work it out:
```
    await users[0].groups.matching({
      store: true,
      orderBy: {
        permissions: {
          id: 'ASC',
        },
      },
      where: {
        permissions: {
          write: true,
        },
      },
      populate: ['permissions'],
      populateWhere: {
        permissions: {
          write: true,
        },
      },
    });
wrap(users).setSerializationContext({
            populate: ['groups.permissions']
          })
```

Onenote, it doesn't work on something like this `wrap(users.groups).set....`, I'd get errors during runtime

**Comment by B4nan** [comment]
> I managed to work it out:

You shouldn't need that explicit `setSerializationContext` call, it's done automatically in this case.

> Onenote, it doesn't work on something like this wrap(users[0].groups).set...., I'd get errors during runtime

You should not use `wrap()` on anything other than entity (in fact, you should use that only on the root entity, not even its relations). So yes, this shouldn't work at all, it's correct you get a runtime error.

**Comment by SDAdham** [comment]
Thanks @B4nan , it doesn't also work for Collection, right? I am getting `core_1.wrap)(...).toObject` when I do this on `Collection<Entity>()`
