### ISSUE TITLE
One-to-one relation not loaded when using custom join column name

### ISSUE THREAD

**Issue by nikolaylaz** [mikro-orm/mikro-orm#557]
```javascript
@Entity()
export class Application {

  @PrimaryKey()
  id: number;

  @OneToOne({joinColumn: 'application_rate_id', inversedBy: 'application'})
  rate: Rate;
}

```

```javascript
@Entity()
export class Rate {

  @PrimaryKey()
  id: number;

  @Property()
  name: string;

  @OneToOne({mappedBy: 'rate'})
  application: Application;
}
```
```sql
CREATE TABLE `application` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `application_rate_id` int(11) NOT NULL,
  PRIMARY KEY (`id`) ....
```

```javascript
this.applicationRepository.findAll({
      populate: ['rate']
    });
```

This is generating the following query:

    select `e0`.* from `application` as `e0`

If i remove joinColumn and rename database column to 'rate_id' the sql query looks likes this:

    select `e0`.*, `e1`.`id` as `application_id` from `rate` as `e0` left join `application` as `e1` on `e0`.`id` = `e1`.`rate_id` where `e0`.`id` in (1, 2) order by `e0`.`id` asc 

Which in my opinion is strange, shouldn't it just be something like this:
`select * from application join rate ...`

**Expected behavior**

Should properly join rate table using the value from joinColumn

**Versions**

| Dependency | Version |
| - | - |
| node | 12.16.1 |
| typescript | 3.7.5 |
| mikro-orm | 3.6.13 |
| mariadb | 2.3.1 |

**Comment by B4nan** [comment]
Well there will always be 2 queries. First one loads root entity (`Application`), second one loads the relation (`Rate`). This is how population works in MikroORM:

https://mikro-orm.io/docs/nested-populate

In v4 it will be also possible to load entities via single query, see more in #517.

**Comment by nikolaylaz** [comment]
The problem is that in the first case the query for rates is missing there is only one query for application:
select `e0`.* from `application` as `e0` 

I have also tried to load the rate for the first result:

```javascript

 let res = await this.applicationRepository.findAll({
      populate: ['rate']
    });
    console.log(res.length); // 2
    console.log(await res[0].rate) // undefined
```

This is the whole output from the code above:

```
[0] [Nest] 10104   - 2020-05-10 1:00:17   [MikroORM] [query] select `e0`.* from `application` as `e0` [took 3 ms]
[0] 2
[0] undefined

```

**Comment by B4nan** [comment]
Confirmed, and its not just about population, inserting to such table also fails. 

As a workaround, looks like it works when you also provide `fieldName`:

    @OneToOne({ joinColumn: 'application_rate_id', fieldName: 'application_rate_id', inversedBy: 'application' })
    rate!: Rate;

**Comment by nikolaylaz** [comment]
Thank you !
