### ISSUE TITLE
Mongodb driver doesn't detect deep updates

### ISSUE THREAD

**Issue by briankchan** [mikro-orm/mikro-orm#5572]
### Describe the bug

Changes in nested objects are not detected when flushing with the mongodb driver. (The same test seems to work fine with the sqlite driver, though.)

### Reproduction

https://github.com/briankchan/mikro-orm-bug-mongodb-deep

### What driver are you using?

@mikro-orm/mongodb

### MikroORM version

tested on 6.2.2 and 6.2.7-dev.0

### Node.js version

v20.12.2

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Interesting, thanks for a failing repro, I remember several cases like this and this one might be the first valid case actually. 

Workaround for now is to reassign the whole object value:

```ts
usr2.a = { b: 100 };
```
