### ISSUE TITLE
[Bug]: Loaded type does not catch missing population types when Collection is in `populate` array

### ISSUE THREAD

**Issue by kpervin** [mikro-orm/mikro-orm#5580]
### Describe the bug

When adding a function that has the loaded type as an argument, it should only accept an entity that has those populated relations. However, if you introduce a `Collection` relation into the `populate` array when fetching the entity before passing it to the function, `Loaded` seems to not throw an error on the function argument.

### Reproduction

https://github.com/kpervin/mikro-orm-reproduction/tree/loaded-population-issue

### What driver are you using?

@mikro-orm/mysql

### MikroORM version

next

### Node.js version

20.9.0

### Operating system

5.15.146.1-microsoft-standard-WSL2

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
You need to use the `Ref` wrapper on the M:1 properties, otherwise this cannot work.

**Comment by kpervin** [comment]
Alright, glad to know that's the issue. I figured that was likely the case, as it was resolved as soon as I added the `Ref` attribute. That being said, the types still don't match so therefore it should throw an error, no?

**Comment by B4nan** [comment]
Nope, without using the `Ref` wrapper, there is no difference between a populated and not populated relation property (on type level), without that the assignability cannot work properly - its not about comparing the populate hint, its about assignability of what the `Loaded` type resolves.

**Comment by kpervin** [comment]
Well I have a lot of refactoring to do it seems given we did not use the `Ref` property in the beginning...

**Comment by B4nan** [comment]
It would be technically possible to make this work without the `Ref` wrapper, but it would be quite a breaking change. It's not just about the assignability of the `Loaded` type itself in explicit hints, it would affect the assignability of relations in general.

Maybe something to think about when I start thinking about v7 (next year+).

**Comment by kpervin** [comment]
Not sure if it's worth it, tbh. It's kind of in the name: Type-Safe relations :P

**Comment by kpervin** [comment]
On second thought, it would be nice to have relations loaded via `populate` and it affects the returned value, where any omitted values from the `populate` array is simply omitted from the returned entity not unlike Prisma. That would reduce the need for the `Ref` type in its entirety. It would be a fundamental change however, but what are your thoughts on that?
