### ISSUE TITLE
Join column named after children when using @ManyToMany on STI parent entity

### ISSUE THREAD

**Issue by ersinakinci** [mikro-orm/mikro-orm#5586]
### Describe the bug

MikroORM exhibits two unexpected behaviors when using `@ManyToMany` on an STI parent entity:

1. When creating the pivot table for the parent entity relationship, the default join column is named after the last initialized child entity.
2. When adding to the many to many collection through a child entity instance, it attempts to use a join column named after the child.

So if I have `@ManyToMany` on Foo (parent), and I have Bar and Baz as children, I expect the default join column to always be `foo_id` on my pivot table, but sometimes it ends up as `bar_id` or `baz_id`.

See repro for an example.

### Reproduction

https://github.com/ersinakinci/mikro-orm-sti-relations-issue

**Entities**

- Privilege
- PrivilegeGroup
- User (STI parent)
  - SuperUser (STI child 1)
  - AdminUser (STI child 2)

Entities are initialized in the following order: User, Privilege, PrivilegeGroup, SuperUser, AdminUser

Pivot table is `user_privileges` with columns `privilege_id` and `admin_user_id` (expected: `user_privileges` with columns `privilege_id` and `user_id`).

Calling `superUser.privileges.add(...)` results in attempting to execute ``insert into `user_privileges` (`privilege_id`, `super_user_id`) values (...)`` (expected: ``insert into `user_privileges` (`privilege_id`, `user_id`) values (...)``)

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.2.7-dev.5

### Node.js version

node 21.7.1, typescript 5.4.5

### Operating system

macOS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ersinakinci** [comment]
A workaround is to redefine the `@ManyToMany` relationship within each child entity and explicitly define the join column:

```
@Entity({ discriminatorColumn: "type" })
class User { ... }

@Entity()
class SuperUser extends User {
  @ManyToMany({ entity: () => Privilege, joinColumn: "user_id" })
  privileges = new Collection<Privilege>(this);
}

@Entity()
class AdminUser extends User {
  @ManyToMany({ entity: () => Privilege, joinColumn: "user_id" })
  privileges = new Collection<Privilege>(this);
}
```

**Comment by B4nan** [comment]
You don't have to redefine anything, just define the `joinColumn` on the parent. Redefining relations seems like a bad idea on its own to me.

**Comment by carlosV2** [comment]
I literally started crafting a minimal example to create a bug report like this at the same time you were creating yours!

Anyway, if anyone is interested, this is the minimal example: https://github.com/carlosV2/mo-test

The idea on the example is to have a parent Book entity and 2 child entities extending it (PaperbackBook and HardcoverBook). The name of the books is a many-to-many with Text which has a language field to provide translations.

This example is a super-simplification of a real-life code I'm currently working on.

You can run `npm run db` to provide yourself a PostgreSQL DB (via docker) and then run `npm run app` to get the SQL printed in screen.

In my case it yields the following:
```
create table "book" ("id" text not null, "pages" int not null, "cover" text check ("cover" in ('paperback', 'hardcover')) not null, constraint "book_pkey" primary key ("id"));
create index "book_cover_index" on "book" ("cover");

create table "text" ("id" text not null, "language" text check ("language" in ('en', 'es')) not null, "content" text not null, constraint "text_pkey" primary key ("id"));

create table "book_name" ("hardcover_book_id" text not null, "text_id" text not null, constraint "book_name_pkey" primary key ("hardcover_book_id", "text_id"));

alter table "book_name" add constraint "book_name_hardcover_book_id_foreign" foreign key ("hardcover_book_id") references "book" ("id") on update cascade on delete cascade;
alter table "book_name" add constraint "book_name_text_id_foreign" foreign key ("text_id") references "text" ("id") on update cascade on delete cascade;
```

Notice how the `book_name` table has the `hardcover_book_id` while it should be just `book_id`.

**Comment by ersinakinci** [comment]
@B4nan thanks for the improved workaround. I just confirmed that works on the test repo, in my actual project, which uses the PostgreSQL driver, and @carlosV2' repo. I *thought* that I had already tried that approach and it didn't work, but it seems that there were some other issues in my code that made it fail.

That said, it's still a workaround. I think that the default behavior is unexpected and undesirable.

**Comment by ersinakinci** [comment]
> I literally started crafting a minimal example to create a bug report like this at the same time you were creating yours!

@carlosV2 small world :-)

**Comment by B4nan** [comment]
I hope the fix wont break anything else :D

**Comment by B4nan** [comment]
Of course, it broke one test and I managed to miss that locally, its gonna be a bit harder.

**Comment by ersinakinci** [comment]
Thank you for jumping on the fix so quickly, @B4nan! I love MikroORM, thanks for all the work you put into it.
