### ISSUE TITLE
'longblob' property generates `varchar(255)`  in the snapshot

### ISSUE THREAD

**Issue by Minhir** [mikro-orm/mikro-orm#5587]
### Describe the bug

The entity with `longblob` type field doesn't preserve it in the `.snapshot.json`. The same is true for `tinyblob` and `mediumblob`. 

## Possible solution

Looks like we should add more cases here https://github.com/mikro-orm/mikro-orm/blob/e8c0c3fe1d539d363f254ba039182eca4f15d39c/packages/core/src/platforms/Platform.ts#L277-L278 and extend the `BlobType`. But also I can see that there are different int types (`TinyIntType`, `MediumIntType`,  `SmallIntType`), so don't sure what is better: to have one `BlobType` with `size` prop inside or create few types `TinyBlobType`, `MediumBlobType`, `LongBlobType`.  @B4nan what do you think? BTW thanks for the great library! 

### Reproduction

Entity with property

```ts
@Property({ lazy: true, type: "longblob" })
public data!: Buffer;
```

will look like this in `json` file:

```json
"data": {
  "name": "data",
  "type": "varchar(255)",
  "unsigned": false,
  "autoincrement": false,
  "primary": false,
  "nullable": false,
  "mappedType": "string"
}
```

### What driver are you using?

@mikro-orm/mysql

### MikroORM version

6.2.7 

### Node.js version

v20.11.1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
You should use `columnType: "longblob"` for anything that is not supported out of box, `type` is a processed variable that can hold different things (e.g. TS runtime type like `number` or a custom type class).

**Comment by Minhir** [comment]
> You should use `columnType: "longblob"` for anything that is not supported out of box, `type` is a processed variable that can hold different things (e.g. TS runtime type like `number` or a custom type class).

It works, thanks! 

I'm a bit confused that `'tinyblob' | 'mediumblob' | 'longblob'` are also part of the `type` field type. Do they add any difference? Maybe removing them from `type` TS definitions and keep them only in `columnType` types can improve DX a bit.

**Comment by B4nan** [comment]
Well, it should be working the way you tried, that's surely a bug. If the value in `type` does not match any existing type implementation, it should fallback to the value, so it should work the same as if you put it into `columnType`.
