### ISSUE TITLE
Explicit serialization throws error when serializing new embeddable

### ISSUE THREAD

**Issue by briankchan** [mikro-orm/mikro-orm#5603]
### Describe the bug

Attempting to serialize an entity after adding a new embeddable to it causes `TypeError: Cannot read properties of undefined (reading 'toJSON')`. E.g.,

```js
// after adding a new embeddable value to an entity
entity.embeddableField = { a: 1 }
// either of the following two lines will throw
wrap(entity).serialize()
serialize(entity) 
```

This seems to happen because `serialize` uses the `helper` function from `wrap`, which doesn't handle the case where `__helper` doesn't not exist.

Workaround: it seems that `wrap(entity).assign({embeddableField: { a: 1 } })` will create `__helper`, allowing explicit serialization to work.

### Reproduction

https://github.com/briankchan/mikro-orm-bug-serialize-new-pojo

### What driver are you using?

@mikro-orm/sqlite

### MikroORM version

6.2.7-dev.0

### Node.js version

node v20.12.2; typescript 5.4.5

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by briankchan** [comment]
Is this documented somewhere? I realize now that I can' find in the documentation anything that explicitly states how to add a new embeddable value to an entity, and assigning a POJO works with both `em.flush()` and implicit serialization, so I've always just assumed that this is how the feature is supposed to work.

Perhaps there could also be a helper type that can be used to cause a typescript error when trying to assign a POJO to an embeddable? E.g.

```
// secret symbol to prevent assigning arbitrary POJO
type Embed<T = unknown> = T & { [__secret]: 1 }
// ...
@Embedded()
embeddableField: Embed<MyEmbeddable>
```

(This would be a bit clunky with arrays of embeddables:

```
@Embedded({ array: true })
embeddables: Embed<MyEmbeddable>[]

// can't push newEmbeddable of type MyEmbeddable into Embed<MyEmbeddable>[]
wrap(entity).assign({ embeddables: [...entity.embeddables, newEmbeddable] })
```

but it does get the job done.)

**Comment by B4nan** [comment]
> Is this documented somewhere?

Generally speaking, the docs show how to do things, not the other way around. What you tried is nowhere in the docs, so I can ask the opposite question, why would you expect that to work, when its not documented anywhere this way? :]

Regarding your proposal, that wouldn't really work, you are supposed to be creating the embedded instance either by hand or via helpers like `em.assign` or `em.create`, and this would basically disallow using the constructor manually (or force you to type cast), I am not interested in that (and it would be breaking on type level).

**Comment by briankchan** [comment]
Ah right, I forgot about the constructor; I guess the proper solution then would be to change the class itself to prevent regular POJOs from matching the class's type. Speaking of `em.create`, are we supposed to be able to use `em.create(MyEmbeddable, {})` to directly create an embeddable? The repro repo above has a test case where attempting to do this throws an error, but I'm not sure if that's expected behavior or a bug. If it's not already a feature, would it be plausible to add it (or a similar helper method for creating embeddables)? I can open a new feature request if so.

> why would you expect that to work

If you're curious, here's my chain of thought:

- when assigning to entities, we can just set values like `entity.value = 10`
- when assigning to a JSON field, using a POJO is fine
- the documentation doesn't provide any examples that suggest that embeddable fields should work any differently from scalar/JSON fields
- assigning a POJO to an embeddable field would pass type checks (because to typescript, a class with no functions is no different from a POJO in many/most cases, even if the class has decorators)
- (obviously, the previous point doesn't make sense if the decorators on the class/fields do anything at runtime, but there's no way for someone who isn't familiar with the implementation to know whether the decorators have runtime significance or are just markers used to bulid the entity cache; and, in theory, the ORM has all the information necessary to allow this to work at runtime--it knows the class that the embeddable is supposed to be, so it could technically create the proper class automatically when it needs to)
- since the documentation doesn't explain how to create embeddables, we either need to read the source code or just try things until something works (and unfortunately I don't have time to read through the source code)
- in the simplest possible example (e.g., the repro repo) there's no custom constructor on the embeddable class, so my inclination is to try using a POJO first (since the syntax is shorter than defining a constructor or first creating an object, then assigning values to its fields)
- as it turns out, in simple cases, assigning a POJO actually works when saving/loading from the database; since the types are valid and the code runs, this must be the right way

There are a couple jumps in logic that that don't necessarily make sense, but that's pretty much how brains work. Since putting a POJO into something that requires a non-POJO is literally using the wrong type, I think the API should ideally trigger a type error, but that would be a breaking change. The second-best thing would be to provide documentation to teach users the intended way to use embeddables and maybe recommend a code pattern that could prevent this--it wont stop anyone from doing dumb things, but at least it would remove the need to use trial-and-error to figure out the right way to do things.

In case you're interested in updating the documentation for defining embeddables, I've pushed [a new branch](https://github.com/briankchan/mikro-orm-bug-serialize-new-pojo/tree/safer-embeddables/src) with examples of easy ways to block POJOs with properties:
- symbol getter function
  ```
  get [typeGuard]() { return }
  ```
- private property (looks neater, but requires `forceEntityConstructor`).
  ```
  #typeGuard: undefined
  ```
Alternatively, it may make more sense to simply recommend that embeddable classes extend `BaseEntity` or some equivalent `BaseEmbeddable` class, since the presence of any instance function is enough to differentiate the type from a POJO...
