### ISSUE TITLE
Renaming indexes generates faulty migration, drops existing indexes

### ISSUE THREAD

**Issue by arminrosu** [mikro-orm/mikro-orm#5617]
### Describe the bug

Hello,

I'm in the process of harmonizing index names in our Database. I stumbled upon a weird bug, where index renames actually drop the old index first, create a new index and try to rename a the lowercases old index.

Of course, the resulting migration is faulty and calling `migration:create` again will error out.

### Reproduction

Given this schema:

```ts
export const GroupSchema = new EntitySchema({
  class: Group,
  properties: {
    createdAt: createdAtField,
    createdBy: {
      entity: () => User,
      // Old index name:
      // index: 'createdBy',
      // Will generate `Group_createdBy_index`
      index: true,
      nullable: true,
      onDelete: 'set null',
      ref: true,
      reference: ReferenceType.MANY_TO_ONE,
    },
```

This is the sql migration that is generated:

```sql
alter table `Group` drop index `createdBy`;

alter table `Group` add index `Group_createdBy_index`(`createdBy`);
-- note the lowercase `createdBy` 
alter table `Group` rename index `createdby` to `Group_createdBy_index`;
```

I tracked down the issue to [these lines](https://github.com/mikro-orm/mikro-orm/blob/fc34c54740a600959d019cd6b0584d2b8f9bd908/packages/knex/src/schema/SchemaComparator.ts#L427-L428) in `@mikro-orm/knex`:

```ts
// createdby
const removedIndexName = removedIndex.keyName.toLowerCase();
// group_createdby_index
const addedIndexName = addedIndex.keyName.toLowerCase();

// ...
// Of course, the lowercased keys are not present in the `addedIndexes` or `removedIndexes` arrays.
delete tableDifferences.addedIndexes[addedIndexName];
delete tableDifferences.removedIndexes[removedIndexName];
```

The resulting `tableDifferences` object looks like:

```js
{
  name: 'Group',
  addedColumns: {},
  addedForeignKeys: {},
  addedIndexes: {
    createdBy: {
      columnNames: [ 'createdBy' ],
      keyName: 'createdBy',
      unique: false,
      primary: false
    }
  },
  addedChecks: {},
  changedColumns: {},
  changedForeignKeys: {},
  changedIndexes: {},
  changedChecks: {},
  removedColumns: {},
  removedForeignKeys: {},
  removedIndexes: {
    Group_createdBy_index: {
      columnNames: [ 'createdBy' ],
      composite: false,
      keyName: 'Group_createdBy_index',
      primary: false,
      unique: false
    }
  },
  removedChecks: {},
  renamedColumns: {},
  renamedIndexes: {
    group_createdby_index: {
      columnNames: [ 'createdBy' ],
      keyName: 'createdBy',
      unique: false,
      primary: false
    }
  },
```

Removing the `toLowerCase` calls generates a correct migration:

```sql
alter table `Group` rename index `createdBy` to `Group_createdBy_index`;
```

### What driver are you using?

@mikro-orm/mysql

### MikroORM version

5.9.8 AND 6.2.3

### Node.js version

20.12.2

### Operating system

MacOS 14.5

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
I hope this won't break anything, I just removed the lowercasing, from both places, as it looks like the keys are not lowercased at all.

**Comment by arminrosu** [comment]
Thanks for the swift fix! Any chance you can backport this to the 5.* branch as well? I understand if not.

**Comment by B4nan** [comment]
Nope, I don't plan to backport anything, only as part of paid support, that would be a different story. Also given this is a fix without any test, it would require more work to be safe to backport too, since tests would be crucial for that.
