### ISSUE TITLE
docs: redundant nav link in the footer

### ISSUE THREAD

**Issue by zetaraku** [mikro-orm/mikro-orm#5619]
There is a redundant nav link in the footer:

![Screenshot 2024-05-28 at 21-15-01 MikroORM TypeScript ORM for Node js based on Data Mapper Unit of Work and Identity Map patterns MikroORM](https://github.com/mikro-orm/mikro-orm/assets/9212875/1e651c17-0e35-476e-9875-4deec834ff19)

https://github.com/mikro-orm/mikro-orm/blob/1051470389d19c8429fbc7ce0e70e216a276f4ae/docs/docusaurus.config.js#L31-L40

**Comment by zetaraku** [comment]
Not sure if the link is just mislabeled or redundant. 🤔

**Comment by B4nan** [comment]
looks like a redundancy to me, i would just remove it
