### ISSUE TITLE
QueryBuilder `execute` Method Doesn't Properly Map Embeddables

### ISSUE THREAD

**Issue by vinialbano** [mikro-orm/mikro-orm#5621]
### Describe the bug

The QueryBuilder class in MikroORM has an `execute` method with the `mapResults` option. When `mapResults` is set to `false`, the method returns the raw table representation, which is the expected behavior. However, when `mapResults` is set to `true`, the method does not convert embeddables back into objects. Instead, it returns them as separate properties named according to the table columns, which doesn't seem to make much sense.

## Example Schemas
```typescript
export const PersonNameSchema = new EntitySchema<PersonName>({
  class: PersonName,
  embeddable: true,
  properties: {
    givenName: {
      type: 'string',
    },
    surname: {
      type: 'string',
    },
  },
});

export const EmergencyContactSchema = new EntitySchema<EmergencyContact>({
  class: EmergencyContact,
  embeddable: true,
  properties: {
    name: {
      kind: 'embedded',
      entity: () => PersonName,
      prefix: 'emergency_contact_', // have to override the parent prefix
    },
    relationship: { type: 'string' },
  },
});

export const PatientSchema = new EntitySchema<Patient>({
  class: Patient,
  properties: {
    id: {
      type: 'text',
      primary: true,
    },
    name: {
      kind: 'embedded',
      entity: () => PersonName,
      prefix: false,
    },
    emergencyContact: {
      kind: 'embedded',
      entity: () => EmergencyContact,
      prefix: 'emergency_contact_',
      nullable: true,
    },
  },
});
```

## Issue Reproduction
When executing the following command:

```typescript
qb.select(['*']).where({ id: '1' });
  const patient = await qb.execute('get', true);
```

## Expected Behavior
I would expect the mapped result to look like:

```json
{
  "id": "1",
  "name": {
    "givenName": "John",
    "surname": "Doe"
  },
  "emergencyContact": {
    "name": {
      "givenName": "Jane",
      "surname": "Doe"
    },
    "relationship": "wife"
  }
}
```

## Actual Behavior
Instead, I receive:

```json
{
  "id": "1",
  "name_givenName": "John",
  "name_surname": "Doe",
  "emergency_contact_name_givenName": "Jane",
  "emergency_contact_name_surname": "Doe",
  "emergency_contact_name_relationship": "wife"
}
```

## Importance
This feature is crucial for making queries without IDs and for correctly mapping complex structures.

Could you please address this issue and ensure that embeddables are properly mapped back to objects when mapResults is set to true? I have updated my repository from another bug to include test scenarios for this issue.

Thank you!

### Reproduction

https://github.com/mikro-orm/reproduction/pull/5

### What driver are you using?

@mikro-orm/sqlite

### MikroORM version

6.2.8

### Node.js version

v20.11.1

### Operating system

MacOS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
FYI this will be quite a big task to achieve, and I am honestly not sure if we shouldn't even consider this breaking. I spent a better part of yesterday trying to make this work, and I can already see it will take a few more _days_ to be able to finalize this.

**Comment by vinialbano** [comment]
IMO, it’s a bug, as we’re exposing MikroORM internal property names, instead of the entity properties, which is not the expected behavior.
But I understand if you prefer to consider it a breaking change. It’s impossible to say if someone currently depends on the current behavior.

Is there anything that I help with to facilitate this feature? I’d be happy to contribute.

**Comment by B4nan** [comment]
Hmm, that's a good point, I thought it maps to the column names, but given your prefixing setup, it's not the case.

**Comment by B4nan** [comment]
The problem here is that to get what you want from just result mapping, it means changing everything internally - result mapping, snapshotting, comparator, driver implementation, that all expect properties that map 1:1 to database columns in the entity snapshot. Even if I do all of that, I would now have to deal with a new problem of detecting partial changes on the inline embedded properties. I managed to implement the hard part, which is result mapping, but it opened a can of worms.

Maybe it would be better to deal with this locally, only in case you explicitly call `qb.execute()`, and keep the internally mapped state as is.

**Comment by vinialbano** [comment]
I don’t think the effort will be worthwhile if you need to change all the ORM internal functioning. I just really care about what we’re exposing to the users in the `qb.execute` since it seems to currently be the only way of querying the database without loading entire entity instances.

My use case is using CQRS, which MikroORM does a great job for commands, but it seems to be more difficult to make custom queries that return results straight from the database for views, without managing state.

So I want to generate reports with a few specific columns, using joins, pagination, and etc. It seems that QueryBuilder is the way to go. It just returns objects with weird property names. I could use `mapResults = false` and manually map data back to an entity-like format. But since the ORM already have tools to do so, and it seemed that it was the intended purpose for `mapResults = true`, I opened this ticked.

Let me change my question then. If changing the return of `qb.execute` will break everything, is there a way to expose some helper mapping functions that we could manually use to parse raw data? That would facilitate my use case a lot.

**Comment by B4nan** [comment]
> from the database for views

I would just use a raw query for that, via virtual entity mapping.

**Comment by vinialbano** [comment]
Okay, great! That will work. I have some questions about how to properly use the virtual entity, but I can ask on Discord.
Thanks @B4nan
