### ISSUE TITLE
createForeignKeyConstraints Configuration options support in Migrations

### ISSUE THREAD

**Issue by harihararam-sriram** [mikro-orm/mikro-orm#5631]
**Is your feature request related to a problem? Please describe.**
`createForeignKeyConstraints` Configuration options support is present in `schemaGenerator` but is missing in migrations. I require this feature for setting up migrations in my project.

**Describe the solution you'd like**
A configuration `createForeignKeyConstraints` to create migrations without foreign key constrains in the generated migration files.

**Describe alternatives you've considered**
I had considered the option of dropping and creating schema which is not efficient and can cause data loss if schema is changed in future. We require support for this in migrations which is incremental and efficient.

**Additional context**
We are using Azure SQL server deployment which is capped at v12.00.5506 and we require this feature to setup migrations.

**Comment by B4nan** [comment]
Migrations use the schema generator, you can use that option already.
