### ISSUE TITLE
Subsequent queries from identity cache don't honor field settings or exclude options

### ISSUE THREAD

**Issue by AdamJessop** [mikro-orm/mikro-orm#5632]
### Describe the bug

When utilising lazy columns and exclude options in queries in order to protect potential sensitive data leaking or any unwanted information being returned, any subsequent query to the database where data sits in the identity cache is merged and returned without respecting such configuration.

### Reproduction

https://github.com/AdamJessop/mikro-orm-cache-hydration-error

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.2.8+

### Node.js version

21.4.0

### Operating system

Ubuntu

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
This is expected behavior, you never get less than what is already loaded. You can use `refresh: true` to replace the already loaded state.
