### ISSUE TITLE
Not able to run migrations in MS SQL Server

### ISSUE THREAD

**Issue by harihararam-sriram** [mikro-orm/mikro-orm#5633]
### Describe the bug

I am trying to run the migration file generated for using the migration up command. It runs into an error
```
Error: createSchema is not supported for this dialect (only PostgreSQL supports it currently).
    at throwOnlyPGError (C:\project\node_modules\.pnpm\knex@3.1.0_pg@8.11.5_tedious@18.2.0\node_modules\knex\lib\schema\compiler.js:182:9)
    at SchemaCompiler_MSSQL.createSchema (C:\project\node_modules\.pnpm\knex@3.1.0_pg@8.11.5_tedious@18.2.0\node_modules\knex\lib\schema\compiler.js:25:5)
    at SchemaCompiler_MSSQL.toSQL (C:\project\node_modules\.pnpm\knex@3.1.0_pg@8.11.5_tedious@18.2.0\node_modules\knex\lib\schema\compiler.js:97:26)
    at SchemaBuilder.toSQL (C:\project\node_modules\.pnpm\knex@3.1.0_pg@8.11.5_tedious@18.2.0\node_modules\knex\lib\schema\builder.js:36:51)
    at ensureConnectionCallback (C:\project\node_modules\.pnpm\knex@3.1.0_pg@8.11.5_tedious@18.2.0\node_modules\knex\lib\execution\internal\ensure-connection-callback.js:4:30)
    at Runner.ensureConnection (C:\project\node_modules\.pnpm\knex@3.1.0_pg@8.11.5_tedious@18.2.0\node_modules\knex\lib\execution\runner.js:318:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Runner.run (C:\project\node_modules\.pnpm\knex@3.1.0_pg@8.11.5_tedious@18.2.0\node_modules\knex\lib\execution\runner.js:30:19)
    at async MigrationStorage.ensureTable (C:\project\node_modules\.pnpm\@mikro-orm+migrations@6.2.8_@mikro-orm+core@6.2.8_@types+node@18.15.11_pg@8.11.5\node_modules\@mikro-orm\migrations\MigrationStorage.js:81:13)
    at async Migrator.ensureDatabase (C:\project\node_modules\.pnpm\@mikro-orm+migrations@6.2.8_@mikro-orm+core@6.2.8_@types+node@18.15.11_pg@8.11.5\node_modules\@mikro-orm\migrations\Migrator.js:173:9)
```

## How to Reproduce

1) Create an Azure SQL server resource and a database
2) Using the MSSQL driver present in version 6.2.8, we have use the following mikroorm configuration in a nest js application.
```ts
import { LoadStrategy, Platform } from '@mikro-orm/core';
import { Migrator } from '@mikro-orm/migrations';
import {
  MsSqlDriver,
  defineConfig,
  StringType,
  Type,
  ArrayType,
} from '@mikro-orm/mssql';
import { TsMorphMetadataProvider } from '@mikro-orm/reflection';
import { SeedManager } from '@mikro-orm/seeder';
import { SqlHighlighter } from '@mikro-orm/sql-highlighter';
import { Logger, NotFoundException } from '@nestjs/common';
import 'dotenv/config';

const logger = new Logger('MikroORM');

// const isPortfolio = process.env.NODE_ENV === 'portfolio';

const config = defineConfig({
  entities: ['dist/backend/**/*.entity.js'],
  entitiesTs: ['src/**/*.entity.ts'],
  driver: MsSqlDriver,
  loadStrategy: LoadStrategy.JOINED,
  dbName: process.env['MSSQL_DBNAME'] as string,
  host: process.env['MSSQL_DBHOST'] as string,
  password: process.env['MSSQL_DBPASSWORD'] as string,
  user: process.env['MSSQL_DBUSERNAME'] as string,
  port: parseInt(process.env['MSSQL_DBPORT'] || '1433', 10),
  highlighter: new SqlHighlighter(),
  driverOptions: {
    connection: {
      database: process.env['MSSQL_DBNAME'] as string,
      userName: process.env['MSSQL_DBUSERNAME'] as string,
      password: process.env['MSSQL_DBPASSWORD'] as string,
      encrypt: true,
      trustServerCertificate: true,
      port: parseInt(process.env['MSSQL_DBPORT'] || '1433', 10),
    },
  },
  debug: true,
  logger: logger.log.bind(logger),
  metadataProvider: TsMorphMetadataProvider,
  allowGlobalContext: true,
  discovery: {
    getMappedType(type: string, platform: Platform) {
      // override the mapping for string properties only
      if (type === 'enum') {
        return Type.getType(StringType);
      }
      if (type === 'string') {
        return Type.getType(StringType);
      }
      if (type === 'enumArray') {
        return Type.getType(ArrayType);
      }

      return platform.getDefaultMappedType(type);
    },
  },
  migrations: {
    tableName: 'mikro_orm_migrations',
    path: './migrations',
    glob: '!(*.d).{js,ts}',
    transactional: true,
    disableForeignKeys: true,
    allOrNothing: true,
    dropTables: false,
    safe: true,
    emit: 'ts', // migration generation mode
  },
  schemaGenerator: {
    disableForeignKeys: true,
    createForeignKeyConstraints: false,
  },
  seeder: {
    path: './dist/backend/seeders',
    pathTs: './seeders',
    defaultSeeder: 'DatabaseSeeder',
    glob: '!(*.d).{js,ts}',
    emit: 'ts',
    fileName: (className: string) => className,
  },
  extensions: [Migrator, SeedManager],
  findOneOrFailHandler: (entityName) => {
    throw new NotFoundException(`${entityName} not found`);
  },
});

export default config;
```
3) After defining the entities, we create a migration file using `pnpm run mikro-orm migration:create`; Migration file is successfully created.
4) We run the migration `pnpm run mikro-orm migration:up` we get the above error.

## Debugging

While debugging the node modules folder I had identified that there is **no function** for getting the namespaces in the file `project\node_modules\@mikro-orm\mssql\MsSqlSchemaHelper.js` like how it is there for the file `PostgreSqlSchemaHelper.js` under the `@mikro-orm/postgresql`.
If you have a look at the below file I have mentioned
`project\node_modules\@mikro-orm\migrations\MigrationStorage.js`
In the line 79, the variable schemas gets an empty value as an array for namespaces, causing the line 81 `knex.schema.createSchema()` to fail (CHECK THE STACK TRACE)

## Solution I had tried

I had tried this solution by pasting this code snippet into MsSqlSchemaHelper.js and I was able to run the migration successfully.
```js
    async getNamespaces(connection){
        return ['dbo'];
    }
```

![image](https://github.com/mikro-orm/mikro-orm/assets/158017326/ab2c7bb4-9513-45b1-bdf3-fb6b990baed9)

Can you please help me out with this.

### What driver are you using?

@mikro-orm/mssql

### MikroORM version

6.2.8

### Node.js version

v20.11.0

### Operating system

Windows 11 23H2

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
This is a missing support in knex, its not coming from the ORM.

**Comment by B4nan** [comment]
But maybe your entities do not use multiple schemas at all - provide a complete repro, I can't tell from your ORM config what you are doing.

> I had tried this solution by pasting this code snippet into MsSqlSchemaHelper.js and I was able to run the migration successfully.

Especially if this helps, it kinda confirms that you don't... What you propose is a workaround, that method needs to be dynamic and return the existing schemas, not just one hardcoded default schema.

**Comment by harihararam-sriram** [comment]
No @B4nan,
I am not using multiple schemas, an all my entities have the plain `@Entity` decorator only on top of their definition.
E.g.
```ts
@Entity()
export class User extends BaseEntity {
  @Property()
  firstName: string;

  @Property()
  lastName: string;

  @Property({ default: false })
  isDeleted = false;

  @Property()
  @Unique()
  email: string;
}
```
This is an entity in my project. All my entities have the same decorator `@Entity()`. All are under the same default schema.

**Comment by harihararam-sriram** [comment]
What I have observed in the
`@mikro-orm\postgresql\PostgreSqlSchemaHelper.js`

There is a override of the `getNamespaces` method inside the class `PostgreSqlSchemaHelper`

I want a similar override of the `getNamespaces` method in the function that can dynamically do the job like how it's done in PostgreSqlSchemaHelper. I require this for my migrations to pass otherwise you won't be able to use migrations in SQL Server as it's broken without this.

**Comment by B4nan** [comment]
> I want a similar override of the getNamespaces method in the function that can dynamically do the job of getting namespaces like how it's done in PostgreSqlSchemaHelper.

Yeah that's exactly what is missing, it needs to dynamically return the existing schemas like in postgres.

**Comment by harihararam-sriram** [comment]
Okay I am up for a PR. I will let you know once I raise one.
