### ISSUE TITLE
MS SQL Get Database Existence query fails during application start

### ISSUE THREAD

**Issue by harihararam-sriram** [mikro-orm/mikro-orm#5638]
## Reference to the Code

https://github.com/mikro-orm/mikro-orm/blob/221ce63ab12db7c9c6a6a0bcefa22aef5c05c0dd/packages/mssql/src/MsSqlSchemaHelper.ts#L42-L44

## Error I am facing

I have a Nest JS project in which I have connected Azure SQL server database with mikro-orm. When I run my server I am unable to 
pass the database existence query as it fails with the following error

### Stacktrace

```
[Nest] 43048  - 05/30/2024, 5:52:10 PM   ERROR [ExceptionHandler] select 1 from master.sys.databases where name = N'credential-manager' - Reference to database and/or server name in 'master.sys.databases' is not supported in this version of SQL Server.
Error: select 1 from master.sys.databases where name = N'credential-manager' - Reference to database and/or server name in 'master.sys.databases' is not supported in this version of SQL Server.
    at RequestTokenHandler.onErrorMessage (C:\project\node_modules\.pnpm\tedious@18.2.0\node_modules\tedious\src\token\handler.ts:389:21)
    at Readable.<anonymous> (C:\project\node_modules\.pnpm\tedious@18.2.0\node_modules\tedious\src\token\token-stream-parser.ts:22:55)
    at Readable.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushObjectMode (node:internal/streams/readable:536:3)
    at Readable.push (node:internal/streams/readable:391:5)
    at nextAsync (node:internal/streams/from:194:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

The SQL query that is being executed to check the existence of the database is:
```sql
select 1 from master.sys.databases where name = N'credential-manager'
```

## Solution I have tried

This query when modified by removing `master.` from `master.sys.databases` in that file, is now working perfectly.

Like this:

```sql
select 1 from sys.databases where name = N'credential-manager'
```

This query is present inside the function getDatabaseExistsSQL (highlight link in the top to the code). If you look at all other queries in the file other than this, they don't have the `master.sys` prefix and are directly referred using `sys.` as prefix without `master`. 
E.g. https://github.com/mikro-orm/mikro-orm/blob/221ce63ab12db7c9c6a6a0bcefa22aef5c05c0dd/packages/mssql/src/MsSqlSchemaHelper.ts#L49

Why are we using this `master.` prefix alone here and I believe we can remove that prefix from `getDatabaseExistsSQL` function and it will function properly. We change the query to this

```sql
select 1 from sys.databases where name = N'credential-manager'
```

Thank you! :)

### Reproduction

1) Create an Azure SQL server resource and a database
2) Using the MSSQL driver present in version 6.2.8, we have use the following mikroorm configuration in a nest js application.
```ts
import { LoadStrategy, Platform } from '@mikro-orm/core';
import { Migrator } from '@mikro-orm/migrations';
import {
  MsSqlDriver,
  defineConfig,
  StringType,
  Type,
  ArrayType,
} from '@mikro-orm/mssql';
import { TsMorphMetadataProvider } from '@mikro-orm/reflection';
import { SeedManager } from '@mikro-orm/seeder';
import { SqlHighlighter } from '@mikro-orm/sql-highlighter';
import { Logger, NotFoundException } from '@nestjs/common';
import 'dotenv/config';

const logger = new Logger('MikroORM');

// const isPortfolio = process.env.NODE_ENV === 'portfolio';

const config = defineConfig({
  entities: ['dist/backend/**/*.entity.js'],
  entitiesTs: ['src/**/*.entity.ts'],
  driver: MsSqlDriver,
  loadStrategy: LoadStrategy.JOINED,
  dbName: process.env['MSSQL_DBNAME'] as string,
  host: process.env['MSSQL_DBHOST'] as string,
  password: process.env['MSSQL_DBPASSWORD'] as string,
  user: process.env['MSSQL_DBUSERNAME'] as string,
  port: parseInt(process.env['MSSQL_DBPORT'] || '1433', 10),
  highlighter: new SqlHighlighter(),
  driverOptions: {
    connection: {
      database: process.env['MSSQL_DBNAME'] as string,
      userName: process.env['MSSQL_DBUSERNAME'] as string,
      password: process.env['MSSQL_DBPASSWORD'] as string,
      encrypt: true,
      trustServerCertificate: true,
      port: parseInt(process.env['MSSQL_DBPORT'] || '1433', 10),
    },
  },
  debug: true,
  logger: logger.log.bind(logger),
  metadataProvider: TsMorphMetadataProvider,
  allowGlobalContext: true,
  discovery: {
    getMappedType(type: string, platform: Platform) {
      // override the mapping for string properties only
      if (type === 'enum') {
        return Type.getType(StringType);
      }
      if (type === 'string') {
        return Type.getType(StringType);
      }
      if (type === 'enumArray') {
        return Type.getType(ArrayType);
      }

      return platform.getDefaultMappedType(type);
    },
  },
  migrations: {
    tableName: 'mikro_orm_migrations',
    path: './migrations',
    glob: '!(*.d).{js,ts}',
    transactional: true,
    disableForeignKeys: true,
    allOrNothing: true,
    dropTables: false,
    safe: true,
    emit: 'ts', // migration generation mode
  },
  schemaGenerator: {
    disableForeignKeys: true,
    createForeignKeyConstraints: false,
  },
  seeder: {
    path: './dist/backend/seeders',
    pathTs: './seeders',
    defaultSeeder: 'DatabaseSeeder',
    glob: '!(*.d).{js,ts}',
    emit: 'ts',
    fileName: (className: string) => className,
  },
  extensions: [Migrator, SeedManager],
  findOneOrFailHandler: (entityName) => {
    throw new NotFoundException(`${entityName} not found`);
  },
});

export default config;
```
3) Run the nest application or the code that initializes your Mikro-orm instance.
4) You will get this error because the first task mikro-orm will run is to check the existence of database using this query, causing the application to error.

### What driver are you using?

@mikro-orm/mssql

### MikroORM version

6.2.8

### Node.js version

v20.11.0

### Operating system

Windows 11 23H2

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
I think I just copied this from somewhere, it was working locally so I thought it's ok. If it works fine without the prefix, let's just remove it.
