### ISSUE TITLE
[v6] Batch Update on unique field failed

### ISSUE THREAD

**Issue by vinverdy** [mikro-orm/mikro-orm#5656]
### Describe the bug

because using batch,
```sql
update `user` set `username` = case when (`id` = 1) then 'test' when (`id` = 2) then NULL else `username` end where `id` in (1, 2)
```
query generated be like this when on db username=test still used by user with id 2

the problem persist even using `useBatchUpdates: false`, 

the query generated
```sql
update `user` set `username` = 'test' where `id` = 1
```
 

### Reproduction

```ts
import { Entity, MikroORM, PrimaryKey, Property } from '@mikro-orm/sqlite';

@Entity()
class User {

  @PrimaryKey()
  id!: number;

  @Property({ nullable: true, unique: true })
  username?: string;

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [User],
    dbName: `:memory:`,
    useBatchUpdates: false,
  });
  await orm.schema.refreshDatabase();
});

afterAll(() => orm.close(true));

test('5656', async () => {
  const userA = new User();
  const userB = new User();
  userB.username = 'test';
  await orm.em.persistAndFlush([userA, userB]);

  userA.username = 'test';
  userB.username = undefined;
  await orm.em.flush();
});
```

### What driver are you using?

@mikro-orm/sqlite

### MikroORM version

6.2.8

### Node.js version

22

### Operating system

mac

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
I am honestly not sure how to fix this. In postgres you could use deferred constraint, but other drivers don't support this, and I would rather not try to deal with the order of queries touching the same entity type internally, we only care about the order of types now. Right now it feels like a wontfix, you should split the queries yourself and flush in the middle.

Note that its really just about the order in which you do things, this will pass:

```ts
const userA = new User();
const userB = new User();
userB.username = 'test';
await orm.em.persistAndFlush([userB, userA]); // changed order here

userA.username = 'test';
userB.username = undefined;
await orm.em.flush();
```

**Comment by B4nan** [comment]
That entity definition seems wrong, 1:1 decorator already creates unique constraint, remove your `@Unique` decorator. Also try using latest dev version, I think there are some fixes connected to this too.

If you would want to keep the explicit unique decorator, you need to specify the defer mode there too. But again, it would only duplicate the constraints.

**Comment by B4nan** [comment]
You dont even need to specify `unique: true`, 1:1 properties are unique by definition.

```ts
@OneToOne(() => Pet, { nullable: true, eager: true, deferMode: DeferMode.INITIALLY_DEFERRED })
pet?: Pet;
```
