### ISSUE TITLE
Wrong migration schema generated when adding value to Enum

### ISSUE THREAD

**Issue by chrisbenincasa** [mikro-orm/mikro-orm#5672]
### Describe the bug

To alter a column, the migration generator for SQLite creates a temp table, moves all existing data, and then renames the table. When using an enum column in SQLite, the `CHECK` directive is used with an `IN` to limit the values that can be inserted.

When adding a new value to an enum type, incorrect schema gets generated, example when adding a single value:
```
    this.addSql('CREATE TABLE `_knex_temp_alter011` (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `t` text check (`t` in (\'a\', \'b\', \'c\')) NOT NULL CHECK (`t` in(\'a\' , \'b\')));');
```

### Reproduction

https://github.com/chrisbenincasa/reproduction-populate-hint/tree/enum-type-migration

Steps I took:

1. Create an Enum with 2 string values
2. Define an Entity with an Enum column and use the Enum from step 1
3. Generate an initial migration schema. At this point we'll have something like this:

```
    this.addSql('create table `a` (`id` integer not null primary key autoincrement, `t` text check (`t` in (\'a\', \'b\')) not null);');
```

4. Add a new string value to the Enum
5. Generate a new migration. This produces the 'temp table' migration, but the new table definition includes the CHECK statements for both the previous incarnation of the Enum and the new one:

```
    this.addSql('CREATE TABLE `_knex_temp_alter011` (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `t` text check (`t` in (\'a\', \'b\', \'c\')) NOT NULL CHECK (`t` in(\'a\' , \'b\')));');
```

 

### What driver are you using?

@mikro-orm/sqlite

### MikroORM version

6.2.9

### Node.js version

20.11.1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chrisbenincasa** [comment]
I stumbled on this while getting a reproduction for another bug. I'll document it here but let me know if you'd like me to open a new issue instead.

The second bug I found is that when adding an index to an entity (column or entity level) while also changing enum values, the enum value changes get dropped in the generated schema, despite the snapshot DB json getting updated (which can lead to some pretty wild behavior later on)

I've branched the reproduction from the initial bug to preserve its state: https://github.com/chrisbenincasa/reproduction-populate-hint/tree/new-index-no-enum

**Comment by B4nan** [comment]
Those are most likely bugs in knex, that is what creates the temp table.

**Comment by chrisbenincasa** [comment]
Ah yep. Looks like the first issue is there already: https://github.com/knex/knex/issues/4450

Not sure about the second issue though where some migrations aren't generated at all.

**Comment by B4nan** [comment]
yeah, lol, and 3 years are gone and they ignore it completely. yet another reason to drop knex.

i will see what i can do, in the end, what knex is doing is a proper black magic which we don't need since we have all the necessary metadata in place. i think we could replace that with custom implementation relatively easily - there wont be major roadblocks, but it will be a lot of work.

**Comment by chrisbenincasa** [comment]
No problem, I appreciate the effort (and have experienced your pain with an unwieldy but core dependency in other projects)!

**Comment by B4nan** [comment]
So I came up with this workaround: #5683. I am not entirely happy with what I did there, but replacing the whole knex based implementation would be way too time-consuming.,
