### ISSUE TITLE
nativeDelete is not supplying table alias in all instances

### ISSUE THREAD

**Issue by DASPRiD** [mikro-orm/mikro-orm#5676]
### Describe the bug

In some instances it seems that the query built for `nativeDelete` (and potentially other cases) is "forgetting" to put the table alias down for the table to delete from, see reproduction case.

### Reproduction

Given the following entities:

```ts
@Entity()
class Author {

  @PrimaryKey({ type: t.integer })
  id?: number;

}

@Entity()
class Book {

  @PrimaryKey({ type: t.integer })
  id?: number;

  @ManyToOne(() => Author)
  author?: Author;

}
```

Running the following code:

```ts
await orm.em.nativeDelete(Book, { author: { id: { $in: [1, 2, 3] } } });
```

Will result in the following error:

```
InvalidFieldNameException: delete from `book` where `b0`.`author_id` in (1, 2, 3) - SQLITE_ERROR: no such column: b0.author_id
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.2.9

### Node.js version

v20.14.0

### Operating system

PopOS 22.04

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DASPRiD** [comment]
I looked a little bit around the code. This seems to happen within the knex `QueryBuilder`. I'm not certain whether the bug is that the alias is omitted from the table itself or that an unknown alias is used in the where clause.

Either way this code is slightly complex and I don't feel confident right now in "fixing" either.

**Comment by B4nan** [comment]
Interested, if this is an explicit usage, you can do this (which works fine):

```ts
await orm.em.nativeDelete(Book, { author: { $in: [1, 2, 3] } });

// or just this

await orm.em.nativeDelete(Book, { author: [1, 2, 3] });
```
