### ISSUE TITLE
Virtual properties defined as getters are recognized as required by RequiredEntityData

### ISSUE THREAD

**Issue by hartbit** [mikro-orm/mikro-orm#5686]
### Describe the bug

Defining a virtual property using a getter, like in the [documentation](https://mikro-orm.io/docs/defining-entities#virtual-properties) breaks calls to `create` and any other function depending on `RequiredEntityData` as it thinks the property is required.

### Reproduction

Using the following reproduction https://github.com/hartbit/reproduction-virtual-property-getter-required, we get the following TypeScript error:

```ts
orm.em.create(User, { firstName: 'Foo', lastName: 'Bar', email: 'foo' });
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Argument of type '{ firstName: string; lastName: string; email: string; }' is not assignable to parameter of type 'RequiredEntityData<User, never, false>'.
  Property 'fullName' is missing in type '{ firstName: string; lastName: string; email: string; }' but required in type '{ firstName: string; lastName: string; readonly fullName: string; email: string; }'.ts(2345)
```

### What driver are you using?

None

### MikroORM version

6.2.10-dev.28

### Node.js version

20.13.1

### Operating system

macOS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
You need to mark it as optional on type level, use `OptionalProps` symbol or `Opt` type. 

https://mikro-orm.io/docs/guide/relationships#using-entity-constructor

**Comment by hartbit** [comment]
@B4nan My bad!

**Comment by B4nan** [comment]
Its actually a good point that we dont use the Opt type in the docs, it was added much later (same with the type level strictness), I will adjust the examples. Let me know if you find more places like this (or send a PR right ahead).
