### ISSUE TITLE
Sorting by relation does not work with `fields` or `populate` option

### ISSUE THREAD

**Issue by mrmlnc** [mikro-orm/mikro-orm#5688]
### Describe the bug

If you specify the `fields` or `populate` field, sorting by relation will not work unless you explicitly specify the sorting field (relation pk).

```js
// Does not work
const projects = await orm.em.findAll(Project, {
  fields: ['workspace.sid'], // It also does not work with `fields: ['*']` or `populate: ['workspace']`.
  orderBy: { workspace: 'ASC' },
});

// SQL:
// select `p0`.`sid`, `p0`.`workspace_sid`, `w1`.`sid` as `w1__sid`
// from `project` as `p0`
// left join `workspace` as `w1` on `p0`.`workspace_sid` = `w1`.`sid`
// order by `p0`.`workspace_sid` asc, `w1`.`workspace` asc

// Error:
// InvalidFieldNameException: … - SQLITE_ERROR: no such column: w1.workspace

// Works
const projects = await orm.em.findAll(Project, {
  fields: ['workspace.sid'],
  orderBy: { workspace: { sid: 'ASC' } },
});

// SQL:
// select `p0`.`sid`, `p0`.`workspace_sid`, `w1`.`sid` as `w1__sid`
// from `project` as `p0`
// left join `workspace` as `w1` on `p0`.`workspace_sid` = `w1`.`sid`
// order by `p0`.`workspace_sid` asc, `w1`.`sid` asc

// Also works
const projects = await orm.em.findAll(Project, {
  orderBy: { workspace: 'ASC' },
});

// SQL:
// select `p0`.*
// from `project` as `p0`
// order by `p0`.`workspace_sid` asc
```

### Reproduction

https://github.com/mrmlnc/mikro-orm-order-by-entity/blob/master/src/example.test.ts

### What driver are you using?

@mikro-orm/sqlite

### MikroORM version

6.2.10-dev.28

### Node.js version

22.1.0

### Operating system

macOS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Fixed via 28119c649c61f070fbe396c4a879f9d071d9aabd

Btw you should be using the `PrimaryKeyProp` symbol since your PK has a non-standard name, without that the types of `em.create` wont accept the FK value, since the ORM does not understand what is the PK of that entity.

https://github.com/mikro-orm/mikro-orm/commit/28119c649c61f070fbe396c4a879f9d071d9aabd#diff-664b82ced9c801185781556d6067d43d92e0209c2d470693ba8ebff6a1fdb75aR36
