### ISSUE TITLE
Order of SQL parameters when using QueryBuilder with raw helper is not correct

### ISSUE THREAD

**Issue by xmajzel** [mikro-orm/mikro-orm#5706]
### Describe the bug

In test bellow there are 4 SQL parameters passed, however the **2-nd** and **4-th** parameter in query have swapped positions.

### Reproduction

```typescript
import {
  MikroORM,
  Entity,
  PrimaryKey,
  DateTimeType, Property, Opt, raw,
} from '@mikro-orm/postgresql';

@Entity()
class User {

  @PrimaryKey()
  readonly id!: bigint;

  @Property({ type: DateTimeType })
  createdAt: Opt<Date> = new Date();

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [User],
    dbName: 'gh-xxxx',
  });
  await orm.schema.createSchema();
});

afterAll(async () => {
  await orm.schema.dropSchema();
  await orm.close(true);
});

test('put sql parameters in right order', async () => {
  const user = orm.em.create(User, {});
  await orm.em.flush();
  orm.em.clear();

  const query = orm.em.createQueryBuilder(User, 'user')
  .where({
    [raw(`(?? at time zone ? at time zone ?)::date`, ['createdAt', 'utc', 'Europe/Bratislava'])]:{
      $nin: raw(`?::date`, ['2024-06-13']),
    },
  });

  await expect(query.getResult()).resolves.not.toThrow();
});

```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.2.9

### Node.js version

20.11.1

### Operating system

Mac OS Sonoma 14.4.1 (23E224)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Feels like a bug in knex to me, I don't have the energy to debug this deeper, so I just made it interpolate early in those cases.

**Comment by xmajzel** [comment]
Thanks!
