### ISSUE TITLE
tsserver performance issues caused by core imports

### ISSUE THREAD

**Issue by sebastiaanviaene** [mikro-orm/mikro-orm#5708]
### Describe the bug

In a more complex nestjs / mikro-orm setup I am experiencing a lot of performance issues when resolving types. It takes up to multiple seconds (sometimes 10-20) to resolve local variables for example, same for adding imports.

In a smaller reproduction repo I am not experiencing these issues. it only becomes an issue when there is more logic in the project.

- I noticed it was due to Mikro-orm because when I removed the mikro-orm/core node module the problem instantly went away
- I was able to work around it a bit by not using `EntityRepository` and `BaseEntity`. this makes it much faster. It's annoying but at least I can develop in peace now.
- I still notice in some files where for example `EntityManager` is imported it's super slow

I've seen the same behaviour in multiple editors so it's not related to VSCode / Webstorm specifically or anything.

**I was however** able to reproduce it in a [reproduction repository](https://github.com/sebastiaanviaene/mikro-orm-reproduction) by simply copying the `EntityManager.ts` class from core and replacing the local imports by core imports. Whenever you change something in the `entity.manager.ts` file you will immediately notice the performance issue. This is very similar to how it behaves in my bigger project.

### Reproduction

https://github.com/sebastiaanviaene/mikro-orm-reproduction

### What driver are you using?

@mikro-orm/sqlite

### MikroORM version

next

### Node.js version

20.9.0

### Operating system

MacOS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
I can't really say this reproduction is helpful, it's not really a reproduction, also you say the issue is valid in WS too, yet your repro is problematic only in vscode.

I will leave this open since I surely agree the types are now very slow, I can see that in the ORM tests too sometimes (especially in large files with >1000 loc), but that doesn't change the fact that we still don't have any actual reproduction. 

Also I really don't know what to do here, already spend ~20 hours trying things out without any success. So any help here would be greatly appreciated.

**Comment by mrmlnc** [comment]
I have encountered similar issues when typing JSON schema. As expected, these issues are related to recursion. To analyze the performance of my code, I used [instruction](https://github.com/microsoft/TypeScript/wiki/Performance-Tracing) from TypeScript team.

I used simplified code for the analysis.

```ts
import { Entity, PrimaryKey } from '@mikro-orm/sqlite';

@Entity()
class Workspace {
  @PrimaryKey()
  sid!: number;
}
```

Using the instructions I get the graph:

<img width="1543" alt="Screenshot 2024-06-22 at 16 00 01" src="https://github.com/mikro-orm/mikro-orm/assets/7034281/f3434830-d493-4f9e-aeb8-d7c6aea3b884">

After carefully examining of the graph, I came to the `FilterQuery` type.

https://github.com/mikro-orm/mikro-orm/blob/cdbab12977cd9b6709442bb4b0838326b2501e98/packages/core/src/typings.ts#L178-L182

Then, while commenting on the union branches, I identified across the source of the performance problems – the `EntityKey` type.

https://github.com/mikro-orm/mikro-orm/blob/cdbab12977cd9b6709442bb4b0838326b2501e98/packages/core/src/typings.ts#L36

It looks like a regular Mapped type. If my understanding of its usage is correct, it should return the literal string of the primary key for the entity and do not look up to relations

```ts
@Entity()
export class Car {
  @PrimaryKey() name: string;
  @PrimaryKey() year: number;
}

type A = EntityKey<Workspace>; // 'name' | 'year'
type B = EntityValue<Workspace>; // string | number
```

So we can just use the `CleanKeys` directly without mapped type:

```ts
export type EntityKey<T = unknown, B extends boolean = false> = string & CleanKeys<T, keyof T>;
```

After this change, the number of symbols and types managed by TS compiler was halved. Left – before changes.

```ts
Files:                         394
Lines of Library:            41041
Lines of Definitions:        73280
Lines of TypeScript:            74
Lines of JavaScript:             0
Lines of JSON:                   0
Lines of Other:                  0
Identifiers:                136779 -> 136776
Symbols:                    462391 -> 228930 (-50%)
Types:                      233552 -> 127752 (-46%)
Instantiations:            3715643 -> 375088 (-90%)
Memory used:               564511K -> 359294K (-37%)
Assignability cache size:   270322 -> 244547
Identity cache size:          1787 -> 493
Subtype cache size:             21
Strict subtype cache size:     527
I/O Read time:               0.02s
Parse time:                  0.20s
ResolveModule time:          0.03s
ResolveTypeReference time:   0.00s
ResolveLibrary time:         0.01s
Program time:                0.30s
Bind time:                   0.10s
Check time:                  4.38s -> 2.34s
transformTime time:          0.01s
commentTime time:            0.00s
I/O Write time:              0.00s
printTime time:              0.02s
Emit time:                   0.02s
Total time:                  4.80s -> 2.77s
```

And, yes, the editor's responsiveness has improved. This is noticeable by the time of type resolution and autocompletion.

But that's not all. Several large blocks are visible on the graph:

<img width="1297" alt="Screenshot 2024-06-22 at 17 22 41" src="https://github.com/mikro-orm/mikro-orm/assets/7034281/2dbc8f4c-641d-4836-a978-e4be04f6a48d">

**Comment by B4nan** [comment]
That's amazing, thank you so much! I can confirm that this change is not breaking any tests in the ORM (but it will require some adjustments in the codebase, it yields 18 type errors now).

**Comment by B4nan** [comment]
Btw what app were you perf testing this on? Because in the ORM repository this doesn't really yield any major improvements (e.g. in the number of symbols or instantiations), I would love to try to improve the other parts too but I still don't have any usable reproduction.

**Comment by mrmlnc** [comment]
> Btw what app were you perf testing this on?

The flamegraph is built on a single file application based on the [reproduction repository](https://github.com/mikro-orm/reproduction). The file contains only the code that I specified in the message above. All images are made for this file.

If we talk about the 800 loc file, then this is our internal application. I can only say that this is an application with 79 entities (quite a lot of relationships), 30 embeddable entities and ~750 TS files (~1/4 works with ORM or its types) with ~120k TS lines.

Here is `tsc -b --extendedDiagnostics` command call for this application before and after the changes:

<details>

<summary>tsc -b --extendedDiagnostics</summary>

```ts
> tsc -b --extendedDiagnostics

Files:                         4538
Lines of Library:             39553
Lines of Definitions:        200410
Lines of TypeScript:         118741
Lines of JavaScript:              0
Lines of JSON:                    0
Lines of Other:                   0
Identifiers:                 447206 -> 447208
Symbols:                     921801 -> 911802 (-1.1%)
Types:                       370870 -> 333010 (-11%)
Instantiations:             3401958 -> 2708940 (-21%)
Memory used:               1149072K -> 1116994K (-3%)
Assignability cache size:    205765 -> 179809 (-14%)
Identity cache size:          15358 -> 15366
Subtype cache size:            5972
Strict subtype cache size:    33072
I/O Read time:                0.32s
Parse time:                   0.59s
ResolveModule time:           0.45s
ResolveLibrary time:          0.02s
ResolveTypeReference time:    0.01s
Program time:                 1.61s
Bind time:                    0.28s
Check time:                   6.03s
transformTime time:           0.24s
commentTime time:             0.02s
printTime time:               0.81s
Emit time:                    0.82s
I/O Write time:               0.46s
Total time:                   8.74s

Projects in scope:                          9
Projects built:                             1
Aggregate Files:                         4538
Aggregate Lines of Library:             39553
Aggregate Lines of Definitions:        200410
Aggregate Lines of TypeScript:         118741
Aggregate Lines of JavaScript:              0
Aggregate Lines of JSON:                    0
Aggregate Lines of Other:                   0
Aggregate Identifiers:                 447206
Aggregate Symbols:                     921801
Aggregate Types:                       370870
Aggregate Instantiations:             3401958
Aggregate Memory used:               1149072K
Aggregate Assignability cache size:    205765
Aggregate Identity cache size:          15358
Aggregate Subtype cache size:            5972
Aggregate Strict subtype cache size:    33072
Aggregate I/O Read time:                0.32s
Aggregate Parse time:                   0.59s
Aggregate ResolveModule time:           0.45s
Aggregate ResolveLibrary time:          0.02s
Aggregate ResolveTypeReference time:    0.01s
Aggregate Program time:                 1.61s
Aggregate Bind time:                    0.28s
Aggregate Check time:                   6.03s
Aggregate transformTime time:           0.24s
Aggregate commentTime time:             0.02s
Aggregate printTime time:               0.81s
Aggregate Emit time:                    0.82s
Aggregate I/O Write time:               0.46s
Config file parsing time:               0.12s
Up-to-date check time:                  0.04s
Build time:                             9.64s
```

</details> 

Before changes:

<img width="1280" alt="Screenshot 2024-07-01 at 14 22 31" src="https://github.com/mikro-orm/mikro-orm/assets/7034281/d365ce9e-c7d4-46ff-a4c5-4e2c0c06e555">

After changes:

<img width="1387" alt="Screenshot 2024-07-01 at 14 25 28" src="https://github.com/mikro-orm/mikro-orm/assets/7034281/dabfa4ba-d4ac-4ea0-bba4-998eba1d52ad">

The `EntityKey` type is mentioned almost 500 times in the type logs. I think this is a cumulative effect.

I tried to build a repository with the main slow parts from the flamegraph, but there is too much knowledge about the application. I'll try again later, depersonalizing them.

**Comment by B4nan** [comment]
Looks like the https://github.com/mikro-orm/guide is a good reproduction for this, it also yields huge results in the count of instantiations, will play with that a bit.

**Comment by B4nan** [comment]
So the huge difference I can see in the https://github.com/mikro-orm/guide repo is only present with TS 5.4, the difference is huge there: 4,3mil vs 920k instantiations. With TS 5.5 it's much smaller but still measurable: 940k vs 914k instantiations.

**Comment by B4nan** [comment]
Merged the `EntityKey` fix, let's open a new issue if you can find a reproduction for the other parts (or another working suggestion like the above, I will be happy to refactor code based on that too to make things faster).

Once again, thank you!
