### ISSUE TITLE
Correctly build where query for getSingleResult QueryBuilder method

### ISSUE THREAD

**Issue by xmajzel** [mikro-orm/mikro-orm#5709]
### Describe the bug

Using query builder as in test bellow produces following SQL query:

```sql
select "user".*,
       "uNotes"."id"                                                as "uNotes__id",
       (extract(epoch from "uNotes"."start"::interval) * 1000)::int as "uNotes__start",
       "uNotes"."user_id"                                           as "uNotes__user_id"
from "user" as "user"
         left join "note" as "uNotes" on "user"."id" = "uNotes"."user_id"
where "user"."id" in (select "user"."id"
                      from (select "user"."id",
                                   "(extract (epoch from ""uNotes"""."""start""::interval) * 1000)::int" as """uNotes__start"""
                            from "user" as "user"
                                     left join "note" as "uNotes" on "user"."id" = "uNotes"."user_id"
                            where "user"."id" = '1'
                            group by "user"."id"
                            order by min((extract(epoch from "uNotes"."start"::interval) * 1000)::int) asc
                            limit 1) as "user")
order by (extract(epoch from "uNotes"."start"::interval) * 1000)::int asc;
```

throwing following error:
```
missing FROM-clause entry for table "(extract (epoch from "uNotes""]
```
**Problem:**
The problem is with `"(extract (epoch from ""uNotes"""."""start""::interval) * 1000)::int"` which is included in **select** within **where** condition.
- It's seemed to be caused by **orderBy** method in QueryBuilder: `.orderBy({ 'uNotes.start': QueryOrder.ASC });`, commenting that line in code causes problem disappear.
- **Workaround:** Instead of `getSingleResult()` use `.getResultList(1)`

### Reproduction

```typescript
import {
  MikroORM,
  Entity,
  PrimaryKey,
  Property,
  Type, ManyToOne, Ref, OneToMany, Collection, wrap, QueryOrder,
} from '@mikro-orm/postgresql';

export class IntervalType extends Type<number, number | null | undefined> {

  getColumnType() {
    return `interval`;
  }

  override get runtimeType(): string {
    return 'number';
  }

  compareAsType(): string {
    return 'number';
  }

  convertToJSValueSQL(key: string) {
    return `(extract (epoch from ${key}::interval) * 1000)::int`;
  }

  convertToDatabaseValueSQL(key: string) {
    return `(${key} || 'milliseconds')::interval`;
  }

}

@Entity()
class User {

  @PrimaryKey()
  readonly id!: bigint;

  @OneToMany(() => Note, m => m.user)
  notes = new Collection<Note>(this);

}

@Entity()
class Note {

  @PrimaryKey()
  readonly id!: bigint;

  @Property({ type: IntervalType })
  start!: number;

  @ManyToOne(() => User, { ref: true })
  user!: Ref<User>;

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [User],
    dbName: 'gh-xxxx',
  });
  await orm.schema.createSchema();
});

afterAll(async () => {
  await orm.schema.dropSchema();
  await orm.close(true);
});

test('correctly build where condition with custom type', async () => {
  const user = orm.em.create(User, {});
  orm.em.create(Note, { user: wrap(user).toReference(), start: 123459 });
  orm.em.create(Note, { user: wrap(user).toReference(), start: 123458 });
  await orm.em.flush();
  orm.em.clear();

  const query = orm.em.createQueryBuilder(User, 'user')
  .leftJoinAndSelect('notes', 'uNotes')
  .where({ 'user.id': user.id })
  .orderBy({ 'uNotes.start': QueryOrder.ASC });

  await expect(query.getSingleResult()).resolves.not.toThrow();
});
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.2.9

### Node.js version

20.11.1

### Operating system

Mac OS Sonoma 14.4.1 (23E224)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Its this line which adds the raw query directly as a string instead of using `knex.raw`

https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/query/QueryBuilder.ts#L1683

But that still wont fix this, you end up with `"uNotes.start" must appear in the GROUP BY clause or be used in an aggregate function`. Not sure if we need to wrap it with `min()` or omit completely, will need to think about this a bit when I have more time.

**Comment by xmajzel** [comment]
I see that you omitted it from select, Thanks!
