### ISSUE TITLE
Error when ordering by a field from a relation when this field is written in CamelCase

### ISSUE THREAD

**Issue by mcasarrubios** [mikro-orm/mikro-orm#572]
First of all, thank you for the amazing work. Mikro-orm is awesome!

**Describe the bug**
I have an Entity with a relation as shown below: 
```
@Entity()
export class A extends BaseEntity {
  // rest of fields
 @OneToOne(
    () => B,
    b => b.a,
  )
  b!: IdentifiedReference<B>;
}

@Entity()
export class B extends BaseEntity {
 // rest of fields

@Property()
@Index()
camelCaseField: string;

@OneToOne(() => A, 'b', { owner: true })
  a!: IdentifiedReference<A>;
}
```

If I do a search ordering by *camelCaseField*:
```
const [items, count] = await this.repository.findAndCount(
      filterBy,
      {
        orderBy: {
          'b.camelCaseField': QueryOrder.ASC
        populate: ['b'],
      },
    );
```

I have the following error:
```
select "e0"."id", "e0"."date", "e0"."code", "e1"."id" as "b_id" from "a" as "e0" left join "b" as "e1" on "e0"."id" = "e1"."a_id" order by "e1"."camelCaseField" asc - column e1.camelCaseField does not exist
```
If I do the same query but typing **camel_case_field**, it works.

**Stack trace**
```
[ExceptionsHandler] select "e0"."id", "e0"."date", "e0"."code", "e1"."id" as "b_id" from "a" as "e0" left join "b" as "e1" on "e0"."id" = "e1"."a_id" order by "e1"."camelCaseField" asc - column e1.camelCaseField does not exist
    at Connection.parseE (/Users/my-user/workspace/tortilla/node_modules/pg/lib/connection.js:600:48)
    at Connection.parseMessage (/Users/my-user/workspace/tortilla/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/Users/my-user/workspace/tortilla/node_modules/pg/lib/connection.js:115:22)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**To Reproduce**
1. Run a query ordering by a nested field written in CamelCase 

**Expected behavior**
I expect it works exactly as it does with the fields that are in the same entity. This unexpected behaviour only happens with nested fields

**Additional context**
I am using postgresql and Nestjs

**Versions**

| Dependency | Version |
| - | - |
| node | v10.15.3 |
| typescript | typescript@3.8.3 |
| mikro-orm | mikro-orm@3.6.5 |
| pg | 8.0.2 |

**Comment by B4nan** [comment]
Well you should do it this way, just like with query condition:

    const [items, count] = await this.repository.findAndCount(filterBy, {
      orderBy: {
        b: { camelCaseField: QueryOrder.ASC },
        populate: ['b'],
      },
    );

But you found a different bug, as this actually does not work at the query builder level when using aliased fields (which in fact you are doing).

**Comment by B4nan** [comment]
Hmm nope, actually no bug there, it works ok even with prefixes. Added a testcase to be sure.
