### ISSUE TITLE
Query returns different BigInt value than the one stored in sqlite database

### ISSUE THREAD

**Issue by kuco23** [mikro-orm/mikro-orm#5737]
### Describe the bug

I'm using Sqlite driver to store a bigint value. When I query that value via the entity manager, it differs from the one stored in the Sqlite file. I have not tried to reproduce this on another database driver. 

It's weird because everything works well if I remove the `textField` property.

### Reproduction

```typescript
import { Entity, PrimaryKey, BigIntType, Options, defineConfig, MikroORM, Property } from "@mikro-orm/core"
import { SqliteDriver } from "@mikro-orm/sqlite"

@Entity()
export class Foo {

  @PrimaryKey({ type: 'text' })
  textField: string

  @Property({ type: new BigIntType('bigint') })
  bigIntField: bigint

  constructor(
    textField: string,
    bigIntField: bigint
  ) {
    this.textField = textField
    this.bigIntField = bigIntField
  }
}

 const ORM_OPTIONS: Options<SqliteDriver> = defineConfig({
  entities: [Foo],
  driver: SqliteDriver,
  dbName: "my.db",
  debug: false
})

async function main() {
  const orm = await MikroORM.init(ORM_OPTIONS)
  const generator = orm.getSchemaGenerator()
  await generator.updateSchema()

  const em = orm.em.fork()
  const bigIntStored = new Foo('', BigInt('999999999999999000'))
  await em.persist(bigIntStored).flush()

  const bigIntQueried = await em.findOneOrFail(Foo, { bigIntField: BigInt('999999999999999000') })
  console.log(bigIntQueried.bigIntField) // 999999999999998976n
  await orm.close(true)
}

main()
```

### What driver are you using?

@mikro-orm/sqlite

### MikroORM version

6.2.9.

### Node.js version

18.19.1

### Operating system

WSL2 ubuntu

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Ok, this is really weird, but `BigInt(999999999999999000)` actually does resolve to `999999999999998976n`

<img width="290" alt="image" src="https://github.com/mikro-orm/mikro-orm/assets/615580/41c12e80-d26f-4948-8914-ccb9959820f0">

But we can get around that by converting to string first.

![Uploading image.png…]()

**Comment by kuco23** [comment]
damn, thanks for the fast response :)
