### ISSUE TITLE
Schema Generator always generates diff for vector(N) type

### ISSUE THREAD

**Issue by wasd171** [mikro-orm/mikro-orm#5739]
### Describe the bug

When using [pgvector](https://github.com/pgvector/pgvector) extension and concrete vector length, mikro-orm always tries to create a column migration like
```
this.addSql('alter table "embeddings" alter column "embedding_v1" type vector(1024) using ("embedding_v1"::vector(1024));');
```

^ note that the column is already of `vector(1024)` type

### Reproduction

Given the following entity
```
@Entity()
export class Embeddings {
	@PrimaryKey()
	id!: string

	@Property({
		name: 'embedding_v1',
		type: 'vector(1024)',
		nullable: true,
	})
	embeddingV1!: unknown | null
}
```

MikroORM can create the schema properly, but on every next iteration it thinks that the column type is just `vector` instead of `vector(1024)` and tries to convert it. I think that's because the schema generator only considers the length for the `datetime_precision, character_maximum_length`

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.2.9

### Node.js version

20.12.2

### Operating system

Ubuntu 24.04

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
>		type: 'vector(1024)',

This is wrong, you want `columnType: 'vector(1024)'`, you should never put lengths into the `type` option (for that it would be `type: 'vector', length: 1024`). Not sure if that works fine or not, but what you are doing is a wrong way to do this.

**Comment by wasd171** [comment]
Both `columnType: 'vector(1024)'` and `type: 'vector', length 1024` also do not work :(

**Comment by B4nan** [comment]
Try enabling verbose logging, you will see what `columnType` the database is using, it needs to match exactly, maybe you are using some alias.

https://mikro-orm.io/docs/schema-generator#debugging

**Comment by wasd171** [comment]
This is the output of the schema introspection query (removed other tables):
```sql
select 
  table_schema as schema_name,
  table_name,
  column_name,
  column_default,
  is_nullable,
  udt_name,
  coalesce(datetime_precision, character_maximum_length) length,
  numeric_precision,
  numeric_scale,
  data_type,
  is_identity,
  identity_generation,
  generation_expression,
  (select pg_catalog.col_description(c.oid, cols.ordinal_position::int) from pg_catalog.pg_class c where c.oid = (select ('"' || cols.table_schema || '"."' || cols.table_name || '"')::regclass::oid) and c.relname = cols.table_name) as column_comment
from information_schema.columns cols where (table_schema = 'public' and table_name = 'embeddings') order by ordinal_position
```

This gives `udt_name = 'vector'`, but since `length` is returned as `null` -> schema generator thinks that the database has this column just as `vector`, not `vector(1024)`

**Comment by B4nan** [comment]
Opened https://github.com/pgvector/pgvector/issues/611 as I am really not sure how can we extract the length from the information schema, since its a custom type (on db level).
