### ISSUE TITLE
Ability to listen for umzug events when using Migrator programmatically

### ISSUE THREAD

**Issue by thetutlage** [mikro-orm/mikro-orm#5763]
**Is your feature request related to a problem? Please describe.**
We are wrapping the Mikro ORM migrations capabilities inside a custom CLI and would like to have more control over the CLI output as the migrations are executed.

I can see you are using `umzug` and [listening for the events under the hood](https://github.com/mikro-orm/mikro-orm/blob/master/packages/migrations/src/Migrator.ts#L141-L144). It will be nice, if there can be an option to listen for the same set of events via the `Migrator` class.

**Describe the solution you'd like**
There are couple of ways to go about it.

- Make `umzug` a public property and then I will define the listeners on it.
- Turn `Migrator` into an EventEmitter and emit events as migrations are executed.

**Describe alternatives you've considered**
Nothing so far.

**Additional context**
NA

**Comment by B4nan** [comment]
I guess I would rather go with the second approach, as in the long run I am considering to replace umzug with custom implementation (since it is not doing much for us really).

Would you like to PR this yourself? It sounds like a simple change to me.

**Comment by thetutlage** [comment]
Sure. I can create a PR. We are currently using Mikro ORM 5.9, will you be okay to accept the PR for both `5.9` and the `latest` version? Or you want it just for the `latest` version?

**Comment by B4nan** [comment]
I won't be releasing any new versions in the 5.x branch, definitely not a feature release, maybe some security fixes. For v5 I would just use the `umzug` property directly (with type assertion or `@ts-ignore` comment).

May I ask what's holding you from upgrading?

**Comment by thetutlage** [comment]
> I won't be releasing any new versions in the 5.x branch, definitely not a feature release, maybe some security fixes. For v5 I would just use the umzug property directly (with type assertion or @ts-ignore comment).

Makes sense! Let me contribute a PR for v6.

> May I ask what's holding you from upgrading?

The project is under refactoring stage right now. So we will eventually upgrade to Mikro ORM v6. Haven't got the time to do so :)
