### ISSUE TITLE
Postgres JSON type simple value returned as the wrong type  

### ISSUE THREAD

**Issue by kevinm-facsware** [mikro-orm/mikro-orm#5773]
### Describe the bug

When using the postgres driver and storing a simple json value IE 
"1", the entity manager returns the value cast to an integer. 

```
@Entity()
export class JSONEntity {
    @PrimaryKey({ unique: true })
    id: string = v4();
    
    @Property({ type: 'jsonb', nullable: true })
    value: any;
}
```

The below test falls as "1" is not returned, 1 is.
```
test('JSON Return Example', async () => {
  const entity = new JSONEntity();
  entity.value = "1";
  await orm.em.persistAndFlush(entity);
  // Clearing orm to ensure that the entity is not cached
  orm.em.clear();
  const result = await orm.em.findOne(JSONEntity, { id: entity.id });
  // this test case fails as "1" is not return, is.
  expect(result).not.toBeNull();
  expect(result?.value).toStrictEqual("1");
});
```

I did run the test with the in memory DB and the issue wasn't present. 

### Reproduction

https://github.com/mikro-orm/reproduction/pull/7

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.2.9

### Node.js version

v20.11.1

### Operating system

macOS Sonoma 14.5

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kevinm-facsware** [comment]
An additional discovery, if you use the knex instance 
```
  const entity = new JSONEntity();
  entity.value = "1";
  await orm.em.persistAndFlush(entity);
  // Clearing orm to ensure that the entity is not cached
  orm.em.clear();
  const knex =  orm.em.getKnex();
  const result = await knex('jsonentity').select('*').where({ id: entity.id });
  // const result = await orm.em.findOne(JSONEntity, { id: entity.id });
  // // this test case fails as "1" is not return, is.
  expect(result[0]).not.toBeNull();
  expect(result[0]?.value).toStrictEqual("1");
  ```
  
  
  the value is correct

**Comment by B4nan** [comment]
The problem here is that postgres handles the conversion automatically, just like some other drivers (but not sqlite, so you can't fall into this there).

It was implemented like this because I thought its not consistent what those underlying db libraries are doing, but now I feel like the whole problem was it only works for the JSON columns and not for their extensions like the postgis ones. I think I know how to fix this.

**Comment by B4nan** [comment]
Btw `@PrimaryKey({ unique: true })` makes very little sense to me, PKs are unique by definition, you are only duplicating the constraint, making things slower without any added value.
