### ISSUE TITLE
Enum column migration does not contain all types when using Single table inheritance

### ISSUE THREAD

**Issue by xmajzel** [mikro-orm/mikro-orm#5807]
### Describe the bug

When using single table inheritance with Entities as defined in reproduction, I would like to have **type** column (defined as enum), which should have specific values for **B** and **C** entities.

Creating migration takes **enum** values only from last defined Entity, creating migration as follows:
```
create table `a` (`id` integer not null primary key autoincrement, `discriminator` text check (`discriminator` in ('b', 'c')) not null, `type` text check (`type` in ('type-2', 'type-3')) null, unique (`id`));
```

In this case **type-1** is missing in database constraint for the **type** column.

### Reproduction

```typescript
import {
  MikroORM,
  Entity,
  Opt,
  BaseEntity,
  Enum,
  PrimaryKey,
} from '@mikro-orm/sqlite';
import { BASE_DIR } from '../helpers';
import { remove } from 'fs-extra';

export enum Discriminator {
  B = 'b',
  C = 'c',
}

export enum BType {
  TYPE_1 = 'type-1',
  TYPE_2 = 'type-2',
  TYPE_3 = 'type-3',
}

export enum CType {
  TYPE_2 = 'type-2',
  TYPE_3 = 'type-3',
}

@Entity({ discriminatorColumn: 'discriminator', abstract: true })
export class A extends BaseEntity {

  @PrimaryKey({ autoincrement: true })
  readonly id!: string;

  @Enum(() => Discriminator)
  discriminator!: Opt<Discriminator>;

}

@Entity({ discriminatorValue: Discriminator.B })
export class B extends A {

  @Enum(() => BType)
  type!: BType;

}

@Entity({ discriminatorValue: Discriminator.C })
export class C extends A {

  @Enum(() => CType)
  type!: CType;

}


let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [A, B, C],
    dbName: ':memory:',
    migrations: { path: BASE_DIR + '/../temp/migrations-456', snapshot: false },
  });
});

afterEach(async () => {
  await remove(process.cwd() + '/temp/migrations-456');
});

afterAll(async () => {
  await orm.close(true);
});

test('correctly build migration for enum type', async () => {
  const migrator = orm.migrator;
  const migration = await migrator.createMigration();

  expect(migration.diff.up[0]).toEqual('create table `a` (`id` integer not null primary key autoincrement, `discriminator` text check (`discriminator` in (\'b\', \'c\')) not null, `type` text check (`type` in (\'type-1\', \'type-2\', \'type-3\')) null, unique (`id`));');
});

```

### What driver are you using?

None

### MikroORM version

6.2.9

### Node.js version

20.11.1

### Operating system

Mac OS Sonoma 14.4.1 (23E224)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Strictly speaking, it's hard to consider this a bug, you're not supposed to change the type of a property with the same name, and changing enum items is basically changing its type.

**Comment by xmajzel** [comment]
Yes, I agree that it's not a bug, more likely feature-request. It's probably kinda specific, but for enum it's really usable case. 
Would be happy if it could be part of mikro-orm.
