### ISSUE TITLE
MsSQL driver stores newline (\n) as plaintext (\\n)

### ISSUE THREAD

**Issue by DASPRiD** [mikro-orm/mikro-orm#5811]
### Describe the bug

When persisting a text property in MsSQL, any `\n` gets encoded as `\\n`. I can't figure out whether this is happening in MikroORM or Tedious.

### Reproduction

I will supply a PR with a failing test.

### What driver are you using?

@mikro-orm/mssql

### MikroORM version

6.2.9

### Node.js version

v20.15.1

### Operating system

PopOS 22.04

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
See #5786

**Comment by DASPRiD** [comment]
@B4nan After testing with 6.3.0 it looks like we have to re-open this issue. `\n` still gets encoded as plaintext.

**Comment by B4nan** [comment]
Provide a new repro then

**Comment by DASPRiD** [comment]
My existing test I created a PR for still fails, does that suffice?

https://github.com/DASPRiD/mikro-orm/commit/ae3db2aea6c7f309a39dba5a0643a8d9d96b94e2

**Comment by B4nan** [comment]
Ok, this is actually really crazy, looks like there is no alternative to `\n` in SQL server, and you need either actual line breaks in the query or using string concatenation with `char(10)`. This goes beyond my imagination :]

**Comment by DASPRiD** [comment]
MSSQL keeps suprising (or rather annoying) me more and more… By the way, looking at the related merged PR a college was wondering: Why is escaping needed with prepared statement parameters?

**Comment by B4nan** [comment]
All of this is here so the queries you see in the logs can be accurate, so you can actually copy/paste them to any other db management tool and they work the same. Plus limitations of other drivers, notably sqlite has quite low limits on the number of parameters in a query.
