### ISSUE TITLE
https://mikro-orm.io/ is down

### ISSUE THREAD

**Issue by frank-mendez** [mikro-orm/mikro-orm#5824]
### Describe the bug

https://mikro-orm.io/ is currently not accessible
![image](https://github.com/user-attachments/assets/894363fa-e7f9-48a4-9f59-090695d5555d)

### Reproduction

Go to https://mikro-orm.io/

### What driver are you using?

None

### MikroORM version

5.9.7

### Node.js version

21.6.2

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SteadEXE** [comment]
It works for me

**Comment by B4nan** [comment]
same, works fine for me
