### ISSUE TITLE
Not able to populate relation on a loaded entity

### ISSUE THREAD

**Issue by kalu06** [mikro-orm/mikro-orm#5834]
### Describe the bug

Hi,

It seems that we are not able to properly populate an entity from a loaded entity relation.
Not sure it's a bug or a misuse of Mikro-ORM (sorry if it's a misuse).
Hope the repro is clear enough.

PS: I don't have the issue if I use Ref on my relations.

Best,
Lucas

### Reproduction

https://github.com/mikro-orm/reproduction/pull/8

### What driver are you using?

None

### MikroORM version

6.3

### Node.js version

v20.9.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
That's because you are trying to populate a relation of entity reference - `userAddress` is not initialized.

It will work if you populate it first:

```ts
const user = await orm.em.findOneOrFail(User, { email: 'foo' }, { populate: ['address'] });
```

**Comment by B4nan** [comment]
Your comment in there says `then populate the address relation of user` but you are not populating the address anywhere, you just try to populate its `city` relation, but on an unloaded `address`.

**Comment by kalu06** [comment]
My mistake, I thought that accessing `user.address` would give me access to the entity, even without populating it.

**Comment by B4nan** [comment]
It does, but to an entity reference, you never tried loading it, so it only has its primary key.

You could as well do this instead of the `em.populate` call to also load the owning entity:

```ts
const loadedAddress = await orm.em.findOneOrFail(Address, userAddress, { populate: ['city'] });
```
