### ISSUE TITLE
Incorectly generated migration when using default value in embeddable entity

### ISSUE THREAD

**Issue by xmajzel** [mikro-orm/mikro-orm#5847]
### Describe the bug

Before [this commit](https://github.com/mikro-orm/mikro-orm/commit/c57b528645042876d71d5816156679a31bdbf215#diff-61ad57ac91248d014b0da6a0a39b4bf5732eab2b0ae92eb7c92206d057c39975R1221) when using embeddable with default value, default value was generated inside migration on database level (e.g. for reward_active column: `'reward_active' integer not null default false`).

After mentioned commit, migration does not have default value (e.g. for reward_active column: `'reward_active' integer not null`).

### Reproduction

```typescript
import {
  MikroORM,
  Entity,
  Opt, Embeddable, Property, PrimaryKey, Embedded,
} from '@mikro-orm/sqlite';
import { BASE_DIR } from '../helpers';
import { remove } from 'fs-extra';


@Embeddable()
class EmbeddableEntity {

  @Property()
  active: Opt<boolean> = false;

  @Property({ type: 'json' })
  email: Opt<Record<string, string>> = { a: 'a', b: 'b' };

  @Property()
  subject: Opt<string> = 'Here is your reward';

}

@Entity()
class EntityA {

  @PrimaryKey({ autoincrement: true })
  readonly id!: Opt<string>;

  @Embedded(() => EmbeddableEntity)
  reward: Opt<EmbeddableEntity> = new EmbeddableEntity();

}


let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [EntityA, EmbeddableEntity],
    dbName: ':memory:',
    migrations: { path: BASE_DIR + '/../temp/migrations-456', snapshot: false },
  });
});

afterEach(async () => {
  await remove(process.cwd() + '/temp/migrations-456');
});

afterAll(async () => {
  await orm.close(true);
});

test('correctly build migration for enum type', async () => {
  const migrator = orm.migrator;
  const migration = await migrator.createMigration();

  expect(migration.diff.up[0]).toEqual('create table `entity_a` (`id` integer not null primary key autoincrement, `reward_active` integer not null default false, `reward_email` json not null, `reward_subject` text not null default \'Here is your reward\', unique (`id`));');
});

```

### What driver are you using?

None

### MikroORM version

6.3.0

### Node.js version

20.11.1

### Operating system

Mac OS Sonoma 14.4.1 (23E224)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Hmm, the motivation behind that commit was mainly polymorphic embeddables, since having db level defaults on properties that are not part of the root entity can cause unwanted diffs. I'll try to find a way to limit this only to that and not to all embeddables.

**Comment by xmajzel** [comment]
Oh, I understand. For our case, its fine, we can define the default value for embeddable property through the `default` parameter in the **@Property** decorator.

Just thought this might be breaking for somebody, because after upgrade of **@mikro-orm** it generates database diff (and updates snapshot as well).

**Comment by xmajzel** [comment]
Thanks!
