### ISSUE TITLE
[Regression] MySQL Dates returning string instead of serializing to `new Date()`

### ISSUE THREAD

**Issue by kpervin** [mikro-orm/mikro-orm#5881]
### Describe the bug

In testing between 6.2.9 and 6.3.0, it seems somewhere along the line that MySQL dates no longer serialize to a Date object, and instead return a string. 

### Reproduction

https://github.com/kpervin/mikro-orm-reproduction/tree/6.3.0-date-issue

Steps to take:

- Set up MySQL instance and change env vars to point to db
- Run ` yarn up @mikro-orm/*@6.2.9` and run the test. It should succeed.
- Run ` yarn up @mikro-orm/*@6.3.0` and run the test. It should then fail.

### What driver are you using?

@mikro-orm/mysql

### MikroORM version

6.3.0

### Node.js version

20.9.0

### Operating system

5.15.146.1-microsoft-standard-WSL2

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Mapping itself works fine, this is about the ts-morph provider and how it handles the `& Opt` type. And last time this was broken, it was caused by TS giving us `any` in there 🙃

**Comment by B4nan** [comment]
It does, I tried your repro, and it works fine without the `Opt` intersection, as well as with `Opt<T>` as a generic type, or with the default metadata provider. Exactly like last time this broke.

**Comment by B4nan** [comment]
It was actually much simpler. The issue with `any` is only present in this repository, I keep forgetting about that. When I checked it in the reproduction repo it was about the missing `| undefined` - I can see this changed in some TS update, or it could be about TS config, so I left both variants.
