### ISSUE TITLE
getNativeEnumDefinitions returns incorrect list of definitions when there are enums with the same name in different database schemas

### ISSUE THREAD

**Issue by triadium** [mikro-orm/mikro-orm#5905]
### Describe the bug

postgresql\PostgreSqlSchemaHelper.js
`getNativeEnumDefinitions` returns only one schema's enum.

Fix:
In getNativeEnumDefinitions function field `n.nspname` add to `group by` clause and remove min() function from `n.nspname` in `select` clause

### Reproduction

```
 const MikroOrmConfig: Options = {
      dbName: configService.get('MODYNO_POSTGRES_DB'),
      driver: PostgreSqlDriver,
      namingStrategy: EntityCaseNamingStrategy,
      entities: [],
      host: configService.get('MODYNO_POSTGRES_HOST'),
      password: configService.get('MODYNO_POSTGRES_PASSWORD'),
      port: configService.get('MODYNO_POSTGRES_PORT'),
      user: configService.get('MODYNO_POSTGRES_USER'),
      metadataCache: {
        enabled: false
      },
      debug: true,
    }
    
    const sambookOneSchema = new EntitySchema<any>({
      name: 'EntityOne',
      schema: 'one_schema',
      properties: {
        id: { type: 'uuid', defaultRaw: 'gen_random_uuid()', primary: true },
        enum1: { type: 'enum', nativeEnumName: 'SomeEnum', items: ['A', 'B', 'D'], nullable: true },
      },
    });

   const sambookTwoSchema = new EntitySchema<any>({
      name: 'EntityTwo',
      schema: 'two_schema', // other schema
      properties: {
        id: { type: 'uuid', defaultRaw: 'gen_random_uuid()', primary: true },
        // Same name - SomeEnum, but must link to two_schema, not one_schema!
        enum2: { type: 'enum', nativeEnumName: 'SomeEnum', items: ['D', 'E', 'F'], nullable: true },
        // this code will work but it is not what we want!
        // enum2: { type: 'enum', nativeEnumName: 'one_schema.SomeEnum', items: ['D', 'E', 'F'], nullable: true },
      },
    });


    MikroOrmConfig.entities.push(sambookOneSchema);
    MikroOrmConfig.entities.push(sambookTwoSchema);
    const orm = await MikroORM.init(MikroOrmConfig)

    const sqlUpdateSchema = await orm.getSchemaGenerator().getUpdateSchemaSQL()
    console.log('======================== UPDATE =====================');
    console.log(sqlUpdateSchema);
    await orm.getSchemaGenerator().updateSchema({ dropDb: false, dropTables: false, wrap: true });
    // Will throw error 
    // DriverException: create type "two_schema"."SomeEnum" as enum ('D', 'E', 'F');
    // set session_replication_role = 'origin'; - type "SomeEnum" already exists
    await orm.getSchemaGenerator().updateSchema({ dropDb: false, dropTables: false, wrap: true });
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.3.3

### Node.js version

v20.11.1

### Operating system

Windows 11

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
> In getNativeEnumDefinitions function field n.nspname add to group by clause and remove min() function from n.nspname in select clause

If you see an easy fix, feel free to PR this right ahead.

**Comment by B4nan** [comment]
You were absolutely right, thanks for the suggestion.
