### ISSUE TITLE
docs: The docs list EntityManager.find() and findAll() fields as "Fields: string = ALL" or "Fields: string = *" but its actually an array

### ISSUE THREAD

**Issue by davidcheal** [mikro-orm/mikro-orm#5907]
Just Started using this library and the docs are a bit confusing. The value for fields in findAll() and find() are show as string, but its actually an array.

![image](https://github.com/user-attachments/assets/5ea8eb6f-4646-492f-a927-596939369d3d)
![image](https://github.com/user-attachments/assets/f9a83af2-c970-439c-a8a3-800170cf2b82)
![image](https://github.com/user-attachments/assets/4b44783e-fc66-4bf4-99d0-27acd112ef7b)

**Comment by B4nan** [comment]
Those are type parameters, not the method options. Those are not arrays but string unions, the docs are correct.
