### ISSUE TITLE
Single table inheritence no longer supports different custom types for a common property under different classes

### ISSUE THREAD

**Issue by ahtcx** [mikro-orm/mikro-orm#5935]
### Describe the bug

Using different custom types under a common property previously of a polymorphic worked but does not since v6.3.0. I suspect it may be due to #5784 but I haven't had the chance to take the time to properly understand the underlying code yet.

```ts
class CatMetadataType extends Type {}
class DogMetadataType extends Type {}

@Entity({ discriminatorColumn: 'type', abstract: true })
class Pet {
  [OptionalProps]?: 'id' | 'type';

  @PrimaryKey()
  id!: number;

  @Property()
  type!: string;
}

const TYPE_CAT = 'cat';
@Entity({ discriminatorValue: TYPE_CAT })
class Cat extends Pet {
  @Property()
  override type = TYPE_CAT;

  @Property({ type: CatMetadataType })
  metadata!: { purrsPerHour?: number };
}

const TYPE_DOG = 'dog';
@Entity({ discriminatorValue: TYPE_DOG })
class Dog extends Pet {
  @Property()
  override type = TYPE_DOG;

  @Property({ type: DogMetadataType }) // doesn't work due to a mismatch between `DogMetadataType` and `CatMetadataType`
  metadata!: { enjoysPlayingFetch?: true };
}
```

The above example worked fine before v6.3.0, but no longer works.

### Reproduction

https://github.com/ahtcx/mikro-orm-polymorphism-regression

The test passes on v6.2.9 but fails on later versions.

### What driver are you using?

None

### MikroORM version

\>=6.3.0

### Node.js version

v20.10.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
What does "no longer works" mean? When I run your repro (on the latest version, as you should), I get a type error, is that what you see?

```ts
    TypeError: Cannot read properties of undefined (reading '0')

      1098 |         console.log('root.prop', exists);
      1099 |       }
    > 1100 |       if (exists && (exists.fieldNames[0] !== prop.fieldNames[0] || exists.type !== prop.type)) {
           |                                       ^
      1101 |         const name = prop.name;
      1102 |         this.initFieldName(prop, prop.object);
      1103 |         prop.name = name + '_' + (i++);
```

**Comment by ahtcx** [comment]
Thanks you! 🙏
