### ISSUE TITLE
docs: Turso connection configuration

### ISSUE THREAD

**Issue by Codethier** [mikro-orm/mikro-orm#5941]
Hi

I am rather glad there is libsql support , does this mean there turso can be used witht the orm? If so there should be a small paragraph somewhere , as turso uses host + key which doesn't fit into the usual configs of :

driver 👍 
host 👍 
port  👎 
dbName 👍 
user 👎 
password ❔
schema 👎

**Comment by B4nan** [comment]
https://mikro-orm.io/docs/usage-with-sql#using-turso-database
