### ISSUE TITLE
The where option in the loadItems and load functions of the collection class is not working.

### ISSUE THREAD

**Issue by myuoong** [mikro-orm/mikro-orm#5975]
### Describe the bug

Hello, I regularly use mikro-orm and appreciate it very much. Thank you.

When running this example code with tables User and Book that have a OneToMany relationship, the test code does not pass. 

It seems that the initially loaded collection objects are being reused continuously.

When a where condition is applied, it should not return the cached objects as-is.

### Reproduction

``` ts
import { MikroORM } from '@mikro-orm/better-sqlite';
import { Collection, Entity, OneToMany, PrimaryKey } from '@mikro-orm/core';
import { Book } from './book';

@Entity()
export class User {
  @PrimaryKey()
  id!: number;

  @OneToMany(() => Book, (book) => book.user)
  books = new Collection<Book>(this);
}

//Book class is located diffrent directory
@Entity()
export class Book {
  @PrimaryKey()
  id!: number;

  @Property()
  name!: string;

  @ManyToOne(() => User)
  user!: User;
}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    dbName: ':memory:',
    entities: [User],
    debug: ['query', 'query-params'],
    allowGlobalContext: true, // only for testing
  });
  await orm.schema.refreshDatabase();
});

afterAll(async () => {
  await orm.close(true);
});

test('test raw sql', async () => {
  const user = orm.em.create(User, {});
  orm.em.create(Book, {
    name: 'book1',
    user,
  });

  orm.em.create(Book, {
    name: 'book2',
    user,
  });

  orm.em.create(Book, {
    name: 'book3',
    user,
  });

  await orm.em.flush();

  const testUser = await orm.em.findOneOrFail(User, { id: 1 });

  const book1 = await testUser.books.loadItems({ where: { name: 'book1' } });
  expect(book1.length).toBe(1); // it fails book1.length is 3
  expect(book1[0].name).toBe('book1');
});

```

### What driver are you using?

@mikro-orm/better-sqlite

### MikroORM version

6.2.2

### Node.js version

18.20.4

### Operating system

mac os m1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
You don't clear the context, so the collection is already populated with all the items. `loadItems` won't do anything if the collection is already initialized.
