### ISSUE TITLE
"Cannot read property 'properties' of undefined" on Collection.add()

### ISSUE THREAD

**Issue by sebastianhaberey** [mikro-orm/mikro-orm#599]
**Describe the bug**
The above error occurs when adding an element to the collection on the owning side of a one-to-many-relationship. I'm sure this is an oversight on my part, but where? I tried using links instead of references as described [here](https://mikro-orm.io/docs/installation#possible-issues-with-circular-dependencies), but to no avail. Do the entities have to be managed to be associated in this way?

**Stack trace**
```
TypeError: Cannot read property 'properties' of undefined
    at Collection.get property [as property] (/Users/user/Documents/Diverse/Projects/autotip/node_modules/mikro-orm/dist/entity/ArrayCollection.js:91:44)
    at Collection.validateItemType (/Users/user/Documents/Diverse/Projects/autotip/node_modules/mikro-orm/dist/entity/Collection.js:199:70)
    at /Users/user/Documents/Diverse/Projects/autotip/node_modules/mikro-orm/dist/entity/Collection.js:35:32
    at Array.map (<anonymous>)
    at Collection.add (/Users/user/Documents/Diverse/Projects/autotip/node_modules/mikro-orm/dist/entity/Collection.js:35:15)
    at App.execute (/Users/user/Documents/Diverse/Projects/autotip/src/App.ts:98:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at App.run (/Users/user/Documents/Diverse/Projects/autotip/src/App.ts:161:7)
```

**To Reproduce**
With the one-to-many-relationship
```
@Entity()
export class Parent {
  @OneToMany(() => Child, (child) => child.parent)
  children = new Collection<Child>(this);
}
```
to
```
@Entity()
export class Child {
  @ManyToOne()
  parent!: Parent;
}
```
the following code fails:
```
const parent = new Parent();
const child = new Child();
parent.children.add(child);
```

**Expected behavior**
The child is added to the parent's collection and the child's reference to the parent is set.

**Versions**

| Dependency | Version |
| - | - |
| node | 12.16.3 |
| typescript | 3.9.3 |
| mikro-orm | 3.6.15 |
| your-driver | 2.1.0 (mysql2) |

**Comment by B4nan** [comment]
Are both of your entities discovered? Did you initialize the ORM before working with your entities? Enable debug mode to see. 

https://mikro-orm.io/docs/debugging

**Comment by sebastianhaberey** [comment]
>  Did you initialize the ORM before working with your entities?

No, I did not. Thank you for helping me out!

**Comment by fmachucas** [comment]
Hi @B4nan is it possible to not having ORM initialized before working with Entity Collections? I mean, how can i achieve this while i'm unit testing? i.e Creating dummy object examples
```
const parent = new Parent();
const child = new Child();
parent.children.add(child);
```

**Comment by B4nan** [comment]
Nope, you need to initialize it, otherwise there is no metadata and the propagation cannot work. FYI in v6 you can use `MikroORM.initSync` if that is your problem.
