### ISSUE TITLE
Issue with selecting embeddable fields from a Many To Many relationship

### ISSUE THREAD

**Issue by tvacherat** [mikro-orm/mikro-orm#5992]
### Describe the bug

The selection of embeddable fields fails when they are requested from a find on a Many To Many relationship. In particular when the refresh option is set to true.
The problem is highlighted by the reproduction repository.
It shows that the following query is generated:
```
select `m0`.`avatar`, `u1`.`id`, `m0`.`user_id` as `fk__user_id`, `m0`.`mailing_list_id` as `fk__mailing_list_id` from `mailing_list_recipients` as `m0` inner join `user` as `u1` on `m0`.`user_id` = `u1`.`id` where `m0`.`mailing_list_id` in (2)
```
should be:
```
select `u1`.`avatar`, `u1`.`id`, `m0`.`user_id` as `fk__user_id`, `m0`.`mailing_list_id` as `fk__mailing_list_id` from `mailing_list_recipients` as `m0` inner join `user` as `u1` on `m0`.`user_id` = `u1`.`id` where `m0`.`mailing_list_id` in (2)
```

### Reproduction

https://github.com/tvacherat/Mikro-Orm-Issue

### What driver are you using?

@mikro-orm/sqlite

### MikroORM version

next

### Node.js version

v20.10.0

### Operating system

Ubuntu 20.04.6 LTS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by robwgreenjr** [comment]
https://github.com/mikro-orm/mikro-orm/pull/5997 PR has been created for this
