### ISSUE TITLE
Execute unable to handle multi-statement sql for postgresql

### ISSUE THREAD

**Issue by VolcanoCookies** [mikro-orm/mikro-orm#6009]
### Describe the bug

Driver: postgresql
Version: checked 6.2.9, 6.3.8

When executing sql with multiple statements, method "all" returns undefined, and both "run" and "get" throw `DriverException: Cannot read properties of undefined (reading '0')`

Example of sql that fails:
```SQL
INSERT INTO "user" ("name", "email") VALUES ('Foo', 'bar');
SELECT * from "user";
```

Regardless of execution method, postgresql driver expects a single object as a result from knex. However knex returns an array, containing the results for each statement in the query.
https://github.com/mikro-orm/mikro-orm/blob/067be3b3aabbdcdea55d8c001dffc4340a30a179/packages/knex/src/AbstractSqlConnection.ts#L162-L163
https://github.com/mikro-orm/mikro-orm/blob/067be3b3aabbdcdea55d8c001dffc4340a30a179/packages/postgresql/src/PostgreSqlConnection.ts#L38-L53

### Reproduction

https://github.com/VolcanoCookies/mikro-orm-postgresql-bug-repr
Follow readme

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

@mikro-orm/core@6.3.8 @mikro-orm/postgresql@6.3.8

### Node.js version

v20.16.0

### Operating system

debian "bullseye"

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
FYI this will break again in v7 most likely, kysely does not return all the query results, instead it gives only an empty array.
