### ISSUE TITLE
Symbol operators to replace string operators

### ISSUE THREAD

**Issue by zachrip** [mikro-orm/mikro-orm#602]
**Is your feature request related to a problem? Please describe.**
When express parses json it doesn't care about the shape meaning you could end up with an object instead of a number or string for example. That object might contain string operators and could be used to tweak the query in nefarious ways.

**Describe the solution you'd like**
Sequelize's pattern of symbol based operators is quite nice. Symbols cannot be created externally like strings can.
``` javascript
const operators = {
  AND: Symbol('morm_and'),
  OR: Symbol('morm_or'),
};

const query = await xyz.findOne({
  [operators.AND]: {
    id: 2,
    name: 'test',
  },
});
```
This would accompany an option to disable string operators.

**Describe alternatives you've considered**
None at the moment.

**Additional context**
https://github.com/sequelize/sequelize/issues/8417

**Comment by B4nan** [comment]
Apparently there has been zero interest from the community, closing this now. As mentioned on slack long time ago, I don't believe an ORM is a place where this should be taken care of (the payload should be properly escaped much sooner).
