### ISSUE TITLE
[bug] Utils.isPrimaryKey() check failing for PK values defined as Date object

### ISSUE THREAD

**Issue by whocaresk** [mikro-orm/mikro-orm#603]
**Describe the bug**
Utils.isPrimaryKey() is ignoring pk, if it represented as date object.

**Stack trace**
```
...
```

**To Reproduce**
https://github.com/whocaresk/mikro-orm/blob/4af93cf1c9f44b8d33a342a29b92cfa1149e7afa/tests/issues/GH603.test.ts

**Expected behavior**
PK defined as datetime and represented as Date object should work

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | v12.14.1 |
| typescript | 3.7.4 |
| mikro-orm | 3.6.15 |
| mysql2 | 2.1.0 |

**Comment by B4nan** [comment]
Closing as fixed in v4
