### ISSUE TITLE
Updatable virtual entities

### ISSUE THREAD

**Issue by mdsystems** [mikro-orm/mikro-orm#6036]
**Is your feature request related to a problem? Please describe.**
Reading the docs, virtual entities appear to be read-only. It seems to me that they are intended to represent views, or general SQL statements.

**Describe the solution you'd like**
I would like for a virtual entity to allow definition of a primary key and for Mikro-orm to treat it as updatable when a primary key is defined.

**Describe alternatives you've considered**
I could update the entities that are used for my tables directly, but I would prefer to be granting permissions to the views. I do not need Mikro-orm to maintain these views as I have scripts that take care of view creation and generation of "instead-of" triggers where necessary.

In this instance, I am using the views to implement a soft-delete feature. I am not aware of this being supported in Mikro-orm, so whilst I handle it myself in the queries that are constructed, it's easier to have the database do it for me if I can have updatable virtual entities.

**Additional context**
I have looked at ticket https://github.com/mikro-orm/mikro-orm/issues/672 and whilst it has similarities to this requirement, I think that my use-case would be covered by treating a virtual entity like a standard entity. To all intents and purposes, if I can flag an entity as being one that I have responsibility for maintaining but that can be written to, that is all I need. Updatable virtual entities seem to be appropriate, in this instance.

We have some development resource available to take a look at this ourselves, but since we are very new to Mikro-orm, we don't really know where to start. If this is something you do not have the time to support, but feel it is appropriate, we could take a look ourselves with a little guidance from the existing maintainers.

**Comment by B4nan** [comment]
This is definitely a wontfix, you cant update an entity that is represented by a query, how would you expect that to work?

**Comment by B4nan** [comment]
In the other issue, you mentioned this

>  I would like to be able to define an entity that Mikro-orm can use, but that it does not necessarily maintain

What do you mean by that? It sounds like all you need is to define an entity and not use schema generator/migrations.

**Comment by mdsystems** [comment]
It's absolutely possible to update views. And so far as an ORM is it is not necessary for it to know that an entity is based on a view or a table, if I am managing it.

If I can define an entity, and exclude it from Mikro-orm's management, that should meet my need.

**Comment by B4nan** [comment]
> It's absolutely possible to update views. 

Maybe, but you are asking to allow this on virtual entities, and that's not an option. Virtual entity can be represented by anything, what do you expect from the ORM, to analyze a raw query and act on that? No plans to do that, that's the job of the db engine, not an ORM.

> If I can define an entity, and exclude it from Mikro-orm's management, that should meet my need.

Let me ask you once again what you mean by this statement because to me it makes no sense. What is that "management" you are talking about?

**Comment by mdsystems** [comment]
I manually have some views that I have created. They are created using scripts and are managed by those scripts. I do not need Mikro-orm do do anything other than allow me to create create updatable entities that will use the views (rather than base tables). Mikro-orm should not try to create or maintain tables for these entities.

**Comment by B4nan** [comment]
Also if it's not clear, the only thing #672 is about is support for schema generator (and in turn migrations) for database views. You can use database views as normal entities already (especially if the db engine supports making updates on them, if not, use a virtual entity which is readonly by definition). It will have no runtime implications, it's purely about the schema.

> I manually have some views that I have created. They are created using scripts and are managed by those scripts. I do not need Mikro-orm do do anything other than allow me to create create updatable entities that will use the views (rather than base tables). Mikro-orm should not try to create or maintain tables for these entities.

So you want to use the schema generator/migrations, but not on those views? You can handle that via metadata hooks and omit anything you don't want the ORM to see. Keep in mind the metadata still need to be there for the runtime, you should skip them only for the context of the schema handling.

https://mikro-orm.io/docs/configuration#onmetadata-hook

**Comment by mdsystems** [comment]
We want to use the schema generation and migrations but not on the views, yes. Thanks for the documentation link. I'll have a read. 

I updated my comment above. We are currently using Typeorm and the @ViewEntity decorator does what we need.

**Comment by B4nan** [comment]
We could also implement #5346, that way you could just list the views in the config options instead of using the metadata hooks.

That should be super simple, I was hoping someone could help out with that, but as usual, it's waiting for me to implement.

**Comment by mdsystems** [comment]
Rather than you having to implement something specific, your answers have led me to think that I can just be more intelligent about how I initialise the ORM when I want to manage database creation and migrations. Just trying that now. If it works, I think no further action is required.

Thank you for taking time to respond to the ticket. Very helpful and much appreciated.

**Comment by B4nan** [comment]
Btw I actually do plan to look into #672 soon, during the 6.x lifecycle, I might take a stab at it and implement at least the basic support even in the next feature release, I think it would make sense to start with being able to just create views (and work with them), we could leave diffing of them for later (which is the problematic part, IIRC typeorm has some metadata table to make it possible). Someone even mentioned recently that in fact, db views are never diffed, only recreated, not sure if that's true.

**Comment by mdsystems** [comment]
I think recreating views is a sensible way of handling it and would keep it simpler, I imagine. Thanks for your help so far.

**Comment by mdsystems** [comment]
The resolution for me was to just exclude the view entity definitions when using the schema generator and then use them to interact with the database. It works just fine, so far.
