### ISSUE TITLE
MikroORM + Angular + Electron SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by wilberalx** [mikro-orm/mikro-orm#604]
Hi @B4nan 

I am trying to use MikroORM with Angular and Electron. I managed to create a connection to the db with MikroORM.init ({...}), but when adding the config file and instantiating MikroORM () without options, I have run into this error:

![image](https://user-images.githubusercontent.com/22874047/84015883-bbf75500-a939-11ea-946d-1c0b98457721.png)

Also when trying to use the Commandline Tool it gives me the same error:

![image](https://user-images.githubusercontent.com/22874047/84014931-53f43f00-a938-11ea-941e-fbd2d09d3869.png)

I have added the mikro-orm.config.ts file and the respective settings in the package.json as the documentation says but it gives me the error.

To use MikroORM with Angular and Electron I am using an extra-webpack-config. It was giving me an error referencing webpack so I added  **discovery: { disableDynamicFileAccess: true }** to my mikro-orm.config.js

**For the integration with Angular and Electron I have based on the project:** https://github.com/MetaiR/angular-electron-typeorm  which does the same with TypeORM

Is there something else I'm not considering?

**Comment by B4nan** [comment]
How does the `package.json` settings look like? Feels like you have ts-node enabled there, which is obviously not possible with webpack build.

Why are you using that file anyway? The purpose of the file is to allow to work with CLI, I would suggest to pass the configuration in `MikroORM.init()` manually in this case.

**Comment by wilberalx** [comment]
The package.json settings: 

![image](https://user-images.githubusercontent.com/22874047/84017353-c4508f80-a93b-11ea-9eed-d41e1410e147.png)

I used the file to check if there was any tool on the command line to generate the db tables based on the entities, is that possible?

**Comment by B4nan** [comment]
I don't really understand what you are doing - what is causing that error? Are you executing CLI somehow? 

Would be good if you prepare a reproduction. This is definitely not a bug in the ORM, its a misconfiguration. The error is about you using TS file inside the compiled JS code. I don't understand how you are mixing the CLI commands with webpack build - how can you "use a file to check"?

Btw you can use `SchemaGenerator` programatically here if you need it: https://mikro-orm.io/docs/schema-generator/#using-schemagenerator-programmatically

I guess what you stated in the first place is your whole issue:

> I managed to create a connection to the db with MikroORM.init ({...}), but when adding the config file and instantiating MikroORM () without options, I have run into this error:

You can't do this with webpack, it means that it will use `require()` to load that config file, based on the paths from `package.json`. That is the dynamic file access you want to disable in general when using webpack. 

So its fine to have that config file for the CLI, also the `package.json` part looks fine, but you can't use `MikroORM.init()` without the config param. What you can do is to require it yourself and pass it there -- it won't be dynamic file access this way (the path to the file will be known at compile time), as the path to the file is known to you, it won't be sniffed from `package.json`.

**Comment by wilberalx** [comment]
I did not explain myself well, sorry. I understand that I need the file to use the CLI, that's what I meant, I wanted to see if in the CLI there was any tool to generate the tables based on the entities, for which I see that I can use SchemaGenerator as you mentioned.

I am left in doubt: when using the CLI after adding the file, when I run for example: npx mikro-orm schema: update --run it gives me the error I mentioned above. From what I understand could I not use CLI in the environment I am working on?

**Comment by B4nan** [comment]
Do you have ts-node installed?

**Comment by wilberalx** [comment]
Yes, it's installed:

![image](https://user-images.githubusercontent.com/22874047/84021238-7474c700-a941-11ea-8051-31d557c53849.png)

It gives me this error

![image](https://user-images.githubusercontent.com/22874047/84021332-a1c17500-a941-11ea-8c04-7167deeb3341.png)

**Comment by B4nan** [comment]
Weird, maybe it's caused by the `tsconfig.json` settings, hard to say. If you prepare a reproduction repository I can take a look. 

Do you have `tsconfig.json` file in the root of your project? 

Maybe this is your problem: https://github.com/TypeStrong/ts-node/issues/922#issuecomment-571734880

**Comment by wilberalx** [comment]
Yes tsconfig.json file is in the project root.

This is a repository where I uploaded the basic structure of the project: https://github.com/wilberalx/mikro-orm-angular-electron

**Comment by wilberalx** [comment]
Great thanks for your help

**Comment by iAmao** [comment]
@B4nan This issue still happens when I try to run a compiled ts project even using `commonjs`

**Comment by B4nan** [comment]
> @B4nan This issue still happens when I try to run a compiled `typescript` project even making  use `commonjs`

There is no issue, never was, this was just a misconfiguration. Your problem will be most probably again wrong setup - hard to help without seeing the details. Check the example projects. 

My guess is that you have wrong paths in `entitiesDirs`, those need to point to the compiled entities (dist), while `entitiesDirsTs` should point to the TS files (src).

**Comment by iAmao** [comment]
> here is no issue, never was, this was just a misconfiguration. Your problem will be most probably again wrong setup - hard to help without seeing the details. Check the example projects.

You are right @B4nan thanks. This happened when I try to run migrations. I moved my migration away from my root dir.
