### ISSUE TITLE
`unsigned: false` not being applied on `@PrimaryKey`

### ISSUE THREAD

**Issue by lsh4711** [mikro-orm/mikro-orm#6057]
### Report related to the Schema Generator

In my case, there were several projects created before using MikroORM, and the primary keys in the mysql databases of these existing projects have the autoincrement bigint attribute.
I decided to switch to MikroORM and used the Entity Generator to import the schema from the existing database and generate entity code.

Then, it is generated as `@PrimaryKey({ unsigned: false })` like this.
```javascript
@Entity()
export class Member {
  [PrimaryKeyProp]?: 'memberId';

  @PrimaryKey({ unsigned: false })
  memberId!: bigint;
  
  ...
}
```

Upon reviewing the generated entities, they were created without any issues.
In other words, the entity generation worked perfectly fine.

And now I have used the Schema Generator to create the DDL.
(`orm.schema.getCreateSchemaSQL()` or `schema:create --dump` or `schema:update --dump`)

The generated DDL always returns unsigned, regardless of the unsigned property.
And `number`(int) type pk has same issue.

```sql
-- if memberId type is bigint and { unsigned: false }
create table `member` (`member_id` bigint unsigned not null auto_increment primary key) -- unexpected unsigned property

-- if memberId type is number and { unsigned: false }
create table `member` (`member_id` int unsigned not null auto_increment primary key) -- unexpected unsigned property
```

I checked the source code and found that it was designed to always output DDL strings with unsigned included, by distinguishing between `increments` and `bigincrements` types.
I modified it to pass the unsigned attribute to check whether it should be unsigned and generate the type accordingly, and it works well.
(In this case, I found that additional modifications are needed for case where the autoincrement attribute is missing in generated schema update DDL.)

I think that, except for special cases, there are people who would like to use the bigint type in databases.
This is probably due to the value types of other programming languages.
Therefore, I believe it would be better to make the unsigned option optional rather than mandatory.

If this is accepted as an issue, I would like to create a PR for it. :)

### Reproduction

https://github.com/lsh4711/reproduction

### What driver are you using?

@mikro-orm/mysql

### MikroORM version

6.3.10

### Node.js version

20.17.0

### Operating system

Windows11

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
PR welcome, it's weird this is not working correctly, we have several tests for this too (and I can't see how they are different from the failing one you provided).
