### ISSUE TITLE
regression, NotNullConstraintViolationException using better-sqlite since 6.3.11 

### ISSUE THREAD

**Issue by darky** [mikro-orm/mikro-orm#6095]
### Describe the bug

I have simple entity like

```ts
@Entity({ tableName: 'some_table' })
class SomeEntity {
  @PrimaryKey({ autoincrement: true, type: 'bigserial' })
  id!: string;
  
  @Property()
  prop!: string;
}
```

And on `flush` error happens:

_NotNullConstraintViolationException: insert into `some_table` (`prop`) values ('test') returning `id`, `prop` - NOT NULL constraint failed: some_table.id_

On 6.3.10 was all fine

### Reproduction

```ts
import { BetterSqliteDriver } from '@mikro-orm/better-sqlite';
import { Entity, MikroORM, PrimaryKey, Property } from '@mikro-orm/core';

@Entity({ tableName: 'some_table' })
class SomeEntity {
  constructor(prop: string) {
    this.prop = prop;
  }

  @PrimaryKey({ autoincrement: true, type: 'bigserial' })
  id!: string;

  @Property()
  prop!: string;
}

(async () => {
  const db = await MikroORM.init({
    dbName: ':memory:',
    driver: BetterSqliteDriver,
    entities: [SomeEntity],
  });

  await db.getSchemaGenerator().refreshDatabase();
  await db.getSchemaGenerator().clearDatabase();

  // on 6.3.11, 6.3.12 error happens; 6.3.10 and below is fine
  await db.em.fork().persistAndFlush(new SomeEntity('test'));

  console.log('done');

  process.exit(0);
})();

```

### What driver are you using?

@mikro-orm/better-sqlite

### MikroORM version

6.3.11, 6.3.12

### Node.js version

22

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
So your test is failing because it is using sqlite while you try to use postgres specific type. With postgres driver it works just fine without any changes. I don't know why this worked before, but it doesn't feel like a bug to me.

**Comment by darky** [comment]
```ts
@PrimaryKey({ autoincrement: true, type: 'bigint' })
id!: string;
```

It's works! Thanks!

**Comment by B4nan** [comment]
This is the line that broke it:

https://github.com/mikro-orm/mikro-orm/pull/6073/files#diff-6e743d85b800af70f543446a0d220434f4473b25979a7dc97ee37cbcf421fc0aR177

cc @lsh4711, maybe we could just move higher to the `MySqlSchemaHelper` class?

**Comment by lsh4711** [comment]
Okay, got it. :)
Then I'll modify it so that `SchemaHelper` behaves as before and the changes apply only to MySQL(modifying `MySqlSchemaHelper`).
Did I understand correctly?"

**Comment by B4nan** [comment]
yop
