### ISSUE TITLE
`migrationsList` as plain array of migrations

### ISSUE THREAD

**Issue by DerHerrGammler** [mikro-orm/mikro-orm#6099]
**Is your feature request related to a problem? Please describe.**
Currently when I create migrations I end up adding it to the list as usualy but its always a bit useless code since it will look like this:
```ts
migrations: [
  // [...],
  {
    class: MigrateXyz127,
    name: MigrateXyz127.name
  }
]
```
A simpler list where I could only provide the class would really great.

**Describe the solution you'd like**
So for example the new list would look like this:
```ts
migrations: [
  // [...],
  MigrateXyz127
]
```
In this case i need 3 less lines of code and my migration is simplified.  
In the beackground it could probably automatically converted into the old format.

**Describe alternatives you've considered**
Another solutions could also be a simple mapping function like this:
```ts
function mapClassesToList(migrations: Array<Constructor<Migration>>): MigrationObject[] {
  return migrations.map((migration): MigrationObject => ({
    class: migration,
    name: migration.name
  }));
}
```
That would map a migration class array to the needed list format with just one small function the package can provide

**Additional context**
This would be just like the migrations of TypeORM as well. Wich probably makes the understanding of the differences for people who wants to switch easier.

**Comment by B4nan** [comment]
Sure, PR welcome.

**Comment by DerHerrGammler** [comment]
What solution would you prefer? The auto mapper in the background or the explicit mapper function?

**Comment by B4nan** [comment]
If we can support both ways (in other words, if this can be non breaking), I would rather do things automatically.
