### ISSUE TITLE
Wrongly single quotes added to update request

### ISSUE THREAD

**Issue by andrii03** [mikro-orm/mikro-orm#6103]
### Describe the bug

Running update query on some entity which has `ManyToOne` or `OneToOne` relations produces  an error `syntax error at or near ...`
The single quotes around nested Select statement (which comes after `in`) are a syntax error, as there should be parentheses instead

### Reproduction

My model looks like this:
```
export class ClientActionEntity extends BaseDateEntity {
  @PrimaryKey({ generated: 'identity' })
  id!: bigint;

  @ManyToOne({ entity: () => ClientEntity })
  client!: ClientEntity;

  @ManyToOne({ entity: () => ActionEntity })
  action!: ActionEntity;

  @Property()
  actionEnabled: boolean = false;
}
```
Executing this code:
```
    async update(clientId: string, actionName: string): Promise<void> {
        const repository = this.entityManager.getRepository(ClientActionEntity)
        await repository.nativeUpdate(
            { client: { id: clientId }, action: { actionName: actionName } },
            { actionFulfilled: true },
        )
    }
```
it produces this query:
```
update "private"."client_actions" set "action_enabled" = true where "id" in 'select "c0"."id" from (select distinct "c0"."id" from "private"."client_actions" as "c0" left join "private"."actions" as "a1" on "c0"."action_id" = "a1"."id" where "c0"."client_id" = ''67d30118-ea49-45cc-b508-ee9050b84054'' and "a1"."action_name" = ''check'') as "c0"'
```
Which produces an error `syntax error at or near ...`

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.3.12

### Node.js version

22.8.0

### Operating system

MacOS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Please provide a [complete reproduction](https://github.com/mikro-orm/reproduction).

**Comment by andrii03** [comment]
@B4nan 
Here is the link
https://github.com/andrii03/mikro-orm-reproduction

There is the same syntax error when running test
