### ISSUE TITLE
add Polymorphic relations without embedding inline properties to type 

### ISSUE THREAD

**Issue by H-0-O** [mikro-orm/mikro-orm#6106]
Elqoent has polymorphic-relationships , some times developer wants to create  polymorphic models ( type, id ) without embedding them into a table, you know like centralized table, ex  : 

translate table that mapped to 

locale 
key
value 
translatble_type
translatble_id

and User, Category, ...
use them without having properties themselves, I think the Embeddable in mikro-orm is a powerful tool but needs to have this feature

**Comment by B4nan** [comment]
Closing as duplicate of #706
