### ISSUE TITLE
Setting a `prefix` manually in a nested embeddable overrides the parent one

### ISSUE THREAD

**Issue by HugoMendes98** [mikro-orm/mikro-orm#6112]
### Describe the bug

When the `prefix` is set manually in an embeddable (of an embeddable), it does not concatenate with the prefix of the parent.
It can lead to duplicate fieldNames, especially when the embeddable is re-used.

This looks similar to [#5642](https://github.com/mikro-orm/mikro-orm/issues/5642), but with `prefix` set manually.

**Do I intent to submit a PR?**
I've already forked the repo, so I'll give it a try.

> **Note**:
> If this is fixed, it will change the generated schema of entities with manually prefixed nested embeddables.

### Reproduction

The full test can be found [here](https://github.com/heap-code/mikro-orm/blob/0c75401f1f25927ab84363f4909489d12612f3f4/tests/features/embeddables/GH.todo.test.ts).

Here's a short version:

```ts
@Embeddable()
class Address {
  @Property()
  city!: string;
}

@Embeddable()
class Company {
  @Property()
  name!: string;

  @Embedded(() => Address, { prefix: 'addr_' })
  address!: Address;
}

@Entity()
class Person extends BaseEntity {
  @PrimaryKey()
  id!: number;

  @Embedded(() => Address)
  addr!: Address;

  @Embedded(() => Company)
  company!: Company;
}

it('should create the metadata without conflict', async () => {
  let orm: MikroORM | undefined;
  const loadORM = async () => orm = await MikroORM.init({
    entities: [Person],
    dbName: ':memory:',
    strict: true,
    validate: true,
    validateRequired: true,
  });

  // MetadataError: Duplicate fieldNames are not allowed: Person.company_address.city (fieldName: 'addr_city'), Person.addr.city (fieldName: 'addr_city')
  await expect(loadORM()).resolves.toBeDefined();

  await orm?.close();
});
```

### What driver are you using?

None

### MikroORM version

6.3.12

### Node.js version

20.17.0

### Operating system

Ubuntu

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
> If this is fixed, it will change the generated schema of entities with manually prefixed nested embeddables.

Hmm, so it will be a bit breaking, but only for people who depend on this misbehavior. I guess it should be fine to fix that outside of a major bump, worst case we can hide the new behavior behind a flag and do it in v7 if anybody complaints.

**Comment by HugoMendes98** [comment]
> Hmm, so it will be a bit breaking, but only for people who depend on this misbehavior.

Indeed.

The changes will probably be detected with a command such as `mikro-orm migration:check`, but:
1. It is far too optimistic to assume that everyone has this sort of check on a CI or similar.
2. Even with an auto-generated migration, it will drop the existing columns and create the correct ones (instead of renaming).
3. As you said, there may be people who need/want this _absolute-prefix_ behavior.

One way of correcting this without any breaking (for now) would be to add a "prefix-mode":
- `absolute`: (current behavior) whatever the nesting level of the embeddable, the `prefix` value is used.
- `relative`: (the "correct" way) behaves like `prefix: false` but uses the provided `prefix` value instead of the property name for the concatenation.

It could be set both on the global configuration and through the `Embedded` decorator:
```ts
@Embeddable()
class EmbeddableLevel0 {
  @Embedded(() => AnotherEmbeddable, { prefix: "root_", prefixMode: "absolute" })
  nested!: AnotherEmbeddable;
}

MikroORM.init({ embeddables: { prefixMode: "relative" }});
```

And, for the moment, this value defaults to `absolute` and could be replaced by `relative` in a future version.
(Although I think it could be `relative` from the start and mentioned in the documentation?)

What do you think ?

**Comment by B4nan** [comment]
Yeah, that sounds good. If you would go that path, I would keep the default on the current behavior to be safe.
