### ISSUE TITLE
Collection of entity not initialized with dataloaders many-to-many relation

### ISSUE THREAD

**Issue by jukkahell** [mikro-orm/mikro-orm#6119]
### Describe the bug

Loading a nested many-to-many relation using dataloaders throws `Collection<Entity1> of entity Entity2[entityId] not initalized` error.

_Edit: Simpler reproduction in the comments. It doesn't need to be a nested relation._

The reproduction contains the simplest scenario where this happens.  It has a Video that belongs to a Series which have many Categories. Client calls a graphql endpoint requesting video.series.categories which triggers the load resolvers. Loading the series works as expected but when loading categories the dataloaderUtils throws this error:
```
Error: Collection<Series> of entity Category[79857533-922f-450f-94bc-af774759d1af] not initialized,
  at Collection.checkInitialized (/usr/src/app/node_modules/@mikro-orm/core/entity/Collection.js:327:19),
  at Collection.getItems (/usr/src/app/node_modules/@mikro-orm/core/entity/Collection.js:108:18),
  at /usr/src/app/node_modules/@mikro-orm/core/utils/DataloaderUtils.js:146:45,
  at Array.filter (<anonymous>),
  at /usr/src/app/node_modules/@mikro-orm/core/utils/DataloaderUtils.js:179:33,
  at Array.map (<anonymous>),
  at DataLoader._batchLoadFn (/usr/src/app/node_modules/@mikro-orm/core/utils/DataloaderUtils.js:171:34),
```

### Reproduction

```typescript
import {
  Collection,
  DataloaderType,
  Entity,
  ManyToMany,
  ManyToOne,
  MikroORM,
  OneToMany,
  PrimaryKey,
  Property,
  Ref,
} from '@mikro-orm/sqlite';
import { SqliteDriver } from '@mikro-orm/sqlite';

@Entity()
class Video {

  @PrimaryKey()
  id!: string;

  @ManyToOne(() => Series, { nullable: true, ref: true })
  series?: Ref<Series>;

}

@Entity()
class Series {

  @PrimaryKey()
  id!: string;

  @OneToMany(() => Video, video => video.series)
  videos = new Collection<Video>(this);

  @ManyToMany(() => Category)
  categories = new Collection<Category>(this);

}

@Entity()
class Category {

  @PrimaryKey()
  id!: string;

  @Property()
  name!: string;

  @ManyToMany(() => Series, series => series.categories, { nullable: true, ref: true })
  series = new Collection<Series>(this);

}

describe('dataloader collection initialize issue', () => {
  let orm: MikroORM;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [Video, Series, Category],
      dbName: ':memory:',
      driver: SqliteDriver,
      allowGlobalContext: true,
      dataloader: DataloaderType.ALL,
    });
    await orm.schema.createSchema();

    const video1 = new Video();
    video1.id = '1';

    const series = new Series();
    series.id = '1';
    series.videos.add([video1]);

    const category1 = new Category();
    category1.id = '1';
    category1.name = 'category';
    category1.series.add(series);

    await orm.em.persistAndFlush(category1);
    orm.em.clear();
  });

  afterAll(() => orm.close(true));

  test('intialize collections using dataloaders', async () => {
    const videos = await orm.em.findAll(Video);
    expect(videos).toHaveLength(1);

    const series = await videos[0].series?.load();
    expect(series).not.toBeNull();
    await series?.categories.load();
  });
});
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.3.13

### Node.js version

20.12.2

### Operating system

MacOS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
cc @darkbasic

**Comment by jukkahell** [comment]
Apparently ManyToMany must not have the `ref: true` option. Without that it works ok.

**Comment by B4nan** [comment]
Indeed, that option is valid only on to-one relations.
