### ISSUE TITLE
Getting error when using $re (mongodb)

### ISSUE THREAD

**Issue by iamomiid** [mikro-orm/mikro-orm#613]
**Describe the bug**
Getting `MongoError: unknown operator: $re` when performing a simple regex find like so:
```typescript
this.repo.findOne({ name: { $re: 'test' } })
```
**To Reproduce**
1. Use one the example
2. Perform a simple regex search

**Expected behavior**
To return documents matching the input regex.

**Versions**

| Dependency | Version |
| - | - |
| node | 14.3.0 |
| typescript | 3.9.4 |
| mikro-orm | 3.6.15 |

**Comment by B4nan** [comment]
That operator is designed for SQL, you don't need it in mongo, just pass the regexp instance directly:

```typescript
this.repo.findOne({ name: /test/ } })
```

(sure we can make it compatible with mongo too)

**Comment by B4nan** [comment]
Closing as fixed in v4 via https://github.com/mikro-orm/mikro-orm/commit/27e7242ecd75f717722cd825c5c21d65065a83f0
