### ISSUE TITLE
Foreign key constraints renamed in snapshot without generating migration

### ISSUE THREAD

**Issue by rcfox** [mikro-orm/mikro-orm#6146]
### Describe the bug

After upgrading from v6.2.9 to v6.3.13, I noticed that a handful of constraint names were renamed in the `.snapshot-<db>.json` file, but no corresponding SQL was generated to actually rename them in the DB.

I think this might be related to this commit that reduced the maximum name length: https://github.com/mikro-orm/mikro-orm/commit/5b866fabb3de4a7c573051e22dda1a2723a5b94e

I also had an index get renamed, but it did generate SQL to rename it in the migration. Maybe this information will help track down the cause of the issue.

PS: While setting up the repro repo, I noticed that if I didn't include the index, no changes were detected when attempting to create a migration after upgrading. Including the index again shows that the index gets renamed, but the foreign key constraint doesn't.

### Reproduction

https://github.com/rcfox/mikro-orm-constrain-rename

(I know the base repo recommends not using the CLI, but I don't know how to use the migration stuff programmatically, and this more closely resembles my usual workflow.)

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.2.9 -> 6.3.13

### Node.js version

Node v21.6.2, typescript@5.4.5

### Operating system

Ubuntu Linux

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
We are not diffing the FK names at all, that's why this doesn't generate any queries. I am not sure if it makes sense to deal with FK names, right now they are not even explicitly configurable.

**Comment by rcfox** [comment]
I guess my concern was that in the future, if a name changes, that the incorrect name would be used in a migration.

**Comment by B4nan** [comment]
Well, since your snapshot file was correctly updated, I don't see how that could happen.

**Comment by rcfox** [comment]
But the database still has the old name.
