### ISSUE TITLE
Loading relations of entity x from multiple different entities throw error with dataloaders

### ISSUE THREAD

**Issue by jukkahell** [mikro-orm/mikro-orm#6148]
### Describe the bug

I'm using graphql to load somewhat deep hierarchy of entities. One entity, X, is related (m:1) in multiple different entities which is the culprit of this issue when loaded by using dataloaders, throwing error:
```
TypeError: Cannot read properties of null (reading '__helper')
at helper (packages/core/src/entity/wrap.ts:35:33)
at packages/core/src/utils/DataloaderUtils.ts:181:22
    at Array.filter (<anonymous>)
at packages/core/src/utils/DataloaderUtils.ts:206:25
    at Array.map (<anonymous>)
at DataLoader._batchLoadFn (packages/core/src/utils/DataloaderUtils.ts:198:28)
```

I have a bit more complicated relations with my application compared to the reproduction but I was able to reproduce the behaviour by not having an await for the first load call. The error happens when the dataloader combines all those X entities and tries to map them with the owner entities in `DataloaderUtils.getColBatchLoadFn`. When one X belongs to another collection, the `getColFilter` can't find `refOrCol` at all.

Here's the actual scenario if it's relevant:
I have entities: Brand, VideoCollection, Video and ImageAsset
```typescript
class Brand {
  @OneToMany(() => ImageAsset, (imageAsset) => imageAsset.brand, { cascade: [Cascade.ALL] })
  images = new Collection<ImageAsset>(this);
}

class VideoCollection {
  @ManyToOne(() => Brand, { nullable: true, ref: true })
  brand?: Ref<Brand>;

  @OneToMany(() => ImageAsset, (image) => image.videoCollection, { cascade: [Cascade.ALL] })
  images = new Collection<ImageAsset>(this);

  @OneToMany(() => Video, (video) => video.videoCollection)
  videos = new Collection<Video>(this);
}

class Video {
  @ManyToOne(() => Brand, { nullable: true, ref: true })
  brand?: Ref<Brand>;

  @ManyToOne(() => VideoCollection, { nullable: true, ref: true })
  videoCollection?: Ref<VideoCollection>;

  @OneToMany(() => ImageAsset, (image) => image.video)
  images = new Collection<ImageAsset>(this);
}

class ImageAsset {
  @ManyToOne(() => Video, { nullable: true, ref: true })
  video?: Ref<Video>;

  @ManyToOne(() => Brand, { nullable: true, ref: true })
  brand?: Ref<Brand>;

  @ManyToOne(() => VideoCollection, { nullable: true, ref: true })
  videoCollection?: Ref<Video>;
}
```
The error occurs when I load Videos and dataload the brand and videoCollection and their images.

### Reproduction

```typescript
import { Collection, Entity, ManyToOne, MikroORM, OneToMany, PrimaryKey, Property, Ref } from '@mikro-orm/core';
import { SqliteDriver } from '../../packages/sqlite/src';

@Entity()
class Video {

  @PrimaryKey()
  id!: number;

  @Property()
  name!: string;

  @OneToMany(() => Category, category => category.video)
  categories = new Collection<Category>(this);

  @OneToMany(() => Image, image => image.video)
  images = new Collection<Image>(this);

}

@Entity()
class Category {

  @PrimaryKey()
  id!: number;

  @Property()
  name!: string;

  @ManyToOne(() => Video, { nullable: true, ref: true })
  video?: Ref<Video>;

  @OneToMany(() => Image, image => image.category)
  images = new Collection<Image>(this);

}

@Entity()
class Image {

    @PrimaryKey()
    id!: number;

    @Property()
    url!: string;

    @ManyToOne(() => Video, { nullable: true, ref: true })
    video?: Ref<Video>;

    @ManyToOne(() => Category, { nullable: true, ref: true })
    category?: Ref<Category>;

}

describe('GH6548', () => {

  let orm: MikroORM;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [Video, Category],
      dbName: ':memory:',
      driver: SqliteDriver,
      debug: true,
      dataloader: true,
      allowGlobalContext: true,
      populateWhere: 'infer',
    });
    await orm.getSchemaGenerator().refreshDatabase();
  });

  afterAll(() => orm.close(true));

  test('Load with relation from different entities', async () => {
    const video = orm.em.create(Video, { name: 'video1', images: [{ url: '/image1' }] });
    const category = orm.em.create(Category, { name: 'category2', images: [{ url: '/image2' }] });
    await orm.em.flush();
    orm.em.clear();

    const v1 = await orm.em.findOneOrFail(Video, video.id);
    const c1 = await orm.em.findOneOrFail(Category, category.id);
    await Promise.all([v1.images.load(), c1.images.load()]);
  });
});
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.3.13

### Node.js version

20.12.2

### Operating system

MacOS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
> not having an await for the first load call

A better way here is using `Promise.all` which fails the same. 

It's similar to #6031, but here the fix is much simpler, we just need to check if the inverse side exists, returning `false` if not.

**Comment by jukkahell** [comment]
True that. I just made a PR for that https://github.com/mikro-orm/mikro-orm/pull/6149
