### ISSUE TITLE
LoadedReference does not have type for primary keys

### ISSUE THREAD

**Issue by abhijeetviswa** [mikro-orm/mikro-orm#6157]
**Is your feature request related to a problem? Please describe.**
Support I do something like this:
```
const e = await Entity.findOne({}, {fields: ['fk']}); 
```

I will not be able to access `e.fk.id` (assuming id is a/the primary key of `fk`). This is despite the property existing on the Reference class ([refer](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/entity/Reference.ts#L25)). 

I'm forced to either suppress the type error or do something like: `e.fk.$.id`. However, this is also not type-safe since the field has a type `Loaded<Entity>` with the fields hint being never meaning I can access all fields even though they weren't included in fields.

**Describe the solution you'd like**
Add the primary keys of the entity being reference in the definition of `LoadedReference` similar to `Ref` type.

**Describe alternatives you've considered**
None.

**Additional context**
Add any other context about the feature request here.

**Comment by B4nan** [comment]
It already works like that. Let's reopen with a complete reproduction if it's not working for you.

**Comment by abhijeetviswa** [comment]
`main.ts`
```
import { Entity, MikroORM, PrimaryKey, Ref, ref } from "@mikro-orm/postgresql";

@Entity()
export class A {
  @PrimaryKey()
  id!: number;

  @OneToOne("B")
  b!: Ref<B>;

  constructor(id: number, b: B) {
    this.id = id;
    this.b = ref(b);
  }
}

export class B {
  @PrimaryKey()
  id!: number;
}

async function main() {
  const orm = await MikroORM.init();
  const a = await orm.em.findOne(
    A,
    {},
    {
      fields: ["b"],
    },
  );
  const b_id = a.b.id;
}

main();
```

Here, `a` has type: 
```
Loaded<A, never, "b", never> | null
```

while `a.b` is:
 ```
LoadedReference<Loaded<B & object, never, never, never>>
```


`tsconfig.json`:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "ES2022",
    "strict": true,
    "outDir": "dist",
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
  },
  "include": [
    "./**/*.ts"
  ],
}
```

`package.json` (only including dependency versions)
```
    "@mikro-orm/core": "^6.2.3",
    "@mikro-orm/postgresql": "^6.2.3",
    "@mikro-orm/reflection": "^6.2.3",
    "typescript": "^5.4.5"
```

**Comment by abhijeetviswa** [comment]
Tried the same with the following dependency versions:
```
    "@mikro-orm/core": "^6.3.6",
    "@mikro-orm/postgresql": "^6.3.6",
    "@mikro-orm/reflection": "^6.3.6",
    "typescript": "^5.4.5"
```

No change to the inferred types :(

**Comment by B4nan** [comment]
It works just fine on my end, except for the fact that you ignore optionality:

<img width="629" alt="image" src="https://github.com/user-attachments/assets/0932fed0-5678-4eee-83a0-0ba1c6522bf9">

> Tried the same with the following dependency versions:

Those are version ranges, not versions. You should always use latest version before you report anything. Hard to guess what version you use just based on a version range.

**Comment by abhijeetviswa** [comment]
Was not aware of the reproduction sample. Will fork the repo and try reproducing there and share a link.

**Comment by B4nan** [comment]
It is mentioned in the bug report template, maybe I should make it more prominent somehow, feel free to suggest some other place where to mention it.

<img width="847" alt="image" src="https://github.com/user-attachments/assets/ff09d103-45bf-45e9-9ef5-ed4d672f8048">
