### ISSUE TITLE
Serialization with forceObject: true does not apply primary key custom type

### ISSUE THREAD

**Issue by leonardbinet** [mikro-orm/mikro-orm#6179]
### Describe the bug

Serialization using `forceObject: true` doesn't apply custom type on foreign key. 

### Reproduction

```ts
import { MikroORM, serialize, Entity, ManyToOne, Platform, PrimaryKey, Property, Ref, Type } from '@mikro-orm/sqlite';

export class IDStoredAsInteger extends Type<string, number> {

  convertToDatabaseValue(value: string): number {
    return parseInt(value);
  }

  convertToJSValue(value: number): string {
    return `${value}`;
  }

  getColumnType() {
    return `integer`;
  }

}

@Entity()
class User {

  @PrimaryKey({ type: IDStoredAsInteger })
  id!: string;

  @Property({ unique: true })
  email!: string;

  @ManyToOne(() => User, { nullable: true })
  bestFriend?: Ref<User>;

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    dbName: ':memory:',
    entities: [User],
  });
  await orm.schema.createSchema();
});

afterAll(async () => {
  await orm.close(true);
});

it('should apply custom type when serializing primary key of non-populated relation', async () => {
  const totoUser = orm.em.create(User, {
    email: 'toto@test.com',
  });
  orm.em.create(User, {
    email: 'yolo@test.com',
    bestFriend: totoUser,
  });
  await orm.em.flush();

  const u1 = await orm.em.fork().findOneOrFail(User, { email: 'yolo@test.com' });
  const dto1 = serialize(u1);
  expect(typeof dto1.id).toBe('string');
  expect(dto1.bestFriend).toBeDefined();
  expect(typeof dto1.bestFriend).toBe('string');

  const u2 = await orm.em.fork().findOneOrFail(User, { email: 'yolo@test.com' }, { populate: ['bestFriend'] });
  const dto2 = serialize(u2);
  expect(typeof dto2.id).toBe('string');
  expect(dto2.bestFriend).toBeDefined();
  expect(typeof dto2.bestFriend).toBe('string');
});
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.3

### Node.js version

v20.11.1

### Operating system

Macos

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Note that this has nothing to do with `forceObject`.

**Comment by leonardbinet** [comment]
I've submitted a new [PR](https://github.com/mikro-orm/mikro-orm/pull/6186) to fix this issue (tests pass but I don't have the bigger picture though on if it might have side-effects)
