### ISSUE TITLE
em.getRepository() does not return correct class when using @Repository decorator

### ISSUE THREAD

**Issue by chrisbrantley** [mikro-orm/mikro-orm#619]
**Describe the bug**
I'm trying to use a custom Repository class for my entity. I've followed the documentation and extended `EntityRepository<T>` and decorated it with `@Repository(T)`.

However when I call `em.getRepository(T)` the instance that is passed is not an instance of my custom repository but rather `EntityRepository`.

Setting the custom repository on the `@Entity` decorator on the Entity class itself does work properly. 

**Versions**
3.5.6
4.0.0-alpha.3

**Comment by B4nan** [comment]
You need to make sure the file is imported first so the decorator is executed, otherwise it can’t work.
