### ISSUE TITLE
Full Text Search

### ISSUE THREAD

**Issue by thekevinbrown** [mikro-orm/mikro-orm#620]
**Is your feature request related to a problem? Please describe.**
We would like to run full text searches on our database.

**Describe the solution you'd like**
A `$fulltext` operator would be nice for this, e.g.

```typescript
const = await em.count(User, { username: { $fulltext: '@whatever.com' } });
```

**Describe alternatives you've considered**
We could bypass the ORM for these queries, but would really like entities to be populated based on the results.

**Additional context**
In most cases this can be done by extending the `getOperatorReplacement` functionality in `QueryBuilderHelper`, but unfortunately for us, MySQL breaks all that with their:

```
where match(?) against ('?' in natural language mode);
```

So this is going to require a more complete swapping of the subclause when using a fulltext operator.

**Comment by ReactReduxRouterDOM** [comment]
Is there any update regarding the implementation of `$fulltext` in MongoDB?

**Comment by thekevinbrown** [comment]
Nope, I was focused on SQL and haven't finished implementing this yet.

**Comment by service-paradis** [comment]
It would be really great to have this supported in MikroOrm!

> where match(?) against ('?' in natural language mode);

The `match` portion here can also received more than one parameters. Ex.

```sql
SELECT * FROM post
        WHERE MATCH (title, description)
        AGAINST ('javascript' IN NATURAL LANGUAGE MODE);
```

 This case might be more difficult to support.

**Comment by BrunMartins** [comment]
Are there any advancements regarding this feature?

Thanks in advance!

**Comment by thekevinbrown** [comment]
We ended up going with trigram indexes, not full text search.

**Comment by BrunMartins** [comment]
Alright, thanks!

**Comment by bozorgmehr96** [comment]
> We ended up going with trigram indexes, not full text search.

I want to use trigram too but I can't figure out how to query with find methods, did you use query builder?

**Comment by thekevinbrown** [comment]
Depending on how you set the index up, this works:

```typescript
const filter = { $ilike: `${fullTextSearch}%` };
```
