### ISSUE TITLE
Accessing original object in lifecycle hook

### ISSUE THREAD

**Issue by njeirath** [mikro-orm/mikro-orm#622]
I'd like to conditionally take some actions if certain fields of my entity have been updated and I'm curious if there is any way to gain access to both the original entity as well as the updated entity in the `afterUpdate` lifecycle hook so I can compare fields to see which were updated?

**Comment by B4nan** [comment]
Currently not, as `afterUpdate` is executed after the original data is already overridden. We could expose that as a parameter (we could have the whole [`ChangeSet` object](https://github.com/mikro-orm/mikro-orm/blob/master/lib/unit-of-work/ChangeSet.ts) there).

Only way I can see now (without accessing private props) is to do the diff yourself, by first saving the state in `beforeUpdate`.

**Comment by njeirath** [comment]
That makes sense.  Just to add some color to what I'm trying to do in case it's helpful for implementation, I'm basically trying to make the entity observable and only take action on certain kinds of changes:

Say I have a user entity:

```
export class User {
    static afterCreateObservers: ((e: any) => Promise<void>)[] = []

    id: string
    userName?: string
    lastLogin: Date

    async afterUpdate(): Promise<void> {
        for (const o of User.afterUpdateObservers) {
            await o(this)
        }
    }
}
```

With an associated EntitySchema object that defines hook the afterUpdate hook.

What I'd like to do is allow an observer to be able to see both the original as well as updated in case it only cares about changes to userName but not lastLogin over the course of the unit of work.

I'll try the approach you recommended and capture the beginning state in a different hook for the time being.

**Comment by B4nan** [comment]
Closing as implemented in v4 via #623, will be part of next alpha.

All hooks will get an `EventArgs` in the parameter, where you will find `changeSet` object, with `originalEntity` instance (keep in mind it is just a POJO of what was retrieved from the database, not an actual instance of entity). 

Theoretically it should be even possible to adjust the payload in `beforeCreate` and `beforeUpdate`.

**Comment by kennethsato** [comment]
Hello @B4nan .

Is it possible to get originalEntity populated?
I've tried the following lines, but my relationships are unpopulated on originalEntity and populated on entity.

```
  async afterUpdate(
    eventArgs: EventArgs<Insercao>,
    options: UpdateOptions<any>,
  ): Promise<void> {
    const oldInsercao = eventArgs.changeSet.originalEntity as Insercao;
...
```

I also tried to eager load the relationship on Insercao Entity definition, but still no success:
```
  @ManyToOne(() => Comercial, { eager: true })
  comercial: Comercial | null;
```

Must I find my Comercial to use its property?

**Comment by B4nan** [comment]
`originalEntity` represents the raw data from database, there are no relations that could be populated, only raw FKs.
