### ISSUE TITLE
Log executed queries when running migrations

### ISSUE THREAD

**Issue by jtomaszewski** [mikro-orm/mikro-orm#6235]
**Is your feature request related to a problem? Please describe.**

Sometimes I have complex migrations that are composed of multiple queries, e.g. creating/dropping indexes, constraints, renaming columns.

Some of them may take extraordinary time, and it may require the dev to rewrite the migration when that happens.

However right now it's hard to tell which exact `this.addSql(...)` is causing the migration to "hang", as the only log I get is like this:

```
> npm exec mikro-orm -- --config src/postgres/orm/config.ts migration:up

Processing 'Migration20241114101813_RemoveExpensiveScoreIndexes'
```

**Describe the solution you'd like**

Instead, the migration log could print SQLs as they are executed:

```
> npm exec mikro-orm -- --config src/postgres/orm/config.ts migration:up

Processing 'Migration20241114101813_RemoveExpensiveScoreIndexes'
> ALTER TABLE "group_competency_score"
                 DROP CONSTRAINT IF EXISTS "group_competency_score_department_id_user_group_id_50f75_unique";
> CREATE INDEX CONCURRENTLY IF NOT EXISTS "group_competency_score_department_id_index" ON "group_competency_score" ("department_id");
> CREATE INDEX CONCURRENTLY IF NOT EXISTS "group_competency_score_calculate_date_index" ON "group_competency_score" ("calculate_date");
...
```

This outputting executed SQLs to the console could be done behind a `--verbose` option available in the `migration:*` commands.

What do you think?

**Describe alternatives you've considered**
1. `debug: true` passed to ORM config doesn't help
2. replacing all of my migrations to extend a custom `Migration` class and their `execute` method - quite easy, but I think mikro-orm could handle it already, as I've found it useful over many years and frameworks, that printing SQLs in migrations is useful

P.S. For anyone interested in the workaround no 2, here's the code:

```ts
import { EntityData } from '@mikro-orm/core';
import { Migration, Query } from '@mikro-orm/migrations';

/**
 * Same as `Migration`, but logs executed SQLs to the console while they are being executed.
 * ( https://github.com/mikro-orm/mikro-orm/issues/6235 )
 */
export abstract class VerboseMigration extends Migration {
  execute(
    sql: Query,
    params?: unknown[],
  ): Promise<Array<EntityData<Partial<any>>>> {
    this.logSql(sql);
    return super.execute(sql, params);
  }

  private logSql(query: Query) {
    const sql = typeof query === 'string' ? query : query.toSQL().sql;
    console.log(`> ${sql}`);
  }
}
```

**Comment by B4nan** [comment]
Its already possible, you need verbose: true for this if Im not mistaken.

**Comment by B4nan** [comment]
Yeah `verbose: true` in the config should do the job, although it will print all the queries, including the schema queries used by the schema diffing (reading from information schema).

I don't mind adding `verbose` CLI flag to the migrations or maybe as a top level flag.

**Comment by rcfox** [comment]
For local development, I like to pass the command line flag `-c log_statement=all` when starting postgres. This will have postgres log all incoming queries. This can be noisy, but super useful for debugging.

**Comment by jtomaszewski** [comment]
@B4nan do you mean `verbose: true` or `debug: true`? ( https://mikro-orm.io/docs/configuration#debugging--logging ) I'm getting confused now which option is for logging the queries.

**Comment by B4nan** [comment]
Yes, `verbose: true`, you need that for the CLI to enable debug mode.

**Comment by B4nan** [comment]
> Or reduce to one.

That's not really an option. The problem is that people like to have `debug: true` in the ORM config, because they want to see queries of their apps. But if you would honor that in the CLI, every command touching the database (like `migration:create` or any `schema:*` command), you would see tons of very long queries used to get the data from information schema. That's why we have debug mode disabled for the CLI, and you can opt in to it via `verbose: true`.

https://github.com/mikro-orm/mikro-orm/blob/master/packages/cli/src/CLIHelper.ts#L30

But I am not entirely sure if `verbose: true` will do the job, initially this was possible only via `MIKRO_ORM_CLI_VERBOSE` env var. This is already documented on several places:

https://mikro-orm.io/docs/quick-start#setting-up-the-commandline-tool
https://mikro-orm.io/docs/schema-generator#debugging
https://mikro-orm.io/docs/migrations#debugging

**Comment by jtomaszewski** [comment]
> But I am not entirely sure if verbose: true will do the job, initially this was possible only via MIKRO_ORM_CLI_VERBOSE env var.

This is what I was missing, thanks. `verbose: true` isn't enough, I had to pass `MIKRO_ORM_CLI_VERBOSE=1` to make the queries be visible while running the migrations.
