### ISSUE TITLE
upsert() fails with 'column.split is not a function' when using custom types

### ISSUE THREAD

**Issue by zachkirsch** [mikro-orm/mikro-orm#6241]
### Describe the bug

I have an entity that uses a custom type:

```ts
  @Property({ type: PointType })
  homeAddressLocation!: Point;
```

The `PointType` custom type is taken straight from [the docs](https://mikro-orm.io/docs/custom-types#advanced-example---pointtype-and-wkt).

However, when I try to `upsert`:

```ts
      await em.upsert(Person, {
        ...
        homeAddressLocation: {
          latitude: addressLocation.lat,
          longitude: addressLocation.lng,
        },
        ...
```

I get this error: `TypeError: 'column.split is not a function'`

This is the line that throws: https://github.com/knex/knex/blob/176151d8048b2a7feeb89a3d649a5580786d4f4e/lib/dialects/postgres/query/pg-querycompiler.js#L162

The root cause is that knex is expecting `column` to be a string, but at runtime it's an instance of the `Raw` class:

<img width="936" alt="image" src="https://github.com/user-attachments/assets/7b999181-c95e-4e2c-9ed0-1b70405dd22c">

Not sure if this is an issue with knex or mikro-orm, but I have a feeling you will know :)

### Reproduction

Had trouble creating a postgres minimal reproduction - it would be really helpful if you made an equivalent of [mikro-orm/reproduction](https://github.com/mikro-orm/reproduction) but for postgres

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.3.10

### Node.js version

v22.6.0

### Operating system

macOS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
> Had trouble creating a postgres minimal reproduction - it would be really helpful if you made an equivalent of [mikro-orm/reproduction](https://github.com/mikro-orm/reproduction) but for postgres

What troubles? All you need to do is install the driver and swap the imports.

**Comment by zachkirsch** [comment]
@B4nan here is the issue i was running into

```ts
  orm = await MikroORM.init({
    driver: PostgreSqlDriver,
    metadataProvider: TsMorphMetadataProvider,
    password: "password",
    dbName: ":memory:",
    entities: [Person],
    debug: ["query", "query-params"],
    allowGlobalContext: true, // only for testing
  });
```

```
  console.log
    [query] select 1 from pg_database where datname = ':memory:' [took 35 ms]

      at DefaultLogger.log (node_modules/@mikro-orm/core/logging/DefaultLogger.js:38:14)

 FAIL  src/__test__/example.test.ts
  ● basic upsert example

    error: password authentication failed for user "postgres"

      at Parser.parseErrorMessage (node_modules/pg-protocol/src/parser.ts:368:69)
      at Parser.handlePacket (node_modules/pg-protocol/src/parser.ts:187:21)
      at Parser.parse (node_modules/pg-protocol/src/parser.ts:102:30)
      at Socket.<anonymous> (node_modules/pg-protocol/src/index.ts:7:48)
```

**Comment by zachkirsch** [comment]
got it - so i need to configure a postgres server for the repro? do you have an existing repo that I can clone to set up the postgres repro?

**Comment by B4nan** [comment]
Well, you need a postgres server if you want to use postgres driver. You can spin one up via docker compose quite easily. The code you provided is correct, there is nothing else needed (except the SSL option if your server requires it).

https://github.com/mikro-orm/mikro-orm/blob/master/docker-compose.yml#L35-L42

We use `pgvector` here but you can swap that with `postgres`.

**Comment by B4nan** [comment]
Also I highly doubt this is about postgres itself, I'd suggest you try to use sqlite instead. The raw fragment shouldn't get into the knex level at all, it needs to be handled earlier.

**Comment by zachkirsch** [comment]
Here's the repro! https://github.com/zachkirsch/mikro-orm-upsert-custom-type-repro

**Comment by B4nan** [comment]
This is indeed a knex bug: https://github.com/knex/knex/issues/5652

**Comment by zachkirsch** [comment]
Bummer, I have a feeling they are less responsive than you are :)

Will add a +1 to that ticket. thanks!

**Comment by B4nan** [comment]
Well, I have a feeling knex is not really maintained, given the last release was a year ago (and the last commit half a year ago) 🙃 

FYI I already have a local branch that reimplements our query builder without it, so this won't be a problem in there. But that will go into v7 and that is still far away.

**Comment by zachkirsch** [comment]
Ah exciting! All good, we're not blocked here. Thanks for the quick replies

**Comment by B4nan** [comment]
It's actually fixable right now from our end, the raw instance there wasn't needed.

**Comment by zachkirsch** [comment]
Ayyy thank you @B4nan!!!
