### ISSUE TITLE
Query using $in operator on JSONB column fails

### ISSUE THREAD

**Issue by leonardbinet** [mikro-orm/mikro-orm#6246]
### Describe the bug

While migrating from version 5.9.8 to version 6.4.0, a query on a jsonb field using $in operator that used to work properly now fails:

```
import { MikroORM } from '@mikro-orm/postgresql';
import {Entity, PrimaryKey, Property} from "@mikro-orm/core";

@Entity()
class User {

  @PrimaryKey()
  id!: number;

  @Property()
  name: string;

  @Property({ type: 'jsonb', nullable: true })
  meta: { age: number; sex: string };

  constructor(name: string, meta: { age: number; sex: string }) {
    this.name = name;
    this.meta = meta;
  }

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    dbName: 'test',
    port: 5453,
    user: 'postgres_user',
    password: 'postgres_password',
    entities: [User],
    debug: ['query', 'query-params'],
    allowGlobalContext: true, // only for testing
  });
  await orm.schema.refreshDatabase();
});

afterAll(async () => {
  await orm.close(true);
});

test('basic CRUD example', async () => {
  orm.em.create(User, { name: 'Foo', meta: { age: 21, sex: "M"} });
  await orm.em.flush();
  orm.em.clear();

  const user = await orm.em.findOneOrFail(User, { meta: {$in: [{age: 21, sex: "M"}, {age: 21, sex: "F"}]} });
  expect(user.name).toBe('Foo');
});


```

<img width="1031" alt="Screenshot 2024-11-20 at 14 15 22" src="https://github.com/user-attachments/assets/7a9298f2-3c64-42e1-b7aa-13d5e44b6209">

The expected behavior would be to apply a filter on `meta` column with `"meta" in ('{"age":21, "sex:" "M"}', '{"age":21, "sex:" "F"}')`.

(the fact that it works on v5.9.8 still has to be confirmed, since it works on an example on our codebase I still fail to replicate [here](https://github.com/leonardbinet/mikroorm-reproduction/pull/1)) in v5.9.8, the resulting query would have been:
```
select "u0".* from "user" as "u0" where "u0"."meta" in ('{"age":21, "sex:" "M"}', '{"age":21, "sex:" "F"}') limit 1
```

### Reproduction

https://github.com/mikro-orm/reproduction/pull/17

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.4.0

### Node.js version

v20.11.1

### Operating system

macos

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by leonardbinet** [comment]
from what I see on the documentation, this behavior is not actually documented (even it seems to work on 5.9.8 under specific circumstances). It would make sense thus to migrate this issue as a discussion: "was this a supported feature?"

I wonder if there are alternative syntaxes to build the query I intend to perform, I tried playing with `raw` method, but failed to build such a query.

**Comment by B4nan** [comment]
It fails exactly the same with v5 on my end.

> "was this a supported feature?"

I don't think so, but if the query you provided works, maybe we can find a way to go with that approach.

I can imagine it will fall short in case you don't provide the full object, leaving out some properties will most likely mean it won't match the rows, since it will check for equality against them. But still better than not allowing this at all.

**Comment by B4nan** [comment]
Btw using the raw fragments here works just fine, its as simple as this:

```ts
  const user = await orm.em.findOneOrFail(User, {
    meta: {
      $in: [
        sql`'{"age":21,"sex":"M"}'`,
        sql`'{"age":21,"sex":"F"}'`,
      ],
    },
  });
```

**Comment by B4nan** [comment]
Yeah, this was actually quite simple to support, we just need to treat the JSON queries as scalars instead of expanding and processing them as nested relation queries.
