### ISSUE TITLE
`findOne()` has unexpected results if primary key is in where object 

### ISSUE THREAD

**Issue by chrisbrantley** [mikro-orm/mikro-orm#625]
`em.findOne(Entity, {...where})` can return an instance that violates the where clause if the primary key is in the where clause AND an entity with that primary key is in the identity map.

**To Reproduce**
Say you have a very simple model like:
```
@Entity()
class User {
    @PrimaryKey()
    id: string = uuid.v4();

    @Property()
    email: string;

    @Property({ type: String })
    status: UserStatus;
}
```

And I persist an instance like:
```
const user = new User();
user.email = "some@email.com";
user.status = UserStatus.SUSPENDED;
em.persist(user);
await em.flush();
```

Then later I want to fetch a user with a known ID, but ONLY if they are active.
```
const user = await em.findOne(User, { id: myId, status: UserStatus.ACTIVE });
```

If the entity is currently in the entity map you will get the user we persisted despite the where clause being violated (status is SUSPENDED and not ACTIVE).

If the entity is not in the identity map everything works as expected.

**Expected behavior**
If the where clause has ANY conditions beyond the primary key I expect whatever is in the identity map to be ignored and the row to be fetched from the database. 

If there was some reliable way to check the entity in the identity map for all conditions that would be fine but I don't know how that would be possible with all drivers. To be safe, execute the query in order to not return unexpected or invalid results.

**Additional context**
I came across this while writing tests for some session handling logic. Sessions are stored in Redis, but user details are in Postgres. Before I can authorize a request I need to check that the user attached to the session still exists AND is active. My tests were failing consistently to fail authentication for suspended users. Looking at the debug output I saw that a query wasn't even being executed for my user check, the user was just returned from the identity map. I forked the identity map and the problem went away.

It would be extremely rare for this specific bug to occur in production since each EntityManager has its own request context and this is one of the first queries executed. However, this behavior is very surprising and given that the identity map should be essentially transparent I think this is a bug.

Dependency | Version
------------- |--------
node | 12.18.1
typescript | 3.8.3
mikro-orm | 4.0.0-alpha.3
postgresql | 4.0.0-alpha.3

**Comment by B4nan** [comment]
Good catch, thanks for the report!

**Comment by B4nan** [comment]
Closing as fixed in dev, will be part of `alpha.5`.
