### ISSUE TITLE
Wrapped with class smart query condition produces invalid query params

### ISSUE THREAD

**Issue by quaternion** [mikro-orm/mikro-orm#626]
**Describe the bug**
A wrapped smart query conditions (e.g. from input contract classes) produces invalid query params.

**To Reproduce**
```typescript 
// QueryBuilderTest.ts
test('select with wrapped smart query condition', async () => {
  class EqCondition { $eq: number = 1 }
  const eqCondition = new EqCondition()    
  const qb = orm.em.createQueryBuilder(Test2);
  qb.select('*').where({ version: eqCondition });
  expect(qb.getQuery()).toEqual('select `e0`.* from `test2` as `e0` where `e0`.`version` = ?');
  expect(qb.getParams()).toEqual([1]); // fail
});
```
![mikro-orm-v4 0 0-alpha 4-query-bug-2020-06-25-17-16-16](https://user-images.githubusercontent.com/254143/85737468-151c0280-b708-11ea-8dba-e6822c60d191.png)

**Versions**

| Dependency | Version |
| - | - |
| node | 12.18.1 |
| typescript | 3.9.5 |
| mikro-orm | 4.0.0-alpha.4 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
Mmmmm only POJOs are considered there, that is on purpose, as this way I am allowing to pass `knex.raw()` instances...

**Comment by B4nan** [comment]
Spent some time on this but with no luck. Closing as wontfix, this was never really intended to work. 

You could always get around this via shallow copy:

```typescript
qb.select('*').where({ version: { ...eqCondition } });
```
