### ISSUE TITLE
docs: missing docs for assign options onlyOwnProperties, onlyProperties

### ISSUE THREAD

**Issue by RDeluxe** [mikro-orm/mikro-orm#6267]
I think the title says it all. I figured out what `onlyOwnProperties` was doing thanks to the initial Github issue (but I'm not 100% sure though).

In general, I think assign options could use more documentation and examples, as they are pretty important when working with a REST like API.

If you manage to explain them to me, I could propose a PR?

As always, a lot of respect for your work.

**Comment by B4nan** [comment]
I don't even recall having `onlyOwnProperties` option, feels quite internal to me. To tell you what you want from me, I would need to dig through the issues and commits myself, which you can do yourself if you want to help 🙃 Quick look into the code seems like it's about ignoring assign on M:N and 1:M collections. Based on its name, I'd guess it was about ignoring thing that are not directly present in the table columns.

`onlyProperties` is simply about ignoring things that are not part of entity definition, it defaults to `true`, so if you try to assign something which doesn't have a corresponding property mapping, it will be ignored.

**Comment by B4nan** [comment]
Hmm looks like `onlyProperties` defaults to `false`, that's weird. As I said above, my memory on those things is rather sparse :D But my description should be correct, I am just confused about the default.

**Comment by RDeluxe** [comment]
I left a few comments, but the commit is awesome thanks. The addition of js comments is a big plus.

I'm still wrapping my head around some concepts, and I'm thinking of creating a base repo with a few examples showing the different options in action. I'll use the [reproduction codebase](https://github.com/mikro-orm/reproduction), that should be barebone enough.

I'll update this issue with the examples when I have the time, thanks again 🙏
