### ISSUE TITLE
Getting "You cannot call em.flush() from inside lifecycle hook handlers" when using Custom Repository

### ISSUE THREAD

**Issue by etienne-bechara** [mikro-orm/mikro-orm#627]
**Describe the bug**
I am using `mikro-orm` along with `nestjs` and `nestjs-mikro-orm`.

When defining a custom repository for my entity and injecting it through through provided decorators I get the following behavior:

With the example below I can create as many resources as I want with POST requests and they persist OK.

The problem is when a unique constraint fails, and it falls into the exception handler, any other subsequent requests will fail with message below:

**Stack trace**
```
2020-06-29 21:02:14  ERR  You cannot call em.flush() from inside lifecycle hook handlers
at Function.cannotCommit ([...]\nestjs-mikro\node_modules\mikro-orm\dist\utils\ValidationError.js:129:16)
at UnitOfWork.commit ([...]\nestjs-mikro\node_modules\mikro-orm\dist\unit-of-work\UnitOfWork.js:87:43)
at EntityManager.flush ([...]\nestjs-mikro\node_modules\mikro-orm\dist\EntityManager.js:330:36)
at EntityManager.persistAndFlush ([...]\nestjs-mikro\node_modules\mikro-orm\dist\EntityManager.js:275:20)
at TeamRepository.persistAndFlush ([...]\nestjs-mikro\node_modules\mikro-orm\dist\entity\EntityRepository.js:12:23)
at TeamService.createEntity ([...]\nestjs-mikro\dist\_abstract\abstract.service.js:28:35)
at TeamController.postEntity ([...]\nestjs-mikro\dist\_abstract\abstract.controller.js:50:29)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**To Reproduce**
1. Create an Entity
```ts
import { Entity, Property, Unique } from 'mikro-orm';

import { AbstractEntity } from '../_abstract/abstract.entity';

@Entity({ tableName: 'user' })
export class UserEntity extends AbstractEntity {

  @Property()
  @Unique()
  public fullName!: string;

}
```

2. Create a Repo
```ts

import { EntityRepository, Repository } from 'mikro-orm';

import { UserEntity } from './user.entity';

@Repository(UserEntity)
export class UserRepository extends EntityRepository<UserEntity> { }
```

3. Create a service with custom method
```ts
import { BadRequestException, ConflictException, Injectable } from '@nestjs/common';
import { InjectRepository } from 'nestjs-mikro-orm';

import { UserEntity } from './user.entity';
import { UserRepository } from './user.repository';

@Injectable()
export class UserService {

  /** */
  public constructor(
    @InjectRepository(UserEntity)
    private readonly userRepository: UserRepository,
  ) { }

  /** */
  public async createEntity(data): Promise<UserEntity> {
    let newEntity: UserEntity;
    try {
      newEntity = this.userRepository.create(data);
      await this.userRepository.persistAndFlush(newEntity);
    }
    catch (e) {
      if (e.message.match(/duplicate entry/gi)) {
        const violation = /entry '(.+?)' for/gi.exec(e.message);
        throw new ConflictException({
          message: 'DUP MESSAGE',
          violation: violation ? violation[1] : null,
        });
      }
      else {
        throw e;
      }
    }
    return newEntity;
  }
}
```

4. Create a Controller
```ts
import { Body, Controller, Post } from '@nestjs/common';

import { UserService } from './user.service';

@Controller('user')
export class UserController {

  /** */
  public constructor(private readonly userService: UserService) { }

  @Post()
  public async postUser(@Body() data) {
    return this.userService.createEntity(data);
  }

}
```

5. Create a Module
```ts
import { Module } from '@nestjs/common';
import { MikroOrmModule } from 'nestjs-mikro-orm';

import { UserController } from './user.controller';
import { UserEntity } from './user.entity';
import { UserService } from './user.service';

@Module({
  imports: [ MikroOrmModule.forFeature({ entities: [ UserEntity ] }) ],
  controllers: [ UserController ],
  providers: [ UserService ],
  exports: [ UserService ],
})
export class UserModule { }
```

6. Import module at Parent & Run

**Expected behavior**

I am not fiddling with hook events so I just expected it to work.

Also, I could not find other topics regarding this same error message.

**Additional context**
Nothing to add.

**Versions**

| Dependency | Version |
| - | - |
| @nestjs/core | 7.2.0 |
| @nestjs/common | 7.2.0 |
| mikro-orm | 3.6.15 |
| nestjs-mikro-orm | 1.0.3 |

**Comment by B4nan** [comment]
Please create a repro repository, this validation is triggered when you try to flush during flush operation - that can happen either when flushing from hooks or when flushing in parallel (like with promise.all), both is forbidden. I am quite sure that your problem lies elsewhere then in what you provided as reproduction.

**Comment by etienne-bechara** [comment]
@B4nan You are correct the problem lies elsewhere
It appears to be tied with the web framework.

If I swap `@nestjs/platform-fastify` for `@nestjs/platform-express` without further modifications the code works.

Also, if I do the opposite (change Express to Fastify), at the `nestjs-realworld-example-app`, when a persistance exception occurs the problem appears.

Are you aware of any compatibility issues with Fastify?

**Comment by B4nan** [comment]
Nope, never tried fastify. Maybe the request context middleware is not set up correctly, that could result in similar behaviour i guess.

**Comment by etienne-bechara** [comment]
This is the middleware injected by package `nestjs-mikro-orm` correct?

Should I proceed with the issue there then?

**Comment by B4nan** [comment]
Honestly i dont think you will get any response from there, the maintainer is not very responsive :/ will be happy to taky a look into the issue next week, when i am back from vacation.

**Comment by etienne-bechara** [comment]
Ok! Thanks for the help!

I'll post an update here if I find anything relevant on why the middleware appears to not be working with fastify

**Comment by B4nan** [comment]
Looks like there are some issues with wildcard middlewares and fastify adapter

https://github.com/nestjs/nest/issues/972
https://github.com/nestjs/nest/issues/3497

https://docs.nestjs.com/middleware#route-wildcards

> WARNING
> The fastify package uses the latest version of the path-to-regexp package, which no longer supports wildcard asterisks *. Instead, you must > use parameters (e.g., (.*), :splat*).

So probably nothing I can fix from the ORM, it will require changes in the nestjs adapter. You could try to register the middleware yourself, all you need to do is to wrap the `next` call in `RequestContext.create()`, like here:

https://github.com/dario1985/nestjs-mikro-orm/blob/master/libs/nestjs-mikro-orm/src/mikro-orm.middleware.ts

**Comment by B4nan** [comment]
FYI fastify support has been added via https://github.com/mikro-orm/nestjs/pull/4

(so v4, with the new `@mikro-orm/nestjs` packages)

**Comment by SDAdham** [comment]
Hello @B4nan , I am experiencing this error as well, not sure if it's related to any modules I have in my `package.json`
```
ValidationError: You cannot call em.flush() from inside lifecycle hook 
handlers
      at Function.cannotCommit (<ProjectDir>\node_modules\@mikro-orm\core\errors.js:74:16)
      at UnitOfWork.commit (<ProjectDir>\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:158:44)
      at SqlEntityManager.flush (<ProjectDir>\node_modules\@mikro-orm\core\EntityManager.js:457:36)
      at SqlEntityRepository.flush (<ProjectDir>\node_modules\@mikro-orm\core\entity\EntityRepository.js:97:24)
      at CurrenciesService.flush (<ProjectDir>\dist\apps\api\src\lib\service.base.js:202:25)
      at CommonModule.initializeCurrencies (<ProjectDir>\dist\apps\api\src\modules\common\common.module.js:91:38)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)      at async CommonModule.init (<ProjectDir>\dist\apps\api\src\modules\common\common.module.js:204:13) {
```

**Comment by SDAdham** [comment]
Here is the example code of where this issue happens:
```
for (const item of currencies) {
      let currency = await this.currenciesService.findOneByShortName(item);
      if (!currency) {
        currency = new Currency();
        currency.name = item;
        this.currenciesService.persist(currency);
      }
    }
    // Regardless any statement below, it would still crash the same error.
    // await this.em.flush();
    await this.currenciesService.flush();
```

**Comment by SDAdham** [comment]
is v4 released?

**Comment by SDAdham** [comment]
I also have another question, could there a race condition happen if 2 flush are called at the same time? Is this handled?

I am asking in the sense of 2 requests coming in at the same time where a flush might get called twice.

**Comment by Mitch-i** [comment]
I have the same issue if 
```
// logs.service.ts
import { EntityRepository } from '@mikro-orm/core'
import { InjectRepository } from '@mikro-orm/nestjs'
@InjectRepository(Log) private readonly logsRepository: EntityRepository<Log>    // here
```
```

And no issue if use custom repository
// log.repository.ts
import { Repository } from '@mikro-orm/core'
import { EntityRepository } from '@mikro-orm/mysql'

import { Log } from '../entities/log.entity'

@Repository(Log)
export class LogRepository extends EntityRepository<Log> {}
```

```
// logs.service.ts
import { LogRepository } from './repositories/log.repository'
import { Log } from './entities/log.entity'
private readonly logRepository: LogRepository   // here

```
