### ISSUE TITLE
`Cannot read properties of null` with cursor orderBy and after

### ISSUE THREAD

**Issue by alcalyn** [mikro-orm/mikro-orm#6308]
### Describe the bug

I want to use cursor, I use `orderBy` on a column in a relation, and use `after` on id, but get errors:

On my app, I have `TypeError: order is not iterable` at this line (order is undefined): https://github.com/mikro-orm/mikro-orm/blob/v6.4.0/packages/core/src/drivers/DatabaseDriver.ts#L256

And when reproducing it in a mikro-orm test, I get `Cannot read properties of null`, with both mysql and sqlite drivers

I found this similar issue, but not using cursor: https://github.com/mikro-orm/mikro-orm/issues/5389

I read this part of the documentation, but there is only "easy" examples https://mikro-orm.io/api/core/class/EntityRepository#findByCursor

### Reproduction

``` ts
import {
  Entity,
  ManyToOne,
  MikroORM,
  PrimaryKey,
  Property,
  SqliteDriver,
} from '@mikro-orm/sqlite';


@Entity()
class Metadata {

  @PrimaryKey()
  id!: number;

  @Property()
  createdAt!: Date;

}

@Entity()
class Book {

  @PrimaryKey()
  id!: number;

  @ManyToOne({
    entity: () => Metadata,
  })
  metadata!: Metadata;

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [Metadata, Book],
    dbName: ':memory:',
    driver: SqliteDriver,
  });
  await orm.schema.refreshDatabase();
  for (let i = 0; i < 20; ++i) {
    const book = new Book();
    const metadata = new Metadata();
    book.metadata = metadata;
    const date = new Date('2024-01-01 00:00:00');
    date.setDate(date.getDate() + i);
    metadata.createdAt = date;
    orm.em.persist([book, metadata]);
  }
  await orm.em.flush();
  orm.em.clear();
});

afterAll(async () => {
  await orm.close(true);
});

test(`TypeError: Cannot read properties of null (reading 'metadata')`, async () => {
  await orm.em.findByCursor(Book, {}, {
    first: 5,
    after: {
      id: 16,
    },
    orderBy: {
      metadata: {
        createdAt: 'desc',
      },
    },
    populate: [
      'metadata',
    ],
  });
});
```

### What driver are you using?

@mikro-orm/mysql

### MikroORM version

6.4.1

### Node.js version

v20.11.1

### Operating system

Ubuntu

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Your cursor needs to match the properties you are ordering by, you can't request items after some ID while the cursor is about something else. All the values are required. I'd guess you want to order by both the timestamp and ID, to have a stable order over items created at the exact same moment, so you want this:

```ts
  const cursor = await orm.em.findByCursor(Book, {}, {
    first: 5,
    after: {
      id: 16,
      metadata: {
        createdAt: new Date('2024-01-01 00:00:00'),
      },
    },
    orderBy: {
      id: 'desc',
      metadata: {
        createdAt: 'desc',
      },
    },
    populate: [
      'metadata',
    ],
  });
```

But looks like that is also broken now. I'll add a validation for the missing properties and fix this one.

What works is using the opaque strings (suitable for URL query parameters) instead of dealing with this manually, which I would call the best practice anyway:

```ts
  const cursor = await orm.em.findByCursor(Book, {}, {
    first: 5,
    orderBy: {
      id: 'desc',
      metadata: {
        createdAt: 'desc',
      },
    },
    populate: [
      'metadata',
    ],
  });
  const cursor2 = await orm.em.findByCursor(Book, {}, {
    first: 5,
    after: cursor.endCursor!, // opaque string containing the boundaries
    orderBy: {
      id: 'desc',
      metadata: {
        createdAt: 'desc',
      },
    },
    populate: [
      'metadata',
    ],
  });
```

I will add a validation for this.
