### ISSUE TITLE
Primary key UUID buffer length error

### ISSUE THREAD

**Issue by iamomiid** [mikro-orm/mikro-orm#634]
**Describe the bug**
I'm using uuid v1 buffer as primary key and getting the following error:
```
alter table `user` add primary key `user_pkey`(`uuid`); - (conn=111, no: 1170, SQLState: 42000) BLOB/TEXT column 'uuid' used in key specification without a key length
sql: alter table `user` add primary key `user_pkey`(`uuid`); - parameters:[]
```

**To Reproduce**
I'm using the code below:
```typescript
class User {
    @PrimaryKey({ length: 16 })
    uuid = Buffer.from(v1());
}

await orm.getSchemaGenerator().ensureDatabase();
await orm.getSchemaGenerator().dropSchema();
await orm.getSchemaGenerator().createSchema();
```

**Versions**

| Dependency | Version |
| - | - |
| node | 14.3.0 |
| typescript | 3.9.4 |
| mikro-orm | 3.6.15 |
| mariadb | 10.4.13 |

**Comment by B4nan** [comment]
Try using custom type, in v4 this should be handled automatically.

**Comment by iamomiid** [comment]
When will be v4 released(beta at least)?

**Comment by B4nan** [comment]
I won't be releasing anything else than alpha + few RC versions, I'd say alpha 4 is quite usable, I am planning to fix few more things next week when I am back from vacation and start migrating my own projects on that. 

Can't give you any precise date, things are going a bit slower than expected, the only big unknown is currently #214 (almost done but too performance heavy).

Here is the `BlobType` used in v4 automatically when we detect `Buffer` type:

https://github.com/mikro-orm/mikro-orm/blob/dev/packages/core/src/types/BlobType.ts

**Comment by iamomiid** [comment]
Thanks very much.
Can't wait for v4!

**Comment by B4nan** [comment]
Just tried on v4 and it is working fine with the `BlobType`, so closing this as resolved in v4.
