### ISSUE TITLE
How MikroORM Detects Changes

### ISSUE THREAD

**Issue by lnguyenfx** [mikro-orm/mikro-orm#635]
Imagine there are two instances (A & B) of the same application running Mikro-ORM and connected to the same database. How would Mikro-ORM detect changes for a mapped entity on instance A when an update to an entity with the same ID is flushed on instance B?

**Comment by B4nan** [comment]
Identity map is request based, there is no need to detect changes like that. We use transactions to ensure integrity.

**Comment by B4nan** [comment]
Be sure to check out this page:


https://mikro-orm.io/docs/transactions#optimistic-locking

**Comment by lnguyenfx** [comment]
Thanks. I found the following article about Identity Map and Request Context to be pretty helpful as well in this regards.

https://mikro-orm.io/docs/identity-map/
