### ISSUE TITLE
What is the preferred way to initialize and populate new entities?

### ISSUE THREAD

**Issue by calvinwyoung** [mikro-orm/mikro-orm#636]
I'm fairly new to mikro-orm, so apologies if this is documented elsewhere, but I'm having a hard time figuring out the right way to initialize entities with `IdentifiedReference` entities. If we use the Book / Author example [from the docs](https://mikro-orm.io/docs/entity-references), it looks like there are few ways to do this:

a. With `EntityManager.create`:

```typescript
const author = new Author(...);
const book = orm.em.create(Book, { title: 'Book Title', author: author.id });
```

b. With `wrap(...).assign()`:
```typescript
const author = new Author(...);
const book = wrap(new Book()).assign({ title: 'Book Title', author: author.id });
```

c. With custom constructor:
```typescript
const author = new Author(...);
const book = new Book('Book title', author.id);
```

I have several questions about this:

1. Is there a reason to prefer any of the above approaches? Does `em.create()` do anything different from `assign()`?

2. How do `em.create()` and `assign()` handle references to SQL tables that have auto-incrementing primary keys? In those cases, the `id` won't be known until the transaction is flushed.

3. I'd prefer to initialize objects like `new Book({ title: 'Book title', author: author.id })`. Is there a recipe for adding a constructor to `BaseEntity` that allows  the user to pass in a properly-typed set of properties for each entity?

Thanks for the incredible work you've put into mikro-orm — it's been a real joy to use so far.

**Comment by B4nan** [comment]
If the question is only about references, it has nothing to do with `create` or `assign` methods. You can wrap any entity instance to become a `Reference`, either via `wrap(ent).toReference()` or via `Reference.create(ent)`. Also your third example with constructor fully depends on your implementation of the constructor (even the supplied `BaseEntity` do nothing in the constructor). 

In general `em.create()` was meant for creating new entity instances, while `assign()` is for updating existing entity instances. There might be slight differences in how those methods hanle references to other entities (not only those defined as `IdentifiedReference`).

**Comment by calvinwyoung** [comment]
@B4nan That makes complete sense. I've really enjoyed using mikro-orm, and am very excited about some of the features that were just released in v4. Thank you!
