### ISSUE TITLE
Make entity change set available to enable papertrail-like features

### ISSUE THREAD

**Issue by maphe** [mikro-orm/mikro-orm#637]
**Is your feature request related to a problem? Please describe.**
I can't find a way to read the change set of an entity. Basically I'd like to implement some kind of papertrail feature where I could log, in a dedicated table (let's call it `versions` here), the changes that occur to specific entities. That would include the before and after save states of the entity.

**Describe the solution you'd like**
Ideally I'd like:
1. a way to read the current change set of an entity: `EntityManager.getChangeSet(entity)`
2. a way to write into the `versions` table upon events like create or update (as far as I understand current limitations on the lifecycle hooks, I can't do it from a @AfterUpdate as it is today). I imagine an event that I can listen to that carries the change set would work.

**Describe alternatives you've considered**
I've looked at the existing lifecycle hooks but limitations are pretty clear and well explained, seems to be a dead end.
I've dig into the UnitOfWork and ChangeSet code but couldn't find anything relevant.
I would like not to have to use/write a MySQL binlog parser.

**Additional context**
My end goal is to have something that looks like https://www.npmjs.com/package/sequelize-paper-trail adapted for mikro-orm, but I don't want to ask for the whole thing, I just need the means to do it so I can do it myself.
If you think I already have everything I need today and I just couldn't find it please point me to the relevant functions and classes.

**Comment by B4nan** [comment]
#642 will add support for flush events, that should allow you to do this:

```typescript
class FlushSubscriber implements EventSubscriber {

  async onFlush(args: FlushEventArgs): Promise<void> {
    const changeSets = args.uow.getChangeSets();
    const cs = changeSets.find(cs => cs.type === ChangeSetType.CREATE && cs.name === 'FooBar');

    if (cs) {
      const baz = new FooBaz();
      baz.name = 'dynamic';
      cs.entity.baz = baz;
      const cs2 = args.uow.computeChangeSet(baz)!; // 
      args.uow.addChangeSet(cs2);
      args.uow.recomputeSingleChangeSet(cs.entity);
    }
  }

}

em.getEventManager().registerSubscriber(new Subscriber());
const bar = new FooBar();
bar.name = 'bar';
await em.persistAndFlush(bar);
```

It works quite similar to doctrine, you need to explicitly compute the changeset of new entity, as well as recompute changesets of existing entities that you want to change in the subscriber: 

https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/events.html#onflush

**Comment by maphe** [comment]
Nice, thanks, I'll try it out when it's merged.

**Comment by B4nan** [comment]
Closing as #642 is merged, will release new alpha later this week.
