### ISSUE TITLE
Firestore Driver

### ISSUE THREAD

**Issue by manwithsteelnerves** [mikro-orm/mikro-orm#638]
**Describe the solution you'd like**
Firestore is pretty commonly used now a days and it would be great to have the support for it.

**Additional context**
I would be happy to contribute for the firestore driver. But It would be great if you can give a short notes on the following

1. What steps are involved in adding a new driver
2. Some methods within the driver interface may not fit firestore. What to do in that case? (for example creating indexes is always at development time but not at runtime)

Thankyou!

**Comment by B4nan** [comment]
No plans to have other drivers natively (as part of this repository), but you can definitely create 3rd party driver yourself, will be happy to help. I would suggest to take a look at current driver implementations, MongoDriver is probably closest one to what you want. 

Regarding methods that does not make sense - I would throw from them, that is how the ORM behaves internally (like when you try to use schema generator in mongo driver). 

Platform is the place where you define what the driver is capable of, driver is where the orchestration happens, and connection is where actual db calls are done. 

https://mikro-orm.io/docs/custom-driver

**Comment by manwithsteelnerves** [comment]
Thanks! I will have a look at the documentation.
Also, I have already the model files currently in my project. How can I make sure those are used instead of creating schemas again?

**Comment by B4nan** [comment]
> Also, I have already the model files currently in my project. How can I make sure those are used instead of creating schemas again?

Not sure I follow, I don't know much about firestore, but it should be NoSQL driver, so there won't be any schema support. It will be pretty much the same as the current mongo driver.

**Comment by oxc** [comment]
@B4nan, did you actually implement this? Is it public somewhere, or would you be willing to share your (partial) work?

**Comment by oxc** [comment]
@manwithsteelnerves, did you actually implement this? Is it public somewhere, or would you be willing to share your (partial) work? 

(Sorry, highlighted the wrong user :))
