### ISSUE TITLE
Ignoring primary key fields in toObject doesn't work

### ISSUE THREAD

**Issue by thekevinbrown** [mikro-orm/mikro-orm#644]
**Describe the bug**
1. Have some entity with an `id` field.
2. Call `toObject(['id'])`.
3. Serialised object still has `id` field.

**Stack trace**
This comes from here: https://github.com/mikro-orm/mikro-orm/blob/88b979a22ac991df0a3d9401a153415ff928204f/lib/entity/EntityTransformer.ts#L16

The `ignoreFields` variable is only checked for non primary key fields.

**Expected behavior**
It's sometimes nice to omit a primary key when serialising an object. Right now our workaround is:

```typescript
const obj = whatever.toObject(['other', 'properties']);
delete obj.id;
return obj;
```

**Additional context**
N/A

**Versions**

| Dependency | Version |
| - | - |
| node | any |
| typescript | any |
| mikro-orm | 3.6.15 |
| your-driver | Postgres, any |

**Comment by B4nan** [comment]
Closing as fixed in v4, will be part of alpha 6.
