### ISSUE TITLE
Cannot perform persiste operation inside event subscriber

### ISSUE THREAD

**Issue by thynson** [mikro-orm/mikro-orm#652]
**Describe the bug**

Currently persist additional entities during hook is impossible.

```typescript
    async afterCreate(args: EventArgs<AnyEntity>): Promise<void> {
      args.em.getRepository(AwesomeEntity).persiste(new AwesomeEntity); // Not flushed, and cleared after flush operation
      args.em.getRepository(AwesomeEntity).persisteAndFlush(new AwesomeEntity); // throws ValidationError: You cannot call em.flush() from inside lifecycle hook handlers
    }
```

It would be nice if such operation is possible, or introduce new hooks like `beforeFlush` to make it possible to do additional persistence before the flush actually begun.

**Additional context**
#614

**Versions**
4.0.0-alpha4

| Dependency | Version |
| - | - |
| node | 14.5.0 |
| typescript | 3.9.6 |
| mikro-orm | 4.0.0-alpha4 |
| your-driver | postgres |

**Comment by B4nan** [comment]
They are already there, will be part of alpha 5, see #642
