### ISSUE TITLE
Query builder variable value as raw SQL on update&insert

### ISSUE THREAD

**Issue by 0ttik** [mikro-orm/mikro-orm#653]
**Is your feature request related to a problem? Please describe.**

For now when I'm using QB I have it always escaped (like in docs here):
```
const qb = orm.em.createQueryBuilder(Author);
qb.update({ name: 'test 123', type: PublisherType.GLOBAL }).where({ id: 123, type: PublisherType.LOCAL });

console.log(qb.getQuery());
// update `publisher2` set `name` = ?, `type` = ? where `id` = ? and `type` = ?
```

But what if I want to use some cool SQL functions as one of a variable value? Then I guess I have to use knex and it's knex.raw() stuff or:

**Describe the solution you'd like**

TypeORM has this syntax:
```
await messageRepo.createQueryBuilder('message')
        .insert()
        .values({
            chat,
            user: request.user,
            text: request.body.text,
            id: () => `MIN(MAX(NOW()-MAX(1))))` <- some sql which uses functions a lot and which is unascaped in end query
        })
        .execute();
}
```

**Additional context**

Does this make any sense?

**Comment by B4nan** [comment]
In v4 you can use `qb.raw()` (which is just a shortcut for `knex.raw()`):

    const qb = orm.em.createQueryBuilder(Book2);
    qb.update({ price: qb.raw('price + 1') }).where({ uuid: '123' });
    expect(qb.getQuery()).toEqual('update `book2` set `price` = price + 1 where `uuid_pk` = ?');

This works for the where condition, if you want to select without escaping, then any field with a space or parens is considered as custom expression and will not be escaped (that works in v3 already):

    const qb2 = orm.em.createQueryBuilder(Book2);
    qb2.select(['min(max(price))']).where({ uuid: '123' });
    expect(qb2.getQuery()).toEqual('select min(max(price)) from `book2` as `e0` where `e0`.`uuid_pk` = ?');
