### ISSUE TITLE
Add support for Map collections or composite key.

### ISSUE THREAD

**Issue by Darpholgshon** [mikro-orm/mikro-orm#66]
I have a table definition which has a composite primary key and was mapped in Java as a CollectionOfElements.

Example:
Supplier:   { id, name, created_at, updated_at }
SupplierConfiguration: {supplier_id, property_key, property_value}

The composite key is supplier_id and property_key, and in Hibernate this is managed as a Map<String, String> using the decorators below.
```
@CollectionOfElements(fetch = FetchType.EAGER)
@JoinTable(name = "supplier_configuration", joinColumns = @JoinColumn(name = "supplier_id"))
@MapKey(columns = @Column(name = "property_key"))
@Column(name = "property_value")
public Map<String, String> getConfiguration() {
  return configuration;
}
```

**Comment by B4nan** [comment]
Hey there! I am definitely planning to support composite PKs. What do you think about the way Nextras ORM does it?

https://nextras.org/orm/docs/2.3/entity#toc-primary-and-primary-proxy

In your example, you are not defining the child entity (`SupplierConfiguration`), and instead you are defining the collection of config options in the Supplier entity directly, right? I would rather define the child entity, and move the composite PK definition there. Then the config collection definition would be pretty much classic `@OneToMany`:

```typescript
@Entity()
export class Supplier {

  @OneToMany({ fieldName: 'property_value' })
  config = new Collection<SupplierConfiguration>(this);

  getConfiguration(): Record<string, string> {
    return this.config.getItems().map(option => option.value);
  }

}

@Entity()
export class SupplierConfiguration {

  @PrimaryKey({ composite: ['supplier', 'key'] })
  id: string;

  @ManyToOne()
  supplier: Supplier;

  @Property({ fieldName: 'property_key' })
  key: string;

  @Property({ fieldName: 'property_value' })
  value: string;

}
```

The composite PK here would be only virtual property, or we could move this to `@Entity` decorator. WDYT?

```typescript
@Entity({ compositePK: ['supplier', 'key'] })
export class SupplierConfiguration {

  // ...

}
```

Unfortunately there is no eager loading ATM, I am planning to add that as well, but not sure when. But when I am thinking about it now, it could be pretty easy to implement.

**Comment by B4nan** [comment]
Mmmmm I forgot about the mapping part to dictionary, but that can be easily done in the `getConfiguration()` method:

```typescript
getConfiguration(): Record<string, string> {
  return this.config.getItems().reduce((c, v) => { c[v.key] = v.value; return c; }, {});
}
```

**Comment by Darpholgshon** [comment]
I prefer the Hibernate way to be honest. Although I'd prefer a solution with less decorators.
Maybe something along the lines of:
```
@EntityMap({table: 'supplier_configuration', key: 'property_key', value: 'property_value'})
configuration = new Map<string, string>();
```
I did think about adding a mappedBy option as well, although that could be derived from the primary key. You could also add extra things like cascade/eager, although my preference would be that they were implied, and the supplier entity would manage the persistence of an entity map automatically. 

I don't like the idea of defining SupplierConfiguration as an Entity in it's own right but that's a personal preference, not a technical limitation.  I like your solution suggestion for the composite primary key - would you mark both fields as PrimaryKey, decorate as property, or would you introduce another decorator i.e. @ComposiiteKey

**Comment by B4nan** [comment]
The thing is that to be able to do what you want will require multiple features to be implemented first. We first need simple composite keys working, then the ability to use FK as PK, then the use case with dedicated `SupplierConfiguration` entity could be working like this. The last feature would be to support doing this under the hood (`@EntityMap`), without defining the entity manually (I would still define it behind the scenes, just like I am doing this with M:N pivot tables). Plus then there is this eager loading... 

To wrap up, this will require a lot of work and time, so we need to start with small steps and build on top of them. I am happy to do this, but cannot promise it any time soon. Any help is welcome obviously :] I already started to play with the ability to define multiple PK yesterday but it will require changes in lots of places. 

Obvious workaround for now is to define the child entity with auto-increment PK. 

Btw hard to compare hibernate with MikroORM, as this is for me free time project and I am alone to develop/maintain it, so please keep this in mind :]

**Comment by Darpholgshon** [comment]
I totally agree that it's alot of work. I appreciate FT projects mature more slowly, and it's definitely worth getting the more fundamental things in place first, like the composite keys. In time more developers may get interested and want to collaborate.

RE: adding an AI PK column; I'm stuck with the table structure it's a legacy database, that can't be touched - I'm simply adding some modern tooling around admin management.

**Comment by localnet** [comment]
How is this?

I am trying to define a composite key:
```typescript
import { Entity, IdentifiedReference, ManyToOne, Property } from "mikro-orm";
import { ArtistEntity } from "./artistEntity";
import { StudioEntity } from "./studioEntity";

@Entity({ collection: "employee" })
export class EmployeeEntity {
    @Property()
    public fulltime!: boolean;

    @ManyToOne(() => StudioEntity, { primary: true })
    public studio!: IdentifiedReference<StudioEntity>;

    @ManyToOne(() => ArtistEntity, { primary: true })
    public artist!: IdentifiedReference<ArtistEntity>;
}
```

But when I try to generate the schema I get a error:
```
TypeError: Cannot read property 'type' of undefined
    at MySqlSchemaHelper.getTypeDefinition (/home/alejandro/Proyectos/tattoo/server/node_modules/mikro-orm/dist/schema/SchemaHelper.js:16:22)
    at MySqlSchemaHelper.getTypeDefinition (/home/alejandro/Proyectos/tattoo/server/node_modules/mikro-orm/dist/schema/MySqlSchemaHelper.js:16:22)
    at MetadataDiscovery.initColumnType (/home/alejandro/Proyectos/tattoo/server/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:354:45)
    at /home/alejandro/Proyectos/tattoo/server/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:198:18
    at Array.forEach (<anonymous>)
    at MetadataDiscovery.processEntity (/home/alejandro/Proyectos/tattoo/server/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:195:40)
    at /home/alejandro/Proyectos/tattoo/server/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:37:63
    at Array.forEach (<anonymous>)
    at MetadataDiscovery.discover (/home/alejandro/Proyectos/tattoo/server/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:37:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function.init (/home/alejandro/Proyectos/tattoo/server/node_modules/mikro-orm/dist/MikroORM.js:36:28)
    at async Function.handleSchemaCommand (/home/alejandro/Proyectos/tattoo/server/node_modules/mikro-orm/dist/cli/SchemaCommandFactory.js:51:21)
```

**Comment by B4nan** [comment]
Composite keys are not yet supported, it currently works only for M:N relations. But this will be one of the features I am planning to support in one of 3.x releases.

**Comment by localnet** [comment]
Thanks, It seems that I didn't read everything. It is not the best place to ask this, but... Does it only apply to `@ManyToOne` or too to `@OneToOne`?

```typescript
@Entity({ collection: "account" })
export class AccountEntity implements IdEntity<AccountEntity> {
    @PrimaryKey()
    public id!: number;

    @OneToOne(() => ArtistEntity, "account")
    public artist!: IdentifiedReference<ArtistEntity>;
}
```

```typescript
@Entity({ collection: "artist" })
export class ArtistEntity implements IdEntity<ArtistEntity> {
    @PrimaryKey()
    public id!: number;

    @OneToOne(() => AccountEntity)
    public account!: IdentifiedReference<AccountEntity>;
}
```

**Comment by B4nan** [comment]
This part of docs was actually added just few days ago. And yes, it applies to all variants of `IdentifiedReference`.

**Comment by darkbasic** [comment]
I would definitely be interested in using FKs as composite PKs. At the moment I'm working it around by using an auto-increment PK and forcing an unique constraint on the FKs pair, but it would be awesome to have composite PKs support.

**Comment by B4nan** [comment]
Looks like lots of this is actually already working in latest version (3.4.1). 

1. original issue is working, although the child entity is required to be defined manually, but I am not planning to change this soon as it would require quite a lot changes in schema generator and other parts. I feel like the requirement for a child entity to be defined is ok (and somewhat expected). 

```typescript
@Entity()
export class Supplier {

  @OneToMany(() => SupplierConfiguration, c => c.supplier)
  config = new Collection<SupplierConfiguration>(this);

  getConfiguration(): Record<string, string> {
    return this.config.getItems().reduce((c, v) => { c[v.key] = v.value; return c; }, {});
  }

}

@Entity()
export class SupplierConfiguration {

  @ManyToOne({ primary: true })
  supplier: Supplier;

  @PrimaryKey()
  key: string;

  @Property()
  value: string;

}
```

2. Schema generator correctly handles entities with composite PKs. 
3. From my tests, it also works fine with FKs as PKs.
4. Eager loading is also already supported.

What is missing is a way to map entity with composite key as an owner of relation (e.g. in Book-Author example, where now we have `author_id` we would have multiple props based on the composite PK of the `Author` entity), not sure how common use case is that (never needed such thing myself). Also will be adding some validation (like you can't merge composite entity without all composite key values set). 

Also from my tests there are some typing issues with `FilterQuery` and entities without simple PK, will fix that in next release.

**Comment by lewispham** [comment]
I'm just wondering how to guarantee the order of the related columns within PK if we're passing option `primary: true` instead of using an array.
