### ISSUE TITLE
Need help about collection propagation 

### ISSUE THREAD

**Issue by iamomiid** [mikro-orm/mikro-orm#665]
I have a test suite like this:
```typescript
await accountServices.addTransaction(userId, { amount: 2000 })
await accountServices.addTransaction(userId, { amount: 4000 })
```
and this service:
```typescript
public async addTransaction(user: string, data: NewTransaction) {
    const account = await this.repo.findOneOrFail({ user }, ['transactions']);
    const newTransaction = new Transaction(data);
    account.transactions.add(newTransaction);
    await this.repo.flush();
    return newTransaction;
}
```
But I'm getting this error: `ValidationError: You cannot call em.flush() from inside lifecycle hook handlers`.
How can I fix this?

**Comment by iamomiid** [comment]
Using `RequestContext` with `express` works fine but while testing with `jest` I get this error.

**Comment by B4nan** [comment]
Use `--runInBand` to disable parallel execution of tests. Or fork the EM so you have dedicated context for each test.

**Comment by iamomiid** [comment]
I was using `--runInBand` but I wasn't forking the EM. Now it's working fine. I want to test concurrent requests on my service. I'm using the following code but again getting the same error. From your reply, I get that this is happening because it's trying to flush on the same EM in parallel.
```typescript
await Promise.all([
      accountServices.addTransaction(userId, { amount: 2000 }),
      accountServices.addTransaction(userId, { amount: 2000}),
]);
```
So how can I achieve this?

**Comment by B4nan** [comment]
Yes, this code is not supported, you can't flush the same UoW in parallel. You need to fork the EM for each "thread".

https://github.com/mikro-orm/mikro-orm/blob/dev/tests/EntityManager.mysql.test.ts#L1645

**Comment by iamomiid** [comment]
Thanks for the fast reply!
And also, thanks for the awesome orm!
Now, Tests are passing but no change is being made in the database.
What is wrong?

**Comment by B4nan** [comment]
My bet is that you are still using the shared `this.repo` to load the parent entity. You need to load it from the forked EM.

**Comment by iamomiid** [comment]
This is the code that I'm using:
```typescript
  public fork(): void {
    this._entityManager = this._orm.em.fork(true) as EntityManager<MariaDbDriver>;
  }

  public get entityManager(): EntityManager<MariaDbDriver> {
    return this._entityManager;
  }

  get repo(): EntityRepository<T> {
    return this.entityManager.getRepository(entity);
  }
```
So, using the shared `this.repo` should cause no error, right?

**Comment by iamomiid** [comment]
I think I found what I'm doing wrong

**Comment by kodeine** [comment]
@iamomiid can you tell me how did you fix this problem?
