### ISSUE TITLE
Question about locking table while inserting new record

### ISSUE THREAD

**Issue by iamomiid** [mikro-orm/mikro-orm#666]
I want to lock a table while inserting a new record into it. I tried reading the documentation but couldn't find the proper solution. Here is an example code:
```typescript
const newTransaction = new Transaction(data);
const account = await repo.findOneOrFail({ user }, ['transactions']);
account.transactions.add(newTransaction);
await repo.flush();
```
Since docs were a little confusing for me, I tried using the `PESSIMISTIC_WRITE` lock but couldn't figure out how to.

**Comment by B4nan** [comment]
I thought locking is for reading, you dont need to lock for writes.

**Comment by B4nan** [comment]
What table would you like to lock here? I don't think you need locking in your example. In v4 you don't even need to load the `transactions` collection to add to it.

**Comment by iamomiid** [comment]
Consider this example:
User requests for invoice generation multiple times in parallel. If there's no lock for writing, then you would end up with multiple invoices with the same payment price. But only one invoice should be generated and other requests should fail.

Is there any other way to achieve this locking behavior?

**Comment by iamomiid** [comment]
I thought that I could lock the `transaction` table so when inserting multiple items only the first item would be valid.

**Comment by B4nan** [comment]
I don't think this is how locking in SQL works. Can you show me what queries would you like to execute (without the ORM being involved)? 

You can lock a row in a db table, but not the table as a whole (or maybe it is possible to lock the whole table in terms of all rows, but not for inserts (at least I though so - again, if you show me what SQL you want to get, it's a different story).

**Comment by B4nan** [comment]
> I thought that I could lock the transaction table so when inserting multiple items only the first item would be valid.

How would that work? What you say would basically mean to block all requests when something is being processed, making everything sequential.

**Comment by iamomiid** [comment]
I'm new to SQL. I don't know if it's possible or not. I was just guessing. It seems that there's no solution for that.
Sorry for the issue.

**Comment by B4nan** [comment]
I could imagine that you could achieve that by adding a bool column like `adding_tx to the user entity, and inside explicit transaction read that user together with condition for `adding_tx = false` to ignore those that are already being processed by another request. As the first query inside the TX update the `adding_tx = true`, as the last one update it back to `adding_tx = false`.

**Comment by 0ttik** [comment]
Well, I guess in MySQL u can lock table (mysql doc [reference](https://dev.mysql.com/doc/refman/8.0/en/lock-tables.html)) for read/write.

> MySQL enables client sessions to acquire table locks explicitly for the purpose of cooperating with other sessions for access to tables, or to prevent other sessions from modifying tables during periods when a session requires exclusive access to them.

Also I suppose that you can lock not only whole table, but specificly the row you are working with (see [here](https://dev.mysql.com/doc/refman/8.0/en/innodb-locking.html)).

You can do this by just sending some raw SQL.
