### ISSUE TITLE
Docs:  Getting started guide for onboarding new users

### ISSUE THREAD

**Issue by jlarmstrongiv** [mikro-orm/mikro-orm#667]
**Is your feature request related to a problem? Please describe.**
I’m a prospective user considering whether to use mikro-orm in my next project.  I’ve used mongoose, sequelize, and prisma in the past.  I’m starting a new project and found mikro-orm from Google researching (maybe via a reddit comment?).  I don’t know enough about mikro-orm to commit to using it over objection.js or typeorm. 

**Describe the solution you'd like**
I would love to see more onboarding resources for new users and beginners.  There are many ways this could take shape:
- [ ] A video course, such as [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd#get-started-) and [redux](https://redux.js.org/introduction/getting-started#additional-tutorials).  My personal favorite and a great way to clearly demonstrate and explain a sample project.  If there were a video tutorial series, I’d definitely watch it and likely convert to mikro-orm.  
- [ ] A detailed tutorial series, such as [Next.js](https://nextjs.org/learn/basics/create-nextjs-app).  Very easy to follow along, with detailed sections covering all important aspects of the framework.
- [ ] A getting started guide, such as [Gatsby.js](https://www.gatsbyjs.org/tutorial/).  Not as fancy as Next.js, but still detailed, well-written, and easy to follow along.
- [x] [Completed](https://github.com/mikro-orm/mikro-orm#-quick-start):  A quick start article, often posted on Medium or Dev.to.  Many that I’ve seen are unofficial, but are still very helpful.  Can be a single article or a multi-part series.  It is distinct due to being very fast-paced and concise.  
- [x] [Completed](https://github.com/mikro-orm/mikro-orm#-example-integrations):  Example projects in GitHub, such as [claudia.js](https://github.com/claudiajs/example-projects).  Examples of how production apps should be setup or how features should be used are valuable to learn from.  (Consider having an examples folder in the repo with a readme.md linking to the other examples)

**Describe alternatives you've considered**
Not using mikro-orm. 

**Additional context**
I was reading #296 and wanted to leave feedback.  

I’d be glad to run through any drafts and give feedback.  It may just be because I’m programming bootcamp instructor and Communication major, but I think there’s a lot of potential in both mikro-orm and onboarding new users 😄 

EDIT:  If I missed anything feel free to point it out.  I’m writing this just before bed.  Have a g’night!

**Comment by B4nan** [comment]
Currently the focus is v4 development (#527), once v4 will be out, I might do a proper getting started guide to showcase all the features.
