### ISSUE TITLE
(v4): cannot assign entity relation on external subscriber

### ISSUE THREAD

**Issue by vinverdy** [mikro-orm/mikro-orm#669]
**Describe the bug**
Cannot assign entity relation on external subscriber

https://github.com/vinverdy/mikro-orm-external-subscriber-issue

```ts
import {
  Cascade,
  Entity,
  EventArgs,
  EventSubscriber,
  MikroORM,
  OneToOne,
  PrimaryKey,
  Property,
  RequestContext,
} from "@mikro-orm/core";
import express from "express";
import { v4 } from "uuid";

@Entity()
export class Address {
  @PrimaryKey()
  public id: string = v4();
}

@Entity()
export class User {
  @PrimaryKey()
  public id: string = v4();

  @Property()
  public username: string = "hello";

  @OneToOne({ orphanRemoval: true, cascade: [Cascade.PERSIST] })
  public address!: Address;
}

export class UserSubscriber implements EventSubscriber {
  async beforeCreate(args: EventArgs<User>): Promise<void> {
    args.entity.address = new Address();
  }

  public getSubscribedEntities() {
    return [User];
  }
}

(async () => {
  const app = express();
  const port = 3300;

  const orm = await MikroORM.init({
    entities: [User, Address],
    type: "sqlite",
    clientUrl: "sqlite://localhost/:memory:",
    subscribers: [new UserSubscriber()],
    logger: console.log.bind(console),
    debug: true,
  });
  await orm.getSchemaGenerator().updateSchema();

  app.use(express.json());
  app.use((req, res, next) => RequestContext.create(orm.em, next));
  app.get("/", (req, res) =>
    orm.em.persistAndFlush(new User()).then(() => res.sendStatus(200))
  );

  app.listen(port, () => console.log(`Listening on http://localhost:${port}`));
})();
```

Generated Query was:
```sql
begin
insert into `user` (`address_id`, `id`, `username`) values ('e26ac6f0-deb2-4aba-b9e9-0a9822805bd0', '6c7ae704-b0eb-47d6-b559-f927eb8f49d4', 'hello') [took 0 ms]
commit
```

no insert query for address

**To Reproduce**
1. access localhost:3300

**Expected behavior**
Should be able to assign entity relation on external subscribers.

**Versions**
next

| Dependency | Version |
| node | 12 |
| typescript | 3.9 |
| mikro-orm | 4.0.0-alpha.5 |
| sqlite3 | 5 |

**Comment by B4nan** [comment]
This works as expected, change sets are already computed when this hook is fired. You need to use flush events and manually trigger change set computation for the new entity.

See this part of v4 docs: https://github.com/mikro-orm/mikro-orm/blob/dev/docs/docs/lifecycle-hooks.md#using-onflush-event

For your particular example the right way is to use property initializer instead of event subscriber:

```typescript
@Entity()
export class User {
  @OneToOne({ orphanRemoval: true, cascade: [Cascade.PERSIST] })
  public address = new Address();
}
```

**Comment by vinverdy** [comment]
ah okay, the real use case of mine, is getting uid from firebase admin for the specified email, and assign in to user entity. I want to place it on subscribers, instead of my entity. therefore no outside library exists on my domain layer.

Thanks!

**Comment by B4nan** [comment]
If it's just about setting a scalar property (string/number) on given entity, it should work this way (you can see that the UUID of that address was properly set in the query). The problem is with adding new entities mainly.

**Comment by vinverdy** [comment]
kay, thanks for your insights
