### ISSUE TITLE
Question about initializing collections

### ISSUE THREAD

**Issue by iamomiid** [mikro-orm/mikro-orm#671]
I'm initializing the same collection with different where clauses like so:
```typescript
const account = await repo.findOneOrFail({ user });
const invoices = await account.transactions.init({ where: { status: 'invoice' } });
const transactions = await account.transactions.init({ where: { status: 'accepted' } });
```
But when I log `invoices` I get this output:
```
Collection {
      '0': Transaction {
        id: '49b8faa0-c98e-11ea-bbc1-2d10c0dbd922',
        account: Reference { entity: [Account] },
        status: 'accepted',
        amount: 10000,
      },
    }
```
What am I doing wrong?

**Comment by iamomiid** [comment]
Even the queries are right:
```
select `e0`.* from `transaction` as `e0` where `e0`.`status` = 'invoice' and `e0`.`account_id` = 'e511b4d0-c752-11ea-ad44-8f0b636e4844' order by `e0`.`id` asc

select `e0`.* from `transaction` as `e0` where `e0`.`status` = 'accepted' and `e0`.`account_id` = 'e511b4d0-c752-11ea-ad44-8f0b636e4844' order by `e0`.`id` asc
```

**Comment by B4nan** [comment]
Let's put it this way:

> What am I doing wrong?

You are initializing the same collection with different where clauses.

There is always only one instance of entity, therefore one instance of the collection. By calling the second `init` method, you override the results of the first one. Don't use `Collection.init()` here (in general one should not do partial collection loads for this very problem). The method is for initializing the collection, so it is changing the state, it's not about returning the results.

Do this instead:

```typescript
const account = await repo.findOneOrFail({ user });
const invoices = await em.find(Transaction, { account, status: 'invoice' }); // guessing the column name is `account` here
const transactions = await em.find(Transaction, { account, status: 'accepted' });
```

**Comment by iamomiid** [comment]
Oh, Ok.
Thanks very much.
