### ISSUE TITLE
Extend QueryOrder

### ISSUE THREAD

**Issue by mcasarrubios** [mikro-orm/mikro-orm#675]
**Is your feature request related to a problem? Please describe.**
I need order by a column with the `NULLS LAST`/`NULLS FIRST`condition (postgres)

**Describe the solution you'd like**
Maybe we can extend QueryOrder Enum: 
```
export declare enum QueryOrder {
    ASC = "ASC",
    ASC_NULLS_LAST = "ASC NULLS LAST",
    ASC_NULLS_FIRST = "ASC NULLS FIRST",
    DESC = "DESC",
    DESC_NULLS_LAST = "DESC NULLS LAST",
    ...
}
```
**Describe alternatives you've considered**
As a workaround, I'm using queryBuilder (knex) for doing it, but I would like to do that from Entity Repository methods.

I would be happy to make a pull request with this feature, but I would need you to point me in the right direction. Do we need modify anything else? Maybe [here](https://github.com/mikro-orm/mikro-orm/blob/0baad8a756f792881e10816737533391112e129f/lib/query/QueryBuilderHelper.ts#L396)?

**Comment by B4nan** [comment]
Feel free to send a PR.

Should be just about adding those to the enum, but ensure it works by testing it (add few tests to `tests/QueryBuilder.test.ts`) :]

**Comment by B4nan** [comment]
Thanks, closing as #677 is merged, will be part of next alpha.
