### ISSUE TITLE
Support for dynamic schema migration

### ISSUE THREAD

**Issue by asmimo** [mikro-orm/mikro-orm#681]
**Is your feature request related to a problem? Please describe.**
I am going to build a multi-tenant app with schema per tenant architecture. There is already a way to query using a  specific schema and this is the main reason I am going for this orm. But there should also be a way to dynamically run migration by providing schema name on already generated migration files, so that while creating new tenant I can only provide a name and the migration is done without the hassle of me doing it manually or using other tacky ways.

**Describe the solution you'd like**
Providing a schema name in entity skips the dynamic migration. for example:
```js
// schema is provided in entity
@Entity({ schema: 'schema' }) 

// normal entity
@Entity()
```
While running a migration dynamically, first entity is skipped while the second entity with no schema provided is not skipped.
And the migration done by
```js
// code
migrator.up({ schema: 'newSchema' });
// command line
npx mikro-orm migration:up -s newSchema -r
```

**Describe alternatives you've considered**
```js
migrator.up({ entities: [EntityOne, EntityTwo] });
```
But this can be done from within code only and cannot be done using command line.

**Additional context**

- dynamic migrations can be run from either code or command line.
- only those enitities which donot provide a schema is run on dynamic migration.
- while creating migration files create seperate migration files for schema and without schema so that the whole file can be skipped if schema is provided.

**Comment by B4nan** [comment]
Not sure how you expect this to work, migrations cannot be executed dynamically like this - a migration is a set of SQL queries, there are no entities involved in executing them. What you propose could work for generating new migrations, but not executing them. 

What I can imagine is to be able to pass arguments to the `MigrationRunner`, you could access them from the `up()` and `down()` methods and make the queries dynamic this way. I can also imagine this kind of `schema` parameter in `SchemaGenerator` methods - those are where we convert the metadata to actual SQL queries that are then used in the migration files.

**Comment by asmimo** [comment]
Cant schema name be injected in the migration queries before actually running it

**Comment by B4nan** [comment]
This is not about injecting schema name, a migration is where we store the state (the diff), it can't be dynamic, it is executed exactly once in given database/schema (based on the migrations table where we store what was executed). 

Also having entities without explicit schema name provided to behave differently sounds wrong - if there is no schema name, it will go to the default schema (in pg its `public`). I don't like the idea of making users explicitly provide that. 

This sounds like you want to bend migrations for a purpose they are not meant for. Agreed that it would be good to have a proper way to handle multi tenant apps where we have schema per tenant, but that is much bigger problem than just having "dynamic migrations" I'd say. Also I would say this is something that can live outside of the ORM, as an extension. 

How do you plan to create new schema/tenant?

**Comment by asmimo** [comment]
I fell like I am explaining this terribly. So, let me explain it the best I can but before that let me tell u something I have been on the back-end side for couple of months only. So, my knowledge is limited and this is the only idea I can come in my head for migration of multi tenant. Here is my take on it and its going to be long.

First you write entities and describe in it whether whether it should be a normal migration or for multi-tenant
```js
// For normal entity
@Entity()
export class User {
  @PrimaryKey()
  id!: number;
  ...
}

// For multi-tenant
@Entity({ type: 'multi' })
export class User {
  @PrimaryKey()
  id!: number;
  ...
}
```

> Also having entities without explicit schema name provided to behave differently sounds wrong - if there is no schema name, it will go to the default schema (in pg its public). I don't like the idea of making users explicitly provide that.

Yeah I agree on that. I was not thinking enough. 

**Generating migrations**
It should generate a migration like this with a reference that it is for multi-tenant or not
```js
// For normal entity
export class Migration20200726091345 extends Migration {
  // have a reference here that it is for normal only
  async up(): Promise<void> {
    this.addSql('create table "user" ("id" serial primary key, ...);');
  }

}

// For multi-tenant
export class Migration20200726091345 extends Migration {
  // have a reference here that it is for multi-tenant only
  async up(schema: string): Promise<void> {
    this.addSql(`create table "${schema}.user" ("id" serial primary key, ...);`);
  }

}
```
Note: Even if the same project have both entity types create separate migration files. So, while running migration either for multi or normal its respective migration file is only picked.

**Running migration**
Inside code
```js
// For normal entity
migrator.up();

// For multi-tenant
migrator.up({ schema: tenantId })
```
If schema name is not provided run normal migration only picking its respective migration file and skipping other and vice versa. And similar can be done through command line.

**And here is how to use it in real app**
I have a tenant identification table in default public schema and when tenant is registered it is first created in that table from which I take its primary key as id and use it to create a new schema. Here is a rough code:
```js
router.post('/register', async (req, res) => {
  const tenant = new Tenant()
  tenant.*** = req.body.***;
  await em.persistAndFlush(tenant);

  await migrator.up({ schema: tenant.id });
})

// Up or down migration on schemas
router.post('/migration', async (req, res) => {
  const tenants = tenant.findAll;
  const type = req.body.type

  if (type === 'up') {
    tenants.forEach(async (tenant) => {
      await migrator.up({ schema: tenant.id });
  }

  if (type === 'down') {
    tenants.forEach(async (tenant) => {
      await migrator.down({ schema: tenant.id });
  }
})
```
And the tenant with schema is created or updated in couple lines of code dynamically.

There is only one source of truth for migration and I believe that will make creating a schema/updating tables easy as there is no multiple migration files for each tenant which need to be kept in sync.

This is a long explanation but I hope you get what I mean. Let me know if this is a bad approach or either can be improved.

**Comment by B4nan** [comment]
Closing this, I really don't see a need to make migrations dynamic - the idea behind them is actually the opposite - they are just raw SQL queries that will get executed exactly once. Btw using migratios from an API endpoint seems like a security flaw to me :]
