### ISSUE TITLE
No entities discovered on CLI when using the nestjs-mikro-orm example

### ISSUE THREAD

**Issue by rangelfinal** [mikro-orm/mikro-orm#690]
**Describe the bug**
When using the [nestjs-mikro-orm](https://github.com/dario1985/nestjs-mikro-orm) example adapted for CLI usage, entity metadata is not loaded.

**Stack trace**
```
ValidationError: Only abstract entities were discovered, maybe you forgot to use @Entity() decorator?
    at Function.onlyAbstractEntitiesDiscovered (/home/rangel/.config/yarn/global/node_modules/mikro-orm/dist/utils/ValidationError.js:91:16)
    at MetadataValidator.validateDiscovered (/home/rangel/.config/yarn/global/node_modules/mikro-orm/dist/metadata/MetadataValidator.js:33:43)
    at MetadataDiscovery.findEntities (/home/rangel/.config/yarn/global/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:68:24)
    at MetadataDiscovery.discover (/home/rangel/.config/yarn/global/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:31:9)
    at Object.handler (/home/rangel/.config/yarn/global/node_modules/mikro-orm/dist/cli/GenerateCacheCommand.js:22:9) {
  entity: undefined
}
```

**To Reproduce**
1. Clone the nestjs-mikro-orm example repo (https://github.com/dario1985/nestjs-mikro-orm)
2. Move DB configuration from `src/app.module.ts` to a new file `src/mikro-orm.config.ts`
3. Add mikro-orm CLI configuration to package.json:
```  
  "mikro-orm": {
    "useTsNode": true,
    "configPaths": [
      "./src/mikro-orm.config.ts",
      "./dist/mikro-orm.config.js"
    ]
  }
```
4. Enable `esModuleInterop` on tsc compiler options (tsconfig.json)
5. Try any command like `mikro-orm cache:generate` or `mikro-orm migration:create`

**Example**: https://github.com/rangelfinal/nestjs-mikro-orm/tree/bug/repro-absctract-bug

**Additional context**
The same problem happens with postgres.  
This problem affects only the CLI, when nest starts mikro-orm can find entities as expected.  
The cache files in the temp folder generated by the CLI contain almost no information, example:
`Foo.js.json`
```
{
  "data": {
    "className": "Foo",
    "properties": {},
    "hooks": {},
    "indexes": [],
    "uniques": [],
    "constructorParams": [],
    "toJsonParams": [],
    "useCache": true,
    "path": "../dist/entities/foo.entity.js"
  },
  "origin": "../dist/entities/foo.entity.js",
  "hash": "f1ff9af7dbdef7d41b8ddbcf3c2e24f5"
}
```
But when generated by the ORM inside nest (`yarn start`), it contains all needed information:
`Foo.ts.json`
```
{
  "data": {
    "className": "Foo",
    "properties": {
      "id": {
        "name": "id",
        "reference": "scalar",
        "primary": true,
        "type": "number"
      },
      "title": {
        "name": "title",
        "reference": "scalar",
        "getter": false,
        "setter": false,
        "type": "string"
      }
    },
    "hooks": {},
    "indexes": [],
    "uniques": [],
    "path": "./entities/foo.entity.ts",
    "name": "Foo",
    "constructorParams": [],
    "toJsonParams": [],
    "useCache": true,
    "primaryKeys": ["id"],
    "compositePK": false,
    "collection": "foo"
  },
  "origin": "./entities/foo.entity.ts",
  "hash": "521a30abad0adc6e47ac47d2cab93abd"
}
```
Removing `"useTsNode": true` from package.json's mikro-orm config causes the following error:
```
/home/rangel/Workspace/boomerang/monorepo/packages/vendor-server/src/mikro-orm.config.ts:1
import type { Options } from 'mikro-orm'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Function.getConfiguration (/home/rangel/.config/yarn/global/node_modules/mikro-orm/dist/cli/CLIHelper.js:27:32)
    at async Object.handler (/home/rangel/.config/yarn/global/node_modules/mikro-orm/dist/cli/GenerateCacheCommand.js:18:24)
```

**Versions**

| Dependency | Version |
| - | - |
| node | 12.16.3 |
| typescript | 3.9.7 |
| mikro-orm | 3.6.15 |
| sqlite | 4.1.1 |
| sqlite3 | 4.0.12 |

**Comment by B4nan** [comment]
`mikro-orm migration:create` runs ok for me (in your forked repo) - this command works with ts-node, which is the same as when you do `yarn start`, so in other words, this uses the same configuration.

`mikro-orm cache:generate` for me returns "no entities discovered" - which is expected, this command is used to build production cache. and production cache is built based on the compiled JS files, so first we need to run `yarn build`.

That is what I did, but it uncovered another problem - bad configuration. If you look into the `dist` folder, you can see that the entities are in `dist/src/entities`, while the config says `dist/entities`.

When I set the `entitiesDirs` correctly, the `mikro-orm cache:generate` is passing.

> Removing "useTsNode": true from package.json's mikro-orm config causes the following error:

Because you still have the first config file as the TS one - it is found, so the ORM tries to load it, but you disabled ts-node so it does not understand it.

**Comment by rangelfinal** [comment]
> mikro-orm migration:create runs ok for me (in your forked repo) - this command works with ts-node, which is the same as when you do yarn start, so in other words, this uses the same configuration.  

Maybe it's a environment problem, as I'm still stuck with `Only abstract entities were discovered, maybe you forgot to use @Entity() decorator?`. What typescript/ts-node versions are you using?

>That is what I did, but it uncovered another problem - bad configuration. If you look into the dist folder, you can see that the entities are in dist/src/entities, while the config says dist/entities.

That's very weird. I don't have a `dist/src` folder, and my entities are in `dist/entities` as expected.

**Comment by B4nan** [comment]
What does `mikro-orm debug` return?

**Comment by rangelfinal** [comment]
Oh, I see what may have happened  
I was in a hurry, and used `yarn` to install/upgrade the packages, creating a `yarn.lock`  
But I forgot to remove `package-lock.json`
That may explain the differences on the dist folder

`mikro-orm debug`
```
Current MikroORM CLI configuration
 - dependencies:
   - mikro-orm 3.6.15
   - node 12.16.3
   - knex 0.20.15
   - sqlite3 4.2.0
   - typescript 3.9.7
 - package.json found
 - ts-node enabled
 - searched config paths:
   - /home/rangel/Workspace/repro-absctract-mikro-orm-bug/nestjs-mikro-orm/src/mikro-orm.config.ts (found)
   - /home/rangel/Workspace/repro-absctract-mikro-orm-bug/nestjs-mikro-orm/dist/mikro-orm.config.js (found)
   - /home/rangel/Workspace/repro-absctract-mikro-orm-bug/nestjs-mikro-orm/mikro-orm.config.ts (not found)
   - /home/rangel/Workspace/repro-absctract-mikro-orm-bug/nestjs-mikro-orm/mikro-orm.config.js (not found)
 - configuration found
 - will use `entitiesDirs` paths:
   - /home/rangel/Workspace/repro-absctract-mikro-orm-bug/nestjs-mikro-orm/dist/entities (found)
```

**Comment by B4nan** [comment]
That project is badly configured, better to look here:

https://github.com/mikro-orm/nestjs-realworld-example-app

Generally its not a good idea to use `baseDir: __dirname` when the file resides in different folder after compilation. The example I linked here uses the default `baseDir` (so `process.cwd()`) and sets the paths correctly for both environments. If you use `__dirname` you need to be careful so the paths are correct for both TS and the compiled JS files, both for `entitiesDirs` (compiled entities) and `entitiesDirsTs` (TS source files). The `cache:generate` command will always use the `entitiesDirs` as it always operates over compiled entities - but with `useTsNode: true` in your package.json it will use the TS config - and that is where the paths are probably broken.

**Comment by rangelfinal** [comment]
Following the example on the realworld app, I've set `src/mikro-orm.config.ts` to
```
import type { Options } from "mikro-orm";
import { Foo } from "./entities/foo.entity";

export default {
  debug: true,
  entities: [ Foo ],
  entitiesDirsTs: ['src/entities'],
  dbName: 'my-db-name.sqlite3',
  type: 'sqlite',
  autoFlush: false,
} as Options;
```
Changes: Removed baseDir, changed `entitiesDirs` to `entities`, added `debug: true`.  
Still stuck with `Only abstract entities were discovered`.  
Tried `yarn mikro-orm migration:create` to check if there was a problem with my global version of mikro-orm, but got
```
TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at MetadataDiscovery.initCustomType (/home/rangel/Workspace/repro-absctract-mikro-orm-bug/nestjs-mikro-orm/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:411:20)
    at /home/rangel/Workspace/repro-absctract-mikro-orm-bug/nestjs-mikro-orm/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:40:86
    at Array.forEach (<anonymous>)
    at /home/rangel/Workspace/repro-absctract-mikro-orm-bug/nestjs-mikro-orm/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:40:65
    at Array.forEach (<anonymous>)
    at MetadataDiscovery.discover (/home/rangel/Workspace/repro-absctract-mikro-orm-bug/nestjs-mikro-orm/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:40:18)
    at Function.init (/home/rangel/Workspace/repro-absctract-mikro-orm-bug/nestjs-mikro-orm/node_modules/mikro-orm/dist/MikroORM.js:45:24)
    at Function.handleMigrationCommand (/home/rangel/Workspace/repro-absctract-mikro-orm-bug/nestjs-mikro-orm/node_modules/mikro-orm/dist/cli/MigrationCommandFactory.js:63:21)
```

**Comment by rangelfinal** [comment]
I will try and rebase my current app to fork nestjs-realworld-example-app instead of nestjs-mikro-orm, maybe that fixes it.

**Comment by rangelfinal** [comment]
- Cloned the nestjs-realworld-example-app repo
- mv src/config.ts.example src/config.ts
- mv src/mikro-orm.config.ts.example src/mikro-orm.config.ts
- Replaced mysql with postgresql and pointed it to a local docker image
```
const config = {
  type: 'postgresql',
  password: 'mysecretpassword',
  dbName: 'db',
  entities: [Article, Comment, User, Tag],
  entitiesDirsTs: ['src'],
  debug: true,
} as Options;
```
`mikro-orm migration:create` gets `ValidationError: Only abstract entities were discovered, maybe you forgot to use @Entity() decorator?`. 
But `yarn mikro-orm migration:create` actually generates the migration. This must be a weird environment issue.

**Comment by rangelfinal** [comment]
Just confirming: `yarn mikro-orm` without `baseDir: __dirname` works as expected.

**Comment by B4nan** [comment]
Works fine for me, did fresh clone of `nestjs-realworld-example-app`, installed via `yarn`, moved those config files and both commands succeed. Maybe you have some global installations of TS that is clashing with the one from your project (just a wild guess)? 

That validation error is triggered when the `@Entity()` decorator is not executed (that is why its suggests that it might be just forgotten - entity without it is considered as abstract - it won't be represented by a db table directly).
