### ISSUE TITLE
Initialize collection manually

### ISSUE THREAD

**Issue by xeladejo** [mikro-orm/mikro-orm#693]
**Is your feature request related to a problem? Please describe.**

I have two entities:
```typescript
@Entity({ tableName: "artist" })
export default class ArtistEntity {
    @PrimaryKey()
    public id!: number;

    @ManyToMany(() => StyleEntity, undefined, { owner: true })
    public styles: Collection<StyleEntity>;

    public constructor() {
        this.styles = new Collection(this);
    }
}

@Entity({ tableName: "style" })
export default class StyleEntity {
    @PrimaryKey()
    public id!: number;

    @ManyToMany(() => ArtistEntity, "styles")
    public artists: Collection<ArtistEntity>;

    public constructor() {
        this.artists = new Collection(this);
    }
}
```

Now I want do requests to get some artists, but optionally with their related styles.

So, I first query to get some artists, calling to `findList`:
```typescript
export default class ArtistStore {
    private artistRepository: EntityRepository<ArtistEntity>;

    public constructor(ormClient: OrmClient) {
        this.artistRepository = ormClient.em.getRepository(ArtistEntity);
    }

    public async findList(limit: number, cursor?: ArtistStoreCursor): Promise<ArtistEntity[]> {
        const query = this.artistRepository.createQueryBuilder().select("*");

        if (cursor) {
            query.where({ created: { $lte: cursor.created } });
            query.andWhere({ $or: [{ created: { $lt: cursor.created } }, { id: { $lt: cursor.id } }] });
        }

        return query.orderBy({ created: "desc", id: "desc" }).limit(limit).getResult();
    }
```

And if in the request I specify that too want the styles then I call to `findArtists`:
```typescript
export default class StyleStore {
    private ormClient: OrmClient;
    private connection: AbstractSqlConnection;
    private styleRepository: EntityRepository<StyleEntity>;

    public constructor(ormClient: OrmClient) {
        this.ormClient = ormClient;
        this.connection = ormClient.em.getConnection("read");
        this.styleRepository = ormClient.em.getRepository(StyleEntity);
    }

    public async findArtists(artists: (number | string)[]): Promise<StyleEntity[]> {
        const results = await this.connection.execute(
            `select e0.*, e1.artist_id from style as e0
                left join artist_styles as e1 on e0.id = e1.style_id
            where e1.artist_id in (?)`,
            [artists],
        );

        const entities = results.map((result) => {
            const entity = this.styleRepository.map(result);

            entity.artists.add(this.ormClient.em.getReference("ArtistEntity", result.artist_id));

            return entity;
        });

        console.log(entities[0]);
        console.log(entities[0].artists.toArray());
        console.log(entities[0].artists.getIdentifiers());
        console.log(entities[0].artists.getItems());

        return [];
    }
}
```

I get output from the first `console.log(entities[0])`:
```typescript
StyleEntity {
  id: 4,
  artists: Collection {
    '0': ArtistEntity {
      id: 5,
      styles: [Collection],
    },
    initialized: false,
    dirty: true
  },
  name: 'Lettering'
}
```

But not from `console.log(entities[0].artists.toArray())`, `console.log(entities[0].artists.getIdentifiers())` or `console.log(entities[0].artists.getItems())`.

**Describe the solution you'd like**
Something to permit relate data in `ManyToMany` without require do more requests to the database when all the data already is loaded.

**Describe alternatives you've considered**
I can't found a way to do it.

**Comment by B4nan** [comment]
> entity.artists.add(this.ormClient.em.getReference("ArtistEntity", result.artist_id));

This is probably the line that is causing the problem - you cannot add a reference (not-loaded entity) and expect it to be somehow automatically populated. This is exactly what you see in the console log - there is an `ArtistEntity` with ID 5, and I am almost certain that its the same as you add via `em.getReference()`, as it has only the PK (I believe your actual `ArtistEntity` has some other props like `name`, right?). And it is not loaded yet in given context. 

In general you are doing it wrong, using `Collection.add()` is for adding new items to existing collections, that will never have an effect on what gets populated in the JSON response. As you can see in the console log, the collection is not `initialized`.

> Something to permit relate data in ManyToMany without require do more requests to the database when all the data already is loaded.

The right method to use is `Collection.hydrate()` - it is how the collection are hydrated internally. I am not sure if we had that method in v3, as well as I am not sure what version you are using, but no plans to change anything in v3 anyway... 

You will probably also need to mark it as populated to be in the JSON response, via `Collection.populated()`.

I don't really understand why you are using raw query for this, as this can be done easily with the EM api, where all the mapping would be handled automatically for you.

```typescript
// this should issue the very same query as you have (at least in v4), and map it automatically
const styles = await em.find(StyleEntity, { artists: [1, 2, 3] });
```

Same with the `findList` method, I don't see a reason why you are using QB there.

But even with that, you would still end up with not initialized collections, resulting in the same behaviour, you still need to use the `Collection.hydrate()` and `Collection.populated()`.

Anyway this looks like you are trying to build things that others already did, so you might want to take a look at existing solutions, e.g. #364 or look into the dependent packages, there are some starter projects for graphql, like this one https://github.com/dougg0k/nodejs_graphql_typescript_starter

I am not a graphql user, so can't help with that, but it would be helpful (for both of us), if you try to omit the GQL part from the reproduction code - you would most probably understand yourself what is happening and why. It's fine to give an example with the resolvers, but you should try to replicate the problem calling it directly, without dataloader in the background. That is the bit that is missing in your description, there is no control code, just few methods, without the context.

**Comment by xeladejo** [comment]
> This is probably the line that is causing the problem - you cannot add a reference (not-loaded entity) and expect it to be somehow automatically populated. This is exactly what you see in the console log - there is an `ArtistEntity` with ID 5, and I am almost certain that its the same as you add via `em.getReference()`, as it has only the PK (I believe your actual `ArtistEntity` has some other props like `name`, right?). And it is not loaded yet in given context.

I use a reference because I am sure the entity is already loaded. It show all the props, not only the PK:
```typescript
StyleEntity {
  id: 4,
  artists: Collection {
    '0': ArtistEntity {
      id: 5,
      styles: [Collection],
      website: 'https://forbes.com',
      instagram: 'http://wufoo.com',
      facebook: 'http://msu.edu',
      created: 2020-02-05T12:30:30.000Z,
      updated: 2020-03-03T12:30:30.000Z,
      about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Imperdiet nulla malesuada pellentesque elit eget. Amet purus gravida quis blandit turpis cursus in hac habitasse. Pellentesque dignissim enim sit amet venenatis urna cursus eget. Ut pharetra sit amet aliquam. In hac habitasse platea dictumst. Imperdiet nulla malesuada pellentesque elit eget gravida. Massa tempor nec feugiat nisl pretium fusce. Vitae tortor condimentum lacinia quis vel eros donec ac. Lectus proin nibh nisl condimentum id venenatis a. Egestas fringilla phasellus faucibus scelerisque. Aliquet sagittis id consectetur purus ut. Elit pellentesque habitant morbi tristique. Bibendum ut tristique et egestas quis ipsum suspendisse. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Pellentesque habitant morbi tristique senectus et netus. Risus feugiat in ante metus dictum at. Volutpat ac tincidunt vitae semper quis lectus nulla at.'
    },
    initialized: false,
    dirty: true
  },
  name: 'Lettering'
}
```

I will do more tries using `Collection.hydrate()` and `Collection.populated()`. I am using version `4.0.0-alpha.11`.

> I don't really understand why you are using raw query for this, as this can be done easily with the EM api, where all the mapping would be handled automatically for you.
> 
> ```ts
> // this should issue the very same query as you have (at least in v4), and map it automatically
> const styles = await em.find(StyleEntity, { artists: [1, 2, 3] });
> ```

Because I need the `artist_id` to can relate the data (styles to artists). If I query by artists ids `[1, 2, 3]` and I get 6 styles, how do I know which of those style is related to the artist with id 1 or with id 2 or with the id 3?

> Anyway this looks like you are trying to build things that others already did, so you might want to take a look at existing solutions, e.g. #364 or look into the dependent packages, there are some starter projects for graphql, like this one ~https://github.com/dougg0k/nodejs_graphql_typescript_starter~ (edit: looks like this repo is not using request context at all, so rather ignore that)

I will try to understand #364. I am try to do something more simple.

> I am not a graphql user, so can't help with that, but it would be helpful (for both of us), if you try to omit the GQL part from the reproduction code - you would most probably understand yourself what is happening and why. It's fine to give an example with the resolvers, but you should try to replicate the problem calling it directly, without dataloader in the background. That is the bit that is missing in your description, there is no control code, just few methods, without the context.

Here a reproduction without GQL. You will need add a `.env`, for example:
```
NODE_ENV="development"

SERVER_HOST="0.0.0.0"
SERVER_PORT=3000

DATABASE_URL="mysql://root@localhost:3306/develop"
```

and after:
```
npm install
npm run build
npm run database
npm run start
```

`http://localhost:3000` is the equivalent to GQL:
```
query {
   artists(limit: 5) {
    id
    website
    ...
  }
}
```

And `http://localhost:3000/styles=true` the equivalent to GQL:
```
query {
   artists(limit: 5) {
    id
    website
    ...
    styles {
      id
      name
    }
  }
}
```

As always, a great ORM and a great work. Thank you.

**Comment by B4nan** [comment]
Here you go:

```typescript
    public async findArtists(artists: (number | string)[]): Promise<StyleEntity[]> {
        const results = await this.connection.execute(
            `select e0.*, e1.artist_id from style as e0
                left join artist_styles as e1 on e0.id = e1.style_id
            where e1.artist_id in (??)`,
            [artists],
        );

        const map = {} as Record<string, ArtistEntity[]>;

        for (const data of results) {
            const style = this.styleRepository.map(data);
            map[style.id] = map[style.id] ?? [];
            const artist = this.ormClient.em.getReference(ArtistEntity, +data.artist_id);
            map[style.id].push(artist);
        }

        const entities = Object.keys(map).map((id) => {
            const style = this.ormClient.em.getReference(StyleEntity, +id);
            style.artists.hydrate(map[id]);
            style.artists.populated();

            return style;
        });

        console.log(entities[0].artists);
        console.log(entities[0].artists.toArray());
        console.log(entities[0].artists.getIdentifiers());
        console.log(entities[0].artists.getItems());

        return entities;
    }
```

**Comment by xeladejo** [comment]
Thanks you @B4nan, but finally not seems to me the correct way. Now I am trying using `EntityRepository.populate`:
```typescript
    public async populateStyle(entities: ArtistEntity[]): Promise<ArtistEntity[]> {
        return this.artistRepository.populate(entities, "style");
    }
```
> Same with the `findList` method, I don't see a reason why you are using QB there.

What do you suggest? better use:
```typescript
    public async findList(limit: number, cursor?: ArtistStoreCursor): Promise<ArtistEntity[]> {
        if (cursor) {
            return this.artistRepository.find(
                {
                    $and: [
                        { created: { $lte: cursor.created } },
                        { $or: [{ created: { $lt: cursor.created } }, { id: { $lt: cursor.id } }] },
                    ],
                },
                { orderBy: { created: "desc", id: "desc" }, limit },
            );
        }

        return this.artistRepository.findAll({ orderBy: { created: "desc", id: "desc" }, limit });
    }
```

PD: It would be great to be able to use `lateral join` in `where` clause of `populate`.
