### ISSUE TITLE
Quotes are omitted for default values by the Schema Generator

### ISSUE THREAD

**Issue by maphe** [mikro-orm/mikro-orm#695]
**Describe the bug**
Could be one of the following:
1. when generating a schema, default values don't have surrounding quotes, causing syntax error
2. if (1) is by design, then the entity generator from existing db omits inside quotes when generating default attribute of @Property

**Stack trace**
```
Error: create table `stuff` (`id` integer not null primary key autoincrement, `value` varchar not null default something here); - SQLITE_ERROR: near "here": syntax error
```

**To Reproduce**
Something Entity (assume this was auto generated from DB)
```ts
import { Entity, PrimaryKey, Property } from 'mikro-orm';

@Entity({ tableName: 'stuff' })
export class Something {
  @PrimaryKey()
  id!: number;

  @Property({ default: `something here` })
  value: string;
}
```

Schema Generation
```ts
    const orm = await MikroORM.init({
      entities: [Something],
      name: 'sfp_test',
      dbName: 'sfp_db_test',
      type: 'sqlite',
      discovery: { disableDynamicFileAccess: true },
      cache: { enabled: false },
    });
    const generator = orm.getSchemaGenerator();
    console.log(await generator.generate());
```

Output:
```sql
    pragma foreign_keys = off;
    
    drop table if exists `stuff`;
    
    create table `stuff` (`id` integer not null primary key autoincrement, `value` varchar not null default something here);
    
    pragma foreign_keys = on;
```

**Expected behavior**
From those 2, I'm not sure which one is right:
1. ``@Property({ default: `something here` })`` to generate sql with surrounding quotes on default value ``create table ... `value` varchar not null default 'something here'``
2. Entity Generation to generate property with inner extra quotes ``@Property({ default: `'something here'` })``

**Versions**

| Dependency | Version |
| - | - |
| node | `v12.16.1` |
| typescript | `3.9.6` |
| mikro-orm | `^3.6.15` |
| your-driver | `sqlite3` |

**Comment by B4nan** [comment]
In v4 you need to wrap strings in quotes, this is on purpose, to support `default: 'now()'` and similar. In v4 we can use `defaultRaw` for that, `default` behaves the way you want.

**Comment by epechuzal** [comment]
@B4nan the issue is that the entity in question was generated via mikro-orm's entity generator (from an existing DB structure). The column in SQL had a default value of `some string`, which mikro-orm defined like
```ts
@Property({ default: `some string` )
propertyName: string;
```

Does this mean that in v4 the entity generator will use `defaultRaw` when the default value is a SQL function and `default` will be used in other cases, or should I raise a separate issue for the entity generator?

**Comment by B4nan** [comment]
`EntityGenerator` is making some assumptions about the default values - if it sees a string, it considers it as an SQL function, it won't be always correct - it was never meant to be always correct - it is a tool to help you with bootstrapping projects with existing database, but you still need to make adjustments.

Will try to improve this in v4 a bit more, by checking whether the default value is wrapped in quotes, but for example MySQL will never return it quoted (for postgres and sqlite it should help).
