### ISSUE TITLE
Feature request: bulk subscribers with user-defined context

### ISSUE THREAD

**Issue by mikeconley12** [mikro-orm/mikro-orm#702]
Hi! First of all, this project is amazing! Thank you. And I really like [the upcoming](https://github.com/mikro-orm/mikro-orm/issues/527) features!

I have a question. Is it possible to have events like `beforeBulkCreate`, `beforeBulkDelete`, `beforeBulkUpdate`, etc in the EventSubscriber? Like in this [pull request](https://github.com/typeorm/typeorm/pull/2881/files#diff-bc26d7ea987873c82b2e7f0a1cea9a7b).

I think this feature will be very useful for access control logic. For example:

```ts
@Subscriber()
export class ProductSubscriber implements EventSubscriber {
  // not the best way to implement this check, just a simple example
  async beforeBulkCreate({ em, entities, ctx }: BulkEventArgs<Product>): Promise<void> {
    const projectIds = entities.map(entity => entity.projectId);
    const projects = await em.find(Project, { id: { $in: projectIds } });
    const isAllowed = projects.every(project => project.userId === ctx.user.id); // ctx is user-defined context
    if (!isAllowed) {
        throw new ForbiddenException();
    }
  }
}
```

**Comment by B4nan** [comment]
You could use flush events for this:

```typescript
@Subscriber()
export class ProductSubscriber implements EventSubscriber {

  async onFlush(args: FlushEventArgs): Promise<void> {
    const changeSets = args.uow.getChangeSets().filter(cs => cs.type === ChangeSetType.CREATE && cs.name === 'Product');
    const projectIds = changeSets.map(cs => cs.entity.projectId);
    const projects = await em.find(Project, { id: { $in: projectIds } });
    const isAllowed = projects.every(project => project.userId === ctx.user.id); // ctx is user-defined context
    if (!isAllowed) {
        throw new ForbiddenException();
    }
  }

}
```

**Comment by B4nan** [comment]
Btw for this kind of things it's much better to use global filters, setting the user id in some middleware. 

https://github.com/mikro-orm/mikro-orm/pull/663

**Comment by mikeconley12** [comment]
> You could use flush events for this:
> 
> ```ts
> @Subscriber()
> export class ProductSubscriber implements EventSubscriber {
> 
>   async onFlush(args: FlushEventArgs): Promise<void> {
>     const changeSets = args.uow.getChangeSets().filter(cs => cs.type === ChangeSetType.CREATE && cs.name === 'Product');
>     const projects = changeSets.map(cs => cs.entity);
>     const isAllowed = projects.every(project => project.userId === ctx.user.id); // ctx is user-defined context
>     if (!isAllowed) {
>         throw new ForbiddenException();
>     }
>   }
> 
> }
> ```
> 
> #642

It's great! But how can I get a user-defined context?



> Btw for this kind of things it's much better to use global filters, setting the user id in some middleware.
> 
> #663

Sorry, but I don't see how I can use global filters to control create/update/delete access. I think filters can only control read access. Can you please explain this?

**Comment by B4nan** [comment]
> It's great! But how can I get a user-defined context?

You could use the global filter params on the EM. Currently there is no getter, but I can add one, no problem with that. 

```typescript
em.setFilterParams('ctx', { user: 123 }); // this is already there
em.getFilterParams('get'); // would return `{ user: 123 }`

// currently you could read it from the private var
// @ts-ignore
const ctx = em.filterParams.ctx;
```

> Sorry, but I don't see how I can use global filters to control create/update/delete access. I think filters can only control read access. Can you please explain this?

Right, they cannot be used for creating stuff... But they are applied for updates done via `em.nativeUpdate()` as well as deletes via `em.nativeDelete()`, and in general, if you filter things you read, you won't be able to read the thing that would be then updated/deleted (so the filter will block the possibility of UoW issueing update/delete queries on such entities, as they will never be loaded).

**Comment by mikeconley12** [comment]
I think `getFilterParams` would be useful in some cases, thank you.

As I understand it, filters will control read/update/delete access, but only if I use the entity manager (not the query builder).
Also I need access control for create (insert) in addition to filters.

Am I right?

**Comment by mikeconley12** [comment]
> Btw for this kind of things it's much better to use global filters, setting the user id in some middleware.
> 
> #663

About "setting the user id in some middleware". Do you mean using async_hooks or alternatives?

**Comment by B4nan** [comment]
> Am I right?

Yes. 

> About "setting the user id in some middleware". Do you mean using async_hooks or alternatives?

Nope, I mean regular (express) middleware, if you are using `RequestContext` helper, you can obtain the EM fork created for that request from that:

```typescript
app.use((req, res, next) => {
  const em = RequestContext.getEntityManager()!; // can be undefined, if the context was not started yet
});
```

**Comment by mikeconley12** [comment]
Got it, thanks for your help!
