### ISSUE TITLE
Being able to order by calculated values

### ISSUE THREAD

**Issue by AzariasB** [mikro-orm/mikro-orm#707]
**Is your feature request related to a problem? Please describe.**
I'm using postgresql and would like to be able to execute an order by like this : `order by length(my_column)`

**Describe the solution you'd like**
Either being able to use the orderBy provided by mikro-orm : `myquery.orderBy({'length(my_column)':'asc'})` 
or adding a new method to have the same thing as knex : `myquery.orderByRaw({'length(my_column)':'asc'})`

**Describe alternatives you've considered**
I could load all the entities and then do the sorting in typescript

**Additional context**
Currently, when doing `order by length(my_column)` I get the error : `column.split is not a function`
I'm using postgreql 12.3 and mikro-orm 4.0.0-alpha.9

**Comment by B4nan** [comment]
`qb.orderBy({ 'length(my_column)': 'asc' })` will be supported in `4.0.0-rc.1`

**Comment by AzariasB** [comment]
Wow, awesome, thanks !
