### ISSUE TITLE
Does mikro-orm 3.6 support embedded entities?

### ISSUE THREAD

**Issue by gpanainte** [mikro-orm/mikro-orm#710]
I'm thinking of moving from typeorm to mikro-orm, but I already have a lot of entities defined, and some of them contain embedded entities. 

Does mikro-orm 3.6 support this feature? If not, is there any workaround that I could use?

An example of embedded entity in typeorm looks like this:

```typescript

export class Name {

    @Column()
    first: string;

    @Column()
    last: string;

}

@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: string;

    @Column(type => Name)
    name: Name;

    @Column()
    isActive: boolean;

}

```

**Comment by B4nan** [comment]
This is supported in v4, no plans to backport it. I'd say use v4, will be shipping RC probably during weekend, when I am back from vacation. 

https://github.com/mikro-orm/mikro-orm/blob/dev/docs/docs/embeddables.md

**Comment by cupcakearmy** [comment]
Is there an example @B4nan? the link you put is down :)

**Comment by cupcakearmy** [comment]
NVM found it in the PR https://github.com/mikro-orm/mikro-orm/pull/514
