### ISSUE TITLE
Audit logging

### ISSUE THREAD

**Issue by Langstra** [mikro-orm/mikro-orm#711]
When using mikro-orm with nestjs (in my case) I want to use the EventSubscriber to act on Insert, Update and Delete events. However, I cannot create new AuditLog entities inside the EventSubscriber. I cannot inject my AuditLogService into the Subscriber

I'd like to be able to inject a service into the EventSubscriber which can then be used to insert new AuditLog entities into the db. 

I used typeorm before, which did support something similar. With Mikro-Orm I have tried to use the @Injectable decorator and added the subscriber to the provider array of nestjs App Module.

**Comment by B4nan** [comment]
It should work fine, all you need to do is to register the subscriber in the `EventManager` when the subscriber gets instanced. Something like this could work:

```typescript
@Injectable()
export class MySubscriber {

  constructor(em: EntityManager) {
    em.getEventManager().registerSubscriber(this);
  }

}
```

But this won't allow you to flush new entities from inside the event handlers (not in the same UoW, you can fire native queries for sure). For that you need to use flush events:

https://github.com/mikro-orm/mikro-orm/blob/dev/docs/docs/lifecycle-hooks.md#flush-events

**Comment by Langstra** [comment]
Does this mean that you can inject your own service into a subscriber along with the EntityManager and the subscribe the thing as an EventSubscriber? And what if in that case the service would try to flush a new (audit log) entity?

**Comment by Langstra** [comment]
I created a repository displaying the problem I am having. If you have time would you mind looking at it? https://github.com/RiskChallenger/mikro-orm-issue (Second example in the repo)

**Comment by B4nan** [comment]
As I already said, you can't use lifecycle events for this, you need to use flush events. Lifecycle events are fired when the transaction is already running, calling flush inside them is forbidden. What you can do is to create a new fork (via `em.fork()`) and use that - which will create separate transaction. Or you can use `em.nativeInsert()` (which is equivalent to using a QB). 

Btw all event handlers will get EM instance in the `EventArgs`. You should use that one, as there can be multiple instances of EM (e.g. when doing nested transactions), and the one in `EventArgs` is always the one that triggered the event.

Will take a look at the repo, I believe it should be working, but I haven't tested this myself yet, so there might be some problem with this lazy registration (maybe you are registering it to the request scoped EM, but you need to register it to the global one).

**Comment by Langstra** [comment]
I tried logging the different id's of the EM's and found that the EM that the EventSubscriber is registered to is different from the EM that is in the RequestContext. So I guess that the EventSubscriber is registered to the global one.

In an additional test I added a TestSubscriber that also subscribed to afterCreate Project events. This EventSubscriber was registered using the @Subscriber() annotation. After both are registered I logged `console.log(em.getEventManager()['listeners']);` what showed both subscribers. Even though both a registered, only the TestSubscriber is triggered after saving a new project.

I have updated the repo with the changes I made to test this.

**Comment by B4nan** [comment]
Btw looking at your project - you don't need to use `@InjectRepository` with custom repositories - as long as there is actual class, it works fine (`@InjectRepository` is needed because by default all repositories are implementations of `EntityRepository`).

**Comment by Langstra** [comment]
I have been looking into the code and I have a hunch, but you are probably better at confirming or debunking this.

My idea is that currently the request scoped EM triggers the events. This request scoped EM is created and then instantiates the EventManager like this `new EventManager(this.config.get('subscribers'));`. The configuration does not contain the EventSubscribers that were registered using the lazy registration.

**Comment by B4nan** [comment]
Yeah that sounds correct.

**Comment by Langstra** [comment]
I think I can make a PR to fix this, but what way do you think it should be fixed? When forking the em the EventManager is not copied, but recreated and then it forgets all the lazy registered EventSubscribers. So I guess we have at least 2 approaches:

1. In the fork method we create a copy of the EventManager and set that as the EventManager of the new EM. I guess we need a new EventManager and not reuse the EventManager of the global EM, right?
2. Push the lazy loaded EventSubscribers to the subscribers config `config.get('subscribers') when registering.

Maybe there are other better solutions?

**Comment by B4nan** [comment]
Thinking about it a bit, and I'd say it should be fine to even reuse the `EventManager` instance. All it does is to hold the list of subscribers, the actual (global) parameter values are held in the `EntityManager` (and even those are copied when forking the EM).

So it should be just about making the property writable and doing `em.eventManager = this.eventManager;` in the fork method. Feel free to send a PR.
