### ISSUE TITLE
Foreign key property (not mapped)

### ISSUE THREAD

**Issue by travigd** [mikro-orm/mikro-orm#750]
**Is your feature request related to a problem? Please describe.**
I don't see a way to declare a property as a foreign key (not as a mapped property à la `@ManyToOne` and friends), which for *reasons* is something I'd like to do (I'm using dataloader with GraphQL so I mostly am just using Mikro as an easier, type-safe-ish way to access the database).

**Describe the solution you'd like**
A way to declare a property as a foreign key without doing data mapping.
```ts
@Property({
  columnType: "int",
  references: "users(id)"
})
userId: number;
```

Alternatively, the ability to specify custom constraints (eg as SQL) would be good enough.

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by awHamer** [comment]
I'd really appreciate to see thing this in Mikro-orm

**Comment by jonasbeyer** [comment]
I think the equivalent TypeORM decorator is `@RelationId`, which also supports many-to-many relations.

```
@JoinTable()
@ManyToMany(() => User)
users: User[];

@RelationId("users")
userIds: number[];
```

**Comment by B4nan** [comment]
I believe the OP is about using just the PK, not two properties for one thing (and also for writes, right?).

I can imagine something like this:

```ts
@ManyToOne(() => User)
user: number;
```

This would allow reusing all the relation definition logic, and we would just need to adjust hydration. @travigd WDYT?

Btw I see that the `@RelationId` is for reads only, you could achieve the same here with a simple getter (and also recently added property serializers, if what you care about is the serialized API response).

**Comment by B4nan** [comment]
I will go with explicit option in the m:1/1:1 decorators, reusing all the logic of schema definition as with mapping to entity:

```ts
@ManyToOne(() => User, { mapToPk: true })
user: number;
```

For composite keys, this will give you ordered tuple representing the raw PKs, which is the internal format of composite PK:

```ts
@ManyToOne(() => User, { mapToPk: true })
user: [string, string]; // [first_name, last_name]
```

Doing something similar for collections is already possible via getters (only for reading purposes):

```ts
@ManyToMany(() => User)
users = new Collection<User>(this);

@Property({ persist: false })
get userPKs: number[] {
  return this.users.getItems(false); // disabling initialization check, depends on the use case
}
```

Btw thanks to recent changes in hydration it is also possible to map the same column to multiple properties (which was not working before), so this is also possible:

```ts
@Entity()
export class Book {

  @ManyToOne(() => Author2)
  author: Author2;

  @Property({ persist: false }) // you should make only one of them "persistable", and use the other as read only
  authorId!: number;

}
```

**Comment by olivierlacan** [comment]
> ```ts
> // you should make only one of them "persistable", and use the other as read only
> ```

I'm curious why both can't be achieved? 

It seems like it should be possible to assign a related entity either as a full object with no primary key **or** assign a previously persisted entity relation via either the foreign key assignment to a reader/writer property (`authorId: "uuid"`) or a full object representation of that same `author` which could be destructured to either only extract the foreign key or do an update operation on the referenced related entity (in case some fields are different).

I think this relates more to #1469 but both issues are closed so I figured here was as good a place as any to discuss it.

**Comment by varunkamra** [comment]
@B4nan Could you please help with my issue?

I have these two tables with following definition:
```
 CREATE TABLE IF NOT EXISTS productions (
    production_guid UUID DEFAULT uuid_generate_v4(), 
    production_status_guid UUID NOT NULL,
    finished_item_guid UUID NOT NULL,
    args JSONB NOT NULL,
    created_at TIMESTAMP(1) NOT NULL DEFAULT CURRENT_TIMESTAMP(1),
    updated_at TIMESTAMP(1) NOT NULL DEFAULT CURRENT_TIMESTAMP(1),
    CONSTRAINT productions_production_status_guid_fkey FOREIGN KEY (production_status_guid)
    REFERENCES production_statuses(production_status_guid) ON DELETE CASCADE,
    CONSTRAINT productions_finished_item_guid_fkey FOREIGN KEY (finished_item_guid)
    REFERENCES items(item_guid) ON DELETE CASCADE,
    CONSTRAINT productions_pkey PRIMARY KEY (production_guid)
    )

CREATE TABLE IF NOT EXISTS production_histories (
    production_history_guid UUID DEFAULT uuid_generate_v4(), 
    production_guid UUID NOT NULL,
    event_type_guid UUID NOT NULL,
    label VARCHAR(255) NOT NULL,
    args JSONB,
    created_at TIMESTAMP(1) NOT NULL DEFAULT CURRENT_TIMESTAMP(1),
    updated_at TIMESTAMP(1) NOT NULL DEFAULT CURRENT_TIMESTAMP(1),
    CONSTRAINT prod_hist_production_guid_fkey FOREIGN KEY (production_guid)
    REFERENCES productions(production_guid) ON DELETE CASCADE,
    CONSTRAINT prod_hist_event_type_guid_fkey FOREIGN KEY (event_type_guid)
    REFERENCES event_types(event_type_guid) ON DELETE CASCADE,
    CONSTRAINT production_histories_pkey PRIMARY KEY (production_history_guid)
    )
```

And these are the entities I wrote for these which are not complete yet:
Production Entity:
```
import { Cascade, Check, Collection, Entity, ManyToOne, OneToMany, PrimaryKey, Property } from "@mikro-orm/core";
import { BaseModel } from "./BaseModel";
import { ProductionStatus } from "./ProductionStatus";
import { Item } from "./Item";
import { ProductionHistory } from "./ProductionHistory";

@Entity({tableName: 'productions'})
export class Production extends BaseModel {
  constructor(productionStatusGuid: string, finishedItemGuid: string, args: object) {
    super();
    this.production_status_guid = productionStatusGuid;
    this.finished_item_guid = finishedItemGuid;
    this.args = args;
  }

  @PrimaryKey({ type: 'string', persist: false })
    production_guid: string;

  @ManyToOne(() => ProductionStatus, {mapToPk: true})
  @Check({expression: 'required'})
    production_status_guid: string;

  @ManyToOne(() => Item, {mapToPk: true})
  @Check({expression: 'required'})
    finished_item_guid: string;

  @Property({ type: 'object' })
  @Check({expression: 'required'})
    args: object;

  @OneToMany({ entity: 'ProductionHistory', mappedBy: 'production_guid', cascade: [Cascade.PERSIST] })
    productionHistories = new Collection<ProductionHistory>(this);
}
```
Production History entity:
```
import { Check, Entity, ManyToOne, PrimaryKey, Property } from "@mikro-orm/core";
import { BaseModel } from "./BaseModel";
import { Production } from "./Production";
import { EventType } from "./EventType";

@Entity({tableName: 'production_histories'})
export class ProductionHistory extends BaseModel {
  constructor(productionGuid: string, eventTypeGuid: string, label: string, args: object) {
    super();
    this.production_guid = productionGuid;
    this.event_type_guid = eventTypeGuid;
    this.label = label;
    this.args = args;
  }

  @PrimaryKey({ type: 'string', persist: false })
    production_history_guid: string;

  @ManyToOne(() => Production, {mapToPk: true})
  @Check({expression: 'required'})
    production_guid: string;

  @ManyToOne(() => EventType, {mapToPk: true})
  @Check({expression: 'required'})
    event_type_guid: string;
  
  @Property({ type: 'string' })
  @Check({expression: 'required'})
    label: string;
  
  @Property({ type: 'object' })
    args: object;
}
```
If we cannot persist both primary key and foreign key at the same time in two different entities, I decided to make primary key non persistable since it is added by default in the database as uuid v4. However, if I do this how do I fetch the latest inserted object from db since we don't have the primary key in the object before it was inserted in the db? If I make the foreign key as non persistable then it does not allow me to save the foreign key which I want to save in the db for production histories table. Could you help?

**Comment by varunkamra** [comment]
Is it also possible to create a gihub issue template for help for mirko-orm?

**Comment by B4nan** [comment]
Why are you asking here, in an issue that is 3 years old?

You should not use issues for help support, ask on slack or use GH discussions. I am moving issues that are neither feature requests nor valid bugs right ahead to discussions anyway.

**Comment by varunkamra** [comment]
Okay, thanks I will ask question on slack.

**Comment by bakura10** [comment]
Hi @B4nan :),

First of all thanks for this work. I am coming from PHP world (where I have used Doctrine 2 extensively) and can see a lot of similarities (I wonder if Doctrine 2 has been an inspiration by the way?).

I am considering creating a small app eventually in Node and come across this repo. I would also like the ability to create a Foreign key _without_ an association. Doctrine suffers from the same limitaton so I am currently manually adding the FK manually in a migration.

The use case is to create references between domain aggregate using an ID, by making sure the entity itself is not exposed at all beside the ID. From what I understand, this can be simulated in Mikro ORM with non-persistable fields, but this still expose the real relation.

Having the ability to create a foreign key maybe like this would help to remove the need to maintain manual migrations.

```
@Property({columnType: "uuid"})
@ForeignKey({foreignTable: "users", foreignColumn: ["id"]})
userId: number;
```
