### ISSUE TITLE
TypeError: Cannot read property 'fieldNames' of undefined

### ISSUE THREAD

**Issue by charmpitz** [mikro-orm/mikro-orm#756]
**Describe the bug**
When configuring the migrations and executing the following command I get an error. It seems to be related to the metadata. Any ideas how to fix it?

**Stack trace**
```
/app $ yarn mikro-orm migration:create
yarn run v1.22.4
$ /app/node_modules/.bin/mikro-orm migration:create
mikro-orm migration:create

Create new migration with current schema diff

Options:
  -b, --blank    Create blank migration                                [boolean]
  -d, --dump     Dumps all queries to console                          [boolean]
  -p, --path     Sets path to directory where to save entities          [string]
  -v, --version  Show version number                                   [boolean]
  -h, --help     Show help                                             [boolean]

TypeError: Cannot read property 'fieldNames' of undefined
    at /app/node_modules/@mikro-orm/knex/src/schema/SchemaGenerator.ts:189:108
    at Array.map (<anonymous>)
    at createIndex (/app/node_modules/@mikro-orm/knex/src/schema/SchemaGenerator.ts:189:74)
    at /app/node_modules/@mikro-orm/knex/src/schema/SchemaGenerator.ts:200:37
    at Array.forEach (<anonymous>)
    at TableBuilder._fn (/app/node_modules/@mikro-orm/knex/src/schema/SchemaGenerator.ts:200:20)
    at TableBuilder.toSQL (/app/node_modules/knex/lib/schema/tablebuilder.js:44:12)
    at SchemaCompiler_PG.createTable (/app/node_modules/knex/lib/schema/compiler.js:89:25)
    at SchemaCompiler_PG.toSQL (/app/node_modules/knex/lib/schema/compiler.js:72:26)
    at SchemaBuilder.toSQL (/app/node_modules/knex/lib/schema/builder.js:79:43)
    at SchemaBuilder.Target.toQuery (/app/node_modules/knex/lib/interface.js:8:21)
    at SchemaGenerator.dump (/app/node_modules/@mikro-orm/knex/src/schema/SchemaGenerator.ts:470:25)
    at SchemaGenerator.getUpdateTableSQL (/app/node_modules/@mikro-orm/knex/src/schema/SchemaGenerator.ts:142:19)
    at SchemaGenerator.getUpdateSchemaSQL (/app/node_modules/@mikro-orm/knex/src/schema/SchemaGenerator.ts:94:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Migrator.getSchemaDiff (/app/node_modules/@mikro-orm/migrations/src/Migrator.ts:79:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**
Call `yarn mikro-orm migration:create` on an existing project.

**Expected behavior**

**Additional context**
I am using 3 entities(user, tag, article), all being tested and working properly when calling the apis of my app. 
All entities have the `@Entity` decorator and haven't had any other issues. 
I'm using nestjs and Postgresql and I have an existing schema inside the database.
Creating a migration via CLI with `--blank` seems to work.

The config I'm using:
```
import * as dotenv from 'dotenv';
import { Options } from '@mikro-orm/core';
import { TsMorphMetadataProvider } from '@mikro-orm/reflection';

dotenv.config();

const config: Options = {
    type: 'postgresql',
    host: process.env.POSTGRES_HOST,
    port: +process.env.POSTGRES_PORT,
    user: process.env.POSTGRES_USER,
    password: process.env.POSTGRES_PASSWORD,
    dbName: process.env.POSTGRES_DB,
    entitiesDirs: ['dist/**/entities'],
    entitiesDirsTs: ['src/**/entities'],
    migrations: {
        path: __dirname + '/migrations/',
        tableName: 'migrations',
        transactional: true,
    },
    tsNode: process.env.NODE_DEV === 'true' ? true : false,
    metadataProvider: TsMorphMetadataProvider,
};

export = config;
```

**Versions**

| Dependency | Version |
| - | - |
| node | 14.7.0 |
|typescript | ^3.7.4 |
|@mikro-orm/cli | ^4.0.0-alpha.0 |
|@mikro-orm/core | ^4.0.0-alpha.0 |
|@mikro-orm/migrations | ^4.0.0-alpha.0 |
|@mikro-orm/nestjs | ^4.0.0-alpha.2 |
|@mikro-orm/postgresql | ^4.0.0-alpha.0 |
|@mikro-orm/reflection | ^4.0.0-alpha.0 |

**Comment by quinnturner** [comment]
FWIW I am also having issues with migrations using the exact stack as you. I can connect via Nest + API at run-time, but the CLI just hasn't worked for me at all.

However, I get this issue instead:

```sh
ValidationError: Only abstract entities were discovered, maybe you forgot to use @Entity() decorator?
```

Here's my config:

```ts
const config: Options<PostgreSqlDriver> = {
  entities: [EmailIdentity],
  metadataProvider: TsMorphMetadataProvider,
  dbName: process.env.PHOENIX_DATABASE_NAME,
  host: process.env.PHOENIX_DATABASE_HOST,
  password: process.env.PHOENIX_DATABASE_PASSWORD,
  user: process.env.PHOENIX_DATABASE_USER,
  port: process.env.PHOENIX_DATABASE_PORT
    ? parseInt(process.env.PHOENIX_DATABASE_PORT, 10)
    : 5432,
  type: 'postgresql',
  logger: logger.log.bind(logger),
  highlighter: new SqlHighlighter(),
  debug: true,
};
```

If I change `entities` to be:

```ts
  entities: ['./dist/**/*.entity.js'],
  entitiesTs: ['./src/**/*.entity.ts'],
```

I receive:

```sh
TypeError: Cannot use 'in' operator to search for 'schema' in ./dist/**/*.entity.js
```

I should probably log these as separate bug reports/questions, but we may be able to address everything in one go!

**Comment by B4nan** [comment]
before reporting anything, you should always upgrade to the latest version, which is now `rc.1`. you are on the very first alpha version.

and ideally provide a reproduction right ahead, at least I need to see your entity definitions, ideally repository including some schema dump, as this is about diffing the dump and your entity definitions. this is not about your configuration, this is about making a schema diff.

**Comment by B4nan** [comment]
@quinnturner open your own issue and provide steps to reproduce, as well as all the issue template info. 

there are working examples of nestjs integrations, including the CLI, you probably have something wrong in your setup. will be happy to take a look if you give me full reproduction, but currently i don't have a clue from what you gave me.

**Comment by B4nan** [comment]
@charmpitz from the stack trace it looks like your problem might be wrong index definition - in the `@Index` decorator you need to use the property names (so those defined in your entity), not column names (defined in your database)

if so, this is a duplicate of #755

**Comment by charmpitz** [comment]
@B4nan You were right it was a duplicate of that. I was using `user_id` (table column name) instead of `user` (property of the entity) for the `@Unique` decorator. Now it works properly. 
I was too tired to post everything and really just hoped it would be an easy fix which it was. Thank you for all the hard work! :v:
