### ISSUE TITLE
Acorn-loose import throws errors

### ISSUE THREAD

**Issue by thomaschaaf** [mikro-orm/mikro-orm#758]
**Describe the bug**
There seems to be a problem with acorn-loose that it can not be packaged with webpack?

**Stack trace**
```
ERROR in /x/node_modules/acorn-loose/dist/acorn-loose.mjs 41:15-19
Can't import the named export 'Node' from non EcmaScript module (only default export is available)
 @ /x/node_modules/@mikro-orm/core/utils/Utils.js
 @ /x/node_modules/@mikro-orm/core/utils/QueryHelper.js
 @ /x/node_modules/@mikro-orm/core/utils/index.js
 @ /x/node_modules/@mikro-orm/core/index.js
 @ /x/src/services.ts
 @ /x/src/lib/adapter/httpAdapter.ts
 @ /x/src/handlers/up.ts

ERROR in /x/node_modules/acorn-loose/dist/acorn-loose.mjs 43:15-19
Can't import the named export 'Node' from non EcmaScript module (only default export is available)
 @ /x/node_modules/@mikro-orm/core/utils/Utils.js
 @ /x/node_modules/@mikro-orm/core/utils/QueryHelper.js
 @ /x/node_modules/@mikro-orm/core/utils/index.js
 @ /x/node_modules/@mikro-orm/core/index.js
 @ /x/src/services.ts
 @ /x/src/lib/adapter/httpAdapter.ts
 @ /x/src/handlers/up.ts


ERROR in /x/node_modules/acorn-loose/dist/acorn-loose.mjs 177:25-31
Can't import the named export 'Parser' from non EcmaScript module (only default export is available)
 @ /x/node_modules/@mikro-orm/core/utils/Utils.js
 @ /x/node_modules/@mikro-orm/core/utils/QueryHelper.js
 @ /x/node_modules/@mikro-orm/core/utils/index.js
 @ /x/node_modules/@mikro-orm/core/index.js
 @ /x/src/services.ts
 @ /x/src/lib/adapter/httpAdapter.ts
 @ /x/src/handlers/up.ts

ERROR in /x/node_modules/acorn-loose/dist/acorn-loose.mjs 20:23-37
Can't import the named export 'SourceLocation' from non EcmaScript module (only default export is available)
 @ /x/node_modules/@mikro-orm/core/utils/Utils.js
 @ /x/node_modules/@mikro-orm/core/utils/QueryHelper.js
 @ /x/node_modules/@mikro-orm/core/utils/index.js
 @ /x/node_modules/@mikro-orm/core/index.js
 @ /x/src/services.ts
 @ /x/src/lib/adapter/httpAdapter.ts
 @ /x/src/handlers/up.ts
```

**Versions**

| Dependency | Version |
| mikro-orm | 4.0.0-beta.rc2 |

**Comment by thomaschaaf** [comment]
Marking `acorn-loose` as an external package. Seems to fix the problem.

**Comment by B4nan** [comment]
Maybe we should replace `acorn` with this: https://github.com/meriyah/meriyah 

As `acorn` is one of the things that don't have any typings.

**Comment by B4nan** [comment]
Hmmm looks like we will need to stick with `acorn-loose` for now, will add a note about it in webpack section.

**Comment by B4nan** [comment]
Could you prepare a reproduction? Just tried to build my nest app with webpack and it works fine with `rc.2` (which is somewhat surprising to me, tbh :D)

**Comment by xeladejo** [comment]
@thomaschaaf, you've tried:
```JavaScript 
resolve: {
   mainFields: ["main", "module"]
}
```

https://webpack.js.org/configuration/resolve/#resolvemainfields

**Comment by B4nan** [comment]
Also have you seen this? 

https://mikro-orm.io/docs/deployment#webpack-configuration

It is not updated for v4, but there is this bit that might help too:

      // Some of MikroORM's dependencies use mjs files, so let's set them up here.
      {
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto',
      },

**Comment by B4nan** [comment]
@thomaschaaf any updates on this?

**Comment by darkadept** [comment]
Is this only fixed in the 4.x branch? I'm seeing this same error when I use mikro-orm 3.6.15.
