### ISSUE TITLE
Support for mixins in superclasses

### ISSUE THREAD

**Issue by oliversalzburg** [mikro-orm/mikro-orm#762]
**Is your feature request related to a problem? Please describe.**
I'm trying to model an existing database structure and there are common properties that could be modeled into TypeScript mixins. MikroORM does not seem to support this.

**Describe the solution you'd like**
Mixins should behave the same way as regular base classes.

**Describe alternatives you've considered**
Complex inheritance structures or copying the repeating properties into every class.

**Additional context**
I've created a repo to illustrate how I was approaching this: https://github.com/oliversalzburg/mixin-mikro-orm

**Comment by B4nan** [comment]
As discussed on slack, this is out of scope of this project. Will be happy to accept PRs, but no plans to work on this in near future (I am not even sure if it's possible/compatible with how MikroORM entity definition works).

Using `EntitySchema` sharing parts of entity definition should be possible.
