### ISSUE TITLE
Distinguish locking failure from other validation error

### ISSUE THREAD

**Issue by thynson** [mikro-orm/mikro-orm#769]
**Is your feature request related to a problem? Please describe.**
I want to handle locking failed error explicitly, unlike other reason that will result in a ValidationError to be thrown, locking failure is usually not caused by bug or configuration error.

**Describe the solution you'd like**
Derive a new type LockingFailedError from ValidationError. Users can handle it by `instanceof` operator.

**Comment by thynson** [comment]
Sorry, but I think the case https://github.com/mikro-orm/mikro-orm/commit/b357686a5775e97a0b82eeed59a232302d3b1875#diff-806f6b932f62de2816121040d9a583aaL53 should be a ValidationError. Try to optimistic-locking an entity has no version property is a bug, and will always fail. What users concern about is handling a possible failure path.

**Comment by B4nan** [comment]
I already replied you, it is a validation error, as its a subclass. The code is aligned with how doctrine works, no plans to change that. 

https://github.com/doctrine/orm/blob/2.7/lib/Doctrine/ORM/OptimisticLockException.php#L89

**Comment by thynson** [comment]
What I wanted to handle the case that when multiple processes concurrently modify one entity, resulting in some process failed to commit their modification

> it is a validation error, as its a subclass.

Yeah, OptimisticLockError is a subtype of ValidationError, but if OptimisticLockError was designed to denote the case described above, then `notVersioned` shall put to ValidationError, not OptimisticLockError.

 Or we could add another child error class:

```typescript
// Represents any error relates to optimistic locking error
class OptimisticLockError extends ValidationError {
   static notVersioned() {/*...*/}
} 
// Represents the case of concurrent modification conflict
class OptimisticLockFailedError extends OptimisticLockError {
    static lockFailedVersionMismatch() { /*...*/}
    static lockFailed() { /*...*/}
}
```

**Comment by thynson** [comment]
Through Doctrine's put all these cases together into one class, I think that is not a good idea.

**Comment by B4nan** [comment]
As I said, this is designed based on doctrine, I have no plans to change it. I really don't see any reason to do so. I do understand what you mean, but I don't see a need to distinguish this. 

`OptimisticLockError` is a runtime error raised when you try to lock and the lock fails. Entity not being versioned is one of the reasons to fail.

**Comment by thynson** [comment]
> I do understand what you mean, but I don't see a need to distinguish this.
It decides whether I should response an HTTP 500 (Bugs) or an HTTP 412 (Failed to update based on the response content of the previous GET request)

**Comment by thynson** [comment]
Anyway, I can accept it as all `notVersioned` case could be eliminated by testing
