### ISSUE TITLE
Is it possible to use selects in migrations?

### ISSUE THREAD

**Issue by sh84** [mikro-orm/mikro-orm#770]
I would like something like this:
```
async up(): Promise<void> {
    const otherTableId = await this.execute('SELECT id FROM other_table WHERE ...');
    this.addSql('alter table test add other_table_id int');
    this.addSql('update table test set other_table_id = ' + otherTableId);
}
```
But I haven't found a way to make a select and get the result of its execution in the migration..

**Comment by B4nan** [comment]
There is a driver instance on the `Migration` class, so something like this should work:

```typescript
const res = await this.driver.execute('...');
```

But thinking about that now, it will probably not use the same transaction.

**Comment by sh84** [comment]
I try it:

> KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
>     at Client_MySQL2.acquireConnection (/app/node_modules/knex/lib/client.js:347:26

**Comment by B4nan** [comment]
Yeah thats the issue, migrations are executed with single connection in the pool. In next rc there is execute method that handles this.
