### ISSUE TITLE
Mssql support

### ISSUE THREAD

**Issue by rubiin** [mikro-orm/mikro-orm#771]
I think the orm should include mssql as a supported database type by default instead of doing a custom database setup

**Comment by B4nan** [comment]
there is some WIP here:

https://github.com/UTGuy/mikro-orm-mssql

Going forward I'd like to support it natively, although not a priority.

**Comment by rubiin** [comment]
> there is some WIP here:
> 
> https://github.com/UTGuy/mikro-orm-mssql
> 
> Going forward I'd like to support it natively, although not a priority.

I am actually starting out a new project in about two weeks later which is on mssql and wanted to use mikroorm instead of sequelize but I am not only the sole developer in the project so we are looking for sequelize alternative which supports mssql out of the box

**Comment by B4nan** [comment]
Will try to spend few hours to check how much is actually done and what is the needed effort to support it.

**Comment by rubiin** [comment]
@B4nan  any updates on this

**Comment by rubiin** [comment]
@B4nan any updates

**Comment by B4nan** [comment]
nope

https://blog.sindresorhus.com/issue-bumping-e3b9740e2a0

**Comment by B4nan** [comment]
I must say SQL server has very weird limitations. First I hit the issue with composite FKs that are sometimes impossible to create in a lazy manner due to SQL server trying to be too smart/strict (it does not allow setting cascading). Now I see `Cannot insert explicit value for identity column in table 'book_tag2' when IDENTITY_INSERT is set to OFF.` 🤷

Why are people using this? :P Seriously, go with postgres people :P 

Anyway, I have around 2/3 tests passing, disabled FKs in the schema generator for now, I know what to do to make it work (and it will also allow having FKs in sqlite at least for creating new tables). So still not there, still few days/weeks ahead of me.

**Comment by rubiin** [comment]
yes, Sql server is too smartass .I came up with those problems when i migrated from pg to mssql

**Comment by svantreeck** [comment]
Is this is still in progress?  Originally I think it was listed as an issue worth exploring in v5 (https://github.com/mikro-orm/mikro-orm/issues/1623), but its not listed there anymore.  Thanks!

**Comment by Langstra** [comment]
I believe B4nan worked on it in this MR https://github.com/mikro-orm/mikro-orm/pull/1375 guess you could have a look at it if you're interested?

**Comment by B4nan** [comment]
There is no progress, I don't consider this as something important, I gave it a try several times, but as for someone who never used mssql, the way that driver behaves is too much out of space to understand it. The blocker is schema generation and diffing, namely complex composite PKs and FK constraints, as that works differently than the rest of SQL drivers. 

As said, there is a WIP PR, feel free to give it a try yourself if it is important to you. 

If there would be some company willing to sponsor the driver development, that would be a different story.

**Comment by UTGuy** [comment]
I just recently updated those drivers. While schema generation is out of the question the driver does function perfectly fine. I also added a Unicode type to handle nvarchar columns.

**Comment by sauravyadav1958** [comment]
I cannot use Micro ORM because it does not support MS SQL

**Comment by B4nan** [comment]
FYI we are quite close to bringing this live. Last missing piece of puzzle is the schema diffing . 

With that said, it took a lot of time already for me as well as @UTGuy, so being close does not mean it will happen soon :]

Intereting idea with the bug bounty, it can definitely change the order of priorities. For me this was kind of a black hole for my spare time, so I usually favour issues I can deal with within hours and not weeks :D I think it would be fair to divide that somehow between me and @UTGuy once we finilize this.

**Comment by justinhenricks** [comment]
About to start a rather large project that relies on a SQL Server DB.. would love to use Mikro ORM, is this driver still a ways out from being pulled in?

**Comment by SteadEXE** [comment]
Any news about this?

**Comment by rubiin** [comment]
most other orms use `tedious` package to work with mssql maybe that would help

**Comment by ruscon** [comment]
Will be good to incapsulate tedious into mikro-orm. Is it possible?

**Comment by B4nan** [comment]
After many obstacles, #1375 is near the finish line and will be part of v6.2.

**Comment by ruscon** [comment]
@B4nan Great news, thanks. We are looking forward to testing it.
