### ISSUE TITLE
Custom validation on update

### ISSUE THREAD

**Issue by arvigeus** [mikro-orm/mikro-orm#776]
**Related**: #564

**Is your feature request related to a problem? Please describe.**
Documentation is lacking, and I cannot figure out a way how to check if the updated data is matching certain criteria.
*Example*: minValue and maxValue properties in entity; I want to check if maxValue is not less than minValue, etc. 

**Describe the solution you'd like**
A second parameter to onUpdate: `changed` that will contain the values updated.

```js
@Property({ onUpdate: (bar: FooBar, changed: unknown) => bar.minValue = Math.min(bar.maxValue, changed.minValue) })
```

**Describe alternatives you've considered**
Global validation per entity, instead of per property:

```js
@Entity({ onUpdate: (bar: FooBar, changed: unknown) => bar.minValue = Math.min(bar.maxValue, changed.minValue) })
```

**Comment by B4nan** [comment]
Use a hook, `onUpdate` on property decorator is not for validation, it's there to allow updating a value when an entity get's updated, like in `updatedAt: Date`.

**Comment by arvigeus** [comment]
Thanks, @B4nan , seems like what I am looking for. How to compare current / next snapshots (like in the case I described)?

**Comment by B4nan** [comment]
In latest versions of v4 you will get `EventArgs` as a parameter, where you also have access to the `changeSet` object:

https://mikro-orm.io/docs/next/lifecycle-hooks#eventargs 
https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/unit-of-work/ChangeSet.ts
