### ISSUE TITLE
Support for generating entities from a schema?

### ISSUE THREAD

**Issue by rex-remind101** [mikro-orm/mikro-orm#78]
Wondering if there's a way to generate Entities from a schema? This is important to our automation process.

**Comment by B4nan** [comment]
Currently no, but I am planning to add that feature soon (rather in weeks than in months).

**Comment by stephenh** [comment]
@B4nan great! I'll selfishly mention https://github.com/stephenh/ts-poet for your code generating pleasure. :-) 

(You can see https://github.com/stephenh/ts-proto/blob/master/src/main.ts for a non-toy example of usage, and then https://github.com/stephenh/ts-proto/blob/master/build/integration/simple.ts for the resulting output.)

(Obviously np if you have your own preferred approach/style/etc.)

**Comment by B4nan** [comment]
Closing as resolved. Available for testing via `next` tag.
