### ISSUE TITLE
Unexpected behaviour when referencing composite keys on pg.

### ISSUE THREAD

**Issue by thephoenixofthevoid** [mikro-orm/mikro-orm#782]
**Describe the bug**

Foreign key, referencing the composite PK, MUST be composite as well (in PostgreSQL 
or even most SQL engines at least), but instead Foreign Key constraints are created
for each part of key independently.

**Stack trace**
Not needed

**To Reproduce**

Consider the example: 
```ts
/***
 * @path entities/WhateverA.ts 
 **/
import { Entity, PrimaryKey, OneToMany, Collection, PrimaryKeyType } from 'mikro-orm';
import { WhateverB } from './WhateverB';

@Entity() class WhateverA {

    [PrimaryKeyType]: [string, string, string];

    @PrimaryKey() AA!: string;
    @PrimaryKey() BB!: string;
    @PrimaryKey() CC!: string;

    @OneToMany(() => WhateverB, r => r.parent) children = new Collection<WhateverB>(this);
}

export { WhateverA }

/***
 * @path entities/WhateverB.ts 
 **/
import { Entity, PrimaryKey, ManyToOne} from 'mikro-orm';
import { WhateverA } from './WhateverA';

@Entity() class WhateverB {
    @PrimaryKey() id: number;
    @ManyToOne() parent: WhateverA;
}

export { WhateverB }

/***
 * @path entities/index.ts 
 **/
import { WhateverB } from '../entities/WhateverB';
import { WhateverA } from '../entities/WhateverA';

// goes to entities in config
export default [ WhateverB, WhateverA ] 
```

Then I try to get SQL for updating my database:
```ts
...
const result = await generator.getUpdateSchemaSQL(false);
```
(In async context, don't write full code here for clarity)

Here is what I get:
```SQL
CREATE TABLE "whatever_b" (
    "id" serial PRIMARY KEY,
    "parent_aa" varchar(255) NOT NULL,
    "parent_bb" varchar(255) NOT NULL,
    "parent_cc" varchar(255) NOT NULL
);

CREATE INDEX "whatever_b_parent_aa_parent_bb_parent_cc_index" ON "whatever_b" ("parent_aa", "parent_bb", "parent_cc");

CREATE TABLE "whatever_a" (
    "aa" varchar(255) NOT NULL,
    "bb" varchar(255) NOT NULL,
    "cc" varchar(255) NOT NULL
);

CREATE INDEX "whatever_a_aa_index" ON "whatever_a" ("aa");
CREATE INDEX "whatever_a_bb_index" ON "whatever_a" ("bb");
CREATE INDEX "whatever_a_cc_index" ON "whatever_a" ("cc");

ALTER TABLE "whatever_a" ADD CONSTRAINT "whatever_a_pkey" PRIMARY KEY ("aa", "bb", "cc");

ALTER TABLE "whatever_b" ADD CONSTRAINT "whatever_b_parent_aa_foreign" FOREIGN KEY ("parent_aa") REFERENCES "whatever_a" ("aa") ON UPDATE CASCADE;
ALTER TABLE "whatever_b" ADD CONSTRAINT "whatever_b_parent_bb_foreign" FOREIGN KEY ("parent_bb") REFERENCES "whatever_a" ("bb") ON UPDATE CASCADE;
ALTER TABLE "whatever_b" ADD CONSTRAINT "whatever_b_parent_cc_foreign" FOREIGN KEY ("parent_cc") REFERENCES "whatever_a" ("cc") ON UPDATE CASCADE;
```
(I use sql-formatter-plus to get nice looking code here, it touches only casing and white-spaces)

Every part of a key gets its own CONSTRAINT, however here is what pg said:

```
alter table "whatever_b" add constraint "whatever_b_parent_aa_foreign" foreign key ("parent_aa") references "whatever_a" ("aa") on update cascade; 
- there is no unique constraint matching given keys for referenced table "whatever_a"
```

There are no unique constraints matching separate parts of the key in the referenced table, thus we cannot add FOREIGN KEY this way. Enforcing UNIQUE constraint on each part would get rid of the error, but not only is incorrect, it is also making pointless using of 
composite key here.

**Expected behavior**

This is correct behaviour and works:
```SQL
CREATE TABLE "whatever_b" (
    "id" serial PRIMARY KEY,
    "parent_aa" varchar(255) NOT NULL,
    "parent_bb" varchar(255) NOT NULL,
    "parent_cc" varchar(255) NOT NULL
);

CREATE INDEX "whatever_b_parent_aa_parent_bb_parent_cc_index" ON "whatever_b" ("parent_aa", "parent_bb", "parent_cc");

CREATE TABLE "whatever_a" (
    "aa" varchar(255) NOT NULL,
    "bb" varchar(255) NOT NULL,
    "cc" varchar(255) NOT NULL
);

CREATE INDEX "whatever_a_aa_index" ON "whatever_a" ("aa");
CREATE INDEX "whatever_a_bb_index" ON "whatever_a" ("bb");
CREATE INDEX "whatever_a_cc_index" ON "whatever_a" ("cc");

ALTER TABLE "whatever_a" ADD  CONSTRAINT "whatever_a_pkey" PRIMARY KEY ("aa", "bb", "cc");

ALTER TABLE "whatever_b" ADD
    CONSTRAINT "whatever_b_parent_aa_parent_bb_parent_cc_foreign" 
    FOREIGN KEY ("parent_aa", "parent_bb", "parent_cc")
    REFERENCES "whatever_a" ("aa", "bb", "cc");
```

**Additional context**

I managed to fix (or workaround) this issue by changing this method:
https://github.com/mikro-orm/mikro-orm/blob/75b407066f61f147637440f5423405a12aaea50c/lib/schema/SchemaGenerator.ts#L433-L452

My code:
```ts
  private createForeignKeyReference(table: TableBuilder, prop: EntityProperty): void {
    table.foreign(prop.fieldNames)
         .references(prop.referencedColumnNames)
         .inTable(prop.referencedTableName);
  }
```

After the change the behaviour matches the expected. I can make PR, but I wonder if the original implementation is required for any case that I am not aware of: like different database driver / metadata provider or whatever? 

**Versions**

| Dependency | Version |
| - | - |
| node | v14.6.0 |
| typescript | 3.9.7 |
| mikro-orm | "3.6.15" |
| pg | 8.3.0 |

**Comment by B4nan** [comment]
This should be already fixed in v4.

**Comment by B4nan** [comment]
Yes, it is fixed, here is the actual code:

https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/schema/SchemaGenerator.ts

So upgrade to v4, no plans to backport things at this stage, will be shipping the final soon.

**Comment by thephoenixofthevoid** [comment]
But v4 is unstable and I cannot use it in production. Backporting this fix to the stable version would be great.

PS: Today I tried v4 and got here:
https://github.com/mikro-orm/mikro-orm/blob/d83c6a14e8ce2b9b663056efc1dd9b7cb45c122a/packages/knex/src/AbstractSqlConnection.ts#L105
the error message that isEnabled is not a function. I suppose it's related to having already using knex, which is not your fork and which NPM used to resolve mikro-orm's dependency.

**Comment by B4nan** [comment]
V4 is stable, I am using it in production for more than a month without any issues. 

I am quite sure you just 1. did not use the latest version (which is `4.0.0-rc.4`), and 2. did not follow the migration guide. Also you should not install knex yourself (and no, there is no "my fork of knex").

**Comment by thephoenixofthevoid** [comment]
1. I didn't needed to migrate, because I didn't have preexisting version. The version were rc4, installed as "next".
2. Knex is an preexisting direct dependency of one of modules of mine. And that's not uncommon situation: it's a popular package and using it directly and in isolation should not lead to crashes. It's rather a dependency resolution issue.

But I got it. Have to "package-patch" it until someday.

**Comment by B4nan** [comment]
I don't even think this is about knex (btw it is reexported from the `@mikro-orm/knex` so you can use it directly, no need to install your own). 

If that line thrown error about `isEnabled` not existing, it means that you had version mismatch in the ORM packages. As the `Logger` comes from `core` package, it has nothing to do with knex. All the package versions need to be aligned.

**Comment by thephoenixofthevoid** [comment]
You may want to check out the concept of peerDependencies. NPM decides on which version to install and link in a very complicated manner and does not provide a clear way to align versions to end user. But provides developers with such. You may want to check React or Babel monorepos as examples how to set it up.

**Comment by merceyz** [comment]
The packages already declare the core as a peer dependency, they also get the knex version correctly so the one you have installed is irrelevant.

I see in your example you're importing from `mikro-orm` you should be importing from `@mikro-orm/core`

**Comment by thephoenixofthevoid** [comment]
By the way, according to 
https://github.com/knex/knex/blob/2ffa7784d8a5444ac740d69bf7b619b33259b37d/lib/knex.js#L27
Knex supports accepting classes as dialects, so instead of monkey patching (and God knows affecting how many unrelated code), you may just inherit from PostgresClient and do string to class replacement by yourself.
