### ISSUE TITLE
Entity relations are not serialized properly when calling `toJSON` on flushed entities after being created with EntityRepository.create

### ISSUE THREAD

**Issue by charmpitz** [mikro-orm/mikro-orm#784]
**Describe the bug**
When using `toJSON` on an Entity after it is being created, persisted and flushed via the `create` and `persistAndFlush` methods on the specific repository, its related entities are not being serialized properly. Instead of getting the result of `toJSON` being called on them we get a number representing their id.

**Stack trace**
```js
function create(input) {
    ...

    let articleEntity: ArticleEntity = this.articleRepository.create({
        ...input,
        user: userEntity,
        tags,
    });

    await this.articleRepository.persistAndFlush(articleEntity);
    console.log(articleEntity.toJSON())
    /* Wrong Output:
    {
        id: 9,
        title: 'Some Article',
        tags: [ 1 ],
        user: 1
    }
    */

    articleEntity = await this.articleRepository.findOne(articleEntity.id)
    console.log(articleEntity.toJSON())
    /* Right Output:
    {
        id: 9,
        title: 'Some Article',
        tags: [
            {
                id: 1,
                name: 'tag1',
                user: [Object],
                ...
            }
        ],
        user: {
            id: 1
            username: 'someusername'
            ...
        }
    }
    */

    return articleEntity.toJSON() as Article;
}
```

**To Reproduce**
See above.

**Expected behavior**
I'm expecting for the `articleEntity.toJSON()` to return 
```js
    {
        id: 9,
        title: 'Some Article',
        tags: [
            {
                id: 1,
                name: 'tag1',
                user: [Object],
                ...
            }
        ],
        user: {
            id: 1,
            username: 'someusername',
            ...
        }
    }
```
without the need of calling `findOne` after flushing.

**Additional context**
-

**Versions**

| Dependency | Version |
| - | - |
| node | 14.7.0 |
| @mikro-orm/cli | ^4.0.0-rc.4 |
| @mikro-orm/core | ^4.0.0-rc.4 |
| @mikro-orm/migrations | ^4.0.0-rc.4 |
| @mikro-orm/nestjs | ^4.0.0-alpha.3 |
| @mikro-orm/postgresql | ^4.0.0-rc.4 |
| @mikro-orm/reflection | ^4.0.0-rc.4 |
| typescript | ^3.7.4 |

**Comment by B4nan** [comment]
This is actually quite huge breaking change, so will make this hidden behind a config toggle, keeping the default behaviour as is.

**Comment by B4nan** [comment]
In `rc.6` you can set `populateAfterFlush: true` to enable this behaviour.

**Comment by B4nan** [comment]
The default will change to true in v5
