### ISSUE TITLE
Ability to get information on pivot table inserts/removals from subscribers

### ISSUE THREAD

**Issue by TiesB** [mikro-orm/mikro-orm#788]
First of all, thanks a million for the amazing work! This is more of a question than a feature request, but it could maybe turn into a feature request. It's also highly possible we're missing something.

**Is your feature request related to a problem? Please describe.**
In our application we need to log changes that are made to entities. We currently use the changeSet.payload we get from afterCreate/Update/Delete methods from the EventSubscriber to do so. However, inserts/removals in the pivot table for a M:N relation are not given in this changeSet.

**Describe the solution you'd like**
We'd like a way to get information on inserts/removals from pivot tables through a subscriber.

**Describe alternatives you've considered**
We looked at the upcoming on/afterFlush methods, and tried to get the information from the uow, but could not find a way to do so.

**Comment by B4nan** [comment]
Collection updates are done separately, they are basically removed from the entity change sets, so the payload is only about what will be changed in the db table for that entity. I see there is no getter for `collectionUpdates`, so I can add that for sure, if you are fine with using flush events for this. 

It is basically an array of all dirty collections, each collection has `getSnapshot()` method to obtain copy of the items array that should represent the current state in database, then in the commit phase this is diffed with `getItems()`.

**Comment by TiesB** [comment]
Understandable, and I think the committed change is a nice addition. Flush events should be fine for us as well.

Thanks so much again for the help and the work!

**Comment by TiesB** [comment]
One thing we're running into is that from the collectionUpdates, we can't find which relation the collection belongs to. E.g., if we find a collection with Users, and User has M:N relations with both Project and Organization, we don't know which one it was.

Do you maybe know a possible solution/workaround for this?

**Comment by B4nan** [comment]
There is `Collection.owner` which is the owning entity.

**Comment by TiesB** [comment]
You're our hero. Thanks so much!
