### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by davingreen** [mikro-orm/mikro-orm#789]
The slack link is broken. Can I recommend creating a Discord instead?

Been following your alternative to TypeORM. Looks great so far -- I wanted to chat with others using it!

**Comment by B4nan** [comment]
Right, I totally forgot about the link there. Slack is active, there are new people joining thru the link pretty much everyday, here is the correct one (can be found on the README and HP):

https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA
