### ISSUE TITLE
migration:create: optional property (marked with ?) doesn't result in a nullable column

### ISSUE THREAD

**Issue by plashenkov** [mikro-orm/mikro-orm#793]
Hi!

**Describe the bug**

For some reason, when I create an optional property and then run `migration:create`, the generated migration contains `not null` column. I'm using MySQL.

Here is an example entity:

```ts
@Entity()
export class User {
  @PrimaryKey()
  public id: number

  @Property()
  private someProp?: string
}
```

Here is my `mikro-orm.config.js`:

```ts
const {User} = require('./src/entities/User')

module.exports = {
  type: 'mysql',
  clientUrl: process.env.DATABASE_URL,
  entities: [User],
  discovery: {disableDynamicFileAccess: true},
  migrations: {
    path: './src/migrations',
  }
}
```

Now let's run `mikro-orm migration:create` (the full command is: `ts-node -T -r tsconfig-paths/register -r dotenv-flow/config ./node_modules/.bin/mikro-orm migration:create`). This is what we get as a result:

```sql
create table `user` (
  `id` int unsigned not null auto_increment primary key,
  `some_prop` varchar(255) not null
) default character set utf8mb4 engine = InnoDB;
```

If I manually add `@Property({nullable: true})` to this optional property then the generated column _will be_ marked as null. But I would like to avoid redundancy. The docs say (https://mikro-orm.io/docs/defining-entities#optional-properties):

> When you define the property as optional (marked with ?), this will be automatically considered as nullable property

**To Reproduce**

I hope the above explanation is sufficient :)

**Expected behavior**

Optional property should result in a nullable column.

**Versions**

| Dependency | Version |
| node | 14.5.0 |
| ts-node | 8.10.2 |
| typescript | 3.9.7 |
| mikro-orm | 3.6.15 |
| your-driver | mysql2 2.1.0 |

**Comment by B4nan** [comment]
What metadata provider are you using? This works only with ts-morph.

**Comment by plashenkov** [comment]
> What metadata provider are you using? This works only with ts-morph.

I really don't know, I didn't configure anything special.
I simply use the following options in `tsconfig.json` and that's all:

```json
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  }
}
```

---

> Also why are you using disableDynamicFileAccess?

Because otherwise MikroORM throws an error when I try to run `migration:create` command:

```
ValidationError: Entity 'any' entity was not discovered, please make sure to provide it in 'entities' array when initializing the ORM
```

I have two entities: User and Account, and Account has this column:

```
@ManyToOne()
user: User
```

I provide Account as well as User into MikroORM config `entities` array, but I get the above error without disableDynamicFileAccess.

**Comment by B4nan** [comment]
By doing that, reflect metadata provider is used. And that one does not support this feature, as there is no information on optionallity provided by reflect metadata.

**Comment by B4nan** [comment]
Read the limitations of reflect metadata here:

https://mikro-orm.io/docs/metadata-providers#limitations-and-requirements

**Comment by plashenkov** [comment]
I also had problems with enum properties, they were not generated correctly until I specified explicitly:
```ts
@Enum(() => SomeEnumProp)
```

Yup, I confirm that removing disableDynamicFileAccess fixes things. But what to do with the error above?

```
ValidationError: Entity 'any' entity was not discovered, please make sure to provide it in 'entities' array when initializing the ORM
```

**Comment by B4nan** [comment]
It means that some type was not inferable - this comes from TS, usually because of circular dependencies between entities. You will need to find which property is causing it and specify the type explicitly. 

In v4 the error is more explanatory, giving you the property name where it originated. In v3 you could log this information yourself (put the console.log to the ORM code in node_modules, inside `MetadataValidator.validateDiscovered()` where this error is thrown.

**Comment by plashenkov** [comment]
I've found another reason why I added disableDynamicFileAccess: when I build and run built app with node, I get:

```
UnhandledPromiseRejectionWarning: Error: Source file for entity /server.ts not found, check your 'entitiesDirsTs' option. If you are using webpack, see https://bit.ly/35pPDNn
```

And following the link I've found that I should add this option (in prod mode there is no TS at all, so...)

The problem is that this metadata stuff looks too complicated for those who just want to use decorators without digging into how all this black magic works internally.

**Comment by B4nan** [comment]
> And following the link I've found that I should add this option (in prod mode there is no TS at all, so...)

If you use ts-morph, then you use the TS source files and TS compiler api in production too. In v3 you need to ship your `.ts` files, in v4 `.d.ts` files are used instead. If you don't want to use this way, then reflect metadata provider is what you want. But then you need to respect all its limitations, as written in the docs.

**Comment by B4nan** [comment]
> The problem is that this metadata stuff looks too complicated for those who just want to use decorators without digging into how all this black magic works internally.

As I said, use reflect metadata provider if you don't like this "black magic". But then you can't expect the features of ts-morph to work, so you will need to explicitly define all types in relation decorators, all nullables, all enums, ...

Again, read the docs: 

https://mikro-orm.io/docs/metadata-providers/#limitations-and-requirements

**Comment by plashenkov** [comment]
Thank you for your help!

**Comment by plashenkov** [comment]
> As I said, use reflect metadata provider if you don't like this "black magic".

It's not that I don't like it. On the contrary, I would like to use this more smart feature.
I mean that the problem is that I try to configure MikroORM by following the docs but it turns out that everything is more complex, and docs about configuration (Overview, Fundamentals) are not sufficient. Some necessary info is in "advanced" category.

> If you use ts-morph, then you use the TS source files and TS compiler api in production too.

For example, I saw nothing about it in the docs about configuring. Maybe this info should be added to the basic docs?

**Comment by plashenkov** [comment]
Ah, nope, I can see it here: https://mikro-orm.io/docs/installation/#entity-discovery-in-typescript
My bad.
Thanks again
