### ISSUE TITLE
Escaping values in migrations

### ISSUE THREAD

**Issue by pigulla** [mikro-orm/mikro-orm#799]
**Is your feature request related to a problem? Please describe.**
When writing migrations, it is not clear how the queries can be constructed safely. While a migration obviously does not contain user input and escaping might not be strictly necessary, it is arguably good form to do so anyway.

**Describe the solution you'd like**
Provide a built-in solution to escape values. Ideally the `knex` instance could be used but it is my understanding that this is not feasible due to its lack of support for MongoDB.

**Describe alternatives you've considered**
Currently I am using [pg-format](https://www.npmjs.com/package/pg-format) which works well enough, but that means tying my migrations to a specific database, which is not ideal.

**Additional context**
I've read [this issue]([https://github.com/mikro-orm/mikro-orm/issues/770) which asks a related question.

**Comment by B4nan** [comment]
In `Migration` class you have access to the `AbstractSqlDriver` (via `this.driver`), where you can either use the MikroORM query builder, or get the configured knex instance via `this.driver.getConnection().getKnex()`.

**Comment by pigulla** [comment]
Thanks for the super quick reply.

It is my understanding that the Knex instance can not be used until the next RC (as mentioned [here](https://github.com/mikro-orm/mikro-orm/issues/770#issuecomment-679840890)) - is that correct?

When playing around with this `this.driver.getConnection` threw `TypeError: this.driver.getConnection is not a function` during runtime, but that's most likely due to me not using the latest RC (my bad). Now I ran into the escaya issue, but I will just hold still until RC5 is out :)

Thanks a lot for your work, looking forward to using it!

**Comment by B4nan** [comment]
> It is my understanding that the Knex instance can not be used until the next RC (as mentioned here) - is that correct?

That is only if you want to execute a query, not if you use it to build a query for `this.addSql()`.

**Comment by pigulla** [comment]
How do I do that? As far as I know Knex'  `toSQL()` or (`toSQL().toNative()`) returns the statement and its (unescaped) bindings as separate values so it is not a query I can pass to `addSql`.

**Comment by B4nan** [comment]
You could use `toString()`, and we could easily allow passing params to `addSql()` too I guess.

**Comment by pigulla** [comment]
Maybe I just need some more coffee, but I don't think this is how Knex works:

```
knex
    .insert({
        id: 42,
        foo: 'bar',
    })
    .into('mytable')
    .toSQL()
    .toNative() // or without this, no difference
    .toString()
```
just returns `[object Object]`. Apparently there are only [pretty ugly workarounds](https://github.com/knex/knex/issues/619) for this (admittedly, an old ticket - couldn't find anything more recent regarding this issue).

**Comment by B4nan** [comment]
```
knex
    .insert({
        id: 42,
        foo: 'bar',
    })
    .into('mytable')
    .toString()
```

**Comment by B4nan** [comment]
But we could easily allow to pass the knex qb instance to `addSql()` too. I feel like the `toString()` method is more of an approximation - I am using that in the query logging and I know about some differences when it comes to object handling (`Date`s in particular are printed with lower precision, without timezone, and in sqlite it prints the date string while in fact the query is using int/timestamps under the hood (that is how sqlite3 does things internally afaik).

So I would definitely not suggest to do this. Personally I would just write the SQL myself, it's easier and you have absolute control over everything.

**Comment by pigulla** [comment]
I'm fine with that, if that's the "official" way to do this. Thanks for the feedback!

**Comment by B4nan** [comment]
`rc.5` will allow to use knex in both `execute` and `addSql` methods, there is also a new shortcut to get knex.

**Comment by pigulla** [comment]
Fantastic!

Do you have an ETA for rc.5 by any chance?
