### ISSUE TITLE
Select with function in where condition

### ISSUE THREAD

**Issue by travigd** [mikro-orm/mikro-orm#802]
**Is your feature request related to a problem? Please describe.**
I'd like some way to query using a function as part of the where condition. Concretely, I have a unique index on `UPPER(payload)` for some table where the payload is case-insensitive, and I want to query using `WHERE UPPER(payload) = UPPER($1)` (obviously, the `UPPER($1)` can be done in the client side, so that's less of an issue here).

**Describe the solution you'd like**
Unclear what the API would be. 

**Describe alternatives you've considered**
There is a querybuilder way of doing this, but it's not what I'm looking for here.
https://github.com/mikro-orm/mikro-orm/blob/bfbc5f8df4c6b541983dfefb75467be5dc3b8901/tests/QueryBuilder.test.ts#L307-L311

**Additional context**
Add any other context about the feature request here.

**Comment by B4nan** [comment]
You can do the same with EM api, you just need to type cast as this dynamic key won't pass the strict `FilterQuery` type. 

```typescript
em.find(Book, { 'json_contains(`e0`.`meta`, ?)': [{ foo: 'bar' }] } as any);
```

**Comment by B4nan** [comment]
We could also have something like `expr` helper, that could allow doing this I guess:

```ts
const author = new Author2('name', 'email');
const b1 = new Book2('b1', author);
const b2 = new Book2('b2', author);
const b3 = new Book2('b3', author);
await orm.em.persistAndFlush([b1, b2, b3]);
orm.em.clear();

const expr: <T> (sql: string) => keyof T = sql => sql as any;
const books = await orm.em.find(Book2, { [expr('upper(title)')]: ['B1', 'B2'] }); // no TS errors
expect(books).toHaveLength(2);
```

(this test is passing with current version, so you can define such `expr` helper yourself right now)

WDYT?

**Comment by B4nan** [comment]
In `rc.6` it will be possible to do this:

```ts
const books = await em.find(Book, {
  [expr('upper(title)')]: em.getKnex().raw('upper(?)', ['b2']),
});
```

**Comment by danitrod** [comment]
I was facing this and managed to work around by creating a RegExp to query and match the case insensitive value. Don't know if it helps for your case, but here it is:
```ts
const caseInsensitive = (str: String): RegExp => {
  const len = str.length;
  let stream = '';
  for (let i = 0; i < len; i++) {
    stream += '[' + str[i].toLowerCase() + str[i].toUpperCase() + ']';
  }
  return new RegExp(stream);
};

const rx = caseInsensitive(title);
const book = await em.findOne(Book, { title: rx });

```

**Comment by KevinNovak** [comment]
@danitrod If you want to find a case insensitive value you can just use a `RegExp` with the `'i'` flag like so:
```typescript
const book = await em.findOne(Book, {
    title: new RegExp(title, 'i'),
});
```
Also make sure to escape any regex characters if that `title` string is coming from the user:
```typescript
title = title.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, '\\$&');
```
Hope this helps someone in the future!
