### ISSUE TITLE
escaya@0.0.23 dependency is not a valid escaya version

### ISSUE THREAD

**Issue by iDavidB** [mikro-orm/mikro-orm#804]
**Describe the bug**
Mikro-orm/core depends on [escaya](https://www.npmjs.com/package/escaya) version 0.0.23. But that version does not exist, at least not on NPM.

**Stack trace**
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for escaya@^0.0.23.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@mikro-orm/core'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/david/.npm/_logs/2020-09-02T15_02_29_518Z-debug.log
```

**To Reproduce**
Not quite sure, as it seems to work on Linux and Mac OS. However, it does not work on Windows or CentOS 7.
Easiest way to achieve getting the error above is by attempting to install escaya yourself in a project that uses RC4.
`npm i -D escaya`

**Expected behavior**
For people to be able to run `npm install`

**Versions**

| Dependency | Version |
| - | - |
| node | 12.18 |
| typescript | 4.0.2 |
| mikro-orm | 4.0.0-rc.4 |

**Comment by B4nan** [comment]
Already fixed, new rc will be shipped within an hour or so.

**Comment by merceyz** [comment]
cc @KFlash

**Comment by KFlash** [comment]
@merceyz What's up? v. 0.0.23 had a bug causing it to run into infinite loop in recovery mode so I removed it from NPM. 

v. 0.0.28 latest working version. Consider that version as stable and almost done when it comes to parsing and recovery mode.

**Comment by B4nan** [comment]
Perfect, `rc.5` now uses `v0.0.28`
