### ISSUE TITLE
Entity property config relationship for hiding entity but outputting id

### ISSUE THREAD

**Issue by Langstra** [mikro-orm/mikro-orm#809]
**Is your feature request related to a problem? Please describe.**
I have a schema where entity A has relationships to B many C's many D's, C has many E's. Now when I return B, it calls toJson function. Since B also has the reverse relation to A, relation A is also outputted, and A then loads B, C and D. This gives me a call stack size exceeded (so maybe I should also file a bug report for this?). However, I'd like to use `{hidden: true}` on entity B for its relation to A, this hides entity A on B. Now I would like to have property a_id on entitiy B when outputting. This way someone using my API does know that entity B has a relation with entity A.

**Describe the solution you'd like**
A configuration property like `showId: boolean`, that when set to true outputs the id of the relationship.

Example: 
A book has an author and an author has many books. When outputting with showId true, a book has a property called authorId and when outputting an author it has a property bookIds.

A different approach could be to have a configuration property showId: string which lets the user specify how the property should be named and when being unset/undefined that the id or id array is not outputted.

**Describe alternatives you've considered**
Currently I am using the hidden property and overriding the toJson method to insert the authorId property myself.

**Comment by B4nan** [comment]
In general, abstracting the serialization is very complex thing, there is no silver bullet to this other than implementing custom `toJSON` method. 

I don't really understand the problem yet (and I don't think adding another boolean flag would solve it), the PK should always be there on the owning sides, as well as on initialized collections. Can you provide some code that demonstrates the issue?

> A book has an author and an author has many books. When outputting with showId true, a book has a property called authorId and when outputting an author it has a property bookIds.

This is already working, Book.author is the owning side (m:1), it will always be part of the output, either the full entity or just the PK.

**Comment by Langstra** [comment]
I will try to create an example repository.

I understand that the PK is always there, but there is no option to choose to always output the PK instead of the full entity. I'd like to output always the PK instead of the full entity, even if it is available in the entity map.

**Comment by B4nan** [comment]
There actually is an option for that, not on the entity definition level, it works automatically based on the populate params. Entity can be marked as populated via `wrap(e).populated()` (and unmarked with a false param).

```ts
const a = await em.findOne(Author, 1, ['favouriteBook']);
console.log(a.toJSON()); // favouriteBook was populated explicitly, so will be full entity
wrap(a.favouriteBook).populated(false);
console.log(a.toJSON()); // favouriteBook was unpopulated, so will be just the PK
```

**Comment by Langstra** [comment]
I guess you are right that this type of behavior should be done at controller (output) level. However, maybe you could add support for adding the relation ID as a property on the entity. That way you can either choose to use 'author' or authorId'.

**Comment by B4nan** [comment]
You can already do that via virtual properties, if it's just about controlling the JSON output (but I would still prefer using custom `toJSON()` method). Something like this should work:

```ts
class Book {

  @ManyToOne({ hidden: true })
  author: Author;

  @Property({ name: 'author_id', persist: false })
  get authorId() {
    return this.author.id;
  }

}
```

But yeah, why not, we can make this easier. Will add `serializer` and `serializedName` to PropertyOptions, so you can do this instead:


```ts
class Book {

  @ManyToOne({ serializedName: 'author_id', serializer: a => a.id })
  author: Author;

}
```
