### ISSUE TITLE
Add support for $contains operator with array of values

### ISSUE THREAD

**Issue by charmpitz** [mikro-orm/mikro-orm#812]
**Is your feature request related to a problem? Please describe.**
I would like to be able to filter by tags in a list of articles.

**Describe the solution you'd like**
Having the `article` and `tag` entities I should be able to call `find` on the article repository with:
```js
{
    tags: { name: { $contains: ['tag1', 'tag2'] } }
}
```
and receive only the articles that contain both of these tags.

**Describe alternatives you've considered**
The only solution I see right now is using the knex query builder which I would like to avoid, after all I think it would be good for the library to support this functionality.

**Comment by B4nan** [comment]
$contains is already there (pg only, not sure what driver you are using)

**Comment by charmpitz** [comment]
I'm using `postgresql` but the typings say that the value that can be used is only `string` not `string[]` in https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/typings.ts#L50

**Comment by charmpitz** [comment]
Also it seems that there is an error when calling with the following arguments:
```js
{
   tags: {
       name: { $contains: "tag1" }
   }
}
```
It gets transformed into:
```sql
select "e0".* from "public"."article" as "e0" 
left join "public"."article_tag" as "e2" on "e0"."id" = "e2"."article_id" 
left join "public"."tag" as "e1" on "e2"."tag_id" = "e1"."id" 
where "e1"."name" @> 'tag1' 
```
and he database throws the following error:
```
operator does not exist: character varying @> unknown
graphql_1     |     at PostgreSqlExceptionConverter.convertException (/app/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
graphql_1     |     at PostgreSqlExceptionConverter.convertException (/app/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:40:22)
graphql_1     |     at PostgreSqlDriver.convertException (/app/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:167:54)
graphql_1     |     at /app/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:171:24
graphql_1     |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
graphql_1     |     at PostgreSqlDriver.find (/app/node_modules/@mikro-orm/postgresql/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:43:24)
graphql_1     |     at SqlEntityManager.find (/app/node_modules/@mikro-orm/core/EntityManager.js:72:25)
graphql_1     |     at async Promise.all (index 0)
graphql_1     |     at SqlEntityManager.findAndCount (/app/node_modules/@mikro-orm/core/EntityManager.js:136:35)
graphql_1     |     at BookmarkService.find (/app/src/graphql/services/abstract.listing.service.ts:74:40)
```

**Comment by charmpitz** [comment]
I think it is because of the single quotes conversion `'tag1'` instead of `"tag1"` although even with the latter I get 
```SQL Error [42703]: ERROR: column "tag1" does not exist```. Also I think the implementation should be different especially if we want to support array of strings.

**Comment by B4nan** [comment]
> I think it is because of the single quotes conversion 'tag1' instead of "tag1"

Single quotes are for values (strings), this is actually correct. This is handled by knex, not MikroORM. Looking at the postgres docs, the operator is probably only for array vs array, not array vs string, and definitely not for string vs string. 

What query are you trying to build? I see you are using the operator on `name`, that is hardly an array, right? I can replicate that error when trying to use the operator on string, which is simply not supported by postgres. Maybe you want `$in` instead?

Also tried to use it with array and string, not working (but the error is different) - again, its postgres complaining, its not an ORM issue, its simply not possible (the operator is not designed for that).

**Comment by B4nan** [comment]
With the changes done in 831ca47, `$contains` now expects array of strings, and the internals are adjusted so it also works with the `ArrayType` (that is automatically used for array types as long as the ORM understands the array type from metadata).

As I mentioned above, I believe you actually want to use `$in` (if you want to compare string property with array of strings), but the $contains operator should be now fixed as well (still - it will work only with array properties comparing to arrays - that is how postgres is working).

**Comment by charmpitz** [comment]
Given that `mikro-orm` is an abstraction over the database I hoped the `$contains` would act like the `$all` operator in Mongo (https://docs.mongodb.com/manual/reference/operator/query/all/) when using the `tag`.`name` property to filter all articles that contain all those tags that have the specified names.

I understand how it would be more difficult to implement (would probably have to use `array(tag.name)` and `GROUP BY article.id` in order to create the array that contains all those values and then apply the `@>`/`$contains` operator on them), however this is the behavior I was expecting. 

Unfortunately the `$in` operator is used to check if at least one of those values exists inside.

How would you solve this without having to make the `article`.`tags` property an array column inside PostgreSQL and keeping the `tag` table (using it as an entity with a relationship of ManyTotMany to `article`)?

I would solve this in SQL with a query similar to
```sql
select a.* from "schema"."article" as a 
join
	(select a_t.article_id, array_agg(t.name)::text[] as tags_arr from "schema"."article_tag" as a_t
		join "schema"."tag" t on a_t.tag_id = t.id
	group by a_t.article_id) as f on a.id = f.article_id
where f.tags_arr @> array['tag1', 'tag2']
```
but I'm not sure I can do this with the EntityRepository.
