### ISSUE TITLE
Chain `init` from a `WrappedEntity` in v4

### ISSUE THREAD

**Issue by maphe** [mikro-orm/mikro-orm#814]
**Is your feature request related to a problem? Please describe.**
With v3 it was possible to init a reference/collection and chain init references/collections to that object.
Eg.
```ts
await wrap(parent).init(['children', 'grandchildren'])
```
Now the init function seems to only take a boolean as its first param. The migration run book is also not very helpful on that.

**Describe the solution you'd like**
Either have the list to populate back as a param, or any alternative would be appreciated.

**Describe alternatives you've considered**
As is, I feel obliged to do something like
```ts
await wrap(parent).init();
await wrap(parent.children).init();
for (const child of parent.children) {
  await wrap(child.grandchildren).init();
}
```

**Comment by B4nan** [comment]
Interesting. You could always use `em.populate()`:

```ts
// the parent here should be loaded, so you might want to use its parent entity
await em.populate(parent, ['children', 'grandchildren']);
```

**Comment by B4nan** [comment]
Not sure what makes you think something changed. In v3 the signature was the very same as in v4, maybe you had the `Collection.init()` in mind? As there we have populate parameter. 

https://github.com/mikro-orm/mikro-orm/blob/v3.6.15/lib/typings.ts#L71

**Comment by maphe** [comment]
Thanks. It seems to work better when I don't wrap the collection, so maybe the difference comes from the `wrap()` function rather than the `init()`.

Using v3 I had something like:
```ts
wrap(parent.children).init(['grandchidren']);
```
It was working ok, but now migrating to v4 I'm forced to change it to:
```ts
parent.children.init(['grandchidren']);
```
Which might be a good thing actually, I'm not quite sure.

**Comment by B4nan** [comment]
Yeah, wapping collections is no longer supported, there was never need for that, it was allowed only for internal usage (but that is no longer needed).

**Comment by maphe** [comment]
Ok cool, makes more sense now. Thank you.
