### ISSUE TITLE
EAV Container Feature in MikroORM

### ISSUE THREAD

**Issue by totalard** [mikro-orm/mikro-orm#817]
**Is your feature request related to a problem? Please describe.**
It is One of the important feature for a ORM, It make Mikro Much better and more useful

**Describe the solution you'd like**
Check the Link https://fuelphp.com/docs/packages/orm/eav.html , it implement the feature

**Describe alternatives you've considered**
https://fuelphp.com/docs/packages/orm/eav.html

**Additional context**
https://fuelphp.com/docs/packages/orm/eav.html

The Link Gives Much information of the feature

**Comment by B4nan** [comment]
No plans to support this natively. But you should be able to model your entities in this fashion in v4, this SO post is about doctrine but the features are same here (in v4):

https://stackoverflow.com/questions/14123953/doctrine-orm-on-eav-tables

Tagging @stalniy, as I know he was talking about EAV in the early days of MikroORM.

**Comment by stalniy** [comment]
From my experience the best way to work with EAV is by writing own project specific ORM. Which can take into consideration all project specific nuances and can apply optimizations where needed. 

But from what I saw in mikro orm it should be quite easy to implement this on top. I’ve never tried though
