### ISSUE TITLE
Transaction isolation levels

### ISSUE THREAD

**Issue by DanTsk** [mikro-orm/mikro-orm#819]
Hello! I need to run a `Serializable` Transaction. 
How I can achieve it with Mikro-ORM?

**Comment by B4nan** [comment]
Depends on the driver, knex does not support this unfortunately. Afaik with postgres it is possible to just fire a query inside explicit transaction to set the isolation level, but it wont work with mysql.

**Comment by B4nan** [comment]
Related issue in knex repository: 

https://github.com/knex/knex/issues/581

For postgres, this should be the way:

```ts
await em.transactional(em2 => {
  await em2.execute('SET TRANSACTION ISOLATION LEVEL SERIALIZABLE');
  // ...
})
```

**Comment by B4nan** [comment]
as this is finally unblocked by knex, v5 will allow doing this:

```ts
await orm.em.transactional(async em => {
  // ...
}, { isolationLevel: IsolationLevel.READ_UNCOMMITTED });
```
