### ISSUE TITLE
Can't access discriminator value on mapped type

### ISSUE THREAD

**Issue by jshearer** [mikro-orm/mikro-orm#827]
**Describe the bug**
I'm trying to access the discriminator value for a type using single-table-inheritance, but it seems that this value is explicitly removed from mapped entities. Is there a particular reason for this? If I remove the code that deletes the key, I do get the data I want.

If I comment out line 84 here: 
https://github.com/mikro-orm/mikro-orm/blob/9a47ad20b0aa3f4740e30c2be243037d7865ba88/packages/core/src/entity/EntityFactory.ts#L82-L87

and remove the `discriminatorColumn` check in this line:
https://github.com/mikro-orm/mikro-orm/blob/9a47ad20b0aa3f4740e30c2be243037d7865ba88/packages/core/src/hydration/Hydrator.ts#L42

things work.

If I also add the discriminator as a column defined in my entity, everything maps nicely typescript-wise.

```typescript
export enum TaskType {
    REPORT = "REPORT",
}

registerEnumType(TaskType, { name: "TaskType" });

@Entity({
    discriminatorColumn: "type",
    discriminatorMap: { REPORT: "Report" } as { [key in TaskType]: string },
})
@InterfaceType()
export class Task extends BaseEntity {
    @Enum()
    @Field(_type => TaskType)
    type: TaskType;
}
```

I imagine you explicitly remove this data so that mapped/hydrated objects don't come back with an unexpected key on them, which makes sense. Is there a good way to expose this? Ultimately my goal is to expose a `getTasks` function (well, GraphQL resolver, but same idea) that can return a list of Tasks, including their type so that the frontend can render them properly and all that.

I suppose an alternative solution would be to write a field resolver for each type that returns its own `TaskType`... but I still want to be able to query for tasks by type, which I can't do (safely) unless I declare `type` as a field on the class.

**Versions**

| Dependency | Version |
| - | - |
| node | `v12.17.0` |
| typescript | `3.9.7` |
| mikro-orm | `4.0.0` |

**Comment by B4nan** [comment]
It is removed because it is not a regular property of the entity (if you just comment those lines as you did, TS should fail unless you cast to something). 

We could make it dependent on the fact that you define the property explicitly.

**Comment by jshearer** [comment]
Oh man, you are the best. This is perfect. Thank you 🎊
