### ISSUE TITLE
Validation of entities with class-validator decorators?

### ISSUE THREAD

**Issue by squareloop1** [mikro-orm/mikro-orm#833]
I want to migrate from TypeORM to MikroORM. However, it seems like class-validator is not compatible with MikroORM which is a bit of a setback as the validation of entities with class-validator decorators was really handy.

Are there any plans of a similiar feature or even making MikroORM compatible to class-validator? Or is there a feature already implemented which supports decorator based entity validation?

Kind of related to https://github.com/mikro-orm/mikro-orm/issues/720
It is said we can use class-validator for the DTOs, but as not every field and property of entities are always handled by a DTO and instead are handled internally, a validation for entity properties is really something I'm missing.

**Comment by B4nan** [comment]
Could you prepare a repo with demonstration of what actually does not work with `class-validator`? I guess it is about the `Collection` wrapper?

**Comment by squareloop1** [comment]
I didn't actually test it yet, but in https://github.com/mikro-orm/mikro-orm/issues/720 it sounds like it would not be advised to use this with MikroORM as of possible sideeffects and class-validator not supporting Collections.

Here is a list with validator decorators: https://github.com/typestack/class-validator#validation-decorators
You can combine multiple decorators to have a very precise validation.

**Comment by B4nan** [comment]
The advice in #720 was mainly about not creating entity via class-transformer, and that won't change. But I think it should be fine to use `class-validate` to validate it.

Btw the `Collection` wrapper acts to a certain degree as an array like structure, it has `length` property and it allows index access (e.g. `author.books[1]`). So I wouldn't be surprised if it actually works fine with `class-validator` already.

**Comment by squareloop1** [comment]
Oh I see. Sounds great, will give this a try. Thank you.
