### ISSUE TITLE
V4 npx mikro-orm command does not work.

### ISSUE THREAD

**Issue by shivam95** [mikro-orm/mikro-orm#835]
According to docs to use CLI we can use the command

` npx mikro-orm`

It is currently throwing error as 
`command not found: mikro-orm`

I tried the below command and it works
npx @mikro-orm/cli

I think the documentation needs an update.

**Comment by B4nan** [comment]
You need to install the cli package first.

**Comment by shivam95** [comment]
Thank you for your quick response. 

Do I need to install it globally? 
I already have it in my local dependencies. 

Note: I recently upgraded my project to  mikro-orm  v4

`
 "dependencies": {
    "@mikro-orm/cli": "^4.0.2",
    "@mikro-orm/core": "^4.0.2",
    "@mikro-orm/migrations": "^4.0.2",
    "@mikro-orm/nestjs": "^4.0.0",
    "@mikro-orm/postgresql": "^4.0.2",
    "@nestjs/common": "^7.0.0",
    "@nestjs/config": "^0.5.0",
    "@nestjs/core": "^7.0.0",
    "@nestjs/jwt": "^7.1.0",
    "@nestjs/passport": "^7.1.0",
    "@nestjs/platform-express": "^7.0.0",
    "aws-sdk": "^2.747.0",
    "bcrypt": "^5.0.0",
    "dotenv": "^8.2.0",
    "jsonwebtoken": "^8.5.1",
    "multer-s3": "^2.9.0",
    "passport": "^0.4.1",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.5.4"
  },
`
