### ISSUE TITLE
Support plural name for mongodb collections

### ISSUE THREAD

**Issue by toshimo** [mikro-orm/mikro-orm#846]
**Is your feature request related to a problem? Please describe.**
Does this library expect mongodb collection names to be singular? If so, please consider to allow developers to use plural named collections.

Let's say you already have database which has `books` and `authors` collections. A simple solution would be to name your entities like `class Authors` instead of `class Author`. The problem is when you define `book.author` relationship, you might have:
```js
class Books{
  // ...
  @ManyToOne() 
  author: Authors; // <- plural name looks confusing
  // ...
}
```
So using plural classes wouldn't be a good option.

**Describe the solution you'd like**
Either `book` or `books` collection can be used and handled automatically. Or the table naming convention choice (plural/singular) can be set through options upon `MikroORM.init` or somewhere else.

**Describe alternatives you've considered**
I have checked [Naming Strategy](https://mikro-orm.io/docs/naming-strategy/) page. So one can implement a solution by themselves.

**Additional context**
I'm testing out this great library just for some hours. I searched this repo but I couldn't find any related issues. I'm sorry if I've missed any doc or misunderstood something.

**Comment by B4nan** [comment]
You can use any name, just specify it in the `@Entity({ collection: 'my-custom-name' })` decorator or define custom naming strategy (you can extend the `MongoNamingStrategy` and override just the one method). No plans to do some pluralization magic automatically (pluralization is not that simple thing, I've been there... :]).

**Comment by toshimo** [comment]
Great, thanks. I agree that pluralization will be a headache and the overriding decorator is enough for my case. thanks!
