### ISSUE TITLE
Implement control over migration transaction

### ISSUE THREAD

**Issue by peter-episource** [mikro-orm/mikro-orm#851]
**Is your feature request related to a problem? Please describe.**
I have a multiple tenant database structure where I would like to sync up migrations across tenant databases. For example, if I have two databases, A and B, this requires that if database A's migrations succeed, but database B's migrations fail, both database A and B's transactions rollback.

**Describe the solution you'd like**
In my scenario, I would have a MikroORM instance for each tenant database where I'd like to control commiting and rollback of the transactions.

The migration methods accept a transaction as a option:
```
migrator.up({ transaction: trx });
```

A way to pull a transaction from the orm. Currently I do a hacky workaround by doing:
``` 
const connection = orm.em.getDriver().getConnection();
// @ts-ignore
const trx = await connection.client.transaction();
```

This way, I can wait for all the migrations in the different databases to finish and commit the transactions only if all migration instances succeed.

**Comment by B4nan** [comment]
In v4 there is `em.getConnection().begin()` that will give you the tx context, so the latter should be fine already.

**Comment by B4nan** [comment]
```ts
await orm.em.transactional(async em => {
  await migrator.up({ transaction: em.getTransactionContext() });
});
```
