### ISSUE TITLE
postgres sql and express get connection

### ISSUE THREAD

**Issue by sptGabriel** [mikro-orm/mikro-orm#856]
Hello i'm trying to make a repository of an entity, i would like to know how i can get the connection to get the repository

like this :

orm.em.getRepository(xx);

```
import {
  RequestContext,
  Repository,
  Connection,
  MikroORM,
  DatabaseDriver
} from '@mikro-orm/core';
import { EntityRepository, EntityManager, } from '@mikro-orm/postgresql';
export class LocationRepositoryImp
  implements LocationRepository<LocationEntity> {
  private repository: EntityRepository<LocationEntity>;
  constructor() {
    this.repository  = DatabaseDriver.
}

```

but I didn't find anything in the documentation on how to get a connection

**Comment by B4nan** [comment]
Not sure what you are up to, you need to initialize the ORM, from that instance you can get EM and repository. There is no way to "make a repository from entity". There is no global state, dont expect any global getter.

**Comment by sptGabriel** [comment]
I wanted something like typeorm's getConnection, but I managed to do it using tsyringe:

```
export class LocationRepositoryImp
  implements LocationRepository<LocationEntity> {
  private repository: EntityRepository<LocationEntity>;
  constructor(@inject(MikroClient) private database: MikroClient) {
    this.repository = this.database
      .getConnection()
      .em.getRepository(LocationEntity);
  }
}
```

**Comment by sptGabriel** [comment]
@B4nan could you tell me if it is bad to create a singleton of the connection?

**Comment by B4nan** [comment]
As long as you use `RequestContext` helper it's fine, otherwise you need to work with a fork of the EM (each request needs to have its own fork). 

So for the `MikroORM` class, it should be singleton, when you use the `RequestContext` in a middleware, it will automatically handle this behind the scenes, even if you use shared EM instance. But still, it is technically possible to have multiple ORM instances, also when using explicit transactions, you can have many EMs for single request - that is one of the reasons why there is no static/global getter. You can always create one, that way, you will clearly see what is happening - but such helper should be used only at the top level (e.g. in the endpoint handler), not somewhere in a service (or even worse entity method) as that could then result in usage of wrong EM instance.

In general, I would say avoid global state, it's evil :]

**Comment by mrfsbDev** [comment]
I have the same question, what would be the best way to share EntityManager?
I managed to make the connection through dependency injection
I didn't want to couple the database context in the request or in the context of GraphQL

**Comment by B4nan** [comment]
> I didn't want to couple the database context in the request or in the context of GraphQL

Having request specific ORM context is pretty much mandatory. Here are some of the reasons why you need request context: 

https://mikro-orm.io/docs/identity-map/#why-is-request-context-needed

And the same applies to graphql.

**Comment by mrfsbDev** [comment]
I created a singleton that returns the fork of EntityManager, through the method orm.em.fork() and I inject it through the constructor, can there be a problem?

**Comment by B4nan** [comment]
Sounds good, as long as you do not use the "global EM" you should be fine.

**Comment by mrfsbDev** [comment]
Thank you! Excellent project.

**Comment by sptGabriel** [comment]
@B4nan can u helpme with this?
i have a singleton from my connection where i have a getEntityManager that returns a fork from my entity manager, is this correct or can i have problems?
my repository:

```
@injectable()
export class DepartamentRepository implements IDepartamentRepository {
  private repository: EntityRepository<Departament>;
  constructor(database = container.resolve(MikroOrmClient)) {
    this.repository = database
      .getEntityManager()
      .getRepository(Departament);
  }
  create = async (departament:Departament):Promise<Departament> => {
    if(!(departament instanceof Departament)) throw new Error(`Not is Departament`)
    await this.repository.persistAndFlush(departament).then((row) => {
      return departament
    })
    return departament
  }
  byId = async (id: string): Promise<Departament | undefined> =>{
    const departamentRow = await this.repository.findOne({id})
    if(!departamentRow) return
    return departamentRow
  }
}
```

my database singleton:

```
@singleton()
export class MikroOrmClient implements IDatabaseORM{
  private connection: MikroORM<IDatabaseDriver<Connection>>;
  constructor(@inject("OrmConfig") private options: Options){
  }
  public getConnection = ():MikroORM<IDatabaseDriver<Connection>> => {
    return this.connection;
  };
  public close(): void {
    if(!this.connection) return
    this.connection.close()
  }
  public getEntityManager():EntityManager {
    return this.connection.em.fork()
  }
  public start = async () => {
    try {
      this.connection = await MikroORM.init(this.options)
      const migrator = await this.connection.getMigrator();
      const migrations = await migrator.getPendingMigrations();
      if (!(migrations && migrations.length > 0)) return;
      await migrator.up();
    } catch (error) {
      process.stdout.write(
        chalk.redBright(`${(error as Error).message}\n`)
      );
    }
  };
}
```

**Comment by douglasscriptore** [comment]
Hello, if someone has the same problem solved as follows:

**MyDatabaseOptions:**

```import { Options } from '@mikro-orm/core';

export default [
  {
    type: 'mysql',
    dbName: process.env.DB_NAME,
    host: process.env.DB_HOST,
    user: process.env.DB_USER,
    password: process.env.DB_PASS,
    port: 3306,
    entities: ['./dist/modules/**/infra/mikroorm/entities/*.js'],
    entitiesTs: ['./src/modules/**/infra/mikroorm/entities/*.ts'],
    baseDir: process.cwd(),
  },
  // {
  //   type: 'mongo',
  //   clientUrl: process.env.MONGO_URL,
  // },
] as Options[];
```


**DatabaseProvier:**

```import { Connection, IDatabaseDriver, MikroORM } from '@mikro-orm/core';
import config from '@config/ormconfig';
import { TsMorphMetadataProvider } from '@mikro-orm/reflection';
import IDatabaseProvider from '../models/IDatabaseProvider';

export default class DatabaseProvider implements IDatabaseProvider {
  private connection: MikroORM<IDatabaseDriver<Connection>>;


  public async connect(): Promise<void> {
    this.connection = await MikroORM.init(
      Object.assign({ metadataProvider: TsMorphMetadataProvider }, ...config),
    );
  }

  public close(): void {
    if (!this.connection) return;
    this.connection.close();
  }

  public getConnection = (): MikroORM<IDatabaseDriver<Connection>> => {
    return this.connection;
  };
}
```

**RegisterSingleton**

```import { container } from 'tsyringe';

import DatabaseProvider from './implementations/DatabaseProvider';
import IDatabaseProvider from './models/IDatabaseProvider';

const providers = {
  mikroORM: DatabaseProvider,
};

container.registerSingleton<IDatabaseProvider>(
  'DatabaseProvider',
  providers.mikroORM,
);
```

**Inject Provider on Repository**

```import { inject, injectable } from 'tsyringe';
import GrupoEmail from '../infra/mikroorm/entities/GrupoEmail';
import IGruposEmailsRepository from '../repositories/IGruposEmailsRepository';

@injectable()
class FindAllGruposEmailsService {
  constructor(
    @inject('GruposEmailsRepository')
    private gruposEmailsRepository: IGruposEmailsRepository,
  ) {}

  public async execute(): Promise<GrupoEmail[]> {
    const gruposEmails = await this.gruposEmailsRepository.findAllGrupos();

    return gruposEmails;
  }
}

export default FindAllGruposEmailsService;
```

use connect function one time in server start
