### ISSUE TITLE
findAndCount returning NaN for count

### ISSUE THREAD

**Issue by followben** [mikro-orm/mikro-orm#858]
**Describe the bug**
When using findAndCount on Postgres with a filterQuery that includes inverse relations, count can incorrectly return NaN

**To Reproduce**
1. check out https://github.com/followben/mikro-orm/tree/gh858
2. run `yarn test GH858`

**Expected behavior**
Count returns a number greater than or equal to zero (or findAndCount() throws an error).

**Versions**

| Dependency | Version |
| - | - |
| node | 12.x |
| typescript | 3.9.7 |
| mikro-orm | 4.0.5 |
| pg | 8.3.0 |

**Comment by B4nan** [comment]
Add a reproduction

**Comment by followben** [comment]
Hah, you're too quick... I was upping one with the GH issue number attached.

**Comment by B4nan** [comment]
Good, ty :] 

Anyway, I never merge those "repro PRs", the idea was that this "single file repro" should be part of the issue - I will be the one adding it to the codebase together with a fix.

**Comment by followben** [comment]
Why is that @B4nan? I mean, why aren't test cases worthy of merging?

**Comment by B4nan** [comment]
Why would I merge something that will cause build failures?

**Comment by followben** [comment]
Because someone went to the trouble of creating it as per the contribution guidelines. You can push to the PR to fix, correct?
