### ISSUE TITLE
Trying to query deep objects in mongodb

### ISSUE THREAD

**Issue by CoreParadox** [mikro-orm/mikro-orm#861]
Maybe my data structure is bad... but I'm trying to query like so:

```
User //Mikro entity
     playlist: Playlist[] // POJO
          songs: Song[] //POJO
              Refreshed:Date
```

it seems I'm not able to do it like so:

`UserCollection.find({ playlists: { songs: { 'fetched:gt': now() } } });`

Excuse the psuedo code, I'm just not able to find an example of how to do this in the documentation.

**Comment by B4nan** [comment]
It works the same as if there was no ORM - you need to use string keys with dots:

```ts
em.find(User, { 'playlists.songs.fetched': { $gt: new Date() } } } } as any); // you need to type cast as `FilterQuery` won't allow such key
```
