### ISSUE TITLE
Implicit changes in em.transactional() aren't written to the db

### ISSUE THREAD

**Issue by followben** [mikro-orm/mikro-orm#863]
**Describe the bug**
EntityManager's `transactional()` used to write any data registered in the IdentityMap (but not explicitly flushed) at the end of the transaction. This no longer seems to be the case.

**Expected behavior**
Given:

```typescript
@Entity()
export class A extends BaseEntity<A, 'id'> {
  @PrimaryKey({ type: 'uuid' })
  id = v4();
}
```
This should result in a database record and a value returned:

```typescript
const id = await orm.em.transactional(async () => {
  const a = new A();
  orm.em.persist(a);
  return a.id;
});
orm.em.clear();
const fetchedA = await orm.em.findOneOrFail(A, { id });
```

**Actual behavior**
No record exists and the last line throws.

**Versions**

| Dependency | Version |
| - | - |
| node | 12.x |
| typescript | 3.9.3 |
| mikro-orm | 4.0.6 |
| pg | 3.8.3 |

**Comment by followben** [comment]
@B4nan - I've been trying to follow what happens here. I can see the entity written to the UOW's `persistStack`, however it's gone by the time `commit()` gets called from the transactional flush. I can't see anything explicitly removing it, which leaves me to wonder if it's actually the same UOW instance?

**Comment by B4nan** [comment]
You need to use the EM from parameter.

```ts
await orm.em.transactional(em => {
  //... do some work
  const user = new User(...);
  user.name = 'George';
  em.persist(user);
});
```

https://mikro-orm.io/docs/transactions#approach-2-explicitly

**Comment by followben** [comment]
Bah, that's what happens when you stare at something for too long. RTFM.

Thanks Martin. Sorry for the noise...
