### ISSUE TITLE
PopulateMap conflicts with FindOptions parameter

### ISSUE THREAD

**Issue by jsprw** [mikro-orm/mikro-orm#867]
**Describe the bug**
The line: 
https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/entity/EntityRepository.ts#L41

... conflicts with:
https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/EntityManager.ts#L89 

... as you can also set an object (PopulateMap) as populate as well: 
https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/typings.ts#L261 -> https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/typings.ts#L259.

Therefore you can cause some confusion as it doesn't populate anything because it thinks it is an options object. The workaround is to wrap the populate in an options object: `find({ ...where... }, { populate: { ...populatemap... }})`.

I can only come up with these (non-)fixes:
1. possible breaking change: remove an overload? Or: remove the PopulateMap (which I like: type safety!)?
2. ugly code by adding a check whether the object contains the key populate and/or orderBy (breaks entities that have a  property with these names).

**Stack trace**
```
...
```

**To Reproduce**
See above.

**Expected behavior**
The find methods should determine the type of argument properly.

**Additional context**
All find options with the overload `P | Find*Options<T, P>` have this issue.

**Versions**

| Dependency | Version |
| - | - |
| mikro-orm | 4.0.7 |

**Comment by B4nan** [comment]
So what exactly is wrong? I don't see any example or stack trace or something, which makes the report quite cryptic :D

> The workaround is to wrap the populate in an options object: find({ ...where... }, { populate: { ...populatemap... }}).

That is not a workaround, this is intended usage.

**Comment by jsprw** [comment]
You can use find like this:

`find({...where...}, ["prop1", "prop2"])` but typing also allows you to use `find({...where...}, {prop1: true, prop2: true})`. And the line https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/EntityManager.ts#L89 checks if the second argument is an object and then assumes that it is an FindOptions object while it is an PopulateMap object.

**Comment by B4nan** [comment]
Again, this is intended, you cannot use `PopulateMap` directly like this, you need to wrap it in `FindOptions`. And I don't think there is a way around this - the typings are already too complex, I don't plan to do additional BCs now, and doing the key check is fragile.
