### ISSUE TITLE
Create if new or Reference existing in collection.add()

### ISSUE THREAD

**Issue by CoreParadox** [mikro-orm/mikro-orm#869]
So I'm trying to see if there is a better way to do this:

Songs is a collection on playlist, with a unique index, where playlist is the owning side of a many to many relationship.
The idea is that all songs are located in a central spot and can be referenced from multiple playlists.

So when I add them to the playlist, I first fetch all the ones with matching songIds in the database, then map them so they don't get created a second time.

```
    let songs: Song[] = req.body.map(MapSongInfo);
    if (!playlist.songs.isInitialized) {
        await playlist.songs.init()
    }
    let existing = await DataServices.EntityManager.find(Song, {
        'songId': { $in: songs.map(s => s.songId) }
    })
    songs = songs.map(s => {
        var index = existing.findIndex(e => e.songId === s.songId);
        if (index !== -1) {
            return existing[index];
        } else {
            return s;
        }
    })
    playlist.songs.add(...songs);
    await DataServices.EntityManager.persistAndFlush(playlist);
```

Is there a cleaner or more performant solution?

Edit: Sorry I didn't mean to tag this as a bug.

**Comment by B4nan** [comment]
> if (!playlist.songs.isInitialized) {

This is a method, you need to call it. 

I don't really understand your snippet, so you have all the songs in the request body, and want to synchronize the state of `playlist.songs` M:N collection? 

If so, there should be much easier way - load existing songs as you do, this will add them to the identity map, then use `em.assign()` to set the items to your collection, if the item will contain PK, it will use the loaded entity from identity map, the rest will be created as new entities.

```ts
await em.find(Song, { id: [...] });
em.assign(playlist, { songs }); // the songs array needs to have same structure as actual Song entities have
await em.flush();
```

There might be issues, it depends on what is the actual payload.

**Comment by CoreParadox** [comment]
Songs come in from the client like so:
```
    songId: string;
    name: string;
    provider: Provider;
    artist: string;
    thumbnail: string;
    url: string;
    runtimeSeconds: number;
```
songId is the unique index, so if I try to run this code:
```
  let songs: Song[] = req.body.map(MapSongInfo);
  let existing = await DataServices.EntityManager.find(Song, {
        songId: { $in: songs.map(s => s.songId) }
   })
   await DataServices.EntityManager.assign(playlist, { songs },);
   await DataServices.EntityManager.flush();
```
I don't think the identity map knows that the songs are loaded, because they aren't associated by songId, if that makes sense.
This is using mongo if that helps clarify.

```
@Entity()
export class Song {
    @PrimaryKey()
    public _id: string;

    @SerializedPrimaryKey()
    public id: string;

    @Property()
    @Unique()
    public songId!: string;

    @Property()
    public provider: Provider;

    @Property()
    public name: string;

    @Property()
    public artist: string;

    @Property()
    public thumbnail: string;

    @Property()
    public runtimeSeconds: number;

    @Property({ onUpdate: () => new Date() })
    public fetched: Date = new Date();

    @ManyToMany(() => Playlist, playlist => playlist.songs)
    private playlists = new Collection<Playlist>(this);
}
```
there's the song model as well

**Comment by B4nan** [comment]
I see, yeah it will work only with the primary key. Why don't you use the song id as PK?

**Comment by CoreParadox** [comment]
Thanks for the update! I'm still learning mongo along with this, when I initially tried it was giving me an error about the format of the PK, but I found that the PK field HAS to be named _id.

Down to this much code and works perfect, thanks for the help!
```
    let songs = req.body.map(MapSongInfo) as Song[];
    let existing = await DataServices.EntityManager.find(Song, songs);
    existing.forEach(e => {
        let songData = songs.find(s => e.id === s.id);
        if (e.fetched.getTime() < songData.fetched.getTime()) {
            DataServices.SongService.assign(e, songData)
        }
    });
    DataServices.EntityManager.assign(playlist, songs);
    await DataServices.EntityManager.flush();

**Comment by CoreParadox** [comment]
```
    let songs = req.body.map(MapSongInfo) as Song[];
    await DataServices.EntityManager.find(Song, songs);
    DataServices.EntityManager.assign(playlist, { songs });
    await DataServices.EntityManager.flush();
```
Alright I guess I was wrong, it does not seem to be working.... 

The song objects have an _id regardless if they are in the db or not, could that be the issue?

`E11000 duplicate key error collection: TestDB.song index: _id_ dup key: { : "IPyFlWvApgw" }`

**Comment by B4nan** [comment]
Hard to say, I don't have a magical orb :] But your code looks weird for sure, e.g. doing `em.find(Song, songs)`? Are you really loading the entities there? What is in `songs` array? It has to be either instances of `Song` entity, or array of PKs, if you want that `em.find()` to do something.

**Comment by CoreParadox** [comment]
The client sends an array of `SongDetail` which gets mapped into and array of `Song` at the server. I've tried `em.find` with both the `Song[]` or `songs.map(s=> s._id)` to the same result.

**Comment by B4nan** [comment]
> which gets mapped into and array of Song at the server

How? You should not use entity ctor for existing entities.

Anyway, I need to see/try the full thing to be able to help, otherwise it's pure guessing.

**Comment by CoreParadox** [comment]
The real issue was calling the constructor.
`const MapSongInfo = r => new Song(r.id, Provider.Youtube, r.name, r.channelTitle, r.runtimeSeconds, r.thumbnail);`

```
DataServices.EntityManager.find(Song, req.body.map(s => s.id));
await DataServices.EntityManager.assign(playlist, { songs: req.body })
await DataServices.EntityManager.flush();
```

Simple and clean, thanks for all your assistance on this.
