### ISSUE TITLE
Single Table Inheritance documentation improvements

### ISSUE THREAD

**Issue by alisd23** [mikro-orm/mikro-orm#870]
I've been having issues with getting STI working (with migrations specifically) and the documentation has thrown me off a bit.

Here's a few things I found confusing or lacking info

1. In the [documention](https://mikro-orm.io/docs/inheritance-mapping), right at the top, it says: `do not use @Entity decorator on base classes`. However, I found a test [here](https://github.com/mikro-orm/mikro-orm/blob/master/tests/single-table-inheritance.mysql.test.ts) that seems to show an abstract class being used as part of a STI hierarchy (which is what I wanted in my case). I assumed from the docs that this was not allowed at all, so maybe that line should be clarified or removed.
2. Is the discriminator column (e.g. `type`) supposed to be defined on the parent entity? Again in the tests it was defined as an `@Enum` column but in the docs not mentioned. I think this should be mentioned even if it is optional, to remove any doubt.
3. (This might be a bug or maybe the documentation is just wrong). If I try to recreate the example in the documentation, (Person/Employee), when running migrations both the tables are completely ignored. However, if I remove the parent table (Person) from the discriminator map - everything works. So I'm slightly confused how the parent table is supposed to work in a STI setup.
4. The setup in the tests seems very different to the documentation (abstract parent class, no base class in `discriminatorMap`), so I'm wondering if the documentation is just incorrect, or if there's bugs, or if I'm wrong on both.

If the documentation example works and is meant to be set up in that way, then I'll try to do a minimal reproduction.

Great library though 👍

**Comment by B4nan** [comment]
1. Well the page is not "documentation for STI", it's for inheritance mapping altogether - two ways are supported, mapped superclass and STI. The statement you are referring to is about mapped superclasses and is absolutely correct.

2. It is not needed, but it can be defined explicitly. If you have it there, you will be able to filter by that column directly, as well as you will have the property accessible as usual. 

3. Maybe a bug in schema diffing, would be good to have it tracked separately with a reproduction. 

4. Setup in tests is done so we can test/cover as much as possible, in general not much in tests is "minimal". The parent entity can be in the discriminator map, but it is not required - it is up to you - up to what you are modelling. But if the class is in the discriminator map, it must not be abstract. 

Agreed that the docs should be improved :]

**Comment by alisd23** [comment]
1. Good point, I just misread that section then - ignore that.

So for documentation, I think good improvements would be:
- Show the discriminator property (e.g. `type`) in the entiyy in the example, and just say it's optional and has no bearing on the relationship itself.
- to have an example *with* the parent in the discriminator map (non-abstract) + an example *without* the parent (abstract). These two options feel like quite distinct setups to me so it would be good to have both.

For the schema diffing bugs, I'll try to get a minimal repro for this one, as well as any others I find - i think there's a couple.

Time is not on my side but would be happy to contribute if I can.
