### ISSUE TITLE
Including parent table in STI discriminator map causes empty migrations

### ISSUE THREAD

**Issue by alisd23** [mikro-orm/mikro-orm#874]
**Describe the bug**
When creating a single table inheritance set up where the parent table is included in the `discriminatorMap` property, generated migrations ignore all the tables. If the parent table is removed from the map - the migrations run correctly.

**To Reproduce**
1. Reproduction: https://github.com/alisd23/mikro-orm-nestjs-starter/tree/bug/sti-migration
2. Run `migration:create` command (info about setup and running commands in  README.md) with parent included in discriminatorMap
3. See new empty migration

With this child table:
```ts
// employee.entity.ts
@Entity()
export class Employee extends Person {
  @Property()
  number: number;
}
```

This works:
```ts
// person.entity.ts
@Entity({
  discriminatorColumn: 'type',
  discriminatorMap: {
    // person: 'Person',
    employee: 'Employee',
  },
})
export class Person {
  @PrimaryKey()
  id: string;
}
```

However this causes empty migrations:
```ts
// person.entity.ts
@Entity({
  discriminatorColumn: 'type',
  discriminatorMap: {
    person: 'Person',
    employee: 'Employee',
  },
})
export class Person {
  @PrimaryKey()
  id: string;
}
```

**Versions**

| Dependency | Version |
| - | - |
| node | 12.18.3 |
| typescript | 4.0.x |
| mikro-orm | 4.0.7 |
| your-driver | mysql2 |

**Comment by thatsnotright** [comment]
@B4nan Do you have an ETA for release of the commits fixing this issue?

**Comment by B4nan** [comment]
Later this week, will be aiming for the first half (tue/wed), but can't promise.

**Comment by thatsnotright** [comment]
@B4nan I made the same fix as you applied here, and it appears to me that in MySQL any sort of many-many pivot table is no longer generated using the migration:create --initial command.

**Comment by B4nan** [comment]
https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/schema/SchemaGenerator.ts#L574
