### ISSUE TITLE
Type infer with the new Loaded and New types

### ISSUE THREAD

**Issue by t7yang** [mikro-orm/mikro-orm#876]
**Describe the bug**
I try to upgrade mikro recently and found an interesting error.

<img width="564" alt="mikrov4" src="https://user-images.githubusercontent.com/4502661/94327931-26afc780-ffe1-11ea-87e5-59d7fd1de3bb.png">

Previously in v3.x, `content` is infer as `Content` which nice but lack of type safety.

In v4.x the new types `Loaded` and `New` introduced in c5f766ba3ce3badf1c8922f1a7c14d60b50194f5 try to improve the type safety but somehow `content` is now infer as `IContent` which is a pure value object.

I try to digging into the source code and fix it but failed :|

**To Reproduce**
1. Passing a **typed object** into the second argument in `orm.em.create`.
2. The type of the return value is infer as the type of the object.

**Expected behavior**
The type of the return value should be an entity.

**Versions**

| Dependency | Version |
| - | - |
| node | 14.12.0 |
| typescript | 4.0.2 |
| @mikro-orm/core | 4.0.7 |
| @mikro-orm/mysql | 4.0.7 |

**Comment by B4nan** [comment]
Interesting. It has nothing to do with the `Loaded` or `New` types, the issue is with the `T` as it was inferred to your `IContent`. I managed to get around it, the issue was with the `EntityData` being defined as `T | ...`, removing that `T | ` fixes it.
