### ISSUE TITLE
EntityWrap and Reference can't find __helper on nestjs e2e tests

### ISSUE THREAD

**Issue by rangelfinal** [mikro-orm/mikro-orm#885]
**Describe the bug**
When running inside an e2e test using the `Test.createTestingModule` from nestjs, mikro-orm does not populate the `__helper` property on entity instances. As a result, `wrap(entity)` calls return `undefined`, and it's impossible to work with references.
The testing module is probably skipping some step on entity discovery or something related. Is there any way to "force" mikro-orm to populate `__helper`?

**Stack trace**
This stack trace is from my code base and not from the reproduction repository.
```
TypeError: Cannot read property 'primaryKeys' of undefined
      at new Reference (../../../node_modules/@mikro-orm/core/entity/Reference.js:11:14)
      at Function.create (../../../node_modules/@mikro-orm/core/entity/Reference.js:30:16)
      at new Location (modules/location/Location.entity.ts:61:30)
```

**To Reproduce**
Minimal reproduction repository: https://github.com/rangelfinal/nestjs-realworld-example-app
See the last commit for changes. Run the failing test with `yarn run test:e2e:repro`.
You can launch a compatible testing database with `docker run --name postgres_test -p 5432:5432 -e POSTGRES_DB=nestjsrealworld -e POSTGRES_USER=root -e POSTGRES_PASSWORD=root -d postgres`

**Versions**
It's a fresh fork of mikro-orm/nestjs-realworld-example-app

| Dependency | Version |
| - | - |
| node | v14.12.0 |
| typescript | 4.0.3 |
| @mikro-orm/core | v4.0.7 |
| @mikro-orm/nestjs | v4.2.0 |
| @mikro-orm/postgresql | v4.0.7 |
| @mikro-orm/reflection | v4.0.7 |
| @mikro-orm/sql-highlighter | v1.0.1 |
| @nestjs/common | v7.4.2 |
| @nestjs/core | v7.4.2 |
| @nestjs/microservices | v7.4.2 |
| @nestjs/platform-express | v7.4.2 |
| @nestjs/swagger | v4.5.12 |
| @nestjs/testing | v7.4.2 |
| @nestjs/websockets | v7.4.2 |

**Comment by B4nan** [comment]
The issue here is that your test is a TS file, but the discovered entities are JS. You can see that from the logs:

```
[discovery] - processing entity Article (/usr/local/var/www/b4nan/mikro-orm-examples/nestjs-realworld-example-app/dist/article/article.entity.js)
```

(when I do not have the project built, it will fail on no entities discovered)

So adding `tsNode: true` to the ORM config will help here:

```ts
        MikroOrmModule.forRoot({
          ...MicroORMConfig,
          dbName: 'test',
          user: 'test',
          password: 'test',
          tsNode: true, // <-- this will force discovery on TS files
        }),
```
