### ISSUE TITLE
SQL Parser for PostgreSQL and MySQL

### ISSUE THREAD

**Issue by pragmaticivan** [mikro-orm/mikro-orm#886]
**Is your feature request related to a problem? Please describe.**
It would be really nice supporting a plugin for parsing raw SQL for multiple DBs.
Maybe even autocomplete from the current DB connection one day.

**Describe the solution you'd like**
ex: https://github.com/stevenmiller888/ts-mysql-parser
https://github.com/segmentio/ts-mysql-plugin

**Comment by B4nan** [comment]
Not sure I follow, what would that be good for? Why would I parse a query on its own, when it will be executed as the whole string? 

Btw I really don't think it is possible to achieve autocomplete for a string at this level, not even with TS 4.1 (not talking about limitations of the string literal types - it's all nice, but in MikroORM things are configurable a lot, we would have to codegen things which I do not want).

**Comment by pragmaticivan** [comment]
The libraries I posted as example would allow raw queries to support autocompletion with typescript. With the plugin I posted in the example, it's possible to connect to a local db and autocomplete with values coming from the db connection.

I agree that it might not makes sense to live in Mikro ORM Maybe just in another package.
