### ISSUE TITLE
SQLITE: wrong number of arguments to function count()

### ISSUE THREAD

**Issue by njeirath** [mikro-orm/mikro-orm#889]
**Describe the bug**
I had submitted #887 yesterday and ran into another issue with the same setup.  I'm not sure if they're related and if this is a sqlite only issue like the other one.  

For reference, the entity I'm using:

```
export class FriendLink {
    requestor: User
    requestee: User
    created: Date

    [PrimaryKeyType]: [string, string]   //User is using a string as it's ID

    constructor(requestor: User, requestee: User) {
        this.requestor = requestor
        this.requestee = requestee
        this.created = new Date()
    }
}

export const schema = new EntitySchema<FriendLink>({
    // Some other stuff here
    properties: {
        requestor: {
            reference: 'm:1',
            entity: 'User',
            nullable: false,
            primary: true,
            joinColumn: 'requestor_user_id',
        },
        requestee: {
            reference: 'm:1',
            entity: 'User',
            nullable: false,
            primary: true,
            joinColumn: 'requestee_user_id',
        },
        created: {type: 'datetime', nullable: false},
    },
})

export const entity = FriendLink
```

And when I try to use this entity to perform a count operation as in the following code:

```
const totalCount = await em.count(FriendLink, {requestee: user})
```

I get an error like:

**Stack trace**
```
DriverException: select count(distinct `e0`.`requestor_user_id`, `e0`.`requestee_user_id`) as `count` from `friend_link` as `e0` where `e0`.`requestee_user_id` = 'user123' - SQLITE_ERROR: wrong number of arguments to function count()
```

**Expected behavior**
I'm assuming, but haven't validated, that the issue is that the distinct needs parenthesis like:
```
select count(distinct (`e0`.`requestor_user_id`, `e0`.`requestee_user_id`)) as `count ...`
```

Alternatively, since both those columns make up a composite key I'd expect them to already be unique so rather than using distinct it could likely just be `select count(*) as count ...`

I was able to work around this for the time being by executing my own SQL query to get what I needed.

**Versions**

| Dependency | Version |
| - | - |
| node | v14.5.0 |
| typescript | 3.8.3 |
| mikro-orm | 4.0.7 |
| your-driver | sqlite |

**Comment by B4nan** [comment]
mmmm would be better to address this in knex, apparently they do not support distinct count with composite keys in sqlite...

https://github.com/knex/knex/pull/2449#issuecomment-450590918

reported, and PR'ed almost 2 years ago

https://github.com/knex/knex/pull/2977

but still open, unresolved

**Comment by njeirath** [comment]
Got it, thanks for pointing me in the right direction
