### ISSUE TITLE
Datetime comparison with SQLite driver

### ISSUE THREAD

**Issue by maphe** [mikro-orm/mikro-orm#895]
**Describe the bug**
Querying Date columns using the SQLite driver does not work as expected.

**To Reproduce**
```ts
@Entity()
class Something {
  constructor(public init?: Date) {
    this.updatedAt = init;
  }

  @PrimaryKey()
  id!: number;

  @Property()
  updatedAt?: Date;
}

const orm = await MikroORM.init({
  entities: [Something],
  name: 'sqlite_test',
  dbName: `test_sqlite_dates`,
  type: 'sqlite',
  debug: ['query', 'query-params'],
  forceUtcTimezone: true,
});

const generator = orm.getSchemaGenerator();
await generator.dropSchema();
await generator.createSchema();

const s1 = new Something(new Date(Date.UTC(2020, 10, 15)));
const s2 = new Something(new Date(Date.UTC(2020, 10, 20)));

await orm.em.persistAndFlush([s1, s2]);

const earlier = await orm.em.getRepository(Something).find({ updatedAt: { $lt: new Date(Date.UTC(2020, 10, 18)) } });
console.log(earlier.length); // expected: 1; actual: 2
const later = await orm.em.getRepository(Something).find({ updatedAt: { $gt: new Date(Date.UTC(2020, 10, 18)) } });
console.log(later.length); // expected 1; actual: 0
```
Generated SQL:
```sql
create table `something` (`id` integer not null primary key autoincrement, `updated_at` datetime null);
insert into `something` (`updated_at`) values ('2020-11-14 16:00:00.000')
insert into `something` (`updated_at`) values ('2020-11-19 16:00:00.000')
select `e0`.* from `something` as `e0` where `e0`.`updated_at` < '2020-11-17 16:00:00.000'
```

**Additional context**
We're using the sqlite driver to run our test suites, replicating the production mysql schema. Some of our custom repositories do include date filtering and a function that may work properly on mysql would fail in a spec if we have a date column in the where clause.

From what I collected googling around, this is a well known limitation of sqlite, however it's possible to workaround the issue by storing dates as timestamps as opposed to strings. Dates comparison then becomes integers comparison and obviously greater than and less than would work there. It sounds like a data transformation that the orm can handle.

**Comment by B4nan** [comment]
Your reproduction is passing on my end, both calls are returning 1 item for me. What version are you on?

The problem with sqlite is that it does store JS `Date` objects to timestamps (number) by default, but you might end up with a string date instead if you use SQL functions for the value, e.g. `now()`. Then the values are no longer comparable. 

Another issue is with knex - the query you see in the console is actually not what gets sent to the db, its just a way knex will serialize the `Date` object, but under the hood it will pass it as it to `sqlite3` which will convert it to number. If you check the db, you should see that. I am currently thinking about using different way to handle the values and pass already interpolated query to the underlying driver (doing escaping at the ORM level instead of via prepared statements), that would help with this.

You can always use a custom type to handle this in a way you want.

**Comment by maphe** [comment]
We're still on mikro-orm 3.6, haven't been able to jump to v4 yet. Do you think that might be the reason?

We're not using any `now()`, we manipulate javascript dates similar to the example I provided (except we use `moment().toDate()`).

Custom types would work if we didn't have to handle 2 different drivers. Sure we don't care that much about what's stored in testing (sqlite) but we still want actual dates in production (mysql).

**Comment by maphe** [comment]
I get actual formatted string when I query the db directly
```
sqlite> select * from `something`;
1|Sat Nov 14 2020 16:00:00 GMT-0800 (Pacific Standard Time)
2|Thu Nov 19 2020 16:00:00 GMT-0800 (Pacific Standard Time)
```

**Comment by B4nan** [comment]
What version of `sqlite3` are you using? Sounds like you upgraded to v5, but they introduced one breaking change with dates, they are no longer stored numbers. In v4 the version is fixed to 4.2.

**Comment by maphe** [comment]
```
✗ sqlite3 --version
3.28.0 2019-04-15 14:49:49 378230ae7f4b721c8b8d83c8ceb891449685cd23b1702a57841f1be40b5daapl
```
I'm not sure about the `node-sqlite3` version but I think you might be right 🤔

**Comment by maphe** [comment]
Is there a way to force sqlite version 4.2 from mikro-orm 3.6?

**Comment by B4nan** [comment]
Just remove the `^` from package.json and fix the version. 

https://github.com/mikro-orm/mikro-orm/blob/master/packages/sqlite/package.json#L52

**Comment by maphe** [comment]
ah yeah I was looking at sqlite cli client 🤦 

Switching back to node-sqlite3 v4.2 fixed the issue. Thanks for the assistance.
