### ISSUE TITLE
Old value on custom types for checking if value changed before proceeding with expensive operations

### ISSUE THREAD

**Issue by squareloop1** [mikro-orm/mikro-orm#896]
**Is your feature request related to a problem? Please describe.**
Say I want a custom PasswordType and I want to make sure the string gets encrypted, I would do something like this:
```TS
[...]
convertToDatabaseValue(value: string,  platform: Platform): string {
  return bcrypt.hashSync(value, 10);
}
convertToJSValue(value: string, platform: Platform): string {
  return value;
}
[...]
```
But to prevent re-encryption of the already encrypted password, I would need to check somehow if the value is a encrypted string (which is not really perfectly possible) or the value has changed, to prevent re-encryption on every update.

**Describe the solution you'd like**
Maybe we could add the old value in params so we have something like `convertToDatabaseValue(newValue: string, oldValue: string, platform: Platform): string`

**Describe alternatives you've considered**
Alternative could be a transformer method on properties to transform values like this:
```TS
export class PasswordTransformer implements ValueTransformer {
  to(value: string) {
    return bcrypt.hashSync(value, 10);
  }
  from(value: string) {
    return value;
  }
}
```
And on the property decorator we could have `@Property({ transformer: new PasswordTransformer() })`

This method should only ever be called when setting a new value to this property or retrieving it. So it should only ever encrypt when setting a new password and not re-encrypt it when not updated.

**Comment by B4nan** [comment]
I don't think custom types are good fit for this. And tbh I would expect the transformers to work the same.

The request on its own does not make sense to me, you ask for "old value", but old value is already encrypted, you would be in the very same position as with custom types, right?

Personally I would just use a setter (`User.changePassword(pw: string): void` or something like that, it could also verify old password if provided...), or you could use lifecycle hooks (`@BeforeCreate` and `@BeforeUpdate`), as there you have the change set object from which you can tell whether the value changed and encrypt it from there. Also hooks can be async. 

https://mikro-orm.io/docs/lifecycle-hooks/#eventargs

**Comment by squareloop1** [comment]
@B4nan 
> The request on its own does not make sense to me, you ask for "old value", but old value is already encrypted, you would be in the very same position as with custom types, right?

Yes, the old value is already encrypted, that's right. If the property would be updated with a new password (in clear text) it would be encrypted again as we could check if it differs from the old, encrypted value. Otherwise it would not be re-encrypted if it hasn't changed at all. If we would have access to the old value and the new value of the property we could do something like this:
```TS
if (newValue !== oldValue) return bcrypt.hashSync(newValue, 10);
else return newValue;
```
> Personally I would just use a setter (User.changePassword(pw: string): void or something like that, it could also verify old password if provided...)

The use case for this feature request is going further than just making sure passwords are stored encrypted. There are many other use cases like e.g. hashing JWT refresh tokens, formatting numbers / strings or other things normally a transformer can be used for. BTW: A transformer just makes sure how values are received or stored in the database, so its already a bit like custom types are implemented right now, it's just missing a way to make sure it does not fire every time, even if the value was not changed at all.

With a transformer you can be sure to have a DRY way of storing a password encrypted, without needing to have an extra subroutine which has to be called on every password change. Same for every other use case where you need to reformat the value with expensive or one-time operations.

> or you could use lifecycle hooks (@BeforeCreate and @BeforeUpdate), as there you have the change set object from which you can tell whether the value changed and encrypt it from there. Also hooks can be async.

This would also be called with every update of any of the entity properties. Additonally this seems to be more for entity level operations as to property level operations. A more appropriate place for something like this would probably be the `onUpdate()` method of the `@Property` decorator, but it seems like we don't have access to the changeset in there and it is also fired on every entity update instead of just the update of the decorated property, which makes it basically the same as `@BeforeUpdate`.

**Comment by B4nan** [comment]
> If we would have access to the old value and the new value of the property we could do something like this:
> `if (newValue !== oldValue) return bcrypt.hashSync(newValue, 10);`

This would not work, as `newValue` is not encrypted but the `oldValue` is. You would have to compare hashes, which is the costly operation you are trying to get around.

**Comment by B4nan** [comment]
> This would also be called with every update of any of the entity properties. 

Yes, and you would have one simple if condition to check if the pw was changed or not.

> Additonally this seems to be more for entity level operations as to property level operations. A more appropriate place for something like this would probably be the onUpdate() method of the @Property decorator, but it seems like we don't have access to the changeset in there and it is also fired on every entity update instead of just the update of the decorated property, which makes it basically the same as @BeforeUpdate.

`onUpdate` is called *every* time the entity is updated, its the same as with hooks.

**Comment by squareloop1** [comment]
@B4nan 
> This would not work, as newValue is not encrypted but the oldValue is. You would have to compare hashes, which is the costly operation you are trying to get around.

No, I am not comparing hashes here, I am basically just comparing strings to avoid re-encrypting or re doing a costly operation or basically any other one time format of e.g. a primitive type where you want to bringt it in some specific format only once, without reformating it every time on every update.

> onUpdate is called every time the entity is updated, its the same as with hooks.

Thats what I'm saying. Would it be possible to have the changeset as param in the `onUpdate()` method too, same as in `@BeforeUpdate`? Does `onUpdate` fire on initial inserts too? Else this would not be a good DRY style, as we would need to handle it in `@BeforeUpdate` and `@BeforeInsert` which makes this just feel hacky, opposed to just a single transformer / custom type on a property.

**Comment by B4nan** [comment]
> No, I am not comparing hashes here, I am basically just comparing strings to avoid re-encrypting or re doing a costly operation or basically any other one time format of e.g. a primitive type where you want to bringt it in some specific format only once, without reformating it every time on every update.

New value is always unencrypted, old value is always encrypted, so again, you cannot compare those without hashing the new value. 

> Else this would not be a good DRY style, as we would need to handle it in @BeforeUpdate and @BeforeInsert which makes this just feel hacky, opposed to just a single transformer / custom type on a property.

You can use both decorators on the same method.

**Comment by squareloop1** [comment]
@B4nan 

> New value is always unencrypted, old value is always encrypted, so again, you cannot compare those without hashing the new value.

I suppose the `convertToDatabaseValue()` method of a custom type is only fired when flushing to db and the `convertToJsValue()` method is only fired when retrieving from db?

So if I get a user from db I have an encrypted `user.password`. If I don't change the `user.password` like this `user.password = '123456'`, both new value and old value in `convertToDatabaseValue()` would be the same string (`newValue = 'hashedstring'; oldValue = 'hashedstring'`). They would only differ, if I set a new clear text password with `user.password = '123456';` (`newValue = '123456'; oldValue = 'hashedstring').

**Comment by B4nan** [comment]
Yeah right, I got confused by the discussion about custom types. Custom types are really not a good fit for this, using hooks is what you want - that check for old value is exactly what happens inside UoW. 

I still feel like using `Property.onUpdate()` for this is wrong (it is not the purpose why the method is there), but I am not opposed to having the full changeset object as second parameter (so we maintain BC). Feel free to send a PR, the place where it's executed is `ChangeSetPersister.processProperty()`.

**Comment by squareloop1** [comment]
Yeah, I guess `onUpdate()` is not the right place for something like this, because it does not fire on inserts, does it? I guess I will fall back to `beforeUpdate` and `beforeCreate`. Just thought it would be a nice and concise way to also have the changeset or the old / new value to make these checks for one-time conversions in custom types.

**Comment by rubiin** [comment]
Facing similar problem. Is there any way to tell if certain field was updated or not before going with some operation like encryption
```ts
	@BeforeCreate()
	@BeforeUpdate()
	async hashPassword() {
		 console.log(this)
		this.password = await HelperService.hashString(this.password);
	}

``

I am using like this . Problem occurs when I am doing updates, it rehashes the password

**Comment by B4nan** [comment]
You should get an event args in the first parameter, with a change set available, so you can see what changed from that (it will be in the payload)

https://mikro-orm.io/docs/events#eventargs

**Comment by rubiin** [comment]
Cool. For anyone bumping into similar issue, here is how i fixed it 
```ts
	@BeforeCreate()
	@BeforeUpdate()
	async hashPassword(args: EventArgs<this>) {
		if(args.changeSet.payload?.password) {
			this.password = await HelperService.hashString(this.password);
		}
	}

```

Thanks @B4nan for the quick reply as always
