### ISSUE TITLE
Run query from db console

### ISSUE THREAD

**Issue by rubiin** [mikro-orm/mikro-orm#898]
It would be cool to have a feature in the orm which would give us  a shell prompt from where we can run queries or maybe the orm code something like in django

**Comment by B4nan** [comment]
I don't think this is needed, creating a shell like experience sounds like something that does not really belong to an ORM. Better to create a script and run that, the only difference is that you need to add the `MikroORM.init()` call at the top (like this, without params, it will use the CLI config automatically), so literally one line. 

If we had a custom query language, like HQL in hibernate (or DQL in doctrine), it would make sense, but for plain SQL it sounds like a bit unnecessary. 

Will close this, although I would probably accept a PR.

**Comment by rubiin** [comment]
cool
