### ISSUE TITLE
Non-empty collection appears empty when using getSnapshot() and loadItems()

### ISSUE THREAD

**Issue by rienheuver** [mikro-orm/mikro-orm#901]
**Describe the bug**
Related to issue #788, we are looking at the collectionUpdates of a Unit Of Work. I have a many-to-many relationship between, let's say, User and Post. I add something to the collection `user.posts`, and then look at onFlush and afterFlush events. In those events I get the collection updates.

When logging this collection itself, there is 1 Post item in it. When I log `collection.getSnapsot()` it is empty and when I log `collection.loadItems()` it is empty as well. How do I get the item that is in the collection?

**To Reproduce**
1. Add something to a many-to-many relation.
2. Get the collection updates in either the onFlush or afterFlush event
3. Log the collection

**Expected behavior**
I expected the item in the collection to be present in `collection.loadItems()`

**Versions**

| Dependency | Version |
| - | - |
| node | 14 |
| typescript | 3.9 |
| mikro-orm | 4.0.7 |
| @mikro-orm/nestjs | 4.2.0 |

**Comment by B4nan** [comment]
> When logging this collection itself, there is 1 Post item in it

All items that are in a collection are returned via `loadItems`, it sounds like what you see in the console.log is the index accessor (so you can do `coll[0]` to get the first element. And if `loadItems` give you empty array, this is just some wrongly removed item, it is no longer part of the collection. You can also do `coll.getItems(false)` that will give you the internal items array without loading it, but that will probably give you the same as `loadItems` (if the collection is already initialized, its the same).

**Comment by rienheuver** [comment]
If that's the case, then any idea why this change is not in the collection? I'd prefer for both the User and the Post to be visible in either the collectionUpdates or the changeSet, but they are not in either.

**Comment by B4nan** [comment]
Well without full reproduction I simply don't know, I need a working script I can run. 

Inside `onFlush`, you should have a reference to collection that is up to date (so already without the removed item). If the collection was loaded before, and you removed some item, it should be visible in `getSnapshot()` by that time.

**Comment by rienheuver** [comment]
We eventually got this to work, seems like we had a bug in our code with awaiting the initialization of the collection.
