### ISSUE TITLE
Store embeddables as embedded documents when using mongoDB

### ISSUE THREAD

**Issue by jeanbmar** [mikro-orm/mikro-orm#906]
**Is your feature request related to a problem? Please describe.**
At the moment, embeddables are stored in mongoDB like a RDBMS. While this is not an issue when manipulating data in memory, it becomes unnatural and limiting when working aside with the database.

**Describe the solution you'd like**
Before : 
```javascript
{
    "_id": ObjectId("5f7de71931bfe0652853c1e6"),
    "address_street": "foo",
    "address_country": "bar"
}
```
After : 
```javascript
{
    "_id": ObjectId("5f7de71931bfe0652853c1e6"),
    "address": { 
        "street": "foo",
        "country": "bar"
    }
}
```

**Comment by B4nan** [comment]
Yeah agreed, I wanted to allow this optionally from the very beginning, as it could work the same in SQL drivers too via JSON columns. I would still keep the current behaviour as default probably, as otherwise it could be seen as breaking change.
