### ISSUE TITLE
the migration folder should be created if not found

### ISSUE THREAD

**Issue by rubiin** [mikro-orm/mikro-orm#907]
If we set a migration folder to a non existent folder `for example: path: ./migrations` , 
we get something like this. It would be rather convienient to create a folder if not exists. Typeorm does that
`
[OperationalError: ENOENT: no such file or directory, scandir '/home/devina/nestjs-starter/migrations'] {
  cause: [Error: ENOENT: no such file or directory, scandir '/home/devina/nestjs-starter/migrations'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'scandir',
    path: '/home/devina/nestjs-starter/migrations'
  },
`

**Comment by rubiin** [comment]
Another, thing i noticed was when path set to ./migrations , why is the folder being addressed to the root of the project. Shouldn't it should be on to the same directory as mikrorom config

**Comment by Langstra** [comment]
> Another, thing i noticed was when path set to ./migrations , why is the folder being addressed to the root of the project. Shouldn't it should be on to the same directory as mikrorom config

I'd rather have the root be the actual root of the project. That way I can better predict where my folders are. Also I think this is logical when comparing it to other frameworks and libraries. For instance Nestjs, the cli generates all its stuff from the root of the project.

**Comment by rubiin** [comment]
> > Another, thing i noticed was when path set to ./migrations , why is the folder being addressed to the root of the project. Shouldn't it should be on to the same directory as mikrorom config
> 
> I'd rather have the root be the actual root of the project. That way I can better predict where my folders are. Also I think this is logical when comparing it to other frameworks and libraries. For instance Nestjs, the cli generates all its stuff from the root of the project.

Also I see the temp folder with json of entities being created. Shouldnt this folder be automatically deleted after the migration is ran

**Comment by B4nan** [comment]
> Also I see the temp folder with json of entities being created. Shouldnt this folder be automatically deleted after the migration is ran

Nope, its a cache folder, why would we wipe it? :] It has nothing to do with migrations, and it will be reused every time you initialize the ORM. You can disable caching if you want (it is "required" only for ts-morph provider, in v4 other providers have cache disabled by default, 
 and the default is reflect-metedata).

https://mikro-orm.io/docs/metadata-cache

**Comment by rubiin** [comment]
> > Also I see the temp folder with json of entities being created. Shouldnt this folder be automatically deleted after the migration is ran
> 
> Nope, its a cache folder, why would we wipe it? :] It has nothing to do with migrations, and it will be reused every time you initialize the ORM. You can disable caching if you want (it is "required" only for ts-morph provider, in v4 other providers have cache disabled by default,
> and the default is reflect-metedata).
> 
> https://mikro-orm.io/docs/metadata-cache

oh , I have been using sequelize and typeorm for a while and they don't do this so got confused. Thanks for the quick reply :) as always

**Comment by rubiin** [comment]
> If we set a migration folder to a non existent folder `for example: path: ./migrations` ,
> we get something like this. It would be rather convienient to create a folder if not exists. Typeorm does that
> `[OperationalError: ENOENT: no such file or directory, scandir '/home/devina/nestjs-starter/migrations'] { cause: [Error: ENOENT: no such file or directory, scandir '/home/devina/nestjs-starter/migrations'] { errno: -2, code: 'ENOENT', syscall: 'scandir', path: '/home/devina/nestjs-starter/migrations' },`

@B4nan  can we address this too?

**Comment by B4nan** [comment]
That is exactly what I just fixed, the migrations folder is created if it is not there when running up/down/create or other `Migrator` methods.

**Comment by rubiin** [comment]
> That is exactly what I just fixed, the migrations folder is created if it is not there when running up/down/create or other `Migrator` methods.

cool then thanks a bunch. Will it be available in coming versions?

**Comment by thomaschaaf** [comment]
@B4nan 
This breaks my use case where I am passing the migrations as classes into umzug as the folder does not exist for me.
This was added here: https://github.com/mikro-orm/mikro-orm/pull/741

**Comment by B4nan** [comment]
Right, so it should happen conditionally based on the `migrationList`.

**Comment by thomaschaaf** [comment]
> Right, so it should happen conditionally based on the `migrationList`.

Yes I will create a pr.
