### ISSUE TITLE
can't find document via ObjectId

### ISSUE THREAD

**Issue by wujingquan** [mikro-orm/mikro-orm#908]
**Describe the bug**
```
const tags = await this.contentTagRepository.find({
      $or: [
        {id: ['5f7e8b8c87e39f36306a911d']},
        {name: ['test']},
        {comments: ['test3']}
      ]
    });
```
![image](https://user-images.githubusercontent.com/22289015/95458443-bcb1fd80-09a4-11eb-8bc5-680649ba7df5.png)
![image](https://user-images.githubusercontent.com/22289015/95458841-58dc0480-09a5-11eb-9311-d68ef2517ae4.png)

**Stack trace**
```
...
```

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

can find document via ObjectId

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node |  12.18.2  |
| typescript | 4.0.2 |
| mikro-orm | 4.0.7 |
| your-driver | mongodb |

**Comment by B4nan** [comment]
How do you define your entity? Looks like you have the PK misconfigured, as the query in the logs is wrong (uses `id` instead of `_id`).

**Comment by wujingquan** [comment]
Thank you very much for your reply。
Entity define :
![image](https://user-images.githubusercontent.com/22289015/95460565-b2ddc980-09a7-11eb-888e-7a7c313e37ef.png)
![image](https://user-images.githubusercontent.com/22289015/95460529-a8bbcb00-09a7-11eb-86c3-0d0cd04c271b.png)

The following is OK
1.
```
const tags = await this.contentTagRepository.find({
      id: ['5f7e8b8c87e39f36306a911d']
    });
```
![image](https://user-images.githubusercontent.com/22289015/95461004-4616ff00-09a8-11eb-88c2-e12b701d78a5.png)

2.
```
const tags = await this.contentTagRepository.find({
      id: {
        $in: ['5f7e8b8c87e39f36306a911d']
      }
    });
```
![image](https://user-images.githubusercontent.com/22289015/95461225-8b3b3100-09a8-11eb-9a4c-683f16a9aaf6.png)

**Comment by B4nan** [comment]
Ok, entities are looking good, so it's probably caused by the `$or` operator.

**Comment by wujingquan** [comment]
Not only `$or`，`$and` `$not`has the same problem.
