### ISSUE TITLE
Using MikroORM instance in helper function

### ISSUE THREAD

**Issue by quinnvaughn** [mikro-orm/mikro-orm#912]
What is the preferred method of getting the ORM instance/Entity Manager in a helper function that isn't directly connected to the setup or has access to context, ideally without passing it in as a variable? 

In GraphQL resolvers/field resolvers I get it through context, but how would I get access to it in an unrelated function?

Do I have to initialize it again?

**Comment by B4nan** [comment]
If you are talking about some standalone script, you would initialize the ORM as usual inside that. Configuration should be shared, no need to duplicate that - you could even let the orm read the CLI config.
