### ISSUE TITLE
named migrations

### ISSUE THREAD

**Issue by rubiin** [mikro-orm/mikro-orm#914]
It would be great to have a migration with an option to pass the migration name

**Comment by B4nan** [comment]
This is not how you suggest new features, the issue template have a reason so please don't ignore it. Something "being great" is not a reason (not talking about it being very subjective) - why would it be great? What problems would it solve? How would you expect the change to be done? Are we talking about file names, or just some metadata?

Migrations need to have names that allow ordering on the file system level, that is the main reason why the name is fixed (and in fact it is not hardcoded anywhere, you can customize it via naming strategy `classToMigrationName` method).

**Comment by johnkahn** [comment]
In case anyone else goes looking for this feature and finds this issue, I figured I would put the solution I wrote that is working quite nicely for my team. IMO I think this is enough, albeit kind of hacky, but doesn't require a change to Mikro-ORM.

We created a custom `fileName` function that is used to generate file names. During that we use the `readline-sync` package to ask the user for a short description of the migration. To keep the order preserved we have a 4 digit counter at the beginning of the file. The end result is a file name like `0012-short-description-from-user-input.ts`.

> Set `migrations.fileName` to this function in your options object.

```typescript
/**
 * Asks the user for a short description and increments a counter.
 * Generates file names that follow the following naming structure.
 *
 * `0012-short-description-from-user-input`
 */
const descriptionFileName = () => {
  const DELIMITER = '-';

  // Get the last migration
  const lastFileName = fs.readdirSync(migrationsPath).pop();
  let counter = 0;

  if (lastFileName) {
    // Increment the counter based on the last migration
    counter = parseInt(lastFileName.split(DELIMITER)[0], 10) + 1;
  }

  // Ask user for a short description (keep asking until you get something or they quit with ctrl+c)
  let name = '';
  while (!name) {
    name = readlineSync
      .question("\nWhat does this migration do? (Keep it short, it's going in the file name)\n> ")
      .replace(/[^\w\s]/gi, '') // Remove any non-alphanumeric or whitespace characters
      .replace(/\s+/gi, DELIMITER) // Replace any number of whitespace characters with the delimiter
      .toLowerCase();
  }

  // New line to find question in logs easier
  console.log();

  return `${counter.toString().padStart(4, '0')}-${name}`;
};
```

**Comment by AbdlrahmanSaberAbdo** [comment]
now you can do that easily from version 5.7, for those who could be interested here's the PR that I made for this feature: https://github.com/mikro-orm/mikro-orm/pull/4250. 
docs https://mikro-orm.io/docs/migrations#using-custom-migration-names.
