### ISSUE TITLE
Add more db support

### ISSUE THREAD

**Issue by rubiin** [mikro-orm/mikro-orm#916]
**Is your feature request related to a problem? Please describe.**
We currently have support for `mongo,mysql,mariadb,postgresql,sqlite` by default . I think we should also consider adding
the widely used databases like `CockroachDB, Microsoft SQL Server ,Oracle ,SAP Hana ,sql.js` by default so as to target more users.

**Describe the solution you'd like**
Defaul mikro-orm connectors for these databases which can be installed as :
```sh
yarn add @mikro-orm/core @mikro-orm/mssql     # for mssql
yarn add @mikro-orm/core @mikro-orm/cockroachdb       # forcockroachdb
yarn add @mikro-orm/core @mikro-orm/oracle     # for Oracle
yarn add @mikro-orm/core @mikro-orm/saphana  # for sap hana
yarn add @mikro-orm/core @mikro-orm/sqljs      # for sql.js
```

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by B4nan** [comment]
No plans to do that, I don't want to spend months learning new technologies I will probably never need/use myself, not talking about the long term maintenance. The ORM is extensible, technically anyone can bring support to any of those. People who use/need those drivers should be responsible for bringing them to life. 

Short term plan (upcoming months) is to support mssql and oracle, but it's not really a priority for me as I will most probably never use those too. 

On the other hand, I would be willing to work on new drivers for some (rather significant) sponsorship, so if there is a company needing those and willing to put some money in the game, feel free to contact me :]

**Comment by rubiin** [comment]
@B4nan I can work on some of them, is it okay

**Comment by rubiin** [comment]
Also , is there a account on opencollective. It would be great if there was so I could personally do some sponsership of some little amount.

**Comment by B4nan** [comment]
Sure you can try, keep in mind that mssql and oracle are both in process already. 

> Also , is there a account on opencollective. It would be great if there was so I could personally do some sponsership of some little amount. 

I am using GH sponsors (and paypal for one time donations):

https://github.com/sponsors/B4nan
https://paypal.me/mikroorm

**Comment by rubiin** [comment]
cool. I think you can also create a topic and pin it so as to get more sponsers
