### ISSUE TITLE
? character being replaced with $1 after upgrading 4.0.7 --> 4.1.0

### ISSUE THREAD

**Issue by njeirath** [mikro-orm/mikro-orm#920]
**Describe the bug**
I recently upgraded from 4.0.7 to 4.1 and noticed some strange behavior when persisting values that contain a `?` character.  For some reason once the data is written to the database I'm seeing the `?` replaced with `$1`.  

**Stack trace**
On 4.0.7 when I save a string containing a `?` I see the following query generated:
```
update "team" set "profilephotourl" = 'https://SOME_URL/profile.png?t=1602648800506' where "id" = '123'
``` 

And in the database it shows up as expected:
```
https://SOME_URL/profile.png?t=1602648800506
```

And on 4.1, I see the following query:
```
update "team" set "profilephotourl" = 'https://SOME_URL/profile.png?t=1602631580559' where "id" = '123'
```

But in the database I see:
```
https://SOME_URL/profile.png$1t=1602631580559
```

Where the `?` appears to have been replaced with a `$1`

**To Reproduce**
Nothing has changed with the code other than to move from 4.0.7 --> 4.1 and the code itself in this case is super simple:
```
const team = await em.findOneOrFail(Team, {id: teamId})
team.profilePhotoUrl = url
await em.flush()
```

Where `url` contains the URL examples from above.

**Versions**

| Dependency | Version |
| - | - |
node | v14.5.0
typescript | 3.8.3
mikro-orm | 4.0.7 & 4.1
your-driver | postgresql

**Comment by B4nan** [comment]
fixed in `4.1.1`
