### ISSUE TITLE
Using discriminatorValue causes ignored child entities

### ISSUE THREAD

**Issue by alisd23** [mikro-orm/mikro-orm#923]
**Describe the bug**
When using the `discriminatorValue` setup for STI entities as described [here](https://mikro-orm.io/docs/inheritance-mapping#using-discriminatorvalue-instead-of-discriminatormap), I am seeing some strange behaviour when combining with an `abstract` base (root) class.

The reproduction has 1 base class (Person) and 3 child entities (Chef, Gardener, Teacher).

When I log the metadata I see 2 issues (1 definite, 1 potential):

1. The discriminator map is wrong. The abstract root class, `Person`, is present when it shouldn't be and the `Gardener` entity is missing.
```
discriminatorMap: { chef: 'Chef', person: 'Person', teacher: 'Teacher' }
```
2. The abstract root class, `Person`, is marked as `abstract: false` in the metadata. I'm not familiar with the internals so this might not be a bug, but it seems wrong given the Person class is `abstract` and I do not want it included in the generated discriminator map.

This is causing entities to not be entered correctly for the missing child entities.

**To Reproduce**

1. Go here to the [reproduction](https://github.com/alisd23/mikro-orm-nestjs-starter/tree/bug/discriminator-value)
2. Run `yarn start:dev` - watch the output of metadata found from the entity classes

**Expected behavior**
Only the non-abstract child entities, `Chef`, `Teacher`, and `Gardener` should exist in the discriminator map, and `Person` should be excluded.

**Versions**

| Dependency | Version |
| - | - |
| node | 12.18.3 |
| typescript | 4.0.3 |
| mikro-orm | 4.1.1 |
| your-driver | MySQL |

**Comment by B4nan** [comment]
Sounds like the order of entities is the problem here, weird. Can you try to specify them explicitly as references (`entities: [A, B, C]`) and play a bit with the order?

**Comment by alisd23** [comment]
Ok that's clearer. So it sounds like you have to rely purely on the `discriminatorColumn`/`discriminatorValue` setup, in this case, to work out the correct entity metadata.

From trying to play with the order here are my results:
- `[Person, Chef, Teacher, Gardener]` (root at start) shows a discriminatorMap with all **4** entities correctly - according to what you said previously (though I'd still say not expected behaviour).

However, the above is still an issue because when the `Parent` entity is in the discriminator map, migrations will try to make the `type` column (the discriminator column) an enum which includes the `Person` type - which is not what I want for an abstract class. Maybe there should be a way of marking a root STI class as abstract in the entity configuration so the `discriminatorColumn`/`discriminatorValue` setup works with abstract root classes.

- `[Chef, Teacher, Gardener, Person]` (root at end) shows a discriminator map of: `{ chef: 'Chef', person: 'Person' }`, which is missing 2 of the child entities.
- `[Chef, Teacher, Person, Gardener]` (root second from end) shows a discriminator map of `{ chef: 'Chef', person: 'Person', gardener: 'Gardener' }`, which is missing the `Teacher` only. 
- `[Chef, Person, Teacher, Gardener]` (root second position) shows a discriminator map with all 4 again.

So it looks you're right, there's some issue with ordering. Seems like the first in the array is always included in the map, then only ones listed **after** the root entity are included on top of that. Very strange

**Comment by B4nan** [comment]
Looking at the abstract entities, unfortunately that is a TS only information, so (unless using ts-morph) there is no way to tell that the class is actually abstract (it is not present in what reflect-metadata gives us). But we could mark the class explicitly as `@Entity({ abstract: true })` and based on that it can be ignored in the discriminator map.
