### ISSUE TITLE
Default Dates not populated for created Entity when specifying id

### ISSUE THREAD

**Issue by hebronwatson** [mikro-orm/mikro-orm#924]
I have the following code, which I have tested using mysql and sqlite:

**Post.ts**
```
import { Entity, PrimaryKey, Property } from '@mikro-orm/core';

@Entity()
export class Post {

  @PrimaryKey()
  id!: number;

  @Property()
  createdAt: Date = new Date(); 

  @Property({onUpdate: () => new Date() })
  updatedAt: Date = new Date();

  @Property()
  title!: string;
}
```

**index.ts**
```
import { MikroORM } from '@mikro-orm/core';
import { Post } from './entities/Post';
import { __PROD__ } from './constants';
import mikroOrmConfig from './mikro-orm.config';
import 'reflect-metadata';

const main = async () => {
    const orm = await MikroORM.init(mikroOrmConfig);

    const post = orm.em.create(Post, {title: 'My first post', id: 6});
    await orm.em.persistAndFlush(post);
    console.log('----------------- SQL V2 --------------');    
}

main();
```

The execution of this code (on the above defined Entity) results in the following SQL statement:
` insert into `post` (`id`, `title`) values (6, 'My first post')`

and the following error (with filepaths anonymized by partial replacement with '<project_root>'):
```
(node:15924) UnhandledPromiseRejectionWarning: NotNullConstraintViolationException: insert into `post` (`id`, `title`) values (6, 'My first post') - SQLITE_CONSTRAINT: NOT NULL constraint failed: post.created_at
    at SqliteExceptionConverter.convertException (<project_root>\node_modules\@mikro-orm\sqlite\SqliteExceptionConverter.js:23:20)
    at SqliteDriver.convertException (<project_root>\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:160:54)
    at <project_root>\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:164:24
    at async SqliteDriver.nativeInsert (<project_root>\node_modules\@mikro-orm\knex\AbstractSqlDriver.js:145:21)
    at async ChangeSetPersister.persistNewEntity (<project_root>\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:55:21)
    at async ChangeSetPersister.executeInserts (<project_root>\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:24:13)
    at async UnitOfWork.commitCreateChangeSets (<project_root>\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:443:9)
    at async UnitOfWork.persistToDatabase (<project_root>\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:405:13)
```

**Expected Behaviour**
I had expected that the function would behave the same as without the specified id.

**Suggestion**
The function should continue to provide defaults as specified in the entity file, except where values that have defaults have been specified. Other unspecified values with defaults should be populated with those defaults.

**Comment by B4nan** [comment]
I know very well what line is causing this, but I believe it had some side effects when I tried fixing it, so it will probably require a bit deeper refactoring (but definitely doable). 

You could do this as a workaround:

```ts
const post = orm.em.create(Post, {title: 'My first post'});
post.id = 6;
```

**Comment by hebronwatson** [comment]
@B4nan Thank you for your response. Can you tel me what line (and in what file)? I looked at the code, but couldn't trace the problem.

**Comment by B4nan** [comment]
The issue is that when you provide all PKs to entity factory, it won't use the constructor (and therefore the property initializers won't be fired, as those live in the ctor).

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/entity/EntityFactory.ts#L88

**Comment by B4nan** [comment]
Interesting, apparently the recent changes I made in 4.1 also helped with this issue I was referring to.
