### ISSUE TITLE
Add more jsdoc/tsdoc to the sources

### ISSUE THREAD

**Issue by mojo2012** [mikro-orm/mikro-orm#928]
## Feature Request
I'm heavily relying vscode autocomplete feature and I'm a bit disappointed that a lot of the API is missing proper tsdoc
<img width="1055" alt="Bildschirmfoto 2020-10-18 um 21 00 24" src="https://user-images.githubusercontent.com/1330361/96377322-5e93d000-1185-11eb-9a89-b0ccf65a86f6.png">

It would be awesome to add the docs on the reference page (https://mikro-orm.io/docs/repositories-api) to the sources.

Thanks, keep up the good work
br, matthias

**Comment by B4nan** [comment]
Right, I forgot to copy those to the `EntityRepository`. Most of the public methods are documented, but only in `EntityManager`.
