### ISSUE TITLE
Refactor use of unnecessary generics

### ISSUE THREAD

**Issue by mojo2012** [mikro-orm/mikro-orm#930]
Hi,

method signatures like this make the autocomplete suggestions in VSCode really hard to read:
```typescript

findAll<P extends Populate<T> = any>(options?: FindOptions<T, P>): Promise<Loaded<T, P>[]>;
```

I think it is even discouraged to use generic parameters in case the param type is only used once, like the `P` in your case.

I suggest to change it to something this:
```typescript
findAll(options?: FindOptions<T, Populate<T>>): Promise<Loaded<T, Populate<T>>[]>;
```

> Mind, I'm not a typescript expert

The less I have to skim back and forth to understand what P, T and other types are, the better!

**Comment by B4nan** [comment]
It's not "unnecessary usage", your suggestion would not work the same. 

The `P` is a populate hint, that will be inferred based on the find options, without using it, the `Loaded` type would not get the inferred "type value" based on the parameters, but a generic `Populate<T>`. 

If you do `em.find(Author, ['books'])`, the return type will be `Loaded<Author, 'books'>[]` - and that will allow you to access type safe getters on the populated properties (here the `books` collection).

For more context see the PR that introduced `Loaded` type hint: https://github.com/mikro-orm/mikro-orm/pull/691
