### ISSUE TITLE
createQueryBuilder - How to include relations?

### ISSUE THREAD

**Issue by ml1nk** [mikro-orm/mikro-orm#932]
We have a complex query which is realized by using "createQueryBuilder". The query is based on specialized operators of postgresql/ltree (~, @>, <@) and a subquery on the right side. As such i couldn't find a way to use it with smart query conditions.

By using "createQueryBuilder" there seems no way to load any relations directly. The "eager" property is ignored, as expected. As a workaround i'm currently using subsequent queries to gather the related objects. In typeorm there is an function called innerJoinAndSelect in the query builder, but i couldn't find a corresponding function here.

Is there a way to get A and B with a single query?

~~~javascript
@Entity()
export class A {
  [PrimaryKeyType]: number
  @OneToOne({ primary: true, eager: true })
  object!: B

  @Property({ columnType: 'ltree' })
  path!: string
}
~~~

**Comment by B4nan** [comment]
Not sure I follow, so you'd like to map multiple results from single QB (as that is currently not really supported, fetch joining works only for the EM/repository API, not via QB)? Can you post what have you tried? 

> In typeorm there is an function called innerJoinAndSelect in the query builder, but i couldn't find a corresponding function here.

You have `join` and `addSelect` methods here.

**Comment by ml1nk** [comment]
Sorry for my bad description. Like you suspected, i want to map multiple results from single QB. I used this feature in typeorm by innerJoinAndSelect which does an inner join on a relation and also maps(=selects) the relation into the result. So you already provided the answer, that it isn't currently supported. Thanks.

>  Can you post what have you tried?
I tried to alias the columns of the relation and used knex to get the raw data. Then i filtered the data by alias per entity and removed the alias in the resulting arrays. Finally i could map the rows with orm.em.map to the expected entities. As the approach was to hacky, i stopped doing it like that.

> What you can do is to use em.populate() to load relations on top of what the QB will give you.
Thanks, it's still a separate request but cleaner then what i used.

**Comment by B4nan** [comment]
I was looking at the implementation, and fetch joining currently lives in the driver, but I would definitely like to support doing this directly with query builder. The functionally is there, it's just on wrong place, so hopefully it won't be that hard. Will try to look into this soon.

**Comment by ml1nk** [comment]
Thank you, i really appreciate your work here.

**Comment by B4nan** [comment]
`v4.3` will have `joinAndSelect` and `leftJoinAndSelect` (see #988).

**Comment by B4nan** [comment]
Before the `v4.3` release, you can try the dev build, latest one is `4.2.4-dev.81`.

**Comment by ml1nk** [comment]
I tested the current dev version 4.2.4-dev.117.

Entities:
~~~
export class CoreTagEntity {
  [PrimaryKeyType]: number
  @OneToOne({ primary: true, onUpdateIntegrity: 'cascade', onDelete: 'cascade', eager: true })
  object!: CoreObjectEntity

  @Property()
  tag!: number
}

export class CoreObjectEntity {
  @PrimaryKey()
  id!: integer

  @Property()
  name!: string
}
~~~

___

~~~javascript
const qb = orm.em.createQueryBuilder(CoreTagEntity, 'tag')
qb.leftJoin('object', 'object')
const items = await qb.getResultList()
~~~
Result:  

CoreTag
~~~javascript
__initialized:true
__populated:true
~~~
tag is available

CoreObject
~~~javascript
__initialized:false
__populated:true
~~~
name is not available

___

~~~javascript
const qb = orm.em.createQueryBuilder(CoreTagEntity, 'tag')
qb.leftJoinAndSelect('object', 'object')
const items = await qb.getResultList()
~~~
Result:  

CoreTag
~~~javascript
__initialized:false => expected true
__populated:true
~~~
tag is not available => expected tag is available

CoreObject
~~~javascript
__initialized:false => expected true
__populated:true
~~~
name is not available => expected name is available

___

qb.select('\*') makes tag available but qb.addSelect('object.*') does not change anything.

___

What am I doing wrong?

**Comment by ml1nk** [comment]
Instead of
~~~javascript 
qb.leftJoinAndSelect('object', 'object')
~~~
i also tried  
~~~javascript 
 qb.leftJoinAndSelect('tag.object', 'object')
~~~

But it does not seem to make any difference. I wonder why the first one works at all.

**Comment by B4nan** [comment]
This works fine in tests:

```ts
    const qb = orm.em.createQueryBuilder(FooBar2, 'fb1');
    qb.select('*').joinAndSelect('fb1.baz', 'fz');
```

Without that `.select('*')` the root entity won't be selected.

> But it does not seem to make any difference. I wonder why the first one works at all.

There is no difference, no need to specify the root alias.

**Comment by ml1nk** [comment]
No idea what is going wrong.

~~~javascript
@Entity({ tableName: 'core_tag' })
export class CoreTagEntity {

  [PrimaryKeyType]: number
  [PrimaryKeyProp]: 'object'
  @OneToOne({ primary: true, onUpdateIntegrity: 'cascade', onDelete: 'cascade', eager: true })
  object!: CoreObjectEntity
}
~~~
~~~javascript
@Entity({ tableName: 'core_object' })
export class CoreObjectEntity {
 
  @PrimaryKey()
  id!: integer

  @Property()
  name!: string
}
~~~
~~~javascript
@Entity({ tableName: 'core_object' })
export class CoreObjectEntity {
 
  @PrimaryKey()
  id!: integer

  @Property()
  name!: string
}
~~~
~~~javascript
    const qb = orm.em.createQueryBuilder(CoreTagEntity, 'tag')
    qb.select('*')
    qb.leftJoinAndSelect('object', 'object')
    const items = await qb.getResultList()
~~~
![image](https://user-images.githubusercontent.com/4943440/99668582-3d691c80-2a6e-11eb-98be-aa08d09efb02.png)
![image](https://user-images.githubusercontent.com/4943440/99668661-5376dd00-2a6e-11eb-8660-45673a3d7a58.png)
![image](https://user-images.githubusercontent.com/4943440/99668723-64bfe980-2a6e-11eb-84c3-599fd80b68b9.png)

**Comment by B4nan** [comment]
I'd suspect the FK as PK to be the issue here, that is not tested.

**Comment by ml1nk** [comment]
Before switching to mikro-orm we used typeorm. It also supports FK as PK at least in theory, but in reality it was buggy as hell unlike your library. I'm using a tree based permission system realized with ltree (pg extension). It heavenly depends on FK as PK.

**Comment by B4nan** [comment]
Yeah no worries, it is supported usecase, I just suspect it will be the problem here as it is not tested. Will look into it.

**Comment by B4nan** [comment]
It works fine for me, closing with a passing test case. Will be happy to reopen if you provide an executable reproduction (ideally try to adjust the test case added in 3c44ffb).
