### ISSUE TITLE
The nested Where condition converts boolean true to string 'true'.

### ISSUE THREAD

**Issue by dekimasoon** [mikro-orm/mikro-orm#940]
**Describe the bug**

The nested Where condition converts boolean to string.
We have defined two Entities, User and UserOrganization, and the relationship between the two is OnetoMany.
The query generated when you find the UserOganization directly is fine.

```ts
em.find(UserOrganization, { isAdmin: true })

> select `e0`.* from `user_organization` as `e0` where `e0`.`is_admin` = true
```

However, if you find with a nested where condition, the boolean true of the generated query will be a string 'true'.

```ts
em.find(User, { organizations: { isAdmin: true } })

> select `e0`.* from `user` as `e0` left join `user_organization` as `e1` on `e0`.`id` = `e1`.`user_id` where `e1`.`is_admin` = 'true'
```

Thank you for the best library. It really helps us!

**Expected behavior**

The query is generated with boolean true.

**Versions**

| Dependency | Version |
| - | - |
| node | v12.18.3 |
| typescript | 3.9.7 |
| mikro-orm | 4.2.1 |
| your-driver | @mikro-orm/mysql@^4.2.1 |

**Comment by B4nan** [comment]
Can't replicate this, can you provide reproduction? Ideally in a single file, like in the tests (https://github.com/mikro-orm/mikro-orm/blob/master/tests/issues/GH222.test.ts).

**Comment by dekimasoon** [comment]
@B4nan

Thank you for your quick response and for your research!
And I apologize for not providing you with sufficient information.

We have created a test code to reproduce it.
https://github.com/dekimasoon/mikro-orm/commit/b924d56f2fcf2802b04769f9dcc16d95b0a19311

I debugged it, and it seems to use BigIntType as a PrimaryKey to reproduce the problem.
It seems that `true` is being converted to the string `'true'` in the `processCustomType` of QueryHelper, but I couldn't identify the cause of the problem.

https://github.com/mikro-orm/mikro-orm/blob/0ec99dc75690bf15df3897b4da0fc3b2ab709cdd/packages/core/src/utils/QueryHelper.ts#L177-L189

**Comment by B4nan** [comment]
Thanks for the repro, will try that later during the day.

One thing that popped immediately:

```ts
  @ManyToOne(() => User, { type: String })
  user: User;
```

What do you expect from that? Drop the `type`, the type is `User`, not `String` and is already defined by the first parameter. 

But I don't think that is causing the issue, it's rather noop than a problem (the first parameter should have precedence here and the `type` should be actually ignored).

**Comment by dekimasoon** [comment]
Sorry for the confusion.
I accidentally left an unnecessary type specification when I copied & pasted.

As you said, deleting the type specification did not change the result.
https://github.com/dekimasoon/mikro-orm/commit/c2f3865f790314f6defe1b6399931f35cb15e731

> will try that later during the day.

Can't believe how quickly you responded to us. Thank you so much!
