### ISSUE TITLE
Schema Diff - Column default raw value matching buggy (postgres)

### ISSUE THREAD

**Issue by dalanad** [mikro-orm/mikro-orm#944]
**Describe the bug**
When the PK is set to a Raw SQL expression like 
``   @PrimaryKey({ defaultRaw: `'PO'||lpad(nextval('purchase_order_id_seq')::TEXT,5,'0')` })
    id: string;
``

A migration / schema diff is executing the following **every** time
`alter table "purchase_order" drop constraint if exists "purchase_order_id_check";`
`alter table "purchase_order" alter column "id" type varchar(255) using ("id"::varchar(255));`
`alter table "purchase_order" alter column "id" set default 'PO'||lpad(nextval('purchase_order_id_seq')::TEXT,5,'0');`
`alter table "purchase_order" add constraint "purchase_order_pkey" primary key ("id");`

**Stack trace**
none

**To Reproduce**
1. Set Default value to a expression
``  @PrimaryKey({ defaultRaw: `'PO'||lpad(nextval('purchase_order_id_seq')::TEXT,5,'0')` })
    id: string;
``
2. Migrate once
3. Every migration thereafter will contain the SQL to re assign the default value

**Expected behavior**
default value to be not reassigned.

**Additional context**
I've done some troubleshooting and have found the issue.

When comparing default raw values in the schema helper, the values are different
value from prop ``'po'||lpad(nextval('purchase_order_id_seq')::text,5,'0')`` 
value from db ``('po'::text || lpad((nextval('purchase_order_id_seq'::regclass))::text, 5, '0'::text))``
this is due to value from postgres  having more data

so as a solution have set the value exactly as returned from the db to the schema helper which solves the problem.

**Versions**

| Dependency | Version |
| - | - |
| node | v14.14.0 |
| typescript | 4.0.3 |
| mikro-orm | 4.1.0 |
| pg | 8.4.1 |

**Comment by B4nan** [comment]
I dont think there is a way around this. The default value you provide needs to be in normalized form. It would be much more buggy to try replacing things to match it.
