### ISSUE TITLE
transactional() with a connection pool of 1

### ISSUE THREAD

**Issue by thekevinbrown** [mikro-orm/mikro-orm#947]
**Describe the bug**
When Knex is limited to a single connection with the pool options, `transactional()` times out. My understanding of this function is that it should simply begin a transaction within the current connection and should not create a new connection.

**Stack trace**
```
Timeout - Async callback was not invoked within the 30000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 30000 ms timeout specified by jest.
```

**To Reproduce**

Test case that replicates this behavior was created in #948.
 
**Expected behavior**
I expected Mikro to start a transaction using the existing connection, or in other words I expected `transactional()` to work with a pool configuration of `{ min: 1, max: 1 }`.

**Additional context**
The intent is to ensure each Lambda in our serverless environment is as gentle as it can be to the database, and as each Lambda only handles one request at a time it should only ever need to have one connection open.

It looks like this is just built in behaviour of Knex, and whenever you start a new transaction it forces that to happen on a new connection:
https://github.com/knex/knex/blob/80355e48509857fb4941f65f4b611973a9ee99d5/lib/transaction.js#L159

Is this intended behaviour?

**Log**
(From setting `debug:true` on `MikroORM.init`:

```
$ jest --runInBand GH947.test
  console.log
    [discovery] ORM entity discovery started, using ReflectMetadataProvider

      at Logger.log (packages/core/src/utils/Logger.ts:18:10)

  console.log
    [discovery] - processing entity A

      at Logger.log (packages/core/src/utils/Logger.ts:18:10)

  console.log
    [discovery] - entity discovery finished, found 1 entities, took 73 ms

      at Logger.log (packages/core/src/utils/Logger.ts:18:10)

  console.log
    [info] MikroORM successfully connected to database mikro_orm_test_gh_947 on postgresql://postgres@127.0.0.1:5432

      at Logger.log (packages/core/src/utils/Logger.ts:18:10)

  console.log
    [query] select 1 from pg_database where datname = 'mikro_orm_test_gh_947' [took 2 ms]

      at Logger.log (packages/core/src/utils/Logger.ts:18:10)

  console.log
    [query] set names 'utf8'; [took 1 ms]

      at Logger.log (packages/core/src/utils/Logger.ts:18:10)

  console.log
    [query] set session_replication_role = 'replica'; [took 1 ms]

      at Logger.log (packages/core/src/utils/Logger.ts:18:10)

  console.log
    [query] drop table if exists "a" cascade; [took 12 ms]

      at Logger.log (packages/core/src/utils/Logger.ts:18:10)

  console.log
    [query] set session_replication_role = 'origin'; [took 1 ms]

      at Logger.log (packages/core/src/utils/Logger.ts:18:10)

  console.log
    [query] select 1 from pg_database where datname = 'mikro_orm_test_gh_947' [took 2 ms]

      at Logger.log (packages/core/src/utils/Logger.ts:18:10)

  console.log
    [query] set names 'utf8'; [took 1 ms]

      at Logger.log (packages/core/src/utils/Logger.ts:18:10)

  console.log
    [query] set session_replication_role = 'replica'; [took 1 ms]

      at Logger.log (packages/core/src/utils/Logger.ts:18:10)

  console.log
    [query] create table "a" ("id" serial primary key); [took 10 ms]

      at Logger.log (packages/core/src/utils/Logger.ts:18:10)

  console.log
    [query] set session_replication_role = 'origin'; [took 1 ms]

      at Logger.log (packages/core/src/utils/Logger.ts:18:10)

  console.log
    [query] begin

      at Logger.log (packages/core/src/utils/Logger.ts:18:10)

 FAIL  tests/issues/GH947.test.ts (37.533 s)
  GH issue 947
    ✕ transactional works with a single postgres connection (30827 ms)

  ● GH issue 947 › transactional works with a single postgres connection

    : Timeout - Async callback was not invoked within the 30000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 30000 ms timeout specified by jest.setTimeout.Error:

      11 | describe('GH issue 947', () => {
      12 | 
    > 13 |   test(`transactional works with a single postgres connection`, async () => {
         |   ^
      14 |     const orm = await MikroORM.init({
      15 |       entities: [A],
      16 |       dbName: `mikro_orm_test_gh_947`,

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (tests/issues/GH947.test.ts:13:3)
      at Object.<anonymous> (tests/issues/GH947.test.ts:11:1)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        38.944 s, estimated 43 s
Ran all test suites matching /GH947.test/i.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

**Versions**

| Dependency | Version |
| - | - |
| node | v12.16.1 |
| typescript | 4.0.3 |
| mikro-orm | latest master |
| your-driver | PostgreSQL |

**Comment by B4nan** [comment]
I think the behaviour is correct, what is wrong in your snippet is that you are not using the inner EM instance:

```ts
await orm.em.transactional(async () => {
  await orm.em.find(A, {}); // <-- here you should use the EM from parameter
});
```

This should work fine:

```ts
await orm.em.transactional(async em => {
  await em.find(A, {});
});
```

**Comment by thekevinbrown** [comment]
It doesn't make it to that line, the hang is on calling `await orm.em.transactional(/* ... */)` before it even tries to call the callback, but I've updated the reproduction to use the inner `em` and it does the same.

I think this is expected Knex behaviour the more I look at it though. If you start a transaction then elsewhere in the code or within the callback you use the original Knex instance, they specifically give you a context that's not in that transaction, which means each transaction needs to be on its own separate connection, no?

**Comment by thekevinbrown** [comment]
I'll investigate.

**Comment by thekevinbrown** [comment]
Ok, that fixes it on the reproduction case, but in our project we're still having this issue. The way we get access to the `em` there should prevent us from doing this anywhere in our codebase.

Is there an easy way to debug what's causing it to try to get the other connection?

**Comment by B4nan** [comment]
Hard to say, but if its caused by usage of wrong EM, you can debug based on `em.id`.

**Comment by thekevinbrown** [comment]
Ok, I've figured out what's going on.

We need to specify an isolation level on our transactions. Currently we're doing the following:
```typescript
await orm.em.transactional(async transactionalEm => {
  await transactionalEm.getConnection().execute(`SET TRANSACTION ISOLATION LEVEL SERIALIZABLE`);
  // Whatever else using transactionalEm.
});
```

This causes the following in the Postgres logs:
```
2020-10-23 16:49:18.155 AEDT [20246] LOG:  statement: select version();
2020-10-23 16:49:18.162 AEDT [20246] LOG:  statement: select 1
2020-10-23 16:49:18.329 AEDT [20246] LOG:  statement: BEGIN;
2020-10-23 16:49:18.387 AEDT [20247] LOG:  statement: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
2020-10-23 16:49:18.387 AEDT [20247] WARNING:  SET TRANSACTION can only be used in transaction blocks
2020-10-23 16:49:18.769 AEDT [20246] LOG:  execute <unnamed>: insert into "organisation" // Whatever else
```
Note the 20246 vs 20247. Different connections, and the statement happens outside of transactionalEm's connection, which is not what we want.

I've verified that when I add this line to the repro, the test times out and behaves as our application does:
https://github.com/mikro-orm/mikro-orm/pull/948/files#diff-fa75b01f3d1790f1791613b79325811ffe41d6256f2d7e820865d1e941b0df99R30

So, the questions are:
  - Why does `getConnection()` return a different connection? and
  - How should we be setting our transaction isolation level inside the transaction? Is there a better way to do this?

**Comment by B4nan** [comment]
Makes sense, you are not passing the ctx context. Use `em.execute()` instead (or you can pass the ctx to the `con.execute()` in the last parameter).

```ts
await orm.em.transactional(async transactionalEm => {
  await transactionalEm.execute(`SET TRANSACTION ISOLATION LEVEL SERIALIZABLE`);
  // Whatever else using transactionalEm.
});
```

**Comment by thekevinbrown** [comment]
Fair enough, that fixes it indeed, thanks for your help again!
