### ISSUE TITLE
Question: How do i use Custom Repository in like my resolvers or something?

### ISSUE THREAD

**Issue by jagabs** [mikro-orm/mikro-orm#950]
ex.

```
@Repository(Author)
export class CustomAuthorRepository extends EntityRepository<Author> {

  // your custom methods...
  public findAndUpdate(...) {
    // ...
  }
}
```
and i want to call findAndUpdate here 👍 

`  @Query(() => Author, { nullable: true })
  public async getAuthor(
    @Arg('id') id: string,
    @Ctx() ctx: MyContext,
    @Info() info: GraphQLResolveInfo,
  ): Promise<Author | null> {
    const relationPaths = fieldsToRelations(info);
    return ctx.em.getRepository(Author).findOne({ id }, relationPaths);
  }
`

also can i used DI without nestjs? 
thanks best regards

**Comment by B4nan** [comment]
Its the same, custom repository will be returned from `em.getRepository()`. You are probably referring the the method not defined on the TS level - you either need to type case, or use `EntityRepositoryType`:

https://mikro-orm.io/docs/repositories/#inferring-custom-repository-type

**Comment by jagabs** [comment]
ohh okie verified and its working thanks :)
