### ISSUE TITLE
Extreme speed differences

### ISSUE THREAD

**Issue by kaihaase** [mikro-orm/mikro-orm#951]
I have tested two different implementations in terms of speed, what causes the big difference?

Implementation A:
```Javascript
for (const element of elements) {
  this.deletedDb.persist(DeletedElement.map({ ...element, originalId: element.id }));
}
await this.deletedDb.flush();
```
Duration: approx. 5800 milliseconds for `elements.length = 6`

Implementation B:
```Javascript
const deletedElements = []
for (const element of elements) {
  deletedElements.push(DeletedElement.map({ ...element, originalId: element.id }));
}
await this.deletedDb.persistAndFlush(deletedElements);
```
Duration: approx. 100 milliseconds for `elements.length = 6`

The elements are loaded via EntityRepository API:
```Javascript
const elements = await this.db.find({ platformId, structureId });
```

**Comment by B4nan** [comment]
Well, i dont have a magic orb :) provide executable repro (with some seeding script included) if you want help with this kind of issue. 

Both snippets should be equal and result is the same query to be used, you should see that in the debug logs. 

What does the map method do?

**Comment by kaihaase** [comment]
@B4nan Wasn't sure if I was missing something obvious. Magic would be something useful, but I'm sure we can solve this without magic.

I will prepare an appropriate repository. Might take a while though, as I'm still very busy at the moment.

Thanks a lot for the fast reaction.

**Comment by kaihaase** [comment]
The map function takes all properties from the passed object, creates an "empty" object (in this case an object of type DeletedElement) and transfers all properties of the passed object to the DeletedElement, which the DeletedElement actually contains (so it is a bit more intelligent than a simple Object.assign, which would simply transfer all properties of the passed object). In addition, special treatments may be performed for certain properties.

**Comment by B4nan** [comment]
What about the query log, does it produce the same query? Have you measured what part is the slow one? Is it the flush call? 

`persistAndFlush` is just a shortcut for `persist().flush()`, so split that and try to compare only the `flush` calls.

**Comment by kaihaase** [comment]
The problem is not due to MikroORM. This is what happens when you only suspect and do not control it properly. It is due to my own `map` method. This method uses `deepClone` from lodash, and there the strange phenomenon occurs, which I still don't understand. In implementation A the time for cloning the element increases many times over the step before. In implementation B this time remains almost constant for every element.

**Comment by B4nan** [comment]
You should not clone entities, they contain lots of internal references to things like EM or the entity state.

**Comment by kaihaase** [comment]
What is the best way to create a copy (with new ID) in the same collection / table?
What is the best way to store a copy (with new ID and extended properties) in another collection / table?

**Comment by B4nan** [comment]
I guess you could use `wrap(e).toObject()` first to make it DTO, and then `em.create()` to build the new entity. Using clone might have side effects due to the internal entity state (which is omitted when you build the DTO).

**Comment by kaihaase** [comment]
With `wrap(e).toObject()` it is much faster. Thanks a lot!
