### ISSUE TITLE
No overload matches this call.

### ISSUE THREAD

**Issue by angelvega93** [mikro-orm/mikro-orm#954]
**Describe the bug**
I don't know if is a bug or i am doing something wrong but i get this error.
https://prnt.sc/v58dhw

**Stack trace**
```
src/index.ts:15:43 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(entityName: EntityName<Test>, where: FilterQuery<Test>, options?: FindOneOptions<Test, any> | undefined): Promise<...>', gave the following error.
    Argument of type '{ id: number; }' is not assignable to parameter of type 'FilterQuery<Test>'.
      Type '{ id: number; }' is not assignable to type 'number'.
  Overload 2 of 2, '(entityName: EntityName<Test>, where: FilterQuery<Test>, populate?: any, orderBy?: QueryOrderMap | undefined): Promise<Test | null>', gave the following error.
    Argument of type '{ id: number; }' is not assignable to parameter of type 'FilterQuery<Test>'.
      Type '{ id: number; }' is not assignable to type 'number'.

15   const test = await orm.em.findOne(Test, { id: 1 });
```

**To Reproduce**
I just have 2 files:
src/index.ts
```
import { MikroORM } from "@mikro-orm/core";
import { Test } from "./entities/Test";

async function main() {
  const orm = await MikroORM.init({
    entities: ["./dist/entities/**/*.js"],
    entitiesTs: ["./src/entities/**/*.ts"],
    dbName: "test",
    user: "postgres",
    password: "123123",
    debug: true,
    type: "postgresql",
  });

  const test = await orm.em.findOne(Test, { id: 1 });
  console.log(test);
}

main();
```

src/entities/Test.ts
```
import { Entity, PrimaryKey, Property } from "@mikro-orm/core";

@Entity()
export class Test {
  @PrimaryKey()
  @Property()
  id!: number;

  @Property()
  name!: string;
}
```

**Versions**

| Dependency | Version |
| - | - |
| node | 12.16.3 |
| typescript | 4.0.3 |
| mikro-orm | 4.2.2 |
| your-driver | 4.2.2 |

**Comment by B4nan** [comment]
Drop the `@Property` decorator, you can't mix it with `@PrimaryKey`. 

And nope, this is not enough to replicate it, it works fine for me. Maybe you have something wrong in your tsconfig.json? 

![image](https://user-images.githubusercontent.com/615580/96996400-15020700-1530-11eb-8f10-1fb3dfbd02bf.png)

**Comment by angelvega93** [comment]
Here is a repo with an example:

https://github.com/angelvega93/MikroORM_Bug

**Comment by B4nan** [comment]
You need to install `@types/node`, then it works fine. 

Also you are missing `reflect-metadata` dependency and its require/registration in your top level script.

**Comment by angelvega93** [comment]
Oh thanks that was all the problem.
