### ISSUE TITLE
Schema generator does not add new indexes when updating

### ISSUE THREAD

**Issue by bahdcoder** [mikro-orm/mikro-orm#957]
**Describe the bug**

When running `schemaGenerator.updateSchema()`, new unique indexes added to the column do not get created.
 
**To Reproduce**
1. Create an entity such as `Article` with a `slug` string column.
2. Create the articles table and slug field in the database.
3. Run schema generator update schema method. Notice the new index is not created.

**Expected behavior**

**Additional context**
1. I have only tested this on mysql.
2. I believe this is the origin of the problem after spending a moment debugging:

```js
// @mikro-orm/knex/SchemaHelper

    hasSameIndex(prop, column) {
        if ([core_1.ReferenceType.SCALAR, core_1.ReferenceType.EMBEDDED].includes(prop.reference)) {
            // TODO: Check indexes on scalar fields instead of returning true.
            return true;
        }
        return prop.referencedColumnNames.some(referencedColumnName => {
            return !!column.fk && referencedColumnName === column.fk.referencedColumnName && prop.referencedTableName === column.fk.referencedTableName;
        });
    }
```
**Versions**

| Dependency | Version |
| - | - |
| node | 12.17.0 |
| typescript | 3.9.5 |
| mikro-orm | 4.2.0 |
| your-driver | mysql |

**Comment by bahdcoder** [comment]
Hey @B4nan please could you share an update on this bug ? Would really appreciate it, thanks.

**Comment by B4nan** [comment]
Index diffing happens in `findIndexDifference` method (`hasSameIndex` is used only for diffing FK indexes), but that was adding missing indexes only for those defined on entity level (those are stored in `meta.indexes` and `meta.uniques`), not on property level (stored on `meta.properties[prop].index` and `unique` respectively).
