### ISSUE TITLE
I cant use Smart Query Conditions

### ISSUE THREAD

**Issue by jagabs** [mikro-orm/mikro-orm#958]
"@mikro-orm/cli": "^4.2.3",
    "@mikro-orm/core": "^4.2.3",
    "@mikro-orm/migrations": "^4.2.3",
    "@mikro-orm/postgresql": "^4.2.3",

![image](https://user-images.githubusercontent.com/17292042/97099923-48c46480-16c9-11eb-9e4a-6f3e517aad98.png)

![image](https://user-images.githubusercontent.com/17292042/97099927-51b53600-16c9-11eb-8a19-0c91dfcf7044.png)

i also tried the example 

![image](https://user-images.githubusercontent.com/17292042/97099994-0d766580-16ca-11eb-96d9-0598925aec15.png)

errors:

![image](https://user-images.githubusercontent.com/17292042/97099952-89bc7900-16c9-11eb-854d-03751ffab46b.png)

**Comment by B4nan** [comment]
You need to type cast `as any` or [use `expr`](https://github.com/mikro-orm/mikro-orm/issues/802#issuecomment-685869127).

But it's better to forget about this feature, I consider it deprecated (this "issue" became a thing with first release of v3), as there is better way via operators that is also type safe. Will probably remove it in v5.

https://mikro-orm.io/docs/upgrading-v2-to-v3/#strict-filterquery-and-smart-query-conditions

Btw using only screenshots instead of code blocks is bad, please don't do this.

**Comment by jagabs** [comment]
okay noted thanks. I wanted to use createQueryBuilder but typescript seem not to noticed it as well. Should i just type cast it to any?

**Comment by B4nan** [comment]
https://mikro-orm.io/docs/upgrading-v3-to-v4#sqlentitymanager-and-mongoentitymanager

**Comment by jagabs** [comment]
Hi @B4nan,

i cant use createQueryBuilder its always undefined in my end. 

I tried importing it here: 

```
import { EntityManager } from "@mikro-orm/postgresql";
public em: EntityManager;
public orm: MikroORM<IDatabaseDriver<Connection>>;
```

using this example: **https://github.com/driescroons/mikro-orm-graphql-example/blob/76eeaeddbf80a37a223c98b4784595170a457db3/src/application.ts**

**Comment by B4nan** [comment]
Well that is just a pseudo code to show that this is typings only issue. Same applies to repositories, you need to use `EntityRepository` from the driver package, not from `core`.

Also this part: `public orm: MikroORM<IDatabaseDriver<Connection>>;` is wrong, as `orm.em` will not be typed correctly. You need to use the driver in type parameter, e.g. `MikroORM<PostgreSqlDriver>`.

https://github.com/mikro-orm/nestjs-realworld-example-app/blob/89ec53ca678f9ef0c1538ff9fc14448a016daa72/src/article/article.service.ts#L27

**Comment by jagabs** [comment]
changing to 

`public orm: MikroORM<PostgreSqlDriver>;`

gives an error

`Type 'PostgreSqlDriver' does not satisfy the constraint 'IDatabaseDriver<Connection>'.
  Types of property 'count' are incompatible.
    Type '(entityName: string, where: any, ctx?: Transaction<any, any>) => Promise<number>' is not assignable to type '<T extends AnyEntity<T>>(entityName: string, where: FilterQuery<T>, options?: CountOptions<T>, ctx?: any) => Promise<number>'.
      Types of parameters 'ctx' and 'options' are incompatible.
        Type 'CountOptions<T>' is missing the following properties from type 'Transaction<any, any>': executionPromise, isCompleted, query, savepoint, and 126 more.ts(2344)


Type 'MikroORM<IDatabaseDriver<Connection>>' is not assignable to type 'MikroORM<PostgreSqlDriver>'.
  Type 'IDatabaseDriver<Connection>' is missing the following properties from type 'PostgreSqlDriver': connection, replicas, platform, mapJoinedProps, and 24 more.ts(2322)
`

**Comment by B4nan** [comment]
If you want help, provide something I can try, as I have no idea what you are doing (and where and how).

The error is caused by you trying to put `MikroORM<IDatabaseDriver<Connection>>` into `MikroORM<PostgreSqlDriver>`, so probably you forgot to use the type also in `MikroORM.init<PostgreSqlDriver>()`.

**Comment by jagabs** [comment]
Im trying out mikro orm, doing some queries etc. So for my base code, i cloned this [https://github.com/driescroons/mikro-orm-graphql-example]().

what i want to do is try out using query builder here with this graphql example.

**Comment by B4nan** [comment]
I asked for your code that does not work, you give me link to example repository that works just fine 🤷 

Again, if you want help, provide code that does not work. Pasting the same error as you already did won't help anybody (and btw I already said why is that error happening).

This needs to be adjusted: 
https://github.com/driescroons/mikro-orm-graphql-example/blob/7791e1c9bc985f66d03fbddafc364c667fda9ae0/src/utils/interfaces/context.interface.ts#L7
https://github.com/driescroons/mikro-orm-graphql-example/blob/master/src/application.ts#L25
https://github.com/driescroons/mikro-orm-graphql-example/blob/master/src/application.ts#L31

**Comment by jagabs** [comment]
uhm i tried changing those. but still error this for example 

```
import { Connection, EntityManager, IDatabaseDriver } from "@mikro-orm/core";
import { UserDTO } from "dto/user.dto";
import { Request, Response } from "express";
import { EntityManager as EM, PostgreSqlDriver } from "@mikro-orm/postgresql";

export interface MyContext {
  req: Request;
  res: Response;
  em: EntityManager<PostgreSqlDriver>;
  userDTO: UserDTO;
}

```

![image](https://user-images.githubusercontent.com/17292042/97102584-a06eca00-16e1-11eb-9a4a-7c7b5abd9f91.png)

**Comment by B4nan** [comment]
```ts
import { Connection, IDatabaseDriver } from "@mikro-orm/core"; // <-- no import of EM from core
import { UserDTO } from "dto/user.dto";
import { Request, Response } from "express";
import { EntityManager, PostgreSqlDriver } from "@mikro-orm/postgresql"; // <-- only from the driver package

export interface MyContext {
  req: Request;
  res: Response;
  em: EntityManager<PostgreSqlDriver>;
  userDTO: UserDTO;
}
```

**Comment by jagabs** [comment]
yeah i figured out that one my bad haha

but for this one 

![Uploading image.png…]()

**Comment by B4nan** [comment]
I'd say that is a version mismatch, make sure your ORM packages are all aligned to 4.2 (the patch version might vary, but in general use the latest of everything). 

But again, without seeing your code (all of it, not just a screenshot of few lines), I simply don't know.

**Comment by jagabs** [comment]
thank you @B4nan it seems deleting node_modules and installing the packages again fixed the issue
