### ISSUE TITLE
Unable to connect database using pg driver (it gives knex timeout error)

### ISSUE THREAD

**Issue by hanzlahabib** [mikro-orm/mikro-orm#960]
**Describe the bug**
Couldn't connect to psql database on local it gives knex error

**Stack trace**
![image](https://user-images.githubusercontent.com/41893448/97114027-e3479680-170f-11eb-91b6-3cf7ef963521.png)

```
MikroORM failed to connect to database epasdasda on postgresql://postgres:*****@127.0.0.1:51970
sdfsdgsd
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (E:\Development\reddit\node_modules\knex\lib\client.js:348:26)
...
```

**To Reproduce**
1. install
```
  "dependencies": {
    "@mikro-orm/cli": "^4.2.3",
    "@mikro-orm/core": "^4.2.3",
    "@mikro-orm/migrations": "^4.2.3",
    "@mikro-orm/postgresql": "^4.2.3",
    "pg": "^8.0.3"
  }
```
2. my current nodejs version
v12.18.4
3. init mikroORM
```
    const orm = await MikroORM.init({
        entities: [Post],
        dbName: 'epa',
        type: 'postgresql',
        debug:  !__prod__,
        user: 'postgres',
        host: '127.0.0.1',
        port: 51970,
        password: '123456789'
    });

   const post =  orm.em.create(Post, {title: 'test'})
    await orm.em.persistAndFlush(post)
    console.log('psql000000000')
    await orm.em.nativeInsert(Post, post)
```
**Versions**

| Dependency | Version |
| - | - |
| node | v12.18.4 |
| typescript | ^4.0.3 |
 "@mikro-orm/cli": "^4.2.3",
    "@mikro-orm/core": "^4.2.3",
    "@mikro-orm/migrations": "^4.2.3",
    "@mikro-orm/postgresql": "^4.2.3",
| pg | ^8.0.3 |

**Comment by B4nan** [comment]
As you can see on the previous line, the connection is not established. You probably have wrong credentials or the db is not running. 

Are you able to connect to the database via pgadmin/tableplus/adminer or some other db management tool?

My bet is that you have wrong dbname, as here you say its `epa` but in the log you can see its `epasdasda`.

**Comment by hanzlahabib** [comment]
i have tested twice, db is running and accessible via pgadmin 
i have verified db name is also same,

log and code difference is my bad,

**Comment by B4nan** [comment]
still, this is not a bug, this is your configuration being wrong or wrongly provided to the orm. 

tried to reproduce the same error as yours, and it was caused by bad host. when the db name or port was wrong, the error is different, but when the host was wrong, knex timed out.

not a windows user currently, but i remember some issues with `127.0.0.1` vs `localhost`, so maybe google that, can't help more.

**Comment by hanzlahabib** [comment]
i added debug flag true but still don't get enough information what thing is being wrong on from my end, any way to debug this??
