### ISSUE TITLE
connection.execute does not handle `??` anymore

### ISSUE THREAD

**Issue by patricklx** [mikro-orm/mikro-orm#983]
**Describe the bug**
A execute statement that uses `??` does not work correctly. It replaces the first ? with the string values instead of replacing `??` with the symbol.

**Versions**

| Dependency | Version |
| node | v12.13.0 |
| typescript | 4.0.3 |
| mikro-orm | 4.2.1 |
| your-driver | postgres |

**Comment by B4nan** [comment]
This was never a goal, how do you use it? Provide something I can try (and what you expect).

**Comment by patricklx** [comment]
e.g. ```await orm.em.getConnection('write').execute(`CREATE USER ?? WITH PASSWORD \'${password}\';` ```
or `GRANT USAGE ON SCHEMA ?? TO ??; `.

**Comment by B4nan** [comment]
I asked also for the expected output. Why dont you use single question mark? How is that different?

As i said, this was never meant to be supported.

**Comment by patricklx** [comment]
the output to the DB should be `CREATE USER USER1 WITH PASSWORD 'X'`, but with single question mark it prints `CREATE 'USER' USER1 WITH PASSWORD 'X'`, which does not work. It must be double quotes or no quotes for this to work...
https://www.postgresql.org/docs/8.0/sql-createuser.html

**Comment by B4nan** [comment]
Before the `v4.3` release, you can try the dev build, latest one is `4.2.4-dev.81`.
