### ISSUE TITLE
Initialized property set as jsonb in initial migration

### ISSUE THREAD

**Issue by standup75** [mikro-orm/mikro-orm#990]
**Describe the bug**
I had a property defined this way
```
  @Property()
  active = true;
```
And the initial migration did not show this column as bool but as json

**To Reproduce**
1. Create an entity with
```
  @Property()
  active != true;
```

2. Make sure you have an empty db and no migration
3. Run `npx mikro-orm migration:create --initial`
4. Inspect the migration file and look at active declaration, it will say `"active" jsonb not null`

**Expected behavior**
Expected is `"active" bool not null`

**Additional context**
Quick workaound:
```
  @Property()
  active: boolean = true;
```

**Versions**

| Dependency | Version |
| - | - |
| node | 13.11.0 |
| typescript | 3.9.3 |
| mikro-orm | 4.2.0 |
| @mikro-orm/postgresql | 4.2.3 |

**Comment by B4nan** [comment]
You need to use ts-morph metadata provide if you want this behaviour. It is not possible with reflect-metadata.

https://mikro-orm.io/docs/metadata-providers/#tsmorphmetadataprovider
https://mikro-orm.io/docs/metadata-providers/#explicit-types
